-- ============================================================
-- Phase 4: jp_quiz_questions + jp_study_sessions
-- ============================================================

-- ── jp_quiz_questions ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.jp_quiz_questions (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  jlpt_level       text NOT NULL,
  category         text NOT NULL,
  question         text NOT NULL,
  question_reading text,
  question_vi      text,
  question_en      text,
  options          jsonb NOT NULL,
  correct_answer   text NOT NULL,
  explanation_vi   text,
  explanation_en   text,
  difficulty       text DEFAULT 'normal',
  is_published     boolean DEFAULT true,
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_jp_quiz_questions_level     ON public.jp_quiz_questions (jlpt_level);
CREATE INDEX IF NOT EXISTS idx_jp_quiz_questions_category  ON public.jp_quiz_questions (category);
CREATE INDEX IF NOT EXISTS idx_jp_quiz_questions_published ON public.jp_quiz_questions (is_published);

ALTER TABLE public.jp_quiz_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "quiz_questions_public_read" ON public.jp_quiz_questions;
CREATE POLICY "quiz_questions_public_read"
  ON public.jp_quiz_questions FOR SELECT
  USING (is_published = true);

-- ── jp_study_sessions ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.jp_study_sessions (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  session_type text NOT NULL,
  level        text,
  score        int,
  total        int,
  duration_sec int,
  detail       jsonb,
  created_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_jp_study_sessions_user ON public.jp_study_sessions (user_id);

ALTER TABLE public.jp_study_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sessions_own_select" ON public.jp_study_sessions;
DROP POLICY IF EXISTS "sessions_own_insert" ON public.jp_study_sessions;
DROP POLICY IF EXISTS "sessions_own_update" ON public.jp_study_sessions;
DROP POLICY IF EXISTS "sessions_own_delete" ON public.jp_study_sessions;

CREATE POLICY "sessions_own_select" ON public.jp_study_sessions FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "sessions_own_insert" ON public.jp_study_sessions FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "sessions_own_update" ON public.jp_study_sessions FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "sessions_own_delete" ON public.jp_study_sessions FOR DELETE USING (user_id = auth.uid());

-- ── Seed: 10 questions per level (N5 → N1) ────────────────
INSERT INTO public.jp_quiz_questions
  (jlpt_level, category, question, question_reading, question_vi, question_en,
   options, correct_answer, explanation_vi, explanation_en, difficulty)
VALUES

-- ═══ N5 ═══════════════════════════════════════════════════

('N5', 'vocabulary',
 '「食べる」の意味は？', 'たべる',
 '"食べる" (taberu) có nghĩa là gì?',
 'What does 食べる (taberu) mean?',
 '[{"key":"A","text":"uống"},{"key":"B","text":"ăn"},{"key":"C","text":"ngủ"},{"key":"D","text":"viết"}]',
 'B',
 '食べる (taberu) = ăn. Ví dụ: ご飯を食べる (gohan wo taberu) = ăn cơm.',
 '食べる (taberu) means "to eat". Example: ご飯を食べる = to eat rice.',
 'easy'),

('N5', 'vocabulary',
 '「大きい」の意味は？', 'おおきい',
 '"大きい" (ookii) có nghĩa là gì?',
 'What does 大きい (ookii) mean?',
 '[{"key":"A","text":"nhỏ"},{"key":"B","text":"nhanh"},{"key":"C","text":"to/lớn"},{"key":"D","text":"đẹp"}]',
 'C',
 '大きい (ookii) = to, lớn. Ví dụ: 大きい犬 (ookii inu) = con chó to.',
 '大きい (ookii) means "big" or "large". Example: 大きい犬 = a big dog.',
 'easy'),

('N5', 'kanji',
 '「日」の読み方はどれですか？', NULL,
 'Cách đọc của chữ "日" là gì?',
 'Which is the correct reading of 日?',
 '[{"key":"A","text":"げつ"},{"key":"B","text":"ねん"},{"key":"C","text":"にち"},{"key":"D","text":"しゅう"}]',
 'C',
 '日 đọc là にち (nichi) hoặc ひ (hi). Ví dụ: 毎日 (まいにち) = mỗi ngày.',
 '日 is read as にち (nichi) or ひ (hi). Example: 毎日 (まいにち) = every day.',
 'easy'),

('N5', 'kanji',
 '「山」の読み方はどれですか？', NULL,
 'Cách đọc của chữ "山" là gì?',
 'Which is the correct reading of 山?',
 '[{"key":"A","text":"かわ"},{"key":"B","text":"うみ"},{"key":"C","text":"もり"},{"key":"D","text":"やま"}]',
 'D',
 '山 đọc là やま (yama). Ví dụ: 富士山 (ふじさん) = núi Phú Sĩ.',
 '山 is read as やま (yama). Example: 富士山 (ふじさん) = Mt. Fuji.',
 'easy'),

('N5', 'grammar',
 '「私（　）学生です。」に入る言葉は？', NULL,
 'Điền trợ từ đúng vào "私（　）学生です。"',
 'Choose the correct particle for 私（　）学生です。',
 '[{"key":"A","text":"が"},{"key":"B","text":"を"},{"key":"C","text":"は"},{"key":"D","text":"に"}]',
 'C',
 'は (wa) là trợ từ chủ đề. 私は学生です = Tôi là học sinh.',
 'は (wa) is the topic particle. 私は学生です = I am a student.',
 'easy'),

('N5', 'grammar',
 '「今、ご飯を食べ（　）います。」に入る言葉は？', NULL,
 'Điền đúng vào "今、ご飯を食べ（　）います。" (đang ăn cơm)',
 'Fill in: 今、ご飯を食べ（　）います。(currently eating)',
 '[{"key":"A","text":"て"},{"key":"B","text":"に"},{"key":"C","text":"で"},{"key":"D","text":"と"}]',
 'A',
 '〜ています diễn tả hành động đang diễn ra. 食べています = đang ăn.',
 '〜ています expresses an ongoing action. 食べています = am eating.',
 'easy'),

('N5', 'vocabulary',
 '「見る」の意味は？', 'みる',
 '"見る" (miru) có nghĩa là gì?',
 'What does 見る (miru) mean?',
 '[{"key":"A","text":"nghe"},{"key":"B","text":"nói"},{"key":"C","text":"nhìn/xem"},{"key":"D","text":"đọc"}]',
 'C',
 '見る (miru) = nhìn, xem. Ví dụ: テレビを見る = xem tivi.',
 '見る (miru) means "to see/watch". Example: テレビを見る = to watch TV.',
 'easy'),

('N5', 'vocabulary',
 '「行く」の意味は？', 'いく',
 '"行く" (iku) có nghĩa là gì?',
 'What does 行く (iku) mean?',
 '[{"key":"A","text":"đến/tới"},{"key":"B","text":"quay về"},{"key":"C","text":"đi"},{"key":"D","text":"dừng lại"}]',
 'C',
 '行く (iku) = đi. Ví dụ: 学校に行く = đi học.',
 '行く (iku) means "to go". Example: 学校に行く = to go to school.',
 'easy'),

('N5', 'vocabulary',
 '「水」の意味は？', 'みず',
 '"水" (mizu) có nghĩa là gì?',
 'What does 水 (mizu) mean?',
 '[{"key":"A","text":"cơm"},{"key":"B","text":"trà"},{"key":"C","text":"sữa"},{"key":"D","text":"nước"}]',
 'D',
 '水 (mizu) = nước. Ví dụ: 水を飲む = uống nước.',
 '水 (mizu) means "water". Example: 水を飲む = to drink water.',
 'easy'),

('N5', 'vocabulary',
 '「好き」の意味は？', 'すき',
 '"好き" (suki) có nghĩa là gì?',
 'What does 好き (suki) mean?',
 '[{"key":"A","text":"ghét"},{"key":"B","text":"thích"},{"key":"C","text":"muốn"},{"key":"D","text":"sợ"}]',
 'B',
 '好き (suki) = thích, yêu thích. Ví dụ: 音楽が好き = thích âm nhạc.',
 '好き (suki) means "to like". Example: 音楽が好き = I like music.',
 'easy'),

-- ═══ N4 ═══════════════════════════════════════════════════

('N4', 'vocabulary',
 '「疲れる」の意味は？', 'つかれる',
 '"疲れる" (tsukareru) có nghĩa là gì?',
 'What does 疲れる (tsukareru) mean?',
 '[{"key":"A","text":"vui vẻ"},{"key":"B","text":"mệt mỏi"},{"key":"C","text":"đói bụng"},{"key":"D","text":"buồn ngủ"}]',
 'B',
 '疲れる (tsukareru) = mệt mỏi. Ví dụ: 仕事で疲れた = mệt vì công việc.',
 '疲れる (tsukareru) means "to get tired". Example: 仕事で疲れた = I got tired from work.',
 'normal'),

('N4', 'grammar',
 '「ここで写真を撮っ（　）ですか？」= được phép chụp ảnh không?', NULL,
 'Điền vào "ここで写真を撮っ（　）ですか？" (được phép chụp ảnh không?)',
 'Fill in: ここで写真を撮っ（　）ですか？(Is it OK to take photos here?)',
 '[{"key":"A","text":"てもいい"},{"key":"B","text":"てはいけない"},{"key":"C","text":"なければならない"},{"key":"D","text":"てしまった"}]',
 'A',
 '〜てもいいですか = được phép không? Đây là cách xin phép lịch sự.',
 '〜てもいいですか is used to ask for permission. It means "Is it OK to...?"',
 'normal'),

('N4', 'kanji',
 '「電話」の読み方は？', NULL,
 'Cách đọc của "電話" là gì?',
 'What is the reading of 電話?',
 '[{"key":"A","text":"でんき"},{"key":"B","text":"でんわ"},{"key":"C","text":"でんとう"},{"key":"D","text":"でんしゃ"}]',
 'B',
 '電話 (でんわ / denwa) = điện thoại. でん = điện, わ = thoại/lời nói.',
 '電話 is read でんわ (denwa), meaning "telephone".',
 'normal'),

('N4', 'vocabulary',
 '「急ぐ」の意味は？', 'いそぐ',
 '"急ぐ" (isogu) có nghĩa là gì?',
 'What does 急ぐ (isogu) mean?',
 '[{"key":"A","text":"dừng lại"},{"key":"B","text":"đi bộ"},{"key":"C","text":"vội vàng"},{"key":"D","text":"chờ đợi"}]',
 'C',
 '急ぐ (isogu) = vội vàng, đi nhanh. Ví dụ: 急いでください = Hãy nhanh lên.',
 '急ぐ (isogu) means "to hurry". Example: 急いでください = Please hurry.',
 'normal'),

('N4', 'grammar',
 '「宿題をし（　）なりません。」= phải làm bài tập', NULL,
 'Điền vào "宿題をし（　）なりません。" (phải làm bài tập)',
 'Fill in: 宿題をし（　）なりません。(must do homework)',
 '[{"key":"A","text":"なくては"},{"key":"B","text":"なければ"},{"key":"C","text":"なくて"},{"key":"D","text":"ないで"}]',
 'B',
 '〜なければなりません = phải làm. Đây là cách diễn tả nghĩa vụ bắt buộc.',
 '〜なければなりません means "must do". It expresses obligation.',
 'normal'),

('N4', 'kanji',
 '「学校」の読み方は？', NULL,
 'Cách đọc của "学校" là gì?',
 'What is the reading of 学校?',
 '[{"key":"A","text":"がっこう"},{"key":"B","text":"こうこう"},{"key":"C","text":"がっき"},{"key":"D","text":"がくせい"}]',
 'A',
 '学校 (がっこう / gakkoo) = trường học.',
 '学校 is read がっこう (gakkoo), meaning "school".',
 'normal'),

('N4', 'vocabulary',
 '「覚える」の意味は？', 'おぼえる',
 '"覚える" (oboeru) có nghĩa là gì?',
 'What does 覚える (oboeru) mean?',
 '[{"key":"A","text":"quên"},{"key":"B","text":"ghi nhớ"},{"key":"C","text":"tìm hiểu"},{"key":"D","text":"lặp lại"}]',
 'B',
 '覚える (oboeru) = ghi nhớ, học thuộc. Ví dụ: 単語を覚える = học thuộc từ vựng.',
 '覚える (oboeru) means "to memorize/remember". Example: 単語を覚える = to memorize vocabulary.',
 'normal'),

('N4', 'grammar',
 '「日本に行っ（　）があります。」= đã từng đến Nhật', NULL,
 'Điền vào "日本に行っ（　）があります。" (đã từng đến Nhật)',
 'Fill in: 日本に行っ（　）があります。(have been to Japan)',
 '[{"key":"A","text":"て"},{"key":"B","text":"たこと"},{"key":"C","text":"ている"},{"key":"D","text":"てから"}]',
 'B',
 '〜たことがあります = đã từng trải nghiệm. 日本に行ったことがあります = đã từng đến Nhật.',
 '〜たことがあります expresses past experience. = I have been to Japan.',
 'normal'),

('N4', 'vocabulary',
 '「準備」の意味は？', 'じゅんび',
 '"準備" (junbi) có nghĩa là gì?',
 'What does 準備 (junbi) mean?',
 '[{"key":"A","text":"hoàn thành"},{"key":"B","text":"bắt đầu"},{"key":"C","text":"chuẩn bị"},{"key":"D","text":"kết thúc"}]',
 'C',
 '準備 (junbi) = chuẩn bị. Ví dụ: 準備をする = chuẩn bị.',
 '準備 (junbi) means "preparation". Example: 準備をする = to prepare.',
 'normal'),

('N4', 'vocabulary',
 '「便利」の意味は？', 'べんり',
 '"便利" (benri) có nghĩa là gì?',
 'What does 便利 (benri) mean?',
 '[{"key":"A","text":"bất tiện"},{"key":"B","text":"tiện lợi"},{"key":"C","text":"chậm chạp"},{"key":"D","text":"phức tạp"}]',
 'B',
 '便利 (benri) = tiện lợi. Ví dụ: このアプリは便利 = ứng dụng này tiện lợi.',
 '便利 (benri) means "convenient". Example: このアプリは便利 = This app is convenient.',
 'normal'),

-- ═══ N3 ═══════════════════════════════════════════════════

('N3', 'vocabulary',
 '「主に」の意味は？', 'おもに',
 '"主に" (omoni) có nghĩa là gì?',
 'What does 主に (omoni) mean?',
 '[{"key":"A","text":"thỉnh thoảng"},{"key":"B","text":"hiếm khi"},{"key":"C","text":"chủ yếu"},{"key":"D","text":"thường xuyên"}]',
 'C',
 '主に (omoni) = chủ yếu, chủ yếu là. Ví dụ: 主に野菜を食べる = chủ yếu ăn rau.',
 '主に (omoni) means "mainly" or "primarily". Example: 主に野菜を食べる = I mainly eat vegetables.',
 'normal'),

('N3', 'grammar',
 '「地域（　）食文化が異なります。」= khác nhau tùy vùng', NULL,
 'Điền vào "地域（　）食文化が異なります。" (khác nhau tùy vùng)',
 'Fill in: 地域（　）食文化が異なります。(food culture varies by region)',
 '[{"key":"A","text":"によって"},{"key":"B","text":"について"},{"key":"C","text":"に対して"},{"key":"D","text":"において"}]',
 'A',
 '〜によって = tùy theo, do. 地域によって = tùy theo vùng/khu vực.',
 '〜によって means "depending on" or "by". 地域によって = depending on the region.',
 'normal'),

('N3', 'kanji',
 '「経験」の読み方は？', NULL,
 'Cách đọc của "経験" là gì?',
 'What is the reading of 経験?',
 '[{"key":"A","text":"けいかん"},{"key":"B","text":"けいけん"},{"key":"C","text":"けっか"},{"key":"D","text":"けんか"}]',
 'B',
 '経験 (けいけん / keiken) = kinh nghiệm.',
 '経験 is read けいけん (keiken), meaning "experience".',
 'normal'),

('N3', 'vocabulary',
 '「断る」の意味は？', 'ことわる',
 '"断る" (kotowaru) có nghĩa là gì?',
 'What does 断る (kotowaru) mean?',
 '[{"key":"A","text":"chấp nhận"},{"key":"B","text":"từ chối"},{"key":"C","text":"thương lượng"},{"key":"D","text":"trì hoãn"}]',
 'B',
 '断る (kotowaru) = từ chối. Ví dụ: 招待を断る = từ chối lời mời.',
 '断る (kotowaru) means "to refuse/decline". Example: 招待を断る = to decline an invitation.',
 'normal'),

('N3', 'grammar',
 '「健康（　）、規則正しく食べています。」= ăn điều độ vì sức khỏe', NULL,
 'Điền vào "健康（　）、規則正しく食べています。" (vì sức khỏe)',
 'Fill in: 健康（　）、規則正しく食べています。(eating regularly for health)',
 '[{"key":"A","text":"によって"},{"key":"B","text":"のために"},{"key":"C","text":"に関して"},{"key":"D","text":"にとって"}]',
 'B',
 '〜のために = vì..., để... Mục đích hoặc lợi ích. 健康のために = vì sức khỏe.',
 '〜のために expresses purpose or benefit. 健康のために = for the sake of health.',
 'normal'),

('N3', 'vocabulary',
 '「努力」の意味は？', 'どりょく',
 '"努力" (doryoku) có nghĩa là gì?',
 'What does 努力 (doryoku) mean?',
 '[{"key":"A","text":"kết quả"},{"key":"B","text":"mục tiêu"},{"key":"C","text":"cố gắng"},{"key":"D","text":"thất bại"}]',
 'C',
 '努力 (doryoku) = sự cố gắng, nỗ lực. Ví dụ: 努力が必要 = cần phải cố gắng.',
 '努力 (doryoku) means "effort". Example: 努力が必要 = Effort is necessary.',
 'normal'),

('N3', 'vocabulary',
 '「親切」の意味は？', 'しんせつ',
 '"親切" (shinsetsu) có nghĩa là gì?',
 'What does 親切 (shinsetsu) mean?',
 '[{"key":"A","text":"kiêu ngạo"},{"key":"B","text":"tốt bụng"},{"key":"C","text":"thông minh"},{"key":"D","text":"lười biếng"}]',
 'B',
 '親切 (shinsetsu) = tốt bụng, thân thiện. Ví dụ: 親切な人 = người tốt bụng.',
 '親切 (shinsetsu) means "kind" or "friendly". Example: 親切な人 = a kind person.',
 'normal'),

('N3', 'grammar',
 '「雨が降り（　）、傘を持って行こう。」= vì sắp mưa nên mang ô', NULL,
 'Điền vào "雨が降り（　）、傘を持って行こう。"',
 'Fill in: 雨が降り（　）、傘を持って行こう。',
 '[{"key":"A","text":"そうだから"},{"key":"B","text":"だけど"},{"key":"C","text":"なのに"},{"key":"D","text":"けれども"}]',
 'A',
 '〜そうだから = vì trông có vẻ... (lý do). 降りそうだから = vì trông có vẻ sắp mưa.',
 '〜そうだから = "it looks like... so". 降りそうだから = Because it looks like it will rain.',
 'normal'),

('N3', 'vocabulary',
 '「以外」の意味は？', 'いがい',
 '"以外" (igai) có nghĩa là gì?',
 'What does 以外 (igai) mean?',
 '[{"key":"A","text":"ngoài ra"},{"key":"B","text":"kể cả"},{"key":"C","text":"bao gồm"},{"key":"D","text":"chẳng hạn"}]',
 'A',
 '以外 (igai) = ngoài ra, trừ... Ví dụ: これ以外 = ngoài cái này ra.',
 '以外 (igai) means "other than" or "except". Example: これ以外 = other than this.',
 'normal'),

('N3', 'grammar',
 '「音楽を聞き（　）、料理します。」= vừa nghe nhạc vừa nấu ăn', NULL,
 'Điền vào "音楽を聞き（　）、料理します。" (vừa...vừa...)',
 'Fill in: 音楽を聞き（　）、料理します。(doing two things simultaneously)',
 '[{"key":"A","text":"ながら"},{"key":"B","text":"てから"},{"key":"C","text":"において"},{"key":"D","text":"につれて"}]',
 'A',
 '〜ながら = vừa... vừa... (làm 2 việc cùng lúc). 聞きながら料理する = vừa nghe vừa nấu.',
 '〜ながら expresses doing two actions simultaneously. = while listening, cooking.',
 'normal'),

-- ═══ N2 ═══════════════════════════════════════════════════

('N2', 'vocabulary',
 '「促す」の意味は？', 'うながす',
 '"促す" (unagasu) có nghĩa là gì?',
 'What does 促す (unagasu) mean?',
 '[{"key":"A","text":"ngăn chặn"},{"key":"B","text":"thúc đẩy"},{"key":"C","text":"tránh né"},{"key":"D","text":"phủ nhận"}]',
 'B',
 '促す (unagasu) = thúc đẩy, thúc giục. Ví dụ: 行動を促す = thúc đẩy hành động.',
 '促す (unagasu) means "to urge" or "to promote". Example: 行動を促す = to urge action.',
 'hard'),

('N2', 'grammar',
 '「人口の増加（　）、問題が複雑化した。」= phức tạp hơn cùng với tăng dân số', NULL,
 'Điền vào "人口の増加（　）、問題が複雑化した。"',
 'Fill in: 人口の増加（　）、問題が複雑化した。',
 '[{"key":"A","text":"に伴い"},{"key":"B","text":"に対して"},{"key":"C","text":"にかかわらず"},{"key":"D","text":"において"}]',
 'A',
 '〜に伴い = cùng với, đi kèm với. Dùng khi 2 sự việc xảy ra song song.',
 '〜に伴い means "along with" or "accompanied by". Used when two things happen in parallel.',
 'hard'),

('N2', 'kanji',
 '「貢献」の読み方は？', NULL,
 'Cách đọc của "貢献" là gì?',
 'What is the reading of 貢献?',
 '[{"key":"A","text":"こうけん"},{"key":"B","text":"こうかん"},{"key":"C","text":"きょうかん"},{"key":"D","text":"きょうけん"}]',
 'A',
 '貢献 (こうけん / kooken) = đóng góp, cống hiến.',
 '貢献 is read こうけん (kooken), meaning "contribution".',
 'hard'),

('N2', 'vocabulary',
 '「概念」の意味は？', 'がいねん',
 '"概念" (gainen) có nghĩa là gì?',
 'What does 概念 (gainen) mean?',
 '[{"key":"A","text":"kết luận"},{"key":"B","text":"khái niệm"},{"key":"C","text":"kết quả"},{"key":"D","text":"quyết định"}]',
 'B',
 '概念 (gainen) = khái niệm. Ví dụ: 概念を理解する = hiểu khái niệm.',
 '概念 (gainen) means "concept" or "notion". Example: 概念を理解する = to understand the concept.',
 'hard'),

('N2', 'grammar',
 '「経験（　）、誰でも参加できます。」= bất kể kinh nghiệm', NULL,
 'Điền vào "経験（　）、誰でも参加できます。" (bất kể kinh nghiệm)',
 'Fill in: 経験（　）、誰でも参加できます。(regardless of experience)',
 '[{"key":"A","text":"にかかわらず"},{"key":"B","text":"に伴い"},{"key":"C","text":"にとって"},{"key":"D","text":"によって"}]',
 'A',
 '〜にかかわらず = bất kể, không phụ thuộc vào. 経験にかかわらず = bất kể kinh nghiệm.',
 '〜にかかわらず means "regardless of". 経験にかかわらず = regardless of experience.',
 'hard'),

('N2', 'vocabulary',
 '「把握」の意味は？', 'はあく',
 '"把握" (haaku) có nghĩa là gì?',
 'What does 把握 (haaku) mean?',
 '[{"key":"A","text":"mất mát"},{"key":"B","text":"nắm bắt"},{"key":"C","text":"thất bại"},{"key":"D","text":"lãng phí"}]',
 'B',
 '把握 (haaku) = nắm bắt, hiểu rõ. Ví dụ: 状況を把握する = nắm bắt tình huống.',
 '把握 (haaku) means "to grasp" or "to understand". Example: 状況を把握する = to grasp the situation.',
 'hard'),

('N2', 'vocabulary',
 '「従来」の意味は？', 'じゅうらい',
 '"従来" (juurai) có nghĩa là gì?',
 'What does 従来 (juurai) mean?',
 '[{"key":"A","text":"tương lai"},{"key":"B","text":"hiện tại"},{"key":"C","text":"trước đây"},{"key":"D","text":"đột ngột"}]',
 'C',
 '従来 (juurai) = trước đây, truyền thống. Ví dụ: 従来の方法 = phương pháp cũ/trước đây.',
 '従来 (juurai) means "conventional" or "traditional". Example: 従来の方法 = the conventional method.',
 'hard'),

('N2', 'grammar',
 '「新製品（　）、詳しく説明します。」= giải thích về sản phẩm mới', NULL,
 'Điền vào "新製品（　）、詳しく説明します。" (giải thích về/liên quan đến)',
 'Fill in: 新製品（　）、詳しく説明します。(regarding the new product)',
 '[{"key":"A","text":"に関して"},{"key":"B","text":"にかかわらず"},{"key":"C","text":"に伴って"},{"key":"D","text":"に対して"}]',
 'A',
 '〜に関して = về, liên quan đến. 新製品に関して = về sản phẩm mới.',
 '〜に関して means "regarding" or "concerning". 新製品に関して = regarding the new product.',
 'hard'),

('N2', 'vocabulary',
 '「妥当」の意味は？', 'だとう',
 '"妥当" (datou) có nghĩa là gì?',
 'What does 妥当 (datou) mean?',
 '[{"key":"A","text":"cực đoan"},{"key":"B","text":"hợp lý"},{"key":"C","text":"lạ thường"},{"key":"D","text":"mâu thuẫn"}]',
 'B',
 '妥当 (datou) = hợp lý, thỏa đáng. Ví dụ: 妥当な判断 = quyết định hợp lý.',
 '妥当 (datou) means "appropriate" or "reasonable". Example: 妥当な判断 = a reasonable judgment.',
 'hard'),

('N2', 'grammar',
 '「若い（　）、彼は非常に経験が豊富だ。」= dù trẻ nhưng giàu kinh nghiệm', NULL,
 'Điền vào "若い（　）、彼は非常に経験が豊富だ。" (mặc dù trẻ)',
 'Fill in: 若い（　）、彼は非常に経験が豊富だ。(although young)',
 '[{"key":"A","text":"ものの"},{"key":"B","text":"ことから"},{"key":"C","text":"ために"},{"key":"D","text":"において"}]',
 'A',
 '〜ものの = tuy/mặc dù... nhưng... Diễn tả sự tương phản. 若いものの = tuy trẻ nhưng...',
 '〜ものの means "although" or "even though". 若いものの = although young...',
 'hard'),

-- ═══ N1 ═══════════════════════════════════════════════════

('N1', 'vocabulary',
 '「懸念」の意味は？', 'けねん',
 '"懸念" (kenen) có nghĩa là gì?',
 'What does 懸念 (kenen) mean?',
 '[{"key":"A","text":"hy vọng"},{"key":"B","text":"lo ngại"},{"key":"C","text":"vui mừng"},{"key":"D","text":"ngạc nhiên"}]',
 'B',
 '懸念 (kenen) = lo ngại, lo lắng. Ví dụ: 安全への懸念 = lo ngại về an toàn.',
 '懸念 (kenen) means "concern" or "worry". Example: 安全への懸念 = concern about safety.',
 'hard'),

('N1', 'grammar',
 '「本日（　）もって、プロジェクトを終了します。」', NULL,
 'Điền vào "本日（　）もって、プロジェクトを終了します。" (kết thúc kể từ hôm nay)',
 'Fill in: 本日（　）もって、プロジェクトを終了します。(ending as of today)',
 '[{"key":"A","text":"で"},{"key":"B","text":"を"},{"key":"C","text":"に"},{"key":"D","text":"が"}]',
 'B',
 '本日をもって = kể từ hôm nay. をもって là cách diễn tả thời điểm hoặc phương tiện trang trọng.',
 '本日をもって means "as of today". をもって is a formal expression indicating the time or means.',
 'hard'),

('N1', 'vocabulary',
 '「隔たり」の意味は？', 'へだたり',
 '"隔たり" (hedatari) có nghĩa là gì?',
 'What does 隔たり (hedatari) mean?',
 '[{"key":"A","text":"gần gũi"},{"key":"B","text":"khoảng cách"},{"key":"C","text":"liên kết"},{"key":"D","text":"hòa hợp"}]',
 'B',
 '隔たり (hedatari) = khoảng cách, sự xa cách. Ví dụ: 意見の隔たり = khoảng cách quan điểm.',
 '隔たり (hedatari) means "gap" or "distance". Example: 意見の隔たり = a gap in opinions.',
 'hard'),

('N1', 'grammar',
 '「この地域（　）文化は世界でも珍しい。」= văn hóa đặc trưng của vùng này', NULL,
 'Điền vào "この地域（　）文化は世界でも珍しい。" (đặc trưng)',
 'Fill in: この地域（　）文化は世界でも珍しい。(unique to this region)',
 '[{"key":"A","text":"ならではの"},{"key":"B","text":"にかかわらず"},{"key":"C","text":"をもって"},{"key":"D","text":"だけあって"}]',
 'A',
 '〜ならではの = đặc trưng của, chỉ có ở. この地域ならではの = đặc trưng chỉ có ở vùng này.',
 '〜ならではの means "unique to" or "characteristic of". この地域ならではの = unique to this region.',
 'hard'),

('N1', 'vocabulary',
 '「煩雑」の意味は？', 'はんざつ',
 '"煩雑" (hanzatsu) có nghĩa là gì?',
 'What does 煩雑 (hanzatsu) mean?',
 '[{"key":"A","text":"đơn giản"},{"key":"B","text":"phức tạp rắc rối"},{"key":"C","text":"rõ ràng"},{"key":"D","text":"có trật tự"}]',
 'B',
 '煩雑 (hanzatsu) = phức tạp, rắc rối, rối rắm. Ví dụ: 煩雑な手続き = thủ tục rắc rối.',
 '煩雑 (hanzatsu) means "complicated" or "troublesome". Example: 煩雑な手続き = complicated procedures.',
 'hard'),

('N1', 'vocabulary',
 '「払拭」の意味は？', 'ふっしょく',
 '"払拭" (fusshoku) có nghĩa là gì?',
 'What does 払拭 (fusshoku) mean?',
 '[{"key":"A","text":"tích lũy thêm"},{"key":"B","text":"xua tan/xóa bỏ"},{"key":"C","text":"che giấu"},{"key":"D","text":"tạo ra"}]',
 'B',
 '払拭 (fusshoku) = xua tan, loại bỏ hoàn toàn. Ví dụ: 不安を払拭する = xua tan lo lắng.',
 '払拭 (fusshoku) means "to dispel" or "to wipe out". Example: 不安を払拭する = to dispel anxiety.',
 'hard'),

('N1', 'grammar',
 '「彼女は育児（　）、小説を書き続けている。」= vừa chăm con vừa viết tiểu thuyết', NULL,
 'Điền vào "彼女は育児（　）、小説を書き続けている。" (trong khi/bên cạnh)',
 'Fill in: 彼女は育児（　）、小説を書き続けている。(while raising children)',
 '[{"key":"A","text":"ながら"},{"key":"B","text":"かたわら"},{"key":"C","text":"つつ"},{"key":"D","text":"に伴い"}]',
 'B',
 '〜かたわら = trong khi đó cũng, bên cạnh việc... (thường là việc phụ song song việc chính).',
 '〜かたわら means "while also doing" or "in addition to". Often used for a side activity alongside the main one.',
 'hard'),

('N1', 'vocabulary',
 '「逡巡」の意味は？', 'しゅんじゅん',
 '"逡巡" (shunjun) có nghĩa là gì?',
 'What does 逡巡 (shunjun) mean?',
 '[{"key":"A","text":"hành động nhanh"},{"key":"B","text":"do dự/chần chừ"},{"key":"C","text":"kiên quyết"},{"key":"D","text":"thẳng thắn"}]',
 'B',
 '逡巡 (shunjun) = do dự, chần chừ, không quyết đoán. Dùng trong văn viết trang trọng.',
 '逡巡 (shunjun) means "hesitation" or "indecision". Used in formal written language.',
 'hard'),

('N1', 'grammar',
 '「資格取得もさることながら、実務経験も重要だ。」- 「もさることながら」の意味は？', NULL,
 '"もさることながら" trong câu có nghĩa gì?',
 'What does もさることながら mean in this sentence?',
 '[{"key":"A","text":"tuy nhiên"},{"key":"B","text":"...cũng quan trọng, nhưng...cũng vậy"},{"key":"C","text":"vì thế"},{"key":"D","text":"thay vì"}]',
 'B',
 'もさることながら = ...cũng quan trọng, nhưng...còn quan trọng hơn. Nhấn mạnh điều tiếp theo.',
 'もさることながら means "not to mention X, but Y is also important". It emphasizes the second point.',
 'hard'),

('N1', 'vocabulary',
 '「杞憂」の意味は？', 'きゆう',
 '"杞憂" (kiyu) có nghĩa là gì?',
 'What does 杞憂 (kiyu) mean?',
 '[{"key":"A","text":"lo lắng có căn cứ"},{"key":"B","text":"sự chuẩn bị kỹ lưỡng"},{"key":"C","text":"lo lắng không cần thiết"},{"key":"D","text":"tự tin quá mức"}]',
 'C',
 '杞憂 (kiyu) = lo lắng vô ích, lo bò trắng răng. Từ điển tích tiếng Hán.',
 '杞憂 (kiyu) means "needless worry" or "unfounded anxiety". It comes from a Chinese idiom.',
 'hard');
