# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-041.csv -- 19 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-041.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("縁側","えんがわ","N4","n",
        "hành lang gỗ (nhà truyền thống Nhật) | hiên nhà kiểu Nhật | engawa",
        "engawa | external corridor on the outer side of traditional Japanese houses",
        "1177630",
        "縁側で日向ぼっこする。","えんがわでひなたぼっこする。",
        "Phơi nắng trên hành lang gỗ.","Sunbathe on the engawa."),
    row("戸棚","とだな","N4","n",
        "tủ chén bát | tủ đứng | tủ đựng đồ | tủ bếp",
        "cupboard | locker | closet | wardrobe | cabinet",
        "1267050",
        "戸棚に食器をしまう。","とだなにしょっきをしまう。",
        "Cất chén bát vào tủ.","Put dishes away in the cupboard."),
    row("始発","しはつ","N4","n",
        "chuyến đầu tiên trong ngày | tàu/xe buýt đầu tiên | ga đầu tuyến",
        "first departure (of the day) | first train | first bus | departing from the first station",
        "1307610",
        "始発に乗る。","しはつにのる。",
        "Đi chuyến tàu đầu tiên.","Ride the first train."),
    row("終電","しゅうでん","N4","n",
        "tàu cuối | chuyến tàu cuối trong ngày",
        "last train (of the day)",
        "1332960",
        "終電を逃した。","しゅうでんをのがした。",
        "Lỡ chuyến tàu cuối.","Missed the last train."),
    row("畳","じょう","N4","n|suf",
        "tatami (đơn vị đo diện tích phòng Nhật, ~1.6–1.8 m²)",
        "tatami mat (esp. as a measure of room size, either 1.82 sqm or 1.54 sqm)",
        "1356740",
        "六畳の部屋。","ろくじょうのへや。",
        "Phòng 6 chiếu tatami.","A six-tatami room."),
    row("畳","たたみ","N4","n",
        "chiếu tatami | sàn cói truyền thống Nhật Bản",
        "tatami mat | Japanese straw floor coverings",
        "1356750",
        "畳の上に座る。","たたみのうえにすわる。",
        "Ngồi trên chiếu tatami.","Sit on the tatami mat."),
    row("請求書","せいきゅうしょ","N4","n",
        "hóa đơn | biên lai yêu cầu thanh toán | phiếu thu",
        "bill | account | invoice | information request form",
        "1381330",
        "請求書を送る。","せいきゅうしょをおくる。",
        "Gửi hóa đơn.","Send an invoice."),
    row("納期","のうき","N4","n",
        "ngày giao hàng | thời hạn giao hàng | hạn nộp tiền",
        "appointed date of delivery | delivery time | due date for payment | period for paying off (a debt)",
        "1470050",
        "納期を守る。","のうきをまもる。",
        "Đảm bảo thời hạn giao hàng.","Meet the delivery deadline."),
    row("発熱","はつねつ","N4","n|vs|vi",
        "sốt | lên cơn sốt | sinh nhiệt",
        "generation of heat | (attack of) fever | pyrexia",
        "1477790",
        "昨日から発熱している。","きのうからはつねつしている。",
        "Bị sốt từ hôm qua.","Have been running a fever since yesterday."),
    row("鼻血","はなぢ","N4","n",
        "chảy máu mũi | máu cam",
        "nosebleed",
        "1583300",
        "鼻血が出る。","はなぢがでる。",
        "Chảy máu mũi.","Have a nosebleed."),
    row("傷跡","きずあと","N4","n",
        "vết sẹo | dấu vết thương",
        "scar | mark left by a wound",
        "1591230",
        "傷跡が残る。","きずあとがのこる。",
        "Để lại vết sẹo.","Leave a scar."),
    row("見積もり","みつもり","N4","n",
        "ước tính | báo giá | dự toán | ước lượng",
        "estimate | estimation | valuation | quotation",
        "1604590",
        "見積もりを出す。","みつもりをだす。",
        "Đưa ra báo giá.","Give an estimate."),
    row("下痢","げり","N4","n|vs|vi",
        "tiêu chảy | đau bụng đi ngoài",
        "diarrhea | diarrhoea",
        "1186540",
        "下痢が続く。","げりがつづく。",
        "Tiêu chảy liên tục.","Have continuous diarrhea."),
    row("咳","せき","N4","n|vs|vi",
        "ho | tiếng ho | cơn ho",
        "cough | coughing | tussis",
        "1204300",
        "咳が止まらない。","せきがとまらない。",
        "Ho không ngừng.","Can't stop coughing."),
    row("捻挫","ねんざ","N4","n|vs|vt",
        "bong gân | trật khớp",
        "sprain | twist | wrench",
        "1469540",
        "足首を捻挫した。","あしくびをねんざした。",
        "Bong gân cổ chân.","Sprained one's ankle."),
    row("畳","たとう","N4","n",
        "giấy gói kimono | hộp giấy gấp đựng kimono",
        "folding paper-case | kimono wrapping paper",
        "2061060",
        "畳紙にきものをしまう。","たとうにきものをしまう。",
        "Cất kimono vào giấy gói.","Store a kimono in wrapping paper."),
    row("障子","しょうじ","N4","n",
        "cửa kéo giấy truyền thống Nhật | shoji",
        "shoji (paper sliding door)",
        "1352090",
        "障子を開ける。","しょうじをあける。",
        "Mở cửa kéo giấy shoji.","Open the shoji door."),
    row("骨折","こっせつ","N4","n|vs|vi",
        "gãy xương",
        "bone fracture",
        "1288640",
        "転んで骨折した。","ころんでこっせつした。",
        "Ngã và gãy xương.","Fall and break a bone."),
    row("鼻水","はなみず","N4","n",
        "nước mũi | sổ mũi | chảy nước mũi",
        "nasal mucus | dripping nose | snot",
        "1487060",
        "鼻水が出る。","はなみずがでる。",
        "Sổ mũi.","Have a runny nose."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
