# -*- coding: utf-8 -*-
OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n3-vi-ready-003.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id):
    return ",".join([q(word), q(reading), q(""), q(lvl), q(pos), q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"), q(""), q(""), q(""), q(""), q("ai_draft"), q("jmdict_ai")])

ROWS = [
    row("芸能人","げいのうじん","N3","n",
        "nghệ sĩ | người biểu diễn | người nổi tiếng | người hoạt động nghệ thuật",
        "entertainer | performer | celebrity | entertainment personality","1253150"),
    row("芸術家","げいじゅつか","N3","n",
        "nghệ sĩ",
        "artist","1253070"),
    row("劇場","げきじょう","N3","n",
        "rạp hát | nhà hát | sân khấu",
        "theatre | theater | playhouse","1253410"),
    row("劇的","げきてき","N3","adj-na",
        "kịch tính | hồi hộp | xúc động | cực đoan",
        "dramatic | exciting | touching | extreme","1253490"),
    row("激励","げきれい","N3","n|vs|vt",
        "khuyến khích | thúc đẩy | cổ vũ",
        "encouragement | spurring (on) | cheering (on)","1253760"),
    row("激増","げきぞう","N3","n|vs|vi",
        "tăng mạnh | tăng đột ngột",
        "sharp increase | sudden rise","1253690"),
    row("激減","げきげん","N3","n|vs|vi",
        "giảm mạnh | giảm đột ngột | sụt giảm đột ngột",
        "dramatic decrease | sharp drop | sudden fall","1253650"),
    row("激怒","げきど","N3","n|vs|vi",
        "cơn thịnh nộ | sự cuồng nộ",
        "rage | fury","1253700"),
    row("激情","げきじょう","N3","n",
        "cảm xúc mãnh liệt | đam mê | cơn cuồng nộ",
        "violent emotion | passion | fury","1253670"),
    row("欠席","けっせき","N3","n|vs|vi",
        "vắng mặt | không có mặt",
        "absence | non-attendance","1254020"),
    row("欠如","けつじょ","N3","n|vs|vt",
        "thiếu | vắng mặt | thiếu hụt | thiếu thốn | tình trạng túng thiếu",
        "lack | absence | shortage | deficiency | privation","1254060"),
    row("欠乏","けつぼう","N3","n|vs|vi",
        "thiếu hụt | không đủ | thiếu thốn | thiếu | khan hiếm",
        "deficiency | insufficiency | shortage | lack | want | dearth | scarcity","1254100"),
    row("決意","けつい","N3","n|vs|vt",
        "quyết định | quyết tâm | nghị quyết",
        "decision | determination | resolution","1254220"),
    row("決心","けっしん","N3","n|vs|vt",
        "quyết tâm | quyết định",
        "determination | resolution","1254340"),
    row("決断","けつだん","N3","n|vs|vt",
        "quyết định | quyết tâm",
        "decision | determination","1254370"),
    row("決定","けってい","N3","n|vs|vt",
        "quyết định | xác định",
        "decision | determination","1254380"),
    row("決定的","けっていてき","N3","adj-na",
        "dứt khoát | cuối cùng | quyết định | có tính kết luận",
        "definite | final | decisive | conclusive","1254400"),
    row("潔白","けっぱく","N3","adj-na|n",
        "vô tội | sự trong sạch | sự thuần khiết | sự ngay thẳng | sự liêm khiết",
        "innocence | guiltlessness | purity | uprightness | integrity","1254460"),
    row("結晶","けっしょう","N3","n|vs|vi",
        "tinh thể | kết tinh | sự kết tinh | thành quả (của lao động)",
        "crystal | crystallization | crystallisation | fruits (of labor, union, etc.)","1254870"),
    row("結束","けっそく","N3","n|vs",
        "đoàn kết | sự thống nhất | tình đoàn kết | bó | ràng buộc | buộc | mặc",
        "union | unity | solidarity | bundling | binding | tying | putting on (clothes)","1254930"),
    row("結末","けつまつ","N3","n",
        "kết thúc | kết luận",
        "end | conclusion","1255010"),
    row("血液型","けつえきがた","N3","n",
        "nhóm máu | loại máu",
        "blood type | blood group","1255150"),
    row("山脈","さんみゃく","N3","n",
        "dãy núi | chuỗi núi",
        "mountain range | mountain belt","1303190"),
    row("惨め","みじめ","N3","adj-na",
        "khốn khổ | đáng thương | bất hạnh | buồn | đáng tội nghiệp",
        "miserable | wretched | unhappy | sad | pitiable","1303280"),
    row("散策","さんさく","N3","n|vs|vi",
        "đi dạo | thả bộ | lang thang | dạo chơi | khám phá",
        "walking | strolling | roaming | wandering | exploring","1303540"),
    row("散文","さんぶん","N3","n",
        "văn xuôi",
        "prose","1303610"),
    row("珊瑚","さんご","N3","n",
        "san hô",
        "coral","1303710"),
    row("産休","さんきゅう","N3","n",
        "nghỉ thai sản | nghỉ phép làm cha",
        "maternity leave | paternity leave","1303760"),
    row("産業","さんぎょう","N3","n",
        "công nghiệp | nghề nghiệp | sinh kế",
        "industry | livelihood | occupation","1303770"),
    row("産地","さんち","N3","n",
        "vùng sản xuất | nơi xuất xứ | vùng trồng trọt",
        "producing area | place of origin | growing district","1303820"),
    row("産物","さんぶつ","N3","n",
        "sản phẩm | nông sản | kết quả | thành quả",
        "product | produce | result | fruit","1303870"),
    row("賛同","さんどう","N3","n|vs|vi",
        "tán thành | ủng hộ",
        "approval | endorsement","1304210"),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
