# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-009.csv — 50 rows (Wave 5 first batch)."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-009.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("コミュニティ","コミュニティ","N4","n",
        "cộng đồng",
        "community",
        "1051040",
        "コミュニティに参加します。","コミュニティにさんかします。","Tôi tham gia cộng đồng.","I join the community."),
    row("サイズ","サイズ","N4","n",
        "kích cỡ | kích thước | cỡ",
        "size",
        "1055780",
        "サイズを確認します。","サイズをかくにんします。","Tôi kiểm tra kích cỡ.","I check the size."),
    row("メディア","メディア","N4","n",
        "phương tiện truyền thông | truyền thông",
        "media",
        "1133620",
        "メディアに注目します。","メディアにちゅうもくします。","Tôi chú ý đến truyền thông.","I pay attention to the media."),
    row("家具","かぐ","N4","n",
        "đồ nội thất | đồ đạc",
        "furniture",
        "1191870",
        "家具を買います。","かぐをかいます。","Tôi mua đồ nội thất.","I buy furniture."),
    row("家賃","やちん","N4","n",
        "tiền thuê nhà | tiền thuê",
        "rent",
        "1192270",
        "家賃を払います。","やちんをはらいます。","Tôi trả tiền thuê nhà.","I pay the rent."),
    row("会社員","かいしゃいん","N4","n",
        "nhân viên công ty | nhân viên văn phòng | người làm công ăn lương",
        "company employee | office worker | white-collar worker",
        "1198560",
        "会社員として働きます。","かいしゃいんとしてはたらきます。","Tôi làm việc với tư cách nhân viên công ty.","I work as a company employee."),
    row("解決策","かいけつさく","N4","n",
        "giải pháp | chiến lược giải quyết",
        "solution | solution strategy",
        "1198970",
        "解決策を考えます。","かいけつさくをかんがえます。","Tôi nghĩ ra giải pháp.","I think of a solution."),
    row("観光客","かんこうきゃく","N4","n",
        "khách du lịch | khách tham quan",
        "tourist",
        "1214870",
        "観光客が多いです。","かんこうきゃくがおおいです。","Có nhiều khách du lịch.","There are many tourists."),
    row("記録","きろく","N4","n|vs|vt",
        "ghi chép | tài liệu | biên bản | nhật ký | ghi âm | ghi vào hồ sơ | kỷ lục (ví dụ trong thể thao) | xác lập kỷ lục",
        "record | document | minutes | log | recording | putting on record | keeping a record (of) | writing down | record (e.g. in sports) | setting (a record)",
        "1223440",
        "記録を更新します。","きろくをこうしんします。","Tôi cập nhật kỷ lục.","I update the record."),
    row("起こる","おこる","N4","v5r|vi",
        "xảy ra | xảy đến",
        "to occur | to happen",
        "1223680",
        "事故が起こりました。","じこがおこりました。","Tai nạn đã xảy ra.","An accident occurred."),
    row("契約","けいやく","N4","n|vs|vt",
        "hợp đồng | thỏa thuận | giao kèo",
        "contract | compact | agreement",
        "1250190",
        "契約を結びます。","けいやくをむすびます。","Tôi ký kết hợp đồng.","I conclude a contract."),
    row("血圧","けつあつ","N4","n",
        "huyết áp",
        "blood pressure",
        "1255110",
        "血圧を測ります。","けつあつをはかります。","Tôi đo huyết áp.","I measure my blood pressure."),
    row("止める","やめる","N4","v1|vt",
        "dừng (một hoạt động) | ngừng | chấm dứt | kết thúc | nghỉ | hủy bỏ | từ bỏ | bỏ cuộc | bãi bỏ | kiêng | kiêng cữ",
        "to stop (an activity) | to cease | to discontinue | to end | to quit | to cancel | to abandon | to give up | to abolish | to abstain | to refrain",
        "1310680",
        "タバコをやめます。","タバコをやめます。","Tôi bỏ thuốc lá.","I quit smoking."),
    row("手段","しゅだん","N4","n",
        "phương tiện | cách thức | biện pháp",
        "means | way | measure",
        "1328110",
        "手段を選びます。","しゅだんをえらびます。","Tôi chọn biện pháp.","I choose a means."),
    row("終了","しゅうりょう","N4","n|vs|vt|vi",
        "kết thúc | đóng lại | kết luận | chấm dứt",
        "end | close | conclusion | termination",
        "1333040",
        "会議が終了します。","かいぎがしゅうりょうします。","Cuộc họp kết thúc.","The meeting concludes."),
    row("床","とこ","N4","n",
        "giường | chỗ ngủ | giường bệnh | hốc trang trí (trong nhà Nhật) | lòng sông | luống hạt giống | sàn nhà",
        "bed | bedding | sickbed | alcove | riverbed | seedbed | straw core of a tatami mat | floor",
        "1349370",
        "床に就きます。","とこにつきます。","Tôi đi ngủ.","I go to bed."),
    row("親密","しんみつ","N4","adj-na|n",
        "sự thân mật | tình thân | tình bạn thân",
        "intimacy | friendship",
        "1365390",
        "親密な関係です。","しんみつなかんけいです。","Là mối quan hệ thân mật.","It is an intimate relationship."),
    row("診断","しんだん","N4","n|vs|vt",
        "chẩn đoán | khám bệnh",
        "diagnosis | medical examination",
        "1365480",
        "医者が診断します。","いしゃがしんだんします。","Bác sĩ chẩn đoán.","The doctor makes a diagnosis."),
    row("人気","ひとけ","N4","n",
        "dấu hiệu sự sống | sự có mặt của người | tính nhân đạo",
        "sign of life | human presence | humanity | humaneness",
        "1367020",
        "人気がない場所です。","ひとけがないばしょです。","Là nơi vắng người.","It is a place with no human presence."),
    row("石","こく","N4","n",
        "koku (đơn vị đo lường truyền thống, khoảng 180,4 lít) | đơn vị đo tải trọng thuyền Nhật Bản (khoảng 278,26 lít)",
        "koku | traditional unit of volume, approx. 180.4 litres | measure of a Japanese-style boat's loading capacity",
        "1382450"),
    row("羨む","うらやむ","N4","v5m|vt",
        "ghen tị | đố kỵ | ghen",
        "to envy | to be envious of | to be jealous of",
        "1391950",
        "彼の成功を羨みます。","かれのせいこうをうらやみます。","Tôi ghen tị với thành công của anh ấy.","I envy his success."),
    row("知事","ちじ","N4","n",
        "tỉnh trưởng | thống đốc tỉnh",
        "prefectural governor",
        "1420580",
        "知事が会見します。","ちじがかいけんします。","Tỉnh trưởng họp báo.","The governor holds a press conference."),
    row("注射","ちゅうしゃ","N4","n|vs|vt",
        "tiêm (thuốc) | mũi tiêm | tiêm chích",
        "injection | jab | shot",
        "1426590",
        "注射を打ちます。","ちゅうしゃをうちます。","Tôi tiêm thuốc.","I get a shot."),
    row("悲しむ","かなしむ","N4","v5m|vt",
        "buồn | thương tiếc | hối tiếc",
        "to be sad | to mourn for | to regret",
        "1483200",
        "別れを悲しみます。","わかれをかなしみます。","Tôi buồn vì phải chia tay.","I am sad about the parting."),
    row("布","ぬの","N4","n",
        "vải | vải vóc | chất liệu | hàng dệt",
        "cloth | fabric | material | textile | bujian (spade-shaped bronze coin of ancient China)",
        "1496840",
        "布を買います。","ぬのをかいます。","Tôi mua vải.","I buy fabric."),
    row("物理","ぶつり","N4","n",
        "quy luật tự nhiên | quy luật vật lý | vật lý học",
        "laws of nature | physical laws | physics",
        "1502790",
        "物理を勉強します。","ぶつりをべんきょうします。","Tôi học vật lý.","I study physics."),
    row("訪れる","おとずれる","N4","v1|vt|vi",
        "ghé thăm | viếng thăm | đến (của mùa, tình huống) | xuất hiện",
        "to visit | to call on | to arrive (of a season, situation, etc.) | to come | to appear",
        "1518080",
        "春が訪れます。","はるがおとずれます。","Mùa xuân đến.","Spring arrives."),
    row("問題点","もんだいてん","N4","n",
        "vấn đề (đang thảo luận) | điểm mấu chốt của vấn đề | vấn đề nan giải",
        "the problem (at issue) | the point at issue | problematic issue | problem",
        "1536050",
        "問題点を指摘します。","もんだいてんをしてきします。","Tôi chỉ ra vấn đề.","I point out the problem."),
    row("飲み物","のみもの","N4","n",
        "đồ uống | thức uống",
        "drink | beverage",
        "1600430",
        "飲み物を注文します。","のみものをちゅうもんします。","Tôi gọi đồ uống.","I order a drink."),
    row("包帯","ほうたい","N4","n|vs|vt",
        "băng y tế | băng bó | băng vết thương",
        "bandage | dressing",
        "1603360",
        "包帯を巻きます。","ほうたいをまきます。","Tôi băng vết thương.","I wrap the bandage."),
    row("市長","しちょう","N4","n",
        "thị trưởng",
        "mayor",
        "1308610",
        "市長が挨拶します。","しちょうがあいさつします。","Thị trưởng chào hỏi.","The mayor greets."),
    row("地震","ない","N4","n",
        "động đất | trận động đất",
        "earthquake",
        "2862777",
        "地震が起きました。","じしんがおきました。","Động đất xảy ra.","An earthquake occurred."),
    row("エチケット","エチケット","N4","n",
        "phép lịch sự | cách ứng xử tốt | tác phong | nghi thức | nhãn (rượu)",
        "politeness | good manners | courtesy | etiquette | (wine) label",
        "1028990",
        "エチケットを守ります。","エチケットをまもります。","Tôi giữ phép lịch sự.","I observe etiquette."),
    row("アレルギー","アレルギー","N4","n|n-suf",
        "dị ứng | phản ứng dị ứng | sự ghét bỏ mạnh (đối với)",
        "allergy | aversion (to) | strong distaste (for)",
        "1019740",
        "花粉アレルギーです。","かふんアレルギーです。","Tôi bị dị ứng phấn hoa.","I have a pollen allergy."),
    row("イベント","イベント","N4","n",
        "sự kiện | buổi tổ chức",
        "event",
        "1021680",
        "イベントに参加します。","イベントにさんかします。","Tôi tham dự sự kiện.","I participate in the event."),
    row("ウイルス","ウイルス","N4","n",
        "vi-rút | vi khuẩn dạng vi-rút",
        "virus",
        "1025450",
        "ウイルスに感染します。","ウイルスにかんせんします。","Tôi bị nhiễm vi-rút.","I am infected with a virus."),
    row("ウェブ","ウェブ","N4","n",
        "web | mạng lưới | World Wide Web",
        "web | World Wide Web",
        "1025850",
        "ウェブで検索します。","ウェブでけんさくします。","Tôi tìm kiếm trên web.","I search on the web."),
    row("ゴール","ゴール","N4","n|vs|vi",
        "cầu môn (trong bóng đá, khúc côn cầu) | rổ (trong bóng rổ) | vạch đích | đích | mục tiêu | đến đích | hoàn thành (cuộc đua)",
        "goal (in soccer, hockey, etc.) | basket (in basketball) | finish line | finishing line | reaching the finish line | finishing (a race) | goal | objective",
        "1054230",
        "ゴールを決めます。","ゴールをきめます。","Tôi ghi bàn.","I score a goal."),
    row("デザイン","デザイン","N4","n|vs|vt",
        "thiết kế | đồ họa",
        "design",
        "1082900",
        "デザインを作ります。","デザインをつくります。","Tôi tạo ra thiết kế.","I create a design."),
    row("ドラマ","ドラマ","N4","n",
        "phim truyền hình (phi tài liệu) | kịch truyền hình | vở kịch | vở diễn | sự kiện kịch tính | bi kịch",
        "(non-documentary) television series | TV drama | play | drama | dramatic incident | spectacle | tragedy",
        "1088830",
        "ドラマを見ます。","ドラマをみます。","Tôi xem phim truyền hình.","I watch a TV drama."),
    row("ニュース","ニュース","N4","n",
        "tin tức | bản tin",
        "news",
        "1091500",
        "ニュースを聞きます。","ニュースをきます。","Tôi nghe tin tức.","I listen to the news."),
    row("バックアップ","バックアップ","N4","n|vs|vt",
        "hỗ trợ (sáng kiến, ứng viên) | sự ủng hộ | sao lưu dự phòng",
        "backing (an initiative, candidate, etc.) | support | backup",
        "1098770",
        "バックアップを取ります。","バックアップをとります。","Tôi sao lưu dữ liệu.","I make a backup."),
    row("ブランド","ブランド","N4","n",
        "thương hiệu | nhãn hiệu",
        "brand",
        "1114090",
        "ブランド品を買います。","ブランドひんをかいます。","Tôi mua hàng hiệu.","I buy a brand-name item."),
    row("プレッシャー","プレッシャー","N4","n",
        "áp lực",
        "pressure",
        "1116860",
        "プレッシャーを感じます。","プレッシャーをかんじます。","Tôi cảm thấy áp lực.","I feel pressure."),
    row("ミーティング","ミーティング","N4","n",
        "cuộc họp | buổi họp",
        "meeting",
        "1130380",
        "ミーティングに出席します。","ミーティングにしゅっせきします。","Tôi tham dự cuộc họp.","I attend the meeting."),
    row("演技","えんぎ","N4","n|vs|vi",
        "diễn xuất | diễn | màn trình diễn",
        "acting | performance",
        "1176820",
        "演技が上手です。","えんぎがじょうずです。","Diễn xuất giỏi.","The acting is good."),
    row("価値","かち","N4","n",
        "giá trị | công lao",
        "value | worth | merit",
        "1189600",
        "価値がある。","かちがある。","Có giá trị.","It has value."),
    row("可能性","かのうせい","N4","n",
        "khả năng | cơ hội | xác suất | tiềm năng | triển vọng",
        "possibility | chance | likelihood | probability | potential | potentiality | promise",
        "1191080",
        "可能性があります。","かのうせいがあります。","Có khả năng.","There is a possibility."),
    row("科学","かがく","N4","n|vs|vt",
        "khoa học | tư duy khoa học",
        "science | to think about scientifically | to think in terms of science",
        "1192700",
        "科学を学びます。","かがくをまなびます。","Tôi học khoa học.","I study science."),
    row("歌手","かしゅ","N4","n",
        "ca sĩ | người hát",
        "singer",
        "1193290",
        "有名な歌手です。","ゆうめいなかしゅです。","Là ca sĩ nổi tiếng.","A famous singer."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
