# -*- coding: utf-8 -*-
"""Build N3 ready wave 054 — 78 freshly-curated N3 food/clothing/shopping + cooking verbs + utensils."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-054.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("味覚","みかく","n","vị giác | khẩu vị","(sense of) taste | palate","1527020"),
    ("風味","ふうみ","n","hương vị | mùi vị","taste | flavor","1624810"),
    ("酸味","さんみ","n","vị chua | độ chua","sourness | acidity","1304390"),
    ("甘味","あまみ","n","vị ngọt | đồ ngọt","sweetness | sugary taste | sweets","1609070"),
    ("苦味","にがみ","n","vị đắng","bitterness | bitter taste","1244630"),
    ("塩辛い","しおからい","adj-i","mặn | mặn chát","salty (taste) | briny","1609860"),
    ("香辛料","こうしんりょう","n","gia vị | hương liệu","spice | spices | condiment","1283050"),
    ("薬味","やくみ","n","gia vị ăn kèm (gừng, wasabi, hành...)","condiment | spice (grated/chopped topping)","1538310"),
    ("食感","しょっかん","n","cảm giác khi ăn | độ giòn/mềm","food texture | mouthfeel","1928680"),
    ("食べ放題","たべほうだい","n","ăn thả ga | ăn buffet không giới hạn","all-you-can-eat","1358360"),
    ("惣菜","そうざい","n","món ăn kèm | thức ăn sẵn","small dish | side dish","1399580"),
    ("外食","がいしょく","n|vs|vi","ăn ngoài | ăn tiệm","eating out | dining out","1203830"),
    ("自炊","じすい","n|vs|vi","tự nấu ăn | tự túc nấu nướng","cooking for oneself | self-catering","1318010"),
    ("食生活","しょくせいかつ","n","chế độ ăn uống | thói quen ăn uống","eating habits | diet","1358510"),
    ("脂肪","しぼう","n","chất béo | mỡ","fat | grease | lard","1311820"),
    ("糖分","とうぶん","n","lượng đường | hàm lượng đường","amount of sugar | sugar content","1449650"),
    ("塩分","えんぶん","n","lượng muối | độ mặn","salt content | salinity","1178870"),
    ("水分","すいぶん","n","nước | độ ẩm | hơi nước","water | moisture | humidity","1372010"),
    ("賞味期限","しょうみきげん","n","hạn sử dụng tốt nhất | hạn dùng","best-before date | expiry date","1351980"),
    ("名産","めいさん","n","đặc sản | sản vật nổi tiếng","noted product | local specialty","1531520"),
    ("特産","とくさん","n|vs|vt","đặc sản | sản vật địa phương","local specialty | being produced in a region","1454920"),
    ("旬","しゅん","n|adj-na","mùa (rau quả, hải sản) | đúng vụ | đang hot","season (for food) | in vogue | fresh","1341350"),
    ("衣服","いふく","n","quần áo | trang phục","clothes","1158810"),
    ("衣類","いるい","n","quần áo | y phục","clothes | clothing | garments","1613280"),
    ("服装","ふくそう","n","trang phục | cách ăn mặc","attire | dress | clothing | garb","1500970"),
    ("私服","しふく","n","thường phục | đồ thường (không đồng phục)","plain clothes | civilian clothes | casual wear","1658300"),
    ("和服","わふく","n","trang phục Nhật | kimono","Japanese clothes","1562190"),
    ("襟","えり","n","cổ áo | ve áo | gáy","collar | lapel | nape of the neck","1588750"),
    ("生地","きじ","n","vải | chất liệu | bột (nhào) | bản chất thật","cloth | fabric | dough | one's true character","1379330"),
    ("繊維","せんい","n","sợi | chất xơ | thớ sợi","fibre | fiber","1391890"),
    ("柄","がら","n|n-suf","họa tiết | hoa văn | vóc dáng | bản chất | hợp với","pattern | design | physique | character | suitable for","1508300"),
    ("縞","しま","n","sọc | vằn | họa tiết kẻ sọc","stripe | bar | stripe pattern","1321670"),
    ("無地","むじ","adj-no|n","trơn | một màu | không họa tiết","plain | patternless | solid (color)","1530650"),
    ("飾り","かざり","n","đồ trang trí | vật trang hoàng","decoration | ornament | trimmings","1357160"),
    ("化粧","けしょう","n|vs|vt|vi","trang điểm | mỹ phẩm | tô điểm","make-up | cosmetics | decoration","1577040"),
    ("美容","びよう","n","làm đẹp | thẩm mỹ | nhan sắc","beauty | beauty treatment | beautification","1486670"),
    ("香水","こうすい","n","nước hoa","perfume | scent","1283060"),
    ("宝石","ほうせき","n","đá quý | trang sức | ngọc","gem | jewel | precious stone","1516220"),
    ("指輪","ゆびわ","n","nhẫn","(finger) ring","1310050"),
    ("購入","こうにゅう","n|vs|vt","mua | mua vào | mua sắm","purchase | buying","1282440"),
    ("売り切れ","うりきれ","adj-no|n","hết hàng | bán hết","sold-out","1473870"),
    ("定価","ていか","n","giá niêm yết | giá gốc | giá quy định","list price | regular price","1435410"),
    ("半額","はんがく","n","nửa giá | giảm nửa giá","half the amount | half price","1479050"),
    ("特売","とくばい","n|vs|vt","bán hạ giá | giảm giá đặc biệt","special sale | bargain sale","1455250"),
    ("現金","げんきん","n|adj-na","tiền mặt | thực dụng | tính toán","cash | ready money | mercenary | calculating","1263550"),
    ("紙幣","しへい","n","tiền giấy | giấy bạc","paper money | note | bill","1311600"),
    ("硬貨","こうか","n","tiền xu | đồng xu","coin | hard currency","1280530"),
    ("小銭","こぜに","n","tiền lẻ | tiền xu | khoản nhỏ","small change | pocket change | coins","1348470"),
    ("釣り銭","つりせん","n","tiền thừa | tiền thối lại","change (for a purchase)","1598160"),
    ("明細","めいさい","n|adj-na","chi tiết | bản kê chi tiết","details | particulars | detailed statement","1532440"),
    ("無駄遣い","むだづかい","n|vs|vt","lãng phí | tiêu hoang | phung phí","waste (of money, time) | squandering","1530520"),
    ("贈り物","おくりもの","n","quà tặng | món quà","present | gift","1589030"),
    ("特典","とくてん","n","ưu đãi | đặc quyền | quyền lợi kèm theo","privilege | special favor | benefit | perk","1455220"),
    ("景品","けいひん","n","quà tặng kèm | quà khuyến mãi | giải thưởng","gift | giveaway | prize","1250880"),
    ("福袋","ふくぶくろ","n","túi may mắn | túi hàng bốc thăm","lucky-dip bag | grab bag","1629750"),
    ("配達","はいたつ","n|vs|vt","giao hàng | phân phát","delivery","1473140"),
    ("計る","はかる","v5r|vt","đo | đong | tính | ước lượng","to measure | to weigh | to time | to surmise","1600650"),
    ("味わう","あじわう","v5u|vt","nếm | thưởng thức | trải nghiệm","to taste | to savor | to appreciate | to experience","1527010"),
    ("飲み込む","のみこむ","v5m|vt","nuốt | hiểu ra | nắm bắt | nuốt (lời)","to swallow | to grasp | to take in | to suppress","1600400"),
    ("吐く","はく","v5k|vt","nôn | thở ra | nhổ | thốt ra","to vomit | to breathe out | to spit | to express","2646460"),
    ("頬張る","ほおばる","v5r|vt","nhét đầy miệng | ngấu nghiến","to stuff one's cheeks | to fill one's mouth (with food)","1851260"),
    ("平らげる","たいらげる","v1|vt","ăn sạch | dẹp yên (loạn) | san phẳng","to eat up | to suppress (a rebellion) | to level out","1506960"),
    ("盛り付ける","もりつける","v1|vt","bày món | trình bày món ăn lên đĩa","to dish up | to arrange (food) on a plate","1848860"),
    ("和える","あえる","v1|vt","trộn (gỏi) | trộn với nước sốt","to dress (a salad) | to toss (in a sauce)","1574260"),
    ("混ぜ合わせる","まぜあわせる","v1|vt","trộn lẫn | pha trộn | kết hợp","to mix | to blend | to combine","1603960"),
    ("漉す","こす","v5s|vt","lọc | gạn","to filter | to strain","1288330"),
    ("垂らす","たらす","v5s|vt","nhỏ giọt | làm rớt | thả lủng lẳng","to dribble | to spill | to suspend | to dangle","1370840"),
    ("振りかける","ふりかける","v1|vt","rắc lên | rưới lên (muối, tiêu)","to sprinkle over (e.g. salt on food)","1361180"),
    ("挟む","はさむ","v5m|vt","kẹp | gắp | xen vào | chen (ý kiến)","to hold between | to insert | to interpose | to interject","1600740"),
    ("釜","かま","n","nồi (gang) | ấm | chõ","iron pot | kettle","1209080"),
    ("皿","さら","n","đĩa | dĩa | món (đếm)","plate | dish | platter | serving","1299680"),
    ("匙","さじ","n","thìa | muỗng","spoon","1585630"),
    ("盆","ぼん","n","khay | mâm | lễ Obon","tray | Obon (Bon Festival)","1523700"),
    ("栓","せん","n","nút | nắp | vòi | van","stopper | cork | plug | tap","1956550"),
    ("蓋","ふた","n","nắp | nắp đậy","cover | lid | cap","1204540"),
    ("柄","え","n","cán | tay cầm | cuống (nấm, lá)","handle | grip | stalk (of a mushroom, leaf)","1508290"),
    ("取っ手","とって","n","tay nắm | tay cầm | núm","handle | grip | knob","1598780"),
    ("持ち手","もちて","n","quai cầm | tay cầm | người cầm","handle | grip | person who holds","2760100"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
