# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-025.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-025.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("何千","なんぜん","N4","n",
        "hàng nghìn",
        "many thousands",
        "1189120",
        "何千人も来ます。","なんぜんにんもきます。","Hàng nghìn người đến.","Many thousands of people come."),
    row("何百","なんびゃく","N4","n",
        "hàng trăm",
        "hundreds",
        "1189290",
        "何百冊も読みます。","なんびゃくさつもよみます。","Tôi đọc hàng trăm cuốn sách.","I read hundreds of books."),
    row("済ます","すます","N4","v5s|vt",
        "hoàn thành | kết thúc | giải quyết | thanh toán | xoay xở (không có)",
        "to finish | to get it over with | to conclude | to settle | to pay back | to get along (without something) | to make do with (without)",
        "1295030",
        "用事を済ます。","ようじをすます。","Tôi hoàn thành việc cần làm.","I finish my errands."),
    row("持ち上げる","もちあげる","N4","v1|vt",
        "nâng lên | nhấc lên | tâng bốc | ca ngợi hết lời",
        "to elevate | to raise | to lift up | to flatter | to extol | to praise to the sky",
        "1315610",
        "荷物を持ち上げます。","にもつをもちあげます。","Tôi nhấc hành lý lên.","I lift the luggage up."),
    row("社会学","しゃかいがく","N4","n",
        "xã hội học",
        "sociology",
        "1322730",
        "社会学を学びます。","しゃかいがくをまなびます。","Tôi học xã hội học.","I study sociology."),
    row("手順","てじゅん","N4","n",
        "quy trình | thủ tục | trình tự | giao thức",
        "process | procedure | sequence | protocol | instruction",
        "1327810",
        "手順に従います。","てじゅんにしたがいます。","Tôi tuân theo quy trình.","I follow the procedure."),
    row("春分","しゅんぶん","N4","n",
        "điểm phân xuân | ngày xuân phân",
        "vernal equinox | spring equinox",
        "1341160",
        "春分の日です。","しゅんぶんのひです。","Hôm nay là ngày xuân phân.","Today is the vernal equinox."),
    row("心理学","しんりがく","N4","n",
        "tâm lý học",
        "psychology",
        "1361010",
        "心理学を勉強します。","しんりがくをべんきょうします。","Tôi học tâm lý học.","I study psychology."),
    row("申請書","しんせいしょ","N4","n",
        "đơn xin | bản đăng ký | tờ khai",
        "written application",
        "1363140",
        "申請書を提出します。","しんせいしょをていしゅつします。","Tôi nộp đơn xin.","I submit the application form."),
    row("通院","つういん","N4","n|vs|vi",
        "đi khám bệnh ngoại trú | điều trị ngoại trú",
        "going to the hospital regularly for treatment | attending hospital as an outpatient",
        "1433040",
        "毎週病院に通院します。","まいしゅうびょういんにつういんします。","Mỗi tuần tôi đi khám bệnh ngoại trú.","I attend the hospital as an outpatient every week."),
    row("哲学","てつがく","N4","n",
        "triết học",
        "philosophy",
        "1437610",
        "哲学を研究します。","てつがくをけんきゅうします。","Tôi nghiên cứu triết học.","I study philosophy."),
    row("動揺","どうよう","N4","n|vs|vi",
        "chấn động | dao động | bất ổn | xáo trộn | kích động",
        "shaking | trembling | pitching | rolling | oscillation | disturbance | unrest | agitation | excitement | commotion | turmoil | discomposure | feeling shaken",
        "1451630",
        "知らせを聞いて動揺します。","しらせをきいてどうようします。","Tôi bị chấn động khi nghe tin.","I feel shaken upon hearing the news."),
    row("返信","へんしん","N4","n|vs|vt|vi",
        "trả lời | hồi âm | phúc đáp",
        "reply (e.g. email, fax, letter) | answer",
        "1512240",
        "メールに返信します。","メールにへんしんします。","Tôi trả lời email.","I reply to the email."),
    row("報告書","ほうこくしょ","N4","n",
        "báo cáo (văn bản)",
        "(written) report",
        "1515690",
        "報告書を作成します。","ほうこくしょをさくせいします。","Tôi soạn báo cáo.","I prepare the report."),
    row("取扱説明書","とりあつかいせつめいしょ","N4","n",
        "hướng dẫn sử dụng | sách hướng dẫn",
        "user's manual | instruction manual | operation manual",
        "1599000",
        "取扱説明書を読みます。","とりあつかいせつめいしょをよみます。","Tôi đọc hướng dẫn sử dụng.","I read the instruction manual."),
    row("露","ろ","N4","n",
        "Nga (viết tắt bằng kanji)",
        "Russia",
        "1147330",
        "露日関係を研究します。","ろにちかんけいをけんきゅうします。","Tôi nghiên cứu quan hệ Nga-Nhật.","I study Russian-Japanese relations."),
    row("委員会","いいんかい","N4","n",
        "ủy ban | hội đồng | ban",
        "committee | commission | board | panel | committee meeting",
        "1156110",
        "委員会で決定します。","いいんかいできていします。","Ủy ban quyết định.","The committee makes a decision."),
    row("葛藤","かっとう","N4","n|vs|vi",
        "mâu thuẫn nội tâm | xung đột | khó khăn",
        "conflict | complication | troubles | discord",
        "1208780",
        "葛藤を感じます。","かっとうをかんじます。","Tôi cảm thấy mâu thuẫn nội tâm.","I feel inner conflict."),
    row("協定","きょうてい","N4","n|vs",
        "thỏa thuận | hiệp định | hiệp ước",
        "arrangement | pact | agreement",
        "1235730",
        "協定を結びます。","きょうていをむすびます。","Chúng tôi ký kết hiệp định.","We conclude an agreement."),
    row("経済学","けいざいがく","N4","n",
        "kinh tế học",
        "economics",
        "1251380",
        "経済学を専攻します。","けいざいがくをせんこうします。","Tôi chuyên ngành kinh tế học.","I major in economics."),
    row("芸術","げいじゅつ","N4","n",
        "nghệ thuật",
        "art | the arts",
        "1253060",
        "芸術に興味があります。","げいじゅつにきょうみがあります。","Tôi quan tâm đến nghệ thuật.","I am interested in art."),
    row("取り扱い","とりあつかい","N4","n",
        "xử lý | giải quyết | quản lý | dịch vụ",
        "treatment | service | handling | management",
        "1598990",
        "丁寧な取り扱いが必要です。","ていねいなとりあつかいがひつようです。","Cần xử lý cẩn thận.","Careful handling is necessary."),
    row("取り組み","とりくみ","N4","n",
        "nỗ lực | sáng kiến | giải quyết | trận đấu",
        "effort | initiative | dealing with | grappling with | wrestling with | bout (in sports, etc.) | match",
        "1599040",
        "環境への取り組みが大切です。","かんきょうへのとりくみがたいせつです。","Nỗ lực bảo vệ môi trường rất quan trọng.","Environmental initiatives are important."),
    row("情けない","なさけない","N4","adj-i",
        "đáng thương | nhục nhã | đáng hổ thẹn | tệ hại",
        "miserable | pitiable | shameful | deplorable | pathetic",
        "1599480",
        "情けない結果になりました。","なさけないけっかになりました。","Kết quả thật tệ hại.","The result turned out pathetic."),
    row("見かける","みかける","N4","v1|vt",
        "tình cờ thấy | nhận ra | bắt gặp",
        "to (happen to) see | to notice | to catch sight of",
        "1604430",
        "駅で友達を見かけます。","えきでともだちをみかけます。","Tôi tình cờ thấy bạn ở ga.","I happen to see my friend at the station."),
    row("何十","なんじゅう","N4","n",
        "hàng chục | vài chục",
        "(several) tens | dozens | scores (of)",
        "1611010",
        "何十人も集まります。","なんじゅうにんもあつまります。","Hàng chục người tập hợp.","Dozens of people gather."),
    row("申し訳ない","もうしわけない","N4","exp|adj-i",
        "thật sự xin lỗi | không thể tha thứ | cảm thấy có lỗi",
        "I'm sorry | (it's) inexcusable | I feel regretful | I feel guilty | thank you very much (for help, etc.)",
        "1612040",
        "申し訳ないと思います。","もうしわけないとおもいます。","Tôi thực sự cảm thấy có lỗi.","I feel truly sorry."),
    row("引き渡し","ひきわたし","N4","n",
        "giao hàng | bàn giao | dẫn độ",
        "delivery | handing over | turning over | extradition",
        "1613410",
        "商品の引き渡しをします。","しょうひんのひきわたしをします。","Tôi bàn giao sản phẩm.","I hand over the product."),
    row("絶対的","ぜったいてき","N4","adj-na",
        "tuyệt đối",
        "absolute",
        "1721650",
        "絶対的な自信があります。","ぜったいてきなじしんがあります。","Tôi có niềm tin tuyệt đối.","I have absolute confidence."),
    row("食材","しょくざい","N4","n",
        "nguyên liệu thực phẩm | nguyên liệu nấu ăn",
        "foodstuff | ingredient",
        "1983500",
        "新鮮な食材を使います。","しんせんなしょくざいをつかいます。","Tôi dùng nguyên liệu tươi.","I use fresh ingredients."),
    row("計画書","けいかくしょ","N4","n",
        "kế hoạch (văn bản) | chương trình | bản kế hoạch",
        "plan | protocol | manifest | program",
        "2531370",
        "計画書を提出します。","けいかくしょをていしゅつします。","Tôi nộp bản kế hoạch.","I submit the plan."),
    row("国民","くにたみ","N4","n",
        "nhân dân của một đất nước (cách đọc cổ)",
        "people of a country",
        "2843598",
        "国民の幸福を願います。","くにたみのこうふくをねがいます。","Tôi mong nhân dân được hạnh phúc.","I wish for the happiness of the people."),
    row("芸能","げいのう","N4","n",
        "nghệ thuật biểu diễn | giải trí công cộng | tài năng",
        "public entertainment | performing arts | accomplishments | attainments",
        "1253130",
        "芸能界に入ります。","げいのうかいにはいります。","Tôi gia nhập làng giải trí.","I enter the entertainment industry."),
    row("血管","けっかん","N4","n",
        "mạch máu | huyết quản",
        "blood vessel | vein",
        "1255180",
        "血管が詰まります。","けっかんがつまります。","Mạch máu bị tắc.","The blood vessel gets blocked."),
    row("戸惑い","とまどい","N4","n|vs",
        "bối rối | mất phương hướng | hoang mang",
        "being at sea | losing one's bearings | confusion | wonderment | disorientation upon waking at night | forgetting which house or room to enter",
        "1267090",
        "戸惑いを感じます。","とまどいをかんじます。","Tôi cảm thấy bối rối.","I feel confused."),
    row("後ろ向き","うしろむき","N4","adj-na|adj-no|n",
        "nhìn về phía sau | tiêu cực | thụ lùi",
        "back-facing | backwards | backward-looking | retrogressive | reactionary | retrospective | negative",
        "1269640",
        "後ろ向きな考えは良くないです。","うしろむきなかんがえはよくないです。","Suy nghĩ tiêu cực không tốt.","Negative thinking is not good."),
    row("交換","こうかん","N4","n|vs|vt",
        "trao đổi | hoán đổi | thay thế | đổi chác",
        "exchange | interchange | switching | reciprocity | barter | substitution | replacement | clearing (of checks, cheques)",
        "1271750",
        "情報を交換します。","じょうほうをこうかんします。","Tôi trao đổi thông tin.","I exchange information."),
    row("骨格","こっかく","N4","n",
        "bộ xương | khung xương | vóc dáng | cấu trúc nền",
        "skeleton | skeletal structure | build | frame | physique | framework",
        "1288570",
        "骨格が強いです。","こっかくがつよいです。","Bộ xương chắc chắn.","The skeletal structure is strong."),
    row("砕く","くだく","N4","v5k|vt",
        "vỡ vụn | đập tan | nghiền nát | làm tan vỡ (hy vọng) | đơn giản hóa",
        "to break (into pieces) | to smash | to crush | to shatter | to grind (into powder) | to pound | to shatter (someone's hopes, confidence, etc.) | to crush | to frustrate | to simplify | to make easy to understand",
        "1295170",
        "岩を砕きます。","いわをくだきます。","Tôi đập vỡ tảng đá.","I smash the rock."),
    row("使い方","つかいかた","N4","n",
        "cách sử dụng | cách dùng | cách xử lý (nhân viên)",
        "way of using (something) | way to use | how to use | usage | use | way of handling (employees, subordinates, etc.) | way of treating | treatment | management",
        "1305950",
        "パソコンの使い方を教えます。","パソコンのつかいかたをおしえます。","Tôi hướng dẫn cách dùng máy tính.","I teach how to use a computer."),
    row("彫刻","ちょうこく","N4","n|vs|vt|vi",
        "điêu khắc | khắc chạm",
        "carving | engraving | sculpture",
        "1427980",
        "彫刻を作ります。","ちょうこくをつくります。","Tôi tạo tác phẩm điêu khắc.","I make a sculpture."),
    row("通知","つうち","N4","n|vs|vt",
        "thông báo | thông tri | thông báo (điện thoại)",
        "notice | notification | report | posting | notification (on a smartphone, PC, etc.)",
        "1433470",
        "通知が届きます。","つうちがとどきます。","Thông báo đến nơi.","The notification arrives."),
    row("潰す","つぶす","N4","v5s|vt",
        "đập bẹp | nghiền nát | đóng cửa (doanh nghiệp) | giết mổ | giết thời gian | lãng phí",
        "to smash | to crush | to flatten | to shut down | to put out of business | to force (a company) to close up shop | to wreck | to break | to block | to thwart | to butcher | to slaughter | to kill (livestock, for food) | to kill (time) | to while away (the time) | to use up (one's time) | to waste (e.g. talents)",
        "1433820",
        "計画を潰します。","けいかくをつぶします。","Tôi phá vỡ kế hoạch.","I wreck the plan."),
    row("潰れる","つぶれる","N4","v1|vi",
        "bị nghiền nát | sụp đổ | phá sản | bị hủy (kế hoạch) | mất đi (giọng nói) | say xỉn",
        "to be crushed | to be squashed | to be smashed | to be destroyed | to be broken | to collapse | to go bankrupt | to go under | to fail | to collapse | to be ruined (of a plan) | to be cancelled | to collapse (e.g. of a project) | to fall through | to blow up | to be lost (of one's voice, eyesight, sense of smell, etc.) | to cease functioning | to be taken up (of one's time) | to be lost | to be wasted | to be missed (of a chance) | to be lost | to be lost (of face, composure, etc.) | to broken down (e.g. of one's courage) | to be broken (of one's heart) | to be worn down (of a pen nib, saw teeth, etc.) | to wear away | to become dull | to get dead drunk",
        "1433830",
        "会社が潰れます。","かいしゃがつぶれます。","Công ty phá sản.","The company goes bankrupt."),
    row("締結","ていけつ","N4","n|vs|vt|vi",
        "ký kết | kết thúc (hợp đồng) | ký hiệp ước",
        "conclusion | execution (of a contract) | entering (into treaty) | fastening (as in a joint)",
        "1436660",
        "条約を締結します。","じょうやくをていけつします。","Chúng tôi ký kết điều ước.","We conclude a treaty."),
    row("天文学","てんもんがく","N4","n",
        "thiên văn học",
        "astronomy",
        "1440280",
        "天文学を学びます。","てんもんがくをまなびます。","Tôi học thiên văn học.","I study astronomy."),
    row("認証","にんしょう","N4","n|vs|vt",
        "chứng nhận | xác thực | xác nhận",
        "certification | attestation | authentication | confirmation | Imperial attestation",
        "1467560",
        "本人認証をします。","ほんにんにんしょうをします。","Tôi xác thực danh tính.","I authenticate my identity."),
    row("燃える","もえる","N4","v1|vi",
        "cháy | bốc lửa | hừng hực nhiệt huyết",
        "to burn | to get fired up",
        "1469570",
        "家が燃えます。","いえがもえます。","Nhà bốc lửa.","The house burns."),
    row("剥く","むく","N4","v5k|vt",
        "bóc vỏ | lột da | bóc | trần (răng) | mở to (mắt)",
        "to peel | to skin | to pare | to hull | to strip | to bare (teeth, fangs) | to open wide (eyes)",
        "1474370",
        "りんごを剥きます。","りんごをむきます。","Tôi gọt vỏ táo.","I peel an apple."),
    row("副作用","ふくさよう","N4","n",
        "tác dụng phụ | phản ứng phụ",
        "side effect | adverse reaction",
        "1500400",
        "薬の副作用があります。","くすりのふくさようがあります。","Thuốc có tác dụng phụ.","The medicine has side effects."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
