# -*- coding: utf-8 -*-
"""Build N2 ready wave 044 — calendar, year/month periods, day phases, seasons, seasonal weather."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-044.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("今年度","こんねんど","n|adv","năm nay | năm tài chính này | năm học này","this year | this fiscal year","1657600"),
    ("来年度","らいねんど","n","năm sau | năm tài chính tới","next year | next fiscal year","2013930"),
    ("前年度","ぜんねんど","adv|n","năm trước | năm tài chính trước","preceding fiscal year","1393850"),
    ("年明け","としあけ","n","đầu năm | sang năm mới","beginning of the year","1469220"),
    ("年始","ねんし","n","đầu năm | năm mới | lời chúc năm mới","beginning of the year | New Year's greetings","1468730"),
    ("年内","ねんない","n","trong năm | phần còn lại của năm","remainder of the year","1469060"),
    ("歳末","さいまつ","n","cuối năm | dịp cuối năm","year end","1295010"),
    ("暮れ","くれ","n|adv|adj-no|n-suf","hoàng hôn | chạng vạng | cuối (mùa) | cuối năm","sunset | nightfall | year-end","1514950"),
    ("正月","しょうがつ","n","Tết | năm mới | tháng Giêng","New Year | first month of the year","1377030"),
    ("元旦","がんたん","n","mùng một Tết | sáng đầu năm | ngày đầu năm","New Year's Day | New Year's morning","1260950"),
    ("新暦","しんれき","n","dương lịch | lịch Gregory","the solar calendar | the Gregorian calendar","1720530"),
    ("陰暦","いんれき","n","âm lịch","lunar calendar","1170540"),
    ("陽暦","ようれき","n","dương lịch","solar calendar","1662270"),
    ("和暦","われき","n","lịch Nhật | niên hiệu Nhật","Japanese calendar | Japanese imperial year","2026280"),
    ("閏年","うるうどし","n|adj-no","năm nhuận","leap year","1588560"),
    ("祭日","さいじつ","n|adj-no","ngày lễ | ngày tế lễ | ngày nghỉ lễ","national holiday | festival day","1295310"),
    ("振替休日","ふりかえきゅうじつ","n","ngày nghỉ bù","substitute national holiday | compensatory holiday","1834400"),
    ("週明け","しゅうあけ","n","đầu tuần (thường thứ Hai) | đầu tuần sau","beginning of next week | early next week","1659230"),
    ("月初め","つきはじめ","n","đầu tháng","beginning of the month","1255710"),
    ("月初","げっしょ","n","đầu tháng","beginning of the month","2857501"),
    ("半期","はんき","n|adv","nửa kỳ | nửa năm | nửa nhiệm kỳ","half-term | half-year","1479120"),
    ("前期","ぜんき","n|adj-no|adv","kỳ trước | nửa đầu năm | giai đoạn đầu","first term | first half-year | early period","1392750"),
    ("後期","こうき","n|adj-no","kỳ sau | nửa cuối | giai đoạn cuối | kỳ hai","latter period | second half | late stage","1269540"),
    ("今期","こんき","n|adv","kỳ này | nhiệm kỳ hiện tại","the present term | the present session","1289080"),
    ("来期","らいき","n|adv","kỳ tới | nhiệm kỳ sau","next term","1834770"),
    ("通年","つうねん","n|adj-no","quanh năm | suốt năm","all year | year round","1984000"),
    ("年間","ねんかん","n|adv|n-suf","trong một năm | hằng năm | trong thời đại","(period of) a year | during the era (of)","1468380"),
    ("月間","げっかん","n","trong tháng | thời gian một tháng","month-long period | month","1255550"),
    ("週間","しゅうかん","n","tuần | trong tuần","week","1333500"),
    ("昼間","ひるま","n|adv","ban ngày | lúc ban ngày","daytime | during the day","1581710"),
    ("夜間","やかん","n|adv","ban đêm | về đêm","night | nighttime","1536530"),
    ("日中","にっちゅう","n|adv","ban ngày | giữa ban ngày | Nhật-Trung","daytime | during the day | Sino-Japanese","1464250"),
    ("未明","みめい","n|adv","tờ mờ sáng | rạng sáng | sáng sớm","early dawn | grey of morning","1528050"),
    ("真昼","まひる","n|adv","giữa trưa | ban ngày ban mặt","midday | broad daylight","1364160"),
    ("早暁","そうぎょう","n|adv","tảng sáng | bình minh | rạng đông","daybreak | dawn","1400210"),
    ("払暁","ふつぎょう","n","rạng đông | hừng đông | tảng sáng","dawn | daybreak","1501630"),
    ("正午","しょうご","n|adv","chính ngọ | đúng trưa | giữa trưa","noon | midday","1377080"),
    ("時差","じさ","n","chênh lệch múi giờ | lệch giờ","time difference","1316240"),
    ("標準時","ひょうじゅんじ","n","giờ chuẩn | múi giờ chuẩn","standard time","1488750"),
    ("時間外","じかんがい","n","ngoài giờ | làm thêm giờ","overtime | outside of hours","1315950"),
    ("定刻","ていこく","n","đúng giờ | giờ đã định | đúng lịch","appointed time | schedule","1435580"),
    ("定時","ていじ","n","giờ cố định | đúng giờ | kỳ hạn định sẵn","fixed time | scheduled time","1435590"),
    ("所定","しょてい","adj-no","đã quy định | định sẵn | được chỉ định","prescribed | designated | fixed","1343350"),
    ("即時","そくじ","adj-no|n|adv","tức thời | tức thì | theo thời gian thực","prompt | immediate | in real time","1404210"),
    ("平年","へいねん","n","năm thường (không nhuận) | năm bình thường","non-leap year | normal year","1507740"),
    ("本年","ほんねん","n|adv","năm nay | trong năm này","this (current) year","1523120"),
    ("昨年度","さくねんど","n|adv","năm trước (tài chính, học)","previous year (fiscal, academic)","1657890"),
    ("春先","はるさき","n|adv","đầu xuân | chớm xuân","beginning of spring","1341110"),
    ("初春","しょしゅん","n","đầu xuân | chớm xuân | tháng Giêng âm","early spring | beginning of spring","1342810"),
    ("晩春","ばんしゅん","adv|n","cuối xuân","late spring","1482200"),
    ("盛夏","せいか","n","giữa hè | đỉnh điểm mùa hè","midsummer | height of summer","1645500"),
    ("晩夏","ばんか","adv|n","cuối hè","late summer","1482130"),
    ("初秋","しょしゅう","n","đầu thu | chớm thu","early autumn","1342790"),
    ("晩秋","ばんしゅう","adv|n","cuối thu","late autumn","1482190"),
    ("初冬","しょとう","adv|n","đầu đông | chớm đông","early winter","1342940"),
    ("厳冬","げんとう","n","mùa đông khắc nghiệt | đông giá rét","severe winter","1262770"),
    ("酷暑","こくしょ","n","nắng nóng gay gắt | nóng khốc liệt","intense heat | severe heat","1287370"),
    ("厳寒","げんかん","n","giá rét | rét buốt | lạnh dữ dội","intense cold","1262580"),
    ("極寒","ごっかん","n|adj-no","cực lạnh | rét cắt da | giữa đông","extreme cold | midwinter","1240280"),
    ("寒波","かんぱ","n","đợt rét | đợt không khí lạnh","cold wave","1210520"),
    ("熱波","ねっぱ","n","đợt nắng nóng | sóng nhiệt","heat wave","1832310"),
    ("梅雨明け","つゆあけ","n|vs|vi","hết mùa mưa | kết thúc mùa mưa","end of the rainy season","1610440"),
    ("長雨","ながあめ","n","mưa dầm | mưa kéo dài","long spell of rain","1797640"),
    ("霜降り","しもふり","adj-no|n","lốm đốm trắng | thịt vân mỡ | trần qua nước sôi | đóng sương","speckled with white | marbling (of beef)","1402970"),
    ("雪解け","ゆきどけ","n","tuyết tan | tan băng | sự hòa dịu (quan hệ)","thawing of snow | thaw (in relations)","1386530"),
    ("春一番","はるいちばん","n","cơn gió đầu xuân | gió mạnh chuyển mùa xuân","first storm of spring","1341030"),
    ("木枯らし","こがらし","n","gió đông lạnh | gió bấc","cold wintry wind","1593140"),
    ("時雨","しぐれ","n","mưa rào cuối thu đầu đông | mưa thoáng theo mùa","rain shower in late autumn/early winter","1315880"),
    ("五月雨","さみだれ","n","mưa đầu hè | mưa rả rích đầu mùa hè","early-summer rain","1578560"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
