# -*- coding: utf-8 -*-
"""Build N2 ready wave 033 — emotions: joy, sorrow, anger, resentment, love, fear, composure."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-033.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("歓喜","かんき","n|vs|vi","hân hoan | vui mừng khôn xiết | hoan hỉ","delight | great joy","1212950"),
    ("喜悦","きえつ","n|vs|vt|vi","niềm vui | hỉ duyệt | hân hoan","joy","1218780"),
    ("悦楽","えつらく","n|vs|vi","niềm vui thú | sự khoái lạc | lạc thú","joy | pleasure | delight","1175270"),
    ("愉悦","ゆえつ","n|vs|vi","sự vui thích | niềm hân hoan | thú vui","joy | pleasure | delight","1653260"),
    ("恍惚","こうこつ","n|adv-to|adj-t|adj-no","ngây ngất | xuất thần | mê mẩn | lú lẫn (tuổi già)","ecstasy | rapture | trance | senility","1566790"),
    ("陶酔","とうすい","n|vs|vi","ngây ngất | say mê | đắm chìm | mê đắm","intoxication | being enraptured","1450680"),
    ("満悦","まんえつ","n|vs|vi","hài lòng | vui sướng mãn nguyện","great delight | great satisfaction","1526740"),
    ("感慨","かんがい","n","xúc động sâu sắc | cảm khái | bồi hồi","deep emotion | strong feelings","1212310"),
    ("感無量","かんむりょう","n|adj-no|adj-na","xúc động khôn xiết | dâng trào cảm xúc","deep emotion | being filled with emotion","1212620"),
    ("郷愁","きょうしゅう","n","nỗi nhớ quê | hoài niệm | nhớ nhà","nostalgia | homesickness","1238500"),
    ("哀愁","あいしゅう","n","nỗi buồn man mác | u sầu | sầu muộn","pathos | sorrow | grief","1150260"),
    ("憂愁","ゆうしゅう","n","u sầu | sầu muộn | ưu phiền","melancholy | gloom | grief","1540830"),
    ("憂鬱","ゆううつ","n|adj-na","u uất | trầm uất | buồn bã | ủ rũ","depression | melancholy | gloom","1605640"),
    ("鬱","うつ","n|adj-t|adv-to","trầm cảm | u uất | rậm rạp (cây cối)","depression | low spirits | luxuriant","2036080"),
    ("憂い","うれい","n","nỗi buồn | u sầu | lo âu | phiền muộn","sorrow | grief | anxiety | misgivings","1540740"),
    ("悲嘆","ひたん","n|vs|vi","đau buồn | bi thương | than khóc","grief | sorrow | lamentation","1483310"),
    ("悲哀","ひあい","n","bi ai | buồn thương | sầu thảm","sorrow | grief | sadness","1483210"),
    ("慟哭","どうこく","n|vs|vi","khóc than | gào khóc | thống thiết","wailing | lamentation","1566920"),
    ("号泣","ごうきゅう","n|vs|vi","khóc rống | khóc nức nở | gào khóc","crying loudly | bawling | weeping","1284250"),
    ("落胆","らくたん","n|vs|vi","nản lòng | thất vọng | chán nản | nản chí","discouragement | despondency | disappointment","1548820"),
    ("絶望","ぜつぼう","n|vs|vi|adj-no","tuyệt vọng | vô vọng","despair | hopelessness","1386960"),
    ("自暴自棄","じぼうじき","adj-na|adj-no|n","buông xuôi | mặc kệ | tự bỏ mặc bản thân","desperation | self-abandonment","1318670"),
    ("自棄","やけ","n|adj-na","buông xuôi | chán đời | mặc kệ tất cả","desperation | despair | self-abandonment","1317520"),
    ("煩悶","はんもん","n|vs|vi","day dứt | trăn trở | khổ tâm","worry | agony","1481990"),
    ("苦渋","くじゅう","n|vs|vi|adj-no","cay đắng | khổ sở | đắng cay | dằn vặt","bitterness | distress | anguish","1244490"),
    ("懊悩","おうのう","n|vs|vi","khổ não | day dứt | dằn vặt","anguish | trouble | agony","1643700"),
    ("焦燥","しょうそう","n|vs|vi","sốt ruột | bồn chồn | nôn nóng | bứt rứt","impatience | irritation | frustration","1350800"),
    ("憤慨","ふんがい","n|vs|vt|vi","phẫn nộ | căm phẫn | bất bình","indignation | resentment","1504650"),
    ("憤怒","ふんぬ","n|adj-no|vs|vi","phẫn nộ | thịnh nộ | cơn giận dữ","anger | rage | indignation","1585730"),
    ("憤り","いきどおり","n","sự phẫn nộ | nỗi căm phẫn | sự bất bình","resentment | indignation | anger","1857970"),
    ("立腹","りっぷく","n|vs|vi","nổi giận | tức giận | phật ý","anger | getting angry | losing one's temper","1551800"),
    ("鬱憤","うっぷん","n","uất ức | nỗi bực dồn nén | hờn dỗi tích tụ","resentment | pent-up anger | frustration","1588300"),
    ("鬱屈","うっくつ","n|vs|vi","u uất | bức bối | ấm ức","gloomy | feeling depressed","1781280"),
    ("鬱積","うっせき","n|vs|vi","dồn nén | tích tụ (bất mãn) | ứ đọng (giận)","accumulation (of discontent) | suppression","1172490"),
    ("怨念","おんねん","n","oán hận | mối hận sâu | thù hận","deep-seated grudge | hatred","1176590"),
    ("遺恨","いこん","n","mối hận | hiềm khích | thù oán","grudge | ill will | enmity","1159230"),
    ("嫌悪","けんお","n|vs|vt","ghê tởm | ghét bỏ | ác cảm | chán ghét","disgust | hate | loathing","1257280"),
    ("反感","はんかん","n","ác cảm | phản cảm | thù địch | sự khó chịu","antipathy | animosity | ill feeling","1480260"),
    ("妬み","ねたみ","n","sự ganh ghét | lòng đố kỵ | ghen tị","jealousy | envy","1444370"),
    ("羨望","せんぼう","n|vs|vt","sự ngưỡng mộ | thèm muốn | ghen tị (ao ước)","envy","1391960"),
    ("自惚れ","うぬぼれ","n","sự tự phụ | tự cao | kiêu căng | ảo tưởng về mình","conceit | vanity | self-importance","1317730"),
    ("自負","じふ","n|vs|vi","tự hào | tự tin | tự phụ về tài năng","pride | self-confidence","1318600"),
    ("矜持","きょうじ","n","lòng tự tôn | niềm kiêu hãnh | phẩm giá","pride | dignity | self-respect","1640670"),
    ("慢心","まんしん","n|vs|vi","tự mãn | kiêu căng | tự cao","self-conceit | pride","1641050"),
    ("過信","かしん","n|vs|vt","tin tưởng thái quá | đánh giá quá cao","trusting too much | overestimating","1196210"),
    ("慎み","つつしみ","n","sự khiêm tốn | sự dè dặt | sự kiềm chế","modesty | self-control | discretion","1361090"),
    ("恐縮","きょうしゅく","n|vs|vi","ngại quá | áy náy | cảm kích | làm phiền","feeling obliged | feeling sorry | embarrassed","1236740"),
    ("戦慄","せんりつ","n|vs|vi","rùng mình | run sợ | kinh hãi","shudder | trembling with fear","1390690"),
    ("畏怖","いふ","n|vs|vt","sợ hãi | kính sợ | khiếp sợ","awe | fear | dread","1157470"),
    ("畏敬","いけい","n|vs|vt","kính nể | tôn kính | kính sợ","reverence | awe | respect","1157450"),
    ("崇敬","すうけい","n|vs|vt","sùng kính | tôn kính | sùng bái","reverence","1372850"),
    ("敬愛","けいあい","n|vs|vt","kính yêu | kính mến","respect and affection","1250710"),
    ("敬慕","けいぼ","n|vs|vt","kính mến | ngưỡng mộ và kính trọng","love and respect","1250780"),
    ("親愛","しんあい","n|adj-na","thân ái | thương yêu | thân mến","deep affection | dear | beloved","1365090"),
    ("情け","なさけ","n","lòng thương | sự cảm thông | tình nghĩa | tình cảm","pity | sympathy | compassion | affection","1356220"),
    ("哀れみ","あわれみ","n|adj-no","lòng thương hại | niềm trắc ẩn | sự thương cảm","pity | compassion","1150130"),
    ("憐憫","れんびん","n","lòng thương xót | sự trắc ẩn | lòng từ bi","pity | compassion | mercy","1608740"),
    ("感応","かんのう","n|vs|vi|adj-no","cảm ứng | đồng cảm | nhạy cảm | cảm ứng (điện từ)","responsiveness | sympathy | induction","1212290"),
    ("琴線","きんせん","n","dây tơ lòng | sợi dây cảm xúc | dây đàn koto","heartstrings | koto string","1241460"),
    ("情念","じょうねん","n","tình cảm | xúc cảm | đam mê","sentiments | passions","1356340"),
    ("情愛","じょうあい","n","tình thương | tình cảm | tình ái","affection | love","1356230"),
    ("愛着","あいちゃく","n|vs|vi","sự gắn bó | quyến luyến | yêu thích","attachment | affection | fondness","1575680"),
    ("未練","みれん","n|adj-na","sự luyến tiếc | còn vương vấn | tiếc nuối | dùng dằng","lingering attachment | regret | reluctance","1528130"),
    ("心残り","こころのこり","n|adj-na","điều luyến tiếc | sự áy náy | tiếc nuối","regret | reluctance","1360690"),
    ("照れ","てれ","n","sự ngượng ngùng | bẽn lẽn | thẹn thùng","abashment | bashfulness","2827422"),
    ("羞恥","しゅうち","n","sự xấu hổ | ngượng ngùng | hổ thẹn","shyness | bashfulness | shame","1570630"),
    ("赤面","せきめん","n|vs|vi","đỏ mặt | thẹn đỏ mặt | mắc cỡ","blushing | embarrassment","1383620"),
    ("超然","ちょうぜん","adj-t|adv-to","siêu thoát | điềm nhiên | bất chấp | dửng dưng","detached | aloof | indifferent","1742480"),
    ("淡々","たんたん","adj-t|adv-to","điềm đạm | thản nhiên | nhạt | nhẹ nhàng","unconcerned | dispassionate | detached | plain","1597270"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
