# -*- coding: utf-8 -*-
"""Build N2 ready wave 049 — housing, rooms, building parts, furniture, fixtures, heating."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-049.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("住居","じゅうきょ","n|vs|vi","nơi ở | nhà ở | chỗ cư trú | địa chỉ","dwelling | residence | address","2841455"),
    ("邸宅","ていたく","n","dinh thự | biệt thự | nhà lớn","(large) house | residence | mansion","1436820"),
    ("民家","みんか","n","nhà dân | nhà tư nhân","private house","1528620"),
    ("古民家","こみんか","n","nhà cổ kiểu Nhật","old Japanese-style house","2799500"),
    ("一軒家","いっけんや","n","nhà riêng | nhà biệt lập | nhà đơn lập","detached house | isolated house","1587440"),
    ("長屋","ながや","n","nhà tập thể dãy dài | dãy nhà liền kề","tenement house | row house","1797650"),
    ("二階建て","にかいだて","n","nhà hai tầng","two-storied building","1599800"),
    ("戸建て","こだて","n","nhà riêng | nhà đơn lập","(separate) house | detached house","2116120"),
    ("持ち家","もちいえ","n","nhà thuộc sở hữu | nhà của mình","one's (own) house","1658400"),
    ("借家","しゃくや","n","nhà thuê | nhà đi thuê","rented house | house for rent","1579690"),
    ("貸家","かしや","n","nhà cho thuê","house for rent","1411170"),
    ("空き部屋","あきべや","n","phòng trống | phòng còn trống (khách sạn)","available room | vacancy","1245350"),
    ("土間","どま","n","nền đất | gian nền đất | khu ghế ngồi (sân khấu)","dirt floor | room with dirt floor","1445300"),
    ("踊り場","おどりば","n","sàn nhảy | chiếu nghỉ cầu thang | giai đoạn chững lại","dance floor | landing (of a staircase) | plateau","1546910"),
    ("吹き抜け","ふきぬけ","n|adj-f|adj-no","giếng trời | khoảng thông tầng | lộng gió","atrium | well (in building) | drafty","1713520"),
    ("床下","ゆかした","n|adj-no","gầm sàn | dưới sàn nhà","under the floor","1349420"),
    ("床の間","とこのま","n","hốc tường trang trí | tokonoma (trưng tranh, hoa)","tokonoma | display alcove","1349400"),
    ("襖","ふすま","n","cửa kéo giấy | vách ngăn kéo (fusuma)","fusuma | Japanese sliding screen","1181720"),
    ("雨戸","あまど","n","cửa chống bão | cửa lùa chắn mưa","sliding storm shutter","1171970"),
    ("軒","のき","n","mái hiên | rìa mái nhà","eaves","1260330"),
    ("軒先","のきさき","n","đầu hiên | rìa hiên | mặt tiền nhà","edge of the eaves | house frontage","1260370"),
    ("庇","ひさし","n","mái che | mái hiên | lưỡi trai (mũ)","awning | eaves | visor (of a cap)","2057300"),
    ("屋上","おくじょう","n","sân thượng | mái nhà bằng","rooftop","1182710"),
    ("書斎","しょさい","n","phòng đọc sách | thư phòng | phòng làm việc tại nhà","study | library | home office","1344030"),
    ("客間","きゃくま","n","phòng khách | phòng tiếp khách","drawing room | parlour | guest room","1226710"),
    ("茶の間","ちゃのま","n","phòng sinh hoạt chung (kiểu Nhật) | gian khách","(Japanese-style) living room","1422600"),
    ("納戸","なんど","n","kho chứa đồ | phòng kho | tủ chứa","storage room | storeroom | closet","1642650"),
    ("食器棚","しょっきだな","n","tủ bát đĩa | tủ chén","cupboard | sideboard","1660270"),
    ("本棚","ほんだな","n","kệ sách | giá sách | tủ sách","bookshelf | bookcase","1522980"),
    ("靴箱","くつばこ","n","tủ giày | kệ giày","shoe box | shoe shelf","2029430"),
    ("下駄箱","げたばこ","n","tủ giày dép (ở lối vào)","shoe rack (at an entrance)","1185830"),
    ("箪笥","たんす","n","tủ ngăn kéo | tủ áo | tủ commốt","chest of drawers | bureau | tansu","1418990"),
    ("座卓","ざたく","n","bàn thấp (ngồi bệt)","low table","1842720"),
    ("座布団","ざぶとん","n","đệm ngồi | gối ngồi (zabuton)","zabuton | flat floor cushion","1291980"),
    ("カーペット","カーペット","n","thảm | thảm trải sàn","carpet","1036580"),
    ("暖簾","のれん","n","rèm cửa hàng | rèm ngăn phòng | uy tín cửa tiệm","curtain hung at shop entrance | goodwill","1419890"),
    ("御簾","みす","n","rèm tre | mành tre","bamboo blind","1694940"),
    ("屏風","びょうぶ","n","bình phong | tấm chắn gấp","folding screen","1566400"),
    ("衝立","ついたて","n","tấm chắn ngăn | bình phong chắn","partitioning screen","1597740"),
    ("間仕切り","まじきり","n","vách ngăn phòng | tấm ngăn chia phòng","partition between rooms | room divider","1950660"),
    ("壁紙","かべがみ","n","giấy dán tường | hình nền (máy tính)","wallpaper | background image","1509330"),
    ("梁","はり","n","xà nhà | dầm | đòn tay","beam | joist","1648740"),
    ("鉄骨","てっこつ","n","khung thép | dầm thép | xà thép","steel frame | steel beam","1437890"),
    ("木造","もくぞう","adj-no|n","làm bằng gỗ | kết cấu gỗ | nhà gỗ","wooden | wooden construction","1534740"),
    ("石造","せきぞう","n|adj-no","làm bằng đá | kết cấu đá","stone construction | (made of) stone","1621230"),
    ("瓦","かわら","n","ngói | ngói lợp","tile (e.g. roof)","1209580"),
    ("漆喰","しっくい","n","vữa | hồ trát | thạch cao trát","mortar | plaster | stucco","1320550"),
    ("床板","ゆかいた","n","ván sàn | tấm lát sàn","floorboard","1349430"),
    ("天井板","てんじょういた","n","ván trần | tấm ốp trần","ceiling boards","1438390"),
    ("合板","ごうはん","n","ván ép | gỗ dán","veneer board | plywood","1578960"),
    ("角材","かくざい","n","gỗ vuông | thanh gỗ hộp","squared timber | rectangular lumber","1206150"),
    ("丸太","まるた","n","khúc gỗ tròn | cây gỗ tròn","log","1216560"),
    ("木材","もくざい","n","gỗ | vật liệu gỗ","lumber | timber | wood","1534660"),
    ("建材","けんざい","n","vật liệu xây dựng","building material","1257400"),
    ("建具","たてぐ","n","đồ mở đóng (cửa, cửa sổ, shoji) | đồ lắp ráp cố định","fittings (doors, windows) | fixtures","1257370"),
    ("扉","とびら","n","cánh cửa | cổng | trang bìa lót","door | gate | title page","1483380"),
    ("窓枠","まどわく","n","khung cửa sổ","window frame | sash","1401460"),
    ("網戸","あみど","n","cửa lưới | cửa chắn côn trùng | cửa chống muỗi","window screen | screen door","1534390"),
    ("排水溝","はいすいこう","n","rãnh thoát nước | mương thoát nước","drainage | gutter | ditch","1472390"),
    ("下水道","げすいどう","n","cống thoát nước | hệ thống thoát nước thải","sewer | sewer system","1185540"),
    ("浄化槽","じょうかそう","n","bể tự hoại | bể lọc nước thải","water-purification tank | septic tank","1635470"),
    ("給湯","きゅうとう","n|vs|vt|vi","cung cấp nước nóng","hot-water supply","1230300"),
    ("温水","おんすい","n|adj-no","nước ấm | nước nóng","warm water","1183440"),
    ("冷水","れいすい","n","nước lạnh","cold water","1557020"),
    ("湯沸かし器","ゆわかしき","n","máy đun nước nóng | bình nóng lạnh","water heater | water boiler","1448680"),
    ("換気扇","かんきせん","n","quạt thông gió | quạt hút","ventilation fan | extractor fan","1212790"),
    ("通気口","つうきこう","n","lỗ thông gió | khe thông khí","air vent","2837529"),
    ("煙突","えんとつ","n","ống khói | ống xả khói","chimney | smokestack | funnel (of a ship)","1177320"),
    ("囲炉裏","いろり","n","bếp lò âm sàn | lò sưởi âm sàn","sunken hearth | sunken fireplace","1156000"),
    ("火鉢","ひばち","n","lò sưởi than | hỏa lò (hibachi)","brazier | hibachi","1194210"),
    ("炬燵","こたつ","n","kotatsu | bàn sưởi có chăn phủ","kotatsu | heated table with a quilt","1194360"),
    ("扇風機","せんぷうき","n","quạt điện","electric fan","1390760"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
