# -*- coding: utf-8 -*-
"""Build N3 ready wave 061 — 98 freshly-curated N3 compound verbs + na-adjectives."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-061.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("受け止める","うけとめる","v1|vt","đỡ | chặn | tiếp nhận | đối mặt với","to catch | to stop (a blow) | to accept | to come to grips with","1329630"),
    ("押し寄せる","おしよせる","v1|vi","ùa tới | tràn tới | dồn đến","to advance on | to surge forward | to inundate","1180190"),
    ("押し付ける","おしつける","v1|vt","ấn vào | ép buộc | áp đặt | đùn đẩy","to press against | to force on | to impose","1180360"),
    ("突き止める","つきとめる","v1|vt","truy ra | xác định | tìm ra (thủ phạm, nguyên nhân)","to determine | to pin down | to ascertain | to locate","1456670"),
    ("引っ込む","ひっこむ","v5m|vi","thụt vào | rút lui | ở ẩn | lõm vào","to draw back | to withdraw | to retire to | to cave in","1169390"),
    ("引っ掛ける","ひっかける","v1|vt","móc | mắc | gài bẫy | lừa | khoác (áo)","to hang on | to hook | to trap | to cheat | to throw on (clothes)","1169360"),
    ("振り回す","ふりまわす","v5s|vt","vung | khua | khoe khoang | lạm dụng | thao túng","to wield | to brandish | to show off | to abuse (power) | to manipulate","1361170"),
    ("見破る","みやぶる","v5r|vt","nhìn thấu | nhận ra (mưu mô) | vạch trần","to see through | to penetrate | to find out","1604720"),
    ("取り扱う","とりあつかう","v5u|vt","xử lý | sử dụng | đối xử | kinh doanh (bán)","to handle | to operate | to deal with | to treat | to sell","1326540"),
    ("取り返す","とりかえす","v5s|vt","lấy lại | giành lại | bù lại","to get back | to regain | to make up (for)","1326930"),
    ("仕込む","しこむ","v5m|vt","rèn dạy | nhồi nhét | nhập (hàng) | ủ (rượu) | lắp vào","to train | to teach | to stock | to prepare (ingredients) | to insert","1304940"),
    ("言い返す","いいかえす","v5s|vt","đáp trả | cãi lại | nhắc lại","to talk back | to retort | to repeat (what one said)","1264290"),
    ("食い止める","くいとめる","v1|vt","ngăn chặn | chặn đứng | kìm hãm","to check | to hold back | to stop | to curb","1358210"),
    ("食い違う","くいちがう","v5u|vi","lệch nhau | không khớp | trái ngược","to not match | to differ | to clash | to be inconsistent","1358110"),
    ("横たわる","よこたわる","v5r|vi","nằm | nằm dài | (hiểm nguy) chực chờ phía trước","to lie down | to stretch out | to lie ahead (of danger)","1180590"),
    ("屈む","かがむ","v5m|vi","cúi | khom | gập người | ngồi xổm","to stoop | to bend forward | to crouch | to squat","1246550"),
    ("しゃがむ","しゃがむ","v5m|vi","ngồi xổm | ngồi thụp","to squat | to crouch","1005630"),
    ("ぶら下がる","ぶらさがる","v5r|vi","treo lủng lẳng | đung đưa | trong tầm tay","to hang down | to dangle | to be within one's reach","1011240"),
    ("ぶら下げる","ぶらさげる","v1|vt","treo | đeo | xách | đung đưa","to hang | to suspend | to dangle | to carry","1011250"),
    ("ふらつく","ふらつく","v5k|vi","loạng choạng | choáng váng | lung lay | lang thang","to feel giddy | to totter | to waver | to wander aimlessly","2009600"),
    ("だらける","だらける","v1|vi","uể oải | lười nhác | rệu rã | uể oải","to be lazy | to be slack | to feel languid","1007490"),
    ("取り囲む","とりかこむ","v5m|vt","vây quanh | bao quanh | bao vây","to surround | to crowd around | to encircle","1326550"),
    ("立ち去る","たちさる","v5r|vi","bỏ đi | rời đi | rời khỏi","to leave | to depart | to take one's leave","1551310"),
    ("立ち尽くす","たちつくす","v5s|vi","đứng chôn chân | đứng lặng","to keep standing | to stand motionless","1852180"),
    ("踏み込む","ふみこむ","v5m|vt","bước vào | xông vào | đột nhập | đi sâu vào","to step into | to break into | to come to grips with","1450150"),
    ("踏みつける","ふみつける","v1|vt","giẫm đạp | chà đạp | coi thường","to trample down | to tread on | to spurn","1602860"),
    ("蹴飛ばす","けとばす","v5s|vt","đá văng | đá mạnh | cự tuyệt thẳng","to kick (hard) | to send flying | to reject flatly","1333440"),
    ("殴り合う","なぐりあう","v5u|vi","ẩu đả | đánh nhau | đấm nhau","to exchange blows | to punch each other | to fight","1181340"),
    ("叩きつける","たたきつける","v1|vt","quăng mạnh | đập vào | ném phịch","to throw violently against | to slam against | to dash","1416140"),
    ("抱きしめる","だきしめる","v1|vt","ôm chặt | ghì chặt | siết vào lòng","to hug tight | to embrace | to cuddle","1516320"),
    ("抱え込む","かかえこむ","v5m|vt","ôm khư khư | ôm đồm | gánh vác | ôm vào lòng","to hold in one's arms | to take upon oneself | to be saddled with","1633980"),
    ("担ぎ込む","かつぎこむ","v5m|vt","khiêng vào | đưa vào (người bị thương)","to carry into | to take into (e.g. a hospital)","1850560"),
    ("運び込む","はこびこむ","v5m|vt","mang vào | chuyển vào | đưa vào","to carry in | to bring in","1172640"),
    ("詰め寄る","つめよる","v5r|vi","áp sát | dồn ép | gặng hỏi","to draw near | to press (for an answer) | to hound","1226530"),
    ("歩み寄る","あゆみよる","v5r|vi","nhượng bộ | gặp nhau ở giữa | bước lại gần","to compromise | to meet halfway | to approach","1514340"),
    ("近寄せる","ちかよせる","v1|vt","kéo lại gần | đưa lại gần | kết giao","to bring close | to associate with | to let come close","1610300"),
    ("押しのける","おしのける","v1|vt","gạt ra | đẩy sang bên | hất ra","to push aside | to brush aside","1180280"),
    ("すり抜ける","すりぬける","v1|vi","lách qua | luồn lách | né tránh","to slip through | to weave through | to elude","1298880"),
    ("通り抜ける","とおりぬける","v1|vi","đi xuyên qua | luồn qua | băng qua","to go through | to pass through | to cut across","1433010"),
    ("行き交う","ゆきかう","v5u|vi","qua lại | đi lại | ngược xuôi","to come and go | to go back and forth","1281700"),
    ("行き届く","いきとどく","v5k|vi","chu đáo | tỉ mỉ | kỹ lưỡng | toàn diện","to be scrupulous | to be attentive | to be thorough","1281750"),
    ("立ち会う","たちあう","v5u|vi","có mặt | chứng kiến | tham gia (giám sát)","to be present | to be witness to | to attend","1551270"),
    ("付き添う","つきそう","v5u|vi","đi kèm | tháp tùng | chăm sóc bên cạnh","to attend on | to accompany | to escort | to chaperone","1495700"),
    ("寄り添う","よりそう","v5u|vi","kề bên | nép sát | sát cánh","to get close | to nestle close to | to snuggle up to","1219640"),
    ("連れ添う","つれそう","v5u|vi","thành đôi | nên duyên vợ chồng | kết tóc","to become a couple | to be man and wife","1559340"),
    ("言い寄る","いいよる","v5r|vi","tán tỉnh | ve vãn | gạ gẫm","to court | to woo | to make advances","1264000"),
    ("飛び交う","とびかう","v5u|vi","bay lượn (qua lại) | bay tới tấp | lan truyền","to fly about | to flutter about | to fly past each other","1485310"),
    ("舞い上がる","まいあがる","v5r|vi","bay bổng | cuốn lên cao | phấn khích","to soar | to be whirled up | to be in high spirits","1499080"),
    ("舞い込む","まいこむ","v5m|vi","bay lọt vào | bất ngờ ghé đến | đến bất ngờ","to come fluttering in | to drop in unexpectedly","1499070"),
    ("転がり込む","ころがりこむ","v5m|vi","lăn vào | tá túc nhờ | từ trên trời rơi xuống","to roll in | to come to live with | to fall into one's lap","1440990"),
    ("割り当てる","わりあてる","v1|vt","phân bổ | giao | chia phần | phân công","to assign | to allot | to allocate | to apportion","1207880"),
    ("振り分ける","ふりわける","v1|vt","chia làm hai | phân chia | phân bổ","to divide in two | to apportion | to distribute","1361280"),
    ("切り分ける","きりわける","v1|vt","cắt chia | chia nhỏ | phân tách (vấn đề)","to cut up | to carve | to distinguish (facets)","1384660"),
    ("仕分ける","しわける","v1|vt","phân loại | sắp xếp | hạch toán","to assort | to classify | to journalize (accounting)","1595110"),
    ("選び出す","えらびだす","v5s|vt","chọn lọc | chọn ra | tuyển ra","to select | to pick out","1392150"),
    ("拾い上げる","ひろいあげる","v1|vt","nhặt lên | chọn ra | nêu ra (điểm chính)","to pick up | to pick out (key points) | to single out","1332550"),
    ("探し出す","さがしだす","v5s|vt","tìm ra | lần ra | truy tìm","to track down | to locate | to find out","1418220"),
    ("見つけ出す","みつけだす","v5s|vt","tìm thấy | phát hiện | tìm ra","to find out | to discover | to locate","1634270"),
    ("作り出す","つくりだす","v5s|vt","tạo ra | sản xuất | sáng tạo ra","to manufacture | to produce | to invent | to create","1297300"),
    ("生み出す","うみだす","v5s|vt","tạo ra | sản sinh | sáng tạo | sinh ra","to create | to bring forth | to produce | to give birth to","1378720"),
    ("編み出す","あみだす","v5s|vt","nghĩ ra | sáng chế | tìm ra (cách)","to think up | to devise | to invent | to work out","1511910"),
    ("描き出す","えがきだす","v5s|vt","khắc họa | vẽ ra | thể hiện | hình dung","to delineate | to draw | to express | to imagine","1490110"),
    ("打ち出す","うちだす","v5s|vt","đề ra | nêu ra | dập nổi | in ra","to set forth | to work out (a policy) | to emboss | to print","1408670"),
    ("押し出す","おしだす","v5s|vt|vi","đẩy ra | ép ra | làm nổi bật","to push out | to squeeze out | to highlight","1589160"),
    ("送り出す","おくりだす","v5s|vt","tiễn đi | gửi đi | đưa tiễn","to send out | to forward | to show (a person) out","1402680"),
    ("追い出す","おいだす","v5s|vt","đuổi ra | tống cổ | xua đuổi","to expel | to drive out","1432350"),
    ("追い払う","おいはらう","v5u|vt","xua đuổi | đuổi đi | giải tán","to drive away | to scatter | to disperse","1432380"),
    ("払いのける","はらいのける","v1|vt","gạt phăng | hất đi | xua đi","to ward off | to brush away | to drive away","1501590"),
    ("取り除ける","とりのける","v1|vt","dẹp bỏ | dọn đi | gạt sang một bên | ngoại trừ","to remove | to clear away | to set aside | to except","2835033"),
    ("厄介","やっかい","adj-na|n","phiền phức | rắc rối | gánh nặng | nhờ vả","trouble | burden | nuisance | dependence","1537820"),
    ("簡素","かんそ","adj-na|n","giản dị | đơn sơ | mộc mạc","simple | plain | modest","1214300"),
    ("簡潔","かんけつ","adj-na","ngắn gọn | súc tích | cô đọng","concise | brief | succinct","1214290"),
    ("入念","にゅうねん","adj-na|n","kỹ lưỡng | tỉ mỉ | cẩn thận","careful | elaborate | scrupulous","1466670"),
    ("大雑把","おおざっぱ","adj-na","đại khái | sơ sài | qua loa | cẩu thả","rough (estimate) | sweeping | careless | sloppy","1412950"),
    ("粗末","そまつ","adj-na|n","sơ sài | thô sơ | đạm bạc | tồi","crude | rough | plain | shabby | poor-quality","1397100"),
    ("雑","ざつ","adj-na|n","cẩu thả | qua loa | lộn xộn | linh tinh","rough | crude | sloppy | messy | miscellaneous","1299240"),
    ("大まか","おおまか","adj-na","đại khái | khái quát | rộng rãi","rough (outline) | broad | general | generous","1412980"),
    ("些細","ささい","adj-na","nhỏ nhặt | vụn vặt | không đáng kể","trivial | trifling | slight | insignificant","1290680"),
    ("重大","じゅうだい","adj-na|n","trọng đại | nghiêm trọng | quan trọng","serious | important | significant | grave","1336500"),
    ("身近","みぢか","adj-na|n","gần gũi | thân thuộc | sát bên mình","near oneself | close to one | familiar","1365650"),
    ("手軽","てがる","adj-na|n","dễ dàng | đơn giản | tiện lợi | rẻ","easy | simple | informal | cheap","1327530"),
    ("気軽","きがる","adj-na|n","thoải mái | vô tư | nhẹ nhõm | dễ dàng","carefree | lighthearted | with ease","1222110"),
    ("身軽","みがる","adj-na","nhanh nhẹn | linh hoạt | gọn nhẹ | thảnh thơi","agile | nimble | light (luggage) | carefree","1611690"),
    ("小柄","こがら","adj-na|n","nhỏ con | vóc người nhỏ | họa tiết nhỏ","small build | small stature | petite | small pattern","1348770"),
    ("小規模","しょうきぼ","adj-na|n","quy mô nhỏ","small scale","1347920"),
    ("小幅","こはば","adj-na|n","nhỏ | hẹp | (biến động) nhỏ","small | narrow","1639860"),
    ("僅少","きんしょう","adj-no|adj-na|n","ít ỏi | nhỏ nhặt | sít sao","a little | slight | trifling | narrow (margin)","1240770"),
    ("多大","ただい","adj-na|adj-no|n","to lớn | rất nhiều | đáng kể","great (quantity) | huge | enormous","1407900"),
    ("甚大","じんだい","adj-na|n","to lớn | nặng nề | nghiêm trọng","very great | enormous | serious","1370040"),
    ("重厚","じゅうこう","adj-na|n","sâu sắc | bề thế | trang trọng | vững chãi","profound | grave | dignified | stately | substantial","1579950"),
    ("軽薄","けいはく","adj-na|n","nông cạn | hời hợt | bồng bột | thiếu chân thành","frivolous | superficial | shallow | insincere","1252830"),
    ("浅はか","あさはか","adj-na","nông cạn | thiển cận | thiếu suy nghĩ | dại dột","shallow | thoughtless | short-sighted | foolish","1609030"),
    ("身勝手","みがって","adj-na|n","ích kỷ | chỉ nghĩ cho mình | tự cho mình","selfish | self-centred | egotistical","1641560"),
    ("自分勝手","じぶんかって","n|adj-na","ích kỷ | tùy tiện | tự ý làm theo ý mình","selfishness | self-centered | (doing) as one pleases","1318630"),
    ("軽率","けいそつ","adj-na|n","khinh suất | hấp tấp | thiếu thận trọng","rash | thoughtless | careless | imprudent","1252910"),
    ("無謀","むぼう","adj-na|n","liều lĩnh | thiếu suy nghĩ | mạo hiểm","reckless | thoughtless | rash | ill-advised","1530880"),
    ("無茶","むちゃ","adj-na|n","vô lý | quá đáng | liều | thái quá","absurd | unreasonable | reckless | excessive","1530670"),
    ("無理","むり","adj-na|n|vs","vô lý | không thể | gượng ép | quá sức","unreasonable | impossible | forced | excessive","1530970"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
