# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-035.csv -- 43 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-035.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("言い聞かせる","いいきかせる","N4","v1|vt",
        "nói để thuyết phục | giảng giải | khuyên bảo | cảnh cáo",
        "to tell | to (try to) persuade | to advise | to warn | to admonish | to reason",
        "1264280",
        "子供に言い聞かせる。","こどもにいいきかせる。",
        "Nói để thuyết phục đứa trẻ.","Persuade the child."),
    row("語りかける","かたりかける","N4","v1",
        "diễn thuyết | nói chuyện với | lên tiếng với",
        "to make a speech | to address",
        "2010900",
        "観衆に語りかける。","かんしゅうにかたりかける。",
        "Diễn thuyết với khán giả.","Address the audience."),
    row("源泉徴収","げんせんちょうしゅう","N4","n|adj-no",
        "khấu trừ thuế tại nguồn | thu thuế tại gốc",
        "tax withholding at the source",
        "1666250",
        "源泉徴収票をもらった。","げんせんちょうしゅうひょうをもらった。",
        "Tôi nhận được phiếu khấu trừ thuế.","I received the withholding tax slip."),
    row("溢れる","あふれる","N4","v1|vi",
        "tràn ra | đầy tràn | ngập tràn",
        "to overflow | to brim over | to flood",
        "1167610",
        "川が溢れる。","かわがあふれる。",
        "Sông tràn bờ.","The river overflows."),
    row("物静か","ものしずか","N4","adj-na|n",
        "yên tĩnh | lặng lẽ | điềm tĩnh",
        "quiet | still | calm",
        "1615950",
        "物静かな人。","ものしずかなひと。",
        "Người yên lặng.","A quiet person."),
    row("生真面目","きまじめ","N4","adj-na|n",
        "quá nghiêm túc | thành tâm sâu sắc | cần mẫn thái quá",
        "overserious | deeply sincere | very earnest",
        "1379150",
        "生真面目な性格。","きまじめなせいかく。",
        "Tính cách quá nghiêm túc.","An overserious personality."),
    row("確定申告","かくていしんこく","N4","n",
        "quyết toán thuế thu nhập | khai thuế cuối năm",
        "final income tax return | final declaration | final report",
        "1819560",
        "確定申告の季節です。","かくていしんこくのきせつです。",
        "Đây là mùa khai thuế cuối năm.","It is tax return season."),
    row("給与明細","きゅうよめいさい","N4","n",
        "phiếu lương | sao kê lương",
        "payslip",
        "2235270",
        "給与明細を確認する。","きゅうよめいさいをかくにんする。",
        "Xác nhận phiếu lương.","Check the payslip."),
    row("色味","いろみ","N4","n",
        "sắc thái màu | tông màu | màu sắc",
        "shade | tone | tinge | hue | colour | color | tint",
        "2662670",
        "色味が異なる。","いろみがことなる。",
        "Sắc thái màu khác nhau.","The shade is different."),
    row("色調","しきちょう","N4","n",
        "tông màu | điệu màu | phối màu",
        "color tone | colour tone",
        "1357860",
        "色調が暖かい。","しきちょうがあたたかい。",
        "Tông màu ấm áp.","The color tone is warm."),
    row("艶","えん","N4","adj-na|n",
        "quyến rũ | mê hoặc | gợi cảm",
        "charming | fascinating | voluptuous",
        "1615260",
        "艶な仕草。","えんなしぐさ。",
        "Cử chỉ quyến rũ.","A charming gesture."),
    row("透明","とうめい","N4","adj-na|adj-no|n",
        "trong suốt | rõ ràng",
        "transparent | clear",
        "1450590",
        "透明なガラス。","とうめいながらす。",
        "Kính trong suốt.","Transparent glass."),
    row("零れる","こぼれる","N4","v1|vi",
        "đổ ra | rơi ra | tràn ra | hé lộ | thoát ra",
        "to spill | to fall out of | to overflow | to peek through | to become visible (although normally not) | to escape (of a smile, tear, etc.)",
        "1557650",
        "コーヒーが零れる。","こーひーがこぼれる。",
        "Cà phê đổ ra.","Coffee spills."),
    row("飛びつく","とびつく","N4","v5k|vi",
        "nhảy lên | lao vào | phóng vào | nhảy bổ vào",
        "to jump at | to leap at | to fly at | to spring at | to pounce on",
        "1485400",
        "チャンスに飛びつく。","ちゃんすにとびつく。",
        "Nhảy vào cơ hội.","Jump at the chance."),
    row("鼻孔","びこう","N4","n",
        "lỗ mũi | hốc mũi",
        "nostril | naris",
        "1486960",
        "鼻孔が広い。","びこうがひろい。",
        "Lỗ mũi to.","Wide nostrils."),
    row("中華料理","ちゅうかりょうり","N4","n",
        "món ăn Trung Hoa | ẩm thực Trung Quốc",
        "Chinese cooking | Chinese food",
        "1423600",
        "中華料理が好きです。","ちゅうかりょうりがすきです。",
        "Tôi thích món ăn Trung Hoa.","I like Chinese food."),
    row("主食","しゅしょく","N4","n",
        "thức ăn chính | lương thực chủ yếu",
        "staple food",
        "1325640",
        "米が主食です。","こめがしゅしょくです。",
        "Gạo là thức ăn chính.","Rice is the staple food."),
    row("体育祭","たいいくさい","N4","n",
        "lễ hội thể thao trường | ngày hội thể thao",
        "(school) athletic festival | sports day | field day",
        "1941700",
        "体育祭に参加した。","たいいくさいにさんかした。",
        "Tôi đã tham gia lễ hội thể thao trường.","I participated in sports day."),
    row("作業療法士","さぎょうりょうほうし","N4","n",
        "nhà trị liệu nghề nghiệp | chuyên gia hoạt động trị liệu",
        "occupational therapist",
        "2445740",
        "作業療法士に相談した。","さぎょうりょうほうしにそうだんした。",
        "Tôi tư vấn với nhà trị liệu nghề nghiệp.","I consulted an occupational therapist."),
    row("初雪","はつゆき","N4","n",
        "tuyết đầu mùa | tuyết đầu tiên trong mùa",
        "first snow (of the season) | first snowfall",
        "1342870",
        "今年の初雪が降った。","ことしのはつゆきがふった。",
        "Tuyết đầu mùa năm nay đã rơi.","This year's first snow fell."),
    row("副食","ふくしょく","N4","n",
        "món phụ | đồ ăn kèm | thức ăn bổ sung",
        "side dish | supplementary food",
        "1500550",
        "副食をいろいろ用意した。","ふくしょくをいろいろようい した。",
        "Tôi chuẩn bị nhiều món phụ.","I prepared various side dishes."),
    row("夜食","やしょく","N4","n",
        "bữa tối | bữa khuya | đồ ăn đêm khuya",
        "supper | night meal | late-night snack | midnight snack",
        "1536850",
        "夜食を食べる。","やしょくをたべる。",
        "Ăn đồ ăn đêm.","Eat a late-night snack."),
    row("始業式","しぎょうしき","N4","n",
        "lễ khai giảng học kỳ | lễ mở đầu học kỳ",
        "opening ceremony (of the school term)",
        "1656620",
        "始業式が行われた。","しぎょうしきがおこなわれた。",
        "Lễ khai giảng học kỳ đã diễn ra.","The opening ceremony was held."),
    row("学芸会","がくげいかい","N4","n",
        "hội diễn nghệ thuật trường học | liên hoan văn nghệ trường",
        "school arts festival",
        "1761140",
        "学芸会で演技した。","がくげいかいでえんぎした。",
        "Tôi đã biểu diễn tại hội diễn nghệ thuật trường.","I performed at the school arts festival."),
    row("建築士","けんちくし","N4","n",
        "kiến trúc sư có chứng chỉ | nhà kiến trúc được cấp phép",
        "authorized architect and builder | licensed architect | registered architect",
        "1714320",
        "建築士の資格を持つ。","けんちくしのしかくをもつ。",
        "Có bằng kiến trúc sư.","Have an architect's license."),
    row("押し込む","おしこむ","N4","v5m|vi|vt",
        "nhét vào | nhồi vào | chen vào | đột nhập vào | cướp nhà",
        "to push into | to cram into | to stuff into | to crowd into | to break in | to burgle",
        "1180260",
        "荷物を押し込む。","にもつをおしこむ。",
        "Nhồi hành lý vào.","Cram luggage in."),
    row("検察官","けんさつかん","N4","n",
        "công tố viên | kiểm sát viên",
        "public prosecutor",
        "1630740",
        "検察官が起訴した。","けんさつかんがきそした。",
        "Công tố viên đã khởi tố.","The prosecutor filed charges."),
    row("氷雨","ひさめ","N4","n",
        "mưa đá | mưa lạnh | mưa đóng băng | mưa tuyết",
        "hail | sleet | chilly rain | freezing rain",
        "1488860",
        "氷雨が降った。","ひさめがふった。",
        "Mưa đá đã rơi.","Hail fell."),
    row("汁物","しるもの","N4","n",
        "súp | canh | món nước",
        "soup",
        "1768750",
        "汁物を作ります。","しるものをつくります。",
        "Tôi nấu súp.","I make soup."),
    row("理学療法士","りがくりょうほうし","N4","n",
        "nhà vật lý trị liệu | chuyên gia vật lý trị liệu",
        "physiotherapist | physical therapist",
        "2001720",
        "理学療法士に診てもらった。","りがくりょうほうしにみてもらった。",
        "Tôi được nhà vật lý trị liệu khám.","I was examined by a physiotherapist."),
    row("終業式","しゅうぎょうしき","N4","n",
        "lễ bế giảng học kỳ | lễ kết thúc học kỳ",
        "ceremony held at the end of a school term | end-of-term ceremony",
        "1698300",
        "終業式が終わった。","しゅうぎょうしきがおわった。",
        "Lễ bế giảng học kỳ đã kết thúc.","The end-of-term ceremony ended."),
    row("脇腹","わきばら","N4","n",
        "hông | sườn | mạng sườn",
        "side (of the torso) | flank",
        "1562550",
        "脇腹が痛い。","わきばらがいたい。",
        "Hông tôi đau.","My flank hurts."),
    row("薄氷","はくひょう","N4","n",
        "lớp băng mỏng | băng mỏng",
        "thin ice",
        "1625930",
        "薄氷の上を歩く。","はくひょうのうえをあるく。",
        "Đi trên lớp băng mỏng.","Walk on thin ice."),
    row("薬剤師","やくざいし","N4","n",
        "dược sĩ | nhà bào chế thuốc",
        "pharmacist | chemist",
        "1538230",
        "薬剤師に相談した。","やくざいしにそうだんした。",
        "Tôi tư vấn với dược sĩ.","I consulted the pharmacist."),
    row("詰め込む","つめこむ","N4","v5m|vt",
        "nhồi nhét | nhét đầy | chèn vào | dồn vào",
        "to cram | to stuff | to jam | to squeeze | to pack | to crowd",
        "1226550",
        "かばんに詰め込む。","かばんにつめこむ。",
        "Nhồi đồ vào túi.","Cram things into the bag."),
    row("軽食","けいしょく","N4","n",
        "bữa ăn nhẹ | đồ ăn nhẹ | snack | bánh mì sandwish",
        "light meal | snack | refreshments",
        "1252760",
        "軽食を食べる。","けいしょくをたべる。",
        "Ăn bữa ăn nhẹ.","Eat a light meal."),
    row("下駄","げた","N4","n",
        "guốc gỗ truyền thống Nhật | guốc geta",
        "geta | traditional Japanese wooden sandal",
        "1185780",
        "下駄を履く。","げたをはく。",
        "Đi guốc geta.","Wear geta sandals."),
    row("光合成","こうごうせい","N4","n",
        "quang hợp | tổng hợp ánh sáng",
        "photosynthesis",
        "1272970",
        "植物は光合成をする。","しょくぶつはこうごうせいをする。",
        "Thực vật thực hiện quang hợp.","Plants do photosynthesis."),
    row("刷り込む","すりこむ","N4","v5m|vt",
        "in vào | khắc sâu vào | nhồi vào tiềm thức | in dấu",
        "to print (on) | to insert (an illustration) | to instill (a thought, impression, etc.) | to imprint (e.g. on one's subconscious)",
        "1298580",
        "考えを刷り込む。","かんがえをすりこむ。",
        "Khắc sâu suy nghĩ vào.","Imprint thoughts."),
    row("受粉","じゅふん","N4","n|vs|vi",
        "thụ phấn | gieo phấn hoa",
        "pollination",
        "1330040",
        "花が受粉する。","はながじゅふんする。",
        "Hoa thụ phấn.","Flowers pollinate."),
    row("叩き込む","たたきこむ","N4","v5m|vt",
        "đóng vào | đập vào | ném vào ngục | khắc sâu vào đầu",
        "to drive into (e.g. a nail into a board) | to hit into (e.g. a home run into the stands) | to throw into (e.g. jail) | to drum into (someone) | to hammer into | to drill into",
        "1416090",
        "知識を叩き込む。","ちしきをたたきこむ。",
        "Khắc sâu kiến thức vào đầu.","Drill knowledge into one's head."),
    row("咲き乱れる","さきみだれる","N4","v1|vi",
        "nở rộ | nở tưng bừng | hoa nở khắp nơi",
        "to bloom in profusion",
        "1297200",
        "桜が咲き乱れる。","さくらがさきみだれる。",
        "Hoa anh đào nở rộ.","Cherry blossoms bloom in profusion."),
    row("帯","おび","N4","n",
        "thắt lưng kimono | obi | dải | băng | vành đai",
        "obi (kimono sash) | band | belt | strip | cingulum",
        "1410410",
        "帯を締める。","おびをしめる。",
        "Thắt dải obi.","Tie the obi sash."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
