# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-028.csv — 32 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-028.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("曲がり角","まがりかど","N4","n",
        "góc đường | khúc quanh | bước ngoặt",
        "(street) corner | turn (in the road) | bend | turning point | watershed",
        "1239710",
        "曲がり角を右に曲がります。","まがりかどをみぎにまがります。","Tôi rẽ phải ở góc đường.","I turn right at the corner."),
    row("献立","こんだて","N4","n",
        "thực đơn | thực đơn bữa ăn | lịch trình",
        "menu | bill of fare | program | programme | schedule",
        "1258500",
        "今日の献立を考えます。","きょうのこんだてをかんがえます。","Tôi nghĩ về thực đơn hôm nay.","I think about today's menu."),
    row("見渡す","みわたす","N4","v5s|vt",
        "nhìn bao quát | ngắm nhìn | phóng tầm mắt",
        "to look out over | to survey (scene) | to take an extensive view of",
        "1259920",
        "海を見渡します。","うみをみわたします。","Tôi nhìn bao quát biển.","I look out over the sea."),
    row("湿気","しっけ","N4","n",
        "độ ẩm | ẩm ướt | hơi ẩm",
        "moisture | humidity | dampness",
        "1320410",
        "湿気が多いです。","しっけがおおいです。","Độ ẩm cao.","There is a lot of humidity."),
    row("心がけ","こころがけ","N4","n",
        "thái độ tâm lý | cách suy nghĩ | sự cẩn thận | dự định | chú ý",
        "(mental) attitude | way of thinking | attention | care | prudence | intention",
        "1360500",
        "日頃の心がけが大切です。","ひごろのこころがけがたいせつです。","Thái độ trong cuộc sống hàng ngày quan trọng.","A daily positive attitude is important."),
    row("体積","たいせき","N4","n",
        "thể tích | dung tích",
        "capacity | volume",
        "1409560",
        "体積を計算します。","たいせきをけいさんします。","Tôi tính thể tích.","I calculate the volume."),
    row("棚卸し","たなおろし","N4","n|vs|vt|vi",
        "kiểm kê hàng tồn kho | đếm hàng tồn | kiểm kê kho",
        "stocktaking | inventory count | faultfinding",
        "1416720",
        "年末に棚卸しをします。","ねんまつにたなおろしをします。","Tôi kiểm kê kho vào cuối năm.","I take inventory at year-end."),
    row("読み返す","よみかえす","N4","v5s|vt",
        "đọc lại | xem lại",
        "to reread | to read again",
        "1456320",
        "レポートを読み返します。","レポートをよみかえします。","Tôi đọc lại bài báo cáo.","I reread the report."),
    row("部品","ぶひん","N4","n",
        "linh kiện | phụ tùng | bộ phận",
        "parts | accessories | components",
        "1499480",
        "部品を交換します。","ぶひんをこうかんします。","Tôi thay linh kiện.","I replace the parts."),
    row("面積","めんせき","N4","n",
        "diện tích | bình phương | mặt sàn",
        "area (measurement) | square measure | size (of land) | floor space",
        "1533500",
        "部屋の面積を測ります。","へやのめんせきをはかります。","Tôi đo diện tích phòng.","I measure the room area."),
    row("取引先","とりひきさき","N4","n",
        "khách hàng | đối tác kinh doanh | công ty khách hàng",
        "customer | client | client company | business connection | trade partner",
        "1599130",
        "取引先に連絡します。","とりひきさきにれんらくします。","Tôi liên hệ đối tác kinh doanh.","I contact the business partner."),
    row("サンプル","サンプル","N4","n",
        "mẫu | mẫu thử | vật mẫu | mô hình trưng bày",
        "sample | example | specimen | display model (e.g. plastic food models used by restaurants)",
        "1058760",
        "サンプルを確認します。","サンプルをかくにんします。","Tôi kiểm tra mẫu thử.","I check the sample."),
    row("遠回り","とおまわり","N4","n",
        "đường vòng | đường đi vòng | cách làm vòng vo",
        "detour | roundabout way",
        "1177930",
        "遠回りして帰ります。","とおまわりしてかえります。","Tôi đi đường vòng về nhà.","I take a detour home."),
    row("塩加減","しおかげん","N4","n",
        "lượng muối | nêm muối | vị mặn",
        "seasoning with salt | amount of salt",
        "1178670",
        "塩加減を調整します。","しおかげんをちょうせいします。","Tôi điều chỉnh lượng muối.","I adjust the amount of salt."),
    row("穏やか","おだやか","N4","adj-na",
        "bình yên | ôn hòa | dịu dàng | nhẹ nhàng | vừa phải",
        "calm | quiet | gentle | peaceful | mild | moderate | reasonable | amicable",
        "1183590",
        "穏やかな天気です。","おだやかなてんきです。","Thời tiết bình yên.","The weather is calm."),
    row("滑らか","なめらか","N4","adj-na",
        "nhẵn bóng | mượt mà | trơn tru | lưu loát",
        "smooth (of a surface) | glassy | velvety | soft | smooth (of an action, proceedings, etc.) | fluent (speech) | fluid | trouble-free",
        "1208560",
        "滑らかな話し方をします。","なめらかなはなしかたをします。","Tôi nói chuyện lưu loát.","I speak in a smooth manner."),
    row("完成品","かんせいひん","N4","n",
        "sản phẩm hoàn thiện | hàng thành phẩm",
        "finished product | finished goods | completed article",
        "1211500",
        "完成品を検査します。","かんせいひんをけんさします。","Tôi kiểm tra sản phẩm hoàn thiện.","I inspect the finished product."),
    row("近頃","ちかごろ","N4","adv|n|adj-no",
        "gần đây | dạo này | ngày nay | cực kỳ",
        "lately | recently | nowadays | terribly | awfully | extremely",
        "1242300",
        "近頃忙しいです。","ちかごろいそがしいです。","Gần đây tôi rất bận.","I've been busy lately."),
    row("見極める","みきわめる","N4","v1|vt",
        "xem đến tận cùng | xác định | nắm vững | tìm hiểu tường tận",
        "to watch to the end | to ascertain | to determine | to get to the bottom of | to make sure of | to know thoroughly | to obtain a deep understanding of",
        "1259490",
        "真実を見極めます。","しんじつをみきわめます。","Tôi xác định sự thật.","I ascertain the truth."),
    row("見本","みほん","N4","n|adj-no",
        "mẫu | mẫu vật | mẫu mực | ví dụ",
        "sample | specimen | pattern | model | example",
        "1260100",
        "見本を見せます。","みほんをみせます。","Tôi cho xem mẫu.","I show you the sample."),
    row("限界","げんかい","N4","n|adj-no",
        "giới hạn | ranh giới | hạn mức",
        "limit | bound",
        "1264650",
        "限界を超えます。","げんかいをこえます。","Tôi vượt giới hạn.","I exceed the limit."),
    row("参考書","さんこうしょ","N4","n",
        "sách tham khảo | sách bổ trợ học tập | tài liệu tham khảo",
        "reference book | study-aid book | supplemental textbook | student handbook",
        "1302300",
        "参考書を買います。","さんこうしょをかいます。","Tôi mua sách tham khảo.","I buy a reference book."),
    row("重量","じゅうりょう","N4","n",
        "trọng lượng | trọng tải",
        "weight",
        "1336900",
        "重量を量ります。","じゅうりょうをはかります。","Tôi cân trọng lượng.","I measure the weight."),
    row("道具","どうぐ","N4","n",
        "dụng cụ | công cụ | thiết bị | đồ dùng | phương tiện",
        "tool | implement | instrument | utensil | apparatus | device | means | furniture",
        "1454180",
        "道具を使います。","どうぐをつかいます。","Tôi dùng dụng cụ.","I use the tool."),
    row("濃度","のうど","N4","n",
        "nồng độ | mật độ | độ đặc",
        "concentration | density | cardinality",
        "1469970",
        "濃度を測ります。","のうどをはかります。","Tôi đo nồng độ.","I measure the concentration."),
    row("有効性","ゆうこうせい","N4","n",
        "tính hợp lệ | hiệu quả | tính hiệu lực",
        "validity | effectiveness",
        "1541340",
        "薬の有効性を確認します。","くすりのゆうこうせいをかくにんします。","Tôi xác nhận hiệu quả của thuốc.","I confirm the effectiveness of the medicine."),
    row("値上がり","ねあがり","N4","n|vs|vi",
        "tăng giá | giá cả tăng lên",
        "price increase | rise in price",
        "1600020",
        "食料品が値上がりします。","しょくりょうひんがねあがりします。","Thực phẩm tăng giá.","Food prices rise."),
    row("見逃す","みのがす","N4","v5s|vt",
        "bỏ lỡ | bỏ qua | không để ý | làm ngơ | lỡ mất cơ hội",
        "to miss | to overlook | to fail to notice | to let pass (a matter) | to overlook (e.g. a wrongdoing) | to turn a blind eye to | to pass up (e.g. an opportunity) | to let (a good ball) go by",
        "1604670",
        "チャンスを見逃します。","チャンスをみのがします。","Tôi bỏ lỡ cơ hội.","I miss the chance."),
    row("立て直す","たてなおす","N4","v5s|vt",
        "dựng lại | phục hồi | tái cơ cấu | xây dựng lại (kế hoạch)",
        "to put back up | to stand back up | to restore (to former strength) | to revive (e.g. the economy) | to reorganize | to rearrange | to put right | to recover | to put back on its feet | to make again (a plan, policy, etc.) | to reformulate | to revise",
        "1610720",
        "経営を立て直します。","けいえいをたてなおします。","Tôi tái cơ cấu kinh doanh.","I revive the business."),
    row("気配り","きくばり","N4","n|vs|vi",
        "sự chú ý | quan tâm (người khác) | tâm lý chăm sóc | ân cần",
        "care | attentiveness | attention | consideration (for others) | solicitude",
        "1614540",
        "気配りができる人です。","きくばりができるひとです。","Đó là người biết quan tâm.","They are a considerate person."),
    row("心配り","こころくばり","N4","n|vs|vi",
        "sự chú tâm | quan tâm chu đáo | tâm lý cẩn thận",
        "exerting care | attention | consideration | thoughtfulness",
        "1640000",
        "心配りが大切です。","こころくばりがたいせつです。","Sự quan tâm chu đáo rất quan trọng.","Thoughtfulness is important."),
    row("調べ直す","しらべなおす","N4","v5s",
        "kiểm tra lại | xem xét lại | kiểm soát lại",
        "to re-examine | to review | to recheck",
        "1655550",
        "データを調べ直します。","データをしらべなおします。","Tôi kiểm tra lại dữ liệu.","I re-examine the data."),
    row("孤独感","こどくかん","N4","n",
        "cảm giác cô đơn | cảm giác bị cô lập",
        "sense of isolation | (feelings of) loneliness",
        "2222170",
        "孤独感を感じます。","こどくかんをかんじます。","Tôi cảm thấy cô đơn.","I feel a sense of isolation."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
