# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-007.csv — 61 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-007.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("チーム","チーム","N4","n",
        "đội | nhóm | đội nhóm",
        "team",
        "1077360",
        "チームで頑張ります。","チームでがんばります。","Tôi cố gắng cùng đội.","I do my best with the team."),
    row("慰める","なぐさめる","N4","v1|vt",
        "an ủi | vỗ về | giải khuây",
        "to comfort | to console | to amuse",
        "1156890",
        "友達を慰めました。","ともだちをなぐさめました。","Tôi an ủi bạn bè.","I comforted my friend."),
    row("会議室","かいぎしつ","N4","n",
        "phòng họp | phòng hội nghị",
        "conference room | council room",
        "1198380",
        "会議室で話し合います。","かいぎしつではなしあいます。","Chúng tôi thảo luận trong phòng họp.","We discuss in the conference room."),
    row("距離","きょり","N4","n",
        "khoảng cách | tầm xa | khoảng thời gian | sự khác biệt (ví dụ quan điểm)",
        "distance | range | interval | difference (e.g. in opinion)",
        "1232920",
        "距離が近いです。","きょりがちかいです。","Khoảng cách gần.","The distance is close."),
    row("結婚式","けっこんしき","N4","n",
        "lễ kết hôn | đám cưới | hôn lễ",
        "marriage ceremony | wedding | nuptials",
        "1254810",
        "結婚式に出席します。","けっこんしきにしゅっせきします。","Tôi tham dự đám cưới.","I attend the wedding ceremony."),
    row("試合","しあい","N4","n|vs|vi",
        "trận đấu | trò chơi | trận thi đấu | cuộc thi",
        "match | game | bout | contest",
        "1312420",
        "試合に勝ちたいです。","しあいにかちたいです。","Tôi muốn thắng trận đấu.","I want to win the match."),
    row("湿度","しつど","N4","n",
        "độ ẩm",
        "humidity",
        "1320490",
        "湿度が高いです。","しつどがたかいです。","Độ ẩm cao.","The humidity is high."),
    row("実は","じつは","N4","exp|adv",
        "thực ra | thực chất | thật ra mà nói | thành thật mà nói | trên thực tế",
        "as a matter of fact | by the way | to tell you the truth | to be honest | in reality",
        "1320830",
        "実は、知りませんでした。","じつは、しりませんでした。","Thực ra, tôi không biết.","As a matter of fact, I didn't know."),
    row("卒業式","そつぎょうしき","N4","n",
        "lễ tốt nghiệp | lễ ra trường",
        "graduation ceremony | commencement",
        "1405920",
        "卒業式に出席します。","そつぎょうしきにしゅっせきします。","Tôi tham dự lễ tốt nghiệp.","I attend the graduation ceremony."),
    row("大学院","だいがくいん","N4","n",
        "trường sau đại học | bậc thạc sĩ và tiến sĩ",
        "graduate school",
        "1413250",
        "大学院で研究します。","だいがくいんでけんきゅうします。","Tôi nghiên cứu ở bậc sau đại học.","I do research in graduate school."),
    row("電話番号","でんわばんごう","N4","n",
        "số điện thoại",
        "telephone number | phone number",
        "1443940",
        "電話番号を教えてください。","でんわばんごうをおしえてください。","Hãy cho tôi số điện thoại.","Please tell me your phone number."),
    row("連絡先","れんらくさき","N4","n",
        "thông tin liên lạc (địa chỉ, số điện thoại, v.v.)",
        "contact information (address, phone number, etc.)",
        "1559930",
        "連絡先を交換します。","れんらくさきをこうかんします。","Chúng tôi trao đổi thông tin liên lạc.","We exchange contact information."),
    row("引っ越し","ひっこし","N4","n|vs|vi",
        "chuyển nhà | dọn nhà | thay đổi chỗ ở",
        "moving (dwelling, office, etc.) | changing residence",
        "1601880",
        "来月引っ越しします。","らいげつひっこしします。","Tháng sau tôi sẽ chuyển nhà.","I will move next month."),
    row("昼食","ちゅうしょく","N4","n",
        "bữa trưa | bữa ăn giữa ngày",
        "lunch | midday meal",
        "1602330",
        "昼食を食べます。","ちゅうしょくをたべます。","Tôi ăn bữa trưa.","I eat lunch."),
    row("技術","ぎじゅつ","N4","n",
        "công nghệ | kỹ thuật | kỹ năng | tay nghề | nghệ thuật | thủ công",
        "technology | engineering | technique | skill | art | craft",
        "1225130",
        "技術を磨きます。","ぎじゅつをみがきます。","Tôi trau dồi kỹ năng.","I polish my skills."),
    row("疑う","うたがう","N4","v5u|vt",
        "nghi ngờ | không tin tưởng | nghi ngờ | ngờ vực",
        "to doubt | to distrust | to be suspicious of | to suspect",
        "1225510",
        "彼を疑います。","かれをうたがいます。","Tôi nghi ngờ anh ấy.","I suspect him."),
    row("自然","しぜん","N4","n|adj-na|adv|adv-to",
        "thiên nhiên | tự nhiên | tự phát | tự động | một cách tự nhiên",
        "nature | natural | spontaneous | automatic | naturally | spontaneously",
        "1318090",
        "自然が大好きです。","しぜんがだいすきです。","Tôi rất yêu thiên nhiên.","I love nature."),
    row("叱る","しかる","N4","v5r|vt",
        "mắng | la mắng | quở trách | khiển trách",
        "to scold | to chide | to rebuke | to reprimand",
        "1319580",
        "子供を叱りました。","こどもをしかりました。","Tôi mắng đứa trẻ.","I scolded the child."),
    row("恋人","こいびと","N4","n",
        "người yêu | bạn gái | bạn trai",
        "lover | sweetheart | boyfriend | girlfriend",
        "1558920",
        "恋人と旅行します。","こいびととりょこうします。","Tôi đi du lịch cùng người yêu.","I travel with my lover."),
    row("システム","システム","N4","n",
        "hệ thống",
        "system",
        "1060300",
        "システムを導入します。","システムをどうにゅうします。","Tôi giới thiệu hệ thống.","I introduce a system."),
    row("割引","わりびき","N4","n|ctr",
        "giảm giá | giảm bớt | chiết khấu | phần mười được giảm",
        "discount | reduction | rebate | tenths discounted | tenths reduced",
        "1606950",
        "割引があります。","わりびきがあります。","Có giảm giá.","There is a discount."),
    row("追いかける","おいかける","N4","v1|vt",
        "đuổi theo | chạy theo | truy đuổi | tiếp theo | theo sau",
        "to chase | to run after | to pursue | subsequently | following",
        "1608720",
        "犬を追いかけます。","いぬをおいかけます。","Tôi đuổi theo con chó.","I chase after the dog."),
    row("オフィス","オフィス","N4","n",
        "văn phòng",
        "office",
        "1034660",
        "オフィスで働きます。","オフィスではたらきます。","Tôi làm việc ở văn phòng.","I work at the office."),
    row("カルチャー","カルチャー","N4","n",
        "văn hóa",
        "culture",
        "1038970",
        "カルチャーを学びます。","カルチャーをまなびます。","Tôi học văn hóa.","I learn about culture."),
    row("コピー","コピー","N4","n|vs|vt",
        "bản sao | photocopy | tóm tắt bìa sách | khẩu hiệu (quảng cáo) | sao chép",
        "copy | photocopy | book jacket blurb | (advertising) slogan",
        "1050590",
        "書類をコピーします。","しょるいをコピーします。","Tôi photocopy tài liệu.","I copy the document."),
    row("スタイル","スタイル","N4","n",
        "vóc dáng | thể hình | dáng vẻ | hình thể | phong cách",
        "(one's) figure | build | physique | shape | style",
        "1069520",
        "スタイルがいいですね。","スタイルがいいですね。","Dáng người đẹp nhỉ.","You have a nice figure."),
    row("センター","センター","N4","n",
        "trung tâm | trung phong (bóng chày) | cầu thủ trung",
        "centre | center | center fielder",
        "1075040",
        "センターに行きます。","センターにいきます。","Tôi đến trung tâm.","I go to the center."),
    row("データ","データ","N4","n",
        "dữ liệu | số liệu",
        "data | datum",
        "1081190",
        "データを分析します。","データをぶんせきします。","Tôi phân tích dữ liệu.","I analyze the data."),
    row("ネット","ネット","N4","n",
        "mạng lưới | Internet | lưới (ví dụ lưới tóc, lưới tennis) | lợi nhuận ròng",
        "network | Internet | net (e.g. hairnet, tennis net) | net (profit, etc.)",
        "1093020",
        "ネットで調べます。","ネットでしらべます。","Tôi tra cứu trên mạng.","I search on the Internet."),
    row("パーティー","パーティー","N4","n",
        "bữa tiệc (tụ họp xã hội) | nhóm người tham gia (ví dụ trong trò chơi)",
        "party (social gathering) | party (group of people participating)",
        "1100760",
        "パーティーを開きます。","パーティーをひらきます。","Tôi tổ chức bữa tiệc.","I hold a party."),
    row("ビジネス","ビジネス","N4","n",
        "kinh doanh | thương mại | doanh nghiệp",
        "business",
        "1104780",
        "ビジネスを始めます。","ビジネスをはじめます。","Tôi bắt đầu kinh doanh.","I start a business."),
    row("ファイル","ファイル","N4","n|vs|vt",
        "tệp tin | hồ sơ giấy tờ | tập tài liệu | tệp máy tính",
        "file (for holding papers) | file (collection of documents) | computer file",
        "1107800",
        "ファイルを保存します。","ファイルをほぞんします。","Tôi lưu tệp.","I save the file."),
    row("フォーマット","フォーマット","N4","n|vs|vt",
        "định dạng | hình thức | định dạng dữ liệu | định dạng (ổ đĩa)",
        "format | form | (data) format | formatting (a disk)",
        "1110280",
        "フォーマットを確認します。","フォーマットをかくにんします。","Tôi kiểm tra định dạng.","I check the format."),
    row("プレゼンテーション","プレゼンテーション","N4","n|vs",
        "bài thuyết trình | buổi trình bày",
        "presentation",
        "1114810",
        "プレゼンテーションをします。","プレゼンテーションをします。","Tôi trình bày.","I give a presentation."),
    row("プロジェクト","プロジェクト","N4","n",
        "dự án | đề án",
        "project",
        "1117210",
        "プロジェクトを進めます。","プロジェクトをすすめます。","Tôi triển khai dự án.","I advance the project."),
    row("ベランダ","ベランダ","N4","n",
        "ban công | hiên nhà | thềm trước",
        "balcony | veranda | verandah | porch",
        "1119940",
        "ベランダで休みます。","ベランダでやすみます。","Tôi nghỉ ngơi trên ban công.","I rest on the balcony."),
    row("意識","いしき","N4","n|vs|vt|vi",
        "ý thức | nhận thức | sự tỉnh táo | ý thức cộng đồng | để ý đến | quan tâm đến",
        "consciousness | becoming aware (of) | awareness | sense | minding | heeding",
        "1156640",
        "安全を意識します。","あんぜんをいしきします。","Tôi ý thức về an toàn.","I am conscious of safety."),
    row("画家","がか","N4","n",
        "họa sĩ | nghệ sĩ | người vẽ tranh",
        "painter | artist",
        "1197120",
        "有名な画家です。","ゆうめいながかです。","Là họa sĩ nổi tiếng.","A famous painter."),
    row("解決","かいけつ","N4","n|vs|vt|vi",
        "giải quyết | giải pháp | giải quyết vấn đề",
        "settlement | solution | resolution",
        "1198960",
        "問題を解決します。","もんだいをかいけつします。","Tôi giải quyết vấn đề.","I solve the problem."),
    row("開始","かいし","N4","n|vs|vt|vi",
        "bắt đầu | khởi đầu | mở đầu | khởi sự",
        "start | commencement | beginning | initiation",
        "1202760",
        "会議を開始します。","かいぎをかいしします。","Tôi bắt đầu cuộc họp.","I start the meeting."),
    row("筋肉","きんにく","N4","n",
        "cơ bắp | cơ | cơ thể",
        "muscle",
        "1241810",
        "筋肉を鍛えます。","きんにくをきたえます。","Tôi rèn luyện cơ bắp.","I train my muscles."),
    row("表す","あらわす","N4","v5s|vt",
        "đại diện | biểu trưng | thể hiện | bộc lộ | biểu đạt | chỉ ra",
        "to represent | to signify | to stand for | to reveal | to show | to express | to indicate",
        "1263490",
        "気持ちを表します。","きもちをあらわします。","Tôi biểu đạt cảm xúc.","I express my feelings."),
    row("湖","みずうみ","N4","n",
        "hồ | hồ nước",
        "lake",
        "1267280",
        "湖で釣りをします。","みずうみでつりをします。","Tôi câu cá ở hồ.","I fish at the lake."),
    row("作家","さっか","N4","n",
        "tác giả | nhà văn | tiểu thuyết gia | nghệ sĩ",
        "author | writer | novelist | artist",
        "1297510",
        "有名な作家になりたいです。","ゆうめいなさっかになりたいです。","Tôi muốn trở thành nhà văn nổi tiếng.","I want to become a famous author."),
    row("指先","ゆびさき","N4","n|adj-no",
        "đầu ngón tay | ngón tay | đầu ngón chân | ngón chân",
        "fingertip | finger | toe tip | toe",
        "1309890",
        "指先が冷たいです。","ゆびさきがつめたいです。","Đầu ngón tay lạnh.","My fingertips are cold."),
    row("時刻","じこく","N4","n",
        "thời điểm | giờ | thời điểm thuận lợi | cơ hội | dịp",
        "time | (the) hour | favourable time | opportunity | chance",
        "1316220",
        "集合時刻は8時です。","しゅうごうじこくははちじです。","Giờ tập trung là 8 giờ.","The meeting time is 8 o'clock."),
    row("借金","しゃっきん","N4","n|vs|vt",
        "nợ | khoản vay | nợ phải trả | vay mượn tiền",
        "debt | loan | liabilities | borrowing money",
        "1323940",
        "借金を返します。","しゃっきんをかえします。","Tôi trả nợ.","I repay the debt."),
    row("条件","じょうけん","N4","n",
        "điều kiện | điều khoản | yêu cầu | tiêu chuẩn | điều kiện tiên quyết",
        "condition | term | requirement | qualification | prerequisite",
        "1356510",
        "条件を確認します。","じょうけんをかくにんします。","Tôi xác nhận điều kiện.","I confirm the conditions."),
    row("食べ物","たべもの","N4","n",
        "thức ăn | đồ ăn",
        "food",
        "1358340",
        "食べ物が好きです。","たべものがすきです。","Tôi thích đồ ăn.","I like food."),
    row("レベル","レベル","N4","n",
        "phiến loạn | kẻ nổi loạn",
        "rebel",
        "2861638"),
    row("選手","せんしゅ","N4","n",
        "vận động viên | cầu thủ | thành viên đội",
        "player (of a sport) | athlete | team member",
        "1392250",
        "選手として頑張ります。","せんしゅとしてがんばります。","Tôi cố gắng với tư cách vận động viên.","I do my best as a player."),
    row("大学生","だいがくせい","N4","n",
        "sinh viên đại học",
        "university student | college student",
        "1413260",
        "大学生として勉強します。","だいがくせいとしてべんきょうします。","Tôi học với tư cách sinh viên đại học.","I study as a university student."),
    row("誕生日","たんじょうび","N4","n",
        "sinh nhật | ngày sinh",
        "birthday",
        "1419110",
        "誕生日おめでとう！","たんじょうびおめでとう！","Chúc mừng sinh nhật!","Happy birthday!"),
    row("貯金","ちょきん","N4","n|vs|vt",
        "tiết kiệm tiền | tiền tiết kiệm | tiền gửi ngân hàng | số tiền đã tiết kiệm",
        "putting money aside | savings | deposit (e.g. in a bank) | amount saved",
        "1427170",
        "毎月貯金します。","まいつきちょきんします。","Hàng tháng tôi tiết kiệm tiền.","I save money every month."),
    row("林","はやし","N4","n",
        "rừng nhỏ | rừng cây | bụi cây | khóm cây | đám đông",
        "wood | woods | forest | grove | copse | thicket | bunch (of people)",
        "1555440",
        "林の中を歩きます。","はやしのなかをあるきます。","Tôi đi trong rừng.","I walk in the woods."),
    row("例えば","たとえば","N4","adv",
        "ví dụ | chẳng hạn như | ví dụ như",
        "for example | for instance | e.g.",
        "1556370",
        "例えば、りんごや桃があります。","たとえば、りんごやもものがあります。","Ví dụ như táo và đào.","For example, there are apples and peaches."),
    row("祭り","まつり","N4","n|n-suf",
        "lễ hội | bữa tiệc | matsuri (lễ hội Nhật Bản) | bị tấn công bởi đám đông Internet",
        "festival | feast | matsuri | harassment by an Internet pitch fork mob",
        "1604130",
        "お祭りが楽しいです。","おまつりがたのしいです。","Lễ hội rất vui.","The festival is fun."),
    row("割合","わりあい","N4","n|adv",
        "tỷ lệ | tỷ suất | phần trăm | tỷ trọng | tương đối | trái với kỳ vọng",
        "rate | ratio | percentage | proportion | comparatively | contrary to expectations",
        "1606810",
        "合格率は高いです。","ごうかくりつはたかいです。","Tỷ lệ đậu rất cao.","The pass rate is high."),
    row("メールアドレス","メールアドレス","N4","n",
        "địa chỉ email",
        "email address",
        "2017400",
        "メールアドレスを教えます。","メールアドレスをおしえます。","Tôi cho biết địa chỉ email.","I tell you my email address."),
    row("退勤","たいきん","N4","n|vs|vi",
        "ra về (khi hết giờ làm) | chấm công ra về",
        "leaving work | clocking out",
        "2219610",
        "6時に退勤します。","ろくじにたいきんします。","Tôi ra về lúc 6 giờ.","I leave work at 6 o'clock."),
    row("ミス","ミス","N4","n",
        "thần thoại | huyền thoại",
        "myth",
        "2849827"),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
