# -*- coding: utf-8 -*-
"""Build N1 ready wave 081 — advanced katakana loanwords (set 81)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-081.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("アーティスティック","アーティスティック","adj-na","nghệ thuật | mang tính nghệ thuật | giàu chất nghệ","artistic","2447280"),
    ("アイロニカル","アイロニカル","adj-na","mỉa mai | châm biếm | trớ trêu","ironical","1014580"),
    ("アクチュアル","アクチュアル","adj-na|n","thực tế | thực tại | hiện thực","actual","1015360"),
    ("アグレッシブ","アグレッシブ","adj-na","hung hăng | quyết liệt | mạnh bạo | tích cực tiến công","aggressive","1015570"),
    ("アシンメトリー","アシンメトリー","n","sự bất đối xứng | tính phi đối xứng","asymmetry","1015810"),
    ("アタッチメント","アタッチメント","n","phụ kiện đính kèm | tập tin đính kèm | bộ phận gắn thêm","attachment","1016420"),
    ("アドリブ","アドリブ","n|adj-no","ứng tác | ngẫu hứng | tùy cơ ứng biến | nói/diễn tùy hứng","ad-lib","1017230"),
    ("アナリスト","アナリスト","n","nhà phân tích | chuyên gia phân tích","analyst","1017470"),
    ("アンソロジー","アンソロジー","n","tuyển tập | hợp tuyển | tập hợp tác phẩm chọn lọc","anthology","1020030"),
    ("イニシエーション","イニシエーション","n","nghi lễ kết nạp | lễ nhập môn | sự khai tâm","initiation","1021540"),
    ("イラショナル","イラショナル","n","phi lý trí | thiếu logic | vô lý","irrational","1021930"),
    ("インタラクティブ","インタラクティブ","adj-na|n","tương tác | có tính tương tác | tương hỗ","interactive","1023200"),
    ("インテンシブ","インテンシブ","adj-na","chuyên sâu | cường độ cao | tăng cường","intensive","1023600"),
    ("インフォーマル","インフォーマル","adj-na","không chính thức | thân mật | suồng sã","informal","1024150"),
    ("インボイス","インボイス","n","hóa đơn | hóa đơn thương mại | hóa đơn thuế","an invoice","1024730"),
    ("ウェルネス","ウェルネス","n","sự khỏe mạnh toàn diện | sức khỏe thể chất tinh thần | lối sống lành mạnh","wellness","2440930"),
    ("エキゾチック","エキゾチック","adj-na","kỳ lạ | mang phong vị xa lạ | đậm chất ngoại lai | dị quốc","exotic","1027880"),
    ("エクスクルーシブ","エクスクルーシブ","adj-na","độc quyền | dành riêng | đặc quyền | cao cấp riêng biệt","exclusive","2831084"),
    ("エコロジー","エコロジー","n","sinh thái học | phong trào bảo vệ môi trường | chủ nghĩa môi trường","ecology | environmentalism","1028390"),
    ("エスニック","エスニック","adj-na|n","mang sắc tộc | đậm chất dân tộc | phong vị bản địa","ethnic","1028820"),
    ("オーガニック","オーガニック","adj-na|adj-no","hữu cơ | tự nhiên không hóa chất | organic","organic","2079250"),
    ("オーセンティック","オーセンティック","adj-na","chính hiệu | đích thực | nguyên bản | xác thực","authentic","1031720"),
    ("オートノミー","オートノミー","n","quyền tự chủ | sự tự trị | tính tự quản","autonomy","2845862"),
    ("オブジェクト","オブジェクト","n","đối tượng | vật thể | đối tượng (lập trình)","object","1034920"),
    ("オペレーター","オペレーター","n","người vận hành | điện thoại viên | người điều khiển máy","operator","1035320"),
    ("カオス","カオス","n","sự hỗn loạn | hỗn mang | tình trạng rối ren | hỗn độn","chaos","1037040"),
    ("カウンセリング","カウンセリング","n","sự tư vấn | tham vấn tâm lý | trị liệu tâm lý","counseling","1036910"),
    ("カスタマイズ","カスタマイズ","n|vs|vt","tùy chỉnh | điều chỉnh theo ý | cá nhân hóa","customization","1037300"),
    ("カタストロフィー","カタストロフィー","n","thảm họa | tai biến | đại họa | kết cục bi thảm","catastrophe","1037490"),
    ("カテゴライズ","カテゴライズ","n|vs|vt","sự phân loại | xếp loại | phân hạng","categorizing","2150780"),
    ("キャスティング","キャスティング","n","sự chọn vai | tuyển diễn viên | phân vai","casting","1041340"),
    ("キュレーション","キュレーション","n","sự tuyển chọn | biên tập nội dung | tổng hợp chọn lọc","curation","2825884"),
    ("クリティカル","クリティカル","adj-na|n","then chốt | nghiêm trọng | mang tính phê phán | chí mạng","critical","1044960"),
    ("グラデーション","グラデーション","n","sự chuyển sắc | hiệu ứng đổ màu | dải màu chuyển dần","gradation","1046560"),
    ("グロテスク","グロテスク","adj-na|n","kỳ dị | quái dị | gớm ghiếc | quái đản","grotesque | bizarre","1047820"),
    ("コーチング","コーチング","n","huấn luyện | sự kèm cặp | dẫn dắt khai vấn","coaching","2666480"),
    ("コミカル","コミカル","adj-na","hài hước | khôi hài | buồn cười | gây cười","comical","1050840"),
    ("コミュニケ","コミュニケ","n","thông cáo | bản tuyên bố chung | thông cáo chính thức","a communiqué","1050970"),
    ("コンセプチュアル","コンセプチュアル","adj-na","mang tính ý niệm | thuộc về khái niệm | trừu tượng ý tưởng","conceptual","2854466"),
    ("サイクル","サイクル","n","chu kỳ | vòng tuần hoàn | chu trình","a cycle","1055520"),
    ("サブリミナル","サブリミナル","n|adj-no|adj-na","tiềm thức | dưới ngưỡng nhận thức | tác động ngầm","subliminal","2130180"),
    ("サマリー","サマリー","n","bản tóm tắt | tóm lược | bản tổng hợp","summary","1057750"),
    ("サンクション","サンクション","n","sự trừng phạt | chế tài | sự cấm vận | sự phê chuẩn","sanction","1058260"),
    ("シニシズム","シニシズム","n","chủ nghĩa hoài nghi | thái độ yếm thế | sự giễu cợt chua chát","cynicism","1060880"),
    ("ジャッジ","ジャッジ","n|vs|vt","trọng tài | sự phán xét | phán quyết | đánh giá","judge | judgement","1065450"),
    ("シンクロ","シンクロ","n|vs","sự đồng bộ | bơi nghệ thuật | sự ăn khớp","synchronization","1063470"),
    ("シンメトリー","シンメトリー","n","sự đối xứng | tính cân đối | đối xứng","symmetry","1063990"),
    ("スキーマ","スキーマ","n","lược đồ | sơ đồ cấu trúc | khung nhận thức","schema","1067810"),
    ("スタミナ","スタミナ","n|adj-f","sức bền | thể lực | sức dẻo dai | năng lượng","stamina | energy","1069810"),
    ("ステレオタイプ","ステレオタイプ","n|adj-na","khuôn mẫu định kiến | sự rập khuôn | hình mẫu cứng nhắc","stereotype","1070680"),
    ("スパン","スパン","n","khoảng thời gian | nhịp | quãng | khẩu độ","span","1072190"),
    ("セグメント","セグメント","n","phân khúc | đoạn | mảng | phân đoạn","segment","1074530"),
    ("ソフィスティケート","ソフィスティケート","n|vs|vt","sự tinh tế | sự sành điệu | làm cho tinh xảo | trau chuốt","sophistication","2497060"),
    ("ダイバーシティ","ダイバーシティ","n","sự đa dạng | tính đa dạng | đa dạng hóa","diversity","2307590"),
    ("ダイジェスト","ダイジェスト","n|vs|vt","bản tóm tắt | tóm lược | bản rút gọn | điểm tin","digest | summary","1076760"),
    ("チャリティー","チャリティー","n","từ thiện | hoạt động từ thiện | lòng bác ái","charity","1077990"),
    ("ディスカッション","ディスカッション","n|vs|vi|vt","cuộc thảo luận | bàn luận | tranh luận","discussion","1081710"),
    ("デカダンス","デカダンス","n","sự suy đồi | chủ nghĩa suy đồi | trụy lạc sa đọa","decadence","1082630"),
    ("デバイス","デバイス","n","thiết bị | dụng cụ | linh kiện | thiết bị điện tử","device","1083510"),
    ("デフォルメ","デフォルメ","n|vs|vt","sự biến dạng cách điệu | sự phóng đại hình họa | sự biếm họa","deformation (artistic distortion)","1083760"),
    ("ニヒリズム","ニヒリズム","n","chủ nghĩa hư vô | thuyết hư vô | tư tưởng phủ định","nihilism","1091310"),
    ("ニュートラル","ニュートラル","adj-na","trung lập | trung tính | vị trí số mo | không nghiêng bên nào","neutral","1091760"),
    ("ネゴシエーション","ネゴシエーション","n","sự đàm phán | thương lượng | thương thảo","negotiation","1092880"),
    ("ノーマライゼーション","ノーマライゼーション","n","sự bình thường hóa | tạo điều kiện bình đẳng cho người khuyết tật","normalization","2060380"),
    ("ハイブリッド","ハイブリッド","n|adj-no","lai | kết hợp | hỗn hợp | giống lai","hybrid","1095480"),
    ("パッシブ","パッシブ","adj-na","thụ động | bị động | không chủ động","passive","1101760"),
    ("パトロン","パトロン","n","người bảo trợ | mạnh thường quân | người chu cấp | ông bầu","a patron | a financial supporter","1101990"),
    ("パニック","パニック","n","sự hoảng loạn | cơn hoảng sợ | sự náo loạn","panic","1102060"),
    ("パラドキシカル","パラドキシカル","adj-na","nghịch lý | ngược đời | mâu thuẫn biểu kiến","paradoxical","2491640"),
    ("パラレル","パラレル","adj-na|n|adj-no","song song | tương đồng | đồng thời tồn tại | song hành","parallel","1102720"),
    ("ピュア","ピュア","adj-na|n","thuần khiết | trong sáng | tinh khiết | nguyên chất","pure","1106910"),
    ("フィクション","フィクション","n","hư cấu | tiểu thuyết | điều bịa đặt | chuyện không có thật","fiction","1109040"),
    ("フェティシズム","フェティシズム","n","sự sùng bái vật | chứng cuồng vật | tôn sùng (vật/bộ phận)","fetishism","1109850"),
    ("フラストレーション","フラストレーション","n","sự bực bội | nỗi ấm ức | tâm trạng bí bách | sự ức chế","frustration","1111300"),
    ("プラグマティズム","プラグマティズム","n","chủ nghĩa thực dụng | thuyết thực dụng | tư tưởng thực dụng","pragmatism","1115600"),
    ("プロトタイプ","プロトタイプ","n","nguyên mẫu | bản mẫu thử | mô hình thử nghiệm","prototype","1117690"),
    ("プロパガンダ","プロパガンダ","n","sự tuyên truyền | chiến dịch tuyên truyền | tuyên truyền chính trị","propaganda","1117740"),
    ("ヘゲモニー","ヘゲモニー","n","quyền bá chủ | quyền lãnh đạo | thế thượng phong","hegemony","1118280"),
    ("ベクトル","ベクトル","n","véc-tơ | hướng (hoạt động/quan tâm) | phương hướng","vector | direction","1119470"),
    ("ボキャブラリー","ボキャブラリー","n","vốn từ vựng | kho từ vựng | từ vựng","vocabulary","1123770"),
    ("ホスピタリティー","ホスピタリティー","n","sự hiếu khách | lòng mến khách | sự tiếp đãi chu đáo","hospitality","1122370"),
    ("ポピュリズム","ポピュリズム","n","chủ nghĩa dân túy | tư tưởng mị dân | chủ nghĩa bình dân","populism","1125520"),
    ("マイルストーン","マイルストーン","n","cột mốc | dấu mốc quan trọng | mốc tiến độ","milestone","1127090"),
    ("マニュアル","マニュアル","n","sổ tay hướng dẫn | cẩm nang | quy trình chuẩn | (xe) số sàn","a manual","1128870"),
    ("メカニカル","メカニカル","adj-na|n","cơ khí | máy móc | mang tính cơ học | rập khuôn máy móc","mechanical","1132940"),
    ("メタファー","メタファー","n","ẩn dụ | phép ẩn dụ | hình ảnh ẩn dụ","metaphor","1133300"),
    ("メランコリー","メランコリー","n","sự u sầu | nỗi buồn man mác | tâm trạng sầu muộn","melancholy","1133940"),
    ("モットー","モットー","n","phương châm | khẩu hiệu | châm ngôn sống","motto","1135110"),
    ("モノローグ","モノローグ","n","độc thoại | màn độc thoại | lời tự bạch","monologue","1135690"),
    ("モラトリアム","モラトリアム","n","sự hoãn | thời gian gia hạn | giai đoạn trì hoãn trưởng thành | lệnh tạm hoãn","moratorium | postponement","1135790"),
    ("ラジカル","ラジカル","adj-na","cấp tiến | triệt để | quá khích | gốc rễ","radical","1138980"),
    ("ロジカル","ロジカル","adj-na|n","hợp logic | có lý | logic | mạch lạc","logical","1147390"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
