# -*- coding: utf-8 -*-
"""Build N1 ready wave 037 — 慣用句 + 四字熟語 + nouns (set 37)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-037.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("羽を伸ばす","はねをのばす","exp|v5s","xõa hết mình | thả lỏng | tự do vui chơi (sau căng thẳng) | sổ lồng","to let one's hair down | to have fun after stress","2537520"),
    ("腹八分目","はらはちぶんめ","n","ăn no tám phần | ăn vừa phải | không ăn quá no","being moderate in eating | stopping before full","2052210"),
    ("万策尽きる","ばんさくつきる","exp|v1","hết cách | cùng đường | dùng hết mọi cách | bó tay","to exhaust all means | to be at one's wits' end","2860408"),
    ("半畳を入れる","はんじょうをいれる","exp|v1","chen ngang chế giễu | la ó phản đối | cắt ngang chê bai","to interrupt | to jeer","2762410"),
    ("引かれ者","ひかれもの","n","tử tù bị giải đi | phạm nhân bị áp giải (引かれ者の小唄: cố tỏ ra bình thản)","a convict on their way to prison","2837235"),
    ("膝を屈する","ひざをくっする","exp|vs-s","khuất phục | quỳ gối | đầu hàng | chịu thua | nhún nhường","to surrender | to yield | to bend one's knee","2869763"),
    ("左団扇","ひだりうちわ","n","sống nhàn nhã sung túc | an nhàn dư dả | thảnh thơi đủ đầy","living in ease and comfort","1789400"),
    ("人聞き","ひとぎき","n","tiếng tăm | thể diện | dư luận (人聞きが悪い: mang tiếng)","reputation | respectability","1369190"),
    ("一筋","ひとすじ","n|adj-na","một đường | một dải | chuyên tâm | một lòng | dốc lòng","one line | single-minded | devoted","1575970"),
    ("一花咲かせる","ひとはなさかせる","exp|v1","tỏa sáng một lần | lập chút thành tựu | ghi dấu son chói lọi (trước khi lui)","to have one's day in the limelight | a brief flourish","2846691"),
    ("火の粉","ひのこ","n","tàn lửa | tia lửa | đốm lửa bắn ra (火の粉が降りかかる: vạ lây)","sparks","1193700"),
    ("日の目を見る","ひのめをみる","exp|v1","ra mắt công chúng | được biết đến | thấy ánh sáng | được công nhận","to see the light of day | to be realized","2179080"),
    ("火蓋","ひぶた","n","nắp đậy ngòi súng | nắp lỗ mồi (火蓋を切る: khai chiến)","cover for the touch-hole of a gun","1193770"),
    ("飄々","ひょうひょう","adj-t|adv-to|vs","phiêu diêu | thoát tục | ung dung tự tại | lãng đãng | vô tư","aloof | easygoing | detached | drifting","1574420"),
    ("拾い物","ひろいもの","n","của nhặt được | món hời bất ngờ | vận may | món hời rẻ","a lucky find | a windfall | a bargain","1332560"),
    ("顰める","しかめる","v1|vt","nhăn mặt | cau có | nhíu mày | nhăn nhó","to scrunch up (one's face) | to furrow (one's brow)","1574340"),
    ("風雲児","ふううんじ","n","người thời thế | anh hùng thời loạn | kẻ nắm thời cơ | tay phiêu lưu gặp vận","an adventurer who rises in troubled times","1844330"),
    ("不倶戴天","ふぐたいてん","n","không đội trời chung | thù không đội trời chung | tử thù | bất cộng đới thiên","an irreconcilable enemy | cannot live under the same sky","1492020"),
    ("袋小路","ふくろこうじ","n","ngõ cụt | đường cùng | bế tắc | ngõ hẻm không lối ra","a blind alley | a dead end | an impasse","1411080"),
    ("不承不承","ふしょうぶしょう","adv|adj-no","miễn cưỡng | bất đắc dĩ | gượng ép | không tình nguyện","reluctantly | grudgingly | unwillingly","1492890"),
    ("舞台裏","ぶたいうら","n","hậu trường | sau sân khấu | bên trong | hậu cảnh","backstage | behind the scenes","1499160"),
    ("仏心","ほとけごころ","n","lòng từ bi | tâm Phật | lòng nhân từ | lòng trắc ẩn","a merciful heart | mercy | charity","2640980"),
    ("筆まめ","ふでまめ","n|adj-na","siêng viết thư | chăm thư từ | viết lách đều đặn","a good correspondent | a ready writer","2012930"),
    ("踏み台","ふみだい","n","ghế kê chân | bệ đỡ | bàn đạp | bước đệm (踏み台にする)","a stool | a stepping stone","1745010"),
    ("不羈奔放","ふきほんぽう","n","phóng khoáng tự do | không gò bó | tự do tự tại | phóng túng","free-spirited and uninhibited","1495520"),
    ("へそで茶を沸かす","へそでちゃをわかす","exp|v5s","nực cười | buồn cười chết đi được | cười vỡ bụng | chuyện khôi hài","what a joke! | to be convulsed with laughter","2761770"),
    ("弁が立つ","べんがたつ","exp|v5t","ăn nói lưu loát | tài hùng biện | khéo ăn nói | có duyên ăn nói","to be eloquent | to have a way with words","2063000"),
    ("箆棒","べらぼう","adj-na|n","quá đáng | kinh khủng | vô lý | ngớ ngẩn | đồ ngốc","extreme | absurd | unreasonable | fool","1615150"),
    ("判官","はんがん","n","phán quan | quan tòa | quan xử án | viên chức bậc 3 (luật cổ)","a judge | a magistrate","1478510"),
    ("忙中閑あり","ぼうちゅうかんあり","exp","trong bận có nhàn | bận mấy cũng có lúc rảnh | giữa bộn bề vẫn có khoảng lặng","there are brief moments of leisure even when busiest","1908950"),
    ("頬被り","ほおかぶり","n|vs|vi","trùm khăn kín đầu | giả lơ | vờ không biết | lờ đi","covering one's head with a cloth | feigning ignorance","1663990"),
    ("臍を固める","ほぞをかためる","exp|v1","quyết tâm | hạ quyết tâm | dứt khoát | định bụng","to make up one's mind | to resolve firmly","2061140"),
    ("仏作って魂入れず","ほとけつくってたましいいれず","exp","làm mà thiếu cái cốt yếu | đúc tượng quên hồn | công dã tràng vì sót khâu cuối","doing everything but the most vital part","2869436"),
    ("骨惜しみ","ほねおしみ","n|vs|vi","ngại khó | lười nhác | tiếc công | ngại bỏ sức","sparing oneself | laziness","1288620"),
    ("骨折り損","ほねおりぞん","n","công cốc | uổng công | dã tràng xe cát | phí sức","a waste of effort | vain labour","1651410"),
    ("本末","ほんまつ","n","gốc ngọn | cốt yếu và râu ria | đầu đuôi | chính phụ (本末転倒)","essence and trivialities | root and branch","1627390"),
    ("馬子にも衣装","まごにもいしょう","exp","người đẹp vì lụa | quần áo làm nên con người | đẹp nhờ ăn mặc","clothes make the man | fine feathers make fine birds","2069580"),
    ("誠","まこと","n|adv","chân thành | trung thực | thành thật | sự thật | quả thực","sincerity | truth | indeed | truly","1580555"),
    ("間尺に合わない","ましゃくにあわない","adj-i","không bõ công | lỗ vốn | chẳng đáng | không xứng công sức","does not pay | not worth one's while","1641070"),
    ("末期の水","まつごのみず","n","nước nhấp môi người hấp hối | giọt nước cuối đời | nước tiễn biệt","water to moisten a dying person's lips","1832930"),
    ("眦","まなじり","n","khóe mắt | đuôi mắt (眦を決する: trợn mắt quyết tâm)","the corner of the eye","1984810"),
    ("満を持す","まんをじす","exp|v5s","chờ đúng thời cơ | giương cung sẵn chờ | nín thở đợi thời | chuẩn bị đầy đủ","to bide one's time | to wait until the time is ripe","2569780"),
    ("水際立つ","みずぎわだつ","v5t|vi","xuất sắc nổi bật | tuyệt vời | điêu luyện | ấn tượng","to be splendid | to be superb","1847430"),
    ("水鳥","みずとり","n","chim nước | thủy cầm | chim sống ở nước","waterfowl | water bird","1580800"),
    ("道連れ","みちづれ","n","bạn đồng hành | người cùng đường | lôi kéo theo (cả khi chết)","a travelling companion | dragging someone along","1454280"),
    ("身銭","みぜに","n","tiền túi | tiền riêng | tiền của mình (身銭を切る)","one's own money","1641790"),
    ("身二つになる","みふたつになる","exp|v5r","sinh con | mẹ tròn con vuông | sinh nở | hạ sinh","to give birth","2118010"),
    ("耳が早い","みみがはやい","exp","thính tai | nhanh nhạy tin tức | biết tin sớm | tai thính","being quick to hear news | having sharp ears","1641640"),
    ("脈々","みゃくみゃく","adj-t|adv-to","liên tục không dứt | mạch nối liền | nối tiếp không ngừng | bền bỉ","continuous | unbroken | ceaseless","1753330"),
    ("冥利に尽きる","みょうりにつきる","exp|v1","may mắn tột bậc | phúc phận viên mãn | cảm thấy diễm phúc","to feel truly blessed in one's position","2129330"),
    ("身を立てる","みをたてる","exp|v1","lập thân | thành danh | gây dựng sự nghiệp | thành đạt","to make a success in life","1911020"),
    ("昔気質","むかしかたぎ","n|adj-no|adj-na","lối nghĩ xưa cũ | tính cách cổ hủ | nếp cũ | cốt cách thời xưa","an old-fashioned way of thinking | old-fashioned spirit","1697150"),
    ("向こう見ず","むこうみず","adj-na|n","liều lĩnh | hấp tấp | bạt mạng | thiếu suy nghĩ | gan cùng mình","reckless | rash | foolhardy | daredevil","1277160"),
    ("無芸大食","むげいたいしょく","n","ăn nhiều mà bất tài | vô tích sự chỉ giỏi ăn | đồ ăn hại","being good for nothing but eating","1672210"),
    ("矛盾撞着","むじゅんどうちゃく","n|vs","tự mâu thuẫn | tiền hậu bất nhất | trống đánh xuôi kèn thổi ngược","self-contradiction","2032750"),
    ("無常","むじょう","n|adj-no|adj-na","vô thường | biến đổi khôn lường | phù du | chóng tàn","impermanence | transitory | ever-changing","1530160"),
    ("無念無想","むねんむそう","n","vô niệm vô tưởng | tâm trống không | thanh tịnh không vướng bận","being free from worldly thoughts","1672350"),
    ("胸を借りる","むねをかりる","exp|v1","tập luyện với người giỏi hơn | nhờ cao thủ chỉ giáo | học hỏi đối thủ mạnh","to practice with a more skilled partner","2024480"),
    ("無味","むみ","adj-na|adj-no|n","vô vị | nhạt nhẽo | tẻ nhạt | không mùi vị","tasteless | insipid | dull","1672460"),
    ("村芝居","むらしばい","n","vở kịch làng | kịch nghiệp dư | hát tuồng do dân làng diễn","a play put on by villagers","1700400"),
    ("冥土","めいど","n","âm phủ | cõi âm | suối vàng | thế giới bên kia","Hades | the underworld | the other world","1531280"),
    ("名状しがたい","めいじょうしがたい","exp|adj-i","khó tả | không thể diễn tả | vượt khỏi ngôn từ | khôn tả xiết","indescribable | beyond description","2863216"),
    ("目に余る","めにあまる","exp|v5r","chướng mắt | không thể chịu nổi | quá quắt | không thể bỏ qua","to be intolerable | to be too much to overlook","1535150"),
    ("目鼻立ち","めはなだち","n","đường nét gương mặt | dung nhan | diện mạo | nét mặt","facial features | looks","1808250"),
    ("目減り","めべり","n|vs|vi","hao hụt | giảm giá trị | sụt giảm | vơi đi","loss (in weight/value) | reduction | decrease","1641190"),
    ("面従腹背","めんじゅうふくはい","n","bằng mặt không bằng lòng | ngoài tuân trong chống | khẩu phật tâm xà","pretending to obey while secretly betraying","1533470"),
    ("妄執","もうしゅう","n","vọng chấp | cố chấp sai lầm | ám ảnh u mê | định kiến sâu","a deep-rooted delusion","1533780"),
    ("盲蛇に怖じず","めくらへびにおじず","exp","điếc không sợ súng | kẻ ngu liều mạng | không biết nên không sợ","fools rush in where angels fear to tread","2094400"),
    ("持ち腐れ","もちぐされ","n","của để không | tài năng bỏ phí | có mà không dùng (宝の持ち腐れ)","an unused possession | wasted potential","1770080"),
    ("物心","ものごころ","n","sự hiểu biết sự đời | nhận thức | ý thức (物心がつく: bắt đầu hiểu chuyện)","awareness of things around one | discretion","1502610"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
