# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-016.csv — 50 rows (Wave 7 pool continued)."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-016.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("一方","いっぽう","N4","n|conj|n-suf|adv",
        "một bên | phía kia | một hướng | mặt khác | trong khi đó | ngày càng | chỉ có",
        "one (esp. of two) | the other | one way | the other way | one direction | the other direction | one side | the other side | on the one hand | on the other hand | whereas | although | meanwhile | in turn | just keeps | continuously | only",
        "1166510",
        "一方で勉強します。","いっぽうでべんきょうします。","Mặt khác tôi học bài.","On the other hand I study."),
    row("鋭い","するどい","N4","adj-i",
        "sắc bén | nhọn | dữ dội (đau, giọng điệu) | chua cay | nhạy bén (trực giác) | sắc sảo | thẩm thấu",
        "sharp (knife, claws, etc.) | pointed | sharp (pain, tone, etc.) | acute | stabbing | cutting (remark, criticism, etc.) | stinging | biting | fierce (attack) | piercing (gaze) | shrill (sound) | keen (intuition, sense of smell, etc.) | sharp (eye, mind, etc.) | astute | shrewd | penetrating (insight, question, etc.) | perceptive",
        "1174890",
        "鋭い質問をします。","するどいしつもんをします。","Tôi đặt câu hỏi sắc bén.","I ask a sharp question."),
    row("取り上げる","とりあげる","N4","v1|vt",
        "nhặt lên | chấp nhận (đề xuất) | đề cập (chủ đề) | đưa tin | tịch thu | tước đoạt | bãi bỏ | đỡ đẻ | thu thuế",
        "to pick up | to adopt (a proposal) | to take up (a topic) | to accept | to listen to | to report (news) | to cover | to feature | to take away | to confiscate | to deprive (someone) of | to revoke | to disqualify | to cancel | to deliver (a baby) | to collect (taxes)",
        "1326800",
        "提案を取り上げます。","ていあんをとりあげます。","Tôi chấp nhận đề xuất.","I take up the proposal."),
    row("縮める","ちぢめる","N4","v1|vt",
        "rút ngắn | giảm | cô đọng | làm co rút | nhăn nhúm | thu nhỏ (cơ thể) | thu chân lại",
        "to shorten | to reduce | to condense | to shrink | to crumple (fabric) | to wrinkle | to make (one's body) smaller | to draw in (one's legs) | to duck (one's head)",
        "1337570",
        "距離を縮めます。","きょりをちぢめます。","Tôi rút ngắn khoảng cách.","I shorten the distance."),
    row("出血","しゅっけつ","N4","n|vs|vi",
        "chảy máu | xuất huyết | thất thoát tiền bạc | bán dưới giá vốn | thương vong | tổn thất",
        "bleeding | haemorrhage | hemorrhage | bleeding money | red ink | selling below cost | casualties | losses | sacrifices",
        "1338750",
        "出血が止まります。","しゅっけつがとまります。","Vết chảy máu dừng lại.","The bleeding stops."),
    row("状態","じょうたい","N4","n",
        "trạng thái | tình trạng | hoàn cảnh | vẻ bề ngoài",
        "state | condition | situation | appearance | circumstances",
        "1356730",
        "体の状態を確認します。","からだのじょうたいをかくにんします。","Tôi kiểm tra tình trạng sức khỏe.","I check the condition of my body."),
    row("食堂","しょくどう","N4","n",
        "phòng ăn | căng-tin | nhà ăn tập thể | nhà hàng | quán ăn",
        "dining room | dining hall | cafeteria | canteen | messroom | restaurant | eatery | snack bar | diner",
        "1358550",
        "食堂で昼食を食べます。","しょくどうでちゅうしょくをたべます。","Tôi ăn trưa ở căng-tin.","I eat lunch at the cafeteria."),
    row("伸びる","のびる","N4","v1|vi",
        "vươn dài | kéo dài | lớn lên | phát triển | trải rộng | mất đàn hồi | nhũn ra | tiến bộ | kiệt sức | gia hạn",
        "to stretch | to extend | to lengthen | to grow (of hair, height, grass, etc.) | to straighten out | to be flattened | to become smooth | to spread (of paint, cream, etc.) | to lose elasticity | to become slack | to become soggy | to make progress | to develop | to expand | to increase | to improve | to be exhausted | to pass out | to collapse | to be prolonged | to be extended (e.g. of a deadline) | to be postponed | to be delayed",
        "1358870",
        "木が伸びます。","きがのびます。","Cây lớn lên.","The tree grows."),
    row("信頼","しんらい","N4","n|vs|vt",
        "tin tưởng | niềm tin | sự trông cậy",
        "trust (in) | confidence | faith | reliance",
        "1359730",
        "信頼を築きます。","しんらいをきずきます。","Tôi xây dựng niềm tin.","I build trust."),
    row("神経","しんけい","N4","n",
        "thần kinh | sợi thần kinh | độ nhạy cảm",
        "nerve | nerves | sensitivity",
        "1364520",
        "神経が細かいです。","しんけいがこまかいです。","Hệ thần kinh nhạy cảm.","The nerves are sensitive."),
    row("人間関係","にんげんかんけい","N4","n",
        "mối quan hệ giữa người với người | quan hệ cá nhân",
        "human relations | personal relationships",
        "1366850",
        "人間関係を大切にします。","にんげんかんけいをたいせつにします。","Tôi trân trọng các mối quan hệ.","I value human relationships."),
    row("人権","じんけん","N4","n",
        "nhân quyền | quyền tự do dân sự",
        "human rights | civil liberties",
        "1367200",
        "人権を守ります。","じんけんをまもります。","Tôi bảo vệ nhân quyền.","I protect human rights."),
    row("整える","ととのえる","N4","v1|vt",
        "sắp xếp | chỉnh lý | dọn gọn | chuẩn bị | điều chỉnh | bình ổn (hơi thở, nhịp điệu)",
        "to put in order | to arrange | to tidy up | to fix | to straighten | to get ready | to prepare | to supply | to assemble | to adjust | to regulate (e.g. rhythm, tune, one's breathing) | to work out (e.g. business deal) | to arrange (e.g. marriage) | to settle",
        "1376140",
        "呼吸を整えます。","こきゅうをととのえます。","Tôi điều chỉnh hơi thở.","I regulate my breathing."),
    row("正義","せいぎ","N4","n",
        "công lý | chính nghĩa | lẽ phải | ý nghĩa đúng",
        "justice | right | righteousness | correct meaning | correct explanation",
        "1376910",
        "正義を守ります。","せいぎをまもります。","Tôi bảo vệ công lý.","I uphold justice."),
    row("積み重ねる","つみかさねる","N4","v1|vt",
        "chồng lên | xếp chồng | tích lũy",
        "to pile up | to accumulate",
        "1382910",
        "経験を積み重ねます。","けいけんをつみかさねます。","Tôi tích lũy kinh nghiệm.","I accumulate experience."),
    row("粗い","あらい","N4","adj-i",
        "thô | sần sùi",
        "coarse | rough",
        "1396910",
        "粗い布です。","あらいぬのです。","Đây là vải thô.","This is rough cloth."),
    row("組む","くむ","N4","v5m|vt|vi",
        "bắt chéo (chân, tay) | liên kết tay | lắp ráp | sản xuất (chương trình) | bện | vật lộn | liên minh",
        "to cross (legs or arms) | to link (arms) | to put together | to construct | to assemble | to produce (e.g. TV program) | to braid | to plait | to grapple | to wrestle | to unite | to join | to link up | to form an alliance",
        "1397590",
        "腕を組みます。","うでをくみます。","Tôi khoanh tay.","I cross my arms."),
    row("想像","そうぞう","N4","n|vs|vt",
        "trí tưởng tượng | suy đoán | phỏng đoán",
        "imagination | supposition | guess",
        "1399610",
        "未来を想像します。","みらいをそうぞうします。","Tôi tưởng tượng tương lai.","I imagine the future."),
    row("相変わらず","あいかわらず","N4","adv|adj-no",
        "như thường lệ | như mọi khi | như cũ | vẫn vậy",
        "as usual | as always | as before | as ever | still",
        "1401310",
        "相変わらず元気です。","あいかわらずげんきです。","Vẫn như thường lệ tôi khỏe.","I am fine as usual."),
    row("葬式","そうしき","N4","n",
        "tang lễ | lễ mai táng",
        "funeral",
        "1402160",
        "葬式に参列します。","そうしきにさんれつします。","Tôi tham dự tang lễ.","I attend the funeral."),
    row("憎い","にくい","N4","adj-i",
        "đáng ghét | đáng khinh | đáng căm thù | khiến bực bội | tuyệt vời (mang nghĩa ngạc nhiên)",
        "hateful | detestable | abominable | vexing | provoking | amazing | fantastic | admirable | lovely | wonderful",
        "1403390",
        "憎い奴です。","にくいやつです。","Tên đó thật đáng ghét.","That person is hateful."),
    row("贈る","おくる","N4","v5r|vt",
        "tặng quà | dâng tặng | ban tặng | trao tặng",
        "to give (as a gift) | to present | to confer | to bestow | to award",
        "1403550",
        "花を贈ります。","はなをおくります。","Tôi tặng hoa.","I give flowers as a gift."),
    row("揃う","そろう","N4","v5u|vi",
        "đầy đủ | tập hợp đủ | đồng đều | khớp nhau | tụ họp",
        "to be complete | to be all present | to make a full set | to be satisfied (of conditions) | to be equal | to be uniform | to be even | to match | to agree | to gather | to assemble | to be collected",
        "1406110",
        "全員が揃います。","ぜんいんがそろいます。","Tất cả mọi người đều có mặt đầy đủ.","Everyone is all present."),
    row("揃える","そろえる","N4","v1|vt",
        "tập hợp | thu thập đủ | sắp xếp | chuẩn bị | làm đồng đều | làm khớp nhau",
        "to collect | to gather | to get together | to complete (a collection) | to arrange | to put in order | to prepare | to get ready | to make uniform | to make even | to match",
        "1406120",
        "書類を揃えます。","しょるいをそろえます。","Tôi chuẩn bị đủ tài liệu.","I prepare all documents."),
    row("尊敬","そんけい","N4","n|vs|vt",
        "tôn trọng | kính trọng | ngưỡng mộ | vinh danh",
        "respect | esteem | reverence | honour | honor",
        "1406400",
        "先生を尊敬します。","せんせいをそんけいします。","Tôi kính trọng thầy giáo.","I respect the teacher."),
    row("体温","たいおん","N4","n",
        "nhiệt độ cơ thể",
        "body temperature",
        "1409250",
        "体温を測ります。","たいおんをはかります。","Tôi đo nhiệt độ cơ thể.","I measure my body temperature."),
    row("肺","はい","N4","n",
        "phổi",
        "lung",
        "1472870",
        "肺が悪いです。","はいがわるいです。","Phổi của tôi có vấn đề.","My lungs are bad."),
    row("吐き気","はきけ","N4","n",
        "buồn nôn | cảm giác muốn ói | khó chịu trong bụng",
        "nausea | feeling like throwing up | feeling sick",
        "1444120",
        "吐き気がします。","はきけがします。","Tôi buồn nôn.","I feel nauseous."),
    row("投票","とうひょう","N4","n|vs|vi",
        "bỏ phiếu | phiếu bầu | cuộc thăm dò bầu cử",
        "voting | ballot | poll | vote",
        "1447320",
        "選挙で投票します。","せんきょでとうひょうします。","Tôi bỏ phiếu trong cuộc bầu cử.","I vote in the election."),
    row("日程","にってい","N4","n",
        "lịch trình | chương trình | nghị trình",
        "schedule | program | programme | agenda",
        "1464300",
        "日程を確認します。","にっていをかくにんします。","Tôi kiểm tra lịch trình.","I check the schedule."),
    row("保つ","たもつ","N4","v5t|vt|vi",
        "giữ gìn | bảo tồn | duy trì | kéo dài | bền lâu | giữ tươi (thức ăn)",
        "to keep | to preserve | to hold | to retain | to maintain | to sustain | to last | to endure | to keep well (food) | to wear well | to be durable",
        "1513250",
        "健康を保ちます。","けんこうをたもちます。","Tôi duy trì sức khỏe.","I maintain my health."),
    row("呆れる","あきれる","N4","v1|vi",
        "sửng sốt | bàng hoàng | ngạc nhiên đến mức bực bội | chán nản | phát chán",
        "to be amazed | to be shocked | to be astonished | to be astounded | to be disgusted | to be exasperated | to be fed up",
        "1515580",
        "その行動に呆れます。","そのこうどうにあきれます。","Tôi sửng sốt vì hành động đó.","I am amazed at that behavior."),
    row("輸出","ゆしゅつ","N4","n|vs|vt|adj-f",
        "xuất khẩu | xuất khẩu hàng hóa",
        "export | exportation | efferent",
        "1538820",
        "商品を輸出します。","しょうひんをゆしゅつします。","Chúng tôi xuất khẩu hàng hóa.","We export goods."),
    row("輸入","ゆにゅう","N4","n|vs|vt|adj-f",
        "nhập khẩu | nhập khẩu hàng hóa | du nhập",
        "import | importation | introduction | afferent",
        "1538870",
        "車を輸入します。","くるまをゆにゅうします。","Chúng tôi nhập khẩu xe hơi.","We import cars."),
    row("予算","よさん","N4","n|vs",
        "ước tính chi phí | ngân sách",
        "estimate (of costs) | budget",
        "1543000",
        "予算を組みます。","よさんをくみます。","Tôi lập ngân sách.","I draw up a budget."),
    row("余暇","よか","N4","n|adj-no",
        "thời gian rảnh rỗi | thời gian tự do",
        "leisure | leisure time | spare time",
        "1543980",
        "余暇を楽しみます。","よかをたのしみます。","Tôi tận hưởng thời gian rảnh.","I enjoy my leisure time."),
    row("余裕","よゆう","N4","n",
        "dư dả | khoảng trống | thời gian dư | linh hoạt | sự thoải mái | bình tĩnh",
        "surplus | margin | leeway | room | space | time | allowance | flexibility | scope | composure | placidity | calm",
        "1544590",
        "余裕があります。","よゆうがあります。","Tôi có thời gian dư.","I have some margin."),
    row("預かる","あずかる","N4","v5r|vt",
        "trông coi | chăm sóc | giữ hộ | phụ trách | được giao trách nhiệm | được ủy thác | hoãn (thông báo) | tự giải quyết",
        "to look after | to take care of | to keep | to hold on to | to keep in custody | to be put in charge of | to be given responsibility for | to be entrusted with | to withhold (an announcement) | to reserve (judgment) | to leave undecided | to settle (a matter) oneself",
        "1544970",
        "荷物を預かります。","にもつをあずかります。","Tôi giữ hộ hành lý.","I look after the luggage."),
    row("預ける","あずける","N4","v1|vt",
        "gửi (để ai đó giữ hộ) | giao cho ai chăm sóc | gửi tiền (vào ngân hàng) | ủy thác | giao quyền quyết định | dựa vào",
        "to leave (in someone's keeping) | to put (in someone's care) | to place (in someone's custody) | to entrust (someone) with | to deposit | to put (someone) in charge of | to leave (a matter) in someone's hands | to let (someone) decide | to lean on | to put one's weight on",
        "1544990",
        "銀行にお金を預けます。","ぎんこうにおかねをあずけます。","Tôi gửi tiền vào ngân hàng.","I deposit money at the bank."),
    row("要求","ようきゅう","N4","n|vs|vt",
        "yêu cầu | đòi hỏi | trưng dụng | nhu cầu",
        "demand | firm request | requisition | requirement | desire",
        "1546680",
        "要求を満たします。","ようきゅうをみたします。","Tôi đáp ứng yêu cầu.","I meet the demand."),
    row("要望","ようぼう","N4","n|vs|vt",
        "yêu cầu | đề nghị",
        "demand for | request",
        "1546830",
        "要望を聞きます。","ようぼうをききます。","Tôi lắng nghe đề nghị.","I listen to the request."),
    row("恋しい","こいしい","N4","adj-i",
        "nhớ nhung | thương nhớ | khao khát",
        "yearned for | longed for | missed",
        "1558760",
        "故郷が恋しいです。","こきょうがこいしいです。","Tôi nhớ quê hương.","I miss my hometown."),
    row("路線","ろせん","N4","n",
        "tuyến đường (xe buýt, tàu hỏa) | đường dây | chính sách | đường lối",
        "route (bus, train, air, etc.) | line | line (taken by a group, organization, etc.) | policy | course",
        "1560040",
        "路線を調べます。","ろせんをしらべます。","Tôi tra cứu tuyến đường.","I look up the route."),
    row("前半","ぜんはん","N4","n",
        "nửa đầu",
        "first half",
        "1581140",
        "前半に得点します。","ぜんはんにとくてんします。","Tôi ghi bàn trong nửa đầu.","I score in the first half."),
    row("鈍い","にぶい","N4","adj-i",
        "cùn | tù (lưỡi dao) | chậm chạp | đần độn | mờ nhạt | lờ đờ | kém nhạy cảm | vô cảm",
        "dull (e.g. a knife) | blunt | thickheaded | obtuse | stupid | dull (sound, color, etc.) | dim (light) | slow | sluggish | inert | lethargic | insensitive | dull (e.g. reflexes) | unperceptive | unfeeling",
        "1582430",
        "鈍いナイフです。","にぶいナイフです。","Đây là con dao cùn.","This is a blunt knife."),
    row("落ち着く","おちつく","N4","v5k|vi",
        "bình tĩnh lại | lấy lại bình tĩnh | thư giãn | ổn định | lắng xuống | an cư (nơi ở, công việc) | được giải quyết | hòa hợp",
        "to calm down | to compose oneself | to regain presence of mind | to relax | to settle down | to die down | to become stable | to abate | to settle down (in a location, job, etc.) | to settle in | to be settled (of an arrangement, conclusion, etc.) | to harmonize with | to match | to suit | to fit | to be quiet | to be subdued",
        "1589220",
        "気持ちが落ち着きます。","きもちがおちつきます。","Tâm trạng tôi bình tĩnh lại.","My feelings calm down."),
    row("整う","ととのう","N4","v5u|vi",
        "sẵn sàng | được chuẩn bị | ngăn nắp | cân đối | hài hòa | được điều chỉnh | được giải quyết (hợp đồng)",
        "to be ready | to be prepared | to be arranged | to be in order | to be well-ordered | to be well-proportioned | to be harmonious | to be adjusted | to be regulated | to be refined (e.g. of a face) | to be settled (e.g. treaty, contract) | to be completed",
        "1598800",
        "準備が整います。","じゅんびがととのいます。","Việc chuẩn bị đã hoàn tất.","The preparations are in order."),
    row("同盟","どうめい","N4","n|vs|vi",
        "liên minh | liên đoàn | đồng minh",
        "alliance | union | league",
        "1599290",
        "同盟を結びます。","どうめいをむすびます。","Chúng tôi kết liên minh.","We form an alliance."),
    row("引き受ける","ひきうける","N4","v1|vt",
        "đảm nhận | nhận lãnh | chấp nhận | phụ trách | chịu trách nhiệm | tiếp quản | bảo đảm | bị mắc (bệnh)",
        "to take on | to undertake | to accept | to take charge of | to assume responsibility for | to take over | to inherit | to guarantee | to vouch for | to contract (a disease)",
        "1601520",
        "仕事を引き受けます。","しごとをひきうけます。","Tôi đảm nhận công việc.","I take on the job."),
    row("気が散る","きがちる","N4","exp|v5r",
        "mất tập trung | bị phân tâm",
        "to get distracted | to jump off the track",
        "2056660",
        "音で気が散ります。","おとできがちります。","Tiếng ồn làm tôi mất tập trung.","The noise distracts me."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
