# -*- coding: utf-8 -*-
"""Build N2 ready wave 036 — quantity, counts, sums (額), ratios (率), math."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-036.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("微量","びりょう","n|adj-na|adj-no","lượng nhỏ | vi lượng | lượng cực ít","minuscule amount | extremely small quantity","1486200"),
    ("軽量","けいりょう","n|adj-no","trọng lượng nhẹ | nhẹ cân","light weight","1252920"),
    ("定量","ていりょう","n|adj-no","định lượng | lượng cố định","fixed quantity","1435790"),
    ("増量","ぞうりょう","n|vs|vt|vi","tăng lượng | tăng khối lượng","increase in amount | increase in quantity","1771780"),
    ("減量","げんりょう","n|vs|vt|vi","giảm cân | giảm lượng","weight reduction | reduction of quantity","1263350"),
    ("推量","すいりょう","n|vs|vt","suy đoán | phỏng đoán | ước đoán","guess | conjecture | inference","1371230"),
    ("器量","きりょう","n","dung mạo | nhan sắc | năng lực | tài năng | uy tín","looks | ability | capability | (public) estimation","1218980"),
    ("力量","りきりょう","n","năng lực | sức mạnh | tài năng | thực lực","ability | capacity | physical strength","1555260"),
    ("技量","ぎりょう","n","tay nghề | kỹ năng | năng lực chuyên môn","ability | competency | skill","1225250"),
    ("度量","どりょう","n","độ lượng | sự bao dung | đo lường","generosity | magnanimity | measures","1624130"),
    ("端数","はすう","n|adj-no","số lẻ | phần lẻ | số dư lẻ","fraction | odd amount | leftover amount","1418900"),
    ("概数","がいすう","n","số ước lượng | con số làm tròn | số gần đúng","approximate figure | round numbers","1204460"),
    ("人数","にんずう","n","số người | nhân số","the number of people","1580700"),
    ("頭数","とうすう","n","số (con vật) | đầu (gia súc)","number of (large) animals","2735120"),
    ("度数","どすう","n","số lần | tần suất | độ (nhiệt độ, độ rượu, độ kính)","frequency | number of times | degree","1445210"),
    ("点数","てんすう","n","điểm số | số điểm | số món | số hiện vật","marks | points | score | number of items","1441660"),
    ("口数","くちかず","n","số lời nói | số người ăn theo | số khẩu (phần)","number of words spoken | number of mouths to feed","1578670"),
    ("歩数","ほすう","n","số bước chân","number of steps","1627520"),
    ("本数","ほんすう","n","số lượng (vật dài) | số chuyến | số lần","number (of long items, trains, etc.)","1522770"),
    ("総数","そうすう","n","tổng số","total (number) | count","1401660"),
    ("半数","はんすう","n|adj-no","một nửa số | phân nửa | đơn bội (sinh học)","half the number | haploid","1479530"),
    ("素数","そすう","n","số nguyên tố","prime number","1397280"),
    ("約数","やくすう","n","ước số","divisor | factor","1538120"),
    ("乗数","じょうすう","n","số nhân | thừa số nhân","multiplier","1355330"),
    ("除数","じょすう","n","số chia","divisor","1345690"),
    ("桁","けた","n","cột | dầm | xà | chữ số | bậc (độ lớn)","beam | girder | digit | order of magnitude","1253800"),
    ("位","くらい","suf|prt","khoảng | cỡ | chừng | đến mức | ít nhất","approximately | about | to the extent that | at least","1154340"),
    ("小数点","しょうすうてん","n","dấu thập phân","decimal point","1348380"),
    ("分母","ぶんぼ","n","mẫu số","denominator","1504310"),
    ("余り","あまり","n|adj-no|adv|adj-na|n-suf","phần dư | phần còn lại | thừa | (không) lắm | quá","remainder | surplus | leftovers | (not) very | too much","1584930"),
    ("端","はした","n|adj-no|adj-na","số lẻ | phần lẻ | tiền lẻ | đầy tớ hạng thấp","fraction | odd money | small change","2590770"),
    ("総額","そうがく","n","tổng số tiền | tổng giá trị | tổng cộng","total amount (of money) | sum total","1401510"),
    ("金額","きんがく","n","số tiền | khoản tiền","amount of money | sum","1242700"),
    ("差額","さがく","n","khoản chênh lệch | số tiền chênh | hiệu số (giá)","balance | difference (in price) | margin","1291370"),
    ("残額","ざんがく","n","số dư | số tiền còn lại","remaining amount | balance (of an account)","1662580"),
    ("全額","ぜんがく","n","toàn bộ số tiền | trọn vẹn | tổng số","total | full amount","1394970"),
    ("増額","ぞうがく","n|vs|vt","tăng số tiền | tăng khoản","increase (in an amount of money)","1771830"),
    ("減額","げんがく","n|vs|vt","giảm tiền | hạ khoản | giảm bớt","reduction (in price or cost) | abatement","1263160"),
    ("高額","こうがく","n|adj-na|adj-no","số tiền lớn | mệnh giá cao | đắt đỏ","large sum (of money) | large denomination","1283320"),
    ("少額","しょうがく","n|adj-no","số tiền nhỏ | khoản nhỏ | mệnh giá nhỏ","small sum (of money) | small denomination","1348960"),
    ("多額","たがく","adj-no|adj-na|n","số tiền lớn | khoản lớn | đắt đỏ","large (amount of money) | huge | hefty","1407520"),
    ("巨額","きょがく","n|adj-no|adj-na","số tiền khổng lồ | khoản tiền lớn","huge sum (of money) | enormous sum","1231950"),
    ("定額","ていがく","n","định mức tiền | số tiền cố định | trọn gói","fixed amount (of money) | flat sum","1435450"),
    ("税額","ぜいがく","n","số tiền thuế","amount of tax","1382080"),
    ("月額","げつがく","n","số tiền hàng tháng | mức phí tháng","monthly sum | monthly amount","1255520"),
    ("年額","ねんがく","n","số tiền hằng năm | mức năm","yearly amount","1468330"),
    ("日額","にちがく","n","số tiền theo ngày","daily amount (of money)","2847526"),
    ("差し引き","さしひき","n|vs|vt|vi","khấu trừ | trừ đi | số dư | sự lên xuống","deduction | subtraction | balance","1291090"),
    ("確率","かくりつ","n","xác suất | khả năng | cơ hội","probability | likelihood | chances","1205950"),
    ("能率","のうりつ","n","hiệu suất | năng suất","efficiency | moment","1470330"),
    ("税率","ぜいりつ","n","thuế suất | mức thuế","tariff | tax rate","1382210"),
    ("打率","だりつ","n","tỷ lệ đánh trúng (bóng chày)","batting average","1408980"),
    ("勝率","しょうりつ","n","tỷ lệ thắng","winning percentage","1706730"),
    ("出生率","しゅっしょうりつ","n","tỷ lệ sinh","birth rate","1580100"),
    ("死亡率","しぼうりつ","n","tỷ lệ tử vong","death rate | mortality rate","1310990"),
    ("失業率","しつぎょうりつ","n","tỷ lệ thất nghiệp","unemployment rate","1319900"),
    ("合格率","ごうかくりつ","n","tỷ lệ đỗ | tỷ lệ trúng tuyển","examination pass rate","1935440"),
    ("普及率","ふきゅうりつ","n","tỷ lệ phổ cập | tỷ lệ lan rộng","diffusion rate | rate of spread","1497130"),
    ("稼働率","かどうりつ","n","tỷ lệ hoạt động | công suất sử dụng | tỷ lệ vận hành","operating rate | utilization rate","1613800"),
    ("増加率","ぞうかりつ","n","tỷ lệ tăng","rate of increase","1941470"),
    ("成長率","せいちょうりつ","n","tỷ lệ tăng trưởng","growth rate","1375810"),
    ("増減","ぞうげん","n|vs|vt|vi","tăng giảm | biến động","increase and decrease | fluctuation","1403200"),
    ("比","ひ","n|n-suf","tỷ lệ | tỷ số | so với | sự so sánh","ratio | proportion | comparison","1483520"),
    ("分","ぶ","num|n","một phần mười | 1 phần trăm | thế thuận lợi","one-tenth | one percent | advantageous circumstances","1502850"),
    ("厘","りん","num|n","một phần trăm | 0,1 phần trăm | rin (đơn vị tiền)","one-hundredth | 0.1 percent | rin (monetary unit)","1555420"),
    ("歩","ぶ","n|n-suf","bu (đơn vị diện tích ~3,31 m²) | phần trăm | hoa hồng","bu (unit of area) | commission | percentage","2145430"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
