# -*- coding: utf-8 -*-
"""Build N3 ready wave 068 — 121 freshly-curated N3 color/shape/state/side nouns + investigation + family/origin nouns. (3000 milestone)"""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-068.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("色彩","しきさい","n","màu sắc | sắc thái | gam màu","colour | hue | tints","1357720"),
    ("濃淡","のうたん","n","đậm nhạt | sắc độ | độ đậm","light and shade | shade (of colour) | depth (of flavor)","1469950"),
    ("明暗","めいあん","n","sáng tối | ánh sáng và bóng tối","light and darkness | light and shade","1532380"),
    ("透ける","すける","v1|vi","trong suốt | nhìn xuyên qua | lộ ra","to be transparent | to show through","1450530"),
    ("透き通る","すきとおる","v5r|vi","trong suốt | trong veo | (giọng) trong trẻo","to be transparent | to be clear (of a voice)","1450510"),
    ("色づく","いろづく","v5k|vi","đổi màu (lá) | ngả vàng/đỏ | chín | dậy thì","to change color (leaves) | to ripen | to reach puberty","1850880"),
    ("瞬く","またたく","v5k|vi","lấp lánh | nhấp nháy | chớp mắt","to twinkle | to flicker | to blink | to wink","1341200"),
    ("点滅","てんめつ","n|vs|vt|vi","nhấp nháy | bật tắt | chớp nháy","switching on and off | flashing | blinking","1441790"),
    ("陰る","かげる","v5r|vi","tối sầm | u ám | (mặt) sa sầm | xấu đi","to become clouded | to darken | to worsen","1590180"),
    ("暮れる","くれる","v1|vi","trời tối | hết (ngày, năm) | chìm trong (tuyệt vọng)","to get dark | to come to an end | to be sunk in","1514960"),
    ("差す","さす","v5s|vi|vt","chiếu (sáng) | dâng lên | che (ô) | tô (son)","to shine | to rise (water) | to hold up (umbrella) | to apply","1291330"),
    ("透かす","すかす","v5s|vt","soi (ánh sáng) | để khe hở | tỉa (cây)","to hold up to the light | to leave space | to prune","1450500"),
    ("浮かべる","うかべる","v1|vt","làm nổi | thả nổi | hiện (lên mặt) | hồi tưởng","to float | to show on one's face | to recall | to imagine","1497360"),
    ("様式","ようしき","n","kiểu | phong cách | mẫu thức","style | form | pattern","1545830"),
    ("形態","けいたい","n","hình thái | hình thức | hình dạng","form | shape | figure | morph","1250390"),
    ("体勢","たいせい","n","tư thế | thế đứng | dáng","posture | position | stance","1854310"),
    ("態勢","たいせい","n","tư thế (sẵn sàng) | thế trận | sự chuẩn bị","attitude | posture | preparedness | readiness","1410770"),
    ("構図","こうず","n","bố cục | cấu trúc | sự sắp đặt","composition (of painting) | structural outline","1279720"),
    ("図形","ずけい","n","hình | hình vẽ | đồ họa","figure | shape | graphic","1370380"),
    ("図表","ずひょう","n","biểu đồ | đồ thị | sơ đồ","chart | diagram | graph | figure","1370490"),
    ("略図","りゃくず","n","sơ đồ phác | bản đồ thô","rough sketch | rough map","1810220"),
    ("設計図","せっけいず","n","bản vẽ thiết kế | bản thiết kế","plan | blueprint","1386040"),
    ("立体","りったい","n|adj-no","khối | vật thể ba chiều | lập thể","solid body | three-dimensional object","1551740"),
    ("平面","へいめん","n","mặt phẳng | bề mặt phẳng","level surface | plane","1507960"),
    ("外形","がいけい","n","hình dáng bên ngoài | ngoại hình","externals | external form","1203500"),
    ("様相","ようそう","n","diện mạo | trạng thái | cục diện","aspect | phase | condition","1545840"),
    ("有様","ありさま","n","tình trạng | cảnh tượng | bộ dạng","state | condition | sight | spectacle","1541060"),
    ("実態","じったい","n","thực trạng | tình hình thực tế | bản chất thật","true state | actual condition | reality","1321360"),
    ("裏側","うらがわ","n","mặt sau | phía sau | mặt khuất | hậu trường","the reverse side | back | hidden side | behind the scenes","1550410"),
    ("内側","うちがわ","n|adj-no","bên trong | phía trong | mặt trong","inside | interior | inner part","1458770"),
    ("外側","そとがわ","n|adj-no","bên ngoài | phía ngoài | mặt ngoài","exterior | outside | outer | lateral","1577440"),
    ("片側","かたがわ","n","một bên | một phía","one side","1511720"),
    ("両側","りょうがわ","n|adj-no","hai bên | cả hai phía","both sides","1585140"),
    ("表向き","おもてむき","n","bề ngoài | chính thức | công khai (danh nghĩa)","outward appearance | ostensible | official","1489540"),
    ("内向き","うちむき","n","hướng vào trong | quay vào trong | hướng nội","facing inward","2140910"),
    ("外向き","そとむき","n","hướng ra ngoài | quay ra ngoài | hướng ngoại","facing outward","2140900"),
    ("上向き","うわむき","n|adj-no","hướng lên | ngửa lên | xu hướng tăng","pointing up | upturn | upward tendency","1580370"),
    ("下向き","したむき","n","hướng xuống | úp xuống | xu hướng giảm","pointing down | downturn | downward trend","1184910"),
    ("横向き","よこむき","n","nằm ngang | quay ngang | khổ ngang","turning sideways | landscape orientation","1180710"),
    ("縦向き","たてむき","n","theo chiều dọc | khổ dọc","portrait orientation | vertical orientation","2766100"),
    ("逆向き","ぎゃくむき","n|adj-no","hướng ngược | chiều ngược lại","opposite direction | reverse","2841237"),
    ("反対側","はんたいがわ","n","phía đối diện | bên kia","opposite side","1480720"),
    ("向こう側","むこうがわ","n","phía bên kia | đối phương | bên đối diện","other side | opposite side | other party","1604830"),
    ("内訳","うちわけ","n","chi tiết | khoản mục | bảng phân tích","itemization | breakdown | the items","1459360"),
    ("全容","ぜんよう","n","toàn cảnh | toàn bộ | bức tranh đầy đủ","full portrait | whole aspect | full story","1396340"),
    ("全貌","ぜんぼう","n","toàn bộ | toàn cảnh | đầy đủ chi tiết","full view | total picture | whole story","1396220"),
    ("大筋","おおすじ","n","ý chính | đại cương | nội dung chủ yếu","outline | summary | gist | basic points","1413490"),
    ("骨子","こっし","n","cốt lõi | điểm mấu chốt | sườn (ý tưởng)","main point | gist | essentials | pith","1288600"),
    ("論旨","ろんし","n","luận điểm | mạch lập luận | ý chính của lập luận","point of an argument | drift of an argument","1561710"),
    ("本筋","ほんすじ","n","mạch chính | nội dung chính (câu chuyện)","main thread (of a story)","1522430"),
    ("逸脱","いつだつ","n|vs|vi|vt","đi chệch | lệch khỏi | bỏ sót","deviation | departure | omission","1167750"),
    ("余談","よだん","n","chuyện ngoài lề | lạc đề","digression","1544370"),
    ("雑談","ざつだん","n|vs|vi","tán gẫu | chuyện phiếm","chatting | idle talk","1299480"),
    ("世間話","せけんばなし","n","chuyện phiếm | chuyện đời thường | tán gẫu","small talk | chat | gossip","1373980"),
    ("立ち話","たちばなし","n|vs|vi","đứng nói chuyện | nói chuyện đứng","talking while standing","1551490"),
    ("内緒","ないしょ","n|adj-no","bí mật | riêng tư | giấu kín","secrecy | confidentiality | secret","1458510"),
    ("秘密","ひみつ","n|adj-na","bí mật | điều bí mật | sự kín đáo","secret | secrecy | mystery","1484150"),
    ("機密","きみつ","n","cơ mật | thông tin tối mật | bí mật","secrecy | highly classified information","1221180"),
    ("極秘","ごくひ","adj-na|adj-no|n","tuyệt mật | tối mật","absolute secrecy","1240470"),
    ("内密","ないみつ","n|adj-na","bí mật | kín đáo | riêng tư","privacy | secrecy | confidentiality","1459230"),
    ("内輪","うちわ","n|adj-no","nội bộ | trong nhà | dè dặt (ước tính)","family circle | in-group | conservative (estimate)","1459540"),
    ("身内","みうち","n","người thân | gia đình | thuộc hạ | toàn thân","relatives | one's family | followers","1365800"),
    ("仲間内","なかまうち","n|adj-no","trong nhóm | giữa bạn bè | nội bộ nhóm","(among) one's friends | (within) one's circle","1621010"),
    ("表沙汰","おもてざた","n","công khai (vụ việc) | đưa ra ánh sáng | kiện ra tòa","going public | becoming public knowledge | litigation","1489570"),
    ("発覚","はっかく","n|vs|vi","bị phát giác | bị lộ | bại lộ","detection (of a plot) | discovery | coming to light","1477200"),
    ("露見","ろけん","n|vs|vi","bị bại lộ | bị phát hiện | lộ tẩy","discovery (of a misdeed) | detection | exposure","1606490"),
    ("発見","はっけん","n|vs|vt","phát hiện | khám phá | tìm ra","discovery | detection | finding","1477310"),
    ("判明","はんめい","n|vs|vi","làm rõ | sáng tỏ | được xác định","becoming clear | coming to light | being identified","1478730"),
    ("追及","ついきゅう","n|vs|vt","truy cứu | chất vấn | truy đuổi","investigation | questioning | hounding | pinning down","1432480"),
    ("追求","ついきゅう","n|vs|vt","theo đuổi | tìm kiếm (mục tiêu)","pursuit (of a goal) | search | seeking after","1432490"),
    ("追究","ついきゅう","n|vs|vt","truy tìm | nghiên cứu thấu đáo (sự thật)","thorough investigation | pursuit (of the truth)","1432500"),
    ("探求","たんきゅう","n|vs|vt","tìm tòi | truy tìm | mưu cầu","search | quest | pursuit","1418270"),
    ("探究","たんきゅう","n|vs|vt","khám phá | nghiên cứu | tìm hiểu","research | investigation | inquiry | study","1418290"),
    ("模索","もさく","n|vs|vt","mò mẫm | dò tìm | tìm kiếm (lời giải)","groping (for) | searching (for a solution)","1533660"),
    ("試行","しこう","n|vs|vt","thử nghiệm | chạy thử | làm thử","making an attempt | trial run","1312400"),
    ("錯誤","さくご","n","sai lầm | sai sót | sự lệch lạc","mistake | error | discrepancy","1298420"),
    ("試行錯誤","しこうさくご","n|vs|vt","thử và sai | mò mẫm thử nghiệm","trial and error","1312410"),
    ("手探り","てさぐり","n|vs|vt","mò mẫm | dò dẫm | sờ soạng","fumbling | groping","1328100"),
    ("暗中模索","あんちゅうもさく","n|vs|vt|vi","mò mẫm trong bóng tối | dò dẫm tìm hướng","groping in the dark | exploring without clues","1154660"),
    ("推理","すいり","n|vs|vt","suy luận | suy lý | trinh thám","reasoning | inference | deduction | mystery genre","1371220"),
    ("推論","すいろん","n|vs|vt","lập luận | suy luận | suy diễn","inference | deduction | reasoning","1371240"),
    ("帰結","きけつ","n|vs|vi","hệ quả | kết quả | kết luận","consequence | result | conclusion","1221320"),
    ("総括","そうかつ","n|vs|vt","tổng kết | khái quát | nhìn lại","summarization | summary | generalization","1401520"),
    ("総合","そうごう","n|vs|vt","tổng hợp | tích hợp | tổng quát","synthesis | combination | integration","1596380"),
    ("統括","とうかつ","n|vs|vt","thống nhất | tổng quản | giám sát","unification | bringing together | control","1449680"),
    ("包括","ほうかつ","n|vs|vt","bao quát | bao gồm | toàn diện","inclusion | complete coverage | comprehensiveness","1515450"),
    ("網羅","もうら","n|vs|vt","bao quát hết | bao trùm | thâu tóm","encompassing | covering exhaustively | comprising","1534450"),
    ("羅列","られつ","n|vs|vt|vi","liệt kê | dàn trải | xếp hàng loạt","enumeration | citation | listing","1547580"),
    ("箇条書き","かじょうがき","n","liệt kê theo gạch đầu dòng | gạch ý","itemized form | itemization","1590280"),
    ("一覧","いちらん","n|vs|vt","danh sách | bảng | xem qua | liếc qua","look | glance | summary | list | table | catalog","1167180"),
    ("目録","もくろく","n","mục lục | danh mục | bảng kê","catalogue | inventory | list | table of contents","1535710"),
    ("便覧","びんらん","n","sổ tay | cẩm nang | sách hướng dẫn","handbook | manual | compendium","1583970"),
    ("要覧","ようらん","n","bản tóm lược | sổ tay tổng quan | tài liệu khái quát","outline | summary | survey | handbook","1662260"),
    ("発掘","はっくつ","n|vs|vt","khai quật | đào lên | phát hiện (tài năng)","excavation | digging up | discovery (of talent)","1477290"),
    ("採掘","さいくつ","n|vs|vt","khai thác (mỏ) | đào (khoáng sản)","mining | digging | working (a mine)","1294750"),
    ("発祥","はっしょう","n|vs|vi","khởi nguồn | phát tích | nơi ra đời","origin | birthplace","1477520"),
    ("原産","げんさん","n|adj-no","nơi sản xuất gốc | xuất xứ | nguồn gốc","place of origin | habitat","1261470"),
    ("由緒","ゆいしょ","n","lai lịch | nguồn gốc | dòng dõi","history | pedigree | lineage","1541780"),
    ("来歴","らいれき","n","lai lịch | quá trình | tiểu sử","history | career","1548340"),
    ("履歴","りれき","n","sơ yếu lý lịch | quá trình | lịch sử (log)","personal history | career | log | record","1549810"),
    ("前歴","ぜんれき","n","tiền sử | lý lịch trước đây | quá khứ","personal history","1394200"),
    ("功名","こうみょう","n","công danh | chiến công | tiếng tăm","great achievement | glorious deed | fame","1275090"),
    ("名門","めいもん","n","danh gia | gia đình danh giá | (trường, công ty) danh tiếng","distinguished family | prestigious organization","1531860"),
    ("名家","めいか","n","gia đình danh giá | bậc thầy | chuyên gia","distinguished family | great master | expert","1531380"),
    ("旧家","きゅうか","n","gia đình lâu đời | nhà cũ | quê cũ","old-established family | one's old home","1230470"),
    ("家柄","いえがら","n","gia thế | dòng dõi | xuất thân","social standing of a family | lineage | pedigree","1192460"),
    ("系譜","けいふ","n","gia phả | phả hệ | dòng dõi","genealogy | lineage | family tree | pedigree","1251070"),
    ("末裔","まつえい","n","hậu duệ | con cháu | dòng dõi","descendant","1584450"),
    ("先祖","せんぞ","n","tổ tiên | ông bà | tiền nhân","ancestor | forefather","1388030"),
    ("親類","しんるい","n","họ hàng | bà con | thân thích","relative | relation | kin","1365420"),
    ("縁者","えんじゃ","n","người thân | họ hàng | thân thuộc","relative | relation","1177580"),
    ("姻戚","いんせき","n","thông gia | họ hàng bên vợ/chồng","in-law | relative by marriage","1168780"),
    ("親子","おやこ","n","cha mẹ và con cái | tình phụ tử/mẫu tử","parent and child","1365170"),
    ("従兄弟","いとこ","n","anh em họ | họ hàng cùng vai","cousin","1335290"),
    ("甥","おい","n","cháu trai (con anh chị em)","nephew","1179140"),
    ("姪","めい","n","cháu gái (con anh chị em)","niece","1532940"),
    ("孫","まご","n","cháu (con của con)","grandchild","1406230"),
    ("祖父母","そふぼ","n","ông bà","grandparents","1396850"),
    ("養子","ようし","n","con nuôi | con rể (kế thừa)","adopted child | son-in-law","1547150"),
    ("継母","ままはは","n","mẹ kế","stepmother","1251850"),
    ("里親","さとおや","n","cha mẹ nuôi | người nhận nuôi (thú cưng)","foster parent | (pet) caretaker","1795720"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
