# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-017.csv — 45 rows (Wave 8 pool batch)."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-017.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("居間","いま","N4","n",
        "phòng khách | phòng sinh hoạt",
        "living room (Western style) | sitting room",
        "1231720",
        "居間でテレビを見ます。","いまでテレビをみます。","Tôi xem TV ở phòng khách.","I watch TV in the living room."),
    row("向き合う","むきあう","N4","v5u|vi",
        "đối mặt | hướng về nhau | đối diện | đương đầu (với vấn đề)",
        "to be opposite | to face each other | to confront (an issue) | to face",
        "1277060",
        "問題と向き合います。","もんだいとむきあいます。","Tôi đương đầu với vấn đề.","I confront the problem."),
    row("市場","いちば","N4","n",
        "chợ | khu chợ | nơi mua bán",
        "(town) market | (street) market | marketplace",
        "1308300",
        "市場で野菜を買います。","いちばでやさいをかいます。","Tôi mua rau ở chợ.","I buy vegetables at the market."),
    row("指導","しどう","N4","n|vs|vt",
        "hướng dẫn | lãnh đạo | chỉ đạo | huấn luyện",
        "guidance | leadership | instruction | direction | coaching",
        "1309950",
        "先生の指導を受けます。","せんせいのしどうをうけます。","Tôi nhận sự hướng dẫn của thầy.","I receive the teacher's guidance."),
    row("支援","しえん","N4","n|vs|vt",
        "hỗ trợ | ủng hộ | viện trợ | giúp đỡ",
        "support | backing | aid | assistance",
        "1310100",
        "支援をします。","しえんをします。","Tôi hỗ trợ.","I provide support."),
    row("森林","しんりん","N4","n|adj-no",
        "rừng | rừng rậm",
        "forest | woods",
        "1362530",
        "森林を守ります。","しんりんをまもります。","Chúng tôi bảo vệ rừng.","We protect the forest."),
    row("選挙","せんきょ","N4","n|vs|vt",
        "cuộc bầu cử | bầu cử",
        "election",
        "1392190",
        "選挙に投票します。","せんきょにとうひょうします。","Tôi bỏ phiếu trong cuộc bầu cử.","I vote in the election."),
    row("部門","ぶもん","N4","n|adj-no",
        "bộ phận | chi nhánh | lĩnh vực | phân ngành | danh mục",
        "division (of a larger group) | branch | field | class (subclass) | group | category | department",
        "1499540",
        "部門を担当します。","ぶもんをたんとうします。","Tôi phụ trách bộ phận.","I am in charge of the department."),
    row("腹痛","ふくつう","N4","n",
        "đau bụng | đau dạ dày",
        "stomach ache | abdominal pain",
        "1501230",
        "腹痛があります。","ふくつうがあります。","Tôi bị đau bụng.","I have a stomach ache."),
    row("文化財","ぶんかざい","N4","n",
        "di sản văn hóa | tài sản văn hóa",
        "cultural assets | cultural property",
        "1505150",
        "文化財を守ります。","ぶんかざいをまもります。","Chúng tôi bảo vệ di sản văn hóa.","We protect cultural assets."),
    row("目次","もくじ","N4","n",
        "mục lục | bảng nội dung",
        "table of contents | contents",
        "1535460",
        "目次を確認します。","もくじをかくにんします。","Tôi kiểm tra mục lục.","I check the table of contents."),
    row("乗せる","のせる","N4","v1|vt",
        "đặt lên | cho đi nhờ | bốc lên | chở | phát sóng | lừa dối | hòa theo (âm nhạc) | đăng (bài báo)",
        "to place on (something) | to give (someone) a ride | to give a lift | to pick up | to help on board | to load (luggage) | to carry | to take on board | to send out (on the airwaves, etc.) | to deceive | to take for a ride | to (sing) along with (musical accompaniment) | to let (someone) take part | to excite (someone) | to publish (an article) | to run (an ad)",
        "1600270",
        "荷物を車に乗せます。","にもつをくるまにのせます。","Tôi bốc hành lý lên xe.","I load the luggage into the car."),
    row("胃","い","N4","n",
        "dạ dày | chòm sao Vị (trong 28 chòm sao)",
        "stomach | Chinese \"stomach\" constellation (one of the 28 mansions)",
        "1158500",
        "胃が痛いです。","いがいたいです。","Dạ dày tôi đau.","My stomach hurts."),
    row("海岸","かいがん","N4","n",
        "bờ biển | bãi biển | bờ kè",
        "seashore | coast | seaside | waterfront | beach",
        "1201280",
        "海岸を散歩します。","かいがんをさんぽします。","Tôi tản bộ dọc bờ biển.","I walk along the coast."),
    row("世界遺産","せかいいさん","N4","n",
        "di sản thế giới | khu di sản thế giới",
        "World Heritage (site)",
        "2078260",
        "世界遺産を訪れます。","せかいいさんをおとずれます。","Tôi thăm khu di sản thế giới.","I visit a World Heritage site."),
    row("床","しょう","N4","ctr",
        "đơn vị đếm giường",
        "counter for beds",
        "2085520",
        "病室に三床あります。","びょうしつにさんしょうあります。","Phòng bệnh có ba giường.","There are three beds in the hospital room."),
    row("平和","ピンフ","N4","n",
        "Pinfu (tay bài mahjong thắng với chuỗi, đôi thường và chờ mở)",
        "concealed winning hand consisting of chows, a pair that isn't a value pair, and an open wait",
        "2749750",
        "平和を上がります。","ピンフをあがります。","Tôi thắng bằng Pinfu.","I win with a Pinfu hand."),
    row("水道代","すいどうだい","N4","n",
        "hóa đơn nước | tiền nước",
        "water bill",
        "2828539",
        "水道代を払います。","すいどうだいをはらいます。","Tôi trả tiền nước.","I pay the water bill."),
    row("バッテリー","バッテリー","N4","n",
        "pin | ắc-quy | cặp đôi ném-bắt (bóng chày)",
        "battery | battery (pitcher and catcher)",
        "1099210",
        "バッテリーが切れます。","バッテリーがきれます。","Pin hết.","The battery runs out."),
    row("筋","すじ","N4","n|n-suf|adj-no|suf|ctr",
        "cơ bắp | gân | sợi | đường | vân | lý do | cốt truyện | nguồn gốc | tài năng | đơn vị đếm vật dài",
        "muscle | tendon | sinew | vein | artery | fiber | fibre | string | line | stripe | streak | reason | logic | plot | storyline | lineage | descent | aptitude | talent | source (of information, etc.) | channel | counter for long thin things",
        "1241750",
        "筋を鍛えます。","すじをきたえます。","Tôi rèn luyện cơ bắp.","I train my muscles."),
    row("原稿","げんこう","N4","n",
        "bản thảo | bản nháp | ghi chú | bài đóng góp",
        "manuscript | copy | draft | notes | contribution",
        "1261340",
        "原稿を書きます。","げんこうをかきます。","Tôi viết bản thảo.","I write a manuscript."),
    row("慌てる","あわてる","N4","v1|vi",
        "hoảng loạn | lúng túng | hoảng hốt | vội vàng | hấp tấp",
        "to become confused (disconcerted, disorganized, disorganised) | to be flustered | to panic | to hurry | to rush | to hasten",
        "1278830",
        "慌てないでください。","あわてないでください。","Xin đừng hoảng loạn.","Please don't panic."),
    row("散らかす","ちらかす","N4","v5s|vt",
        "làm lộn xộn | để bừa bộn | làm loạn",
        "to scatter around | to leave untidy | to make a mess",
        "1303420",
        "部屋を散らかします。","へやをちらかします。","Tôi làm phòng bừa bộn.","I make a mess in the room."),
    row("散らかる","ちらかる","N4","v5r|vi",
        "bừa bộn | lộn xộn | vương vãi",
        "to be in disorder | to lie scattered around",
        "1303430",
        "部屋が散らかります。","へやがちらかります。","Phòng bừa bộn.","The room is in disorder."),
    row("思い込む","おもいこむ","N4","v5m|vi",
        "tin tưởng chắc chắn | có ấn tượng (rằng) | quyết tâm | cố chấp | ám ảnh (bởi suy nghĩ)",
        "to be convinced (that) | to be under the impression (that) | to feel sure (that) | to assume (that) | to make up one's mind | to set one's heart on | to be determined (to do) | to be bent on | to be obsessed (with a thought, idea, etc.) | to think about obsessively",
        "1309230",
        "成功できると思い込みます。","せいこうできるとおもいこみます。","Tôi tin chắc có thể thành công.","I am convinced I can succeed."),
    row("演奏","えんそう","N4","n|vs|vt",
        "biểu diễn âm nhạc | trình diễn",
        "musical performance",
        "1607520",
        "ピアノを演奏します。","ピアノをえんそうします。","Tôi biểu diễn piano.","I perform on the piano."),
    row("指示","しじ","N4","n|vs|vt",
        "chỉ thị | chỉ dẫn | chỉ định | hướng dẫn",
        "indication | denotation | designation | instructions | directions",
        "1309800",
        "指示に従います。","しじにしたがいます。","Tôi làm theo chỉ thị.","I follow the instructions."),
    row("支持","しじ","N4","n|vs|vt",
        "ủng hộ | hậu thuẫn | tán thành | chống đỡ",
        "support | backing | endorsement | approval | propping up | holding up",
        "1310150",
        "計画を支持します。","けいかくをしじします。","Tôi ủng hộ kế hoạch.","I support the plan."),
    row("資源","しげん","N4","n",
        "tài nguyên",
        "resources",
        "1312720",
        "資源を節約します。","しげんをせつやくします。","Tôi tiết kiệm tài nguyên.","I save resources."),
    row("資料","しりょう","N4","n",
        "tài liệu | dữ liệu | thông tin",
        "material | materials | data | information | documents",
        "1312820",
        "資料を集めます。","しりょうをあつめます。","Tôi thu thập tài liệu.","I collect materials."),
    row("寝室","しんしつ","N4","n",
        "phòng ngủ",
        "bedroom",
        "1360140",
        "寝室で休みます。","しんしつでやすみます。","Tôi nghỉ ngơi trong phòng ngủ.","I rest in the bedroom."),
    row("草原","そうげん","N4","n",
        "đồng cỏ | thảo nguyên | đồng bằng cỏ",
        "grassy field | grassland | meadow | grass-covered plain | savannah | prairie | steppe",
        "1401970",
        "草原を歩きます。","そうげんをあるきます。","Tôi đi bộ trên đồng cỏ.","I walk on the grassland."),
    row("大陸","たいりく","N4","n|adj-no",
        "lục địa | đại lục | châu lục",
        "continent | continental Asia (esp. mainland China) | continental Europe",
        "1415150",
        "大陸を旅行します。","たいりくをりょこうします。","Tôi đi du lịch châu lục.","I travel the continent."),
    row("貧困","ひんこん","N4","n|adj-na|adj-no",
        "nghèo đói | bần cùng | thiếu thốn",
        "poverty | penury | need | destitution | shortage | lack | want",
        "1490830",
        "貧困を撲滅します。","ひんこんをぼくめつします。","Chúng tôi xóa đói giảm nghèo.","We eliminate poverty."),
    row("分ける","わける","N4","v1|vt",
        "chia | phân chia | tách ra | phân loại | chia sẻ | phân phối | phân biệt | hòa giải",
        "to divide (into) | to split (into) | to part | to separate | to divide up | to classify | to sort out | to share | to distribute | to deal out | to dish out | to distinguish | to discriminate | to differentiate (between) | to break up (a fight) | to mediate | to call a draw | to tie",
        "1503000",
        "班を分けます。","はんをわけます。","Tôi chia thành các nhóm.","I divide into groups."),
    row("雰囲気","ふんいき","N4","n",
        "bầu không khí | không khí | tâm trạng | khí quyển",
        "atmosphere | mood | ambience | ambiance | aura | feel | a certain air | presence | (Earth's) atmosphere",
        "1505070",
        "雰囲気が良いです。","ふんいきがよいです。","Bầu không khí rất tốt.","The atmosphere is nice."),
    row("平和","へいわ","N4","n|adj-na",
        "hòa bình | hài hòa",
        "peace | harmony",
        "1508070",
        "世界平和を願います。","せかいへいわをねがいます。","Tôi mong muốn hòa bình thế giới.","I wish for world peace."),
    row("役割","やくわり","N4","n",
        "vai trò | phần việc | nhiệm vụ",
        "part | assigning (allotment of) parts | role | duties",
        "1538000",
        "重要な役割を果たします。","じゅうようなやくわりをはたします。","Tôi đảm nhận vai trò quan trọng.","I play an important role."),
    row("取引","とりひき","N4","n|vs|vt",
        "giao dịch | kinh doanh | thỏa thuận",
        "transactions | dealings | business",
        "1599120",
        "取引を行います。","とりひきをおこないます。","Chúng tôi thực hiện giao dịch.","We conduct transactions."),
    row("打ち消す","うちけす","N4","v5s|vt",
        "phủ nhận | bác bỏ | phủ định | lấn át (âm thanh)",
        "to deny | to contradict | to negate (esp. a sound) | to drown out",
        "1609310",
        "うわさを打ち消します。","うわさをうちけします。","Tôi bác bỏ tin đồn.","I deny the rumor."),
    row("間違う","まちがう","N4","v5u|vi|vt",
        "nhầm lẫn | sai | không đúng | nhầm (cái này với cái kia)",
        "to be mistaken | to be incorrect | to be wrong | to make a mistake (in) | to do incorrectly | to get wrong | to mistake (one thing with another) | to confuse",
        "1611610",
        "名前を間違います。","なまえをまちがいます。","Tôi nhầm lẫn tên.","I get the name wrong."),
    row("湖","こ","N4","suf",
        "hồ (trong địa danh)",
        "lake (in place names)",
        "2087990",
        "琵琶湖を訪れます。","びわこをおとずれます。","Tôi thăm hồ Biwa.","I visit Lake Biwa."),
    row("生産","せいざん","N4","n",
        "sinh đẻ tự nhiên | sinh con sống",
        "live birth",
        "2092600",
        "生産を支援します。","せいざんをしえんします。","Tôi hỗ trợ việc sinh đẻ.","I support live birth."),
    row("ノートパソコン","ノートパソコン","N4","n",
        "máy tính xách tay | laptop",
        "laptop (computer) | notebook (computer)",
        "2257490",
        "ノートパソコンを使います。","ノートパソコンをつかいます。","Tôi dùng máy tính xách tay.","I use a laptop computer."),
    row("寒気","かんき","N4","n",
        "lạnh | sự lạnh giá | không khí lạnh",
        "cold | coldness | cold air",
        "2866134",
        "寒気が入ります。","かんきがはいります。","Không khí lạnh tràn vào.","Cold air comes in."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
