# -*- coding: utf-8 -*-
"""Build N3 ready wave 047 — 95 freshly-curated N3 emotion + economy/work nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-047.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("恐怖","きょうふ","n|vs|vt|vi","sợ hãi | khiếp sợ | kinh hoàng","fear | dread | terror | horror","1236750"),
    ("恐れ","おそれ","n","nỗi sợ | lo ngại | nguy cơ | sự kính sợ","fear | anxiety | risk | danger | awe","1236660"),
    ("興奮","こうふん","n|vs|vi","phấn khích | kích động | hưng phấn","excitement | stimulation | agitation | arousal","1238380"),
    ("感心","かんしん","n|vs|adj-na","khâm phục | thán phục | đáng khen","admiration | being impressed | admirable | praiseworthy","1212450"),
    ("自信","じしん","n","tự tin | sự tự tin","self-confidence | confidence (in oneself)","1317970"),
    ("誇り","ほこり","n","niềm tự hào | sự hãnh diện","pride | boast | credit (to)","1267740"),
    ("不平","ふへい","n|adj-na","bất bình | bất mãn | than phiền","discontent | dissatisfaction | complaint | grievance","1494790"),
    ("苦痛","くつう","n","đau đớn | khổ sở | dằn vặt","pain | agony | suffering | distress","1244560"),
    ("苦悩","くのう","n|vs|vi","khổ não | đau khổ | dằn vặt tinh thần","(mental) agony | anguish | suffering | distress","1244610"),
    ("悩み","なやみ","n","nỗi phiền muộn | lo lắng | vấn đề trăn trở","trouble | worry | distress | anguish | problem","1469850"),
    ("嫉妬","しっと","n|vs|vt|vi","ghen tị | đố kỵ | ghen tuông","jealousy | envy","1320280"),
    ("恨み","うらみ","n","oán hận | hận thù | hối tiếc","resentment | grudge | malice | regret","1289740"),
    ("同情","どうじょう","n|vs|vi","đồng cảm | thương cảm | thông cảm","sympathy | compassion | pity","1452720"),
    ("哀れ","あわれ","n|adj-na","đáng thương | bi ai | trắc ẩn","pity | sorrow | misery | compassion | pitiful","1150110"),
    ("愛情","あいじょう","n","tình yêu | tình cảm | tình thương","love | affection","1150860"),
    ("親しみ","したしみ","n","sự thân thiết | gần gũi | thân thuộc","intimacy | affection | familiarity","1609880"),
    ("油断","ゆだん","n|vs|vi","chủ quan | lơ là | mất cảnh giác","negligence | carelessness | unpreparedness","1538690"),
    ("用心","ようじん","n|vs|vt|vi","đề phòng | thận trọng | cảnh giác","care | precaution | caution","1546310"),
    ("覚悟","かくご","n|vs|vt","sẵn sàng | quyết tâm | chuẩn bị tinh thần","readiness | preparedness | resolution | determination","1206080"),
    ("辛抱","しんぼう","n|vs|vt|vi","kiên nhẫn | nhẫn nhịn | chịu đựng","patience | endurance | perseverance","1365930"),
    ("忍耐","にんたい","n|vs|vt","nhẫn nại | kiên trì | nhẫn nhịn","endurance | perseverance | patience","1467500"),
    ("苦心","くしん","n|vs|vi","khổ tâm | dày công | nỗ lực vất vả","pains | hard work | effort | trouble","1244530"),
    ("相場","そうば","n","giá thị trường | đầu cơ | định mức thông thường","market price | speculation | conventional estimation","1401070"),
    ("金融","きんゆう","n","tài chính | tiền tệ | tín dụng","finance | financing | credit | circulation of money","1243290"),
    ("預金","よきん","n|vs|vt|vi","tiền gửi | tài khoản ngân hàng","deposit | bank account","1545020"),
    ("資金","しきん","n","vốn | quỹ | nguồn vốn","funds | capital","1312700"),
    ("資本","しほん","n","tư bản | vốn","funds | capital","1312780"),
    ("財産","ざいさん","n","tài sản | của cải | gia sản","property | fortune | assets","1296820"),
    ("資産","しさん","n","tài sản | tài lực | của cải","property | fortune | means | assets","1312750"),
    ("財政","ざいせい","n","tài chính (công) | ngân sách | tình hình tài chính","public finance | financial affairs | financial situation","1296830"),
    ("報酬","ほうしゅう","n","thù lao | tiền công | phần thưởng","remuneration | recompense | reward","1515700"),
    ("賃金","ちんぎん","n","tiền lương | tiền công | tiền thuê","wages | pay | rental payment","1431990"),
    ("所得","しょとく","n","thu nhập | lợi tức","income | earnings","1343360"),
    ("収益","しゅうえき","n","lợi nhuận | doanh thu | thu lợi","earnings | proceeds | returns | revenue","1330500"),
    ("流通","りゅうつう","n|vs|vi","lưu thông | phân phối | lưu hành","circulation (of money, goods) | distribution | ventilation","1552440"),
    ("販売","はんばい","n|vs|vt","bán hàng | tiêu thụ | kinh doanh","sale | sales | selling | marketing","1481800"),
    ("営業","えいぎょう","n|vs|vt","kinh doanh | hoạt động | bán hàng","business | trade | operations | sales","1173430"),
    ("商売","しょうばい","n|vs|vi","buôn bán | kinh doanh | nghề nghiệp","trade | business | commerce | occupation","1347200"),
    ("商業","しょうぎょう","n","thương mại | thương nghiệp","commerce | trade | business","1346740"),
    ("工業","こうぎょう","n","công nghiệp (chế tạo)","(manufacturing) industry","1278040"),
    ("倒産","とうさん","n|vs|vi","phá sản | vỡ nợ | sụp đổ (doanh nghiệp)","(corporate) bankruptcy | insolvency | commercial failure","1445890"),
    ("破産","はさん","n|vs|vi","phá sản | vỡ nợ","bankruptcy | insolvency","1471330"),
    ("失業","しつぎょう","n|vs|vi","thất nghiệp | mất việc","unemployment | losing one's job","1319860"),
    ("雇用","こよう","n|vs|vt","tuyển dụng | thuê mướn | việc làm","employment | hire","1267860"),
    ("労働","ろうどう","n|vs|vi","lao động | làm việc","labor | work","1606450"),
    ("勤務","きんむ","n|vs|vi","làm việc | công tác | nhiệm vụ","service | duty | work","1241070"),
    ("通勤","つうきん","n|vs|vi","đi làm | đi lại tới chỗ làm","commuting to work","1433140"),
    ("事業","じぎょう","n","sự nghiệp | dự án | hoạt động kinh doanh","business | enterprise | venture | undertaking | project","1313670"),
    ("業務","ぎょうむ","n","nghiệp vụ | công việc | hoạt động","business | work | operations | duties","1239540"),
    ("職務","しょくむ","n","chức vụ | nhiệm vụ công việc","professional duties","1357580"),
    ("任務","にんむ","n","nhiệm vụ | sứ mệnh | chức trách","duty | function | mission | task | role","1467260"),
    ("免許","めんきょ","n|vs|vt","giấy phép | bằng | chứng chỉ","license | permission | permit | certificate","1533130"),
    ("証明書","しょうめいしょ","n","giấy chứng nhận | giấy chứng thực","certificate | credentials | testimonial","1351700"),
    ("契約書","けいやくしょ","n","hợp đồng (văn bản) | bản thỏa thuận","(written) contract | agreement","1250210"),
    ("納税","のうぜい","n|vs|vt|vi","nộp thuế | đóng thuế","payment of taxes","1470060"),
    ("徴収","ちょうしゅう","n|vs|vt","thu (phí, thuế) | thu nộp","collection (of fees, taxes) | levy","1428110"),
    ("徴税","ちょうぜい","n|vs|vt|vi","thu thuế | đánh thuế","tax collection | taxation","1428120"),
    ("納付","のうふ","n|vs|vt","nộp | đóng (tiền) | giao nộp","payment | supply","1470110"),
    ("支給","しきゅう","n|vs|vt","chi trả | cấp phát | trợ cấp","provision | supply | payment | allowance","1310130"),
    ("歳出","さいしゅつ","n","chi tiêu hàng năm | chi ngân sách","annual expenditure (of a state, organization)","1294960"),
    ("歳入","さいにゅう","n","thu nhập hàng năm | thu ngân sách","annual revenue (government) | budget receipts","1294970"),
    ("収支","しゅうし","n","thu chi | cán cân thu chi","income and expenditure","1330640"),
    ("黒字","くろじ","n","thặng dư | lãi | có lời","(being in) the black | surplus","1287710"),
    ("赤字","あかじ","n","thâm hụt | thua lỗ | bút đỏ (sửa bài)","(being in) the red | deficit | corrections in red","1383440"),
    ("借入","しゃくにゅう","n|vs","vay | khoản vay | mượn","loan | borrowing","2078920"),
    ("返済","へんさい","n|vs|vt","trả nợ | hoàn trả | thanh toán","repayment | reimbursement | redemption","1512210"),
    ("延滞","えんたい","n|vs|vi","quá hạn | chậm trễ | nợ đọng","arrears | (being) overdue | delay (in payment)","1176490"),
    ("滞納","たいのう","n|vs|vt","chậm nộp | nợ đọng | quá hạn nộp","falling behind (with a payment) | non-payment | delinquency","1410940"),
    ("督促","とくそく","n|vs|vt","đốc thúc | hối thúc | giục","urge | demand | importunity","1455390"),
    ("請負","うけおい","n","nhận thầu | nhận khoán | hợp đồng làm","contract (for work) | contracting | undertaking","1751540"),
    ("委託","いたく","n|vs|vt","ủy thác | giao phó | ký gửi","entrusting | consignment | commission","1156160"),
    ("依頼","いらい","n|vs|vt|vi","nhờ vả | yêu cầu | phó thác","request | commission | reliance","1155710"),
    ("納品","のうひん","n|vs|vt|vi","giao hàng | giao sản phẩm","delivery of goods","1470100"),
    ("発注","はっちゅう","n|vs|vt","đặt hàng | đặt mua","ordering (materials) | placing an order","1477710"),
    ("受注","じゅちゅう","n|vs|vt","nhận đơn hàng | nhận đặt hàng","accepting an order | orders received","1329970"),
    ("卸売","おろしうり","n","bán buôn | bán sỉ","wholesale | wholesaling","1589540"),
    ("小売","こうり","n|vs|vt","bán lẻ","retail","1593050"),
    ("販路","はんろ","n","thị trường tiêu thụ | đầu ra | kênh bán","market (for goods) | outlet (for selling)","1481880"),
    ("顧客","こきゃく","n","khách hàng | khách quen","customer | client | patron","1578540"),
    ("得意先","とくいさき","n","khách hàng quen | khách ruột","(regular) customer | client | clientele","1454530"),
    ("業者","ぎょうしゃ","n","nhà cung cấp | nhà thầu | bên kinh doanh","trader | dealer | vendor | supplier | contractor","1239440"),
    ("同業","どうぎょう","n","cùng ngành | đồng nghiệp (cùng nghề)","same trade | same business | same profession","1452160"),
    ("競合","きょうごう","n|vs|vi","cạnh tranh | đối đầu | ganh đua","contention | competition | rivalry","1234100"),
    ("独占","どくせん","n|vs|vt","độc quyền | chiếm độc quyền | giữ riêng","monopoly | exclusivity | keeping to oneself","1455870"),
    ("寡占","かせん","n|vs|vt","độc quyền nhóm | thiểu số kiểm soát thị trường","oligopoly | control of a market","1192620"),
    ("合弁","ごうべん","n","liên doanh | hợp doanh","joint management | joint venture","1285250"),
    ("子会社","こがいしゃ","n","công ty con","subsidiary (company)","1307820"),
    ("本社","ほんしゃ","n","trụ sở chính | công ty mẹ","head office | headquarters | parent company","1522630"),
    ("支社","ししゃ","n","chi nhánh | văn phòng chi nhánh","branch office","1310170"),
    ("支店","してん","n","chi nhánh | cửa hàng chi nhánh","branch office | branch store","1310230"),
    ("本店","ほんてん","n","cửa hàng chính | trụ sở chính","head office | main store | flagship store","1523020"),
    ("営業所","えいぎょうしょ","n","văn phòng kinh doanh | địa điểm kinh doanh","business office | place of business","1613520"),
    ("事務所","じむしょ","n","văn phòng | trụ sở làm việc","office","1314400"),
    ("工場","こうじょう","n","nhà máy | xưởng | xí nghiệp","factory | plant | mill | workshop","1578700"),
    ("店舗","てんぽ","n","cửa hàng | cửa tiệm | gian hàng","shop | store | establishment","1440800"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
