# -*- coding: utf-8 -*-
"""Build N1 ready wave 028 — 慣用句 idiomatic expressions (set 28)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-028.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("油を売る","あぶらをうる","exp|v5r","cà kê | lề mề trốn việc | tán gẫu lãng phí thời gian","to loaf around (on the job) | to idle one's time away","1538610"),
    ("胸を撫で下ろす","むねをなでおろす","exp|v5s","thở phào nhẹ nhõm | trút được gánh nặng | yên tâm","to be relieved | to feel relieved","2528130"),
    ("腹を割る","はらをわる","exp|v5r","nói thẳng ruột gan | thành thật | trải lòng | bộc bạch","to be frank | to drop all pretense","2247100"),
    ("腹を括る","はらをくくる","exp|v5r","quyết tâm | đánh liều | chuẩn bị tinh thần | hạ quyết tâm","to prepare oneself (for the worst) | to resolve","2247100"),
    ("腰を据える","こしをすえる","exp|v1","an cư | tập trung dốc sức | yên vị | trụ vững làm tới cùng","to settle down (to do) | to concentrate all one's energy","1876650"),
    ("腰が低い","こしがひくい","exp|adj-i","khiêm tốn | nhún nhường | nhã nhặn | lễ độ","humble | modest","2185570"),
    ("顔が広い","かおがひろい","exp","quen biết rộng | giao thiệp rộng | nhiều mối quan hệ","well connected | having a wide circle of acquaintances","2139970"),
    ("顔に泥を塗る","かおにどろをぬる","exp|v5r","bôi tro trát trấu | làm bẽ mặt | làm nhục | bôi nhọ thanh danh","to bring disgrace on | to put to shame","1864210"),
    ("口が堅い","くちがかたい","exp|adj-i","kín miệng | biết giữ bí mật | kín đáo | chắc chắn","tight-lipped | able to keep a secret","2134550"),
    ("口を割る","くちをわる","exp|v5r","khai ra | thú nhận | hé miệng tiết lộ | mở miệng nói","to confess | to disclose | to spill the beans","1872200"),
    ("口車に乗る","くちぐるまにのる","exp|v5r","mắc lừa lời ngọt | bị dụ dỗ | nghe lời đường mật","to fall for (smooth talk) | to be taken in","2836490"),
    ("歯が立たない","はがたたない","exp|adj-i","không địch nổi | bó tay | không nhằm nhò | quá khó","unable to compete with | not able to make a dent","1313030"),
    ("歯に衣着せぬ","はにきぬきせぬ","exp|adj-f","nói thẳng nói thật | bộc trực | không úp mở | thẳng tính","outspoken | forthright | frank | direct","2399560"),
    ("目を疑う","めをうたがう","exp|v5u","không tin vào mắt mình | nghi ngờ mắt mình | sửng sốt","to doubt one's own eyes","2755550"),
    ("目を盗む","めをぬすむ","exp|v5m","lén lút | qua mắt | làm vụng trộm sau lưng","to do behind someone's back | to do without being seen","2227030"),
    ("目の上のたんこぶ","めのうえのたんこぶ","exp","cái gai trong mắt | kẻ chướng mắt | vật cản đường","a thorn in one's side | a person standing in one's way","2153150"),
    ("鼻にかける","はなにかける","exp|v1","vênh váo | tự đắc | khoe khoang | lên mặt","to be full of pride | to be boastful","2034310"),
    ("鼻が高い","はながたかい","exp|adj-i","hãnh diện | tự hào | nở mày nở mặt | vênh mặt","proud | feeling proud","1486730"),
    ("耳が痛い","みみがいたい","exp|adj-i","nghe mà nhói lòng | trúng tim đen | chạm tự ái | đau tai","being painfully true (e.g. reprimand) | striking home","2578130"),
    ("首を突っ込む","くびをつっこむ","exp|v5m","chõ mũi vào | dây dưa vào | can dự | tọc mạch","to poke one's nose into | to meddle in | to take interest in","2016320"),
    ("首を長くする","くびをながくする","exp|vs-i","mong mỏi | trông ngóng | dài cổ chờ đợi","to eagerly look forward to","1329250"),
    ("肩を持つ","かたをもつ","exp|v5t","bênh vực | đứng về phía | ủng hộ | che chở","to side with | to support (someone)","1258980"),
    ("肩の荷が下りる","かたのにがおりる","exp|v1","trút gánh nặng | nhẹ cả người | thoát gánh lo","to feel relieved of one's burden","2119420"),
    ("手を焼く","てをやく","exp|v5k","bó tay | lúng túng | đau đầu vì | khốn khổ với","to not know what to do with | to have difficulty with","2028670"),
    ("手に余る","てにあまる","exp|v5r","quá sức | ngoài tầm | không kham nổi | vượt khả năng","to be beyond one's capacities | to be unmanageable","1895820"),
    ("手を打つ","てをうつ","exp|v5t","ra tay phòng bị | đi nước cờ | thỏa thuận | vỗ tay","to take measures | to strike a bargain | to clap hands","2200440"),
    ("手玉に取る","てだまにとる","exp|v5r","xỏ mũi | thao túng | điều khiển như con rối | dắt mũi","to lead by the nose | to twist around one's finger","2089280"),
    ("足を引っ張る","あしをひっぱる","exp|v5r","kéo lùi | cản trở | níu chân | phá đám","to hold (someone) back | to stand in the way of","2119830"),
    ("足が出る","あしがでる","exp|v1","vượt ngân sách | lạm chi | thâm hụt | lòi đuôi (bí mật)","to exceed the budget | to go into the red","1404640"),
    ("足を洗う","あしをあらう","exp|v5u","rửa tay gác kiếm | hoàn lương | từ bỏ (việc xấu) | đoạn tuyệt","to wash one's hands of | to go straight | to quit","1856360"),
    ("舌を巻く","したをまく","exp|v5k","kinh ngạc | thán phục | trầm trồ | sửng sốt","to be amazed | to be deeply impressed","2274510"),
    ("喉から手が出る","のどからてがでる","exp|v1","thèm muốn cháy bỏng | khao khát tột độ | thèm rỏ dãi","wanting something so badly one can almost taste it","2028680"),
    ("骨が折れる","ほねがおれる","exp|v1","vất vả | cực nhọc | gian nan | tốn công sức","to be hard (to do) | to be laborious","1627350"),
    ("骨を折る","ほねをおる","exp|v5r","dốc sức | cố gắng hết mình | nhọc công | gãy xương","to make efforts | to take pains","1908600"),
    ("腑に落ちない","ふにおちない","exp|adj-i","không thông | khó hiểu | không thuyết phục | thấy gợn","cannot understand | unconvincing | doesn't ring true","1728810"),
    ("肝に銘じる","きもにめいじる","exp|v1","khắc cốt ghi tâm | tạc dạ | ghi lòng tạc dạ | ghi nhớ kỹ","to take to heart | to engrave on one's heart | to bear in mind","1869730"),
    ("胸を張る","むねをはる","exp|v5r","ưỡn ngực tự hào | đường hoàng | hiên ngang | tự tin","to throw out one's chest | to be puffed up with pride","2029360"),
    ("水を差す","みずをさす","exp|v5s","dội gáo nước lạnh | phá đám | làm cụt hứng | gây chia rẽ","to throw cold water on | to hinder | to estrange","1371290"),
    ("油を絞る","あぶらをしぼる","exp|v5r","mắng cho một trận | xạc cho té tát | quở trách nặng | ép dầu","to chew out | to reprimand severely | to scold","1538600"),
    ("釘を刺す","くぎをさす","exp|v5s","dặn dò kỹ | cảnh báo trước | nhắc nhở phòng xa | đóng đinh","to give a warning | to remind (a person)","1871830"),
    ("峠を越す","とうげをこす","exp|v5s","qua cơn nguy kịch | vượt giai đoạn khó | qua đỉnh điểm","to pass the peak | to be over the worst","1454430"),
    ("拍車をかける","はくしゃをかける","exp|v1","thúc đẩy | đẩy nhanh | tăng tốc | tiếp thêm động lực","to spur on | to expedite | to encourage","1474810"),
    ("道草を食う","みちくさをくう","exp|v5u","la cà dọc đường | lãng phí thời gian | rong chơi lề mề","to loiter on the way | to waste time","2252740"),
    ("襟を正す","えりをただす","exp|v5s","chỉnh đốn lại | nghiêm túc lại | sửa lại tư thế tác phong","to straighten oneself | to adopt a more serious attitude","1861510"),
    ("お茶を濁す","おちゃをにごす","exp|v5s","lảng tránh | nói cho qua chuyện | đánh trống lảng | ậm ừ","to evade (questions) | to beat around the bush","2102530"),
    ("高をくくる","たかをくくる","exp|v5r","coi thường | xem nhẹ | đánh giá thấp | khinh suất","to underrate | to make light of","1890990"),
    ("泡を食う","あわをくう","exp|v5u","cuống cuồng | hốt hoảng | luống cuống mất bình tĩnh","to be flurried | to be confused | to lose one's head","1517520"),
    ("熱を上げる","ねつをあげる","exp|v1","phát cuồng | mê mệt | say đắm | hăng máu","to become enthusiastic | to have a crush on","1900610"),
    ("気が置けない","きがおけない","exp|adj-i","dễ gần | thoải mái | không câu nệ | dễ chịu","easy to get on with | not needing formality","2089790"),
    ("気に病む","きにやむ","exp|v5m","lo lắng | bận lòng | day dứt | phiền muộn","to worry about | to fret over | to be anxious","2236490"),
    ("板につく","いたにつく","exp|v5k","thành thạo | quen tay | nhuần nhuyễn | vào nếp","to get used to | to become accustomed to","1858410"),
    ("焼け石に水","やけいしにみず","exp","muối bỏ bể | như gió vào nhà trống | chẳng thấm vào đâu | vô ích","a drop in the bucket | too little too late","2152910"),
    ("立て板に水","たていたにみず","exp|n","nói như nước chảy | hoạt ngôn | thao thao bất tuyệt | trôi chảy","eloquence | volubility","1838070"),
    ("猫の手も借りたい","ねこのてもかりたい","exp|adj-i","bận tối mắt | bận rối tay | thiếu người làm trầm trọng","extremely busy | short-handed","1845600"),
    ("猫をかぶる","ねこをかぶる","exp|v5r","giả vờ hiền lành | đeo mặt nạ | giả nai | đóng kịch","to feign friendliness | to play the hypocrite","2275680"),
    ("犬猿の仲","けんえんのなか","exp|n","như chó với mèo | xung khắc | thù địch | không ưa nhau","like cats and dogs | on very bad terms","1258340"),
    ("雀の涙","すずめのなみだ","exp|n","ít ỏi | nhỏ giọt | chẳng đáng là bao | bèo bọt","a drop in the bucket | a pittance","1373570"),
    ("鶴の一声","つるのひとこえ","exp|n","lời phán quyết của bề trên | tiếng nói quyền uy | một lời định đoạt","voice of authority | authoritative pronouncement","2140260"),
    ("虫がいい","むしがいい","exp|adj-ix","ích kỷ | đòi hỏi quá đáng | chỉ nghĩ cho mình | tham lam","selfish | asking too much","1426690"),
    ("腹の虫","はらのむし","exp|n","giun sán | cơn giận trong bụng | tâm trạng | tiếng bụng réo","intestinal worm | feelings affecting one's mood","1628850"),
    ("我を忘れる","われをわすれる","exp|v1","quên cả mình | mất tự chủ | quên hết sự đời | đắm chìm","to forget oneself | to lose control of oneself","2037240"),
    ("身を粉にする","みをこにする","exp|vs-i","làm việc quên mình | dốc hết sức | nai lưng làm | cật lực","to work assiduously | to give one's all","2406640"),
    ("根に持つ","ねにもつ","exp|v5t","ôm hận | để bụng | thù dai | ghim trong lòng","to hold a grudge | to hold something against someone","1290050"),
    ("袂を分かつ","たもとをわかつ","exp|v5t","chia tay | đường ai nấy đi | đoạn tuyệt | cắt đứt quan hệ","to part company with | to break off relations","2078390"),
    ("火花を散らす","ひばなをちらす","exp|v5s","tóe lửa | tranh cãi nảy lửa | giao tranh ác liệt | đối đầu gay gắt","to give off sparks | to have a heated argument","2792180"),
    ("波に乗る","なみにのる","exp|v5r","thuận theo dòng | bắt nhịp thời thế | gặp thời | thuận buồm","to go with the flow | to ride the wave","2087220"),
    ("図に乗る","ずにのる","exp|v5r","được đằng chân lân đằng đầu | làm tới | quá đà | tự mãn","to get carried away | to push one's luck","1855390"),
    ("棚に上げる","たなにあげる","exp|v1","làm ngơ lỗi mình | giả lơ | gác sang một bên | bỏ qua (lỗi mình)","to shut one's eyes to (one's own faults) | to put on a shelf","2086780"),
    ("苦杯","くはい","n","chén đắng | trải nghiệm cay đắng | thất bại ê chề","bitter cup | bitter experience | bitter defeat","1244620"),
    ("苦杯をなめる","くはいをなめる","exp|v1","nếm trải cay đắng | chuốc lấy thất bại | nếm mùi thất bại","to have a bitter experience | to suffer a defeat","2857018"),
    ("御の字","おんのじ","exp|n","quá mãn nguyện | hài lòng lắm rồi | còn gì bằng | tốt quá","most satisfactory | quite enough","1694070"),
    ("心血","しんけつ","n","tâm huyết | cả tấm lòng | toàn bộ sức lực","heart and soul | all one's energy","1360650"),
    ("心血を注ぐ","しんけつをそそぐ","exp|v5g","dồn hết tâm huyết | dốc cả tâm sức | đổ hết tâm can","to put one's heart and soul into","2791840"),
    ("微力","びりょく","n","sức mọn | tài hèn (khiêm) | chút sức lực nhỏ bé | khả năng hạn hẹp","little power | one's poor ability | what little one can do","1486210"),
    ("不問","ふもん","n|n-suf","bỏ qua | làm ngơ | không truy cứu | không hỏi tới","not asking | disregarding | overlooking","1495130"),
    ("不問に付す","ふもんにふす","exp|v5s","bỏ qua lỗi | không truy cứu | cho qua | xí xóa","to disregard (a fault) | to let go unquestioned","1495140"),
    ("無下に","むげに","adv","phũ phàng | thẳng thừng | dứt khoát (từ chối) | lạnh lùng","bluntly (refusing) | flatly | out of hand","1671850"),
    ("矢継ぎ早","やつぎばや","adj-na|adj-no|n","dồn dập | liên tiếp | tới tấp | liên tục (câu hỏi)","in rapid succession (e.g. questions)","1659890"),
    ("横車","よこぐるま","exp|n","ngang ngược | cố chấp | ngang bướng vô lý (横車を押す)","perverseness | obstinacy | something unreasonable","1180830"),
    ("論より証拠","ろんよりしょうこ","exp","trăm nghe không bằng một thấy | bằng chứng hơn lời nói | nói có sách","the proof is in the pudding | evidence beats debate","2187770"),
    ("和して同ぜず","わしてどうぜず","exp","hòa nhi bất đồng | hòa hợp nhưng không a dua | hòa mà không đồng","to harmonize but not agree blindly","1917480"),
    ("枚挙","まいきょ","n|vs|vt|adj-no","liệt kê | kể ra | đếm | nêu từng cái","enumeration","1524620"),
    ("枚挙にいとまがない","まいきょにいとまがない","exp|adj-i","nhiều không kể xiết | vô số | nhiều vô kể | đếm không xuể","too many to count | too numerous to mention","2038540"),
    ("身も蓋もない","みもふたもない","exp|adj-i","nói toạc móng heo | quá thẳng thừng | trắng trợn | phũ phàng","blunt | too direct | outspoken","2120210"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
