# -*- coding: utf-8 -*-
"""Build N2 ready wave 006 — 81 freshly-curated N2 compound verbs (〜込む/〜付く/〜合う/〜返す/〜抜く/〜寄る etc.)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-006.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("見受ける","みうける","v1|vt","bắt gặp | trông thấy | đoán qua vẻ ngoài","to catch sight of | to suppose from appearances","1259690"),
    ("受け持つ","うけもつ","v5t|vt","phụ trách | đảm nhận","to take charge of","1329640"),
    ("入り組む","いりくむ","v5m|vi","rắc rối | phức tạp | rối rắm","to become complicated | to become intricate | to become tangled","1465500"),
    ("黙り込む","だまりこむ","v5m|vi","im bặt | nín lặng | lặng thinh","to say no more | to sink into silence","1534920"),
    ("信じ込む","しんじこむ","v5m|vt","tin chắc | tin sái cổ | đinh ninh","to believe implicitly | to believe firmly","1359060"),
    ("教え込む","おしえこむ","v5m|vt","dạy kỹ | nhồi nhét | rèn cho thấm","to teach thoroughly | to instill | to drum into","1236910"),
    ("座り込む","すわりこむ","v5m|vi","ngồi lì | ngồi bệt | tọa kháng","to sit down (and refuse to move) | to sit in (protest)","1291790"),
    ("寝込む","ねこむ","v5m|vi","ngủ say | nằm liệt giường | ốm liệt","to fall fast asleep | to be confined to one's bed","1360130"),
    ("老け込む","ふけこむ","v5m|vi","già sọm | trở nên già nua","to age | to become old","1980750"),
    ("咳き込む","せきこむ","v5m|vi","ho sặc sụa | ho dữ dội","to cough violently | to have a coughing fit","1852620"),
    ("話し込む","はなしこむ","v5m|vt","mải nói chuyện | trò chuyện say sưa","to be deep in talk","1562320"),
    ("注ぎ込む","そそぎこむ","v5m|vt","rót vào | đổ vào | dồn (tiền, đầu tư)","to pour in (liquids, money) | to pump in (investment)","1581720"),
    ("流れ込む","ながれこむ","v5m|vi","chảy vào | tràn vào | đổ vào","to flow into | to pour into | to stream into","1552150"),
    ("寝付く","ねつく","v5k|vi","đi ngủ | ngủ thiếp | nằm bệnh","to fall asleep | to be laid up (with a cold)","1360280"),
    ("住み着く","すみつく","v5k|vi","định cư | an cư | ở yên","to settle (in a place) | to settle down","1334020"),
    ("噛み付く","かみつく","v5k|vi","cắn | táp | gắt gỏng | nổi cáu","to bite (at) | to snap at | to flare up at","1209220"),
    ("巻き付く","まきつく","v5k","quấn quanh | cuốn vào","to twine around","1211180"),
    ("助け合う","たすけあう","v5u|vi","giúp đỡ lẫn nhau | tương trợ","to help each other | to cooperate","1344430"),
    ("認め合う","みとめあう","v5u","công nhận lẫn nhau | thừa nhận nhau","to mutually recognize | to accept","2398990"),
    ("愛し合う","あいしあう","v5u","yêu nhau | thương yêu nhau","to love one another | to be affectionate toward each other","1981950"),
    ("支え合う","ささえあう","v5u","nâng đỡ nhau | tương trợ lẫn nhau","to support each other","2397990"),
    ("競い合う","きそいあう","v5u","đua tranh | cạnh tranh nhau","to compete with | to vie for","1630140"),
    ("奪い合う","うばいあう","v5u|vt","giành giật | tranh giành","to scramble for | to struggle for | to fight for","1416310"),
    ("取り合う","とりあう","v5u|vt|vi","nắm tay nhau | tranh giành | để tâm | đối đáp","to take each other's hands | to scramble for | to pay attention to","1327000"),
    ("分かち合う","わかちあう","v5u|vt","chia sẻ với nhau","to share","1502890"),
    ("隣り合う","となりあう","v5u|vi","kề nhau | sát cạnh nhau","to adjoin each other | to sit side by side","1598830"),
    ("出くわす","でくわす","v5s|vi","tình cờ gặp | đụng phải | bắt gặp","to happen to meet | to come across | to run into","1337950"),
    ("言い合う","いいあう","v5u|vt|vi","nói qua nói lại | cãi vã | tranh luận","to say to each other | to quarrel | to dispute","1587000"),
    ("通じ合う","つうじあう","v5u|vi","thấu hiểu nhau | tâm đầu ý hợp","to be understood by each other | to communicate with each other","1432890"),
    ("分かり合う","わかりあう","v5u|vi","hiểu nhau | đồng cảm","to understand each other","2038420"),
    ("連れ立つ","つれだつ","v5t|vi","đi cùng nhau | sánh bước","to go together | to go in company with","1559360"),
    ("思い返す","おもいかえす","v5s|vt","nghĩ lại | hồi tưởng | đổi ý","to re-think | to think back upon | to change one's mind","1309400"),
    ("見返す","みかえす","v5s|vt|vi","nhìn lại | xem lại | lật ngược thế cờ (cho bõ)","to look at again | to re-examine | to prove oneself superior","1260050"),
    ("聞き返す","ききかえす","v5s|vt","nghe lại | hỏi lại","to listen again | to ask again | to ask for a repeated explanation","1591060"),
    ("巻き返す","まきかえす","v5s|vt","cuốn lại | lội ngược dòng | gỡ lại","to rewind | to rally | to recover | to come back","2463100"),
    ("折り返す","おりかえす","v5s|vt","gấp lại | quay đầu | hồi đáp lại","to fold back | to turn back | to return (a call)","1385900"),
    ("裏返す","うらがえす","v5s|vt","lộn trái | lật ngược | lật lại","to turn inside out | to turn over","1550630"),
    ("蒸し返す","むしかえす","v5s|vt","hấp lại | khơi lại (chuyện cũ) | nhai lại","to reheat | to bring up again (an old problem) | to rehash","1356890"),
    ("寝返る","ねがえる","v5r|vi","trở mình | phản bội | trở mặt","to roll over (in bed) | to betray | to change sides","1360310"),
    ("持て成す","もてなす","v5s|vt","tiếp đãi | chiêu đãi | hiếu khách","to treat (a guest) | to entertain | to be hospitable to","1315740"),
    ("勝ち抜く","かちぬく","v5k|vi","thắng liên tiếp | vượt qua (vòng) | giành thắng cuối","to win through | to win game after game | to come out on top","1346120"),
    ("生き抜く","いきぬく","v5k|vi","sống sót | sống đến cùng | trụ vững","to live through | to survive","1851550"),
    ("耐え抜く","たえぬく","v5k","chịu đựng đến cùng | cố trụ tới cùng","to stick it out (until the end)","2222900"),
    ("考え抜く","かんがえぬく","v5k","suy nghĩ thấu đáo | nghĩ cho tới cùng","to think thoroughly","1281080"),
    ("やり抜く","やりぬく","v5k|vt","làm tới cùng | hoàn thành | theo đến cùng","to carry through | to see through | to accomplish","1846810"),
    ("出し抜く","だしぬく","v5k|vt","qua mặt | chơi xỏ | đi trước một bước","to outwit | to steal a march on | to forestall","1338110"),
    ("突き抜ける","つきぬける","v1|vi","xuyên thủng | đâm xuyên qua","to pierce through | to break through","1456820"),
    ("駆け抜ける","かけぬける","v1|vi","chạy xuyên qua | lướt qua | vượt qua","to run through | to sweep through | to overtake","1244820"),
    ("追い抜く","おいぬく","v5k|vt","vượt qua | qua mặt | bỏ xa","to overtake | to surpass | to outstrip","1432370"),
    ("切り抜く","きりぬく","v5k|vt","cắt ra | cắt rời | trích cắt","to cut out | to clip from | to extract","1384610"),
    ("打ち解ける","うちとける","v1|vi","cởi mở | thân mật | hòa đồng | thoải mái","to open up (to someone) | to become friendly | to feel at ease","1408620"),
    ("差し掛かる","さしかかる","v5r|vi","đến gần | sắp tới | bước vào (giai đoạn) | che phủ","to approach | to be on the verge of | to overhang","1291140"),
    ("見計らう","みはからう","v5u|vt","tự liệu chừng | canh thời điểm | ước lượng","to choose at one's discretion | to estimate (the time for)","1259510"),
    ("振り切る","ふりきる","v5r|vt","hất ra | bứt khỏi (truy đuổi) | dứt khoát | vung hết sức","to shake off | to break away from | to reject | to swing fully","1361250"),
    ("言い切る","いいきる","v5r|vt","khẳng định | quả quyết | nói dứt khoát","to declare | to assert | to state definitively","1264100"),
    ("使い切る","つかいきる","v5r|vt","dùng hết | dùng cạn | xài sạch","to use up | to exhaust | to wear out","1305870"),
    ("出し切る","だしきる","v5r|vt","dốc hết | dùng cạn | gắng hết sức","to use up (all one's strength, ideas) | to do one's best","1849640"),
    ("売り切れる","うりきれる","v1|vi","bán hết | hết hàng","to be sold out","1473880"),
    ("途切れる","とぎれる","v1|vi","gián đoạn | đứt đoạn | ngắt quãng","to break off | to be interrupted | to pause","1598690"),
    ("振り絞る","ふりしぼる","v5r|vt","dồn hết (sức) | gắng hết (can đảm) | gào hết giọng","to use to the full | to muster all of (strength, courage)","1851760"),
    ("締め切る","しめきる","v5r|vt","đóng kín | đóng lại (hết hạn) | ngừng nhận","to close up | to cut off (deadline expired) | to close off","1594600"),
    ("踏ん張る","ふんばる","v5r|vi","gồng mình | trụ vững | cố gắng cầm cự","to brace one's legs | to stand firm | to hold out | to persist","1450280"),
    ("出っ張る","でっぱる","v5r|vi","nhô ra | lồi ra | thò ra","to project | to jut out | to protrude","1338220"),
    ("威張る","いばる","v5r|vi","vênh váo | ra oai | kiêu căng","to put on airs | to swagger | to act arrogantly","1156320"),
    ("欲張る","よくばる","v5r|vi","tham lam | tham | thèm muốn quá độ","to be greedy | to be avaricious | to covet","1547400"),
    ("気張る","きばる","v5r|vi|vt","gồng sức | dồn sức | gắng | chi mạnh tay","to bear down | to exert oneself | to splurge (on)","1850230"),
    ("強張る","こわばる","v5r|vi","cứng đờ | căng cứng | đơ ra","to stiffen | to become stiff | to harden","1609790"),
    ("意地張る","いじばる","v5r|vi","bướng bỉnh | cố chấp | lì lợm","to be stubborn | to be obstinate | to not give in","2399360"),
    ("見回る","みまわる","v5r|vi","đi tuần | tuần tra | đi kiểm tra","to make one's rounds | to patrol","1641610"),
    ("出回る","でまわる","v5r|vi","có mặt trên thị trường | vào mùa | lan truyền","to appear on the market | to be in season | to circulate widely","1338420"),
    ("立ち回る","たちまわる","v5r|vi","đi đứng | xử sự | xoay xở (có lợi) | ghé qua","to conduct oneself | to maneuver (to one's benefit) | to stop by","1551290"),
    ("動き回る","うごきまわる","v5r|vi","di chuyển khắp nơi | chạy đôn chạy đáo","to move around | to move about | to get around","1451200"),
    ("這い回る","はいまわる","v5r|vi","bò khắp nơi | bò quanh","to creep about | to crawl around","1600600"),
    ("こねくり回す","こねくりまわす","v5s|vt","nhào nặn | xoay vần | mân mê","to knead | to turn over and over","2274570"),
    ("取り巻く","とりまく","v5k|vt","vây quanh | bao quanh | xu nịnh","to surround | to encircle | to fawn over (someone)","1326610"),
    ("垂れ込める","たれこめる","v1|vi","giăng thấp (mây, sương) | khép mình (sau rèm)","to hang low (clouds, fog) | to seclude oneself","2258940"),
    ("忍び寄る","しのびよる","v5r|vi","lén đến gần | rón rén lại gần | âm thầm tới","to creep | to steal up | to draw near unnoticed","1467410"),
    ("にじり寄る","にじりよる","v5r|vi","nhích lại gần | xích lại gần","to sidle up to","1848600"),
    ("擦り寄る","すりよる","v5r|vi","nép sát | sán lại gần | nịnh nọt xán đến","to draw close to | to snuggle up to | to edge up to","1595890"),
    ("駆け寄る","かけよる","v5r|vi","chạy đến | lao đến gần","to run up to | to rush over","1244750"),
    ("畳み掛ける","たたみかける","v1|vt","dồn dập | tới tấp | dồn ép (câu hỏi)","to press (for an answer) | to shower (questions) | to give no leeway","1356760"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
