# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-003.csv in UTF-8 — 86 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-003.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("パスワード","パスワード","N4","n",
        "mật khẩu",
        "password",
        "1100140",
        "パスワードを入力します。","パスワードをにゅうりょくします。","Tôi nhập mật khẩu.","I enter the password."),
    row("汚す","よごす","N4","v5s|vt",
        "làm bẩn | gây ô nhiễm | làm dơ | để lại vết bẩn | làm ô uế | làm nhơ nhuốc | xúc phạm | làm mất danh dự",
        "to pollute | to contaminate | to soil | to make dirty | to stain | to make impure | to defile | to desecrate | to disgrace | to dishonour",
        "1157500",
        "服を汚しました。","ふくをよごしました。","Tôi làm bẩn quần áo.","I got my clothes dirty."),
    row("乾かす","かわかす","N4","v5s|vt",
        "làm khô | sấy khô",
        "to dry (clothes, etc.) | to desiccate",
        "1209640",
        "洗濯物を乾かします。","せんたくものをかわかします。","Tôi phơi quần áo cho khô.","I dry the laundry."),
    row("苦しむ","くるしむ","N4","v5m|vi",
        "khổ sở | rên rỉ | lo lắng khổ tâm",
        "to suffer | to groan | to be worried",
        "1241070",
        "彼は病気で苦しんでいます。","かれはびょうきでくるしんでいます。","Anh ấy đang khổ sở vì bệnh.","He is suffering from illness."),
    row("効果的","こうかてき","N4","adj-na",
        "hiệu quả | thành công",
        "effective | successful",
        "1271500",
        "効果的な方法です。","こうかてきなほうほうです。","Đây là phương pháp hiệu quả.","It is an effective method."),
    row("残業","ざんぎょう","N4","n|vs|vi",
        "làm thêm giờ | tăng ca",
        "overtime (work)",
        "1295940",
        "今日は残業があります。","きょうはざんぎょうがあります。","Hôm nay tôi làm thêm giờ.","I have overtime today."),
    row("悩む","なやむ","N4","v5m|vi",
        "lo lắng | phiền muộn | khổ tâm | băn khoăn",
        "to be worried | to be troubled",
        "1324660",
        "将来のことで悩んでいます。","しょうらいのことでなやんでいます。","Tôi đang lo lắng về tương lai.","I am worried about my future."),
    row("沸かす","わかす","N4","v5s|vt",
        "đun sôi | đun nóng (chất lỏng) | chuẩn bị (bồn tắm, đồ uống nóng) | khơi dậy hứng khởi",
        "to boil | to heat (a liquid) | to prepare (a bath, hot drink) | to excite",
        "1603160",
        "お湯を沸かします。","おゆをわかします。","Tôi đun nước sôi.","I boil water."),
    row("領収書","りょうしゅうしょ","N4","n",
        "biên lai thu tiền (thường viết tay)",
        "formal receipt (of payment; oft. hand-written)",
        "1147760",
        "領収書をください。","りょうしゅうしょをください。","Cho tôi biên lai nhé.","Please give me a receipt."),
    row("アイデア","アイデア","N4","n",
        "ý tưởng",
        "idea",
        "1015990",
        "いいアイデアですね。","いいアイデアですね。","Ý tưởng hay đấy nhỉ.","That's a good idea."),
    row("アカウント","アカウント","N4","n",
        "tài khoản",
        "account",
        "1016130",
        "アカウントを作ります。","アカウントをつくります。","Tôi tạo tài khoản.","I create an account."),
    row("アパート","アパート","N4","n",
        "tòa chung cư | căn hộ chung cư | nhà chung cư | căn hộ",
        "apartment building | apartment block | apartment house | apartment",
        "1017580",
        "アパートに住んでいます。","アパートにすんでいます。","Tôi đang sống ở chung cư.","I live in an apartment."),
    row("アプリ","アプリ","N4","n",
        "ứng dụng | app",
        "app | application",
        "1019100",
        "アプリをダウンロードします。","アプリをダウンロードします。","Tôi tải ứng dụng về.","I download an app."),
    row("エレベーター","エレベーター","N4","n",
        "thang máy",
        "elevator | lift",
        "1029400",
        "エレベーターに乗ります。","エレベーターにのります。","Tôi đi thang máy.","I take the elevator."),
    row("カーテン","カーテン","N4","n",
        "rèm cửa | màn cửa",
        "curtain | curtains",
        "1036250",
        "カーテンを開けます。","カーテンをあけます。","Tôi mở rèm cửa.","I open the curtains."),
    row("サイト","サイト","N4","n",
        "trang web | trang mạng",
        "site | website",
        "1067310",
        "このサイトを見てください。","このサイトをみてください。","Hãy xem trang web này.","Please look at this website."),
    row("ショッピング","ショッピング","N4","n|vs|vi",
        "mua sắm",
        "shopping",
        "1071360",
        "ショッピングに行きます。","ショッピングにいきます。","Tôi đi mua sắm.","I go shopping."),
    row("ジム","ジム","N4","n",
        "phòng tập gym | phòng tập thể dục",
        "gym | gymnasium",
        "1073570",
        "ジムでトレーニングします。","ジムでトレーニングします。","Tôi tập luyện ở phòng gym.","I train at the gym."),
    row("セール","セール","N4","n",
        "đợt giảm giá | sale",
        "sale",
        "1079780",
        "セール中です。","セールちゅうです。","Đang trong đợt giảm giá.","It is on sale."),
    row("タブレット","タブレット","N4","n",
        "máy tính bảng | viên thuốc | tấm bia khắc chữ",
        "tablet | pill | tablet computer | (inscribed) slab",
        "1075420",
        "タブレットで本を読みます。","タブレットでほんをよみます。","Tôi đọc sách trên máy tính bảng.","I read books on a tablet."),
    row("ダウンロード","ダウンロード","N4","n|vs|vt",
        "tải xuống",
        "download",
        "1076210",
        "ファイルをダウンロードします。","ファイルをダウンロードします。","Tôi tải file xuống.","I download the file."),
    row("フォーク","フォーク","N4","n",
        "dĩa (nĩa) | forkball (bóng chày)",
        "fork | forkball",
        "1109810",
        "フォークで食べます。","フォークでたべます。","Tôi ăn bằng dĩa.","I eat with a fork."),
    row("運転","うんてん","N4","n|vs|vt|vi",
        "vận hành (máy móc) | chạy máy | hoạt động | lái xe",
        "operation (of a machine) | running | working | driving (a vehicle)",
        "1167660",
        "車を運転します。","くるまをうんてんします。","Tôi lái xe.","I drive a car."),
    row("汚れる","よごれる","N4","v1|vi",
        "trở nên bẩn | bị dơ | bị ô uế | bị tha hóa",
        "to get dirty | to become dirty | to become sullied | to become corrupt",
        "1157510",
        "服が汚れました。","ふくがよごれました。","Quần áo bị bẩn rồi.","The clothes got dirty."),
    row("怪我","けが","N4","n|vs|vt|vi",
        "thương tích | vết thương | lỗi lầm | tai nạn | mất mát",
        "injury | wound | mistake | accident | loss",
        "1222750",
        "怪我をしました。","けがをしました。","Tôi bị thương.","I got injured."),
    row("懐かしい","なつかしい","N4","adj-i",
        "thân thương (kỷ niệm cũ) | được nhớ đến với tình cảm | được yêu quý | bị nhớ nhung | hoài cổ",
        "dear (old) | fondly remembered | beloved | missed | nostalgic",
        "1324520",
        "懐かしい歌ですね。","なつかしいうたですね。","Bài hát hoài cổ quá nhỉ.","What a nostalgic song."),
    row("慣れる","なれる","N4","v1|vi|aux-v",
        "quen với | trở nên quen thuộc | làm quen với | thành thạo | nắm được",
        "to get used to | to grow accustomed to | to become familiar with | to become skilled in | to get the hang of",
        "1324710",
        "新しい仕事に慣れました。","あたらしいしごとになれました。","Tôi đã quen với công việc mới.","I got used to the new job."),
    row("希望","きぼう","N4","n|vs|vt",
        "hy vọng | mong muốn | khát vọng | triển vọng tươi sáng | kỳ vọng",
        "hope | wish | aspiration | (bright) prospects | expectation",
        "1229330",
        "希望を持ちましょう。","きぼうをもちましょう。","Hãy giữ hy vọng.","Let's have hope."),
    row("季節","きせつ","N4","n|adj-no",
        "mùa | mùa trong năm",
        "season | time of year",
        "1230260",
        "春は好きな季節です。","はるはすきなきせつです。","Mùa xuân là mùa yêu thích của tôi.","Spring is my favorite season."),
    row("休暇","きゅうか","N4","n",
        "kỳ nghỉ | ngày nghỉ | ngày nghỉ phép | thời gian nghỉ | nghỉ phép",
        "holiday | vacation | day off | time off | leave | furlough",
        "1230320",
        "休暇を取ります。","きゅうかをとります。","Tôi xin nghỉ phép.","I take a vacation."),
    row("休憩","きゅうけい","N4","n|vs|vi",
        "nghỉ ngơi | giải lao | nghỉ giữa giờ | giờ giải lao",
        "rest | break | recess | intermission",
        "1230340",
        "少し休憩しましょう。","すこしきゅうけいしましょう。","Nghỉ ngơi một chút nhé.","Let's take a short break."),
    row("救急","きゅうきゅう","N4","n",
        "sơ cứu | cấp cứu | cứu thương",
        "first-aid | emergency (aid)",
        "1230390",
        "救急車を呼びます。","きゅうきゅうしゃをよびます。","Tôi gọi xe cứu thương.","I call an ambulance."),
    row("驚く","おどろく","N4","v5k|vi",
        "ngạc nhiên | bị bất ngờ | kinh ngạc | sửng sốt",
        "to be surprised | to be taken aback | to be amazed | to be astonished",
        "1156570",
        "驚きました！","おどろきました！","Tôi ngạc nhiên quá!","I was surprised!"),
    row("広告","こうこく","N4","n|vs|vt",
        "quảng cáo | thông báo | thông cáo",
        "advertisement | advertising | announcement | notice",
        "1270330",
        "広告を見ます。","こうこくをみます。","Tôi xem quảng cáo.","I watch an advertisement."),
    row("洪水","こうずい","N4","n",
        "lũ lụt | ngập lụt",
        "flood | flooding",
        "1271290",
        "洪水が起きました。","こうずいがおきました。","Lũ lụt xảy ra.","A flood occurred."),
    row("酸っぱい","すっぱい","N4","adj-i",
        "chua | có vị chua",
        "sour | acid",
        "1382210",
        "このレモンは酸っぱいです。","このレモンはすっぱいです。","Quả chanh này rất chua.","This lemon is sour."),
    row("捨てる","すてる","N4","v1|vt",
        "vứt bỏ | ném đi | bỏ lại | vứt | bỏ rơi | bỏ đi | để lại phía sau",
        "to throw away | to cast away | to dump | to discard | to abandon | to desert | to leave behind",
        "1383750",
        "ゴミを捨てます。","ゴミをすてます。","Tôi vứt rác.","I throw away the garbage."),
    row("社会","しゃかい","N4","n",
        "xã hội | cộng đồng | công chúng | thế giới | môn xã hội học",
        "society | public | community | the world | social studies",
        "1357600",
        "社会のために働きます。","しゃかいのためにはたらきます。","Tôi làm việc vì xã hội.","I work for society."),
    row("社会人","しゃかいじん","N4","n",
        "người lớn đi làm | thành viên thực sự của xã hội",
        "working adult | full-fledged member of society",
        "1357610",
        "社会人になりました。","しゃかいじんになりました。","Tôi đã trở thành người đi làm.","I became a working adult."),
    row("手間","てま","N4","n",
        "thời gian | công sức | nỗ lực | tiền công (lao động) | chi phí | thời gian cần thiết",
        "time | labour | labor | effort | payment (for labour) | pay | charge | (the) time (it takes)",
        "1426830",
        "手間がかかります。","てまがかかります。","Mất nhiều công sức.","It takes a lot of effort."),
    row("手術","しゅじゅつ","N4","n|vs|vt",
        "phẫu thuật | ca mổ | thủ thuật | kỹ năng tay nghề | ảo thuật (xiếc)",
        "surgery | operation | procedure | skill with one's hands | sleight of hand | juggling",
        "1355820",
        "手術が成功しました。","しゅじゅつがせいこうしました。","Ca phẫu thuật thành công.","The surgery was successful."),
    row("種類","しゅるい","N4","n|ctr",
        "loại | loại hình | thể loại | phạm trù | đếm loại, chủng loại",
        "variety | kind | type | category | counter for kinds, species, etc.",
        "1356370",
        "いろいろな種類があります。","いろいろなしゅるいがあります。","Có nhiều loại khác nhau.","There are various kinds."),
    row("情報","じょうほう","N4","n",
        "thông tin | tin tức | báo cáo | tình báo",
        "information | news | report | intelligence",
        "1368620",
        "情報を集めます。","じょうほうをあつめます。","Tôi thu thập thông tin.","I gather information."),
    row("診察","しんさつ","N4","n|vs|vt",
        "khám bệnh | kiểm tra sức khỏe | tư vấn y tế",
        "medical examination | checkup | consultation",
        "1365430",
        "医者に診察してもらいます。","いしゃにしんさつしてもらいます。","Tôi được bác sĩ khám bệnh.","I have a medical examination by a doctor."),
    row("制服","せいふく","N4","n",
        "đồng phục",
        "uniform",
        "1386590",
        "学校の制服を着ます。","がっこうのせいふくをきます。","Tôi mặc đồng phục trường.","I wear the school uniform."),
    row("政治","せいじ","N4","n",
        "chính trị | chính phủ",
        "politics | government",
        "1388080",
        "政治に興味があります。","せいじにきょうみがあります。","Tôi quan tâm đến chính trị.","I am interested in politics."),
    row("税金","ぜいきん","N4","n",
        "thuế | thuế quan",
        "tax | duty",
        "1388290",
        "税金を払います。","ぜいきんをはらいます。","Tôi nộp thuế.","I pay taxes."),
    row("積極的","せっきょくてき","N4","adj-na",
        "tích cực | quyết đoán | chủ động | chủ động tham gia | mạnh mẽ",
        "positive | assertive | active | proactive | aggressive",
        "1388750",
        "積極的に参加します。","せっきょくてきにさんかします。","Tôi tham gia một cách tích cực.","I participate actively."),
    row("単純","たんじゅん","N4","adj-na|n",
        "đơn giản | mộc mạc | không phức tạp | rõ ràng | tư duy đơn giản | ngây thơ",
        "simple | plain | uncomplicated | straightforward | simple-minded | naive",
        "1403880",
        "単純な問題です。","たんじゅんなもんだいです。","Đây là vấn đề đơn giản.","It is a simple problem."),
    row("担当","たんとう","N4","n|vs|vt",
        "phụ trách | chịu trách nhiệm | đảm nhiệm",
        "being in charge (of an area of responsibility) | being responsible (for) | taking charge of",
        "1403950",
        "この案件を担当します。","このあんけんをたんとうします。","Tôi phụ trách vụ việc này.","I am in charge of this case."),
    row("断る","ことわる","N4","v5r|vt",
        "từ chối | bác bỏ | không chấp nhận | thông báo (về quyết định) | báo trước | từ bỏ",
        "to refuse | to reject | to dismiss | to turn down | to decline | to inform (of a decision) | to tell (in advance) | to notify",
        "1274470",
        "誘いを断りました。","さそいをことわりました。","Tôi từ chối lời mời.","I declined the invitation."),
    row("暖房","だんぼう","N4","n|vs|vt",
        "hệ thống sưởi (trong nhà) | máy sưởi",
        "(indoor) heating",
        "1404800",
        "暖房をつけます。","だんぼうをつけます。","Tôi bật máy sưởi.","I turn on the heating."),
    row("知らせる","しらせる","N4","v1|vt",
        "thông báo | báo cho biết | cho biết",
        "to notify | to advise | to inform",
        "1362010",
        "結果を知らせます。","けっかをしらせます。","Tôi sẽ thông báo kết quả.","I will notify the results."),
    row("地震","じしん","N4","n",
        "động đất",
        "earthquake",
        "1363010",
        "地震が起きました。","じしんがおきました。","Động đất xảy ra.","An earthquake occurred."),
    row("恥ずかしい","はずかしい","N4","adj-i",
        "xấu hổ | ngại ngùng | nhục nhã | bị nhục | e thẹn | đáng xấu hổ",
        "embarrassing | embarrassed | ashamed | humiliated | shy | disgraceful | shameful",
        "1600310",
        "恥ずかしいです。","はずかしいです。","Tôi xấu hổ quá.","I'm embarrassed."),
    row("突然","とつぜん","N4","adj-no|adj-na|adv",
        "đột ngột | bất ngờ | không mong đợi",
        "abrupt | sudden | unexpected",
        "1458260",
        "突然雨が降りました。","とつぜんあめがふりました。","Đột ngột trời đổ mưa.","It suddenly rained."),
    row("鍋","なべ","N4","n|n-suf",
        "xoong | nồi | nồi đun | món hầm | lẩu",
        "pan | pot | saucepan | stew | hot pot",
        "1461190",
        "鍋料理を作ります。","なべりょうりをつくります。","Tôi nấu món lẩu.","I make a hot pot dish."),
    row("熱","ねつ","N4","n|suf",
        "nhiệt | sốt | nhiệt độ | nhiệt huyết | đam mê | hứng khởi | cuồng nhiệt | cơn sốt | nhiệt độ cơ thể",
        "heat | fever | temperature | zeal | passion | enthusiasm | mania | craze | (body) temperature",
        "1465300",
        "熱があります。","ねつがあります。","Tôi đang bị sốt.","I have a fever."),
    row("反省","はんせい","N4","n|vs|vt",
        "suy ngẫm | tự xét lại | nội tâm | thiền định | chiêm nghiệm | hối hận sâu sắc | ăn năn",
        "reflection | reconsideration | introspection | meditation | contemplation | (profound) regret | repentance",
        "1597450",
        "自分の行動を反省します。","じぶんのこうどうをはんせいします。","Tôi suy ngẫm về hành động của mình.","I reflect on my own behavior."),
    row("皮膚","ひふ","N4","n",
        "da | da thịt",
        "skin",
        "1602290",
        "皮膚が乾燥しています。","ひふがかんそうしています。","Da đang bị khô.","The skin is dry."),
    row("膝","ひざ","N4","n",
        "đầu gối | đùi (khi ngồi)",
        "knee | lap | knee and thigh (while sitting)",
        "1602300",
        "膝が痛いです。","ひざがいたいです。","Đầu gối đau.","My knee hurts."),
    row("必ず","かならず","N4","adv",
        "luôn luôn | không ngoại lệ | nhất thiết | chắc chắn | không bao giờ thất bại | nhất định",
        "always | without exception | necessarily | certainly | without fail | definitely",
        "2028940",
        "必ず連絡してください。","かならずれんらくしてください。","Nhất định hãy liên lạc nhé.","Please be sure to contact me."),
    row("表情","ひょうじょう","N4","n",
        "biểu cảm khuôn mặt | sắc mặt | vẻ ngoài | diện mạo | biểu đạt (giọng nói v.v.)",
        "facial expression | countenance | look | appearance | expression (vocal, etc.)",
        "1603370",
        "嬉しい表情をしています。","うれしいひょうじょうをしています。","Trên mặt lộ vẻ vui mừng.","I have a happy expression."),
    row("不安","ふあん","N4","n|adj-na",
        "lo lắng | bất an | lo âu | lo sợ | sợ hãi | thiếu an toàn | hồi hộp",
        "anxiety | uneasiness | worry | apprehension | fear | insecurity | suspense",
        "1604190",
        "試験前に不安です。","しけんまえにふあんです。","Tôi lo lắng trước kỳ thi.","I am anxious before the exam."),
    row("不合格","ふごうかく","N4","n",
        "trượt (kỳ thi) | bị loại | không đủ tiêu chuẩn",
        "(examination) failure | rejection | disqualification",
        "1604510",
        "不合格でした。","ふごうかくでした。","Tôi đã trượt.","I failed."),
    row("布団","ふとん","N4","n",
        "đệm futon | chăn đệm kiểu Nhật (gồm đệm và chăn) | gối thiền Zen hình tròn",
        "futon | Japanese bedding consisting of a mattress and a duvet | round cushion used for Zen meditation",
        "1604770",
        "布団を干します。","ふとんをほします。","Tôi phơi chăn đệm.","I air out the futon."),
    row("部長","ぶちょう","N4","n",
        "trưởng phòng | trưởng bộ phận | giám đốc bộ phận | chủ nhiệm câu lạc bộ (trường) | quản lý | trưởng",
        "head (chief, director) of a section or department | head of a (school) club | manager | chief",
        "1605330",
        "部長に報告します。","ぶちょうにほうこくします。","Tôi báo cáo với trưởng phòng.","I report to the department head."),
    row("文化","ぶんか","N4","n",
        "văn hóa | văn minh",
        "culture | civilization | civilisation",
        "1607040",
        "日本の文化が好きです。","にほんのぶんかがすきです。","Tôi thích văn hóa Nhật Bản.","I like Japanese culture."),
    row("文章","ぶんしょう","N4","n",
        "bài viết | bài luận | bài tiểu luận | bài báo | đoạn văn | văn xuôi | văn phong",
        "writing | composition | essay | article | passage | prose | (writing) style",
        "1607140",
        "文章を書きます。","ぶんしょうをかきます。","Tôi viết bài.","I write a composition."),
    row("保険","ほけん","N4","n",
        "bảo hiểm | bảo đảm | bảo hành",
        "insurance | guarantee | warranty",
        "1610710",
        "保険に入ります。","ほけんにはいります。","Tôi đăng ký bảo hiểm.","I sign up for insurance."),
    row("包丁","ほうちょう","N4","n",
        "dao bếp | nghệ thuật nấu ăn | thức ăn",
        "kitchen knife | cooking | food",
        "1610640",
        "包丁で野菜を切ります。","ほうちょうでやさいをきります。","Tôi cắt rau bằng dao bếp.","I cut vegetables with a kitchen knife."),
    row("訪ねる","たずねる","N4","v1|vt",
        "thăm | đến thăm | ghé thăm",
        "to visit | to call on | to pay a visit to",
        "1404020",
        "友人を訪ねます。","ゆうじんをたずねます。","Tôi đến thăm bạn.","I visit my friend."),
    row("廊下","ろうか","N4","n",
        "hành lang | đường đi giữa các phòng",
        "corridor | hallway | passageway",
        "1147660",
        "廊下を歩きます。","ろうかをあるきます。","Tôi đi dọc hành lang.","I walk down the hallway."),
    row("和","わ","N4","n|n-pref|adj-no",
        "tổng | hài hòa | hòa bình | Nhật Bản | phong cách Nhật Bản",
        "sum | harmony | peace | Japan | Japanese-style",
        "1583150",
        "和食が好きです。","わしょくがすきです。","Tôi thích ẩm thực Nhật Bản.","I like Japanese food."),
    row("腕","うで","N4","n",
        "cánh tay | khả năng | kỹ năng | tài năng | năng lực | sức mạnh (thể chất)",
        "arm | ability | skill | talent | competence | (physical) strength",
        "1157020",
        "腕を磨きます。","うでをみがきます。","Tôi trau dồi kỹ năng.","I polish my skills."),
    row("安心","あんじん","N4","n",
        "đạt được sự bình yên trong tâm hồn qua đức tin hoặc tu tập khổ hạnh",
        "obtaining peace of mind through faith or ascetic practice",
        "1160050"),
    row("温める","ぬるめる","N4","v1|vt",
        "pha nguội (nước) | làm bớt nóng (ví dụ bằng cách thêm nước lạnh)",
        "to cool (water) down | to make less hot (e.g. by adding cold water)",
        "1163890"),
    row("米","べい","N4","n",
        "Mỹ | Hoa Kỳ (Mỹ) | nước Mỹ",
        "(United States of) America | USA",
        "1179750"),
    row("薬","やく","N4","n",
        "chất gây mê | chất ma túy | thuốc (gây nghiện)",
        "dope | narcotic | drug",
        "2402580"),
    row("急に","きゅうに","N4","adv",
        "nhanh chóng | vội vã | gấp gáp | ngay lập tức | hấp tấp | đột ngột | bất chợt",
        "swiftly | rapidly | quickly | immediately | hastily | hurriedly | suddenly | all of a sudden",
        "2028810",
        "急に雨が降りました。","きゅうにあめがふりました。","Đột ngột trời đổ mưa.","Suddenly it rained."),
    row("夜中","よじゅう","N4","n|adv",
        "suốt đêm | cả đêm",
        "all night | the whole night",
        "1450050"),
    row("スマホ","スマホ","N4","n",
        "điện thoại thông minh | smartphone",
        "smartphone | smart phone",
        "2855244",
        "スマホを使います。","スマホをつかいます。","Tôi dùng điện thoại thông minh.","I use a smartphone."),
    row("注文","ちゅうぶん","N4","n",
        "chú thích | ghi chú giải thích",
        "annotation | explanatory note",
        "1436490"),
    row("包む","くるむ","N4","v5m|vt",
        "gói vào | cuộn vào | nhét vào",
        "to wrap up (in) | to roll up (in) | to tuck (up)",
        "1436840",
        "プレゼントを包みます。","プレゼントをくるみます。","Tôi gói quà.","I wrap the present."),
    row("大事","おおごと","N4","n",
        "việc nghiêm trọng | sự cố lớn | vấn đề cực kỳ nghiêm trọng | khủng hoảng",
        "serious matter | major incident | matter of grave concern | crisis",
        "1437050",
        "大事になりました。","おおごとになりました。","Việc trở nên nghiêm trọng.","It became a serious matter."),
    row("土","ト","N4","n",
        "Thổ Nhĩ Kỳ",
        "Turkey",
        "1437520"),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
