# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-038.csv -- 31 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-038.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("汚れ","けがれ","N4","n",
        "ô uế | sự không trong sạch | nhơ nhúa | điều nhơ bẩn",
        "uncleanness | impurity | defilement | disgrace | shame | stain | blot | corruption",
        "1178990",
        "心の汚れを洗い流す。","こころのけがれをあらいながす。",
        "Rửa sạch sự nhơ bẩn trong tâm hồn.","Wash away the impurity of one's heart."),
    row("垢","あか","N4","n",
        "cáu ghét | bụi bẩn | chất bẩn trên da",
        "dirt | filth | grime",
        "1277420",
        "垢をこすり落とす。","あかをこすりおとす。",
        "Chà rửa cáu ghét.","Scrub off the grime."),
    row("煮込む","にこむ","N4","v5m|vt",
        "hầm nhừ | ninh kỹ | nấu lâu | om",
        "to boil well | to stew | to simmer (for a long time) | to cook (various ingredients) together",
        "1322580",
        "肉を煮込む。","にくをにこむ。",
        "Hầm nhừ thịt.","Simmer the meat for a long time."),
    row("蒸らす","むらす","N4","v5s|vt",
        "hấp chín | đồ chín bằng hơi nước | ủ chín",
        "to cook by steam",
        "1356910",
        "ご飯を蒸らす。","ごはんをむらす。",
        "Ủ chín cơm.","Steam the rice."),
    row("昼下がり","ひるさがり","N4","n",
        "buổi xế chiều | đầu giờ chiều",
        "early afternoon",
        "1426270",
        "昼下がりにお茶を飲む。","ひるさがりにおちゃをのむ。",
        "Uống trà vào buổi xế chiều.","Drink tea in the early afternoon."),
    row("木陰","こかげ","N4","n",
        "bóng cây | bóng mát dưới cây",
        "shade of a tree | bower",
        "1534570",
        "木陰で休む。","こかげでやすむ。",
        "Nghỉ ngơi dưới bóng cây.","Rest in the shade of a tree."),
    row("夕暮れ","ゆうぐれ","N4","n",
        "hoàng hôn | chiều tà | lúc chạng vạng",
        "evening | dusk | twilight",
        "1542770",
        "夕暮れに散歩する。","ゆうぐれにさんぽする。",
        "Đi dạo vào lúc hoàng hôn.","Take a walk at dusk."),
    row("夕焼け","ゆうやけ","N4","n",
        "ánh hoàng hôn | ráng chiều | bầu trời đỏ lúc chiều",
        "evening glow | red sunset | afterglow (of sunset)",
        "1542720",
        "美しい夕焼け。","うつくしいゆうやけ。",
        "Ánh hoàng hôn đẹp.","A beautiful evening glow."),
    row("埃","ほこり","N4","n",
        "bụi | bụi bặm",
        "dust",
        "1565750",
        "埃を払う。","ほこりをはらう。",
        "Phủi bụi.","Brush away the dust."),
    row("木漏れ日","こもれび","N4","n",
        "ánh nắng lọc qua tán lá | ánh sáng lốm đốm qua lá cây",
        "sunlight filtering through trees",
        "1593440",
        "木漏れ日が美しい。","こもれびがうつくしい。",
        "Ánh nắng lọc qua tán lá đẹp.","The sunlight through the leaves is beautiful."),
    row("埃","あい","N4","n",
        "Ai Cập | một phần mười tỷ",
        "one ten-billionth | Egypt",
        "2248500",
        "埃及はエジプトのことだ。","あいきゅうはえじぷとのことだ。",
        "Ai Cập là Nhật ngữ viết tắt cho Egypt.","Egypt in Sino-Japanese."),
    row("土砂降り","どしゃぶり","N4","n",
        "mưa như trút | mưa tầm tã | mưa xối xả",
        "downpour | pouring rain | heavy rain | pelting rain | cloudburst",
        "1445340",
        "土砂降りの雨。","どしゃぶりのあめ。",
        "Mưa trút như thác.","A pouring rain."),
    row("塵","ゴミ","N4","n",
        "rác | rác thải | đồ vứt đi",
        "rubbish | trash | garbage | refuse | litter",
        "1369900",
        "塵を捨てる。","ゴミをすてる。",
        "Vứt rác.","Throw away trash."),
    row("塵","ちり","N4","n",
        "bụi | rác | chút nhỏ nhặt | điều tầm thường",
        "dust | trash | garbage | dirt | negligible amount | tiny bit",
        "1369910",
        "塵も積もれば山となる。","ちりもつもればやまとなる。",
        "Tích tiểu thành đại.","Many a little makes a mickle."),
    row("塵","じん","N4","n|num",
        "ô nhiễm tâm linh (Phật giáo) | tạp chất | một phần tỷ",
        "defilement | impurity | affliction | object (perceived with the mind or the senses) | one billionth",
        "2248490",
        "塵を離れる。","じんをはなれる。",
        "Thoát khỏi ô uế trần gian.","Free oneself from worldly defilement."),
    row("夜明け","よあけ","N4","n",
        "bình minh | rạng đông | bình minh ngày mới",
        "dawn | daybreak",
        "1537150",
        "夜明けに起きる。","よあけにおきる。",
        "Thức dậy lúc bình minh.","Wake up at dawn."),
    row("日暮れ","ひぐれ","N4","n",
        "hoàng hôn | lúc mặt trời lặn | chạng vạng tối",
        "twilight | sunset | dusk | evening",
        "1464420",
        "日暮れまでに帰る。","ひぐれまでにかえる。",
        "Về nhà trước khi trời tối.","Return home before sunset."),
    row("明け方","あけがた","N4","n|adv",
        "tảng sáng | lúc bình minh | sáng sớm",
        "dawn | daybreak",
        "1532300",
        "明け方に地震があった。","あけがたにじしんがあった。",
        "Có động đất vào lúc tảng sáng.","There was an earthquake at dawn."),
    row("汚れ","よごれ","N4","n",
        "vết bẩn | chỗ dơ | vết ố",
        "dirt | filth | stain | blot | spot",
        "1612200",
        "シャツに汚れがある。","しゃつによごれがある。",
        "Áo sơ mi có vết bẩn.","There is a stain on the shirt."),
    row("波紋","はもん","N4","n",
        "gợn sóng | vòng tròn trên mặt nước | ảnh hưởng lan rộng",
        "ripple | ring on the water | repercussions",
        "1471090",
        "石が波紋を広げる。","いしがはもんをひろげる。",
        "Hòn đá tạo ra những gợn sóng.","The stone creates ripples."),
    row("湯気","ゆげ","N4","n",
        "hơi nước | hơi bốc lên | khói hơi",
        "steam | vapour | vapor",
        "1448600",
        "鍋から湯気が出る。","なべからゆげがでる。",
        "Hơi nước bốc lên từ nồi.","Steam rises from the pot."),
    row("漬物","つけもの","N4","n",
        "dưa muối kiểu Nhật | rau củ muối chua | tsukemono",
        "tsukemono (pickled vegetables)",
        "1433700",
        "漬物を食べる。","つけものをたべる。",
        "Ăn dưa muối.","Eat pickled vegetables."),
    row("炊き込みご飯","たきこみごはん","N4","n",
        "cơm nấu chung với nguyên liệu | cơm thập cẩm Nhật",
        "rice seasoned and cooked with various ingredients",
        "1891030",
        "炊き込みご飯を作る。","たきこみごはんをつくる。",
        "Nấu cơm thập cẩm Nhật.","Make seasoned rice."),
    row("焦げ","こげ","N4","n",
        "vết cháy | phần cháy | cơm cháy (dưới nồi)",
        "scorching | scorch | burn | scorched rice (at the bottom of the pot) | crispy rice",
        "2803090",
        "鍋の焦げを落とす。","なべのこげをおとす。",
        "Tẩy vết cháy trên nồi.","Remove the burn from the pot."),
    row("蒸し物","むしもの","N4","n",
        "đồ hấp | món ăn hấp chín",
        "food cooked by steaming",
        "2140760",
        "蒸し物が好きです。","むしものがすきです。",
        "Tôi thích đồ hấp.","I like steamed food."),
    row("酢の物","すのもの","N4","exp|n",
        "món trộn giấm | đồ ngâm giấm kiểu Nhật",
        "vinegared dish | pickled dish",
        "1370280",
        "酢の物を作る。","すのものをつくる。",
        "Làm món trộn giấm.","Make a vinegared dish."),
    row("霰","あられ","N4","n",
        "mưa đá nhỏ | hạt mưa đá | mochi nướng hạt nhỏ",
        "hail (esp. hailballs under 5 mm) | graupel | roasted mochi pieces",
        "1574100",
        "霰が降る。","あられがふる。",
        "Mưa đá rơi.","Hail falls."),
    row("靄","もや","N4","n",
        "sương mù nhẹ | hơi sương | khói sương",
        "mist | haze",
        "1574130",
        "靄がかかっている。","もやがかかっている。",
        "Sương mù bao phủ.","Mist hangs in the air."),
    row("黄昏","たそがれ","N4","n",
        "hoàng hôn | chạng vạng | tuổi xế chiều",
        "dusk | twilight | twilight years | melancholia | melancholic nostalgia",
        "1576750",
        "黄昏時の空。","たそがれどきのそら。",
        "Bầu trời lúc hoàng hôn.","The sky at twilight."),
    row("垢","く","N4","n",
        "phiền não (Phật giáo) | tâm chướng | tạp niệm",
        "klesha (polluting thoughts such as greed, hatred and delusion, which result in suffering)",
        "2270490",
        "心の垢を落とす。","こころのくをおとす。",
        "Loại bỏ phiền não trong tâm.","Remove the defilements of the mind."),
    row("垢","アカ","N4","n",
        "tài khoản (mạng xã hội, dịch vụ trực tuyến)",
        "account (e.g. for an online service)",
        "2795290",
        "垢を作る。","あかをつくる。",
        "Tạo tài khoản.","Create an account."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
