# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-022.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-022.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("パスポート","パスポート","N4","n",
        "hộ chiếu",
        "passport",
        "1101510",
        "パスポートを見せます。","パスポートをみせます。","Tôi xuất trình hộ chiếu.","I show my passport."),
    row("以来","いらい","N4","n-suf|n|adv",
        "kể từ | từ khi | từ đó đến nay",
        "since | henceforth | ever since",
        "1155210",
        "それ以来会っていません。","それいらいあっていません。","Từ đó tôi không gặp lại.","I haven't seen them since then."),
    row("運賃","うんちん","N4","n",
        "giá vé | cước phí hàng hóa | phí vận chuyển",
        "(passenger) fare | freight rates | shipping expenses",
        "1172820",
        "運賃を払います。","うんちんをはらいます。","Tôi trả tiền vé.","I pay the fare."),
    row("化石燃料","かせきねんりょう","N4","n",
        "nhiên liệu hóa thạch",
        "fossil fuel",
        "1187240",
        "化石燃料を減らします。","かせきねんりょうをへらします。","Chúng tôi giảm sử dụng nhiên liệu hóa thạch.","We reduce the use of fossil fuels."),
    row("驚き","おどろき","N4","n",
        "sự ngạc nhiên | kinh ngạc | sự kỳ diệu",
        "surprise | astonishment | wonder | amazement",
        "1238660",
        "驚きを隠せません。","おどろきをかくせません。","Tôi không giấu được sự ngạc nhiên.","I can't hide my surprise."),
    row("苦しみ","くるしみ","N4","n",
        "đau khổ | khốn khổ | đau đớn | gian khổ",
        "pain | anguish | distress | suffering | hardship",
        "1244340",
        "苦しみを乗り越えます。","くるしみをのりこえます。","Tôi vượt qua đau khổ.","I overcome suffering."),
    row("言い張る","いいはる","N4","v5r|vt",
        "khăng khăng | cứng đầu | kiên quyết nói",
        "to insist | to assert | to be obstinate in saying",
        "1264170",
        "自分の意見を言い張ります。","じぶんのいけんをいいはります。","Tôi khăng khăng giữ ý kiến của mình.","I insist on my own opinion."),
    row("呼吸","こきゅう","N4","n|vs|vt|vi",
        "hô hấp | thở | bí quyết | kỹ năng | sự hài hòa | nhịp thở",
        "breathing | respiration | knack | trick | secret (of doing something) | harmony | balance | synchronization | accord | short interval | short pause",
        "1266470",
        "深呼吸をします。","ふかこきゅうをします。","Tôi hít thở sâu.","I take a deep breath."),
    row("持ち歩く","もちあるく","N4","v5k|vt",
        "mang theo người | xách theo",
        "to carry around | to carry on one's person",
        "1315680",
        "傘を持ち歩きます。","かさをもちあるきます。","Tôi mang theo ô.","I carry an umbrella around."),
    row("受け入れる","うけいれる","N4","v1|vt",
        "chấp nhận | tiếp nhận | đồng ý",
        "to accept | to receive | to agree",
        "1329670",
        "提案を受け入れます。","ていあんをうけいれます。","Tôi chấp nhận đề xuất.","I accept the proposal."),
    row("恥じる","はじる","N4","v1|vt",
        "xấu hổ | cảm thấy xấu hổ",
        "to feel ashamed",
        "1421610",
        "行動を恥じます。","こうどうをはじます。","Tôi xấu hổ về hành động của mình.","I feel ashamed of my actions."),
    row("紛争","ふんそう","N4","n|vs|vi",
        "tranh chấp | xung đột | bất ổn | đấu tranh",
        "dispute | conflict | trouble | unrest | strife",
        "1505060",
        "紛争を解決します。","ふんそうをかいけつします。","Chúng tôi giải quyết xung đột.","We resolve the conflict."),
    row("露","つゆ","N4","n|adv",
        "sương (trên lá) | nước mắt | chút nào (phủ định)",
        "dew | tears | (not) a bit | (not) at all",
        "1560070",
        "朝露が光ります。","あさつゆがひかります。","Sương sớm lấp lánh.","Morning dew glistens."),
    row("姉妹","しまい","N4","n",
        "chị em gái",
        "sisters",
        "1579490",
        "姉妹で仲がいいです。","しまいでなかがいいです。","Hai chị em gái thân thiết.","The sisters get along well."),
    row("乗客","じょうきゃく","N4","n",
        "hành khách",
        "passenger",
        "1580490",
        "乗客が降ります。","じょうきゃくがおります。","Hành khách xuống xe.","The passengers get off."),
    row("途中","とちゅう","N4","n|adv",
        "trên đường | giữa chừng | dở chừng | nửa chừng",
        "on the way | en route | in the middle of | midway | halfway",
        "1582200",
        "途中で止まります。","とちゅうでとまります。","Tôi dừng lại giữa chừng.","I stop midway."),
    row("基準","きじゅん","N4","n",
        "tiêu chuẩn | tiêu chí | chuẩn mực | thước đo | cơ sở",
        "standard | criterion | norm | benchmark | measure | gauge | basis",
        "1591210",
        "基準を満たします。","きじゅんをみたします。","Tôi đáp ứng tiêu chuẩn.","I meet the standard."),
    row("引き止める","ひきとめる","N4","v1|vt",
        "giữ lại | ngăn lại | cản trở",
        "to detain | to check | to restrain | to stop",
        "1601750",
        "友達を引き止めます。","ともだちをひきとめます。","Tôi giữ bạn lại.","I stop my friend from leaving."),
    row("親族","うから","N4","n",
        "người thân máu mủ | ruột thịt",
        "blood relative",
        "2820740",
        "親族が集まります。","うからがあつまります。","Người thân tập hợp.","Blood relatives gather."),
    row("アンケート","アンケート","N4","n",
        "bảng câu hỏi | khảo sát | thăm dò ý kiến",
        "questionnaire | survey | poll",
        "1019940",
        "アンケートに答えます。","アンケートにこたえます。","Tôi trả lời bảng câu hỏi.","I answer the questionnaire."),
    row("カレンダー","カレンダー","N4","n",
        "lịch",
        "calendar | calender (machine for flattening things)",
        "1039220",
        "カレンダーを見ます。","カレンダーをみます。","Tôi xem lịch.","I look at the calendar."),
    row("栄養","えいよう","N4","n",
        "dinh dưỡng | chất bổ dưỡng",
        "nutrition | nourishment",
        "1173990",
        "栄養を取ります。","えいようをとります。","Tôi bổ sung dinh dưỡng.","I take nutrition."),
    row("加害者","かがいしゃ","N4","n",
        "thủ phạm | người gây hại | kẻ tấn công | bên có lỗi",
        "perpetrator | wrong-doer | aggressor | assailant | offender | at-fault party (e.g. in an accident)",
        "1190030",
        "加害者を逮捕します。","かがいしゃをたいほします。","Cảnh sát bắt giữ thủ phạm.","The police arrest the perpetrator."),
    row("夏至","げし","N4","n",
        "điểm phân hạ | ngày hạ chí",
        "summer solstice",
        "1191460",
        "夏至の日は長いです。","げしのひはながいです。","Ngày hạ chí rất dài.","The day of the summer solstice is long."),
    row("兄弟","きょうだい","N4","n",
        "anh chị em | anh em | bạn bè | anh em kết nghĩa",
        "brothers and sisters | siblings | half-siblings | step-siblings | siblings by marriage or adoption | mate | friend",
        "1249960",
        "兄弟は三人います。","きょうだいはさんにんいます。","Tôi có ba anh chị em.","I have three siblings."),
    row("研修","けんしゅう","N4","n|vs|vt",
        "đào tạo | tập huấn | khóa học thực tập",
        "training (esp. in-service) | induction course",
        "1258660",
        "新人研修を受けます。","しんじんけんしゅうをうけます。","Tôi tham gia đào tạo nhân viên mới.","I attend new employee training."),
    row("原則","げんそく","N4","n|adv",
        "nguyên tắc | quy tắc chung | về nguyên tắc",
        "principle | general rule | as a rule | in principle | in general",
        "1262070",
        "原則として禁止です。","げんそくとしてきんしです。","Về nguyên tắc, điều này bị cấm.","As a rule, this is prohibited."),
    row("現在","げんざい","N4","n|adv|adj-no|n-suf|vs|vi",
        "hiện tại | bây giờ | lúc này | thì hiện tại",
        "the present | present time | now | as of | present tense | this world | this life | to actually exist | to exist right now | to exist right in front of one",
        "1263650",
        "現在の状況を説明します。","げんざいのじょうきょうをせつめいします。","Tôi giải thích tình hình hiện tại.","I explain the current situation."),
    row("呼び止める","よびとめる","N4","v1|vt",
        "gọi dừng lại | vẫy gọi (taxi) | chặn lại",
        "to (call and) stop | to call (someone) to stop | to hail (e.g. a taxi)",
        "1266330",
        "タクシーを呼び止めます。","タクシーをよびとめます。","Tôi vẫy gọi taxi.","I hail a taxi."),
    row("呼び出す","よびだす","N4","v5s|vt",
        "gọi ra | gọi điện | triệu tập | thỉnh (thần linh) | gọi (hàm/file)",
        "to call (someone) to (the door, phone, etc.) | to tell (someone) to come | to call up (on the phone) | to summon | to page | to invoke (e.g. a spirit) | to invoke (e.g. a subroutine) | to call | to open (e.g. a file)",
        "1266350",
        "社長に呼び出されます。","しゃちょうによびだされます。","Tôi được giám đốc gọi ra.","I am summoned by the president."),
    row("国際","こくさい","N4","adj-no|n",
        "quốc tế",
        "international | diplomatic intercourse",
        "1286400",
        "国際会議に参加します。","こくさいかいぎにさんかします。","Tôi tham dự hội nghị quốc tế.","I attend an international conference."),
    row("国民","こくみん","N4","n",
        "nhân dân | người dân | công dân | quốc dân",
        "people (of a country) | nation | citizen | national | Democratic Party for the People",
        "1287070",
        "国民の声を聞きます。","こくみんのこえをききます。","Tôi lắng nghe tiếng nói nhân dân.","I listen to the voice of the people."),
    row("子孫","しそん","N4","n",
        "con cháu | hậu duệ",
        "descendant | progeny | offspring",
        "1307990",
        "子孫に伝えます。","しそんにつたえます。","Tôi truyền lại cho con cháu.","I pass it on to descendants."),
    row("取り込む","とりこむ","N4","v5m|vt|vi",
        "tiếp nhận | mang vào | áp dụng | nhập (hình ảnh, dữ liệu) | chinh phục | lừa gạt | bận rộn",
        "to take in | to bring in | to adopt (e.g. behaviour) | to introduce | to capture (e.g. image) | to import | to win over | to please | to curry favour with | to flatter | to defraud of | to swindle | to embezzle | to be busy | to be in confusion | to have trouble",
        "1326720",
        "洗濯物を取り込みます。","せんたくものをとりこみます。","Tôi thu quần áo phơi vào.","I bring in the laundry."),
    row("宗教","しゅうきょう","N4","n",
        "tôn giáo | tín ngưỡng | đức tin",
        "religion | religious affiliation | belief | faith | creed | religious activity",
        "1331400",
        "宗教を信じます。","しゅうきょうをしんじます。","Tôi tin vào tôn giáo.","I believe in a religion."),
    row("抽象的","ちゅうしょうてき","N4","adj-na",
        "trừu tượng",
        "abstract",
        "1426200",
        "抽象的な概念です。","ちゅうしょうてきなかいねんです。","Đây là khái niệm trừu tượng.","It is an abstract concept."),
    row("津波","つなみ","N4","n",
        "sóng thần",
        "tsunami | tidal wave",
        "1432220",
        "津波が来ます。","つなみがきます。","Sóng thần ập đến.","A tsunami comes."),
    row("塗る","ぬる","N4","v5r|vt",
        "sơn | bôi | trát | phủ (kem, thuốc) | tráng (sơn mài)",
        "to paint | to spread | to plaster | to apply (cream, lotion) | to smear | to lacquer | to varnish | to put up (wallpaper)",
        "1444270",
        "壁を塗ります。","かべをぬります。","Tôi sơn tường.","I paint the wall."),
    row("冬至","とうじ","N4","n",
        "điểm phân đông | ngày đông chí",
        "winter solstice",
        "1446130",
        "冬至にゆず湯に入ります。","とうじにゆずゆにはいります。","Vào ngày đông chí, tôi tắm bồn yuzu.","On the winter solstice, I take a yuzu bath."),
    row("盗む","ぬすむ","N4","v5m|vt",
        "ăn cắp | trộm | đạo văn | học lén | làm lén lút | tranh thủ thời gian",
        "to steal | to plagiarize | to steal (a technique, idea, etc.) | to watch and learn | to do stealthily | to do during scant time | to steal a base",
        "1448440",
        "技を盗みます。","わざをぬすみます。","Tôi học lén kỹ thuật.","I steal a technique by watching."),
    row("当時","とうじ","N4","n|adv",
        "lúc đó | thời đó | hồi đó",
        "at that time | in those days",
        "1449090",
        "当時は若かったです。","とうじはわかかったです。","Lúc đó tôi còn trẻ.","I was young at that time."),
    row("配る","くばる","N4","v5r|vt",
        "phân phát | phân chia | giao | phân bổ | bố trí (nhân sự)",
        "to distribute | to hand out | to deliver | to deal out | to serve out | to allot | to allocate | to place (staff, soldiers, etc.) | to station",
        "1472990",
        "チラシを配ります。","チラシをくばります。","Tôi phát tờ rơi.","I hand out flyers."),
    row("買い込む","かいこむ","N4","v5m|vt",
        "mua nhiều | tích trữ | mua dự trữ",
        "to buy in quantity | to buy a lot (of) | to stock up (on) | to lay in",
        "1473610",
        "食料を買い込みます。","しょくりょうをかいこみます。","Tôi tích trữ thực phẩm.","I stock up on food."),
    row("売り出す","うりだす","N4","v5s|vt|vi",
        "bán ra thị trường | bán | bắt đầu bán | trở nên nổi tiếng",
        "to put on the market | to put out for sale | to put on sale | to begin selling | to market | to become popular",
        "1473860",
        "新商品を売り出します。","しんしょうひんをうりだします。","Chúng tôi bán sản phẩm mới ra thị trường.","We put the new product on the market."),
    row("歩き回る","あるきまわる","N4","v5r|vi",
        "đi lại | đi vòng quanh | đi khắp nơi | đi dạo",
        "to walk about | to walk around | to walk to and fro | to pace around | to wander",
        "1514310",
        "街を歩き回ります。","まちをあるきまわります。","Tôi đi khắp thành phố.","I walk around the city."),
    row("磨く","みがく","N4","v5k|vt",
        "đánh bóng | chà sát | đánh răng | mài (kính) | rèn giũa (kỹ năng) | tu dưỡng",
        "to polish | to shine | to burnish | to scour | to scrub | to brush (teeth) | to grind (e.g. a lens) | to refine (a skill, etc.) | to improve | to hone | to polish (up) | to cultivate (one's character)",
        "1523940",
        "歯を磨きます。","はをみがきます。","Tôi đánh răng.","I brush my teeth."),
    row("雷","かみなり","N4","n",
        "sấm sét | tiếng sấm | tia sét | thần sấm | cơn giận dữ",
        "lightning | thunder | thunderbolt | god of thunder | god of lightning | anger | fit of anger",
        "1585060",
        "雷が鳴ります。","かみなりがなります。","Sấm vang lên.","Thunder rumbles."),
    row("暗記","あんき","N4","n|vs|vt",
        "học thuộc lòng | ghi nhớ | học vẹt",
        "memorization | memorisation | learning by heart",
        "1586910",
        "単語を暗記します。","たんごをあんきします。","Tôi học thuộc từ vựng.","I memorize vocabulary."),
    row("悲しみ","かなしみ","N4","n",
        "nỗi buồn | nỗi đau | sự đau buồn | tình cảm",
        "sadness | sorrow | grief | affection | love",
        "1590550",
        "悲しみを感じます。","かなしみをかんじます。","Tôi cảm nhận nỗi buồn.","I feel sadness."),
    row("飛び込む","とびこむ","N4","v5m|vi",
        "nhảy vào | lao vào | lặn xuống | xông vào",
        "to jump in | to leap in | to plunge into | to dive | to burst in | to barge in",
        "1598890",
        "プールに飛び込みます。","プールにとびこみます。","Tôi lao xuống bể bơi.","I dive into the pool."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
