# -*- coding: utf-8 -*-
"""Build N2 ready wave 002 — 85 freshly-curated N2 abstract nouns + 〜点/〜的 + na-adjectives."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-002.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("前兆","ぜんちょう","n","điềm báo | dấu hiệu | điềm | tiền triệu","omen | portent | sign | premonition","1596330"),
    ("物腰","ものごし","n","cử chỉ | phong thái | tác phong","manner | demeanour | bearing","1502510"),
    ("身振り","みぶり","n","điệu bộ | cử chỉ | động tác","gesture | gesticulation | motion","1365720"),
    ("物事","ものごと","n","sự việc | mọi việc | sự vật","things | everything","1502550"),
    ("出来事","できごと","n","sự việc | sự kiện | biến cố","occurrence | happening | incident | event","1340570"),
    ("事柄","ことがら","n","sự việc | vấn đề | tình huống","matter | thing | affair | circumstance","1314240"),
    ("事情","じじょう","n","hoàn cảnh | tình hình | lý do | sự tình","circumstances | situation | reasons","1314010"),
    ("情勢","じょうせい","n","tình thế | tình hình | cục diện","state of affairs | situation | conditions","1356320"),
    ("局面","きょくめん","n","cục diện | thế cờ | tình huống | giai đoạn","position in a game | situation | phase | aspect","1239680"),
    ("実例","じつれい","n","ví dụ thực tế | minh họa | tiền lệ","example | illustration | precedent","1321560"),
    ("事例","じれい","n","ví dụ | trường hợp | tiền lệ","example | precedent | case","1314540"),
    ("前例","ぜんれい","n","tiền lệ","precedent","1394190"),
    ("慣例","かんれい","n","thông lệ | tập quán | lệ thường","custom | practice | convention | precedent","1212750"),
    ("異例","いれい","adj-no|n","ngoại lệ | bất thường | chưa có tiền lệ","exceptional | unusual | unprecedented","1158140"),
    ("特例","とくれい","n","trường hợp đặc biệt | ngoại lệ","special case | exception","1455380"),
    ("本題","ほんだい","n","chủ đề chính | vấn đề chính | đề tài chính","main topic | main subject | main issue","1522970"),
    ("論議","ろんぎ","n|vs|vt","luận bàn | tranh luận | thảo luận","discussion | argument | debate","1561660"),
    ("異論","いろん","n","ý kiến khác | phản đối | dị nghị","different opinion | objection","1158150"),
    ("持論","じろん","n","quan điểm riêng | lý lẽ tâm đắc","one's cherished opinion | pet theory","1635160"),
    ("正論","せいろん","n","lý lẽ đúng đắn | lập luận chính đáng","sound argument | just reasoning","1378130"),
    ("矛先","ほこさき","n","mũi giáo | hướng công kích | mũi nhọn (chỉ trích)","spearhead | focus (of one's attack/criticism) | target","1531100"),
    ("争点","そうてん","n","điểm tranh chấp | vấn đề tranh cãi","point at issue","1400700"),
    ("盲点","もうてん","n","điểm mù | điểm yếu | kẽ hở","blind spot | weak point | loophole","1534280"),
    ("利点","りてん","n","ưu điểm | điểm lợi | thế mạnh","advantage | point in favour","1549620"),
    ("難点","なんてん","n","nhược điểm | điểm yếu | điểm khó | điểm gây tranh cãi","fault | weakness | drawback | difficult point","1461040"),
    ("起点","きてん","n","điểm khởi đầu | điểm xuất phát","starting point | origin","1223860"),
    ("原点","げんてん","n","điểm gốc | khởi điểm | gốc tọa độ","starting point | origin | datum point","1262160"),
    ("拠点","きょてん","n","căn cứ | địa bàn | cứ điểm | vị trí trọng yếu","base (of operations) | foothold | stronghold","1232440"),
    ("接点","せってん","n","điểm tiếp xúc | tiếp điểm | điểm chung","point of contact | (electrical) contact | common ground","1385610"),
    ("時点","じてん","n","thời điểm | mốc thời gian","point in time | occasion","1316340"),
    ("平穏","へいおん","adj-na|n","yên bình | êm ả | thanh bình","tranquil | calm | peaceful | quiet","1507070"),
    ("柔和","にゅうわ","adj-na|n","dịu dàng | hiền hòa | nhu mì","gentle | mild | meek | tender","1335510"),
    ("律儀","りちぎ","adj-na|n","chính trực | thật thà | tận tâm","upright | honest | conscientious | sincere","1551170"),
    ("実直","じっちょく","adj-na|n","trung thực | chững chạc | thật thà","honest | steady","1321390"),
    ("純情","じゅんじょう","n|adj-na","ngây thơ | trong sáng | hồn nhiên","pure heart | naivete | innocence","1341910"),
    ("忠実","ちゅうじつ","adj-na|n","trung thành | tận tụy | trung thực","faithful | devoted | loyal | honest","1012210"),
    ("怠惰","たいだ","adj-na|n","lười biếng | uể oải | biếng nhác","lazy | idle | indolent | slothful","1410730"),
    ("横着","おうちゃく","n|adj-na|vs","lười nhác | trốn việc | trơ tráo","laziness | shirking | impudent","1180920"),
    ("無愛想","ぶあいそう","adj-na|n","lạnh lùng | cộc cằn | khó gần","unsociable | blunt | surly | curt","1529580"),
    ("寡黙","かもく","adj-na|n","ít nói | trầm lặng | kiệm lời","untalkative | quiet | taciturn | reticent","1192660"),
    ("饒舌","じょうぜつ","n|adj-na","nói nhiều | lắm lời | dẻo mồm","talkativeness | garrulity | loquacity","1574520"),
    ("気長","きなが","adj-na","kiên nhẫn | thong thả | điềm tĩnh","patient | unhurried | leisurely","1222480"),
    ("気短","きみじか","adj-na","nóng tính | thiếu kiên nhẫn | hấp tấp","short-tempered | impatient | hasty","1791230"),
    ("短気","たんき","n|adj-na","nóng tính | dễ cáu | thiếu kiên nhẫn","short temper | impatience | irritability","1418670"),
    ("内気","うちき","adj-na|n","nhút nhát | rụt rè | e dè","shy | bashful | timid | reserved","1458020"),
    ("勝ち気","かちき","adj-na|n","hiếu thắng | không chịu thua | ý chí mạnh","determined spirit | unyielding spirit","1706630"),
    ("弱気","よわき","adj-na|n","yếu đuối | nhụt chí | bi quan (thị trường)","timid | weak-kneed | fainthearted | bearish","1324710"),
    ("強気","つよき","adj-na|n","mạnh mẽ | tự tin | cứng rắn | lạc quan (thị trường)","confident | firm | strong | bullish","1236230"),
    ("正気","しょうき","n|adj-no","tỉnh táo | minh mẫn | sáng suốt","sanity | consciousness | soberness","1580850"),
    ("本気","ほんき","n|adj-na","nghiêm túc | thật lòng | thật sự","seriousness | earnestness","1522370"),
    ("高飛車","たかびしゃ","adj-na|n","hống hách | trịch thượng | kẻ cả","high-handed | domineering | on one's high horse","1283910"),
    ("高圧的","こうあつてき","adj-na","cao tay | áp chế | đàn áp","high-handed | oppressive","1808790"),
    ("威圧的","いあつてき","adj-na","uy hiếp | hống hách | áp đảo","coercive | overbearing","1781230"),
    ("攻撃的","こうげきてき","adj-na","mang tính tấn công | hung hăng | gây hấn","offensive | aggressive","1675250"),
    ("好戦的","こうせんてき","adj-na","hiếu chiến | thích gây chiến","belligerent | warlike","1835960"),
    ("排他的","はいたてき","adj-na","bài ngoại | loại trừ | cục bộ","exclusive | exclusionary | clannish","1472430"),
    ("独善的","どくぜんてき","adj-na","tự cho mình đúng | độc đoán tự mãn","self-righteous","1691620"),
    ("利己的","りこてき","adj-na","ích kỷ | vị kỷ | tư lợi","selfish | egoistic | self-serving","1549540"),
    ("打算的","ださんてき","adj-na","tính toán | vụ lợi | thực dụng","calculating | mercenary | self-interested","1408890"),
    ("現実的","げんじつてき","adj-na","thực tế | thực dụng","realistic | pragmatic","1263730"),
    ("理想的","りそうてき","adj-na","lý tưởng","ideal","1550040"),
    ("楽天的","らくてんてき","adj-na","lạc quan | yêu đời","optimistic","1207480"),
    ("保守的","ほしゅてき","adj-na","bảo thủ","conservative","1603490"),
    ("革新的","かくしんてき","adj-na","cách tân | đổi mới | cấp tiến","innovative | progressive | reformist","1206490"),
    ("進歩的","しんぽてき","adj-na","tiến bộ","progressive","1813340"),
    ("封建的","ほうけんてき","adj-na","phong kiến","feudal | feudalistic","1611510"),
    ("独創的","どくそうてき","adj-na","sáng tạo | độc đáo | mới mẻ","creative | original","1455950"),
    ("建設的","けんせつてき","adj-na","mang tính xây dựng | tích cực","constructive","1257460"),
    ("破壊的","はかいてき","adj-na","phá hoại | tàn phá | hủy diệt","destructive | devastating","1471270"),
    ("徹底的","てっていてき","adj-na","triệt để | toàn diện | tận gốc","thorough | exhaustive | complete","1437680"),
    ("断片的","だんぺんてき","adj-na","rời rạc | mảnh vụn | manh mún","fragmentary","1704890"),
    ("中途半端","ちゅうとはんぱ","adj-na|n","nửa vời | dở dang | không trọn vẹn","halfway | unfinished | half-baked | half-hearted","1425050"),
    ("不十分","ふじゅうぶん","adj-na|n","không đủ | thiếu sót | chưa đầy đủ","insufficient | inadequate | imperfect","1492740"),
    ("不完全","ふかんぜん","adj-na|n","không hoàn chỉnh | khiếm khuyết | lỗi","imperfect | incomplete | defective","1491710"),
    ("周到","しゅうとう","adj-na|n","chu đáo | kỹ lưỡng | tỉ mỉ","careful | thorough | meticulous | scrupulous","1331230"),
    ("細心","さいしん","adj-na|n","cẩn thận tỉ mỉ | thận trọng | chu đáo","meticulous | careful | discreet | prudent","1295650"),
    ("痛烈","つうれつ","adj-na|n","gay gắt | kịch liệt | sâu cay","severe | bitter | scathing","1432820"),
    ("熾烈","しれつ","adj-na|n","khốc liệt | ác liệt | gay gắt","fierce | severe | bitter | cutthroat","1569130"),
    ("鮮烈","せんれつ","adj-na|n","sống động | ấn tượng mạnh | rực rỡ","vivid | striking","1392550"),
    ("壮絶","そうぜつ","adj-na|n","hào hùng | ác liệt | hùng tráng","heroic | fierce | grand | sublime","1399420"),
    ("凄絶","せいぜつ","adj-na|n","kinh hoàng | dữ dội | đẫm máu","extremely gruesome | violent | fierce","1725780"),
    ("悲惨","ひさん","adj-na|n","thê thảm | bi thảm | khốn khổ","disastrous | tragic | miserable | wretched","1483290"),
    ("凄惨","せいさん","adj-na|n","kinh khủng | rùng rợn | thảm khốc","ghastly | gruesome | appalling | lurid","1374580"),
    ("無残","むざん","adj-na|n","tàn nhẫn | thảm thương | bi thảm","cruel | merciless | ruthless | pitiful | tragic","1530010"),
    ("峻烈","しゅんれつ","adj-na|n","nghiêm khắc | gay gắt | sắc bén","severe | harsh | rigorous | trenchant | incisive","1700080"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
