# -*- coding: utf-8 -*-
"""Build N3 ready wave 055 — 73 freshly-curated N3 weather/season/time + geography/nature/ecology nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-055.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("気象","きしょう","n","khí tượng | thời tiết | tính khí","weather (conditions) | disposition","1222270"),
    ("晴天","せいてん","n","trời quang | trời nắng đẹp | trời trong","fine weather | clear sky | fair skies","1376550"),
    ("雨天","うてん","n","trời mưa | thời tiết mưa","rainy weather","1172100"),
    ("猛暑","もうしょ","n","nắng nóng gay gắt | đợt nóng dữ dội","heat wave | fierce heat","1534050"),
    ("真夏","まなつ","n","giữa hè | đỉnh điểm mùa hè","middle of summer | midsummer","1363480"),
    ("真冬","まふゆ","n","giữa đông | đỉnh điểm mùa đông","midwinter | dead of winter","1364210"),
    ("初夏","しょか","n","đầu hè","early summer","1342580"),
    ("日差し","ひざし","n","ánh nắng | tia nắng","sunlight | rays of the Sun","1601830"),
    ("日陰","ひかげ","n","bóng râm | chỗ râm | nắng","shade | shadow | sunshine","1463840"),
    ("日向","ひなた","n","chỗ có nắng | nơi có ánh nắng","sunny place | in the sun","1464050"),
    ("満開","まんかい","n|vs|vi","nở rộ | nở rộ hết cỡ (hoa)","full bloom (esp. cherry blossom)","1526750"),
    ("新緑","しんりょく","n","màu xanh non | lá non đầu mùa","fresh verdure | new green leaves","1362460"),
    ("若葉","わかば","n","lá non | chồi non","new leaves | young leaves","1324460"),
    ("四季","しき","n","bốn mùa | tứ thời","the four seasons","1307130"),
    ("暦","こよみ","n","lịch | niên lịch","calendar | almanac","1557950"),
    ("平日","へいじつ","n|adv","ngày thường | ngày trong tuần","weekday | ordinary days","1507720"),
    ("休日","きゅうじつ","n","ngày nghỉ | ngày lễ","holiday | day off","1228040"),
    ("年末","ねんまつ","n|adv","cuối năm | dịp cuối năm","end-of-year | year-end","1469210"),
    ("元日","がんじつ","n","ngày mùng 1 Tết | ngày đầu năm","New Year's Day","1261010"),
    ("上旬","じょうじゅん","n","thượng tuần | 10 ngày đầu tháng","first third of a month | first ten days","1353410"),
    ("中旬","ちゅうじゅん","n","trung tuần | 10 ngày giữa tháng","middle ten days of a month","1424490"),
    ("下旬","げじゅん","n","hạ tuần | 10 ngày cuối tháng","last third of a month","1185330"),
    ("半ば","なかば","n|adv","giữa | nửa | quá nửa | gần như","middle | halfway | half (of) | partly | nearly","1478780"),
    ("当日","とうじつ","n|adv","đúng ngày | ngày hôm đó","day in question | that very day","1449210"),
    ("前日","ぜんじつ","n|adv","ngày hôm trước | hôm trước","previous day | day before | eve","1393790"),
    ("翌日","よくじつ","n|adv","ngày hôm sau | hôm sau","next day","1547510"),
    ("前夜","ぜんや","n|adv","đêm hôm trước | đêm trước (lễ)","last night | the previous night | eve","1394100"),
    ("深夜","しんや","n|adv","đêm khuya | nửa đêm","late at night","1362810"),
    ("早朝","そうちょう","n","sáng sớm | tinh mơ","early morning","1397340"),
    ("日没","にちぼつ","n","hoàng hôn | mặt trời lặn","sunset","1464450"),
    ("日の出","ひので","n","bình minh | mặt trời mọc","sunrise","1463790"),
    ("真夜中","まよなか","n","nửa đêm | giữa đêm khuya","midnight | dead of night","1363400"),
    ("地上","ちじょう","n","mặt đất | trên mặt đất","above ground | on the ground","1421900"),
    ("大地","だいち","n","đại địa | mặt đất | đất đai","ground | earth | the land","1414380"),
    ("土地","とち","n","đất | thửa đất | vùng đất | địa phương","plot of land | soil | locality | region","1445470"),
    ("土壌","どじょう","n","đất (trồng) | thổ nhưỡng | mảnh đất (cho...)","soil | breeding ground (for) | fertile ground","1445380"),
    ("沼","ぬま","n","đầm | đầm lầy | ao | sự nghiện ngập","marsh | swamp | pond | obsession","1350010"),
    ("沿岸","えんがん","n","duyên hải | ven biển | vùng ven bờ","coast | shore | coastal area","1176740"),
    ("湾","わん","n","vịnh | vũng","bay | gulf | inlet","1562800"),
    ("潮","しお","n","thủy triều | dòng nước | thời cơ","tide | current | sea water | opportunity","1428620"),
    ("鉱山","こうざん","n","mỏ (khoáng sản)","mine (ore)","1282570"),
    ("鉱物","こうぶつ","n","khoáng vật | khoáng sản","mineral","1282650"),
    ("家畜","かちく","n","gia súc | vật nuôi","domestic animals | livestock | cattle","1192240"),
    ("野生","やせい","adj-no|n","hoang dã | mọc/sống hoang","wild | growing wild | living in the wild","1537470"),
    ("雑草","ざっそう","n","cỏ dại","weed","1299460"),
    ("樹木","じゅもく","n","cây cối | cây gỗ | cây và bụi","tree | trees and shrubs","1330400"),
    ("苗","なえ","n","cây giống | cây con | mạ","seedling | young plant | rice seedling","1490470"),
    ("果実","かじつ","n","quả | trái cây | hạt | lợi tức","fruit | nut | berry | profit","1192940"),
    ("種子","しゅし","n","hạt giống | hạt | hột","seed | pit","1328830"),
    ("胞子","ほうし","n","bào tử","spore","1517730"),
    ("群れ","むれ","n","bầy | đàn | đám đông | cụm","group | crowd | flock | herd | swarm","1247510"),
    ("巣","す","n","tổ | hang | ổ | mạng nhện","nest | hive | den | (spider's) web","1400390"),
    ("獲物","えもの","n","con mồi | chiến lợi phẩm | thú săn","prey | catch | game | spoils","1205760"),
    ("餌","えさ","n","thức ăn (vật nuôi) | mồi | miếng nhử","(animal) feed | fodder | bait | lure","1173340"),
    ("天敵","てんてき","n","thiên địch | kẻ thù tự nhiên","natural enemy","1440030"),
    ("食物連鎖","しょくもつれんさ","n","chuỗi thức ăn","food chain","1839580"),
    ("繁殖","はんしょく","n|vs|vi","sinh sản | nhân giống | phát triển","breeding | propagation | reproduction","1481700"),
    ("生息","せいそく","n|vs|vi","sinh sống | sinh sống (động vật)","inhabiting | living","1379220"),
    ("渡り鳥","わたりどり","n","chim di cư | chim di trú","migratory bird","1444650"),
    ("冬眠","とうみん","n|vs|vi","ngủ đông","hibernation | winter sleep","1446150"),
    ("保護","ほご","n|vs|vt","bảo vệ | che chở | bảo tồn","protection | safeguard | preservation | conservation","1513530"),
    ("乱獲","らんかく","n|vs|vt","đánh bắt/săn bừa bãi | khai thác cạn kiệt","overfishing | overhunting | indiscriminate hunting","1606200"),
    ("密漁","みつりょう","n|vs|vt","đánh bắt trộm | săn bắt trái phép (hải sản)","poaching (fish or seafood)","1731580"),
    ("公害","こうがい","n","ô nhiễm môi trường | tác hại công cộng","pollution | public nuisance | contamination","1273420"),
    ("排出","はいしゅつ","n|vs|vt","thải ra | xả thải | bài tiết","discharge | emission (e.g. of CO2) | excretion","1472360"),
    ("廃棄","はいき","n|vs|vt","thải bỏ | vứt bỏ | hủy bỏ","disposal | scrapping | abolition | annulment","1472030"),
    ("処分","しょぶん","n|vs|vt","xử lý | thải bỏ | xử phạt","disposal | dealing with | punishment | penalty","1342490"),
    ("再利用","さいりよう","n|vs","tái sử dụng | tái chế","reuse | recycling","2019260"),
    ("発電","はつでん","n|vs|vt|vi","phát điện | sản xuất điện","generation of electricity | power generation","1477750"),
    ("電力","でんりょく","n","điện năng | công suất điện","electric power","1443810"),
    ("石油","せきゆ","n","dầu mỏ | dầu hỏa","oil | petroleum | kerosene","1382830"),
    ("石炭","せきたん","n","than đá","coal","1382700"),
    ("天然","てんねん","n|adj-no","tự nhiên | thiên nhiên","nature | natural","1439580"),
    ("人工","じんこう","n|adj-no","nhân tạo | do con người tạo ra","artificial | man-made","1367380"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
