# -*- coding: utf-8 -*-
"""Build N2 ready wave 025 — sino-verbs: establishment, creation, production, in/out, change, use, employment."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-025.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("創出","そうしゅつ","n|vs|vt","tạo ra | sản sinh | kiến tạo","creation | generation","1638030"),
    ("創設","そうせつ","n|vs|vt","sáng lập | thành lập | thiết lập","establishment | founding","1398540"),
    ("創立","そうりつ","n|vs|vt","sáng lập | thành lập | khai sáng","establishment | founding","1398640"),
    ("設立","せつりつ","n|vs|vt","thành lập | thiết lập | sáng lập (doanh nghiệp)","establishment | founding | incorporation","1386090"),
    ("樹立","じゅりつ","n|vs|vt|vi","thiết lập | gây dựng | lập (kỷ lục)","establishment | founding | setting (a record)","1330410"),
    ("確立","かくりつ","n|vs|vt|vi","xác lập | thiết lập | củng cố vững chắc","establishment | settlement","1206030"),
    ("成立","せいりつ","n|vs|vi","thành lập | hình thành | đạt được | thông qua","formation | establishment | conclusion","1375880"),
    ("擁立","ようりつ","n|vs|vt","ủng hộ | hậu thuẫn | nâng đỡ (lên vị trí)","backing (for a position) | giving support to","1545760"),
    ("建立","こんりゅう","n|vs|vt","xây dựng (chùa, đài) | dựng | kiến lập","building (temple, monument) | erection","1257550"),
    ("創造","そうぞう","n|vs|vt","sáng tạo | sáng thế","creation","1398560"),
    ("構築","こうちく","n|vs|vt","xây dựng | thiết lập | kiến tạo (hệ thống)","construction | building | formulation","1279810"),
    ("編成","へんせい","n|vs|vt","biên chế | tổ chức | thành lập | dàn dựng","composition | formation | compilation","1512040"),
    ("構成","こうせい","n|vs|vt","cấu thành | tạo nên | kết cấu | cơ cấu","composition | construction | structure","1279730"),
    ("醸成","じょうせい","n|vs|vt","ủ men | nung nấu | tạo nên (bầu không khí)","brewing | fermenting | bringing about","1357080"),
    ("作成","さくせい","n|vs|vt","lập (báo cáo, kế hoạch) | soạn | tạo (file)","making (a document) | drawing up | creating","1297760"),
    ("完成","かんせい","n|vs|vt|vi","hoàn thành | hoàn thiện | hoàn tất","completion | perfection | accomplishment","1211490"),
    ("養成","ようせい","n|vs|vt","đào tạo | bồi dưỡng | huấn luyện","training | education | development","1547190"),
    ("生成","せいせい","n|vs|vt|vi","tạo thành | sinh ra | hình thành","creation | generation | formation","1379180"),
    ("組成","そせい","n|vs|vt","thành phần | cấu tạo | tỷ lệ cấu thành","composition | constitution","1397670"),
    ("促成","そくせい","n|vs|vt","thúc cho mau lớn | thúc tăng trưởng","promotion of growth","1403800"),
    ("速成","そくせい","n|vs|vt","hoàn thành nhanh | đào tạo cấp tốc","rapid completion | intensive training","1709080"),
    ("既成","きせい","adj-no|n","đã có sẵn | đã hình thành | đã thành (sự thật)","established | existing | accomplished","1220390"),
    ("特製","とくせい","n|vs|vt|adj-no","chế tạo đặc biệt | hàng đặc chế | cao cấp","special make | deluxe","1455100"),
    ("精製","せいせい","n|vs|vt","tinh chế | tinh luyện | chế tác kỹ lưỡng","refining | purification","1380070"),
    ("製作","せいさく","n|vs|vt","chế tạo | sản xuất | sản xuất (phim, kịch)","manufacture | production (of a film, etc.)","1380650"),
    ("増産","ぞうさん","n|vs|vt","tăng sản lượng | tăng sản xuất","increase in production","1403220"),
    ("減産","げんさん","n|vs|vt|vi","giảm sản lượng | giảm sản xuất","decrease in production","1263180"),
    ("産出","さんしゅつ","n|vs|vt","sản xuất | sản lượng | khai thác (khoáng sản)","production | output | extraction","1303810"),
    ("算出","さんしゅつ","n|vs|vt","tính ra | tính toán | tính được","calculation | computation","1303910"),
    ("案出","あんしゅつ","n|vs|vt","nghĩ ra | sáng chế | phát kiến","contrivance | invention","1154850"),
    ("摘出","てきしゅつ","n|vs|vt","lấy ra | bóc tách | cắt bỏ (phẫu thuật) | vạch ra","picking out | (surgical) removal | exposure","1437070"),
    ("輩出","はいしゅつ","n|vs|vt|vi","sản sinh hàng loạt (nhân tài) | xuất hiện nối tiếp","producing (people) in great numbers","1472980"),
    ("放出","ほうしゅつ","n|vs|vt|vi","phóng thích | thải ra | tỏa ra | xả (hàng)","emission | release | discharge","1516710"),
    ("噴出","ふんしゅつ","n|vs|vt|vi","phun ra | trào ra | phun trào | bộc phát","spewing | gushing | eruption","1504600"),
    ("流出","りゅうしゅつ","n|vs|vi","chảy ra | tràn ra | rò rỉ | chảy máu (chất xám)","outflow | spill | leak | drain","1552350"),
    ("流入","りゅうにゅう","n|vs|vi","chảy vào | đổ vào | tràn vào","inflow | influx","1552510"),
    ("浸入","しんにゅう","n|vs|vi","thấm vào | ngấm vào | nước tràn vào","infiltration (e.g. of water) | flooding","2826248"),
    ("侵入","しんにゅう","n|vs|vi","xâm nhập | đột nhập | xâm lược | xâm phạm","invasion | intrusion | trespass | hacking","1359850"),
    ("混入","こんにゅう","n|vs|vt|vi","trộn lẫn | pha trộn | lẫn vào | pha tạp","mixing | blending | adulteration","1290510"),
    ("封入","ふうにゅう","n|vs|vt","gói kín bên trong | gửi kèm (trong thư)","sealing inside | enclosing","1499700"),
    ("記入","きにゅう","n|vs|vt","ghi vào | điền vào (mẫu, sổ)","entry (in a form) | filling in","1223330"),
    ("編入","へんにゅう","n|vs|vt","biên chế vào | sáp nhập | chuyển tiếp (vào lớp)","admission | incorporation | enrollment","1512060"),
    ("組み入れ","くみいれ","n","đưa vào | lồng vào | lắp ghép vào","incorporating | inserting | nesting","2798470"),
    ("組み込み","くみこみ","n|vs|vt|adj-f","tích hợp | cài vào | nhúng (phần mềm)","insertion | inclusion | built-in | embedded","1397500"),
    ("取り入れ","とりいれ","n","thu vào | thu hoạch | tiếp nhận","taking in | harvesting","1707310"),
    ("受け入れ","うけいれ","n","tiếp nhận | chấp nhận | đón nhận","receiving | acceptance | admission","1329660"),
    ("申し入れ","もうしいれ","n","đề nghị | đề xuất | yêu cầu | thông báo","proposal | offer | proposition | request","1605130"),
    ("立ち上げ","たちあげ","n","khởi động | khởi sự (doanh nghiệp, máy)","starting up (e.g. business, computer)","2056160"),
    ("打ち切り","うちきり","n","kết thúc | ngừng | cắt ngang | hủy bỏ","end | discontinuance | cancellation | aborting","1633630"),
    ("入れ替え","いれかえ","n|vs|vt","thay thế | thay đổi | đổi chỗ | dồn toa","replacement | substitution | switching","1791760"),
    ("組み替え","くみかえ","n|vs","sắp xếp lại | tái tổ hợp | phân lại (lớp)","rearrangement | recombination","1397520"),
    ("建て替え","たてかえ","n|vs|vt","xây lại | xây dựng lại | tái thiết","rebuilding | reconstruction","2581570"),
    ("書き換え","かきかえ","n","viết lại | làm mới (giấy phép) | sang tên","rewriting | renewal (of a license) | transfer","2076640"),
    ("言い換え","いいかえ","n","nói cách khác | diễn đạt lại | thay lời","rephrasing | rewording | paraphrase","1756480"),
    ("取り替え","とりかえ","n","đổi | trao đổi | thay thế","swap | exchange","1599020"),
    ("引き換え","ひきかえ","n","đổi lấy | hoán đổi | quy đổi","exchange | conversion","1601550"),
    ("模様替え","もようがえ","n|vs|vt","sắp xếp lại | bài trí lại | đổi cách bố trí","rearranging | remodeling","1670970"),
    ("方向転換","ほうこうてんかん","n|vs","đổi hướng | chuyển hướng","change of course","1709890"),
    ("転化","てんか","n|vs|vi","chuyển hóa | biến đổi | đảo ngược","change | transformation | inversion","1654320"),
    ("併用","へいよう","n|vs|vt","dùng kết hợp | sử dụng đồng thời","combined use | using together","1506200"),
    ("兼用","けんよう","n|vs|vt|adj-no","dùng kiêm | dùng chung | dùng đa năng","multi-use | combined use","1256720"),
    ("代用","だいよう","n|vs|vt|adj-no","dùng thay | thay thế | thế phẩm","substitution","1412360"),
    ("乱用","らんよう","n|vs|vt","lạm dụng | dùng quá mức | dùng sai","abuse | misuse","1549120"),
    ("誤用","ごよう","n|vs|vt","dùng sai | dùng nhầm | lạm dụng","misuse | incorrect use","1271500"),
    ("盗用","とうよう","n|vs|vt","dùng trộm | đạo (văn) | chiếm dụng trái phép","embezzlement | plagiarism | appropriation","1448550"),
    ("重用","じゅうよう","n|vs|vt","trọng dụng | tin dùng | giao trọng trách","appointing to a position of trust | making much of","1336810"),
    ("免職","めんしょく","n|vs|vt","cách chức | sa thải | thôi việc","dismissal | sacking | discharge","1533220"),
    ("休職","きゅうしょく","n|vs|vi","nghỉ việc tạm thời | đình chỉ công tác","leave of absence | suspension from office","1227840"),
    ("復職","ふくしょく","n|vs|vi","phục chức | trở lại làm việc","reinstatement | reappointment","1500850"),
    ("辞職","じしょく","n|vs|vi","từ chức | thôi việc","resignation","1318980"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
