# -*- coding: utf-8 -*-
"""Build N3 ready wave 050 — 85 freshly-curated N3 adverbs/onomatopoeia/time + IT/media nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-050.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("うっかり","うっかり","adv|vs","lơ đãng | vô ý | sơ ý","carelessly | thoughtlessly | inadvertently","1001010"),
    ("たっぷり","たっぷり","adv|adj-na","đầy đủ | dư dả | nhiều | rộng rãi","plentifully | amply | a lot | with room to spare","1007240"),
    ("さっぱり","さっぱり","adv|vs|adj-na","sảng khoái | gọn gàng | thanh đạm | chẳng chút nào","refreshed | neat | light (taste) | not at all (with neg.)","1005210"),
    ("きっぱり","きっぱり","adv|vs","dứt khoát | rõ ràng | thẳng thừng","clearly | decisively | flatly | resolutely","1003440"),
    ("うんざり","うんざり","adv|vs","chán ngán | phát ngấy | ngán ngẩm","tedious | boring | being fed up with","1001110"),
    ("ゆったり","ゆったり","adv|vs","thoải mái | thư thái | rộng rãi","comfortable | relaxed | loose | spacious","2010000"),
    ("ぐったり","ぐったり","adv|vs","bơ phờ | rũ rượi | kiệt sức","limply | wearily | listlessly | exhaustedly","1004070"),
    ("ぎっしり","ぎっしり","adv","chật ních | dày đặc | kín mít","tightly (packed) | densely | crammed","1003590"),
    ("めっきり","めっきり","adv","rõ rệt | thấy rõ | đáng kể","remarkably | noticeably | visibly | considerably","1012470"),
    ("てっきり","てっきり","adv","chắc mẩm | đinh ninh | chắc chắn","surely | certainly | without doubt","1008290"),
    ("偶々","たまたま","adv","tình cờ | ngẫu nhiên | thỉnh thoảng","by chance | accidentally | occasionally","1597180"),
    ("一々","いちいち","n|adv","từng cái một | từng li từng tí | mỗi cái","one-by-one | each and every | in detail","1587320"),
    ("別々","べつべつ","adj-na|n","riêng rẽ | tách biệt | mỗi người một","separate | respective | different","1603290"),
    ("我々","われわれ","pn","chúng tôi | chúng ta","we","1607050"),
    ("早々","そうそう","n|adv","ngay sau khi | vội vàng | sớm","as soon as ... | hurriedly | promptly | early","1596420"),
    ("着実","ちゃくじつ","adj-na|n","vững chắc | chắc chắn | đáng tin","steady | sound | solid | reliable","1423050"),
    ("案の定","あんのじょう","adv","đúng như dự đoán | quả nhiên | y như rằng","as expected | just as one thought | sure enough","1154790"),
    ("思い切り","おもいきり","adv|n","hết mình | thỏa thích | dứt khoát","to one's heart's content | as hard as one can | decisiveness","2834138"),
    ("突如","とつじょ","adv","đột nhiên | bất thình lình | bất ngờ","suddenly | all of a sudden | unexpectedly","1457090"),
    ("急遽","きゅうきょ","adv|adj-na","gấp gáp | vội vàng | đột xuất","hurriedly | hastily | sudden | abrupt","1229020"),
    ("直後","ちょくご","n|adv","ngay sau | liền sau đó","immediately following","1430930"),
    ("直前","ちょくぜん","n|adv","ngay trước | sát trước | trước mặt","just before | just prior to | right in front of","1431330"),
    ("事前","じぜん","adj-no","trước | trước khi | từ trước","prior | beforehand | in advance","1314050"),
    ("事後","じご","adj-no","sau (sự việc) | hậu kỳ","after | post | after the fact","1313880"),
    ("当面","とうめん","adj-no|n|adv","trước mắt | hiện tại | đối mặt","current | impending | for the meantime | to confront","1449250"),
    ("近年","きんねん","n|adv","những năm gần đây | thời gian gần đây","recent years","1242510"),
    ("日頃","ひごろ","adv|n","thường ngày | bình thường | lâu nay","usually | habitually | always","1464070"),
    ("終始","しゅうし","n|vs|adv","từ đầu đến cuối | suốt | nhất quán","from beginning to end | throughout | consistently","1332820"),
    ("絶えず","たえず","adv","không ngừng | liên tục | luôn luôn","constantly | always | continually","1386700"),
    ("永遠","えいえん","n|adj-na","vĩnh viễn | mãi mãi | vĩnh hằng","eternity | perpetuity | permanence","1174070"),
    ("永久","えいきゅう","n|adj-na","vĩnh cửu | lâu dài | vĩnh viễn","eternity | permanence | perpetuity","1576520"),
    ("一時","いちじ","n|adv","một thời | tạm thời | có lúc | một giờ","once | for a time | temporarily | one o'clock","1576100"),
    ("通信","つうしん","n|vs|vt|vi","liên lạc | truyền thông | thông tin","correspondence | communication | transmission | telecommunications","1433330"),
    ("通話","つうわ","n|vs|vi","cuộc gọi | đàm thoại | gọi điện","telephone call | speaking over the phone | voice call","1433610"),
    ("端末","たんまつ","n","thiết bị đầu cuối | máy (điện thoại, máy tính)","terminal | computer terminal | device","1418950"),
    ("機器","きき","n","thiết bị | máy móc | dụng cụ","device | equipment | machinery | apparatus","1220900"),
    ("画像","がぞう","n","hình ảnh | ảnh","image | picture | portrait","1197390"),
    ("映像","えいぞう","n","hình ảnh (màn hình) | video | đoạn phim","image (on a screen) | video | footage","1173800"),
    ("音声","おんせい","n","âm thanh | giọng nói | tiếng","voice | speech | sound","1183880"),
    ("再生","さいせい","n|vs|vt|vi","tái sinh | tái chế | phát lại | phục hồi","regeneration | recycling | playback | rebirth","1292960"),
    ("入力","にゅうりょく","n|vs|vt","nhập (dữ liệu) | đầu vào | gõ","input | (data) entry | typing","1466850"),
    ("出力","しゅつりょく","n|vs|vt","đầu ra | xuất (tín hiệu)","output (electrical, signal, etc.)","1340700"),
    ("表示","ひょうじ","n|vs|vt","hiển thị | biểu thị | thể hiện","indication | showing | display | representation","1489610"),
    ("起動","きどう","n|vs|vt|vi","khởi động | kích hoạt | bật","startup | booting up | activation | launch","1223880"),
    ("伝達","でんたつ","n|vs|vt","truyền đạt | chuyển tiếp | dẫn truyền","transmission | communication | conveyance | relay","1442240"),
    ("発信","はっしん","n|vs|vt|vi","phát đi | gửi | đưa tin","dispatch | transmission | informing | sharing","1477560"),
    ("受信","じゅしん","n|vs|vt","nhận (tin) | thu (sóng)","receiving (a message) | reception (radio, TV)","1329810"),
    ("送信","そうしん","n|vs|vt","gửi đi | truyền đi","transmission | sending","1402820"),
    ("配信","はいしん","n|vs|vt","phân phối (nội dung) | phát sóng | phát trực tuyến","distribution | delivery | streaming","1639050"),
    ("中継","ちゅうけい","n|vs|vt","tiếp sóng | trung chuyển | truyền hình trực tiếp","relay | hook-up | relay broadcasting","1424040"),
    ("番組","ばんぐみ","n","chương trình (TV, radio)","program (e.g. TV) | programme","1482340"),
    ("視聴","しちょう","n|vs|vt","xem (truyền hình) | theo dõi | sự chú ý","(television) viewing | watching | (public) attention","1312070"),
    ("観客","かんきゃく","n","khán giả | người xem","spectator | audience","1214810"),
    ("聴衆","ちょうしゅう","n","thính giả | người nghe | khán thính giả","audience | attendance | hearers","1428910"),
    ("読者","どくしゃ","n","độc giả | người đọc","reader","1456400"),
    ("購読","こうどく","n|vs|vt","đặt mua (báo) | đăng ký đọc | mua đọc","subscribing | buying and reading | taking (a newspaper)","1282420"),
    ("投稿","とうこう","n|vs|vt|vi","đăng bài | gửi bài | bài đăng","contribution (to a publication) | submission | post","1447180"),
    ("噂","うわさ","n|vs","tin đồn | lời đồn | bàn tán","rumour | report | gossip | common talk","1172590"),
    ("評論","ひょうろん","n|vs|vt","bình luận | phê bình | nhận xét","criticism | critique | review | comment","1490080"),
    ("感想","かんそう","n","cảm tưởng | cảm nghĩ | suy nghĩ","impressions | thoughts | feelings | reactions","1212480"),
    ("発言","はつげん","n|vs|vt|vi","phát ngôn | phát biểu | lời nói","statement | remark | utterance | speech","1477350"),
    ("主題","しゅだい","n","chủ đề | đề tài | mô-típ","subject | theme | motif","1325870"),
    ("要約","ようやく","n|vs|vt","tóm tắt | tóm lược","summary | digest","1605860"),
    ("描写","びょうしゃ","n|vs|vt","miêu tả | mô tả | khắc họa","depiction | description | portrayal","1490140"),
    ("象徴","しょうちょう","n|vs|vt","biểu tượng | tượng trưng","symbol | emblem | (symbolic) representation","1351900"),
    ("抽象","ちゅうしょう","n|vs|vt","trừu tượng","abstraction","1426190"),
    ("具体","ぐたい","n","cụ thể | sự cụ thể hóa","concreteness | embodiment","1245020"),
    ("概略","がいりゃく","n|adv","sơ lược | đại cương | tóm tắt","outline | summary | gist | in brief","1204510"),
    ("細部","さいぶ","n","chi tiết | phần chi tiết | tiểu tiết","details | particulars","1295710"),
    ("部分","ぶぶん","n","bộ phận | phần | một phần","portion | section | part","1499490"),
    ("一部","いちぶ","n|adv","một phần | một bộ phận | một bản (sách)","one part | one portion | one copy (of a book)","1166180"),
    ("過半数","かはんすう","n","đa số | quá bán","majority","1196380"),
    ("少数","しょうすう","n|adj-no","số ít | thiểu số","small number | few | minority","1349070"),
    ("多数","たすう","n|adj-no","số đông | đa số | nhiều","large number (of) | many | majority","1407860"),
    ("複数","ふくすう","adj-no|n","số nhiều | nhiều | đa số","plural | multiple","1501400"),
    ("単数","たんすう","adj-no|n","số ít | đơn","single | singular (number)","1417670"),
    ("無数","むすう","adj-no|adj-na|n","vô số | vô vàn | không đếm xuể","innumerable | countless | numberless","1530280"),
    ("多量","たりょう","n|adj-na","lượng lớn | nhiều","large quantity | large amount","1408170"),
    ("適量","てきりょう","n","lượng vừa đủ | liều thích hợp","proper quantity | suitable amount | proper dose","1437530"),
    ("分量","ぶんりょう","n|vs|vt","phân lượng | định lượng | khối lượng","amount | quantity | measuring","1504430"),
    ("総量","そうりょう","n","tổng lượng | tổng khối lượng","aggregate amount","1401850"),
    ("最高","さいこう","adj-na|n","cao nhất | tối đa | tuyệt nhất","best | supreme | highest | maximum","1293850"),
    ("最低","さいてい","adj-na|n|adv","thấp nhất | tối thiểu | tệ nhất | ít nhất","least | lowest | minimum | worst | at the very least","1294220"),
    ("総計","そうけい","n|vs|vt","tổng cộng | tổng số","total | sum total | total amount","1401540"),
    ("累計","るいけい","n|vs|vt","lũy kế | tổng tích lũy","cumulative total | accumulated total","1555970"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
