# -*- coding: utf-8 -*-
"""Build N2 ready wave 058 — idioms, time words, critical-moment terms, expertise, performance."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-058.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("一部始終","いちぶしじゅう","n","đầu đuôi sự việc | toàn bộ chi tiết | từ đầu chí cuối","full particulars | the whole story","1166190"),
    ("自由奔放","じゆうほんぽう","n|adj-na","tự do phóng khoáng | tùy hứng không gò bó","free and uncontrolled | freewheeling","2031180"),
    ("我武者羅","がむしゃら","adj-na|n","liều lĩnh | bất chấp | hùng hục lao tới","reckless | daredevil | frantic","1196910"),
    ("順風満帆","じゅんぷうまんぱん","n","thuận buồm xuôi gió | mọi việc suôn sẻ","smooth sailing","1342400"),
    ("波乱万丈","はらんばんじょう","adj-no|adj-na|n","sóng gió ba đào | đầy thăng trầm gian truân","stormy and full of drama | with many vicissitudes","1471110"),
    ("古今東西","ここんとうざい","n","cổ kim đông tây | mọi thời mọi nơi","all times and places | all ages and countries","1265390"),
    ("森羅万象","しんらばんしょう","n","vạn vật trong trời đất | muôn vật vạn tượng","all things in nature | the whole creation","1362520"),
    ("有象無象","うぞうむぞう","n","đám đông ô hợp | bọn tầm thường | vạn vật","mob | the masses | riffraff","1745650"),
    ("玉石混交","ぎょくせきこんこう","n","vàng thau lẫn lộn | tốt xấu lẫn lộn","mixture of good and bad | jumble of wheat and chaff","1240630"),
    ("清濁併呑","せいだくへいどん","n","bao dung cả tốt lẫn xấu | rộng lượng dung nạp mọi hạng","being broad-minded enough to accept good and evil","2031550"),
    ("酒池肉林","しゅちにくりん","n","yến tiệc xa hoa | rượu chè trác táng | tửu trì nhục lâm","sumptuous feast | debauch","1329160"),
    ("質疑応答","しつぎおうとう","n","phần hỏi đáp | vấn đáp","question and answer session","1320690"),
    ("談論風発","だんろんふうはつ","n|vs|vi","tranh luận sôi nổi | bàn bạc rôm rả","spirited discussion","1838910"),
    ("喧々囂々","けんけんごうごう","n|adj-no|adj-t|adv-to","ồn ào náo loạn | nhao nhao bàn tán | huyên náo","wild uproar | clamor of voices | tumult","1257020"),
    ("唯々諾々","いいだくだく","adj-t|adv-to","ngoan ngoãn vâng dạ | răm rắp tuân theo | phục tùng","obedient | submissive | slavish","1587010"),
    ("異口同音","いくどうおん","n|adj-no","đồng thanh | nhất loạt cùng nói | một lời như nhau","(saying) with one voice | in unison | unanimously","1157650"),
    ("満場一致","まんじょういっち","n|adj-no","nhất trí toàn thể | cả hội trường đồng thuận","unanimity | unanimous consent","1526830"),
    ("全会一致","ぜんかいいっち","n|adj-no","toàn thể nhất trí | đồng thuận tuyệt đối","unanimous agreement | unanimity","1394910"),
    ("大同小異","だいどうしょうい","adj-na|adj-no|n","đại đồng tiểu dị | giống nhau về cơ bản, khác chút ít","essentially the same with minor differences","1414690"),
    ("同工異曲","どうこういきょく","n","bình mới rượu cũ | hình thức khác nội dung như nhau","equal workmanship but different style","1452310"),
    ("換骨奪胎","かんこつだったい","n|vs|vt","cải biên | thay cốt đổi lốt | viết lại theo ý mình","adaptation | recasting | rewriting","1747550"),
    ("温故知新","おんこちしん","n","ôn cố tri tân | học cái mới từ cái cũ","developing new ideas based on the past","1781130"),
    ("他山の石","たざんのいし","n","bài học từ sai lầm người khác | tấm gương để soi","lesson learned from someone else's mistake | object lesson","1407110"),
    ("反面教師","はんめんきょうし","n","tấm gương phản diện | bài học từ điều không nên làm","bad example from which one can learn","1481020"),
    ("枝葉末節","しようまっせつ","n","chi tiết vụn vặt | điều không quan trọng | tiểu tiết","unimportant details | inessentials","1310590"),
    ("本日","ほんじつ","n|adv","hôm nay | ngày hôm nay","today | this day","1523110"),
    ("後日","ごじつ","n|adv","sau này | hôm khác | về sau","in the future | another day | later","1269980"),
    ("先日","せんじつ","n|adv","hôm trước | mấy hôm trước | dạo nọ","the other day | a few days ago","1388300"),
    ("近日","きんじつ","n|adv","nay mai | trong vài ngày tới | sắp tới","soon | in a few days","1242490"),
    ("終日","しゅうじつ","n|adv","suốt cả ngày | cả ngày","all day | for a whole day","1332980"),
    ("半日","はんにち","n|adv","nửa ngày","half day","1583180"),
    ("丸一日","まるいちにち","n","trọn một ngày | cả ngày trời","the whole day | all the day","1922680"),
    ("一昼夜","いっちゅうや","n|adv","suốt một ngày đêm | 24 tiếng","whole day and night | 24 hours","1164770"),
    ("昼夜","ちゅうや","n|adv|adj-no","ngày đêm","day and night","1426430"),
    ("昼夜兼行","ちゅうやけんこう","n","làm việc suốt ngày đêm | bất kể ngày đêm","around-the-clock | (working) day and night","1426450"),
    ("不眠症","ふみんしょう","n","chứng mất ngủ","sleeplessness | insomnia","1495020"),
    ("時差ぼけ","じさぼけ","n","lệch múi giờ | mệt do chênh giờ bay","jet lag","1316250"),
    ("寝坊","ねぼう","n|vs|vi|adj-na|adj-no","ngủ nướng | dậy muộn | người hay ngủ quên","sleeping in late | oversleeping | late riser","1360320"),
    ("早起き","はやおき","n|vs|vi","dậy sớm | người dậy sớm","getting up early | early riser","1400200"),
    ("夜更かし","よふかし","n|vs|vi","thức khuya | ngủ muộn","staying up late | keeping late hours","1606000"),
    ("朝寝坊","あさねぼう","n|vs|vi","ngủ nướng buổi sáng | người dậy muộn","sleeping in | late riser","1428410"),
    ("朝飯前","あさめしまえ","adj-no|n","dễ như ăn kẹo | chuyện vặt | dễ ợt","very easy | piece of cake | child's play","1428510"),
    ("朝一","あさいち","n","ngay sáng sớm | việc đầu tiên trong buổi sáng","first thing in the morning","2140240"),
    ("夕暮れ時","ゆうぐれどき","n","lúc hoàng hôn | chập tối | chiều tà","time around sunset | early evening","2836369"),
    ("真っ只中","まっただなか","n","ngay giữa | giữa lúc | đang cao trào | đỉnh điểm","(right in the) middle | midst | heyday | height","1604090"),
    ("分かれ目","わかれめ","n","ngã rẽ | bước ngoặt | điểm phân định","fork | junction | parting of the ways | turning point","1502980"),
    ("正念場","しょうねんば","n","thời khắc quyết định | giây phút sống còn | thử thách then chốt","critical moment | do-or-die situation","1735290"),
    ("山場","やまば","n","cao trào | đỉnh điểm | thời khắc quan trọng | bước ngoặt","climax | peak | critical moment | turning point","1662100"),
    ("佳境","かきょう","n","cao trào (câu chuyện) | đoạn hấp dẫn | nơi cảnh đẹp","most interesting part | climax | scenic spot","1189700"),
    ("クライマックス","クライマックス","n","cao trào | đỉnh điểm","climax","1043930"),
    ("ぎりぎり","ぎりぎり","adv|adv-to","sát nút | tối đa | nghiến (răng) | siết chặt","(at) the very limit | grinding | tightly","2832861"),
    ("辛うじて","かろうじて","adv","vừa kịp | suýt soát | chật vật mới","barely | narrowly | only just","1365870"),
    ("危うく","あやうく","adv","suýt nữa | tí nữa thì | sém chút","barely | narrowly | almost | nearly","1218370"),
    ("危なく","あぶなく","adv","suýt | tí thì | gần như","nearly | almost | on the point of (doing)","2034940"),
    ("間一髪","かんいっぱつ","n","trong gang tấc | sợi tóc mong manh | suýt soát","hair's breadth","1215340"),
    ("紙一重","かみひとえ","adj-no|n","mong manh như tờ giấy | khác biệt mảy may | sít sao","paper-thin (difference) | very slight","1762920"),
    ("拮抗","きっこう","n|vs|vi","kèn cựa ngang sức | so kè | cân tài cân sức","rivalry (between equally strong sides) | being an equal match","1567370"),
    ("横並び","よこならび","n","ngang hàng | dàn hàng | rập khuôn theo nhau | đối xử đồng đều","positioning side-by-side | following the crowd","2140460"),
    ("横一線","よこいっせん","adj-no","ngang nhau | sít sao | bằng vai phải lứa","(running) abreast | neck and neck | (almost) equal","2853590"),
    ("首位","しゅい","n|adj-no","vị trí đầu | hạng nhất | dẫn đầu","first place | leading position","1594690"),
    ("最下位","さいかい","n|adj-no","hạng bét | vị trí cuối | thấp nhất","last place | lowest position","1721220"),
    ("独走","どくそう","n|vs|vi","bứt tốp chạy một mình | dẫn trước xa | tự tung tự tác","running solo | having a large lead | acting arbitrarily","1455980"),
    ("独壇場","どくだんじょう","n","sân khấu của riêng mình | lĩnh vực một mình tung hoành","field in which one acts unchallenged | one's monopoly","1691720"),
    ("独擅場","どくせんじょう","n","sân khấu của riêng mình | nơi một mình làm chủ","field in which one acts unchallenged | one's monopoly","1652920"),
    ("真骨頂","しんこっちょう","n","giá trị đích thực | bản lĩnh thật sự | thực lực thật","one's true worth | what one is really made of","1705090"),
    ("本領","ほんりょう","n","sở trường | bản lĩnh thật | thực tài | đất phong","one's real ability | one's specialty | fief","1523290"),
    ("持ち味","もちあじ","n","nét đặc trưng | hương vị riêng | bản sắc riêng","inherent flavor | distinctive characteristic","1658460"),
    ("お家芸","おいえげい","n","sở trường | ngón nghề riêng | tủ","one's specialty | one's forte","1694470"),
    ("十八番","おはこ","n","ngón tủ | sở trường | tiết mục tủ | bài tủ","one's specialty | one's forte | party trick","1579900"),
    ("得手","えて","adj-na|n","sở trường | điểm mạnh | ngón sở trường","forte | strong point","1454550"),
    ("不得手","ふえて","adj-na|n","điểm yếu | sở đoản | vụng về","weak point | unskillfulness","1494360"),
    ("玄人","くろうと","n","người chuyên nghiệp | dân nhà nghề | bậc thầy | sành sỏi","expert | professional | connoisseur","1263430"),
    ("素人","しろうと","n","tay mơ | nghiệp dư | người ngoài nghề | tân binh","amateur | layman | novice","1397270"),
    ("名人","めいじん","n","bậc thầy | danh thủ | cao thủ","master | expert","1531680"),
    ("熟達","じゅくたつ","n|vs|vi","thành thạo | điêu luyện | tinh thông","mastery","1337880"),
    ("円熟","えんじゅく","n|vs|vi","chín muồi | nhuần nhuyễn | lão luyện | điêu luyện","ripeness | mellowness | maturity","1175880"),
    ("老練","ろうれん","adj-na|adj-no|n","lão luyện | dày dạn | kỳ cựu | từng trải","experienced | veteran | skilled | expert","1616030"),
    ("腕利き","うできき","adj-no|adj-na|n","tay nghề cao | giỏi giang | cao tay | người tài giỏi","highly skilled | very capable | master-hand","1562920"),
    ("凄腕","すごうで","n|adj-no","tài năng xuất chúng | tay nghề siêu | cao thủ","remarkable ability | virtuoso | go-getter","1374610"),
    ("敏腕","びんわん","n|adj-na|adj-no","tài giỏi | lành nghề | có năng lực","ability | capability | competence","1491100"),
    ("辣腕","らつわん","n|adj-no|adj-na","sắc bén | lão luyện | tay nghề cứng | nhạy bén","shrewdness | sharpness | acumen","1573610"),
    ("手腕","しゅわん","n","tài năng | năng lực | kỹ năng | tay nghề","ability | capability | skill","1328450"),
    ("力作","りきさく","n|vs","tác phẩm dụng công | công trình tâm huyết | kiệt tác","painstaking piece of work | tour de force","1554980"),
    ("労作","ろうさく","n|vs","công trình lao tâm | tác phẩm nhọc công | việc vất vả","toil | painstaking piece of work","1560310"),
    ("大作","たいさく","n","tác phẩm đồ sộ | đại tác phẩm | kiệt tác lớn","large-scale work | monumental work | masterpiece","1413830"),
    ("力演","りきえん","n|vs|vt|vi","diễn nhiệt huyết | màn trình diễn dốc sức","enthusiastic performance","1796080"),
    ("熱演","ねつえん","n|vs|vt","diễn hết mình | trình diễn say sưa","enthusiastic performance","1832550"),
    ("熱弁","ねつべん","n","bài diễn thuyết hùng hồn | lời lẽ nhiệt thành","impassioned speech | fervent speech","1467980"),
    ("名演","めいえん","n","màn trình diễn xuất sắc | diễn xuất tuyệt vời","fine performance | excellent performance","2013320"),
    ("快演","かいえん","n|vs|vt","màn trình diễn ấn tượng | diễn hay","superb performance","2807150"),
    ("怪演","かいえん","n|vs|vt","diễn xuất quái dị mà cuốn hút | vai diễn dị biệt ấn tượng","eerie yet fascinating performance","2807130"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
