# -*- coding: utf-8 -*-
"""Build N1 ready wave 031 — 慣用句 idiomatic expressions (set 31)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-031.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("青菜に塩","あおなにしお","exp","ỉu xìu | rũ rượi | tiu nghỉu | héo hon (như rau gặp muối)","feeling downhearted | down in the dumps","2140980"),
    ("悪びれる","わるびれる","v1|vi","rụt rè | ngượng ngùng | tỏ vẻ bối rối | e dè ngại ngùng","to act timid | to appear embarrassed | to look ashamed","1151680"),
    ("足が棒になる","あしがぼうになる","exp|v5r","chân cứng đờ | mỏi rã chân | chân mỏi như khúc gỗ","to get stiff legs (from walking/standing long)","2404250"),
    ("足元にも及ばない","あしもとにもおよばない","exp|adj-i","không đáng xách dép | kém xa | không thể sánh bằng","to be no match for | to not hold a candle to","2191420"),
    ("頭ごなし","あたまごなし","adv|n","mắng té tát | không cho phân trần | quở trách phủ đầu","unsparingly | without giving a chance to explain","2034810"),
    ("後足で砂をかける","あとあしですなをかける","exp|v1","ăn cháo đá bát | phản bội lúc ra đi | gây hại khi rời đi","to do something spiteful as one leaves | a parting shot","2102040"),
    ("痘痕","あばた","n","mặt rỗ | sẹo đậu mùa | vết rỗ","pockmark","1649560"),
    ("案ずるより産むが易し","あんずるよりうむがやすし","exp","lo bò trắng răng | làm thì dễ lo thì khó | đừng lo quá","it is easier to do than to worry","2237250"),
    ("言い得て妙","いいえてみょう","exp","nói quá chuẩn | diễn đạt cực khéo | câu chữ đắt giá","a perfectly fitting phrase","2088760"),
    ("意気に感じる","いきにかんじる","exp|v1","cảm kích khí khái | nể chí khí | đáp lại tấm lòng nhiệt thành","to be moved by someone's strength of spirit","2119970"),
    ("息巻く","いきまく","v5k|vi","nổi đóa | hùng hổ | hăm dọa | nói hăng máu","to rage | to storm at | to speak with vigour","1850830"),
    ("痛くも痒くもない","いたくもかゆくもない","exp|adj-i","chẳng hề hấn gì | không nhằm nhò | mặc kệ | bất chấp","of no concern at all | couldn't care less","2110790"),
    ("一目置く","いちもくおく","exp|v5k","nể nang | thừa nhận hơn mình | kính nể một bậc","to acknowledge another's superiority","1627710"),
    ("一翼を担う","いちよくをになう","exp|v5u","gánh một phần | góp một tay | đảm nhận một vai trò","to play a part | to share the burden","2803970"),
    ("否が応でも","いやがおうでも","exp","dù muốn hay không | bất kể thế nào | ép buộc phải","whether one likes it or not | willy-nilly","2557610"),
    ("色を失う","いろをうしなう","exp|v5u","tái mặt | mất sắc | xanh mặt | thất sắc","to turn pale | to lose color","1859500"),
    ("有耶無耶","うやむや","adj-na|n","mập mờ | lấp lửng | nửa vời | chưa ngã ngũ | ậm ờ","vague | hazy | unsettled | left undecided","1612660"),
    ("裏をかく","うらをかく","exp|v5k","qua mặt | lừa được | cao tay hơn | đi trước một bước","to outwit | to outsmart","1860660"),
    ("うらぶれる","うらぶれる","v1|vi","tàn tạ | xuống dốc | sa sút | tiều tụy","to get shabby | to go to seed | to go downhill","2036240"),
    ("悦に浸る","えつにひたる","exp|v5r","đắm trong khoái cảm | tự mãn | hả hê | đắc ý","to be pleased | to glow with self-satisfaction","2832116"),
    ("得手勝手","えてかって","adj-na|n","ích kỷ | tùy tiện | chỉ biết mình | làm theo ý riêng","self-willed | doing things to suit oneself","1454560"),
    ("襟首","えりくび","n","gáy | cổ áo sau | sau gáy","nape of the neck","1242020"),
    ("大目に見る","おおめにみる","exp|v1","châm chước | bỏ qua | rộng lượng | du di | dung thứ","to overlook (a fault) | to be lenient","1415110"),
    ("おくびにも出さない","おくびにもださない","exp|adj-i","không hé răng | giấu kín | không lộ chút nào | tuyệt nhiên không nhắc","not giving the slightest indication | saying nothing","2138190"),
    ("お茶の子","おちゃのこ","n","chuyện vặt | dễ như trở bàn tay | dễ ợt | bữa ăn nhẹ","easy task | piece of cake | light snack","1694380"),
    ("鬼の首を取ったよう","おにのくびをとったよう","exp|adj-na","đắc thắng (chuyện cỏn con) | làm như lập đại công | huênh hoang","triumphant over a small achievement | boastful","2102560"),
    ("お払い箱","おはらいばこ","n","vứt bỏ | sa thải | loại bỏ | tống khứ","discarding | dismissal | getting rid of","1693950"),
    ("顔を立てる","かおをたてる","exp|v1","giữ thể diện | nể mặt | làm đẹp lòng | giữ sĩ diện cho","to save face | to show deference","1217790"),
    ("踵を返す","きびすをかえす","exp|v5s","quay gót | quay đầu trở lại | trở gót | quay lưng","to turn on one's heel | to turn back","2103110"),
    ("気が気でない","きがきでない","exp|adj-i","đứng ngồi không yên | lo nóng ruột | bồn chồn lo lắng","feeling uneasy | on tenterhooks | very anxious","2056670"),
    ("机上の空論","きじょうのくうろん","exp|n","lý thuyết suông | bàn giấy | kế hoạch viển vông | không khả thi","armchair theory | impracticable plan","1220230"),
    ("肝を冷やす","きもをひやす","exp|v5s","rởn tóc gáy | hú vía | hết hồn | lạnh sống lưng","to be terrified | to be scared to death","1869750"),
    ("急場をしのぐ","きゅうばをしのぐ","exp|v5g","chữa cháy tạm | vượt cơn nguy cấp | đối phó tình thế gấp","to tide over a crisis | to use a stopgap measure","2122670"),
    ("窮鼠猫を噛む","きゅうそねこをかむ","exp|v5m","chó cùng rứt giậu | chuột cùng cắn mèo | tức nước vỡ bờ","a cornered rat will bite a cat | desperation breeds courage","2103200"),
    ("口火を切る","くちびをきる","exp|v5r","mở màn | khơi mào | nổ phát súng đầu | châm ngòi","to get the ball rolling | to fire the first shot","1275870"),
    ("口を糊する","くちをのりする","exp|vs-i","kiếm ăn lần hồi | sống lay lắt | chật vật mưu sinh","to eke out a living | to barely get by","2563000"),
    ("軍門に下る","ぐんもんにくだる","exp|v5r","đầu hàng | quy hàng | chịu khuất phục | thần phục","to capitulate | to surrender | to submit","1873050"),
    ("犬馬の労","けんばのろう","n","sức khuyển mã | dốc chút sức mọn | hết lòng phục vụ","rendering what little service one can","1874110"),
    ("紅一点","こういってん","n","đóa hồng duy nhất | bóng hồng | người nữ duy nhất trong nhóm","the lone woman in a group","1836960"),
    ("業を煮やす","ごうをにやす","exp|v5s","sốt ruột phát cáu | mất kiên nhẫn | bực mình | nóng gáy","to lose patience | to get exasperated","1877800"),
    ("ご多分に漏れず","ごたぶんにもれず","exp","cũng như bao kẻ khác | không ngoại lệ | y như mọi người","like many others | being no exception","2125000"),
    ("小耳に挟む","こみみにはさむ","exp|v5m","tình cờ nghe được | nghe loáng thoáng | nghe lỏm","to happen to hear | to overhear","1348240"),
    ("鯱張る","しゃちほこばる","v5r|vi","căng cứng | trịnh trọng cứng nhắc | gồng mình | khép nép","to stand on ceremony | to stiffen up | to be tense","2218980"),
    ("四の五の言う","しのごのいう","exp|v5u","lằng nhằng | càu nhàu lý sự | kêu ca chuyện vặt | vòng vo","to grumble about something trivial","2073090"),
    ("舌を出す","したをだす","exp|v5s","lè lưỡi | thè lưỡi | cười nhạo sau lưng | chế giễu","to stick out one's tongue | to ridicule behind one's back","1880790"),
    ("私腹を肥やす","しふくをこやす","exp|v5s","vinh thân phì gia | lợi dụng chức vụ tư túi | bòn rút làm giàu","to line one's own pockets (abusing position)","1311370"),
    ("死活問題","しかつもんだい","n","vấn đề sống còn | chuyện sinh tử | việc hệ trọng","matter of life or death","1936500"),
    ("尻拭い","しりぬぐい","n","dọn hậu quả | gánh hậu quả cho người khác | chùi đít hộ","cleaning up someone else's mess","1647150"),
    ("雀百まで踊り忘れず","すずめひゃくまでおどりわすれず","exp","tật nào nết nấy | giang sơn dễ đổi bản tính khó dời | thói quen từ bé khó bỏ","what's learned in the cradle is carried to the tomb","2418480"),
    ("擦った揉んだ","すったもんだ","n|vs|vi","lùm xùm | giằng co cãi vã | rối ren | om sòm","quarreling | wrangling | fuss","1523950"),
    ("関の山","せきのやま","exp|n","tối đa là | hết mức cũng chỉ | cùng lắm là | quá lắm","the most one can do | the best one can expect","1811740"),
    ("背筋が寒くなる","せすじがさむくなる","exp|v5r","lạnh sống lưng | rùng mình | ớn lạnh xương sống | sởn gai ốc","to feel a chill run down one's spine","1636860"),
    ("高みの見物","たかみのけんぶつ","exp|n","khoanh tay đứng nhìn | bàng quan | xem từ xa | ngồi xem","looking on from afar | being a mere spectator","2759140"),
    ("血が騒ぐ","ちがさわぐ","exp|v5g","máu nóng sôi sục | rạo rực | nôn nao muốn làm | hứng khởi","to get excited | to be roused to action","2772330"),
    ("血眼","ちまなこ","n","mắt vằn tia máu | điên cuồng (làm gì) | dốc sức cuồng nhiệt","bloodshot eyes | (doing in a) frenzy","1255190"),
    ("茶飯事","さはんじ","n","chuyện cơm bữa | việc thường tình | chuyện thường ngày","commonplace event | matter of no importance","1422820"),
    ("血を分ける","ちをわける","exp|v1","cùng huyết thống | ruột thịt | có quan hệ máu mủ","to be related by blood","2832794"),
    ("鼻であしらう","はなであしらう","exp|v5u","khinh khỉnh | hắt hủi | xem thường | đối xử lạnh nhạt","to spurn | to snub | to treat with contempt","2272620"),
    ("角を矯めて牛を殺す","つのをためてうしをころす","exp|v5s","sửa sừng giết bò | vì tiểu tiết hỏng đại sự | lợi bất cập hại","straining at a gnat and swallowing a camel | ruining the whole for a trifle","2553380"),
    ("壺にはまる","つぼにはまる","exp|v5r","trúng phóc | đúng ý đồ | đúng tủ | gãi đúng chỗ ngứa","to hit the bull's-eye | to go as planned","2727860"),
    ("手ぐすね引く","てぐすねひく","exp|v5k","sẵn sàng chờ đợi | rình sẵn | thủ thế chờ thời | mai phục","to be ready and waiting | to be on the alert","2121110"),
    ("天秤にかける","てんびんにかける","exp|v1","cân nhắc lợi hại | đặt lên bàn cân | so đo | bắt cá hai tay","to weigh (one against another) | to play a double game","1440150"),
    ("取り越し苦労","とりこしぐろう","n|vs|vi","lo bò trắng răng | lo hão | lo xa vô ích | lo viển vông","overanxiety | needless worry","1707870"),
    ("泥縄","どろなわ","n","nước đến chân mới nhảy | nhổ rồi mới chạy | làm gấp lúc muộn","measure taken too late | acting in haste at last minute","1656370"),
    ("無いものねだり","ないものねだり","n","đòi hỏi điều không thể | mơ tưởng viển vông | đứng núi này trông núi nọ","asking for the moon | asking for the impossible","2009110"),
    ("無きにしもあらず","なきにしもあらず","exp","không phải là không có | ít nhiều cũng có | cũng có phần","not non-existent | there is some","2067550"),
    ("鳴かず飛ばず","なかずとばず","exp","im hơi lặng tiếng | mai danh ẩn tích | án binh bất động | chìm nghỉm","living in obscurity | lying low | remaining unnoticed","2275470"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
