# -*- coding: utf-8 -*-
"""Build N1 ready wave 038 — 慣用句 + 四字熟語 + nouns (set 38)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-038.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("物の数","もののかず","exp|n","đáng kể | đáng nói tới | có giá trị (物の数ではない: chẳng đáng gì)","something worth mentioning | something to count on","2729820"),
    ("門戸を開く","もんこをひらく","exp|v5k","mở cửa | mở rộng cửa (cho thế giới, phụ nữ...) | rộng mở","to open the door (to outsiders)","2402290"),
    ("焼け野原","やけのはら","n","bãi đất cháy | cánh đồng cháy trụi | vùng bị thiêu rụi","a burnt field | land devastated by fire","1742770"),
    ("柳眉","りゅうび","n","mày liễu | đôi mày đẹp | mày ngài (柳眉を逆立てる: giận dữ)","beautiful eyebrows","1538520"),
    ("病み上がり","やみあがり","n|adj-no","mới ốm dậy | đang dưỡng bệnh | mới khỏi bệnh | hồi sức","convalescence | recovering from an illness","1490170"),
    ("槍玉","やりだま","n","vật tế thần | nạn nhân bị nhắm | bị lôi ra chỉ trích (槍玉に挙げる)","scapegoat | someone singled out for criticism","1400510"),
    ("有終の美","ゆうしゅうのび","exp|n","kết thúc viên mãn | trọn vẹn đến cùng | về đích vẻ vang | thành công mỹ mãn","a perfect end | a triumphant finish","2675740"),
    ("油断大敵","ゆだんたいてき","exp","chớ chủ quan | lơ là là kẻ thù lớn | cẩn tắc vô áy náy | đừng mất cảnh giác","carelessness is the great enemy | don't let your guard down","1538700"),
    ("指折り","ゆびおり","adj-no|n","hàng đầu | xuất chúng | đếm trên đầu ngón tay | nổi bật","leading | prominent | foremost | counting on fingers","1759650"),
    ("夢枕","ゆめまくら","n","trong giấc mơ | bên gối mộng (夢枕に立つ: hiện về trong mơ)","at the bedside where one dreams","1773590"),
    ("余念がない","よねんがない","exp|adj-i","mải mê | chuyên tâm | dồn hết tâm trí | toàn tâm toàn ý","being concentrated on one thing | devoting oneself fully","2744920"),
    ("寄る年波","よるとしなみ","exp","tuổi cao sức yếu | tuổi tác chồng chất | tuổi già ập đến","one's advancing age | approaching old age","2863593"),
    ("弱り目","よわりめ","n","lúc suy yếu | khi sa cơ | lúc khốn khó (弱り目に祟り目)","a time of weakness","1324630"),
    ("来し方","きしかた","n","quá khứ | dĩ vãng | chặng đường đã qua | thuở trước","the past | bygone days","1585020"),
    ("埒もない","らちもない","exp|adj-i","vớ vẩn | vô nghĩa | nhảm nhí | tào lao | ngớ ngẩn","incoherent | silly | foolish","2533350"),
    ("李下","りか","n","dưới gốc mận (李下に冠を正さず: tránh hiềm nghi)","underneath a plum tree","2826232"),
    ("良知","りょうち","n","lương tri | trực giác đạo đức | bản năng phân biệt phải trái","intuition | innate moral sense","1775230"),
    ("臨機","りんき","adj-no","tùy cơ ứng biến | linh hoạt theo tình huống | thích ứng (臨機応変)","suited to the occasion | expedient","1815770"),
    ("類焼","るいしょう","n|vs|vi","cháy lan | lửa lan từ nhà bên | bị vạ lây hỏa hoạn","catching fire from next door | spreading fire","1618710"),
    ("冷汗三斗","れいかんさんと","n","toát mồ hôi lạnh | sợ toát mồ hôi | xấu hổ đến vã mồ hôi","breaking into a cold sweat (from fear or shame)","2033130"),
    ("轆轤","ろくろ","n","bàn xoay gốm | máy tiện | ròng rọc | trục quay","a potter's wheel | a lathe | a pulley","1573510"),
    ("六根清浄","ろっこんしょうじょう","n","lục căn thanh tịnh | gột rửa sáu giác quan | tịnh tâm","purification of the six roots of perception","1561350"),
    ("若気","わかげ","n","sự bồng bột tuổi trẻ | nhiệt huyết tuổi trẻ | tính nông nổi","youthful impetuosity | youthful vitality","1762480"),
    ("和洋","わよう","n","Nhật và Tây | phong cách Nhật-Âu | Á-Âu (和洋折衷)","Japan and the West | Japanese and Western style","1562280"),
    ("腕白","わんぱく","adj-na|n","nghịch ngợm | tinh nghịch | hiếu động | quậy phá","naughty | mischievous | unruly","1562910"),
    ("合縁奇縁","あいえんきえん","n","duyên kỳ ngộ | nhân duyên kỳ lạ | gặp gỡ do số phận | cơ duyên","an uncanny relationship formed by fate","1683820"),
    ("相棒","あいぼう","n","cộng sự | bạn nối khố | đồng bọn | bạn chí cốt","partner | pal | accomplice","1401350"),
    ("青二才","あおにさい","n","kẻ non choẹt | trẻ ranh | lính mới | còn non nớt","a green youth | a novice | a greenhorn","1381740"),
    ("赤の他人","あかのたにん","exp|n","người dưng | người xa lạ hoàn toàn | kẻ qua đường","a complete stranger","1828990"),
    ("灰汁","あく","n","nước tro | bọt váng | vị chát | cá tính gắt (灰汁が強い)","lye | scum (on broth) | harsh individuality","1201960"),
    ("朝駆け","あさがけ","n|vs|vi","tập kích sáng sớm | đột kích lúc bình minh | đánh úp ban mai","an early-morning attack","1696160"),
    ("足掻き","あがき","n","sự vùng vẫy | giãy giụa | cố vùng thoát | quẫy đạp","struggling | floundering","2015800"),
    ("徒疎か","あだおろそか","adj-na","coi nhẹ | xem thường | lơ là | sao nhãng","making light of | disregarding","2768050"),
    ("仇討ち","あだうち","n","báo thù | trả thù | rửa hận | phục thù","vengeance | revenge | retaliation","1227440"),
    ("当て字","あてじ","n","chữ mượn âm | kanji dùng theo âm | chữ ghép âm | ateji","kanji used phonetically | substitute character","1448890"),
    ("後釜","あとがま","n","người kế nhiệm | người thay thế | kế vị | vợ kế","successor | replacement | second wife","1269530"),
    ("雨模様","あまもよう","n","trời sắp mưa | dấu hiệu mưa | trời u ám chực mưa","signs of rain | threat of rain","1576450"),
    ("飴と鞭","アメとムチ","exp|n","cây gậy và củ cà rốt | vừa đấm vừa xoa | mềm nắn rắn buông","carrot and stick","1970680"),
    ("言いなり","いいなり","n","răm rắp nghe theo | bảo sao nghe vậy | ngoan ngoãn phục tùng | con rối","doing as one is told | a yes-man","1610590"),
    ("意気地なし","いくじなし","n|adj-na","kẻ hèn nhát | nhu nhược | không có khí phách | đồ bỏ đi","a coward | a weakling | spineless","1156490"),
    ("石橋","いしばし","n","cầu đá (石橋を叩いて渡る: thận trọng quá mức)","a stone bridge","1382580"),
    ("韋駄天","いだてん","n","thần chạy nhanh | người chạy như bay | thiện thần hộ pháp Vi Đà","a fleet-footed deity | a great runner","1858460"),
    ("一意専心","いちいせんしん","adv|n|adj-no","một lòng một dạ | chuyên tâm | toàn tâm toàn ý | dốc lòng","single-mindedly | wholeheartedly","1161050"),
    ("一望","いちぼう","n|vs|vt","tầm nhìn bao quát | nhìn toàn cảnh một lượt | thu vào tầm mắt","a sweeping view | an unbroken view","1587360"),
    ("一献","いっこん","n","một chén rượu | mời chén rượu | tiệc rượu nhỏ | nhâm nhi","one cup of sake | a drink","1162160"),
    ("一切合切","いっさいがっさい","n|adv","tất tần tật | toàn bộ | hết thảy | sạch sành sanh","any and every thing | lock, stock and barrel","1587460"),
    ("一矢","いっし","n","một mũi tên | lời đáp trả (一矢報いる: phản công)","one arrow | a retort","1167070"),
    ("一日の長","いちじつのちょう","exp|n","nhỉnh hơn một chút | có phần trội hơn | hơn một bậc (kinh nghiệm)","slight superiority (in experience, ability)","1165450"),
    ("一張羅","いっちょうら","n","bộ đồ tốt nhất | bộ cánh duy nhất | quần áo diện nhất","one's only good clothes | one's Sunday best","1587510"),
    ("一杯食わす","いっぱいくわす","exp|v5s","lừa một vố | chơi khăm | gạt | bịp","to play a trick on | to deceive | to dupe","1847110"),
    ("一服","いっぷく","n|vs|vt|vi","một hơi (thuốc) | nghỉ giải lao | một liều (thuốc) | tách trà","a puff | a short rest | one dose","1166260"),
    ("一辺","いっぺん","n","một cạnh (hình học) | một bên | một phía","a side (of a shape)","1627950"),
    ("田舎芝居","いなかしばい","n","kịch quê | đoàn hát rong | tuồng tỉnh lẻ | diễn xuất quê mùa","a provincial theatrical performance","1833260"),
    ("意表","いひょう","n|adj-na","bất ngờ | điều không lường trước | ngoài dự đoán (意表を突く)","surprise | something unexpected","1156790"),
    ("今際","いまわ","n","phút lâm chung | giờ hấp hối | giây phút cuối đời","one's dying hour | the hour of death","1681800"),
    ("否応","いやおう","n","đồng ý hay không | thuận hay nghịch | dù muốn hay không (否応なし)","yes or no | consent or refusal","1482960"),
    ("内兜","うちかぶと","n","bên trong mũ giáp | nội tình giấu kín | hoàn cảnh bí mật","inside of a helmet | hidden circumstances","1588180"),
    ("旨煮","うまに","n","món kho ngọt | cá thịt rau hầm nước tương ngọt | món om đậm đà","food stewed in a sweet soy sauce","1951990"),
    ("得手不得手","えてふえて","n","sở trường sở đoản | mặt mạnh mặt yếu | điểm giỏi điểm kém","strengths and weaknesses | likes and dislikes","2620900"),
    ("偉そう","えらそう","adj-na","ra vẻ ta đây | vênh váo | tỏ vẻ quan trọng | kiêu căng | làm bộ","self-important | pompous | conceited","2036550"),
    ("遠慮会釈","えんりょえしゃく","n","sự nể nang giữ ý | dè dặt và quan tâm (遠慮会釈もなく: chẳng nể nang gì)","reserve and consideration for others","1178480"),
    ("老い先","おいさき","n","quãng đời còn lại | những năm cuối đời | tuổi xế chiều","one's remaining years","1643540"),
    ("大威張り","おおいばり","n|adj-na","vênh vang | khoe khoang | ra oai | tự đắc","bragging | showing off | pride","1786230"),
    ("大盤","おおばん","n","bàn cờ minh họa (cờ vây, cờ tướng) | bàn cờ lớn trình diễn","a demonstration board (for Go, Shogi)","2040030"),
    ("お門違い","おかどちがい","n","nhầm đối tượng | trách nhầm người | gõ nhầm cửa | đổ oan","barking up the wrong tree | calling at the wrong house","1694335"),
    ("傍目","おかめ","n","con mắt người ngoài | cái nhìn của kẻ bàng quan | nhìn từ bên ngoài","looking on from the side | an outsider's view","1182490"),
    ("臆病風","おくびょうかぜ","n","cơn nhát gan | nỗi sợ chợt đến | mất nhuệ khí (臆病風に吹かれる)","a sudden loss of nerve | an attack of nerves","1760010"),
    ("押し出し","おしだし","n","sự đẩy ra | dáng vẻ bệ vệ | phong thái | đẩy đối thủ ra (sumo)","extrusion | presence | appearance","1589150"),
    ("お節介","おせっかい","adj-na|n","lo chuyện bao đồng | nhiều chuyện | xía vào | kẻ lắm chuyện","meddling | nosiness | a busybody","1270450"),
    ("お為ごかし","おためごかし","n|adj-no","tốt giả tạo | tử tế vì tư lợi | giả nhân giả nghĩa | lấy lòng có mục đích","a self-interested show of kindness","1694360"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
