# -*- coding: utf-8 -*-
"""Build N3 ready wave 062 — 79 freshly-curated N3 adverbs/conjunctions/〜的 adjectives + religion/ethics nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-062.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("反面","はんめん","conj|n","mặt khác | trái lại | đồng thời | mặt trái","while | on the other hand | reverse | other side","1481000"),
    ("他方","たほう","n|conj","phía bên kia | mặt khác | một bên","the other | one way | on the other hand","1407370"),
    ("逆に","ぎゃくに","adv","ngược lại | trái lại","conversely | on the contrary","1226980"),
    ("それにしても","それにしても","exp","dù vậy | dẫu sao | dù sao đi nữa","nevertheless | even so | be that as it may","2008730"),
    ("同じく","おなじく","adv|conj","tương tự | giống như | cũng vậy","in the same way | likewise | similarly","1451760"),
    ("且つ","かつ","conj|adv","và | hơn nữa | đồng thời | vừa...vừa","and | moreover | as well as | at the same time","1208840"),
    ("要は","ようは","adv","tóm lại | điều quan trọng là | nói gọn","in short | the point is | basically","1914670"),
    ("所詮","しょせん","adv","rốt cuộc | suy cho cùng | dù sao","after all | in the end | (not) at all","1343300"),
    ("畢竟","ひっきょう","adv|n","rốt cuộc | tóm lại | cuối cùng","after all | in the end | in short","1487760"),
    ("況して","まして","exp|adv","huống chi | nói gì đến | huống hồ","still more | to say nothing of | still less","1237470"),
    ("仮に","かりに","adv","giả sử | cho dù | tạm thời","supposing | even if | temporarily | provisionally","1187300"),
    ("万一","まんいち","n|adv","vạn nhất | lỡ may | trường hợp xấu nhất","(unlikely event of) emergency | by some chance | in the unlikely event","1525780"),
    ("仮にも","かりにも","adv","dù chỉ | dù thế nào | ít nhất là","(not even) for a moment | at any rate | at the very least","1187310"),
    ("言わば","いわば","adv","có thể nói là | nói cách khác","so to speak | as it were","1264380"),
    ("所謂","いわゆる","adj-pn","cái gọi là | được gọi là","what is called | so-called","1343150"),
    ("換言","かんげん","n|vs|vt|vi","nói cách khác | diễn đạt lại","saying in other words | putting another way","1747530"),
    ("逆説的","ぎゃくせつてき","adj-na","nghịch lý | mang tính nghịch lý","paradoxical","1693620"),
    ("比較的","ひかくてき","adv","tương đối | khá","comparatively | relatively","1483600"),
    ("根本的","こんぽんてき","adj-na","căn bản | cơ bản | tận gốc","fundamental | basic","1290290"),
    ("本質的","ほんしつてき","adj-na","mang tính bản chất | cốt lõi | thực chất","essential | substantial | intrinsic","1822900"),
    ("表面的","ひょうめんてき","adj-na","bề ngoài | hời hợt | hình thức","superficial | apparent | surface | cosmetic","1489920"),
    ("部分的","ぶぶんてき","adj-na","cục bộ | từng phần","partial","1499510"),
    ("全面的","ぜんめんてき","adj-na","toàn diện | toàn bộ | tổng lực","total | complete | all-out | full-scale","1396300"),
    ("全般的","ぜんぱんてき","adj-na","toàn thể | chung | bao quát","general | overall | across-the-board","1396080"),
    ("総合的","そうごうてき","adj-na","tổng hợp | toàn diện | tổng thể","comprehensive | all-round | overall | combined","1401570"),
    ("段階的","だんかいてき","adj-na","theo từng bước | dần dần | theo giai đoạn","incremental | step-by-step | gradual","2846385"),
    ("飛躍的","ひやくてき","adj-na","vượt bậc | nhanh chóng | đột phá","tremendous | rapid | dramatic","1485570"),
    ("画一的","かくいつてき","adj-na","đồng nhất | rập khuôn | tiêu chuẩn hóa","uniform | standard","1197100"),
    ("意図的","いとてき","adj-na","có chủ ý | cố ý | có chủ đích","intentional | on purpose","1156700"),
    ("作為的","さくいてき","adj-na","cố tình | dàn dựng | giả tạo","intentional | deliberate | contrived | artificial","1798340"),
    ("強制的","きょうせいてき","adj-na","mang tính cưỡng chế | bắt buộc","forced | compulsory","1236390"),
    ("自発的","じはつてき","adj-na","tự giác | tự nguyện","spontaneous | voluntary","1318560"),
    ("主観的","しゅかんてき","adj-na","chủ quan","subjective","1325210"),
    ("感情的","かんじょうてき","adj-na","cảm tính | đầy cảm xúc | dễ xúc động","emotional | sentimental","1614170"),
    ("理論的","りろんてき","adj-na","mang tính lý thuyết | lý luận","theoretical","1795880"),
    ("科学的","かがくてき","adj-na","mang tính khoa học | khoa học","scientific","1192760"),
    ("信仰","しんこう","n|vs|vt","tín ngưỡng | đức tin | niềm tin tôn giáo","(religious) faith | belief | creed","1359150"),
    ("信者","しんじゃ","n","tín đồ | người theo đạo | fan cuồng","believer | adherent | devotee | follower","1359340"),
    ("仏教","ぶっきょう","n","Phật giáo | đạo Phật","Buddhism","1501930"),
    ("祈り","いのり","n","lời cầu nguyện | sự nguyện cầu","prayer | supplication","1222760"),
    ("参拝","さんぱい","n|vs|vi","đi lễ (đền, chùa) | viếng (đền chùa)","worshipping (at a shrine or temple) | visit to worship","1302570"),
    ("供える","そなえる","v1|vt","dâng cúng | cúng | tiến dâng","to offer | to sacrifice | to dedicate","1233580"),
    ("葬儀","そうぎ","n","lễ tang | tang lễ","funeral | funeral service","1402140"),
    ("法事","ほうじ","n","lễ giỗ | lễ cầu siêu (Phật giáo)","Buddhist memorial service","1805140"),
    ("墓","はか","n","mộ | mồ mả | phần mộ","grave | gravesite | tomb","1514840"),
    ("供養","くよう","n|vs|vt","cúng lễ | lễ cầu siêu | tế lễ","memorial service for the dead | holding a service","1233910"),
    ("縁起","えんぎ","n","điềm | sự may rủi | duyên khởi | lai lịch","omen | sign of luck | origin | dependent arising","1177540"),
    ("占い","うらない","n","bói toán | sự bói | thầy bói","fortune-telling | divination | fortune-teller","1389410"),
    ("迷信","めいしん","n","mê tín | niềm tin mê tín","superstition | superstitious belief","1532760"),
    ("運勢","うんせい","n","vận | số mệnh | vận may","fortune | luck","1172790"),
    ("運命","うんめい","n|adj-no","vận mệnh | số phận | định mệnh","fate | destiny | lot","1173030"),
    ("天国","てんごく","n","thiên đường | thiên đàng","paradise | heaven","1439080"),
    ("地獄","じごく","n","địa ngục | cảnh khổ ải","hell | misery | inferno","1421090"),
    ("霊","れい","n","linh hồn | hồn | vong | ma","soul | spirit | departed soul | ghost","1557730"),
    ("幽霊","ゆうれい","n","ma | hồn ma | bóng ma","ghost | specter | apparition | phantom","1540590"),
    ("魂","たましい","n|suf","linh hồn | hồn | tinh thần | ý chí","soul | spirit | mind | willpower | vitality","1579170"),
    ("呪い","のろい","n","lời nguyền | sự nguyền rủa | bùa chú","curse | spell | malediction","1330100"),
    ("神話","しんわ","n","thần thoại","myth | mythology","1364940"),
    ("伝説","でんせつ","n|adj-no","truyền thuyết | giai thoại","legend | folklore | tradition","1442100"),
    ("神聖","しんせい","n|adj-na","thiêng liêng | thần thánh | tôn nghiêm","holiness | sacredness | sanctity","1364730"),
    ("神秘","しんぴ","n|adj-na","huyền bí | thần bí | bí ẩn","mystery | mysteriousness | secret","1364830"),
    ("崇拝","すうはい","n|vs|vt","sùng bái | tôn thờ | ngưỡng mộ","worship | adoration | admiration | cult","1372870"),
    ("教義","きょうぎ","n","giáo lý | giáo điều | tín điều","creed | doctrine | dogma","1237060"),
    ("布教","ふきょう","n|vs|vt","truyền giáo | truyền đạo","propagation (of a religion) | missionary work","1616790"),
    ("修行","しゅぎょう","n|vs|vt","tu hành | tu luyện | rèn luyện | khổ luyện","training | discipline | study | ascetic practices","2650010"),
    ("悟り","さとり","n","sự giác ngộ | sự thấu hiểu | đốn ngộ","comprehension | enlightenment | spiritual awakening","1270840"),
    ("解脱","げだつ","n|vs|vi","giải thoát | giác ngộ | siêu thoát","liberation from earthly desires | deliverance | moksha","1199140"),
    ("煩悩","ぼんのう","n","phiền não | dục vọng trần thế | tham sân si","worldly desires | evil passions | klesha","1481980"),
    ("慈悲","じひ","n|adj-no","từ bi | lòng thương | khoan dung","mercy | compassion | clemency | benevolence","1315440"),
    ("慈愛","じあい","n","lòng từ ái | tình thương (cha mẹ) | yêu thương","affection (esp. parental) | love | fondness","1315290"),
    ("博愛","はくあい","n|adj-no","bác ái | nhân ái | tình thương nhân loại","charity | benevolence | philanthropy | fraternity","1474530"),
    ("善良","ぜんりょう","adj-na|n","lương thiện | tốt bụng | hiền lành","good (person) | good-natured | virtuous | honest","1394560"),
    ("邪悪","じゃあく","adj-na|n","tà ác | gian ác | xấu xa","wicked | evil","1323430"),
    ("善悪","ぜんあく","n","thiện ác | tốt xấu | đúng sai","right and wrong | good and evil","1394300"),
    ("非常識","ひじょうしき","n|adj-na","thiếu hiểu biết | vô lý | bất thường","lack of common sense | senselessness | absurdity","1484990"),
    ("品格","ひんかく","n","phẩm cách | tư cách | sự cao quý","dignity | quality | grace | level","1490560"),
    ("威厳","いげん","n","uy nghiêm | sự uy nghi | trang nghiêm","dignity | majesty | solemnity | gravity","1156270"),
    ("尊厳","そんげん","adj-na|n","tôn nghiêm | phẩm giá | sự uy nghiêm","dignity | majesty | sanctity","1406420"),
    ("名声","めいせい","n","danh tiếng | tiếng tăm | thanh danh","fame | reputation | renown","1531690"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
