# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-033.csv -- 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-033.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("溢れる","あぶれる","N4","v1|vi",
        "thất bại (trong việc tìm việc làm) | bị loại ra | không được chọn | bị đẩy ra ngoài",
        "to fail (in getting a job) | to miss out (at fishing, hunting, etc.) | to be left out | to be crowded out",
        "1000460",
        "仙5事にあぶれないように努力する。","shigotoni aburenai youni nd suru.",
        "Tôi cố gắng không bị thất nghiệp.","I try not to lose my job."),
    row("米","メートル","N4","n",
        "mét (đơn vị đo chiều dài) | đồng hồ đo",
        "metre (unit of length) | meter | gauge",
        "1132570",
        "100米走ります。","100メートルはしります.",
        "Tôi chạy 100 mét.","I run 100 metres."),
    row("栄養士","えいようし","N4","n",
        "chuyên gia dinh dưỡng | cố vấn dinh dưỡng có chứng chỉ",
        "dietitian | (licensed) nutritionist",
        "1174020",
        "彼女は栄養士です。","かのじょはえいようしです.",
        "Cô ấy là chuyên gia dinh dưỡng.","She is a dietitian."),
    row("芽生える","めばえる","N4","v1|vi",
        "nảy mầm | nứt chồi | xuất hiện | bắt đầu phát triển",
        "to bud | to sprout | to arise | to begin to grow",
        "1197740",
        "春に芽生える。","はるにめばえる.",
        "Chồi xuất hiện vào mùa xuân.","Buds appear in spring."),
    row("滑り込む","すべりこむ","N4","v5m|vi",
        "trượt vào | lách vào | lọt vào",
        "to slide into | to slip into",
        "1208600",
        "塀に滑り込んだ。","するにすべりこんだ.",
        "Trượt vào đích.","I slid into base."),
    row("間食","かんしょく","N4","n|vs|vi",
        "ăn vặt | ăn giữa các bữa | ăn snack",
        "eating between meals | snacking",
        "1215500",
        "間食をやめました。","かんしょくをやめました.",
        "Tôi đã bỏ ăn vặt.","I quit snacking."),
    row("公倍数","こうばいすう","N4","n",
        "bội số chung",
        "common multiple",
        "1274490",
        "6は2と 3の公倍数だ。","6は2と3のこうばいすうだ.",
        "6 là bội số chung của 2 và 3.","6 is a common multiple of 2 and 3."),
    row("根深い","ねぶかい","N4","adj-i",
        "ăn sâu | bám rễ | cắm rễ | khó thay đổi",
        "deep-rooted | ingrained",
        "1290200",
        "偏見は根深い。","へんけんはねぶかい.",
        "Định kiến ăn sâu.","Prejudice is deep-rooted."),
    row("首筋","くびすじ","N4","n",
        "gáy | sau cổ | mặt sau cổ",
        "nape of the neck | back of the neck | scruff of the neck",
        "1329260",
        "首筋が痛い。","くびすじがいたい.",
        "Gáy tôi bị đau.","My neck is sore."),
    row("小雨","こさめ","N4","n",
        "mưa nhẹ | mưa phùn | mưa bụi",
        "light rain | drizzle",
        "1347810",
        "外は小雨です。","そとはこさめです.",
        "Ngoài trời đang mưa phùn.","It is drizzling outside."),
    row("消費税","しょうひぜい","N4","n",
        "thuế tiêu thụ | thuế VAT | thuế giá trị gia tăng",
        "consumption tax (incl. sales tax, VAT, excise duty, etc.)",
        "1350320",
        "消費税は10パーセントです。","しょうひぜいは10パーセントです.",
        "Thuế tiêu thụ là 10%.","The consumption tax is 10%."),
    row("新芽","しんめ","N4","n",
        "chồi non | mầm mới | búp mới",
        "sprout | bud | shoot",
        "1361540",
        "木に新芽が出た。","きにしんめがでた.",
        "Cây nảy chồi non.","Buds sprouted on the tree."),
    row("新雪","しんせつ","N4","n",
        "tuyết mới | tuyết tươi | tuyết vừa rơi",
        "fresh snow | new snow",
        "1362090",
        "新雪が穏もりました。","しんせつがつもりました.",
        "Tuyết mới đã rơi.","Fresh snow has piled up."),
    row("炒飯器","すいはんき","N4","n",
        "nồi cơm điện",
        "rice cooker",
        "1372360",
        "炒飯器でご飯を炒きます。","すいはんきでごはんをたきます.",
        "Tôi nấu cơm bằng nồi cơm điện.","I cook rice with the rice cooker."),
    row("生意気","なまいき","N4","adj-na|n",
        "ngạo mạn | láo xược | hỗn láo | kiêu ngạo | vô lễ",
        "impertinent | saucy | cheeky | impudent | audacious | cocky | pert | brash",
        "1378790",
        "生意気な夫度をやめなさい。","なまいきなたいどをやめなさい.",
        "Hãy bỏ cái thái độ láo xược đó.","Stop being so impudent."),
    row("税理士","ぜいりし","N4","n",
        "cố vấn thuế | kế toán thuế có chứng chỉ",
        "tax counsellor | tax counselor | licensed tax accountant",
        "1382200",
        "税理士に相談します。","ぜいりしにそうだんします.",
        "Tôi tư vấn với cố vấn thuế.","I consult with the tax accountant."),
    row("鮮明","せんめい","N4","adj-na|n",
        "sống động | rõ ràng | sắc nét",
        "vivid | clear | distinct",
        "1392540",
        "記憶が鮮明です。","きおくがせんめいです.",
        "Ký ức của tôi rất sống động.","My memory is vivid."),
    row("霜柱","しもばしら","N4","n",
        "cột băng giá | kim băng đá | trụ sương giá",
        "frost columns | ice needles",
        "1402980",
        "圖に霜柱ができた。","にわにしもばしらができた.",
        "Cột băng giá xuất hiện trên vườn.","Ice needles formed in the garden."),
    row("足首","あしくび","N4","n",
        "mắt cá chân",
        "ankle",
        "1404840",
        "足首を捧った。","あしくびをくじった.",
        "Tôi đã bị gãy mắt cá chân.","I sprained my ankle."),
    row("体","てい","N4","n",
        "vẻ bề ngoài | dáng vẻ | tình trạng | hình thức",
        "appearance | air | condition | state | form",
        "1409160",
        "体よく利用する。","ていよくりようする.",
        "Tôi sử dụng một cách khéo léo.","I use it skillfully."),
    row("討論","とうろん","N4","n|vs|vt",
        "tranh luận | thảo luận | phản biện",
        "debate | discussion",
        "1449980",
        "討論します。","とうろんします.",
        "Chúng tôi tranh luận.","We debate."),
    row("働き者","はたらきもの","N4","n",
        "người siêng năng | người chăm chỉ làm việc",
        "hard worker | hardworking person",
        "1451080",
        "彼は働き者です。","かれははたらきものです.",
        "Anh ấy là người chăm chỉ.","He is a hard worker."),
    row("同時","どうじ","N4","n|adj-f",
        "cùng lúc | đồng thời | đồng bộ",
        "same time | simultaneous | concurrent | synchronous",
        "1452500",
        "同時に始めます。","どうじにはじめます.",
        "Chúng tôi bắt đầu cùng lúc.","We start at the same time."),
    row("二桁","ふたけた","N4","n",
        "số hai chữ số | hàng chục | hai con số",
        "two-digit number | \"tens\" column | two digits | double figures",
        "1461540",
        "二桁の数字。","ふたけたのすうじ.",
        "Số hai chữ số.","A two-digit number."),
    row("眉毛","まゆげ","N4","n",
        "lông mày",
        "eyebrow",
        "1486330",
        "眉毛をしかめます。","まゆげをしかめます.",
        "Tôi nhăn mày.","I frown my eyebrows."),
    row("文化祭","ぶんかさい","N4","n",
        "lễ hội văn hóa trường | ngày hội mở cửa trường | hội diễn văn nghệ",
        "school festival | cultural festival | annual open day school event showcasing student talent",
        "1505140",
        "文化祭に参加します。","ぶんかさいにさんかします.",
        "Tôi tham dự lễ hội văn hóa trường.","I attend the school cultural festival."),
    row("頰骨","ほおぼの","N4","n",
        "xương gò má | xương gò má mặt",
        "cheekbone | zygomatic bone | malar bone",
        "1520650",
        "頰骨が高いです。","ほôぼのがたかいです.",
        "Gò má cô ấy cao.","She has high cheekbones."),
    row("霧雨","きりさめ","N4","n",
        "mưa phùn | mưa bụi | mưa lất phất",
        "drizzle | light rain",
        "1531120",
        "霧雨が降っている。","きりさめがふっている.",
        "Trời đang mưa phùn.","It is drizzling."),
    row("問い合わせる","といあわせる","N4","v1|vt",
        "hỏi thêm thông tin | liên hệ hỏi | thăm dò",
        "to enquire | to inquire | to seek information",
        "1535960",
        "店に問い合わせる。","みせにといあわせる.",
        "Tôi hỏi thêm thông tin với cửa hàng.","I inquire at the shop."),
    row("問い返す","といかえす","N4","v5s|vt",
        "hỏi lại | hỏi ngược lại | phản hỏi",
        "to ask again | to repeat one's question | to ask back | to ask in return | to counter",
        "1535990",
        "問い返すことは失礼です。","といかえすことはしつれいです.",
        "Hỏi lại là vô lễ.","Asking back is rude."),
    row("夕立","ゆうだち","N4","n",
        "mưa rào mùa hè (buổi chiều tối) | cơn mưa chiều hè",
        "(sudden, heavy) shower (on a summer afternoon or evening) | evening shower",
        "1542820",
        "夕立にふられました。","ゆうだちにふられました.",
        "Tôi đã bị dính mưa rào chiều hè.","I got caught in the evening shower."),
    row("洋食","ようしょく","N4","n",
        "món ăn phương Tây | ẩm thực châu Âu | kỹ ẩm phương Tây kiểu Nhật",
        "Western food | Western dish | Western cooking | Japanized Western cuisine",
        "1546000",
        "洋食が好きです。","ようしょくがすきです.",
        "Tôi thích món ăn phương Tây.","I like Western food."),
    row("露","あらわ","N4","adj-na",
        "trần trụi | phơi bày | công khai | để lộ ra",
        "exposed | scanty | bare | unconcealed | naked | public | open",
        "1560080",
        "本音が露になる。","ほんねがあらわになる.",
        "Ý định thật của tôi bị lộ ra.","My true intention is exposed."),
    row("和食","わしょく","N4","n",
        "món ăn Nhật | ẩm thực Nhật Bản",
        "Japanese food | Japanese dish | Japanese cuisine",
        "1562130",
        "和食が好きです。","わしょくがすきです.",
        "Tôi thích món ăn Nhật.","I like Japanese food."),
    row("耳たぶ","みみたぶ","N4","n",
        "dái tai | thùy tai",
        "earlobe",
        "1579600",
        "耳たぶにピアスをつける。","みみたぶにぴあすをつける.",
        "Tôi đeo khuyên tai vào dái tai.","I wear earrings on my earlobes."),
    row("春雨","はるさめ","N4","n",
        "mưa xuân | miến | miến đậu xanh | miến khoai tây",
        "gentle spring rain | glass noodles | cellophane noodles | thin noodles made from bean starch (or potato starch)",
        "1580180",
        "春雨が降ります。","はるさめがふります.",
        "Mưa xuân đang rơi.","Spring rain is falling."),
    row("落ち葉","おちば","N4","n|vs|vi|adj-no",
        "lá rụng | lá khô | rụng lá | lá xanh rụng xuống",
        "fallen leaves | leaf litter | falling leaves | leaf fall | dropping leaves | defoliation | deciduous",
        "1585070",
        "落ち葉を掃きます。","おちばをはきます.",
        "Tôi quét lá rụng.","I sweep fallen leaves."),
    row("打ち合わせる","うちあわせる","N4","v1|vt",
        "sắp xếp trước | thảo luận trước | phối hợp | gõ vào nhau",
        "to knock together | to strike against each other | to clash | to arrange (e.g. a meeting) | to discuss (in advance) | to coordinate | to prearrange",
        "1588150",
        "打ち合わせをします。","うちあわせをします.",
        "Chúng tôi thảo luận trước.","We prearrange a meeting."),
    row("交代","こうたい","N4","n|vs|vt|vi",
        "thay thế | luân phiên | xoay ca | đổi chỗ | thay ca",
        "change | alternation | rotation | replacement | substitution | shift | relief | taking turns",
        "1592990",
        "交代で弹きます。","こうたいでひきます.",
        "Chúng tôi luân phiên đán.","We take turns playing."),
    row("情け深い","なさけぶかい","N4","adj-i",
        "tốt bụng | giàu lòng trắc ẩn | nhân từ | hào hiệp",
        "tender-hearted | compassionate | charitable | good-hearted",
        "1599490",
        "情け深い人です。","なさけぶかいひとです.",
        "Anh ấy là người tốt bụng.","He is a tender-hearted person."),
    row("縫い目","ぬいめ","N4","n",
        "đường khâu | đường may | chỉ khâu",
        "seam | stitch | suture",
        "1599960",
        "縫い目が見えます。","ぬいめがみえます.",
        "Đường khâu được nhìn thấy.","The seam is visible."),
    row("履物","はきもの","N4","n",
        "giày dép | đồ đi chân",
        "footwear | footgear | shoes",
        "1600680",
        "履物を脱いでください。","はきものをぬいでください.",
        "Xin hãy bỏ giày dép ra.","Please remove your footwear."),
    row("形","なり","N4","n|adj-no",
        "hình dáng | vẻ ngoài | phong cách | trạng thái",
        "style | way | shape | form | appearance | state",
        "2138450",
        "形が変わった。","なりがかわった.",
        "Hình dáng đã thay đổi.","The appearance has changed."),
    row("首を振る","くびをふる","N4","exp|v5r",
        "lắc đầu",
        "to shake one's head",
        "2253980",
        "首を振って断る。","くびをふってことわる.",
        "Tôi lắc đầu từ chối.","I shake my head to refuse."),
    row("花弁","かべん","N4","n",
        "cánh hoa",
        "petal",
        "2862000",
        "花弁が散る。","かべんがちる.",
        "Các cánh hoa rơi.","Petals fall."),
    row("大人","たいじん","N4","n",
        "người có đức hạnh | bậc vĩ nhân | người bao dung",
        "person of virtue | great person | magnanimous person | giant | adult | exalted person",
        "1785170",
        "大人の行動だ。","たいじんのこうどうだ.",
        "Đó là hành động của bậc đại nhân.","That is the conduct of a great person."),
    row("大人","だいにん","N4","n",
        "người lớn | người trưởng thành",
        "adult",
        "2860067",
        "大人になりました。","だいにんになりました.",
        "Tôi đã trưởng thành.","I became an adult."),
    row("大人","うし","N4","n",
        "bậc tôn quý | lãnh chúa | quan lại | quý tộc",
        "exalted person | person of high education | feudal lord | nobleman",
        "2864579",
        "大人が居ていた。","うしがいた.",
        "Bậc tôn quý sống ở đó.","The nobleman lived there."),
    row("大人","おおびと","N4","n",
        "người khổng lồ | người to lớn",
        "giant",
        "2866562",
        "大人の傳説。","おおびとのでんせつ.",
        "Truyền thuyết về người khổng lồ.","The legend of the giant."),
    row("頭","とう","N4","ctr",
        "con (đếm gia súc lớn) | (bộ đếm côn trùng trong bộ sưu tập)",
        "counter for large animals (e.g. head of cattle) | counter for insects in a collection | counter for helmets, masks, etc.",
        "1450690",
        "牛10頭。","うしじゅっとう.",
        "10 con bò.","Ten head of cattle."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
