# -*- coding: utf-8 -*-
OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n3-vi-ready-004.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id):
    return ",".join([q(word), q(reading), q(""), q(lvl), q(pos), q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"), q(""), q(""), q(""), q(""), q("ai_draft"), q("jmdict_ai")])

ROWS = [
    row("賛否両論","さんぴりょうろん","N3","n",
        "tranh luận ủng hộ và phản đối | ủng hộ và phản đối | phản ứng trái chiều | đánh giá trái chiều",
        "arguments for and against | pros and cons | mixed reception | mixed reviews","1304230"),
    row("酸素","さんそ","N3","n",
        "oxy | khí oxy",
        "oxygen (O)","1304350"),
    row("暫定","ざんてい","N3","adj-no|n",
        "tạm thời | tạm | thử nghiệm | tạm quyền",
        "provisional | temporary | tentative | interim","1304450"),
    row("残念ながら","ざんねんながら","N3","exp",
        "đáng tiếc là | thật đáng tiếc",
        "unfortunately | regrettably","1304700"),
    row("使節","しせつ","N3","n",
        "đặc sứ | đại sứ | đại biểu | phái viên | phái đoàn",
        "envoy | ambassador | delegate | emissary | mission","1306030"),
    row("上半身","じょうはんしん","N3","n",
        "nửa trên cơ thể | phần thân trên",
        "upper half of the body | upper body","1354180"),
    row("上辺","うわべ","N3","n",
        "bề ngoài | bề mặt | vẻ bề ngoài | dáng vẻ | vẻ ngoài",
        "exterior | surface | outside | outward appearance | looks","1354340"),
    row("上辺","じょうへん","N3","n",
        "cạnh trên | phía trên (bàn cờ)",
        "upper side (of a go, chess or othello board)","1354350"),
    row("乗り越す","のりこす","N3","v5s|vt",
        "đi quá trạm | đi quá điểm đến | leo qua | vượt qua",
        "to ride past (one's stop) | to overshoot | to climb over | to get over","1354790"),
    row("上役","うわやく","N3","n",
        "cấp trên | sếp | người bề trên",
        "one's superior | higher-up | boss | senior","1354410"),
    row("上流","じょうりゅう","N3","n",
        "thượng nguồn | dòng trên | đầu nguồn | thượng lưu | tầng lớp thượng lưu",
        "upper stream | upper course | upper reaches | upstream | upper classes","1354510"),
    row("上等","じょうとう","N3","adj-na|n",
        "hạng nhất | cao cấp | xuất sắc | chất lượng cao | tốt thôi!",
        "superior | first-class | excellent | top quality | (that's) just fine!","1354030"),
    row("上陸","じょうりく","N3","n|vs|vi",
        "đổ bộ | lên bờ | xuống tàu | đổ bộ vào đất liền",
        "landing | going ashore | disembarkation | making landfall (of a typhoon)","1354480"),
    row("乗り出す","のりだす","N3","v5s",
        "khởi hành | ra khơi | bắt đầu (sự nghiệp mới) | vươn ra",
        "to set out | to set sail | to embark on (a new venture) | to lean out","1354940"),
    row("乗り気","のりき","N3","adj-na|n",
        "hứng thú | nhiệt tình | hăng hái",
        "interest | eagerness | enthusiasm","1354860"),
    row("乗り継ぐ","のりつぐ","N3","v5g|vi",
        "chuyển tiếp (chuyến bay) | kết nối tàu xe | đổi tuyến",
        "to connect (with a different flight, train, etc.) | to make a connection | to change (planes, trains)","1354870"),
    row("乗り込む","のりこむ","N3","v5m",
        "lên tàu | lên xe | leo vào (ô tô) | xông vào",
        "to board (a train, plane, etc.) | to get into (a car) | to get on (a bus) | to barge in","1354910"),
    row("仕入れ","しいれ","N3","n|vs|vt",
        "mua hàng | nhập hàng | thu mua vật liệu | dự trữ",
        "buying (of stock, materials, etc.) | purchasing | stocking | laying in","1305300"),
    row("仕返し","しかえし","N3","n|vs|vi",
        "trả thù | ăn miếng trả miếng | trả đũa | báo thù",
        "payback | tit for tat | retaliation | revenge","1305410"),
    row("使命","しめい","N3","n",
        "nhiệm vụ | sứ mệnh | công việc | nghĩa vụ",
        "mission | errand | task | duty | obligation","1306160"),
    row("斬新","ざんしん","N3","adj-na|adj-no",
        "mới mẻ | độc đáo | sáng tạo | đột phá",
        "novel | original | new | innovative","1304410"),
    row("残留","ざんりゅう","N3","n|vs|vi",
        "ở lại | còn lại | dư lại | tồn dư",
        "staying behind | remaining | residual","1304740"),
    row("残虐","ざんぎゃく","N3","adj-na|n",
        "tàn nhẫn | tàn bạo | hung tàn | man rợ",
        "cruel | brutal | savage | barbarous","1304540"),
    row("残酷","ざんこく","N3","adj-na|n",
        "tàn ác | tàn nhẫn | không khoan nhượng | vô nhân đạo | tàn bạo",
        "cruel | brutal | ruthless | merciless | inhuman","1304600"),
    row("残骸","ざんがい","N3","n",
        "tàn tích | đống đổ nát | xác tàu | tàn dư | mảnh vỡ",
        "ruins | wreckage | wreck | broken remains | debris","1304520"),
    row("賛美","さんび","N3","n|vs|vt",
        "ca ngợi | tán dương | tôn vinh",
        "praise | glorification | extolment","1304240"),
    row("酸性","さんせい","N3","n",
        "tính axit | có tính axit",
        "acidity | acidic","1304330"),
    row("酸性雨","さんせいう","N3","n",
        "mưa axit",
        "acid rain","1304340"),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
