# -*- coding: utf-8 -*-
"""Build N2 ready wave 027 — isms, rights, virtues, ambition, honor, judgement."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-027.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("主義","しゅぎ","n","chủ nghĩa | nguyên tắc | tôn chỉ","doctrine | principle | -ism","1325260"),
    ("資本主義","しほんしゅぎ","n|adj-no","chủ nghĩa tư bản","capitalism","1312800"),
    ("社会主義","しゃかいしゅぎ","n|adj-no","chủ nghĩa xã hội","socialism","1322740"),
    ("共産主義","きょうさんしゅぎ","n","chủ nghĩa cộng sản","communism","1234490"),
    ("民主主義","みんしゅしゅぎ","n|adj-no","chủ nghĩa dân chủ | nền dân chủ","democracy","1528840"),
    ("自由主義","じゆうしゅぎ","n","chủ nghĩa tự do","liberalism","1658640"),
    ("個人主義","こじんしゅぎ","n","chủ nghĩa cá nhân","individualism | egoism","1264850"),
    ("利己主義","りこしゅぎ","n","chủ nghĩa vị kỷ | sự ích kỷ","egoism | egotism | selfishness","1612240"),
    ("理想主義","りそうしゅぎ","n|adj-no","chủ nghĩa lý tưởng","idealism","1550030"),
    ("現実主義","げんじつしゅぎ","n|adj-no","chủ nghĩa hiện thực | chủ nghĩa thực tế","realism","1263720"),
    ("完璧主義","かんぺきしゅぎ","n","chủ nghĩa hoàn hảo | cầu toàn","perfectionism","2529790"),
    ("合理主義","ごうりしゅぎ","n","chủ nghĩa duy lý | chủ nghĩa hợp lý","rationalism","1285350"),
    ("人道主義","じんどうしゅぎ","n","chủ nghĩa nhân đạo | nhân văn","humanism | humanitarianism","1368920"),
    ("平和主義","へいわしゅぎ","n|adj-no","chủ nghĩa hòa bình","pacifism","1508190"),
    ("保護主義","ほごしゅぎ","n","chủ nghĩa bảo hộ","protectionism","2432410"),
    ("帝国主義","ていこくしゅぎ","n|adj-no","chủ nghĩa đế quốc","imperialism","1435930"),
    ("全体主義","ぜんたいしゅぎ","n|adj-no","chủ nghĩa toàn trị","totalitarianism","1395700"),
    ("主権","しゅけん","n","chủ quyền | quyền tối thượng","sovereignty | supremacy | dominion","1325360"),
    ("特権","とっけん","n|adj-no","đặc quyền | quyền đặc biệt","privilege | special right","1454870"),
    ("利権","りけん","n","quyền lợi | đặc quyền kinh tế | nhượng quyền","interest | rights | concession","1549520"),
    ("所有権","しょゆうけん","n","quyền sở hữu","ownership | property rights","1343400"),
    ("選挙権","せんきょけん","n","quyền bầu cử","suffrage | right to vote","1392200"),
    ("参政権","さんせいけん","n","quyền tham chính | quyền bầu cử ứng cử","suffrage | franchise","1302470"),
    ("拒否権","きょひけん","n","quyền phủ quyết","right of veto","1232420"),
    ("発言権","はつげんけん","n","quyền phát biểu | quyền lên tiếng","right to speak","1679330"),
    ("優先権","ゆうせんけん","n","quyền ưu tiên","priority | preferential right | right of way","1539430"),
    ("既得権","きとくけん","n","quyền đã có | quyền lợi đã giành được","vested rights","1220500"),
    ("版権","はんけん","n","bản quyền | quyền xuất bản","copyright | publishing rights","1481520"),
    ("覇権","はけん","n|adj-no","quyền bá chủ | bá quyền","hegemony","1470950"),
    ("実権","じっけん","n","thực quyền | quyền lực thật sự","real power","1634990"),
    ("公権力","こうけんりょく","n","công quyền | quyền lực nhà nước","public power | governmental authority","1951430"),
    ("信義","しんぎ","n","tín nghĩa | lòng trung thành | chữ tín","faith | fidelity | loyalty","1359120"),
    ("仁義","じんぎ","n","nhân nghĩa | đạo nghĩa | nghi thức chào (giang hồ)","humanity and justice | duty | moral code","1369670"),
    ("忠義","ちゅうぎ","adj-na|n","trung nghĩa | lòng trung thành | tận trung","loyalty | devotion","1426120"),
    ("節操","せっそう","n","khí tiết | tiết tháo | sự kiên định | trung trinh","integrity | fidelity | constancy | principle","1386290"),
    ("誠意","せいい","n","thành ý | lòng chân thành | thiện chí","sincerity | good faith","1381170"),
    ("善意","ぜんい","n","thiện ý | ý tốt | thiện chí | suy nghĩ tích cực","good intentions | good will | good faith","1394310"),
    ("悪意","あくい","n|adj-no","ác ý | ý xấu | ác tâm | dụng ý xấu","ill will | malice | bad faith","1151390"),
    ("敵意","てきい","n","địch ý | sự thù địch | ác cảm","hostility | animosity | enmity","1437110"),
    ("好意","こうい","n","thiện cảm | hảo ý | lòng tốt | sự mến mộ","kindness | goodwill | affection | liking","1277530"),
    ("厚意","こうい","n","hậu ý | lòng tốt | sự ưu ái","kindness | courtesy | good offices","1275370"),
    ("真心","まごころ","n|adj-no","chân tâm | lòng thành | sự tận tâm","sincerity | true heart | devotion","1363970"),
    ("信条","しんじょう","n","tín điều | niềm tin | phương châm sống","creed | belief | conviction","1359370"),
    ("志","こころざし","n","chí | hoài bão | ý chí | thiện ý | quà tạ lòng","will | ambition | aim | goodwill","1309050"),
    ("野心","やしん","n","tham vọng | dã tâm | mưu đồ","ambition | aspiration | sinister designs","1537430"),
    ("野望","やぼう","n","tham vọng | dã vọng | khát vọng lớn","ambition | aspiration","1537650"),
    ("大志","たいし","n","chí lớn | hoài bão lớn | đại chí","ambition | aspiration","1413920"),
    ("抱負","ほうふ","n","hoài bão | dự định | nguyện vọng | kế hoạch","aspiration | ambition | plan | hopes","1516420"),
    ("誠心","せいしん","n","lòng thành | thành tâm","sincerity","1764590"),
    ("犠牲","ぎせい","n","hy sinh | nạn nhân | sự tế thần","sacrifice | victim | casualty","1225450"),
    ("偉業","いぎょう","n","kỳ tích | sự nghiệp vĩ đại | công lao lớn","great achievement | great feat","1155840"),
    ("殊勲","しゅくん","n","công lao đặc biệt | chiến công | thành tích nổi bật","distinguished services | meritorious deeds","1328680"),
    ("栄誉","えいよ","n","vinh dự | danh dự | vẻ vang","honour | glory","1173970"),
    ("栄光","えいこう","n","vinh quang | hào quang","glory","1173920"),
    ("誉れ","ほまれ","n","niềm vinh dự | danh tiếng | vẻ vang","honour | glory | renown","1544900"),
    ("風格","ふうかく","n","phong thái | cốt cách | dáng vẻ","personality | style | appearance","1499790"),
    ("気品","きひん","n","sự thanh tao | khí chất | sự tao nhã | phẩm giá","elegance | refinement | grace | dignity","1222540"),
    ("貫禄","かんろく","n","khí phách | uy thế | sự bệ vệ | sự đường bệ","presence | dignity | corpulence","1215110"),
    ("威風","いふう","n","uy phong | uy nghi | sự oai vệ","majesty | dignity","1156350"),
    ("威容","いよう","n","dáng vẻ uy nghi | vẻ oai phong | dáng đường bệ","dignified appearance | imposing appearance","1587680"),
    ("気迫","きはく","n","khí phách | tinh thần | nghị lực | hồn","spirit | soul | drive | vigour","1222520"),
    ("気概","きがい","n","khí khái | dũng khí | tinh thần kiên cường","strong spirit | mettle | backbone | fighting spirit","1221990"),
    ("英断","えいだん","n","quyết định sáng suốt | quyết đoán đúng đắn","firm decision | excellent decision","1174610"),
    ("果断","かだん","adj-na|n","quyết đoán | dứt khoát | cương quyết","decisive | resolute | drastic","1193020"),
    ("独断","どくだん","n|vs|adj-no","độc đoán | tự quyết | chuyên quyền | giáo điều","one's own judgement | arbitrary decision | dogmatism","1455990"),
    ("専断","せんだん","n|vs|vt|adj-na|adj-no","chuyên quyền | tự ý quyết định | độc đoán","arbitrary decision | acting on one's own authority","1389830"),
    ("分別","ふんべつ","n|vs|vt","sự suy xét | sự khôn ngoan | óc phán đoán","discretion | prudence | good sense | judgement","1504190"),
    ("思慮","しりょ","n|vs|vt","sự cân nhắc | sự thận trọng | suy nghĩ chín chắn","prudence | discretion | consideration","1309610"),
    ("卓見","たっけん","n","kiến giải xuất sắc | nhãn quan sâu sắc | minh kiến","excellent idea | great insight | wisdom","1415620"),
    ("先見","せんけん","n|vs|vt","nhìn xa | tiên liệu | tầm nhìn xa","foresight | anticipation","1387510"),
    ("私見","しけん","n","ý kiến cá nhân | thiển ý","personal opinion","1311180"),
    ("所見","しょけん","n","quan điểm | nhận định | kết quả khám","view | opinion | finding","1343200"),
    ("異存","いぞん","n","ý kiến phản đối | sự bất đồng","objection","1157900"),
    ("暴論","ぼうろん","n","luận điệu phi lý | lý lẽ ngông cuồng","irrational argument","1797230"),
    ("極論","きょくろん","n|vs|vt","cực đoan hóa | lập luận thái quá | nói cực đoan","extreme logic | extreme argument","1240520"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
