# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-012.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-012.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("テープ","テープ","N4","n",
        "băng dán | băng | cuộn băng",
        "tape",
        "1078750",
        "テープを使います。","テープをつかいます。","Tôi dùng băng dán.","I use tape."),
    row("ひっくり返る","ひっくりかえる","N4","v5r|vi",
        "bị lật ngược | bị đảo ngược | lật qua | bị lật úp | ngã | lăn | nghiêng | nằm ngửa",
        "to be overturned | to be reversed | to turn over | to capsize | to fall down | to tumble down | to topple over | to lie on one's back",
        "1169320",
        "コップがひっくり返りました。","コップがひっくりかえりました。","Cái cốc bị lật úp.","The cup was overturned."),
    row("歌詞","かし","N4","n",
        "lời bài hát | lời ca | libretto",
        "song lyrics | words of a song | libretto",
        "1193280",
        "歌詞を覚えます。","かしをおぼえます。","Tôi học thuộc lời bài hát.","I memorize the lyrics."),
    row("確かに","たしかに","N4","adv",
        "chắc chắn | nhất định | quả thực",
        "surely | certainly",
        "1205770",
        "確かに正しいです。","たしかにただしいです。","Chắc chắn là đúng.","It is certainly correct."),
    row("骨","こつ","N4","n",
        "bí quyết | kỹ năng | mẹo vặt | bí mật | kinh nghiệm | xương | bộ xương | tro cốt (sau hỏa táng)",
        "knack | skill | trick | secret | know-how | the ropes | bone | skeleton | cremated remains | ashes",
        "1288540",
        "骨を身につけます。","こつをみにつけます。","Tôi học được bí quyết.","I acquire the knack."),
    row("消費","しょうひ","N4","n|vs|vt",
        "tiêu thụ | chi tiêu | tiêu dùng",
        "consumption | expenditure | spending",
        "1350290",
        "エネルギーを消費します。","エネルギーをしょうひします。","Tôi tiêu thụ năng lượng.","I consume energy."),
    row("展覧会","てんらんかい","N4","n",
        "triển lãm",
        "exhibition",
        "1440660",
        "展覧会に行きます。","てんらんかいにいきます。","Tôi đến triển lãm.","I go to the exhibition."),
    row("入学式","にゅうがくしき","N4","n",
        "lễ nhập học | lễ khai giảng",
        "school entrance ceremony",
        "1465910",
        "入学式に参加します。","にゅうがくしきにさんかします。","Tôi tham dự lễ khai giảng.","I attend the school entrance ceremony."),
    row("必ずしも","かならずしも","N4","adv",
        "không nhất thiết | không phải lúc nào cũng | không hẳn | không hoàn toàn",
        "(not) always | (not) necessarily | (not) entirely | (not) all",
        "1487410",
        "必ずしも正しいとは限りません。","かならずしもただしいとはかぎりません。","Không nhất thiết là đúng.","It is not necessarily correct."),
    row("片付く","かたづく","N4","v5k|vi",
        "được dọn dẹp gọn gàng | được sắp xếp | được giải quyết xong | được hoàn thành | được gả đi",
        "to be put in order | to be put to rights | to be disposed of | to be solved | to be finished | to be married (off)",
        "1511770",
        "部屋が片付きました。","へやがかたづきました。","Phòng đã được dọn dẹp.","The room is cleaned up."),
    row("香ばしい","こうばしい","N4","adj-i",
        "thơm ngát (đậu rang, trà rang) | thơm (ví dụ gỗ đốt) | có mùi thơm dễ chịu | thơm ngon (ví dụ thịt nướng) | ngon miệng",
        "aromatic (roasted beans, roasted tea, etc.) | fragrant (e.g. burning wood) | pleasant-smelling | savory-smelling (e.g. barbecued meat) | appetizing",
        "1578880",
        "香ばしい匂いです。","こうばしいにおいです。","Mùi thơm ngát.","It smells aromatic."),
    row("受付","うけつけ","N4","n|vs|vt|vi",
        "quầy lễ tân | bàn thông tin | lễ tân | nhân viên thông tin | biên nhận | chấp nhận",
        "reception (desk) | information desk | receptionist | information clerk | receipt | acceptance",
        "1588060",
        "受付で聞きます。","うけつけできます。","Tôi hỏi ở quầy lễ tân.","I ask at the reception desk."),
    row("思いつく","おもいつく","N4","v5k|vt|vi",
        "nghĩ ra | nảy ra ý nghĩ | nảy ra trong đầu | nảy ra một ý tưởng | nhớ lại | hồi tưởng",
        "to think of | to hit upon | to come into one's mind | to be struck with an idea | to remember | to recall",
        "1589330",
        "いい方法を思いつきました。","いいほうほうをおもいつきました。","Tôi nghĩ ra phương pháp tốt.","I came up with a good method."),
    row("傷つく","きずつく","N4","v5k|vi",
        "bị thương | bị tổn thương | cảm thấy đau lòng | bị hư hỏng | bị sứt mẻ | bị trầy xước",
        "to be wounded | to get injured | to get hurt feelings | to get damaged | to get chipped | to get scratched",
        "1591240",
        "心が傷つきました。","こころがきずつきました。","Tâm hồn tôi bị tổn thương.","My heart got hurt."),
    row("建つ","たつ","N4","v5t|vi",
        "được xây dựng | được dựng lên",
        "to be erected | to be built",
        "1597045",
        "新しい建物が建ちます。","あたらしいたてものがたちます。","Tòa nhà mới được xây dựng.","A new building is built."),
    row("広がる","ひろがる","N4","v5r|vi",
        "lan rộng | mở rộng | kéo dài | đến được | lan ra | đầy (ví dụ không gian)",
        "to spread (out) | to extend | to stretch | to reach to | to get around | to fill (e.g. a space)",
        "1602360",
        "ニュースが広がります。","ニュースがひろがります。","Tin tức lan rộng.","The news spreads."),
    row("火","か","N4","n",
        "thứ Ba | lửa (nguyên tố thứ hai trong ngũ hành)",
        "Tuesday | fire (second of the five elements)",
        "2248560",
        "火曜日は忙しいです。","かようびはいそがしいです。","Thứ Ba bận rộn.","Tuesday is busy."),
    row("エリア","エリア","N4","n",
        "khu vực | vùng",
        "area",
        "1030100",
        "このエリアは安全です。","このエリアはあんぜんです。","Khu vực này an toàn.","This area is safe."),
    row("カラー","カラー","N4","n|vs|vt",
        "màu sắc | màu | đặc điểm | đặc tính | không khí | nhuộm (tóc)",
        "color | colour | character | characteristics | atmosphere | coloring (one's hair) | dyeing",
        "1038500",
        "カラーを選びます。","カラーをえらびます。","Tôi chọn màu sắc.","I choose the color."),
    row("キャンペーン","キャンペーン","N4","n",
        "khuyến mại (bán hàng) | chiến dịch (bán hàng, quảng cáo) | chiến dịch (bầu cử, thay đổi xã hội) | phong trào | chiến dịch gây quỹ",
        "(sales) promotion | (sales, advertising) campaign | campaign (for an election, social change, etc.) | movement | drive (fund-raising, recruitment, etc.)",
        "1042250",
        "キャンペーンに参加します。","キャンペーンにさんかします。","Tôi tham gia chiến dịch.","I participate in the campaign."),
    row("スペース","スペース","N4","n",
        "không gian | phòng | khoảng cách (giữa các chữ cái, từ) | khoảng không vũ trụ",
        "space | room | space (between letters, words, etc.) | (outer) space",
        "1072810",
        "スペースが広いです。","スペースがひろいです。","Không gian rộng.","The space is large."),
    row("ペット","ペット","N4","n",
        "thú cưng | kèn trumpet",
        "pet | trumpet",
        "1120990",
        "ペットを飼います。","ペットをかいます。","Tôi nuôi thú cưng.","I keep a pet."),
    row("ホーム","ホーム","N4","n",
        "sân ga | bến",
        "platform",
        "1121740",
        "ホームで待ちます。","ホームでまちます。","Tôi chờ trên sân ga.","I wait on the platform."),
    row("ワクチン","ワクチン","N4","n",
        "vắc-xin | phần mềm diệt virus",
        "vaccine | antivirus software",
        "1148960",
        "ワクチンを打ちます。","ワクチンをうちます。","Tôi tiêm vắc-xin.","I get vaccinated."),
    row("改札","かいさつ","N4","n|vs|vi",
        "kiểm tra vé | cổng vé | rào chắn vé",
        "examination of tickets | ticket gate | ticket barrier",
        "1200840",
        "改札を通ります。","かいさつをとおります。","Tôi qua cổng vé.","I pass through the ticket gate."),
    row("環境","かんきょう","N4","n",
        "môi trường | xung quanh | hoàn cảnh",
        "environment | surroundings | circumstances",
        "1213280",
        "環境を守ります。","かんきょうをまもります。","Tôi bảo vệ môi trường.","I protect the environment."),
    row("肝臓","かんぞう","N4","n",
        "gan",
        "liver",
        "1214660",
        "肝臓が悪いです。","かんぞうがわるいです。","Gan tôi không tốt.","My liver is bad."),
    row("関節","かんせつ","N4","n",
        "khớp | khớp xương",
        "joint",
        "1215960",
        "関節が痛いです。","かんせつがいたいです。","Khớp tôi đau.","My joints hurt."),
    row("鏡","かがみ","N4","n",
        "gương | gương soi | nắp thùng | bánh mochi hình gương",
        "mirror | looking-glass | barrel head | mirror-shaped mochi",
        "1238550",
        "鏡を見ます。","かがみをみます。","Tôi nhìn vào gương.","I look in the mirror."),
    row("交渉","こうしょう","N4","n|vs|vt|vi",
        "đàm phán | thương lượng | thảo luận | cuộc thương thảo | mối liên hệ | quan hệ",
        "negotiations | bargaining | discussions | talks | connection | relationship | dealings",
        "1272110",
        "交渉が成功します。","こうしょうがせいこうします。","Cuộc đàm phán thành công.","The negotiations succeed."),
    row("公務員","こうむいん","N4","n",
        "nhân viên công vụ | nhân viên chính phủ | công chức | người phục vụ công",
        "public employee | government employee | public-sector worker | public servant | civil servant",
        "1274820",
        "公務員として働きます。","こうむいんとしてはたらきます。","Tôi làm việc với tư cách công chức.","I work as a civil servant."),
    row("荒い","あらい","N4","adj-i",
        "thô ráp | hoang dã | bạo lực | thô lỗ | thô | khắc nghiệt | dữ dội | nặng nề (ví dụ hơi thở) | liều lĩnh",
        "rough | wild | violent | rude | coarse | harsh | fierce | heavy (e.g. breathing) | reckless",
        "1281450",
        "荒い言葉を使います。","あらいことばをつかいます。","Tôi dùng ngôn ngữ thô lỗ.","I use rough language."),
    row("行動","こうどう","N4","n|vs|vi|adj-no",
        "hành động | hành vi | cử chỉ | ứng xử | huy động",
        "action | conduct | behaviour | behavior | mobilization | mobilisation",
        "1282100",
        "行動を起こします。","こうどうをおこします。","Tôi hành động.","I take action."),
    row("講義","こうぎ","N4","n|vs|vt",
        "bài giảng | buổi giảng | giảng dạy",
        "lecture",
        "1282260",
        "講義に出席します。","こうぎにしゅっせきします。","Tôi tham dự buổi giảng.","I attend the lecture."),
    row("講師","こうし","N4","n",
        "diễn giả | giảng viên | giảng viên (đại học, cao đẳng) | giáo viên bán thời gian | gia sư",
        "speaker | lecturer | lecturer (at a university or college) | instructor | part-time teacher | tutor (at a cram school)",
        "1282280",
        "講師が教えます。","こうしがおしえます。","Giảng viên giảng dạy.","The lecturer teaches."),
    row("合否","ごうひ","N4","n",
        "đậu hay rớt | kết quả",
        "success or failure | result",
        "1285200",
        "合否を確認します。","ごうひをかくにんします。","Tôi kiểm tra kết quả đậu rớt.","I confirm the pass/fail result."),
    row("在庫","ざいこ","N4","n|vs|vt|vi",
        "hàng tồn kho | tồn kho | có trong kho",
        "stock | inventory | having in stock | being in stock",
        "1296470",
        "在庫を確認します。","ざいこをかくにんします。","Tôi kiểm tra tồn kho.","I check the inventory."),
    row("市場","しじょう","N4","n",
        "thị trường (tài chính, chứng khoán, nội địa) | chợ | sàn giao dịch | chợ (đường phố)",
        "market (financial, stock, domestic, etc.) | marketplace | exchange | (street) market",
        "1308305",
        "市場が拡大します。","しじょうがかくだいします。","Thị trường mở rộng.","The market expands."),
    row("実験","じっけん","N4","n|vs|vt",
        "thí nghiệm | thực nghiệm",
        "experiment | experimentation",
        "1320970",
        "実験を行います。","じっけんをおこないます。","Tôi tiến hành thí nghiệm.","I conduct an experiment."),
    row("頼る","たよる","N4","v5r|vi|vt",
        "dựa vào | phụ thuộc vào | đặt niềm tin vào | nhờ đến (để giúp đỡ)",
        "to rely on | to depend on | to count on | to turn to (for help)",
        "1597200",
        "友人に頼ります。","ゆうじんにたよります。","Tôi dựa vào bạn bè.","I rely on my friend."),
    row("実際に","じっさいに","N4","adv",
        "thực tế | thực sự | thật sự | thật ra | trong thực tế | trên thực tế",
        "actually | really | truly | indeed | in practice | practically",
        "1321120",
        "実際に試してみます。","じっさいにためしてみます。","Tôi thực sự thử xem.","I actually try it."),
    row("書類","しょるい","N4","n",
        "tài liệu | giấy tờ | hồ sơ",
        "document | papers",
        "1344200",
        "書類を提出します。","しょるいをていしゅつします。","Tôi nộp tài liệu.","I submit the documents."),
    row("助かる","たすかる","N4","v5r|vi",
        "được cứu | được giải cứu | sống sót | thoát khỏi nguy hiểm | được giúp đỡ | được tránh phiền phức",
        "to be saved | to be rescued | to survive | to escape harm | to be helped | to be saved trouble",
        "1344380",
        "助かりました。","たすかりました。","Tôi được cứu.","I was saved."),
    row("商品","しょうひん","N4","n",
        "hàng hóa | sản phẩm thương mại | hàng | hàng tồn kho | hàng mua bán",
        "commodity | article of commerce | goods | stock | merchandise",
        "1347310",
        "商品を販売します。","しょうひんをはんばいします。","Tôi bán hàng hóa.","I sell merchandise."),
    row("常識","じょうしき","N4","n",
        "lẽ thường | phán đoán tốt | kiến thức chung | kiến thức tổng quát | thực hành phổ biến | nghi lễ xã hội",
        "common sense | good sense | common knowledge | general knowledge | common practice | social etiquette",
        "1356000",
        "常識があります。","じょうしきがあります。","Có lẽ thường.","There is common sense."),
    row("腎臓","じんぞう","N4","n",
        "thận",
        "kidney",
        "1370110",
        "腎臓が悪いです。","じんぞうがわるいです。","Thận tôi không tốt.","My kidney is bad."),
    row("性格","せいかく","N4","n",
        "tính cách (của người) | nhân cách | xu hướng tính cách | bản tính | đặc điểm",
        "character (of a person) | personality | disposition | nature | characteristics",
        "1375290",
        "明るい性格です。","あかるいせいかくです。","Là tính cách vui vẻ.","A cheerful personality."),
    row("生産","せいさん","N4","n|vs|vt",
        "sản xuất | chế tạo",
        "production | manufacture",
        "1378990",
        "生産量が増えます。","せいさんりょうがふえます。","Sản lượng tăng.","Production increases."),
    row("節約","せつやく","N4","n|vs|vt",
        "tiết kiệm | tiết kiệm tiền | chi tiêu tiết kiệm",
        "economising | saving",
        "1386350",
        "電気を節約します。","でんきをせつやくします。","Tôi tiết kiệm điện.","I save electricity."),
    row("定期券","ていきけん","N4","n",
        "vé tháng | thẻ đi lại định kỳ | vé theo mùa",
        "commuter pass | season ticket",
        "1435510",
        "定期券を使います。","ていきけんをつかいます。","Tôi dùng vé tháng.","I use the commuter pass."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
