# -*- coding: utf-8 -*-
"""Build N3 ready wave 048 — 69 freshly-curated N3 nature/science/politics/law nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-048.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("天候","てんこう","n","thời tiết","weather","1438970"),
    ("気圧","きあつ","n","khí áp | áp suất không khí","atmospheric pressure | air pressure","1221880"),
    ("海洋","かいよう","n","đại dương | biển khơi","ocean | sea","1201790"),
    ("平野","へいや","n","đồng bằng | cánh đồng","plain | open field","1508030"),
    ("火山","かざん","n","núi lửa","volcano","1193910"),
    ("噴火","ふんか","n|vs|vi","phun trào | núi lửa phun","eruption | volcanic eruption","1504560"),
    ("災害","さいがい","n","thiên tai | thảm họa | tai họa","calamity | disaster | misfortune","1295100"),
    ("被害","ひがい","n","thiệt hại | tổn hại | bị hại","(suffering) damage | injury | harm","1484350"),
    ("細胞","さいぼう","n","tế bào","cell (biology)","1295740"),
    ("遺伝","いでん","n|vs|vi","di truyền","heredity | (genetic) inheritance","1159460"),
    ("進化","しんか","n|vs|vi","tiến hóa | tiến bộ | phát triển","evolution | progress | advancement","1366000"),
    ("分布","ぶんぷ","n|vs|vi","phân bố | sự phân bố","distribution","1504160"),
    ("水素","すいそ","n","hydro (H)","hydrogen (H)","1371780"),
    ("炭素","たんそ","n","cacbon (C)","carbon (C)","1418570"),
    ("物質","ぶっしつ","n","vật chất | chất","material | substance | matter","1502560"),
    ("成分","せいぶん","n","thành phần | cấu thành","ingredient | component | composition","1375860"),
    ("液体","えきたい","n","chất lỏng","liquid","1175030"),
    ("気体","きたい","n","chất khí | thể khí","gas | vapour","1222460"),
    ("固体","こたい","n","chất rắn | thể rắn","solid (body) | solid matter","1266640"),
    ("内臓","ないぞう","n","nội tạng | phủ tạng","internal organs | viscera","1458740"),
    ("薬品","やくひん","n","dược phẩm | hóa chất | thuốc","medicine | drug | chemical","1538280"),
    ("予防","よぼう","n|vs|vt","phòng ngừa | phòng tránh | dự phòng","prevention | protection (against) | precaution","1543660"),
    ("感染","かんせん","n|vs|vi","lây nhiễm | nhiễm | bị ảnh hưởng","infection | contagion | being influenced (by)","1212470"),
    ("介護","かいご","n|vs|vt","chăm sóc | điều dưỡng (người bệnh, già)","nursing | care | caregiving","1198060"),
    ("看護","かんご","n|vs|vt","điều dưỡng | hộ lý | chăm sóc bệnh","nursing | (army) nurse","1213810"),
    ("福祉","ふくし","n","phúc lợi | an sinh | phúc lợi xã hội","welfare | well-being | social welfare","1501060"),
    ("衛生","えいせい","n","vệ sinh | sức khỏe | nhà vệ sinh","hygiene | sanitation | cleanliness","1174790"),
    ("政府","せいふ","n","chính phủ | nhà nước","government | administration","1376070"),
    ("候補","こうほ","n","ứng cử viên | ứng viên | dự bị","candidate | contender | prospect | nomination","1272730"),
    ("与党","よとう","n","đảng cầm quyền","ruling party | party in power","1544870"),
    ("野党","やとう","n","đảng đối lập | phe đối lập","opposition party | the opposition","1537580"),
    ("内閣","ないかく","n","nội các (chính phủ)","cabinet (of a government)","1457910"),
    ("官僚","かんりょう","n","quan chức | bộ máy quan liêu","bureaucrat | government official | bureaucracy","1211860"),
    ("行政","ぎょうせい","n","hành chính | quản lý nhà nước | nhà chức trách","executive | administration | governance | the authorities","1282010"),
    ("法案","ほうあん","n","dự luật | dự thảo luật","bill (law) | measure","1517160"),
    ("条例","じょうれい","n","điều lệ | quy định địa phương | pháp lệnh","regulations | (local) regulation | ordinance | bylaw","1356610"),
    ("法令","ほうれい","n","pháp lệnh | luật lệ | quy định","statute | law | act | ordinance","1517500"),
    ("判決","はんけつ","n|vs|vt","phán quyết | bản án | tuyên án","judicial decision | judgement | sentence","1478520"),
    ("訴訟","そしょう","n|vs|vi","kiện tụng | vụ kiện | tố tụng","lawsuit | (legal) action | litigation","1397740"),
    ("弁護","べんご","n|vs|vt","bào chữa | biện hộ | bênh vực","defense | pleading | advocacy","1512830"),
    ("検察","けんさつ","n|vs|vt","kiểm sát | điều tra truy tố","criminal investigation | prosecution","1257910"),
    ("容疑","ようぎ","n|n-suf","tình nghi | cáo buộc | nghi vấn","suspicion | charge","1545380"),
    ("捜査","そうさ","n|vs|vt","điều tra (hình sự) | truy tìm","search (criminal investigation) | investigation","1399660"),
    ("取り締まり","とりしまり","n","kiểm soát | giám sát | quản lý chặt","control | management | supervision","1599070"),
    ("罰金","ばっきん","n","tiền phạt | phạt tiền","fine | penalty","1478090"),
    ("処罰","しょばつ","n|vs|vt","xử phạt | trừng phạt","punishment | penalty","1342480"),
    ("刑罰","けいばつ","n","hình phạt | án phạt","(criminal) punishment | penalty | sentence","1249780"),
    ("被告","ひこく","n","bị cáo | bị đơn","defendant | the accused","1484410"),
    ("原告","げんこく","n","nguyên đơn | bên khởi kiện","plaintiff | accuser","1261400"),
    ("裁判官","さいばんかん","n","thẩm phán | quan tòa","judge","1296130"),
    ("検事","けんじ","n","công tố viên | kiểm sát viên","public prosecutor","1257930"),
    ("首脳","しゅのう","n","người đứng đầu | lãnh đạo | thượng đỉnh","head | leader | top","1329360"),
    ("会談","かいだん","n|vs|vi","hội đàm | cuộc gặp | đàm phán","talks (formal discussions) | conference | meeting","1198760"),
    ("戦争","せんそう","n|vs|vi","chiến tranh | giao tranh","war | fighting","1390360"),
    ("軍事","ぐんじ","n","quân sự","military affairs","1248080"),
    ("軍隊","ぐんたい","n","quân đội | binh lính","armed forces | military | troops","1248710"),
    ("兵士","へいし","n","binh lính | quân lính","soldier","1506420"),
    ("武器","ぶき","n","vũ khí | khí giới | lợi thế","weapon | arms | asset","1498460"),
    ("核兵器","かくへいき","n","vũ khí hạt nhân","nuclear weapon","1205700"),
    ("平等","びょうどう","n|adj-na","bình đẳng | công bằng","equality | impartiality","1507670"),
    ("民主","みんしゅ","n","dân chủ","democracy | popular sovereignty","1528790"),
    ("独立","どくりつ","n|vs|vi","độc lập | tự lập | tách riêng","independence | self-reliance | separation","1456040"),
    ("革命","かくめい","n","cách mạng","revolution","1206500"),
    ("抗議","こうぎ","n|vs|vt|vi","kháng nghị | phản đối | phản kháng","protest | objection","1278860"),
    ("世論","よろん","n","dư luận | công luận | dân ý","public opinion | public sentiment","1606150"),
    ("取材","しゅざい","n|vs|vt","thu thập tin | đưa tin | phỏng vấn (tin tức)","gathering material | covering (an event) | reporting","1327020"),
    ("公開","こうかい","n|vs|vt","công khai | công bố | ra mắt","opening to the public | release | disclosure","1273370"),
    ("公表","こうひょう","n|vs|vt","công bố chính thức | tuyên bố","official announcement | proclamation","1274550"),
    ("声明","せいめい","n|vs|vt|vi","tuyên bố | thanh minh | công bố","declaration | statement | proclamation","1380540"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
