# -*- coding: utf-8 -*-
"""Build N1 ready wave 085 — advanced katakana loanwords (set 85)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-085.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("アーギュメント","アーギュメント","n","luận điểm | sự tranh luận | đối số (hàm số) | lập luận","argument","1013440"),
    ("アサーション","アサーション","n","sự quả quyết | sự khẳng định | lời tuyên bố dứt khoát","assertion","2431690"),
    ("アジテーター","アジテーター","n","kẻ kích động | người xúi giục | tay mị dân","agitator","1015880"),
    ("アドボカシー","アドボカシー","n","sự vận động ủng hộ | hoạt động bênh vực | sự cổ vũ","advocacy","2816840"),
    ("アロケーション","アロケーション","n","sự phân bổ | sự cấp phát | phân chia nguồn lực","allocation","1019790"),
    ("アンサー","アンサー","n","câu trả lời | sự đáp lại | lời giải đáp","answer","2465340"),
    ("インシデント","インシデント","n","sự cố | sự việc bất thường | sự kiện xảy ra","incident","1022400"),
    ("インスペクション","インスペクション","n","sự kiểm tra | sự thanh tra | giám định","inspection","1022670"),
    ("ウェルビーイング","ウェルビーイング","n","sự an lạc | tình trạng khỏe mạnh hạnh phúc | hạnh phúc toàn diện","well-being","2863012"),
    ("エクイティ","エクイティ","n","vốn cổ phần | vốn chủ sở hữu | sự công bằng","equity","1980460"),
    ("エクスチェンジ","エクスチェンジ","n|vs|vt","sự trao đổi | giao dịch ngoại hối | quầy đổi tiền | tỷ giá","exchange","1027990"),
    ("エスタブリッシュメント","エスタブリッシュメント","n","giới quyền lực | tầng lớp thống trị | thể chế cầm quyền","the Establishment","1028680"),
    ("エポック","エポック","n","kỷ nguyên | thời đại | mốc thời đại | thời kỳ","epoch","1029830"),
    ("エンタープライズ","エンタープライズ","n","doanh nghiệp | xí nghiệp | sự nghiệp kinh doanh","enterprise","1031080"),
    ("オーバーチュア","オーバーチュア","n","khúc dạo đầu | màn mở màn | nhạc mở đầu","overture","1032520"),
    ("オブセッション","オブセッション","n","nỗi ám ảnh | sự ám ảnh dai dẳng | ý nghĩ cố hữu","obsession","2447450"),
    ("オペレーショナル","オペレーショナル","adj-na","thuộc vận hành | mang tính tác nghiệp | sẵn sàng hoạt động","operational","1035250"),
    ("カオティック","カオティック","adj-na","hỗn loạn | rối ren | hỗn độn | náo loạn","chaotic","2869888"),
    ("カバレッジ","カバレッジ","n","phạm vi bao phủ | độ phủ sóng | mức độ đưa tin","coverage","1038030"),
    ("クライシス","クライシス","n","khủng hoảng | cơn nguy biến | thời điểm nguy cấp","crisis","1043880"),
    ("クリアランス","クリアランス","n","sự thanh lý | khoảng trống | sự thông quan | giải phóng","clearance","1044640"),
    ("クレンジング","クレンジング","n|vs","sự làm sạch | tẩy trang | làm sạch da","cleansing","2182130"),
    ("グローバリズム","グローバリズム","n","chủ nghĩa toàn cầu | tư tưởng toàn cầu hóa","globalism","1047690"),
    ("コアバリュー","コアバリュー","n","giá trị cốt lõi | giá trị nền tảng (của tổ chức)","core values","2857177"),
    ("コーポレーション","コーポレーション","n","tập đoàn | công ty cổ phần | doanh nghiệp lớn","corporation","1049310"),
    ("コミットメント","コミットメント","n","sự cam kết | sự dấn thân | trách nhiệm cam kết","commitment","1986620"),
    ("コレスポンデンス","コレスポンデンス","n","sự tương ứng | thư từ qua lại | sự liên lạc","correspondence","1051620"),
    ("コンセッション","コンセッション","n|adj-f","sự nhượng bộ | quyền nhượng quyền | đặc nhượng","concession","2611520"),
    ("コンテンション","コンテンション","n","sự tranh chấp | sự xung đột (tài nguyên) | sự giành giật","contention","2297270"),
    ("コンビニエンス","コンビニエンス","n","sự tiện lợi | sự thuận tiện | tiện ích","convenience","1053290"),
    ("サーキュレーション","サーキュレーション","n","sự lưu thông | sự tuần hoàn | lượng phát hành","circulation","1054820"),
    ("サブシステム","サブシステム","n","hệ thống con | tiểu hệ thống | phân hệ","subsystem","1057260"),
    ("シミュレート","シミュレート","n|vs|vt","sự mô phỏng | giả lập | mô hình hóa","simulation","1061240"),
    ("シャドー","シャドー","n","bóng | bóng tối | bóng đổ | hình bóng","shadow","1061610"),
    ("ジャスティフィケーション","ジャスティフィケーション","n","sự biện minh | sự bào chữa | sự minh chứng tính chính đáng","justification","1065230"),
    ("ジャンクション","ジャンクション","n","nút giao | điểm giao cắt | nút giao thông liên tuyến","junction","1065760"),
    ("スーパーバイザー","スーパーバイザー","n","người giám sát | người quản lý | giám sát viên","supervisor","1066900"),
    ("スクリプト","スクリプト","n","kịch bản | tập lệnh (lập trình) | chữ viết tay (phông) | đoạn mã","script","1068630"),
    ("スタンディング","スタンディング","n|adj-f","đứng | vị trí | bảng xếp hạng | thường trực | đứng yên","standing | rankings","1923860"),
    ("ストレート","ストレート","adj-na|n","thẳng | thẳng thắn | bộc trực | nguyên chất | thắng liên tiếp | dị tính","straight | direct | blunt","1071450"),
    ("セパレーション","セパレーション","n","sự tách biệt | sự chia ly | sự phân tách","separation","2817500"),
    ("ソリダリティー","ソリダリティー","n","tình đoàn kết | sự gắn kết tập thể | tinh thần liên đới","solidarity","2496980"),
    ("ターゲティング","ターゲティング","n","việc xác định mục tiêu | nhắm đối tượng | định hướng mục tiêu","targeting","2808990"),
    ("ディシプリン","ディシプリン","n","kỷ luật | sự rèn luyện | ngành học | sự nghiêm khắc","discipline","2172010"),
    ("ディテクション","ディテクション","n","sự phát hiện | sự dò tìm | sự nhận biết","detection","2564880"),
    ("デプロイ","デプロイ","n|vs","sự triển khai | sự đưa vào vận hành | sự dàn quân","deployment","2792770"),
    ("デリバティブ","デリバティブ","n","công cụ phái sinh | sản phẩm tài chính phái sinh","derivative","1957920"),
    ("トランスフォーメーション","トランスフォーメーション","n","sự chuyển đổi | sự biến đổi | sự cải tổ toàn diện","transformation","1086290"),
    ("トランスペアレンシー","トランスペアレンシー","n","tính minh bạch | sự trong suốt | sự công khai","transparency","1086300"),
    ("ナレーション","ナレーション","n","lời thuyết minh | lời dẫn truyện | giọng tường thuật","narration","1090770"),
    ("ノミネーション","ノミネーション","n","sự đề cử | việc được đề cử | danh sách đề cử","nomination","1094090"),
    ("ハイテンション","ハイテンション","adj-na|n","phấn khích | hưng phấn cao độ | sôi nổi căng thẳng | cao áp","excited | enthusiastic | high-tension","2229390"),
    ("バウンス","バウンス","n","sự nảy lại | email bị trả về | sự dội lại","bounce","2318640"),
    ("バックボーン","バックボーン","n","xương sống tinh thần | nền tảng | chỗ dựa | đường trục (mạng)","backbone","1099030"),
    ("バリアント","バリアント","n","biến thể | dạng biến đổi | phiên bản khác","variant","1099740"),
    ("パンデミック","パンデミック","n","đại dịch | dịch bệnh toàn cầu","pandemic","2448140"),
    ("ピューリタン","ピューリタン","n","tín đồ Thanh giáo | người Thanh giáo | kẻ khắt khe đạo đức","Puritan","1106880"),
    ("ヒロイズム","ヒロイズム","n","chủ nghĩa anh hùng | tinh thần anh hùng | khí phách anh hùng","heroism","1104250"),
    ("フィナンシャル","フィナンシャル","adj-no|adj-na","thuộc tài chính | tài chính | tiền tệ","financial","2835102"),
    ("フェミニズム","フェミニズム","n","chủ nghĩa nữ quyền | phong trào bình đẳng giới | nữ quyền luận","feminism","1109920"),
    ("フォーミュラ","フォーミュラ","n","công thức | phương trình | quy tắc | đua công thức","formula","2468760"),
    ("フラクタル","フラクタル","n","hình fractal | cấu trúc tự đồng dạng | hình phân dạng","fractal","1111250"),
    ("フリーランス","フリーランス","n|adj-no","làm tự do | nghề tự do | người làm việc độc lập","freelance","1111920"),
    ("プレシジョン","プレシジョン","n","sự chính xác | độ chính xác | tính tỉ mỉ","precision","2830203"),
    ("プロミネンス","プロミネンス","n","sự nổi bật | tầm vóc nổi trội | tai lửa mặt trời","prominence","1117910"),
    ("ヘルスケア","ヘルスケア","n","chăm sóc sức khỏe | dịch vụ y tế | bảo vệ sức khỏe","health care","2185760"),
    ("ボーダー","ボーダー","n","đường biên | ranh giới | viền | họa tiết kẻ ngang","border | edge | stripes","1123410"),
    ("ホメオスタシス","ホメオスタシス","n","sự cân bằng nội môi | trạng thái tự cân bằng | hằng định nội môi","homeostasis","2237050"),
    ("マーケティング","マーケティング","n","tiếp thị | hoạt động marketing | nghiên cứu thị trường","marketing","1126280"),
    ("マニピュレーション","マニピュレーション","n","sự thao túng | sự điều khiển | sự lèo lái","manipulation","1128820"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
