# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-021.csv — 46 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-021.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("懐かしむ","なつかしむ","N4","v5m|vt",
        "nhớ nhung | cảm thấy hoài niệm | nhớ lại với cảm xúc | hoài niệm",
        "to yearn (for) | to miss | to feel nostalgic (for) | to recall fondly",
        "1200500",
        "故郷を懐かしみます。","こきょうをなつかしみます。","Tôi nhớ nhung quê hương.","I feel nostalgic for my hometown."),
    row("基本","きほん","N4","n|adj-no",
        "cơ bản | nền tảng | căn bản | cơ sở",
        "basics | fundamentals | basis | foundation",
        "1219190",
        "基本を学びます。","きほんをまなびます。","Tôi học những điều cơ bản.","I learn the basics."),
    row("技能","ぎのう","N4","n",
        "kỹ năng | khả năng kỹ thuật | năng lực",
        "technical skill | ability | capacity",
        "1225230",
        "技能を身につけます。","ぎのうをみにつけます。","Tôi học hỏi kỹ năng.","I acquire technical skills."),
    row("考察","こうさつ","N4","n|vs|vt",
        "xem xét | nghiên cứu | điều tra | khảo sát",
        "consideration | inquiry | enquiry | investigation | study",
        "1281150",
        "問題を考察します。","もんだいをこうさつします。","Tôi nghiên cứu vấn đề.","I investigate the problem."),
    row("効率","こうりつ","N4","n",
        "hiệu quả | hiệu suất",
        "efficiency",
        "1275210",
        "効率よく働きます。","こうりつよくはたらきます。","Tôi làm việc hiệu quả.","I work efficiently."),
    row("資格","しかく","N4","n",
        "trình độ | bằng cấp | điều kiện | tiêu chuẩn",
        "qualifications | requirements | capabilities",
        "1312690",
        "資格を取ります。","しかくをとります。","Tôi lấy bằng cấp.","I get a qualification."),
    row("植える","うえる","N4","v1|vt",
        "trồng cây | gieo trồng | cấy ghép | tiêm (vi khuẩn) | gieo vào (ý tưởng, giá trị) | khắc sâu",
        "to plant | to grow | to raise | to insert | to transplant | to implant | to set (type) | to inoculate (e.g. an infectious agent) | to instill (idea, value, etc.) | to inculcate",
        "1357250",
        "花を植えます。","はなをうえます。","Tôi trồng hoa.","I plant flowers."),
    row("制度","せいど","N4","n",
        "chế độ | thể chế | hệ thống | tổ chức",
        "system | institution | organization | organisation",
        "1374880",
        "制度を改革します。","せいどをかいかくします。","Tôi cải cách chế độ.","I reform the system."),
    row("方針","ほうしん","N4","n",
        "phương hướng | chính sách | nguyên tắc | kế hoạch hành động | kim la bàn",
        "policy | course | plan (of action) | principle | magnetic needle",
        "1517040",
        "方針を決めます。","ほうしんをきめます。","Tôi quyết định phương hướng.","I decide on a policy."),
    row("インフレ","インフレ","N4","n",
        "lạm phát",
        "inflation",
        "1024430",
        "インフレが進みます。","インフレがすすみます。","Lạm phát đang tăng.","Inflation is progressing."),
    row("傾ける","かたむける","N4","v1|vt",
        "nghiêng | làm nghiêng | dốc sức vào | tập trung vào | phá sản | uống cạn (rượu)",
        "to incline | to lean | to tip | to tilt | to slant | to bend | to list | to devote oneself to | to concentrate on | to pour one's energy into | to ruin | to squander | to empty | to drink (alcohol)",
        "1249420",
        "耳を傾けます。","みみをかたむけます。","Tôi lắng nghe.","I lend an ear."),
    row("刑事","けいじ","N4","n|adj-f",
        "thám tử | cảnh sát điều tra | hình sự",
        "(police) detective | criminal matter",
        "1249660",
        "刑事が捜査します。","けいじがそうさします。","Thám tử điều tra vụ án.","The detective investigates."),
    row("景気","けいき","N4","n",
        "tình hình kinh tế | điều kiện thị trường | hưng thịnh | sự sôi động | sức sống | tinh thần",
        "business conditions | the market | economic activity | economic climate | good (economic) times | prosperity | boom | liveliness | energy | vigour | vigor | spirit",
        "1250830",
        "景気が回復します。","けいきがかいふくします。","Kinh tế phục hồi.","The economy recovers."),
    row("警察官","けいさつかん","N4","n",
        "cảnh sát | nhân viên cảnh sát",
        "police officer | policeman | policewoman",
        "1252400",
        "警察官が来ます。","けいさつかんがきます。","Cảnh sát đến.","The police officer comes."),
    row("決算","けっさん","N4","n|adj-no|vs|vi",
        "quyết toán | đóng sổ sách | kết quả tài chính | báo cáo kế toán",
        "settlement of accounts | closing accounts | financial results | reporting (of accounts)",
        "1254290",
        "決算を報告します。","けっさんをほうこくします。","Tôi báo cáo kết quả tài chính.","I report the financial results."),
    row("結論","けつろん","N4","n|vs|vi",
        "kết luận",
        "conclusion (of an argument, discussion, study, etc.) | conclusion",
        "1255020",
        "結論を出します。","けつろんをだします。","Tôi đưa ra kết luận.","I draw a conclusion."),
    row("誇る","ほこる","N4","v5r|vt",
        "tự hào | kiêu hãnh | khoe khoang",
        "to boast of | to be proud of | to take pride in",
        "1267760",
        "成功を誇ります。","せいこうをほこります。","Tôi tự hào về thành công.","I take pride in my success."),
    row("裁判","さいばん","N4","n|vs|vt|adj-no",
        "xét xử | phán quyết | tòa án | phiên tòa",
        "trial | judgement | judgment",
        "1296120",
        "裁判が始まります。","さいばんがはじまります。","Phiên tòa bắt đầu.","The trial begins."),
    row("裁判所","さいばんしょ","N4","n",
        "tòa án | phòng xử án",
        "court | courthouse",
        "1296160",
        "裁判所に行きます。","さいばんしょにいきます。","Tôi đến tòa án.","I go to the courthouse."),
    row("震える","ふるえる","N4","v1|vi",
        "run rẩy | rùng mình | rung | run sợ",
        "to shiver | to shake | to quake | to tremble | to quaver | to quiver",
        "1366310",
        "寒くて震えます。","さむくてふるえます。","Tôi run rẩy vì lạnh.","I shiver from the cold."),
    row("犯罪","はんざい","N4","n",
        "tội phạm | tội ác | vi phạm pháp luật",
        "crime | offence | offense",
        "1481590",
        "犯罪を防ぎます。","はんざいをふせぎます。","Tôi ngăn chặn tội phạm.","I prevent crime."),
    row("被害者","ひがいしゃ","N4","n",
        "nạn nhân | người bị thiệt hại | người bị hại",
        "victim | injured party | sufferer",
        "1484370",
        "被害者を助けます。","ひがいしゃをたすけます。","Tôi giúp đỡ nạn nhân.","I help the victim."),
    row("弁護士","べんごし","N4","n",
        "luật sư",
        "lawyer | attorney",
        "1512850",
        "弁護士に相談します。","べんごしにそうだんします。","Tôi tham khảo ý kiến luật sư.","I consult with a lawyer."),
    row("抱える","かかえる","N4","v1|vt",
        "ôm trong vòng tay | kẹp dưới cánh tay | gánh chịu (vấn đề, nợ nần) | chịu trách nhiệm | nuôi (gia đình) | tuyển dụng",
        "to hold in one's arms | to carry in one's arms | to carry under one's arm | to hold (one's head) in one's hands | to have (problems, debts, etc.) | to take on (a responsibility) | to be burdened with (e.g. care of a family member) | to have (children, etc.) to provide for | to employ | to have (on one's staff) | to hire",
        "1516310",
        "問題を抱えます。","もんだいをかかえます。","Tôi gánh chịu vấn đề.","I have problems to deal with."),
    row("縫う","ぬう","N4","v5u|vt",
        "may vá | khâu | vượt qua (đám đông)",
        "to sew | to stitch | to weave one's way (e.g. through a crowd)",
        "1517700",
        "服を縫います。","ふくをぬいます。","Tôi may quần áo.","I sew clothes."),
    row("騙す","だます","N4","v5s|vt",
        "lừa gạt | gian lận | lừa đảo | dỗ dành | xoa dịu",
        "to trick | to cheat | to deceive | to swindle | to dupe | to coax | to wheedle | to soothe | to calm",
        "1574550",
        "人を騙します。","ひとをだまします。","Tôi lừa dối người khác.","I deceive someone."),
    row("抱く","いだく","N4","v5k|vt",
        "ôm ấp | ôm vào lòng | ấp ủ (tình cảm) | nuôi dưỡng (hoài bão) | mang trong lòng (nghi ngờ, hận thù)",
        "to hold in one's arms (e.g. a baby) | to embrace | to hug | to have (a thought or feeling) | to hold | to harbour (suspicion, doubt, etc.) | to harbor | to bear (a grudge, ill will, etc.) | to entertain (hope, illusions, etc.) | to cherish (e.g. an ambition)",
        "1584090",
        "夢を抱きます。","ゆめをいだきます。","Tôi ấp ủ ước mơ.","I cherish a dream."),
    row("干す","ほす","N4","v5s|vt",
        "phơi nắng | làm khô | làm cạn | uống cạn | tước bỏ vai trò",
        "to air | to dry | to desiccate | to drain (off) | to drink up | to deprive of a role, job, etc.",
        "1603510",
        "洗濯物を干します。","せんたくものをほします。","Tôi phơi quần áo.","I hang out the laundry."),
    row("メニュー","メニュー","N4","n",
        "thực đơn | danh sách | lịch trình | chương trình",
        "menu | schedule | program | programme | course | services | menu",
        "1133790",
        "メニューを見ます。","メニューをみます。","Tôi xem thực đơn.","I look at the menu."),
    row("稲妻","いなずま","N4","n",
        "tia sét | ánh chớp | sét đánh",
        "lightning | flash of lightning | lightning bolt",
        "1167860",
        "稲妻が光ります。","いなずまがひかります。","Tia sét lóe sáng.","Lightning flashes."),
    row("会計","かいけい","N4","n|adj-no|vs",
        "kế toán | tài chính | hoá đơn (nhà hàng) | thanh toán | thủ quỹ | tình trạng kinh tế",
        "accounting | finance | account | reckoning | bill (at a restaurant) | check | accountant | treasurer | paymaster | cashier | settlement (of a bill, fee, etc.), payment | economic condition",
        "1198430",
        "会計をお願いします。","かいけいをおねがいします。","Cho tôi tính tiền.","Please give me the bill."),
    row("解雇","かいこ","N4","n|vs|vt",
        "sa thải | cho thôi việc | đuổi việc | cắt giảm nhân sự",
        "dismissal (of an employee) | discharge | firing | layoff",
        "1198980",
        "社員を解雇します。","しゃいんをかいこします。","Công ty sa thải nhân viên.","The company fires an employee."),
    row("採用","さいよう","N4","n|vs|vt",
        "tuyển dụng | áp dụng | chấp nhận | bổ nhiệm",
        "use | adoption | acceptance | appointment | employment | engagement | recruitment",
        "1294890",
        "新入社員を採用します。","しんにゅうしゃいんをさいようします。","Chúng tôi tuyển dụng nhân viên mới.","We recruit new employees."),
    row("秋分","しゅうぶん","N4","n",
        "điểm phân thu | ngày thu phân",
        "autumnal equinox | autumn equinox | fall equinox",
        "1332730",
        "秋分の日です。","しゅうぶんのひです。","Hôm nay là ngày thu phân.","Today is the autumnal equinox."),
    row("食欲","しょくよく","N4","n",
        "cảm giác thèm ăn | khẩu vị | sự ngon miệng",
        "appetite (for food)",
        "1358660",
        "食欲がありません。","しょくよくがありません。","Tôi không có cảm giác thèm ăn.","I have no appetite."),
    row("寝かせる","ねかせる","N4","v1|vt",
        "cho ngủ | đặt nằm xuống | để tiền nhàn rỗi | để lên men | ủ (rượu vang)",
        "to put to bed | to let sleep | to lay (something) down | to put on its side | to let (money, goods, etc.) lie idle | to set aside unused | to let (stock) lie unsold | to (let) ferment | to (let) age | to let (dough) rise | to lay down (wine)",
        "1359970",
        "子供を寝かせます。","こどもをねかせます。","Tôi cho trẻ ngủ.","I put the child to bed."),
    row("霜","しも","N4","n",
        "sương giá | tóc bạc",
        "frost | white hair | grey hair | gray hair",
        "1402930",
        "霜が降ります。","しもがおります。","Sương giá rơi xuống.","Frost falls."),
    row("退職","たいしょく","N4","n|vs|vi",
        "về hưu | từ chức | nghỉ việc",
        "retirement | resignation",
        "1411420",
        "定年で退職します。","ていねんでたいしょくします。","Tôi về hưu theo tuổi quy định.","I retire at the mandatory age."),
    row("転職","てんしょく","N4","n|vs|vi",
        "chuyển việc | thay đổi nghề nghiệp | đổi nghề",
        "change of job | change of occupation | career change",
        "1441210",
        "転職を考えます。","てんしょくをかんがえます。","Tôi suy nghĩ về việc chuyển việc.","I think about changing jobs."),
    row("予習","よしゅう","N4","n|vs|vt",
        "chuẩn bị bài trước | học trước bài | ôn bài trước",
        "preparation for a lesson",
        "1543070",
        "授業の予習をします。","じゅぎょうのよしゅうをします。","Tôi chuẩn bị bài trước giờ học.","I prepare for the lesson in advance."),
    row("立てる","たてる","N4","v1|vt|suf",
        "dựng lên | đặt đứng | lập kế hoạch | tạo ra (tiếng động) | thành lập | đề cử | tôn trọng | mài (vật nhọn) | pha trà matcha | chia cho",
        "to stand up | to put up | to set up | to erect | to raise | to thrust into | to bury into | to dig into | to make (a noise) | to start (a rumour) | to raise (a cloud of dust, etc.) | to cause | to make | to establish | to set up | to develop | to formulate | to put up (a political candidate) | to make (one's leader) | to treat with respect | to give (someone) their due | to make (someone) look good | to avoid embarrassing (someone) | to sharpen | to make clear | to shut | to close | to make tea (matcha) | to perform the tea ceremony | to divide by | to do ... vigorously",
        "1551530",
        "計画を立てます。","けいかくをたてます。","Tôi lập kế hoạch.","I make a plan."),
    row("転ぶ","ころぶ","N4","v5b|vi",
        "ngã | vấp ngã | lăn | nhào lộn | từ bỏ đạo Thiên Chúa",
        "to fall down | to fall over | to turn out | to play out | to abandon Christianity (and convert to Buddhism) | to apostatize | to roll | to tumble | (for a geisha) to prostitute (herself) in secret",
        "1582130",
        "転んで怪我します。","ころんでけがします。","Tôi ngã và bị thương.","I fall and get injured."),
    row("割り勘","わりかん","N4","n",
        "chia đôi tiền | thanh toán mỗi người một phần | chia tiền thanh toán",
        "splitting the cost | splitting the bill | Dutch treat",
        "1606840",
        "割り勘にしましょう。","わりかんにしましょう。","Chúng ta hãy chia đôi tiền.","Let's split the bill."),
    row("場合","ばやい","N4","n",
        "trường hợp | dịp | tình huống | hoàn cảnh",
        "case | occasion | situation | circumstances",
        "2017460",
        "その場合はどうしますか。","そのばあいはどうしますか。","Trong trường hợp đó, bạn làm gì?","What do you do in that case?"),
    row("塗る","まぶる","N4","v5r|vt",
        "phủ lên | bôi lên | rắc lên",
        "to cover (with) | to smear | to sprinkle",
        "2862613",
        "粉を塗ります。","こなをまぶります。","Tôi rắc bột lên.","I sprinkle powder on it."),
    row("布","ふ","N4","n",
        "Hawaii (cách viết cũ bằng kanji)",
        "Hawaii",
        "2862651",
        "布は温かい。","ふはあたたかい。","Hawaii ấm áp.","Hawaii is warm."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
