# -*- coding: utf-8 -*-
"""Build N1 ready wave 018 — literary/formal Sino-Japanese nouns (set 18)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-018.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("遺志","いし","n","di nguyện | ý nguyện người đã khuất | tâm nguyện cuối","wishes of a deceased person | dying wish","1159290"),
    ("遺業","いぎょう","n","sự nghiệp dang dở (người đã mất) | di nghiệp | công trạng để lại","work left uncompleted at death | one's life work","1159100"),
    ("威光","いこう","n","uy quyền | quyền uy | thanh thế | uy lực","power | authority | influence","1156280"),
    ("委細","いさい","n|adv","chi tiết | cặn kẽ | tường tận | mọi việc","details | particulars | every last detail","1156140"),
    ("逸品","いっぴん","n","tuyệt phẩm | hàng hiếm | kiệt tác | của quý","excellent article | masterpiece | gem","1167760"),
    ("遺漏","いろう","n|vs","sơ sót | bỏ sót | thiếu sót","omission","1159670"),
    ("迂遠","うえん","adj-na","vòng vo | quanh co | không thực tế | viển vông","roundabout | circuitous | impractical","1171850"),
    ("有頂天","うちょうてん","n|adj-na","ngất ngây | sung sướng tột đỉnh | mừng như mở cờ","ecstasy | rapture | highest heaven","1541540"),
    ("会心","かいしん","n|vs|adj-no","hài lòng | mãn nguyện | đắc ý | toại nguyện","congeniality | satisfaction | gratification","1198680"),
    ("慨嘆","がいたん","n|vs|vt|vi","than thở | cảm thán | đau xót | thở dài tiếc nuối","deploring | lamentation | regret","1616860"),
    ("寡聞","かぶん","n","ít hiểu biết | kém thông tin | tài hèn sức mọn (khiêm)","having little knowledge | being ill-informed","1192640"),
    ("過分","かぶん","adj-na|adj-no|n","quá mức | quá phận | quá hậu (lời khen) | không xứng đáng","excessive | unmerited | generous","1196430"),
    ("過言","かごん","n","nói quá | cường điệu | lỡ lời | phóng đại","exaggeration | overstatement | saying too much","1196080"),
    ("寡作","かさく","adj-na|n","sáng tác ít | viết ít | (nghệ sĩ) ít tác phẩm","unprolific (writer, artist)","1192590"),
    ("我流","がりゅう","n|adj-no","tự học | theo cách riêng | lối riêng | tự mày mò","self-taught method | one's own way","1197010"),
    ("肝胆","かんたん","n","gan mật | tâm can | nội tâm | lòng dạ","the liver and gall bladder | one's inner being","1757560"),
    ("甘言","かんげん","n|adj-no","lời đường mật | lời ngọt ngào | dụ dỗ | nịnh hót","sweet words | smooth talk | flattery","1213490"),
    ("気宇","きう","n","khí độ | tấm lòng rộng lượng | độ lượng | khí phách","breadth of mind | generosity | magnanimity","1221910"),
    ("機微","きび","n|adj-na","sự tinh tế | điều vi tế | ẩn ý sâu xa | cái khó nắm bắt","subtleties | niceties | inner workings","1221160"),
    ("帰依","きえ","n|vs|vi","quy y | theo đạo | cải đạo | trở thành tín đồ thành tâm","becoming a devout believer | (religious) conversion","1221280"),
    ("詭計","きけい","n","mưu kế | quỷ kế | mánh khóe | thủ đoạn gian xảo","tricks | wiles","1572630"),
    ("窮状","きゅうじょう","n","cảnh khốn cùng | tình cảnh ngặt nghèo | hoàn cảnh bi đát","distress | wretched condition","1230090"),
    ("急逝","きゅうせい","n|vs|vi","đột tử | qua đời đột ngột | mất bất ngờ","sudden death | unexpected death","1228830"),
    ("驕慢","きょうまん","n|adj-na","kiêu căng | ngạo mạn | hợm hĩnh | tự cao tự đại","arrogance | haughtiness | pride","1808660"),
    ("均整","きんせい","n","cân đối | hài hòa | cân xứng | đều đặn","symmetry | balance | proportion","1241300"),
    ("苦境","くきょう","n","cảnh khó khăn | tình thế khốn đốn | nghịch cảnh | thế bí","difficult situation | predicament | distress","1244440"),
    ("功罪","こうざい","n","công và tội | mặt tốt mặt xấu | ưu khuyết điểm","merits and demerits | good and bad points","1275060"),
    ("高邁","こうまい","adj-na|n","cao thượng | cao quý | thanh cao | cao siêu","noble | lofty | high-minded","1809640"),
    ("傲岸","ごうがん","adj-na|n","ngạo mạn | kiêu căng | ngông nghênh | trịch thượng","haughty | arrogant | supercilious","1563930"),
    ("高遠","こうえん","adj-na|n","cao xa | cao thâm | cao vời | thâm sâu","noble | lofty","1809430"),
    ("巧拙","こうせつ","n","khéo vụng | hay dở | trình độ tay nghề | giỏi kém","skill | workmanship | quality","1278330"),
    ("碩学","せきがく","n","học giả uyên thâm | bậc đại trí | bậc thông thái","great scholar | profound scholar","1383720"),
    ("極致","きょくち","n","đỉnh cao | tột bậc | cảnh giới cao nhất | sự hoàn mỹ","culmination | acme | height | perfection","1240410"),
    ("故意","こい","n|adj-no","cố ý | chủ tâm | có dụng ý | ác ý","intent | intention | bad faith","1267140"),
    ("昏倒","こんとう","n|vs|vi","ngất xỉu | bất tỉnh | ngã quỵ | xỉu lăn ra","falling unconscious | fainting","1289970"),
    ("懇請","こんせい","n|vs|vt","khẩn cầu | tha thiết yêu cầu | nài nỉ | thỉnh cầu","appeal | entreaty | request","1289880"),
    ("懇願","こんがん","n|vs|vt","van xin | khẩn khoản | cầu khẩn | nài xin","pleading | entreaty | supplication","1289840"),
    ("懇望","こんもう","n|vs|vt","tha thiết mong mỏi | khẩn cầu | hết lòng thỉnh cầu","entreaty | solicitation | earnest request","1289930"),
    ("些事","さじ","n","việc nhỏ nhặt | chuyện vặt | điều cỏn con | tiểu tiết","something small | something petty | trifle","1593790"),
    ("作意","さくい","n","ý đồ | chủ ý | dụng ý | ý tưởng sáng tác","idea | design | motif | intention","1297490"),
    ("錯綜","さくそう","n|vs|vi","rắc rối | phức tạp | đan xen rối rắm | chằng chịt","becoming complicated | being intricate | entangled","1298440"),
    ("猜疑心","さいぎしん","n","lòng nghi kỵ | tâm lý ngờ vực | tính đa nghi | đố kỵ","suspicion (of others) | jealousy","1569300"),
    ("雑駁","ざっぱく","adj-na|n","lộn xộn | rời rạc | chắp vá | thiếu mạch lạc","confused | inconsistent | incoherent | patchy","1299500"),
    ("惨憺","さんたん","adj-t|adv-to","thảm hại | thê thảm | bi đát | dốc hết tâm sức","miserable | pitiful | wretched | painstaking","1303370"),
    ("私淑","ししゅく","n|vs|vi","tôn làm thầy (gián tiếp) | ngưỡng mộ học theo | sùng bái noi theo","looking up to someone as one's model | idolizing","1311220"),
    ("至言","しげん","n","lời chí lý | câu nói thấu đáo | lời vàng ngọc","apt remark | wise saying","1311930"),
    ("旨趣","ししゅ","n","tôn chỉ | mục đích | ý đồ | chủ ý","objective | purport | intent","2841923"),
    ("七難","しちなん","n","thất nạn | bảy tai ương | vô số khuyết điểm | trăm điều khổ","the Seven Misfortunes | great number of faults","1721440"),
    ("失意","しつい","n|adj-no","thất ý | chán nản | thất vọng | sa cơ thất thế","disappointment | despair | despondency | adversity","1319800"),
    ("昵懇","じっこん","n|adj-na","thân thiết | thân mật | gần gũi | thân tình","intimacy | familiarity | closeness","1567880"),
    ("失念","しつねん","n|vs|vt","quên mất | lỡ quên | đãng trí | nhất thời quên","forgetting | lapse of memory","1320130"),
    ("邪推","じゃすい","n|vs|vt","nghi oan | suy diễn xấu | ngờ vực bất công | nghĩ xấu","unjust suspicion | distrust","1323480"),
    ("従容","しょうよう","adj-t|adv-to","ung dung | thản nhiên | điềm tĩnh | bình thản","calm | composed | tranquil","1709410"),
    ("熟思","じゅくし","n|vs|vt","suy nghĩ kỹ | cân nhắc thấu đáo | ngẫm nghĩ chín chắn","deliberation | careful consideration","1717130"),
    ("殊勝","しゅしょう","adj-na|n","đáng khen | đáng quý | đáng nể | đáng trân trọng","admirable | laudable","1328700"),
    ("順逆","じゅんぎゃく","n","thuận nghịch | phải trái | trung và phản | tuân và chống","right and wrong | loyalty and treason","1635790"),
    ("慫慂","しょうよう","n|vs|vt","khuyên nhủ | thuyết phục | xúi giục | gợi ý","advice | recommendation | persuasion","2396380"),
    ("所存","しょぞん","n","ý kiến | suy nghĩ | dự định | ý định (khiêm nhường)","opinion | intention | thought","1648620"),
    ("真贋","しんがん","n","thật giả | tính chân thực | đồ thật và đồ giả","genuineness or spuriousness | authenticity","1363500"),
    ("深奥","しんおう","n|adj-na","thâm sâu | uyên áo | huyền bí | thâm thúy","depths | inner mysteries | profound | abstruse","1362700"),
    ("辛酸","しんさん","n","cay đắng | gian khổ | nếm trải đắng cay | khốn khó","hardships | privation","1365900"),
    ("心酔","しんすい","n|vs|vi","say mê | tôn sùng | ngưỡng mộ hết mực | mê đắm","adoration | admiration | devotion","1360760"),
    ("寸暇","すんか","n","chút thời gian rảnh | giây phút rảnh rỗi | thời gian ít ỏi","moment's leisure | free minute","1373700"),
    ("精彩","せいさい","n","sống động | rạng rỡ | sắc nét | sinh khí | rực rỡ","brilliance | vividness | life","1751280"),
    ("切歯","せっし","n|vs|vi","răng cửa | nghiến răng | nghiến răng (tức giận)","incisor | grinding one's teeth | gnashing of teeth","1385030"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
