# -*- coding: utf-8 -*-
"""Build N3 ready wave 057 — 90 freshly-curated N3 relationship/society + spatial/shape/place nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-057.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("交際","こうさい","n|vs|vi","giao thiệp | kết giao | hẹn hò","association | friendship | (romantic) involvement | dating","1271990"),
    ("仲","なか","n","mối quan hệ | quan hệ (giữa người)","relation | relationship","1425710"),
    ("縁","えん","n","duyên | nhân duyên | mối liên hệ","fate | destiny | relationship | bond | connection","1177490"),
    ("絆","きずな","n","sự gắn bó | mối ràng buộc tình cảm","bond (between people) | (emotional) ties | connection","1570420"),
    ("口論","こうろん","n|vs|vt|vi","cãi vã | tranh cãi | đấu khẩu","quarrel | argument | (verbal) dispute","1277000"),
    ("団結","だんけつ","n|vs|vi","đoàn kết | đồng lòng | hợp sức","unity | solidarity | banding together","1419230"),
    ("一致","いっち","n|vs|vi","nhất trí | trùng khớp | đồng nhất","agreement | correspondence | match | unity","1164740"),
    ("分裂","ぶんれつ","n|vs|vi","chia rẽ | phân liệt | tan rã","split | division | break up","1504510"),
    ("孤立","こりつ","n|vs|vi","cô lập | đơn độc | bị cô lập","isolation | being alone | being friendless","1266860"),
    ("排除","はいじょ","n|vs|vt","loại trừ | loại bỏ | dẹp bỏ","exclusion | removal | elimination | getting rid of","1472370"),
    ("身分","みぶん","n","thân phận | địa vị | xuất thân | hoàn cảnh","(social) standing | status | rank | identity","1365810"),
    ("義理","ぎり","n","nghĩa lý | bổn phận | ơn nghĩa | quan hệ thông gia","duty | sense of duty | debt of gratitude | in-law","1225920"),
    ("人情","にんじょう","n","tình người | nhân tình | lòng nhân ái","humanity | empathy | kindness | human nature","1368180"),
    ("恩","おん","n","ân | ơn | ân huệ | ơn nghĩa","favour | obligation | debt of gratitude | kindness","1183090"),
    ("恩返し","おんがえし","n|vs|vi","báo đáp | trả ơn | đền ơn","paying back a favour | repayment (of kindness)","1183280"),
    ("恩恵","おんけい","n","ân huệ | lợi ích | phúc lành","grace | favor | blessing | benefit","1183140"),
    ("方角","ほうがく","n","phương hướng | hướng | la bàn","direction | point of the compass | bearing","1516950"),
    ("方位","ほうい","n","phương vị | hướng | tọa độ la bàn","bearing | heading | point of the compass","1516940"),
    ("向き","むき","n|n-suf","hướng | chiều | phù hợp với | khuynh hướng","direction | orientation | suited to | tendency","1277040"),
    ("正面","しょうめん","n|adj-no","mặt trước | chính diện | trực diện","front | frontage | facade | main","1378030"),
    ("背後","はいご","n|adj-no","phía sau | đằng sau | hậu trường","back | rear | background | behind the scenes","1472730"),
    ("周囲","しゅうい","n","xung quanh | chu vi | môi trường quanh","surroundings | environs | circumference","1331030"),
    ("周辺","しゅうへん","n|n-suf","vùng phụ cận | ngoại vi | lân cận | ngoại biên","outskirts | environs | vicinity | (computer) peripheral","1331300"),
    ("付近","ふきん","n|n-suf","khu vực gần | lân cận | phụ cận","neighborhood | vicinity | surrounding area","1496240"),
    ("近辺","きんぺん","n","vùng lân cận | gần đây | xung quanh","neighbourhood | vicinity","1242530"),
    ("周り","まわり","n","xung quanh | chu vi | người xung quanh","circumference | surroundings | vicinity | people around","1604290"),
    ("端","はし","n","đầu | mép | rìa | đầu mối | mẩu","end | tip | edge | beginning | scrap","1581610"),
    ("隅","すみ","n|n-suf","góc | xó | ngóc ngách","corner | nook | recess","1246440"),
    ("縁","ふち","n","mép | viền | rìa | bờ","rim | brim | edge | brink","1177500"),
    ("中央","ちゅうおう","n|adj-no","trung tâm | giữa | trung ương","centre | middle | capital | seat of government","1423430"),
    ("内部","ないぶ","n|adj-no","nội bộ | bên trong | phần trong","interior | inside | internal","1459030"),
    ("外部","がいぶ","n|adj-no","bên ngoài | phần ngoài | bên ngoài (tổ chức)","outside | exterior | outside world","1204070"),
    ("表面","ひょうめん","n|adj-no","bề mặt | mặt ngoài | bề ngoài","surface | face | exterior | appearances","1489880"),
    ("頂上","ちょうじょう","n|adj-no","đỉnh | chóp | đỉnh cao","top | summit | peak","1430220"),
    ("先端","せんたん","n","đầu nhọn | mũi | tiên phong | tiên tiến","pointed end | tip | forefront | leading edge","1388110"),
    ("間隔","かんかく","n","khoảng cách | khoảng trống | khe","space | interval | gap","1215380"),
    ("幅","はば","n","chiều rộng | bề ngang | biên độ | chênh lệch","width | breadth | latitude | range","1500880"),
    ("奥行き","おくゆき","n","chiều sâu | độ sâu | chiều dài","depth | length","1179480"),
    ("厚み","あつみ","n","độ dày | bề dày | chiều sâu","thickness | profundity | depth","1275600"),
    ("重み","おもみ","n","trọng lượng | sức nặng (lời nói) | uy nghi","weight | weight (of words) | dignity | importance","1589410"),
    ("位置","いち","n|vs|vi","vị trí | vị thế | chỗ đứng","place | position | location | standing","1587310"),
    ("区域","くいき","n","khu vực | vùng | địa phận | ranh giới","area | zone | district | section | boundary","1244090"),
    ("境界線","きょうかいせん","n","đường ranh giới | đường biên","boundary line","1235970"),
    ("中間","ちゅうかん","n|adj-no","trung gian | ở giữa | nửa chừng | tạm thời","middle | midway | intermediate | interim","1423680"),
    ("両端","りょうたん","n","hai đầu | hai mép | hai phía","both ends | either end | both edges","1585170"),
    ("左右","さゆう","n|vs|vt","trái phải | hai bên | chi phối | tùy thuộc","left and right | (asserting) control | influence","1290810"),
    ("上下","じょうげ","n|vs|vi","trên dưới | lên xuống | thượng hạ | bộ (đồ)","top and bottom | up and down | upper and lower classes","1352710"),
    ("前後","ぜんご","n|adv|vs","trước sau | khoảng | thứ tự | đảo lộn","front and back | around (approximately) | order | inversion","1392910"),
    ("内外","ないがい","n|adj-no|n-suf","trong ngoài | trong và ngoài nước | khoảng chừng","inside and outside | home and abroad | approximately","1582470"),
    ("表裏","ひょうり","n|vs|vi","mặt phải mặt trái | hai mặt | hai lòng","front and back | two sides | duplicity","1489940"),
    ("縦","たて","n|adj-no","chiều dọc | chiều cao | chiều bắc-nam | quan hệ tôn ti","the vertical | height | length | vertical (relationship)","1335640"),
    ("斜め","ななめ","adj-no|adj-na|n","xiên | nghiêng | chéo | (tâm trạng) không vui","slanting | tilted | diagonal | bad (mood)","1322400"),
    ("垂直","すいちょく","adj-na|adj-no|n","thẳng đứng | vuông góc | thẳng góc","vertical | perpendicular","1370980"),
    ("水平","すいへい","adj-na|adj-no|n","nằm ngang | thăng bằng | bằng phẳng","horizontal | level | even","1372040"),
    ("平行","へいこう","n|vs|vi","song song | đồng thời | bế tắc (đàm phán)","parallelism | running parallel | not reaching an agreement","2835826"),
    ("直角","ちょっかく","n|adj-na|adj-no","góc vuông","right angle","1430800"),
    ("角度","かくど","n|adj-no","góc độ | góc","angle","1206190"),
    ("傾斜","けいしゃ","n|vs|vi","độ dốc | sự nghiêng | độ nghiêng","inclination | slant | slope | tilt","1249500"),
    ("勾配","こうばい","n","độ dốc | độ nghiêng | hệ số góc","slope | incline | gradient | pitch","1275300"),
    ("曲線","きょくせん","n","đường cong","curve","1239970"),
    ("直線","ちょくせん","n|adj-no","đường thẳng","straight line","1431310"),
    ("点線","てんせん","n","đường chấm | đường đứt nét","dotted line | perforated line","1441690"),
    ("円形","えんけい","n","hình tròn | dạng tròn","round shape | circle | circular form","1576590"),
    ("球形","きゅうけい","n|adj-no","hình cầu | dạng cầu","globular shape | spherical shape","1229930"),
    ("正方形","せいほうけい","n|adj-no","hình vuông","square","1377920"),
    ("長方形","ちょうほうけい","n|adj-no","hình chữ nhật","rectangle | oblong","1430130"),
    ("三角形","さんかくけい","n|adj-no","hình tam giác","triangle","1579380"),
    ("頂点","ちょうてん","n","đỉnh | đỉnh điểm | tột đỉnh | cực điểm","vertex | apex | top | peak | climax","1430240"),
    ("底辺","ていへん","n","cạnh đáy | tầng đáy (xã hội) | nền tảng","base (of a polygon) | bottom (of society) | foundation","1661390"),
    ("奥","おく","n","phía trong | bên trong | sâu trong | thâm sâu","inner part | interior | depths | recesses","1179320"),
    ("手前","てまえ","n|pn","phía trước mặt | gần đây | thể diện | tay nghề","in front of one | nearby | one's appearance | skill","1328030"),
    ("真ん中","まんなか","n","chính giữa | trung tâm | trung điểm","middle | centre | midpoint","1604350"),
    ("真上","まうえ","n|adj-no","ngay trên | thẳng phía trên | chính trên đầu","right above | directly above | overhead","1363940"),
    ("真下","ました","n|adj-no","ngay dưới | thẳng phía dưới","right under | directly below","1363460"),
    ("真横","まよこ","n","ngay bên cạnh | sát bên","(right at the) side | just beside","1363450"),
    ("真後ろ","まうしろ","n|adj-no","ngay phía sau | sát sau lưng","right behind | directly behind","1363680"),
    ("左隣","ひだりどなり","n|adj-no","bên trái | nhà/người kế bên trái","neighbour to the left","2668720"),
    ("右隣","みぎどなり","n|adj-no","bên phải | nhà/người kế bên phải","neighbour to the right","2668710"),
    ("近隣","きんりん","n|adj-no","lân cận | láng giềng | vùng phụ cận","neighbourhood | vicinity","1242570"),
    ("遠方","えんぽう","n","nơi xa | phương xa | xa xôi","distant place | faraway location","1178340"),
    ("各地","かくち","n","khắp nơi | các nơi | mọi miền","each place | various places | all parts","1205100"),
    ("現地","げんち","n","hiện trường | thực địa | tại chỗ | nơi đang ở","actual place | the spot | on site","1263860"),
    ("本場","ほんば","n|adj-no","nơi chính gốc | xứ sở (nổi tiếng) | cái nôi","home (of something) | place famous for | birthplace","1522690"),
    ("郊外","こうがい","n","ngoại ô | vùng ven đô","suburb | outskirts of a city","1282490"),
    ("都心","としん","n","trung tâm thành phố | nội đô","city centre | heart of a city | downtown","1445000"),
    ("中心地","ちゅうしんち","n","trung tâm | nơi trung tâm","center | metropolis","1424590"),
    ("繁華街","はんかがい","n","khu sầm uất | phố mua sắm | khu trung tâm","business district | shopping district | downtown","1481690"),
    ("住宅街","じゅうたくがい","n","khu dân cư | khu nhà ở","residential area","1334160"),
    ("歓楽街","かんらくがい","n","khu giải trí | khu ăn chơi","entertainment district | pleasure quarter","1212940"),
    ("大通り","おおどおり","n","đại lộ | phố lớn | đường chính","main street | avenue | boulevard","1414570"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
