# -*- coding: utf-8 -*-
"""Build N1 ready wave 030 — 慣用句 idiomatic expressions (set 30)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-030.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("あごを出す","あごをだす","exp|v5s","kiệt sức | mệt lả | rã rời | đuối sức","to be exhausted | to be worn out","2841233"),
    ("揚げ足を取る","あげあしをとる","exp|v5r","bắt bẻ lời nói | vạch lá tìm sâu | soi mói câu chữ | chỉ trích vặt","to jump on someone's verbal mistake | to find fault","1586280"),
    ("足元を見る","あしもとをみる","exp|v1","lợi dụng thế yếu | bắt bí | thừa nước đục thả câu | chèn ép","to take advantage (of a weak position)","2028770"),
    ("頭が下がる","あたまがさがる","exp|v5r","khâm phục | ngả mũ thán phục | cúi đầu kính nể","to admire greatly | to take one's hat off to","2237310"),
    ("後の祭り","あとのまつり","exp|n","muộn màng | nước đến chân | trở tay không kịp | đã quá trễ","too late | a day after the fair","1678830"),
    ("息を呑む","いきをのむ","exp|v5m","nín thở | sững sờ | nghẹt thở (kinh ngạc) | há hốc","to have one's breath taken away | to gasp","2015880"),
    ("板挟み","いたばさみ","n","kẹt giữa hai làn đạn | tiến thoái lưỡng nan | khó xử","being stuck between a rock and a hard place | dilemma","1481360"),
    ("一矢を報いる","いっしをむくいる","exp|v1","đáp trả | phản công | gỡ gạc | đánh trả một đòn","to retaliate | to strike back","1858910"),
    ("腕によりをかける","うでによりをかける","exp|v1","trổ hết tài | dốc hết tay nghề | thi thố tài năng","to put all one's skill into doing something","2063970"),
    ("裏目に出る","うらめにでる","exp|v1","phản tác dụng | gậy ông đập lưng ông | kết quả ngược lại","to backfire","2830571"),
    ("悦に入る","えつにいる","exp|v5r","khoái chí | hả hê | tự mãn | đắc ý ngầm","to be pleased | to gloat | to glow with satisfaction","1175260"),
    ("お株を奪う","おかぶをうばう","exp|v5u","vượt mặt sở trường | giỏi hơn cả chuyên gia | cướp nghề","to beat someone at their own game","2102500"),
    ("お墨付き","おすみつき","n","sự bảo chứng | giấy chứng nhận | cái gật đầu của cấp trên | đảm bảo","seal of approval | certification | the thumbs up","1002680"),
    ("顔から火が出る","かおからひがでる","exp|v1","đỏ mặt tía tai | ngượng chín mặt | xấu hổ nóng bừng","to be extremely embarrassed | to burn with shame","1217740"),
    ("影が薄い","かげがうすい","exp|adj-i","mờ nhạt | không nổi bật | lu mờ | thiếu hiện diện","in the background | not standing out","2006530"),
    ("肩透かしを食う","かたすかしをくう","exp|v5u","hụt hẫng | bị né tránh | trật lất | mất hứng","to suffer a disappointment | to be given the slip","2748040"),
    ("角が立つ","かどがたつ","exp|v5t","gây mất lòng | làm sứt mẻ tình cảm | căng thẳng | mếch lòng","to cause offence | to create hard feelings","2109080"),
    ("気が利く","きがきく","exp|v5k","tinh ý | ý tứ | khéo léo | tinh tế chu đáo","to be thoughtful | to be tactful | to be sensitive","1221640"),
    ("木で鼻をくくる","きではなをくくる","exp|v5r","lạnh lùng cộc lốc | trả lời cụt lủn | thờ ơ lạnh nhạt","to be blunt | to be curt","2103090"),
    ("気をもむ","きをもむ","exp|v5m","lo lắng | bồn chồn | sốt ruột | đứng ngồi không yên","to worry | to fret | to get anxious","2097260"),
    ("釘付け","くぎづけ","n|vs|vt","đóng đinh | dán mắt | đứng như trời trồng | bất động (đứng yên)","nailing down | being glued to | being rooted to the spot","1776900"),
    ("口が滑る","くちがすべる","exp|v5r","lỡ miệng | buột miệng | nói hớ | lỡ lời","to make a slip of the tongue | to let something slip","1640380"),
    ("口を尖らせる","くちをとがらせる","exp|v1","bĩu môi | chu mỏ | hờn dỗi | phụng phịu","to pout","2785620"),
    ("首が回らない","くびがまわらない","exp","ngập trong nợ | nợ ngập đầu | không xoay xở nổi (nợ nần)","being up to one's neck in debt","2839755"),
    ("軍配を上げる","ぐんばいをあげる","exp|v1","tuyên bố người thắng | phân định thắng thua | xử thắng","to declare someone the winner","2828264"),
    ("財布の紐","さいふのひも","exp|n","hầu bao | tay hòm chìa khóa | việc chi tiêu (財布の紐が固い)","purse strings","2867879"),
    ("舌が回る","したがまわる","exp|v5r","nói lưu loát | dẻo miệng | hoạt ngôn | ăn nói trơn tru","to be talkative | to speak fluently","2527660"),
    ("尻馬に乗る","しりうまにのる","exp|v5r","ăn theo | hùa theo mù quáng | bắt chước theo | dựa hơi","to follow blindly | to ride someone's coattails","1982890"),
    ("心臓に毛が生えている","しんぞうにけがはえている","exp|v1","mặt dày | gan lì | trơ tráo | thần kinh thép","to be shameless | to have nerves of steel","2655400"),
    ("図星","ずぼし","n","trúng tim đen | đúng phóc | điểm mấu chốt | nói trúng","bull's-eye | hitting the mark","1654230"),
    ("立つ瀬がない","たつせがない","exp|adj-i","khó ăn khó nói | mất mặt | bị dồn vào thế bí | không còn thể diện","being put in an awkward position | losing face","2146320"),
    ("玉に瑕","たまにきず","exp|n","ngọc có vết | tì vết duy nhất | điểm trừ nhỏ | mỹ trung bất túc","a fly in the ointment | the only flaw","1608890"),
    ("血道を上げる","ちみちをあげる","exp|v1","mê đắm | say mê mù quáng | lao vào điên cuồng | si mê","to be crazy about | to be infatuated with","2672540"),
    ("血も涙もない","ちもなみだもない","exp|adj-i","máu lạnh | nhẫn tâm | vô tình | không chút tình người","cold-blooded | heartless | unfeeling","1255090"),
    ("つむじを曲げる","つむじをまげる","exp|v1","trở chứng | dở quẻ | giận dỗi cố chấp | bướng bỉnh","to be contrary | to get cranky","2833937"),
    ("手が空く","てがあく","exp|v5k","rảnh tay | có thời gian rảnh | xong việc | rảnh rỗi","to be free | to be available","2093080"),
    ("峠を越える","とうげをこえる","exp|v1","qua đỉnh điểm | vượt giai đoạn khó nhất | qua cơn nguy","to pass the peak | to get through the worst","1896840"),
    ("取り付く島もない","とりつくしまもない","exp|adj-i","không biết bám víu vào đâu | bơ vơ | bị cự tuyệt | không chỗ dựa","left utterly helpless | unapproachable","2662180"),
    ("泥を吐く","どろをはく","exp|v5k","khai sạch | thú tội | cung khai | nhận tội","to confess one's crimes | to come clean","2745300"),
    ("長い目で見る","ながいめでみる","exp|v1","nhìn xa trông rộng | xét về lâu dài | nhìn theo hướng dài hạn","to look at the long term","2404360"),
    ("二の足を踏む","にのあしをふむ","exp|v5m","chần chừ | do dự | chùn bước | ngần ngại","to hesitate | to think twice | to get cold feet","1461300"),
    ("二の句が継げない","にのくがつげない","exp|adj-i","cứng họng | nghẹn lời | không nói nên lời | á khẩu","to be at a loss for words | to be dumbfounded","1461260"),
    ("願ったり叶ったり","ねがったりかなったり","n","cầu được ước thấy | đúng như ý nguyện | toại nguyện | vẹn cả đôi đường","everything working out as desired","1217960"),
    ("音を上げる","ねをあげる","exp|v1","đầu hàng | chịu thua | bó tay | than vãn bỏ cuộc","to give up | to admit defeat | to throw in the towel","2066630"),
    ("歯切れが悪い","はぎれがわるい","exp|adj-i","ấp úng | nói không rõ ràng | lập lờ | lúng búng","inarticulate | evasive | not clear","2628280"),
    ("鼻持ちならない","はなもちならない","exp|adj-i","khó ngửi | không chịu nổi | đáng ghét | chướng tai gai mắt","intolerable | unbearable | disgusting","1626080"),
    ("腹に据えかねる","はらにすえかねる","exp|v1","không nuốt trôi cơn giận | không thể chịu đựng | uất không nén nổi","cannot suppress one's anger | cannot stomach","2126260"),
    ("歯を食いしばる","はをくいしばる","exp|v5r","nghiến răng chịu đựng | cắn răng | gắng gượng | kìm nén","to clench one's teeth | to bear up (in hardship)","1313060"),
    ("一肌脱ぐ","ひとはだぬぐ","exp|v5g","xắn tay giúp đỡ | ra tay tương trợ | góp sức | giúp một tay","to pitch in and help | to give someone a hand","1165720"),
    ("火蓋を切る","ひぶたをきる","exp|v5r","khai chiến | mở màn | nổ phát súng đầu | khởi sự","to start (a battle, an argument)","2252980"),
    ("顰蹙を買う","ひんしゅくをかう","exp|v5u","bị chê trách | gây khó chịu | làm người ta cau mày | bị phản cảm","to invite frowns of disapproval | to displease","1574370"),
    ("不意を突く","ふいをつく","exp|v5k","đánh úp | bất ngờ tập kích | ra đòn bất thình lình | đánh lén","to take by surprise","2188660"),
    ("腑抜け","ふぬけ","n|adj-na","kẻ hèn nhát | nhu nhược | bạc nhược | không có khí phách","coward | spineless person | wimp","1570960"),
    ("臍を噛む","ほぞをかむ","exp|v5m","hối hận khôn nguôi | tiếc nuối đắng cay | ăn năn muộn màng","to regret bitterly","2061130"),
    ("骨身を惜しまず","ほねみをおしまず","exp","không quản nhọc nhằn | tận tụy | cật lực không tiếc sức","tirelessly | painstakingly | unsparingly","2856727"),
    ("水と油","みずとあぶら","exp|n","như nước với lửa | kỵ nhau | không hợp nhau | như dầu với nước","two incompatible things | like oil and water","2119060"),
    ("水を打ったよう","みずをうったよう","exp|adj-na","im phăng phắc | lặng như tờ | tĩnh lặng đột ngột","suddenly quiet | hushed","2200430"),
    ("道を付ける","みちをつける","exp|v1","mở đường | dọn đường | chỉ lối | dạy vỡ lòng","to pave the way | to give an elementary lesson","2085250"),
    ("身を引く","みをひく","exp|v5k","rút lui | từ bỏ | nhường bước | lui về | né tránh","to step aside | to retire | to back away","2029260"),
    ("胸が騒ぐ","むねがさわぐ","exp|v5g","bồn chồn | thấp thỏm | linh tính chẳng lành | tim đập loạn","to feel uneasy | to have a presentiment","2737640"),
    ("目を皿にする","めをさらにする","exp|vs-i","trố mắt | mở to mắt | căng mắt nhìn | dán mắt tìm","to open one's eyes wide","2129770"),
    ("目をつぶる","めをつぶる","exp|v5r","nhắm mắt làm ngơ | bỏ qua | lờ đi | nhắm mắt (qua đời)","to turn a blind eye | to overlook | to close one's eyes","1535180"),
    ("矢面に立つ","やおもてにたつ","exp|v5t","đứng mũi chịu sào | hứng chịu chỉ trích | đương đầu đối chất","to bear the brunt | to be in the firing line","1537800"),
    ("横槍を入れる","よこやりをいれる","exp|v1","xen ngang | chen vào | nói leo | can thiệp ngang","to interrupt | to butt in","2402600"),
    ("類を見ない","るいをみない","exp|adj-i","có một không hai | chưa từng có | độc nhất vô nhị","unprecedented | unique | unparalleled","2795670"),
    ("脇目も振らず","わきめもふらず","exp","mải miết | chuyên tâm | một lòng một dạ | không lơ là","single-mindedly | wholeheartedly | without distraction","2514790"),
    ("渡りをつける","わたりをつける","exp|v1","bắt mối | liên hệ trước | tạo quan hệ | móc nối","to make contact | to get in touch","2825720"),
    ("轍を踏む","てつをふむ","exp|v5m","đi vào vết xe đổ | lặp lại sai lầm | giẫm lên vết cũ","to repeat someone's mistake | to follow the same ruts","2131030"),
    ("天狗になる","てんぐになる","exp|v5r","tự cao tự đại | vênh váo | kiêu căng | tự phụ","to get conceited | to become vain | to get a swollen head","2596000"),
    ("泥仕合","どろじあい","n","cuộc cãi vã bôi nhọ | đấu tố lẫn nhau | bới móc nhau","mudslinging contest","1729590"),
    ("鼻白む","はなじろむ","v5m|vi","tẽn tò | cụt hứng | ngượng nghịu | thất vọng ra mặt","to look daunted | to look embarrassed","1847290"),
    ("反故にする","ほごにする","exp|vs-i","phế bỏ | xé bỏ | nuốt lời | hủy bỏ | vô hiệu hóa","to scrap | to renege | to make null and void","1480360"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
