# -*- coding: utf-8 -*-
"""Build N2 ready wave 052 — crime, investigation, arrest, court, sentencing, prison."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-052.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("犯行","はんこう","n","hành vi phạm tội | vụ phạm tội","crime | criminal act | offence","1481570"),
    ("共犯","きょうはん","n","đồng phạm","complicity","1235110"),
    ("主犯","しゅはん","n","chủ mưu | tội phạm chính","principal offender","1326110"),
    ("従犯","じゅうはん","n|adj-no","tòng phạm | đồng phạm phụ","accomplice | complicity","1335370"),
    ("累犯","るいはん","n","tái phạm | phạm tội nhiều lần","repeated offense | recidivism","1738400"),
    ("初犯","しょはん","n","phạm tội lần đầu | tội phạm lần đầu","first offence | first-time offender","1343040"),
    ("再犯","さいはん","n|vs|vi","tái phạm | phạm tội lần hai","second offence | reoffending","1293450"),
    ("真犯人","しんはんにん","n","thủ phạm thực sự | hung thủ thật","the real criminal | true culprit","1884230"),
    ("容疑者","ようぎしゃ","n|n-suf","nghi phạm | nghi can","suspect","1545390"),
    ("被疑者","ひぎしゃ","n","nghi phạm | người bị tình nghi","suspect","1771640"),
    ("目撃者","もくげきしゃ","n","nhân chứng | người chứng kiến","eye-witness | witness","1535400"),
    ("共謀","きょうぼう","n|vs|vt","đồng mưu | thông đồng | cấu kết","conspiracy | collusion","1235170"),
    ("教唆","きょうさ","n|vs|vt","xúi giục | kích động (phạm tội)","instigation | incitement","1237100"),
    ("幇助","ほうじょ","n|vs|vt","tiếp tay | trợ giúp | tòng phạm (giúp sức)","assistance | aiding and abetting (a crime)","1566590"),
    ("隠蔽工作","いんぺいこうさく","n|vs","việc che giấu | dàn dựng che đậy","(creating) a cover-up","2041890"),
    ("証拠隠滅","しょうこいんめつ","n","tiêu hủy chứng cứ | phi tang bằng chứng","destruction of evidence","1648140"),
    ("口裏合わせ","くちうらあわせ","n","thông cung | dàn xếp lời khai khớp nhau","getting the stories straight","2835252"),
    ("アリバイ","アリバイ","n","bằng chứng ngoại phạm","alibi","1019160"),
    ("手口","てぐち","n","thủ đoạn | mánh khóe | cách thức gây án","modus operandi | criminal technique","1327590"),
    ("遺留品","いりゅうひん","n","tang vật để lại | đồ vật bỏ lại (hiện trường)","article left behind (at a crime scene)","1159660"),
    ("指紋","しもん","n","dấu vân tay","fingerprint","1310040"),
    ("足跡","あしあと","n","dấu chân | dấu vết | lịch sử người ghé thăm","footprints | record of visitors","1581330"),
    ("現場","げんば","n","hiện trường | nơi xảy ra | công trường | phim trường","actual spot | scene (of a crime) | job site","1263760"),
    ("犯行現場","はんこうげんば","n","hiện trường vụ án","scene of the crime","1945570"),
    ("密室","みっしつ","n","phòng kín | căn phòng bí mật","locked room | secret room","1528260"),
    ("人質","ひとじち","n","con tin","hostage","1367960"),
    ("身代金","みのしろきん","n","tiền chuộc","ransom","1365610"),
    ("拉致","らち","n|vs|vt","bắt cóc | bắt đi","kidnapping | abduction","1567330"),
    ("指名手配","しめいてはい","n|vs|vt","truy nã (đích danh) | đưa vào danh sách truy nã","putting (a suspect) on the wanted list","1310020"),
    ("公開捜査","こうかいそうさ","n","điều tra công khai","open criminal investigation","1677400"),
    ("聞き込み","ききこみ","n","thu thập tin (qua hỏi nhân chứng) | lấy tin điều tra","getting information (in a police investigation)","1823280"),
    ("張り込み","はりこみ","n","mai phục | theo dõi | canh chừng | dán ghép","stakeout | ambush | lookout","1427790"),
    ("尾行","びこう","n|vs|vt","theo dõi | bám đuôi | đeo bám","shadow | tail | following","1485790"),
    ("おとり捜査","おとりそうさ","n","điều tra cài bẫy | điều tra chìm","sting operation | undercover investigation","2453490"),
    ("家宅捜索","かたくそうさく","n","khám xét nhà (của cảnh sát)","house search (by the police)","1192230"),
    ("連行","れんこう","n|vs|vt","áp giải | dẫn giải (nghi phạm) | lôi đi","taking (a suspect to the police) | dragging away","1559440"),
    ("留置","りゅうち","n|vs|vt","tạm giữ | giam giữ (trong điều tra)","detention | imprisonment | custody","1552820"),
    ("拘置","こうち","n|vs|vt","giam giữ | tạm giam | bắt giữ","detention | confinement | arrest","1279010"),
    ("身柄","みがら","n","thân thể | bản thân (người bị giữ)","one's person","1365830"),
    ("取り調べ","とりしらべ","n","thẩm vấn | điều tra | hỏi cung","investigation | examination | inquiry","1599080"),
    ("事情聴取","じじょうちょうしゅ","n|vs","lấy lời khai | điều tra hỏi cung | thẩm vấn","inquiry | (police) interview | questioning","2046010"),
    ("自供","じきょう","n|vs|vt","khai nhận | thú tội | cung khai","confession","1317560"),
    ("黙秘","もくひ","n|vs|vi","giữ im lặng | không khai | giữ bí mật","remaining silent | keeping secret","1535040"),
    ("冤罪","えんざい","n","án oan | bị buộc tội oan | vu oan","false charge | false accusation","1564270"),
    ("誤認逮捕","ごにんたいほ","n|vs","bắt nhầm | bắt giữ do nhận nhầm","mistaken arrest","2751160"),
    ("不起訴","ふきそ","n","không truy tố | miễn tố","nonprosecution | nonindictment","1491870"),
    ("書類送検","しょるいそうけん","n|vs|vt","chuyển hồ sơ sang viện kiểm sát | đề nghị truy tố","sending documents to a prosecutor","1702070"),
    ("送検","そうけん","n|vs|vt","chuyển hồ sơ truy tố | đưa vụ án lên công tố","referring a case to a public prosecutor","1402780"),
    ("起訴猶予","きそゆうよ","n","đình chỉ truy tố | hoãn truy tố","suspension of indictment","1614560"),
    ("略式起訴","りゃくしききそ","n","truy tố theo thủ tục rút gọn","summary indictment","2658780"),
    ("公判","こうはん","n","phiên tòa công khai | việc xét xử","public hearing | trial","1274510"),
    ("法廷","ほうてい","n","tòa án | phòng xử án","court (of law) | courtroom","1517400"),
    ("被告人","ひこくにん","n","bị cáo | người bị buộc tội","accused | defendant","1484420"),
    ("陪審","ばいしん","n","bồi thẩm đoàn","jury","1474150"),
    ("裁判員","さいばんいん","n","hội thẩm nhân dân | bồi thẩm công dân","lay judge | citizen judge | juror","2076700"),
    ("傍聴","ぼうちょう","n|vs|vt","dự thính | tham dự (phiên tòa, họp)","listening | attending | sitting in (on a meeting)","1518940"),
    ("証人","しょうにん","n","nhân chứng | người làm chứng","witness","1351660"),
    ("宣誓","せんせい","n|vs|vt","tuyên thệ | thề | lời thề","oath | pledge","1389710"),
    ("求刑","きゅうけい","n|vs|vt","đề nghị mức án | yêu cầu hình phạt (công tố)","recommended sentence | prosecution's demand","1229390"),
    ("論告","ろんこく","n|vs|vt","luận tội | lời buộc tội kết thúc của công tố","prosecutor's closing argument","1738670"),
    ("弁護人","べんごにん","n","người bào chữa | luật sư biện hộ","counsel | defender | advocate","1512880"),
    ("情状酌量","じょうじょうしゃくりょう","n|vs|vt|vi","xem xét tình tiết giảm nhẹ | châm chước hoàn cảnh","taking extenuating circumstances into consideration","1356310"),
    ("執行猶予","しっこうゆうよ","n","án treo | hoãn thi hành án","stay of execution | suspended sentence","1319640"),
    ("実刑","じっけい","n","án tù giam | án thực thi (không treo)","prison sentence (without a stay of execution)","1637960"),
    ("無期懲役","むきちょうえき","n","tù chung thân | tù không thời hạn","life imprisonment","1673150"),
    ("死刑","しけい","n","tử hình | án tử","death penalty | capital punishment","1310810"),
    ("科料","かりょう","n","tiền phạt (tội nhẹ)","fine (for a minor offence)","1192780"),
    ("過料","かりょう","n","tiền phạt hành chính | phạt không hình sự","administrative fine | nonpenal fine","1196470"),
    ("追放","ついほう","n|vs|vt","trục xuất | đày | thanh trừng | loại bỏ","exile | banishment | deportation | purge","1432670"),
    ("更生","こうせい","n|vs|vi|vt","cải tạo | làm lại cuộc đời | hồi sinh | tái sinh","rehabilitation | starting life anew | regeneration","1279390"),
    ("仮出所","かりしゅっしょ","n","tạm tha | được tại ngoại | ra tù có điều kiện","release on bail | parole","1187560"),
    ("出所","しゅっしょ","n|vs|vi","nguồn gốc | xuất xứ | ra tù | mãn hạn tù","source | origin | release from prison","1580030"),
    ("服役","ふくえき","n|vs|vi","thụ án | ngồi tù | lao động khổ sai | nghĩa vụ quân sự","serving time in prison | military service","1500990"),
    ("受刑","じゅけい","n|vs|vi","thụ án | chịu hình phạt","punishment","1329720"),
    ("刑期","けいき","n","thời hạn tù | thời gian thụ án","prison term","1249620"),
    ("監獄","かんごく","n","nhà tù | nhà giam","prison","1213620"),
    ("刑務所","けいむしょ","n","trại giam | nhà tù","prison | jail | penitentiary","1249820"),
    ("拘置所","こうちしょ","n","trại tạm giam | nhà tạm giữ","detention house | detention center","1279020"),
    ("留置場","りゅうちじょう","n","buồng tạm giữ | nhà tạm giam (đồn)","police cell | place of detention","1840270"),
    ("独房","どくぼう","n","phòng giam đơn | xà lim biệt giam","single-person cell | solitary confinement cell","1456020"),
    ("雑居房","ざっきょぼう","n","phòng giam tập thể | buồng giam chung","multi-person cell | shared cell","2753730"),
    ("看守","かんしゅ","n","cai ngục | quản giáo | lính canh tù","prison guard | warder | jailer","1213950"),
    ("囚人","しゅうじん","n","tù nhân | phạm nhân","prisoner | convict","1330470"),
    ("脱獄","だつごく","n|vs|vi|vt","vượt ngục | trốn tù | bẻ khóa (thiết bị)","escaping from prison | jailbreak","1623770"),
    ("恩赦","おんしゃ","n","ân xá | đặc xá","amnesty | pardon","1183180"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
