# -*- coding: utf-8 -*-
"""Build N3 ready wave 059 — 81 freshly-curated N3 language/abstract nouns + 〜度/〜性 nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-059.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("語彙","ごい","n","từ vựng | vốn từ","vocabulary | lexicon | terminology","1271260"),
    ("用語","ようご","n","thuật ngữ | từ ngữ | cách dùng từ","term | terminology | wording","1546270"),
    ("言葉遣い","ことばづかい","n","cách dùng từ | cách ăn nói | lời lẽ","speech | wording | language","1264560"),
    ("略語","りゃくご","n","từ viết tắt | từ rút gọn","abbreviation | acronym","1551990"),
    ("通訳","つうやく","n|vs|vt","phiên dịch (nói) | thông dịch viên","interpretation (oral) | interpreter","1433560"),
    ("字幕","じまく","n","phụ đề","subtitles | captioning","1315220"),
    ("記号","きごう","n","ký hiệu | dấu hiệu | biểu tượng","sign | symbol | mark","1223210"),
    ("符号","ふごう","n","ký hiệu | mã | dấu (âm dương)","sign | mark | code | sign (positive/negative)","1497710"),
    ("文体","ぶんたい","n","văn phong | thể văn","literary style | form of written language","1505510"),
    ("口調","くちょう","n","giọng điệu | cách nói","tone (of voice) | manner of talking","1276610"),
    ("語尾","ごび","n","đuôi từ | cuối câu","(inflectional) ending of a word | end of a sentence","1271180"),
    ("訛り","なまり","n","giọng địa phương | cách phát âm sai | thổ ngữ","accent | dialect | mispronunciation","1572570"),
    ("筆跡","ひっせき","n","nét chữ | bút tích | chữ viết tay","handwriting | calligraphy specimen","1487850"),
    ("活字","かつじ","n","chữ in | con chữ | bản in","(printing) type | printed word | print","1208300"),
    ("発行","はっこう","n|vs|vt","phát hành | xuất bản | cấp (giấy tờ)","publication | issue (of banknotes, passport, etc.)","1477390"),
    ("連載","れんさい","n|vs|vt","đăng nhiều kỳ | truyện đăng dài kỳ","serialization | serial story","1559510"),
    ("執筆","しっぴつ","n|vs|vt","viết (bài) | chấp bút | sáng tác","writing | authoring","1319710"),
    ("本音","ほんね","n","ý thật | lòng thật | điều thật sự nghĩ","real intention | true opinion | what one really thinks","1522250"),
    ("言い分","いいぶん","n","lý lẽ | ý kiến | điều muốn nói | lời than phiền","one's say | one's claim | complaint","1264250"),
    ("真相","しんそう","n","sự thật | chân tướng | tình hình thực","truth | real situation","1364110"),
    ("真実","しんじつ","n|adj-no","sự thật | chân thật | thực sự","truth | reality | truly","1363780"),
    ("道理","どうり","n","đạo lý | lẽ phải | lý lẽ","reason | logic | sense | truth","1454260"),
    ("理屈","りくつ","n","lý lẽ | lý sự | ngụy biện | cái cớ","theory | reason | (unreasonable) argument | excuse","1606240"),
    ("理性","りせい","n","lý trí | lý tính | sự tỉnh táo","reason | reasoning power | sense","1550010"),
    ("感性","かんせい","n","cảm tính | sự nhạy cảm | cảm thụ","sensitivity | sense (of...)","1212460"),
    ("教訓","きょうくん","n|vs|vt","bài học | lời răn | giáo huấn","lesson | precept | moral","1237080"),
    ("真理","しんり","n|adj-no","chân lý","truth","1364400"),
    ("法則","ほうそく","n","quy luật | định luật","law | rule","1517380"),
    ("原理","げんり","n","nguyên lý | nguyên tắc cơ bản","principle | theory | fundamental truth","1262460"),
    ("根源","こんげん","n","căn nguyên | nguồn gốc | cội nguồn","root | source | origin | cause","1290160"),
    ("由来","ゆらい","n|vs|adv","nguồn gốc | xuất xứ | vốn dĩ","origin | source | derivation | originally","1541810"),
    ("沿革","えんかく","n","lịch sử (hình thành) | quá trình phát triển","history | development","1176730"),
    ("経緯","けいい","n","diễn biến | đầu đuôi sự việc | kinh và vĩ độ","details | sequence of events | circumstances","1251120"),
    ("発端","ほったん","n","khởi nguồn | mở đầu | sự khởi đầu","origin | genesis | start | beginning","1477690"),
    ("意義","いぎ","n","ý nghĩa | tầm quan trọng","meaning | significance","1156520"),
    ("値打ち","ねうち","n|adj-na","giá trị | đáng giá | sự đánh giá","value | worth | merit | (good) value for money","1420340"),
    ("真価","しんか","n","giá trị thật | giá trị đích thực","true value | real worth","1363470"),
    ("水準","すいじゅん","n","trình độ | mức | mức nước","level | standard | water level","1371610"),
    ("程度","ていど","n|adv|n-suf","mức độ | trình độ | khoảng chừng","degree | grade | standard | about","1436540"),
    ("度合い","どあい","n","mức độ | phạm vi","degree | extent","1445200"),
    ("比例","ひれい","n|vs|vi","tỷ lệ | tỷ lệ thuận | đại diện theo tỷ lệ","proportion | proportional representation","1483700"),
    ("率","りつ","n|n-suf","tỷ lệ | tỷ suất | phần trăm","rate | ratio | proportion | percentage","1551200"),
    ("頻度","ひんど","n","tần suất | tần số xuất hiện","frequency (of occurrence)","1491030"),
    ("強度","きょうど","n|adj-no","cường độ | độ bền | độ mạnh","strength | intensity | powerful","1236490"),
    ("精度","せいど","n","độ chính xác | độ tinh vi","precision | accuracy","1380110"),
    ("高度","こうど","n|adj-na","độ cao | cao cấp | tiên tiến","altitude | high-degree | advanced | sophisticated","1283830"),
    ("深度","しんど","n","độ sâu","depth","1362780"),
    ("鮮度","せんど","n","độ tươi","(degree of) freshness","1392530"),
    ("純度","じゅんど","n","độ tinh khiết","purity (of a substance)","1341980"),
    ("透明度","とうめいど","n","độ trong suốt","transparency | degree of clearness","1854640"),
    ("重要度","じゅうようど","n","mức độ quan trọng | độ ưu tiên","importance | priority","2363690"),
    ("満足度","まんぞくど","n","mức độ hài lòng","(degree of) satisfaction","2740200"),
    ("完成度","かんせいど","n","độ hoàn thiện | mức độ hoàn chỉnh","degree of perfection | level of completion","2730630"),
    ("難易度","なんいど","n","độ khó | mức độ khó dễ","degree of difficulty | difficulty level","1460880"),
    ("優先度","ゆうせんど","n","mức độ ưu tiên","priority level","2390990"),
    ("信頼度","しんらいど","n","độ tin cậy | độ đáng tin","dependability | credibility","2114430"),
    ("貢献度","こうけんど","n","mức độ đóng góp","degree of contribution","2859611"),
    ("認知度","にんちど","n","độ nhận biết | mức độ quen thuộc","degree of recognition | level of familiarity","2412120"),
    ("利便性","りべんせい","n","tính tiện lợi | sự thuận tiện","convenience | user-friendliness","2532880"),
    ("安全性","あんぜんせい","n","tính an toàn | độ an toàn","safety | security","1153990"),
    ("信頼性","しんらいせい","n","độ tin cậy | tính xác thực","credibility | reliability","1359770"),
    ("危険性","きけんせい","n","mức độ nguy hiểm | tính rủi ro","(degree of) risk | danger","1218630"),
    ("将来性","しょうらいせい","n","triển vọng | tiềm năng tương lai","future prospects | promise","1347720"),
    ("独自性","どくじせい","n","tính độc đáo | nét riêng | sự độc nhất","originality | distinctiveness | uniqueness","1691430"),
    ("柔軟性","じゅうなんせい","n","tính linh hoạt | độ mềm dẻo","flexibility | pliability | elasticity","1335500"),
    ("妥当性","だとうせい","n","tính hợp lý | tính thỏa đáng | tính đúng đắn","validity | propriety","1408550"),
    ("透明性","とうめいせい","n","tính minh bạch | sự minh bạch","transparency","1450600"),
    ("一貫性","いっかんせい","n","tính nhất quán","consistency","1161590"),
    ("方向性","ほうこうせい","n","tính định hướng | hướng đi | mục tiêu","direction | course (of action) | orientation","2389200"),
    ("専門性","せんもんせい","n","tính chuyên môn | chuyên môn","specialization | expertise","2101430"),
    ("持続性","じぞくせい","n","tính bền vững | độ bền","durability","1770070"),
    ("即効性","そっこうせい","n|adj-no","tính hiệu quả tức thì | tác dụng nhanh","prompt efficiency | immediate effectivity","2668080"),
    ("実用性","じつようせい","n","tính thực dụng | tính hữu ích","practicality | utility | usefulness","2840480"),
    ("生産性","せいさんせい","n","năng suất | tính năng suất","productivity","1379030"),
    ("効率性","こうりつせい","n","tính hiệu quả | hiệu suất","efficiency","2151290"),
    ("規則性","きそくせい","n","tính quy luật | tính đều đặn","regularity","2128240"),
    ("具体性","ぐたいせい","n","tính cụ thể | tính khả thi","concreteness | feasibility","1712760"),
    ("客観性","きゃっかんせい","n","tính khách quan","objectivity","1685470"),
    ("主体性","しゅたいせい","n","tính chủ động | tính tự chủ | bản sắc","independence of will | autonomy | initiative","1325850"),
    ("積極性","せっきょくせい","n","tính tích cực | sự chủ động","assertiveness | positiveness | initiative","1383020"),
    ("創造性","そうぞうせい","n","tính sáng tạo","creativity","1398580"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
