# -*- coding: utf-8 -*-
"""Build N3 ready wave 052 — 86 freshly-curated N3 arts/sports + feeling-nouns + adjectives."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-052.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("娯楽","ごらく","n|vs","giải trí | tiêu khiển | thú vui","amusement | entertainment | recreation | pastime","1269290"),
    ("鑑賞","かんしょう","n|vs|vt","thưởng thức | thưởng lãm (nghệ thuật)","appreciation (of art, music, poetry)","1215200"),
    ("演劇","えんげき","n","kịch | sân khấu | vở kịch","drama | theatre | play","1176860"),
    ("上演","じょうえん","n|vs|vt","công diễn | trình diễn | dàn dựng","performance (of a play) | staging | presentation","1352670"),
    ("出演","しゅつえん","n|vs|vi","xuất hiện | tham gia diễn (phim, show)","appearance (in a film, show) | performance","1338290"),
    ("主演","しゅえん","n|vs|vi","đóng vai chính | thủ vai chính","starring | playing the leading part","1325050"),
    ("役者","やくしゃ","n","diễn viên | người khôn khéo","actor | actress | clever person","1538010"),
    ("作品","さくひん","n","tác phẩm","work (book, film, painting) | piece | production","1297910"),
    ("創作","そうさく","n|vs|vt","sáng tác | sáng tạo | bịa đặt","creation | creative work | (creative) writing | fabrication","1398420"),
    ("制作","せいさく","n|vs|vt","chế tác | sản xuất (phim, sách) | sáng tạo","work (film, book) | production | creation","1374810"),
    ("美術","びじゅつ","n","mỹ thuật | nghệ thuật","art | fine arts","1486440"),
    ("文学","ぶんがく","n","văn học","literature","1505190"),
    ("展示","てんじ","n|vs|vt","trưng bày | triển lãm","exhibition | display","1440610"),
    ("競技","きょうぎ","n|vs|vi","thi đấu | môn thi | cuộc thi","game | match | contest | competition | (sporting) event","1234080"),
    ("審判","しんぱん","n|vs|vt","phán xử | trọng tài | phân xử","judgement | refereeing | referee | umpire","1360410"),
    ("敗北","はいぼく","n|vs|vi","thất bại | thua cuộc","defeat | loss | setback","1472610"),
    ("勝敗","しょうはい","n","thắng thua | thắng bại | kết quả","victory or defeat | outcome (of a game)","1346220"),
    ("引き分け","ひきわけ","n","hòa | trận hòa","draw (in competition) | tie game","1169120"),
    ("得点","とくてん","n|vs|vi","điểm số | ghi điểm | bàn thắng","scoring | score | points | goals","1454590"),
    ("順位","じゅんい","n","thứ hạng | thứ tự | vị trí (xếp hạng)","order | rank | position (in a race)","1342260"),
    ("対戦","たいせん","n|vs|vi","đối đầu | thi đấu (với) | giao đấu","fighting (against) | facing | match | contest","1410190"),
    ("鍛える","きたえる","v1|vt","rèn luyện | tôi luyện | rèn (kim loại)","to forge | to temper | to train | to discipline","1419120"),
    ("応援","おうえん","n|vs|vt","cổ vũ | ủng hộ | tiếp viện","aid | support | cheering | rooting (for)","1179840"),
    ("声援","せいえん","n|vs|vt","cổ vũ | hò reo động viên","(shout of) encouragement | cheering | support","1380460"),
    ("歓声","かんせい","n","tiếng reo hò | tiếng hoan hô","cheer | shout of joy","1213000"),
    ("拍手","はくしゅ","n|vs|vi","vỗ tay | tán thưởng","clapping hands | applause","1474820"),
    ("興味","きょうみ","n","hứng thú | sự quan tâm | tò mò","interest | curiosity | zest (for)","1238410"),
    ("関心","かんしん","n","quan tâm | mối quan tâm | chú ý","concern | interest","1215870"),
    ("熱中","ねっちゅう","n|vs|vi","say mê | mê mải | đắm chìm","being enthusiastic about | being absorbed in","1467950"),
    ("夢中","むちゅう","adj-na|n","mải mê | say mê | quên mình","absorbed in | crazy about | forgetting oneself","1529500"),
    ("没頭","ぼっとう","n|vs|vi","vùi đầu | chìm đắm | dồn hết tâm sức","immersing oneself in | being absorbed in | devoting oneself","1522010"),
    ("専念","せんねん","n|vs|vi","chuyên tâm | dồn hết tâm trí | tập trung vào","absorption | giving undivided attention | devoting oneself","1389850"),
    ("集中","しゅうちゅう","n|vs|vt|vi","tập trung | tập trung hóa | dồn về","concentration | focusing | centralization","1333750"),
    ("気晴らし","きばらし","n|vs|vi","giải khuây | thư giãn | tiêu khiển","recreation | diversion | relaxation","1222390"),
    ("気分転換","きぶんてんかん","n","đổi gió | thay đổi tâm trạng | giải tỏa","change of pace | change of mood | refreshment","1222610"),
    ("迷惑","めいわく","n|adj-na|vs|vi","phiền phức | làm phiền | rắc rối","trouble | bother | nuisance | inconvenience","1532800"),
    ("手数","てすう","n","sự phiền phức | công sức | số nước đi","trouble | bother | number of moves","1327970"),
    ("苦労","くろう","n|vs|vt|vi","vất vả | gian khổ | nhọc nhằn | lo lắng","trouble | hardship | difficulty | toil | worry","1244680"),
    ("根気","こんき","n","sự kiên trì | bền bỉ | nhẫn nại","patience | perseverance | persistence | tenacity","1290110"),
    ("粘り","ねばり","n","độ dẻo | sự bền bỉ | tính kiên trì","stickiness | viscosity | tenacity | persistence","1469670"),
    ("意地","いじ","n","sự bướng bỉnh | lòng tự ái | ý chí | thèm muốn","stubbornness | willpower | pride | appetite","1156720"),
    ("向上心","こうじょうしん","n","chí tiến thủ | tinh thần cầu tiến","ambition | aspiration | desire to improve oneself","1277260"),
    ("好奇心","こうきしん","n","tính tò mò | sự hiếu kỳ","curiosity | inquisitiveness","1277590"),
    ("自尊心","じそんしん","n","lòng tự tôn | lòng tự trọng | tính tự cao","self-esteem | self-respect | pride","1318220"),
    ("優越感","ゆうえつかん","n","cảm giác hơn người | sự tự cao","superiority complex | sense of superiority","1539130"),
    ("責任感","せきにんかん","n","tinh thần trách nhiệm","sense of responsibility","1645890"),
    ("正義感","せいぎかん","n","tinh thần chính nghĩa | ý thức công lý","sense of justice | moral sense","1376920"),
    ("罪悪感","ざいあくかん","n","mặc cảm tội lỗi | cảm giác tội lỗi","feelings of guilt","1296700"),
    ("緊張感","きんちょうかん","n","cảm giác căng thẳng | sự hồi hộp","feeling of tension | nervousness","2428940"),
    ("安心感","あんしんかん","n","cảm giác an tâm | sự yên lòng","sense of security","1613240"),
    ("充実感","じゅうじつかん","n","cảm giác viên mãn | sự trọn vẹn","sense of fulfillment | sense of accomplishment","2525090"),
    ("親近感","しんきんかん","n","cảm giác gần gũi | sự thân thiết","affinity | feeling of closeness | feeling of kinship","1365140"),
    ("違和感","いわかん","n","cảm giác khó chịu | sự gượng gạo | thấy lạ","uncomfortable feeling | sense of discomfort | feeling out of place","1159020"),
    ("危機感","ききかん","n","cảm giác khủng hoảng | ý thức nguy cơ","sense of impending crisis | sense of danger","1821440"),
    ("使命感","しめいかん","n","tinh thần sứ mệnh | ý thức trách nhiệm","sense of duty | sense of purpose | vocation","2100390"),
    ("一体感","いったいかん","n","cảm giác hòa làm một | sự gắn kết","sense of unity | (feeling of) identification","1930310"),
    ("平凡","へいぼん","adj-na|n","tầm thường | bình thường | không có gì nổi bật","ordinary | commonplace | mediocre | unremarkable","1507910"),
    ("非凡","ひぼん","adj-na|n","phi thường | xuất chúng | hiếm có","extraordinary | uncommon | remarkable | prodigious","1485170"),
    ("独特","どくとく","n|adj-na","độc đáo | đặc trưng | riêng biệt","peculiarity | uniqueness | characteristic","1456010"),
    ("特殊","とくしゅ","adj-na|n","đặc thù | đặc biệt | riêng biệt","special | particular | peculiar | unique","1454970"),
    ("通常","つうじょう","adj-no|n|adv","thông thường | bình thường | thường lệ","usual | ordinary | normal | regular","1433280"),
    ("正常","せいじょう","adj-na|n","bình thường | thông thường","normal | regular","1377390"),
    ("異常","いじょう","adj-na|n","bất thường | dị thường | khác thường","abnormal | unusual | extraordinary","1157760"),
    ("正規","せいき","adj-no|adj-na|n","chính quy | chính thức | hợp pháp","regular | normal | formal | legitimate","1376850"),
    ("正式","せいしき","adj-na|adj-no|n","chính thức | đúng quy cách | hợp lệ","formal | official | regular | proper","1377290"),
    ("非公式","ひこうしき","adj-no|adj-na|n","không chính thức | phi chính thức","informal | unofficial","1484850"),
    ("公式","こうしき","adj-no|n","chính thức | công thức (toán) | tài khoản chính thức","official | formal | formula (mathematical)","1273820"),
    ("本格的","ほんかくてき","adj-na","chính thức | thực thụ | quy mô đầy đủ | nghiêm túc","genuine | authentic | full-scale | full-fledged","1522330"),
    ("本来","ほんらい","adv|n","vốn dĩ | về bản chất | đúng ra","originally | essentially | by nature | proper","1523270"),
    ("元来","がんらい","adv","vốn dĩ | nguyên bản | thực ra | ban đầu","originally | essentially | by nature | in the first place","1261080"),
    ("本格","ほんかく","n","cách thức nguyên bản | phương pháp chính thống","original method | genuine way (of doing something)","1522310"),
    ("極端","きょくたん","n|adj-na","cực đoan | thái quá | cực độ","extreme | extremity","1240380"),
    ("過度","かど","adj-na|n","quá độ | thái quá | quá mức","excessive | immoderate","1196310"),
    ("過敏","かびん","adj-na|n","quá nhạy cảm | dễ kích ứng","nervousness | oversensitivity","1196400"),
    ("鈍重","どんじゅう","adj-na|n","chậm chạp | ì ạch | trì độn","slow-witted | phlegmatic | sluggish","1457650"),
    ("快活","かいかつ","adj-na","vui vẻ | hoạt bát | yêu đời","cheerful | lively | lighthearted","1200000"),
    ("活発","かっぱつ","adj-na|n","sôi nổi | năng động | hoạt bát","lively | active | vigorous | brisk","1208410"),
    ("温和","おんわ","adj-na|n","ôn hòa | dịu dàng | hiền hòa","mild (climate) | gentle (nature) | moderate","1589620"),
    ("凶暴","きょうぼう","adj-na|n","hung bạo | tàn bạo | dữ tợn","ferocious | brutal | savage","1591680"),
    ("獰猛","どうもう","adj-na|n","hung dữ | dữ tợn | hung tợn","ferocious | fierce | savage","1585790"),
    ("高慢","こうまん","adj-na|n","kiêu căng | ngạo mạn | tự cao","haughty | arrogant | proud | stuck-up","1615850"),
    ("傲慢","ごうまん","adj-na|n","ngạo mạn | kiêu ngạo | hống hách","haughty | arrogant | insolent | overbearing","1563960"),
    ("卑屈","ひくつ","adj-na|n","khúm núm | hèn hạ | quỵ lụy","servile | subservient | obsequious | self-abasing","1482740"),
    ("横柄","おうへい","adj-na|n","ngạo mạn | hống hách | xấc xược","arrogant | haughty | insolent","1181030"),
    ("華奢","きゃしゃ","adj-na|n","mảnh mai | thanh mảnh | mong manh","dainty | delicate | slender | fragile","1195660"),
    ("俊敏","しゅんびん","adj-na|n","nhanh nhẹn | nhạy bén | lanh lợi","quick-witted and agile | keen and nimble","1340980"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
