# -*- coding: utf-8 -*-
"""Build N3 ready wave 065 — 85 freshly-curated N3 motion/sound verbs + 〜しい/〜然 adjectives + panic/spirit nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-065.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("降り注ぐ","ふりそそぐ","v5g|vi","đổ xuống | trút xuống | rọi xuống","to rain incessantly | to downpour | to pour down","1282780"),
    ("立ち込める","たちこめる","v1|vi","bao trùm | giăng kín | mịt mù","to hang over | to shroud | to envelop","1551510"),
    ("漲る","みなぎる","v5r|vi","tràn đầy | dâng cao | căng tràn (sức sống)","to overflow | to swell | to be filled with (energy)","1568820"),
    ("突き刺す","つきさす","v5s|vt","đâm | chọc | xuyên thủng","to stab | to pierce | to thrust","1456650"),
    ("突く","つく","v5k|vt","chọc | đâm | thúc | tấn công (điểm yếu)","to poke | to thrust | to prod | to attack","1456890"),
    ("射る","いる","v1|vt","bắn (tên)","to shoot (an arrow, bolt, dart)","1322180"),
    ("放つ","はなつ","v5t|vt","bắn | thả ra | phát ra (ánh sáng, mùi)","to fire | to set free | to emit (light) | to give off","1516490"),
    ("投げ出す","なげだす","v5s|vt","ném ra | duỗi (chân) | từ bỏ | hy sinh","to throw out | to abandon | to give freely | to sacrifice","1447040"),
    ("投げかける","なげかける","v1|vt","ném tới | đặt (câu hỏi) | nêu ra","to throw at | to turn | to raise (a question)","1447010"),
    ("浴びせる","あびせる","v1|vt","dội | xối | trút (lên ai)","to pour on | to shower with","1547440"),
    ("降りかかる","ふりかかる","v5r|vi","rơi xuống | giáng xuống | ập đến","to fall on | to rain down | to befall","1602930"),
    ("見舞う","みまう","v5u|vt","thăm hỏi | thăm bệnh | (tai họa) ập đến","to visit and console | to ask after (health) | to strike (disaster)","1259990"),
    ("襲う","おそう","v5u|vt","tấn công | tập kích | ập đến | kế thừa","to attack | to assail | to strike | to succeed (a post)","1333330"),
    ("鳴り響く","なりひびく","v5k|vi","vang vọng | vang dội | nổi danh","to reverberate | to resound | to be renowned","1532890"),
    ("轟く","とどろく","v5k|vi","gầm vang | rền vang | vang danh | đập rộn (tim)","to roar | to rumble | to become famous | to pound (heart)","1285710"),
    ("唸る","うなる","v5r|vi|vt","gầm gừ | rên | gào (gió, máy) | trầm trồ","to groan | to growl | to howl (wind) | to ooh and aah","1565300"),
    ("吠える","ほえる","v1|vi","sủa | gầm | rống | gào thét","to bark | to howl | to roar | to yell","1603420"),
    ("呻く","うめく","v5k|vi","rên rỉ | rên la","to moan | to groan","1565140"),
    ("嘆息","たんそく","n|vs|vi","than thở | thở dài | ai oán","sigh (of grief) | grieving | lamenting","1418120"),
    ("寝言","ねごと","n","nói mơ | nói trong lúc ngủ | lời vô nghĩa","talking in one's sleep | nonsense | gibberish","1360100"),
    ("独り言","ひとりごと","n","lời độc thoại | nói một mình","soliloquy | monologue | speaking to oneself","1455670"),
    ("重々しい","おもおもしい","adj-i","trang nghiêm | trịnh trọng | uy nghi","serious | grave | dignified | solemn","1589360"),
    ("軽々しい","かるがるしい","adj-i","khinh suất | nhẹ dạ | thiếu thận trọng","rash | thoughtless | careless | frivolous","1590700"),
    ("馬鹿馬鹿しい","ばかばかしい","adj-i","ngớ ngẩn | vô lý | nực cười","absurd | ridiculous | silly | nonsensical","1471740"),
    ("白々しい","しらじらしい","adj-i","trơ trẽn | giả tạo | lộ liễu (giả vờ)","barefaced (lie) | transparent | shameless | disingenuous","1595060"),
    ("仰々しい","ぎょうぎょうしい","adj-i","khoa trương | phô trương | làm quá","exaggerated | bombastic | highly coloured","1592070"),
    ("弱々しい","よわよわしい","adj-i","yếu ớt | mỏng manh | yếu đuối","weak | feeble | frail | faint","1606170"),
    ("神々しい","こうごうしい","adj-i","thần thánh | linh thiêng | uy nghiêm","divine | sublime | solemn","1639830"),
    ("瑞々しい","みずみずしい","adj-i","tươi tắn | mơn mởn | mọng nước","fresh and youthful | vibrant | juicy","1372810"),
    ("初々しい","ういういしい","adj-i","ngây thơ | trong sáng | non nớt","(young and) innocent | naive | fresh | artless","1587960"),
    ("華々しい","はなばなしい","adj-i","rực rỡ | huy hoàng | lộng lẫy","brilliant | splendid | glorious | spectacular","1600960"),
    ("猛々しい","たけだけしい","adj-i","hung tợn | dữ dằn | trơ tráo","ferocious | fierce | audacious | shameless","1596890"),
    ("露骨","ろこつ","adj-na|n","trắng trợn | lộ liễu | thẳng thừng | tục tĩu","open | blatant | undisguised | crude","1560120"),
    ("歴然","れきぜん","adj-t|adv-to","rõ ràng | rành rành | hiển nhiên","evident | plain | distinct | clear","1612300"),
    ("平然","へいぜん","adj-t|adv-to","điềm nhiên | bình thản | thản nhiên","calm | composed | cool","1507540"),
    ("悠然","ゆうぜん","adj-t|adv-to","ung dung | thong thả | điềm tĩnh","calm | composed | leisurely","1540700"),
    ("整然","せいぜん","adj-t|adv-to","ngăn nắp | có trật tự | mạch lạc","orderly | systematic | well-organized | tidy","1376200"),
    ("雑然","ざつぜん","adj-t|adv-to","lộn xộn | bừa bộn | hỗn độn","untidy | messy | cluttered | chaotic","1299450"),
    ("騒然","そうぜん","adj-t|adv-to","ồn ào | náo loạn | xôn xao","noisy | confused | uproarious","1403070"),
    ("公然","こうぜん","adj-no|adj-t|adv-to","công khai | công nhiên | rành rành","open | public | overt","1274190"),
    ("必然","ひつぜん","adj-no|adj-na|n","tất yếu | tất nhiên | tính tất yếu","inevitable | necessary | certain | necessity","1487570"),
    ("依然","いぜん","adj-t|adv-to|adv","vẫn | vẫn như cũ | y nguyên","still | as yet | as it has been","1155650"),
    ("呆然","ぼうぜん","adj-t|adv-to","ngơ ngác | sững sờ | thẫn thờ","dumbfounded | in blank amazement | in a daze","1515610"),
    ("愕然","がくぜん","adj-t|adv-to","sửng sốt | kinh ngạc | choáng váng","astonished | shocked | aghast","1693200"),
    ("憤然","ふんぜん","adj-t|adv-to","phẫn nộ | căm phẫn | giận dữ","angry | indignant | wrathful | enraged","1689570"),
    ("敢然","かんぜん","adv-to|adj-t","dũng cảm | quả quyết | kiên quyết","boldly | bravely | resolutely","1212890"),
    ("猛然","もうぜん","adv-to|adj-t","mãnh liệt | dữ dội | quyết liệt","fiercely | ferociously | furiously","1674780"),
    ("俄然","がぜん","adv","đột nhiên | bỗng nhiên | hẳn lên","suddenly | abruptly | absolutely | by far","1196620"),
    ("判然","はんぜん","adv-to|vs","rõ ràng | rành mạch | minh bạch","clearly | distinctly | evidently","1478600"),
    ("釈然","しゃくぜん","adj-t|adv-to","thông suốt | hết nghi ngờ | nguôi ngoai","fully satisfied (with an explanation) | cleared of doubt","1324250"),
    ("画然","かくぜん","adj-t|adv-to","rõ rệt | rạch ròi | phân minh","clear (distinction) | distinct | clear-cut","1197360"),
    ("渾然","こんぜん","adj-t|adv-to","hài hòa | hòa quyện | trọn vẹn","whole | harmonious | well-rounded","1568760"),
    ("端然","たんぜん","adj-t|adv-to","ngay ngắn | đoan trang | chỉnh tề","proper (posture) | correct | neat | upright","1704810"),
    ("泰然","たいぜん","adj-t|adv-to","ung dung | điềm tĩnh | thản nhiên","calm | composed | self-possessed | firm","1410890"),
    ("朦朧","もうろう","adj-t|adv-to","mơ hồ | lờ mờ | lơ mơ","dim | hazy | vague | indistinct | fuzzy","1567970"),
    ("茫然","ぼうぜん","adj-t|adv-to","mơ hồ | ngẩn ngơ | mờ mịt","vague | dazed | blank","2835317"),
    ("唖然","あぜん","adj-t|adv-to","á khẩu | sững người | cứng họng","dumbfounded | speechless | flabbergasted","1784380"),
    ("憮然","ぶぜん","adj-t|adv-to","thất vọng | bần thần | sững sờ | bực dọc","disappointed | dejected | astonished | indignant","1566980"),
    ("慄然","りつぜん","adj-t|adv-to","kinh hãi | rùng mình | sợ tái người","terrified | horrified | trembling with fear","1566910"),
    ("凛然","りんぜん","adj-t|adv-to","oai nghiêm | uy nghi | rét buốt","commanding | awe-inspiring | piercing (cold)","1564330"),
    ("毅然","きぜん","adj-t|adv-to","kiên quyết | cứng cỏi | dũng cảm","resolute | firm | dauntless | undaunted","1822530"),
    ("傲然","ごうぜん","adj-t|adv-to","ngạo nghễ | kiêu căng | hống hách","proud | arrogant | haughty","1563940"),
    ("泰然自若","たいぜんじじゃく","adj-t|adv-to","điềm nhiên tự tại | bình tĩnh tự chủ","self-possessed | imperturbable | calm and composed","1410900"),
    ("沈着","ちんちゃく","n|adj-na|vs","điềm tĩnh | bình tĩnh | lắng đọng | bám","composure | calmness | presence of mind | deposition","1431760"),
    ("動転","どうてん","n|vs|vi","hoảng loạn | mất bình tĩnh | rối trí","disturbance of mind | losing one's head | being upset","1451460"),
    ("狼狽","ろうばい","n|vs|vi","hoảng hốt | bối rối | hốt hoảng","confusion | dismay | consternation | panic","1560960"),
    ("混乱","こんらん","n|vs|vi","hỗn loạn | rối loạn | lộn xộn","disorder | chaos | confusion | mayhem","1290560"),
    ("錯乱","さくらん","n|vs|vi","loạn trí | rối loạn | mất phương hướng","confusion | distraction | derangement","1298450"),
    ("取り乱す","とりみだす","v5s|vi|vt","mất bình tĩnh | rối bời | bày bừa","to lose one's composure | to be flustered | to put in disorder","1326950"),
    ("慌てふためく","あわてふためく","v5k|vi","cuống cuồng | hớt hải | nháo nhào","to get into a panic | to be flustered","1278820"),
    ("たじろぐ","たじろぐ","v5g|vi","chùn bước | nao núng | rụt lại","to shrink back | to wince | to flinch | to recoil","1007220"),
    ("身震い","みぶるい","n|vs|vi","run rẩy | rùng mình | run lên","shivering (with cold) | trembling (with fear)","1365730"),
    ("鳥肌","とりはだ","n","da gà | nổi da gà | da sần","goosebumps | gooseflesh | rough skin","1430320"),
    ("冷や汗","ひやあせ","n","mồ hôi lạnh | toát mồ hôi hột","cold sweat","1602210"),
    ("脂汗","あぶらあせ","n","mồ hôi nhờn | mồ hôi (đau, lo)","cold sweat | greasy sweat","1538640"),
    ("武者震い","むしゃぶるい","n|vs|vi","run lên vì phấn khích | rạo rực","trembling with excitement","1604860"),
    ("胸騒ぎ","むなさわぎ","n|vs|vi","bồn chồn | lo lắng mơ hồ | linh tính xấu","uneasiness | vague apprehension | premonition","1237930"),
    ("気後れ","きおくれ","n|vs|vi","rụt rè | e dè | mất tự tin | chùn","losing one's nerve | feeling timid | being daunted","1222160"),
    ("気負い","きおい","n","hăng hái | nhiệt huyết | khí thế","eagerness | enthusiasm | fighting spirit","1222570"),
    ("意気込み","いきごみ","n","khí thế | nhiệt huyết | sự hăng hái","ardor | enthusiasm","1613260"),
    ("張り切る","はりきる","v5r","hăng hái | đầy khí thế | căng hết sức","to be in high spirits | to be enthusiastic | to stretch tight","1427870"),
    ("意気込む","いきごむ","v5m|vi","hăng hái | quyết tâm | hăm hở","to be enthusiastic | to be eager | to be determined","1156450"),
    ("勢い","いきおい","n|adv","khí thế | đà | sức mạnh | tất yếu","force | vigor | momentum | influence | naturally","1375040"),
    ("勢いづく","いきおいづく","v5k|vi","lên tinh thần | thừa thắng | được tiếp sức","to gain strength | to gather momentum | to be encouraged","1375060"),
    ("活気","かっき","n","sức sống | sinh khí | sự sôi nổi","energy | vigour | liveliness | animation","1208270"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
