# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-019.csv — 50 rows (Wave 10 pool batch)."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-019.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("一戸建て","いっこだて","N4","n",
        "nhà riêng | nhà một hộ gia đình | nhà độc lập",
        "detached house | stand-alone house | single-family home",
        "1162320",
        "一戸建てに住みます。","いっこだてにすみます。","Tôi sống trong nhà riêng.","I live in a detached house."),
    row("出版","しゅっぱん","N4","n|vs|vt",
        "xuất bản | phát hành",
        "publication",
        "1340030",
        "本を出版します。","ほんをしゅっぱんします。","Tôi xuất bản sách.","I publish a book."),
    row("生態系","せいたいけい","N4","n",
        "hệ sinh thái",
        "ecosystem",
        "1379300",
        "生態系を守ります。","せいたいけいをまもります。","Chúng tôi bảo vệ hệ sinh thái.","We protect the ecosystem."),
    row("絶滅","ぜつめつ","N4","n|vs|vi",
        "tuyệt chủng | diệt vong | xóa sổ",
        "extinction | extermination | eradication | stamping out | wiping out",
        "1386990",
        "動物が絶滅します。","どうぶつがぜつめつします。","Động vật tuyệt chủng.","Animals go extinct."),
    row("遅延","ちえん","N4","n|vs|vi|adj-no",
        "trì hoãn | độ trễ",
        "delay | latency",
        "1422030",
        "電車が遅延します。","でんしゃがちえんします。","Tàu bị trễ.","The train is delayed."),
    row("都市","とし","N4","n|adj-no",
        "thành phố | đô thị | thành thị",
        "town | city | municipal | urban",
        "1444990",
        "都市に住みます。","としにすみます。","Tôi sống ở thành phố.","I live in the city."),
    row("糖尿病","とうにょうびょう","N4","n",
        "bệnh tiểu đường | đái tháo đường",
        "diabetes | diabetes mellitus",
        "1449640",
        "糖尿病を予防します。","とうにょうびょうをよぼうします。","Tôi phòng ngừa bệnh tiểu đường.","I prevent diabetes."),
    row("分析","ぶんせき","N4","n|vs|vt",
        "phân tích",
        "analysis",
        "1503870",
        "データを分析します。","データをぶんせきします。","Tôi phân tích dữ liệu.","I analyze data."),
    row("文明","ぶんめい","N4","n",
        "văn minh | văn hóa | nền văn minh",
        "civilization | civilisation | culture",
        "1505650",
        "文明が発展します。","ぶんめいがはってんします。","Văn minh phát triển.","Civilization develops."),
    row("乗り場","のりば","N4","n",
        "bến xe | điểm đón xe | sân ga | bến tàu",
        "place for boarding vehicles | bus stop | bus terminal | railway platform | taxi stand | jetty | wharf",
        "1600520",
        "バスの乗り場を探します。","バスののりばをさがします。","Tôi tìm bến xe buýt.","I look for the bus stop."),
    row("太陽光","たいようこう","N4","n",
        "ánh sáng mặt trời",
        "sunlight",
        "1890800",
        "太陽光エネルギーを使います。","たいようこうエネルギーをつかいます。","Tôi sử dụng năng lượng mặt trời.","I use solar energy."),
    row("問題集","もんだいしゅう","N4","n",
        "tập bài tập | tuyển tập đề thi | bài tập",
        "question collection | problem collection | problem set | workbook",
        "2259180",
        "問題集を解きます。","もんだいしゅうをときます。","Tôi giải bài tập.","I solve the workbook problems."),
    row("温暖化","おんだんか","N4","n|vs|vi",
        "sự nóng lên (toàn cầu) | ấm lên",
        "(global) warming",
        "2658470",
        "地球温暖化が進みます。","ちきゅうおんだんかがすすみます。","Trái đất nóng lên tiếp tục.","Global warming progresses."),
    row("再生可能","さいせいかのう","N4","adj-na",
        "tái tạo | có thể tái tạo",
        "renewable",
        "2847574",
        "再生可能エネルギーが必要です。","さいせいかのうエネルギーがひつようです。","Năng lượng tái tạo là cần thiết.","Renewable energy is necessary."),
    row("お酢","おす","N4","n",
        "giấm",
        "vinegar",
        "2855385",
        "お酢を入れます。","おすをいれます。","Tôi cho giấm vào.","I add vinegar."),
    row("水力","すいりょく","N4","n|adj-no",
        "thủy lực | năng lượng nước",
        "hydraulic power | water power",
        "1372260",
        "水力発電をします。","すいりょくはつでんをします。","Chúng tôi phát điện thủy lực.","We generate hydroelectric power."),
    row("腸","ちょう","N4","n",
        "ruột | đường ruột",
        "intestine | bowel",
        "1428960",
        "腸を整えます。","ちょうをととのえます。","Tôi điều chỉnh đường ruột.","I regulate my intestines."),
    row("調査","ちょうさ","N4","n|vs|vt",
        "điều tra | khảo sát | kiểm tra",
        "investigation | examination | inquiry | enquiry | survey",
        "1429120",
        "現地を調査します。","げんちをちょうさします。","Tôi điều tra thực địa.","I investigate the site."),
    row("調味料","ちょうみりょう","N4","n",
        "gia vị | chất điều vị | nước chấm",
        "seasoning | flavoring | flavouring | condiment",
        "1429290",
        "調味料を加えます。","ちょうみりょうをくわえます。","Tôi thêm gia vị.","I add seasoning."),
    row("沈む","しずむ","N4","v5m|vi",
        "chìm xuống | lặn (mặt trời) | sụp xuống | buồn bã | ảm đạm",
        "to sink | to go under | to submerge | to go down (e.g. sun) | to set | to descend | to feel depressed | to become subdued | to become somber",
        "1431670",
        "太陽が沈みます。","たいようがしずみます。","Mặt trời lặn.","The sun sinks."),
    row("掴む","つかむ","N4","v5m|vt",
        "nắm lấy | giữ lấy | bắt lấy | đạt được | lĩnh hội",
        "to seize | to catch | to grasp | to grip | to grab | to clutch | to hold | to catch hold of | to lay one's hands on | to obtain | to acquire | to get | to win | to capture | to understand | to grasp | to comprehend",
        "1433650",
        "機会を掴みます。","きかいをつかみます。","Tôi nắm lấy cơ hội.","I seize the opportunity."),
    row("飛び出す","とびだす","N4","v5s|vi",
        "nhảy ra | lao ra | bất ngờ xuất hiện | nhô ra | bỏ đi (khỏi nhà) | cắt đứt liên hệ",
        "to jump out | to leap out | to fly out | to run out | to rush out | to bolt out | to appear (suddenly) | to emerge | to come out | to protrude | to project | to jut out | to stick out | to leave (a company, one's hometown, etc.) | to run away (from home) | to cut ties with | to start flying",
        "1485350",
        "車が飛び出します。","くるまがとびだします。","Xe lao ra đột ngột.","A car rushes out suddenly."),
    row("不況","ふきょう","N4","n",
        "suy thoái kinh tế | khủng hoảng kinh tế | sụt giảm",
        "(economic) depression | recession | slump",
        "1491950",
        "不況が続きます。","ふきょうがつづきます。","Suy thoái kinh tế kéo dài.","The recession continues."),
    row("付け加える","つけくわえる","N4","v1|vt",
        "thêm vào | bổ sung | thêm nữa",
        "to add (one thing to another) | to add (a few more words, an explanation, etc.)",
        "1495790",
        "コメントを付け加えます。","コメントをつけくわえます。","Tôi bổ sung bình luận.","I add a comment."),
    row("浮く","うく","N4","v5k|vi",
        "nổi | trôi nổi | vui vẻ | lỏng lẻo | cảm thấy xa cách | có dư",
        "to float | to become merry | to be cheerful | to become loose | to become unsteady | to feel out of it | to be cut off (e.g. from those around you) | to feel out of place | to have (time, money, etc.) left over | to be saved (e.g. money)",
        "1497420",
        "水に浮きます。","みずにうきます。","Tôi nổi trên mặt nước.","I float on water."),
    row("浮かぶ","うかぶ","N4","v5b|vi",
        "nổi lên | lơ lửng | nổi lên bề mặt | xuất hiện | hiện lên trong tâm trí",
        "to float | to be suspended | to rise to the surface | to appear | to emerge | to show up | to loom (up) | to come to mind | to have inspiration",
        "1497430",
        "アイデアが浮かびます。","アイデアがうかびます。","Ý tưởng hiện lên trong đầu.","An idea comes to mind."),
    row("貿易","ぼうえき","N4","n|vs|vi",
        "thương mại quốc tế | buôn bán ngoại thương | xuất nhập khẩu",
        "(foreign) trade | (international) commerce | importing and exporting",
        "1520120",
        "貿易を拡大します。","ぼうえきをかくだいします。","Chúng tôi mở rộng thương mại.","We expand trade."),
    row("利率","りりつ","N4","n",
        "lãi suất",
        "interest rate",
        "1549680",
        "利率が上がります。","りりつがあがります。","Lãi suất tăng.","The interest rate rises."),
    row("立場","たちば","N4","n",
        "lập trường | vị trí | quan điểm | góc nhìn",
        "position | situation | viewpoint | standpoint | point of view",
        "1551710",
        "立場を守ります。","たちばをまもります。","Tôi giữ vững lập trường.","I maintain my position."),
    row("炒める","いためる","N4","v1|vt",
        "xào | rán | chiên xào",
        "to fry | to saute | to stir-fry",
        "1568920",
        "野菜を炒めます。","やさいをいためます。","Tôi xào rau.","I stir-fry vegetables."),
    row("砂漠","さばく","N4","n",
        "sa mạc",
        "desert",
        "1593800",
        "砂漠を横断します。","さばくをおうだんします。","Tôi vượt qua sa mạc.","I cross the desert."),
    row("辞典","じてん","N4","n",
        "từ điển",
        "dictionary | lexicon",
        "1595270",
        "辞典で調べます。","じてんでしらべます。","Tôi tra từ điển.","I look it up in the dictionary."),
    row("文化交流","ぶんかこうりゅう","N4","n",
        "giao lưu văn hóa",
        "cultural exchange",
        "1622150",
        "文化交流を行います。","ぶんかこうりゅうをおこないます。","Chúng tôi thực hiện giao lưu văn hóa.","We conduct cultural exchange."),
    row("銀行口座","ぎんこうこうざ","N4","n",
        "tài khoản ngân hàng",
        "bank account",
        "1933650",
        "銀行口座を開きます。","ぎんこうこうざをひらきます。","Tôi mở tài khoản ngân hàng.","I open a bank account."),
    row("少子化","しょうしか","N4","n",
        "suy giảm tỷ lệ sinh | già hóa dân số do ít trẻ em",
        "declining birth rate | decline in the number of children | sub-replacement fertility",
        "2011350",
        "少子化が進みます。","しょうしかがすすみます。","Tỷ lệ sinh giảm dần.","The birth rate continues to decline."),
    row("高齢化","こうれいか","N4","n|vs|vi",
        "già hóa dân số | lão hóa",
        "aging (of a population) | ageing",
        "2086740",
        "高齢化が進みます。","こうれいかがすすみます。","Già hóa dân số tiến triển.","Population aging progresses."),
    row("喉","こん","N4","n|suf|ctr",
        "cá | đơn vị đếm cá",
        "fish | counter for fish",
        "2248340",
        "三喉の魚がいます。","さんこんのさかながいます。","Có ba con cá.","There are three fish."),
    row("歌詞","うたことば","N4","n",
        "từ ngữ thơ ca | từ dùng trong thơ tanka",
        "word mainly used in tanka | poetical word",
        "2715440",
        "歌詞を作ります。","うたことばをつくります。","Tôi làm lời thơ.","I compose poetical words."),
    row("揚げる","あげる","N4","v1|vt",
        "chiên ngập dầu | phóng (pháo hoa) | kéo cao (cờ) | thả (diều) | cập bờ",
        "to deep-fry | to make deep-fried food | to launch (fireworks, etc.) | to hoist (e.g. a flag) | to (let) fly (e.g. a kite) | to set off | to summon (for geishas, etc.) | to call in | to land (e.g. a boat) | to come ashore | to move (something) onto land | to suck up (water; e.g. a plant) | to absorb | to draw up",
        "2864817",
        "鶏肉を揚げます。","とりにくをあげます。","Tôi chiên thịt gà.","I deep-fry chicken."),
    row("顔","がお","N4","suf",
        "trông giống... | mang vẻ... | có vẻ ngoài... | biểu cảm của...",
        "resembling ... | having the traits or characteristics of ... | -looking | with a ...-like expression | with an air of ...",
        "2868628",
        "得意顔をします。","とくいがおをします。","Tôi mang vẻ đắc ý.","I have a proud look."),
    row("引き起こす","ひきおこす","N4","v5s|vt",
        "gây ra | tạo ra | kéo đứng lên | đỡ dậy",
        "to cause | to induce | to bring about | to provoke | to pull upright | to help up (e.g. a fallen person)",
        "1168880",
        "問題を引き起こします。","もんだいをひきおこします。","Tôi gây ra vấn đề.","I cause a problem."),
    row("観察","かんさつ","N4","n|vs|vt",
        "quan sát | khảo sát | theo dõi",
        "observation | survey | watching",
        "1214900",
        "自然を観察します。","しぜんをかんさつします。","Tôi quan sát thiên nhiên.","I observe nature."),
    row("憲法","けんぽう","N4","n",
        "hiến pháp | quy tắc | quy định",
        "constitution | rules | regulation",
        "1257590",
        "憲法を守ります。","けんぽうをまもります。","Tôi tuân thủ hiến pháp.","I follow the constitution."),
    row("原子力","げんしりょく","N4","n|adj-no",
        "năng lượng nguyên tử | năng lượng hạt nhân",
        "atomic energy | nuclear power",
        "1261750",
        "原子力発電所があります。","げんしりょくはつでんしょがあります。","Có nhà máy điện hạt nhân.","There is a nuclear power plant."),
    row("高速道路","こうそくどうろ","N4","n",
        "đường cao tốc | xa lộ | đường tốc hành",
        "highway | freeway | expressway | motorway",
        "1283720",
        "高速道路を走ります。","こうそくどうろをはしります。","Tôi chạy trên đường cao tốc.","I drive on the expressway."),
    row("証明","しょうめい","N4","n|vs|vt",
        "bằng chứng | chứng minh | chứng nhận | xác minh",
        "proof | testimony | demonstration | verification | certification",
        "1351680",
        "身分を証明します。","みぶんをしょうめいします。","Tôi chứng minh danh tính.","I prove my identity."),
    row("二酸化炭素","にさんかたんそ","N4","n",
        "carbon dioxide | CO2 | khí CO2",
        "carbon dioxide | CO2",
        "1461820",
        "二酸化炭素を削減します。","にさんかたんそをさくげんします。","Chúng tôi giảm CO2.","We reduce carbon dioxide."),
    row("入試","にゅうし","N4","n",
        "kỳ thi tuyển sinh | kỳ thi đầu vào",
        "entrance examination",
        "1466200",
        "入試に合格します。","にゅうしにごうかくします。","Tôi thi đậu kỳ thi tuyển sinh.","I pass the entrance examination."),
    row("不満","ふまん","N4","n|adj-na",
        "sự không hài lòng | bất mãn | phàn nàn | không vui",
        "dissatisfaction | discontent | displeasure | complaint | unhappiness",
        "1494970",
        "不満を言います。","ふまんをいいます。","Tôi bày tỏ sự không hài lòng.","I express dissatisfaction."),
    row("風力","ふうりょく","N4","n|pref",
        "năng lượng gió | sức gió | cấp gió",
        "wind power | force (level on the Beaufort wind speed scale)",
        "1500080",
        "風力発電をします。","ふうりょくはつでんをします。","Chúng tôi phát điện sức gió.","We generate wind power."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
