# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-058.csv -- 23 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-058.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("泣ける","なける","N4","v1|vi",
        "rơi nước mắt | xúc động đến rơi lệ",
        "to shed tears | to be moved to tears",
        "1229850",
        "この映画は泣ける。","このえいがはなける。",
        "Bộ phim này khiến rơi nước mắt.","This movie moves you to tears."),
    row("給食","きゅうしょく","N4","n|vs|vi",
        "bữa ăn trưa (trường/công sở) | cung cấp bữa ăn | dịch vụ bữa trưa",
        "provision of lunch (e.g. at office, school, etc.) | providing a meal | lunch service",
        "1230250",
        "学校の給食。","がっこうのきゅうしょく。",
        "Bữa ăn trưa ở trường.","School lunch."),
    row("給料日","きゅうりょうび","N4","n",
        "ngày lương | ngày nhận lương",
        "payday | pay day",
        "1230370",
        "今日は給料日だ。","きょうはきゅうりょうびだ。",
        "Hôm nay là ngày nhận lương.","Today is payday."),
    row("求職","きゅうしょく","N4","n|vs|vi|adj-no",
        "tìm việc | tìm kiếm việc làm",
        "job hunting | seeking employment",
        "1229450",
        "求職活動をする。","きゅうしょくかつどうをする。",
        "Hoạt động tìm kiếm việc làm.","Do job-hunting activities."),
    row("究極","きゅうきょく","N4","adj-no|n|vs|vi",
        "cuối cùng | tối thượng | sau cùng | rốt cuộc",
        "ultimate | final | last | eventual",
        "1230040",
        "究極の目標。","きゅうきょくのもくひょう。",
        "Mục tiêu tối thượng.","The ultimate goal."),
    row("窮地","きゅうち","N4","n",
        "tình thế khó khăn | bước đường cùng",
        "dilemma | predicament",
        "1230100",
        "窮地に立つ。","きゅうちにたつ。",
        "Rơi vào bước đường cùng.","Be in a predicament."),
    row("窮屈","きゅうくつ","N4","adj-na|n",
        "chật hẹp | chặt | chật chội | trang trọng | cứng nhắc | nghiêm khắc | nghi lễ | bảo thủ | gò bó | khó chịu | ngặt (tài chính)",
        "narrow | tight | cramped | formal | stiff | strict | ceremonious | rigid | constrained | uncomfortable | tight (e.g. finances)",
        "1230080",
        "窮屈な部屋。","きゅうくつなへや。",
        "Căn phòng chật hẹp.","A cramped room."),
    row("泣き声","なきごえ","N4","n",
        "tiếng khóc (ví dụ trẻ em) | tiếng nức nở | tiếng rên rỉ | giọng đầy nước mắt | giọng khóc lóc",
        "cry (e.g. of a baby) | sob | whine | tearful voice | weepy voice",
        "1229730",
        "赤ちゃんの泣き声。","あかちゃんのなきごえ。",
        "Tiếng khóc của em bé.","The cry of a baby."),
    row("去る","さる","N4","v5r|vi|vt|aux-v|adj-pn",
        "rời đi | đi khỏi | trôi qua | trôi qua | cách xa | cho đi | xua đi | ly hôn | (làm) hoàn toàn | tháng/năm trước (ví dụ tháng Tư vừa rồi)",
        "to leave | to go away | to pass | to elapse | to be distant | to send away | to drive off | to divorce | to (do) completely | last ... (e.g. \"last April\")",
        "1231650",
        "故郷を去る。","こきょうをさる。",
        "Rời quê hương.","Leave one's hometown."),
    row("居残り","いのこり","N4","n|vs|vi",
        "làm thêm giờ | bị giữ lại | ở lại sau giờ học",
        "working overtime | detention | being kept in (e.g. after school)",
        "1231780",
        "放課後に居残り。","ほうかごにいのこり。",
        "Ở lại sau giờ học.","Staying after school."),
    row("居眠り","いねむり","N4","n|vs|vi",
        "gật gù (khi ngồi) | ngủ gà ngủ gật",
        "nodding off (while sitting) | dozing",
        "1231890",
        "電車で居眠りする。","でんしゃでいねむりする。",
        "Ngủ gật trên tàu điện.","Doze off on the train."),
    row("居酒屋","いざかや","N4","n",
        "izakaya | quán rượu Nhật phục vụ đồ ăn",
        "izakaya | tavern, bar, etc. that also serves various dishes and snacks",
        "1231800",
        "居酒屋で飲む。","いざかやでのむ。",
        "Uống ở izakaya.","Drink at an izakaya."),
    row("巨大","きょだい","N4","adj-na|n",
        "khổng lồ | to lớn | vô cùng lớn",
        "huge | gigantic | enormous",
        "1232180",
        "巨大な建物。","きょだいなたてもの。",
        "Tòa nhà khổng lồ.","A huge building."),
    row("拒む","こばむ","N4","v5m|vt",
        "từ chối | bác bỏ | khước từ | ngăn cản (khỏi làm) | từ chối (tiếp cận) | chặn",
        "to refuse | to reject | to decline | to prevent (from doing) | to deny (e.g. access) | to block",
        "1232360",
        "要求を拒む。","ようきゅうをこばむ。",
        "Từ chối yêu cầu.","Refuse a demand."),
    row("拒絶","きょぜつ","N4","n|vs|vt",
        "sự từ chối | sự bác bỏ",
        "refusal | rejection",
        "1232390",
        "申し出を拒絶する。","もうしでをきょぜつする。",
        "Từ chối đề nghị.","Reject an offer."),
    row("教養","きょうよう","N4","n",
        "văn hóa (hiểu biết/đánh giá) | học vấn | tu dưỡng | sự tinh tế | sự tao nhã",
        "(understanding or appreciation of) culture | (one's) education | cultivation | sophistication | refinement",
        "1237370",
        "教養のある人。","きょうようのあるひと。",
        "Người có học vấn.","A cultured person."),
    row("旧友","きゅうゆう","N4","n",
        "bạn cũ | bạn thuở xưa",
        "old friend | old pal",
        "1231370",
        "旧友と再会する。","きゅうゆうとさいかいする。",
        "Gặp lại bạn cũ.","Reunite with an old friend."),
    row("旧式","きゅうしき","N4","adj-na|adj-no",
        "kiểu cũ | phong cách cũ",
        "old type | old style",
        "1230790",
        "旧式の機械。","きゅうしきのきかい。",
        "Máy móc kiểu cũ.","Old-fashioned machinery."),
    row("旧暦","きゅうれき","N4","n",
        "âm lịch Nhật Bản (lịch mặt trăng-mặt trời cũ)",
        "Japan's old (lunisolar) calendar",
        "1231430",
        "旧暦で祝う。","きゅうれきでいわう。",
        "Ăn mừng theo âm lịch.","Celebrate by the old calendar."),
    row("旧正月","きゅうしょうがつ","N4","n",
        "Tết âm lịch (đặc biệt Tết Trung Quốc)",
        "lunar New Year (esp. the Chinese New Year)",
        "1230940",
        "旧正月を祝う。","きゅうしょうがつをいわう。",
        "Ăn mừng Tết âm lịch.","Celebrate the lunar New Year."),
    row("求人","きゅうじん","N4","n|vs|vt|vi",
        "tuyển dụng | đề nghị việc làm | vị trí tuyển dụng",
        "recruiting | job offer | job vacancy",
        "1229500",
        "求人広告を出す。","きゅうじんこうこくをだす。",
        "Đăng quảng cáo tuyển dụng.","Post a help-wanted advertisement."),
    row("泣き笑い","なきわらい","N4","n|vs|vi",
        "vừa khóc vừa cười | mỉm cười qua nước mắt | lúc cười lúc khóc | nước mắt và tiếng cười | vui buồn",
        "laughing while crying | smiling through one's tears | (alternately) laughing and crying | tears and laughter | joy and sorrow",
        "1229710",
        "泣き笑いの人生。","なきわらいのじんせい。",
        "Cuộc đời vui buồn lẫn lộn.","A life full of tears and laughter."),
    row("泣き虫","なきむし","N4","n",
        "người hay khóc | kẻ hay mếu máo",
        "crybaby | blubberer",
        "1229740",
        "泣き虫な子。","なきむしなこ。",
        "Đứa trẻ hay khóc.","A crybaby child."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
