# -*- coding: utf-8 -*-
"""Build N2 ready wave 042 — documents, copies, seals, editing, publishing, text structure."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-042.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("情報源","じょうほうげん","n","nguồn thông tin | nguồn tin","source of information | intelligence source","1356430"),
    ("出典","しゅってん","n","nguồn trích dẫn | xuất xứ | nguồn gốc","source (e.g. quotation) | authority","1339790"),
    ("典拠","てんきょ","n","căn cứ | nguồn dẫn | xuất xứ","authority | source | reference","1438070"),
    ("原典","げんてん","n","nguyên bản | văn bản gốc","original (text)","1262150"),
    ("原文","げんぶん","n","nguyên văn | văn bản gốc","original text","1262340"),
    ("原本","げんぽん","n","bản gốc | bản chính | nguồn gốc","original (document) | source","1262360"),
    ("写し","うつし","n","bản sao | bản chép | bản gửi kèm (cc)","copy | duplicate | transcript | cc","1321790"),
    ("副本","ふくほん","n","bản sao | bản phụ","duplicate | copy","1500650"),
    ("正本","せいほん","n","bản chính | bản gốc | bản sao chứng thực","original | authenticated copy","1377970"),
    ("謄本","とうほん","n","bản sao y | bản trích lục (hộ tịch)","certified copy | transcript","1450020"),
    ("抄本","しょうほん","n","bản trích lục | bản tóm tắt","excerpt | abridgment","1349540"),
    ("証書","しょうしょ","n","văn bằng | chứng thư | giấy chứng nhận | khế ước","document | certificate | bond | deed","1351650"),
    ("証文","しょうもん","n","khế ước | giấy nợ | văn tự | hợp đồng","bond | deed | contract","1707050"),
    ("証憑","しょうひょう","n","chứng từ | bằng chứng giao dịch","voucher | documentary evidence","2018130"),
    ("公文書","こうぶんしょ","n","văn bản công | công văn | tài liệu chính thức","official document | archives","1274630"),
    ("私文書","しぶんしょ","n","văn bản tư | tài liệu cá nhân","private document","1658310"),
    ("古文書","こもんじょ","n","tài liệu cổ | văn thư cổ | thư tịch cổ","historical document | old manuscript","1578500"),
    ("親展","しんてん","n|adj-no","mật | chỉ người nhận mở | thư riêng","confidential","1365290"),
    ("帳票","ちょうひょう","n","sổ sách chứng từ | biểu mẫu kế toán","financial records (account books, forms)","2016190"),
    ("名簿","めいぼ","n","danh sách | sổ danh bạ | bảng danh sách","register of names | roster","1531830"),
    ("名鑑","めいかん","n","danh bạ | danh mục | sổ tra cứu","directory | list","1531400"),
    ("書式設定","しょしきせってい","n","định dạng | thiết lập định dạng","formatting","2841146"),
    ("雛形","ひながた","n","mẫu | mô hình thu nhỏ | biểu mẫu | quy cách","model | miniature | sample | prescribed form","1373430"),
    ("草稿","そうこう","n","bản thảo | bản nháp | bản phác","notes | draft | manuscript","1401980"),
    ("推敲","すいこう","n|vs|vt","trau chuốt câu chữ | gọt giũa | chỉnh sửa văn","polishing (writing) | revision | refinement","1371250"),
    ("添削","てんさく","n|vs|vt","sửa bài | chỉnh sửa | soát sửa","correction | looking over","1440850"),
    ("校閲","こうえつ","n|vs|vt","biên duyệt | hiệu đính | soát lỗi","revision | proofreading","1279480"),
    ("査読","さどく","n|vs|vt","bình duyệt | phản biện (bài báo)","peer review | refereeing","1291460"),
    ("監修","かんしゅう","n|vs|vt","giám sát biên tập | chủ biên | tổng đạo diễn","editorial supervision | supervising director","1213710"),
    ("編纂","へんさん","n|vs|vt","biên soạn (từ điển, sử) | biên tập","compilation | editing","1511980"),
    ("著述","ちょじゅつ","n|vs|vt","viết sách | trước tác | tác phẩm","writing | book | literary work","1427120"),
    ("著作","ちょさく","n|vs|vt|vi","sáng tác | trước tác | tác phẩm | viết sách","writing (a book) | (literary) work","1427090"),
    ("口述","こうじゅつ","n|vs|vt|adj-no","đọc cho chép | trình bày miệng | khẩu thuật","dictation | verbal statement","1276310"),
    ("代筆","だいひつ","n|vs|vt","viết hộ | viết thay","writing on someone's behalf","1412160"),
    ("記名","きめい","n|vs|vt|vi","ký tên | ghi tên | đăng ký tên","signature | signing one's name | registration","1223430"),
    ("無記名","むきめい","n","không ký tên | khuyết danh | vô danh","unsigned | unregistered","1672820"),
    ("押印","おういん","n|vs|vt|vi","đóng dấu | điểm chỉ dấu","affixing a seal | putting one's seal","1180480"),
    ("捺印","なついん","n|vs|vi","đóng dấu | dập dấu","affixing a seal | stamping","1459700"),
    ("印鑑","いんかん","n","con dấu | con dấu cá nhân | ấn triện","stamp | seal","1168120"),
    ("実印","じついん","n","con dấu đã đăng ký chính thức","officially registered seal","1320880"),
    ("認印","にんいん","n","con dấu thường | dấu cá nhân chưa đăng ký","private seal | unregistered seal","2019940"),
    ("拇印","ぼいん","n","dấu vân tay | điểm chỉ","thumb print","1567310"),
    ("落款","らっかん","n|vs|vt|vi","triện lạc khoản | chữ ký và dấu (tranh, thư pháp)","signature and seal (on calligraphy, paintings)","1548690"),
    ("記帳","きちょう","n|vs|vt","ghi sổ | vào sổ | ký sổ | ghi chép kế toán","registry | book-keeping | signature","1223320"),
    ("転記","てんき","n|vs|vt","sao chép | chuyển ghi | ghi lại","posting (of notes) | transcription","1704190"),
    ("追記","ついき","n|vs|vt","tái bút | ghi thêm | bổ sung (dữ liệu)","PS | postscript | appending","1661860"),
    ("付記","ふき","n|vs|vt","ghi chú thêm | bổ sung | phụ chú","addition | appendix | note","1496220"),
    ("脚注","きゃくちゅう","n","chú thích cuối trang","footnote","1226850"),
    ("傍注","ぼうちゅう","n","chú thích bên lề | chú giải bên","marginal notes | gloss","1603670"),
    ("頭注","とうちゅう","n","chú thích đầu trang","headnote","1653000"),
    ("欄外","らんがい","n|adj-no","lề (trang) | bên lề","margin","1549360"),
    ("記入欄","きにゅうらん","n","ô điền | mục để điền | ô nhập","blank (to be filled out) | input field","2861345"),
    ("備考","びこう","n","ghi chú | lưu ý | chú thích tham khảo","note (for reference) | remarks","1485670"),
    ("注記","ちゅうき","n|vs|vt","chú thích | chú giải | ghi chú giải thích","annotation | commentary | explanatory note","1426580"),
    ("但し書き","ただしがき","n","điều khoản kèm theo | dòng lưu ý | mục bổ sung","proviso","1596980"),
    ("脚色","きゃくしょく","n|vs|vt","chuyển thể | cải biên | thêm thắt | thổi phồng","dramatization | adaptation | embellishment (of facts)","1226830"),
    ("大意","たいい","n","đại ý | tóm tắt | ý chính | nội dung khái quát","synopsis | summary | gist | outline","1413040"),
    ("骨組み","ほねぐみ","n","khung xương | bộ khung | kết cấu | dàn ý","skeletal frame | framework | outline","1288670"),
    ("体裁","ていさい","n","hình thức | thể thức | bề ngoài | thể diện | lời khách sáo","(outward) appearance | format | appearances","1409480"),
    ("見栄え","みばえ","n|vs|vi","vẻ bắt mắt | trông đẹp | có hình thức","good outward appearance | looking nice","2849579"),
    ("書き出し","かきだし","n","phần mở đầu | câu mở đầu | giấy đòi tiền","beginning (of writing) | opening passage","1343790"),
    ("結び","むすび","n","phần kết | sự liên kết | nút thắt | nắm cơm","ending | conclusion | knot | onigiri","1254610"),
    ("末尾","まつび","n","phần cuối | đoạn kết (văn bản)","end (of a document, paragraph)","1525610"),
    ("冒頭","ぼうとう","n","mở đầu | đoạn đầu | phần mở đầu","beginning | opening | outset","1519860"),
    ("本文","ほんぶん","n","nội dung chính | phần thân (thư) | đoạn này","text (of a book) | body (of a letter)","1584270"),
    ("全文","ぜんぶん","n","toàn văn | toàn bộ nội dung | trọn câu","whole passage | full text","1396180"),
    ("続編","ぞくへん","n","phần tiếp theo | hậu truyện","sequel | continuation","1405860"),
    ("前編","ぜんぺん","n","phần đầu | tập đầu | tiền truyện","first part (of a book, film) | prequel","1596340"),
    ("後編","こうへん","n","phần sau | tập cuối | phần kết","latter part | second half | sequel","1270090"),
    ("完結","かんけつ","n|vs|vi","hoàn thành | kết thúc | hoàn tất","conclusion | completion","1211440"),
    ("増補","ぞうほ","n|vs|vt","bổ sung (sách) | mở rộng | tăng bổ","augmenting | enlarging | supplementing","1771790"),
    ("改訂版","かいていばん","n","bản hiệu đính | bản sửa đổi","revised edition","1201070"),
    ("新装版","しんそうばん","n","bản tái bản (định dạng/bìa mới) | bản đặc biệt","publication in a new format | special edition","2724630"),
    ("復刻","ふっこく","n|vs|vt","tái bản | in lại | phục chế","republication | reissue | reproduction","1500790"),
    ("絶版","ぜっぱん","n|adj-no","hết bản in | ngừng xuất bản","out of print","1386940"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
