# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-053.csv -- 19 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-053.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("終点","しゅうてん","N4","n",
        "điểm cuối | trạm cuối (xe lửa)",
        "terminus | last stop (e.g. train)",
        "1332950",
        "終点で降りる。","しゅうてんでおりる。",
        "Xuống ở điểm cuối.","Get off at the terminus."),
    row("設定","せってい","N4","n|vs|vt",
        "thiết lập | tạo lập | đặt vấn đề | bối cảnh (phim/tiểu thuyết) | cảnh | cài đặt tuỳ chọn | cài đặt tùy thích | cấu hình | thiết lập hệ thống",
        "establishment | creation | posing (a problem) | setting (movie, novel, etc.) | scene | options setting | preference settings | configuration | setup",
        "1386060",
        "設定を変える。","せっていをかえる。",
        "Thay đổi cài đặt.","Change the settings."),
    row("地味","じみ","N4","adj-na|n|adv",
        "giản dị | đơn giản | kín đáo | điềm tĩnh | dè dặt (hành vi/thái độ) | khiêm tốn | yên tĩnh | không nổi bật | khá | một chút",
        "plain | simple | subdued | sober | reserved (behaviour, attitude, etc.) | modest | quiet | unobtrusive | quite | a (little) bit",
        "1421490",
        "地味な服を着る。","じみなふくをきる。",
        "Mặc quần áo giản dị.","Wear plain clothes."),
    row("着替える","きがえる","N4","v1|vt|vi",
        "thay quần áo | thay đồ",
        "to change (one's clothes)",
        "1423170",
        "着替えてから出かける。","きがえてからでかける。",
        "Thay đồ xong rồi đi ra ngoài.","Change clothes before going out."),
    row("抜け道","ぬけみち","N4","n",
        "đường nhỏ | đường vòng | đường phụ | lối đi bí mật | đường tắt | lối thoát | kẽ hở | cách thoát khỏi rắc rối | cái cớ",
        "byway | bypath | byroad | secret path | shortcut | way of escape | loophole | way out (of trouble) | excuse",
        "1599990",
        "抜け道を探す。","ぬけみちをさがす。",
        "Tìm đường tắt.","Look for a shortcut."),
    row("満足","まんぞく","N4","n|adj-na|vs|vt|vi",
        "sự thỏa mãn | sự hài lòng | sự thích thú | đủ | thỏa đáng | vừa đủ | thích hợp | đúng mực | tử tế | thỏa mãn (phương trình)",
        "satisfaction | contentment | gratification | sufficient | satisfactory | enough | adequate | proper | decent | satisfying (an equation)",
        "1526860",
        "満足できる結果。","まんぞくできるけっか。",
        "Kết quả thỏa đáng.","A satisfactory result."),
    row("遠慮","えんりょ","N4","n|vs|vt|vi",
        "e ngại | ràng buộc | kiềm chế | khiêm tốn | rụt rè | do dự | tự kiềm mình | sự khéo léo | lịch tế | chu đáo | từ chối | tránh né | thận trọng | nhìn xa trông rộng",
        "reserve | constraint | restraint | modesty | diffidence | hesitation | holding back | discretion | tact | thoughtfulness | declining | refraining | forethought | foresight",
        "1178450",
        "遠慮なく言ってください。","えんりょなくいってください。",
        "Xin cứ tự nhiên nói.","Please speak without hesitation."),
    row("乗り越える","のりこえる","N4","v1|vi",
        "trèo qua | vượt qua | leo qua (núi) | khắc phục (khó khăn/trở ngại) | vượt qua | vượt qua (bệnh tật/khủng hoảng) | vượt qua (nỗi đau) | vượt trội hơn (người tiền nhiệm) | đuổi kịp",
        "to climb over | to get over | to cross (a mountain) | to overcome (a difficulty, obstacle, etc.) | to surmount | to get through (an illness, crisis, etc.) | to get over (e.g. one's pain) | to surpass (a predecessor) | to overtake",
        "1354770",
        "困難を乗り越える。","こんなんをのりこえる。",
        "Vượt qua khó khăn.","Overcome difficulties."),
    row("そっと","そっと","N4","adv|vs",
        "nhẹ nhàng | khẽ khàng | lặng lẽ | nhẹ nhàng | lén lút | bí mật | trong bí mật | để mặc | để nguyên",
        "softly | gently | quietly | lightly | stealthily | secretly | in secret | to leave alone | to leave as it is",
        "1006810",
        "そっとドアを閉める。","そっとどあをしめる。",
        "Nhẹ nhàng đóng cửa.","Gently close the door."),
    row("ふらふら","ふらふら","N4","adv|adv-to|vs|adj-na",
        "loạng choạng (chân đứng) | run rẩy | chao đảo | lảo đảo | ngã đổ | chóng mặt | ngây ngất | dao động | không vững | không quyết đoán | lang thang vô định | vô thức | theo ý thích | không suy nghĩ",
        "unsteadily (e.g. on one's feet) | shakily | staggering | tottering | reeling | dizzily | giddily | wavering (in one's mind) | unsteadily | indecisively | aimlessly | unconsciously | whimsically | without thinking",
        "1011060",
        "疲れてふらふらする。","つかれてふらふらする。",
        "Mệt mỏi đến mức loạng choạng.","Staggering from exhaustion."),
    row("訴える","うったえる","N4","v1|vt",
        "nêu lên | thu hút sự chú ý | kêu gọi (lý trí/cảm xúc) | tác động vào cảm xúc | đánh vào tình cảm | kêu ca | kiện (ai đó) | đưa ra tòa án | viện đến (vũ lực)",
        "to raise | to bring to (someone's attention) | to appeal to (reason, emotions, etc.) | to work on (one's emotions) | to play on (one's sympathies) | to complain | to sue (a person) | to take someone to court | to resort to (e.g. arms, violence)",
        "1397720",
        "裁判所に訴える。","さいばんしょにうったえる。",
        "Đưa ra tòa án.","Take to court."),
    row("地盤","じばん","N4","n",
        "nền đất | vỏ trái đất | tầng đất (sỏi/sông) | móng (tòa nhà) | nền tảng | khu vực bầu cử | cơ sở quyền lực | sự ủng hộ (bầu cử) | chỗ đứng | điểm tựa",
        "ground | crust (earth) | bed (gravel, river, etc.) | foundation (building, etc.) | base | constituency | power base | support (electoral) | footing | foothold",
        "1421420",
        "地盤が固い。","じばんがかたい。",
        "Nền đất vững chắc.","The ground is solid."),
    row("抑える","おさえる","N4","v1|vt",
        "giữ trong giới hạn (chi tiêu) | kiềm chế (cảm xúc) | kiểm soát | hạn chế | kìm giữ | ngăn chặn (kẻ thù) | kiểm tra | hạn chế | chứa đựng | dập tắt | chế phục | đè bẹp | kìm nén",
        "to keep within limits (e.g. spending) | to restrain (e.g. emotions) | to control | to curb | to hold in check | to hold back (e.g. an enemy) | to check | to curb | to contain | to quell | to subdue | to suppress | to repress",
        "2836285",
        "感情を抑える。","かんじょうをおさえる。",
        "Kiềm chế cảm xúc.","Restrain one's emotions."),
    row("捉える","とらえる","N4","v1|vt",
        "bắt | nắm bắt | chộp lấy | bắt giữ | tóm lấy | nắm chặt | nắm vững (ý nghĩa) | cảm nhận | ghi lại (đặc điểm) | cuốn hút | làm xúc động",
        "to catch | to capture | to seize | to arrest | to grab | to catch hold of | to grasp (e.g. meaning) | to perceive | to capture (e.g. features) | to captivate | to move (one's heart)",
        "1598960",
        "チャンスを捉える。","ちゃんすをとらえる。",
        "Nắm bắt cơ hội.","Seize the opportunity."),
    row("不器用","ぶきよう","N4","adj-na|n",
        "vụng về | lóng ngóng | kém khéo léo | thiếu năng lực | không khéo | cẩu thả | ngượng ngùng (giao tiếp) | thiếu thanh lịch | thiếu lịch lãm",
        "clumsy | awkward | unskillful | incompetent | inept | bungling | (socially) awkward | gawky | gauche",
        "1491790",
        "手先が不器用だ。","てさきがぶきようだ。",
        "Khéo tay thì ít mà vụng thì nhiều.","One is clumsy with one's hands."),
    row("不器用","ぶきっちょ","N4","adj-na|n",
        "vụng về | lóng ngóng | kém khéo léo | thiếu năng lực | không khéo | cẩu thả | ngượng ngùng (giao tiếp) | thiếu thanh lịch | thiếu lịch lãm",
        "clumsy | awkward | unskillful | incompetent | inept | bungling | (socially) awkward | gawky | gauche",
        "1632530",
        "ぶきっちょな人。","ぶきっちょなひと。",
        "Người vụng về.","A clumsy person."),
    row("器用","きよう","N4","adj-na|n",
        "khéo léo | lành nghề | khéo tay | tài tình | linh hoạt | nhanh nhẹn | khéo xử | thuận tiện | thông minh | lanh lợi | sáng tạo",
        "skillful | skilful | adroit | dexterous | dextrous | deft | nimble | handy | clever | shrewd | ingenious",
        "1218960",
        "手先が器用だ。","てさきがきようだ。",
        "Khéo léo với đôi tay.","Dexterous with one's hands."),
    row("畳む","たたむ","N4","v5m|vt",
        "gấp (quần áo, ô dù) | đóng cửa (cửa hàng/kinh doanh) | dọn đi",
        "to fold (clothes, umbrella) | to close (a shop, business) | to vacate",
        "1356780",
        "洗濯物を畳む。","せんたくものをたたむ。",
        "Gấp quần áo vừa giặt.","Fold the laundry."),
    row("賑やか","にぎやか","N4","adj-na",
        "nhộn nhịp | bận rộn | đông đúc | sôi động | thịnh vượng | phồn thịnh | sôi nổi (tiệc tùng/giọng nói) | ồn ào | náo nhiệt | vui vẻ | vui tươi",
        "bustling | busy | crowded | lively | prosperous | thriving | lively (party, voices, etc.) | loud | noisy | merry | cheerful",
        "1463480",
        "賑やかな街。","にぎやかなまち。",
        "Khu phố nhộn nhịp.","A bustling street."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
