# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-013.csv — 30 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-013.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("ひょっとして","ひょっとして","N4","exp",
        "biết đâu | có thể | phòng trường hợp | tình cờ mà",
        "by any chance | (should) it happen (that) | by some chance",
        "2096190",
        "ひょっとして知っていますか。","ひょっとしてしっていますか。","Biết đâu bạn có biết không?","By any chance, do you know?"),
    row("提出","ていしゅつ","N4","n|vs|vt",
        "nộp (tài liệu) | đệ trình (đơn, báo cáo) | xuất trình (bằng chứng) | trình bày (dự luật) | nộp hồ sơ",
        "presentation (of documents) | submission (of an application, report, etc.) | production (e.g. of evidence) | introduction (e.g. of a bill) | filing | turning in",
        "1436410",
        "書類を提出します。","しょるいをていしゅつします。","Tôi nộp tài liệu.","I submit the documents."),
    row("伝統","でんとう","N4","n",
        "truyền thống | tập tục",
        "tradition | convention",
        "1442260",
        "伝統を守ります。","でんとうをまもります。","Tôi giữ gìn truyền thống.","I preserve tradition."),
    row("電気代","でんきだい","N4","n",
        "hóa đơn điện | tiền điện",
        "electricity bill | electric bill",
        "1443100",
        "電気代を払います。","でんきだいをはらいます。","Tôi trả tiền điện.","I pay the electricity bill."),
    row("入院","にゅういん","N4","n|vs|vi",
        "nhập viện | vào viện",
        "hospitalization | hospitalisation",
        "1465720",
        "明日入院します。","あしたにゅういんします。","Ngày mai tôi nhập viện.","I will be hospitalized tomorrow."),
    row("必要性","ひつようせい","N4","n",
        "sự cần thiết | nhu cầu",
        "necessity | need",
        "1487730",
        "必要性を感じます。","ひつようせいをかんじます。","Tôi cảm thấy sự cần thiết.","I feel the necessity."),
    row("評価","ひょうか","N4","n|vs|vt",
        "định giá | thẩm định | đánh giá | nhận xét | ước tính | xếp hạng | ghi nhận | khen ngợi",
        "valuation | appraisal | evaluation | assessment | estimation | rating | judging | appreciation | recognition | praising",
        "1490010",
        "評価を受けます。","ひょうかをうけます。","Tôi nhận được đánh giá.","I receive an evaluation."),
    row("付き合い","つきあい","N4","n",
        "giao thiệp | giao lưu xã hội | giao tiếp | sự gắn bó",
        "association | socializing | socialising | fellowship",
        "1495640",
        "付き合いを大切にします。","つきあいをたいせつにします。","Tôi trân trọng mối quan hệ giao lưu.","I value social relationships."),
    row("利益","りえき","N4","n|vs|vt",
        "lợi nhuận | thu được | lợi ích | lợi thế | điều tốt | lợi ích (ví dụ xã hội) | ân sủng (của Thần, Phật) | phúc lành",
        "profit | gains | benefit | advantage | good | interests (e.g. of society) | grace (of God, Buddha, etc.) | blessing | miracle",
        "1549470",
        "利益を上げます。","りえきをあげます。","Tôi tăng lợi nhuận.","I increase profit."),
    row("話し合う","はなしあう","N4","v5u|vt",
        "thảo luận | bàn bạc cùng nhau",
        "to discuss | to talk together",
        "1562310",
        "問題について話し合います。","もんだいについてはなしあいます。","Chúng tôi thảo luận về vấn đề.","We discuss the problem."),
    row("糸","し","N4","n|num",
        "chỉ | phần mười nghìn (đơn vị đo lường)",
        "thread | 0.0001 | one ten-thousandth",
        "2127930",
        "糸を使います。","いとをつかいます。","Tôi dùng chỉ.","I use thread."),
    row("夜中","やちゅう","N4","n|adv",
        "ban đêm | trong đêm tối",
        "during the night | at night",
        "1584830",
        "夜中に目が覚めます。","やちゅうにめがさめます。","Tôi thức dậy ban đêm.","I wake up in the middle of the night."),
    row("打ち合わせ","うちあわせ","N4","n|vs|vt",
        "cuộc họp chuẩn bị | buổi thuyết trình ngắn | sắp xếp trước | chồng lên nhau (áo) | làm cho khớp chính xác",
        "(preparatory) meeting | briefing session | (making) advance arrangements | overlap (of a coat, etc.) | making something match exactly",
        "1588140",
        "打ち合わせをします。","うちあわせをします。","Chúng tôi họp chuẩn bị.","We have a preparatory meeting."),
    row("人気","じんき","N4","n",
        "tâm trạng chủ đạo của địa phương | khí hậu tình cảm của khu vực",
        "prevailing mood of a locality | emotional climate of a district",
        "2153960",
        "地域の人気があります。","ちいきのじんきがあります。","Có tâm trạng của địa phương.","There is a mood of the district."),
    row("付き合う","つきあう","N4","v5u|vi",
        "giao lưu với | kết giao với | hẹn hò với | ổn định với ai | hòa thuận với | đi cùng | thỏa hiệp",
        "to associate with | to keep company with | to go out with | to go steady with | to get on with | to accompany someone | to compromise",
        "1597790",
        "友人と付き合います。","ゆうじんとつきあいます。","Tôi giao lưu với bạn bè.","I associate with my friend."),
    row("乗り換え","のりかえ","N4","n|vs|vi",
        "chuyển xe (tàu, xe buýt) | thay đổi | kết nối | chuyển đổi (sang ý thức hệ, đảng, hệ thống khác) | trao đổi chéo nhiễm sắc thể",
        "transfer (trains, buses, etc.) | change | connection | switch (to another ideology, party, system, method, etc.) | chromosomal crossover",
        "1600460",
        "電車を乗り換えます。","でんしゃをのりかえます。","Tôi chuyển tàu.","I transfer trains."),
    row("ひっくり返す","ひっくりかえす","N4","v5s|vt",
        "lật qua | lật ngược | lật lên | lật ngược ra | làm đổ | làm lật | bác bỏ (ví dụ quyết định) | đảo ngược",
        "to turn over | to turn upside down | to turn up | to turn inside out | to knock over | to tip over | to overturn (e.g. a decision) | to reverse",
        "1601870",
        "決定をひっくり返します。","けっていをひっくりかえします。","Tôi bác bỏ quyết định.","I overturn the decision."),
    row("分かれる","わかれる","N4","v1|vi",
        "phân nhánh | rẽ đôi | phân kỳ | tách ra | chia tách | chia cắt | phân tán | rải rác",
        "to branch | to fork | to diverge | to separate | to split | to divide | to disperse | to scatter",
        "1606600",
        "道が分かれます。","みちがわかれます。","Con đường phân nhánh.","The road branches."),
    row("注文書","ちゅうもんしょ","N4","n",
        "đơn đặt hàng (bằng văn bản) | phiếu đặt hàng",
        "written order | order form",
        "1942610",
        "注文書を送ります。","ちゅうもんしょをおくります。","Tôi gửi đơn đặt hàng.","I send the order form."),
    row("チェックリスト","チェックリスト","N4","n",
        "danh sách kiểm tra",
        "checklist",
        "2017000",
        "チェックリストを作ります。","チェックリストをつくります。","Tôi tạo danh sách kiểm tra.","I make a checklist."),
    row("食堂","じきどう","N4","n",
        "phòng ăn (tại chùa) | đại sảnh ăn uống (tại chùa)",
        "dining hall (at a temple)",
        "2253570",
        "食堂で食事します。","じきどうでしょくじします。","Tôi dùng bữa tại phòng ăn chùa.","I eat at the temple dining hall."),
    row("スマートフォン","スマートフォン","N4","n",
        "điện thoại thông minh",
        "smartphone | smart phone",
        "2304550",
        "スマートフォンを使います。","スマートフォンをつかいます。","Tôi dùng điện thoại thông minh.","I use a smartphone."),
    row("土","に","N4","n",
        "đất (đặc biệt là đất đỏ)",
        "soil (esp. reddish soil)",
        "2423330",
        "赤い土があります。","あかいにがあります。","Có đất đỏ.","There is reddish soil."),
    row("いっそ","いっそ","N4","adv",
        "thà | hơn thế | thích hơn | không bằng | nên hơn là | ngược lại",
        "rather | sooner | preferably | might as well | just | on the contrary | if anything",
        "2613280",
        "いっそ諦めます。","いっそあきらめます。","Thà là từ bỏ.","I might as well give up."),
    row("筋","きん","N4","n",
        "cơ bắp | cơ",
        "muscle",
        "2657060",
        "筋を鍛えます。","きんをきたえます。","Tôi rèn luyện cơ bắp.","I train my muscles."),
    row("叩く","はたく","N4","v5k|vt",
        "phủi bụi | lau bụi | tát | đánh (bằng lòng bàn tay) | tiêu hết tiền",
        "to dust | to remove dust | to slap | to hit (with the palm) | to use up money",
        "2829135",
        "机を叩きます。","つくえをはたきます。","Tôi phủi bụi bàn.","I dust the desk."),
    row("石","せき","N4","ctr",
        "đếm đá quý trong đồng hồ | đếm transistor, diode trong sản phẩm điện tử",
        "counter for jewels in a watch | counter for transistors, diodes, etc. in an electronic product",
        "2843288"),
    row("熱","ねち","N4","n",
        "sốt | cơn sốt",
        "fever",
        "2843495",
        "熱があります。","ねちがあります。","Tôi bị sốt.","I have a fever."),
    row("温める","ぬくめる","N4","v1|vt",
        "làm ấm | hâm nóng",
        "to warm (up) | to heat (up)",
        "2853516",
        "体を温めます。","からだをぬくめます。","Tôi làm ấm cơ thể.","I warm up my body."),
    row("背","そびら","N4","n",
        "lưng | mặt sau (của cơ thể)",
        "back (of the body)",
        "2854021",
        "背を向けます。","そびらをむけます。","Tôi quay lưng lại.","I turn my back."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
