# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-015.csv — 50 rows (Wave 7 pool batch)."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-015.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("音楽会","おんがくかい","N4","n",
        "buổi hòa nhạc | buổi biểu diễn âm nhạc",
        "concert | recital",
        "1183740",
        "音楽会に行きます。","おんがくかいにいきます。","Tôi đi nghe hòa nhạc.","I go to a concert."),
    row("外交","がいこう","N4","n",
        "ngoại giao | bán hàng (ví dụ gõ cửa từng nhà) | vận động",
        "diplomacy | selling (e.g. door-to-door) | canvassing",
        "1203540",
        "外交が大切です。","がいこうがたいせつです。","Ngoại giao rất quan trọng.","Diplomacy is important."),
    row("楽器","がっき","N4","n|adj-no",
        "nhạc cụ",
        "musical instrument",
        "1207340",
        "楽器を弾きます。","がっきをひきます。","Tôi chơi nhạc cụ.","I play a musical instrument."),
    row("寒気","さむけ","N4","n",
        "cảm giác lạnh | ớn lạnh | run rẩy",
        "chill | the shivers | shivering fit",
        "1210410",
        "寒気がします。","さむけがします。","Tôi cảm thấy ớn lạnh.","I feel a chill."),
    row("甘える","あまえる","N4","v1|vi",
        "nhõng nhẽo | cầu xin sự nuông chiều | lợi dụng (lòng tốt của ai) | dựa dẫm vào | đòi hỏi sự chiếu cố",
        "to behave like a spoiled child | to fawn on | to take advantage of | to presume upon (e.g. another's benevolence) | to depend on",
        "1213440",
        "子供が親に甘えます。","こどもがおやにあまえます。","Đứa trẻ nhõng nhẽo với cha mẹ.","The child fawns on the parents."),
    row("気に入る","きにいる","N4","exp|v5r",
        "thích | hài lòng với | vui thích | có cảm tình | hợp ý",
        "to like | to be pleased with | to be delighted with | to take a liking to | to suit one's fancy",
        "1221740",
        "このデザインが気に入ります。","このデザインがきにいります。","Tôi thích thiết kế này.","I like this design."),
    row("給与","きゅうよ","N4","n|vs|vt",
        "lương | tiền lương | trợ cấp | cấp phát | cung cấp",
        "pay | salary | wages | allowance | grant | supply | providing with",
        "1230350",
        "給与が上がります。","きゅうよがあがります。","Lương tăng.","The salary goes up."),
    row("教授","きょうじゅ","N4","n|vs|vt",
        "giáo sư | giảng dạy | chỉ dẫn",
        "professor | teaching | instruction",
        "1237160",
        "教授に質問します。","きょうじゅにしつもんします。","Tôi hỏi giáo sư.","I ask the professor."),
    row("狭まる","せばまる","N4","v5r|vi",
        "thu hẹp lại | co lại",
        "to narrow | to contract",
        "1237690",
        "道が狭まります。","みちがせばまります。","Con đường thu hẹp lại.","The road narrows."),
    row("後半","こうはん","N4","n",
        "nửa sau | nửa cuối",
        "second half | latter half",
        "1270040",
        "後半に点を取ります。","こうはんにてんをとります。","Tôi ghi bàn trong nửa sau.","I score in the second half."),
    row("合意","ごうい","N4","n|vs|vi",
        "thỏa thuận | đồng ý | hiểu biết lẫn nhau | nhất trí | đồng thuận",
        "(coming to an) agreement | consent | mutual understanding | accord | consensus",
        "1284550",
        "合意に達します。","ごういにたっします。","Chúng tôi đạt được thỏa thuận.","We reach an agreement."),
    row("時刻表","じこくひょう","N4","n",
        "thời gian biểu | lịch trình",
        "timetable | schedule",
        "1316230",
        "時刻表を確認します。","じこくひょうをかくにんします。","Tôi kiểm tra thời gian biểu.","I check the timetable."),
    row("取り消す","とりけす","N4","v5s|vt",
        "hủy bỏ | rút lại | thu hồi | lấy lại (lời nói) | bãi bỏ",
        "to cancel | to withdraw | to retract | to take back (words, etc.) | to revoke",
        "1326790",
        "予約を取り消します。","よやくをとりけします。","Tôi hủy đặt chỗ.","I cancel the reservation."),
    row("重要性","じゅうようせい","N4","n",
        "tầm quan trọng | sự trọng yếu",
        "importance | gravity",
        "1336850",
        "重要性を理解します。","じゅうようせいをりかいします。","Tôi hiểu tầm quan trọng.","I understand the importance."),
    row("縮む","ちぢむ","N4","v5m|vi",
        "co rút | thu nhỏ | thu hẹp kích thước",
        "to shrink | to contract | to diminish (in size)",
        "1337560",
        "服が縮みます。","ふくがちぢみます。","Quần áo co rút.","The clothes shrink."),
    row("申し出る","もうしでる","N4","v1|vt",
        "đề nghị | đề xuất | gợi ý | đưa ra | yêu cầu | xin ứng tuyển | báo cáo | thông báo",
        "to offer | to propose | to suggest | to put forward | to request | to ask (for) | to apply (for) | to report (to) | to notify",
        "1362930",
        "協力を申し出ます。","きょうりょくをもうしでます。","Tôi đề nghị hợp tác.","I offer to cooperate."),
    row("損失","そんしつ","N4","n",
        "tổn thất | thiệt hại (tài sản, lợi nhuận)",
        "loss (of assets, profit, etc.)",
        "1406750",
        "損失を出します。","そんしつをだします。","Chúng tôi chịu tổn thất.","We incur a loss."),
    row("打つ","ぶつ","N4","v5t|vt",
        "đánh (ai đó) | đập | gây thương tích | phát biểu (bài diễn văn) | đánh bạc",
        "to hit (someone) | to strike | to beat | to make (a speech) | to give (an address) | to gamble",
        "1408815",
        "ボールを打ちます。","ボールをうちます。","Tôi đánh bóng.","I hit the ball."),
    row("体育館","たいいくかん","N4","n",
        "phòng thể dục | nhà thi đấu",
        "gymnasium",
        "1409230",
        "体育館で運動します。","たいいくかんでうんどうします。","Tôi tập thể dục trong phòng thi đấu.","I exercise in the gymnasium."),
    row("配慮","はいりょ","N4","n|vs|vt|vi",
        "sự quan tâm | sự chu đáo | sự chú ý | sự sắp xếp | sự chăm sóc",
        "consideration | concern | attention | thoughtfulness | making arrangements | care | trouble",
        "1473210",
        "配慮をします。","はいりょをします。","Tôi thể hiện sự quan tâm.","I show consideration."),
    row("友情","ゆうじょう","N4","n",
        "tình bạn | tình đồng chí | tinh thần đồng đội",
        "friendship | fellowship | camaraderie",
        "1540130",
        "友情を大切にします。","ゆうじょうをたいせつにします。","Tôi trân trọng tình bạn.","I value friendship."),
    row("打ち明ける","うちあける","N4","v1|vt",
        "thổ lộ | tiết lộ | chia sẻ thật lòng | nói thẳng | mở lòng",
        "to confide | to reveal | to disclose | to lay bare | to speak frankly | to open (one's heart)",
        "1588130",
        "秘密を打ち明けます。","ひみつをうちあけます。","Tôi thổ lộ bí mật.","I confide a secret."),
    row("徐々に","じょじょに","N4","adv",
        "dần dần | từ từ | từng bước một | theo từng bước",
        "gradually | steadily | slowly | little by little | step by step | by degrees",
        "1595480",
        "徐々に上達します。","じょじょにじょうたつします。","Tôi tiến bộ dần dần.","I improve gradually."),
    row("きちんと","きちんと","N4","adv|vs",
        "đúng cách | chính xác | gọn gàng | ngăn nắp | đều đặn",
        "properly | accurately | exactly | precisely | regularly | neatly | tidily | orderly",
        "1003400",
        "きちんと整理します。","きちんとせいりします。","Tôi sắp xếp gọn gàng.","I organize neatly."),
    row("すっかり","すっかり","N4","adv|adv-to",
        "hoàn toàn | tất cả | hoàn hảo | triệt để",
        "all | completely | totally | entirely | thoroughly",
        "1006110",
        "すっかり忘れます。","すっかりわすれます。","Tôi hoàn toàn quên mất.","I completely forget."),
    row("アップロード","アップロード","N4","n|vs|vt",
        "tải lên",
        "upload",
        "1016710",
        "ファイルをアップロードします。","ファイルをアップロードします。","Tôi tải tệp lên.","I upload a file."),
    row("リサイクル","リサイクル","N4","n|vs|vt",
        "tái chế",
        "recycling",
        "1141350",
        "リサイクルをします。","リサイクルをします。","Tôi tái chế.","I recycle."),
    row("リスク","リスク","N4","n",
        "rủi ro",
        "risk",
        "1141440",
        "リスクを減らします。","リスクをへらします。","Tôi giảm rủi ro.","I reduce risk."),
    row("ロボット","ロボット","N4","n",
        "robot | con rối | bù nhìn | hư vị",
        "robot | (mere) puppet | pawn | figurehead",
        "1147870",
        "ロボットが動きます。","ロボットがうごきます。","Robot cử động.","The robot moves."),
    row("案外","あんがい","N4","adv|adv-to|adj-na",
        "bất ngờ | ngoài dự đoán | không ngờ | đáng ngạc nhiên",
        "unexpectedly | surprisingly | unexpected | unanticipated | unforeseen | surprising",
        "1154820",
        "案外簡単です。","あんがいかんたんです。","Không ngờ lại dễ vậy.","It is unexpectedly easy."),
    row("援助","えんじょ","N4","n|vs|vt",
        "viện trợ | hỗ trợ | giúp đỡ",
        "assistance | aid | support",
        "1176660",
        "援助をします。","えんじょをします。","Tôi viện trợ.","I provide assistance."),
    row("汚れる","けがれる","N4","v1|vi",
        "bị ô uế | bị hủy hoại | bị ô nhiễm | bị vấy bẩn",
        "to be violated | to be corrupted | to be polluted | to be stained",
        "1179000",
        "心が汚れます。","こころがけがれます。","Tâm hồn bị ô uế.","The heart becomes stained."),
    row("汚染","おせん","N4","n|vs|vt|vi",
        "ô nhiễm | nhiễm bẩn",
        "pollution | contamination",
        "1179040",
        "水質汚染が問題です。","すいしつおせんがもんだいです。","Ô nhiễm nguồn nước là vấn đề.","Water pollution is a problem."),
    row("化学","かがく","N4","n",
        "hóa học",
        "chemistry",
        "1186760",
        "化学を学びます。","かがくをまなびます。","Tôi học hóa học.","I study chemistry."),
    row("いつの間にか","いつのまにか","N4","adv",
        "lúc nào không hay | trước khi biết | không biết từ lúc nào | trong vô thức",
        "before one knows | before one becomes aware of | unnoticed | unawares",
        "1188850",
        "いつの間にか眠ります。","いつのまにかねむります。","Tôi ngủ lúc nào không hay.","I fall asleep without realizing it."),
    row("価格","かかく","N4","n",
        "giá cả | giá trị | chi phí",
        "price | value | cost",
        "1189500",
        "価格を確認します。","かかくをかくにんします。","Tôi kiểm tra giá cả.","I check the price."),
    row("改めて","あらためて","N4","adv",
        "một lần nữa | lại | làm lại | chính thức | đặc biệt | cố ý",
        "another time | again | over again | once again | anew | formally | especially | intentionally | deliberately",
        "1200740",
        "改めて確認します。","あらためてかくにんします。","Tôi xác nhận lại một lần nữa.","I confirm again."),
    row("格差","かくさ","N4","n",
        "chênh lệch | cách biệt | khoảng cách (chất lượng, thu nhập)",
        "qualitative difference | disparity | gap",
        "1205340",
        "格差が広がります。","かくさがひろがります。","Khoảng cách chênh lệch mở rộng.","The gap widens."),
    row("額","がく","N4","n|n-suf",
        "khung tranh | bức tranh có khung | số tiền | tổng số",
        "(picture) frame | framed picture | amount (esp. of money) | sum",
        "1207500",
        "多額を支払います。","たがくをしはらいます。","Tôi trả số tiền lớn.","I pay a large sum."),
    row("管理","かんり","N4","n|vs|vt",
        "quản lý | kiểm soát (ví dụ kinh doanh)",
        "control | management (e.g. of a business)",
        "1214200",
        "データを管理します。","データをかんりします。","Tôi quản lý dữ liệu.","I manage data."),
    row("期待","きたい","N4","n|vs|vt|vi|adj-no",
        "kỳ vọng | mong đợi | hy vọng | đầy hứa hẹn | triển vọng",
        "expectation | anticipation | hope | promising | rising | up-and-coming",
        "1220570",
        "期待に応えます。","きたいにこたえます。","Tôi đáp ứng kỳ vọng.","I meet expectations."),
    row("議員","ぎいん","N4","n",
        "nghị sĩ | thành viên quốc hội | thành viên nghị viện",
        "member of an assembly | member of the Diet | member of parliament | member of Congress",
        "1226020",
        "議員に選ばれます。","ぎいんにえらばれます。","Tôi được bầu làm nghị sĩ.","I am elected as a member of parliament."),
    row("供給","きょうきゅう","N4","n|vs|vt",
        "cung cấp | cung ứng",
        "supply | provision",
        "1233630",
        "電力を供給します。","でんりょくをきょうきゅうします。","Chúng tôi cung cấp điện.","We supply electricity."),
    row("叫ぶ","さけぶ","N4","v5b|vi",
        "la hét | kêu | hét | thét | hô to | kêu gọi | vận động | phản đối | kêu cứu",
        "to shout | to cry (out) | to scream | to shriek | to yell | to exclaim | to clamor (for or against) | to advocate | to insist | to protest | to appeal",
        "1235910",
        "助けを叫びます。","たすけをさけびます。","Tôi kêu cứu.","I shout for help."),
    row("恐ろしい","おそろしい","N4","adj-i",
        "kinh khủng | đáng sợ | hãi hùng | đáng kinh ngạc | phi thường",
        "terrible | dreadful | terrifying | frightening | surprising | startling | tremendous | amazing",
        "1236690",
        "恐ろしい夢を見ます。","おそろしいゆめをみます。","Tôi thấy giấc mơ đáng sợ.","I have a frightening dream."),
    row("繰り返す","くりかえす","N4","v5s|vt|vi",
        "lặp lại | làm lại từ đầu",
        "to repeat | to do over again",
        "1247030",
        "間違いを繰り返します。","まちがいをくりかえします。","Tôi lặp lại lỗi lầm.","I repeat the mistake."),
    row("更に","さらに","N4","adv|conj",
        "hơn nữa | càng thêm | ngoài ra | hơn bao giờ hết",
        "furthermore | again | after all | more and more | moreover | even more",
        "1279310",
        "更に努力します。","さらにどりょくします。","Tôi cố gắng hơn nữa.","I make even more effort."),
    row("国会","こっかい","N4","n",
        "Quốc hội Nhật Bản | nghị viện | hội đồng lập pháp",
        "National Diet | legislative assembly of Japan (1947-) | Imperial Diet | legislative assembly of Japan (1889-1947) | legislative assembly | parliament | congress",
        "1286240",
        "国会で議論します。","こっかいでぎろんします。","Người ta tranh luận trong Quốc hội.","They debate in the National Diet."),
    row("参考","さんこう","N4","n",
        "tham khảo | tư vấn",
        "reference | consultation",
        "1302280",
        "参考にします。","さんこうにします。","Tôi dùng làm tham khảo.","I use it as reference."),
    row("習慣","しゅうかん","N4","n",
        "thói quen | tập quán xã hội | thực hành | phong tục | truyền thống",
        "habit | (social) custom | practice | convention | tradition",
        "1333090",
        "良い習慣をつけます。","よいしゅうかんをつけます。","Tôi tạo thói quen tốt.","I form a good habit."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
