# -*- coding: utf-8 -*-
"""Build N3 ready wave 058 — 69 freshly-curated N3 body/health/medical + sensation nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-058.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("脈","みゃく","n","mạch | nhịp mạch | mạch (núi) | hy vọng","pulse | vein | chain (of mountains) | hope","1528440"),
    ("鼓動","こどう","n|vs|vi","nhịp đập (tim) | đập thình thịch","beat | palpitation | throbbing","1268000"),
    ("器官","きかん","n","cơ quan (cơ thể)","organ","1218910"),
    ("貧血","ひんけつ","n","thiếu máu","anemia","1490800"),
    ("高熱","こうねつ","n","sốt cao | nhiệt độ cao","high fever | intense heat","1283880"),
    ("微熱","びねつ","n","sốt nhẹ","slight fever","1486130"),
    ("痛み","いたみ","n","cơn đau | sự đau đớn | hư hỏng | đau buồn","pain | ache | grief | damage","1587300"),
    ("腫れ","はれ","n","sưng | chỗ sưng | mụn nhọt","swelling | boil","1952290"),
    ("炎症","えんしょう","n","viêm | chứng viêm | viêm nhiễm","inflammation | irritation","1177100"),
    ("持病","じびょう","n","bệnh mãn tính | bệnh kinh niên | tật xấu","chronic disease | old complaint | bad habit","1315830"),
    ("慢性","まんせい","adj-no|n","mãn tính | kinh niên","chronic (illness)","1526640"),
    ("急性","きゅうせい","adj-no|n","cấp tính","acute (illness)","1228820"),
    ("障害","しょうがい","n|vs|vt","trở ngại | chướng ngại | khuyết tật | rối loạn","obstacle | hindrance | disorder | disability","1352060"),
    ("体質","たいしつ","n","thể chất | cơ địa | bản chất (tổ chức)","constitution (physical) | predisposition | character","1409520"),
    ("抵抗力","ていこうりょく","n","sức đề kháng | sức kháng cự","(power of) resistance","1759090"),
    ("握力","あくりょく","n","lực nắm tay | lực bóp","grip strength","1152750"),
    ("視覚","しかく","n","thị giác","(sense of) sight | vision","1312010"),
    ("聴覚","ちょうかく","n","thính giác","(sense of) hearing","1428880"),
    ("触覚","しょっかく","n","xúc giác","sense of touch | tactile","1358030"),
    ("気配","けはい","n","dấu hiệu | hơi hướng | cảm giác | xu thế (thị trường)","indication | sign | hint | sensation","1222510"),
    ("痕跡","こんせき","n","dấu vết | vết tích | bằng chứng","trace | vestige | mark | evidence","1290580"),
    ("名残","なごり","n","tàn dư | dấu vết | lưu luyến (chia tay)","remains | vestiges | (the sorrow of) parting","1531530"),
    ("余韻","よいん","n","âm vang còn đọng | dư vị | dư âm","reverberation | lingering memory | aftertaste","1543930"),
    ("反響","はんきょう","n|vs|vi","tiếng vọng | phản hồi | tiếng vang | dư luận","echo | reverberation | response | repercussions","1480310"),
    ("物音","ものおと","n","tiếng động | âm thanh","noise | sound","1502420"),
    ("雑音","ざつおん","n","tạp âm | nhiễu | tiếng ồn | lời ra tiếng vào","noise | interference (radio) | static | gossip","1299280"),
    ("沈黙","ちんもく","n|vs|vi","im lặng | trầm mặc | án binh","silence | being silent | reticence | inaction","1431810"),
    ("無言","むごん","n|adj-no","không lời | lặng thinh | im lặng","silence (not speaking) | muteness","1529860"),
    ("悪臭","あくしゅう","n","mùi hôi | mùi khó chịu | mùi thối","bad smell | foul smell | stench","1151900"),
    ("刺激","しげき","n|vs|vt","kích thích | kích động | sự kích thích","stimulus | stimulation | irritation | impetus","1594190"),
    ("感触","かんしょく","n","cảm giác (chạm) | xúc cảm | ấn tượng","feel | touch | texture | sensation | impression","1212440"),
    ("手触り","てざわり","n","cảm giác khi chạm | xúc cảm tay","feel | touch","1327920"),
    ("温もり","ぬくもり","n","hơi ấm | sự ấm áp","warmth","1183330"),
    ("眠気","ねむけ","n","cơn buồn ngủ | sự buồn ngủ","sleepiness | drowsiness","1529340"),
    ("投薬","とうやく","n|vs|vt|vi","kê thuốc | cho dùng thuốc | dùng thuốc","administration (of medicine) | medication | dosage","1447370"),
    ("服用","ふくよう","n|vs|vt","uống thuốc | dùng thuốc","taking medicine | dosing","1501010"),
    ("内服","ないふく","n|vs|vt","uống (thuốc) | dùng trong","internal use (of medicine)","1459080"),
    ("麻酔","ますい","n","gây mê | gây tê","anaesthesia","1603940"),
    ("輸血","ゆけつ","n|vs|vt|vi","truyền máu","blood transfusion","1538810"),
    ("移植","いしょく","n|vs|vt","cấy ghép | ghép (tạng) | di thực (cây)","transplanting | transplantation (organ) | porting (software)","1158310"),
    ("検診","けんしん","n|vs|vt","khám sàng lọc | khám kiểm tra (bệnh)","medical examination | health screening","1256350"),
    ("診療","しんりょう","n|vs|vt","khám và điều trị | chẩn trị","diagnosis and treatment | medical care","1365500"),
    ("病棟","びょうとう","n","khu bệnh (bệnh viện) | tòa nhà bệnh","(hospital) ward","1490400"),
    ("病室","びょうしつ","n","phòng bệnh","sickroom | hospital room","1490310"),
    ("外来","がいらい","adj-no|n","ngoại lai | ngoại trú | du nhập","foreign | imported | outpatient","1204240"),
    ("応急","おうきゅう","n|adj-no","cấp cứu | sơ cứu | biện pháp tạm thời","emergency fix | tentative measure","1179880"),
    ("救命","きゅうめい","n|adj-no","cứu mạng | cứu sinh","lifesaving","1229270"),
    ("蘇生","そせい","n|vs|vi","hồi sinh | hồi sức | tái sinh","revival | resuscitation | regeneration","1596520"),
    ("延命","えんめい","n|vs","kéo dài sự sống | duy trì sự sống","prolonging life | life extension","1176540"),
    ("治癒","ちゆ","n|vs|vi","chữa lành | hồi phục | khỏi bệnh","healing | cure | recovery","1316880"),
    ("完治","かんち","n|vs|vi","khỏi hẳn | chữa khỏi hoàn toàn","complete recovery","1614110"),
    ("発病","はつびょう","n|vs|vi","phát bệnh | đổ bệnh","onset of an illness | falling ill","1477870"),
    ("発作","ほっさ","n","cơn (bệnh) | cơn co giật | đột quỵ","fit | attack | spasm | seizure | stroke","1477470"),
    ("合併症","がっぺいしょう","n","biến chứng","complication","1285230"),
    ("後遺症","こういしょう","n","di chứng | hậu chứng","after-effect | sequela","1269450"),
    ("抗体","こうたい","n","kháng thể","antibody","1278960"),
    ("体内","たいない","n|adj-no","trong cơ thể | nội tại","interior of the body","1409640"),
    ("体外","たいがい","n|adj-no","ngoài cơ thể","outside the body","1409280"),
    ("粘膜","ねんまく","n","niêm mạc","mucous membrane | mucosa","1469780"),
    ("胃腸","いちょう","n","dạ dày và ruột | tiêu hóa | hệ tiêu hóa","stomach and intestines | digestive organs","1158610"),
    ("脳","のう","n","não | bộ não | đầu óc","brain | brains | mind","1470380"),
    ("嗅覚","きゅうかく","n","khứu giác","sense of smell | olfaction","1565490"),
    ("痛覚","つうかく","n","cảm giác đau","sense of pain","1652590"),
    ("錯覚","さっかく","n|vs|vt|vi","ảo giác | nhầm tưởng | hiểu lầm","illusion | misapprehension | misconception","1298400"),
    ("幻覚","げんかく","n","ảo giác | ảo tưởng","hallucination | illusion","1262910"),
    ("本能","ほんのう","n|adj-no","bản năng","instinct","1523130"),
    ("反応","はんのう","n|vs|vi","phản ứng | phản hồi | phản ứng (hóa, sinh)","reaction | response | physical reaction","1480210"),
    ("感度","かんど","n","độ nhạy | độ thu (sóng) | độ nhạy (phim)","sensitivity | reception (radio, TV)","1212550"),
    ("感受性","かんじゅせい","n","tính nhạy cảm | sự thụ cảm | sức cảm thụ","sensitivity | sensibility | susceptibility","1212390"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
