# -*- coding: utf-8 -*-
"""Build N3 ready wave 045 — 103 freshly-curated N3 verbs + adjectives.
Readings/pos/ent_seq verified against japanese_raw_jmdict; meaning_vi authored by hand.
"""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-045.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(word, reading, pos, vi, en, sid):
    return ",".join([q(word),q(reading),q(""),q("N3"),q(pos),q(vi),q(en),q(""),q("0"),
        q("jmdict"),q(sid),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])

DATA = [
    ("含める","ふくめる","v1|vt","bao gồm | tính cả | căn dặn cho hiểu","to include (in a scope) | to instruct | to make one understand","1216890"),
    ("占める","しめる","v1|vt","chiếm | chiếm giữ | giành được","to account for | to make up | to occupy | to secure","1389460"),
    ("兼ねる","かねる","suf|v1|vt","kiêm | gồm cả hai | khó mà (làm)","to serve two roles | to combine | to be unable to do","1256520"),
    ("及ぶ","およぶ","v5b|vi","đạt tới | lan tới | sánh bằng","to reach | to extend | to amount to | to compare with","1228170"),
    ("飽きる","あきる","v1|vi","chán | ngán | phát ngấy","to get tired of | to lose interest in | to get sick of","1586250"),
    ("暴れる","あばれる","v1|vi","làm loạn | nổi loạn | giãy giụa","to act violently | to rage | to struggle","1519340"),
    ("余る","あまる","v5r|vi","dư | thừa | còn lại","to remain | to be left over | to be in excess","1543910"),
    ("操る","あやつる","v5r|vt","điều khiển | thao túng | sử dụng thành thạo","to operate | to handle | to manipulate | to have a good command of","1400010"),
    ("限る","かぎる","v5r|vt|vi","giới hạn | chỉ riêng | tốt nhất là","to restrict | to limit | to be limited to | to be best (for)","1264640"),
    ("稼ぐ","かせぐ","v5g|vt|vi","kiếm (tiền) | ghi (điểm) | câu giờ","to earn (money) | to score (points) | to gain (time)","1194450"),
    ("担ぐ","かつぐ","v5g|vt","vác (lên vai) | tiến cử | lừa | gánh","to shoulder | to nominate | to deceive | to carry","1418140"),
    ("絡む","からむ","v5m|vi","quấn vào | dính líu | gây sự","to get tangled | to be involved (in) | to pick a quarrel","1548520"),
    ("心得る","こころえる","v1|vt","hiểu rõ | nắm được | thông thạo","to understand | to be aware of | to have a knowledge of","1360920"),
    ("異なる","ことなる","v5r|vi","khác | khác biệt | không giống","to differ | to be different | to vary","1157510"),
    ("好む","このむ","v5m|vt","thích | ưa thích | ưa chuộng","to like | to prefer","1277520"),
    ("籠もる","こもる","v5r|vi","ru rú trong nhà | chứa chan (cảm xúc) | ngột ngạt | (giọng) nghẹt","to shut oneself in | to be filled with (emotion) | to be stuffy | to be muffled","1593430"),
    ("転がる","ころがる","v5r|vi","lăn | ngã lăn | nằm lăn lóc | xoay chuyển","to roll | to tumble | to lie around | to turn out","1441000"),
    ("定める","さだめる","v1|vt","quy định | xác định | ấn định | bình định","to decide | to determine | to establish | to prescribe","1435380"),
    ("仕上げる","しあげる","v1|vt","hoàn thành | làm xong | hoàn thiện","to finish up | to complete | to finish off","1305140"),
    ("親しむ","したしむ","v5m|vi","thân thiết | gần gũi | làm quen","to be intimate with | to befriend | to become familiar with","1365070"),
    ("縛る","しばる","v5r|vt","trói | buộc | ràng buộc","to tie | to bind | to fasten | to restrict","1476050"),
    ("絞る","しぼる","v5r|vt","vắt | siết | thu hẹp | mắng","to wring | to squeeze | to narrow down | to scold","1594520"),
    ("備える","そなえる","v1|vt","trang bị | chuẩn bị | sẵn có (phẩm chất)","to equip with | to prepare for | to be endowed with","1244960"),
    ("損なう","そこなう","v5u|vt|suf","làm hỏng | gây tổn hại | suýt (làm)","to harm | to damage | to spoil | to fail to do","1596510"),
    ("例える","たとえる","v1|vt","ví von | so sánh | ẩn dụ","to compare to | to liken | to speak figuratively","1597130"),
    ("努める","つとめる","v1|vi","nỗ lực | cố gắng | gắng sức","to endeavor | to try hard | to make an effort","1240820"),
    ("積もる","つもる","v5r|vi|vt","chất đống | tích tụ | ước tính","to pile up | to accumulate | to estimate","1382990"),
    ("問う","とう","v5u-s|vt","hỏi | truy cứu | buộc tội | coi trọng","to ask | to pursue (responsibility) | to accuse of | to call into question","1536000"),
    ("唱える","となえる","v1|vt","tụng (niệm) | hô | chủ trương | đề xướng","to recite | to chant | to advocate | to insist","1347490"),
    ("飛ばす","とばす","v5s|vt","làm bay | phóng nhanh | bỏ qua | tung (tin)","to make fly | to drive fast | to skip over | to spread (a rumour)","1485230"),
    ("殴る","なぐる","v5r|vt","đánh | đấm | nện","to strike | to hit | to beat | to punch","1181390"),
    ("馴染む","なじむ","v5m|vi","quen | thích nghi | hòa hợp | ăn nhập","to get used to | to adapt to | to become attached | to go well with","1459820"),
    ("賑わう","にぎわう","v5u|vi","đông đúc | nhộn nhịp | phồn thịnh","to be crowded with people | to be bustling | to prosper","1463500"),
    ("濁る","にごる","v5r|vi","đục | vẩn đục | (âm) đục","to become muddy | to become cloudy | to become impure | (sound) to become voiced","1415960"),
    ("逃れる","のがれる","v1|vi","trốn thoát | thoát khỏi","to escape","1450440"),
    ("果たす","はたす","v5s|vt","hoàn thành | thực hiện | làm tròn","to accomplish | to carry out | to fulfill","1192850"),
    ("弾む","はずむ","v5m|vi|vt","nảy lên | sôi nổi | chi mạnh tay | thở hổn hển","to bounce | to get lively | to splurge | to pant","1419400"),
    ("果てる","はてる","v1|vi","kết thúc | cạn kiệt | qua đời","to end | to be exhausted | to die","1192910"),
    ("省みる","かえりみる","v1|vt","tự xét | tự kiểm điểm | suy ngẫm","to reflect on (oneself) | to examine | to introspect","2836356"),
    ("浸す","ひたす","v5s|vt","ngâm | nhúng | thấm ướt","to soak | to dip | to immerse | to moisten","1362560"),
    ("膨らむ","ふくらむ","v5m|vi","phồng lên | nở ra | (kỳ vọng) lớn dần","to expand | to swell | to get big | to become inflated","1519990"),
    ("塞ぐ","ふさぐ","v5g|vt|vi","bịt | chặn | che | chán nản","to stop up | to block | to cover | to feel depressed","1602590"),
    ("防ぐ","ふせぐ","v5g|vt","phòng | ngăn ngừa | bảo vệ","to defend against | to prevent | to avert","1520190"),
    ("隔たる","へだたる","v5r|vi","cách xa | xa cách","to be distant","1206340"),
    ("施す","ほどこす","v5s|vt","bố thí | thực hiện | gia công | gieo","to give | to perform | to apply (processing) | to sow","1310370"),
    ("任せる","まかせる","v1|vt","giao phó | ủy thác | mặc kệ | dốc hết","to entrust (to someone) | to leave (to) | to use to the full","1467150"),
    ("紛れる","まぎれる","v1|vi","lẫn vào | lạc vào | bị phân tâm | khó phân biệt","to be lost in | to slip into | to be distracted by | to be confusingly similar","1505010"),
    ("増す","ます","v5s|vi|vt","tăng | gia tăng | lớn lên","to increase | to grow","1403120"),
    ("惑う","まどう","v5u|vi","lạc lối | bối rối | mê muội","to get lost | to be perplexed | to be tempted","1562570"),
    ("免じる","めんじる","v1|vt","miễn nhiệm | miễn (cho) | tha","to dismiss (from a position) | to exempt | to forgive","1533070"),
    ("恵まれる","めぐまれる","v1|vi","được ưu đãi | may mắn có | dồi dào","to be blessed with | to be rich in | to abound in","1611980"),
    ("目指す","めざす","v5s|vt","nhắm tới | hướng tới | đặt mục tiêu","to aim at | to try for | to head for","1535440"),
    ("設ける","もうける","v1|vt","thiết lập | lập ra | bố trí | đặt ra (quy tắc)","to prepare | to set up | to establish | to lay down (rules)","1386000"),
    ("催促","さいそく","n|vs|vt","thúc giục | hối thúc | đòi hỏi","pressing | urging | demanding","1292200"),
    ("基づく","もとづく","v5k|vi","dựa trên | căn cứ vào | bắt nguồn từ","to be based on | to be grounded on | to originate in","1605270"),
    ("求める","もとめる","v1|vt","tìm kiếm | yêu cầu | mong muốn | mua","to want | to request | to demand | to seek | to purchase","1229350"),
    ("雇う","やとう","v5u|vt","thuê | tuyển dụng | thuê (xe)","to employ | to hire | to take on | to charter","1605570"),
    ("譲り合う","ゆずりあう","v5u|vt","nhường nhịn nhau | thỏa hiệp","to give and take | to make mutual concessions | to compromise","1357000"),
    ("緩む","ゆるむ","v5m|vi","lỏng ra | chùng | thả lỏng | dịu đi","to become loose | to slacken | to relax | to become softer","1214430"),
    ("緩める","ゆるめる","v1|vt","nới lỏng | thả lỏng | giảm tốc","to loosen | to relax | to ease | to slow down","1214440"),
    ("酔う","よう","v5u|vi","say (rượu) | say (xe) | ngất ngây","to get drunk | to feel sick (in a vehicle) | to be in raptures","1372650"),
    ("詰る","なじる","v5r|vt","trách móc | khiển trách | bắt bẻ","to rebuke | to scold | to find fault","1226560"),
    ("適切","てきせつ","adj-na|n","thích hợp | thỏa đáng | phù hợp","appropriate | suitable | apt | pertinent","1437430"),
    ("適度","てきど","adj-na|n","vừa phải | điều độ | thích hợp","moderate (degree) | proper (amount) | temperate","1437440"),
    ("過剰","かじょう","n|adj-na","quá mức | dư thừa | thái quá","excess | surplus | overabundance","1196170"),
    ("膨大","ぼうだい","adj-na|n","khổng lồ | đồ sộ | to lớn","huge | vast | enormous | colossal","1603660"),
    ("僅か","わずか","adj-na|adv","ít ỏi | chút xíu | chỉ vỏn vẹn","a little | slight | only | merely","1240750"),
    ("莫大","ばくだい","adj-na|n","khổng lồ | to lớn | kếch xù","vast | huge | immense | enormous","1476060"),
    ("微妙","びみょう","adj-na|n","tinh tế | tế nhị | khó nói | mập mờ","subtle | delicate | tricky | iffy","1486170"),
    ("明白","めいはく","adj-na","rõ ràng | hiển nhiên | minh bạch","obvious | clear | evident | explicit","1000220"),
    ("明瞭","めいりょう","adj-na|n","rõ ràng | rành mạch | minh bạch","clear | plain | distinct | articulate","1532620"),
    ("緩やか","ゆるやか","adj-na","thoai thoải | chậm rãi | khoan dung","gentle (slope) | slow (speed) | lenient | lax","1214450"),
    ("密接","みっせつ","adj-na|vs|vi","mật thiết | gần gũi | sát nhau","close (relationship) | intimate | adjacent","1528290"),
    ("深刻","しんこく","adj-na|n","nghiêm trọng | trầm trọng | sâu sắc","serious | severe | grave | acute","1362730"),
    ("切実","せつじつ","adj-na|n","tha thiết | cấp thiết | thiết thực","earnest | acute | pressing | urgent | pertinent","1385050"),
    ("強烈","きょうれつ","adj-na|n","mãnh liệt | dữ dội | mạnh mẽ","strong | intense | severe","1236620"),
    ("猛烈","もうれつ","adj-na|adv","mãnh liệt | kịch liệt | dữ dội","fierce | intense | violent | terrific","1534100"),
    ("顕著","けんちょ","adj-na|n","nổi bật | rõ rệt | đáng chú ý","remarkable | striking | obvious","1260640"),
    ("著しい","いちじるしい","adj-i","rõ rệt | đáng kể | nổi bật","striking | remarkable | considerable","1427070"),
    ("乏しい","とぼしい","adj-i","thiếu thốn | khan hiếm | nghèo nàn","meagre | scarce | lacking | poor","1584130"),
    ("著名","ちょめい","adj-na|n","nổi tiếng | trứ danh | có tiếng","famous | noted | eminent | distinguished","1427150"),
    ("豊富","ほうふ","adj-na|n","phong phú | dồi dào | giàu có","abundant | plentiful | rich | ample","1518180"),
    ("過密","かみつ","n|adj-na","quá tải | chen chúc | dày đặc","overcrowding | congestion | crammed (schedule)","1196460"),
    ("精密","せいみつ","adj-na|n","tinh vi | chính xác | tỉ mỉ","precise | exact | detailed | accurate","1380190"),
    ("綿密","めんみつ","adj-na|n","tỉ mỉ | kỹ lưỡng | chu đáo","minute | detailed | careful | scrupulous","1533390"),
    ("厳密","げんみつ","adj-na","nghiêm ngặt | chính xác | chặt chẽ","strict | close | precise | scrupulous","1262830"),
    ("厳重","げんじゅう","adj-na|n","nghiêm ngặt | chặt chẽ | kiên cố","strict | severe | stringent | rigorous","1262660"),
    ("寛容","かんよう","n|adj-na","khoan dung | độ lượng | bao dung","tolerance | open-mindedness | generosity","1211970"),
    ("頑丈","がんじょう","adj-na|n","chắc chắn | cứng cáp | vững chãi","solid | firm | sturdy | strong","1217690"),
    ("純粋","じゅんすい","adj-na|n","thuần khiết | trong sáng | nguyên chất","pure | true | genuine | unmixed","1341930"),
    ("無邪気","むじゃき","adj-na|n","ngây thơ | hồn nhiên","innocent | naive | simple-minded","1530080"),
    ("陽気","ようき","adj-na|n","vui vẻ | sôi nổi | tươi vui","cheerful | jovial | merry | lively","1546990"),
    ("陰気","いんき","adj-na|n","u ám | ảm đạm | buồn bã","gloomy | dismal | melancholy","1170280"),
    ("不快","ふかい","n|adj-na","khó chịu | bất an | không thoải mái","displeasure | discomfort | unpleasantness","1491570"),
    ("愉快","ゆかい","adj-na|n","vui vẻ | thú vị | sảng khoái","pleasant | delightful | enjoyable | cheerful","1538560"),
    ("爽快","そうかい","adj-na|n","sảng khoái | khoan khoái | phấn chấn","refreshing | exhilarating | invigorating","1399530"),
    ("退屈","たいくつ","adj-na|vs|vi","chán | buồn tẻ | tẻ nhạt","tedious | boring | dull | to feel bored","1596750"),
    ("華やか","はなやか","adj-na","rực rỡ | lộng lẫy | hào nhoáng","gorgeous | showy | brilliant | splendid","1600990"),
    ("質素","しっそ","adj-na|n","giản dị | mộc mạc | đạm bạc","simple | plain | modest | frugal","1320710"),
    ("贅沢","ぜいたく","n|adj-na|vs","xa xỉ | xa hoa | lãng phí","luxury | extravagance | lavish | wasteful","1573150"),
    ("豪華","ごうか","adj-na|n","xa hoa | sang trọng | lộng lẫy","extravagant | lavish | luxurious | gorgeous","1285520"),
    ("優雅","ゆうが","adj-na|n","thanh lịch | tao nhã | nhàn nhã","elegant | graceful | refined | leisurely","1539180"),
    ("下品","げひん","adj-na|n","thô tục | thiếu lịch sự | tầm thường","vulgar | indecent | coarse | crude","1186230"),
]

rows=[row(*d) for d in DATA]
content = HEADER + "\n" + "\n".join(rows) + "\n"
with open(OUT,"w",encoding="utf-8",newline="\n") as f:
    f.write(content)
print(f"Written {len(rows)} rows to {os.path.abspath(OUT)}")
