# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-037.csv -- 34 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-037.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("手を抜く","てをぬく","N4","exp|v5k",
        "làm qua loa | cắt giảm công sức | không tận tâm | nương tay",
        "to cut corners | to be shoddy | to slack off | to go easy (on an opponent) | to hold back",
        "1327310",
        "手を抜いてはいけない。","てをぬいてはいけない。",
        "Không được làm qua loa.","You must not cut corners."),
    row("著作権","ちょさくけん","N4","n",
        "bản quyền | quyền tác giả",
        "copyright",
        "1427100",
        "著作権を保護する。","ちょさくけんをほごする。",
        "Bảo vệ bản quyền.","Protect copyright."),
    row("飛び回る","とびまわる","N4","v5r|vi",
        "bay khắp nơi | nhảy nhót | tất tả chạy vòng vòng",
        "to fly about | to jump about | to bustle about",
        "1485270",
        "忙しく飛び回る。","いそがしくとびまわる。",
        "Tất tả bận rộn khắp nơi.","Bustle about busily."),
    row("朗らか","ほがらか","N4","adj-na",
        "vui tươi | hồn nhiên | sáng sủa | trong sáng",
        "cheerful | merry | sunny | bright (sky, day, etc.) | fine | clear | melodious",
        "1560710",
        "朗らかな笑顔。","ほがらかなえがお。",
        "Nụ cười tươi vui.","A cheerful smile."),
    row("論争","ろんそう","N4","n|vs|vi",
        "tranh luận | tranh cãi | bàn cãi",
        "dispute | controversy | debate | argument | taking issue",
        "1561760",
        "活発な論争。","かっぱつなろんそう。",
        "Cuộc tranh luận sôi nổi.","A lively debate."),
    row("和む","なごむ","N4","v5m|vi",
        "dịu lại | bình tĩnh lại | thư giãn",
        "to be softened | to calm down",
        "1561930",
        "雰囲気が和む。","ふんいきがなごむ。",
        "Không khí dịu lại.","The atmosphere calms down."),
    row("論理的","ろんりてき","N4","adj-na",
        "hợp lý | logic | có lý luận",
        "logical",
        "1561890",
        "論理的に考える。","ろんりてきにかんがえる。",
        "Suy nghĩ một cách logic.","Think logically."),
    row("清々しい","すがすがしい","N4","adj-i",
        "sảng khoái | trong lành | khoan khoái | mát mẻ",
        "refreshing (e.g. feeling, scene, wind, morning air) | brisk | bracing | fresh | refreshed",
        "1595560",
        "清々しい朝の空気。","すがすがしいあさのくうき。",
        "Không khí buổi sáng trong lành.","Fresh morning air."),
    row("本編","ほんぺん","N4","n",
        "câu chuyện gốc | nội dung chính | phần chính | phim chính",
        "original story (as opposed to a sequel, spin-off, etc.) | main story | main part(s) of a story | feature film",
        "2020990",
        "本編が始まります。","ほんぺんがはじまります。",
        "Phần chính bắt đầu.","The main story begins."),
    row("牧","まき","N4","n",
        "đồng cỏ | bãi chăn thả",
        "pasture | grazing land",
        "2020920",
        "牛を牧で放す。","うしをまきではなす。",
        "Thả bò trên đồng cỏ.","Release cattle on the pasture."),
    row("おっとり","おっとり","N4","adv-to|adv|vs",
        "nhẹ nhàng | khoan thai | bình tĩnh",
        "gently | quietly | calmly",
        "2021000",
        "おっとりした性格。","おっとりしたせいかく。",
        "Tính cách nhẹ nhàng khoan thai.","A calm, gentle personality."),
    row("和やか","にこやか","N4","adj-na",
        "tươi cười | rạng rỡ | vui vẻ",
        "smiling | beaming | radiant | bright | cheerful",
        "1009570",
        "にこやかな笑顔。","にこやかなえがお。",
        "Nụ cười tươi rạng.","A beaming smile."),
    row("和やか","なごやか","N4","adj-na",
        "ôn hòa | điềm đạm | nhẹ nhàng | thân thiện | hài hòa",
        "mild | calm | gentle | quiet | congenial | amicable | harmonious | peaceful",
        "1561940",
        "和やかな雰囲気。","なごやかなふんいき。",
        "Bầu không khí hài hòa.","A harmonious atmosphere."),
    row("和らぐ","やわらぐ","N4","v5g|vi",
        "dịu đi | lắng xuống | thuyên giảm | giảm bớt",
        "to soften | to calm down | to be eased | to be mitigated | to subside | to abate",
        "1561950",
        "痛みが和らぐ。","いたみがやわらぐ。",
        "Cơn đau dịu đi.","The pain subsides."),
    row("和らげる","やわらげる","N4","v1|vt",
        "làm dịu | xoa dịu | làm giảm nhẹ",
        "to soften | to moderate | to relieve",
        "1561960",
        "緊張を和らげる。","きんちょうをやわらげる。",
        "Xoa dịu căng thẳng.","Relieve tension."),
    row("晴れやか","はれやか","N4","adj-na",
        "trong sáng | rực rỡ | tươi sáng",
        "clear | bright | sunny",
        "2215160",
        "晴れやかな笑顔。","はれやかなえがお。",
        "Nụ cười rực rỡ.","A bright smile."),
    row("目を見張る","めをみはる","N4","exp|v5r",
        "mở to mắt (ngạc nhiên) | kinh ngạc | há hốc mồm",
        "to open one's eyes wide (in astonishment, wonder, etc.) | to be wide-eyed | to be amazed",
        "2020910",
        "目を見張る景色。","めをみはるけしき。",
        "Cảnh đẹp làm mở to mắt.","A breathtaking view."),
    row("耳を傾ける","みみをかたむける","N4","exp|v1",
        "lắng nghe | chú ý nghe | lắng tai",
        "to lend an ear | to hearken | to give an ear to | to listen carefully",
        "2069560",
        "話に耳を傾ける。","はなしにももをかたむける。",
        "Lắng nghe câu chuyện.","Listen carefully to the story."),
    row("論点","ろんてん","N4","n",
        "điểm tranh luận | vấn đề đang bàn",
        "point in question (at issue)",
        "1561800",
        "論点を整理する。","ろんてんをせいりする。",
        "Sắp xếp các điểm tranh luận.","Organize the points at issue."),
    row("論理","ろんり","N4","n",
        "logic | lý luận | tư duy logic",
        "logic",
        "1561850",
        "論理が通らない。","ろんりがとおらない。",
        "Lý luận không thông.","The logic doesn't hold."),
    row("論破","ろんぱ","N4","n|vs|vt",
        "bác bỏ lập luận | thắng tranh luận | phản bác",
        "defeating an argument | winning an argument | refutation | confutation",
        "1561810",
        "相手の意見を論破する。","あいてのいけんをろんぱする。",
        "Bác bỏ lập luận của đối phương.","Refute the opponent's argument."),
    row("論評","ろんぴょう","N4","n|vs|vt",
        "bình luận | nhận xét | phê bình | đánh giá",
        "comment | criticism | critique | review",
        "1561830",
        "作品を論評する。","さくひんをろんぴょうする。",
        "Phê bình tác phẩm.","Critique the work."),
    row("論調","ろんちょう","N4","n",
        "giọng điệu trong lập luận | xu hướng luận điểm",
        "tone (of argument) | tenor | drift",
        "1561790",
        "論調が変わった。","ろんちょうがかわった。",
        "Giọng điệu lập luận đã thay đổi.","The tone of the argument has changed."),
    row("代替案","だいたいあん","N4","n",
        "phương án thay thế | kế hoạch thay thế | đề xuất khác",
        "alternative plan | alternate proposal | counterplan | counterproposal",
        "2864182",
        "代替案を出す。","だいたいあんをだす。",
        "Đề xuất phương án thay thế.","Present an alternative plan."),
    row("仮構","かこう","N4","n|vs|vt",
        "hư cấu | bịa đặt | giàn giáo tạm (xây dựng)",
        "fiction | fabrication | concoction | invention | falsework (scaffolding, etc.)",
        "2826974",
        "仮構の世界。","かこうのせかい。",
        "Thế giới hư cấu.","A fictional world."),
    row("企業理念","きぎょうりねん","N4","n",
        "tầm nhìn doanh nghiệp | triết lý kinh doanh | sứ mệnh công ty",
        "corporate vision | corporate philosophy | philosophy of business | corporate ethos",
        "2826984",
        "企業理念を共有する。","きぎょうりねんをきょうゆうする。",
        "Chia sẻ triết lý kinh doanh.","Share the corporate philosophy."),
    row("口を出す","くちをだす","N4","exp|v5s",
        "xen miệng vào | can thiệp | nhúng tay vào | chen ngang",
        "to interrupt | to interfere | to meddle | to intrude | to butt in | to poke one's nose into",
        "1275760",
        "余計な口を出すな。","よけいなくちをだすな。",
        "Đừng xen miệng vào chuyện thừa.","Don't butt in unnecessarily."),
    row("増減率","ぞうげんりつ","N4","n",
        "tỷ lệ thay đổi | tốc độ biến động",
        "rate of change",
        "2826977",
        "増減率を計算する。","ぞうげんりつをけいさんする。",
        "Tính toán tỷ lệ thay đổi.","Calculate the rate of change."),
    row("気を抜く","きをぬく","N4","exp|v5k",
        "mất tập trung | lơ là | sao nhãng",
        "to lose focus | to let one's mind wander | to relax one's attention",
        "2127660",
        "気を抜くな。","きをぬくな。",
        "Đừng lơ là.","Don't lose focus."),
    row("泥団子","どろだんご","N4","n",
        "viên bùn | cục đất bùn nặn tròn",
        "mud ball | dirt ball",
        "2826988",
        "泥団子を作る。","どろだんごをつくる。",
        "Nặn viên bùn.","Make a mud ball."),
    row("牧","ぼく","N4","n",
        "quan thái thú (cổ đại Trung Hoa)",
        "regional governor in ancient China",
        "2844214",
        "牧となる。","ぼくとなる。",
        "Trở thành thái thú.","Become a regional governor."),
    row("聞き間違い","ききまちがい","N4","n",
        "nghe nhầm | nhầm lẫn khi nghe",
        "mishearing",
        "2826970",
        "聞き間違いだった。","ききまちがいだった。",
        "Đó là nghe nhầm.","It was a mishearing."),
    row("諸事情","しょじじょう","N4","n",
        "các lý do khác nhau | nhiều hoàn cảnh | mọi nguyên nhân",
        "various reasons",
        "2826989",
        "諸事情により中止。","しょじじょうによりちゅうし。",
        "Hủy bỏ vì nhiều lý do.","Cancelled due to various reasons."),
    row("通話表","つうわひょう","N4","n",
        "bảng ký hiệu âm vần điện thoại | bảng chính tả âm thanh",
        "phonetic alphabet (e.g. A for alpha, B for bravo, etc.) | phonetic code",
        "2826967",
        "通話表を使う。","つうわひょうをつかう。",
        "Sử dụng bảng ký hiệu âm thanh.","Use the phonetic alphabet."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
