# -*- coding: utf-8 -*-
"""Build N3 ready wave 064 — 88 freshly-curated N3 emotion/study verbs + ability adjectives + group/order nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-064.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("恐れる","おそれる","v1|vt","sợ | lo sợ | e ngại","to fear | to be afraid of","1589200"),
    ("恨む","うらむ","v5m|vt","oán hận | căm giận | trách","to bear a grudge against | to resent | to blame","1289780"),
    ("嫌う","きらう","v5u|vt","ghét | không ưa | né tránh","to hate | to dislike | to avoid","1257250"),
    ("嫌がる","いやがる","v5r|vt","tỏ ra khó chịu | không thích | ghét","to seem to hate | to express dislike","1609260"),
    ("惚れる","ほれる","v1|vi","phải lòng | say mê | mê mẩn","to fall in love (with) | to be captivated (by) | to admire","1288500"),
    ("恋する","こいする","vs-i|vt|vi","yêu | phải lòng | đem lòng yêu","to fall in love (with) | to love","1609750"),
    ("焦がれる","こがれる","v1|vi","khao khát | mong mỏi | si mê","to long (for) | to yearn (for) | to love ardently","1350720"),
    ("浮かれる","うかれる","v1|vi","vui vẻ | hân hoan | phấn khởi","to make merry | to be festive","1497370"),
    ("はしゃぐ","はしゃぐ","v5g|vi","nô đùa | hớn hở | nhặng xị","to make merry | to frolic | to be in high spirits","1010730"),
    ("泣かせる","なかせる","v1|vt","làm ai khóc | làm xúc động | làm khổ","to make someone cry | to move to tears | to grieve","1229640"),
    ("困らせる","こまらせる","v1","làm khó | làm bối rối | gây phiền","to trouble | to embarrass | to put on the spot","1289550"),
    ("驚かす","おどろかす","v5s|vt","làm giật mình | dọa | gây xôn xao","to surprise | to frighten | to create a stir","1238650"),
    ("弄ぶ","もてあそぶ","v5b|vt","nghịch | đùa giỡn (tình cảm) | mặc tình","to fiddle with | to toy with (emotions) | to trifle with","1980760"),
    ("仕向ける","しむける","v1|vt","khiến cho | dụ | đối xử | gửi đến","to induce (to do) | to tempt | to treat | to send","1594580"),
    ("促す","うながす","v5s|vt","thúc giục | khuyến khích | đôn đốc | kích thích","to urge | to encourage | to prompt | to stimulate","1403760"),
    ("駆り立てる","かりたてる","v1|vt","thôi thúc | thúc đẩy | lùa | dồn ép","to drive (to do) | to urge on | to spur | to impel","1244830"),
    ("奨励","しょうれい","n|vs|vt","khuyến khích | cổ vũ | thúc đẩy","encouragement | promotion | inducement","1347550"),
    ("推奨","すいしょう","n|vs|vt","khuyến nghị | giới thiệu | tán thành","recommendation | endorsement","1371120"),
    ("推薦","すいせん","n|vs|vt","tiến cử | giới thiệu | đề cử","recommendation | referral | endorsement","1371170"),
    ("教わる","おそわる","v5r|vt","được dạy | học | thụ giáo","to be taught | to learn | to take lessons in","1236940"),
    ("身につける","みにつける","exp|v1","học được | trang bị (kỹ năng) | mặc | mang theo","to learn | to acquire (knowledge) | to wear | to put on","1980660"),
    ("音読","おんどく","n|vs|vt","đọc to | đọc thành tiếng | âm Hán (on)","reading aloud | reading (a kanji) by its on'yomi","1183990"),
    ("筆記","ひっき","n|vs|vt","ghi chép | chép | viết","(taking) notes | copying","1487800"),
    ("演習","えんしゅう","n|vs|vt|vi","diễn tập | thực hành | hội thảo | tập trận","practice | exercise | drill | seminar | military exercise","1176930"),
    ("実習","じっしゅう","n|vs|vt","thực tập | thực hành","practice (in the field) | training | practical exercise","1321200"),
    ("実践","じっせん","n|vs|vt","thực hành | thực tiễn | áp dụng","practice | putting into practice | implementation","1321260"),
    ("再現","さいげん","n|vs|vi|vt","tái hiện | tái diễn | phục dựng","reappearance | reproduction | reenactment","1292640"),
    ("模倣","もほう","n|vs|vt","mô phỏng | bắt chước | sao chép","imitation | copying","1533700"),
    ("会得","えとく","n|vs|vt","lĩnh hội | nắm vững | thấu hiểu","understanding | grasp | mastery (of a skill)","1198830"),
    ("熟知","じゅくち","n|vs|vt","thông thạo | am hiểu tường tận | rành rẽ","being familiar with | having thorough knowledge of","1337890"),
    ("精通","せいつう","n|vs|vi","tinh thông | thông thạo | am tường","being well versed (in) | being familiar (with)","1380100"),
    ("博識","はくしき","n|adj-na","uyên bác | kiến thức rộng | thông thái","extensive knowledge | erudition | well-informed","1474660"),
    ("無知","むち","n|adj-na","vô tri | ngu dốt | thiếu hiểu biết","ignorance | innocence | stupidity","1530630"),
    ("無能","むのう","n|adj-na","bất tài | vô năng | kém cỏi","incompetence | inability | incompetent person","1530780"),
    ("有能","ゆうのう","adj-na|n","có năng lực | tài giỏi | hiệu quả","able | capable | competent | talented","1541570"),
    ("巧妙","こうみょう","adj-na|n","khéo léo | tinh vi | tài tình","ingenious | skillful | clever | sophisticated","1278340"),
    ("拙い","つたない","adj-i","vụng về | non kém | thô vụng","poor-quality | crude | unskillful | inept | clumsy","1385260"),
    ("緻密","ちみつ","adj-na|n","tỉ mỉ | tinh vi | chính xác | mịn","fine | delicate | intricate | precise | meticulous","1570520"),
    ("克明","こくめい","adj-na","tỉ mỉ | cặn kẽ | trung thực | cần mẫn","detailed | scrupulous | minute | faithful | diligent","1285800"),
    ("丹念","たんねん","adj-na|n","cẩn thận | tỉ mỉ | công phu | kỹ lưỡng","painstaking | careful | meticulous | elaborate","1417000"),
    ("丁重","ていちょう","adj-na|n","lịch sự | trang trọng | ân cần","polite | courteous | hospitable","1427290"),
    ("粗雑","そざつ","adj-na|n","thô sơ | cẩu thả | sơ sài","coarse | rough | crude","1608150"),
    ("精巧","せいこう","adj-na|n","tinh xảo | tinh vi | tinh tế","elaborate | delicate | exquisite","1379900"),
    ("精緻","せいち","adj-na|n","tinh vi | tỉ mỉ | chi tiết | tinh tế","delicate | minute | fine | detailed | subtle","1380270"),
    ("繊細","せんさい","adj-na|n","tinh tế | mảnh mai | nhạy cảm | tế nhị","dainty | delicate | fine | sensitive | subtle","1391930"),
    ("鋭敏","えいびん","adj-na|n","nhạy bén | sắc sảo | tinh tường | thính","sharp (senses) | keen | acute | sharp-witted","1174940"),
    ("明敏","めいびん","adj-na|n","minh mẫn | sáng suốt | nhạy bén","intelligence | discernment","1532600"),
    ("利口","りこう","adj-na|n","thông minh | lanh lợi | khôn ngoan | ngoan","clever | intelligent | smart | shrewd | well-behaved","1549550"),
    ("小賢しい","こざかしい","adj-i","ranh mãnh | láu cá | tinh tướng | hỗn","clever | shrewd | cunning | impertinent","1744610"),
    ("ずる賢い","ずるがしこい","adj-i","gian xảo | mưu mô | xảo quyệt","devious | cunning | sly | crafty","1610030"),
    ("抜け目ない","ぬけめない","adj-i","khôn ngoan | tinh ranh | nhạy bén | không sơ hở","shrewd | astute | cunning | alert","1679950"),
    ("要領","ようりょう","n","điểm mấu chốt | bí quyết | mẹo | đại ý","point | gist | knack | the ropes","1546850"),
    ("手際","てぎわ","n","tay nghề | kỹ năng | sự khéo léo","skill | ability | dexterity | workmanship","1327690"),
    ("工程","こうてい","n","công đoạn | quy trình | tiến độ","process | operation | stage of a process","1278200"),
    ("序列","じょれつ","n","thứ bậc | trật tự xếp hạng | tôn ti","rank | ranking order | hierarchy","1345550"),
    ("優劣","ゆうれつ","n","hơn kém | ưu nhược | chất lượng","(relative) merits | superiority or inferiority","1539620"),
    ("甲乙","こうおつ","n","giáp ất | hơn kém | A và B | sự phân định","first and second | superiority and inferiority | distinction","1280080"),
    ("差異","さい","n","sự khác biệt | chênh lệch | khoảng cách","difference | disparity | gap","1291340"),
    ("相違","そうい","n|vs|vi","sự khác nhau | sai khác | bất đồng","difference | discrepancy | variation","1400820"),
    ("共通","きょうつう","adj-no|n|vs","chung | tương đồng | dùng chung","common | shared | mutual","1234700"),
    ("互い","たがい","n|adj-no","lẫn nhau | qua lại","each other | one another","1268770"),
    ("双方","そうほう","n|adj-no","hai bên | cả hai phía","both parties | both sides","1398940"),
    ("両者","りょうしゃ","n","cả hai | hai bên | cả đôi","the two | both persons | both things","1553650"),
    ("当事者","とうじしゃ","n","đương sự | bên liên quan | người trong cuộc","person concerned | interested party","1449080"),
    ("本人","ほんにん","n","đương sự | chính người đó | bản thân","the person in question | the person themselves","1522750"),
    ("当人","とうにん","n","người đó | đương sự | người trong cuộc","the person concerned | the said person","1449120"),
    ("各自","かくじ","n|adv","mỗi người | từng người | riêng từng","each (person) | everyone | individual | respective","1205010"),
    ("各々","おのおの","n|adv","mỗi cái | từng cái | mỗi người","each | every one","2826190"),
    ("銘々","めいめい","adv|n","mỗi người | riêng từng | từng cá nhân","each | individual","1532810"),
    ("全員","ぜんいん","n|adv","toàn thể | tất cả mọi người | cả đoàn","all members | everyone | whole crew","1394840"),
    ("一同","いちどう","n|n-suf","toàn thể | tất cả | mọi người (cùng)","all present | all concerned | all of us","1165340"),
    ("一行","いっこう","n","đoàn | nhóm | một hành động","party | group | company | one act","2833774"),
    ("一団","いちだん","n","một nhóm | một đoàn | một toán","body | group | party | troupe","1164680"),
    ("多勢","たぜい","n","đông người | ưu thế về số đông","great numbers | numerical superiority","1407880"),
    ("少人数","しょうにんずう","n|adj-no","ít người | số người nhỏ","small number of people","2011360"),
    ("大人数","おおにんずう","n","đông người | số người lớn","large number of people","2137420"),
    ("個別","こべつ","adj-no","riêng lẻ | cá biệt | từng trường hợp","individual | separate | case-by-case","1265000"),
    ("個々","ここ","n|adj-no","từng cái | riêng lẻ | cá thể","individual | one by one | separate | each","1593190"),
    ("別個","べっこ","adj-no","riêng biệt | khác | tách bạch","another | different | separate | discrete","1509710"),
    ("随時","ずいじ","adv","bất cứ lúc nào | khi cần | tùy lúc","whenever necessary | as needed | at any time","1372760"),
    ("逐次","ちくじ","adv","lần lượt | tuần tự | từng cái một","successively | sequentially | one by one","1422500"),
    ("順次","じゅんじ","adv","theo thứ tự | tuần tự | lần lượt","in order | sequential | seriatim","1342330"),
    ("適宜","てきぎ","adj-na|adv","thích hợp | tùy nghi | phù hợp | tùy ý","suitable | appropriate | as required | at one's discretion","1437380"),
    ("随意","ずいい","adj-na|n","tùy ý | tự nguyện | tùy chọn","voluntary | optional | free | elective","1372720"),
    ("任意","にんい","adj-no|adj-na|n","tùy ý | tự nguyện | tùy chọn | bất kỳ","optional | voluntary | arbitrary | discretionary","1467160"),
    ("必須","ひっす","adj-no|adj-na|n","bắt buộc | thiết yếu | không thể thiếu","indispensable | essential | requisite | compulsory","1487540"),
    ("必至","ひっし","adj-na|n","tất yếu | không tránh khỏi | chắc chắn","inevitable | unavoidable | certain","1601895"),
    ("不可欠","ふかけつ","adj-na|n","không thể thiếu | thiết yếu | tất yếu","indispensable | essential","1491400"),
    ("不可避","ふかひ","adj-na|n","không thể tránh | tất yếu | không thể né","inevitable | inescapable | unavoidable","1491540"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
