# -*- coding: utf-8 -*-
OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n3-vi-ready-005.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id):
    return ",".join([q(word), q(reading), q(""), q(lvl), q(pos), q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"), q(""), q(""), q(""), q(""), q("ai_draft"), q("jmdict_ai")])

ROWS = [
    row("冗談","じょうだん","N3","n",
        "chuyện đùa | câu chuyện hài hước",
        "joke | jest | funny story","1355540"),
    row("冗長","じょうちょう","N3","adj-na|n",
        "dài dòng | lắm lời | rườm rà | thừa thãi",
        "tedious | verbose | wordy | lengthy | prolix | redundancy","1355580"),
    row("城","しろ","N3","n",
        "lâu đài | pháo đài",
        "castle","1355710"),
    row("城","じょう","N3","n",
        "lâu đài (trong địa danh) | pháo đài",
        "castle (in place names) | castle | fortress","2088010"),
    row("城下町","じょうかまち","N3","n",
        "thành thị quanh lâu đài | thành phố lâu đài",
        "castle town | city in Japan that developed around the castle of a feudal lord","1355730"),
    row("城壁","じょうへき","N3","n",
        "tường thành | tường bảo vệ | thành lũy | tường pháo đài",
        "castle wall | town walls | defensive wall | rampart","1355770"),
    row("場内","じょうない","N3","n",
        "trong nhà | trong khu vực | trong khuôn viên | hội trường | nhà hát",
        "in-house | (on) the grounds | (in) the premises | hall | theatre | theater","1355880"),
    row("場違い","ばちがい","N3","adj-na|n",
        "không phù hợp | không đúng chỗ | lạc lõng",
        "out-of-place | inappropriate | sticking out like a sore thumb","1355800"),
    row("乗車","じょうしゃ","N3","n|vs|vi",
        "lên tàu | lên xe buýt | bước lên (taxi)",
        "boarding (a train, bus, etc.) | getting into (e.g. a taxi)","1355270"),
    row("乗車券","じょうしゃけん","N3","n",
        "vé tàu | vé xe buýt | vé hành khách",
        "ticket (for bus, train, etc.) | passenger ticket | basic fare ticket","1355290"),
    row("乗馬","じょうば","N3","n|vs|vi",
        "cưỡi ngựa | ngựa cưỡi",
        "horse riding | horseback riding | mounting a horse | riding horse","1355390"),
    row("乗船","じょうせん","N3","n|vs|vi",
        "lên tàu | đăng tàu | tàu chở người",
        "embarking (a ship) | embarkation | boarding","1355360"),
    row("乗組員","のりくみいん","N3","n",
        "thành viên thủy thủ đoàn | thành viên phi hành đoàn | thành viên đội ngũ",
        "crew (of a ship, airplane, etc.) | crew member","1355380"),
    row("乗務員","じょうむいん","N3","n",
        "nhân viên vận chuyển | thành viên phi hành đoàn | lái xe",
        "transport staff (driver, conductor, etc.) | crew member | crewman","1355440"),
    row("乗用車","じょうようしゃ","N3","n",
        "xe ô tô (chở khách) | xe hơi",
        "(passenger) car | automobile","1355460"),
    row("常時","じょうじ","N3","adv|n",
        "thường | bình thường | luôn luôn | liên tục",
        "usually | ordinarily | always | continuous | 24-hour (operation, care, etc.)","1355990"),
    row("常習","じょうしゅう","N3","n",
        "thói quen | phong tục | thói quen thông thường",
        "custom | common practice | habit","1356010"),
    row("常設","じょうせつ","N3","n|vs|vt",
        "thường trực | thường trú | triển lãm thường xuyên",
        "standing (committee) | permanent (exhibit)","1356060"),
    row("常任","じょうにん","N3","adj-no|n",
        "thường trực | thường xuyên | vĩnh viễn",
        "standing | regular | permanent","1356100"),
    row("常務","じょうむ","N3","n",
        "giám đốc điều hành | công việc thường nhật",
        "managing director | executive director | routine business | regular business","1356130"),
    row("常用","じょうよう","N3","n|vs|vt",
        "sử dụng thường xuyên | dùng thường ngày",
        "habitual use | daily use","1356140"),
    row("側面","そくめん","N3","n",
        "mặt bên | cạnh bên | hồ sơ | khía cạnh | chiều",
        "side | flank | profile | sidelight | lateral | aspect | dimension","1404040"),
    row("則る","のっとる","N3","v5r|vi",
        "tuân theo (quy tắc) | làm theo | phù hợp với",
        "to follow (a rule, precedent, style, etc.) | to conform to | to be in accordance with","1404080"),
    row("即刻","そっこく","N3","adv",
        "ngay lập tức | ngay tức khắc | tức thì",
        "immediately | at once | instantly","1404170"),
    row("即座","そくざ","N3","adj-na|n",
        "ngay tức thì | tại chỗ | tức thời | tức khắc",
        "immediate | right there on the spot | impromptu | instant | instantaneous","1404180"),
    row("即死","そくし","N3","n|vs|vi",
        "chết tức thì | chết ngay tại chỗ",
        "instant death","1404200"),
    row("即興","そっきょう","N3","adj-no|n",
        "ứng tấu | ứng khẩu | ứng biến | ngẫu hứng",
        "improvisation | improvised | impromptu | extempore | ad-lib | off-the-cuff","1404130"),
    row("即断","そくだん","N3","n|vs|vt",
        "quyết định nhanh | phán đoán tức thời",
        "prompt decision | snap judgement | snap judgment","1404250"),
    row("即日","そくじつ","N3","n|adv",
        "ngay trong ngày | cùng ngày",
        "(on) the same day","1404280"),
    row("即答","そくとう","N3","n|vs|vi",
        "trả lời ngay | đáp ngay tức thì",
        "immediate reply","1404270"),
    row("即席","そくせき","N3","adj-no|adj-na|n",
        "ứng tấu | ứng biến | tức thời | mì ăn liền",
        "impromptu | improvised | extempore | ad-lib | instant (e.g. ramen)","1404240"),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
