# -*- coding: utf-8 -*-
"""Build N1 ready wave 041 — formal/colloquial nouns + 慣用句 (set 41)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-041.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("取り付く","とりつく","v5k|vi","bám lấy | níu giữ | bắt tay vào | ám (vong/ý nghĩ) | nắm được manh mối","to cling to | to set about (doing) | to possess (of a spirit)","1326900"),
    ("鳥目","とりめ","n|adj-no","quáng gà | bệnh mù đêm | chứng quáng gà","night-blindness","1796150"),
    ("泥沼化","どろぬまか","n|vs","sa lầy | lún sâu bế tắc | kéo dài dây dưa | rơi vào vũng lầy","bogging down | turning into a quagmire","2800320"),
    ("団栗","どんぐり","n","quả sồi | hạt dẻ rừng | hạt sồi (団栗の背比べ)","an acorn","1419200"),
    ("飛んだ","とんだ","adj-pn|adv","tai hại | tệ hại | ngoài dự liệu | khủng khiếp | quá ư","unexpected | terrible | outrageous | extremely","1008770"),
    ("情け容赦","なさけようしゃ","n","sự nương tay | lòng khoan dung (情け容赦もなく: không chút nương tay)","mercy | leniency","1750460"),
    ("何食わぬ顔","なにくわぬかお","exp|n","vẻ mặt tỉnh bơ | thản nhiên như không | giả ngây | mặt tỉnh queo","an innocent look | a nonchalant air","1189080"),
    ("生返事","なまへんじ","n|vs|vi","trả lời lấy lệ | đáp ậm ừ | trả lời hờ hững | đáp qua loa","a half-hearted reply | a vague answer","1642560"),
    ("涙腺","るいせん","n","tuyến lệ | tuyến nước mắt (涙腺が緩い: mau nước mắt)","the tear gland | the lacrimal gland","1644740"),
    ("名うて","なうて","adj-no","khét tiếng | nổi danh | có tiếng | trứ danh","notorious | famous","2642430"),
    ("難色","なんしょく","n","vẻ khó chịu | thái độ phản đối | sự miễn cưỡng | tỏ ý không bằng lòng","disapproval | reluctance","1461000"),
    ("匂わせる","におわせる","v1|vt","tỏa hương | bóng gió ám chỉ | ngụ ý | gợi ý xa xôi","to give off a scent | to hint at | to insinuate","1463470"),
    ("苦笑い","にがわらい","n|vs|vi","cười gượng | cười khổ | cười nhạt | cười méo xệch","a bitter smile | a wry smile","1244510"),
    ("逃げ口上","にげこうじょう","n","lời thoái thác | cớ lảng tránh | viện cớ | nói tránh né","an excuse | an evasion | a subterfuge","1808400"),
    ("二束","ふたたば","n","hai bó | hai nắm | hai chùm (二束三文: rẻ như bèo)","two bunches | two bundles","2038520"),
    ("二の足","にのあし","exp|n","bước thứ hai | sự chần chừ | do dự (二の足を踏む)","second step | hesitation","1461290"),
    ("人気者","にんきもの","n","người được yêu thích | ngôi sao | người nổi tiếng | được lòng mọi người","a popular person | a favorite","1367030"),
    ("糠","ぬか","n","cám gạo | cám | trấu mịn (糠喜び: mừng hụt)","rice bran","1918540"),
    ("盗み聞き","ぬすみぎき","n|vs|vt","nghe lén | nghe trộm | rình nghe | nghe ngóng","eavesdropping | wiretapping","1643370"),
    ("濡れ衣","ぬれぎぬ","n","tội oan | bị vu oan | nỗi oan | mang tiếng oan (濡れ衣を着せる)","a false accusation | a groundless charge","1819830"),
    ("願い下げ","ねがいさげ","n","xin rút lại | từ chối khéo | xin miễn | thôi không nhận","withdrawal | begging off | refusing","1666270"),
    ("猫かぶり","ねこかぶり","n","giả nai | giả vờ hiền lành | đeo mặt nạ | sói đội lốt cừu","feigned innocence | a wolf in sheep's clothing","1467690"),
    ("根城","ねじろ","n","căn cứ | sào huyệt | đại bản doanh | tổng hành dinh","a stronghold | a base of operations","1290190"),
    ("鼠算","ねずみざん","n","cấp số nhân | sinh sôi như chuột | tăng vọt theo cấp số","geometric progression | multiplying like rats","1703670"),
    ("寝ぼけ","ねぼけ","n","ngái ngủ | còn lơ mơ chưa tỉnh | nửa tỉnh nửa mê","being still half-asleep","1792930"),
    ("能天気","のうてんき","adj-na|n","vô tư lự | hời hợt | vô lo | sống thờ ơ thiếu suy nghĩ","carefree | thoughtless | happy-go-lucky","2027320"),
    ("のけ者","のけもの","n","kẻ bị ruồng bỏ | người bị cô lập | kẻ bị gạt ra rìa | kẻ lạc loài","an outcast | a pariah | the odd one out","1711220"),
    ("熨斗","のし","n","noshi (dải bào ngư khô gói giấy đính trên quà tặng Nhật)","noshi (decoration attached to a gift)","1569080"),
    ("咽喉","いんこう","n","yết hầu | cuống họng | vị trí then chốt | điểm trọng yếu","the throat | a vital passage | a key position","1168590"),
    ("暖簾分け","のれんわけ","n|vs|vi","cho nhân viên mở chi nhánh cùng thương hiệu | nhượng hiệu cho người làm lâu","helping a loyal employee open a branch shop","2835495"),
    ("拍子抜け","ひょうしぬけ","n|vs|vi|adj-no","cụt hứng | hụt hẫng | mất hứng | tẽn tò | thất vọng","an anticlimax | a let-down | loss of interest","1690650"),
    ("白紙","はくし","n|adj-no","giấy trắng | tờ giấy trắng | trạng thái ban đầu | xóa sạch làm lại (白紙に戻す)","white paper | a blank slate | starting over","1475200"),
    ("端折る","はしょる","v5r|vt","xắn vạt áo | rút gọn | lược bớt | bỏ qua | cắt ngắn (câu chuyện)","to tuck up | to abridge | to cut short | to omit","1581620"),
    ("旗印","はたじるし","n","biểu tượng trên cờ | ngọn cờ | khẩu hiệu | tôn chỉ | mục tiêu","an emblem on a banner | a slogan | a cause","1614430"),
    ("鉢合わせ","はちあわせ","n|vs|vi","đụng đầu | va vào nhau | chạm trán bất ngờ | tình cờ gặp","bumping heads | running into | an unexpected encounter","1477100"),
    ("鼻歌","はなうた","n","hát nghêu ngao | ngân nga | nhẩm hát khe khẽ","humming | crooning","1486850"),
    ("鼻息","はないき","n","hơi thở mũi | khí thế hăng hái | sự phấn khích (鼻息が荒い)","nasal breathing | one's excitement or eagerness","1583350"),
    ("鼻緒","はなお","n","quai guốc | quai dép | dây xỏ guốc geta","a sandal strap | a geta strap","1487040"),
    ("歯抜け","はぬけ","n|adj-no","rụng răng | sún răng | thiếu răng | hổng chỗ","missing teeth | toothlessness","1770190"),
    ("羽振り","はぶり","n","thế lực | uy thế | sự sung túc oai phong | sự vỗ cánh (羽振りがいい)","influence | power | flapping of wings","1171790"),
    ("破天荒","はてんこう","adj-na|n","chưa từng có | phá lệ | táo bạo phóng túng | ngông cuồng vô tiền khoáng hậu","unprecedented | daring | wild | unconventional","1471410"),
    ("はみ出す","はみだす","v5s|vi","lòi ra | tràn ra | thò ra ngoài | vượt quá | bị đẩy ra","to protrude | to stick out | to exceed | to be forced out","1601060"),
    ("腹いせ","はらいせ","n","trả đũa | trả thù cho hả giận | trút giận | báo thù","retaliation | revenge (to vent one's anger)","1748370"),
    ("半可通","はんかつう","n|adj-na","biết nửa vời | ra vẻ thông thạo | hiểu lõm bõm | thầy dùi nửa mùa","superficial knowledge | a dilettante | a know-it-all","1478950"),
    ("半端者","はんぱもの","n","kẻ ngớ ngẩn | đồ vô tích sự | kẻ dở hơi | đầu óc nửa mùa","a halfwit | a fool | a blockhead","1679060"),
    ("日陰者","ひかげもの","n","kẻ sống trong bóng tối | người bị xã hội ruồng bỏ | kẻ có dĩ vãng | người sống ẩn dật","a social outcast | a person with something to hide","1730440"),
    ("引け目","ひけめ","n","mặc cảm | tự ti | điểm yếu | sự thua kém (引け目を感じる)","a sense of inferiority | one's weak point","1169310"),
    ("膝詰め","ひざづめ","n|adj-no","ngồi đối mặt | mặt đối mặt | bàn bạc trực diện | thẳng thắn đối chất","sitting knee-to-knee | face-to-face","1721960"),
    ("左前","ひだりまえ","n","mặc áo vạt trái (kiểu khâm liệm) | sa sút | suy thoái | làm ăn thất bát","wearing a kimono right-over-left | an economic downturn","1290950"),
    ("人目","ひとめ","n","ánh mắt người đời | sự chú ý của công chúng | con mắt thiên hạ (人目を引く)","public notice | the public eye","1580760"),
    ("火の用心","ひのようじん","exp","cẩn thận lửa | đề phòng hỏa hoạn | coi chừng cháy nổ | giữ gìn phòng cháy","be careful about fire | watch out for fire","2416810"),
    ("日歩","ひぶ","n","lãi suất ngày | tiền lãi tính theo ngày","daily interest | a daily rate","1464410"),
    ("非の打ち所","ひのうちどころ","exp|n","điểm để chê trách | khuyết điểm | chỗ sơ hở (非の打ち所がない: hoàn hảo)","a fault | a flaw | a weak point","2865927"),
    ("百も承知","ひゃくもしょうち","exp","biết thừa | thừa hiểu | rõ mười mươi | quá rõ","knowing only too well | being fully aware","2126760"),
    ("冷や水","ひやみず","n","nước lạnh | nước mát (年寄りの冷や水: già mà còn liều)","cold water","1556790"),
    ("日和","ひより","n","thời tiết | tiết trời đẹp | ngày quang đãng | tình hình | thời cơ","the weather | fine weather | the situation","1464950"),
    ("ひれ伏す","ひれふす","v5s|vi","phủ phục | quỳ rạp | sụp lạy | cúi rạp mình","to prostrate oneself (before)","1507810"),
    ("頻り","しきり","adj-na","liên tục | dồn dập | không ngớt | mãnh liệt | dữ dội","frequent | continual | intense | severe","2017760"),
    ("貧乏くじ","びんぼうくじ","n","lá thăm xui xẻo | phần thiệt thòi | rút trúng vận đen | phần hẩm hiu","the short end of the stick | a bad bargain","1490970"),
    ("風采","ふうさい","n","phong thái | dáng vẻ bề ngoài | diện mạo | tướng mạo","appearance | air | mien","1625020"),
    ("俯く","うつむく","v5k|vi","cúi đầu | cúi mặt | nhìn xuống | gục mặt","to hang one's head | to look down","1563570"),
    ("不気味","ぶきみ","adj-na","rùng rợn | ghê rợn | kỳ quái | đáng sợ | u ám đáng ngại","weird | eerie | ominous | creepy","1491830"),
    ("不細工","ぶさいく","adj-na|n","vụng về | lóng ngóng | xấu xí | thô kệch | làm ẩu","clumsy | poorly made | ugly | unattractive","1492440"),
    ("無沙汰","ぶさた","n|vs|vi","lâu không liên lạc | bặt tin | lâu rồi không thư từ (ご無沙汰: lâu không gặp)","not contacting for a while | a long silence","1672130"),
    ("不調法","ぶちょうほう","adj-na|n","vụng về | thất lễ | sơ suất | bất cẩn | lỡ làng","impoliteness | clumsiness | carelessness","1603160"),
    ("仏頂","ぶっちょう","n|adj-na","đỉnh đầu Phật | vẻ lạnh lùng cau có (仏頂面: mặt khó đăm đăm)","brusqueness | grumpiness","2185920"),
    ("無難","ぶなん","adj-na|n","an toàn | ổn thỏa | không có gì để chê | vừa phải | tạm ổn","safe | innocuous | passable | acceptable","1530750"),
    ("不文律","ふぶんりつ","n","luật bất thành văn | quy tắc ngầm | lệ không thành văn","an unwritten law | an unwritten rule","1494780"),
    ("へそ曲がり","へそまがり","n|adj-na|adj-no","cố chấp ngang bướng | tính khó chiều | kẻ trái khoáy | gàn dở","perverseness | a contrary person","1571220"),
    ("減らず口","へらずぐち","n","cãi cố | nói lý sự cùn | cãi chày cãi cối | nói vớt vát (減らず口を叩く)","impudent talk | talking back | needless retort","1682840"),
    ("弁え","わきまえ","n","sự phân biệt phải trái | ý thức chừng mực | hiểu biết | sự nhận thức","discernment | discretion | good sense","2516660"),
    ("朴念仁","ぼくねんじん","n","kẻ lầm lì khó gần | người cứng đầu | đồ ngốc nghếch | kẻ vô tâm","a quiet unsociable person | a blockhead","1521750"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
