# -*- coding: utf-8 -*-
"""Build N1 ready wave 073 — compound nouns (-te, -yaku, -nin, -gyou, -waza) (set 73)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-073.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("使い手","つかいて","n","người sử dụng | bậc thầy (kiếm/võ) | người dùng | kẻ tiêu xài hoang","a user | a master (of a skill)","1305840"),
    ("書き手","かきて","n","người viết | tác giả | người vẽ | nhà thư pháp | cây bút cừ khôi","a writer | a skilful writer","1701600"),
    ("作り手","つくりて","n","người làm | người sáng tạo | nhà sản xuất | người chế tác | nông dân","a maker | a creator | a builder","1597880"),
    ("担い手","にないて","n","người gánh vác | người đảm đương | trụ cột | người chịu trách nhiệm | lực lượng nòng cốt","a bearer | a person in charge | a key supporter","1638080"),
    ("聞き手","ききて","n","người nghe | thính giả | khán giả | người phỏng vấn | người đặt câu hỏi","a listener | an audience | an interviewer","1505810"),
    ("話し手","はなして","n","người nói | diễn giả | người giỏi ăn nói | người kể","a speaker | a good talker","1562330"),
    ("受け手","うけて","n","người nhận | bên tiếp nhận | người xem | người tiếp thu","a receiver | the receiving side","1697660"),
    ("送り手","おくりて","n","người gửi | bên truyền đi | người phát","a sender","1709610"),
    ("乗り手","のりて","n","người cưỡi | tay đua | kỵ sĩ giỏi | hành khách | người điều khiển","a rider | a good rider","1600500"),
    ("買い手","かいて","n","người mua | bên mua | khách hàng | người tiêu thụ","a buyer","1589700"),
    ("売り手","うりて","n","người bán | bên bán | người chào hàng | nhà cung cấp","a seller | a vendor","1588540"),
    ("借り手","かりて","n","người vay | con nợ | người thuê | bên đi vay","a borrower | a tenant","1323680"),
    ("貸し手","かして","n","người cho vay | chủ nợ | bên cho vay | người cho thuê","a lender","1824910"),
    ("取り手","とりて","n","người nhận | người tiếp nhận | cao thủ (judo/sumo) | người bốc bài (karuta)","a recipient | a skilled practitioner","1633410"),
    ("歌い手","うたいて","n","ca sĩ | người hát | giọng ca | ca sĩ nghiệp dư đăng video","a singer | a vocalist","1662010"),
    ("弾き手","ひきて","n","người chơi nhạc cụ | nhạc công | người biểu diễn (đàn)","a player (of an instrument)","1801620"),
    ("読み手","よみて","n","người đọc | độc giả | người đọc bài (karuta) | người làm thơ","a reader | a composer (of poems)","1456220"),
    ("やり手","やりて","n","người tài giỏi | tay lão luyện | người tháo vát | kẻ năng nổ | tú bà","a capable person | a go-getter | a hotshot","1716650"),
    ("語り手","かたりて","n","người kể chuyện | người dẫn chuyện | người thuyết minh | người trần thuật","a narrator | a storyteller","1270970"),
    ("働き手","はたらきて","n","trụ cột gia đình | người lao động | lao động chính | người làm việc giỏi","a breadwinner | a worker","1582340"),
    ("稼ぎ手","かせぎて","n","trụ cột kinh tế | người kiếm tiền chính | lao động chính trong nhà","a breadwinner | a hard worker","1194440"),
    ("若手","わかて","n|adj-no","người trẻ | lớp trẻ | thế hệ trẻ | tay trẻ","a young person","1324360"),
    ("古手","ふるて","n|adj-no|adj-na","đồ cũ | người kỳ cựu | nhân viên lâu năm | lối cũ | sờn rách","a used article | a veteran | an old-timer","1265520"),
    ("痛手","いたで","n","đòn nặng | tổn thất lớn | vết thương trầm trọng | cú sốc nặng","a serious wound | a hard blow","1432780"),
    ("薄手","うすで","adj-no|adj-na|n","mỏng | loại mỏng | hời hợt | nông cạn | vết thương nhẹ","thin (make) | superficial | a slight wound","1621510"),
    ("厚手","あつで","adj-no|adj-na|n","dày | loại dày | (vải/giấy) dày dặn | nặng","thick (make) | heavy","1275470"),
    ("横手","よこて","n|adj-no","bên cạnh | mé bên | một bên | phần bên (lưỡi kiếm)","the side | beside","1613660"),
    ("土手","どて","n","bờ đê | đê | bờ kè | con đê","an embankment | a bank","1445370"),
    ("平手","ひらて","n","bàn tay xòe | tát bằng lòng bàn tay | chơi ngang cơ | không chấp","an open palm | playing on equal terms","1507380"),
    ("小手","こて","n","cẳng tay | phần cánh tay dưới | bao tay (kiếm đạo)","the forearm","1743460"),
    ("助っ人","すけっと","n","người trợ giúp | viện binh | người hỗ trợ | ngoại binh (đội thể thao)","a helper | a backer | a foreign player","1344500"),
    ("火付け役","ひつけやく","n","kẻ châm ngòi | người khởi xướng | kẻ kích động | người mở màn | kẻ gây rối","an instigator | an initiator","1613790"),
    ("案内役","あんないやく","n","người hướng dẫn | hướng dẫn viên | chủ tiệc | người dẫn đường","a guide | a host","2125860"),
    ("進行役","しんこうやく","n","người điều phối | người dẫn chương trình | người chủ trì | MC","a facilitator | a moderator","2239510"),
    ("調整役","ちょうせいやく","n","người điều phối | vai trò dàn xếp | người hòa giải | điều hợp viên","a coordinator","2571100"),
    ("相談役","そうだんやく","n","cố vấn | người tư vấn | người để hỏi ý kiến | tham mưu","a counselor | an adviser","1749250"),
    ("世話役","せわやく","n","người quản lý | người chăm lo | người trông coi | người lo việc","a manager | a caretaker","1753910"),
    ("取締役","とりしまりやく","n","giám đốc | thành viên hội đồng quản trị | ủy viên ban giám đốc","a company director | a board member","1610920"),
    ("監査役","かんさやく","n","kiểm soát viên | thanh tra | người kiểm toán nội bộ | giám sát viên","an auditor | an inspector","1213650"),
    ("仕掛け人","しかけにん","n","kẻ chủ mưu | người gài bẫy | kẻ giật dây | người dàn dựng","an instigator | a schemer","1817570"),
    ("仕事人","しごとにん","n","người chuyên nghiệp | tay nghề cao | người làm việc chuẩn xác | sát thủ chuyên nghiệp","a professional | a person good at their job","2759010"),
    ("請負人","うけおいにん","n","nhà thầu | người nhận khoán | người thầu công trình","a contractor","1381340"),
    ("発起人","ほっきにん","n","người khởi xướng | người sáng lập | người đề xướng | người chủ trì lập","an originator | a promoter","1611560"),
    ("代理人","だいりにん","n","người đại diện | người ủy quyền | luật sư | người được ủy nhiệm","a proxy | an agent | a representative","1412470"),
    ("管財人","かんざいにん","n","người quản lý tài sản | người được ủy thác | quản tài viên | người tiếp quản phá sản","a trustee | a receiver","1665840"),
    ("名義人","めいぎにん","n","người đứng tên | chủ sở hữu hợp pháp | người có tên trên giấy tờ","the holder of a title (deed)","1752490"),
    ("旅人","たびびと","n","lữ khách | khách lữ hành | người đi đường | du khách","a traveller | a wayfarer","1553210"),
    ("狩人","かりゅうど","n","thợ săn | người đi săn | tay săn bắn","a hunter","1328750"),
    ("仲買人","なかがいにん","n","người môi giới | trung gian | cò mồi | người buôn trung gian","a broker | a middleman","1426040"),
    ("両替商","りょうがえしょう","n","nghề đổi tiền | tiệm đổi tiền | nhà buôn đổi tiền","the money-exchange business","1553850"),
    ("御用達","ごようたし","n-suf","nhà cung cấp (hoàng gia) | nơi được giới nào đó ưa chuộng | thương hiệu được tín nhiệm","a purveyor (to the Imperial Household)","1694010"),
    ("生業","なりわい","n","kế sinh nhai | nghề nghiệp | nghề kiếm sống | sinh kế","an occupation | a livelihood","1645430"),
    ("内職","ないしょく","n|vs|vi","nghề tay trái | việc làm thêm tại nhà | gia công ở nhà | làm việc riêng (trong giờ học)","a side job | working from home | doing other things in class","1458540"),
    ("天職","てんしょく","n","thiên chức | nghề trời định | sứ mệnh cao cả | công việc lý tưởng","a vocation | a calling | a lifework","1439440"),
    ("休業","きゅうぎょう","n|vs|vi","tạm nghỉ kinh doanh | đóng cửa tạm thời | nghỉ bán | ngừng hoạt động","suspension of business | temporary closure","1227700"),
    ("従業","じゅうぎょう","n|vs|vi","làm việc | đang làm việc | sự làm thuê (従業員)","employment","1335240"),
    ("神業","かみわざ","n","tuyệt kỹ | kỳ tích siêu phàm | điều thần kỳ | tài nghệ phi thường | nghi lễ Thần đạo","a divine work | a superhuman feat","1364510"),
    ("力業","ちからわざ","n","việc nặng nhọc | sức mạnh cơ bắp | kỳ công sức lực | lao động chân tay","heavy work | a feat of strength","1554950"),
    ("荒業","あらわざ","n","lao động nặng | việc nặng nhọc | đòn mạnh | thế đánh dũng mãnh | nước cờ táo bạo","heavy labour | a powerful technique","1671240"),
    ("離れ業","はなれわざ","n","tuyệt chiêu | màn mạo hiểm | kỳ tích táo bạo | pha biểu diễn ngoạn mục","a stunt | a feat","1821570"),
    ("早業","はやわざ","n","thủ pháp nhanh gọn | tài khéo thoăn thoắt | màn ảo thuật nhanh tay","quick work | a clever feat","1608440"),
    ("大技","おおわざ","n","đòn lớn | thế đánh mạnh | nước đi táo bạo | chiêu uy lực (sumo/judo)","a bold, powerful move","1663740"),
    ("合わせ技","あわせわざ","n","đòn phối hợp | kết hợp kỹ thuật | hai waza-ari thắng | tổng hợp các cách","a combination of techniques","1857410"),
    ("裏技","うらわざ","n","mánh bí mật | thủ thuật riêng | tuyệt chiêu giấu | mẹo qua mặt | cheat (game)","a secret trick | a trick of the trade","1550240"),
    ("小技","こわざ","n","tiểu xảo | đòn nhỏ tinh tế | thủ thuật khéo | nước đi tinh vi (sumo/judo)","a delicate technique | a little trick","2414790"),
    ("仕事師","しごとし","n","thợ lành nghề | doanh nhân | kẻ mưu mô | người giỏi xoay xở","a workman | an enterpriser | a schemer","1304980"),
    ("奇計","きけい","n","kỳ kế | diệu kế bất ngờ | mưu kế lạ lùng | nước cờ độc đáo","a clever, outlandish scheme","1777960"),
    ("妙案","みょうあん","n","diệu kế | sáng kiến tuyệt vời | ý hay | kế sách tài tình","an ingenious idea | a bright idea","1528500"),
    ("名案","めいあん","n","ý hay | sáng kiến hay | kế hay | giải pháp tốt","a good idea","1531360"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
