# -*- coding: utf-8 -*-
"""Build N2 ready wave 032 — competition/sports, training, travel/tourism, aesthetics."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-032.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("予選","よせん","n|vs|vt","vòng loại | vòng sơ tuyển | sơ khảo","preliminary contest | qualifying round | screening","1543110"),
    ("決勝","けっしょう","n","chung kết | trận quyết định","decision of a contest | finals","1254320"),
    ("準決勝","じゅんけっしょう","n","bán kết","semifinal","1341580"),
    ("準優勝","じゅんゆうしょう","n|vs","á quân | về nhì","being the runner-up | finishing second","2022560"),
    ("入賞","にゅうしょう","n|vs|vi","đoạt giải | đạt thứ hạng cao","winning a prize | placing (high)","1466330"),
    ("完封","かんぷう","n|vs|vt","phong tỏa hoàn toàn | chặn đứng | thắng trắng","total blockage | shutout","1211600"),
    ("惜敗","せきはい","n|vs|vi","thua sít sao | thất bại đáng tiếc","regrettable defeat | defeat by a narrow margin","1382310"),
    ("快勝","かいしょう","n|vs|vi","thắng giòn giã | thắng dễ dàng","sweeping victory | easy victory","1613870"),
    ("圧勝","あっしょう","n|vs|vi","thắng áp đảo | thắng tuyệt đối","overwhelming victory | landslide victory","1153140"),
    ("辛勝","しんしょう","n|vs|vi","thắng chật vật | thắng sít sao","narrow victory","1365910"),
    ("完勝","かんしょう","n|vs|vi","thắng tuyệt đối | toàn thắng","complete victory | total victory","1614120"),
    ("連勝","れんしょう","n|vs|vt|vi","thắng liên tiếp | chuỗi thắng","consecutive victories | winning streak","1559560"),
    ("連敗","れんぱい","n|vs|vi","thua liên tiếp | chuỗi thua","consecutive defeats","1559750"),
    ("失点","しってん","n","điểm bị mất | bàn thua | sai sót","lost point | conceded goal | error","1320100"),
    ("反則","はんそく","n|vs|vi","phạm luật | phạm quy | vi phạm","foul | breaking the rules | infringement","1480650"),
    ("判定","はんてい","n|vs|vt","phán quyết | phân định | quyết định trọng tài","judgement | decision | ruling | verdict","1478660"),
    ("失格","しっかく","n|vs","bị loại | mất tư cách | bất xứng","disqualification | elimination | being unfit","1319820"),
    ("出場","しゅつじょう","n|vs|vi","tham gia (thi đấu) | ra sân | xuất hiện | xuất phát","participation | appearance | taking part","1339220"),
    ("欠場","けつじょう","n|vs|vi","vắng mặt | không tham gia thi đấu","absence | not taking part","1630620"),
    ("登場","とうじょう","n|vs|vi","xuất hiện | lên sân khấu | ra mắt | trình làng","entrance | appearance | emergence | advent","1444800"),
    ("退場","たいじょう","n|vs|vi","rời sân | bị đuổi | rút lui | hạ màn","leaving | exit | walkout","1619510"),
    ("強豪","きょうごう","n","đội/người mạnh | cường địch | thế lực mạnh","powerhouse | very strong player or team","1608600"),
    ("中堅","ちゅうけん","n|adj-no","nòng cốt | trụ cột | tầm trung | trung phong","nucleus | mainstay | mid-level | center field","1424090"),
    ("主力","しゅりょく","n","lực lượng chủ lực | sức mạnh chính | trọng tâm","main force | main strength | primary focus","1326430"),
    ("控え","ひかえ","n|n-suf","dự bị | dự phòng | ghi chú | bản sao | chờ đến lượt","reserve | spare | note | duplicate","1279050"),
    ("補欠","ほけつ","n|adj-no","dự bị | bổ sung | thay thế | người thế chỗ","filling a vacancy | substitute | spare","1514540"),
    ("鍛錬","たんれん","n|vs|vt","tôi luyện | rèn luyện | rèn giũa","tempering (metal) | toughening | training","1419170"),
    ("特訓","とっくん","n|vs|vt","luyện tập đặc biệt | huấn luyện cấp tốc","special training | crash course","1454850"),
    ("猛練習","もうれんしゅう","n","luyện tập gắt gao | tập luyện cật lực","very intensive training","1912360"),
    ("準備運動","じゅんびうんどう","n|vs","khởi động | bài tập khởi động","warming up | warming-up exercises","1938210"),
    ("持久走","じきゅうそう","n","chạy bền | chạy đường dài (thể dục)","marathon training in physical education","2115090"),
    ("柔軟体操","じゅうなんたいそう","n","thể dục mềm dẻo | bài tập kéo giãn","calisthenics","1827310"),
    ("瞬発力","しゅんぱつりょく","n","sức bộc phát | sức bật tức thì | phản xạ nhanh","explosive power | instantaneous force","2404720"),
    ("反射神経","はんしゃしんけい","n","phản xạ | thần kinh phản xạ","reflexes","1945490"),
    ("体型","たいけい","n","vóc dáng | hình thể | thể trạng","figure | body shape | physique","1409370"),
    ("骨太","ほねぶと","adj-no|adj-na|n","xương to | vạm vỡ | chắc chắn | (kế hoạch) vững","big-boned | sturdily built | solid","1667970"),
    ("頑健","がんけん","adj-na|n","cường tráng | khỏe mạnh | tráng kiện","robust | fit and healthy | sturdy","1217670"),
    ("強靭","きょうじん","adj-na|n","dẻo dai | bền bỉ | kiên cường","tough | strong | tenacious","1236340"),
    ("敏捷","びんしょう","adj-na|n","nhanh nhẹn | lanh lợi | nhạy bén","nimble | agile | quick | alert","1491080"),
    ("機敏","きびん","adj-na|n","nhanh nhạy | tháo vát | nhạy bén | tinh ý","quick | alert | astute | quick-witted","1221170"),
    ("寄り道","よりみち","n|vs|vi","ghé qua | rẽ vào | đi đường vòng","dropping in on the way | making a detour","1219650"),
    ("道草","みちくさ","n|vs|vi","la cà dọc đường | nấn ná | cỏ ven đường","loitering on the way | wayside grass","1611760"),
    ("迷子","まいご","n","trẻ lạc | người lạc đường","lost child | lost person","1532750"),
    ("案内","あんない","n|vs|vt","hướng dẫn | dẫn đường | chỉ dẫn | thông báo | mời","guidance | leading the way | information | invitation","1154860"),
    ("道案内","みちあんない","n|vs|vi","chỉ đường | dẫn đường | biển chỉ đường","guidance | showing the way | signpost","1641500"),
    ("標識","ひょうしき","n","biển báo | dấu hiệu | mốc | đèn hiệu","sign | mark | marker | beacon","1488700"),
    ("目印","めじるし","n","dấu mốc | dấu nhận biết | điểm mốc","mark (for identification) | landmark | sign","1535300"),
    ("道標","どうひょう","n","cột mốc chỉ đường | biển chỉ đường","guidepost | signpost","1454250"),
    ("旧跡","きゅうせき","n","di tích lịch sử | dấu tích xưa | phế tích","historic site | historic remains | ruins","1603010"),
    ("景勝","けいしょう","n|adj-no","thắng cảnh | cảnh đẹp | vị trí đắc địa","picturesque scenery | strategic location","1250850"),
    ("絶景","ぜっけい","n","cảnh tuyệt đẹp | tuyệt cảnh","superb view | picturesque scenery","1655930"),
    ("見物","けんぶつ","n|vs|vt","tham quan | xem | người xem | khán giả","sightseeing | watching | spectator","1260000"),
    ("行楽","こうらく","n","đi chơi | du ngoạn | dã ngoại","outing | excursion | pleasure trip","1281870"),
    ("保養地","ほようち","n","khu nghỉ dưỡng","health resort","1514020"),
    ("避暑","ひしょ","n|vs|vi","tránh nóng | đi nghỉ mát mùa hè","escaping the summer heat | summering","1484640"),
    ("避寒","ひかん","n|vs|vi","tránh rét | đi nghỉ đông nơi ấm áp","wintering | going somewhere warmer for winter","1751800"),
    ("湯治","とうじ","n|vs|vi","chữa bệnh bằng suối nóng | ngâm suối khoáng","hot-spring cure | taking the baths","1448620"),
    ("登山","とざん","n|vs|vi","leo núi | trèo núi","mountain climbing | mountaineering","1444780"),
    ("下山","げざん","n|vs|vi","xuống núi","descending a mountain | descent","1185050"),
    ("縦走","じゅうそう","n|vs|vi","đi dọc sống núi | leo nối nhiều đỉnh | chạy dọc","traversing a mountain range | running lengthwise","1635940"),
    ("野宿","のじゅく","n|vs|vi","ngủ ngoài trời | màn trời chiếu đất","sleeping outdoors | camping","1634050"),
    ("野営","やえい","n|vs|vi","cắm trại | hạ trại | đóng trại","camping | making camp","1655150"),
    ("宿泊","しゅくはく","n|vs|vi","lưu trú | nghỉ trọ | trọ lại","accommodation | lodging","1337300"),
    ("素泊まり","すどまり","n","nghỉ không kèm ăn | trọ chỉ ngủ không có bữa ăn","staying overnight without meals","1854140"),
    ("民宿","みんしゅく","n","nhà nghỉ tư nhân | homestay","guest house | bed and breakfast","1528950"),
    ("宿","やど","n","chỗ trọ | nhà nghỉ | quán trọ | nhà ở","lodging | inn | dwelling","1337190"),
    ("宿屋","やどや","n","quán trọ | nhà trọ","inn","1337230"),
    ("合宿","がっしゅく","n|vs|vi","ở chung tập huấn | trại tập trung | nhà tập thể","lodging together | training camp","1284850"),
    ("名物","めいぶつ","n","đặc sản | sản vật nổi tiếng | thứ nổi danh","famous product | speciality","1531810"),
    ("郷土","きょうど","n","quê hương | bản xứ | vùng quê | địa phương","native place | one's old home | locality","1238510"),
    ("風物","ふうぶつ","n","cảnh sắc | phong cảnh | nét đặc trưng vùng miền","natural features | scenery | characteristic scenes","1500040"),
    ("風情","ふぜい","n|suf","phong vị | nét duyên | vẻ tao nhã | hạng như... ","taste | elegance | charm | the likes of...","1499900"),
    ("趣","おもむき","n","ý vị | nội dung | nét duyên | vẻ tao nhã | phong vị","meaning | gist | charm | elegance | taste","1328960"),
    ("雅","みやび","n|adj-na","sự tao nhã | nét thanh lịch | vẻ lịch lãm","refinement | elegance | grace","2056470"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
