# -*- coding: utf-8 -*-
"""Build N1 ready wave 029 — 諺 proverbs (set 29)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-029.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("猿も木から落ちる","さるもきからおちる","exp|v1","khỉ cũng có lúc ngã cây | thánh nhân cũng có lúc lầm | ai cũng có thể sai","even monkeys fall from trees | anyone can make a mistake","1177410"),
    ("弘法も筆の誤り","こうぼうもふでのあやまり","exp","cao nhân cũng có lúc sai | bậc thầy cũng có khi lỗi","anyone can make a mistake | even Homer nods","2836534"),
    ("河童の川流れ","かっぱのかわながれ","exp","kappa cũng chết đuối | chuyên gia cũng có lúc thất bại | giỏi cũng có khi sảy chân","even an expert can make a mistake","1778490"),
    ("石の上にも三年","いしのうえにもさんねん","exp|n","có công mài sắt có ngày nên kim | kiên trì ắt thành công | ba năm trên đá","perseverance prevails | patience pays off","2141280"),
    ("急がば回れ","いそがばまわれ","exp","dục tốc bất đạt | muốn nhanh thì đi đường vòng | chậm mà chắc","more haste, less speed | slow and steady wins","1228590"),
    ("為せば成る","なせばなる","exp|v5r","có chí thì nên | quyết tâm ắt làm được | có công sẽ thành","where there's a will there's a way","2039140"),
    ("七転び八起き","ななころびやおき","n|vs|vi","thất bại không nản | ngã đâu đứng dậy đó | bảy lần ngã tám lần dậy","falling seven times, getting up eight | never giving up","1319410"),
    ("覆水盆に返らず","ふくすいぼんにかえらず","exp","bát nước đổ đi khó hốt lại | ván đã đóng thuyền | gạo nấu thành cơm","what's done is done | no use crying over spilt milk","1501510"),
    ("五十歩百歩","ごじっぽひゃっぽ","exp|n","nửa cân tám lạng | kẻ tám lạng người nửa cân | chẳng khác gì nhau","six of one, half a dozen of the other","1268340"),
    ("灯台下暗し","とうだいもとくらし","exp","gần chùa gọi bụt bằng anh | ngay dưới chân đèn lại tối | việc gần lại không thấy","it's hard to see what is under your nose","1448740"),
    ("能ある鷹は爪を隠す","のうあるたかはつめをかくす","exp|v5s","đại trí giả ngu | người tài không khoe | chim ưng giỏi giấu móng","a wise man keeps his talents in reserve","1470130"),
    ("餅は餅屋","もちはもちや","exp","nghề nào nghiệp nấy | chuyện ai người nấy rành | giao việc cho chuyên gia","every man knows his own business best","2420180"),
    ("良薬は口に苦し","りょうやくはくちににがし","exp","thuốc đắng dã tật | lời thật mất lòng | lời khuyên tốt khó nghe","good medicine tastes bitter | honest advice is hard to hear","2153120"),
    ("類は友を呼ぶ","るいはともをよぶ","exp|v5b","ngưu tầm ngưu mã tầm mã | đồng thanh tương ứng | nồi nào úp vung nấy","birds of a feather flock together","2077530"),
    ("渡りに船","わたりにふね","exp|n|adj-no","buồn ngủ gặp chiếu manh | đúng lúc cần | của trời cho | gặp may đúng lúc","a godsend | a timely offer | a lifesaver","2152720"),
    ("論語読みの論語知らず","ろんごよみのろんごしらず","exp","học mà không hành | biết lý thuyết không biết áp dụng | mọt sách","knowing a theory without being able to apply it","2152750"),
    ("雨垂れ石を穿つ","あまだれいしをうがつ","exp|v5t","nước chảy đá mòn | kiên trì ắt thành | mưa dầm thấm lâu","constant dripping wears away a stone","2141070"),
    ("一寸の虫にも五分の魂","いっすんのむしにもごぶのたましい","exp","con giun xéo lắm cũng quằn | kẻ yếu cũng có chí | đừng coi thường kẻ nhỏ","even a tiny bug will defend itself | don't underestimate the weak","2416670"),
    ("鬼に金棒","おににかなぼう","exp","như hổ thêm cánh | mạnh càng thêm mạnh | gậy sắt cho quỷ","making the strong even stronger","2141470"),
    ("帯に短し襷に長し","おびにみじかしたすきにながし","exp","dở dở ương ương | chẳng ra gì cả | nửa nạc nửa mỡ","neither one thing nor the other","2087430"),
    ("かわいい子には旅をさせよ","かわいいこにはたびをさせよ","exp","thương con cho roi cho vọt | yêu con thì cho con va vấp | rèn con trong gian khó","spare the rod and spoil the child","2103020"),
    ("木を見て森を見ず","きをみてもりをみず","exp","thấy cây không thấy rừng | sa đà tiểu tiết bỏ đại cục | nhìn hẹp","to not see the forest for the trees","2078140"),
    ("腐っても鯛","くさってもたい","exp","gừng càng già càng cay | hàng tốt vẫn là hàng tốt | đồ quý dù cũ vẫn quý","quality is quality | an old eagle beats a young crow","2120320"),
    ("口は災いの元","くちはわざわいのもと","exp","họa từ miệng mà ra | vạ miệng | lời nói gây tai họa | uốn lưỡi bảy lần","words can lead to disaster | the tongue is the root of calamity","2417350"),
    ("苦しい時の神頼み","くるしいときのかみだのみ","exp","nước đến chân mới nhảy | hoạn nạn mới cầu trời | bình thường không tu đến lúc khó mới khấn","man turns to God only in times of trouble","1244330"),
    ("転ばぬ先の杖","ころばぬさきのつえ","exp","phòng bệnh hơn chữa bệnh | lo xa khỏi họa | chuẩn bị trước khi vấp ngã","prevention is better than cure | look before you leap","2404390"),
    ("触らぬ神に祟りなし","さわらぬかみにたたりなし","exp","tránh voi chẳng xấu mặt nào | không đụng thì không họa | mặc kệ thì yên","let sleeping dogs lie","2418080"),
    ("親しき仲にも礼儀あり","したしきなかにもれいぎあり","exp","thân nhau mấy cũng phải giữ lễ | gần nhau vẫn cần phép tắc","good fences make good neighbors","2201620"),
    ("朱に交われば赤くなる","しゅにまじわればあかくなる","exp|v5r","gần mực thì đen gần đèn thì sáng | chọn bạn mà chơi | môi trường tạo con người","people take on the traits of those around them","2417820"),
    ("知らぬが仏","しらぬがほとけ","exp","không biết là sướng | ngu si hưởng thái bình | điếc không sợ súng","ignorance is bliss","2418960"),
    ("過ぎたるは猶及ばざるが如し","すぎたるはなおおよばざるがごとし","exp","thái quá bất cập | quá đà cũng như chưa đủ | làm gì cũng nên có chừng mực","too much is as bad as too little | less is more","2395090"),
    ("背に腹は代えられない","せにはらはかえられない","exp","cùng tắc biến | hy sinh cái nhỏ giữ cái lớn | không còn cách nào khác","you can't make an omelet without breaking eggs | needs must","2395090"),
    ("善は急げ","ぜんはいそげ","exp","việc tốt nên làm ngay | đừng chần chừ điều thiện | làm ngay khi còn nhiệt","strike while the iron is hot | do good without delay","1394290"),
    ("備えあれば憂いなし","そなえあればうれいなし","exp","có phòng bị thì không lo | lo xa khỏi buồn gần | cẩn tắc vô áy náy","if you are prepared you don't have to worry","2209960"),
    ("立つ鳥跡を濁さず","たつとりあとをにごさず","exp","chim bay không vẩn tổ | ra đi để lại sạch sẽ | giữ tiếng thơm khi rời đi","one should leave a place as clean as one found it","1551520"),
    ("旅は道連れ","たびはみちづれ","exp","đi đường có bạn | đường xa cần bạn đồng hành | có nhau mà sống","a fellow traveler makes the journey easier","2419260"),
    ("月とすっぽん","つきとすっぽん","exp","một trời một vực | khác nhau như mặt trăng với ba ba | chênh lệch hẳn","as different as chalk and cheese | poles apart","2418850"),
    ("鉄は熱いうちに打て","てつはあついうちにうて","exp","rèn sắt khi còn nóng | dạy con từ thuở còn thơ | làm ngay khi còn cơ hội","strike while the iron is hot","2168390"),
    ("出る杭は打たれる","でるくいはうたれる","exp|v1","cây cao đón gió | trội quá thì bị ghét | xuất đầu lộ diện thì bị dập","the nail that sticks out gets hammered down","1985430"),
    ("時は金なり","ときはかねなり","exp","thời gian là vàng bạc | tấc bóng tấc vàng","time is money","2140350"),
    ("所変われば品変わる","ところかわればしなかわる","exp|v5r","đất lề quê thói | mỗi nơi mỗi khác | nhập gia tùy tục","so many countries, so many customs","2417890"),
    ("毒を食らわば皿まで","どくをくらわばさらまで","exp","đã trót thì phải trét | làm tới cùng | đâm lao theo lao","in for a penny, in for a pound","2419250"),
    ("隣の芝生は青い","となりのしばふはあおい","exp|adj-i","cỏ nhà hàng xóm xanh hơn | đứng núi này trông núi nọ | của người luôn ngon hơn","the grass is always greener on the other side","1008660"),
    ("無くて七癖","なくてななくせ","exp","ai cũng có tật riêng | không ai hoàn hảo | nhân vô thập toàn","every person has their quirks","1642520"),
    ("情けは人の為ならず","なさけはひとのためならず","exp","làm ơn không thiệt | gieo nhân gặt quả | giúp người là giúp mình","kindness is never wasted | what goes around comes around","2419260"),
    ("二階から目薬","にかいからめぐすり","exp|n","nhỏ thuốc mắt từ tầng hai | việc khó đến vô vọng | cách làm vòng vo vô ích","a frustratingly roundabout and ineffective effort","2140170"),
    ("二兎を追う者は一兎をも得ず","にとをおうものはいっとをもえず","exp","đứng núi này trông núi nọ thì mất cả | tham thì thâm | đuổi hai thỏ mất cả hai","if you chase two hares you catch neither","2419260"),
    ("盗人にも三分の理","ぬすびとにもさんぶのり","exp","kẻ trộm cũng có lý lẽ | việc gì cũng có cớ | ngụy biện cho cái sai","even thieves have their reasons","2419170"),
    ("猫に小判","ねこにこばん","exp","đàn gảy tai trâu | đem ngọc cho mèo | của quý vào tay người không biết","casting pearls before swine","1467650"),
    ("寝耳に水","ねみみにみず","exp|n","như sét đánh ngang tai | bất ngờ choáng váng | nước dội vào tai khi ngủ","a bolt from the blue | a sudden shock","2011520"),
    ("喉元過ぎれば熱さを忘れる","のどもとすぎればあつさをわすれる","exp|v1","qua cơn hoạn nạn quên thầy quên thuốc | hết đau quên thầy | qua khỏi thì quên","once the danger has passed, it is forgotten","2417360"),
    ("花より団子","はなよりだんご","exp","thực dụng hơn hình thức | bánh hơn hoa | cái thực tế hơn cái hào nhoáng","substance over style | dumplings over flowers","1194530"),
    ("人の振り見て我が振り直せ","ひとのふりみてわがふりなおせ","exp","trông người mà ngẫm đến ta | lấy người làm gương sửa mình | thấy lỗi người sửa lỗi mình","learn from the faults of others to correct your own","2125080"),
    ("百聞は一見に如かず","ひゃくぶんはいっけんにしかず","exp","trăm nghe không bằng một thấy | mắt thấy hơn tai nghe","seeing once is better than hearing a hundred times","2153130"),
    ("火のない所に煙は立たぬ","ひのないところにけむりはたたぬ","exp","không có lửa làm sao có khói | có nguyên do mới sinh chuyện","there's no smoke without fire","2834564"),
    ("仏の顔も三度","ほとけのかおもさんど","exp","Bụt hiền cũng có lúc giận | sự nhẫn nhịn có giới hạn | quá tam ba bận","even a saint's patience has limits","1501770"),
    ("負けるが勝ち","まけるがかち","exp","thua là thắng | lùi một bước để tiến | nhường nhịn là khôn","sometimes you have to lose to win | losing is winning","2419540"),
    ("待てば海路の日和あり","まてばかいろのひよりあり","exp","ai chờ được ắt có ngày | kiên nhẫn sẽ gặp thời | chờ đợi sẽ có ngày đẹp trời","good things come to those who wait","2418850"),
    ("ミイラ取りがミイラになる","ミイラとりがミイラになる","exp","gậy ông đập lưng ông | đi thuyết phục lại bị thuyết phục | tự sa vào bẫy mình","the biter bit | going for wool and coming home shorn","2082110"),
    ("身から出た錆","みからでたさび","exp","gậy ông đập lưng ông | tự làm tự chịu | gieo gió gặt bão | tự chuốc lấy","reaping what you sow | suffering the consequences of one's own actions","1365530"),
    ("三つ子の魂百まで","みつごのたましいひゃくまで","exp","bản tính khó dời | dạy con từ thuở còn thơ | tính nết từ bé đến già","a leopard cannot change its spots | the child is father to the man","2252990"),
    ("昔取った杵柄","むかしとったきねづか","exp|n","nghề cũ không quên | tài xưa vẫn còn | kinh nghiệm cũ vẫn hữu dụng","skill learned in one's former days","2006670"),
    ("目は口ほどに物を言う","めはくちほどにものをいう","exp|v5u","ánh mắt nói thay lời | đôi mắt biết nói | mắt là cửa sổ tâm hồn","the eyes are as eloquent as the tongue","2153130"),
    ("門前の小僧習わぬ経を読む","もんぜんのこぞうならわぬきょうをよむ","exp|v5m","gần đèn thì sáng | học lỏm thành tài | môi trường dạy ta lúc nào không hay","you learn from your surroundings without realizing","2125080"),
    ("安物買いの銭失い","やすものがいのぜにうしない","exp","ham rẻ hóa đắt | tiền nào của nấy | mua rẻ mất tiền oan","you get what you pay for | penny wise pound foolish","2152900"),
    ("柳の下にいつも泥鰌はいない","やなぎのしたにいつもどじょうはいない","exp|adj-i","may mắn không lặp lại mãi | đừng trông chờ vận may cũ | họa phúc khôn lường","good luck doesn't always repeat itself","2419940"),
    ("病は気から","やまいはきから","exp","bệnh từ tâm mà ra | tinh thần quyết định sức khỏe | lo nghĩ sinh bệnh","sickness starts with the mind","2152850"),
    ("郷に入っては郷に従え","ごうにいってはごうにしたがえ","exp","nhập gia tùy tục | đáo giang tùy khúc | đến đâu theo phong tục đó","when in Rome, do as the Romans do","1238480"),
    ("弱り目に祟り目","よわりめにたたりめ","exp","họa vô đơn chí | đã khổ còn gặp hạn | phúc bất trùng lai họa vô đơn chí","misfortunes never come singly","1324640"),
    ("楽あれば苦あり","らくあればくあり","exp","có sướng có khổ | khổ tận cam lai | hết vui tới buồn | không hoa hồng nào không gai","after pleasure comes pain | no rose without a thorn","1978610"),
    ("逃がした魚は大きい","にがしたさかなはおおきい","exp|adj-i","con cá xổng luôn là con to | cái đã mất luôn tiếc | tiếc nuối cơ hội vuột mất","the one that got away always seems bigger","2419190"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
