# -*- coding: utf-8 -*-
"""Build N3 ready wave 046 — 101 freshly-curated N3 suru-nouns + common nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-046.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("協調","きょうちょう","n|vs|vi","hợp tác | hòa hợp | phối hợp","cooperation | conciliation | harmony | coordination","1235700"),
    ("提携","ていけい","n|vs|vt|vi","hợp tác | liên kết | bắt tay","cooperation | tie-up | partnership | alliance","1436380"),
    ("調整","ちょうせい","n|vs|vt","điều chỉnh | điều phối | tinh chỉnh","adjustment | regulation | coordination | tuning","1429200"),
    ("調節","ちょうせつ","n|vs|vt","điều tiết | điều chỉnh | kiểm soát","regulation | adjustment | control","1429240"),
    ("統一","とういつ","n|vs|vt","thống nhất | hợp nhất | đồng nhất","unity | unification | consolidation | uniformity","1449670"),
    ("統合","とうごう","n|vs|vt","tích hợp | hợp nhất | tổng hợp","integration | unification | combination | synthesis","1449760"),
    ("統制","とうせい","n|vs|vt","kiểm soát | quản chế | khống chế","regulation | control","1449820"),
    ("運営","うんえい","n|vs|vt","vận hành | điều hành | quản lý","management | administration | operation","1172690"),
    ("運用","うんよう","n|vs|vt","vận dụng | ứng dụng | điều hành (vốn)","making use of | application | effective management","1173090"),
    ("活用","かつよう","n|vs|vt|vi","tận dụng | vận dụng | chia (động từ)","practical use | making good use of | conjugation","1208460"),
    ("応用","おうよう","n|vs|vt","ứng dụng | áp dụng | vận dụng thực tế","(practical) application | putting to practical use","1180060"),
    ("共有","きょうゆう","n|vs|vt","chia sẻ | sở hữu chung | dùng chung","joint ownership | sharing (a viewpoint, files, etc.)","1235240"),
    ("所有","しょゆう","n|vs|vt","sở hữu | chiếm hữu","possession | ownership","1343390"),
    ("保有","ほゆう","n|vs|vt","nắm giữ | sở hữu | lưu giữ","possession | retention | holding | keeping","1513970"),
    ("蓄積","ちくせき","n|vs|vt|vi","tích lũy | tích trữ | dồn lại","accumulation | store","1422440"),
    ("募集","ぼしゅう","n|vs|vt","tuyển | chiêu mộ | kêu gọi (quyên góp)","recruitment | invitation | taking applications | raising (funds)","1514830"),
    ("操作","そうさ","n|vs|vt","thao tác | vận hành | thao túng","operation | handling | manipulation","1400050"),
    ("作動","さどう","n|vs|vi","hoạt động | vận hành | chạy","operation | functioning | running","1297890"),
    ("連動","れんどう","n|vs|vi","liên động | phối hợp | kết nối","operating together | being linked | interlocking","1559710"),
    ("同調","どうちょう","n|vs|vi","đồng điệu | hùa theo | đồng tình","conformity | alignment | sympathy | following suit","1453120"),
    ("共鳴","きょうめい","n|vs|vi","cộng hưởng | đồng cảm","resonance | sympathy (with an idea)","1235190"),
    ("共感","きょうかん","n|vs|vi","đồng cảm | thấu cảm","sympathy | empathy | identification (with someone)","1234370"),
    ("同感","どうかん","n|vs|vi","đồng cảm | cùng quan điểm | đồng tình","same feeling | sympathy | agreement | concurrence","1452020"),
    ("同意","どうい","n|vs|vi","đồng ý | tán thành | cùng nghĩa","agreement | consent | approval | same meaning","1451850"),
    ("了承","りょうしょう","n|vs|vt","chấp thuận | hiểu và đồng ý | thông cảm","acknowledgement | understanding | approval | consent","1606280"),
    ("承諾","しょうだく","n|vs|vt","đồng ý | chấp thuận | ưng thuận","consent | approval | acceptance | compliance","1349470"),
    ("受諾","じゅだく","n|vs|vt","chấp nhận | tiếp nhận","acceptance","1329960"),
    ("容認","ようにん","n|vs|vt","chấp nhận | dung thứ | cho phép","approval | acceptance | toleration","1545440"),
    ("黙認","もくにん","n|vs|vt","ngầm chấp thuận | làm ngơ | mặc nhận","tacit approval | connivance | overlooking","1535030"),
    ("否認","ひにん","n|vs|vt","phủ nhận | bác bỏ | không thừa nhận","denial | negation | repudiation","1483040"),
    ("拒否","きょひ","n|vs|vt","từ chối | cự tuyệt | phủ quyết","refusal | rejection | denial | veto","1232410"),
    ("辞退","じたい","n|vs|vi","từ chối | rút lui | thoái thác","declining | refusal | withdrawal | excusing oneself","1318990"),
    ("放棄","ほうき","n|vs|vt","từ bỏ | buông bỏ | bỏ cuộc","abandonment | renunciation | giving up | waiving","1516580"),
    ("強要","きょうよう","n|vs|vt","ép buộc | cưỡng ép | tống tiền","coercion | extortion | compulsion","1236580"),
    ("要請","ようせい","n|vs|vt|vi","yêu cầu | kêu gọi | đòi hỏi","appeal | call for | request | demand","1546780"),
    ("請求","せいきゅう","n|vs|vt","yêu cầu | đòi (thanh toán) | thỉnh cầu","claim | demand | billing | request","1381320"),
    ("勧誘","かんゆう","n|vs|vt","mời chào | rủ rê | thuyết phục","invitation | solicitation | canvassing | persuasion","1211120"),
    ("誘惑","ゆうわく","n|vs|vt","cám dỗ | quyến rũ | mê hoặc","temptation | allurement | lure | seduction","1542040"),
    ("解釈","かいしゃく","n|vs|vt","giải thích | diễn giải | lý giải","interpretation | explanation | construction","1199010"),
    ("解明","かいめい","n|vs|vt","làm sáng tỏ | giải mã | làm rõ","elucidation | clarification | unravelling","1199290"),
    ("究明","きゅうめい","n|vs|vt","điều tra làm rõ | truy cứu | tìm hiểu","investigation | finding out the facts | inquiring into","1230050"),
    ("分解","ぶんかい","n|vs|vt|vi","tháo rời | phân hủy | phân tích","disassembly | dismantling | decomposition | analysis","1503210"),
    ("分割","ぶんかつ","n|vs|vt","chia | phân chia | tách","partition | division | separation | splitting","1503280"),
    ("区分","くぶん","n|vs|vt","phân loại | phân khu | phân chia","division | demarcation | classification | sorting","1244230"),
    ("分類","ぶんるい","n|vs|vt","phân loại | phân nhóm | sắp xếp","classification | categorization | sorting","1504460"),
    ("選別","せんべつ","n|vs|vt","tuyển chọn | sàng lọc | phân loại","selection | sorting | culling | screening","1392390"),
    ("識別","しきべつ","n|vs|vt","phân biệt | nhận dạng | nhận biết","distinction | discrimination | identification","1319160"),
    ("判別","はんべつ","n|vs|vt","phân biệt | nhận định | phân định","distinction | distinguishing | discernment","1478710"),
    ("査定","さてい","n|vs|vt","thẩm định | định giá | đánh giá","assessment (of value) | revision (of a budget)","1291450"),
    ("審査","しんさ","n|vs|vt","thẩm tra | xét duyệt | giám định","judging | inspection | examination | review","1360380"),
    ("点検","てんけん","n|vs|vt","kiểm tra | rà soát | kiểm điểm","detailed inspection | thorough examination | checking","1441540"),
    ("観測","かんそく","n|vs|vt","quan trắc | quan sát | đo đạc | dự đoán","observation | measurement | prediction","1214980"),
    ("換算","かんさん","n|vs|vt","quy đổi | chuyển đổi | đổi (đơn vị)","conversion (e.g. yen to dollars) | exchange","1212820"),
    ("集計","しゅうけい","n|vs|vt","tổng hợp | thống kê | cộng dồn","totalization | aggregation | tally | summing up","1333640"),
    ("姿","すがた","n|n-suf","dáng vẻ | hình dáng | bóng hình | trang phục","figure | form | appearance | guise | state","1307710"),
    ("格好","かっこう","n|adj-na","hình dáng | dáng vẻ | tư thế | vừa vặn","shape | appearance | posture | style | suitable","1590480"),
    ("振る舞い","ふるまい","n","hành vi | cử chỉ | sự chiêu đãi","behavior | conduct | entertainment | treat","1952740"),
    ("行為","こうい","n","hành vi | hành động | việc làm","act | deed | conduct","1281830"),
    ("動作","どうさ","n|vs|vi","động tác | cử động | thao tác | (máy) chạy","movement | action | gesture | operation (of a machine)","1451350"),
    ("慣習","かんしゅう","n|vs","tập quán | thông lệ | quen thuộc","custom | convention | common practice","1212700"),
    ("儀式","ぎしき","n","nghi thức | nghi lễ | lễ nghi","ceremony | rite | ritual","1224700"),
    ("行事","ぎょうじ","n","sự kiện | hoạt động | lễ hội","event | function","1281930"),
    ("催し","もよおし","n","sự kiện | buổi lễ | buổi gặp mặt","event | festivities | function | social gathering","1292140"),
    ("配置","はいち","n|vs|vt","bố trí | sắp xếp | dàn trận","arrangement | deployment | layout | configuration","1473150"),
    ("設置","せっち","n|vs|vt","lắp đặt | thiết lập | thành lập","establishment | installation | institution","1386050"),
    ("装置","そうち","n|vs|vt","thiết bị | bộ máy | dụng cụ","equipment | device | apparatus | installation","1402360"),
    ("団体","だんたい","n","đoàn thể | tập thể | tổ chức","group | party | team | organization | association","1419270"),
    ("集団","しゅうだん","n","tập thể | nhóm | quần thể","group | mass","1333730"),
    ("民衆","みんしゅう","n","dân chúng | quần chúng | đại chúng","people | populace | masses","1528920"),
    ("庶民","しょみん","n","dân thường | thường dân | bình dân","common people | ordinary people | masses","1343560"),
    ("住人","じゅうにん","n","cư dân | người ở | dân cư","dweller | inhabitant | resident","1334110"),
    ("人物","じんぶつ","n","nhân vật | con người | nhân cách | người tài","person | character | figure | able person","1369070"),
    ("人材","じんざい","n","nhân tài | nhân lực | người có năng lực","capable person | talented person | human resources","1367760"),
    ("人格","じんかく","n","nhân cách | tính cách | phẩm cách","personality | character | individuality","1366730"),
    ("個性","こせい","n","cá tính | nét riêng | đặc trưng cá nhân","individuality | personality | character","1264960"),
    ("気質","きしつ","n","khí chất | tính khí | bản tính","disposition | temperament | nature | mentality","1222250"),
    ("本性","ほんしょう","n","bản tính | bản chất thật","true character | real nature","1522780"),
    ("気性","きしょう","n","tính khí | tính tình | bản tính","disposition | temperament | temper","1222380"),
    ("根性","こんじょう","n","tinh thần | nghị lực | bản lĩnh | bản tính","willpower | guts | grit | spirit | nature","1290210"),
    ("情熱","じょうねつ","n","nhiệt huyết | đam mê | nhiệt tình","passion | enthusiasm | zeal","1356330"),
    ("熱意","ねつい","n","nhiệt tình | nhiệt huyết | hăng hái","zeal | enthusiasm | ardor","1467760"),
    ("気力","きりょく","n","ý chí | nghị lực | sức lực tinh thần","willpower | energy | vitality","1222690"),
    ("活力","かつりょく","n","sức sống | sinh lực | năng lượng","vitality | energy | dynamism","1208480"),
    ("実力","じつりょく","n","thực lực | năng lực thật | sức mạnh","(real) ability | true strength | competency","1321530"),
    ("勢力","せいりょく","n","thế lực | sức mạnh | ảnh hưởng","influence | power | might | strength","1375150"),
    ("迫力","はくりょく","n","sức hút | sự ấn tượng | uy lực","impressiveness | impact | force | intensity","1475770"),
    ("魅力","みりょく","n","sức hút | sự quyến rũ | sức hấp dẫn","charm | fascination | attraction | appeal","1528150"),
    ("有力","ゆうりょく","adj-na|n","có thế lực | nổi bật | có khả năng","influential | prominent | strong | likely","1541710"),
    ("無力","むりょく","n|adj-na","bất lực | vô dụng | yếu kém","powerlessness | helplessness | incompetence","1531050"),
    ("全力","ぜんりょく","n","toàn lực | hết sức | dốc toàn lực","all one's power | one's utmost","1396390"),
    ("重力","じゅうりょく","n","trọng lực | lực hấp dẫn","gravity | gravitation","1336980"),
    ("圧力","あつりょく","n","áp lực | áp suất | sức ép","pressure | (political) pressure","1153340"),
    ("視力","しりょく","n","thị lực | tầm nhìn","eyesight | vision | visual acuity","1312150"),
    ("聴力","ちょうりょく","n","thính lực | khả năng nghe","hearing ability","1428950"),
    ("記憶力","きおくりょく","n","trí nhớ | khả năng ghi nhớ","memory | ability to remember","1795410"),
    ("集中力","しゅうちゅうりょく","n","khả năng tập trung | sự tập trung","(powers of) concentration | ability to concentrate","1937890"),
    ("判断力","はんだんりょく","n","khả năng phán đoán | sự nhận định","judgment | discernment","1478650"),
    ("想像力","そうぞうりょく","n","trí tưởng tượng | sức tưởng tượng","(power of) imagination","1749300"),
    ("創造力","そうぞうりょく","n","sức sáng tạo | khả năng sáng tạo","creative power | creativity","1398620"),
    ("表現力","ひょうげんりょく","n","khả năng biểu đạt | sức diễn đạt","power of expression | expressiveness","1945910"),
    ("影響力","えいきょうりょく","n","sức ảnh hưởng | tầm ảnh hưởng","influence | clout | leverage","1173680"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
