# -*- coding: utf-8 -*-
"""Build N3 ready wave 049 — 75 freshly-curated N3 education/transport/food/housing nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-049.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("学問","がくもん","n|vs|vi","học vấn | học thuật | kiến thức","study | scholarship | learning | knowledge","1207130"),
    ("講演","こうえん","n|vs|vt|vi","diễn thuyết | bài giảng | thuyết trình","lecture | address | speech","1282240"),
    ("演説","えんぜつ","n|vs|vi","diễn thuyết | bài phát biểu","speech | address","1176960"),
    ("講座","こうざ","n","khóa học | giảng tòa (đại học)","course (of lectures) | academic university unit","1282270"),
    ("教材","きょうざい","n","tài liệu giảng dạy | giáo cụ","teaching materials","1237110"),
    ("学科","がっか","n","môn học | ngành học | khoa","subject (of study) | course of study | department","1206590"),
    ("学部","がくぶ","n","khoa (đại học) | phân khoa","faculty (of a university) | school | department","1207080"),
    ("学年","がくねん","n","năm học | khối lớp","academic year | year in school | grade","1207030"),
    ("進学","しんがく","n|vs|vi","học lên | lên cấp học cao hơn","advancing to the next stage of education","1366010"),
    ("受験","じゅけん","n|vs|vt","dự thi | thi (tuyển sinh)","taking an (entrance) examination","1329740"),
    ("進路","しんろ","n","hướng đi | lộ trình | con đường tương lai","route | course | one's future course","1366200"),
    ("学歴","がくれき","n","học vấn | bằng cấp | quá trình học tập","academic background | academic credentials","1207200"),
    ("学位","がくい","n","học vị | bằng cấp","(academic) degree","1206540"),
    ("専攻","せんこう","n|vs|vt","chuyên ngành | chuyên môn","major subject | special study","1389780"),
    ("訓練","くんれん","n|vs|vt","huấn luyện | đào tạo | rèn luyện","training | drill | practice | discipline","1247470"),
    ("学者","がくしゃ","n","học giả | nhà nghiên cứu","scholar | academic | learned person","1206800"),
    ("児童","じどう","n","trẻ em | nhi đồng","children | juvenile","1315060"),
    ("幼児","ようじ","n","trẻ nhỏ | nhi đồng (chưa đi học)","young child | toddler","1545160"),
    ("横断","おうだん","n|vs|vi|vt","băng qua | cắt ngang | xuyên (đông-tây)","crossing (a road) | traversing | cutting across","1180900"),
    ("歩道","ほどう","n","vỉa hè | lối đi bộ","footpath | walkway | sidewalk","1514420"),
    ("車線","しゃせん","n","làn đường | làn xe","traffic lane | road lane","1323180"),
    ("線路","せんろ","n","đường ray | tuyến đường sắt","railway track | railway line | track","1391880"),
    ("下車","げしゃ","n|vs|vi","xuống xe | xuống tàu","alighting (from a train) | getting off","1185170"),
    ("発車","はっしゃ","n|vs|vi","khởi hành | xuất phát (xe, tàu)","departure (of a train, car) | starting","1477500"),
    ("停車","ていしゃ","n|vs|vi","dừng xe | đỗ xe (tàu)","stopping (of a train, car) | stop","1434960"),
    ("満員","まんいん","n|adj-no","kín chỗ | hết chỗ | chật kín người","full house | no vacancy | crowded","1526720"),
    ("運行","うんこう","n|vs|vt|vi","vận hành (tuyến xe, tàu) | sự di chuyển","operation (of a bus/train service) | movement (of a body)","1172750"),
    ("直通","ちょくつう","n|vs|vi","trực tiếp | đi thẳng | tuyến thẳng","direct line | through service | nonstop service","1431440"),
    ("高速","こうそく","adj-na|n","tốc độ cao | cao tốc","high-speed | rapid | highway | expressway","1283700"),
    ("燃料","ねんりょう","n","nhiên liệu","fuel","1469660"),
    ("給油","きゅうゆ","n|vs|vt|vi","tiếp nhiên liệu | đổ xăng | tra dầu","refueling | lubricating | oiling","1230340"),
    ("駐車","ちゅうしゃ","n|vs|vi","đỗ xe | đậu xe","parking (a vehicle)","1426910"),
    ("調理","ちょうり","n|vs|vt","nấu nướng | chế biến món ăn","cooking | food preparation","1429310"),
    ("食料","しょくりょう","n","thực phẩm | đồ ăn","food","1358670"),
    ("食糧","しょくりょう","n","lương thực | nguồn lương thực","food (esp. staple food) | provisions | rations","1358690"),
    ("満腹","まんぷく","n|vs|adj-na","no bụng | no nê | đầy đủ","full stomach | eating one's fill | full","1526890"),
    ("空腹","くうふく","n|adj-na","đói bụng | bụng đói","empty stomach | hunger","1246000"),
    ("食卓","しょくたく","n","bàn ăn","dining table","1358530"),
    ("食器","しょっき","n","bát đĩa | đồ dùng ăn uống","tableware","1358430"),
    ("容器","ようき","n","hộp đựng | vật chứa | bao bì","container | receptacle | vessel | packaging","1545370"),
    ("包装","ほうそう","n|vs|vt","đóng gói | bao gói","packing | wrapping","1515510"),
    ("加熱","かねつ","n|vs|vt","làm nóng | gia nhiệt | hâm","heating | application of heat","1190470"),
    ("家電","かでん","n","đồ điện gia dụng | điện máy","household (electrical) appliances","1192380"),
    ("寝具","しんぐ","n","chăn ga gối | đồ dùng ngủ","bedding | bedclothes","1360080"),
    ("浴室","よくしつ","n","phòng tắm","bathroom","1547460"),
    ("洗面所","せんめんじょ","n","phòng rửa mặt | nhà vệ sinh","washroom | bathroom","1391070"),
    ("建設","けんせつ","n|vs|vt","xây dựng | kiến thiết | thành lập","construction | establishment","1257420"),
    ("改築","かいちく","n|vs|vt","cải tạo | xây sửa lại | tu sửa","structural alteration | reconstruction | remodeling","1201020"),
    ("増築","ぞうちく","n|vs|vt","xây thêm | mở rộng công trình","addition to a building","1403320"),
    ("施工","せこう","n|vs|vt|vi","thi công | thực hiện công trình","construction | carrying out | workmanship","1618920"),
    ("材木","ざいもく","n","gỗ (xây dựng) | gỗ xẻ","wood (for building) | lumber | timber","1296660"),
    ("鉄筋","てっきん","n","cốt thép | thanh thép | bê tông cốt thép","rebar | reinforcing steel | reinforced concrete","1437830"),
    ("住宅","じゅうたく","n","nhà ở | nơi cư trú | khu dân cư","residence | housing | residential building","1334150"),
    ("団地","だんち","n","khu chung cư | khu tập thể","multi-unit apartments | apartment complex","1419300"),
    ("集合住宅","しゅうごうじゅうたく","n","chung cư | khu nhà ở tập thể","apartment building | housing complex","1813490"),
    ("賃貸","ちんたい","n|vs|vt","cho thuê | thuê (nhà)","leasing (out) | renting out | letting","1432030"),
    ("退去","たいきょ","n|vs|vt|vi","rời đi | sơ tán | dọn ra","departure | leaving | evacuation","1411370"),
    ("内装","ないそう","n|vs|vt","nội thất | trang trí bên trong","interior design | interior | upholstery","1458730"),
    ("外装","がいそう","n","ngoại thất | lớp vỏ ngoài | bao bì","exterior | packaging | cladding","1806840"),
    ("配管","はいかん","n|vs|vi","đường ống | hệ thống ống nước","plumbing | piping","1625610"),
    ("配線","はいせん","n|vs|vt|vi","đi dây điện | hệ thống dây","wiring","1473110"),
    ("換気","かんき","n|vs|vi","thông gió | thông khí","ventilation","1212780"),
    ("採光","さいこう","n|vs|vt|vi","lấy sáng | chiếu sáng tự nhiên","(natural) lighting (of an interior)","1741320"),
    ("防音","ぼうおん","n|vs|vi","cách âm | chống ồn","soundproofing","1520240"),
    ("耐震","たいしん","n|adj-no","chịu động đất | chống động đất","resistant to earthquakes","1410370"),
    ("省エネ","しょうエネ","n","tiết kiệm năng lượng","energy conservation","1351060"),
    ("眺め","ながめ","n","khung cảnh | tầm nhìn | quang cảnh","scene | view | prospect | outlook","1610960"),
    ("家庭","かてい","n","gia đình | mái ấm | hộ gia đình","home | household | family","1192280"),
    ("世帯","せたい","n","hộ gia đình | hộ","household | family","1374170"),
    ("夫妻","ふさい","n","vợ chồng | cặp vợ chồng","husband and wife | married couple","1496520"),
    ("独身","どくしん","adj-no|n","độc thân | chưa kết hôn","unmarried | single","1455850"),
    ("未婚","みこん","adj-no|n","chưa kết hôn | chưa lập gia đình","unmarried | not yet married","1527480"),
    ("婚約","こんやく","n|vs|vi","đính hôn | hứa hôn","engagement | betrothal","1289710"),
    ("妊娠","にんしん","n|vs|vi","mang thai | thai nghén","pregnancy | conception | gestation","1467350"),
    ("出産","しゅっさん","n|vs|vt|vi","sinh con | sinh đẻ | sinh nở","childbirth | (giving) birth | delivery","1339010"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
