# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-027.csv — 46 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-027.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("以降","いこう","N4","n|adv",
        "từ ... trở đi | sau đó | kể từ",
        "on and after | from ... onward | since",
        "1155110",
        "来月以降に始めます。","らいげついこうにはじめます。","Tôi bắt đầu từ tháng sau trở đi.","I will start from next month onward."),
    row("条約","じょうやく","N4","n",
        "hiệp ước | hiệp định | công ước | thỏa thuận",
        "treaty | pact | convention | agreement",
        "1356580",
        "条約を結びます。","じょうやくをむすびます。","Chúng tôi ký kết hiệp ước.","We conclude a treaty."),
    row("担当者","たんとうしゃ","N4","n",
        "người phụ trách | người có trách nhiệm | người liên hệ",
        "person in charge (of an area of work, etc.) | person responsible | contact (person)",
        "1418180",
        "担当者に連絡します。","たんとうしゃにれんらくします。","Tôi liên hệ người phụ trách.","I contact the person in charge."),
    row("変化","へんげ","N4","n|vs|vi",
        "hóa thân | biến hình (của thú hoặc linh hồn) | yêu quái | ma quái",
        "shapeshifting (of an animal or spirit) | goblin | ghost | apparition | bugbear | incarnation | transformation",
        "1510900",
        "狐が変化します。","きつねがへんげします。","Con cáo hóa thân.","The fox shapeshifts."),
    row("味付け","あじつけ","N4","n|vs|vt|vi",
        "nêm nếm | gia vị | tạo hương vị",
        "seasoning | flavour | flavor",
        "1526980",
        "味付けが大切です。","あじつけがたいせつです。","Nêm nếm rất quan trọng.","Seasoning is important."),
    row("気まぐれ","きまぐれ","N4","n|adj-na",
        "tính bất thường | thất thường | bất chợt | hay thay đổi",
        "whim | caprice | fancy | capricious | fickle | whimsical | impulsive | changeable | temperamental",
        "1591410",
        "気まぐれな人です。","きまぐれなひとです。","Đó là người thất thường.","They are a whimsical person."),
    row("凍る","こおる","N4","v5r|vi",
        "đóng băng | đông cứng",
        "to freeze | to become frozen | to freeze over",
        "1593100",
        "池が凍りました。","いけがこおりました。","Ao đã đóng băng.","The pond has frozen."),
    row("形","けい","N4","suf|n",
        "dạng | hình thức | tính từ (trong tiếng Nhật)",
        "form | adjective | i-adjective (in Japanese)",
        "2254010",
        "い形容詞は「い形」です。","いけいようしは「いけい」です。","Tính từ đuôi い là 「i-adjective」.","I-adjectives are the 「i form」."),
    row("夫婦","めおと","N4","n|n-pref",
        "vợ chồng | cặp đôi (lớn nhỏ) | bộ đôi vợ chồng",
        "married couple | husband and wife | man and wife | set of two (one large, one small) | pair (for husband and wife) | his and hers (e.g. teacups)",
        "2857591",
        "めおと茶碗を使います。","めおとちゃわんをつかいます。","Tôi dùng bộ chén vợ chồng.","I use a his-and-hers teacup set."),
    row("地域","ちいき","N4","n",
        "khu vực | vùng | địa phương | địa bàn",
        "area | region | district | locality",
        "1420800",
        "この地域に住んでいます。","このちいきにすんでいます。","Tôi sống ở khu vực này.","I live in this area."),
    row("リフォーム","リフォーム","N4","n|vs|vt",
        "cải tạo (nhà) | trang trí lại | sửa chữa | làm mới | sửa (quần áo)",
        "renovation (e.g. a house) | redecoration | refurbishment | makeover | alteration (e.g. of clothes) | re-tailoring | repair (e.g. of shoes)",
        "1142520",
        "家をリフォームします。","いえをリフォームします。","Tôi cải tạo ngôi nhà.","I renovate the house."),
    row("一方通行","いっぽうつうこう","N4","n|adj-no",
        "một chiều | giao thông một chiều | giao tiếp một phía",
        "one-way traffic | one-way (e.g. communication) | one-sided",
        "1166550",
        "ここは一方通行です。","ここはいっぽうつうこうです。","Đây là đường một chiều.","This is a one-way street."),
    row("確実性","かくじつせい","N4","n",
        "sự chắc chắn | tính xác thực | tính đáng tin cậy",
        "certainty",
        "1205840",
        "計画の確実性を高めます。","けいかくのかくじつせいをたかめます。","Tôi nâng cao tính chắc chắn của kế hoạch.","I increase the certainty of the plan."),
    row("間取り","まどり","N4","n",
        "mặt bằng (nhà) | sơ đồ phòng | bố trí phòng",
        "layout (of a house or apartment) | arrangement of rooms",
        "1215490",
        "間取りを確認します。","まどりをかくにんします。","Tôi xem mặt bằng nhà.","I check the room layout."),
    row("気さく","きさく","N4","adj-na",
        "thân thiện | cởi mở | hòa đồng | dễ gần | thẳng thắn",
        "friendly | openhearted | sociable | amiable | good-humored | good-humoured | frank | candid | willing | ready",
        "1221660",
        "気さくな人が好きです。","きさくなひとがすきです。","Tôi thích người cởi mở.","I like friendly people."),
    row("四半期","しはんき","N4","n",
        "quý (một năm) | quý tài chính",
        "quarter (of a year)",
        "1307330",
        "第一四半期の報告をします。","だいいちしはんきのほうこくをします。","Tôi báo cáo quý đầu tiên.","I report on the first quarter."),
    row("施設","しせつ","N4","n|vs|vt",
        "cơ sở | công trình | cơ sở vật chất | nhà dưỡng lão",
        "facility | facilities | institution | establishment | home (for the elderly, orphans, etc.)",
        "1310410",
        "福祉施設で働きます。","ふくししせつではたらきます。","Tôi làm việc tại cơ sở phúc lợi.","I work at a welfare facility."),
    row("従来","じゅうらい","N4","n|adv|adj-no",
        "từ trước đến nay | truyền thống | thông thường | hiện có",
        "up to now | so far | traditional | conventional | usual | existing",
        "1335400",
        "従来の方法を変えます。","じゅうらいのほうほうをかえます。","Tôi thay đổi phương pháp truyền thống.","I change the conventional method."),
    row("上半期","かみはんき","N4","n",
        "nửa đầu năm | nửa đầu năm tài chính",
        "first half of the year | first half of the fiscal year",
        "1354170",
        "上半期の売上を報告します。","かみはんきのうりあげをほうこくします。","Tôi báo cáo doanh thu nửa đầu năm.","I report the sales for the first half of the year."),
    row("鮮やか","あざやか","N4","adj-na",
        "sặc sỡ | rực rỡ | tươi sáng | xuất sắc | điêu luyện",
        "vivid | bright | brilliant | clear | fresh | vibrant | skillful | skilful | adroit | brilliant (performance, goal, etc.) | splendid | superb | magnificent | fine",
        "1392500",
        "鮮やかな色が好きです。","あざやかないろがすきです。","Tôi thích màu sắc rực rỡ.","I like vivid colors."),
    row("地球温暖化","ちきゅうおんだんか","N4","n",
        "sự nóng lên toàn cầu | biến đổi khí hậu | hiệu ứng nhà kính",
        "global warming",
        "1420980",
        "地球温暖化を止めましょう。","ちきゅうおんだんかをとめましょう。","Hãy ngăn sự nóng lên toàn cầu.","Let's stop global warming."),
    row("仲裁","ちゅうさい","N4","n|vs|vt",
        "trọng tài | hòa giải | dàn xếp | đứng ra làm trung gian",
        "arbitration | intercession | mediation",
        "1425900",
        "二人の仲裁をします。","ふたりのちゅうさいをします。","Tôi hòa giải cho hai người.","I mediate between the two."),
    row("仲直り","なかなおり","N4","n|vs|vi",
        "hòa giải | làm lành | kết bạn lại | giải quyết hiểu lầm",
        "reconciliation | making up (with) | making peace (with) | being friends again | patching up a quarrel",
        "1426000",
        "友達と仲直りしました。","ともだちとなかなおりしました。","Tôi đã làm lành với bạn.","I reconciled with my friend."),
    row("仲良し","なかよし","N4","n|adj-no|vs|vi",
        "bạn thân | tình bạn thân thiết | thân thiết",
        "close friendship | close friend | good friend | bosom buddy | chum | pal | intimate relations",
        "1426100",
        "二人は仲良しです。","ふたりはなかよしです。","Hai người rất thân nhau.","The two are close friends."),
    row("値下がり","ねさがり","N4","n|vs|vi",
        "giảm giá | sụt giá",
        "price decline | fall in price",
        "1430770",
        "物価が値下がりします。","ぶっかがねさがりします。","Giá cả sụt giảm.","Prices fall."),
    row("当初","とうしょ","N4","n|adj-no|adv",
        "lúc đầu | ban đầu | ban sơ | từ đầu",
        "beginning | start | outset | at first | at the beginning | initially | originally",
        "1449110",
        "当初の計画を変えません。","とうしょのけいかくをかえません。","Tôi không thay đổi kế hoạch ban đầu.","I don't change the original plan."),
    row("歩道橋","ほどうきょう","N4","n",
        "cầu vượt người đi bộ | cầu bộ hành",
        "footbridge | pedestrian bridge | pedestrian overpass",
        "1514430",
        "歩道橋を渡ります。","ほどうきょうをわたります。","Tôi đi qua cầu vượt bộ hành.","I cross the pedestrian bridge."),
    row("捧げる","ささげる","N4","v1|vt",
        "dâng lên | hiến dâng | cống hiến | hy sinh | tận hiến",
        "to lift up | to hold up | to hold above eye level | to give | to offer | to consecrate | to devote | to sacrifice | to dedicate",
        "1516430",
        "命を捧げます。","いのちをささげます。","Tôi cống hiến tính mạng.","I dedicate my life."),
    row("模様","もよう","N4","n",
        "hoa văn | họa tiết | thiết kế | tình trạng | dường như",
        "pattern | figure | design | state | condition | conjecture of the current situation | the way it seems | model | pattern | example | indicates that something seems likely (e.g. rain or storm)",
        "1533720",
        "花模様が好きです。","はなもようがすきです。","Tôi thích hoa văn hoa lá.","I like floral patterns."),
    row("嵐","あらし","N4","n",
        "bão tố | giông tố | bão (ví dụ phong trào)",
        "storm | tempest | uproar | hullabaloo | storm (e.g. of protest) | winds (e.g. of change)",
        "1549340",
        "嵐が来ます。","あらしがきます。","Bão tố đến.","A storm is coming."),
    row("几帳面","きちょうめん","N4","adj-na|n",
        "tỉ mỉ | cẩn thận | chu đáo | đúng giờ | có phương pháp",
        "methodical | precise | meticulous | scrupulous | regular | punctual",
        "1564360",
        "几帳面な性格です。","きちょうめんなせいかくです。","Tôi có tính cách tỉ mỉ.","I have a meticulous personality."),
    row("茹でる","ゆでる","N4","v1|vt",
        "luộc | đun sôi",
        "to boil (something in hot water) | to treat with medicinal steam (a swelling, etc.)",
        "1571470",
        "卵を茹でます。","たまごをゆでます。","Tôi luộc trứng.","I boil eggs."),
    row("燃やす","もやす","N4","v5s|vt",
        "đốt cháy | đốt | bừng cháy (cảm xúc)",
        "to burn | to burn with (emotion, feeling) | to be fired up",
        "1582900",
        "やる気を燃やします。","やるきをもやします。","Tôi bừng cháy động lực.","I burn with motivation."),
    row("込む","こむ","N4","v5m|vi|suf",
        "đông đúc | chật chội | tắc nghẽn | hoàn toàn | kỹ càng (tiếp vĩ ngữ)",
        "to be crowded | to be packed | to be congested | to be thronged (with) | to be complex | to be intricate | to go into | to go in | to put into | to become (completely) | to do thoroughly | to do sufficiently | to remain (silent, seated, etc.) | to stay ...",
        "1593410",
        "電車が込んでいます。","でんしゃがこんでいます。","Tàu điện đông đúc.","The train is crowded."),
    row("近道","ちかみち","N4","n|vs|vi",
        "đường tắt | lối tắt",
        "shorter way | shortcut",
        "1597380",
        "近道を使います。","ちかみちをつかいます。","Tôi dùng đường tắt.","I use the shortcut."),
    row("見た目","みため","N4","n",
        "vẻ bề ngoài | diện mạo | ngoại hình",
        "appearance | look",
        "1611750",
        "見た目が大切です。","みためがたいせつです。","Bề ngoài rất quan trọng.","Appearance is important."),
    row("環境汚染","かんきょうおせん","N4","n",
        "ô nhiễm môi trường",
        "environmental pollution",
        "1666030",
        "環境汚染を減らします。","かんきょうおせんをへらします。","Tôi giảm ô nhiễm môi trường.","I reduce environmental pollution."),
    row("数十","すうじゅう","N4","n|adj-no",
        "hàng chục | vài chục",
        "dozens | scores of | decades",
        "1709220",
        "数十人が参加します。","すうじゅうにんがさんかします。","Hàng chục người tham gia.","Dozens of people participate."),
    row("最終的","さいしゅうてき","N4","adj-na",
        "cuối cùng | tối hậu | sau cùng",
        "final | eventual | ultimate",
        "1721330",
        "最終的な決定をします。","さいしゅうてきなけっていをします。","Tôi đưa ra quyết định cuối cùng.","I make the final decision."),
    row("町内会","ちょうないかい","N4","n",
        "hội khu phố | ban đại diện khu dân cư",
        "neighborhood association | neighbourhood association",
        "1776790",
        "町内会に参加します。","ちょうないかいにさんかします。","Tôi tham gia hội khu phố.","I join the neighborhood association."),
    row("迂回路","うかいろ","N4","n",
        "đường vòng | tuyến đường thay thế | đường đi vòng",
        "detour | diversion | alternative route",
        "1930480",
        "迂回路を通ります。","うかいろをとおります。","Tôi đi qua đường vòng.","I take the detour."),
    row("就職活動","しゅうしょくかつどう","N4","n",
        "tìm việc làm | hoạt động xin việc | săn việc",
        "job hunting | job searching",
        "1937720",
        "就職活動を始めます。","しゅうしょくかつどうをはじめます。","Tôi bắt đầu tìm việc làm.","I start job hunting."),
    row("満足感","まんぞくかん","N4","n",
        "cảm giác thỏa mãn | sự hài lòng",
        "feeling of satisfaction",
        "1947220",
        "達成の満足感があります。","たっせいのまんぞくかんがあります。","Có cảm giác thỏa mãn khi hoàn thành.","There is a feeling of satisfaction from achievement."),
    row("三分の一","さんぶんのいち","N4","exp|n",
        "một phần ba | 1/3",
        "one third | a third part",
        "1949730",
        "三分の一を食べます。","さんぶんのいちをたべます。","Tôi ăn một phần ba.","I eat one third."),
    row("相談相手","そうだんあいて","N4","n",
        "người để hỏi ý kiến | người tư vấn | bạn tâm tình",
        "adviser | someone to consult with | someone to turn to about one's concerns | confidant",
        "2049240",
        "相談相手がいます。","そうだんあいてがいます。","Tôi có người để hỏi ý kiến.","I have someone to consult with."),
    row("達成感","たっせいかん","N4","n",
        "cảm giác thành tựu | cảm giác hoàn thành",
        "sense of accomplishment",
        "2638040",
        "達成感を感じます。","たっせいかんをかんじます。","Tôi cảm thấy thành tựu.","I feel a sense of accomplishment."),
    row("住民","じゅうみん","N4","n",
        "cư dân | người dân | dân cư",
        "inhabitant | resident | citizen | population",
        "1334210",
        "地域住民が集まります。","ちいきじゅうみんがあつまります。","Cư dân địa phương tập hợp.","The local residents gather."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
