# -*- coding: utf-8 -*-
"""Build N1 ready wave 033 — 慣用句 + idioms (set 33)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-033.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("焦点を絞る","しょうてんをしぼる","exp|v5r","tập trung trọng tâm | thu hẹp tiêu điểm | dồn vào điểm chính","to narrow the focus | to zero in","2779090"),
    ("尻込み","しりごみ","n|vs|vi","chùn bước | ngần ngại | rụt rè | lùi lại do dự","hesitation | flinching | balking","1619080"),
    ("心機","しんき","n","tâm trạng | tinh thần | thái độ (心機一転)","mental state | attitude","1793800"),
    ("垂涎の的","すいぜんのまと","exp|n","đối tượng thèm khát | thứ ai cũng thèm | tâm điểm khao khát","object of avid desire | object of envy","2844698"),
    ("据え膳","すえぜん","n","mâm cơm dọn sẵn | cơ hội bày sẵn | sự gợi ý của phụ nữ","meal set before one | a woman's advances","1655660"),
    ("図に当たる","ずにあたる","exp|v5r","trúng kế | đúng như tính toán | trúng phóc | thành công như ý","to hit the bull's-eye | to go as planned","1855380"),
    ("生殺与奪","せいさつよだつ","n","quyền sinh sát | nắm quyền sống chết | toàn quyền định đoạt","having life-and-death power over","1378980"),
    ("背に腹","せにはら","exp","cùng tắc biến | hy sinh nhỏ giữ lớn | đành chọn cái ít tệ hơn","a small sacrifice may be necessary for a bigger goal","2871209"),
    ("善後策","ぜんごさく","n","biện pháp khắc phục | kế sách thu xếp | đối sách | cách xử lý hậu quả","remedial measure | countermeasure | remedy","1596280"),
    ("千秋楽","せんしゅうらく","n","ngày diễn cuối | buổi cuối | ngày bế mạc (giải sumo)","final day of a performance | closing day","1388920"),
    ("先手を打つ","せんてをうつ","exp|v5t","ra tay trước | đi nước trước | tiên hạ thủ vi cường | chặn đầu","to forestall | to beat to the punch","1387850"),
    ("相好を崩す","そうごうをくずす","exp|v5s","cười tươi rói | nở nụ cười rạng rỡ | toét miệng cười","to smile broadly | to grin widely","2693930"),
    ("そりが合う","そりがあう","exp|v5u","hợp tính | tâm đầu ý hợp | ăn ý | hợp cạ","to think alike | to get along","2854176"),
    ("舵を取る","かじをとる","exp|v5r","cầm lái | chèo lái | điều khiển | dẫn dắt (con thuyền)","to steer | to take the helm | to manage","2102840"),
    ("立つ鳥","たつとり","n","chim cất cánh (立つ鳥跡を濁さず) | chim bay đi","bird taking flight","2573410"),
    ("店子","たなこ","n","người thuê nhà | khách trọ | người mướn nhà","tenant | renter","1440700"),
    ("血祭り","ちまつり","n","tế cờ bằng máu | giết để khích lệ trước trận | tàn sát đẫm máu","blood offering before battle | bloodbath","1255260"),
    ("茶々を入れる","ちゃちゃをいれる","exp|v1","chen ngang đùa cợt | nói leo trêu chọc | phá đám bằng câu đùa","to interrupt with frivolous remarks | to butt in teasingly","1597510"),
    ("長蛇の列","ちょうだのれつ","exp|n","hàng dài dằng dặc | xếp hàng rồng rắn | dòng người dài","long line | long queue","1430010"),
    ("血道","ちみち","n","mạch máu | huyết mạch","blood vessels","2672550"),
    ("血で血を洗う","ちでちをあらう","exp|v5u","lấy máu rửa máu | huynh đệ tương tàn | xung đột đẫm máu | nồi da xáo thịt","to engage in a bloody feud | to quarrel with one's own kin","2732350"),
    ("亭主関白","ていしゅかんぱく","n","chồng chúa vợ tôi | ông chồng gia trưởng | đàn ông độc đoán","domineering husband | husband who rules the roost","1434170"),
    ("手が後ろに回る","てがうしろにまわる","exp|v5r","bị bắt | bị còng tay | bị tóm vì phạm tội","to be arrested | to have one's hands tied behind","2125820"),
    ("手取り足取り","てとりあしとり","exp","cầm tay chỉ việc | tận tình hướng dẫn | chỉ bảo tỉ mỉ | dìu dắt từng li","attentively | with great attention to detail (teaching)","2068420"),
    ("天地神明","てんちしんめい","n","thần linh trời đất | quỷ thần hai vai | trời đất chứng giám","the gods of heaven and earth","1439840"),
    ("頭角を現す","とうかくをあらわす","exp|v5s","nổi bật hơn người | lộ rõ tài năng | trổ tài | bộc lộ năng lực","to distinguish oneself | to stand out","1450800"),
    ("堂々巡り","どうどうめぐり","n|vs|vi","luẩn quẩn | đi vòng vòng không lối thoát | dậm chân tại chỗ","going around in circles","1599280"),
    ("時を稼ぐ","ときをかせぐ","exp|v5g","câu giờ | kéo dài thời gian | dùng kế hoãn binh","to play for time | to use delaying tactics","2402910"),
    ("毒気を抜かれる","どっきをぬかれる","exp|v1","cụt hứng | đứng hình | bị làm cho ngỡ ngàng | mất khí thế","to be taken aback | to be dumbfounded","2792400"),
    ("胴上げ","どうあげ","n|vs|vt","tung hô lên cao | công kênh ăn mừng | nhấc bổng tung hô","tossing someone into the air in celebration","1454040"),
    ("鳥肌が立つ","とりはだがたつ","exp|v5t","nổi da gà | sởn gai ốc | rùng mình | run lên (cảm động)","to get goosebumps | to get chills","2213430"),
    ("泣き寝入り","なきねいり","n|vs|vi","khóc thầm cam chịu | nuốt nước mắt bỏ qua | đành chịu thiệt","accepting meekly | giving up in frustration | crying oneself to sleep","1229870"),
    ("名を馳せる","なをはせる","exp|v1","nổi danh | lừng danh | tạo dựng tên tuổi | vang danh","to win fame | to make a name for oneself","2568460"),
    ("二進も三進も","にっちもさっちも","exp|adv","bế tắc hoàn toàn | tiến thoái lưỡng nan | hết đường xoay xở","in no way (out of a deadlock) | stuck","1462430"),
    ("二の舞","にのまい","n","lặp lại vết xe đổ | giẫm lại sai lầm cũ | đi vào lối mòn thất bại","repeating the same failure | making the same mistake","1461320"),
    ("寝た子を起こす","ねたこをおこす","exp|v5s","bới chuyện | khơi lại chuyện cũ | đánh thức con quái ngủ yên","to wake a sleeping dog | to stir up trouble","2613810"),
    ("熱に浮かされる","ねつにうかされる","exp|v1","mê sảng vì sốt | phát cuồng vì | mê muội say sưa | sốt mê man","to be delirious with fever | to be crazy about","2777200"),
    ("根回し","ねまわし","n|vs|vi","vận động ngầm | dàn xếp trước | đi đêm | chuẩn bị hậu trường","laying the groundwork | behind-the-scenes maneuvering","1290090"),
    ("能書き","のうがき","n","khoe khoang | quảng cáo công dụng | nói phét về ưu điểm | tự đề cao","boasting | self-advertisement | listing virtues","1470190"),
    ("伸るか反るか","のるかそるか","exp|adv|adj-no","được ăn cả ngã về không | một mất một còn | liều một phen | thành bại tại đây","sink or swim | all or nothing | make or break","1600540"),
    ("歯がゆい","はがゆい","adj-i","sốt ruột | bứt rứt | bực bội | ngứa ngáy khó chịu","impatient | irritating | frustrating | vexing","1313540"),
    ("這いつくばる","はいつくばる","v5r|vi","bò lê | quỳ rạp | bò sát đất | phủ phục","to grovel | to go down on hands and knees","2057280"),
    ("裸一貫","はだかいっかん","n","tay trắng | hai bàn tay trắng | khởi nghiệp từ con số không","having nothing but one's body | being penniless","1547630"),
    ("鼻っ柱","はなっぱしら","n","tính hiếu thắng | khí thế ngang ngạnh | tinh thần bất khuất | bướng bỉnh","aggressiveness | competitive spirit | fighting spirit","1486740"),
    ("歯止め","はどめ","n","cái phanh | sự kìm hãm | điểm dừng | giới hạn (歯止めをかける)","brake | restraint | check | imposed limit","1313330"),
    ("腹が黒い","はらがくろい","exp|adj-i","bụng dạ đen tối | thâm hiểm | nham hiểm | gian xảo","scheming | malicious | blackhearted","2057010"),
    ("針のむしろ","はりのむしろ","exp|n","ngồi trên đống lửa | như ngồi trên bàn chông | đứng ngồi không yên","a bed of nails | a very uncomfortable situation","2159600"),
    ("万事休す","ばんじきゅうす","exp","hết cách | bó tay | hết nước hết cái | đành chịu thua","there is nothing more that can be done | it's all over","1601360"),
    ("引っ込みがつかない","ひっこみがつかない","exp|adj-i","đã trót | lỡ leo lưng cọp | không thể rút lui | tiến thoái lưỡng nan","being in too deep to back out","2126540"),
    ("人いきれ","ひといきれ","n","hơi người ngột ngạt | không khí oi bức (đông người) | hầm hơi","stuffy air from a crowd | body heat in close quarters","2411140"),
    ("人垣","ひとがき","n","bức tường người | đám đông vây quanh | rào người | vòng người","wall of people | throng of people","1366720"),
    ("一筋縄","ひとすじなわ","n","cách thông thường | (一筋縄ではいかない: không dễ xơi)","an ordinary method | a single rope","1161960"),
    ("火に油","ひにあぶら","exp|n","đổ thêm dầu vào lửa | làm tình hình tệ hơn | châm dầu","adding fuel to the fire","2835733"),
    ("紐解く","ひもとく","v5k|vt","mở sách đọc | lần giở | khám phá (bí ẩn) | tìm hiểu","to peruse (a book) | to unravel (a mystery)","2016890"),
    ("昼行灯","ひるあんどん","n","kẻ vô dụng | đồ bỏ đi | kẻ lờ đờ | (đèn lồng giữa ban ngày)","a useless person | dunce | inattentive person","1426320"),
    ("深手","ふかで","n","vết thương nặng | trọng thương | vết chém sâu","severe wound | serious gash","1769000"),
    ("腹心","ふくしん","n|adj-no","tâm phúc | tay chân thân tín | người tin cẩn | cánh tay phải","one's confidant | trusted retainer","1501210"),
    ("不退転","ふたいてん","n","kiên định | quyết tâm không lùi | bất thoái chuyển | một lòng","determination | unshakable conviction","1493760"),
    ("札付き","ふだつき","adj-no|n","có tiếng xấu | khét tiếng | tai tiếng | nổi danh (xấu)","notorious | infamous | hardened","1721990"),
    ("仏頂面","ぶっちょうづら","n","mặt khó đăm đăm | mặt nhăn nhó | bộ mặt cau có | mặt sưng sỉa","sour look | surly face | pout","1502220"),
    ("筆不精","ふでぶしょう","adj-na|n","lười viết thư | ngại viết lách | kém thư từ qua lại","poor correspondent | disliking writing","1487900"),
    ("踏ん切り","ふんぎり","n","sự quyết đoán | sự dứt khoát | quyết định dứt khoát","determination | decision","2106740"),
    ("臍繰り","へそくり","n","tiền riêng giấu kín | quỹ đen | tiền phòng thân giấu kỹ","secret savings | money hidden away","1571230"),
    ("弁慶","べんけい","n","người mạnh mẽ | kẻ làm bộ dũng mãnh | ống tre cắm đồ bếp | họa tiết kẻ caro","a strong person | one putting on a brave front | checked pattern","1512770"),
    ("忙殺","ぼうさつ","n|vs|vt","bận tối tăm mặt mũi | ngập đầu công việc | bù đầu | bận túi bụi","being extremely busy | being swamped with work","1603655"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
