# -*- coding: utf-8 -*-
"""Build N1 ready wave 032 — 慣用句 idiomatic expressions (set 32)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-032.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("二枚舌","にまいじた","n|adj-no","lá mặt lá trái | nói hai lời | tráo trở | lật lọng","double-dealing | duplicity | double-tongued","1463200"),
    ("似たり寄ったり","にたりよったり","adj-na|n","na ná nhau | xêm xêm | kẻ tám lạng người nửa cân | tương tự","much the same | similar","1314570"),
    ("猫の額","ねこのひたい","exp|n","bé tí | chật hẹp | nhỏ như lỗ mũi | mảnh đất con con","tiny area | tiny space","1845690"),
    ("根掘り葉掘り","ねほりはほり","exp|adv","cặn kẽ | tra hỏi tỉ mỉ | hỏi tới tấp | moi móc đến cùng","inquisitively | pryingly | thoroughly","1290060"),
    ("歯が浮く","はがうく","exp|v5k","sởn da gà (lời sáo rỗng) | ghê răng | khó chịu | phát ngấy","to be set on edge (by flattery) | to become annoyed","1313020"),
    ("拍車","はくしゃ","n","cựa thúc ngựa | sự thúc đẩy | đà tăng tốc (拍車をかける)","spur | spurring on | acceleration","1474800"),
    ("鼻が利く","はながきく","exp|v5k","thính mũi | nhạy bén | đánh hơi giỏi | tinh nhạy","to have a keen nose | to have a good instinct","2843787"),
    ("腹芸","はらげい","n","diễn xuất nội tâm | dùng khí chất áp đảo | nghệ thuật ngầm | thị uy ngầm","implied acting | asserting one's will by force of personality","1649000"),
    ("腹を据える","はらをすえる","exp|v1","hạ quyết tâm | bình tĩnh lại | kiên nhẫn chịu đựng | định thần","to make up one's mind | to calm oneself | to endure","1628180"),
    ("火の車","ひのくるま","exp|n","túng quẫn | cháy túi | khốn đốn tài chính | kiệt quệ tiền bạc","desperate financial situation | dire straits","1193670"),
    ("膝を打つ","ひざをうつ","exp|v5t","vỗ đùi đắc ý | chợt vỡ lẽ | reo lên tâm đắc | bừng tỉnh","to slap one's knee (in sudden recognition)","2844780"),
    ("人を食う","ひとをくう","exp|v5u","xấc xược | hỗn xược | trịch thượng | coi thường người","to be insolent | to be arrogant | to be impudent","2856007"),
    ("顰める","ひそめる","v1|vt","nhíu mày | cau mày | nhăn trán | chau mày","to knit (one's eyebrows) | to furrow","2703030"),
    ("眉唾物","まゆつばもの","n","chuyện đáng ngờ | tin vịt | chuyện bịa | thông tin không đáng tin","dubious tale | cock-and-bull story","1486320"),
    ("不甲斐ない","ふがいない","adj-i","bạc nhược | bất tài | hèn nhát | đáng thất vọng | vô dụng","good-for-nothing | spineless | pathetic | disappointing","1570950"),
    ("袋叩き","ふくろだたき","n","hội đồng đánh | xúm vào đánh | bị chỉ trích tới tấp | hùa nhau công kích","ganging up to beat someone | facing a barrage of criticism","1411100"),
    ("反吐が出る","へどがでる","exp|v1","buồn nôn | phát tởm | ghê tởm | lợm giọng","to be nauseating | to be disgusting | to be revolting","2796060"),
    ("骨抜き","ほねぬき","n|adj-no","rút xương (cá thịt) | làm rỗng (kế hoạch) | làm mất chất | vô hiệu hóa","boning | watering down (a plan) | emasculation","1288730"),
    ("盆と正月","ぼんとしょうがつ","exp|n","lễ Vu Lan và Tết cùng đến | hai niềm vui cùng lúc | vui như trẩy hội","two great things happening at once","2842238"),
    ("眉をひそめる","まゆをひそめる","exp|v1","cau mày | nhíu mày khó chịu | tỏ vẻ không hài lòng | chau mày","to knit one's brows | to frown (in disapproval)","2125270"),
    ("身につまされる","みにつまされる","exp|v1","đồng cảm sâu sắc | chạnh lòng | thấy như chuyện mình | xót xa","to sympathize deeply with | to strike a chord","2220570"),
    ("身の毛がよだつ","みのけがよだつ","exp|v5t","dựng tóc gáy | rợn người | sởn gai ốc | rùng mình","to have one's hair stand on end","2085730"),
    ("水を得た魚","みずをえたうお","exp|n","như cá gặp nước | gặp đúng môi trường | tha hồ vẫy vùng","like a fish that has found water | in one's element","2401990"),
    ("目から鼻へ抜ける","めからはなへぬける","exp|v1","thông minh lanh lợi | nhanh trí | sắc sảo | tinh ranh","to be very shrewd | to be highly intelligent","2129780"),
    ("目に角を立てる","めにかどをたてる","exp|v1","trừng mắt giận dữ | quắc mắt | nhìn hằn học | nổi đóa","to look angrily at | to glare with anger","2129390"),
    ("目もくれない","めもくれない","exp|adj-i","chẳng thèm để ý | phớt lờ | làm ngơ | không buồn nhìn","indifferent | paying no attention","2037760"),
    ("目を白黒させる","めをしろくろさせる","exp|v1","trợn trừng mắt | lóng ngóng hốt hoảng | bối rối ngơ ngác | trố mắt","to be bewildered | to be flustered | to roll one's eyes","2144580"),
    ("目を光らせる","めをひからせる","exp|v1","để mắt canh chừng | giám sát chặt | theo dõi sát sao | canh gác","to keep a watchful eye on","2625640"),
    ("持ちつ持たれつ","もちつもたれつ","exp|n","tương trợ lẫn nhau | nương tựa nhau | có qua có lại | giúp đỡ qua lại","helping each other | give and take | interdependence","1315490"),
    ("元の木阿弥","もとのもくあみ","exp","đâu lại vào đấy | công cốc | trở về vạch xuất phát | dã tràng xe cát","ending up right back where one started","1260690"),
    ("門前雀羅","もんぜんじゃくら","n","cửa nhà vắng vẻ | đìu hiu hắt | vắng như chùa Bà Đanh | thưa khách","a deserted house with few visitors","2032890"),
    ("矢の催促","やのさいそく","exp|n","giục liên hồi | thúc ép tới tấp | đòi dồn dập | hối thúc dồn dập","strongly and repeatedly urging","2764700"),
    ("槍玉に挙げる","やりだまにあげる","exp|v1","lôi ra làm gương | đem ra chỉ trích | nhắm làm vật tế thần | bêu riếu","to single out for criticism | to make an example of","1850370"),
    ("湯水のように","ゆみずのように","exp","tiêu như nước | phung phí | vung tay quá trán | xài như rác","like water | spending lavishly","2838423"),
    ("横紙破り","よこがみやぶり","n","ngang ngược | làm trái lẽ thường | bất chấp lý lẽ | cố chấp phi lý","acting illogically | being unreasonable","1719680"),
    ("弱り果てる","よわりはてる","v1|vi","kiệt sức hoàn toàn | bí bách | bó tay hết cách | rã rời","to be utterly exhausted | to be at one's wits' end","1662370"),
    ("脇が甘い","わきがあまい","exp|adj-i","sơ hở | phòng thủ kém | mất cảnh giác | dễ bị tấn công","having weak defenses | off one's guard","2573210"),
    ("我が物顔","わがものがお","adj-na|n","như chốn không người | ngông nghênh | làm chủ như của mình | nghênh ngang","acting as if one owned the place","1196930"),
    ("腕が立つ","うでがたつ","exp|v5t","tay nghề cao | giỏi giang | có tài | thạo việc","to be talented | to be skilled","2108270"),
    ("腕が鳴る","うでがなる","exp|v5r","ngứa nghề | nóng lòng trổ tài | háo hức thi thố | rạo rực muốn ra tay","to be itching to put one's skills to use","2079560"),
    ("味を占める","あじをしめる","exp|v1","quen mùi | nếm mùi ngọt rồi ham | bén mùi | được đà","to get a taste for | to be encouraged by initial success","2102010"),
    ("目処","めど","n","mục tiêu | triển vọng | đích nhắm | hướng nhìn (目処が立つ)","aim | goal | prospect | outlook","1535470"),
    ("当てが外れる","あてがはずれる","exp|v1","trật dự tính | sai kỳ vọng | hụt hẫng | tính không như mong","to be contrary to one's expectations","1856780"),
    ("息の根を止める","いきのねをとめる","exp|v1","kết liễu | giết chết | bóp nghẹt | dứt điểm","to kill | to choke the life out of","2102080"),
    ("一巻の終わり","いっかんのおわり","exp","tới số | hết đời | màn cuối | chấm hết | xong phim","the end of the line | curtains","2520460"),
    ("芋を洗うよう","いもをあらうよう","exp|adj-na","chen chúc | đông nghịt | chật như nêm | người người chen lấn","jam-packed | teeming with people","2102140"),
    ("鵜呑み","うのみ","n","nuốt chửng | tin sái cổ | tin mà không suy xét | nghe gì tin nấy","swallowing whole | accepting without questioning","1172210"),
    ("裏腹","うらはら","adj-na|n","trái ngược | ngược lại | mặt trước mặt sau | trái với","opposite | contrary | back to back","1550610"),
    ("得体の知れない","えたいのしれない","exp|adj-i","khó lường | bí hiểm | không rõ lai lịch | đáng ngờ","mysterious | strange | suspicious","1454580"),
    ("大盤振る舞い","おおばんぶるまい","n|vs|vi","thết đãi linh đình | hào phóng chiêu đãi | bao trọn gói | đãi ngộ rộng rãi","lavish feast | splendid banquet | lavish hospitality","2040040"),
    ("お鉢が回る","おはちがまわる","exp|v5r","đến lượt mình | tới phiên | đến lượt phải làm","one's turn comes around","2417310"),
    ("顔が利く","かおがきく","exp|v5k","có thế lực | quen biết rộng | có uy tín | nói có người nghe","to have influence | to have clout | to be influential","2028440"),
    ("肩身が狭い","かたみがせまい","exp|adj-i","tủi hổ | mặc cảm | thấy xấu hổ | thấy mình kém cỏi","feeling ashamed | feeling inferior","1259050"),
    ("固唾を呑む","かたずをのむ","exp|v5m","nín thở hồi hộp | nín thở chờ đợi | nuốt nước bọt lo âu","to hold one's breath (in anxiety)","1266630"),
    ("株が上がる","かぶがあがる","exp|v5r","tăng uy tín | được nể trọng hơn | lên giá | được lòng hơn","to rise in esteem | to become popular","1208940"),
    ("気が引ける","きがひける","exp|v1","ngại ngùng | e dè | thấy áy náy | rụt rè ngần ngại","to feel awkward | to feel ashamed | to feel shy","1221550"),
    ("牙を剥く","きばをむく","exp|v5k","nhe nanh | giương nanh vuốt | trở mặt tấn công | lộ bản chất hung dữ","to bare one's fangs | to snarl at","2712840"),
    ("草分け","くさわけ","n","người tiên phong | người khai phá | người sáng lập | bậc khai sơn","pathfinder | trailblazer | pioneer | founder","1640590"),
    ("逆鱗に触れる","げきりんにふれる","exp|v1","chọc giận bề trên | khiến cấp trên nổi giận | phạm long nhan","to incur a superior's wrath","2089050"),
    ("檄を飛ばす","げきをとばす","exp|v5s","hiệu triệu | kêu gọi cổ vũ | ra lời hịch | khích lệ tinh thần","to issue a manifesto | to rally | to appeal","1568390"),
    ("碁敵","ごがたき","n","kỳ phùng địch thủ (cờ vây) | đối thủ chơi cờ vây","rival in the game of go","2414870"),
    ("腰が引ける","こしがひける","exp|v1","chùn bước | nhụt chí | rụt rè lùi bước | e ngại rút lui","to get cold feet | to back away","2630650"),
    ("采配を振る","さいはいをふる","exp|v5r","cầm quân | chỉ huy | điều binh khiển tướng | nắm quyền chỉ đạo","to lead | to direct | to take command","1295150"),
    ("私語","しご","n|vs|vi","nói chuyện riêng | rì rầm | thì thầm | nói chuyện (trong giờ học)","whispering | private talk | talking during a lecture","1646550"),
    ("痺れを切らす","しびれをきらす","exp|v5s","sốt ruột | hết kiên nhẫn chờ đợi | nóng ruột mất bình tĩnh","to grow impatient | to get tired of waiting","2029220"),
    ("食指が動く","しょくしがうごく","exp|v5k","động lòng tham | thèm muốn | nổi hứng | háo hức muốn","to have an urge for | to be eager to | to have a craving","1358480"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
