# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-005.csv in UTF-8 — 100 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-005.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("どうせ","どうせ","N4","adv",
        "dù sao thì | bất kể thế nào | dù gì đi nữa | xét cho cùng | lắm thì cũng chỉ",
        "in any case | regardless | either way | after all | no matter what | anyway | at best | at most",
        "1008950",
        "どうせ行かないでしょう。","どうせいかないでしょう。","Dù sao thì cũng sẽ không đi thôi.","You probably won't go anyway."),
    row("子育て","こそだて","N4","n|vs|vi",
        "nuôi dạy con cái | nuôi nấng con | làm cha mẹ",
        "child rearing | child raising | raising children | parenting",
        "1307790",
        "子育ては大変です。","こそだてはたいへんです。","Nuôi dạy con cái rất vất vả.","Raising children is difficult."),
    row("少しずつ","すこしずつ","N4","adv",
        "từng chút một | dần dần từng bước",
        "little by little | bit by bit",
        "1348880",
        "少しずつ上手になります。","すこしずつじょうずになります。","Dần dần tôi trở nên giỏi hơn.","I am getting better little by little."),
    row("知識","ちしき","N4","n",
        "kiến thức | tri thức | thông tin",
        "knowledge | information",
        "1420590",
        "知識を深めます。","ちしきをふかめます。","Tôi mở mang kiến thức.","I deepen my knowledge."),
    row("通り過ぎる","とおりすぎる","N4","v1|vi",
        "đi ngang qua | đi qua | vượt qua",
        "to go past | to pass | to pass by",
        "1432980",
        "駅を通り過ぎました。","えきをとおりすぎました。","Tôi đã đi qua ga.","I passed by the station."),
    row("怒り","いかり","N4","n",
        "sự tức giận | cơn giận | sự phẫn nộ | cơn thịnh nộ",
        "anger | rage | fury | wrath | indignation",
        "1445670",
        "怒りを抑えます。","いかりをおさえます。","Tôi kìm nén cơn giận.","I suppress my anger."),
    row("部下","ぶか","N4","n",
        "cấp dưới | thuộc cấp | nhân viên dưới quyền",
        "subordinate person",
        "1499350",
        "部下を指導します。","ぶかをしどうします。","Tôi hướng dẫn cấp dưới.","I guide my subordinates."),
    row("霧","きり","N4","n",
        "sương mù | sương | tia phun",
        "fog | mist | spray",
        "1531110",
        "霧が出ています。","きりがでています。","Có sương mù.","There is fog."),
    row("明確","めいかく","N4","adj-na",
        "rõ ràng | chính xác | dứt khoát | phân biệt rõ",
        "clear | precise | definite | distinct",
        "1532410",
        "明確に答えます。","めいかくにこたえます。","Tôi trả lời rõ ràng.","I answer clearly."),
    row("面接","めんせつ","N4","n|vs|vi",
        "phỏng vấn (ví dụ xin việc)",
        "interview (e.g. for a job)",
        "1533510",
        "明日面接があります。","あしためんせつがあります。","Ngày mai tôi có phỏng vấn.","I have an interview tomorrow."),
    row("野原","のはら","N4","n",
        "cánh đồng | đồng bằng | đồng cỏ rộng | đầm lầy",
        "field | plain | prairie | moor",
        "1537360",
        "野原で遊びます。","のはらであそびます。","Tôi chơi trên cánh đồng.","I play in the field."),
    row("友人","ゆうじん","N4","n",
        "bạn bè | người bạn | bạn thân",
        "friend",
        "1540150",
        "友人と話します。","ゆうじんとはなします。","Tôi nói chuyện với bạn.","I talk with a friend."),
    row("履歴書","りれきしょ","N4","n",
        "hồ sơ cá nhân | lý lịch | hồ sơ xin việc",
        "personal history document | curriculum vitae | resume",
        "1549820",
        "履歴書を書きます。","りれきしょをかきます。","Tôi viết hồ sơ xin việc.","I write my resume."),
    row("頬","ほお","N4","n",
        "má | gò má",
        "cheek (of the face)",
        "1584160",
        "頬が赤くなりました。","ほおがあかくなりました。","Má đỏ hồng lên.","My cheeks turned red."),
    row("主人","しゅじん","N4","n",
        "chủ nhà | chủ cửa hàng | chủ nhà trọ | ông chủ | chồng tôi",
        "head (of a household) | proprietor (of a store) | proprietress | landlord | employer | boss | (my) husband",
        "1579780",
        "主人は今家にいます。","しゅじんはいまいえにいます。","Chồng tôi hiện đang ở nhà.","My husband is at home now."),
    row("伝言","でんごん","N4","n|vs|vt",
        "lời nhắn | tin nhắn lời nói",
        "(verbal) message | word (from someone)",
        "1582180",
        "伝言をお願いします。","でんごんをおねがいします。","Nhờ nhắn giúp một tin.","Please pass on a message."),
    row("温まる","あたたまる","N4","v5r|vi",
        "sưởi ấm | phơi nắng | ấm lên | trở nên ấm",
        "to warm oneself | to sun oneself | to warm up | to get warm",
        "1586430",
        "体が温まりました。","からだがあたたまりました。","Cơ thể đã ấm lên.","My body has warmed up."),
    row("悔しい","くやしい","N4","adj-i",
        "tiếc nuối | khó chịu | ấm ức | bực bội | uất ức",
        "frustrated (over a failure, humiliation or injustice) | annoyed | chagrin",
        "1592350",
        "悔しいです！","くやしいです！","Tôi thật tiếc nuối!","I'm so frustrated!"),
    row("治る","なおる","N4","v5r|vi",
        "hồi phục | khỏi bệnh | bình phục | được chữa khỏi",
        "to get better | to get well | to recover (from an illness) | to be cured",
        "1599400",
        "風邪が治りました。","かぜがなおりました。","Cảm đã khỏi rồi.","My cold has recovered."),
    row("喉","のど","N4","n",
        "cổ họng | giọng ca | gáy sách (lề trong của sách)",
        "throat | singing voice | gutter (inner margins of a book)",
        "1600280",
        "喉が痛いです。","のどがいたいです。","Cổ họng đau.","My throat hurts."),
    row("乗り物","のりもの","N4","n",
        "phương tiện giao thông | xe cộ | phương tiện vận chuyển | trò chơi (ở hội chợ, công viên)",
        "vehicle | conveyance | (means of) transport | ride (at a fair, amusement park, etc.)",
        "1600530",
        "どんな乗り物が好きですか。","どんなのりものがすきですか。","Bạn thích phương tiện gì?","What kind of vehicle do you like?"),
    row("部署","ぶしょ","N4","n",
        "phòng ban | bộ phận | ban | chi nhánh",
        "one's post | one's station | department | bureau | section",
        "1603140",
        "どの部署ですか。","どのぶしょですか。","Bạn ở phòng ban nào?","Which department are you in?"),
    row("コスト","コスト","N4","n",
        "chi phí | giá thành",
        "cost",
        "1050080",
        "コストを削減します。","コストをさくげんします。","Tôi cắt giảm chi phí.","I reduce costs."),
    row("ストレス","ストレス","N4","n",
        "căng thẳng | stress | áp lực",
        "stress",
        "1071490",
        "ストレスを解消します。","ストレスをかいしょうします。","Tôi giải tỏa căng thẳng.","I relieve stress."),
    row("ヒント","ヒント","N4","n",
        "gợi ý | manh mối | chỉ dẫn",
        "hint | clue",
        "1104300",
        "ヒントをください。","ヒントをください。","Hãy cho tôi một gợi ý.","Please give me a hint."),
    row("エスカレーター","エスカレーター","N4","n",
        "thang cuốn",
        "escalator",
        "1028580",
        "エスカレーターで上がります。","エスカレーターであがります。","Tôi đi thang cuốn lên.","I go up on the escalator."),
    row("クーポン","クーポン","N4","n",
        "phiếu giảm giá | coupon | voucher",
        "coupon | voucher",
        "1043290",
        "クーポンを使います。","クーポンをつかいます。","Tôi dùng phiếu giảm giá.","I use a coupon."),
    row("スプーン","スプーン","N4","n",
        "muỗng | thìa | mồi câu hình thìa",
        "spoon | spoon lure",
        "1072590",
        "スプーンで食べます。","スプーンでたべます。","Tôi ăn bằng muỗng.","I eat with a spoon."),
    row("フライパン","フライパン","N4","n",
        "chảo chiên | chảo",
        "fry pan | frying pan",
        "1111160",
        "フライパンで炒めます。","フライパンでいためます。","Tôi xào bằng chảo.","I stir-fry in a frying pan."),
    row("プール","プール","N4","n|vs|vt",
        "bể bơi | hồ bơi | biliards (thể thao cơ) | gộp chung (tiền, tài nguyên)",
        "(swimming) pool | pool (cue sport) | pooling (money, resources, etc.)",
        "1115150",
        "プールで泳ぎます。","プールでおよぎます。","Tôi bơi ở bể bơi.","I swim in the pool."),
    row("マンション","マンション","N4","n",
        "căn hộ chung cư (thường trung hoặc cao tầng) | tòa nhà căn hộ",
        "condominium (usu. mid or high-rise) | apartment building | apartment house | apartment",
        "1130040",
        "マンションに住んでいます。","マンションにすんでいます。","Tôi sống ở chung cư.","I live in a condominium."),
    row("メッセージ","メッセージ","N4","n",
        "tin nhắn | thông điệp",
        "message",
        "1133570",
        "メッセージを送ります。","メッセージをおくります。","Tôi gửi tin nhắn.","I send a message."),
    row("引き返す","ひきかえす","N4","v5s|vi",
        "quay lại | trở lại | đi ngược lại | theo dấu vết cũ",
        "to turn back | to go back | to come back | to return | to retrace one's steps",
        "1169140",
        "道に迷って引き返しました。","みちにまよってひきかえしました。","Tôi lạc đường và phải quay lại.","I got lost and turned back."),
    row("額","ひたい","N4","n",
        "trán | vầng trán",
        "forehead | brow",
        "1207510",
        "額に汗をかきます。","ひたいにあせをかきます。","Tôi toát mồ hôi trán.","I sweat on my forehead."),
    row("具体的","ぐたいてき","N4","adj-na",
        "cụ thể | rõ ràng | xác định | thực chất | đáng kể",
        "concrete | definite | specific | material | substantial",
        "1245050",
        "具体的に説明します。","ぐたいてきにせつめいします。","Tôi giải thích cụ thể.","I explain specifically."),
    row("経済","けいざい","N4","n",
        "nền kinh tế | kinh tế học | tài chính | tài chính cá nhân | tình hình tài chính",
        "economy | economics | finance | (one's) finances | financial circumstances | economic affairs",
        "1251320",
        "経済が成長しています。","けいざいがせいちょうしています。","Nền kinh tế đang tăng trưởng.","The economy is growing."),
    row("計画","けいかく","N4","n|vs|vt",
        "kế hoạch | dự án | lịch trình | phương án | chương trình",
        "plan | project | schedule | scheme | program | programme",
        "1252090",
        "計画を立てます。","けいかくをたてます。","Tôi lập kế hoạch.","I make a plan."),
    row("事件","じけん","N4","n",
        "sự kiện | vụ việc | sự cố | vụ án | âm mưu | rắc rối | bê bối",
        "event | affair | incident | case | plot | trouble | scandal",
        "1313830",
        "事件が起きました。","じけんがおきました。","Một sự cố xảy ra.","An incident occurred."),
    row("持ち込む","もちこむ","N4","v5m|vt",
        "mang vào | đem vào | chuyển vào | tiếp cận (ai đó) với (đề xuất, vấn đề)",
        "to bring in | to take in | to carry in | to approach (someone) with (a proposal, problem, etc.)",
        "1315590",
        "荷物を持ち込みます。","にもつをもちこみます。","Tôi mang hành lý vào.","I bring luggage in."),
    row("持ち出す","もちだす","N4","v5s|vt",
        "mang ra | đem ra | lấy ra khỏi nơi thuộc về | đề cập | nêu lên (chủ đề) | đưa ra",
        "to take out | to carry out | to bring out from where it belongs | to mention | to bring up (a topic) | to raise (a subject)",
        "1315600",
        "資料を持ち出します。","しりょうをもちだします。","Tôi mang tài liệu ra.","I take out the materials."),
    row("治療","ちりょう","N4","n|vs|vt",
        "điều trị (y tế) | chăm sóc | liệu pháp | chữa khỏi | phương thuốc",
        "(medical) treatment | care | therapy | cure | remedy",
        "1316890",
        "治療を受けます。","ちりょうをうけます。","Tôi nhận điều trị.","I receive treatment."),
    row("上司","じょうし","N4","n",
        "cấp trên | sếp | cấp chỉ huy",
        "(one's) superior | (one's) boss | the higher-ups",
        "1353260",
        "上司に報告します。","じょうしにほうこくします。","Tôi báo cáo với cấp trên.","I report to my boss."),
    row("知人","ちじん","N4","n",
        "người quen | quen biết | bạn bè",
        "friend | acquaintance",
        "1420620",
        "昔の知人に会いました。","むかしのちじんにあいました。","Tôi gặp người quen cũ.","I met an old acquaintance."),
    row("諦める","あきらめる","N4","v1|vt",
        "từ bỏ | bỏ cuộc | từ bỏ (hy vọng, kế hoạch) | chấp nhận (thực tế)",
        "to give up | to abandon (hope, plans) | to resign oneself (to)",
        "1436730",
        "諦めないでください。","あきらめないでください。","Đừng bỏ cuộc.","Please don't give up."),
    row("電子レンジ","でんしレンジ","N4","n",
        "lò vi sóng",
        "microwave oven",
        "1443380",
        "電子レンジで温めます。","でんしレンジであたためます。","Tôi hâm nóng bằng lò vi sóng.","I heat it in the microwave."),
    row("都合","つごう","N4","n|vs|vt|adv",
        "hoàn cảnh | điều kiện | sự thuận tiện | sắp xếp | quản lý | tổng cộng",
        "circumstances | condition | convenience | arranging | managing | lending | borrowing | in all | in total",
        "1444980",
        "都合がいいですか。","つごうがいいですか。","Bạn có thuận tiện không?","Is it convenient for you?"),
    row("努力","どりょく","N4","n|vs|vi",
        "nỗ lực | cố gắng | chuyên cần | sự chăm chỉ | vất vả | phấn đấu",
        "effort | exertion | endeavour | endeavor | hard work | striving",
        "1445130",
        "努力します！","どりょくします！","Tôi sẽ nỗ lực!","I will make an effort!"),
    row("土","つち","N4","n",
        "đất | đất đai | bùn | đất sét | đất bẩn | mặt đất | đất đai",
        "earth | soil | dirt | clay | mud | the earth (historically) | the ground | land",
        "1445270",
        "土を掘ります。","つちをほります。","Tôi đào đất.","I dig the soil."),
    row("眉","まゆ","N4","n",
        "lông mày",
        "eyebrow | eyebrows",
        "1486270",
        "眉を整えます。","まゆをととのえます。","Tôi chỉnh lông mày.","I groom my eyebrows."),
    row("箸","はし","N4","n",
        "đũa",
        "chopsticks",
        "1476410",
        "箸を使います。","はしをつかいます。","Tôi dùng đũa.","I use chopsticks."),
    row("肌","はだ","N4","n|n-suf",
        "da | thân thể (trong bối cảnh tiếp xúc cơ thể thân mật) | bề mặt | thớ (gỗ) | kết cấu",
        "skin | body (in the context of intimate bodily contact) | surface | grain (of wood, etc.) | texture",
        "1476450",
        "肌が乾燥しています。","はだがかんそうしています。","Da đang bị khô.","My skin is dry."),
    row("名刺","めいし","N4","n",
        "danh thiếp | card danh thiếp",
        "business card",
        "1531550",
        "名刺を渡します。","めいしをわたします。","Tôi đưa danh thiếp.","I hand over my business card."),
    row("目標","もくひょう","N4","n",
        "mục tiêu | đích nhắm | mục đích | cột mốc | dấu hiệu | điểm mốc",
        "goal | target | aim | objective | mark | sign | landmark",
        "1535650",
        "目標を達成します。","もくひょうをたっせいします。","Tôi đạt mục tiêu.","I achieve my goal."),
    row("冷静","れいせい","N4","n|adj-na",
        "bình tĩnh | tự chủ | điềm tĩnh | thản nhiên | tỉnh táo",
        "calmness | composure | coolness | serenity | presence of mind",
        "1557050",
        "冷静に考えます。","れいせいにかんがえます。","Tôi suy nghĩ bình tĩnh.","I think calmly."),
    row("冷房","れいぼう","N4","n|vs|vt",
        "máy lạnh | điều hòa không khí | làm lạnh trong nhà",
        "air conditioning | air cooling",
        "1557290",
        "冷房をつけます。","れいぼうをつけます。","Tôi bật máy lạnh.","I turn on the air conditioning."),
    row("励ます","はげます","N4","v5s|vt",
        "khích lệ | cổ vũ | động viên | tiếp thêm sinh khí | truyền cảm hứng",
        "to encourage | to cheer on | to cheer (someone) up | to raise (one's voice) | to inspirit | to invigorate",
        "1557350",
        "友達を励まします。","ともだちをはげまします。","Tôi cổ vũ bạn bè.","I encourage my friend."),
    row("歴史","れきし","N4","n",
        "lịch sử",
        "history",
        "1558050",
        "歴史を勉強します。","れきしをべんきょうします。","Tôi học lịch sử.","I study history."),
    row("気づく","きづく","N4","v5k|vi",
        "nhận ra | chú ý | nhận thức | trở nên ý thức (được) | nhận thấy",
        "to notice | to realize | to realise | to become aware (of) | to perceive",
        "1591330",
        "間違いに気づきました。","まちがいにきづきました。","Tôi nhận ra lỗi sai.","I noticed a mistake."),
    row("チャンス","チャンス","N4","n",
        "cơ hội | may mắn | dịp",
        "chance | opportunity",
        "1078040",
        "チャンスを掴みます。","チャンスをつかみます。","Tôi nắm bắt cơ hội.","I seize the opportunity."),
    row("バランス","バランス","N4","n|vs|vi",
        "sự cân bằng | cân bằng",
        "balance",
        "1099690",
        "バランスを保ちます。","バランスをたもちます。","Tôi duy trì sự cân bằng.","I maintain balance."),
    row("気をつける","きをつける","N4","exp|v1",
        "cẩn thận | chú ý | để ý | thận trọng",
        "to be careful | to pay attention | to take care",
        "1591990",
        "気をつけてください。","きをつけてください。","Hãy cẩn thận nhé.","Please be careful."),
    row("支払い","しはらい","N4","n",
        "sự thanh toán | chi trả | thanh toán",
        "payment",
        "1594480",
        "支払いをします。","しはらいをします。","Tôi thanh toán.","I make a payment."),
    row("締め切り","しめきり","N4","n",
        "thời hạn chót | hạn chót | ngày đóng cửa | đóng (cửa, cửa sổ)",
        "deadline | closing | cut-off | closing (a door, window, etc.)",
        "1594590",
        "締め切りは明日です。","しめきりはあしたです。","Hạn chót là ngày mai.","The deadline is tomorrow."),
    row("手続き","てつづき","N4","n",
        "thủ tục | quy trình | tiến hành | thủ tục hành chính",
        "procedure | process | proceedings | formalities",
        "1598350",
        "手続きが必要です。","てつづきがひつようです。","Cần phải làm thủ tục.","Procedures are required."),
    row("値段","ねだん","N4","n",
        "giá | giá cả | chi phí",
        "price | cost",
        "1600160",
        "値段はいくらですか。","ねだんはいくらですか。","Giá bao nhiêu tiền?","How much is the price?"),
    row("褒める","ほめる","N4","v1|vt",
        "khen ngợi | ca ngợi | tán dương | nói tốt về | nói lời khen",
        "to praise | to commend | to compliment | to speak well of | to speak highly of",
        "1603550",
        "先生に褒められました。","せんせいにほめられました。","Tôi được thầy khen.","I was praised by the teacher."),
    row("申し込み","もうしこみ","N4","n",
        "đăng ký | nộp đơn | yêu cầu | đăng ký dịch vụ | đề nghị | đề xuất | lời mời",
        "application | entry | request | subscription | offer | proposal | overture",
        "1605140",
        "申し込みをします。","もうしこみをします。","Tôi đăng ký.","I make an application."),
    row("治す","なおす","N4","v5s|vt",
        "chữa bệnh | chữa lành",
        "to cure | to heal",
        "2856318",
        "病気を治します。","びょうきをなおします。","Tôi chữa bệnh.","I cure the illness."),
    row("リラックス","リラックス","N4","n|vs|vi",
        "thư giãn | nghỉ ngơi | thả lỏng",
        "relaxing | relaxation",
        "1143240",
        "リラックスしましょう。","リラックスしましょう。","Hãy thư giãn nào.","Let's relax."),
    row("屋根","やね","N4","n",
        "mái nhà",
        "roof",
        "1182700",
        "屋根が壊れました。","やねがこわれました。","Mái nhà bị hỏng.","The roof is broken."),
    row("岩","いわ","N4","n",
        "đá | tảng đá | vách đá",
        "rock | boulder | crag",
        "1217270",
        "岩の上に登ります。","いわのうえにのぼります。","Tôi leo lên tảng đá.","I climb on the rock."),
    row("教育","きょういく","N4","n|vs|vt",
        "giáo dục | trường học | đào tạo | hướng dẫn | giảng dạy | nuôi dưỡng",
        "education | schooling | training | instruction | teaching | upbringing",
        "1236950",
        "教育が大切です。","きょういくがたいせつです。","Giáo dục rất quan trọng.","Education is important."),
    row("昆虫","こんちゅう","N4","n|adj-no",
        "côn trùng | sâu bọ",
        "insect | bug",
        "1289980",
        "昆虫を観察します。","こんちゅうをかんさつします。","Tôi quan sát côn trùng.","I observe insects."),
    row("最小","さいしょう","N4","adj-no|n",
        "nhỏ nhất | ít nhất | tối thiểu | tối giản",
        "smallest (in size, degree, etc.) | least | minimum | minimal",
        "1294000",
        "最小限にします。","さいしょうげんにします。","Tôi giảm xuống mức tối thiểu.","I minimize it."),
    row("最大","さいだい","N4","n|adj-no",
        "lớn nhất | vĩ đại nhất | tối đa | cực đại",
        "biggest | greatest | largest | maximum",
        "1294180",
        "最大の努力をします。","さいだいのどりょくをします。","Tôi nỗ lực tối đa.","I make maximum effort."),
    row("才能","さいのう","N4","n",
        "tài năng | khả năng | năng khiếu",
        "talent | ability",
        "1294630",
        "才能があります。","さいのうがあります。","Có tài năng.","There is talent."),
    row("支出","ししゅつ","N4","n|vs|vt",
        "chi tiêu | chi phí | khoản chi",
        "expenditure | disbursement | expenses",
        "1310180",
        "支出を減らします。","ししゅつをへらします。","Tôi giảm chi tiêu.","I reduce expenses."),
    row("次第に","しだいに","N4","adv",
        "dần dần | từng bước | ít một | từ từ",
        "gradually | by degrees | little by little | bit by bit",
        "1316690",
        "次第に慣れてきました。","しだいになれてきました。","Dần dần tôi đã quen.","I gradually got used to it."),
    row("収入","しゅうにゅう","N4","n",
        "thu nhập | tiền kiếm được | doanh thu | thu được | tiền thu vào",
        "income | earnings | revenue | proceeds | takings | receipts",
        "1330790",
        "収入が増えました。","しゅうにゅうがふえました。","Thu nhập tăng lên.","Income has increased."),
    row("出勤","しゅっきん","N4","n|vs|vi",
        "đi làm | có mặt tại nơi làm việc | chấm công",
        "going to work | leaving for work | attendance (at work) | being at work",
        "1338600",
        "毎日9時に出勤します。","まいにちくじにしゅっきんします。","Hàng ngày tôi đi làm lúc 9 giờ.","I go to work at 9 o'clock every day."),
    row("出張","しゅっちょう","N4","n|vs|vi",
        "công tác | đi công tác | chuyến đi công việc",
        "business trip | official trip",
        "1339660",
        "来週出張があります。","らいしゅうしゅっちょうがあります。","Tuần tới tôi đi công tác.","I have a business trip next week."),
    row("詳細","しょうさい","N4","n|adj-na",
        "chi tiết | đặc điểm cụ thể | tỉ mỉ | cẩn thận | chi ly",
        "details | particulars | specifics | detailed | specific | minute | close | careful",
        "1351760",
        "詳細を確認します。","しょうさいをかくにんします。","Tôi xác nhận chi tiết.","I confirm the details."),
    row("植物","しょくぶつ","N4","n",
        "thực vật | cây cối | thảm thực vật",
        "plant | vegetation",
        "1357300",
        "植物を育てます。","しょくぶつをそだてます。","Tôi trồng cây.","I grow plants."),
    row("数量","すうりょう","N4","n",
        "số lượng | khối lượng | số",
        "quantity | volume | amount",
        "1373320",
        "数量を確認します。","すうりょうをかくにんします。","Tôi xác nhận số lượng.","I confirm the quantity."),
    row("生物","せいぶつ","N4","n",
        "sinh vật | cơ thể sống | tạo vật | sự sống | sinh học",
        "living thing | organism | creature | life | biology",
        "1379430",
        "海の生物が好きです。","うみのせいぶつがすきです。","Tôi thích sinh vật biển.","I like sea creatures."),
    row("石","いし","N4","n",
        "đá | đá cuội | đá quý | đá lửa | quân cờ vây",
        "stone | rock | pebble | jewel | precious stone | flint (in a lighter) | counter for games of go",
        "1382440",
        "石を拾いました。","いしをひろいました。","Tôi nhặt viên đá.","I picked up a stone."),
    row("泥","どろ","N4","n",
        "bùn | đất ẩm ướt | kẻ trộm | Android (hệ điều hành di động)",
        "mud | (wet) dirt | thief | Android (mobile operating system)",
        "1436900",
        "泥だらけになりました。","どろだらけになりました。","Tôi bị dính bùn đầy người.","I got covered in mud."),
    row("転勤","てんきん","N4","n|vs|vi",
        "luân chuyển công tác | thuyên chuyển nơi làm việc | chuyển nội bộ công ty",
        "job transfer | job relocation | intra-company transfer",
        "1441120",
        "来月転勤になりました。","らいげつてんきんになりました。","Tháng sau tôi được thuyên chuyển.","I got transferred next month."),
    row("投資","とうし","N4","n|vs|vt|vi",
        "đầu tư",
        "investment",
        "1447230",
        "将来のために投資します。","しょうらいのためにとうしします。","Tôi đầu tư cho tương lai.","I invest for the future."),
    row("動物","どうぶつ","N4","n",
        "động vật | con vật",
        "animal",
        "1451470",
        "動物が好きです。","どうぶつがすきです。","Tôi thích động vật.","I like animals."),
    row("能力","のうりょく","N4","n",
        "năng lực | khả năng | tài năng | kỹ năng",
        "ability | faculty",
        "1470370",
        "能力を高めます。","のうりょくをたかめます。","Tôi nâng cao năng lực.","I improve my ability."),
    row("物価","ぶっか","N4","n",
        "giá cả hàng hóa | giá cả (nói chung) | chi phí sinh hoạt",
        "prices of commodities | prices (in general) | cost-of-living",
        "1502430",
        "物価が上がりました。","ぶっかがあがりました。","Giá cả tăng lên.","Prices have risen."),
    row("物置","ものおき","N4","n",
        "phòng kho | kho chứa đồ | kho",
        "storage room | storeroom | lumber room",
        "1502690",
        "物置に入れます。","ものおきにいれます。","Tôi cất vào kho.","I put it in storage."),
    row("木の葉","このは","N4","exp|n",
        "lá (của cây) | lá cây | tán lá",
        "leaf (of a tree) | tree leaves | foliage",
        "1534560",
        "木の葉が落ちました。","このはがおちました。","Lá cây rụng xuống.","The leaves fell."),
    row("利息","りそく","N4","n",
        "lãi suất | tiền lãi (vay, tiền gửi)",
        "interest (on a loan, deposit etc.)",
        "1549600",
        "利息がつきます。","りそくがつきます。","Có lãi suất.","Interest is added."),
    row("離婚","りこん","N4","n|vs|vi",
        "ly hôn | ly dị",
        "divorce",
        "1550880",
        "離婚しました。","りこんしました。","Họ đã ly hôn.","They divorced."),
    row("留学生","りゅうがくせい","N4","n",
        "du học sinh | sinh viên trao đổi",
        "overseas student | exchange student",
        "1552750",
        "留学生として日本に来ました。","りゅうがくせいとしてにほんにきました。","Tôi đến Nhật Bản với tư cách du học sinh.","I came to Japan as an overseas student."),
    row("少なくとも","すくなくとも","N4","adv",
        "ít nhất | tối thiểu",
        "at least",
        "1595610",
        "少なくとも一時間かかります。","すくなくともいちじかんかかります。","Mất ít nhất một tiếng.","It takes at least one hour."),
    row("根っこ","ねっこ","N4","n",
        "rễ (của cây) | gốc cây | căn nguyên (của vấn đề) | cơ sở | nguồn gốc",
        "root (of a plant) | stump (of a tree) | root (of a problem, etc.) | base | origin",
        "1612490",
        "問題の根っこを探します。","もんだいのねっこをさがします。","Tôi tìm căn nguyên của vấn đề.","I look for the root of the problem."),
    row("だんだん","だんだん","N4","int",
        "cảm ơn (phương ngữ vùng Izumo)",
        "thank you",
        "2546180"),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
