# -*- coding: utf-8 -*-
"""Build N3 ready wave 063 — 100 freshly-curated N3 finance/legal/admin nouns + action verbs."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-063.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("口座","こうざ","n","tài khoản (ngân hàng)","account (e.g. bank)","1276150"),
    ("通帳","つうちょう","n","sổ ngân hàng | sổ tiết kiệm","passbook | bankbook","1433490"),
    ("残高","ざんだか","n","số dư (tài khoản) | phần còn lại","(bank) balance | remainder","1304590"),
    ("送金","そうきん","n|vs|vt|vi","chuyển tiền | gửi tiền","remittance | sending money | transferring money","1402750"),
    ("入金","にゅうきん","n|vs|vt|vi","nạp tiền | tiền vào | thanh toán","receipt of money | depositing | payment","1466040"),
    ("金利","きんり","n","lãi suất | tiền lãi","interest rate | interest","1243330"),
    ("担保","たんぽ","n|vs|vt","thế chấp | tài sản đảm bảo | bảo đảm","security | collateral | mortgage | guarantee","1418210"),
    ("保証人","ほしょうにん","n","người bảo lãnh | người bảo đảm","guarantor | surety | sponsor","1513820"),
    ("債務","さいむ","n","khoản nợ | nghĩa vụ nợ","debt | liabilities | obligation","1292110"),
    ("債権","さいけん","n","quyền đòi nợ | trái quyền","credit | claim","1292080"),
    ("破綻","はたん","n|vs|vi","đổ vỡ | phá sản | sụp đổ | rạn nứt","failure | collapse | bankruptcy | break-up","1471390"),
    ("清算","せいさん","n|vs|vt","thanh toán | quyết toán | thanh lý | chấm dứt","(financial) settlement | liquidation | ending (a relationship)","1378210"),
    ("精算","せいさん","n|vs|vt","tính toán chính xác | quyết toán | điều chỉnh","exact calculation | squaring of accounts | adjustment","1379930"),
    ("投機","とうき","n","đầu cơ | đánh bạc (cổ phiếu)","speculation | venture | gambling (on stocks)","1447120"),
    ("証券","しょうけん","n","chứng khoán | trái phiếu | chứng chỉ","bond | certificate | security","1351610"),
    ("国債","こくさい","n","nợ công | trái phiếu chính phủ","national debt | government bonds","1286390"),
    ("配当","はいとう","n|vs|vt","cổ tức | phân chia | chia phần","allotment | share | dividend","1473170"),
    ("暴落","ぼうらく","n|vs|vi","rớt giá thê thảm | sụt giá mạnh","slump | crash | heavy fall","1519570"),
    ("高騰","こうとう","n|vs|vi","tăng vọt (giá) | leo thang","sharp rise (in prices) | soaring","1283870"),
    ("下落","げらく","n|vs|vi","sụt giảm | mất giá | rớt giá","depreciation | decline | fall | slump","1186510"),
    ("急騰","きゅうとう","n|vs|vi","tăng đột biến | tăng vọt","sudden rise (in price) | surge","1228920"),
    ("変動","へんどう","n|vs|vi","biến động | dao động","change | fluctuation","1511450"),
    ("利回り","りまわり","n","lợi suất | lợi tức (đầu tư)","interest | (investment) yield | profits","1549490"),
    ("元本","がんぽん","n","tiền gốc | vốn gốc","principal | capital","1261070"),
    ("資本金","しほんきん","n","vốn điều lệ | vốn cổ phần","capital stock","1312790"),
    ("出資","しゅっし","n|vs|vt|vi","góp vốn | đầu tư | tài trợ","investment | contribution | financing","1339080"),
    ("融資","ゆうし","n|vs|vt","cho vay | tài trợ vốn | khoản vay","financing | loan","1542600"),
    ("貸付","かしつけ","n|vs","cho vay | khoản cho vay","loan","1411150"),
    ("借入金","かりいれきん","n","tiền vay | khoản nợ vay","loan | loan payable | debt","1324030"),
    ("負債","ふさい","n","nợ | khoản nợ phải trả","debt | liabilities","1498080"),
    ("純資産","じゅんしさん","n","tài sản ròng | vốn chủ sở hữu","net worth | net assets","2689220"),
    ("帳簿","ちょうぼ","n","sổ kế toán | sổ sách | sổ cái","account book | register | ledger","1427560"),
    ("簿記","ぼき","n","kế toán sổ sách | ghi sổ","bookkeeping","1515230"),
    ("勘定","かんじょう","n|vs|vt","tính toán | hóa đơn | tài khoản | thanh toán","calculation | bill | account | payment","1210750"),
    ("台帳","だいちょう","n","sổ cái | sổ đăng ký | sổ gốc","account book | ledger | register","1412720"),
    ("伝票","でんぴょう","n","phiếu | hóa đơn | chứng từ","chit | slip | voucher","1442410"),
    ("領収","りょうしゅう","n|vs|vt","biên nhận | nhận (tiền)","receipt (of money) | receiving","1554750"),
    ("未払い","みはらい","adj-no|n","chưa thanh toán | quá hạn | còn nợ","unpaid | overdue","1527990"),
    ("分割払い","ぶんかつばらい","n","trả góp | thanh toán nhiều kỳ","payment by installments | hire-purchase","1503300"),
    ("手形","てがた","n","hối phiếu | kỳ phiếu | dấu tay","draft | promissory note | bill | handprint","1327520"),
    ("小切手","こぎって","n","séc | chi phiếu","cheque | check","1348410"),
    ("振替","ふりかえ","n","chuyển khoản | chuyển đổi","transfer | money transfer (between accounts)","1602920"),
    ("口座振替","こうざふりかえ","n","ghi nợ trực tiếp | chuyển khoản tự động","direct debit | account-to-account transfer","2799690"),
    ("名乗る","なのる","v5r|vi|vt","xưng tên | tự giới thiệu | nhận là | mang danh","to give one's name | to introduce oneself | to claim to be","1531650"),
    ("名付ける","なづける","v1|vt","đặt tên | gọi tên","to name | to call | to christen","1531790"),
    ("諭す","さとす","v5s|vt","khuyên nhủ | răn dạy | thuyết phục","to reason with | to advise | to admonish","1538770"),
    ("庇う","かばう","v5u|vt","che chở | bênh vực | bảo vệ | nâng niu","to protect (someone) | to defend | to stand up for","1483060"),
    ("擁護","ようご","n|vs|vt","bảo vệ | ủng hộ | che chở","protection | defence | support | safeguarding","1605850"),
    ("突っぱねる","つっぱねる","v1|vt","cự tuyệt | từ chối thẳng | gạt phắt","to reject | to spurn | to turn down","2012590"),
    ("押し切る","おしきる","v5r|vt","áp đảo | bất chấp phản đối | gạt qua","to overcome (opposition) | to force one's way","1180270"),
    ("申し立てる","もうしたてる","v1|vt","khai báo | trình bày | kiến nghị","to declare | to plead","1363070"),
    ("反論","はんろん","n|vs|vt|vi","phản bác | bác bỏ | lập luận phản đối","objection | refutation | rebuttal","1481130"),
    ("異議","いぎ","n","dị nghị | phản đối | bất đồng","objection | dissent | protest","1157580"),
    ("申し立て","もうしたて","n","lời khai | bản trình bày | sự kiến nghị","statement | declaration | allegation","1605160"),
    ("請願","せいがん","n|vs|vt","thỉnh nguyện | đơn kiến nghị","petition","1381310"),
    ("陳情","ちんじょう","n|vs|vt","kiến nghị | trần tình | thỉnh cầu","petition | appeal","1432190"),
    ("嘆願","たんがん","n|vs|vt","khẩn cầu | van xin | thỉnh cầu","entreaty | appeal | petition","1418100"),
    ("苦情","くじょう","n","khiếu nại | phàn nàn | than phiền","complaint | objection | grievance","1244520"),
    ("クレーム","クレーム","n","khiếu nại | đòi bồi thường | phàn nàn","claim (for compensation) | complaint","1045270"),
    ("告発","こくはつ","n|vs|vt","tố giác | tố cáo | khởi tố","indictment | prosecution | complaint","1286070"),
    ("告訴","こくそ","n|vs|vt","tố cáo | kiện | khởi kiện","accusation | complaint | legal action","1286030"),
    ("提訴","ていそ","n|vs|vt","khởi kiện | đệ đơn kiện","presenting a case | suing","1436440"),
    ("起訴","きそ","n|vs|vt","truy tố | khởi tố","prosecution | indictment","1223840"),
    ("上訴","じょうそ","n|vs|vi","kháng cáo | kháng án","appeal (in court)","1353680"),
    ("控訴","こうそ","n|vs|vi","kháng cáo (lên tòa cấp cao)","appeal to a higher court","1279090"),
    ("上告","じょうこく","n|vs|vi","kháng cáo lên tòa tối cao | giám đốc thẩm","final appeal to the highest court","1353200"),
    ("申告","しんこく","n|vs|vt","khai báo | kê khai (thuế) | trình báo","report | (tax) return | declaration | filing","1363100"),
    ("届け出","とどけで","n","đơn trình báo | thông báo (đăng ký)","report | notification","1457240"),
    ("登記","とうき","n|vs|vt","đăng ký (pháp lý) | đăng bạ","registry | registration","1444750"),
    ("認可","にんか","n|vs|vt","phê chuẩn | cấp phép | cho phép","approval | license | permission","1467540"),
    ("許認可","きょにんか","n|vs","cấp phép và phê duyệt | giấy phép","approval and authorization | permits and licences","2524900"),
    ("認定","にんてい","n|vs|vt","công nhận | chứng nhận | xác nhận","authorization | acknowledgment | certification","1467590"),
    ("立証","りっしょう","n|vs|vt","chứng minh | minh chứng | lập luận chứng","establishing proof | demonstration | substantiation","1551690"),
    ("証言","しょうげん","n|vs|vt","lời khai | chứng cứ (lời) | làm chứng","testimony | (verbal) evidence","1351640"),
    ("供述","きょうじゅつ","n|vs|vt","lời khai | khẩu cung | cung khai","affidavit | deposition | testimony","1233720"),
    ("自白","じはく","n|vs|vt","thú tội | tự thú | khai nhận","confession | admission","1318530"),
    ("釈明","しゃくめい","n|vs|vt|vi","giải thích | thanh minh | biện bạch","explanation | vindication","1324270"),
    ("弁明","べんめい","n|vs|vt","biện minh | thanh minh | giải trình","explanation | excuse | clarification | apology","1513140"),
    ("拘束","こうそく","n|vs|vt","ràng buộc | giam giữ | hạn chế","restriction | restraint | binding | constraint","1279000"),
    ("拘留","こうりゅう","n|vs|vt","tạm giam | giam giữ","custody | detention | confinement","1279040"),
    ("勾留","こうりゅう","n|vs|vt","tạm giam chờ xét xử | giam giữ","detention pending trial | custody","1275310"),
    ("監禁","かんきん","n|vs|vt","giam cầm | nhốt | giam giữ","confinement | imprisonment | incarceration","1213610"),
    ("押収","おうしゅう","n|vs|vt","tịch thu | thu giữ","seizure | confiscation","1180510"),
    ("没収","ぼっしゅう","n|vs|vt","tịch thu | sung công | thu hồi","seizure | confiscation | forfeiture","1521990"),
    ("差し押さえ","さしおさえ","n|vs|vt","kê biên | tịch biên | phong tỏa (tài sản)","seizure | attachment | foreclosure","1291110"),
    ("強制","きょうせい","n|vs|vt","cưỡng chế | ép buộc | bắt buộc","compulsion | coercion | enforcement","1236350"),
    ("執行","しっこう","n|vs|vt","thi hành | thực thi | chấp hành","execution | carrying out | enforcement","1319630"),
    ("適用","てきよう","n|vs|vt","áp dụng | vận dụng","application (of a rule, law, method)","1437500"),
    ("準用","じゅんよう","vs|vt","áp dụng tương tự | vận dụng có điều chỉnh","to apply (the law) with necessary modifications","1341770"),
    ("援用","えんよう","n|vs|vt","viện dẫn | trích dẫn (để chứng minh)","quotation (to support an argument) | invocation","1176690"),
    ("遵守","じゅんしゅ","n|vs|vt","tuân thủ | chấp hành | tuân theo","observance (of laws, rules) | adherence | compliance","1342180"),
    ("侵害","しんがい","n|vs|vt","xâm hại | xâm phạm | vi phạm","infringement | violation | encroachment","1359810"),
    ("侵犯","しんぱん","n|vs|vt","xâm phạm | xâm lấn | vi phạm","violation (of territory, rights) | invasion","1359880"),
    ("妨害","ぼうがい","n|vs|vt","cản trở | gây nhiễu | phá rối","obstruction | hindrance | interference | sabotage","1519130"),
    ("阻害","そがい","n|vs|vt","cản trở | kìm hãm | ức chế","obstruction | impediment | hindrance | inhibition","1397810"),
    ("抑圧","よくあつ","n|vs|vt","đàn áp | kìm nén | áp chế","check | restraint | oppression | suppression","1547270"),
    ("弾圧","だんあつ","n|vs|vt","đàn áp | trấn áp","oppression | suppression | pressure","1419410"),
    ("迫害","はくがい","n|vs|vt","ngược đãi | bức hại | đàn áp","persecution | oppression","1475730"),
    ("虐待","ぎゃくたい","n|vs|vt","ngược đãi | bạo hành | hành hạ","abuse | ill-treatment | maltreatment | cruelty","1226950"),
    ("搾取","さくしゅ","n|vs|vt","bóc lột | vắt kiệt | trục lợi","exploitation | bleeding dry | squeezing dry","1298170"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
