# -*- coding: utf-8 -*-
"""Build N1 ready wave 023 — literary/formal Sino-Japanese nouns (set 23)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-023.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("直訴","じきそ","n|vs|vt","trực tiếp khiếu nại | kêu oan thẳng lên cấp cao | thượng tố trực tiếp","direct appeal | direct petition","1431340"),
    ("直披","じきひ","n","thư riêng | thư mật (chỉ người nhận mở)","personal | confidential (letter)","1581830"),
    ("鎮魂","ちんこん","n|vs|vt","cầu siêu | an ủi vong linh | lễ siêu độ","repose of a soul | requiem","1432060"),
    ("沈潜","ちんせん","n|vs|vi","chìm sâu suy tư | lắng đọng | đắm chìm chiêm nghiệm","sinking into deep thought | contemplation","1616560"),
    ("痛哭","つうこく","n|vs|vi","khóc thảm thiết | gào khóc | đau đớn khóc than","lamentation","1687610"),
    ("追懐","ついかい","n|vs|vt","hồi tưởng | nhớ lại | hoài niệm | tưởng nhớ","recollection | reminiscence","1661850"),
    ("追慕","ついぼ","n|vs|vt","tưởng nhớ | thương nhớ | hoài niệm người đã khuất","cherishing the memory of | yearning for","1432660"),
    ("亭主","ていしゅ","n","ông chủ | chủ nhà | chủ quán | người chồng","household head | master | host | husband","1434160"),
    ("諦観","ていかん","n|vs|vt","nhìn thấu | buông bỏ | cam chịu số phận | chấp nhận","clear insight | resignation | acceptance","1436740"),
    ("逓信","ていしん","n","bưu chính viễn thông | thông tin liên lạc (bưu điện)","communications (post, telegraph)","1436780"),
    ("泥濘","でいねい","n","bùn lầy | vũng lầy | lầy lội","mud | mire","2863417"),
    ("低廉","ていれん","adj-na|n","rẻ | giá rẻ | bình dân | phải chăng","cheap | inexpensive","1434840"),
    ("定款","ていかん","n","điều lệ công ty | quy chế thành lập | hiến chương doanh nghiệp","articles of incorporation | company statute","1435480"),
    ("適者","てきしゃ","n","người phù hợp | kẻ thích nghi (適者生存)","suitable person | the fit","1656950"),
    ("鉄面皮","てつめんぴ","n|adj-na|adj-no","mặt dày | trơ trẽn | trơ tráo | vô liêm sỉ","impudence | shamelessness | brazenness","1779610"),
    ("伝播","でんぱ","n|vs|vi","lan truyền | truyền bá | lan tỏa | phát tán","transmission | propagation | spread | diffusion","1442370"),
    ("顛倒","てんどう","n","đảo lộn nhận thức | lệch lạc tư duy | rối loạn nhận thức","cognitive distortion","2271040"),
    ("天稟","てんぴん","n","thiên bẩm | tài năng trời cho | năng khiếu bẩm sinh","natural talents","1440540"),
    ("点綴","てんてい","n|vs|vt|vi","điểm xuyết | rải rác tô điểm | chấm phá","interspersion | dotting | studding","1582170"),
    ("天変","てんぺん","n","hiện tượng thiên nhiên bất thường (trên trời) | dị tượng","irregular natural phenomenon (in the sky)","1598510"),
    ("登竜門","とうりゅうもん","n","cửa vũ môn | bệ phóng thành công | cánh cửa danh vọng","gateway to success","1654630"),
    ("党派","とうは","n","phe phái | đảng phái | bè cánh | phe nhóm","faction | party | clique","1446030"),
    ("踏破","とうは","n|vs|vt","đi bộ vượt chặng | cuốc bộ băng qua | trekking xuyên suốt","travelling on foot across | traversing","1619760"),
    ("塗炭","とたん","n","cảnh lầm than | khốn khổ cùng cực | nước sôi lửa bỏng","misery | distress","1444300"),
    ("独白","どくはく","n|vs|vt|vi","độc thoại | tự nói với mình | màn độc thoại","monologue | soliloquy | talking to oneself","1624030"),
    ("吐血","とけつ","n|vs|vi","thổ huyết | nôn ra máu | ói máu","vomiting blood | hematemesis","1444170"),
    ("貪婪","どんらん","n|adj-na","tham lam | tham tàn | tham lam vô độ","avarice | greed","1585990"),
    ("内訌","ないこう","n","lục đục nội bộ | nội chiến | mâu thuẫn bên trong","internal discord","1459620"),
    ("内応","ないおう","n|vs|vi","nội ứng | thông đồng từ bên trong | làm nội gián | phản bội","secret understanding | collusion | betrayal","1457820"),
    ("難渋","なんじゅう","adj-na|n|vs|vi","khốn đốn | trắc trở | bế tắc | chật vật khó khăn","suffering | difficulty | being bogged down","1460980"),
    ("二心","ふたごころ","n","hai lòng | bụng dạ hai mặt | phản trắc | lá mặt lá trái","duplicity | treachery | double-dealing","1599850"),
    ("入魂","にゅうこん","n|vs|adj-no","dồn hết tâm huyết | thổi hồn (vào tượng) | dốc cả tâm can","putting one's heart and soul into | breathing a soul into","2807270"),
    ("韮","にら","n","hẹ | rau hẹ | lá hẹ","garlic chives | Chinese chives","1467090"),
    ("人相","にんそう","n","tướng mạo | diện mạo | nét mặt | nhân tướng học","looks | countenance | physiognomy","1368530"),
    ("忍従","にんじゅう","n|vs|vi","nhẫn nhịn phục tùng | cam chịu | nhún nhường chịu đựng","submission | resignation","1467480"),
    ("寧日","ねいじつ","n","ngày yên bình | ngày thanh thản | ngày bình yên","peaceful day","1642840"),
    ("熱誠","ねっせい","adj-na|n","nhiệt thành | chân thành tha thiết | hết lòng","earnestness","1832520"),
    ("脳裏","のうり","n","trong tâm trí | trong đầu | tâm khảm (脳裏に浮かぶ)","one's mind","1470550"),
    ("覗き","のぞき","n|adj-no","nhìn trộm | nhòm ngó | rình mò | trò xem lén","peep | peeping | peep show","1470810"),
    ("野放図","のほうず","adj-na|n","buông tuồng | vô tổ chức | bừa bãi | tràn lan không kiểm soát","wild | unruly | uncontrolled | rampant","1537640"),
    ("俳諧","はいかい","n","thơ hài hước | thơ haikai | renga trào phúng | hài hước","haikai | comical linked verse","1471990"),
    ("背反","はいはん","n|vs|vi","phản nghịch | đi ngược lại | mâu thuẫn | nổi loạn","revolting | going against | contradiction","1616980"),
    ("廃絶","はいぜつ","n|vs|vt|vi","bãi bỏ | xóa sổ | tuyệt diệt | chấm dứt hẳn","abolition | elimination | extinction","1472150"),
    ("排他","はいた","n","bài ngoại | loại trừ | bài xích | độc quyền cự tuyệt","exclusion","1472420"),
    ("売名","ばいめい","n","đánh bóng tên tuổi | tự quảng cáo | mua danh","self-advertisement","1474080"),
    ("莫逆","ばくぎゃく","n","tâm giao | thâm tình | bạn chí cốt | bằng hữu khăng khít","cordial relations","1662840"),
    ("博引","はくいん","n|vs","viện dẫn rộng rãi | trích dẫn phong phú | dẫn chứng nhiều","extensive references","1690320"),
    ("迫真","はくしん","adj-no|n","chân thực | sống động như thật | như thật","realistic | true to life","1475760"),
    ("白眉","はくび","n","xuất sắc nhất | tinh hoa | đỉnh cao | nổi bật nhất","finest example | the best (of)","1841440"),
    ("覇道","はどう","n","bá đạo | cai trị bằng vũ lực | con đường xưng bá","rule by military force | path of supremacy","1841810"),
    ("跋扈","ばっこ","n|vs|vi","hoành hành | lộng hành | tác oai tác quái | ngang ngược","rampancy | prevalence | domination","1573260"),
    ("跋文","ばつぶん","n","lời bạt | phần kết | hậu ký | bài viết cuối","afterword | epilogue | postscript","1680140"),
    ("万感","ばんかん","n","muôn vàn cảm xúc | trăm mối cảm hoài | bao tâm tư","flood of emotions | many thoughts","1525860"),
    ("半端","はんぱ","n|adj-na","dở dang | lưng chừng | lẻ | nửa vời | thiếu hoàn chỉnh","incomplete | halfway | half-hearted | fraction","1479640"),
    ("反目","はんもく","n|vs|vi","đối địch | thù hằn | bất hòa | xích mích","enmity | antagonism | hostility","1481040"),
    ("万雷","ばんらい","n","sấm rền | tiếng vang như sấm (万雷の拍手)","heavy thunder","1526570"),
    ("比肩","ひけん","n|vs|vi","sánh ngang | ngang hàng | tương đương | sánh vai","ranking equal with | comparing favourably with","1483630"),
    ("鼻祖","びそ","n","thủy tổ | ông tổ | người khai sáng | người đầu tiên","founder | originator","1487080"),
    ("畢生","ひっせい","n|adv","cả đời | trọn đời | cả cuộc đời | suốt đời","lifetime","1731880"),
    ("逼迫","ひっぱく","n|vs|vi","căng thẳng | eo hẹp (tài chính) | bức bách | ngặt nghèo","tightness (of finances) | pressure | being strained","1487940"),
    ("匹夫","ひっぷ","n","kẻ thất phu | người thường | kẻ tầm thường | thất phu","man of humble position | commoner | man of little worth","1487260"),
    ("非道","ひどう","adj-na|adj-no|n","bất nhân | vô đạo | tàn nhẫn | phi nghĩa","unjust | inhuman","1688840"),
    ("微塵","みじん","n|adj-no","mảy may | hạt bụi | một chút | tí xíu (微塵もない: không một chút)","particle | tiny piece | not the slightest","1486050"),
    ("冷や飯","ひやめし","n","cơm nguội | kẻ ăn bám | bị hắt hủi | bị ghẻ lạnh (冷や飯を食う)","cold rice | hanger-on | being treated coldly","1556800"),
    ("飄逸","ひょういつ","adj-na","thảnh thơi | phóng khoáng | vô tư lự | ung dung tự tại","easygoing | unconventional | happy-go-lucky","2104320"),
    ("披瀝","ひれき","n|vs|vt","bày tỏ | giãi bày | thổ lộ | bộc bạch (心境を披瀝)","expressing one's opinion | speaking one's mind | revealing","1483480"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
