# -*- coding: utf-8 -*-
"""Build N2 ready wave 003 — 79 freshly-curated N2 〜化/〜性 nouns + policy/society + 〜算/〜金 nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-003.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("強化","きょうか","n|vs|vt","tăng cường | củng cố | gia cố","strengthening | reinforcement | enhancement","1236200"),
    ("合理化","ごうりか","n|vs|vt","hợp lý hóa | tinh giản | biện minh","rationalization | streamlining | justification","1285340"),
    ("近代化","きんだいか","n|vs|vt|vi","hiện đại hóa","modernization","1242430"),
    ("民営化","みんえいか","n|vs|vt","tư nhân hóa | cổ phần hóa","privatization","1528600"),
    ("自由化","じゆうか","n|vs|vt","tự do hóa | nới lỏng","liberalization | freeing","1318750"),
    ("多様化","たようか","n|vs|vi","đa dạng hóa","diversification","1408110"),
    ("一般化","いっぱんか","n|vs|vt|vi","tổng quát hóa | phổ biến hóa","generalization | popularization","1165810"),
    ("標準化","ひょうじゅんか","n|vs|vt","tiêu chuẩn hóa","standardization","1488720"),
    ("過疎化","かそか","n|vs|vi","giảm dân số | thưa dân","depopulation | decrease in population","2526640"),
    ("同化","どうか","n|vs|vt|vi","đồng hóa | hòa nhập | hấp thụ","assimilation | absorption | adaptation","1451960"),
    ("美化","びか","n|vs|vt","làm đẹp | mỹ hóa | tô vẽ | lý tưởng hóa","beautification | glorification | idealization","1486370"),
    ("浄化","じょうか","n|vs|vt","thanh lọc | làm sạch | thanh trừng","purification | cleanup | purge","1356630"),
    ("民主化","みんしゅか","n|vs","dân chủ hóa","democratization","1528800"),
    ("国際化","こくさいか","n|vs|vt|vi","quốc tế hóa","internationalization","1286420"),
    ("活性化","かっせいか","n|vs|vt|vi","kích hoạt | làm sôi động | phục hồi sinh khí","stimulation | revitalization | activation","1208340"),
    ("正常化","せいじょうか","n|vs|vt|vi","bình thường hóa","normalization","1377400"),
    ("簡素化","かんそか","n|vs|vt","đơn giản hóa | tinh giản","simplification","1214310"),
    ("老朽化","ろうきゅうか","n|vs|vi","cũ kỹ | xuống cấp | hao mòn","deterioration | becoming decrepit | becoming worn out","2147680"),
    ("慣性","かんせい","n","quán tính","inertia","1212710"),
    ("必然性","ひつぜんせい","n","tính tất yếu | tính tất nhiên","necessity | inevitability","1487580"),
    ("普遍性","ふへんせい","n","tính phổ quát | tính phổ biến","universality","1497300"),
    ("公共性","こうきょうせい","n","tính công cộng | tính cộng đồng","publicness | public nature | commonality","1273560"),
    ("整合性","せいごうせい","n","tính nhất quán | tính phù hợp | tính tương thích","integrity | consistency | conformity","1376180"),
    ("正当性","せいとうせい","n","tính chính đáng | tính hợp pháp | tính hợp lý","legitimacy | legality | validity | justifiability","1377680"),
    ("治安","ちあん","n","trị an | an ninh trật tự | an ninh công cộng","public order | public security | law and order","1316840"),
    ("秩序","ちつじょ","n","trật tự | kỷ cương | quy củ","order | discipline | regularity | system","1422520"),
    ("規律","きりつ","n","kỷ luật | quy tắc | trật tự","order | discipline | rules | regulations","1223120"),
    ("道義","どうぎ","n","đạo nghĩa | đạo lý | nguyên tắc đạo đức","morality | moral principles","1454150"),
    ("模範","もはん","n","khuôn mẫu | gương mẫu | hình mẫu","exemplar | model | example | pattern","1533690"),
    ("規範","きはん","n","chuẩn mực | quy phạm | tiêu chuẩn | khuôn mẫu","model | standard | norm | criterion","1591390"),
    ("尺度","しゃくど","n","thước đo | tiêu chuẩn | chuẩn mực | tỷ lệ","gauge | standard | measure | criterion | scale","1324130"),
    ("目安","めやす","n","tiêu chí | mốc | thước đo | ước lượng","criterion | yardstick | aim | rough estimate","1535280"),
    ("指標","しひょう","n","chỉ số | chỉ tiêu | thước đo","index | indicator","1309990"),
    ("指針","ししん","n","kim chỉ nam | phương châm | hướng dẫn | kim (đồng hồ)","guiding principle | guideline | needle (gauge)","1309840"),
    ("要綱","ようこう","n","cương lĩnh | đề cương | nguyên tắc chính | hướng dẫn","main principle | gist | general plan | guidelines","1546740"),
    ("綱領","こうりょう","n","cương lĩnh | tôn chỉ | điểm chính | bản tuyên ngôn","general plan | platform | mission statement","1280940"),
    ("方策","ほうさく","n","đối sách | biện pháp | phương sách","plan | measure | means | scheme | policy","1517020"),
    ("施策","しさく","n","chính sách | biện pháp (thực thi)","policy | measure","1310380"),
    ("策略","さくりゃく","n","mưu lược | mưu kế | thủ đoạn | sách lược","stratagem | trick | ruse | scheme | tactics","1298300"),
    ("謀略","ぼうりゃく","n","mưu đồ | âm mưu | quỷ kế","scheme | plot | stratagem | trick","1520110"),
    ("陰謀","いんぼう","n","âm mưu | mưu đồ | thông đồng","plot | intrigue | conspiracy","1170500"),
    ("画策","かくさく","n|vs|vt","mưu tính | toan tính | giật dây","scheming | maneuvering | plotting","1197210"),
    ("工作","こうさく","n|vs|vt","thủ công | thi công | vận động hậu trường","handicraft | construction | maneuvering","1278100"),
    ("布石","ふせき","n|vs|vt","bày binh bố trận | nước đi mở đầu | sự chuẩn bị nền tảng","opening moves | preparatory steps | laying the groundwork","1496880"),
    ("布陣","ふじん","n|vs","bày trận | đội hình | bố trí lực lượng","battle formation | lineup","1624660"),
    ("方式","ほうしき","n","phương thức | cách thức | hệ thống | công thức","form | method | system | formula","1517030"),
    ("書式","しょしき","n","mẫu (viết) | định dạng | quy cách","prescribed form | format","1344060"),
    ("図式","ずしき","n","sơ đồ | biểu đồ | giản đồ","diagram | graph | schema","1370400"),
    ("数式","すうしき","n","biểu thức số | công thức số học","numerical formula","1373070"),
    ("等式","とうしき","n","đẳng thức","equality","1733560"),
    ("方程式","ほうていしき","n","phương trình | công thức (giải)","equation | formula","1517060"),
    ("算式","さんしき","n","biểu thức toán | phép tính","mathematical formula | numerical expression","2024540"),
    ("公算","こうさん","n","xác suất | khả năng","probability | likelihood","1273720"),
    ("誤算","ごさん","n|vs|vt","tính sai | sai lầm trong tính toán","miscalculation","1271340"),
    ("打算","ださん","n|vs|vt","tính toán | vụ lợi | ích kỷ","calculation | self-interest | selfishness","1623720"),
    ("概算","がいさん","n|vs|vt","ước tính | tính sơ bộ | con số áng chừng","approximation | rough estimate | ballpark figure","1204450"),
    ("試算","しさん","n|vs|vt","tính thử | tính sơ bộ | ước tính","trial calculation | estimation","1312460"),
    ("通算","つうさん","n|vs|vt","tổng cộng | cộng dồn | tổng","total | sum | aggregate","1433230"),
    ("加算","かさん","n|vs|vt","cộng | phép cộng | bổ sung","addition | adding | supplement","1190230"),
    ("減算","げんざん","n|vs|vt|vi","phép trừ | trừ","subtraction","1682990"),
    ("乗算","じょうざん","n|vs|vt","phép nhân | nhân","multiplication","1355250"),
    ("除算","じょさん","n|vs|vt","phép chia | chia","division","1345680"),
    ("逆算","ぎゃくさん","n|vs|vt","tính ngược | tính lùi | phép tính ngược","counting backwards | inverse operation","1227060"),
    ("暗算","あんざん","n|vs|vt","tính nhẩm","mental arithmetic","1154540"),
    ("珠算","しゅざん","n","tính bằng bàn tính | toán bàn tính","calculation on an abacus","1328790"),
    ("検算","けんざん","n|vs|vt","kiểm tra phép tính | tính lại","verification of a calculation","1592690"),
    ("合算","がっさん","n|vs|vt","cộng gộp | tính tổng","adding up | totalling","1284800"),
    ("積算","せきさん","n|vs|vt","tính tổng | cộng dồn | dự toán (khối lượng)","addition | integration | estimate | quantity survey","1383050"),
    ("起算","きさん","n|vs|vi","tính từ (mốc) | bắt đầu tính","reckoning from (a point, date)","1223790"),
    ("換金","かんきん","n|vs|vt","đổi ra tiền | thanh khoản | chuyển thành tiền","realization (into money) | conversion (into money)","1212800"),
    ("献金","けんきん","n|vs|vt|vi","quyên góp | đóng góp | hiến tặng (tiền)","donation | contribution | offering","1258420"),
    ("基金","ききん","n","quỹ | quỹ tài trợ","fund | foundation","1219020"),
    ("代金","だいきん","n","tiền (hàng) | chi phí | khoản phải trả","price | cost | charge | payment","1411790"),
    ("出金","しゅっきん","n|vs|vt|vi","rút tiền | chi tiền | góp vốn","withdrawal (of money) | payment | financing","1338650"),
    ("返金","へんきん","n|vs|vt|vi","hoàn tiền | trả lại tiền | bồi hoàn","refund | repayment | reimbursement","1512200"),
    ("集金","しゅうきん","n|vs|vt|vi","thu tiền | gom tiền","money collection","1333620"),
    ("賞金","しょうきん","n","tiền thưởng | giải thưởng (tiền)","prize money | monetary award","1351930"),
    ("頭金","あたまきん","n","tiền đặt cọc | tiền trả trước","down payment | deposit","1450840"),
    ("元金","がんきん","n","tiền gốc | vốn gốc","principal | capital | seed money","1578370"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
