# -*- coding: utf-8 -*-
"""Build N1 ready wave 082 — advanced katakana loanwords (set 82)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-082.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("アイデンティファイ","アイデンティファイ","n|vs","sự nhận diện | xác định danh tính | nhận dạng","identify","1014300"),
    ("アウトソーシング","アウトソーシング","n|vs","thuê ngoài | gia công bên ngoài | khoán việc cho bên thứ ba","outsourcing","1960360"),
    ("アドホック","アドホック","adj-na|n","tạm thời | đặc biệt cho từng trường hợp | đột xuất","ad hoc | temporary","1017170"),
    ("アナクロニズム","アナクロニズム","n","sự lỗi thời | sai lệch thời đại | điều không hợp thời","anachronism","1017370"),
    ("アニミズム","アニミズム","n","thuyết vạn vật hữu linh | tín ngưỡng linh hồn vạn vật","animism","1017580"),
    ("アペリティフ","アペリティフ","n","rượu khai vị | rượu uống trước bữa ăn","aperitif","1018360"),
    ("アルゴリズム","アルゴリズム","n","thuật toán | quy trình tính toán | giải thuật","algorithm","1019310"),
    ("アンチノミー","アンチノミー","n","nghịch lý logic | mâu thuẫn nội tại | phản đề đối lập","antinomy","1020310"),
    ("イコール","イコール","adj-na|n|exp","bằng | tương đương | dấu bằng | ngang bằng","equal | equivalent","1021220"),
    ("イマジネーション","イマジネーション","n","trí tưởng tượng | sự hình dung | óc tưởng tượng","imagination","1021710"),
    ("インタフェース","インタフェース","n","giao diện | mặt tiếp xúc | giao tiếp (hệ thống)","interface","1022940"),
    ("インテグレーション","インテグレーション","n","sự tích hợp | hợp nhất | sự hòa nhập","integration","1023360"),
    ("ウェイティング","ウェイティング","n","sự chờ đợi | việc xếp hàng chờ | sự kìm giữ","waiting | holding back","1926030"),
    ("エクスプレッション","エクスプレッション","n","sự biểu đạt | cách diễn đạt | biểu cảm","expression","1028070"),
    ("エモーショナル","エモーショナル","adj-na","đầy cảm xúc | giàu tình cảm | dễ xúc động","emotional","2484200"),
    ("エンパシー","エンパシー","n","sự đồng cảm | khả năng thấu cảm | sự cảm thông sâu sắc","empathy","1031330"),
    ("オーガナイザー","オーガナイザー","n","nhà tổ chức | người điều phối | ban tổ chức","organizer","1031520"),
    ("オーバーラップ","オーバーラップ","n|vs|vt|vi","sự chồng lấp | sự trùng lặp | sự đè lên nhau","overlap","1032800"),
    ("オーラ","オーラ","n","hào quang | thần thái | khí chất tỏa ra | luồng khí","aura","1033380"),
    ("オリエンテーション","オリエンテーション","n","buổi định hướng | sự hướng dẫn ban đầu | khóa làm quen","orientation","1035550"),
    ("カウンターパート","カウンターパート","n","đối tác tương ứng | người đồng cấp | bên đối ứng","counterpart","2025770"),
    ("カクテル","カクテル","n","cocktail | rượu pha | đồ uống pha trộn","cocktail","1037070"),
    ("カモフラージュ","カモフラージュ","n|vs|vt","sự ngụy trang | che giấu | đánh lạc hướng | trá hình","camouflage","1038460"),
    ("ガイダンス","ガイダンス","n","sự hướng dẫn | buổi định hướng | sự chỉ dẫn","guidance","1039890"),
    ("キャパシティ","キャパシティ","n","dung lượng | sức chứa | năng lực | khả năng tối đa","capacity","1041720"),
    ("キャプション","キャプション","n","chú thích | tiêu đề | dòng mô tả | phụ đề","caption","1041830"),
    ("クオータ","クオータ","n","hạn ngạch | chỉ tiêu | định mức | phần quy định","quota","2842269"),
    ("クレジット","クレジット","n|vs|vt","tín dụng | trả góp | thẻ tín dụng | dòng ghi công | danh đề","credit","1045330"),
    ("クロニクル","クロニクル","n","biên niên sử | ký sự | sử biên niên","chronicle","1045870"),
    ("グランドデザイン","グランドデザイン","n","thiết kế tổng thể | bản quy hoạch lớn | tầm nhìn tổng quát","grand design","2010290"),
    ("ケミストリー","ケミストリー","n","hóa học | sự ăn ý | sự tương hợp (giữa người)","chemistry","1048190"),
    ("コーポレート","コーポレート","adj-f","thuộc về công ty | doanh nghiệp | mang tính tập đoàn","corporate","2223060"),
    ("コノテーション","コノテーション","n","nghĩa hàm ẩn | nghĩa bóng | hàm ý","connotation","1050540"),
    ("コミュニカティブ","コミュニカティブ","adj-na","có tính giao tiếp | dễ giao tiếp | thiên về giao tiếp","communicative","2840261"),
    ("コラージュ","コラージュ","n","tranh cắt dán | nghệ thuật ghép hình | collage","collage","1051300"),
    ("コンサバティブ","コンサバティブ","adj-na|n","bảo thủ | thận trọng | theo lối cũ","conservative","1052000"),
    ("コンソーシアム","コンソーシアム","n","tổ hợp | liên hiệp | hiệp hội hợp tác","consortium","1052360"),
    ("サブカルチャー","サブカルチャー","n","văn hóa nhóm | tiểu văn hóa | văn hóa ngách","subculture","1057210"),
    ("サブスタンス","サブスタンス","n","bản chất | thực chất | thực thể | nội dung cốt lõi","substance","1057280"),
    ("ジェスチャー","ジェスチャー","n","cử chỉ | điệu bộ | động tác ra hiệu | trò đố hành động","gesture","1064170"),
    ("ジェンダー","ジェンダー","n","giới | giới tính (xã hội) | vai trò giới","gender","1064480"),
    ("ジャスティス","ジャスティス","n","công lý | sự công bằng | chính nghĩa","justice","1065210"),
    ("シンジケート","シンジケート","n","tổ chức tài phiệt | nghiệp đoàn | tập đoàn tội phạm | liên minh kinh doanh","syndicate","1063630"),
    ("シンドローム","シンドローム","n","hội chứng | tập hợp triệu chứng","syndrome","1063750"),
    ("スキャニング","スキャニング","n|vs|vt","sự quét | quét hình ảnh | rà quét","scanning","1067980"),
    ("スクリーニング","スクリーニング","n|vs|vt","sự sàng lọc | tầm soát | lọc chọn | kiểm tra sàng lọc","screening","1068540"),
    ("スコープ","スコープ","n","phạm vi | tầm | kính ngắm | tầm bao quát","scope","1068990"),
    ("スタンドアロン","スタンドアロン","adj-no","độc lập | đứng riêng | hoạt động độc lập | không kết nối","standalone","2275530"),
    ("ストック","ストック","n|vs|vt","hàng tồn kho | dự trữ | tích trữ | cổ phiếu | nước dùng","stock | inventory","1071010"),
    ("スパイラル","スパイラル","n","hình xoắn ốc | vòng xoáy | đường xoắn | sự xoắn trôn ốc","spiral","1072030"),
    ("スペクトル","スペクトル","n","quang phổ | phổ | dải phổ","spectrum","1073030"),
    ("スポイル","スポイル","n|vs|vt","sự làm hỏng | sự nuông chiều hư | làm hư hỏng","spoil","1073410"),
    ("セオレティカル","セオレティカル","adj-na","mang tính lý thuyết | trên lý thuyết | thuộc về lý luận","theoretical","2394900"),
    ("セッション","セッション","n","phiên | buổi (làm việc/chơi nhạc) | phiên giao dịch | buổi ngẫu hứng","session","1074580"),
    ("セレブリティー","セレブリティー","n","người nổi tiếng | nhân vật danh tiếng | ngôi sao","celebrity","2103840"),
    ("ソフィスティケーション","ソフィスティケーション","n","sự tinh tế | sự sành điệu | sự trau chuốt phức tạp","sophistication","2497070"),
    ("ダイレクト","ダイレクト","adj-na","trực tiếp | thẳng | không qua trung gian","direct","1076920"),
    ("ダンディズム","ダンディズム","n","phong cách lịch lãm | sự bảnh bao tao nhã | chủ nghĩa phong nhã (nam giới)","dandyism","2431370"),
    ("チュートリアル","チュートリアル","n","bài hướng dẫn | hướng dẫn từng bước | bài học nhập môn","tutorial","1078090"),
    ("テンポラリー","テンポラリー","n","tạm thời | nhất thời | lâm thời","temporary","1081140"),
    ("ディスクロージャー","ディスクロージャー","n","sự công bố thông tin | sự tiết lộ | minh bạch thông tin","disclosure","1081820"),
    ("ディストピア","ディストピア","n","xã hội đen tối | thế giới phản địa đàng | viễn cảnh u ám","dystopia","2231840"),
    ("ディプロマ","ディプロマ","n","văn bằng | chứng chỉ tốt nghiệp | bằng cấp","diploma","1082320"),
    ("デコレーション","デコレーション","n","sự trang trí | đồ trang trí | vật trang hoàng","decoration","1082810"),
    ("デモグラフィック","デモグラフィック","n","nhân khẩu học | đặc điểm dân số | phân khúc nhân khẩu","demographic","1084050"),
    ("テロップ","テロップ","n","dòng chữ trên màn hình | phụ đề | chữ chạy trên TV","on-screen caption","1080870"),
    ("ドキュメンタリー","ドキュメンタリー","n","phim tài liệu | thể loại tài liệu | ký sự tư liệu","documentary","1088080"),
    ("ドメスティック","ドメスティック","adj-no","nội địa | trong nước | thuộc gia đình | hẹp hòi địa phương","domestic | provincial","2448100"),
    ("ナルシシズム","ナルシシズム","n","sự tự yêu bản thân | thói ái kỷ | chủ nghĩa ngã ái","narcissism","1090730"),
    ("ニュートン","ニュートン","n","Newton (đơn vị lực) | Niu-tơn","newton (unit of force)","1091780"),
    ("ネットワーキング","ネットワーキング","n","sự kết nối mạng lưới | xây dựng quan hệ | tạo dựng mối quan hệ","networking","1093110"),
    ("ノーブル","ノーブル","adj-na","cao quý | quý phái | thanh cao | sang trọng","noble","1093550"),
    ("ハーモニー","ハーモニー","n","sự hòa hợp | hòa âm | sự hài hòa","harmony","1094850"),
    ("バイオレンス","バイオレンス","n|adj-na","bạo lực | sự hung bạo | mang tính bạo lực","violence","1097770"),
    ("バランス感覚","バランスかんかく","n","khả năng giữ cân bằng | sự cân nhắc thăng bằng | óc dung hòa","a sense of balance","2212210"),
    ("パースペクティブ","パースペクティブ","n","góc nhìn | viễn cảnh | phối cảnh | tầm nhìn","perspective","1100570"),
    ("パーソナリティー","パーソナリティー","n","tính cách | cá tính | nhân cách | người dẫn (chương trình)","personality","1100630"),
    ("パイオニア","パイオニア","n","người tiên phong | người khai phá | người mở đường","pioneer","1101080"),
    ("パッケージング","パッケージング","n","sự đóng gói | bao bì | cách trình bày gói sản phẩm","packaging","1101750"),
    ("ヒステリー","ヒステリー","n","chứng cuồng loạn | sự kích động thái quá | hysteria","hysteria","1103720"),
    ("ピボット","ピボット","n","trục xoay | điểm tựa | sự chuyển hướng chiến lược","pivot","1106870"),
    ("ファクト","ファクト","n","sự thật | dữ kiện | thực tế | điều có thật","fact","1107990"),
    ("フォーカス","フォーカス","n|vs|vi|vt","tiêu điểm | sự tập trung | lấy nét | trọng tâm","focus","1110100"),
    ("フォーメーション","フォーメーション","n","đội hình | sự sắp xếp đội hình | cách bố trí","formation","1110370"),
    ("プラトニック","プラトニック","adj-na","tình yêu thuần khiết | tinh thần thuần túy | phi xác thịt","platonic","1115840"),
    ("ブランディング","ブランディング","n|vs","xây dựng thương hiệu | tạo dựng nhãn hiệu | định vị thương hiệu","branding","2747230"),
    ("ヘテロ","ヘテロ","pref|n|adj-no","dị | khác loại | dị tính | dị hợp tử","hetero- | heterosexual","1118530"),
    ("ポートフォリオ","ポートフォリオ","n","danh mục đầu tư | hồ sơ năng lực | tập tác phẩm","portfolio","1124730"),
    ("マネジメント","マネジメント","n","sự quản lý | việc điều hành | quản trị","management","1128980"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
