# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-034.csv -- 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-034.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("頭","がしら","N4","suf",
        "đứng đầu... | trưởng... | thủ lĩnh...",
        "top of ... | head of ... | the moment that ...",
        "2252670",
        "組がしら。","くみがしら。",
        "Trưởng nhóm.","Head of the group."),
    row("頭","かぶし","N4","n",
        "hình dạng đầu",
        "shape of one's head",
        "2791490",
        "かぶしが大きい。","かぶしがおおきい。",
        "Cái đầu to.","One's head is large."),
    row("頭","こうべ","N4","n",
        "đầu (cách đọc cổ điển)",
        "head",
        "2791510",
        "こうべを垂れる。","こうべをたれる。",
        "Cúi đầu.","Bow one's head."),
    row("頭","ず","N4","n",
        "đầu (trong từ ghép)",
        "head",
        "2843246",
        "ず痛。","ずつう。",
        "Đau đầu.","Headache."),
    row("頭","かぶり","N4","n",
        "đầu (dùng trong cụm từ lắc đầu)",
        "head",
        "2856438",
        "かぶりを振る。","かぶりをふる。",
        "Lắc đầu.","Shake one's head."),
    row("頭","つむり","N4","n",
        "cái đầu | đỉnh đầu",
        "head",
        "2856439",
        "つむりをなでる。","つむりをなでる。",
        "Xoa đầu.","Pat one's head."),
    row("頭","つむ","N4","n",
        "đỉnh đầu | cái đầu (dạng rút gọn)",
        "head",
        "2856440",
        "つむを下げる。","つむをさげる。",
        "Cúi đầu.","Lower one's head."),
    row("米","よね","N4","n",
        "88 tuổi | gạo (cách đọc cổ)",
        "88 years old | rice",
        "2848538",
        "米寿はよねじゅです。","べいじゅはよねじゅです。",
        "Thọ 88 tuổi là beinju.","88 years old is beiju."),
    row("腰","ごし","N4","n-suf",
        "tư thế | cách đứng | thái độ",
        "posture | position | pose | attitude",
        "2819280",
        "腰が低い。","こしがひくい。",
        "Khiêm tốn.","Humble posture."),
    row("止まる","とどまる","N4","v5r|vi",
        "dừng lại | ở lại | bị giới hạn trong | chỉ tính đến",
        "to remain | to abide | to stay (in the one place) | to be limited to | to be confined to | to only account for",
        "2657130",
        "現状に止まる。","げんじょうにとどまる。",
        "Dừng lại ở hiện trạng.","Remain in the current state."),
    row("止まる","やまる","N4","v5r|vi",
        "chấm dứt | ngừng lại | kết thúc",
        "to cease | to stop | to be over",
        "2657250",
        "雨がやまる。","あめがやまる。",
        "Mưa ngừng.","The rain stops."),
    row("音","おん","N4","n|n-suf",
        "âm thanh | cách đọc Hán-Nhật của chữ Hán",
        "sound | noise | (speech) sound | Chinese-derived reading of a kanji",
        "2859161",
        "音読みです。","おんよみです。",
        "Đây là âm Hán.","This is the on'yomi reading."),
    row("音","ね","N4","n",
        "âm thanh | thanh âm | nốt nhạc | tiếng kêu",
        "sound | tone | note | ring | chirp",
        "2859162",
        "虫の音。","むしのね。",
        "Tiếng côn trùng.","Sound of insects."),
    row("腸","わた","N4","n",
        "lòng ruột | nội tạng",
        "entrails | guts",
        "2863261",
        "腸を取り出す。","わたをとりだす。",
        "Lấy ruột ra.","Remove the entrails."),
    row("抱く","だく","N4","v5k|vt",
        "ôm trong tay | ôm chặt | ấp trứng | ngủ cùng",
        "to hold in one's arms (e.g. a baby) | to embrace | to hug | to have sex with | to sit on (eggs) | to brood",
        "2844997",
        "赤ちゃんを抱く。","あかちゃんをだく。",
        "Ôm em bé vào lòng.","Hold the baby in one's arms."),
    row("抱く","うだく","N4","v4k|vt",
        "ôm trong tay | ôm chặt (dạng cổ)",
        "to hold in one's arms (e.g. a baby) | to embrace | to hug",
        "2844998",
        "子をうだく。","こをうだく。",
        "Bồng đứa trẻ.","Hold a child in one's arms."),
    row("雷","いかずち","N4","n",
        "sét | sấm | tia sét (cách đọc cổ)",
        "lightning | thunder | thunderbolt",
        "2868304",
        "いかずちが落ちた。","いかずちがおちた。",
        "Sét đã đánh xuống.","Lightning struck."),
    row("雷","らい","N4","n",
        "sấm sét | sét (trong từ ghép)",
        "thunder | lightning",
        "2868307",
        "雷鳴が聞こえる。","らいめいがきこえる。",
        "Nghe tiếng sấm vang.","I can hear thunder."),
    row("葛藤","つづらふじ","N4","n",
        "cây nguyệt quế Trung Quốc | mối quan hệ rắc rối phức tạp",
        "Chinese moonseed (Sinomenium acutum) | complex inter-relationship",
        "2464550",
        "葛藤が生じた。","かっとうがしょうじた。",
        "Mâu thuẫn nảy sinh.","Conflict arose."),
    row("形","かた","N4","n|n-suf",
        "hình dạng | hình thức | phong cách | tài sản thế chấp",
        "shape | form | style | security | collateral | obverse of an old zeni coin",
        "2068070",
        "形にしたがう。","かたにしたがう。",
        "Làm theo hình thức.","Follow the form."),
    row("光沢","こうたく","N4","n",
        "độ bóng | sự lấp lánh | sự đánh bóng | bề mặt bóng",
        "brilliance | polish | lustre | luster | glossy finish",
        "1273050",
        "光沢がある。","こうたくがある。",
        "Có độ bóng.","It is glossy."),
    row("力強い","ちからづよい","N4","adj-i",
        "mạnh mẽ | lực lưỡng | quyết đoán | làm tôi yên tâm",
        "powerful | strong | forceful | vigorous | reassuring | encouraging",
        "1554940",
        "力強い返答。","ちからづよいへんとう。",
        "Câu trả lời mạnh mẽ.","A powerful reply."),
    row("半透明","はんとうめい","N4","adj-na|adj-no|n",
        "nửa trong suốt | mờ đục | bán trong suốt",
        "semi-transparent | translucent",
        "1479780",
        "半透明のガラス。","はんとうめいのがらす。",
        "Kính bán trong suốt.","Semi-transparent glass."),
    row("口座番号","こうざばんごう","N4","n",
        "số tài khoản (ngân hàng)",
        "account number (bank, etc.)",
        "2143390",
        "口座番号を教えてください。","こうざばんごうをおしえてください。",
        "Xin cho tôi biết số tài khoản.","Please tell me the account number."),
    row("噴く","ふく","N4","v5k|vt|vi",
        "phun ra | xịt ra | trào ra | sôi trào",
        "to emit | to spout | to spurt | to boil over",
        "2836243",
        "水を噴く。","みずをふく。",
        "Phun nước ra.","Spout water."),
    row("奥深い","おくふかい","N4","adj-i",
        "sâu sắc | uyên thâm | sâu xa | tận sâu bên trong",
        "profound | deep | deep (of a cave, etc.) | innermost | interior",
        "1179570",
        "奥深い意味。","おくふかいいみ。",
        "Ý nghĩa sâu sắc.","A profound meaning."),
    row("年末調整","ねんまつちょうせい","N4","n",
        "quyết toán thuế cuối năm",
        "year-end tax adjustment",
        "1731010",
        "年末調整をします。","ねんまつちょうせいをします。",
        "Tôi thực hiện quyết toán thuế cuối năm.","I do the year-end tax adjustment."),
    row("引き落とし","ひきおとし","N4","n",
        "ghi nợ | rút tiền tự động | thanh toán tự động",
        "debit | withdrawal | pulling (one's opponent) down",
        "1950210",
        "口座引き落とし。","こうざひきおとし。",
        "Rút tiền tự động từ tài khoản.","Automatic bank debit."),
    row("手数料","てすうりょう","N4","n",
        "phí dịch vụ | phí giao dịch | hoa hồng | phí môi giới",
        "(handling) fee | charge (e.g. for a cancellation) | commission | brokerage",
        "1327980",
        "手数料がかかります。","てすうりょうがかかります。",
        "Có tính phí dịch vụ.","There is a handling fee."),
    row("繰り越し","くりこし","N4","n",
        "chuyển khoản | mang sang kỳ sau | số dư chuyển tiếp",
        "carry-over (of a balance, annual leave, etc.) | carrying over | carrying forward | balance brought forward",
        "1592430",
        "残高を繰り越します。","ざんだかをくりこします。",
        "Tôi chuyển số dư sang kỳ sau.","I carry over the balance."),
    row("加湿器","かしつき","N4","n",
        "máy tạo độ ẩm | máy phun sương",
        "humidifier",
        "1190280",
        "加湿器をつけました。","かしつきをつけました。",
        "Tôi đã bật máy tạo độ ẩm.","I turned on the humidifier."),
    row("根","こん","N4","n",
        "sự kiên trì | bền bỉ | nền tảng | căn nguyên",
        "stick-to-itiveness | perseverance | persistence | radical",
        "2182870",
        "根がある人。","こんがあるひと。",
        "Người có sự kiên trì.","A person with perseverance."),
    row("鼻をかむ","はなをかむ","N4","exp|v5m",
        "xì mũi | hỉ mũi",
        "to blow one's nose",
        "2256050",
        "鼻をかんでください。","はなをかんでください。",
        "Xin hãy xì mũi.","Please blow your nose."),
    row("お盆","おぼん","N4","n",
        "lễ Obon | lễ cúng tổ tiên Phật giáo | khay",
        "Obon | Bon Festival | Buddhist festival for honouring the spirits of one's ancestors | tray",
        "1002690",
        "お盆に帰省します。","おぼんにきせいします。",
        "Tôi về quê dịp lễ Obon.","I return home for Obon."),
    row("一桁","ひとけた","N4","n",
        "một chữ số | hàng đơn vị | một con số",
        "one digit | one column | the \"ones\" column",
        "1162100",
        "一桁の数字。","ひとけたのすうじ。",
        "Số một chữ số.","A one-digit number."),
    row("倍数","ばいすう","N4","n",
        "bội số",
        "multiple",
        "1473290",
        "3の倍数。","さんのばいすう。",
        "Bội số của 3.","Multiples of 3."),
    row("偶数","ぐうすう","N4","n|adj-no",
        "số chẵn",
        "even number",
        "1246250",
        "2は偶数です。","2はぐうすうです。",
        "2 là số chẵn.","2 is an even number."),
    row("億","おく","N4","num",
        "một trăm triệu | 100.000.000",
        "hundred million | 100,000,000 | 10^8",
        "1182620",
        "10億円。","じゅうおくえん。",
        "1 tỷ yên.","1 billion yen."),
    row("兆","ちょう","N4","num|n",
        "nghìn tỷ | 1.000.000.000.000 | dấu hiệu | điềm báo",
        "10^12 | 1,000,000,000,000 | trillion | sign | omen | indication | portent",
        "1427430",
        "1兆円。","いっちょうえん。",
        "1 nghìn tỷ yên.","1 trillion yen."),
    row("公約数","こうやくすう","N4","n",
        "ước số chung | ước chung",
        "common factor | common divisor",
        "1274890",
        "最大公約数。","さいだいこうやくすう。",
        "Ước số chung lớn nhất.","Greatest common divisor."),
    row("切り抜ける","きりぬける","N4","v1|vt",
        "vượt qua | thoát khỏi | chiến thắng (khó khăn)",
        "to cut one's way through | to fight one's way through | to get over | to come through | to overcome (a difficulty)",
        "1384620",
        "危機を切り抜ける。","ききをきりぬける。",
        "Vượt qua khủng hoảng.","Overcome the crisis."),
    row("切り開く","きりひらく","N4","v5k|vt",
        "khai phá | mở đường | cắt mở | tạo ra (tương lai)",
        "to cut open | to clear (land) | to cut (a path, road, etc.) | to open | to carve out (a new career, future, etc.)",
        "1383920",
        "道を切り開く。","みちをきりひらく。",
        "Khai phá con đường.","Carve out a path."),
    row("切り離す","きりはなす","N4","v5s|vt",
        "cắt đứt | tách ra | tháo rời | ngắt kết nối",
        "to cut off (from) | to separate | to detach | to sever | to uncouple",
        "1384760",
        "電源を切り離す。","でんげんをきりはなす。",
        "Ngắt nguồn điện.","Disconnect the power source."),
    row("呼びかける","よびかける","N4","v1|vt",
        "kêu gọi | hô hào | kêu gọi mọi người | kêu gào | thúc giục",
        "to call out to | to hail | to address | to appeal (e.g. to the public) | to urge | to exhort | to advise",
        "1266280",
        "市民に呼びかける。","しみんによびかける。",
        "Kêu gọi người dân.","Appeal to citizens."),
    row("奇数","きすう","N4","n|adj-no",
        "số lẻ",
        "odd number",
        "1219410",
        "3は奇数です。","3はきすうです。",
        "3 là số lẻ.","3 is an odd number."),
    row("応急処置","おうきゅうしょち","N4","n",
        "sơ cứu | biện pháp khẩn cấp | xử lý tạm thời",
        "emergency measure | emergency procedures | first-aid treatment | stop-gap treatment | temporary repairs",
        "1973820",
        "応急処置をします。","おうきゅうしょちをします。",
        "Tôi thực hiện sơ cứu.","I administer first aid."),
    row("批判","ひはん","N4","n|vs|vt",
        "phê bình | chỉ trích | phán xét | góp ý",
        "criticism | judgement | judgment | comment",
        "1483420",
        "政策を批判する。","せいさくをひはんする。",
        "Chỉ trích chính sách.","Criticize the policy."),
    row("批評","ひひょう","N4","n|vs|vt",
        "bình luận | phê bình | đánh giá | nhận xét",
        "criticism | critique | review | commentary",
        "1483440",
        "映画を批評する。","えいがをひひょうする。",
        "Phê bình bộ phim.","Critique the film."),
    row("洞窟","どうくつ","N4","n",
        "hang động | hang | động đá",
        "cave | cavern | grotto",
        "1453860",
        "洞窟を探険する。","どうくつをたんけんする。",
        "Khám phá hang động.","Explore the cave."),
    row("言い渡す","いいわたす","N4","v5s|vt",
        "thông báo | tuyên bố | tuyên phán | ra lệnh",
        "to announce | to tell | to sentence | to order",
        "1264190",
        "判決を言い渡す。","はんけつをいいわたす。",
        "Tuyên phán quyết.","Pronounce judgment."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
