# -*- coding: utf-8 -*-
"""Build N1 ready wave 080 — advanced katakana loanwords (set 80)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-080.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("アーカイブ","アーカイブ","n","kho lưu trữ | bản lưu | tệp lưu trữ","an archive","1013380"),
    ("アサイン","アサイン","n|vs|vt","sự phân công | giao nhiệm vụ | chỉ định","assignment","1015720"),
    ("アジェンダ","アジェンダ","n","chương trình nghị sự | lịch trình | nội dung bàn thảo","an agenda","1985750"),
    ("アセスメント","アセスメント","n","sự đánh giá | thẩm định | định giá","assessment","1016260"),
    ("アテンド","アテンド","n|vs|vt","việc tháp tùng | chăm sóc | tiếp đón | phục vụ","attending to someone | taking care of","2019900"),
    ("アドバンテージ","アドバンテージ","n","lợi thế | ưu thế | điểm có lợi | quyền lợi (thể thao)","advantage","1017130"),
    ("アナログ","アナログ","adj-na|adj-no|n","tương tự (analog) | kiểu cũ không số hóa | analog","analog","1017480"),
    ("アノニマス","アノニマス","adj-f","ẩn danh | nặc danh | giấu tên","anonymous","1017670"),
    ("アライアンス","アライアンス","n","liên minh | sự liên kết | đồng minh","an alliance","1018970"),
    ("アンサンブル","アンサンブル","n","sự hòa hợp | hợp tấu | bộ trang phục đồng bộ | sự ăn ý","ensemble | harmony","1019990"),
    ("アンチテーゼ","アンチテーゼ","n","phản đề | luận điểm đối lập | sự đối nghịch","antithesis","1020280"),
    ("イニシアティブ","イニシアティブ","n","thế chủ động | sáng kiến | quyền chủ động | vai trò dẫn dắt","initiative","1021520"),
    ("イラスト","イラスト","n","tranh minh họa | hình vẽ | hình minh họa | tranh vẽ","an illustration | a picture","1021940"),
    ("インサイト","インサイト","n","sự thấu hiểu | cái nhìn sâu sắc | tuệ giác | sự nhận thức","insight","2437710"),
    ("インパクト","インパクト","n","tác động | ấn tượng mạnh | sự ảnh hưởng | cú va chạm","impact | a strong impression","1024010"),
    ("ウェイト","ウェイト","n","trọng lượng | cân nặng | tầm quan trọng | sự nhấn mạnh | tạ","weight | importance | emphasis","1025680"),
    ("エキスパート","エキスパート","n","chuyên gia | người thành thạo | bậc thầy","an expert","1027790"),
    ("エクスタシー","エクスタシー","n","sự ngất ngây | trạng thái xuất thần | cảm giác cực lạc | thuốc lắc","ecstasy","1027980"),
    ("エッセイ","エッセイ","n","bài tiểu luận | tản văn | bài luận | tùy bút","an essay","1029100"),
    ("オブザーバー","オブザーバー","n","quan sát viên | người dự thính | người theo dõi","an observer","1034880"),
    ("オプション","オプション","n","tùy chọn | lựa chọn | phần tùy chọn thêm | mục riêng","an option","1035040"),
    ("オペレーション","オペレーション","n","hoạt động | quá trình vận hành | ca phẫu thuật | thao tác","operation","1035260"),
    ("オマージュ","オマージュ","n","sự tri ân | lời tôn vinh | tác phẩm tưởng nhớ","homage","2084090"),
    ("ガジェット","ガジェット","n","thiết bị nhỏ tiện ích | đồ công nghệ | tiện ích nhỏ","a gadget","1040040"),
    ("ガバナンス","ガバナンス","n","quản trị | sự điều hành | quản trị doanh nghiệp","governance","2025780"),
    ("キャパ","キャパ","n","sức chứa | khả năng | dung lượng | giới hạn","capacity","2038340"),
    ("ギミック","ギミック","n","mánh lới thu hút | chiêu trò | cơ chế đặc biệt | thủ thuật","a gimmick","1043000"),
    ("ギャップ","ギャップ","n","khoảng cách | sự chênh lệch | sự khác biệt | độ vênh","a gap | a disparity","1043060"),
    ("クエスト","クエスト","n","nhiệm vụ (game) | cuộc tìm kiếm | hành trình truy tìm","a quest","2731860"),
    ("クライアント","クライアント","n","khách hàng | thân chủ | bên thuê dịch vụ","a client","1043850"),
    ("クリエイティブ","クリエイティブ","adj-na","sáng tạo | mang tính sáng tạo | đầy ý tưởng","creative","1044690"),
    ("グレード","グレード","n","cấp độ | hạng | thứ bậc | chất lượng","grade","1047530"),
    ("ケア","ケア","n|vs|vt","sự chăm sóc | sự quan tâm | chăm nom | điều dưỡng","care | attention | nursing","1048030"),
    ("コアラ","コアラ","n","gấu koala | koala","koala","1049830"),
    ("コーディネート","コーディネート","n|vs|vt","sự phối hợp | phối đồ | điều phối | sự kết hợp hài hòa","coordination | matching","1048970"),
    ("コミット","コミット","n|vs|vi","sự cam kết | sự dấn thân | sự tham gia | gắn kết trách nhiệm","commitment | involvement","1050910"),
    ("コモンセンス","コモンセンス","n","lẽ thường | nhận thức chung | hiểu biết phổ thông","common sense","1051270"),
    ("コロニー","コロニー","n","thuộc địa | khu định cư | quần thể (sinh vật)","a colony","1051710"),
    ("サスペンス","サスペンス","n","sự hồi hộp | tình tiết gay cấn | yếu tố giật gân | sự nín thở chờ đợi","suspense","1056590"),
    ("シェア","シェア","n|vs|vt","sự chia sẻ | thị phần | chia sẻ (mạng xã hội) | dùng chung","sharing | market share","1059930"),
    ("シナジー","シナジー","n","sức mạnh cộng hưởng | hiệu ứng cộng hưởng | sự hợp lực","synergy","1060800"),
    ("シナリオ","シナリオ","n","kịch bản | tình huống giả định | viễn cảnh | cốt truyện","a scenario | a screenplay","1060830"),
    ("シビア","シビア","adj-na","khắc nghiệt | nghiêm khắc | gay gắt | khó khăn","severe | strict | tough","1061020"),
    ("ジェネレーション","ジェネレーション","n","thế hệ | thời thế hệ","generation","1064360"),
    ("ジャーゴン","ジャーゴン","n","biệt ngữ | tiếng lóng chuyên ngành | từ ngữ chuyên môn khó hiểu","jargon","1064950"),
    ("ジャンル","ジャンル","n","thể loại | dòng | loại hình | phân loại","genre | category","1065920"),
    ("スキーム","スキーム","n","kế hoạch | sơ đồ | cơ chế | phương án","scheme","1067820"),
    ("スキル","スキル","n","kỹ năng | tay nghề | năng lực chuyên môn","skill","1068060"),
    ("スケール","スケール","n","quy mô | tỷ lệ | thang đo | tầm cỡ | thước","scale","1068830"),
    ("スタンス","スタンス","n","lập trường | quan điểm | tư thế | thái độ","stance | standpoint","1069850"),
    ("スタンダード","スタンダード","adj-na|n","tiêu chuẩn | chuẩn mực | mức chuẩn","standard","1069870"),
    ("スポンサー","スポンサー","n","nhà tài trợ | người bảo trợ | đơn vị tài trợ","a sponsor","1073510"),
    ("スマート","スマート","adj-na","thanh mảnh | bảnh bao | thông minh | khôn khéo | gọn gàng","stylish | slim | clever","1073570"),
    ("セクター","セクター","n","khu vực | lĩnh vực | ngành | rẻ quạt (đĩa)","sector","1074500"),
    ("セレモニー","セレモニー","n","nghi lễ | buổi lễ | nghi thức","a ceremony","1074930"),
    ("ゾーン","ゾーン","n","vùng | khu vực | địa hạt | phạm vi","a zone","1075690"),
    ("ターゲット","ターゲット","n","mục tiêu | đối tượng nhắm tới | đích nhắm","a target","1075720"),
    ("タイト","タイト","adj-na|n","chật | bó sát | eo hẹp | căng (lịch) | sát sao","tight","1075880"),
    ("タクティクス","タクティクス","n","chiến thuật | sách lược tác chiến | mưu kế","tactics","1076230"),
    ("ダウンサイジング","ダウンサイジング","n|vs","sự thu nhỏ quy mô | tinh giản | cắt giảm nhân sự | thu gọn","downsizing","1076990"),
    ("ダメージ","ダメージ","n","thiệt hại | tổn thương | hư hại | sát thương","damage","1077160"),
    ("チャネル","チャネル","n","kênh | đường truyền | kênh phân phối","a channel","1077960"),
    ("チョイス","チョイス","n|vs|vt","sự lựa chọn | sự chọn lựa | lựa chọn","choice | selection","2192410"),
    ("ディテール","ディテール","n","chi tiết | tiểu tiết | phần chi tiết","detail","1082090"),
    ("ディベート","ディベート","n","tranh luận | hùng biện | thảo luận đối kháng","debate","1082330"),
    ("テーゼ","テーゼ","n","luận đề | luận điểm | mệnh đề","thesis | statement","1078600"),
    ("テリトリー","テリトリー","n","lãnh thổ | địa bàn | phạm vi hoạt động | lãnh địa","territory","1080200"),
    ("デフォルト","デフォルト","n|adj-no","mặc định | thiết lập mặc định | vỡ nợ (tài chính)","default","1083740"),
    ("デリバリー","デリバリー","n","sự giao hàng | dịch vụ giao tận nơi | chuyển phát","delivery","1084350"),
    ("トーン","トーン","n","tông màu | âm điệu | sắc thái | giọng điệu","tone","1084780"),
    ("ドラマチック","ドラマチック","adj-na","kịch tính | đầy kịch tính | gay cấn | giàu cảm xúc","dramatic","1088860"),
    ("ドリル","ドリル","n|vs","mũi khoan | máy khoan | bài luyện tập | sự rèn luyện lặp lại","a drill","1089070"),
    ("ナビゲーション","ナビゲーション","n|vs","sự dẫn đường | định vị chỉ đường | điều hướng","navigation","2207130"),
    ("ニッチ","ニッチ","adj-na|n","ngách | thị trường ngách | lĩnh vực hẹp | hốc tường","niche","2105290"),
    ("ノウハウ","ノウハウ","n","bí quyết | kinh nghiệm thực tiễn | kỹ thuật chuyên môn | cách làm","know-how | expertise","1093820"),
    ("ノミネート","ノミネート","n|vs|vt","sự đề cử | sự được đề cử | bình chọn ứng viên","nomination","1094100"),
    ("バーチャル","バーチャル","adj-na|adj-f","ảo | thực tế ảo | mô phỏng | giả lập","virtual","1097190"),
    ("バッファ","バッファ","n","vùng đệm | bộ đệm | khoảng dự phòng","a buffer","1099270"),
    ("パートナーシップ","パートナーシップ","n","quan hệ đối tác | sự hợp tác | mối quan hệ cộng sự","partnership","1100860"),
    ("パフォーマンス","パフォーマンス","n","màn trình diễn | hiệu suất | sự biểu diễn | hành động phô trương","performance","1102220"),
    ("パラダイム","パラダイム","n","hệ hình | khuôn mẫu tư duy | mô thức | hệ chuẩn","paradigm","1102510"),
    ("ヒューマニズム","ヒューマニズム","n","chủ nghĩa nhân văn | chủ nghĩa nhân đạo | tinh thần nhân bản","humanism","1104030"),
    ("ピーク","ピーク","n","đỉnh điểm | cao điểm | đỉnh cao | điểm cực đại","peak","1106180"),
    ("ファシリテーター","ファシリテーター","n","người điều phối | người dẫn dắt thảo luận | người hỗ trợ tiến trình","a facilitator","2826653"),
    ("フェーズ","フェーズ","n","giai đoạn | pha | thời kỳ | chặng","phase","1109520"),
    ("フォロー","フォロー","n|vs|vt|vi","sự theo dõi | hỗ trợ | giúp đỡ | theo dõi (mạng xã hội) | bù đắp","follow | follow-up | support","1110800"),
    ("プレゼンス","プレゼンス","n","sự hiện diện | tầm ảnh hưởng | vị thế hiện hữu","presence","2025850"),
    ("ベンチマーク","ベンチマーク","n","tiêu chuẩn so sánh | mốc chuẩn | điểm đối chiếu | chuẩn đánh giá","benchmark","1120310"),
    ("ポジティブ","ポジティブ","adj-na|n","tích cực | lạc quan | dương tính | cực dương","positive","1125070"),
    ("マインド","マインド","n","tâm trí | tư duy | tâm thế | tinh thần","mind | mindset","1127120"),
    ("マニフェスト","マニフェスト","n","tuyên ngôn | cương lĩnh tranh cử | bản tuyên bố chính sách","manifesto","1128860"),
    ("メカニズム","メカニズム","n","cơ chế | nguyên lý vận hành | bộ máy | guồng máy","mechanism","1132960"),
    ("メソッド","メソッド","n","phương pháp | cách thức | phương thức (lập trình)","method","1133210"),
    ("モジュール","モジュール","n","mô-đun | khối chức năng | bộ phận lắp ghép","module","1134840"),
    ("レトリック","レトリック","n","thuật hùng biện | nghệ thuật tu từ | lối nói hoa mỹ","rhetoric","1145640"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
