# -*- coding: utf-8 -*-
"""Build N2 ready wave 053 — school types, terms, staff, facilities, exams, school life."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-053.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("幼稚園","ようちえん","n","trường mẫu giáo | nhà trẻ (3 tuổi đến tiểu học)","kindergarten | preschool","1545260"),
    ("保育園","ほいくえん","n","nhà trẻ | trường mầm non","nursery school | day care center","1513300"),
    ("小学校","しょうがっこう","n","trường tiểu học | trường cấp một","primary school | elementary school","1347870"),
    ("中学校","ちゅうがっこう","n","trường trung học cơ sở | cấp hai","junior high school | middle school","1423650"),
    ("高等学校","こうとうがっこう","n","trường trung học phổ thông | cấp ba","senior high school | high school","1283860"),
    ("専門学校","せんもんがっこう","n","trường trung cấp nghề | trường chuyên môn","vocational school | technical school","1703820"),
    ("短期大学","たんきだいがく","n","trường cao đẳng | đại học hệ ngắn hạn","junior college","1418650"),
    ("私立","しりつ","n|adj-no","tư thục | dân lập | tư nhân","private (establishment)","1311420"),
    ("公立","こうりつ","n","công lập","public (institution)","1275000"),
    ("国立","こくりつ","adj-no|n","quốc lập | nhà nước","national","1287180"),
    ("共学","きょうがく","n|vs|vi","trường nam nữ chung | giáo dục hỗn hợp","coeducation | mixed-sex education","1234350"),
    ("男子校","だんしこう","n","trường nam sinh","boys' school","1942230"),
    ("女子校","じょしこう","n","trường nữ sinh","girls' school","1938300"),
    ("全寮制","ぜんりょうせい","n|adj-no","chế độ nội trú toàn bộ | trường nội trú","residential system | boarding system","1824230"),
    ("寄宿舎","きしゅくしゃ","n","ký túc xá | nhà nội trú","boarding house | dormitory","1219740"),
    ("学区","がっく","n","khu vực tuyển sinh | địa bàn trường học","school district","1206710"),
    ("校区","こうく","n","khu vực trường | địa bàn tuyển sinh","school district","2719860"),
    ("新学期","しんがっき","n","học kỳ mới","new school term","1361560"),
    ("始業","しぎょう","n|vs|vi","bắt đầu làm việc | khai giảng | bắt đầu (ca)","start of work | commencement","1307560"),
    ("終業","しゅうぎょう","n|vs|vi","hết giờ làm | bế giảng | kết thúc kỳ học","end of the work day | end of the school term","1332790"),
    ("修了","しゅうりょう","n|vs|vt|vi","hoàn thành khóa học | tốt nghiệp khóa","completion (of a course)","1332450"),
    ("進級","しんきゅう","n|vs|vi","lên lớp | thăng cấp","promotion (school, military)","1366030"),
    ("落第","らくだい","n|vs|vi","thi rớt | ở lại lớp | không đạt | trượt","failure (in an exam) | not making the grade","1548810"),
    ("飛び級","とびきゅう","n|vs|vi","học vượt lớp | nhảy lớp","skipping a grade","1461440"),
    ("編入学","へんにゅうがく","n|vs","chuyển tiếp vào học | nhập học chuyển trường","transfer admission | advanced-standing admission","2544540"),
    ("転校","てんこう","n|vs|vi","chuyển trường","changing schools","1441140"),
    ("教頭","きょうとう","n","phó hiệu trưởng | hiệu phó","deputy head teacher | vice principal","1630240"),
    ("担任","たんにん","n|vs|vt","phụ trách lớp | giáo viên chủ nhiệm","being in charge of (a class) | homeroom teacher","1418200"),
    ("教官","きょうかん","n","giảng viên | giáo quan | huấn luyện viên","teacher | instructor | professor","1237050"),
    ("助手","じょしゅ","n","trợ lý | trợ giảng | phụ tá nghiên cứu","assistant | helper | research assistant","1344650"),
    ("非常勤","ひじょうきん","n","làm bán thời gian | làm không thường xuyên","part-time work","1648540"),
    ("常勤","じょうきん","n|vs|vi","làm toàn thời gian | làm chính thức","full-time employment","1798220"),
    ("教壇","きょうだん","n","bục giảng","(teacher's) platform | podium","1237270"),
    ("教卓","きょうたく","n","bàn giáo viên | bục giảng bài","teacher's desk | teacher's lectern","1761620"),
    ("職員室","しょくいんしつ","n","phòng giáo viên | phòng nhân viên","staff room","1357500"),
    ("保健室","ほけんしつ","n","phòng y tế (trường, công sở)","infirmary | nurse's office","1946650"),
    ("図書室","としょしつ","n","phòng đọc sách | thư viện nhỏ","library (single-room)","1370440"),
    ("校門","こうもん","n","cổng trường","school gate","1279620"),
    ("校舎","こうしゃ","n","tòa nhà trường học | dãy lớp học","school building | schoolhouse","1279540"),
    ("講堂","こうどう","n","hội trường | giảng đường","auditorium | lecture hall","1282340"),
    ("時間割","じかんわり","n","thời khóa biểu | lịch học","timetable | schedule","1315960"),
    ("補講","ほこう","n|vs|vt|vi","giảng bù | tiết học bổ sung | dạy thêm","supplementary lecture | extra classes","1690300"),
    ("補習","ほしゅう","n|vs|vt","học bổ trợ | học phụ đạo","supplementary lessons","1627510"),
    ("自習","じしゅう","n|vs|vt|vi","tự học | học tự do (khi vắng giáo viên)","self-study | teaching oneself","1317900"),
    ("板書","ばんしょ","n|vs|vt","viết bảng | việc ghi bảng","writing on a blackboard","1732720"),
    ("丸暗記","まるあんき","n|vs|vt","học thuộc lòng | học vẹt | nhồi nhét máy móc","rote memorization | rote learning","1604220"),
    ("中間試験","ちゅうかんしけん","n","thi giữa kỳ","midterm examination","1942470"),
    ("期末試験","きまつしけん","n","thi cuối kỳ","final exam | term-end examination","1220630"),
    ("模擬試験","もぎしけん","n","thi thử | thi mô phỏng","mock exam | practice test","1533640"),
    ("追試","ついし","n|vs|vt","thi lại | thi bổ sung | kiểm chứng lại (thí nghiệm)","makeup exam | replication (of an experiment)","1854740"),
    ("再試験","さいしけん","n","thi lại | kiểm tra lại","reexamination | resit","1292790"),
    ("小テスト","しょうテスト","n","bài kiểm tra nhỏ | kiểm tra ngắn","quiz | short test","2082190"),
    ("抜き打ち","ぬきうち","n|adj-no","bất ngờ không báo trước | đột xuất | tuốt kiếm chém liền","doing without prior notice | sudden","1478170"),
    ("採点","さいてん","n|vs|vt","chấm điểm | cho điểm","marking | grading | scoring","1294850"),
    ("赤点","あかてん","n","điểm liệt | điểm rớt","failing mark (e.g. in exam)","2153820"),
    ("評定","ひょうてい","n|vs|vt","đánh giá | xếp loại | xếp hạng | bình điểm","assessment | rating | grade","1490060"),
    ("通知表","つうちひょう","n","phiếu điểm | sổ liên lạc | bảng thông báo kết quả","report card","1687200"),
    ("内申","ないしん","n|vs|vt","báo cáo không chính thức | hồ sơ đánh giá nội bộ","unofficial report | confidential report","1458560"),
    ("偏差値","へんさち","n","điểm偏差 | điểm chuẩn hóa (đánh giá học lực)","deviation value | standard score","1611480"),
    ("留学","りゅうがく","n|vs|vi","du học | đi học ở nơi khác","studying abroad","1552740"),
    ("交換留学","こうかんりゅうがく","n","trao đổi du học sinh | du học trao đổi","(student) exchange | study abroad","2070840"),
    ("奨学生","しょうがくせい","n","học sinh học bổng | sinh viên được cấp học bổng","scholarship student","1347540"),
    ("特待生","とくたいせい","n","học sinh được ưu đãi | học sinh học bổng đặc biệt","scholarship student","1455140"),
    ("聴講生","ちょうこうせい","n","sinh viên dự thính","auditor | auditing student","1800600"),
    ("卒業生","そつぎょうせい","n","cựu học sinh | người tốt nghiệp","graduate | alumnus","1405940"),
    ("在校生","ざいこうせい","n","học sinh đang theo học | học sinh hiện tại","current student | enrolled student","1296490"),
    ("同窓","どうそう","n|adj-no","cùng trường | bạn học cùng trường | đồng môn","being a graduate of the same school","1452990"),
    ("同窓会","どうそうかい","n","hội cựu học sinh | buổi họp lớp","alumni association | class reunion","1453000"),
    ("部活","ぶかつ","n","hoạt động câu lạc bộ | hoạt động ngoại khóa","club activities | extracurricular activities","1622100"),
    ("部活動","ぶかつどう","n","hoạt động câu lạc bộ | sinh hoạt ngoại khóa","club activities","2532360"),
    ("文化系","ぶんかけい","adj-f","thuộc nhóm văn hóa | hệ văn hóa (CLB)","cultural","2652300"),
    ("運動部","うんどうぶ","n","câu lạc bộ thể thao | ban thể thao","sports club (at school)","2221900"),
    ("帰宅部","きたくぶ","n","học sinh không tham gia CLB nào | hội về thẳng nhà","pupils not in any school club | go-home club","2215930"),
    ("顧問","こもん","n","cố vấn | tư vấn | giáo viên phụ trách CLB","adviser | consultant | club supervisor","1267880"),
    ("先輩後輩","せんぱいこうはい","exp","tiền bối hậu bối | quan hệ trên dưới theo thâm niên","one's seniors and juniors | seniority hierarchy","2105750"),
    ("新入生","しんにゅうせい","n","học sinh mới | sinh viên năm nhất | tân sinh viên","new student | freshman","1362270"),
    ("新歓","しんかん","n","chào đón thành viên mới | đón tân sinh viên","welcoming new students or members","2033600"),
    ("学園祭","がくえんさい","n","lễ hội trường | hội trường","school festival | campus festival","1206580"),
    ("修学旅行","しゅうがくりょこう","n","chuyến tham quan học tập | dã ngoại của trường","excursion | school trip","1331960"),
    ("林間学校","りんかんがっこう","n","trại học trong rừng | trường dã ngoại","school camp | outdoors school","1838550"),
    ("臨海学校","りんかいがっこう","n","trại học ven biển","seaside school","1852950"),
    ("吹奏楽","すいそうがく","n","nhạc kèn | nhạc hơi | hòa tấu kèn","wind music | wind instrument music","1370800"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
