# -*- coding: utf-8 -*-
"""Build N2 ready wave 056 — 〜的 adjectives (style, scope, time, attitude) + 4-char idioms."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-056.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("詩的","してき","adj-na","đầy chất thơ | nên thơ | thi vị","poetic","1312230"),
    ("比喩的","ひゆてき","adj-na","mang tính ẩn dụ | ví von | hình tượng","figurative","1731770"),
    ("象徴的","しょうちょうてき","adj-na","mang tính biểu tượng | tượng trưng","symbolic","1794680"),
    ("神秘的","しんぴてき","adj-na","huyền bí | thần bí | bí ẩn","mysterious | mystical","1364850"),
    ("幻想的","げんそうてき","adj-na","huyền ảo | mộng mơ | kỳ ảo | như cổ tích","fantastic | magical | wondrous","2085790"),
    ("牧歌的","ぼっかてき","adj-na","đồng quê | điền viên | thanh bình","pastoral | idyllic","1615180"),
    ("官能的","かんのうてき","adj-na","gợi cảm | khêu gợi | nhục cảm","sensual | voluptuous | sexy","1211770"),
    ("享楽的","きょうらくてき","adj-na","hưởng lạc | ham vui | tìm khoái lạc","pleasure-seeking","1233260"),
    ("退廃的","たいはいてき","adj-na","sa đọa | đồi trụy | suy đồi","degenerate | decadent | corrupt","1610180"),
    ("厭世的","えんせいてき","adj-na","yếm thế | chán đời | bi quan","sick of life | world-weary | pessimistic","1175540"),
    ("悲劇的","ひげきてき","adj-na","bi kịch | bi thảm","tragic","1689110"),
    ("喜劇的","きげきてき","adj-na","hài hước | khôi hài","comical | farcical","2835738"),
    ("普遍的","ふへんてき","adj-na","phổ quát | phổ biến | hiện diện khắp nơi","universal | omnipresent | ubiquitous","1615290"),
    ("個別的","こべつてき","adj-na","riêng lẻ | cá biệt | rời rạc | riêng biệt","individual | particular | discrete","2632110"),
    ("包括的","ほうかつてき","adj-na","toàn diện | bao quát | bao trùm","comprehensive | inclusive","1515460"),
    ("根源的","こんげんてき","adj-na","căn nguyên | nền tảng | gốc rễ | nguyên thủy","primordial | fundamental | basic","2758430"),
    ("副次的","ふくじてき","adj-na","thứ yếu | phụ | thứ cấp","secondary","1500450"),
    ("二次的","にじてき","adj-na","thứ cấp | thứ yếu | phái sinh","secondary","1461910"),
    ("派生的","はせいてき","adj-na","phái sinh | phụ thuộc | thứ cấp","derivative | secondary","1471170"),
    ("恒久的","こうきゅうてき","adj-na","vĩnh cửu | lâu dài | bền vững","permanent | perpetual | lasting","1760250"),
    ("暫定的","ざんていてき","adj-na","tạm thời | lâm thời | tạm định","provisional | temporary | interim","1815040"),
    ("恒常的","こうじょうてき","adj-na","thường xuyên | bất biến | kinh niên | liên tục","constant | invariable | chronic","1760310"),
    ("慢性的","まんせいてき","adj-na","mạn tính | kinh niên","chronic","1526650"),
    ("突発的","とっぱつてき","adj-na","đột phát | bất ngờ | không lường trước","sudden | unexpected | unforeseen","1457140"),
    ("散発的","さんぱつてき","adj-na","lẻ tẻ | rời rạc | thỉnh thoảng","sporadic","1616060"),
    ("継続的","けいぞくてき","adj-na","liên tục | liền mạch","continuous","1769740"),
    ("連続的","れんぞくてき","adj-na","liên tiếp | liên tục | nối tiếp","consecutive | continuous | successive","2638800"),
    ("断続的","だんぞくてき","adj-na","ngắt quãng | gián đoạn | lúc có lúc không","intermittent","1704990"),
    ("周期的","しゅうきてき","adj-na","theo chu kỳ | tuần hoàn | định kỳ","periodic | cyclic","2123720"),
    ("規則的","きそくてき","adj-na","có quy luật | đều đặn | có hệ thống","systematic | regular | routine","1223050"),
    ("不規則","ふきそく","adj-na|n","không đều | bất quy tắc | lộn xộn","irregular | unsystematic | disorderly","1491840"),
    ("不定期","ふていき","adj-na|adj-no|n","không định kỳ | bất thường | không cố định kỳ hạn","irregular (schedule) | indeterminate","1493900"),
    ("定期的","ていきてき","adj-na","định kỳ | đều đặn | thường lệ","periodic | regular | routine","1777250"),
    ("日常的","にちじょうてき","adj-na","thường ngày | hằng ngày | bình thường","mundane | routine | everyday","2726220"),
    ("習慣的","しゅうかんてき","adj-na","theo thói quen | theo tập quán","habitual | customary","2765360"),
    ("慣習的","かんしゅうてき","adj-na","theo lệ | theo tập quán | thông lệ","customary | conventional | traditional","2831633"),
    ("伝統的","でんとうてき","adj-na","truyền thống | mang tính truyền thống","traditional | customary | conventional","1442270"),
    ("古典的","こてんてき","adj-na","cổ điển | kinh điển","classical | classic","1265900"),
    ("近代的","きんだいてき","adj-na","cận đại | hiện đại","modern","1242460"),
    ("現代的","げんだいてき","adj-na","hiện đại | tân thời","modern | modernistic","1715970"),
    ("前衛的","ぜんえいてき","adj-na","tiên phong | tiền vệ | avant-garde","avant-garde","2119500"),
    ("革命的","かくめいてき","adj-na","mang tính cách mạng | đột phá","revolutionary","1206520"),
    ("発展的","はってんてき","adj-na","mang tính phát triển | tiến triển","developing | developmental","2726270"),
    ("否定的","ひていてき","adj-na","tiêu cực | phủ định | bác bỏ","negative | contradictory","1483020"),
    ("肯定的","こうていてき","adj-na","khẳng định | tán thành | tích cực","affirmative","1281200"),
    ("好意的","こういてき","adj-na","thiện cảm | có thiện ý | ủng hộ","favorable | favourable","1835970"),
    ("批判的","ひはんてき","adj-na","mang tính phê phán | chỉ trích | soi xét","critical | judgmental | censorious","1483430"),
    ("懐疑的","かいぎてき","adj-na","hoài nghi | đa nghi | bán tín bán nghi","skeptical | incredulous","2862608"),
    ("盲目的","もうもくてき","adj-na","mù quáng | nhắm mắt (tin theo) | liều lĩnh","blind (devotion) | reckless","1534350"),
    ("偽善的","ぎぜんてき","adj-na","giả nhân giả nghĩa | đạo đức giả","hypocritical","2859136"),
    ("挑発的","ちょうはつてき","adj-na","khiêu khích | kích động | gợi dục | khêu gợi","provocative | inflammatory | suggestive","1428270"),
    ("差別的","さべつてき","adj-na","phân biệt đối xử | kỳ thị","discriminatory","2803070"),
    ("官僚的","かんりょうてき","adj-na","quan liêu | hành chính cứng nhắc","bureaucratic","2725870"),
    ("機械的","きかいてき","adj-na","máy móc | rập khuôn | một cách máy móc","mechanical","1780150"),
    ("事務的","じむてき","adj-na","khô khan | thực dụng | thuần công việc | lạnh lùng","administrative | businesslike | impersonal","1314450"),
    ("形式的","けいしきてき","adj-na","hình thức | mang tính nghi thức | qua loa hình thức","formal","1250320"),
    ("便宜的","べんぎてき","adj-na","tiện lợi | tạm bợ | đối phó | cho qua","convenient | expedient | makeshift","2523540"),
    ("即興的","そっきょうてき","adj-na","ứng tác | ngẫu hứng | tùy hứng | tại chỗ","improvised | impromptu | off-the-cuff","2726110"),
    ("衝動買い","しょうどうがい","n|vs|vt","mua sắm bốc đồng | mua theo cảm hứng","impulse buying | impulse purchase","1351550"),
    ("無計画","むけいかく","adj-na|n","thiếu kế hoạch | tùy tiện | không tính toán","lacking a plan | haphazard","1672650"),
    ("場当たり","ばあたり","n|adj-na|adj-no","tùy cơ ứng biến | tạm bợ | làm cho qua | mua vui","playing to the gallery | ad hoc | haphazard","1774020"),
    ("出たとこ勝負","でたとこしょうぶ","exp|n","phó mặc may rủi | tùy cơ ứng biến | được chăng hay chớ","leaving a matter to chance","1338190"),
    ("行き当たりばったり","いきあたりばったり","adj-no","tùy hứng | bạ đâu hay đó | không kế hoạch | hú họa","random | haphazard | hit-or-miss | unplanned","2035340"),
    ("臨機応変","りんきおうへん","n|adj-na|adj-no","tùy cơ ứng biến | linh hoạt theo tình huống","adapting to the moment | playing by ear","1555580"),
    ("当意即妙","とういそくみょう","n|adj-na|adj-no","ứng đối nhanh nhạy | đối đáp khéo léo tức thì","ready wit | repartee","1448950"),
    ("変幻自在","へんげんじざい","adj-na|adj-no|n","biến hóa khôn lường | thiên biến vạn hóa | thay đổi tùy ý","protean | shape-shifting | ever-changing","1511020"),
    ("自由自在","じゆうじざい","adj-na","tự do tự tại | thoải mái | làm chủ hoàn toàn","free | unrestricted | with complete mastery","1318770"),
    ("縦横無尽","じゅうおうむじん","adj-na|n","tung hoành | thỏa sức | dọc ngang tùy ý","freely | as one pleases","1335650"),
    ("天衣無縫","てんいむほう","adj-na|n","tự nhiên hoàn mỹ | thiên y vô phùng | không tì vết","perfect beauty with no trace of artifice | flawless","1438330"),
    ("自然体","しぜんたい","n","tư thế tự nhiên (judo) | phong thái thoải mái | điềm tĩnh","natural posture | relaxed manner","2153610"),
    ("余裕綽々","よゆうしゃくしゃく","adj-na|adj-no|adj-t|adv-to","ung dung | thư thái | điềm nhiên dư dả","calm and collected | with composure","1544600"),
    ("冷静沈着","れいせいちんちゃく","n|adj-na","bình tĩnh điềm đạm | điềm tĩnh sáng suốt","calm, cool, and collected","2055130"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
