# -*- coding: utf-8 -*-
"""Build N3 ready wave 051 — 67 freshly-curated N3 compound verbs + motion/physics nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-051.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("取り入れる","とりいれる","v1|vt","đưa vào | tiếp thu | thu hoạch | áp dụng","to take in | to adopt | to introduce | to harvest","1326880"),
    ("取り戻す","とりもどす","v5s|vt","lấy lại | giành lại | khôi phục","to take back | to regain | to recover | to restore","1326940"),
    ("取り付ける","とりつける","v1|vt","lắp đặt | gắn vào | có được (sự đồng ý)","to install | to fit | to set up | to obtain (agreement)","1326910"),
    ("差し出す","さしだす","v5s|vt","chìa ra | đưa ra | nộp | gửi đi","to hold out | to present | to submit | to send","1291230"),
    ("差し引く","さしひく","v5k|vt|vi","khấu trừ | trừ đi | bù trừ","to deduct | to take away | to discount","1291100"),
    ("打ち切る","うちきる","v5r|vt","ngừng | đình chỉ | cắt bỏ | kết thúc","to stop | to abort | to discontinue | to close","1408720"),
    ("申し上げる","もうしあげる","v1|vt","kính thưa | xin nói | bày tỏ (khiêm nhường)","to say (humbly) | to state | to express | to offer","1362950"),
    ("見下ろす","みおろす","v5s|vt","nhìn xuống | bao quát | coi thường","to overlook | to command a view of | to look down on","1259370"),
    ("見上げる","みあげる","v1|vt","ngước nhìn | ngẩng nhìn | kính nể","to look up at | to look up to | to admire","1259740"),
    ("思い浮かべる","おもいうかべる","v1|vt","hình dung | mường tượng | nhớ lại","to recall | to imagine | to picture in one's mind","1658200"),
    ("立ち止まる","たちどまる","v5r|vi","dừng bước | đứng lại | khựng lại","to stop (in one's tracks) | to halt | to stand still","1551350"),
    ("立ち寄る","たちよる","v5r|vi","ghé qua | tạt vào | tạt qua","to drop in (at) | to drop by | to stop by","1551300"),
    ("駆けつける","かけつける","v1|vi","chạy vội đến | hối hả tới","to run to | to come running | to rush (someplace)","1590110"),
    ("突っ込む","つっこむ","v5m|vt|vi","đâm vào | nhồi nhét | lao vào | đào sâu | bắt bẻ","to thrust into | to plunge into | to delve into | to retort","1456940"),
    ("巻き込む","まきこむ","v5m|vt","cuốn vào | lôi kéo | dính líu","to roll up | to involve | to drag into","1211150"),
    ("追いつく","おいつく","v5k|vi","đuổi kịp | bắt kịp | theo kịp","to catch up (with) | to reach | to make up for","1588810"),
    ("抜け出す","ぬけだす","v5s|vi","lẻn ra | thoát ra | vượt lên","to slip out | to break free | to get ahead","1478220"),
    ("組み込む","くみこむ","v5m|vt","tích hợp | lồng ghép | cài vào","to insert | to incorporate | to embed | to install","1397510"),
    ("持ち帰る","もちかえる","v5r|vt","mang về | đem về | mua mang đi","to take home | to bring back home | to take out (food)","1658430"),
    ("受け継ぐ","うけつぐ","v5g|vt","kế thừa | thừa kế | tiếp nối","to inherit | to succeed | to take over","1329600"),
    ("読み取る","よみとる","v5r|vt","đọc hiểu | nắm bắt | quét (mã)","to read and understand | to sense | to scan (a code)","1456210"),
    ("出迎える","でむかえる","v1|vt","ra đón | nghênh đón","to meet | to greet","1338720"),
    ("出来上がる","できあがる","v5r|vi","hoàn thành | làm xong | sẵn sàng","to be completed | to be finished | to be ready","1340610"),
    ("受かる","うかる","v5r|vi","thi đỗ | đậu (kỳ thi)","to pass (an examination)","1329580"),
    ("近寄る","ちかよる","v5r|vi","lại gần | tiến đến gần","to approach | to draw near","1242230"),
    ("近づく","ちかづく","v5k|vi","đến gần | tới gần | làm quen","to approach | to draw near | to get acquainted with","1242170"),
    ("遠ざかる","とおざかる","v5r|vi","xa dần | nhạt dần | xa lánh","to go away | to fade away | to be estranged","1177830"),
    ("すれ違う","すれちがう","v5u|vi","lướt qua nhau | lỡ gặp | bất đồng","to pass by each other | to fail to meet | to be at odds","1595920"),
    ("巡る","めぐる","v5r|vi","đi vòng quanh | xoay quanh | tuần hoàn | liên quan đến","to go around | to circulate | to concern (a matter)","1342050"),
    ("辿る","たどる","v5r|vt","lần theo | dò theo | đi theo (con đường)","to follow (a path) | to trace | to pursue (a course)","1416690"),
    ("彷徨う","さまよう","v5u|vi","lang thang | lảng vảng | phiêu bạt","to wander about | to roam | to loiter","1566730"),
    ("跨ぐ","またぐ","v5g|vt","bước qua | nhảy qua | bắc qua","to step over | to straddle | to span | to bridge","1267830"),
    ("よじ登る","よじのぼる","v5r|vi","leo trèo | bám leo lên","to climb | to clamber up | to scale","1632750"),
    ("這う","はう","v5u|vi","bò | trườn | leo (dây leo)","to crawl | to creep | to trail (of vines)","1474200"),
    ("滑る","すべる","v5r|vi","trượt | trơn | trượt (kỳ thi)","to slide | to glide | to slip | to be slippery | to fail (an exam)","1208640"),
    ("跳ねる","はねる","v1|vi","nhảy | bật lên | bắn lên","to jump | to leap | to spring up | to bound","1429620"),
    ("舞う","まう","v5u|vi","múa | bay lượn | xoáy (trong gió)","to dance | to flutter (about) | to swirl | to circle","1499100"),
    ("溺れる","おぼれる","v1|vi","chết đuối | đắm chìm | sa đà","to (nearly) drown | to indulge in | to wallow in","1437560"),
    ("割れる","われる","v1|vi","vỡ | nứt | tách ra | chia rẽ | lộ ra","to break | to crack | to split | to be divided | to come to light","1208020"),
    ("砕ける","くだける","v1|vi","vỡ vụn | tan vỡ | trở nên thân mật","to break into pieces | to crumble | to become less formal","1295190"),
    ("破れる","やぶれる","v1|vi","rách | thủng | đổ vỡ (đàm phán)","to get torn | to wear out | to break down (negotiations)","1471210"),
    ("削れる","けずれる","v1","bị bào mòn | bị gọt đi","to be shaved or planed","2036970"),
    ("焦げる","こげる","v1|vi","cháy | khét | xém","to burn | to scorch | to char | to singe","1350730"),
    ("腐る","くさる","v5r|vi","thối | hỏng | mục | nản lòng","to rot | to go bad | to decay | to feel depressed","1497800"),
    ("錆びる","さびる","v1|vi","gỉ | gỉ sét | hoen gỉ","to rust | to become rusty","1299640"),
    ("萎れる","しおれる","v1|vi","héo | tàn | rũ | ỉu xìu","to wither | to wilt | to droop | to be dejected","1158690"),
    ("膨れる","ふくれる","v1|vi","phồng lên | trương lên | phụng phịu","to swell | to expand | to bulge | to get sulky","1602550"),
    ("反る","そる","v5r|vi","cong | vênh | ưỡn (người)","to warp | to curve | to arch | to bend backward","1480170"),
    ("絡まる","からまる","v5r|vi","quấn vào | vướng víu | dính líu","to be entwined | to be involved","1548490"),
    ("解ける","ほどける","v1|vi","tuột ra | tháo ra | được nới lỏng","to come loose | to come untied | to loosen up","1198920"),
    ("膨張","ぼうちょう","n|vs|vi","giãn nở | phình to | tăng trưởng","expansion | swelling | increase | growth","1520010"),
    ("収縮","しゅうしゅく","n|vs|vi","co lại | co rút | thu nhỏ","contraction | shrinking | constriction","1330670"),
    ("振動","しんどう","n|vs|vi","rung động | dao động | chấn động","oscillation | vibration | swing","1361420"),
    ("回転","かいてん","n|vs|vi","quay | xoay | luân chuyển","rotation | revolution | turn | spin | turnover","1199640"),
    ("移動","いどう","n|vs|vt|vi","di chuyển | di động | di dời","movement | transfer | migration | moving","1158400"),
    ("停止","ていし","n|vs|vt|vi","dừng lại | ngừng | đình chỉ","stoppage | halt | suspension | cessation","1434920"),
    ("逆転","ぎゃくてん","n|vs|vt|vi","đảo ngược | lội ngược dòng | xoay chuyển","reversal (of a situation) | turnaround | comeback","1227170"),
    ("転倒","てんとう","n|vs|vi","ngã | lật úp | đảo lộn | hoảng loạn","fall | tumbling | toppling over | inversion","1619700"),
    ("落下","らっか","n|vs|vi","rơi | rơi xuống | hạ xuống","fall | drop | descent","1548650"),
    ("墜落","ついらく","n|vs|vi","rơi | rớt | (máy bay) rơi","fall | crash (of an aircraft)","1432240"),
    ("衝撃","しょうげき","n","cú sốc | chấn động | va đập","impact | shock | impulse | (psychological) shock","1351510"),
    ("反射","はんしゃ","n|vs|vt|vi","phản xạ | phản chiếu","reflection | reflex","1480420"),
    ("屈折","くっせつ","n|vs|vi","khúc xạ | bẻ cong | méo mó (cảm xúc)","bending | refraction | distortion (of feelings)","1246620"),
    ("貫通","かんつう","n|vs|vt|vi","xuyên qua | đâm thủng | thông suốt","passing through | penetrating | piercing","1215080"),
    ("浮上","ふじょう","n|vs|vi","nổi lên | trồi lên | vươn lên","surfacing | rising to the surface | emerging","1497500"),
    ("沈没","ちんぼつ","n|vs|vi","chìm | đắm (tàu)","sinking | foundering | submersion","1431800"),
    ("漂流","ひょうりゅう","n|vs|vi","trôi dạt | lênh đênh","drifting | drift | being adrift","1489300"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
