# -*- coding: utf-8 -*-
"""Build N2 ready wave 054 — broadcasting, programs, journalism, online, names, reporting."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-054.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("生放送","なまほうそう","n|vs|vt","phát sóng trực tiếp","live broadcast","1379520"),
    ("生中継","なまちゅうけい","n|vs|vt","truyền hình trực tiếp | tường thuật trực tiếp","live broadcast | live coverage","1379360"),
    ("再放送","さいほうそう","n|vs|vt","phát lại | chiếu lại","rebroadcasting | rerun","1293590"),
    ("視聴率","しちょうりつ","n","tỷ suất người xem | rating chương trình","ratings | audience rating","1312120"),
    ("視聴者","しちょうしゃ","n","người xem | khán giả","viewer | audience","1312110"),
    ("聴取","ちょうしゅ","n|vs|vt","lắng nghe | thu thập ý kiến | hỏi cung | nghe đài","hearing | questioning | listening (to radio)","1428900"),
    ("聴取者","ちょうしゅしゃ","n","thính giả | người nghe đài","listener (of radio) | audience","1800490"),
    ("放映","ほうえい","n|vs|vt","phát sóng (truyền hình) | chiếu | lên sóng","televising | broadcasting | airing","1516550"),
    ("放送局","ほうそうきょく","n","đài phát thanh truyền hình | đài phát sóng","broadcasting station","1516760"),
    ("電波","でんぱ","n|adj-na","sóng điện từ | sóng | tín hiệu | (lóng) nói linh tinh","radio wave | signal | reception","1443720"),
    ("衛星放送","えいせいほうそう","n","truyền hình vệ tinh","satellite broadcasting","1174780"),
    ("有線","ゆうせん","adj-no|n","hữu tuyến | có dây | truyền qua dây","wired | cabled | communication by wire","1541460"),
    ("地上波","ちじょうは","n|adj-no","sóng mặt đất | truyền hình mặt đất","terrestrial broadcast signal | over-the-air","2374320"),
    ("中波","ちゅうは","n","sóng trung | tần số trung","medium wave | medium frequency","1425290"),
    ("短波","たんぱ","n|adj-no","sóng ngắn","short wave","1418810"),
    ("受信料","じゅしんりょう","n","phí thu (đài, truyền hình) | phí dịch vụ truyền hình","(TV) license fee","1937620"),
    ("共演","きょうえん","n|vs|vt|vi","đóng chung | diễn chung | góp mặt cùng","appearing together | co-starring","1234320"),
    ("助演","じょえん","n|vs|vt|vi","vai phụ | đóng vai phụ","supporting performance","1344510"),
    ("司会","しかい","n|vs|vt|vi","dẫn chương trình | chủ trì | người dẫn (MC)","leading a meeting | host | master of ceremonies","1306640"),
    ("進行","しんこう","n|vs|vi|vt","tiến triển | diễn tiến | dẫn dắt (chương trình) | tiến lên","progress | advance | progression (of a disease)","1366060"),
    ("実況","じっきょう","n|vs|vt","tình hình thực tế | tường thuật trực tiếp | bình luận live","actual conditions | live broadcast | running commentary","1320930"),
    ("解説","かいせつ","n|vs|vt","giải thích | bình luận | thuyết minh | diễn giải","explanation | commentary | exposition","1199080"),
    ("副音声","ふくおんせい","n","kênh âm thanh phụ | tiếng phụ","second (supplementary) sound channel","1954580"),
    ("字幕版","じまくばん","n","bản phụ đề (phim)","subtitled version (of a movie)","2670640"),
    ("報道番組","ほうどうばんぐみ","n","chương trình thời sự | chương trình tin tức","news program","1946810"),
    ("情報番組","じょうほうばんぐみ","n","chương trình thông tin giải trí","infotainment program | information program","2845425"),
    ("娯楽番組","ごらくばんぐみ","n","chương trình giải trí","amusement program","1269310"),
    ("教養番組","きょうようばんぐみ","n","chương trình giáo dục (TV, radio)","educational program","1237380"),
    ("連続ドラマ","れんぞくドラマ","n","phim truyền hình dài tập | phim bộ","drama serial","1959940"),
    ("特番","とくばん","n","chương trình đặc biệt | tập đặc biệt","special radio or television programme","2145370"),
    ("ゴールデンタイム","ゴールデンタイム","n","khung giờ vàng | giờ cao điểm (phát sóng)","prime time | peak time","1054320"),
    ("深夜番組","しんやばんぐみ","n","chương trình khuya | chương trình phát sóng nửa đêm","late-night show","2745780"),
    ("収録","しゅうろく","n|vs|vt","ghi lại (trong sách) | thu (âm, hình) | đưa vào","recording (in a book) | recording (audio/video)","1330980"),
    ("放送事故","ほうそうじこ","n","sự cố phát sóng | sai sót khi phát sóng","TV blooper | broadcasting blunder","2847871"),
    ("報道機関","ほうどうきかん","n","cơ quan báo chí | giới truyền thông","information media | press","1515750"),
    ("記者会見","きしゃかいけん","n|vs|vi","họp báo","press conference","1223260"),
    ("取材源","しゅざいげん","n","nguồn tin (cho bài báo)","source (for a news article)","2721780"),
    ("スクープ","スクープ","n|vs|vt","tin độc quyền | tin giật gân","(news) scoop","1068210"),
    ("特ダネ","とくダネ","n","tin độc quyền | tin nóng riêng","exclusive news | scoop","1455040"),
    ("情報操作","じょうほうそうさ","n|vs","thao túng thông tin | bóp méo thông tin","manipulation of information | spin","2831963"),
    ("世論操作","よろんそうさ","n","thao túng dư luận | dẫn dắt dư luận","manipulation of public opinion","2054750"),
    ("偏向報道","へんこうほうどう","n","đưa tin thiên lệch | đưa tin có thành kiến","biased coverage | bias in reporting","2831964"),
    ("名誉毀損","めいよきそん","n","bôi nhọ danh dự | phỉ báng | vu khống","libel | defamation | slander","1641380"),
    ("肖像権","しょうぞうけん","n","quyền hình ảnh | quyền chân dung","rights to usage of one's likeness","1742910"),
    ("著作権侵害","ちょさくけんしんがい","n","vi phạm bản quyền | xâm phạm tác quyền","copyright infringement | piracy","1942640"),
    ("盗作","とうさく","n|vs|vt","đạo văn | tác phẩm ăn cắp","plagiarism | plagiarised work","1448450"),
    ("剽窃","ひょうせつ","n|vs|vt","đạo văn | ăn cắp ý tưởng","plagiarism","1564770"),
    ("無断転載","むだんてんさい","n","đăng lại trái phép | sao chép không xin phép","unauthorized reproduction | unauthorized copying","1530620"),
    ("誹謗中傷","ひぼうちゅうしょう","n|vs|vt","phỉ báng bôi nhọ | vu khống lăng mạ","slander | defamation | abuse","2052500"),
    ("個人情報","こじんじょうほう","n","thông tin cá nhân","personal information","1264870"),
    ("情報漏洩","じょうほうろうえい","n","rò rỉ thông tin | lộ dữ liệu","information leak | data breach","2831082"),
    ("不正アクセス","ふせいアクセス","n","truy cập trái phép | xâm nhập (máy tính) | hack","unauthorized (computer) access | hacking","2099230"),
    ("迷惑メール","めいわくメール","n","thư rác | email spam","spam | unsolicited email","2057920"),
    ("利用規約","りようきやく","n","điều khoản sử dụng | quy định dịch vụ","terms of service | terms of use","2831622"),
    ("匿名","とくめい","n|adj-no","ẩn danh | nặc danh | dùng tên giả","anonymity | using an assumed name","1454470"),
    ("実名","じつめい","n","tên thật","real name","1321470"),
    ("仮名","かめい","n","bí danh | tên giả | bút danh","alias | pseudonym | pen name","1577090"),
    ("偽名","ぎめい","n","tên giả | danh tính giả | bí danh","false name | alias | assumed name","1224670"),
    ("本名","ほんみょう","n","tên thật","real name","1523240"),
    ("別名","べつめい","n","tên khác | biệt danh | bí danh | bút danh","another name | synonym | alias","1583930"),
    ("通称","つうしょう","n|vs|vt","tên thường gọi | tên gọi phổ biến | biệt danh","popular name | common name | nickname","1433270"),
    ("愛称","あいしょう","n","tên thân mật | biệt danh trìu mến","pet name | nickname | affectionate name","1150840"),
    ("略称","りゃくしょう","n|vs|vt","tên viết tắt | từ viết tắt","abbreviation","1552030"),
    ("正式名称","せいしきめいしょう","n","tên gọi chính thức","official name | formal name","2216920"),
    ("異名","いみょう","n","biệt danh | tên gọi khác | danh xưng khác","another name | nickname | alias","1158110"),
    ("名義","めいぎ","n","tên (trên giấy tờ) | đứng tên | danh nghĩa | cái cớ","name (on a deed) | moral duty | pretext","1531410"),
    ("署名運動","しょめいうんどう","n","phong trào thu thập chữ ký","signature-collecting campaign","1701340"),
    ("請願書","せいがんしょ","n","đơn thỉnh cầu | đơn kiến nghị","(written) petition","1751640"),
    ("内部告発","ないぶこくはつ","n","tố giác nội bộ | tố cáo từ bên trong","whistleblowing","1792030"),
    ("通報","つうほう","n|vs|vt|vi","báo tin | thông báo | trình báo | mật báo","report | notification | tip","1433530"),
    ("垂れ込み","たれこみ","n","tin mật báo | chỉ điểm | tố giác nặc danh","tip-off (to the authorities) | anonymous report","1704480"),
    ("情報提供","じょうほうていきょう","n|vs|vi","cung cấp thông tin","providing information","2124810"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
