# -*- coding: utf-8 -*-
"""Build N2 ready wave 004 — 81 freshly-curated N2 〜感/〜観 nouns + emotive i-adjectives + formal verbs."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-004.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("解放感","かいほうかん","n","cảm giác giải thoát | sự nhẹ nhõm tự do","sense of liberation | feeling of freedom","1931520"),
    ("開放感","かいほうかん","n","cảm giác thoáng đãng | sự rộng rãi","sense of space | spaciousness","2671400"),
    ("圧迫感","あっぱくかん","n","cảm giác bị áp chế | sự ngột ngạt | bức bối","feeling of oppression","1153320"),
    ("臨場感","りんじょうかん","n","cảm giác như thật | cảm giác sống động như đang ở đó","(sense of) presence | feeling of actually being there | realism","1555670"),
    ("透明感","とうめいかん","n","cảm giác trong trẻo | độ trong | sự minh bạch","feeling of transparency | clear and unclouded feel","2647780"),
    ("連帯感","れんたいかん","n","cảm giác đoàn kết | tình đồng đội","feeling of solidarity","1559670"),
    ("疎外感","そがいかん","n","cảm giác bị bỏ rơi | sự lạc lõng | bị xa lánh","feeling of alienation | sense of being excluded","1396720"),
    ("喪失感","そうしつかん","n","cảm giác mất mát | sự hụt hẫng","sense of loss | feeling of loss","2583550"),
    ("無力感","むりょくかん","n","cảm giác bất lực | sự vô vọng","sense of helplessness | feeling of powerlessness","2130230"),
    ("焦燥感","しょうそうかん","n","cảm giác sốt ruột | bồn chồn | nôn nóng","irritability | feeling of impatience | uneasiness","2845065"),
    ("嫌悪感","けんおかん","n","cảm giác ghê tởm | sự chán ghét | ác cảm","(feeling of) disgust | aversion | loathing","2146500"),
    ("不信感","ふしんかん","n","cảm giác ngờ vực | sự nghi ngờ","distrust | suspicion","2106140"),
    ("抵抗感","ていこうかん","n","cảm giác phản kháng | sự e ngại | miễn cưỡng","antipathy | reluctance | resistance","2582240"),
    ("高級感","こうきゅうかん","n","cảm giác sang trọng | vẻ cao cấp","air of luxury | high class feel","2833981"),
    ("距離感","きょりかん","n","cảm giác khoảng cách (vật lý/tình cảm)","sense of distance (physical or emotional)","1933160"),
    ("高揚感","こうようかん","n","cảm giác phấn chấn | sự thăng hoa | hưng phấn","exaltation | emotional uplift","2837650"),
    ("価値観","かちかん","n","quan niệm giá trị | hệ giá trị","sense of values | value system","1189610"),
    ("世界観","せかいかん","n","thế giới quan | nhân sinh quan | bối cảnh (tác phẩm)","worldview | outlook | setting (of a work)","1645810"),
    ("人生観","じんせいかん","n","quan niệm sống | thái độ với cuộc đời","one's view of life | outlook","1368400"),
    ("歴史観","れきしかん","n","sử quan | quan điểm lịch sử","historical viewpoint","1558110"),
    ("先入観","せんにゅうかん","n","định kiến | thành kiến | ý niệm có sẵn","preconception | preconceived notion | prejudice","1388330"),
    ("固定観念","こていかんねん","n","định kiến cố hữu | tư tưởng rập khuôn","fixed idea | stereotype | prejudice","1266660"),
    ("楽観","らっかん","n|vs|vt","lạc quan | nhìn theo hướng tích cực","optimism | taking an optimistic view","1207310"),
    ("悲観","ひかん","n|vs|vt|vi","bi quan | tuyệt vọng | thất vọng","pessimism | gloomy view | despair","1483240"),
    ("壮観","そうかん","n|adj-na","cảnh tượng hùng vĩ | quang cảnh ngoạn mục","magnificent spectacle | grand view","1399360"),
    ("概観","がいかん","n|vs|vt","khái quát | nhìn tổng quan","general view | outline","1204430"),
    ("傍観","ぼうかん","n|vs|vt","đứng nhìn | bàng quan | khoanh tay đứng ngoài","looking on | standing by and watching","1518800"),
    ("夥しい","おびただしい","adj-i","vô số | rất nhiều | nhiều vô kể","innumerable | great many | immense | abundant","1565840"),
    ("久しい","ひさしい","adj-i","đã lâu | lâu rồi","long (time passed) | old (story)","1227340"),
    ("聡い","さとい","adj-i","thông minh | nhạy bén | sắc sảo (tai, óc)","clever | smart | sharp | discerning","2087260"),
    ("疎い","うとい","adj-i","xa cách | ít hiểu biết | mù mờ | không rành","distant | knowing little (of) | ill-informed (about)","1396620"),
    ("危うい","あやうい","adj-i","nguy hiểm | bấp bênh | hiểm nghèo | đáng lo","dangerous | precarious | in jeopardy | uncertain","1218360"),
    ("脆い","もろい","adj-i","giòn | dễ vỡ | yếu ớt | dễ mủi lòng","brittle | fragile | frail | tender-hearted","1382220"),
    ("儚い","はかない","adj-i","phù du | mong manh | thoáng qua | viển vông","fleeting | transient | ephemeral | vain","1600630"),
    ("淡い","あわい","adj-i","nhạt | nhợt | thoáng qua | mơ hồ","light | faint | pale | fleeting","1418420"),
    ("渋い","しぶい","adj-i","chát | trầm | nhã | sâu lắng | cau có | keo kiệt","astringent | tasteful (quiet) | refined | sour (look) | stingy","1335540"),
    ("図太い","ずぶとい","adj-i","trơ tráo | lì lợm | mặt dày | gan lì","bold | shameless | cheeky | impudent","1370470"),
    ("執念深い","しゅうねんぶかい","adj-i","dai dẳng | cố chấp | thù dai","tenacious | persistent | vindictive | vengeful","1319700"),
    ("注意深い","ちゅういぶかい","adj-i","cẩn thận | thận trọng | chu đáo | cảnh giác","attentive | cautious | careful | watchful","1610330"),
    ("辛抱強い","しんぼうづよい","adj-i","kiên nhẫn | nhẫn nại | bền chí","patient | persevering","1633500"),
    ("我慢強い","がまんづよい","adj-i","rất kiên nhẫn | chịu đựng giỏi","(very) patient | persevering","1985140"),
    ("名高い","なだかい","adj-i","nổi tiếng | trứ danh | có tiếng","famous | noted | renowned | celebrated","1531490"),
    ("心地よい","ここちよい","adj-ix","dễ chịu | thoải mái | êm ái","comfortable | pleasant","1360830"),
    ("手強い","てづよい","adj-i","mạnh mẽ | cứng cỏi | kiên quyết | nghiêm","strong | resolute | firm | strict","1327465"),
    ("程よい","ほどよい","adj-i","vừa phải | vừa độ | vừa vặn","moderate | proper | just right","1735840"),
    ("名残惜しい","なごりおしい","adj-i","lưu luyến | bịn rịn | tiếc nuối (lúc chia tay)","reluctant (to part)","1531540"),
    ("焦れったい","じれったい","adj-i","sốt ruột | nóng ruột | bực bội | khó chịu","irritating | impatient | frustrating | vexing","1006010"),
    ("気まずい","きまずい","adj-i","gượng gạo | ngượng ngùng | khó xử","unpleasant | awkward | embarrassing | uneasy","1222550"),
    ("あどけない","あどけない","adj-i","ngây thơ | hồn nhiên | trẻ con (đáng yêu)","innocent | cherubic | childlike","1000410"),
    ("浅ましい","あさましい","adj-i","đáng khinh | hèn hạ | thảm hại | đê tiện","wretched | shameful | mean | despicable | abject","1390810"),
    ("痛ましい","いたましい","adj-i","đau lòng | thương tâm | bi thương","pitiful | heartbreaking | tragic | sad","1609200"),
    ("微笑ましい","ほほえましい","adj-i","đáng yêu | ấm lòng | dễ thương","heartwarming | pleasant | charming | amusing","1486000"),
    ("恨めしい","うらめしい","adj-i","oán hận | trách móc | cay đắng","reproachful | hateful | bitter","1289790"),
    ("妬ましい","ねたましい","adj-i","ghen tị | đố kỵ","jealous | envious","1444360"),
    ("喜ばしい","よろこばしい","adj-i","đáng mừng | vui mừng | đáng hoan nghênh","joyful | delightful | gratifying | welcome","1614400"),
    ("嘆かわしい","なげかわしい","adj-i","đáng buồn | đáng tiếc | thảm thương","lamentable | deplorable | regrettable | sad","1418060"),
    ("忌まわしい","いまわしい","adj-i","ghê tởm | đáng ghét | gở | xui xẻo","abhorrent | detestable | ominous | inauspicious","1220070"),
    ("汚らわしい","けがらわしい","adj-i","bẩn thỉu | nhơ nhuốc | ghê tởm | đê tiện","filthy | disgusting | foul | repulsive","1178980"),
    ("紛らわしい","まぎらわしい","adj-i","dễ nhầm | gây nhầm lẫn | mập mờ","easily mixed up | confusing | misleading | ambiguous","1504990"),
    ("煩わしい","わずらわしい","adj-i","phiền phức | rắc rối | phiền toái","troublesome | annoying | complicated","1481940"),
    ("赴く","おもむく","v5k|vi","đi đến | tiến tới | hướng về | tuân theo","to proceed toward | to repair to | to obey","1498190"),
    ("仰ぐ","あおぐ","v5g|vt","ngước nhìn | tôn kính | xin (chỉ dẫn) | nốc (uống)","to look up at | to respect | to ask for (guidance) | to gulp down","1238780"),
    ("葬る","ほうむる","v5r|vt","chôn cất | mai táng | che giấu | xếp xó","to bury | to inter | to cover up | to shelve","1402130"),
    ("崇める","あがめる","v1|vt","tôn sùng | tôn kính | thờ phụng","to revere | to respect | to worship","1372840"),
    ("称える","たたえる","v1|vt","ca ngợi | tán dương | tôn vinh","to praise | to extol | to laud | to celebrate","1351230"),
    ("嘲る","あざける","v5r|vt","cười nhạo | chế giễu | nhạo báng","to scoff | to laugh at | to ridicule | to jeer at","1565590"),
    ("見下す","みくだす","v5s|vt","coi thường | khinh thường | nhìn xuống","to look down on | to condescend (to)","1259360"),
    ("翻す","ひるがえす","v5s|vt","lật lại | thay đổi (ý) | rút lại (lời) | phất (cờ)","to turn over | to reverse (a decision) | to retract | to fly (a flag)","1523340"),
    ("牛耳る","ぎゅうじる","v5r|vt","thao túng | nắm quyền chi phối | dẫn dắt","to control | to take the lead in | to have under one's thumb","1231520"),
    ("統べる","すべる","v1|vt","cai trị | thống trị | thống nhất | hợp nhất","to rule over | to govern | to integrate | to unite","1449660"),
    ("駆使","くし","n|vs|vt","vận dụng thành thạo | sử dụng linh hoạt | bắt làm hết sức","making full use of | having a good command of","1244850"),
    ("酷使","こくし","n|vs|vt","bóc lột | vắt kiệt | lạm dụng","exploitation | overuse | abuse","1287350"),
    ("行使","こうし","n|vs|vt","thực thi | hành sử (quyền, vũ lực)","use | exercise (of a right, power)","1281910"),
    ("悪用","あくよう","n|vs|vt","lạm dụng | dùng vào việc xấu | bóp méo","abuse | misuse | perversion","1152570"),
    ("流用","りゅうよう","n|vs|vt","dùng sai mục đích | biển thủ | tái sử dụng","diversion (of funds) | misappropriation | reuse","1552550"),
    ("転用","てんよう","n|vs|vt","chuyển dùng | dùng vào mục đích khác","diversion | putting to another use","1441360"),
    ("起用","きよう","n|vs|vt","bổ nhiệm | trọng dụng | đề bạt","appointment | being used for a role | promotion","1223940"),
    ("登用","とうよう","n|vs|vt","bổ nhiệm | đề bạt | trọng dụng","appointment | assignment | promotion","1598650"),
    ("任用","にんよう","n|vs|vt","bổ nhiệm | tuyển dụng","appointment | employment","1467320"),
    ("奔走","ほんそう","n|vs|vi","chạy ngược xuôi | dốc sức lo liệu | bôn ba","running about | making every effort | busying oneself","1522100"),
    ("尽力","じんりょく","n|vs|vi","nỗ lực | dốc sức | tận lực | giúp đỡ","efforts | exertion | endeavour | assistance","1370100"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
