# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-045.csv -- 16 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-045.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("のんびり","のんびり","N4","adv|adv-to|vs",
        "thư thả | nhàn nhã | thong thả | không vội",
        "at leisure | in a relaxed manner | in a carefree manner | quietly | peacefully",
        "1010050",
        "のんびりと過ごす。","のんびりとすごす。",
        "Sống thư thả thoải mái.","Spend time in a relaxed manner."),
    row("説得","せっとく","N4","n|vs|vt",
        "sự thuyết phục | thuyết phục ai đó",
        "persuasion",
        "1386440",
        "相手を説得する。","あいてをせっとくする。",
        "Thuyết phục đối phương.","Persuade the other party."),
    row("宣言","せんげん","N4","n|vs|vt",
        "tuyên bố | tuyên ngôn | công bố | tuyên cáo",
        "declaration | proclamation | announcement",
        "1389680",
        "独立を宣言する。","どくりつをせんげんする。",
        "Tuyên bố độc lập.","Declare independence."),
    row("日食","にっしょく","N4","n",
        "nhật thực | nhật thực (mặt trời bị che khuất)",
        "solar eclipse",
        "1464220",
        "日食を観察する。","にっしょくをかんさつする。",
        "Quan sát nhật thực.","Observe a solar eclipse."),
    row("報告","ほうこく","N4","n|vs|vt",
        "báo cáo | thông báo | tường thuật",
        "report | information",
        "1515670",
        "結果を報告する。","けっかをほうこくする。",
        "Báo cáo kết quả.","Report the results."),
    row("雷雨","らいう","N4","n",
        "mưa sấm sét | cơn giông | bão có sấm chớp",
        "thunderstorm | thundershower",
        "1548420",
        "激しい雷雨。","はげしいらいう。",
        "Cơn giông dữ dội.","A violent thunderstorm."),
    row("雹","ひょう","N4","n",
        "mưa đá (viên lớn từ 5mm) | đá mưa to",
        "hail (esp. hailballs 5 mm or greater)",
        "1574070",
        "雹が降る。","ひょうがふる。",
        "Mưa đá to rơi xuống.","Hail falls."),
    row("うとうと","うとうと","N4","adv|adv-to|vs",
        "ngủ gà | chợp mắt | thiu thiu ngủ",
        "falling into a doze | dozing off | nodding off",
        "1001030",
        "授業中にうとうとする。","じゅぎょうちゅうにうとうとする。",
        "Ngủ gà trong giờ học.","Doze off during class."),
    row("ぐっすり","ぐっすり","N4","adv",
        "ngủ say | ngủ sâu | ngủ như chết",
        "soundly (sleeping) | fast (asleep)",
        "1004060",
        "ぐっすり眠る。","ぐっすりねむる。",
        "Ngủ say sưa.","Sleep soundly."),
    row("こっそり","こっそり","N4","adv",
        "lén lút | âm thầm | bí mật | lén lén",
        "stealthily | secretly | in secret",
        "1004520",
        "こっそり部屋を出る。","こっそりへやをでる。",
        "Lén lút ra khỏi phòng.","Secretly leave the room."),
    row("三日月","みかづき","N4","n",
        "trăng lưỡi liềm | trăng non hình lưỡi liềm",
        "crescent moon | young moon",
        "1301340",
        "三日月が見える。","みかづきがみえる。",
        "Nhìn thấy trăng lưỡi liềm.","The crescent moon is visible."),
    row("天の川","あまのがわ","N4","n",
        "dải Ngân Hà | Ngân Hà | dải sáng trên bầu trời đêm",
        "Milky Way | luminous band corresponding to the plane of the galaxy",
        "1582020",
        "天の川を眺める。","あまのがわをながめる。",
        "Ngắm nhìn dải Ngân Hà.","Gaze at the Milky Way."),
    row("新月","しんげつ","N4","n",
        "trăng non | trăng mới | ngày mồng một âm lịch",
        "new moon | first day of the lunar month",
        "1720200",
        "今夜は新月だ。","こんやはしんげつだ。",
        "Đêm nay là trăng non.","Tonight is a new moon."),
    row("月食","げっしょく","N4","n",
        "nguyệt thực | nguyệt thực (mặt trăng bị che khuất)",
        "lunar eclipse",
        "1255730",
        "皆既月食。","かいきげっしょく。",
        "Nguyệt thực toàn phần.","A total lunar eclipse."),
    row("流れ星","ながれぼし","N4","n",
        "sao băng | sao đổi ngôi | meteor",
        "shooting star | falling star | meteor",
        "1552200",
        "流れ星に願いを込める。","ながれぼしにねがいをこめる。",
        "Ước nguyện khi thấy sao băng.","Make a wish on a shooting star."),
    row("満月","まんげつ","N4","n",
        "trăng tròn | trăng rằm | trăng đầy",
        "full moon",
        "1526770",
        "満月の夜。","まんげつのよる。",
        "Đêm trăng rằm.","A full moon night."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
