# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-024.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-024.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("感じ取る","かんじとる","N4","v5r|vt",
        "cảm nhận | nhận ra | nắm bắt",
        "to perceive | to sense | to take in | to grasp | to feel",
        "1212270",
        "変化を感じ取ります。","へんかをかんじとります。","Tôi cảm nhận sự thay đổi.","I perceive the change."),
    row("気にかける","きにかける","N4","exp|v1|vt",
        "lo lắng về | băn khoăn | quan tâm đến",
        "to weigh on one's mind | to trouble one's heart | to be concerned about | to worry about",
        "1221700",
        "友達のことを気にかけます。","ともだちのことをきにかけます。","Tôi quan tâm đến bạn bè.","I am concerned about my friend."),
    row("広まる","ひろまる","N4","v5r|vi",
        "lan rộng | phổ biến",
        "to spread | to be propagated",
        "1278450",
        "噂が広まります。","うわさがひろまります。","Tin đồn lan rộng.","The rumor spreads."),
    row("考え込む","かんがえこむ","N4","v5m|vi",
        "suy ngẫm sâu | trầm tư | lo âu",
        "to ponder | to brood",
        "1281030",
        "深く考え込みます。","ふかくかんがえこみます。","Tôi suy nghĩ sâu sắc.","I brood deeply."),
    row("手渡す","てわたす","N4","v5s|vt",
        "trao tận tay | giao tận tay",
        "to hand (over) | to deliver in person",
        "1328210",
        "書類を手渡します。","しょるいをてわたします。","Tôi trao tận tay tài liệu.","I hand over the documents in person."),
    row("柔軟","じゅうなん","N4","adj-na|n",
        "linh hoạt | mềm mại | dẻo | thể dục thể hình",
        "flexible | lithe | soft | pliable | calisthenics",
        "1335480",
        "柔軟な対応が必要です。","じゅうなんなたいおうがひつようです。","Cần phản ứng linh hoạt.","Flexible response is needed."),
    row("数千","すうせん","N4","n",
        "hàng nghìn | vài nghìn",
        "thousands | several thousand",
        "1373120",
        "数千人が参加します。","すうせんにんがさんかします。","Hàng nghìn người tham gia.","Thousands of people participate."),
    row("相対的","そうたいてき","N4","adj-na",
        "tương đối",
        "relative",
        "1401180",
        "相対的に見ると違います。","そうたいてきにみるとちがいます。","Nhìn một cách tương đối thì khác nhau.","It looks different relatively speaking."),
    row("体力","たいりょく","N4","n",
        "sức mạnh thể chất | thể lực | sức bền | sức chịu đựng",
        "physical strength | power | stamina | endurance | vigor | resistance to disease | strength (of a business, economy, etc.)",
        "1409760",
        "体力をつけます。","たいりょくをつけます。","Tôi tăng cường thể lực.","I build up physical strength."),
    row("搭乗","とうじょう","N4","n|vs|vi",
        "lên tàu | lên máy bay | lên xe",
        "embarkation | boarding (a ship or aircraft)",
        "1447400",
        "飛行機に搭乗します。","ひこうきにとうじょうします。","Tôi lên máy bay.","I board the airplane."),
    row("同様","どうよう","N4","adj-no|adj-na|n|n-suf",
        "giống như | tương tự | bằng nhau",
        "same | similar | (just) like | equal",
        "1453550",
        "同様の方法で行います。","どうようのほうほうでおこないます。","Tôi thực hiện bằng phương pháp tương tự.","I do it in the same way."),
    row("問いかける","といかける","N4","v1|vt",
        "đặt câu hỏi | hỏi | bắt đầu hỏi",
        "to ask a question | to begin to ask a question",
        "1535940",
        "自分に問いかけます。","じぶんにといかけます。","Tôi tự hỏi bản thân mình.","I ask myself a question."),
    row("に比べ","にくらべ","N4","exp",
        "so với | so sánh với",
        "compared to",
        "1009840",
        "去年に比べて暖かいです。","きょねんにくらべてあたたかいです。","So với năm ngoái thì ấm hơn.","It is warmer compared to last year."),
    row("直行","ちょっこう","N4","n|vs|vi|adj-no",
        "đi thẳng | đi thẳng tới đích | không dừng | quyết đoán",
        "going straight (to) | going direct | going without stopping | unwavering action | decisive action | upright conduct",
        "1430960",
        "直行便で行きます。","ちょっこうびんでいきます。","Tôi đi chuyến bay thẳng.","I go on a direct flight."),
    row("通じる","つうじる","N4","v1|vi",
        "thông | dẫn đến | liên lạc được | hiểu được | tinh thông | phổ biến rộng rãi",
        "to be open (to traffic) | to lead to | to communicate (with) | to flow (liquid, current) | to pass | to get through to | to be understood | to be comprehended | to be honored | to be good | to be well versed in | to be well-informed | to communicate clandestinely | to keep in touch (e.g. with the enemy) | to form a liaison | to be intimate | to spread widely | to disseminate",
        "1432880",
        "英語が通じます。","えいごがつうじます。","Tiếng Anh được hiểu.","English gets through."),
    row("廃棄物","はいきぶつ","N4","n",
        "chất thải | rác thải | phế liệu",
        "waste matter | waste | garbage | trash",
        "1472040",
        "廃棄物を処理します。","はいきぶつをしょりします。","Tôi xử lý chất thải.","I dispose of waste."),
    row("排気","はいき","N4","n|vs|vi",
        "khí thải | ống xả | thông gió",
        "exhaust | emission (of gas from an engine) | expulsion (of air) | ventilation",
        "1472320",
        "排気ガスを減らします。","はいきガスをへらします。","Tôi giảm khí thải.","I reduce exhaust fumes."),
    row("品切れ","しなぎれ","N4","n|adj-no",
        "hết hàng | bán hết",
        "out of stock | sold out",
        "1490640",
        "品切れになりました。","しなぎれになりました。","Hàng đã bán hết.","We are sold out."),
    row("撫でる","なでる","N4","v1|vt",
        "vuốt ve | xoa đầu | chải (tóc) | xoa nhẹ",
        "to stroke | to caress | to brush gently | to pat | to rub | to comb (hair) | to smooth down",
        "1498290",
        "猫を撫でます。","ねこをなでます。","Tôi vuốt ve con mèo.","I stroke the cat."),
    row("平静","へいせい","N4","n|adj-na",
        "bình tĩnh | điềm tĩnh | yên tĩnh | bình thản",
        "calm | peace | serenity | tranquility | tranquillity | composure | equanimity | presence of mind",
        "1507530",
        "平静を保ちます。","へいせいをたもちます。","Tôi giữ bình tĩnh.","I maintain composure."),
    row("返品","へんぴん","N4","n|vs|vt|vi",
        "trả hàng | hàng trả lại",
        "returned goods | returning purchased goods",
        "1512300",
        "商品を返品します。","しょうひんをへんぴんします。","Tôi trả lại sản phẩm.","I return the product."),
    row("揚げ物","あげもの","N4","n",
        "đồ chiên | món chiên giòn",
        "deep-fried food",
        "1545530",
        "揚げ物が好きです。","あげものがすきです。","Tôi thích đồ chiên.","I like deep-fried food."),
    row("溜める","ためる","N4","v1|vt",
        "tích lũy | gom góp | để dành | để nợ",
        "to amass | to accumulate | to store | to leave unpaid",
        "1552630",
        "お金を溜めます。","おかねをためます。","Tôi để dành tiền.","I save money."),
    row("溜まる","たまる","N4","v5r|vi",
        "tích tụ | đọng lại | chồng chất | tích lũy",
        "to collect | to gather | to save | to accumulate | to pile up",
        "1552650",
        "ストレスが溜まります。","ストレスがたまります。","Stress tích lũy lại.","Stress accumulates."),
    row("頷く","うなずく","N4","v5k|vi",
        "gật đầu | đồng ý bằng cách gật đầu",
        "to nod | to bow one's head in assent | to agree",
        "1574310",
        "同意して頷きます。","どういしてうなずきます。","Tôi gật đầu đồng ý.","I nod in agreement."),
    row("切り出す","きりだす","N4","v5s|vt",
        "khai thác đá | cưa gỗ | bắt đầu nói chuyện | phá băng | chắt lọc (từ file media)",
        "to quarry | to cut (timber) | to cut and carry off | to begin to talk | to break the ice | to broach | to start a fire (with flint, by rubbing sticks together, etc.) | to select and extract (from a media file) | to splice out",
        "1580950",
        "本題を切り出します。","ほんだいをきりだします。","Tôi đi vào chủ đề chính.","I broach the main topic."),
    row("喜び","よろこび","N4","n",
        "niềm vui | hân hoan | sự vui mừng | lời chúc mừng",
        "joy | delight | rapture | pleasure | gratification | rejoicing | congratulations | felicitations",
        "1606140",
        "喜びを感じます。","よろこびをかんじます。","Tôi cảm nhận niềm vui.","I feel joy."),
    row("味見","あじみ","N4","n|vs|vt",
        "thử vị | nếm thử",
        "tasting | sampling",
        "1722300",
        "料理を味見します。","りょうりをあじみします。","Tôi nếm thử món ăn.","I taste the dish."),
    row("寂しさ","さびしさ","N4","n",
        "nỗi cô đơn | sự hiu quạnh",
        "(feeling of) loneliness | desolation",
        "2423480",
        "寂しさを感じます。","さびしさをかんじます。","Tôi cảm thấy cô đơn.","I feel loneliness."),
    row("地方","じかた","N4","n",
        "người phụ trách âm nhạc (biểu diễn múa) | bờ biển | vùng quê | nông thôn",
        "person in charge of music (in a Japanese dance performance) | person singing ballads (in noh) | coast (esp. as seen from the water) | shore | the country | countryside | the provinces | rural area",
        "2796690",
        "地方の音楽を担当します。","じかたのおんがくをたんとうします。","Tôi phụ trách âm nhạc biểu diễn.","I am in charge of the music for the performance."),
    row("兄弟","けいてい","N4","n",
        "anh em trai | huynh đệ (cách đọc hán văn)",
        "older and younger brothers | brothers",
        "2870775",
        "兄弟の仲が良いです。","けいていのなかがよいです。","Tình anh em rất tốt.","The relationship between brothers is good."),
    row("絵画","かいが","N4","n",
        "tranh vẽ | hội họa",
        "painting | picture",
        "1202300",
        "絵画を鑑賞します。","かいがをかんしょうします。","Tôi thưởng thức tranh vẽ.","I appreciate paintings."),
    row("権利","けんり","N4","n",
        "quyền lợi | đặc quyền | quyền",
        "right | privilege",
        "1258200",
        "権利を守ります。","けんりをまもります。","Tôi bảo vệ quyền lợi.","I protect rights."),
    row("見合わせる","みあわせる","N4","v1|vt",
        "nhìn nhau | hoãn lại | so sánh | đối chiếu",
        "to exchange glances | to look at each other | to postpone | to put off | to withhold | to abandon | to contrast | to compare",
        "1259570",
        "計画を見合わせます。","けいかくをみあわせます。","Tôi hoãn kế hoạch.","I postpone the plan."),
    row("見守る","みまもる","N4","v5r|vt",
        "trông chừng | canh giữ | dõi theo | nhìn chăm chú",
        "to watch over | to keep watch over | to keep an eye on | to watch intently | to stare | to gaze | to watch (and see what happens) | to follow",
        "1259680",
        "子供を見守ります。","こどもをみまもります。","Tôi trông chừng trẻ em.","I watch over the children."),
    row("行き先","いきさき","N4","n",
        "điểm đến | nơi đến | tương lai | triển vọng",
        "destination | whereabouts | future | prospects",
        "1281720",
        "行き先を教えます。","いきさきをおしえます。","Tôi cho biết điểm đến.","I tell you the destination."),
    row("作曲","さっきょく","N4","n|vs|vt|vi",
        "sáng tác âm nhạc | soạn nhạc",
        "composition (of music) | setting | writing music",
        "1297650",
        "曲を作曲します。","きょくをさっきょくします。","Tôi sáng tác bài nhạc.","I compose a piece of music."),
    row("作詞","さくし","N4","n|vs|vt|vi",
        "viết lời bài hát | sáng tác lời nhạc",
        "(writing) song lyrics",
        "1297680",
        "歌詞を作詞します。","かしをさくしします。","Tôi viết lời bài hát.","I write song lyrics."),
    row("撮影","さつえい","N4","n|vs|vt",
        "chụp ảnh | quay phim | ghi hình",
        "photography (still or motion) | photographing | filming | shooting | (video) recording",
        "1298800",
        "写真を撮影します。","しゃしんをさつえいします。","Tôi chụp ảnh.","I take photos."),
    row("数百","すうひゃく","N4","n",
        "hàng trăm | vài trăm",
        "several hundred | hundreds (of)",
        "1373250",
        "数百人が来ます。","すうひゃくにんがきます。","Hàng trăm người đến.","Hundreds of people come."),
    row("走り回る","はしりまわる","N4","v5r|vi",
        "chạy lung tung | chạy khắp nơi",
        "to run around",
        "1402430",
        "子供が走り回ります。","こどもがはしりまわります。","Trẻ em chạy lung tung.","The children run around."),
    row("働きかける","はたらきかける","N4","v1|vt|vi",
        "tác động lên | kêu gọi | tiếp cận | gây áp lực | bắt đầu làm việc",
        "to work on (someone) | to appeal to | to make approaches to | to pressure | to exert influence on | to seek action from | to begin to work",
        "1451060",
        "政府に働きかけます。","せいふにはたらきかけます。","Tôi kêu gọi chính phủ.","I appeal to the government."),
    row("同等","どうとう","N4","adj-na|adj-no|n",
        "bình đẳng | ngang hàng | tương đương",
        "equality | equal | same rights | same rank | equivalence",
        "1453190",
        "同等の扱いをします。","どうとうのあつかいをします。","Tôi đối xử bình đẳng.","I treat equally."),
    row("話しかける","はなしかける","N4","v1|vt",
        "bắt chuyện | trò chuyện với | bắt đầu nói chuyện",
        "to address (someone) | to accost a person | to talk (to someone) | to begin to talk | to start a conversation",
        "1562300",
        "知らない人に話しかけます。","しらないひとにはなしかけます。","Tôi bắt chuyện với người lạ.","I talk to a stranger."),
    row("文書","ぶんしょ","N4","n",
        "tài liệu | văn bản | giấy tờ | hồ sơ | thư",
        "document | writing | letter | papers | notes | records | archives | document addressed to someone",
        "1583840",
        "文書を作成します。","ぶんしょをさくせいします。","Tôi soạn thảo tài liệu.","I prepare a document."),
    row("売り場","うりば","N4","n",
        "khu bán hàng | quầy hàng | gian hàng | thời điểm tốt để bán",
        "selling area | counter | section | department | sales floor | favorable time to sell | good time to sell",
        "1588550",
        "売り場を探します。","うりばをさがします。","Tôi tìm quầy hàng.","I look for the counter."),
    row("切り替える","きりかえる","N4","v1|vt",
        "chuyển đổi | thay thế | đổi sang | gia hạn",
        "to change | to switch | to change over (to) | to renew",
        "1591780",
        "モードを切り替えます。","モードをきりかえます。","Tôi chuyển đổi chế độ.","I switch the mode."),
    row("環境問題","かんきょうもんだい","N4","n",
        "vấn đề môi trường",
        "environmental problem | environmental issue",
        "1932330",
        "環境問題を考えます。","かんきょうもんだいをかんがえます。","Tôi suy nghĩ về vấn đề môi trường.","I think about environmental problems."),
    row("声をかける","こえをかける","N4","exp|v1",
        "chào hỏi | gọi to | bắt chuyện | mời | liên lạc | cổ vũ",
        "to greet | to call out (to) | to start talking (to) | to invite | to get in touch (with) | to give a shout (to) | to let (someone) know (one is in the area or has time to meet, etc.) | to cheer (on) | to give vocal support (to)",
        "1593080",
        "友達に声をかけます。","ともだちにこえをかけます。","Tôi gọi bạn bè.","I call out to my friend."),
    row("問い合わせ","といあわせ","N4","n",
        "thắc mắc | hỏi thêm thông tin | yêu cầu tư vấn",
        "inquiry | query | enquiry",
        "1598590",
        "問い合わせに答えます。","といあわせにこたえます。","Tôi trả lời thắc mắc.","I answer the inquiry."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
