# -*- coding: utf-8 -*-
"""Build N3 ready wave 066 — 94 freshly-curated N3 objects/tools/materials + counters + route/space nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-066.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("器具","きぐ","n","dụng cụ | thiết bị | đồ dùng","utensil | implement | tool | appliance","1218920"),
    ("用具","ようぐ","n","dụng cụ | đồ nghề | thiết bị","tool | implement | equipment","1546240"),
    ("機材","きざい","n","máy móc và vật tư | thiết bị","machinery and materials | equipment","1220960"),
    ("備品","びひん","n","trang thiết bị | vật dụng | đồ đạc","equipment | fixtures | furnishings | supplies","1485730"),
    ("文房具","ぶんぼうぐ","n","văn phòng phẩm | đồ dùng học tập","stationery","1505620"),
    ("日用品","にちようひん","n","đồ dùng hàng ngày | nhu yếu phẩm","daily necessities | everyday item","1464910"),
    ("雑貨","ざっか","n","tạp hóa | hàng tạp phẩm | đồ lặt vặt","miscellaneous goods | general goods | sundries","1299290"),
    ("刃物","はもの","n","dao kéo | vật sắc | dụng cụ cắt","edged tool | cutting instrument | knife","1369890"),
    ("付属品","ふぞくひん","n","phụ kiện | đồ phụ tùng | đồ kèm theo","accessory | fittings | appurtenances","1496330"),
    ("釘","くぎ","n","đinh | đinh tán | chốt","nail | spike | tack | rivet","1436840"),
    ("針金","はりがね","n","dây thép | dây kim loại","wire","1366250"),
    ("紐","ひも","n","dây | dây buộc | dây đeo","string | cord | leash","1487970"),
    ("縄","なわ","n","dây thừng | dây chão","rope | cord","1459830"),
    ("綱","つな","n","dây thừng to | dây cáp | đường dây","rope | cord | line","1280880"),
    ("鎖","くさり","n","dây xích | xiềng xích","chain | chains","1291730"),
    ("歯車","はぐるま","n","bánh răng | mắt xích (trong tổ chức)","gear | cogwheel | cog","1313350"),
    ("軸","じく","n|n-suf","trục | cán | tâm | điểm mấu chốt","axis | shaft | axle | center | key point","1319180"),
    ("輪","わ","n","vòng | vòng tròn | bánh xe | nhóm (bạn)","ring | circle | loop | wheel","1555710"),
    ("枠","わく","n|n-suf","khung | khuôn khổ | giới hạn | suất | khung giờ","frame | framework | limit | quota | time slot","1562610"),
    ("棒","ぼう","n","cây gậy | thanh | que | gạch (đường kẻ)","pole | rod | stick | bar | line","1519750"),
    ("板","いた","n","tấm ván | tấm (kim loại, kính) | thớt | đầu bếp","board | plank | sheet | cutting board | chef","1481350"),
    ("仕切り","しきり","n","vách ngăn | sự phân chia | quyết toán | điều hành","partition | division | settlement of accounts | managing","1305170"),
    ("管","くだ","n","ống | ống dẫn | suốt chỉ","pipe | tube | bobbin","2868440"),
    ("筒","つつ","n","ống | ống trụ | nòng | súng","pipe | tube | cylinder | gun barrel","1449590"),
    ("缶","かん","n|ctr","lon | hộp thiếc | đồ hộp","can | tin | canned food","1214540"),
    ("瓶","びん","n","chai | lọ | bình","bottle | jar | flagon | vial","1491120"),
    ("樽","たる","n","thùng (gỗ) | thùng tô-nô","cask | barrel","1633680"),
    ("桶","おけ","n","xô | thùng | chậu gỗ","bucket | pail | tub","1182830"),
    ("籠","かご","n","giỏ | rổ | lồng | cũi","basket | hamper | cage","1590200"),
    ("袋","ふくろ","n","túi | bao | bọc","bag | sack | pouch","1411070"),
    ("包み","つつみ","n|ctr","gói | bọc | bưu kiện","bundle | package | parcel","1515340"),
    ("束","たば","n|ctr","bó | nắm | xấp","bundle | bunch | sheaf","1404450"),
    ("塊","かたまり","n","cục | khối | đám | hiện thân (của tính chất)","lump | mass | clump | cluster | embodiment","1590410"),
    ("粒","つぶ","n|ctr","hạt | giọt | viên","grain | bead | drop","1552890"),
    ("欠片","かけら","n","mảnh vỡ | mẩu | chút (sự thật, lương tâm)","fragment | chip | shard | trace | shred","1254090"),
    ("破片","はへん","n","mảnh vỡ | mảnh vụn | miểng","fragment | broken piece | splinter | shard","1471420"),
    ("屑","くず","n","rác | phế liệu | đồ bỏ đi | kẻ cặn bã","waste | scrap | garbage | dregs | loser","1246510"),
    ("粉","こな","n","bột | bụi","flour | meal | powder | dust","1504770"),
    ("灰","はい","n","tro | tàn tro","ash | ashes","1201860"),
    ("泡","あわ","n","bọt | bong bóng | bọt khí","bubble | foam | froth | suds","1517510"),
    ("滴","しずく","n","giọt (nước) | giọt nhỏ","drop (of water) | drip","1437210"),
    ("集まり","あつまり","n","cuộc tụ họp | buổi gặp | sự tập hợp","gathering | meeting | collection","1609050"),
    ("山積み","やまづみ","n|vs","chất đống | chất cao | dồn ứ","huge mound | heap | pile","1755720"),
    ("回数","かいすう","n","số lần | tần số","number of times | frequency | count","1199510"),
    ("部数","ぶすう","n","số bản | số lượng phát hành","number of copies | circulation","1499410"),
    ("枚数","まいすう","n","số tờ | số tấm (vật phẳng)","the number of flat things","1524630"),
    ("戸数","こすう","n","số hộ | số nhà","number of houses | number of households","1267020"),
    ("台数","だいすう","n","số lượng (xe, máy...)","number of large objects (cars, computers)","1412690"),
    ("件数","けんすう","n","số vụ | số trường hợp | số ca","number of cases, items, etc.","1255950"),
    ("個数","こすう","n","số lượng (cái) | số món","number of articles | quantity","1593250"),
    ("冊数","さっすう","n","số cuốn (sách)","number of books","1298550"),
    ("単位","たんい","n|suf","đơn vị | tín chỉ | theo đơn vị","unit | denomination | credit (school) | in units of","1417040"),
    ("倍率","ばいりつ","n","độ phóng đại | tỷ lệ cạnh tranh | bội số","magnification | competitiveness ratio | scaling factor","1473340"),
    ("坪","つぼ","n","tsubo (đơn vị diện tích, ~3,3 m²)","tsubo (unit of land area, approx. 3.3 m²)","1433840"),
    ("密閉","みっぺい","n|vs|vt","đậy kín | làm kín khí | niêm kín","shutting tightly | making airtight | sealing","1528360"),
    ("密封","みっぷう","n|vs|vt","niêm phong | dán kín | gắn kín","sealing hermetically | sealing up","1528350"),
    ("封印","ふういん","n|vs|vt|vi","đóng dấu niêm phong | niêm phong","seal | to seal up | to affix a seal","1499610"),
    ("密集","みっしゅう","n|vs|vi","tụ tập dày đặc | quây quần | san sát","crowding together | clustering | close formation","1528280"),
    ("余白","よはく","n","khoảng trắng | lề | chỗ trống","blank space | margin","1544480"),
    ("空白","くうはく","n|adj-no","khoảng trống | chỗ trống | sự trống rỗng","blank space | void | gap | vacuum","1245950"),
    ("空間","くうかん","n","không gian | khoảng không | bầu không khí","space | room | airspace | atmosphere","1245450"),
    ("空欄","くうらん","n","ô trống | chỗ để trống","blank column | blank space","1246080"),
    ("合間","あいま","n","khoảng nghỉ | lúc rảnh | quãng giữa","interval | break | pause | spare moment","1284670"),
    ("隙","すき","n","khe hở | kẽ hở | lúc sơ hở | điểm yếu | cơ hội","gap | opening | unguarded moment | weak spot | chance","1253780"),
    ("間際","まぎわ","n","ngay trước lúc | sát giờ | bên bờ vực","the point just before | the verge (of) | the eve (of)","1215450"),
    ("寸前","すんぜん","n|n-suf","ngay trước | sát nút | bên bờ","just before | on the verge of | just ahead of","1373750"),
    ("土壇場","どたんば","n","phút chót | giờ phút quyết định | nước cùng","last moment | eleventh hour","1445460"),
    ("瀬戸際","せとぎわ","n","bờ vực | thời khắc quyết định | ranh giới","brink | verge | critical moment","1374380"),
    ("矢先","やさき","n","mũi tên | ngay lúc | đúng lúc (sắp)","arrowhead | the very moment (when)","1634060"),
    ("真っ最中","まっさいちゅう","n","ngay giữa lúc | đang cao trào | đỉnh điểm","right in the middle (of) | midst | height","1363210"),
    ("道中","どうちゅう","n|adv","dọc đường | trên đường đi | suốt hành trình","journey | on the way | during the journey","1770610"),
    ("道のり","みちのり","n","quãng đường | hành trình | chặng đường","distance | journey | path (to a goal) | route","1454110"),
    ("行程","こうてい","n","hành trình | chặng đường | lịch trình | hành trình (piston)","journey | course | itinerary | stroke (of a piston)","1282070"),
    ("航路","こうろ","n","tuyến đường (biển/hàng không) | hải trình","(air or sea) route | course | line","1281440"),
    ("針路","しんろ","n","hướng đi | lộ trình (la bàn)","course | direction","1366280"),
    ("退路","たいろ","n","đường rút lui | lối thoát","path of retreat","1779260"),
    ("帰路","きろ","n","đường về | lúc trở về","return journey | one's way home","1221500"),
    ("往路","おうろ","n","đường đi | lượt đi","outward journey","1179800"),
    ("復路","ふくろ","n|adv","đường về | lượt về | đường hồi","return path | return trip","1500870"),
    ("順路","じゅんろ","n","lộ trình tham quan | đường đi theo chỉ dẫn","(regular) route | suggested route","1609940"),
    ("迂回","うかい","n|vs|vi","đường vòng | đi đường vòng | vu hồi","detour | circumvention | turning movement","1171860"),
    ("回り道","まわりみち","n|vs","đường vòng | đi vòng | lối đi quanh","detour | circuitous route","1199360"),
    ("横道","よこみち","n","đường ngang | đường rẽ | lạc đề","byway | side street | digression","1180960"),
    ("脇道","わきみち","n|adj-no","đường nhánh | đường phụ | lạc đề","side road | byroad | digression","1823640"),
    ("裏道","うらみち","n","đường tắt phía sau | ngõ sau | con đường gian dối","back lane | byway | dishonest means","1550530"),
    ("分かれ道","わかれみち","n","ngã rẽ | đường rẽ nhánh | bước ngoặt","forked road | fork | turning point","1606580"),
    ("枝分かれ","えだわかれ","n|vs|vi","phân nhánh | rẽ nhánh | chia nhánh","ramification | branching off","1861290"),
    ("分岐","ぶんき","n|vs|vi","phân nhánh | rẽ | phân kỳ","divergence | bifurcation | branching off","1503340"),
    ("合流","ごうりゅう","n|vs|vi","hợp lưu | nhập làn | hội quân | gặp nhau","confluence | joining | merging | meeting up","1285390"),
    ("交差","こうさ","n|vs|vi","giao nhau | giao cắt | bắt chéo","crossing | intersection | crossing over","1271970"),
    ("接触","せっしょく","n|vs|vi","tiếp xúc | va chạm | giao tiếp","touch | contact | touching","1385450"),
    ("密着","みっちゃく","n|vs|vi","áp sát | bám sát | gắn chặt | bám chắc","close adhesion | sticking firmly | being glued to","1528300"),
    ("隣接","りんせつ","n|vs|vi","liền kề | giáp ranh | kế cận","adjacency | contiguity | being adjoined","1555870"),
    ("近接","きんせつ","n|vs|vi","cận kề | gần | tiếp cận","proximity | nearness | being adjacent | approaching","1242400"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
