# -*- coding: utf-8 -*-
"""Writes jmdict-n5-vi-ready-007.csv in UTF-8."""
import os

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n5-vi-ready-007.csv"

HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"

LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    s = str(v)
    return '"' + s.replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    # --- rows 1-75 (batch 007 first half) ---
    row("一番","ひとつがい","N5","n","cặp | đôi | bộ đôi","pair | couple | brace","1165980"),
    row("引っ越す","ひっこす","N5","v5s|vi","chuyển nhà | thay chỗ ở","to move (house) | to change residence","1169340",
        "来月引っ越します。","らいげつひっこします。","Tháng sau tôi chuyển nhà.","I am moving next month."),
    row("運転手","うんてんしゅ","N5","n","tài xế | lái xe","driver | chauffeur","1172870",
        "運転手に頼みます。","うんてんしゅにたのみます。","Tôi nhờ tài xế.","I ask the driver."),
    row("確かめる","たしかめる","N5","v1|vt","xác nhận | kiểm tra | chắc chắn | xác thực | kiểm chứng","to make sure | to check | to ascertain | to confirm | to verify","1205780",
        "もう一度確かめます。","もういちどたしかめます。","Tôi xác nhận lại một lần nữa.","I confirm once more."),
    row("感謝","かんしゃ","N5","n|vs|vt|vi","cảm ơn | lòng biết ơn | sự trân trọng | biết ơn","thanks | gratitude | appreciation | thankfulness","1212380",
        "感謝します。","かんしゃします。","Tôi xin cảm ơn.","I am grateful."),
    row("間違える","まちがえる","N5","v1|vt","mắc lỗi | phạm sai lầm | làm sai | nhầm lẫn | nhầm (cái này với cái kia) | lẫn lộn","to make a mistake (in) | to commit an error | to get wrong | to do incorrectly | to mistake (one thing for another) | to confuse","1215330",
        "名前を間違えました。","なまえをまちがえました。","Tôi nhầm tên.","I got the name wrong."),
    row("空","から","N5","n|adj-no|pref","trống rỗng | tình trạng trống | không mang gì | không có gánh nặng | tay không | (hóa đơn, lời hứa) bị từ chối | giả | vắng mặt (đặt chỗ) | giả vờ (vui vẻ, dũng cảm) | lời khen trống rỗng | không thật lòng","emptiness | being empty | not carrying anything | unburdened | empty-handed | dishonoured (bill, promise, etc.) | false | no-show (reservation) | put-on (cheeriness, courage, etc.) | empty (compliments) | insincere","1245280"),
    row("広さ","ひろさ","N5","n","diện tích | phạm vi | kích thước | cỡ | chiều rộng | bề rộng","area | extent | dimensions | size | width | breadth","1278440",
        "部屋の広さはどのくらいですか。","へやのひろさはどのくらいですか。","Diện tích phòng là bao nhiêu?","What is the size of the room?"),
    row("高さ","たかさ","N5","n","chiều cao | độ cao | độ cao so với mặt biển | mức độ | cao độ","height | altitude | elevation | level | altitude | height","1283200",
        "この山の高さは何メートルですか。","このやまのたかさはなんメートルですか。","Ngọn núi này cao bao nhiêu mét?","What is the height of this mountain?"),
    row("始まる","はじまる","N5","v5r|vi","bắt đầu | khởi đầu | khai mạc | xảy ra (lại) | bắt đầu (mới) | bắt nguồn (từ) | khởi nguồn (từ)","to begin | to start | to commence | to happen (again) | to begin (anew) | to date (from) | to originate (in)","1307500",
        "授業が始まります。","じゅぎょうがはじまります。","Buổi học bắt đầu.","Class begins."),
    row("授業料","じゅぎょうりょう","N5","n","học phí | lệ phí khóa học","tuition fee | course fee","1330310"),
    row("週末","しゅうまつ","N5","adv|n","cuối tuần","weekend","1333520",
        "週末は何をしますか。","しゅうまつはなにをしますか。","Cuối tuần bạn làm gì?","What do you do on the weekend?"),
    row("重さ","おもさ","N5","n","trọng lượng","weight","1335760",
        "重さを量ります。","おもさをはかります。","Tôi đo trọng lượng.","I measure the weight."),
    row("笑顔","えがお","N5","n","khuôn mặt tươi cười | nụ cười","smiling face | smile","1351400",
        "笑顔が素敵ですね。","えがおがすてきですね。","Nụ cười đẹp quá.","What a lovely smile."),
    row("上がる","あがる","N5","v5r|vi|vt|suf|exp",
        "lên | đi lên | đến (từ bên ngoài) | lên cao | được nâng lên | vào (từ ngoài vào) | đi vào | đến nơi | vào (trường) | lên lớp | lên bờ (từ nước) | lên bờ | bị sóng đẩy lên bờ | nổi trên mặt nước | nổi lên mặt biển | nổi lên bề mặt | tăng | được tăng (ví dụ lương) | tăng lên | cải thiện | tiến bộ | được thăng chức | tiến lên | được tạo ra | xảy ra | đủ (để trang trải chi phí) | đã xong | đã hoàn thành | đã kết thúc | dừng (mưa) | tạnh (thời tiết) | dừng hoạt động | bị ngắt | hết (năng lượng) | chết | thắng (trong trò chơi bài) | được nói to | được hét lên | lo lắng | run sân khấu | được dâng lên (thần linh) | đi | thăm | ăn | uống | phục vụ (trong nhà chủ) | vào khu đèn đỏ | nổi lên mạnh mẽ | trở nên hứng khởi | ồn ào (đám đông) | hoàn chỉnh | hoàn thành | thêm hàm ý hành động diễn ra mạnh | ở trên | về phía bắc của",
        "to rise | to go up | to come up | to ascend | to be raised | to enter (esp. from outdoors) | to come in | to go in | to enter (a school) | to advance to the next grade | to get out (of water) | to come ashore | to be washed ashore | to float atop the water | to surface from the sea (e.g. of a corpse) | to rise to the surface | to increase | to be raised (e.g. of a salary) | to rise | to improve | to make progress | to be promoted | to advance | to be made (of profit, etc.) | to occur (esp. of a favourable result) | to be adequate (to cover expenses, etc.) | to be finished | to be done | to be over | to stop (of rain) | to clear up (of weather) | to stop (working properly) | to cut out | to give out | to die | to win (in a card game, etc.) | to be spoken loudly | to be raised loudly (of a voice) | to get nervous | to get stage fright | to be offered (to the gods, etc.) | to go | to visit | to eat | to drink | to serve (in one's master's home) | to enter a red light district | to amuse oneself in a red light district | to visit a brothel | to arise vigorously (e.g. of voices in excitement) | to become excited | to be in uproar (e.g. of a crowd) | to be complete | to finish | adds the connotation of an action happening strongly or violently | above | north of",
        "1352290",
        "値段が上がりました。","ねだんがあがりました。","Giá đã tăng.","The price went up."),
    row("水泳","すいえい","N5","n|vs|vi","bơi lội","swimming","1371320",
        "水泳が得意です。","すいえいがとくいです。","Tôi giỏi bơi lội.","I am good at swimming."),
    row("成績","せいせき","N5","n","kết quả | thành tích | điểm số | điểm","results | record | grades | marks","1375760",
        "成績がよかったです。","せいせきがよかったです。","Kết quả tốt.","The grades were good."),
    row("速さ","はやさ","N5","n","tốc độ | vận tốc | nhanh nhẹn | sự mau lẹ | sự sớm","speed | velocity | quickness | rapidity | earliness","1404990"),
    row("昼寝","ひるね","N5","n|vs|vi","ngủ trưa | ngủ buổi chiều | siesta","(afternoon) nap | sleeping during the day | siesta","1426370",
        "昼寝をします。","ひるねをします。","Tôi ngủ trưa.","I take a nap."),
    row("長さ","ながさ","N5","n","chiều dài","length","1429770"),
    row("彼氏","かれし","N5","n|pn","bạn trai | anh ấy | anh ta","boyfriend | he | him","1483140",
        "彼氏がいますか。","かれしがいますか。","Bạn có bạn trai không?","Do you have a boyfriend?"),
    row("比較","ひかく","N5","n|vs|vt","so sánh","comparison","1483560",
        "比較してみます。","ひかくしてみます。","Thử so sánh xem.","I will try comparing."),
    row("方向","ほうこう","N5","n","hướng | phương hướng | phương vị | hướng đi | lộ trình (ví dụ hành động)","direction | orientation | bearing | way | course (e.g. of action)","1516990",
        "方向が違います。","ほうこうがちがいます。","Hướng sai rồi.","The direction is wrong."),
    row("味","あじ","N5","n|adj-na","hương vị | vị | khẩu vị | sức hút | sức quyến rũ | sự độc đáo | sự hấp dẫn | kinh nghiệm | mùi vị (ví dụ của chiến thắng) | thông minh | lanh lợi | hóm hỉnh | kỳ lạ | aji | vị thế có tiềm năng khai thác sau này (cờ vây)","flavor | flavour | taste | charm | appeal | uniqueness | attractiveness | experience | taste (e.g. of victory) | smart | clever | witty | strange | aji | position that has some lingering potential that may be exploited later in the game","1526960",
        "この料理の味はどうですか。","このりょうりのあじはどうですか。","Món này có vị thế nào?","How does this dish taste?"),
    row("鳴く","なく","N5","v5k|vi","kêu (của động vật) | gọi | khóc | rên | hót | kêu chiêm chiếp | gọi bài (ví dụ pung, kong trong mạt chược)","to make sound (of an animal) | to call | to cry | to whine | to sing | to chirp | to make a meld call (e.g. pung, kong)","1532870",
        "鳥が鳴いています。","とりがないています。","Con chim đang hót.","The bird is singing."),
    row("料金","りょうきん","N5","n","phí | lệ phí | giá vé","fee | charge | fare","1554280",
        "料金はいくらですか。","りょうきんはいくらですか。","Phí là bao nhiêu?","How much is the fee?"),
    row("冷やす","ひやす","N5","v5s|vt","làm lạnh | ướp lạnh | để lạnh | bình tĩnh lại | nguội lại | lấy lại bình tĩnh | thư giãn | sợ hãi (vì) | bị dọa (bởi)","to cool | to chill | to refrigerate | to calm down | to cool off | to regain one's composure | to relax | to be frightened (at) | to be scared (of)","1556770",
        "ビールを冷やします。","ビールをひやします。","Tôi ướp lạnh bia.","I chill the beer."),
    row("丈夫","じょうふ","N5","n","anh hùng | người đàn ông dũng cảm | chiến binh","hero | manly person | warrior","1580485"),
    row("例","れい","N5","n","ví dụ | minh họa | trường hợp | tiền lệ | tập quán | thói quen | thông lệ | cách dùng","example | instance | illustration | case | precedent | custom | habit | practice | usage","1585230",
        "例えばどんな問題ですか。","たとえばどんなもんだいですか。","Ví dụ như vấn đề gì?","For example, what kind of problem?"),
    row("山","さん","N5","suf","núi | ngọn núi | chùa","Mt. | Mount | temple","2085690"),
    row("八","パー","N5","num","tám","eight","2748000"),
    row("九","チュー","N5","num","chín","nine","2748010"),
    row("十","シー","N5","num","mười","ten","2748020"),
    row("朝","あした","N5","n","buổi sáng","morning","2857350"),
    row("ネクタイ","ネクタイ","N5","n","cà vạt | cravat","tie | necktie","1092820",
        "ネクタイを締めます。","ネクタイをしめます。","Tôi thắt cà vạt.","I tie a necktie."),
    row("バイク","バイク","N5","n","xe máy | xe mô-tô | xe đạp","motorcycle | motorbike | bike | bicycle","1097810",
        "バイクで行きます。","バイクでいきます。","Tôi đi xe máy.","I go by motorcycle."),
    row("プログラム","プログラム","N5","n|vs|vt","chương trình (sự kiện, âm nhạc) | chương trình | tập sách chương trình | tờ rơi | tờ brochure | chương trình (máy tính) | lập trình","program (of events, music, etc.) | programme | program (booklet) | brochure | pamphlet | (computer) program | programming","1117080"),
    row("マナー","マナー","N5","n","phép lịch sự | nghi thức | ứng xử","manners | etiquette | polite behaviour","1128740",
        "マナーを守ります。","マナーをまもります。","Tôi giữ phép lịch sự.","I follow manners."),
    row("メンバー","メンバー","N5","n","thành viên | người tham gia | người dự | đội hình (thể thao)","member | participant | attendee | lineup (sport)","1134370"),
    row("ルール","ルール","N5","n","quy tắc","rule","1143920",
        "ルールを守ってください。","ルールをまもってください。","Hãy tuân theo quy tắc.","Please follow the rules."),
    row("安心","あんしん","N5","n|adj-na|vs|vi","sự an tâm | sự nhẹ nhõm | cảm giác an toàn | sự bình yên | sự đảm bảo | sự tin tưởng","peace of mind | relief | (sense of) security | safety | assurance | confidence","1153890",
        "安心してください。","あんしんしてください。","Hãy yên tâm.","Please rest assured."),
    row("彼","あれ","N5","pn|n","cái đó | thứ đó | người đó | lúc đó | thời điểm đó | chỗ đó (ở đằng kia) | chỗ dưới đó (bộ phận sinh dục) | kỳ kinh | kinh nguyệt","that | that thing | that person | then | that time | that place (over there) | down there (i.e. one's genitals) | period | menses","1000580"),
    row("点","ちょぼ","N5","n","chấm | điểm | dấu | nhạc công gidayū","dot | point | mark | gidayū musicians","1007860"),
    row("アニメ","アニメ","N5","n","hoạt hình | phim hoạt hình | phim hoạt hình (anime)","animation | animated film | animated cartoon | anime","1017590",
        "アニメが好きです。","アニメがすきです。","Tôi thích hoạt hình.","I like anime."),
    row("グループ","グループ","N5","n","nhóm (thường là người)","group (usu. of people)","1047300",
        "グループで話し合います。","グループではなしあいます。","Chúng tôi thảo luận theo nhóm.","We discuss in groups."),
    row("コンサート","コンサート","N5","n","buổi hòa nhạc","concert","1051970",
        "コンサートに行きます。","コンサートにいきます。","Tôi đến buổi hòa nhạc.","I go to a concert."),
    row("ゴルフ","ゴルフ","N5","n","golf","golf","1054620"),
    row("サッカー","サッカー","N5","n","bóng đá | bóng đá (liên đoàn)","soccer | (association) football","1056700",
        "サッカーが好きです。","サッカーがすきです。","Tôi thích bóng đá.","I like soccer."),
    row("サラダ","サラダ","N5","n","salad","salad","1057850"),
    row("シャツ","シャツ","N5","n","áo may-ô | áo lót | áo sơ mi (mặc ngoài)","shirt (undergarment) | undershirt | singlet | shirt (outerwear; usu. with collar and buttons)","1061520",
        "シャツを着ます。","シャツをきます。","Tôi mặc áo sơ mi.","I wear a shirt."),
    row("意見","いけん","N5","n|vs|vt|vi","ý kiến | quan điểm | nhận xét | mắng | khiển trách | chỉ trích | lời khuyên | cảnh báo | nhắc nhở","opinion | view | comment | scolding | reprimand | rebuke | admonition | cautioning | warning","1156530",
        "意見を聞かせてください。","いけんをきかせてください。","Hãy cho tôi nghe ý kiến của bạn.","Please share your opinion."),
    row("育つ","そだつ","N5","v5t|vi","được nuôi dưỡng | được lớn lên | trưởng thành","to be raised (e.g. child) | to be brought up | to grow (up)","1160540",
        "子供が育ちました。","こどもがそだちました。","Đứa trẻ đã lớn lên.","The child grew up."),
    row("育てる","そだてる","N5","v1|vt","nuôi dưỡng | chăm sóc | dạy dỗ | đào tạo | giáo dục | thúc đẩy sự tăng trưởng | bồi dưỡng | phát triển","to raise | to rear | to bring up | to train | to teach | to educate | to promote the growth of | to nurture | to foster | to develop","1160570",
        "子供を育てます。","こどもをそだてます。","Tôi nuôi dạy con.","I raise children."),
    row("一週間","いっしゅうかん","N5","n","một tuần","one week","1163270",
        "一週間後に会いましょう。","いっしゅうかんごにあいましょう。","Hẹn gặp sau một tuần.","Let's meet in one week."),
    row("一緒","いっしょ","N5","n|adj-no","cùng nhau | một mớ | cùng loại | giống nhau | như nhau | đồng thời","(doing) together | one lump | one mixture | the same category | the same | identical | (at) the same time","1163400",
        "一緒に行きましょう。","いっしょにいきましょう。","Hãy cùng đi.","Let's go together."),
    row("一年間","いちねんかん","N5","n","một năm (khoảng thời gian)","(period of) one year","1165570"),
    row("隠れる","かくれる","N5","v1|vi","ẩn | che giấu bản thân | trốn | biến mất (sau) | bị ẩn (bởi) | bị che phủ | khuất khỏi tầm nhìn | sống ẩn dật | nghỉ hưu (khỏi thế giới) | không được biết đến (ví dụ tài năng) | chưa được khám phá | bị ẩn (ý nghĩa) | qua đời (người có địa vị cao)","to hide | to conceal oneself | to take cover | to disappear (behind) | to be hidden (by) | to be covered | to go out of sight | to live in seclusion | to retire (from the world) | to be unknown (e.g. of a talent) | to be undiscovered | to be hidden (e.g. of a meaning) | to pass away (of a person of high position)","1170660",
        "隠れてください。","かくれてください。","Hãy trốn đi.","Please hide."),
    row("宇宙","うちゅう","N5","n","vũ trụ | không gian","universe | cosmos | space","1171300",
        "宇宙が好きです。","うちゅうがすきです。","Tôi thích vũ trụ.","I like space."),
    row("運ぶ","はこぶ","N5","v5b|vt|vi","mang | vận chuyển | di chuyển | chuyển tải | đến | đi | dùng (bút, đũa) | thực hiện | tiến hành | thu xếp | tiến triển | đi (tốt)","to carry | to transport | to move | to convey | to come | to go | to use (a brush, chopsticks, etc.) | to move | to carry out | to proceed with | to arrange | to go (well, etc.) | to proceed | to progress","1172660",
        "荷物を運びます。","にもつをはこびます。","Tôi mang hành lý.","I carry the luggage."),
    row("運動会","うんどうかい","N5","n","hội thao trường | ngày thể thao | hội thao ngoài trời | lễ hội thể thao","athletic meet (esp. at a school) | sports day | field day | sports festival","1172940",
        "来週運動会があります。","らいしゅううんどうかいがあります。","Tuần sau có hội thao.","There is a sports day next week."),
    row("下がる","さがる","N5","v5r|vi","xuống | đi xuống | rơi | giảm | chìm | thấp hơn | treo | lơ lửng | lùi lại | lùi bước | rút lui | nghỉ hưu | xấu đi | giảm (chất lượng) | bị hạ cấp | gần với hiện tại hơn | đánh sagari (nhạc) | kéo dài xuống dưới","to come down | to go down | to fall | to drop | to sink | to get lower | to hang | to dangle | to move back | to step back | to withdraw | to retire | to deteriorate | to fall off | to be downgraded | to get closer to the present day | to play a sagari | to extend downwards","1184160",
        "温度が下がりました。","おんどがさがりました。","Nhiệt độ đã giảm.","The temperature dropped."),
    row("課長","かちょう","N5","n","trưởng phòng | trưởng ban","section manager | section chief","1195840",
        "課長に報告します。","かちょうにほうこくします。","Tôi báo cáo với trưởng phòng.","I report to the section manager."),
    row("灰色","はいいろ","N5","n|adj-no","xám | màu xám | tro","grey | gray | ashen","1201970"),
    row("階段","かいだん","N5","n","cầu thang | thang bộ | bậc thang","stairs | stairway | staircase","1203090",
        "階段を上ります。","かいだんをのぼります。","Tôi leo cầu thang.","I climb the stairs."),
    row("楽","らく","N5","n|adj-na","thoải mái | dễ chịu | nhẹ nhõm | bình yên | thư giãn | dễ | đơn giản | không vất vả | không khó khăn | (kinh tế) dư dả | gốm raku | sukha (hạnh phúc)","comfort | ease | relief | (at) peace | relaxation | easy | simple | without trouble | without hardships | (economically) comfortable | raku pottery | sukha (happiness)","1207230",
        "楽な仕事ですね。","らくなしごとですね。","Công việc thoải mái nhỉ.","What an easy job."),
    row("感情","かんじょう","N5","n|adj-no","cảm xúc | tình cảm | cảm giác","emotion | feeling | feelings | sentiment","1212410",
        "感情を大切にします。","かんじょうをたいせつにします。","Tôi trân trọng cảm xúc.","I value emotions."),
    row("汗","あせ","N5","n|int","mồ hôi | sự đổ mồ hôi | ẩm ướt | hơi nước | ồ | ối","sweat | perspiration | moisture | condensation | gulp | oops","1213060",
        "汗をかきます。","あせをかきます。","Tôi đổ mồ hôi.","I sweat."),
    row("観光","かんこう","N5","n|vs|vt","tham quan | du lịch","sightseeing | tourism","1214840",
        "観光に行きます。","かんこうにいきます。","Tôi đi tham quan.","I go sightseeing."),
    row("記憶","きおく","N5","n|vs|vt","ký ức | hồi ức | sự nhớ | trí nhớ | bộ nhớ","memory | recollection | remembrance | memory | storage","1223150",
        "記憶が薄れます。","きおくがうすれます。","Ký ức dần mờ phai.","Memories fade."),
    row("記念","きねん","N5","n|vs|vt","kỷ niệm | lễ kỷ niệm | sự nhớ | ký ức | tưởng niệm | vật kỷ niệm | quà lưu niệm","commemoration | celebration | remembrance | memory | honoring the memory of | memento | souvenir | keepsake","1223340",
        "記念写真を撮ります。","きねんしゃしんをとります。","Tôi chụp ảnh kỷ niệm.","I take a commemorative photo."),
    row("許す","ゆるす","N5","v5s|vt","cho phép | chấp thuận | đồng ý | tha thứ | xin lỗi | miễn | ngoại lệ | tha | phóng thích | thừa nhận | tin tưởng | hạ thủ | nhường (điểm trong trận đấu, khoảng cách)","to permit | to allow | to approve | to consent to | to forgive | to pardon | to excuse | to tolerate | to exempt (someone) from | to remit | to release | to let off | to acknowledge | to admit | to trust | to confide in | to let one's guard down | to give up (points in a game, distance in a race, etc.) | to yield","1232870",
        "ゆるしてください。","ゆるしてください。","Xin hãy tha thứ.","Please forgive me."),
    row("競争","きょうそう","N5","n|vs|vt|vi","cạnh tranh | cuộc thi | sự đối địch | cuộc đua | cạnh tranh (giữa sinh vật hoặc loài)","competition | contest | rivalry | race | competition (between organisms or species)","1234140",
        "競争に勝ちました。","きょうそうにかちました。","Tôi thắng cuộc thi.","I won the competition."),
    row("曲がる","まがる","N5","v5r|vi","cong | vẹo | bị cong | uốn | vặn | quẹo | lệch | không thẳng","to bend | to curve | to warp | to wind | to twist | to turn | to be awry | to be askew | to be crooked","1239730",
        "右に曲がります。","みぎにまがります。","Tôi rẽ phải.","I turn right."),
    row("曲げる","まげる","N5","v1|vt","uốn cong | bẻ cong | nghiêng | cong xuống | cong | nghiêng sang | xiên | bóp méo (sự thật) | bóp méo | bẻ quẹo | từ bỏ (một nguyên tắc) | phớt lờ (ý kiến thật) | cầm cố","to bend | to crook | to bow | to curve | to curl | to lean | to tilt | to incline | to slant | to bend (the truth) | to distort | to twist | to pervert | to yield (a point) | to depart (from a principle) | to ignore (what one really thinks) | to pawn","1239740"),
    row("近所","きんじょ","N5","n|adj-no","xóm giềng | hàng xóm | vùng lân cận","neighbourhood | neighborhood | vicinity","1242350",
        "近所に公園があります。","きんじょにこうえんがあります。","Gần đây có công viên.","There is a park nearby."),

    # --- rows 76-150 ---
    row("苦手","にがて","N5","adj-na|n","kém (ở) | yếu (trong) | không giỏi lắm | không phải sở thích | không phải điều ưa thích","poor (at) | weak (in) | not very good (at) | not one's cup of tea | not one's favorite","1244470",
        "数学が苦手です。","すうがくがにがてです。","Tôi kém toán.","I am bad at math."),
    row("交番","こうばん","N5","n|adj-f","đồn cảnh sát nhỏ | koban | đồn cảnh sát khu phố | luân phiên | dòng điện xoay chiều","police box | koban | small neighborhood police station | alternation | alternating (current, stress, etc.)","1272500",
        "交番で聞きます。","こうばんできます。","Tôi hỏi tại đồn cảnh sát.","I ask at the police box."),
    row("厚い","あつい","N5","adj-i","dày | đậm | nặng | tốt bụng | nồng hậu | hiếu khách | ân cần | trung thành | nghiêm trọng (bệnh) | phong phú","thick | deep | heavy | kind | cordial | hospitable | warm | faithful | serious (of an illness) | abundant","1275320",
        "厚い本ですね。","あついほんですね。","Quyển sách dày nhỉ.","What a thick book."),
    row("校長","こうちょう","N5","n","hiệu trưởng | thầy hiệu trưởng | cô hiệu trưởng","principal | head teacher | headmaster | headmistress","1279590",
        "校長先生が話します。","こうちょうせんせいがはなします。","Thầy hiệu trưởng phát biểu.","The principal speaks."),
    row("考え","かんがえ","N5","n","suy nghĩ | tư tưởng | quan điểm | ý kiến | khái niệm | ý tưởng | tưởng tượng | ý định | kế hoạch | thiết kế | cân nhắc | phán xét | suy xét | sự phản ánh | ước muốn | hy vọng | kỳ vọng","thinking | thought | view | opinion | concept | idea | notion | imagination | intention | plan | design | consideration | judgement | deliberation | reflection | wish | hope | expectation","1281000",
        "考えがあります。","かんがえがあります。","Tôi có ý tưởng.","I have an idea."),
    row("指す","さす","N5","v5s|vt","chỉ vào | đề cử | chọn | xác định (người) | chỉ định | chỉ ra | tượng trưng | chơi (cờ shogi) | di chuyển (quân cờ) | duỗi thẳng tay (trong múa)","to point | to nominate | to select someone | to specify some person | to identify | to indicate | to point out | to play (a game of shogi) | to move (a piece) | to extend one's arm straight ahead (in dance)","1309670",
        "地図で指します。","ちずでさします。","Tôi chỉ trên bản đồ.","I point on the map."),
    row("社長","しゃちょう","N5","n","giám đốc công ty | giám đốc | tổng giám đốc","company president | manager | director","1322920",
        "社長に報告します。","しゃちょうにほうこくします。","Tôi báo cáo với giám đốc.","I report to the president."),
    row("考える","かんがえる","N5","v1|vt","suy nghĩ (về) | nghĩ lại | cân nhắc | suy ngẫm | phản ánh (về) | thiền định (về) | xem xét | ghi nhớ | tính đến | tính đến (khi cân nhắc) | nghĩ (rằng) | tin | giữ (quan điểm) | phán xét | kết luận | nghi ngờ | có ý định (làm) | nghĩ đến (việc làm) | lên kế hoạch | dự đoán | kỳ vọng | mong đợi | tưởng tượng | nảy ra | nghĩ ra | mưu tính | nghĩ ra cách | coi (là) | xem (là) | nhìn (là) | cho rằng | xem như","to think (about, of) | to think over | to ponder | to contemplate | to reflect (on) | to meditate (on) | to consider | to bear in mind | to allow for | to take into consideration | to think (that) | to believe | to hold (a view) | to judge | to conclude | to suspect | to intend (to do) | to think of (doing) | to plan | to predict | to anticipate | to expect | to imagine | to come up with | to think up | to contrive | to devise | to consider (as) | to regard (as) | to look on (as) | to take | to view","1281020",
        "よく考えます。","よくかんがえます。","Tôi suy nghĩ kỹ.","I think carefully."),
    row("合う","あう","N5","v5u|vi|aux-v","gặp nhau | hội tụ | hợp nhất | gặp | phù hợp | khớp | vừa vặn | đồng ý | đúng | có lợi | công bằng | làm ... với nhau | làm ... cùng nhau","to come together | to merge | to unite | to meet | to fit | to match | to suit | to agree with | to be correct | to be profitable | to be equitable | to do ... to each other | to do ... together","1284430",
        "サイズが合いません。","サイズがあいません。","Size không vừa.","The size doesn't fit."),
    row("合わせる","あわせる","N5","v1|vt","khớp (nhịp điệu, tốc độ) | kết hợp | hợp nhất | tổng hợp | cộng | đối mặt | đứng đối diện | so sánh | kiểm tra | khiến gặp nhau | đặt cùng nhau | kết nối | chồng lên | pha trộn | kết hợp | đặt lưỡi kiếm chạm nhau | chiến đấu","to match (rhythm, speed, etc.) | to join together | to unite | to combine | to add up | to face | to be opposite (someone) | to compare | to check with | to cause to meet (e.g. an unpleasant fate) | to place together | to connect | to overlap | to mix | to combine | to put blade to blade | to fight","1284480",
        "音楽に合わせて踊ります。","おんがくにあわせておどります。","Tôi nhảy theo nhạc.","I dance to the music."),
    row("指","ゆび","N5","n","ngón tay | ngón chân | ngón","finger | toe | digit","1309650",
        "指を切りました。","ゆびをきりました。","Tôi cắt tay.","I cut my finger."),
    row("謝る","あやまる","N5","v5r|vt|vi","xin lỗi | từ chối | không chịu được | bị đánh bại (bởi) | bối rối | không biết làm gì","to apologize (apologise) | to refuse | to decline | to be unable to bear | to be defeated (by) | to be at a loss | to be stumped (by)","1323010",
        "すみませんと謝ります。","すみませんとあやまります。","Tôi xin lỗi.","I apologize."),
    row("手伝う","てつだう","N5","v5u|vt","giúp | hỗ trợ | trợ giúp | đóng góp | là nguyên nhân của","to help | to assist | to aid | to contribute to | to be a factor in","1328190",
        "手伝ってください。","てつだってください。","Xin hãy giúp tôi.","Please help me."),
    row("臭い","くさい","N5","adj-i|suf","hôi | có mùi | đáng nghi | khả nghi | diễn quá đà | cường điệu | thô thiển | vụng về | kém kỹ năng | (quá) có mùi | có hương vị mạnh | mùi như | trông như | có vẻ như | giống như | -ish","stinking | smelly | suspicious | fishy | hammy (acting) | over-the-top | cheesy | clumsy | unskilled | (overly) gamey | strong-tasting | smelling of | looking like | appearing like | smacking of | -ish","1333150"),
    row("重要","じゅうよう","N5","adj-na","quan trọng | thiết yếu | đáng kể | chính | then chốt | cốt lõi","important | essential | significant | major | key | principal","1336820",
        "重要な問題です。","じゅうようなもんだいです。","Đây là vấn đề quan trọng.","This is an important issue."),
    row("祝日","しゅくじつ","N5","n|adj-no","ngày lễ quốc gia | ngày nghỉ lễ","national holiday | public holiday","1337500",
        "明日は祝日です。","あしたはしゅくじつです。","Ngày mai là ngày lễ.","Tomorrow is a national holiday."),
    row("春休み","はるやすみ","N5","n","kỳ nghỉ xuân | nghỉ hè xuân","spring break | spring vacation","1341080",
        "春休みはいつですか。","はるやすみはいつですか。","Kỳ nghỉ xuân là khi nào?","When is spring break?"),
    row("助ける","たすける","N5","v1|vt","cứu | giải cứu | tha | giúp đỡ | hỗ trợ | hỗ trợ tài chính | đóng góp | cung cấp viện trợ | tạo điều kiện | kích thích | thúc đẩy | đóng góp vào","to save | to rescue | to spare | to help | to assist | to support (financially) | to contribute (to) | to provide aid | to facilitate | to stimulate | to promote | to contribute to","1344410",
        "助けてください！","たすけてください！","Hãy giúp tôi!","Please help me!"),
    row("消防士","しょうぼうし","N5","n","lính cứu hỏa | lính chữa cháy","firefighter | fireman","1350350"),
    row("新幹線","しんかんせん","N5","n","tàu Shinkansen | tàu cao tốc","Shinkansen | bullet train","1361590",
        "新幹線に乗ります。","しんかんせんにのります。","Tôi đi tàu cao tốc.","I ride the Shinkansen."),
    row("深さ","ふかさ","N5","n","độ sâu | chiều sâu","depth | profundity","1362650"),
    row("親","おや","N5","n|adj-no","bố mẹ | cha mẹ | cha và mẹ | cái (trong trò chơi) | nhà cái | người sáng lập | người sáng chế | chủ nhân (thú cưng) | chính | tổ chức mẹ | chính yếu | tổ tiên | tiền nhân","parent | parents | mother and father | dealer | banker | founder | inventor | (pet) owner | key | parent (organization) | main | ancestor | forefather","1365040",
        "親に感謝します。","おやにかんしゃします。","Tôi cảm ơn bố mẹ.","I am grateful to my parents."),
    row("辛い","つらい","N5","adj-i","đau | cay đắng | đau lòng | khó (về mặt cảm xúc) | gian khổ | khó khăn | khắc nghiệt | tàn nhẫn | lạnh lùng","painful | bitter | heart-breaking | difficult (emotionally) | tough | difficult | hard (usu. of situations) | cruel | harsh | cold","1365860",
        "辛い仕事ですね。","つらいしごとですね。","Công việc vất vả nhỉ.","What a tough job."),
    row("数える","かぞえる","N5","v1|vt","đếm | liệt kê","to count | to enumerate","1372900",
        "一から数えます。","いちからかぞえます。","Tôi đếm từ một.","I count from one."),
    row("数学","すうがく","N5","n","toán học","mathematics","1372980",
        "数学が好きです。","すうがくがすきです。","Tôi thích toán học.","I like mathematics."),
    row("晴れ","はれ","N5","n|adj-no","thời tiết đẹp | nắng | chính thức | nghi lễ | công khai | đã xóa bỏ nghi ngờ","clear weather | fine weather | formal | ceremonial | public | cleared of suspicion","1376460",
        "今日は晴れですね。","きょうははれですね。","Hôm nay trời đẹp nhỉ.","It's fine weather today."),
    row("切符","きっぷ","N5","n","vé","ticket","1385170",
        "切符を買います。","きっぷをかいます。","Tôi mua vé.","I buy a ticket."),
    row("息子","むすこ","N5","n","con trai | dương vật","son | penis","1404390",
        "息子が生まれました。","むすこがうまれました。","Con trai tôi đã chào đời.","My son was born."),
    row("体育","たいいく","N5","n","thể dục | thể dục thể thao | giờ thể dục","physical education | PE | gym (class)","1409200",
        "体育の授業があります。","たいいくのじゅぎょうがあります。","Có giờ thể dục.","There is a PE class."),
    row("態度","たいど","N5","n","thái độ | cách cư xử | hành vi | dáng dấp | tư thế | lập trường | quan điểm","attitude | manner | behaviour | demeanour | bearing | position | stance | stand","1410780",
        "態度が大切です。","たいどがたいせつです。","Thái độ rất quan trọng.","Attitude is important."),
    row("大事","だいじ","N5","adj-na|n","quan trọng | nghiêm trọng | thiết yếu | quý giá | đáng trân trọng | chuyện nghiêm trọng | sự kiện lớn | việc đáng lo ngại | khủng hoảng | sự nghiệp lớn | điều tuyệt vời | an toàn | OK","important | serious | crucial | valuable | precious | serious matter | major incident | matter of grave concern | crisis | great undertaking | great enterprise | great thing | safe | OK","1413940",
        "大事にしてください。","だいじにしてください。","Hãy giữ gìn cẩn thận.","Please take good care of it."),
    row("大人しい","おとなしい","N5","adj-i","hiền lành | yên lặng | nhẹ nhàng | ngoan ngoãn | tuân thủ | ngoan | đã được thuần hóa | nhẹ nhàng (màu sắc) | giản dị","gentle | quiet | mild | meek | obedient | docile | well-behaved | tame | quiet (color, pattern, etc.) | sober","1414190",
        "大人しい子ですね。","おとなしいこですね。","Đứa trẻ ngoan nhỉ.","What a well-behaved child."),
    row("注意","ちゅうい","N5","n|vs|vi|vt","chú ý | sự chú ý | thận trọng | cảnh giác | phòng tránh | để ý | coi chừng | lời khuyên | cảnh báo | nhắc nhở | khiển trách | mắng","attention | notice | heed | care | caution | precaution | looking out (for) | watching out (for) | advice | warning | caution | reminder | admonishment | reprimand | telling-off","1426530",
        "注意してください。","ちゅういしてください。","Hãy cẩn thận.","Please be careful."),
    row("挑戦","ちょうせん","N5","n|vs|vi","thách thức | chống đối | dám | thử thách | cố gắng","challenge | defiance | dare | attempt | try","1428240",
        "挑戦します！","ちょうせんします！","Tôi sẽ thử thách!","I will take on the challenge!"),
    row("眺める","ながめる","N5","v1|vt","nhìn | ngắm | xem | nhìn chằm chằm | nhìn ra (cảnh vật) | ngắm nhìn | chiêm ngưỡng | đứng bên cạnh quan sát | đứng xem | quan sát","to look at | to gaze at | to watch | to stare at | to look out over | to get a view of | to admire (e.g. the scenery) | to look on (from the sidelines) | to stand by and watch | to observe","1428830",
        "海を眺めます。","うみをながめます。","Tôi ngắm biển.","I gaze at the sea."),
    row("飛ぶ","とぶ","N5","v5b|vi","bay | lướt | nhảy | bật nhảy | bật | nhảy xa | nhảy nhỏ | bắn tung | rải rác | bắn tóe | bay (ví dụ tia lửa) | vội vã | lao đi | chạy trốn | chạy mất | thoát | biến mất | mất hút | mờ dần | loãng dần | đứt | rời ra | rơi ra | nổ (cầu chì) | được gửi đi (lệnh) | bay (tin đồn) | bay đến (ví dụ đấm, đá) | thiếu (trang, mũi khâu) | bỏ qua | nhảy (ví dụ câu chuyện)","to fly | to soar | to jump | to leap | to spring | to bound | to hop | to spatter | to scatter | to splash | to fly (e.g. of sparks) | to hurry | to rush | to flee | to run off | to escape | to disappear | to vanish | to fade | to thin out | to break off | to come off | to fall off | to blow (of a fuse) | to be sent out (of an order) | to fly (of false rumours, catcalls, etc.) | to come flying (of a punch, kick, etc.) | to be missing (of a page, stitch, etc.) | to skip | to jump (e.g. of a conversation)","1429700",
        "鳥が飛びます。","とりがとびます。","Con chim bay.","The bird flies."),
    row("発音","はつおん","N5","n|vs|vt","phát âm | tạo ra âm thanh","pronunciation | production of sound","1477170",
        "発音を練習します。","はつおんをれんしゅうします。","Tôi luyện phát âm.","I practice pronunciation."),
    row("半分","はんぷん","N5","n","nửa phút","half minute","1479900"),
    row("同僚","どうりょう","N5","n","đồng nghiệp | bạn làm","coworker | co-worker | colleague | associate","1453580",
        "同僚と話します。","どうりょうとはなします。","Tôi nói chuyện với đồng nghiệp.","I talk with my colleague."),
    row("得意","とくい","N5","n|adj-na|adj-no","sự hài lòng | niềm tự hào | chiến thắng | phấn khởi | điểm mạnh | sở trường | chuyên môn | khách hàng thường xuyên | khách quen","satisfaction | pride | triumph | elation | one's strong point | one's forte | one's specialty | regular customer | regular client | patron","1454510",
        "得意な教科は何ですか。","とくいなきょうかはなんですか。","Môn học sở trường của bạn là gì?","What subject are you good at?"),
    row("内容","ないよう","N5","n","nội dung | chủ đề | thực chất | vấn đề | chi tiết | ý nghĩa","contents | content | substance | matter | detail | import","1459400",
        "内容を確認します。","ないようをかくにんします。","Tôi xác nhận nội dung.","I confirm the content."),
    row("濃い","こい","N5","adj-i","đậm (màu sắc) | tối | đậm đà (hương vị, mùi) | đặc (độ sánh) | dày đặc | mạnh (khả năng) | thân thiết | gần gũi | sâu đậm (tình yêu)","deep (colour) | dark | strong (flavour, smell, etc.) | thick (consistency) | dense | strong (possibility, etc.) | thick (close) | close | deep (love, etc.)","1469890",
        "コーヒーが濃いです。","コーヒーがこいです。","Cà phê đặc quá.","The coffee is strong."),
    row("馬","うま","N5","n","ngựa | đua ngựa | tượng chủ (cờ shogi thăng cấp) | quân kỵ sĩ (bài karuta)","horse | horse racing | promoted bishop | knight (court card in mekuri karuta and unsun karuta)","1471560",
        "馬に乗ります。","うまにのります。","Tôi cưỡi ngựa.","I ride a horse."),
    row("泊まる","とまる","N5","v5r|vi","ở lại (ví dụ khách sạn) | neo đậu | cập bến | cắm neo","to stay at (e.g. hotel) | to be docked | to be berthed | to be moored","1474850",
        "ホテルに泊まります。","ホテルにとまります。","Tôi ở lại khách sạn.","I stay at a hotel."),
    row("薄い","うすい","N5","adj-i","mỏng | nhạt | nhạt màu | mờ | lỏng | pha loãng | yếu (vị) | ít (tình cảm) | không nhiều (sự hiện diện) | ít (khả năng) | nhỏ | thưa | rải rác | loang lổ","thin (of an object) | pale | light | faint | watery | thin | diluted | weak (taste, etc.) | little (affection, etc.) | not much (of a presence) | slim (probability, etc.) | small | sparse | patchy | scattered","1475480",
        "この本は薄いですね。","このほんはうすいですね。","Quyển sách này mỏng nhỉ.","This book is thin."),
    row("美しい","うつくしい","N5","adj-i","đẹp | xinh | duyên dáng | ngọt ngào | trong sáng (lòng dạ, tình bạn)","beautiful | pretty | lovely | sweet | pure (heart, friendship, etc.)","1486360",
        "美しい景色ですね。","うつくしいけしきですね。","Cảnh đẹp quá.","What a beautiful scenery."),
    row("負け","まけ","N5","n|suf","thua | thất bại | thất bại (trong trận đấu) | không xứng (với tên, ngoại hình) | giảm giá | lỗ (trong bán hàng)","defeat | loss | losing (a game) | failing to live up to (one's name, looks, etc.) | discount | loss (on a sale)","1497960",
        "今日は負けました。","きょうはまけました。","Hôm nay tôi thua.","I lost today."),
    row("風","ふう","N5","n|suf","cách | kiểu | phong cách | vẻ | không khí | giống như | tập quán | thông lệ | thực hành | dân ca (thể loại Kinh Thi) | gió (một trong ngũ hành) | -ish | giống | trông như","manner | way | style | appearance | air | likeness | custom | convention | practice | folk song (genre of the Shi Jing) | wind (one of the five elements) | -ish | resembling | -looking","1499730"),
    row("文法","ぶんぽう","N5","n","ngữ pháp","grammar","1505600",
        "文法を勉強します。","ぶんぽうをべんきょうします。","Tôi học ngữ pháp.","I study grammar."),
    row("片付ける","かたづける","N5","v1|vt","dọn dẹp | sắp xếp | thu dọn | cất đi | giải quyết (vấn đề) | xử lý | hoàn thành | kết thúc | làm xong | gả (con gái) | giết (ai đó) | thủ tiêu","to put in order | to tidy up | to clean up | to put away | to clear away | to settle (a matter) | to solve | to deal with | to dispose of | to finish | to get through | to complete | to get (something) done | to marry off (one's daughter) | to do away with (someone) | to bump off | to kill | to eliminate","1511790",
        "部屋を片付けます。","へやをかたづけます。","Tôi dọn dẹp phòng.","I tidy up the room."),
    row("冒険","ぼうけん","N5","n|vs|vi|adj-na","phiêu lưu | mạo hiểm | việc mạo hiểm khó thành | cố gắng liều | nguy hiểm | rủi ro","adventure | venture | venture which is unlikely to succeed | risky attempt | danger | hazard | risk","1519830",
        "冒険が好きです。","ぼうけんがすきです。","Tôi thích phiêu lưu.","I like adventure."),
    row("北","きた","N5","n","bắc | hướng bắc | vùng phía bắc | Bắc Triều Tiên | gió bắc","north | the North | northern territories | North Korea | north wind","1520670",
        "北に行きます。","きたにいきます。","Tôi đi về hướng bắc.","I go north."),
    row("翻訳","ほんやく","N5","n|vs|vt","dịch thuật | giải mã | phiên dịch","translation | deciphering | decoding | translation","1523400",
        "翻訳します。","ほんやくします。","Tôi dịch.","I translate."),
    row("万","ばん","N5","adv","hoàn toàn | tuyệt đối | hoàn hảo","completely | absolutely | totally","1525750"),
    row("娘","むすめ","N5","n","con gái | cô gái (chưa lập gia đình)","daughter | girl (i.e. a young, unmarried woman)","1531190",
        "娘が生まれました。","むすめがうまれました。","Con gái tôi đã chào đời.","My daughter was born."),
    row("迷う","まよう","N5","v5u|vi","lạc đường | đi lạc | lạc lối | do dự | ngần ngại | lưỡng lự | không thể quyết định | không biết phải làm gì | bối rối | lúng túng | bị mê hoặc | say mê | bị cuốn hút | bị làm mù quáng | đắm chìm | lang thang (hồn người đã mất) | không yên nghỉ | không thể yên nghỉ","to lose one's way | to get lost | to go astray | to waver | to hesitate | to vacillate | to be of two minds (about) | to be unable to make up one's mind | to not know what to do | to be at a loss | to be puzzled | to be perplexed | to be captivated (by) | to be infatuated (with) | to be charmed (by) | to be carried away (by) | to be blinded (by) | to be lost (in) | to lose oneself (to) | to linger (of a departed soul) | to be restless in one's grave | to be unable to rest in peace","1532710",
        "道に迷いました。","みちにまよいました。","Tôi bị lạc đường.","I got lost."),
    row("野球","やきゅう","N5","n","bóng chày","baseball","1537300",
        "野球が好きです。","やきゅうがすきです。","Tôi thích bóng chày.","I like baseball."),
    row("約束","やくそく","N5","n|vs|vt","lời hứa | thỏa thuận | dàn xếp | lời cam kết | hợp đồng | giao ước | cuộc hẹn | đính hôn | buổi hẹn | quy ước | quy tắc | số phận | định mệnh","promise | agreement | arrangement | one's word | contract | pact | appointment | engagement | date | convention | rule | destiny | fate","1538130",
        "約束を守ります。","やくそくをまもります。","Tôi giữ lời hứa.","I keep my promise."),
    row("薬局","やっきょく","N5","n","nhà thuốc | hiệu thuốc | quầy thuốc | nhà thuốc bệnh viện | phòng bào chế","pharmacy | drugstore | chemist's (shop) | hospital pharmacy | dispensary","1538200",
        "薬局で薬を買います。","やっきょくでくすりをかいます。","Tôi mua thuốc ở nhà thuốc.","I buy medicine at the pharmacy."),
    row("勇気","ゆうき","N5","n","dũng cảm | can đảm | lòng dũng cảm | gan dạ | sự táo bạo","courage | bravery | valour | valor | nerve | boldness","1539740",
        "勇気を出してください。","ゆうきをだしてください。","Hãy dũng cảm lên.","Please have courage."),
    row("様子","ようす","N5","n","trạng thái (sự việc) | tình huống | hoàn cảnh | ngoại hình | vẻ ngoài | không khí | cách cư xử | hành vi | dấu hiệu | biểu hiện","state (of affairs) | situation | circumstances | appearance | look(s) | air | manner | behaviour | demeanor | sign | indication","1545820",
        "様子を見ます。","ようすをみます。","Tôi xem tình hình.","I see how things are."),
    row("理科","りか","N5","n","khoa học (khoa học tự nhiên và các lĩnh vực liên quan) | ngành khoa học, kỹ thuật, y tế (tại đại học) | môn khoa học (ở trường)","science (natural sciences and related fields, incl. mathematics, engineering, medicine, etc.) | faculties of science, engineering, medicine, etc. (at a university) | science (as a school subject)","1549900",
        "理科が好きです。","りかがすきです。","Tôi thích môn khoa học.","I like science."),
    row("理解","りかい","N5","n|vs|vt","sự hiểu biết | sự thấu hiểu | sự đánh giá cao | sự đồng cảm","understanding | comprehension | appreciation | sympathy","1549910",
        "理解できますか。","りかいできますか。","Bạn có hiểu không?","Can you understand?"),
    row("旅館","りょかん","N5","n","ryokan | nhà trọ kiểu Nhật truyền thống","ryokan | traditional Japanese inn","1553130",
        "旅館に泊まります。","りょかんにとまります。","Tôi ở lại ryokan.","I stay at a Japanese inn."),
    row("緑","みどり","N5","n|adj-no","màu xanh lá | xanh mướt | cây xanh","green | greenery | verdure","1555300",
        "緑が好きです。","みどりがすきです。","Tôi thích màu xanh lá.","I like green."),
    row("涙","なみだ","N5","n","nước mắt | giọt nước mắt | dịch tuyến lệ | sự thương cảm","tear | tears | lachrymal secretion | sympathy","1555930",
        "涙が出ます。","なみだがでます。","Nước mắt tôi chảy ra.","Tears come out."),
    row("礼儀","れいぎ","N5","n","phép lịch sự | sự lễ phép | nghi thức","manners | courtesy | etiquette","1557470",
        "礼儀が大切です。","れいぎがたいせつです。","Phép lịch sự rất quan trọng.","Manners are important."),
    row("居る","おる","N5","v5r|vi|aux-v|suf","có mặt (sinh vật) | tồn tại | đang ... | đã ... | đang được ... | dám làm","to be (animate) | to be | to exist | to be ...-ing | to have ...-ed | to be ...-ed | to (have the audacity to) do","1577985"),
    row("次","じ","N5","pref|ctr","tiếp theo | hypo- (chứa nguyên tố hóa trị thấp) | thứ tự | lần | lần lượt","next | hypo- (i.e. containing an element with low valence) | order | sequence | time | times","1579580"),
    row("夫婦","ふうふ","N5","n","vợ chồng | chồng và vợ | đôi vợ chồng","married couple | husband and wife | man and wife","1583640",
        "仲良し夫婦ですね。","なかよしふうふですね。","Đôi vợ chồng hòa thuận nhỉ.","What a happy couple."),
    row("嫌","いや","N5","adj-na|int","không thích | không muốn | miễn cưỡng | khó chịu | đáng ghét | tồi | khủng khiếp | kinh tởm | không mong muốn | không được chào đón | không! | thôi! | dừng lại!","disliking | not wanting | unwilling (to do) | reluctant | unpleasant | disagreeable | nasty | horrible | disgusting | undesirable | unwelcome | no! | quit it! | stop!","1587610",
        "嫌いです。","きらいです。","Tôi không thích.","I dislike it."),
    row("生む","うむ","N5","v5m|vt","sinh con | mang thai | đẻ trứng | sản xuất | tạo ra | gây ra | sinh ra | mang lại","to give birth | to bear (child) | to lay (eggs) | to produce | to yield | to give rise to | to deliver","1588410"),
    row("遅れる","おくれる","N5","v1|vi","đến muộn | bị trễ | chậm tiến độ | quá hạn | tụt lại (trong cuộc đua, học tập) | đi sau | lạc hậu (thời đại) | bị mất đi | bị qua mặt (bởi ai đó qua đời trước) | chậm (đồng hồ)","to be late | to be delayed | to fall behind schedule | to be overdue | to fall behind (in a race, one's studies, etc.) | to lag behind | to be behind (the times) | to be bereaved of | to be preceded by (someone) in death | to be slow (of a clock or watch)","1589040",
        "電車が遅れました。","でんしゃがおくれました。","Tàu điện bị trễ.","The train is delayed."),
    row("戦う","たたかう","N5","v5u|vi","giao chiến | chiến tranh | đánh nhau | thi đấu | chiến đấu | cạnh tranh (với) | đấu tranh (với khó khăn) | chống lại","to make war (on) | to wage war (against) | to go to war (with) | to fight (with) | to do battle (against) | to compete (against) | to struggle (against adversities, etc.) | to fight | to contend | to resist","1596960",
        "頑張って戦います。","がんばってたたかいます。","Tôi cố gắng chiến đấu.","I fight hard."),
    row("夏","か","N5","n","nhà Hạ (triều đại Trung Quốc; khoảng 2070-1600 TCN) | nhà Hạ","Xia dynasty (of China; ca. 2070-1600 BCE; possibly mythological) | Hsia dynasty","2253330"),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)

print(f"Written {len(ROWS)} rows + header to {OUT}")
