# -*- coding: utf-8 -*-
"""Build N2 ready wave 013 — emotion/praise/apology, control, rebellion, escape, deception."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-013.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("感銘","かんめい","n|vs|vi","ấn tượng sâu sắc | cảm động sâu xa","deep impression | being deeply moved","1212630"),
    ("感嘆","かんたん","n|vs|vi|adj-no","thán phục | trầm trồ | kinh ngạc","admiration | wonder | astonishment","1212490"),
    ("哀悼","あいとう","n|vs|vt|adj-no","thương tiếc | tiếc thương | chia buồn","condolence | sorrow | lament","1150350"),
    ("追悼","ついとう","n|vs|vt","tưởng niệm | truy điệu | tưởng nhớ","mourning","1432610"),
    ("慰問","いもん","n|vs|vt","thăm hỏi | ủy lạo | an ủi (người bệnh)","visit to console | giving comfort","1156950"),
    ("慰労","いろう","n|vs|vt","úy lạo | ghi nhận công lao | khích lệ","recognition of services","1156980"),
    ("鼓舞","こぶ","n|vs|vt","cổ vũ | khích lệ | động viên | nâng cao sĩ khí","encouragement | inspiration | rousing","1268020"),
    ("絶賛","ぜっさん","n|vs|vt|adv","ca ngợi hết lời | tán dương | đang (diễn ra)","high praise | acclaim | currently","1721830"),
    ("礼賛","らいさん","n|vs|vt","tán dương | tôn vinh | ngợi ca","praise | worship | glorification","1557510"),
    ("顕彰","けんしょう","n|vs|vt","biểu dương | vinh danh | tôn vinh công lao","honouring (publicly) | making achievements known","1260630"),
    ("称揚","しょうよう","n|vs|vt","tán dương | đề cao | ca tụng","praise | admiration | extolling","1619270"),
    ("褒美","ほうび","n","phần thưởng | tưởng thưởng","reward | prize","1518050"),
    ("報奨","ほうしょう","n|vs|vt","tiền thưởng | khen thưởng | đãi ngộ","bonus | bounty | reward","1627500"),
    ("謝礼","しゃれい","n|vs|vi","tiền thù lao | thù lao cảm ơn","reward | honorarium | remuneration","1323070"),
    ("返礼","へんれい","n|vs|vi","đáp lễ | quà đáp lại | trả ơn | trả đũa","return present | something done in return","1512320"),
    ("答礼","とうれい","n|vs|vi","đáp lễ | chào đáp lại | thăm đáp lễ","return of a courtesy | return salute","1661760"),
    ("陳謝","ちんしゃ","n|vs|vt","xin lỗi | ngỏ lời xin lỗi","apology","1432170"),
    ("謝罪","しゃざい","n|vs|vt","xin lỗi | tạ lỗi | tạ tội","apology","1323030"),
    ("弁解","べんかい","n|vs|vt","biện bạch | thanh minh | bào chữa","explanation | excuse | justification","1512760"),
    ("申し開き","もうしひらき","n","phân trần | thanh minh | giải bày","excuse | explanation | justification","1764870"),
    ("口実","こうじつ","n","cái cớ | lý do viện ra | viện cớ","excuse | pretext","1276220"),
    ("庇護","ひご","n|vs|vt","che chở | bảo trợ | bảo hộ","patronage | protection","1731810"),
    ("養護","ようご","n|vs|vt","chăm sóc | nuôi dưỡng | bảo dưỡng (trẻ)","nursing | protective care","1605847"),
    ("干渉","かんしょう","n|vs|vi","can thiệp | xen vào | giao thoa","interference | intervention | meddling","1212050"),
    ("介入","かいにゅう","n|vs|vi","can thiệp | nhúng tay vào","intervention","1198110"),
    ("関与","かんよ","n|vs|vi","tham gia | dính líu | liên quan","participation | being concerned in","1216050"),
    ("参画","さんかく","n|vs|vi","tham gia (hoạch định) | góp phần lập kế hoạch","taking part (in planning) | participation","1302120"),
    ("参与","さんよ","n|vs|adj-no|vi","tham gia | cố vấn | tham mưu","participation | consultant | adviser","1302610"),
    ("従事","じゅうじ","n|vs|vi","làm (nghề) | tham gia vào | theo đuổi (công việc)","engaging in (work) | being involved in","1335320"),
    ("着手","ちゃくしゅ","n|vs|vi","bắt tay vào | khởi sự | bắt đầu làm","starting work (on) | setting about","1423060"),
    ("服従","ふくじゅう","n|vs|vi","phục tùng | tuân theo | quy phục","obedience | submission","1500950"),
    ("降伏","こうふく","n|vs|vi","đầu hàng | quy hàng | khuất phục","surrender | capitulation | submission","1282940"),
    ("屈辱","くつじょく","n","nỗi nhục | sỉ nhục | ô nhục","disgrace | humiliation","1246600"),
    ("侮辱","ぶじょく","n|vs|vt","lăng mạ | sỉ nhục | xúc phạm","insult | affront | contempt","1498260"),
    ("蔑視","べっし","n|vs|vt","khinh thường | coi khinh | rẻ rúng","contempt | derision | disdain","1510290"),
    ("排斥","はいせき","n|vs|vt","bài xích | tẩy chay | trục xuất","rejection | expulsion | boycott | ostracism","1472400"),
    ("圧迫","あっぱく","n|vs|vt","đè ép | áp bức | gây sức ép | chèn ép","pressure | oppression | suppression","1153310"),
    ("威圧","いあつ","n|vs|vt","uy hiếp | áp đảo | trấn áp","coercion | overpowering | daunting","1156210"),
    ("虐殺","ぎゃくさつ","n|vs|vt","tàn sát | thảm sát","slaughter | massacre","1226930"),
    ("殺戮","さつりく","n|vs|vt","tàn sát | giết chóc | thảm sát","slaughter | massacre","1579320"),
    ("暴動","ぼうどう","n","bạo động | bạo loạn | nổi loạn","insurrection | riot | uprising","1519520"),
    ("暴徒","ぼうと","n","đám bạo loạn | quân nổi loạn | phiến quân","rioters | mob | insurgents","1519500"),
    ("反乱","はんらん","n|vs|vi","phản loạn | nổi loạn | binh biến","insurrection | mutiny | rebellion","1481090"),
    ("内乱","ないらん","n","nội chiến | nội loạn | xung đột trong nước","civil war | insurrection | domestic conflict","1459460"),
    ("動乱","どうらん","n","động loạn | rối loạn | biến động (xã hội)","disturbance | upheaval | unrest","1451640"),
    ("騒乱","そうらん","n|adj-no","náo loạn | hỗn loạn | gây rối","disturbance | riot | mayhem","1403090"),
    ("騒動","そうどう","n|vs|vi","xáo trộn | rối ren | vụ ầm ĩ | tranh cãi om sòm","riot | turmoil | uproar | controversy","1403080"),
    ("逃避","とうひ","n|vs|vi","trốn tránh | lảng tránh | né tránh","escape | evasion | flight","1450460"),
    ("逃亡","とうぼう","n|vs|vi","đào tẩu | bỏ trốn | chạy trốn","escape | flight | running away","1450470"),
    ("逃走","とうそう","n|vs|vi|adj-no","tẩu thoát | chạy trốn | đào tẩu","flight | desertion | escape","1450450"),
    ("脱走","だっそう","n|vs|vi","vượt ngục | đào ngũ | trốn thoát","escape | breakout | desertion","1610240"),
    ("離脱","りだつ","n|vs|vi","rút khỏi | thoát ly | ly khai | tách ra","withdrawal | secession | breakaway","1550930"),
    ("失踪","しっそう","n|vs|vi","mất tích | bỏ đi biệt tăm | lẩn trốn","disappearance | going missing | absconding","1320260"),
    ("潜伏","せんぷく","n|vs|vi","ẩn náu | mai phục | tiềm ẩn (bệnh) | nằm vùng","concealment | ambush | incubation | latency","1391380"),
    ("隠匿","いんとく","n|vs|vt","giấu giếm | che giấu (tội phạm) | tàng trữ","concealment | sheltering | harboring","1170790"),
    ("隠蔽","いんぺい","n|vs|vt","che đậy | bưng bít | giấu giếm","concealment | covering up | suppression","1170850"),
    ("秘匿","ひとく","n|vs|vt","giấu kín | bí mật cất giấu","hiding | concealment","1484120"),
    ("変装","へんそう","n|vs|vi","cải trang | hóa trang | ngụy trang","disguise | masquerade","1511280"),
    ("仮装","かそう","n|vs|vi","hóa trang | giả trang | cải trang","costume | fancy dress | disguise","1187790"),
    ("扮装","ふんそう","n|vs|vi","hóa trang | trang điểm (vai) | trang phục diễn","make-up | get-up | disguise","1956940"),
    ("擬態","ぎたい","n|vs|vi","ngụy trang | bắt chước (sinh học) | mô phỏng","mimicry | mimesis | camouflage","1759900"),
    ("模造","もぞう","n|vs|vt|adj-no","làm giả | nhái | mô phỏng | đồ giả","imitation | counterfeit | fake","1533680"),
    ("偽造","ぎぞう","n|vs|vt|adj-no","làm giả | giả mạo | ngụy tạo","forgery | counterfeiting | falsification","1224580"),
    ("捏造","ねつぞう","n|vs|vt","bịa đặt | ngụy tạo | dựng chuyện","fabrication | forgery | hoax","1567420"),
    ("改ざん","かいざん","n|vs|vt","sửa đổi gian lận | làm giả | xuyên tạc số liệu","alteration | falsification | faking","1201170"),
    ("歪曲","わいきょく","n|vs|vt","bóp méo | xuyên tạc | làm sai lệch","distortion | falsification | perversion","1562460"),
    ("誇張","こちょう","n|vs|vt","cường điệu | phóng đại | thổi phồng","exaggeration","1267820"),
    ("粉飾","ふんしょく","n|vs|vt","tô vẽ | trang điểm | làm đẹp số liệu (gian dối)","embellishment | ornamentation | window dressing","1504810"),
    ("水増し","みずまし","n|vs|vt","pha loãng | khai khống | thổi phồng (số liệu)","dilution | watering down | padding","1371810"),
    ("でっち上げ","でっちあげ","n","bịa đặt | dựng chuyện | vu khống | ngụy tạo","fabrication | made-up story | frame-up","1950070"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
