# -*- coding: utf-8 -*-
"""Build N2 ready wave 055 — body parts, internal organs, bodily fluids, postures."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-055.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("瞼","まぶた","n","mí mắt","eyelid","1569920"),
    ("瞳","ひとみ","n","con ngươi | đồng tử | đôi mắt","pupil (of the eye) | one's eyes","1453900"),
    ("眼球","がんきゅう","n|adj-no","nhãn cầu | tròng mắt","eyeball","1217180"),
    ("鼻筋","はなすじ","n","sống mũi","bridge of the nose","1486920"),
    ("小鼻","こばな","n","cánh mũi | lỗ mũi","nostrils | wings of the nose","1348690"),
    ("歯茎","はぐき","n","lợi | nướu răng","gums | gingiva","1313290"),
    ("顎","あご","n","hàm | cằm | ngạnh (lưỡi câu)","jaw | chin | barb (of a fishhook)","1207560"),
    ("喉仏","のどぼとけ","n","yết hầu | trái cổ","Adam's apple","1677730"),
    ("鎖骨","さこつ","n","xương đòn","collarbone | clavicle","1291750"),
    ("肩甲骨","けんこうこつ","n","xương bả vai","shoulder blade | scapula","1578340"),
    ("背骨","せぼね","n","cột sống | xương sống","spine | backbone","1472750"),
    ("脊椎","せきつい","n","cột sống | đốt sống | xương sống","spine | vertebral column | vertebra","1383130"),
    ("肋骨","あばらぼね","n","xương sườn | khung sườn (tàu)","rib | frame (of a ship)","1585320"),
    ("骨盤","こつばん","n","xương chậu | khung chậu","pelvis","1288740"),
    ("腰骨","こしぼね","n","xương hông | sự kiên trì | sức bền bỉ","hipbone | fortitude | perseverance","1288400"),
    ("肘","ひじ","n","khuỷu tay","elbow","1487380"),
    ("手首","てくび","n","cổ tay","wrist","1327770"),
    ("手のひら","てのひら","n","lòng bàn tay","palm (of the hand)","1580300"),
    ("甲","こう","n","mai | vỏ cứng | hạng nhất | mu bàn tay | bên A (hợp đồng)","carapace | grade A | back of hand | the first party","1578730"),
    ("拳","こぶし","n","nắm đấm | quả đấm","fist","1257740"),
    ("脇","わき","n","nách | bên hông | bên cạnh | sang một bên | lạc đề | vai phụ","armpit | side | aside | supporting role","1562530"),
    ("太もも","ふともも","n","đùi","thigh","1408270"),
    ("膝小僧","ひざこぞう","n","đầu gối | xương bánh chè","kneecap","1721900"),
    ("足の裏","あしのうら","exp|n","gan bàn chân | lòng bàn chân","sole of the foot","1628950"),
    ("踵","かかと","n","gót chân | gót (giày, tất)","heel (of foot, shoe)","1573310"),
    ("土踏まず","つちふまず","n","vòm bàn chân | lõm gan bàn chân","arch of the foot","1702430"),
    ("つま先","つまさき","n","đầu ngón chân | mũi (giày, tất)","toes | toe of a shoe","1433910"),
    ("横隔膜","おうかくまく","n","cơ hoành","diaphragm","1180660"),
    ("食道","しょくどう","n","thực quản","esophagus | gullet","1358570"),
    ("気管","きかん","n","khí quản","trachea | windpipe","1222030"),
    ("気道","きどう","n","đường thở | đường hô hấp","respiratory tract | air duct","1222500"),
    ("大腸","だいちょう","n","ruột già | đại tràng","large intestine | colon","1414560"),
    ("小腸","しょうちょう","n","ruột non","small intestine","1660120"),
    ("盲腸","もうちょう","n","manh tràng | ruột thừa | viêm ruột thừa","cecum | appendix | appendicitis","1534260"),
    ("膵臓","すいぞう","n","tuyến tụy","pancreas","1571130"),
    ("脾臓","ひぞう","n","lá lách","spleen","1570920"),
    ("膀胱","ぼうこう","n","bàng quang","urinary bladder","1571020"),
    ("子宮","しきゅう","n|adj-no","tử cung | dạ con","womb | uterus","1307830"),
    ("卵巣","らんそう","n","buồng trứng","ovary","1549260"),
    ("前立腺","ぜんりつせん","n","tuyến tiền liệt","prostate (gland)","1394170"),
    ("甲状腺","こうじょうせん","n","tuyến giáp","thyroid (gland)","1280170"),
    ("神経系","しんけいけい","n","hệ thần kinh","nervous system","1646820"),
    ("中枢神経","ちゅうすうしんけい","n","thần kinh trung ương","central nerves","1695710"),
    ("末梢神経","まっしょうしんけい","n","thần kinh ngoại biên","peripheral nerves","1525450"),
    ("脊髄","せきずい","n","tủy sống","spinal cord","1383120"),
    ("延髄","えんずい","n|adj-no","hành tủy","medulla oblongata","1176470"),
    ("大脳","だいのう","n","đại não","cerebrum","1414750"),
    ("小脳","しょうのう","n","tiểu não","cerebellum","1348600"),
    ("脳幹","のうかん","n","thân não","brain stem","1828290"),
    ("血流","けつりゅう","n","dòng máu | lưu lượng máu","bloodstream | blood flow","2129170"),
    ("血行","けっこう","n","sự lưu thông máu | tuần hoàn máu","circulation (of the blood)","1255230"),
    ("心拍","しんぱく","n","nhịp tim","heartbeat","1360940"),
    ("呼吸器","こきゅうき","n","cơ quan hô hấp","respiratory organs","1266480"),
    ("消化器","しょうかき","n","cơ quan tiêu hóa","digestive organ","1660230"),
    ("循環器","じゅんかんき","n","cơ quan tuần hoàn","circulatory organ","1735930"),
    ("泌尿器","ひにょうき","n","cơ quan tiết niệu","urinary organs","1602070"),
    ("生殖器","せいしょくき","n","cơ quan sinh dục | bộ phận sinh sản","genital organ | reproductive organ","1379130"),
    ("内分泌","ないぶんぴつ","adj-f|n","nội tiết | bài tiết trong","endocrine | internal secretion","1582560"),
    ("ホルモン","ホルモン","n","hormone | nội tạng (bò, heo nướng)","hormone | offal","1122910"),
    ("排尿","はいにょう","n|vs|vi","tiểu tiện | đi tiểu","urination","1472460"),
    ("排便","はいべん","n|vs|vi","đại tiện | đi ngoài","defecation","1472470"),
    ("発汗","はっかん","n|vs|vi","đổ mồ hôi | tiết mồ hôi","sweating | perspiration","1477220"),
    ("分泌物","ぶんぴつぶつ","n","chất tiết | dịch tiết","secretion","1504140"),
    ("唾液","だえき","n","nước bọt | nước miếng","saliva | sputum","1408420"),
    ("胃液","いえき","n","dịch vị | dịch dạ dày","gastric juice","1158510"),
    ("胆汁","たんじゅう","n","mật | dịch mật","bile | gall","1419030"),
    ("粘液","ねんえき","n|adj-no","chất nhầy | dịch nhầy | đờm","mucus | viscous liquid | phlegm","1469710"),
    ("体液","たいえき","n","dịch cơ thể | thể dịch","body fluid","1409240"),
    ("細胞膜","さいぼうまく","n","màng tế bào","cell membrane","1295780"),
    ("核","かく","n|adj-no","hạt (quả) | hạt nhân | nòng cốt | lõi | vòng (hóa học)","stone (of a fruit) | nucleus | core | nuclear weapons","1205510"),
    ("寄りかかる","よりかかる","v5r|vi","tựa vào | dựa vào | ỷ lại | dựa dẫm","to lean against | to rely on","1606110"),
    ("仰向け","あおむけ","n","nằm ngửa | mặt ngửa lên","facing upward","1238910"),
    ("正座","せいざ","n|vs|vi","ngồi quỳ kiểu Nhật (seiza)","seiza | kneeling formally","1595990"),
    ("猫背","ねこぜ","n|adj-no|adj-na","lưng gù | lưng còng | tật gù lưng","bent back | hunchback | stoop","1467680"),
    ("前かがみ","まえかがみ","n","khom người về phía trước | cúi gập","slouch | stooping forward","1392820"),
    ("仁王立ち","におうだち","n|vs|vi","đứng hiên ngang | đứng sừng sững | tư thế uy nghi","imposing stance | daunting pose","2181590"),
    ("棒立ち","ぼうだち","n","đứng đơ | đứng như trời trồng | (ngựa) chồm lên","standing bolt upright | rearing","1519810"),
    ("直立","ちょくりつ","n|vs|vi|adj-no","đứng thẳng | đứng thẳng tắp | dựng đứng | sừng sững","standing upright | rising perpendicularly","1431570"),
    ("起立","きりつ","n|vs|vi","đứng dậy | đứng lên","standing up","1223950"),
    ("着席","ちゃくせき","n|vs|vi","ngồi vào chỗ | an tọa","taking a seat | sitting down","1423130"),
    ("中腰","ちゅうごし","n","tư thế khom nửa người | dáng đứng lom khom","half-sitting posture | stooping position","1424320"),
    ("膝立ち","ひざだち","n","tư thế quỳ gối","kneeling","2838299"),
    ("四つん這い","よつんばい","n","bò bằng tứ chi | bò bằng tay và đầu gối","crawling on all fours","1307050"),
    ("腕組み","うでぐみ","n|vs|vi","khoanh tay","folding one's arms","1562900"),
    ("腕まくり","うでまくり","n|vs|vi","xắn tay áo","rolling up one's sleeves","1665120"),
    ("背伸び","せのび","n|vs|vi","kiễng chân vươn người | rướn người | cố quá sức mình","standing on tiptoe | overreaching oneself","1472770"),
    ("背筋","せすじ","n","sống lưng | đường xương sống | đường may sau lưng","spine | line of the backbone","1646310"),
    ("猫なで声","ねこなでごえ","n","giọng nịnh nọt | giọng ngọt ngào dụ dỗ","soft coaxing voice | wheedling voice","1600060"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
