# -*- coding: utf-8 -*-
"""Build N2 ready wave 037 — locations, areas, indoor/outdoor, construction/land, surfaces, directions."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-037.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("界隈","かいわい","n|n-suf","vùng lân cận | khu vực | giới (cùng sở thích)","neighborhood | vicinity | community (of fans)","1202130"),
    ("一帯","いったい","n|adj-no","cả vùng | toàn khu vực | một dải","whole area | whole region | belt | zone","1164570"),
    ("近郊","きんこう","n","vùng ngoại ô | vùng ven | khu lân cận","outskirts | environs (of a city)","1242290"),
    ("辺境","へんきょう","n|adj-no","vùng biên giới | nơi hẻo lánh | biên cương","remote region | border district | frontier","1512100"),
    ("僻地","へきち","n","nơi hẻo lánh | vùng sâu vùng xa","remote place | backcountry | hinterland","1509240"),
    ("奥地","おくち","n|adj-no","vùng sâu | nội địa | vùng hẻo lánh","interior | backwoods | hinterland","1576690"),
    ("内陸","ないりく","n|adj-no","nội địa | trong đất liền","inland","1459500"),
    ("沿線","えんせん","n|adj-no","dọc tuyến (đường sắt, đường lớn)","places alongside a railway line","1176750"),
    ("沿道","えんどう","n|adj-no","ven đường | dọc đường","roadside | wayside | route","1176760"),
    ("路上","ろじょう","n","trên đường | ngoài phố | giữa đường","on the road | on the street","1612340"),
    ("横丁","よこちょう","n","ngõ | hẻm | ngõ ngách | con phố nhỏ","bystreet | side street | alley","1605910"),
    ("街頭","がいとう","n","ngoài phố | trên đường phố","(on the) street","1204640"),
    ("広場","ひろば","n","quảng trường | bãi đất trống | khoảng trống","public square | plaza | open space","1278590"),
    ("敷地","しきち","n","khu đất | mặt bằng | lô đất | khuôn viên","site | plot | lot | grounds","1497060"),
    ("用地","ようち","n","đất sử dụng | khu đất (cho mục đích) | mặt bằng","site (for a purpose)","1546370"),
    ("圏内","けんない","n","trong phạm vi | trong vùng | trong tầm","inside (a region) | within range","1257100"),
    ("圏外","けんがい","n","ngoài phạm vi | ngoài vùng phủ sóng | ngoài tầm","outside (a region) | out of range","1257090"),
    ("管内","かんない","n|adj-no","trong phạm vi quản lý | trong địa hạt | trong ống","within the jurisdiction (of) | in a pipe","1214190"),
    ("構内","こうない","n","trong khuôn viên | trong khu | sân ga","premises | grounds | campus | precincts","1279820"),
    ("館内","かんない","n|adj-no","trong (thư viện, bảo tàng, rạp) | trong cơ sở","inside a building (library, museum) | on the premises","1614320"),
    ("店内","てんない","n|adj-no","trong cửa hàng | nội bộ quán","inside of a store | store interior","1440780"),
    ("室内","しつない","n|adj-no","trong phòng | trong nhà","indoor | inside the room","1320350"),
    ("屋内","おくない","n|adj-no","trong nhà | trong nhà có mái che","indoors","1182730"),
    ("屋外","おくがい","n|adj-no","ngoài trời | bên ngoài","outdoors | outside","1182680"),
    ("野外","やがい","n|adj-no","ngoài trời | ngoài đồng | ngoại ô","outdoors | open air | fields","1537270"),
    ("車内","しゃない","n|adj-no","trong xe (tàu, buýt)","inside a car (train, bus)","1323220"),
    ("機内","きない","adj-no|n","trong máy bay | trên chuyến bay","inside a plane | in-flight","1221120"),
    ("庁舎","ちょうしゃ","n","tòa nhà cơ quan chính phủ | trụ sở hành chính","government office building","1427600"),
    ("官庁","かんちょう","n","cơ quan chính phủ | nhà chức trách","government office | government agency","1211730"),
    ("役所","やくしょ","n","cơ quan hành chính | ủy ban | công sở","government office | public office","1538020"),
    ("本部","ほんぶ","n","tổng bộ | trụ sở chính | bản doanh","headquarters | head office","1523170"),
    ("支部","しぶ","n|adj-no","chi nhánh | phân bộ | văn phòng nhánh","branch | branch office | subdivision","1310290"),
    ("据え置き","すえおき","n|adj-no","để nguyên | hoãn | chưa đáo hạn | giữ nguyên (giá)","deferment | leaving as it stands | stationary","1610690"),
    ("据え付け","すえつけ","n","lắp đặt | gắn cố định | lắp ráp","installation | setting | mounting","1952980"),
    ("備え付け","そなえつけ","n","trang bị | lắp đặt sẵn | trang thiết bị","equipment | provision","1596630"),
    ("仮設","かせつ","n|adj-no|vs|vt","xây tạm | dựng tạm | giả định | giả thiết","temporary construction | assumption","1590325"),
    ("増設","ぞうせつ","n|vs|vt","lắp thêm | mở rộng | bổ sung thiết bị","adding (equipment) | extension | expansion","1403290"),
    ("新設","しんせつ","n|vs|vt|adj-no","thành lập mới | lập mới | xây mới","establishing | founding | setting up","1362070"),
    ("併設","へいせつ","n|vs|vt","đặt kèm | xây kèm | lập chung | xây liền kề","joint establishment | establishment as an annex","1506150"),
    ("移設","いせつ","n|vs|vt","di dời (cơ sở) | chuyển sang vị trí khác","relocation (of facilities) | moving","1158340"),
    ("敷設","ふせつ","n|vs|vt","lắp đặt (đường ray, ống) | xây lắp | rải","laying (a railroad, pipes) | construction","1497050"),
    ("架設","かせつ","n|vs|vt","xây dựng | bắc (cầu) | lắp đặt (đường dây)","construction | building","1193150"),
    ("造成","ぞうせい","n|vs|vt","san lấp tạo mặt bằng | cải tạo đất | bồi đắp","development (of land) | reclamation","1620240"),
    ("整地","せいち","n|vs|vt|vi","san nền | làm phẳng đất | làm đất (trồng trọt)","levelling of ground | preparation of soil","1376220"),
    ("盛り土","もりど","n","đắp nền | tôn nền | nền đắp","embankment | raising the ground level | fill","1764400"),
    ("埋め立て","うめたて","n","lấn biển | san lấp | lấp đất","land reclamation | land fill","1610610"),
    ("干拓","かんたく","n|vs|vt","quai đê lấn biển | khai hoang lấn biển","land reclamation (from sea)","1212060"),
    ("区画整理","くかくせいり","n","chỉnh trang quy hoạch đất | quy hoạch lại khu đất","land readjustment | town planning","1592120"),
    ("都市計画","としけいかく","n","quy hoạch đô thị","city planning | urban planning","1700860"),
    ("再開発","さいかいはつ","n|vs|vt","tái phát triển | tái thiết quy hoạch","redevelopment","1657660"),
    ("立ち退き","たちのき","n","sự di dời | giải tỏa | trục xuất khỏi nhà","eviction","1838160"),
    ("更地","さらち","n","đất trống | lô đất bỏ không","empty lot | vacant plot of land","1279420"),
    ("廃屋","はいおく","n","nhà hoang | nhà bỏ hoang | nhà đổ nát","dilapidated house | deserted house","1625680"),
    ("別棟","べつむね","n","nhà riêng | dãy nhà tách biệt | nhà phụ","separate building | outbuilding","1510060"),
    ("高層","こうそう","adj-no|n","cao tầng | nhà chọc trời | tầng cao (khí quyển)","high-rise (building) | upper (atmosphere)","1283690"),
    ("低層","ていそう","adj-no|n","thấp tầng | nhà thấp tầng","low-rise (architecture) | low-level","1434550"),
    ("中層","ちゅうそう","n|adj-no","tầng giữa | độ sâu trung bình | nhà tầm trung","middle part | medium depth | medium-rise","2616160"),
    ("通路","つうろ","n","lối đi | đường đi | hành lang | lối thông","passage | pathway | aisle","1433600"),
    ("出入り口","でいりぐち","n","cửa ra vào | lối ra vào","exit and entrance","1598540"),
    ("非常口","ひじょうぐち","n","lối thoát hiểm | cửa thoát hiểm","emergency exit","1484950"),
    ("背面","はいめん","n|adj-no","mặt sau | phía sau | mặt lưng","rear | back | reverse","1625650"),
    ("裏面","りめん","n","mặt sau | mặt trái | hậu trường | góc khuất","back (side) | the inside | behind the scenes","2858813"),
    ("全面","ぜんめん","n|adj-no","toàn bộ mặt | toàn diện | toàn bộ","whole surface | entire","1396260"),
    ("半面","はんめん","conj|prt|n|adj-no","mặt khác | nửa mặt | một mặt | mặt nghiêng","while | on the other hand | one side | profile","1479920"),
    ("両面","りょうめん","n|adj-no","hai mặt | cả hai mặt | hai chiều","both sides | two sides | double-sided","1554030"),
    ("片面","かためん","n|adj-no","một mặt","one side","1511820"),
    ("曲面","きょくめん","n","mặt cong","curved surface","1240120"),
    ("斜面","しゃめん","n","mặt nghiêng | sườn dốc | mặt vát","slope | slanting surface | bevel","1322470"),
    ("段差","だんさ","n","chênh lệch độ cao | bậc | gờ | ổ gà","difference in level | step | bump (in road)","1419960"),
    ("高低","こうてい","n|vs|vi","cao thấp | sự lên xuống | độ cao thấp","high and low | rise and fall","1283810"),
    ("凹凸","おうとつ","n","gồ ghề | lồi lõm | mấp mô | chênh lệch","unevenness | bumpiness | disparity","1179280"),
    ("起伏","きふく","n|vs|vi","gập ghềnh | nhấp nhô | thăng trầm | lên xuống","undulation | ups and downs | highs and lows","1223930"),
    ("鋭角","えいかく","n","góc nhọn","acute angle","1174910"),
    ("鈍角","どんかく","n","góc tù","obtuse angle","1457590"),
    ("対角","たいかく","n","đường chéo | góc đối","diagonal | opposite angle","1409910"),
    ("縦横","じゅうおう","n|adj-na","dọc ngang | chiều dài chiều rộng | tứ phương | thỏa thích","length and width | every direction | at will","1579920"),
    ("四方","しほう","n","bốn phương | tứ phía | xung quanh | khắp nơi | hình vuông","the four directions | all directions | surroundings","1307370"),
    ("八方","はっぽう","n","tám phương | mọi hướng | khắp các phía","all sides | the eight directions","1477020"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
