# -*- coding: utf-8 -*-
"""Build N1 ready wave 086 — advanced katakana loanwords (set 86)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-086.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("ミクスチャー","ミクスチャー","n","hỗn hợp | sự pha trộn | thể loại pha trộn","mixture","2471010"),
    ("ミスマッチ","ミスマッチ","n","sự không khớp | sự lệch pha | sự không tương xứng | sự ghép sai","mismatch","1130840"),
    ("ムーブメント","ムーブメント","n","phong trào | trào lưu | bộ máy (đồng hồ) | sự chuyển động","movement","1132220"),
    ("メンター","メンター","n|vs","người cố vấn | người dìu dắt | người hướng dẫn dày dạn","mentor","2448460"),
    ("モーメント","モーメント","n","khoảnh khắc | thời điểm | cơ hội | mô-men (vật lý)","moment","1134740"),
    ("モディフィケーション","モディフィケーション","n","sự điều chỉnh | sự sửa đổi | sự biến đổi","modification","1135190"),
    ("モニタリング","モニタリング","n","sự giám sát | theo dõi liên tục | quan trắc","monitoring","1135450"),
    ("ヤングケアラー","ヤングケアラー","n","người chăm sóc trẻ tuổi | trẻ phải chăm sóc người thân bệnh tật","a young carer","2849321"),
    ("ユニーク","ユニーク","adj-na","độc đáo | duy nhất | khác biệt | có một không hai","unique | original","1137120"),
    ("ユニバーサル","ユニバーサル","adj-na","phổ quát | toàn cầu | mang tính phổ biến | đa dụng","universal","1137310"),
    ("ユニフィケーション","ユニフィケーション","n","sự thống nhất | sự hợp nhất | sự nhất thể hóa","unification","1137400"),
    ("ライセンス","ライセンス","n","giấy phép | bản quyền | chứng nhận hành nghề","license","1137860"),
    ("ラショナリズム","ラショナリズム","n","chủ nghĩa duy lý | thuyết duy lý | tư tưởng lý trí","rationalism","1138770"),
    ("ランドマーク","ランドマーク","n","địa danh nổi bật | mốc địa hình | công trình biểu tượng","landmark","1140230"),
    ("リアリズム","リアリズム","n","chủ nghĩa hiện thực | tinh thần thực tế | thuyết hiện thực","realism","1140960"),
    ("リーズナブル","リーズナブル","adj-na","hợp lý | giá phải chăng | có lý | thỏa đáng","reasonable | affordable","1140550"),
    ("リーダーシップ","リーダーシップ","n","khả năng lãnh đạo | tài lãnh đạo | vai trò dẫn dắt","leadership","1140600"),
    ("リカレント","リカレント","n","lặp lại | tái diễn | tuần hoàn | học tập suốt đời","recurrent","1141110"),
    ("リコメンデーション","リコメンデーション","n","sự gợi ý | đề xuất | khuyến nghị | lời giới thiệu","recommendation","1141300"),
    ("リソース","リソース","n","nguồn lực | tài nguyên | nguồn tài nguyên","resource","1141670"),
    ("リテラシー","リテラシー","n","khả năng đọc hiểu | năng lực sử dụng (thông tin) | trình độ hiểu biết","literacy","1141940"),
    ("リハビリテーション","リハビリテーション","n","sự phục hồi chức năng | tập vật lý trị liệu | sự tái hòa nhập","rehabilitation","1142250"),
    ("リバイバル","リバイバル","n|vs|vi","sự phục hưng | sự hồi sinh | sự khôi phục | làm sống lại","revival","1142330"),
    ("リフレクション","リフレクション","n","sự phản chiếu | sự suy ngẫm | sự phản ánh | nhìn lại bản thân","reflection","1142600"),
    ("リフレッシュ","リフレッシュ","n|vs|vt|vi","sự làm tươi mới | nạp lại năng lượng | thư giãn | làm mới","refreshment | refreshing oneself","1142630"),
    ("リベラリズム","リベラリズム","n","chủ nghĩa tự do | tư tưởng phóng khoáng | thuyết tự do","liberalism","1142780"),
    ("リミット","リミット","n","giới hạn | hạn mức | mức tối đa | ngưỡng","limit","1142960"),
    ("リユース","リユース","n|vs|vt","sự tái sử dụng | dùng lại | sử dụng lại","reuse","2448560"),
    ("リレーション","リレーション","n","mối quan hệ | sự liên hệ | sự liên kết","relation","1143340"),
    ("ルーラル","ルーラル","adj-f|n","nông thôn | vùng quê | thuộc miền quê","rural","1143900"),
    ("レアケース","レアケース","n","trường hợp hiếm | ca hiếm gặp | ngoại lệ | tình huống cá biệt","a rare case","2826911"),
    ("レイアウト","レイアウト","n|vs|vt","bố cục | cách dàn trang | sự sắp đặt | thiết kế bố trí","layout","1144540"),
    ("レガシー","レガシー","n|adj-no","di sản | tài sản kế thừa | hệ thống cũ kế thừa","legacy","2338530"),
    ("レギュレーション","レギュレーション","n","quy định | luật lệ | quy chế | điều lệ","regulation","1144820"),
    ("レシピエント","レシピエント","n","người nhận | người được ghép tạng | bên tiếp nhận","recipient","2448580"),
    ("レゾナンス","レゾナンス","n","sự cộng hưởng | sự đồng vọng | hiện tượng cộng hưởng","resonance","1145410"),
    ("レゾリューション","レゾリューション","n","nghị quyết | độ phân giải | sự giải quyết | quyết tâm","resolution","1145420"),
    ("レトロスペクティブ","レトロスペクティブ","n|adj-no","sự hồi cố | nhìn lại quá khứ | mang tính hồi tưởng | triển lãm hồi cố","retrospective","2540400"),
    ("レピュテーション","レピュテーション","n","danh tiếng | tiếng tăm | uy tín","reputation","2448590"),
    ("レンジ","レンジ","n","phạm vi | khoảng | bếp | lò vi sóng","range | stove","1146110"),
    ("ロー","ロー","adj-f|n","thấp | mức thấp | số thấp (xe)","low","1146270"),
    ("ローカリゼーション","ローカリゼーション","n","sự bản địa hóa | nội địa hóa | địa phương hóa","localization","1983680"),
    ("ワークショップ","ワークショップ","n","hội thảo thực hành | buổi tập huấn | xưởng làm việc chung","workshop","1148380"),
    ("ワークフロー","ワークフロー","n","quy trình làm việc | luồng công việc | trình tự tác nghiệp","workflow","2339880"),
    ("ワーディング","ワーディング","n","cách dùng từ | cách diễn đạt | câu chữ","wording","2530070"),
    ("ワイズ","ワイズ","n","khôn ngoan | sáng suốt | minh triết","wise","1148650"),
    ("アグリゲーション","アグリゲーション","n","sự tổng hợp | sự gom nhóm | tập hợp dữ liệu","aggregation","2858505"),
    ("アクセシビリティ","アクセシビリティ","n","khả năng tiếp cận | tính dễ truy cập | sự thuận tiện sử dụng","accessibility","1985700"),
    ("アスリート","アスリート","n","vận động viên | lực sĩ | tuyển thủ thể thao","athlete","1016180"),
    ("アテンション","アテンション","n","sự chú ý | sự quan tâm | sự lưu tâm","attention","1016740"),
    ("アンテナ","アンテナ","n","ăng-ten | giác quan nắm bắt thông tin | sự nhạy bén thông tin","antenna","1020410"),
    ("インストラクション","インストラクション","n","sự hướng dẫn | chỉ dẫn | lệnh (lập trình)","instruction","1022640"),
    ("インタープリテーション","インタープリテーション","n","sự diễn giải | sự thông dịch | cách hiểu | lý giải","interpretation","2857737"),
    ("インディペンデント","インディペンデント","adj-na|n","độc lập | tự chủ | riêng lẻ không phụ thuộc","independent","1023720"),
    ("エクスポージャー","エクスポージャー","n","sự phơi bày | mức độ tiếp xúc | độ phơi sáng | mức rủi ro","exposure","2662740"),
    ("エスカレーション","エスカレーション","n","sự leo thang | sự gia tăng | sự đẩy lên cấp cao hơn","escalation","1028570"),
    ("エモーション","エモーション","n","cảm xúc | xúc cảm | tình cảm","emotion","1030010"),
    ("オーガニゼーション","オーガニゼーション","n","tổ chức | cơ cấu tổ chức | bộ máy","organization","1031540"),
    ("オーソリティー","オーソリティー","n","quyền uy | chuyên gia uy tín | nhà chức trách | bậc thầy","authority","1031750"),
    ("オブリゲーション","オブリゲーション","n","nghĩa vụ | sự ràng buộc | trách nhiệm phải làm","obligation","1034990"),
    ("オムニバス","オムニバス","n","tuyển tập | phim/truyện nhiều phân đoạn | tổng hợp nhiều tác phẩm","omnibus","1035430"),
    ("カスタム","カスタム","adj-f|n|vs|vt","tùy chỉnh | đặt làm riêng | hải quan | thuế quan","custom | customs","1037310"),
    ("カテゴリ","カテゴリ","n","hạng mục | thể loại | phạm trù | loại","category","1037790"),
    ("クオリア","クオリア","n","cảm chất | trải nghiệm chủ quan | tính chất cảm nhận","qualia","2130090"),
    ("グルーヴ","グルーヴ","n","nhịp điệu cuốn hút | mạch cảm xúc âm nhạc | rãnh","groove","1047390"),
    ("コーポラティブ","コーポラティブ","n","hợp tác | hợp tác xã | sự cộng tác","cooperative","2829190"),
    ("コネクション","コネクション","n","mối quan hệ | sự kết nối | quan hệ thân quen","connection","1050490"),
    ("コミューン","コミューン","n","công xã | cộng đồng tự quản | đơn vị hành chính xã","commune","1050950"),
    ("コンサイス","コンサイス","n","súc tích | cô đọng | ngắn gọn | tinh giản","concise","1052020"),
    ("コンセントレーション","コンセントレーション","n","sự tập trung | sự chuyên chú | nồng độ","concentration","1052340"),
    ("コンソリデーション","コンソリデーション","n","sự hợp nhất | sự củng cố | sự sáp nhập","consolidation","2265000"),
    ("コンディション","コンディション","n","tình trạng | điều kiện | phong độ | thể trạng","condition","1052690"),
    ("サーティフィケート","サーティフィケート","n","giấy chứng nhận | chứng chỉ | văn bằng","certificate","2088210"),
    ("サポート","サポート","n|vs|vt","sự hỗ trợ | sự trợ giúp | ủng hộ | chống đỡ","support","1057630"),
    ("シェルター","シェルター","n","nơi trú ẩn | hầm trú | mái ấm | chỗ tạm lánh","shelter","1060060"),
    ("シンプル","シンプル","adj-na","đơn giản | giản dị | mộc mạc | gọn nhẹ","simple | plain","1063870"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
