# -*- coding: utf-8 -*-
"""Build N2 ready wave 005 — 72 freshly-curated N2 〜やか/〜らか adjectives + formal adverbs + 〜する/〜属/〜備."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-005.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("爽やか","さわやか","adj-na","sảng khoái | tươi mát | lưu loát (giọng)","fresh | refreshing | invigorating | fluent (speech)","1399520"),
    ("健やか","すこやか","adj-na|n","khỏe mạnh | tráng kiện | lành mạnh","vigorous | healthy | sound","1256110"),
    ("細やか","こまやか","adj-na","tinh tế | chu đáo | tỉ mỉ | đậm đà","tender | thoughtful | meticulous | deep (of colour)","1295550"),
    ("軽やか","かろやか","adj-na","nhẹ nhàng | thanh thoát | nhẹ nhõm","light | easy | non-serious","1578260"),
    ("大らか","おおらか","adj-na","rộng lượng | phóng khoáng | điềm đạm","placid | big-hearted | broad-minded | generous","1413000"),
    ("安らか","やすらか","adj-na|n","an yên | thanh thản | bình yên","peaceful | tranquil | calm | restful","1153690"),
    ("高らか","たからか","adj-na","vang vọng | dõng dạc | sang sảng","loud | sonorous | ringing","1616310"),
    ("なだらか","なだらか","adj-na","thoai thoải | dốc nhẹ | êm ả | từ tốn","gently sloping | gentle | gradual | smooth","1632290"),
    ("艶やか","あでやか","adj-na","kiều diễm | quyến rũ | lộng lẫy thanh tao","glamorous | charming | fascinatingly elegant","1177720"),
    ("煌びやか","きらびやか","adj-na","lộng lẫy | rực rỡ | chói lọi","gorgeous | dazzling | resplendent","1570480"),
    ("しなやか","しなやか","adj-na","dẻo dai | mềm mại | uyển chuyển | thanh nhã","supple | flexible | graceful | elegant","1566110"),
    ("伸びやか","のびやか","adj-na|n","thoải mái | thư thái | vô tư","comfortable | carefree","1358860"),
    ("冷ややか","ひややか","adj-na","lạnh lùng | lạnh nhạt | thờ ơ | điềm tĩnh","cold | chilly | indifferent | distant | composed","1602240"),
    ("密やか","ひそやか","adj-na","im ắng | lặng lẽ | lén lút","quiet | still | surreptitious","2116250"),
    ("漸く","ようやく","adv","cuối cùng | rốt cuộc | vừa vặn | dần dần","finally | at last | barely | gradually","1394600"),
    ("漸次","ぜんじ","adv","dần dần | từ từ | từng bước","gradually | little by little | incrementally","1394650"),
    ("順々","じゅんじゅん","adv|n","lần lượt | theo thứ tự | luân phiên","in order | in turn","1342230"),
    ("代々","だいだい","adv|n","đời đời | qua nhiều thế hệ | nối đời","for generations | from generation to generation","1606090"),
    ("屡々","しばしば","adv","thường xuyên | nhiều lần | hay","often | frequently | repeatedly","1005580"),
    ("折々","おりおり","adv","thỉnh thoảng | đôi khi | theo từng lúc","occasionally | now and then | from time to time","1589440"),
    ("引っ切り無し","ひっきりなし","adj-no|adj-na","liên tục | không ngớt | không dứt","continuous | incessant | without interruption","1169420"),
    ("専ら","もっぱら","adv|adj-no","chuyên | hoàn toàn | chủ yếu | một mực","wholly | solely | exclusively | mainly","1389740"),
    ("努めて","つとめて","adv","cố gắng | hết sức | siêng năng","as much as possible | to the best of one's ability | diligently","1445110"),
    ("極力","きょくりょく","adv","hết sức | tận lực | nỗ lực tối đa","to the utmost | to the best of one's ability","1240510"),
    ("精々","せいぜい","adv","nhiều nhất | cùng lắm | hết sức","at the most | at best | as much as possible","1596050"),
    ("高々","たかだか","adv","cao vút | cùng lắm | nhiều nhất | chỉ","high up | at most | at best | merely","1596810"),
    ("よもや","よもや","adv","chẳng lẽ | không lẽ nào | chắc không","surely (not) | certainly (not)","2069480"),
    ("概ね","おおむね","adv|n","đại thể | nhìn chung | hầu hết | ý chính","in general | mostly | roughly | on the whole | gist","1204410"),
    ("あべこべ","あべこべ","adj-no|adj-na|n","ngược lại | trái ngược | đảo lộn","contrary | opposite | inverse | back-to-front","1000470"),
    ("やけに","やけに","adv","quá mức | dữ dội | một cách lạ thường","awfully | desperately | unduly | extremely","1012770"),
    ("否応なしに","いやおうなしに","exp|adv","dù muốn hay không | bất đắc dĩ | bắt buộc","whether one likes it or not | inevitably | by force","1482970"),
    ("心なしか","こころなしか","exp","không hiểu sao | dường như | có lẽ","somehow | somewhat | seemingly","2699510"),
    ("我ながら","われながら","adv","tự mình thấy | dù tự nói cũng thấy","even if I say so myself","1196710"),
    ("生憎","あいにく","adj-na|adv","đáng tiếc | không may | tiếc là","unfortunately | sorry, but ...","1379210"),
    ("心ゆくまで","こころゆくまで","adv","thỏa thích | đã đời | cho thỏa lòng","to one's heart's content","1640050"),
    ("思う存分","おもうぞんぶん","exp|adv","thỏa thích | hết mình | tha hồ","to one's heart's content | heartily | without restraint","1609460"),
    ("心置きなく","こころおきなく","adv","thoải mái | không e dè | tự nhiên","freely | frankly | without reserve","1850310"),
    ("遠慮なく","えんりょなく","adv","không khách sáo | tự nhiên | thẳng thắn","without reservation | freely | frankly","1178460"),
    ("否応なく","いやおうなく","adv","dù muốn hay không | không có lựa chọn","whether one wants to or not | without choice","2727480"),
    ("称する","しょうする","vs-s|vt","tự xưng | gọi là | tự nhận | vờ là | tán dương","to call oneself | to claim | to profess | to feign | to praise","1351250"),
    ("類する","るいする","vs-s|vi","tương tự | giống như | cùng loại","to be similar (to) | to be akin (to) | to be like","1960080"),
    ("介する","かいする","vs-s|vt","thông qua (trung gian) | bận tâm | để ý","to use as an intermediary | to mind | to care","2006200"),
    ("期する","きする","vs-s|vt","định (thời điểm) | kỳ vọng | quyết tâm | hứa","to fix (a time) | to expect | to resolve (to do) | to pledge","2065140"),
    ("託する","たくする","vs-s|vt","gửi gắm | ủy thác | nhờ chuyển | mượn (để bày tỏ)","to entrust with | to have someone deliver | to express through","1596850"),
    ("課する","かする","vs-s|vt","áp (thuế, phạt) | giao (nhiệm vụ)","to impose (a tax, fine) | to assign (a task)","1195730"),
    ("服する","ふくする","vs-s|vi|vt","phục tùng | tuân theo | thụ (án) | uống (thuốc)","to obey | to submit to | to serve (a sentence) | to take (medicine)","1960150"),
    ("屈する","くっする","vs-s|vi|vt","khuất phục | chịu thua | nhụt chí | uốn cong","to yield | to give in | to be daunted | to bend","1246540"),
    ("属する","ぞくする","vs-s|vi","thuộc về | trực thuộc | chịu sự chi phối","to belong to | to come under | to be affiliated with","1405710"),
    ("配する","はいする","vs-s|vt","bố trí | sắp đặt | phân bổ | đày ải","to distribute | to arrange | to lay out | to banish","2180320"),
    ("要する","ようする","vs-s|vt","cần | đòi hỏi | mất (thời gian)","to need | to demand | to take | to require","1546610"),
    ("解する","かいする","vs-s|vt","hiểu | lĩnh hội | diễn giải","to understand | to appreciate | to interpret","2006240"),
    ("有する","ゆうする","vs-s|vt","có | sở hữu | nắm giữ","to have | to possess | to own","1540950"),
    ("擁する","ようする","vs-s|vt","ôm | có (lực lượng) | thống lĩnh | hậu thuẫn","to embrace | to possess | to command | to back up","1545740"),
    ("帰属","きぞく","n|vs|vi","quy thuộc | quy về | thuộc quyền | sở hữu","belonging | attribution | possession | jurisdiction","1221420"),
    ("所属","しょぞく","n|vs|vi","trực thuộc | thuộc (nhóm, tổ chức)","belonging to | affiliation (with) | being attached to","1343310"),
    ("従属","じゅうぞく","n|vs|vi","lệ thuộc | phụ thuộc | phục tùng","subordination | dependency","1335340"),
    ("付属","ふぞく","n|vs|vi","kèm theo | phụ thuộc | trực thuộc | (trường) phụ thuộc","being attached to | affiliated | attached school","1602700"),
    ("専属","せんぞく","n|vs|vi","độc quyền | thuộc riêng | chuyên thuộc","exclusive | attached to | specialist","1389820"),
    ("直属","ちょくぞく","n|vs|vi","trực thuộc | trực tiếp dưới quyền","direct control | direct supervision","1431390"),
    ("隷属","れいぞく","n|vs|vi","lệ thuộc | nô dịch | làm tôi tớ","subordination | servitude | vassalage","1557620"),
    ("兼ね備える","かねそなえる","v1|vt","hội tụ cả hai | có đủ cả | kết hợp","to have both | to possess both | to combine with","1256550"),
    ("充てる","あてる","v1|vt","dành cho | bố trí | phân bổ vào","to assign | to set aside","1334270"),
    ("宛てる","あてる","v1|vt","gửi đến | đề (tên người nhận)","to address","1153480"),
    ("配備","はいび","n|vs|vt","triển khai | bố trí | điều động","deployment | disposition | stationing","1473180"),
    ("完備","かんび","n|vs|vt|adj-na","trang bị đầy đủ | hoàn chỉnh | đầy đủ tiện nghi","being fully equipped | complete","1211560"),
    ("常備","じょうび","n|vs|vt","luôn sẵn có | trữ sẵn | thường trực","(always) having ready | standing | permanent","1798180"),
    ("予備","よび","n|adj-no","dự bị | dự phòng | chuẩn bị | sơ bộ","reserve | spare | preparation | preliminaries","1543320"),
    ("軍備","ぐんび","n","quân bị | trang bị quân sự | chuẩn bị chiến tranh","armaments | military preparations","1248870"),
    ("装備","そうび","n|vs|vt","trang bị | thiết bị","equipment","1402400"),
    ("不備","ふび","n|adj-na","thiếu sót | khiếm khuyết | chưa hoàn chỉnh","defect | deficiency | imperfection | inadequacy","1494610"),
    ("無防備","むぼうび","adj-na|adj-no","không phòng bị | sơ hở | không được bảo vệ","defenseless | unprotected | vulnerable","1530890"),
    ("防備","ぼうび","n|vs|vt","phòng bị | phòng thủ | chuẩn bị đối phó","defense | defensive preparations","1520580"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
