# -*- coding: utf-8 -*-
"""Build N1 ready wave 034 — 慣用句 + 四字熟語 (set 34)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-034.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("本腰を入れる","ほんごしをいれる","exp|v1","dốc toàn lực | bắt tay làm nghiêm túc | thực sự nghiêm túc | toàn tâm toàn ý","to set about in earnest | to put one's back into it","1908670"),
    ("眉に唾をつける","まゆにつばをつける","exp|v1","cảnh giác | đề phòng bị lừa | thận trọng dè chừng","to be on one's guard | to be wary of trickery","2670370"),
    ("水入らず","みずいらず","n|adj-no","riêng tư (gia đình/bạn thân) | chỉ người thân | quây quần riêng tư","among close family/friends only | private gathering","1611710"),
    ("水掛け論","みずかけろん","n","cãi nhau không hồi kết | tranh luận vô bổ | đôi co không lối thoát","endless argument | fruitless dispute","1371270"),
    ("身銭を切る","みぜにをきる","exp|v5r","tự bỏ tiền túi | móc hầu bao mình | tự chi trả","to pay out of one's own pocket","2401970"),
    ("三つ巴","みつどもえ","n","thế chân vạc | cuộc đấu tay ba | ba bên giằng co | thế ba phe","three-way fight | three-sided struggle","1299820"),
    ("身も心も","みもこころも","exp","cả thể xác lẫn tâm hồn | toàn tâm toàn ý | trọn vẹn cả người","body and soul | mind and body","2826044"),
    ("脈がある","みゃくがある","exp|v5r-i","còn hy vọng | còn cơ hội | chưa hết hẳn | còn nước còn tát","to have a chance | to be not altogether hopeless","2118050"),
    ("虫の居所が悪い","むしのいどころがわるい","exp|adj-i","đang bực bội | tâm trạng xấu | đang cáu | trở chứng khó tính","irritable | bad-tempered","1426720"),
    ("虫が知らせる","むしがしらせる","exp|v1","linh tính mách bảo | có điềm báo | dự cảm","to forebode | to have a presentiment","1426700"),
    ("胸三寸","むねさんずん","n","trong lòng | nội tâm | bụng dạ | tâm tư (胸三寸に納める)","one's heart | mind | feelings","1237900"),
    ("無理が通れば道理が引っ込む","むりがとおればどうりがひっこむ","exp|v5m","cường quyền thắng công lý | lẽ phải phải nhường sức mạnh | mạnh được yếu thua","where might is master, justice is servant","2419790"),
    ("目から鱗が落ちる","めからうろこがおちる","exp|v1","bừng tỉnh ngộ ra | vỡ lẽ | sáng mắt ra | chợt thông suốt","to see the light | to have the scales fall from one's eyes","2065100"),
    ("目くじらを立てる","めくじらをたてる","exp|v1","soi mói chuyện vặt | bắt bẻ tiểu tiết | nổi giận vì chuyện nhỏ","to find fault over trivial matters | to nitpick","2079460"),
    ("目処が立つ","めどがたつ","exp|v5t","có triển vọng | thấy hướng giải quyết | có hy vọng hoàn thành","the prospects look brighter | there is hope of accomplishing","2419890"),
    ("目鼻が付く","めはながつく","exp|v5k","đâu vào đấy | định hình | hòm hòm | xong phần cơ bản","to take concrete shape | for the main parts to be done","1535640"),
    ("目を奪われる","めをうばわれる","exp|v1","bị hút hồn | mê mẩn ngắm nhìn | không rời mắt | bị cuốn hút","to be captivated (visually)","2424390"),
    ("目を三角にする","めをさんかくにする","exp|vs-i","trợn mắt giận dữ | quắc mắt | nhìn hằm hằm | nổi đóa","to look daggers at | to be furious","1535220"),
    ("目論む","もくろむ","v5m|vt","mưu tính | toan tính | lập mưu | dự định","to plan | to scheme | to intend to do","1535720"),
    ("元も子もない","もともこもない","exp|adj-i","mất cả chì lẫn chài | trắng tay | xôi hỏng bỏng không | công cốc","losing everything | coming to nothing","2078990"),
    ("物議を醸す","ぶつぎをかもす","exp|v5s","gây tranh cãi | dấy lên dư luận | gây xôn xao | làm dậy sóng","to cause controversy | to cause a stir","1906870"),
    ("門外漢","もんがいかん","n","người ngoại đạo | tay ngang | kẻ nghiệp dư | người ngoài nghề","outsider | layman | amateur","1536150"),
    ("柳に風","やなぎにかぜ","exp","mềm mỏng tránh va chạm | dĩ nhu xử thế | nhẹ nhàng cho qua | uyển chuyển","handling things without making waves | taking in stride","2406290"),
    ("野放し","のばなし","n|adj-no","thả rông | buông lỏng | để mặc | thả nổi không kiểm soát","letting run loose | leaving unchecked","1537630"),
    ("藪から棒","やぶからぼう","exp|n","bất thình lình | ngang xương | như sét đánh ngang tai | đột ngột","a bolt from the blue | a complete surprise","2843894"),
    ("病膏肓に入る","やまいこうこうにいる","exp|v5r","bệnh vào cao hoang | bệnh nan y vô phương | nghiện ngập khó bỏ","to become incurably ill | to become a slave of a habit","1913380"),
    ("山を張る","やまをはる","exp|v5r","đánh cược | đoán mò | tủ (bài thi) | liều đoán","to speculate | to make an educated guess | to gamble","2526440"),
    ("横車を押す","よこぐるまをおす","exp|v5s","làm càn | cố chấp phi lý | ép buộc điều vô lý | ngang ngược","to push through an unreasonable idea | to have one's own way","1914960"),
    ("寄ってたかって","よってたかって","exp|adv","cả đám xúm vào | hùa nhau | xúm lại | đông người vây","ganging up on | joining forces (against)","2130850"),
    ("埒外","らちがい","n","ngoài phạm vi | ngoài giới hạn | vượt khuôn khổ | ngoài lề","out of bounds | beyond the pale","1822140"),
    ("立錐の余地もない","りっすいのよちもない","exp|adj-i","chật như nêm | không còn chỗ cắm dùi | kín mít | đông nghẹt","jam-packed | full to capacity","2083270"),
    ("溜飲が下がる","りゅういんがさがる","exp|v5r","hả dạ | nhẹ nhõm | hả hê | trút được bực dọc","to feel relieved | to feel satisfied","1852380"),
    ("両天秤","りょうてんびん","n","bắt cá hai tay | hai lựa chọn | nước đôi | đứng giữa hai ngả","two alternatives | playing both sides","1553880"),
    ("路頭に迷う","ろとうにまよう","exp|v5u","màn trời chiếu đất | lang thang đầu đường | mất kế sinh nhai | bơ vơ không nơi nương tựa","to be left without means | to be rendered homeless","2130980"),
    ("論陣を張る","ろんじんをはる","exp|v5r","lập luận vững vàng | bày binh bố trận tranh luận | tranh biện quyết liệt","to take a firm stand in argument","1917130"),
    ("若気の至り","わかげのいたり","exp|n","bồng bột tuổi trẻ | nông nổi thời trẻ | sai lầm tuổi trẻ","youthful indiscretion | youthful folly","2131010"),
    ("笑い種","わらいぐさ","n","trò cười | điều lố bịch | đề tài bị giễu cợt | trò hề","laughingstock","1351320"),
    ("我に返る","われにかえる","exp|v5r","hoàn hồn | định thần lại | tỉnh trí | bình tâm trở lại","to come to one's senses | to calm down","2125250"),
    ("合いの手","あいのて","n","đoạn nhạc đệm | tiếng hô đệm | lời chêm vào | hòa giọng","interlude (in music) | chiming in | interjection","1284450"),
    ("相槌を打つ","あいづちをうつ","exp|v5t","ậm ừ phụ họa | gật gù tán thành | đế lời tỏ ý lắng nghe","to throw in interjections to show one is listening","1401230"),
    ("青写真","あおじゃしん","n","bản kế hoạch | bản thiết kế | viễn cảnh tương lai | bản phác thảo","blueprint | plan (for the future)","1750060"),
    ("垢抜け","あかぬけ","n|vs|vi","sành điệu | tinh tế | thanh lịch | phong cách | thoát quê","refinement | style | sophistication","1837190"),
    ("足蹴","あしげ","n","đá | đối xử tệ bạc | chà đạp | hắt hủi","kick | treating someone poorly","1404850"),
    ("足手まとい","あしでまとい","adj-na|n","vướng chân vướng tay | gánh nặng | cản trở | của nợ","impediment | burden | hindrance","1663120"),
    ("足並みを揃える","あしなみをそろえる","exp|v1","đồng tâm nhất trí | bước cùng nhịp | thống nhất hành động | đồng lòng","to keep step with | to get on the same page","2841276"),
    ("頭打ち","あたまうち","n","chạm trần | đến ngưỡng | bão hòa | tới hạn không tăng nữa","reaching a peak | plateauing | maxing out","1582330"),
    ("徒花","あだばな","n","hoa không kết trái | thứ phô trương rỗng tuếch | hào nhoáng vô thực","sterile flower | something flashy with no substance","1444450"),
    ("痘痕も笑窪","あばたもえくぼ","exp","yêu nên tốt ghét nên xấu | tình yêu mù quáng | yêu thì rỗ cũng thành lúm","love is blind","2089340"),
    ("一矢報いる","いっしむくいる","exp|v1","đáp trả | gỡ gạc một đòn | phản công | trả miếng","to retaliate | to strike back","2859706"),
    ("一目散","いちもくさん","n","chạy bán sống bán chết | chạy thục mạng | phóng hết tốc lực","running at full speed | as fast as one can","1166980"),
    ("一蓮托生","いちれんたくしょう","n","cùng hội cùng thuyền | chung số phận | sống chết có nhau | đồng cam cộng khổ","sharing one's fate with another | being in the same boat","1167440"),
    ("居丈高","いたけだか","adj-na|n","hống hách | kẻ cả | trịch thượng | nạt nộ","high-handed | overbearing","1717800"),
    ("一巻","いっかん","n","một cuốn | một tập | tập một | một cuộn","one volume | one roll | first volume","1161510"),
    ("一辺倒","いっぺんとう","n-suf|n","ngả hẳn về một phía | dốc toàn lực vào | thiên về tuyệt đối | nhất biên đảo","complete devotion to | total commitment to","1166440"),
    ("意馬心猿","いばしんえん","n","tâm viên ý mã | dục vọng khó kiềm | lòng dạ bất an","being unable to control one's passions and desires","1156780"),
    ("韋編三絶","いへんさんぜつ","n|vs","đọc đi đọc lại | nghiền ngẫm kỹ | đọc đến sờn sách | đọc say mê","reading repeatedly and carefully","2041790"),
    ("有為","うい","n","vô thường | biến đổi do nghiệp | thăng trầm cuộc đời | hữu vi","perpetual change | vicissitudes of life","1859830"),
    ("雨後の筍","うごのたけのこ","exp","măng mọc sau mưa | mọc lên như nấm | xuất hiện ồ ạt liên tiếp","things turning up one after another | mushrooming","2093090"),
    ("牛の歩み","うしのあゆみ","exp|n","chậm như rùa | bước đi ì ạch | nhích từng chút | lê thê","a snail's pace","1845280"),
    ("後ろ髪を引かれる","うしろがみをひかれる","exp|v1","lưu luyến không nỡ | bịn rịn | dùng dằng nửa ở nửa đi | quyến luyến","to do with painful reluctance | to feel torn","2102250"),
    ("内弁慶","うちべんけい","n","khôn nhà dại chợ | hùng hổ ở nhà nhút nhát bên ngoài | anh hùng xó bếp","being a lion at home but a mouse outside","1459160"),
    ("瓜二つ","うりふたつ","adj-no","giống như đúc | giống hệt | như hai giọt nước | y chang","exactly alike | like two peas in a pod","1172580"),
    ("紆余","うよ","n","quanh co | khúc khuỷu | ngoằn ngoèo | uốn lượn (紆余曲折)","meandering | winding","1570400"),
    ("雲泥の差","うんでいのさ","exp|n","khác một trời một vực | chênh lệch khủng khiếp | một chín một mười khác xa","a world of difference | a wide gap","1173240"),
    ("大手を振る","おおでをふる","exp|v5r","nghênh ngang | đường hoàng công khai | vung tay sải bước | trơ trẽn ngang nhiên","to act freely | to be brazen | to swing one's arms boldly","2102440"),
    ("大風呂敷","おおぶろしき","n","khoác lác | nói phét | vẽ vời hoành tráng | thùng rỗng kêu to | ba hoa","big talk | vain boasting | blowing one's own trumpet","1414860"),
    ("お先棒","おさきぼう","n","tay sai | con rối | kẻ bị lợi dụng | chân chạy việc","a flunky | a cat's-paw | a tool","1694090"),
    ("押し問答","おしもんどう","n|vs|vi","đôi co qua lại | cãi vã giằng co | tranh luận dai dẳng | lời qua tiếng lại","arguing back and forth | a verbal tug-of-war","1180420"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
