# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-052.csv -- 16 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-052.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("鳥居","とりい","N4","n",
        "cổng torii (cổng đền Shinto) | cổng thần đạo",
        "torii (Shinto shrine archway)",
        "1430280",
        "鳥居をくぐる。","とりいをくぐる。",
        "Đi qua cổng torii.","Pass through the torii gate."),
    row("冷ます","さます","N4","v5s|vt",
        "để nguội | làm nguội | hạ nhiệt độ",
        "to cool (e.g. from a high temperature to room temperature) | to let cool | to dampen (e.g. enthusiasm)",
        "1556740",
        "スープを冷ます。","すーぷをさます。",
        "Để nguội súp.","Let the soup cool down."),
    row("子犬","こいぬ","N4","n",
        "cún con | chó con | chó nhỏ",
        "puppy | small dog",
        "1592900",
        "子犬と遊ぶ。","こいぬとあそぶ。",
        "Chơi với cún con.","Play with a puppy."),
    row("仏壇","ぶつだん","N4","n",
        "bàn thờ Phật (trong nhà Nhật) | am thờ Phật gia đình",
        "Buddhist (household) altar",
        "1502200",
        "仏壇にお参りする。","ぶつだんにおまいりする。",
        "Thắp hương bàn thờ Phật.","Pray at the household Buddhist altar."),
    row("土台","どだい","N4","n|adv",
        "nền móng | cơ sở | căn bản | từ đầu | từ ban đầu",
        "foundation | base | basis | from the beginning | from the outset | by nature",
        "1445450",
        "土台を固める。","どだいをかためる。",
        "Củng cố nền móng.","Solidify the foundation."),
    row("外壁","がいへき","N4","n",
        "tường ngoài | vách ngoài | tường bên ngoài",
        "outer wall",
        "1204100",
        "外壁を塗り直す。","がいへきをぬりなおす。",
        "Sơn lại tường ngoài.","Repaint the outer wall."),
    row("子猫","こねこ","N4","n",
        "mèo con | mèo nhỏ",
        "kitten | small cat",
        "1593380",
        "子猫が生まれた。","こねこがうまれた。",
        "Mèo con ra đời.","Kittens were born."),
    row("子羊","こひつじ","N4","n",
        "cừu con | chiên non",
        "lamb",
        "1593390",
        "子羊が草を食べる。","こひつじがくさをたべる。",
        "Cừu con ăn cỏ.","Lambs eat grass."),
    row("柱","はしら","N4","n|suf",
        "cột trụ | cột nhà | điểm tựa | trụ cột | (đơn vị đếm Phật, thần)",
        "pillar | post | support | prop | mainstay | counter for buddhas, gods, noble persons",
        "1426480",
        "柱が太い。","はしらがふとい。",
        "Cột trụ to chắc.","The pillars are thick."),
    row("柱","ちゅう","N4","n",
        "ngựa đàn koto | hình trụ | lăng trụ",
        "bridge (of a koto, etc.) | cylinder | prism",
        "2424140",
        "琴の柱。","ことのちゅう。",
        "Ngựa đàn koto.","The bridge of a koto."),
    row("柱","じゅう","N4","n",
        "phím đàn biwa | ngựa đàn biwa",
        "fret (of a biwa)",
        "2424150",
        "琵琶の柱。","びわのじゅう。",
        "Phím đàn biwa.","The fret of a biwa."),
    row("武道","ぶどう","N4","n",
        "võ thuật | võ đạo | nghệ thuật chiến đấu Nhật",
        "martial arts | military arts | Bushido",
        "1498880",
        "武道を習う。","ぶどうをならう。",
        "Học võ thuật Nhật.","Learn martial arts."),
    row("能","のう","N4","n",
        "năng khiếu | tài năng | khả năng | noh (kịch truyền thống Nhật)",
        "talent | gift | function | noh (theatre) | noh play",
        "1470120",
        "能を鑑賞する。","のうをかんしょうする。",
        "Thưởng thức kịch noh.","Appreciate a noh play."),
    row("花道","はなみち","N4","n",
        "hành lang sân khấu kabuki | kết thúc vinh quang | hoa đạo (cắm hoa)",
        "elevated walkway through the audience to the stage | honourable end to one's career",
        "1194830",
        "花道を歩く。","はなみちをあるく。",
        "Đi trên hành lang sân khấu kabuki.","Walk the hanamichi."),
    row("茶道","さどう","N4","n",
        "trà đạo | nghi lễ pha trà Nhật | nghệ thuật uống trà",
        "tea ceremony | Way of Tea | sadō",
        "1422770",
        "茶道を習う。","さどうをならう。",
        "Học trà đạo.","Learn the tea ceremony."),
    row("落語","らくご","N4","n",
        "rakugo | kịch hài kể chuyện truyền thống Nhật",
        "rakugo | traditional Japanese comic storytelling | comic story (told by a rakugo performer)",
        "1548720",
        "落語を聞く。","らくごをきく。",
        "Nghe kịch rakugo.","Listen to rakugo."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
