# -*- coding: utf-8 -*-
"""Build N2 ready wave 030 — diseases, symptoms, wounds, medical treatment."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-030.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("肺炎","はいえん","n","viêm phổi","pneumonia","1472880"),
    ("胃炎","いえん","n","viêm dạ dày","gastritis","1158520"),
    ("腸炎","ちょうえん","n","viêm ruột","enteritis","1622980"),
    ("肝炎","かんえん","n","viêm gan","hepatitis","1214640"),
    ("皮膚炎","ひふえん","n","viêm da","dermatitis","2081520"),
    ("関節炎","かんせつえん","n","viêm khớp","arthritis","1215980"),
    ("気管支炎","きかんしえん","n","viêm phế quản","bronchitis","1791310"),
    ("鼻炎","びえん","n","viêm mũi","rhinitis | nasal inflammation","1486810"),
    ("中耳炎","ちゅうじえん","n","viêm tai giữa","otitis media | middle-ear infection","1424440"),
    ("結膜炎","けつまくえん","n","viêm kết mạc | đau mắt đỏ","conjunctivitis","1255000"),
    ("膀胱炎","ぼうこうえん","n","viêm bàng quang","cystitis","1571030"),
    ("化膿","かのう","n|vs|vi","mưng mủ | làm mủ | nhiễm trùng","suppuration | festering | infection","1187260"),
    ("膿","うみ","n","mủ | ung nhọt | điều xấu xa","pus | corruption | evils","1470560"),
    ("潰瘍","かいよう","n","vết loét | loét","ulcer","1636160"),
    ("糜爛","びらん","n|vs|vi","loét | trợt da | xói mòn | ung nhọt","sore | erosion | ulceration","1570380"),
    ("壊死","えし","n|vs|vi","hoại tử","necrosis","1781260"),
    ("浮腫","むくみ","n","phù | sưng | phù nề","swelling | edema | dropsy","1497480"),
    ("発疹","ほっしん","n|vs|vi","phát ban | nổi mẩn","rash | eruption","1477600"),
    ("湿疹","しっしん","n","chàm | eczema | mẩn ngứa","eczema | rash","1320450"),
    ("蕁麻疹","じんましん","n","mề đay | nổi mày đay","hives | nettle rash | urticaria","1571740"),
    ("水疱","すいほう","n","bóng nước | mụn nước | phỏng nước","blister","1737320"),
    ("痒み","かゆみ","n","ngứa | sự ngứa ngáy","itch | itching | itchiness","2007700"),
    ("吹き出物","ふきでもの","n","mụn | nốt sần | nhọt | mụn trứng cá","(skin) eruption | rash | pimple | acne","1602520"),
    ("古傷","ふるきず","n","vết thương cũ | sẹo cũ | ký ức đau buồn | lỗi lầm xưa","old wound | scar | painful memory","1603040"),
    ("擦り傷","すりきず","n","vết trầy | vết xước | vết trầy xước","scratch | graze | abrasion","1595820"),
    ("切り傷","きりきず","n","vết cắt | vết rạch | vết đứt","cut | gash | incision","1591800"),
    ("刺し傷","さしきず","n","vết đâm | vết chích | vết cắn (côn trùng)","stab wound | puncture wound | sting","1306440"),
    ("裂傷","れっしょう","n","vết rách | vết thương hở","laceration","1558640"),
    ("骨粗鬆症","こつそしょうしょう","n","loãng xương","osteoporosis","1288660"),
    ("高血圧","こうけつあつ","n","cao huyết áp | tăng huyết áp","high blood pressure | hypertension","1283450"),
    ("低血圧","ていけつあつ","n","huyết áp thấp","low blood pressure","1434410"),
    ("心臓病","しんぞうびょう","n","bệnh tim | bệnh tim mạch","heart disease | cardiopathy","1793880"),
    ("脳卒中","のうそっちゅう","n","đột quỵ | tai biến mạch máu não","stroke | cerebral haemorrhage","1470490"),
    ("脳梗塞","のうこうそく","n","nhồi máu não | đột quỵ thiếu máu","cerebral infarction | (ischemic) stroke","1470420"),
    ("心筋梗塞","しんきんこうそく","n","nhồi máu cơ tim","heart attack | myocardial infarction","1648630"),
    ("動脈硬化","どうみゃくこうか","n","xơ vữa động mạch | xơ cứng động mạch | sự cứng nhắc","arteriosclerosis | institutional rigidity","1451600"),
    ("肥満","ひまん","n|vs|vi|adj-no","béo phì | mập | thừa cân","corpulence | fatness | obesity","1484300"),
    ("痩身","そうしん","n","thân hình mảnh khảnh | giảm cân | thon gọn","slim figure | slimming | weight reduction","1835350"),
    ("栄養失調","えいようしっちょう","n|adj-no","suy dinh dưỡng","malnutrition","1174030"),
    ("脱水症状","だっすいしょうじょう","n","triệu chứng mất nước","dehydration","1998040"),
    ("熱中症","ねっちゅうしょう","n","say nắng | sốc nhiệt","heatstroke","2097700"),
    ("食中毒","しょくちゅうどく","n","ngộ độc thực phẩm","food poisoning","1609950"),
    ("伝染病","でんせんびょう","n","bệnh truyền nhiễm | bệnh lây | dịch bệnh","contagious disease | infectious disease","1442130"),
    ("風土病","ふうどびょう","n","bệnh địa phương | bệnh đặc hữu vùng","endemic disease | local disease","1500030"),
    ("難病","なんびょう","n","bệnh nan y | bệnh khó chữa","intractable disease | serious disease","1461080"),
    ("奇病","きびょう","n","bệnh lạ | bệnh hiếm gặp","strange disease | rare disease","1219470"),
    ("急病","きゅうびょう","n","bệnh cấp tính | bệnh đột ngột","sudden illness","1228950"),
    ("仮病","けびょう","n|adj-no","bệnh giả vờ | giả ốm | giả bệnh","feigned illness","1188000"),
    ("病める","やめる","exp|adj-f|v1|vi","ốm yếu | bệnh tật | đau nhức","sick | ill | ailing | to ache","2519800"),
    ("患う","わずらう","v5u|vt|vi","mắc bệnh | bị bệnh | ốm đau","to be ill | to suffer from","1212200"),
    ("病む","やむ","v5m|vi|vt","đổ bệnh | mắc bệnh | u sầu | tổn thương tâm lý","to fall ill | to suffer from | to be depressed","1490210"),
    ("往診","おうしん","n|vs|vt|vi","khám tại nhà | bác sĩ đến nhà khám","doctor's visit | house call","1179710"),
    ("問診","もんしん","n|vs|vt","hỏi bệnh | khai thác bệnh sử","interview (with a doctor) | history taking","1648860"),
    ("触診","しょくしん","n|vs|vt","sờ nắn khám | xúc chẩn","palpation","1691740"),
    ("聴診","ちょうしん","n|vs|vt|adj-no","nghe (tim phổi) | thính chẩn","auscultation","1800560"),
    ("健診","けんしん","n","khám sức khỏe | kiểm tra sức khỏe định kỳ","health checkup | medical examination","2861042"),
    ("施術","せじゅつ","n|vs|vi","thực hiện điều trị | làm thủ thuật | phẫu thuật","treatment | surgical operation | procedure","1646600"),
    ("止血","しけつ","n|vs|vi","cầm máu","stopping of bleeding | hemostasis","1310690"),
    ("殺菌","さっきん","n|vs|vt","diệt khuẩn | khử trùng | tiệt trùng","sterilization | disinfection | pasteurization","1299070"),
    ("滅菌","めっきん","n|vs|vt|vi","tiệt trùng | khử khuẩn hoàn toàn","sterilization","1641410"),
    ("除菌","じょきん","n|vs|vt","khử khuẩn | loại bỏ vi khuẩn","disinfection | sterile filtration","2234880"),
    ("献血","けんけつ","n|vs|vi","hiến máu","blood donation","1258430"),
    ("採血","さいけつ","n|vs|vt|vi","lấy máu | rút máu","drawing blood | collecting blood","1294770"),
    ("切開","せっかい","n|vs|vt","rạch | mổ | phẫu thuật cắt mở","incision | operation | section","1384980"),
    ("縫合","ほうごう","n|vs|vt","khâu | khâu vết thương | khâu nối","sewing together | stitching up | suture","1517710"),
    ("鎮痛","ちんつう","n|adj-no|vs|vt|vi","giảm đau | làm dịu cơn đau","pain relief | killing pain","2241710"),
    ("解熱","げねつ","n|vs|vi|adj-no","hạ sốt | giảm sốt","lowering a fever | alleviation of fever","1199220"),
    ("禁忌","きんき","n|vs|vt|adj-no","điều cấm kỵ | chống chỉ định | kiêng kỵ","taboo | contraindication","1241510"),
    ("抗生物質","こうせいぶっしつ","n","kháng sinh","antibiotic","1278940"),
    ("鎮痛剤","ちんつうざい","n","thuốc giảm đau | thuốc an thần","analgesic | painkiller | sedative","1432140"),
    ("解熱剤","げねつざい","n","thuốc hạ sốt","fever medicine | antipyretic","1199230"),
    ("睡眠薬","すいみんやく","n","thuốc ngủ","sleeping pill","1372400"),
    ("予防接種","よぼうせっしゅ","n","tiêm phòng | chủng ngừa | tiêm chủng","vaccination | immunization","1543690"),
    ("免疫力","めんえきりょく","n","sức đề kháng | khả năng miễn dịch","immune strength | immunity","2741870"),
    ("持久力","じきゅうりょく","n","sức bền | sức dẻo dai | sự bền bỉ","stamina | tenacity","1769910"),
    ("回復力","かいふくりょく","n","khả năng phục hồi | sức hồi phục | sự dẻo dai","power of recovery | resilience","1199750"),
    ("快癒","かいゆ","n|vs|vi","bình phục | khỏi bệnh | hồi phục","recovery | convalescence","1805770"),
    ("余命","よめい","n","tuổi thọ còn lại | thời gian sống còn lại","remainder of one's life | time left to live","1544570"),
    ("末期","まっき","n","cuối kỳ | giai đoạn cuối | thời kỳ cuối (bệnh)","last stage | final stages | terminal stage","1604040"),
    ("臨終","りんじゅう","n","lúc lâm chung | giờ hấp hối | giây phút cuối đời","deathbed | dying hour | one's death","1555630"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
