# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-044.csv -- 15 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-044.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("お辞儀","おじぎ","N4","n|vs|vi",
        "cúi chào | cái cúi đầu chào | cúi người chào hỏi",
        "bow | bowing",
        "1002030",
        "深くお辞儀する。","ふかくおじぎする。",
        "Cúi chào thật sâu.","Bow deeply."),
    row("敬意","けいい","N4","n",
        "sự kính trọng | lòng tôn kính | sự tôn trọng",
        "respect | honour | honor",
        "1250720",
        "敬意を表す。","けいいをあらわす。",
        "Bày tỏ lòng tôn kính.","Show respect."),
    row("月末","げつまつ","N4","n|adv",
        "cuối tháng | cuối kỳ tháng",
        "end of the month",
        "1255840",
        "月末に支払う。","げつまつにしはらう。",
        "Thanh toán vào cuối tháng.","Pay at the end of the month."),
    row("見出し","みだし","N4","n",
        "tiêu đề | đầu đề | tít bài | từ mục (trong từ điển)",
        "heading | headline | title | caption | index | headword",
        "1259710",
        "大きな見出し。","おおきなみだし。",
        "Tiêu đề lớn.","A large headline."),
    row("今頃","いまごろ","N4","n|adv",
        "vào giờ này | khoảng thời gian này | giờ này (mới biết thì đã muộn)",
        "about this time | about now",
        "1289160",
        "今頃になって後悔する。","いまごろになってこうかいする。",
        "Giờ này mới hối hận thì đã muộn.","Regretting now, at this late stage."),
    row("段落","だんらく","N4","n",
        "đoạn văn | đoạn | điểm dừng | kết thúc",
        "paragraph | end | stopping place | conclusion",
        "1419980",
        "段落ごとに読む。","だんらくごとによむ。",
        "Đọc từng đoạn văn.","Read paragraph by paragraph."),
    row("注釈","ちゅうしゃく","N4","n|vs|vt",
        "chú thích | ghi chú | chú giải",
        "notes | comment | remark | annotation",
        "1426610",
        "注釈を加える。","ちゅうしゃくをくわえる。",
        "Thêm chú thích.","Add annotations."),
    row("溶け込む","とけこむ","N4","v5m|vi",
        "hòa tan vào | hòa nhập | pha lẫn vào | thấm vào",
        "to melt into | to dissolve into | to merge into | to blend into (surroundings) | to fit in",
        "1546090",
        "地域に溶け込む。","ちいきにとけこむ。",
        "Hòa nhập vào cộng đồng địa phương.","Blend into the local community."),
    row("礼節","れいせつ","N4","n",
        "lễ tiết | phép tắc | lịch sự | phép lịch sự",
        "decorum | propriety | politeness",
        "1557540",
        "礼節を守る。","れいせつをまもる。",
        "Giữ gìn lễ tiết.","Maintain proper etiquette."),
    row("一昨年","おととし","N4","n|adv",
        "hai năm trước | năm kia",
        "year before last",
        "1576060",
        "一昨年の出来事。","おととしのできごと。",
        "Sự kiện xảy ra hai năm trước.","An event from the year before last."),
    row("一昨日","おととい","N4","n|adv",
        "hôm kia | ngày kia (trước hôm qua)",
        "day before yesterday",
        "1576050",
        "一昨日に会った。","おとといにあった。",
        "Đã gặp nhau vào hôm kia.","Met the day before yesterday."),
    row("下書き","したがき","N4","n|vs|vt",
        "bản nháp | bản thảo | bản phác thảo",
        "draft | rough copy",
        "1185370",
        "下書きを書く。","したがきをかく。",
        "Viết bản nháp.","Write a draft."),
    row("清書","せいしょ","N4","n|vs|vt",
        "bản sạch | bản viết lại sạch sẽ | bản cuối",
        "fair copy | clean copy",
        "1378240",
        "清書して提出する。","せいしょしててていしゅつする。",
        "Viết lại sạch sẽ rồi nộp.","Write a clean copy and submit it."),
    row("索引","さくいん","N4","n",
        "bảng tra cứu | chỉ mục | mục lục cuối sách",
        "index (in a book)",
        "1298320",
        "索引で調べる。","さくいんでしらべる。",
        "Tra cứu qua mục lục.","Look up in the index."),
    row("風習","ふうしゅう","N4","n",
        "phong tục | tập tục | tập quán địa phương",
        "custom | local custom | practice",
        "1499890",
        "地域の風習を守る。","ちいきのふうしゅうをまもる。",
        "Gìn giữ phong tục địa phương.","Maintain local customs."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
