# -*- coding: utf-8 -*-
"""Build N2 ready wave 057 — four-character idioms (yojijukugo)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-057.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("一石二鳥","いっせきにちょう","exp","một mũi tên trúng hai đích | nhất cử lưỡng tiện","killing two birds with one stone","1164160"),
    ("一長一短","いっちょういったん","n","có hơn có kém | lợi bất cập hại | được mặt này mất mặt kia","merits and demerits | advantages and disadvantages","1164870"),
    ("一進一退","いっしんいったい","n|vs|vi|adj-no","lúc tiến lúc lùi | giằng co | khi lên khi xuống","now advancing and now retreating | ebb and flow","1163690"),
    ("一喜一憂","いっきいちゆう","n|vs|vi","khi vui khi lo | thấp thỏm vui buồn | lúc mừng lúc lo","alternating between happiness and anxiety","1161670"),
    ("一朝一夕","いっちょういっせき","n","một sớm một chiều | trong chốc lát","in a day | in a brief space of time","1164850"),
    ("一日千秋","いちじつせんしゅう","n","một ngày dài tựa ngàn thu | mong mỏi từng giây","each moment seeming like an eternity","1576270"),
    ("一心不乱","いっしんふらん","adj-na|n","một lòng một dạ | toàn tâm toàn ý | chuyên chú","wholeheartedly | with intense concentration","1163610"),
    ("一網打尽","いちもうだじん","n","tóm gọn một mẻ | bắt trọn ổ","round-up | wholesale arrest","1166920"),
    ("一刀両断","いっとうりょうだん","n","chặt phăng một nhát | quyết đoán dứt khoát","cutting in two with a single stroke | decisive action","1165200"),
    ("一目瞭然","いちもくりょうぜん","adj-na|adj-no|n","nhìn là biết ngay | rõ như ban ngày","obvious | (as) clear as day","1167000"),
    ("二束三文","にそくさんもん","adj-no|n","rẻ như bèo | rẻ mạt","dirt cheap | very cheap","1599870"),
    ("三日坊主","みっかぼうず","n","cả thèm chóng chán | làm ba bữa rồi bỏ | đầu voi đuôi chuột","person who cannot stick to anything | unsteady worker","1301380"),
    ("四苦八苦","しくはっく","n|vs|vi","khốn đốn trăm bề | vật lộn vất vả | tứ khổ bát khổ","being in dire distress | being hard pressed","1307150"),
    ("四面楚歌","しめんそか","n|adj-no","bốn bề thọ địch | bị cô lập tứ phía","being surrounded by enemies on all sides","1307390"),
    ("五里霧中","ごりむちゅう","adj-no|n","mù mịt phương hướng | mò mẫm trong sương | hoàn toàn bế tắc","totally at a loss | in a fog | bewildered","1268670"),
    ("七転八倒","しちてんばっとう","n|vs|vi","lăn lộn vì đau | quằn quại đau đớn","writhing in agony","1615010"),
    ("十人十色","じゅうにんといろ","exp|n","mỗi người mỗi ý | chín người mười ý","everyone has his own tastes | different strokes for different folks","1334840"),
    ("千差万別","せんさばんべつ","adj-na|adj-no|n","muôn hình vạn trạng | vô vàn khác biệt","an infinite variety of | multifarious","1388840"),
    ("千変万化","せんぺんばんか","n|vs|vi|adj-no","thiên biến vạn hóa | biến đổi khôn lường","innumerable changes | infinite variety","1389210"),
    ("千載一遇","せんざいいちぐう","adj-no|n","cơ hội ngàn năm có một | dịp may hiếm có","once-in-a-lifetime (opportunity) | golden opportunity","1388870"),
    ("百発百中","ひゃっぱつひゃくちゅう","n","bách phát bách trúng | trăm trận trăm thắng","always hitting the bull's-eye | infallible","1488420"),
    ("百戦錬磨","ひゃくせんれんま","adj-no","dày dạn trận mạc | lão luyện | từng trải","battle-worn | hard-bitten | very experienced","1602170"),
    ("朝令暮改","ちょうれいぼかい","n|vs|vi","sáng ra lệnh chiều đổi | chính sách thất thường","(orders or laws) being revised often | unsettled course of action","1428570"),
    ("日進月歩","にっしんげっぽ","n|adj-no|vs|vi","tiến bộ không ngừng | ngày một tiến nhanh","steady progress | rapid advance","1464230"),
    ("無我夢中","むがむちゅう","n","quên cả bản thân | mải mê say sưa | nhập tâm","losing oneself | being absorbed (in)","1529720"),
    ("半信半疑","はんしんはんぎ","n|adj-no","bán tín bán nghi | nửa tin nửa ngờ","half in doubt | dubious | incredulous","1479460"),
    ("危機一髪","ききいっぱつ","exp|n","ngàn cân treo sợi tóc | trong gang tấc | suýt nữa","by a hair's breadth | in the nick of time","1218460"),
    ("起死回生","きしかいせい","n|adj-no","cải tử hoàn sinh | lội ngược dòng từ tuyệt vọng","revival from the brink of death | recovering from a hopeless situation","1223800"),
    ("弱肉強食","じゃくにくきょうしょく","n","mạnh được yếu thua | cá lớn nuốt cá bé | luật rừng","the law of the jungle | the strong prey on the weak","1324880"),
    ("適者生存","てきしゃせいぞん","n","ai thích nghi thì tồn tại | sinh tồn của kẻ thích nghi","survival of the fittest","1734970"),
    ("自業自得","じごうじとく","exp|adj-na|adj-no|n","gieo gió gặt bão | tự làm tự chịu | gậy ông đập lưng ông","reap what you sow | getting one's just deserts","1317570"),
    ("因果応報","いんがおうほう","n","nhân quả báo ứng | gieo nhân nào gặt quả nấy","retribution | karma | just deserts","1822250"),
    ("悪戦苦闘","あくせんくとう","n|vs|vi","vật lộn gian khổ | chiến đấu cam go | chật vật","hard fighting | fighting against heavy odds","1152160"),
    ("切磋琢磨","せっさたくま","n|vs|vi","dùi mài kinh sử | cùng nhau cố gắng | thi đua rèn luyện","diligent application | mutual encouragement to improve","1385250"),
    ("意気投合","いきとうごう","n|vs|vi","tâm đầu ý hợp | hợp gu | hợp tính nhau","hit it off with | mutual understanding","1156510"),
    ("意気消沈","いきしょうちん","n|vs|vi","ỉu xìu | nhụt chí | chán nản ngã lòng","low spirits | dejection | despondency","1156460"),
    ("意気揚々","いきようよう","adj-t|adv-to","hớn hở đắc thắng | nghênh ngang đắc ý | dương dương tự đắc","triumphant | exultant | in high spirits","1587120"),
    ("得意満面","とくいまんめん","adj-na|adj-no|n","mặt mày hớn hở | vẻ đắc thắng | dương dương tự mãn","triumphant air | smugness","1770380"),
    ("自画自賛","じがじさん","n|vs|vt","tự khen mình | mèo khen mèo dài đuôi | tự tâng bốc","singing one's own praises","1317470"),
    ("自給自足","じきゅうじそく","n|vs|vt","tự cung tự cấp","self-sufficiency","1317550"),
    ("独立独歩","どくりつどっぽ","n|adj-no","tự lập tự cường | tự thân vận động","self-reliance | self-help","1456100"),
    ("独立自尊","どくりつじそん","n","tinh thần độc lập tự tôn","(spirit of) independence and self-respect","1691360"),
    ("公明正大","こうめいせいだい","adj-na|n","công minh chính đại | quang minh chính trực","fair and just | open and honest | aboveboard","1274860"),
    ("公平無私","こうへいむし","adj-na|adj-no|n","công bằng vô tư | chí công vô tư","impartiality | fair play","1274660"),
    ("正々堂々","せいせいどうどう","adj-no|adj-t|adv-to","đường đường chính chính | quang minh chính đại","fair and square | open and aboveboard","1596030"),
    ("品行方正","ひんこうほうせい","adj-na|adj-no|n","đức hạnh ngay thẳng | hạnh kiểm tốt | đoan chính","irreproachable conduct | high morals","1805500"),
    ("質実剛健","しつじつごうけん","n|adj-na","mộc mạc cương nghị | giản dị mà kiên cường","unaffected and sincere, with fortitude and vigor","1320700"),
    ("温厚篤実","おんこうとくじつ","n|adj-na","ôn hòa chân thật | hiền hậu thành thực","having a gentle and sincere personality","2030180"),
    ("誠心誠意","せいしんせいい","adv|n|adj-no","thành tâm thành ý | hết lòng hết dạ | toàn tâm toàn ý","in all sincerity | whole-hearted devotion","1381190"),
    ("全身全霊","ぜんしんぜんれい","n","toàn tâm toàn lực | dốc cả thân tâm | hết mình","complete devotion | body and soul | one's best","1662630"),
    ("粉骨砕身","ふんこつさいしん","n|vs|vi","dốc hết sức mình | tận lực | nỗ lực hết mình","making one's best exertions","1504790"),
    ("不眠不休","ふみんふきゅう","n|adj-no","thức trắng không nghỉ | làm việc ngày đêm","no sleep or rest | working day and night","1495030"),
    ("東奔西走","とうほんせいそう","n|vs|vi","chạy ngược chạy xuôi | bôn ba khắp nơi | đôn đáo","busying oneself about | being on the move","1448200"),
    ("右往左往","うおうさおう","n|vs|vi|adj-no","chạy nháo nhào | rối rít loạn xạ | nhốn nháo","moving about in confusion | going every which way","1171050"),
    ("七転八起","しちてんはっき","n|vs|vi","thất bại không nản | ngã đâu đứng đó | bền chí đến cùng","not giving up | keeping at it until one succeeds","2858831"),
    ("不撓不屈","ふとうふくつ","n|adj-no","kiên cường bất khuất | không nao núng","tenacity | indomitableness | dauntlessness","1495510"),
    ("堅忍不抜","けんにんふばつ","adj-na|n","kiên nhẫn bền bỉ | nhẫn nại vững vàng","indomitable perseverance | invincible fortitude","1257200"),
    ("初志貫徹","しょしかんてつ","n","kiên định ý chí ban đầu | theo đuổi đến cùng chí hướng","carrying out one's original intention","1342760"),
    ("有言実行","ゆうげんじっこう","n|vs","nói được làm được | giữ đúng lời hứa","carrying out one's words | being as good as one's word","2054520"),
    ("言行一致","げんこういっち","n|vs|adj-no","lời nói đi đôi với việc làm | nhất quán lời và việc","consistency between speech and action","1264480"),
    ("首尾一貫","しゅびいっかん","n|vs","nhất quán từ đầu đến cuối | trước sau như một","consistent | unchanging from beginning to end","1696720"),
    ("理路整然","りろせいぜん","adj-t|adv-to","mạch lạc | logic chặt chẽ | lập luận rõ ràng","logical | cogent | well-reasoned","1795870"),
    ("明朗快活","めいろうかいかつ","n|adj-na","vui tươi cởi mở | lạc quan hoạt bát","cheerful and openhearted","2054210"),
    ("天真爛漫","てんしんらんまん","adj-na|n","ngây thơ hồn nhiên | trong sáng chất phác","innocent | naive | artless | childlike","1439480"),
    ("傍若無人","ぼうじゃくぶじん","n|adj-na|adj-no","ngông nghênh coi trời bằng vung | bất chấp người khác","behaving outrageously | arrogance | insolence","1518880"),
    ("厚顔無恥","こうがんむち","adj-na|n","mặt dày vô liêm sỉ | trơ trẽn trắng trợn","shameless | brazen and unscrupulous","1275420"),
    ("唯我独尊","ゆいがどくそん","n","duy ngã độc tôn | tự cao tự đại | ta là nhất","self-conceit | self-centeredness | vainglory","1538940"),
    ("傲岸不遜","ごうがんふそん","n|adj-na","kiêu căng ngạo mạn | xấc xược hống hách","haughty arrogance","1742070"),
    ("優柔不断","ゆうじゅうふだん","adj-na|adj-no|n","do dự thiếu quyết đoán | ưu nhu bất quyết","indecisive | irresolute | vacillating","1539260"),
    ("意志薄弱","いしはくじゃく","adj-na|adj-no|n","ý chí yếu đuối | thiếu nghị lực | bạc nhược","weak-willed | lacking will power","1156600"),
    ("日和見主義","ひよりみしゅぎ","n","chủ nghĩa cơ hội | ngả theo chiều gió","opportunism","1464970"),
    ("二転三転","にてんさんてん","n|vs|vi","thay đổi xoành xoạch | lật đi lật lại | tráo trở liên tục","changing again and again | being in a state of flux","2051550"),
    ("紆余曲折","うよきょくせつ","n|vs|vi","quanh co khúc khuỷu | lắm trắc trở | nhiều biến cố","twists and turns | ups and downs | complications","1570410"),
    ("栄枯盛衰","えいこせいすい","n","thịnh suy của đời người | bãi bể nương dâu | hưng vong","ups and downs of life | vicissitudes of fortune","1173910"),
    ("盛者必衰","じょうしゃひっすい","exp","thịnh ắt có suy | kẻ mạnh rồi cũng tàn","even the prosperous inevitably decay","1580900"),
    ("諸行無常","しょぎょうむじょう","n","vạn vật vô thường | mọi sự đều đổi thay","all things must pass | all worldly things are impermanent","1344260"),
    ("喜怒哀楽","きどあいらく","n","hỉ nộ ái ố | mọi cung bậc cảm xúc","human emotions (joy, anger, grief, pleasure)","1218870"),
    ("酔生夢死","すいせいむし","n","sống say chết mộng | phí hoài cuộc đời vô nghĩa","idling one's life away | living to no purpose","1372680"),
    ("夢幻泡影","むげんほうよう","n","mộng huyễn bào ảnh | đời người hư ảo phù du","a dream, illusion, bubble, shadow (transience of life)","2846460"),
    ("電光石火","でんこうせっか","n|adj-no","nhanh như chớp | trong nháy mắt | thần tốc","flash | instant | lightning (speed)","1443270"),
    ("疾風迅雷","しっぷうじんらい","n","thần tốc như gió cuốn sấm vang | nhanh như chớp","with lightning speed","1320620"),
    ("猪突猛進","ちょとつもうしん","n|vs","lao đầu liều lĩnh | xông pha bất chấp | hùng hục tiến tới","headlong rush | rushing recklessly","1427060"),
    ("勇猛果敢","ゆうもうかかん","n|adj-na","dũng mãnh quả cảm | gan dạ quyết đoán","daring and resolute | dauntless courage","2032960"),
    ("大胆不敵","だいたんふてき","adj-na|n","gan lì táo bạo | cả gan không sợ trời | bạo gan","daring | fearless | audacious | dauntless","1786190"),
    ("明鏡止水","めいきょうしすい","n","tâm như gương sáng nước lặng | lòng thanh thản tĩnh tại","clear and serene (mind)","1674700"),
    ("無味乾燥","むみかんそう","adj-na|n","khô khan nhạt nhẽo | tẻ ngắt | vô vị","dull | dry | insipid | boring","1530900"),
    ("単純明快","たんじゅんめいかい","n|adj-na","đơn giản rõ ràng | rõ ràng minh bạch","simple and clear | plain and simple","2031880"),
    ("複雑怪奇","ふくざつかいき","adj-na|n","phức tạp khó hiểu | rắc rối kỳ bí","complicated and mysterious","1827960"),
    ("奇想天外","きそうてんがい","adj-na|adj-no|n","kỳ quặc khó tin | ý tưởng quái dị | độc đáo bất ngờ","fantastic | bizarre | incredible","1219430"),
    ("荒唐無稽","こうとうむけい","adj-na|n","hoang đường vô lý | nhảm nhí phi lý","absurd | nonsensical | preposterous","1281600"),
    ("誇大妄想","こだいもうそう","n|adj-no","hoang tưởng tự đại | ảo tưởng vĩ cuồng","megalomania | delusions of grandeur","1267800"),
    ("妄言多謝","もうげんたしゃ","exp","xin lượng thứ lời nói liều | tha lỗi cho lời thiếu suy nghĩ","kindly excuse my reckless remarks","2040840"),
    ("我田引水","がでんいんすい","n","co kéo về phần mình | bòn nước vào ruộng mình | vụ lợi","seeking one's own interests | straining to suit one's own interests","1196890"),
    ("本末転倒","ほんまつてんとう","n|vs|vi","đảo lộn gốc ngọn | đặt cày trước trâu | lẫn lộn chính phụ","putting the cart before the horse | mistaking means for end","1603640"),
    ("主客転倒","しゅかくてんとう","n|vs","đảo lộn chủ khách | đặt cày trước trâu | lẫn lộn trọng yếu","reversing the order of importance | putting the cart before the horse","1594810"),
    ("時期尚早","じきしょうそう","adj-na|adj-no|n","còn quá sớm | chưa đến lúc | non thời cơ","premature","1316070"),
    ("前代未聞","ぜんだいみもん","n|adj-no","chưa từng có | xưa nay hiếm | vô tiền khoáng hậu","unheard-of | unprecedented","1393580"),
    ("空前絶後","くうぜんぜつご","n|adj-no","vô tiền khoáng hậu | có một không hai","the first and probably the last (so marvelous or horrible)","1245710"),
    ("言語道断","ごんごどうだん","adj-na|adj-no|n","quá quắt không lời nào tả nổi | không thể chấp nhận | hết chỗ nói","outrageous | preposterous | inexcusable","1264450"),
    ("以心伝心","いしんでんしん","n|adj-no","tâm truyền tâm | hiểu nhau không cần lời | ý hợp tâm đầu","tacit understanding | telepathy","1155130"),
    ("意味深長","いみしんちょう","adj-na|n","thâm thúy | hàm ý sâu xa | đầy ẩn ý","with profound (hidden) meaning | suggestive","1156820"),
    ("理非曲直","りひきょくちょく","n","đúng sai phải trái | sự công minh đúng sai","the rights and wrongs (of a case)","1550110"),
    ("是々非々","ぜぜひひ","n","công tâm phân định đúng sai | thẳng thắn vô tư","fair and just | calling a spade a spade","1596260"),
    ("公私混同","こうしこんどう","n|vs","công tư lẫn lộn | nhập nhằng việc công việc tư","mixing of public and private affairs","2028220"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
