# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-018.csv — 50 rows (Wave 9 pool batch)."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-018.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("ネットワーク","ネットワーク","N4","n",
        "mạng lưới | mạng",
        "network",
        "1093120",
        "ネットワークを構築します。","ネットワークをこうちくします。","Tôi xây dựng mạng lưới.","I build a network."),
    row("結局","けっきょく","N4","adv|n|adj-no",
        "sau cùng | cuối cùng | rốt cuộc | kết thúc",
        "after all | in the end | ultimately | eventually | conclusion | end",
        "1254730",
        "結局失敗します。","けっきょくしっぱいします。","Rốt cuộc tôi thất bại.","In the end I fail."),
    row("血液","けつえき","N4","n",
        "máu | máu huyết",
        "blood",
        "1255120",
        "血液を検査します。","けつえきをけんさします。","Tôi xét nghiệm máu.","I test the blood."),
    row("常に","つねに","N4","adv",
        "luôn luôn | thường xuyên | liên tục",
        "always | constantly | at all times | habitually",
        "1355970",
        "常に努力します。","つねにどりょくします。","Tôi luôn luôn cố gắng.","I always make an effort."),
    row("信号機","しんごうき","N4","n",
        "đèn giao thông | đèn tín hiệu | thiết bị tín hiệu",
        "traffic light | traffic signal | signal (mechanism) | semaphore (apparatus)",
        "1359260",
        "信号機を守ります。","しんごうきをまもります。","Tôi tuân thủ đèn giao thông.","I obey the traffic light."),
    row("成し遂げる","なしとげる","N4","v1|vt",
        "hoàn thành | đạt được | thực hiện được | tiến hành đến cùng",
        "to accomplish | to achieve | to complete | to carry out | to carry through",
        "1375550",
        "目標を成し遂げます。","もくひょうをなしとげます。","Tôi hoàn thành mục tiêu.","I accomplish the goal."),
    row("盛る","さかる","N4","v5r|vi",
        "trở nên mạnh mẽ | phát triển mạnh | thịnh vượng | hưng thịnh | động dục (động vật)",
        "to become vigorous | to gain force | to become more active | to prosper | to thrive | to flourish | to be in heat | to be in rut | to copulate",
        "1379730",
        "ビジネスが盛ります。","ビジネスがさかります。","Kinh doanh phát triển mạnh.","The business flourishes."),
    row("踏まえる","ふまえる","N4","v1|vt",
        "dựa trên | lấy làm cơ sở | tính đến | dựa vào",
        "to be based on | to take into account | to build upon | to have origin in | to have one's feet firmly planted on | to plant oneself on",
        "1450110",
        "事実を踏まえて判断します。","じじつをふまえてはんだんします。","Tôi quyết định dựa trên sự thật.","I make a judgment based on the facts."),
    row("難民","なんみん","N4","n|n-suf",
        "người tị nạn | người di dời | người bị mắc kẹt",
        "refugee | displaced person | person inconvenienced by (lack of something, etc.) | person who is stuck (in a place or situation)",
        "1461110",
        "難民を支援します。","なんみんをしえんします。","Tôi hỗ trợ người tị nạn.","I support refugees."),
    row("認める","したためる","N4","v1|vt",
        "viết (thư, tài liệu) | ghi chép | ăn (bữa ăn)",
        "to write (e.g. a letter) | to draw up (a document) | to take down (e.g. notes) | to have (lunch, dinner, etc.) | to eat",
        "1467520",
        "手紙を認めます。","てがみをしたためます。","Tôi viết bức thư.","I write a letter."),
    row("利子","りし","N4","n",
        "lãi suất | tiền lãi",
        "interest (on a deposit, loan, etc.)",
        "1549560",
        "利子を払います。","りしをはらいます。","Tôi trả tiền lãi.","I pay the interest."),
    row("やり直す","やりなおす","N4","v5s|vt",
        "làm lại | bắt đầu lại | làm từ đầu | tiếp tục lại",
        "to do over again | to redo | to start over | to remake | to resume | to recommence",
        "1605620",
        "仕事をやり直します。","しごとをやりなおします。","Tôi làm lại công việc.","I redo the work."),
    row("言い換える","いいかえる","N4","v1|vt",
        "diễn đạt bằng lời khác | nói cách khác | diễn giải lại | đổi cách nói",
        "to say in other words | to put another way | to express in different words | to reword | to rephrase",
        "1610580",
        "難しい言葉を言い換えます。","むずかしいことばをいいかえます。","Tôi diễn giải lại từ khó.","I rephrase the difficult word."),
    row("どんどん","どんどん","N4","adv|adv-to",
        "liên tục | nhanh chóng | ào ạt | tiếng trống (ùm ùm)",
        "drumming (noise) | beating | pounding | banging | rapidly | quickly | steadily | continuously | one after the other | in succession",
        "1009320",
        "どんどん進みます。","どんどんすすみます。","Tôi tiến triển nhanh chóng.","I advance rapidly."),
    row("もどかしい","もどかしい","N4","adj-i",
        "bực bội | khó chịu | đáng thất vọng | bứt rứt | nôn nóng",
        "irritating | irritated | frustrating | vexing | (feeling things are) not quick enough | (feeling) too slow-going | (feeling) impatient | tantalizing | tantalising",
        "1012640",
        "もどかしい気持ちです。","もどかしいきもちです。","Tôi cảm thấy bứt rứt.","I feel frustrated."),
    row("ソフトウェア","ソフトウェア","N4","n",
        "phần mềm",
        "software",
        "1075510",
        "ソフトウェアをインストールします。","ソフトウェアをインストールします。","Tôi cài đặt phần mềm.","I install software."),
    row("データベース","データベース","N4","n",
        "cơ sở dữ liệu",
        "database",
        "1081350",
        "データベースを管理します。","データベースをかんりします。","Tôi quản lý cơ sở dữ liệu.","I manage the database."),
    row("デフレ","デフレ","N4","n",
        "giảm phát | giảm phát kinh tế",
        "deflation",
        "1083780",
        "デフレが続きます。","デフレがつづきます。","Giảm phát kéo dài.","Deflation continues."),
    row("ハードウェア","ハードウェア","N4","n",
        "phần cứng",
        "hardware",
        "1094490",
        "ハードウェアを交換します。","ハードウェアをこうかんします。","Tôi thay thế phần cứng.","I replace the hardware."),
    row("為替","かわせ","N4","n",
        "hối phiếu | séc | ngoại hối",
        "money order | draft | exchange (e.g. foreign)",
        "1157330",
        "為替レートを確認します。","かわせレートをかくにんします。","Tôi kiểm tra tỷ giá ngoại hối.","I check the exchange rate."),
    row("移民","いみん","N4","n|vs|vi",
        "di dân | nhập cư | di cư | người nhập cư | người di cư",
        "immigration | emigration | immigrant | emigrant",
        "1158440",
        "移民を受け入れます。","いみんをうけいれます。","Chúng tôi tiếp nhận người nhập cư.","We accept immigrants."),
    row("株式","かぶしき","N4","n",
        "cổ phần | cổ phiếu",
        "share (in a company) | stock",
        "1208970",
        "株式を購入します。","かぶしきをこうにゅうします。","Tôi mua cổ phiếu.","I purchase stock."),
    row("建てる","たてる","N4","v1|vt",
        "xây dựng | xây cất",
        "to build | to construct",
        "1257330",
        "家を建てます。","いえをたてます。","Tôi xây nhà.","I build a house."),
    row("見直す","みなおす","N4","v5s|vt|vi",
        "xem xét lại | xét duyệt lại | nhìn nhận lại tích cực hơn | cải thiện | phục hồi",
        "to look at again | to re-examine (policy, estimate, plan, etc.) | to review | to get a better opinion of | to see in a more positive light | to improve | to recover",
        "1259900",
        "計画を見直します。","けいかくをみなおします。","Tôi xem xét lại kế hoạch.","I review the plan."),
    row("やり遂げる","やりとげる","N4","v1|vt",
        "hoàn thành | tiến hành đến cùng | thực hiện trọn vẹn",
        "to accomplish | to finish | to carry through | to follow through",
        "1260430",
        "任務をやり遂げます。","にんむをやりとげます。","Tôi hoàn thành nhiệm vụ.","I accomplish the mission."),
    row("言い出す","いいだす","N4","v5s|vt",
        "bắt đầu nói | nêu ra | đưa ra ý kiến | đề xuất",
        "to begin to say | to start talking | to broach (a matter) | to bring up | to come out with | to be the first to say | to suggest (doing) | to propose",
        "1264080",
        "意見を言い出します。","いけんをいいだします。","Tôi đưa ra ý kiến.","I bring up an opinion."),
    row("好況","こうきょう","N4","n",
        "kinh tế phồn thịnh | điều kiện thuận lợi | bùng nổ kinh tế | thị trường sôi động",
        "prosperous (economic) conditions | favourable conditions | (economic) boom | thriving business | brisk market",
        "1277620",
        "好況が続きます。","こうきょうがつづきます。","Kinh tế phồn thịnh kéo dài.","The economic boom continues."),
    row("差別","さべつ","N4","n|vs|vt",
        "phân biệt | phân biệt đối xử | kỳ thị",
        "distinction | differentiation | discrimination | discrimination (against people)",
        "1291410",
        "差別に反対します。","さべつにはんたいします。","Tôi phản đối phân biệt đối xử.","I oppose discrimination."),
    row("最終","さいしゅう","N4","adj-no|n",
        "cuối cùng | chung cuộc | chuyến cuối (tàu, xe buýt)",
        "last | final | closing | last train (bus, flight, etc.; of the day)",
        "1293940",
        "最終電車に乗ります。","さいしゅうでんしゃにのります。","Tôi lên chuyến tàu cuối.","I take the last train."),
    row("刺さる","ささる","N4","v5r|vi",
        "ghim vào | đâm vào | mắc kẹt (trong) | gây xúc động cảm xúc",
        "to stick into (of something with a sharp point) | to prick | to pierce | to get stuck (in) | to lodge (in) | to resonate emotionally | to move",
        "1306390",
        "とげが刺さります。","とげがささります。","Gai đâm vào.","A thorn sticks in."),
    row("刺す","さす","N4","v5s|vt",
        "đâm | chọc | ghim | châm | đốt (côn trùng) | khâu | thêu",
        "to pierce | to stab | to prick | to stick | to thrust | to sting | to bite | to sew | to stitch | to embroider | to pole (a boat) | to catch (with a limed pole) | to put (a runner) out | to pick off",
        "1306470",
        "針で刺します。","はりでさします。","Tôi đâm bằng kim.","I prick with a needle."),
    row("煮る","にる","N4","v1|vt",
        "luộc | nấu chín | hầm | om",
        "to boil | to simmer | to stew | to seethe",
        "1322540",
        "野菜を煮ます。","やさいをにます。","Tôi luộc rau.","I boil vegetables."),
    row("取り組む","とりくむ","N4","v5m|vi",
        "vật lộn với | đấu tranh với | giải quyết (vấn đề) | nỗ lực giải quyết",
        "to grapple with | to wrestle with | to engage in a bout | to be matched against | to tackle (e.g. a problem) | to come to grips with | to work hard on",
        "1326820",
        "問題に取り組みます。","もんだいにとりくみます。","Tôi giải quyết vấn đề.","I tackle the problem."),
    row("取り替える","とりかえる","N4","v1|vt",
        "trao đổi | hoán đổi | trao đổi hàng | thay thế",
        "to exchange | to swap | to barter | to trade | to replace | to substitute",
        "1326830",
        "部品を取り替えます。","ぶひんをとりかえます。","Tôi thay thế linh kiện.","I replace the parts."),
    row("手に入れる","てにいれる","N4","exp|v1",
        "lấy được | đạt được | có được | giành được",
        "to obtain | to get | to procure | to win | to secure",
        "1327230",
        "情報を手に入れます。","じょうほうをてにいれます。","Tôi có được thông tin.","I obtain information."),
    row("手放す","てばなす","N4","v5s|vt",
        "buông tay | thả ra | từ bỏ | nhường lại | bán đi | xa cách",
        "to let go of | to release | to drop | to part with (e.g. a possession) | to relinquish | to spare | to sell | to send away (e.g. one's child) | to let go | to part with | to temporarily stop working",
        "1328370",
        "大切なものを手放します。","たいせつなものをてばなします。","Tôi từ bỏ thứ quý giá.","I let go of something precious."),
    row("需要","じゅよう","N4","n",
        "nhu cầu | cầu (kinh tế)",
        "demand | need",
        "1330450",
        "需要が増えます。","じゅようがふえます。","Nhu cầu tăng lên.","Demand increases."),
    row("渋滞","じゅうたい","N4","n|vs|vi",
        "tắc đường | ùn tắc giao thông | trì hoãn | đình trệ",
        "(traffic) congestion | traffic jam | gridlock | delay | stagnation",
        "1335570",
        "渋滞に巻き込まれます。","じゅうたいにまきこまれます。","Tôi bị kẹt trong ùn tắc giao thông.","I get stuck in a traffic jam."),
    row("書き直す","かきなおす","N4","v5s|vt",
        "viết lại | chép lại | làm bản sạch",
        "to write (a book, etc.) over again | to make a fair copy | to rewrite",
        "1343830",
        "報告書を書き直します。","ほうこくしょをかきなおします。","Tôi viết lại báo cáo.","I rewrite the report."),
    row("昇進","しょうしん","N4","n|vs|vi",
        "thăng chức | thăng tiến | thăng cấp",
        "promotion | advancement | rising in rank",
        "1349780",
        "昇進します。","しょうしんします。","Tôi được thăng chức.","I get a promotion."),
    row("切り刻む","きりきざむ","N4","v5m|vt",
        "chặt nhỏ | băm nhỏ | thái nhỏ | cắt vụn",
        "to hew | to chop up | to mangle | to mince",
        "1384130",
        "野菜を切り刻みます。","やさいをきりきざみます。","Tôi thái nhỏ rau.","I mince the vegetables."),
    row("相応しい","ふさわしい","N4","adj-i",
        "phù hợp | thích hợp | xứng đáng",
        "appropriate | adequate | suitable | fitting | worthy",
        "1400850",
        "相応しい候補者です。","ふさわしいこうほしゃです。","Đây là ứng viên phù hợp.","This is a suitable candidate."),
    row("統計","とうけい","N4","n|vs|vt",
        "thống kê",
        "statistics",
        "1449710",
        "統計を分析します。","とうけいをぶんせきします。","Tôi phân tích thống kê.","I analyze statistics."),
    row("頭痛","ずつう","N4","n",
        "đau đầu",
        "headache",
        "1450890",
        "頭痛があります。","ずつうがあります。","Tôi bị đau đầu.","I have a headache."),
    row("同時に","どうじに","N4","exp|adv|conj",
        "đồng thời | cùng lúc | ngay lúc | và cùng lúc đó",
        "at the same time | at once | simultaneously | concurrently | just as ... | the moment ... | just after ... | (but) at the same time | as well as | also | on the other hand",
        "1452510",
        "二つのことを同時にします。","ふたつのことをどうじにします。","Tôi làm hai việc cùng lúc.","I do two things simultaneously."),
    row("読み直す","よみなおす","N4","v5s|vt",
        "đọc lại",
        "to read (a book, etc.) over again",
        "1456300",
        "本を読み直します。","ほんをよみなおします。","Tôi đọc lại cuốn sách.","I read the book over again."),
    row("濡れる","ぬれる","N4","v1|vi",
        "bị ướt | ướt",
        "to get wet",
        "1467620",
        "雨で濡れます。","あめでぬれます。","Tôi bị ướt vì mưa.","I get wet from the rain."),
    row("半島","はんとう","N4","n",
        "bán đảo | Bán đảo Triều Tiên",
        "peninsula | Korea",
        "1479770",
        "半島を旅行します。","はんとうをりょこうします。","Tôi du lịch bán đảo.","I travel the peninsula."),
    row("飛び越える","とびこえる","N4","v1|vt",
        "nhảy qua | vượt qua | bay qua | vượt bậc | bỏ qua",
        "to jump over | to leap over | to clear | to fly over | to fly across | to jump ahead (of someone) | to skip over | to leapfrog",
        "1485250",
        "障害を飛び越えます。","しょうがいをとびこえます。","Tôi vượt qua trở ngại.","I leap over the obstacle."),
    row("傾く","かたむく","N4","v5k|vi",
        "nghiêng | ngả | có xu hướng | nghiêng về phía | suy tàn | tắt lặn (mặt trời)",
        "to incline toward | to slant | to lurch | to heel over | to be disposed to | to trend toward | to be prone to | to go down (sun, moon) | to sink | to decline | to wane | to ebb | to fall away | to tend (towards) | to be inclined (to)",
        "1578210",
        "建物が傾きます。","たてものがかたむきます。","Tòa nhà bị nghiêng.","The building tilts."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
