# -*- coding: utf-8 -*-
"""Build N2 ready wave 001 — 76 freshly-curated N2 formal verbs + 〜する/〜ずる verbs + onomatopoeia."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-001.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("案じる","あんじる","v1|vt","lo lắng | bận tâm | nghĩ ra (kế) | cân nhắc","to be anxious (about) | to worry | to think out (a plan)","1154780"),
    ("危ぶむ","あやぶむ","v5m|vt","lo ngại | e ngại | nghi ngại","to fear | to have misgivings about | to be apprehensive about","1218410"),
    ("労る","いたわる","v5r|vt","an ủi | quan tâm | chăm sóc | ghi nhận công lao","to sympathize with | to care for | to console | to appreciate (efforts)","1560240"),
    ("営む","いとなむ","v5m|vt","kinh doanh | điều hành | tiến hành | sống (cuộc đời)","to run (a business) | to conduct | to lead (a life)","1173420"),
    ("戒める","いましめる","v1|vt","răn dạy | cảnh cáo | cấm | khiển trách","to warn against | to admonish | to prohibit | to rebuke","1200650"),
    ("偽る","いつわる","v5r|vt|vi","nói dối | giả vờ | làm giả | lừa dối","to lie | to feign | to falsify | to deceive","1224390"),
    ("拝む","おがむ","v5m|vt","vái lạy | chắp tay cầu | bái lạy | khẩn cầu","to assume a praying posture | to do reverence | to beg","1472230"),
    ("賄う","まかなう","v5u|vt","chu cấp | trang trải | nuôi (gia đình) | cấp ăn","to supply | to cover (costs) | to finance | to provide meals","1562510"),
    ("束ねる","たばねる","v1|vt","bó lại | buộc thành bó | quản lý | thống lĩnh","to tie up in a bundle | to manage | to govern","1581320"),
    ("司る","つかさどる","v5r|vt","phụ trách | quản lý | cai quản | điều hành","to be in charge of | to manage | to administer | to govern","1306630"),
    ("培う","つちかう","v5u|vt","bồi dưỡng | nuôi dưỡng | vun đắp","to cultivate | to foster","1473350"),
    ("連なる","つらなる","v5r|vi","nối tiếp | trải dài | xếp hàng | có liên quan","to stretch out | to stand in a row | to be linked","1559240"),
    ("繕う","つくろう","v5u|vt","vá | sửa | chỉnh trang | che đậy","to mend | to repair | to tidy up | to cover up (a mistake)","1396480"),
    ("蔑む","さげすむ","v5m|vt","khinh thường | coi rẻ | xem thường","to scorn | to despise | to look down on","1510260"),
    ("蘇る","よみがえる","v5r|vi","hồi sinh | sống lại | được khôi phục | (ký ức) ùa về","to be resurrected | to be revived | to be recalled (memories)","1606020"),
    ("滅びる","ほろびる","v1|vi","diệt vong | suy tàn | tuyệt diệt","to go to ruin | to be destroyed | to die out | to perish","1603610"),
    ("滅ぼす","ほろぼす","v5s|vt","tiêu diệt | hủy diệt | làm sụp đổ","to destroy | to overthrow | to ruin","1603620"),
    ("栄える","さかえる","v1|vi","thịnh vượng | phồn vinh | hưng thịnh","to prosper | to flourish | to thrive","1173860"),
    ("衰える","おとろえる","v1|vi","suy yếu | suy tàn | suy thoái | tàn lụi","to become weak | to decline | to decay | to waste away","1372430"),
    ("老いる","おいる","v1|vi","già đi | lão hóa","to age | to grow old","1560990"),
    ("老ける","ふける","v1|vi","già đi (vẻ ngoài) | trông già","to age | to grow old (in appearance)","1561010"),
    ("潤う","うるおう","v5u|vi","ẩm ướt | thấm ướt | sung túc | được lợi","to become moist | to profit | to become prosperous","1341790"),
    ("潤す","うるおす","v5s|vt","làm ẩm | làm giàu | đem lại lợi ích","to moisten | to enrich | to benefit","1341810"),
    ("覆る","くつがえる","v5r|vi","lật úp | bị lật đổ | bị đảo ngược (phán quyết)","to topple over | to capsize | to be overturned | to be reversed","1501500"),
    ("損ねる","そこねる","v1|vt","làm hại | làm tổn thương | lỡ mất (cơ hội)","to harm | to hurt | to miss one's chance to (do)","1406690"),
    ("損じる","そんじる","v1|vi","làm hại | làm hỏng | gây tổn thương","to harm | to injure | to damage","1406680"),
    ("労する","ろうする","vs-s|vi|vt","vất vả | lao nhọc | bắt làm việc","to labor | to put to work","2255190"),
    ("即する","そくする","vs-s|vi","phù hợp với | thích ứng | dựa trên","to conform to | to be adapted to | to be based on","1404090"),
    ("反する","はんする","vs-s|vi","trái với | đi ngược | vi phạm | nổi loạn","to be contrary to | to violate | to disobey","1480080"),
    ("徹する","てっする","vs-s|vi","xuyên thấu | dốc lòng | tận tụy (suốt)","to penetrate | to devote oneself to | to do throughout","1598340"),
    ("没する","ぼっする","vs-s|vi|vt","chìm | lặn | qua đời | tịch thu","to sink | to set | to pass away | to confiscate","2013080"),
    ("帰する","きする","vs-s","quy về | dẫn đến | quy kết | đổ (lỗi)","to come to (in the end) | to attribute | to blame","2082270"),
    ("害する","がいする","vs-s|vt","làm hại | gây tổn hại | cản trở | giết","to injure | to harm | to hinder | to kill","1609490"),
    ("逸する","いっする","vs-s|vt","để lỡ (cơ hội) | bỏ sót | đi chệch","to miss (a chance) | to overlook | to deviate","1587490"),
    ("処する","しょする","vs-s|vt","xử lý | đối phó | xử (án) | trừng phạt","to manage | to deal with | to sentence | to punish","2008380"),
    ("博する","はくする","vs-s|vt","giành được | thu được | lan rộng (danh tiếng)","to win | to gain | to spread (one's name)","2012880"),
    ("化する","かする","vs-s|vt|vi","biến thành | hóa thành | cảm hóa","to change into | to transform into | to influence","1186740"),
    ("喫する","きっする","vs-s|vt","ăn | uống | hút | hứng chịu (thất bại)","to eat | to drink | to smoke | to suffer (e.g. defeat)","1226380"),
    ("封じる","ふうじる","v1|vt","niêm phong | phong tỏa | ngăn chặn | bịt","to seal | to prevent | to block | to seal off","1980510"),
    ("転じる","てんじる","v1|vt|vi","chuyển | xoay | thay đổi","to turn | to shift | to change","1441040"),
    ("減じる","げんじる","v1|vi|vt","giảm | giảm bớt | trừ đi","to decrease | to reduce | to subtract","2008020"),
    ("案ずる","あんずる","vz|vt","lo lắng | bận tâm | nghĩ ra (kế)","to be anxious about | to worry | to think out (a plan)","1586940"),
    ("重んずる","おもんずる","vz|vt","coi trọng | tôn trọng | đề cao","to honor | to respect | to esteem","1335950"),
    ("軽んずる","かろんずる","vz|vt","coi thường | xem nhẹ | khinh","to despise | to belittle | to look down on","2010790"),
    ("甘んずる","あまんずる","vz|vi","cam chịu | bằng lòng | an phận","to content oneself with | to be resigned to","2577820"),
    ("存ずる","ぞんずる","vz|vt","biết | nghĩ | cho rằng (khiêm nhường)","to know | to think | to believe (humble)","1983710"),
    ("信ずる","しんずる","vz|vt","tin | tin tưởng | tin cậy","to believe | to place trust in | to have faith in","1359070"),
    ("あざ笑う","あざわらう","v5u|vt","cười nhạo | giễu cợt | chế giễu","to laugh at | to ridicule | to mock | to sneer at","1565610"),
    ("のさばる","のさばる","v5r|vi","làm càn | tác oai tác quái | lộng hành","to throw one's weight around | to act high-handedly","2251810"),
    ("ふやける","ふやける","v1|vi","nở ra (ngấm nước) | mềm nhũn | trở nên lười","to swell up (soaking) | to become soggy | to become lazy","1341800"),
    ("ぼやく","ぼやく","v5k|vi","càu nhàu | phàn nàn | cằn nhằn","to grumble | to complain","1011850"),
    ("あっさり","あっさり","adv|vs","dễ dàng | gọn lẹ | thanh đạm | đơn giản","easily | flatly | lightly (seasoned) | plainly","1000360"),
    ("うっとり","うっとり","adv|vs","ngây ngất | mê mẩn | thẫn thờ","ecstatically | spellbound | absentmindedly","1631640"),
    ("うろうろ","うろうろ","adv|vs","lảng vảng | lang thang | đi tới đi lui bồn chồn","restlessly | aimlessly | to loiter | to wander aimlessly","1001060"),
    ("がっしり","がっしり","adv|vs","vạm vỡ | chắc chắn | rắn rỏi","firmly | solidly | sturdily | strongly","1003200"),
    ("きっちり","きっちり","adv|vs","khít khao | chính xác | đúng giờ | vừa khít","exactly | precisely | punctually | (fitting) perfectly","1003420"),
    ("じっくり","じっくり","adv","kỹ càng | thong thả | thấu đáo | cẩn thận","carefully | without haste | thoroughly | deliberately","1005860"),
    ("しんなり","しんなり","adv|vs","mềm mại | dẻo | mềm rũ","soft | supple | pliant","2761120"),
    ("すんなり","すんなり","adv|vs","thon thả | trơn tru | dễ dàng | suôn sẻ","slender | smoothly | without trouble | easily","1006320"),
    ("そわそわ","そわそわ","adv|vs","bồn chồn | đứng ngồi không yên | lo lắng","restlessly | nervously | uneasily | in a fidget","1007120"),
    ("だぶだぶ","だぶだぶ","adj-na|adv|vs","rộng thùng thình | lùng thùng | óc ách","loose (clothing) | baggy | sloshing | overflowing","1007430"),
    ("ちやほや","ちやほや","vs|adv","cưng chiều | nuông chiều | tâng bốc","to pamper | to spoil | to flatter (with attention)","1007620"),
    ("てきぱき","てきぱき","adv|vs","nhanh nhẹn | gọn gàng | mau lẹ","briskly | quickly | promptly","2009050"),
    ("どっと","どっと","adv","ồ lên (cười) | ào ào | đổ dồn | đột ngột","bursting out (laughter) | in a rush | flooding in | suddenly","1009210"),
    ("にっこり","にっこり","adv|vs","mỉm cười tươi | cười toe","sweetly (smiling) | broadly (grinning)","1632320"),
    ("のろのろ","のろのろ","adv|vs","chậm chạp | lề mề | ì ạch","slowly | sluggishly","1010040"),
    ("はきはき","はきはき","adv|vs","lanh lợi | dứt khoát | rõ ràng | mạch lạc","briskly | smartly | clearly | lucidly","1010090"),
    ("びっしょり","びっしょり","adj-na|adv","ướt sũng | ướt đẫm | đầm đìa","wet through | drenched","1010760"),
    ("ふんわり","ふんわり","adv","nhẹ nhàng | bồng bềnh | xốp mềm","gently | airily | fluffily","2069720"),
    ("ぼつぼつ","ぼつぼつ","adv|n","dần dần | từ từ | sắp | rải rác | nốt sần","gradually | soon | here and there | spots | pimples","1011840"),
    ("まごまご","まごまご","adv|vs","lúng túng | bối rối | luống cuống","confused | flustered | at a loss","1012110"),
    ("くたくた","くたくた","adj-na|adv","mệt lử | rã rời | nhàu nát | nhừ","exhausted | worn out | ragged | boiled to a pulp","1003770"),
    ("じめじめ","じめじめ","adv|vs","ẩm ướt | ẩm thấp | u uất | rầu rĩ","damp | humid | clammy | gloomy | melancholy","1005890"),
    ("からから","からから","adj-na|adv","khô khốc | cạn khô | trống rỗng | lạch cạch | cười khanh khách","parched | bone-dry | empty | rattling | laughing loudly","1003000"),
    ("ずらり","ずらり","adv","thành hàng dài | san sát | dàn hàng","in a row | in a line","2008600"),
    ("がやがや","がやがや","adv|vs","ồn ào | xôn xao | nhốn nháo","noisily | clamorously | in a hubbub","1003280"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
