# -*- coding: utf-8 -*-
"""Build N2 ready wave 051 — vehicles, car parts, driving, traffic, accidents, licensing."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-051.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("車両","しゃりょう","n","phương tiện | xe | toa tàu | đầu máy toa xe","(wheeled) vehicle | (railroad) car | rolling stock","1323250"),
    ("車種","しゃしゅ","n","loại xe | dòng xe | phân loại xe","car model | type of vehicle","1323160"),
    ("商用車","しょうようしゃ","n","xe thương mại | xe chở hàng","commercial vehicle","2702870"),
    ("営業車","えいぎょうしゃ","n","xe kinh doanh (taxi, buýt, tải)","commercial vehicle (taxi, bus, truck)","2842334"),
    ("社用車","しゃようしゃ","n","xe công ty","company car","1322970"),
    ("公用車","こうようしゃ","n","xe công | xe công vụ","official vehicle","1274960"),
    ("軽自動車","けいじどうしゃ","n","xe ô tô cỡ nhỏ (kei car, dưới 660cc)","light motor vehicle | kei car","1630580"),
    ("普通車","ふつうしゃ","n","xe cỡ thường | toa thường (tàu) | toa hạng hai","standard-size car | ordinary carriage","2532240"),
    ("大型車","おおがたしゃ","n","xe cỡ lớn","large-sized car","1941900"),
    ("中古車","ちゅうこしゃ","n","xe cũ | xe đã qua sử dụng","used car | secondhand car","1424170"),
    ("新車","しんしゃ","n","xe mới","new car","1361920"),
    ("廃車","はいしゃ","n|vs|vt","xe bỏ | xe hết hạn sử dụng | hủy đăng ký xe","decommissioned vehicle | deregistering (vehicle)","1472130"),
    ("改造車","かいぞうしゃ","n","xe độ | xe được cải tạo | xe sửa đổi","modified car | custom car","1931590"),
    ("試乗","しじょう","n|vs|vi","lái thử | chạy thử | đi thử (xe)","test drive | test ride","1646590"),
    ("運転席","うんてんせき","n","ghế lái | ghế tài xế","driver's seat","1172880"),
    ("助手席","じょしゅせき","n","ghế phụ | ghế phía trước cạnh tài","passenger seat","1938290"),
    ("後部座席","こうぶざせき","n","ghế sau (ô tô)","back seat (of a car) | rear seat","1934790"),
    ("車外","しゃがい","n|adj-no","bên ngoài xe","outside a car (train, bus)","2533370"),
    ("車体","しゃたい","n","thân xe | khung xe","body (of car) | frame","1323200"),
    ("車輪","しゃりん","n","bánh xe","(vehicle) wheel","1323280"),
    ("車軸","しゃじく","n","trục xe | trục bánh","axle","1323150"),
    ("前輪","ぜんりん","n","bánh trước","front wheel","1581150"),
    ("後輪","こうりん","n","bánh sau","rear wheel","1649480"),
    ("駆動","くどう","n|vs|vt|vi","truyền động | dẫn động | lực dẫn động","drive | driving (force)","1244900"),
    ("動力","どうりょく","n","động lực | nguồn lực vận hành | điện ba pha","power | motive power","1451660"),
    ("馬力","ばりき","n","mã lực | sức ngựa | sinh lực | sức bền","horsepower | energy | vitality","1471870"),
    ("排気量","はいきりょう","n","dung tích xi-lanh | dung tích động cơ","(engine) displacement","1472340"),
    ("燃費","ねんぴ","n","mức tiêu hao nhiên liệu | mức tốn xăng","fuel consumption | gas mileage","1469650"),
    ("満タン","まんタン","n","đầy bình (xăng) | đầy dung lượng","full tank (of gas) | full capacity","1526700"),
    ("燃料計","ねんりょうけい","n","đồng hồ nhiên liệu | đồng hồ xăng","fuel gauge","2862875"),
    ("速度計","そくどけい","n","đồng hồ tốc độ","speedometer","1405060"),
    ("計器盤","けいきばん","n","bảng đồng hồ | bảng điều khiển | táp-lô","dashboard | instrument panel","2174330"),
    ("方向指示器","ほうこうしじき","n","đèn xi-nhan | đèn báo rẽ","direction indicator | turn signal","2526190"),
    ("警笛","けいてき","n","còi báo | còi xe | còi hú | còi sương mù","horn | alarm | whistle","1252480"),
    ("急停車","きゅうていしゃ","n|vs","dừng xe đột ngột | thắng gấp dừng","(coming to a) sudden stop","1228900"),
    ("急ブレーキ","きゅうブレーキ","n","phanh gấp | thắng gấp","sudden braking | slamming on the brakes","2841530"),
    ("追い越し","おいこし","n","vượt | sự vượt xe","passing | overtaking","1432270"),
    ("車線変更","しゃせんへんこう","n|vs","chuyển làn | đổi làn đường","lane change | changing lanes","2831557"),
    ("側道","そくどう","n","đường gom | đường song hành | đường bên","service road | frontage road","2792060"),
    ("本線","ほんせん","n","tuyến chính | đường chính | làn chính","main line | trunk line","1522830"),
    ("走行車線","そうこうしゃせん","n","làn đường thường | làn chạy chậm","slow (cruising) lane","1941440"),
    ("中央分離帯","ちゅうおうぶんりたい","n","dải phân cách giữa","(highway) median | median strip","1695570"),
    ("路肩","ろかた","n","lề đường | vai đường","shoulder (of a road) | berm","1560030"),
    ("青信号","あおしんごう","n","đèn xanh | tín hiệu cho phép đi","green light | go-ahead signal","1381600"),
    ("赤信号","あかしんごう","n","đèn đỏ | dấu hiệu nguy hiểm","red light | sign of danger","1634690"),
    ("混雑","こんざつ","n|vs|vi","đông đúc | chen chúc | tắc nghẽn | hỗn loạn","congestion | crowding | confusion","1290390"),
    ("通勤ラッシュ","つうきんラッシュ","n","giờ cao điểm đi làm | giờ tắc đường buổi sáng","commuter rush | rush hour","2404380"),
    ("帰宅ラッシュ","きたくラッシュ","n","giờ cao điểm tan tầm buổi chiều","evening rush hour","2851657"),
    ("進入禁止","しんにゅうきんし","exp","cấm vào | cấm đi vào | đi ngược chiều","Do Not Enter | No Entry","2827182"),
    ("駐車禁止","ちゅうしゃきんし","exp|n","cấm đỗ xe","No Parking | parking ban","1692060"),
    ("駐車違反","ちゅうしゃいはん","n","vi phạm đỗ xe | đỗ xe sai quy định","parking violation","1692050"),
    ("速度違反","そくどいはん","n","vi phạm tốc độ | chạy quá tốc độ","speeding","1941540"),
    ("スピード違反","スピードいはん","n","chạy quá tốc độ | vượt giới hạn tốc độ","exceeding the speed limit | speeding","2144660"),
    ("飲酒運転","いんしゅうんてん","n","lái xe khi say rượu | lái xe có nồng độ cồn","drunk driving | driving under the influence","1169910"),
    ("無免許","むめんきょ","n","không có bằng | không có giấy phép","having no license | being unlicensed","1672380"),
    ("無免許運転","むめんきょうんてん","n","lái xe không bằng | lái xe không giấy phép","driving without a license","1672390"),
    ("ひき逃げ","ひきにげ","n|vs|vt|vi","tông xe rồi bỏ chạy (gây thương vong)","hit-and-run (causing personal injury)","1573540"),
    ("当て逃げ","あてにげ","n|vs|vi","va quệt rồi bỏ chạy (hư hỏng tài sản)","hit-and-run causing property damage","1448910"),
    ("正面衝突","しょうめんしょうとつ","n|vs|adj-no","đâm trực diện | va chạm đối đầu","head-on collision","1378070"),
    ("接触事故","せっしょくじこ","n","va chạm nhẹ | quệt xe | tai nạn va quệt","minor collision | fender bender","1940800"),
    ("人身事故","じんしんじこ","n","tai nạn gây thương vong (giao thông, đường sắt)","accident resulting in personal injury or death","1368310"),
    ("物損事故","ぶっそんじこ","n","tai nạn hư hỏng tài sản","traffic accident resulting in property damage","1502670"),
    ("事故車","じこしゃ","n","xe bị tai nạn | xe có tiền sử tai nạn","car involved in an accident","2840910"),
    ("レッカー","レッカー","n|vs|vt","xe cứu hộ | xe kéo | việc kéo xe","tow truck | wrecker | towing","1145480"),
    ("牽引","けんいん","n|vs|vt","kéo | lai dắt | dẫn dắt (tăng trưởng)","traction | towing | pulling | driving (growth)","1258240"),
    ("故障車","こしょうしゃ","n","xe hỏng | xe chết máy","broken-down car","1934710"),
    ("路上駐車","ろじょうちゅうしゃ","n","đỗ xe trên đường | đỗ ven đường","street parking | on-street parking","1948910"),
    ("縦列駐車","じゅうれつちゅうしゃ","n|vs|vt|vi","đỗ xe song song | đỗ xe nối đuôi ven đường","parallel parking","2062220"),
    ("車庫","しゃこ","n","gara | nhà xe | bãi đỗ (tàu, xe buýt)","garage | depot (for trains, buses)","1323120"),
    ("車庫入れ","しゃこいれ","n|vs","đưa xe vào gara | đỗ xe vào nhà xe","parking in a garage","2062230"),
    ("洗車","せんしゃ","n|vs|vi","rửa xe","car washing","1390960"),
    ("車検","しゃけん","n","đăng kiểm xe | kiểm định xe","vehicle inspection","1323110"),
    ("名義変更","めいぎへんこう","n","sang tên | chuyển quyền sở hữu | đổi tên chủ","transfer of ownership | change of name","2865951"),
    ("ナンバープレート","ナンバープレート","n","biển số xe","number plate | license plate","1090890"),
    ("免許証","めんきょしょう","n","giấy phép | bằng lái | chứng chỉ hành nghề","licence | permit | certificate","1533150"),
    ("失効","しっこう","n|vs|vi","hết hiệu lực | mất hiệu lực | hết hạn","lapse | invalidation | expiration","1319980"),
    ("講習","こうしゅう","n|vs|vt","khóa học ngắn | tập huấn | bồi dưỡng","short course | training","1282290"),
    ("教習所","きょうしゅうじょ","n","trung tâm đào tạo | trường dạy lái xe","training institute | driving school","1237180"),
    ("仮免","かりめん","n","bằng lái tạm | giấy phép tạm thời","temporary licence | provisional license","1931010"),
    ("実技","じつぎ","n","kỹ năng thực hành | phần thực hành","practical skill","1635340"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
