# -*- coding: utf-8 -*-
"""Build N3 ready wave 044 — 117 freshly-curated common N3 nouns/adj/adv/vs-nouns.
Readings/pos/ent_seq verified against japanese_raw_jmdict; meaning_vi authored by hand.
"""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-044.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(word, reading, pos, vi, en, sid):
    return ",".join([q(word),q(reading),q(""),q("N3"),q(pos),q(vi),q(en),q(""),q("0"),
        q("jmdict"),q(sid),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])

DATA = [
    ("偶然","ぐうぜん","n|adj-na|adv","ngẫu nhiên | tình cờ | sự trùng hợp","coincidence | chance | by chance | accidentally","1246270"),
    ("偏見","へんけん","n","thành kiến | định kiến | cái nhìn thiên lệch","prejudice | bias | distorted view","1510380"),
    ("観点","かんてん","n","quan điểm | góc nhìn | lập trường","point of view | viewpoint | standpoint | angle","1215000"),
    ("視点","してん","n","góc nhìn | quan điểm | điểm nhìn","point of view | viewpoint | angle | perspective","1312130"),
    ("要素","ようそ","n","yếu tố | thành phần | nhân tố","component | factor | element","1546800"),
    ("要因","よういん","n","nguyên nhân chính | nhân tố chủ yếu","main cause | primary factor","1546670"),
    ("背景","はいけい","n","bối cảnh | hậu cảnh | phông nền","background | backdrop | setting | context","1472720"),
    ("趣旨","しゅし","n","ý chính | mục đích | tôn chỉ","point (of a statement) | gist | intent | aim","1328990"),
    ("概要","がいよう","n","khái quát | tóm tắt | tổng quan","outline | summary | overview | synopsis","1204500"),
    ("要旨","ようし","n","ý chính | điểm cốt lõi | tóm lược","main point | gist | essentials | summary","1546770"),
    ("本質","ほんしつ","n","bản chất | thực chất","essence | true nature | substance | reality","1522620"),
    ("性質","せいしつ","n","tính chất | bản tính | đặc tính","nature | disposition | character | property","1375390"),
    ("特性","とくせい","n","đặc tính | đặc trưng | nét riêng","special characteristic | trait | peculiarity","1455090"),
    ("機能","きのう","n|vs|vi","chức năng | tính năng | công năng","function | facility | feature","1221130"),
    ("効力","こうりょく","n","hiệu lực | hiệu quả | tác dụng","effect | efficacy | validity | potency","1275250"),
    ("効能","こうのう","n","công dụng | hiệu quả | tác dụng","effect | effectiveness | efficacy | benefit","1275180"),
    ("範囲","はんい","n","phạm vi | giới hạn | tầm","extent | scope | range | sphere","1481890"),
    ("規模","きぼ","n","quy mô | tầm cỡ","scale | scope | structure","1223090"),
    ("境界","きょうかい","n","ranh giới | biên giới | giới hạn","boundary | border | limit | frontier","1235960"),
    ("領域","りょういき","n","lĩnh vực | phạm vi | địa hạt","territory | domain | field | area | realm","1554720"),
    ("分野","ぶんや","n","lĩnh vực | ngành | mảng","field | sphere | division | branch","1504330"),
    ("項目","こうもく","n","hạng mục | mục | khoản","item | heading | category | entry","1283000"),
    ("要点","ようてん","n","điểm chính | trọng điểm","gist | main point","1546820"),
    ("重点","じゅうてん","n","trọng điểm | điểm nhấn | ưu tiên","important point | emphasis | priority","1336570"),
    ("焦点","しょうてん","n","tiêu điểm | trọng tâm | điểm hội tụ","focus | focal point | point at issue","1350810"),
    ("核心","かくしん","n","cốt lõi | mấu chốt | trọng tâm","core | heart (of the matter) | crux","1205590"),
    ("根本","こんぽん","n","căn bản | gốc rễ | nền tảng","root | source | origin | foundation | basis","2848289"),
    ("基盤","きばん","n","nền tảng | cơ sở | nền móng","base | basis | foundation | infrastructure","1219170"),
    ("基礎","きそ","n","cơ sở | nền tảng | cơ bản","foundation | basis","1219060"),
    ("推測","すいそく","n|vs|vt","suy đoán | phỏng đoán | ước đoán","guess | conjecture","1371200"),
    ("推定","すいてい","n|vs|vt","suy định | ước tính | giả định","presumption | assumption | estimation","1371210"),
    ("予測","よそく","n|vs|vt","dự đoán | dự báo | ước lượng","prediction | estimation","1543200"),
    ("予想","よそう","n|vs|vt","dự đoán | dự kiến | tiên liệu","expectation | anticipation | prediction | forecast","1543130"),
    ("主観","しゅかん","n","chủ quan | quan điểm cá nhân","subjectivity | one's personal opinion","1325180"),
    ("客観","きゃっかん","n","khách quan","objectivity | objective","1226690"),
    ("誤り","あやまり","n","sai sót | lỗi | nhầm lẫn","error | mistake | slip","1271290"),
    ("衝突","しょうとつ","n|vs|vi","va chạm | đụng độ | xung đột","collision | crash | clash | conflict","1351560"),
    ("対立","たいりつ","n|vs|vi","đối lập | đối đầu | mâu thuẫn","confrontation | opposition | antagonism","1410290"),
    ("抵抗","ていこう","n|vs|vi","kháng cự | phản kháng | điện trở","resistance | opposition | reluctance | (electrical) resistance","1436260"),
    ("反発","はんぱつ","n|vs|vi","phản đối | phản kháng | bật lại | hồi phục (giá)","opposition | backlash | repulsion | rebound (in price)","1480890"),
    ("成果","せいか","n","thành quả | kết quả | thành tựu","(good) result | outcome | accomplishment","1375650"),
    ("業績","ぎょうせき","n","thành tích | kết quả kinh doanh | cống hiến","achievement | (business) performance | results | contribution","1239460"),
    ("実績","じっせき","n","thành tích thực tế | kết quả đạt được | bề dày","actual results | accomplishments | track record","1321240"),
    ("功績","こうせき","n","công lao | công trạng | đóng góp","achievement | meritorious deed | distinguished service","1275070"),
    ("評判","ひょうばん","n|adj-no","danh tiếng | tiếng tăm | dư luận","reputation | popularity | rumour | fame","1490070"),
    ("名誉","めいよ","n|adj-na","danh dự | danh tiếng | vinh dự","honor | credit | glory | fame | prestige","1531870"),
    ("信用","しんよう","n|vs|vt","tín nhiệm | tin tưởng | uy tín | tín dụng","confidence | trust | reputation | credit","1359620"),
    ("信念","しんねん","n","niềm tin | tín niệm | xác tín","belief | faith | conviction","1359550"),
    ("確信","かくしん","n|vs|vt","tin chắc | xác tín | niềm tin vững","conviction | belief | confidence","1205870"),
    ("自覚","じかく","n|vs|vt","tự giác | tự ý thức | tự nhận thức","self-consciousness | self-awareness","1317490"),
    ("感覚","かんかく","n|vs|vt","cảm giác | giác quan | cảm nhận","sense | sensation | feeling | intuition","1212330"),
    ("直感","ちょっかん","n|vs|vt","trực giác | linh cảm","intuition | instinct | hunch","1430850"),
    ("観念","かんねん","n|vs|vt","quan niệm | ý niệm | cam chịu","idea | notion | concept | resignation (to fate)","1215010"),
    ("理念","りねん","n","lý niệm | tư tưởng nền tảng | triết lý","(guiding) ideal | foundational principle | doctrine","1550060"),
    ("思想","しそう","n","tư tưởng | ý thức hệ","thought | idea | ideology","1309560"),
    ("臆病","おくびょう","adj-na|n","nhút nhát | hèn nhát | dễ sợ hãi","cowardly | timid | easily frightened","1182790"),
    ("強引","ごういん","adj-na|n","cưỡng ép | áp đặt | lấn lướt","overbearing | coercive | pushy | high-handed","1236170"),
    ("鈍感","どんかん","adj-na|n","vô cảm | chậm hiểu | trơ lì","insensitive | thickheaded | dull","1457600"),
    ("敏感","びんかん","adj-na|n","nhạy cảm | tinh nhạy | dễ nhạy","sensitive | alert | susceptible","1491070"),
    ("楽観的","らっかんてき","adj-na","lạc quan | đầy hy vọng","optimistic | hopeful","1207320"),
    ("悲観的","ひかんてき","adj-na","bi quan | ảm đạm","pessimistic | gloomy","1483250"),
    ("客観的","きゃっかんてき","adj-na","khách quan","objective","1226700"),
    ("合理的","ごうりてき","adj-na","hợp lý | có lý | logic","rational | reasonable | logical","1285380"),
    ("実用的","じつようてき","adj-na","thực dụng | thiết thực | hữu dụng","practical | useful | pragmatic","1321510"),
    ("標準的","ひょうじゅんてき","adj-na","tiêu chuẩn | điển hình | thông thường","standard | average | typical | normal","2383820"),
    ("平均的","へいきんてき","adj-na","trung bình | bình thường","average | ordinary | normal","2119430"),
    ("典型的","てんけいてき","adj-na","điển hình | tiêu biểu | khuôn mẫu","typical | representative | archetypal","1438090"),
    ("代表的","だいひょうてき","adj-na","tiêu biểu | đại diện | điển hình","representative | exemplary | model","1412220"),
    ("圧倒的","あっとうてき","adj-na","áp đảo | vượt trội tuyệt đối","overwhelming","1153270"),
    ("尚","なお","adv|conj","vẫn còn | hơn nữa | ngoài ra | lưu ý rằng","still | furthermore | moreover | note that","1349300"),
    ("及び","および","conj","và | cùng với","and | as well as","1228140"),
    ("或いは","あるいは","conj|adv","hoặc là | hay là | có lẽ","or | either ... or | maybe | perhaps","1586850"),
    ("故に","ゆえに","conj","vì vậy | do đó | cho nên","therefore | consequently","1267130"),
    ("恐らく","おそらく","adv","có lẽ | chắc là | e rằng","probably | most likely | I'm afraid","1236650"),
    ("当たり前","あたりまえ","adj-na|n","đương nhiên | hiển nhiên | bình thường","natural | obvious | usual | ordinary","1448800"),
    ("無論","むろん","adv","tất nhiên | dĩ nhiên | đương nhiên","of course | certainly | naturally","1531080"),
    ("一層","いっそう","adv","càng | hơn nữa | càng thêm","even more | still more | all the more","1164340"),
    ("却って","かえって","adv","trái lại | ngược lại | thành ra","on the contrary | rather | instead","1226610"),
    ("敢えて","あえて","adv","cố tình | dám | không hẳn","daringly | deliberately | not necessarily","1212850"),
    ("強いて","しいて","adv","cố ép | gượng ép | nếu buộc phải","by force | if forced (to say)","1236080"),
    ("予め","あらかじめ","adv","trước | từ trước | sẵn","beforehand | in advance | previously","1542860"),
    ("直ちに","ただちに","adv","ngay lập tức | tức khắc | trực tiếp","at once | immediately | right away | directly","1430670"),
    ("一斉に","いっせいに","adv","đồng loạt | cùng một lúc | nhất tề","simultaneously | all at once | in unison","1164050"),
    ("瞬間","しゅんかん","n","khoảnh khắc | giây lát | thời khắc","moment | instant | second","1341210"),
    ("延期","えんき","n|vs|vt","hoãn lại | trì hoãn | dời lại","postponement | deferment | adjournment","1176430"),
    ("持続","じぞく","n|vs|vt|vi","duy trì | kéo dài | bền vững","continuation | lasting | sustaining | enduring","1315810"),
    ("維持","いじ","n|vs|vt","duy trì | giữ gìn | bảo trì","maintenance | preservation","1158450"),
    ("保持","ほじ","n|vs|vt","giữ | nắm giữ | bảo tồn","retention | maintenance | preservation","1513700"),
    ("確保","かくほ","n|vs|vt","đảm bảo | giành được | giữ chắc","securing | ensuring | guarantee | maintaining","1205920"),
    ("獲得","かくとく","n|vs|vt","giành được | đạt được | thu được","acquisition | possession","1205750"),
    ("取得","しゅとく","n|vs|vt","có được | lấy (bằng cấp) | thủ đắc","obtaining (a qualification) | acquisition | getting","1327070"),
    ("実行","じっこう","n|vs|vt","thực hiện | thi hành | thực thi","execution | carrying out | implementation","1321040"),
    ("遂行","すいこう","n|vs|vt","hoàn thành | thực thi | thực hiện","accomplishment | execution","1372640"),
    ("履行","りこう","n|vs|vt","thực hiện (nghĩa vụ) | thi hành (hợp đồng)","performance (of a duty) | fulfillment | execution","1549790"),
    ("施行","しこう","n|vs|vt","thi hành (luật) | thực thi | áp dụng","putting in force (a law) | enforcement | carrying out","1579510"),
    ("導入","どうにゅう","n|vs|vt","đưa vào | giới thiệu | lắp đặt | phần dẫn nhập","introduction | bringing in | installation","1453790"),
    ("採択","さいたく","n|vs|vt","thông qua | lựa chọn | chọn dùng","adoption | selection | choice","1294830"),
    ("考慮","こうりょ","n|vs|vt","cân nhắc | xem xét | tính đến","consideration | taking into account","1281170"),
    ("工夫","くふう","n|vs|vt","nghĩ cách | sáng tạo | tìm tòi | ý tưởng","devising (a way) | contriving | figuring out | idea","1278220"),
    ("革新","かくしん","n|vs|vt","cách tân | đổi mới | cải cách","reform | innovation","1206470"),
    ("転換","てんかん","n|vs|vt|vi","chuyển đổi | thay đổi | xoay chuyển","conversion | changeover | switchover","1441080"),
    ("変換","へんかん","n|vs|vt","chuyển đổi | biến đổi | hoán đổi","change | conversion | transformation","1510950"),
    ("移行","いこう","n|vs|vt|vi","chuyển sang | quá độ | dịch chuyển","transition | changeover | shift | transfer","1158240"),
    ("普及","ふきゅう","n|vs|vt|vi","phổ cập | lan rộng | phổ biến","diffusion | spread | popularization","1497110"),
    ("浸透","しんとう","n|vs|vi","thẩm thấu | thấm nhuần | lan tỏa","permeation | infiltration | spread | osmosis","1362630"),
    ("拡大","かくだい","n|vs|vt|vi","mở rộng | phóng to | khuếch đại","expansion | magnification | enlargement","1205200"),
    ("拡張","かくちょう","n|vs|vt","mở rộng | nới rộng | mở mang","expansion | extension | enlargement","1205220"),
    ("縮小","しゅくしょう","n|vs|vt|vi","thu nhỏ | thu hẹp | cắt giảm","reduction | curtailment | scaling down | contraction","1337630"),
    ("削減","さくげん","n|vs|vt","cắt giảm | giảm bớt","cut | reduction | curtailment","1298110"),
    ("低下","ていか","n|vs|vi","giảm sút | hạ thấp | suy giảm","fall | decline | lowering | deterioration","1434250"),
    ("上昇","じょうしょう","n|vs|vi","tăng lên | đi lên | leo thang","rising | ascending | climbing","1353450"),
    ("下降","かこう","n|vs|vi","đi xuống | giảm | hạ xuống","descent | fall | drop | decline","1184940"),
    ("抑制","よくせい","n|vs|vt","kìm chế | ức chế | kiềm hãm","control | restraint | suppression | inhibition","1547290"),
    ("制限","せいげん","n|vs|vt","hạn chế | giới hạn | hạn định","restriction | restraint | limitation | limit","1374700"),
    ("規定","きてい","n|vs|vt","quy định | điều khoản | quy chế","stipulation | provision | regulation | rule","1223060"),
    ("提示","ていじ","n|vs|vt","đưa ra | trình | xuất trình","presentation | showing | production | citing","1436400"),
    ("提供","ていきょう","n|vs|vt","cung cấp | đề xuất | hiến (máu) | tài trợ","offer | providing | supplying | donating | sponsoring","1436360"),
]

rows=[row(*d) for d in DATA]
content = HEADER + "\n" + "\n".join(rows) + "\n"
with open(OUT,"w",encoding="utf-8",newline="\n") as f:
    f.write(content)
print(f"Written {len(rows)} rows to {os.path.abspath(OUT)}")
