# -*- coding: utf-8 -*-
"""Build N3 ready wave 060 — 87 freshly-curated N3 manufacturing/business/HR/meeting nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-060.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("素材","そざい","n","nguyên liệu | chất liệu | đề tài","ingredient | (raw) material | subject matter","1397220"),
    ("原料","げんりょう","n","nguyên liệu thô | thành phần","raw materials | ingredient","1262490"),
    ("製品","せいひん","n","sản phẩm | thành phẩm","manufactured goods | finished goods | product","1380760"),
    ("規格","きかく","n","quy cách | tiêu chuẩn | chuẩn","standard | norm","1222970"),
    ("仕様","しよう","n","cách thức | thông số kỹ thuật | quy cách","way | method | (technical) specification","1305500"),
    ("性能","せいのう","n","hiệu năng | tính năng | hiệu suất","ability | performance | efficiency","1375470"),
    ("自動","じどう","adj-no|n","tự động | nội động (từ)","automatic | intransitive verb","1318340"),
    ("手動","しゅどう","n|adj-no","thủ công | bằng tay","manual (operation)","1328240"),
    ("遠隔","えんかく","n|adj-no","từ xa | cách xa | điều khiển xa","distant | remote | isolated","1177950"),
    ("操縦","そうじゅう","n|vs|vt","điều khiển | lái | thao túng","steering | piloting | control | manipulation","1400080"),
    ("不具合","ふぐあい","n|adj-na","trục trặc | lỗi | sự cố","flaw | defect | bug | malfunction","1492030"),
    ("整備","せいび","n|vs|vt","bảo dưỡng | trang bị | hoàn thiện","maintenance | servicing | development | equipping","1376240"),
    ("寿命","じゅみょう","n","tuổi thọ | thời hạn sử dụng","lifespan | life | service life","1330240"),
    ("損傷","そんしょう","n|vs|vt|vi","tổn thương | hư hại | thiệt hại","damage | injury","1406760"),
    ("破損","はそん","n|vs|vt|vi","hư hỏng | vỡ | hư hại","damage | breakage","1471380"),
    ("欠陥","けっかん","n","khiếm khuyết | lỗi | thiếu sót","defect | fault | flaw | deficiency","1253950"),
    ("不良","ふりょう","adj-no|adj-na|n","kém | hỏng | lỗi | hư hỏng (người)","bad | poor | defective | delinquent | hooligan","1495290"),
    ("製造","せいぞう","n|vs|vt","chế tạo | sản xuất","manufacture | production","1380690"),
    ("試作","しさく","n|vs|vt","chế thử | làm thử | mẫu thử","trial manufacture | prototype","1312430"),
    ("特許","とっきょ","n","bằng sáng chế | giấy phép đặc biệt","patent | special permission | license","1454780"),
    ("発明","はつめい","n|vs|vt","phát minh | sáng chế","invention","1477910"),
    ("最新","さいしん","n|adj-no","mới nhất | cập nhật nhất","latest | newest","1294090"),
    ("新型","しんがた","n|adj-no","kiểu mới | mẫu mới | chủng mới","new type | new model | new strain","1361770"),
    ("戦略","せんりゃく","n|adj-no","chiến lược","strategy | tactics","1390600"),
    ("戦術","せんじゅつ","n|adj-no","chiến thuật","tactics","1390280"),
    ("構想","こうそう","n|vs|vt","ý tưởng | kế hoạch | tầm nhìn | bố cục","plan | conception | vision | scheme","1279780"),
    ("展望","てんぼう","n|vs|vt","tầm nhìn | triển vọng | viễn cảnh","view | outlook | prospect","1440640"),
    ("採算","さいさん","n","lợi nhuận | sự sinh lời | hạch toán","profit | profitability","1294780"),
    ("弊社","へいしゃ","n","công ty chúng tôi (khiêm)","our company | our firm","1508280"),
    ("当社","とうしゃ","n","công ty này | công ty chúng tôi","this company | this firm","1449100"),
    ("職員","しょくいん","n","nhân viên | cán bộ | viên chức","staff member | employee | personnel","1357490"),
    ("従業員","じゅうぎょういん","n","nhân viên | người làm | công nhân viên","employee | worker","1335250"),
    ("役員","やくいん","n","ban giám đốc | cán bộ | người phụ trách","director | executive | officer | official","1537990"),
    ("幹部","かんぶ","n","ban lãnh đạo | cán bộ cấp cao","management | (executive) staff | leadership","1212170"),
    ("管理職","かんりしょく","n","vị trí quản lý | chức quản lý","management | managerial position","1214250"),
    ("責任者","せきにんしゃ","n","người phụ trách | người chịu trách nhiệm","person in charge | responsible party | supervisor","1383190"),
    ("主任","しゅにん","n","chủ nhiệm | trưởng nhóm | người phụ trách","person in charge | chief | head | manager","1326040"),
    ("新人","しんじん","n","người mới | nhân viên mới | tân binh","newcomer | recruit | rookie | new talent","1361960"),
    ("同期","どうき","n|adj-no|vs","cùng khóa | cùng kỳ | đồng bộ hóa","same period | same year (graduation) | synchronization","1452030"),
    ("出世","しゅっせ","n|vs|vi","thăng tiến | thành đạt | tiến thân","success in life | getting ahead | promotion","1339340"),
    ("配属","はいぞく","n|vs|vt","phân công | bố trí (nhân sự)","assignment (of a person) | attachment","1473130"),
    ("就業","しゅうぎょう","n|vs|vi","có việc làm | bắt đầu làm việc","employment | starting work","1331590"),
    ("勤続","きんぞく","n|vs|vi","thâm niên | làm việc liên tục","continuous service","1241010"),
    ("在職","ざいしょく","n|vs|vi","đương chức | đang công tác","being in office | holding a position","1296520"),
    ("退社","たいしゃ","n|vs|vi","nghỉ việc | tan sở | rời công ty","resignation | leaving work","1411400"),
    ("出社","しゅっしゃ","n|vs|vi","đi làm | đến công ty","going to work | coming to work","1339150"),
    ("早退","そうたい","n|vs|vi","về sớm | tan sớm","leaving early","1400310"),
    ("遅刻","ちこく","n|vs|vi","đi muộn | đến trễ","lateness | tardiness | arriving late","1422050"),
    ("有給","ゆうきゅう","adj-no|n","có lương | nghỉ phép có lương","salaried | paid | paid vacation","1541200"),
    ("無給","むきゅう","n|adj-no","không lương | làm không công","unpaid | nonsalaried","1529810"),
    ("昼休み","ひるやすみ","n|adv","nghỉ trưa | giờ nghỉ trưa","lunch break | noon recess","1426290"),
    ("当番","とうばん","n|adj-no","trực ban | phiên trực | người trực","being on duty | person on duty | one's turn","1449220"),
    ("日勤","にっきん","n|vs|vi","ca ngày | làm ban ngày","day shift | day duty","1463950"),
    ("夜勤","やきん","n","ca đêm | trực đêm","night duty | night shift","1536650"),
    ("宿直","しゅくちょく","n|vs|vi","trực đêm | gác đêm","night watch | night shift","1337280"),
    ("功労","こうろう","n","công lao | công trạng","meritorious deed | services","1275110"),
    ("表彰","ひょうしょう","n|vs|vt","tuyên dương | khen thưởng | vinh danh","(official) commendation | public recognition | awarding","1489670"),
    ("昇給","しょうきゅう","n|vs|vi","tăng lương","salary raise","1349760"),
    ("減給","げんきゅう","n|vs|vt|vi","giảm lương | cắt lương","pay cut | salary cut","1630940"),
    ("賞与","しょうよ","n","tiền thưởng | phần thưởng","bonus | reward | prize","1351990"),
    ("手当","てあて","n|vs","trợ cấp | phụ cấp | tiền thưởng | sơ cứu","allowance | benefit | compensation | medical care","1598240"),
    ("福利","ふくり","n","phúc lợi","welfare","1501100"),
    ("待遇","たいぐう","n|vs|vt","đãi ngộ | tiếp đãi | điều kiện làm việc","treatment | reception | working conditions | remuneration","1410610"),
    ("熟練","じゅくれん","n|vs|vi","lành nghề | thành thạo | điêu luyện","skill | expertise | proficiency | mastery","1337930"),
    ("未熟","みじゅく","adj-na|n","non nớt | chưa chín | thiếu kinh nghiệm","unripe | immature | inexperienced | unskilled","1527560"),
    ("専門","せんもん","n","chuyên môn | chuyên ngành | sở trường","speciality | area of expertise | (one's) field","1389880"),
    ("分担","ぶんたん","n|vs|vt","phân chia (việc) | đảm nhận phần việc","taking on one's share | apportionment | allotment","1503950"),
    ("協業","きょうぎょう","n|vs|vi","hợp tác | cộng tác | làm việc chung","cooperation | collaboration","1235640"),
    ("議題","ぎだい","n","chủ đề thảo luận | chương trình nghị sự","topic of discussion | agenda","1226130"),
    ("議事","ぎじ","n","nghị sự | nội dung họp | việc bàn nghị","proceedings | business (of the day)","1226080"),
    ("採決","さいけつ","n|vs|vt","biểu quyết | bỏ phiếu","vote | ballot | division","1294760"),
    ("否決","ひけつ","n|vs|vt","bác bỏ | phủ quyết | bỏ phiếu chống","rejection | voting down","1482980"),
    ("保留","ほりゅう","n|vs|vt","bảo lưu | tạm hoãn | giữ lại","reservation | putting on hold | deferment","1514030"),
    ("議決","ぎけつ","n|vs|vt","nghị quyết | quyết nghị | biểu quyết","resolution | decision | vote","1226050"),
    ("討議","とうぎ","n|vs|vt","thảo luận | tranh luận","debate | discussion","1449960"),
    ("協議","きょうぎ","n|vs|vt","hội ý | bàn bạc | thương lượng","conference | consultation | negotiation","1235570"),
    ("審議","しんぎ","n|vs|vt","thẩm nghị | bàn xét | thảo luận","deliberation | discussion | consideration","1360360"),
    ("答弁","とうべん","n|vs|vi","trả lời chất vấn | giải trình | biện hộ","response | reply | defence","1449570"),
    ("質疑","しつぎ","n|vs","chất vấn | hỏi đáp","question | interpellation","1320680"),
    ("企画書","きかくしょ","n","bản kế hoạch | đề án (văn bản)","(written) proposal","1218160"),
    ("提案書","ていあんしょ","n","bản đề xuất | đề nghị (văn bản)","(written) proposal","2220710"),
    ("議事録","ぎじろく","n","biên bản họp | biên bản nghị sự","record of proceedings | minutes","1226100"),
    ("覚書","おぼえがき","n","biên bản ghi nhớ | bản ghi nhớ | ghi chú","memo | memorandum | note","1589300"),
    ("草案","そうあん","n","bản thảo | dự thảo","draft (for a speech, bill, etc.)","1401930"),
    ("原案","げんあん","n","dự thảo gốc | bản đề xuất ban đầu","original plan | original bill | draft","1261160"),
    ("修正案","しゅうせいあん","n","dự thảo sửa đổi | bản đề xuất chỉnh sửa","proposed amendment","1332140"),
    ("最終案","さいしゅうあん","n","phương án cuối cùng | bản cuối","final plan | final program","1935890"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
