# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-057.csv -- 27 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-057.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("一概に","いちがいに","N4","adv",
        "một cách tuyệt đối | như một quy tắc",
        "unconditionally | as a rule",
        "1161390",
        "一概に言えない。","いちがいにいえない。",
        "Không thể nói một cách tuyệt đối.","Cannot say unconditionally."),
    row("一周年","いっしゅうねん","N4","n",
        "một năm đầy đủ | kỷ niệm một năm",
        "one full year | first anniversary",
        "1163220",
        "開店一周年。","かいてんいっしゅうねん。",
        "Kỷ niệm một năm khai trương.","One-year anniversary of opening."),
    row("一瞬","いっしゅん","N4","n|adv",
        "thoáng chốc | khoảnh khắc | trong thoáng chốc",
        "instant | moment | for an instant",
        "1163340",
        "一瞬の出来事。","いっしゅんのできごと。",
        "Sự việc xảy ra trong thoáng chốc.","An event that happened in an instant."),
    row("一所懸命","いっしょけんめい","N4","adv|adj-na|n",
        "rất cố gắng | với nỗ lực tối đa | hết sức có thể | với tất cả sức lực | để bảo vệ mạng sống | hăng hái | tuyệt vọng | (samurai) tận tâm bảo vệ lãnh thổ",
        "very hard | with utmost effort | as hard as one can | with all one's might | for dear life | eagerly | desperately | (of a samurai) devoting oneself to (the defence of) one's territory",
        "1163380",
        "一所懸命働く。","いっしょけんめいはたらく。",
        "Làm việc hết sức.","Work as hard as one can."),
    row("一心","いっしん","N4","adv|n",
        "một lòng | tận tâm | toàn tâm toàn ý",
        "one mind | wholeheartedness | one's whole heart",
        "1163580",
        "一心に祈る。","いっしんにいのる。",
        "Cầu nguyện một lòng.","Pray wholeheartedly."),
    row("カツ丼","カツどん","N4","n",
        "cơm katsudon | cơm áp chảo thịt heo",
        "katsudon | pork cutlet served on top of a bowl of rice",
        "1037740",
        "カツ丼を食べる。","かつどんをたべる。",
        "Ăn cơm katsudon.","Eat katsudon."),
    row("一人前","いちにんまえ","N4","n|adj-no|adj-na",
        "một phần | một suất | một người | người lớn | người trưởng thành | đã trưởng thành | hoàn thiện | đã thành danh | đủ tiêu chuẩn",
        "one portion | one serving | one person | adult | grown-up | person who has come of age | fully fledged | established | qualified",
        "1163770",
        "一人前になる。","いちにんまえになる。",
        "Trở thành người trưởng thành.","Become a fully-fledged adult."),
    row("ウーロン茶","ウーロンちゃ","N4","n",
        "trà oolong",
        "oolong tea",
        "1025020",
        "ウーロン茶を飲む。","うーろんちゃをのむ。",
        "Uống trà oolong.","Drink oolong tea."),
    row("一休み","ひとやすみ","N4","n|vs|vi",
        "nghỉ ngơi (ngắn) | thở lấy sức | nghỉ giải lao",
        "(short) rest | breather | break",
        "1161830",
        "一休みしましょう。","ひとやすみしましょう。",
        "Hãy nghỉ giải lao nào.","Let's take a short break."),
    row("一向","いっこう","N4","adv|n",
        "hoàn toàn | tuyệt đối | hoàn toàn | không chút nào | không chút nào | không mảy may | thành tâm | chuyên chú | quyết tâm | Tịnh Độ Chân Tông",
        "completely | absolutely | totally | (not) at all | (not) a bit | (not) in the least | earnestly | intently | determinedly | Jōdo Shinshū",
        "1162410",
        "一向に気にしない。","いっこうにきにしない。",
        "Hoàn toàn không để ý.","Not minding at all."),
    row("一向","ひたぶる","N4","adj-na",
        "quyết tâm | chuyên tâm | chú tâm | tuyệt vọng | dữ dội",
        "determined | single-minded | intent | desperate | wild",
        "2833250",
        "ひたぶるな努力。","ひたぶるなどりょく。",
        "Nỗ lực không ngừng.","Single-minded effort."),
    row("一式","いっしき","N4","n",
        "bộ đầy đủ | trang phục | bộ dụng cụ | bộ hoàn chỉnh | tất cả | mọi thứ",
        "(complete) set | outfit | kit | suite | all | everything",
        "1163080",
        "道具一式。","どうぐいっしき。",
        "Bộ dụng cụ đầy đủ.","A complete set of tools."),
    row("一新","いっしん","N4","n|vs|vt|vi",
        "thay đổi hoàn toàn | cải cách | khôi phục | cải tạo | cải tạo lại | đổi mới",
        "complete change | reform | restoration | remodeling | remodelling | renewal",
        "1163620",
        "気持ちを一新する。","きもちをいっしんする。",
        "Đổi mới tâm trạng.","Renew one's spirit."),
    row("一時的","いちじてき","N4","adj-na",
        "tạm thời | ngắn ngủi | không lâu dài",
        "temporary | transitory | short-lived",
        "1162980",
        "一時的な措置。","いちじてきなそち。",
        "Biện pháp tạm thời.","A temporary measure."),
    row("一時間","いちじかん","N4","n",
        "một tiếng đồng hồ",
        "one hour",
        "1162940",
        "一時間かかる。","いちじかんかかる。",
        "Mất một tiếng.","It takes one hour."),
    row("一種","いっしゅ","N4","n|adv",
        "một loại | một dạng | một kiểu | một loài | có phần là | có vẻ như là | một loại | gần như | phần nào",
        "a kind | a sort | a variety | a species | of sorts | something of a | a sort of | sort of | somewhat",
        "1163170",
        "一種の習慣。","いっしゅのしゅうかん。",
        "Một loại thói quen.","A kind of habit."),
    row("一際","ひときわ","N4","adv",
        "nổi bật | đáng chú ý | đặc biệt | ấn tượng | xuất sắc | đặc biệt hơn | nhất là",
        "conspicuously | noticeably | remarkably | strikingly | outstandingly | especially | particularly",
        "1162630",
        "一際目立つ。","ひときわめだつ。",
        "Đặc biệt nổi bật.","Stand out conspicuously."),
    row("北","ペー","N4","n",
        "quân bài gió bắc (mạt chược) | bộ thắng bằng pung/kong gió bắc",
        "north wind tile | winning hand with a pung (or kong) of north wind tiles",
        "2833070",
        "北を引く。","ぺーをひく。",
        "Rút quân gió bắc.","Draw the north wind tile."),
    row("南","ナン","N4","n",
        "quân bài gió nam (mạt chược) | bộ thắng bằng pung/kong gió nam",
        "south wind tile | winning hand with a pung (or kong) of south wind tiles",
        "2833068",
        "南を引く。","なんをひく。",
        "Rút quân gió nam.","Draw the south wind tile."),
    row("南","みんなみ","N4","n",
        "phía nam",
        "south",
        "2869017",
        "南の方向。","みんなみのほうこう。",
        "Hướng về phía nam.","The southern direction."),
    row("南","なん","N4","pref|n-suf",
        "phương nam | miền nam | nam man | món ăn với ớt và hành tây",
        "southern | south | nanban | dish prepared using chili peppers and Welsh onions",
        "2869020",
        "南蛮料理。","なんばんりょうり。",
        "Món ăn kiểu nam man.","Nanban-style dish."),
    row("東","あずま","N4","n",
        "miền đông Nhật Bản (Kamakura/Edo xưa) | các tỉnh phía đông | phía đông | đàn wagon | yamatogoto | đàn 6 dây truyền thống Nhật | vợ/chồng",
        "eastern Japan (esp. Kamakura or Edo, from perspective of Kyoto or Nara) | eastern provinces | east | wagon | yamatogoto | six-stringed native Japanese zither | my spouse",
        "1447430",
        "東の地方。","あずまのちほう。",
        "Các tỉnh phía đông.","The eastern provinces."),
    row("東","トン","N4","n",
        "quân bài gió đông (mạt chược) | bộ thắng bằng pung/kong gió đông",
        "east wind tile | winning hand with a pung (or kong) of east wind tiles",
        "2833067",
        "東を引く。","とんをひく。",
        "Rút quân gió đông.","Draw the east wind tile."),
    row("東","とう","N4","pref|n",
        "phía đông | đông | Tokyo",
        "eastern | east | Tokyo",
        "2869019",
        "東日本。","ひがしにほん。",
        "Đông Nhật Bản.","Eastern Japan."),
    row("火花","ひばな","N4","n",
        "tia lửa",
        "spark",
        "1193760",
        "火花が散る。","ひばながちる。",
        "Tia lửa bắn ra.","Sparks fly."),
    row("西","にし","N4","n",
        "phía tây",
        "west",
        "1380840",
        "西の空。","にしのそら。",
        "Bầu trời phía tây.","The western sky."),
    row("西","シャー","N4","n",
        "quân bài gió tây (mạt chược) | bộ thắng bằng pung/kong gió tây",
        "west wind tile | winning hand with a pung (or kong) of west wind tiles",
        "2833069",
        "西を引く。","しゃーをひく。",
        "Rút quân gió tây.","Draw the west wind tile."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
