# -*- coding: utf-8 -*-
"""Build N3 ready wave 053 — 72 freshly-curated N3 i-adjectives + emotion/state verbs + health nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-053.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("貧しい","まずしい","adj-i","nghèo | nghèo nàn | thiếu thốn","poor | needy | scanty | inadequate","1490740"),
    ("等しい","ひとしい","adj-i","bằng nhau | giống hệt | tương đương","equal | identical | the same | equivalent","1449330"),
    ("騒がしい","さわがしい","adj-i","ồn ào | náo nhiệt | bất ổn (thời cuộc)","noisy | boisterous | turbulent | troubled","1403000"),
    ("慌ただしい","あわただしい","adj-i","vội vã | hối hả | bận rộn","busy | hectic | hurried | rushed","1278810"),
    ("甚だしい","はなはだしい","adj-i","cực kỳ | quá đáng | nghiêm trọng","extreme | excessive | terrible | intense","1370010"),
    ("望ましい","のぞましい","adj-i","đáng mong muốn | nên có | thích hợp hơn","desirable | hoped for | preferable | advisable","1519610"),
    ("好ましい","このましい","adj-i","dễ chịu | đáng quý | đáng mong muốn","nice | likeable | desirable","1277490"),
    ("厚かましい","あつかましい","adj-i","trơ trẽn | trâng tráo | dày mặt","impudent | shameless | brazen | cheeky","1275330"),
    ("緩い","ゆるい","adj-i","lỏng | lơi | thoai thoải | chậm | nhạt","loose | lenient | gentle (slope) | slow | weak","1214410"),
    ("清い","きよい","adj-i","trong sạch | thanh khiết | trong trẻo","clean | clear | pure | innocent","1378140"),
    ("平たい","ひらたい","adj-i","phẳng | dẹt | dễ hiểu (lời lẽ)","flat | even | level | plain (language)","1506900"),
    ("分厚い","ぶあつい","adj-i","dày | dày cộp | đồ sộ","thick | bulky | massive | heavy","1503510"),
    ("細長い","ほそながい","adj-i","dài và hẹp | thon dài","long and narrow","1295690"),
    ("奥深い","おくふかい","adj-i","sâu sắc | thâm sâu | thâm thúy","profound | deep | innermost","1179570"),
    ("興味深い","きょうみぶかい","adj-i","rất thú vị | đầy hứng thú","very interesting | of great interest","1238420"),
    ("何気ない","なにげない","adj-i","vô tình | tự nhiên | thản nhiên | bình thường","casual | unconcerned | nonchalant | ordinary","1599570"),
    ("切ない","せつない","adj-i","day dứt | nghẹn ngào | khắc khoải","painful | heartrending | trying | oppressive","1383770"),
    ("心強い","こころづよい","adj-i","yên tâm | vững dạ | an lòng","heartening | reassuring","1360640"),
    ("心細い","こころぼそい","adj-i","bất an | cô đơn | nản lòng","helpless | forlorn | lonely | discouraging","1360680"),
    ("粘り強い","ねばりづよい","adj-i","kiên trì | bền bỉ | dẻo dai","tenacious | persevering | persistent | steadfast","1469690"),
    ("若々しい","わかわかしい","adj-i","trẻ trung | tươi trẻ | trông trẻ","youthful | young | young-looking","1606610"),
    ("そそっかしい","そそっかしい","adj-i","hấp tấp | đoảng | bất cẩn","careless | thoughtless | hasty | rash","1006740"),
    ("呟く","つぶやく","v5k|vt|vi","lẩm bẩm | thì thầm | đăng tweet","to mutter | to murmur | to tweet","1565120"),
    ("喚く","わめく","v5k|vi","la hét | gào thét | kêu gào","to shout | to cry out | to yell | to scream","1211260"),
    ("微笑む","ほほえむ","v5m|vi","mỉm cười","to smile","1486030"),
    ("戸惑う","とまどう","v5u|vi","bối rối | lúng túng | hoang mang","to be bewildered | to be perplexed","1267100"),
    ("躊躇う","ためらう","v5u|vi","do dự | chần chừ | lưỡng lự","to hesitate | to waver","1573390"),
    ("怯える","おびえる","v1|vi","sợ hãi | hoảng sợ | khiếp sợ","to become frightened | to be scared (of)","1236630"),
    ("怖がる","こわがる","v5r|vt|vi","sợ | e ngại | hoảng sợ","to be afraid (of) | to fear | to be scared","1496930"),
    ("照れる","てれる","v1|vi","ngượng | mắc cỡ | xấu hổ","to be shy | to be bashful | to feel embarrassed","1350880"),
    ("苛立つ","いらだつ","v5t|vi","bực bội | cáu kỉnh | sốt ruột","to be irritated | to get annoyed | to lose patience","1195200"),
    ("憤る","いきどおる","v5r|vi","phẫn nộ | tức giận | bất bình","to be angry | to resent | to be indignant","1504640"),
    ("妬む","ねたむ","v5m|vt","ghen tị | đố kỵ | ghen ghét","to be jealous of | to envy | to begrudge","1444380"),
    ("悔いる","くいる","v1|vt","hối hận | hối tiếc | ăn năn","to regret","1200400"),
    ("偲ぶ","しのぶ","v5b|vt","hồi tưởng | tưởng nhớ | hoài niệm","to recollect | to reminisce | to be nostalgic for","1321590"),
    ("慕う","したう","v5u|vt","mến mộ | yêu kính | nhớ nhung | đi theo","to yearn for | to adore | to idolize | to follow","1514910"),
    ("戯れる","たわむれる","v1|vi","đùa giỡn | nô đùa | trêu ghẹo","to be playful | to frolic | to joke | to flirt with","1224970"),
    ("荒れる","あれる","v1|vi","nổi bão | hoang tàn | (da) khô ráp | nổi loạn","to become stormy | to fall into ruin | to get chapped | to go wild","1281490"),
    ("荒らす","あらす","v5s|vt","tàn phá | phá hoại | xâm nhập | quấy phá","to lay waste | to devastate | to break into | to troll","1281480"),
    ("散らばる","ちらばる","v5r|vi","vương vãi | rải rác | phân tán","to be scattered about | to disperse | to be littered","1303480"),
    ("撒く","まく","v5k|vt","rải | rắc | phát (tờ rơi) | cắt đuôi","to scatter | to sprinkle | to hand out | to shake off","1303400"),
    ("零す","こぼす","v5s|vt","làm đổ | rơi (nước mắt) | càu nhàu","to spill | to shed (tears) | to grumble (about)","1557640"),
    ("浸る","ひたる","v5r|vi","ngâm | đắm chìm | đắm mình (cảm xúc)","to be soaked | to be immersed in (joy, memories)","1362570"),
    ("漬ける","つける","v1|vt","ngâm | nhúng | muối (dưa)","to soak | to dip | to pickle | to preserve","1433680"),
    ("浸かる","つかる","v5r|vi","ngâm mình | bị ngập | (dưa) ngấm","to be submerged | to be soaked | to be pickled","1433670"),
    ("染みる","しみる","v1|vi","thấm | ngấm | xót | thấm thía","to soak (into) | to permeate | to sting | to sink in (mind)","1391120"),
    ("漏れる","もれる","v1|vi","rò rỉ | lọt ra | bị lộ | bị bỏ sót","to leak out | to shine through | to be divulged | to be omitted","1605330"),
    ("漏らす","もらす","v5s|vt","làm lộ | tiết lộ | để lọt | bỏ sót","to let leak | to divulge | to let out | to omit","1605320"),
    ("垂れる","たれる","v1|vi|vt","rủ xuống | buông thõng | nhỏ giọt","to hang | to droop | to dangle | to drip","1370870"),
    ("滴る","したたる","v5r|vi","nhỏ giọt | rỏ xuống | ứ tràn (sức sống)","to drip | to trickle | to overflow (with freshness)","1437230"),
    ("吹き出す","ふきだす","v5s|vi|vt","phun ra | trào ra | bật cười | đâm chồi","to spout out | to gush out | to burst into laughter | to bud","1602500"),
    ("湧き出る","わきでる","v1|vi","tuôn ra | trào ra | dâng lên | xuất hiện","to gush forth | to well up | to emerge","1606670"),
    ("ぼやける","ぼやける","v1|vi","mờ đi | nhòe | nhạt nhòa","to become dim | to become blurred","1011860"),
    ("霞む","かすむ","v5m|vi","mờ ảo | mờ mịt | bị lu mờ","to become misty | to become hazy | to be overshadowed","1196520"),
    ("曇る","くもる","v5r|vi","u ám | nhiều mây | mờ (kính) | rầu rĩ","to get cloudy | to fog up | to be gloomy","1457560"),
    ("晴れる","はれる","v1|vi","quang đãng | tạnh | hết nghi ngờ | nhẹ lòng","to clear up | to stop raining | to be cleared (of suspicion)","1376470"),
    ("凍える","こごえる","v1|vi","cóng | tê cóng | lạnh buốt","to freeze (of one's body) | to become numb with cold","1446180"),
    ("痺れる","しびれる","v1|vi","tê | tê cứng | bị điện giật | mê mẩn","to become numb | to get an electric shock | to be enthralled","1569620"),
    ("火照る","ほてる","v5r|vi","nóng bừng | hừng hực | đỏ bừng","to feel hot | to flush | to burn","1194010"),
    ("腫れる","はれる","v1|vi","sưng | sưng tấy | phù lên","to swell (from inflammation) | to become swollen","1328910"),
    ("寛ぐ","くつろぐ","v5g|vi","thư giãn | thoải mái | nghỉ ngơi","to relax | to feel at home","1211920"),
    ("解す","ほぐす","v5s|vt","gỡ rối | tháo gỡ | làm dịu | thư giãn","to disentangle | to loosen | to ease | to relax","1632920"),
    ("癒える","いえる","v1|vi","lành | bình phục | hồi phục","to recover | to be healed","1538740"),
    ("癒す","いやす","v5s|vt","chữa lành | xoa dịu | làm dịu","to heal | to cure | to alleviate (sorrow, fatigue)","1538750"),
    ("全快","ぜんかい","n|vs|vi","khỏi hẳn | bình phục hoàn toàn","complete recovery of health","1394940"),
    ("悪化","あっか","n|vs|vi","xấu đi | trầm trọng thêm | suy thoái","deterioration | getting worse | aggravation","1151470"),
    ("看病","かんびょう","n|vs|vt","chăm sóc người bệnh | trông bệnh","nursing (a patient)","1214030"),
    ("介抱","かいほう","n|vs|vt","chăm sóc | săn sóc (người bệnh, say)","nursing | looking after","1198130"),
    ("養生","ようじょう","n|vs|vi","dưỡng sức | tĩnh dưỡng | bảo dưỡng (che phủ)","taking care of one's health | recuperation | protective covering","1547200"),
    ("休養","きゅうよう","n|vs|vi","nghỉ ngơi | dưỡng sức | tĩnh dưỡng","rest | relaxation | recuperation","1228100"),
    ("静養","せいよう","n|vs|vi","tĩnh dưỡng | nghỉ dưỡng bệnh","(convalescent) rest","1750950"),
    ("保養","ほよう","n|vs|vi","dưỡng sức | nghỉ dưỡng | tiêu khiển","health preservation | recuperation | recreation","1514000"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
