# -*- coding: utf-8 -*-
"""Build N3 ready wave 056 — 86 freshly-curated N3 verbs (〜じる/〜める/〜まる/compound) + defense/aid nouns."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-056.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("占う","うらなう","v5u|vt","bói toán | tiên đoán | dự đoán","to tell someone's fortune | to divine | to predict","1389430"),
    ("委ねる","ゆだねる","v1|vt","phó thác | giao phó | đắm mình vào","to entrust to | to leave to | to abandon oneself to","1156090"),
    ("託す","たくす","v5s|vt","ủy thác | gửi gắm | nhờ chuyển","to entrust with | to leave with | to have someone deliver","1610210"),
    ("授かる","さずかる","v5r|vt","được ban tặng | được trao | được phú cho","to be awarded | to be given | to be blessed with","1330270"),
    ("恵む","めぐむ","v5m|vt","ban phước | bố thí | thương xót","to bless | to show mercy to | to give (alms)","1250480"),
    ("報いる","むくいる","v1|vt|vi","đền đáp | báo đáp | trả thù","to reward | to repay | to retaliate","1515630"),
    ("値する","あたいする","vs-i|vi","đáng giá | xứng đáng | đáng","to be worth | to be worthy of | to deserve","1609040"),
    ("適する","てきする","vs-s|vi","phù hợp | thích hợp | hợp với","to fit | to suit","1437340"),
    ("応じる","おうじる","v1|vi","đáp ứng | hưởng ứng | tùy theo","to respond | to comply with | to accept","1179830"),
    ("応える","こたえる","v1|vi","đáp lại | đáp ứng (kỳ vọng) | thấm","to respond | to meet (expectations) | to take a toll","1179810"),
    ("報じる","ほうじる","v1|vt|vi","đưa tin | báo cáo | báo đáp","to report | to inform | to repay","1515650"),
    ("講じる","こうじる","v1|vt","áp dụng (biện pháp) | giảng | bàn bạc","to take (measures) | to lecture | to devise","1631440"),
    ("投じる","とうじる","v1|vt|vi","ném | bỏ (phiếu) | đầu tư | dốc sức","to throw | to cast (a vote) | to invest | to devote oneself","1447100"),
    ("命じる","めいじる","v1|vt","ra lệnh | bổ nhiệm | chỉ định","to order | to command | to appoint","1531950"),
    ("演じる","えんじる","v1|vt","diễn | đóng vai | gây ra (chuyện)","to act (a part) | to play (a role) | to commit (a blunder)","1176780"),
    ("生じる","しょうじる","v1|vt|vi","phát sinh | sinh ra | nảy sinh","to produce | to cause | to arise | to result from","1378650"),
    ("禁じる","きんじる","v1|vt","cấm | ngăn cấm | kìm nén","to forbid | to ban | to suppress (a feeling)","1241470"),
    ("念じる","ねんじる","v1|vt","cầu nguyện | mong mỏi | niệm (thầm)","to wish (for) | to pray (for) | to recite silently","1469330"),
    ("重んじる","おもんじる","v1|vt","coi trọng | tôn trọng | đề cao","to respect | to esteem | to prize","1335940"),
    ("軽んじる","かろんじる","v1|vt","coi thường | xem nhẹ | khinh","to look down on | to make light of","1252570"),
    ("甘んじる","あまんじる","v1|vi","cam chịu | bằng lòng | an phận","to content oneself with | to be resigned to","1621660"),
    ("論じる","ろんじる","v1|vt","bàn luận | tranh luận | bàn về","to discuss | to argue | to deal with (a topic)","1561620"),
    ("凝る","こる","v5r|vi","mỏi (cơ) | say mê | cầu kỳ | chăm chút","to become stiff | to get absorbed in | to be elaborate","1239070"),
    ("練る","ねる","v5r|vt|vi","nhào | nhồi | trau chuốt (kế hoạch) | rèn","to knead | to polish (a plan) | to refine | to train","1559140"),
    ("研ぐ","とぐ","v5g|vt","mài | mài sắc | vo (gạo) | đánh bóng","to sharpen | to whet | to wash (rice) | to polish","1598700"),
    ("剥がす","はがす","v5s|vt","lột | bóc | gỡ ra","to tear off | to peel off | to strip off","1600670"),
    ("剥がれる","はがれる","v1|vi","bong ra | tróc ra | bong tróc","to come unstuck | to peel off | to come off","1474330"),
    ("捲る","めくる","v5r|vt","lật (trang) | giở | bóc","to turn over | to turn (pages) | to tear off","1257810"),
    ("広める","ひろめる","v1|vt","truyền bá | phổ biến | mở rộng","to spread | to propagate | to broaden","1278460"),
    ("狭める","せばめる","v1|vt","thu hẹp | làm hẹp | giảm","to narrow | to reduce | to contract","1237700"),
    ("強める","つよめる","v1|vt","tăng cường | làm mạnh thêm | nhấn mạnh","to strengthen | to emphasize","1236150"),
    ("弱める","よわめる","v1|vt","làm yếu đi | giảm bớt","to weaken","1324590"),
    ("深める","ふかめる","v1|vt","đào sâu | làm sâu sắc thêm | tăng cường","to deepen | to heighten | to intensify","1362680"),
    ("早める","はやめる","v1|vt","đẩy sớm | làm nhanh hơn | thúc đẩy","to bring forward | to hasten | to quicken | to speed up","1601080"),
    ("遅らせる","おくらせる","v1|vt","làm chậm lại | hoãn | trì hoãn","to delay | to postpone | to slow down","1422010"),
    ("早まる","はやまる","v5r|vi","sớm hơn | hấp tấp | nhanh hơn","to be brought forward | to be hasty | to speed up","1400170"),
    ("薄める","うすめる","v1|vt","pha loãng | làm nhạt | làm dịu","to dilute | to water down | to thin | to soften","1475500"),
    ("加わる","くわわる","v5r|vi","được thêm vào | tham gia | gia tăng","to be added | to join in | to increase","1189980"),
    ("添える","そえる","v1|vt","kèm theo | đính kèm | hỗ trợ","to garnish | to accompany | to add as support","1596490"),
    ("沿う","そう","v5u|vi","chạy dọc | đi theo | tuân theo | đáp ứng","to run along | to follow (a policy) | to meet (expectations)","1176700"),
    ("締める","しめる","v1|vt|vi","buộc | thắt chặt | tổng kết | nghiêm khắc","to fasten | to tighten | to total | to be strict with","1436570"),
    ("寄せる","よせる","v1|vt","ghé sát | tập hợp | gửi (ý kiến, thư) | dồn","to bring near | to gather | to send (a letter) | to push","1219560"),
    ("寄る","よる","v5r|vi","lại gần | tụ tập | ghé qua | dựa vào","to approach | to gather | to stop by | to lean against","1219680"),
    ("集う","つどう","v5u|vi","tụ họp | tụ tập | hội tụ","to meet | to assemble | to congregate","1333540"),
    ("群がる","むらがる","v5r|vi","tụ tập | vây quanh | chen chúc","to swarm | to gather","1247500"),
    ("退ける","しりぞける","v1|vt","từ chối | bác bỏ | đẩy lui | loại bỏ","to reject | to repel | to drive away | to oust","1411260"),
    ("逃す","のがす","v5s|vt","bỏ lỡ | để vuột mất | thả ra","to miss (a chance) | to let get away | to set free","1450430"),
    ("逃がす","にがす","v5s|vt","thả ra | phóng thích | để sổng | bỏ lỡ","to set free | to release | to let get away | to miss","1450320"),
    ("隠す","かくす","v5s|vt","giấu | che giấu | giấu giếm","to hide | to conceal","1170650"),
    ("潜む","ひそむ","v5m|vi","ẩn náu | ẩn giấu | tiềm ẩn","to lurk | to be hidden | to be latent","1391240"),
    ("潜める","ひそめる","v1|vt","giấu kín | hạ thấp (giọng) | náu mình","to hide | to lower (one's voice) | to become inconspicuous","1391250"),
    ("忍ぶ","しのぶ","v5b|vi|vt","ẩn mình | chịu đựng | nhẫn nhịn","to conceal oneself | to endure | to put up with","1467450"),
    ("勤しむ","いそしむ","v5m|vi","chuyên cần | chăm chỉ | dốc sức","to work hard at | to devote oneself to | to be diligent","2087880"),
    ("争う","あらそう","v5u|vi","tranh giành | tranh cãi | đối đầu","to compete | to quarrel | to dispute | to oppose","1400620"),
    ("張り合う","はりあう","v5u|vi","ganh đua | cạnh tranh | đối địch","to compete (with each other) | to vie for | to rival","1427780"),
    ("競り合う","せりあう","v5u|vi","giành giật | cạnh tranh | so kè","to struggle for | to compete with | to vie with","1630160"),
    ("抗う","あらがう","v5u|vi","chống lại | phản kháng | cưỡng lại","to go against | to oppose | to resist","2261110"),
    ("反抗","はんこう","n|vs|vi","phản kháng | chống đối | nổi loạn","opposition | resistance | defiance | rebellion","1480380"),
    ("反撃","はんげき","n|vs|vi","phản công | đánh trả","counterattack | counteroffensive","1480340"),
    ("攻撃","こうげき","n|vs|vt","tấn công | công kích | chỉ trích","attack | assault | offensive | criticism","1279170"),
    ("防衛","ぼうえい","n|vs|vt","phòng vệ | bảo vệ | phòng thủ","defense | protection","1520200"),
    ("守備","しゅび","n|vs|vt","phòng thủ | phòng ngự | (bóng) thủ","defense | fielding","1327180"),
    ("護衛","ごえい","n|vs|vt","hộ tống | bảo vệ | cận vệ","guard | convoy | escort","1271510"),
    ("防御","ぼうぎょ","n|vs|vt","phòng ngự | phòng thủ | bảo vệ","defense | safeguard | protection","1520330"),
    ("備蓄","びちく","n|vs|vt","dự trữ | tích trữ (phòng khẩn cấp)","stockpile | reserves | storing","1485710"),
    ("貯蔵","ちょぞう","n|vs|vt","lưu trữ | dự trữ | tích trữ","storage | preservation | stockpiling","1427220"),
    ("保管","ほかん","n|vs|vt","bảo quản | lưu giữ | cất giữ","custody | safekeeping | storage","1513320"),
    ("監視","かんし","n|vs|vt","giám sát | theo dõi | canh chừng","monitoring | surveillance | supervision","1213680"),
    ("統率","とうそつ","n|vs|vt","chỉ huy | thống lĩnh | lãnh đạo","command | leadership | generalship","1449840"),
    ("率いる","ひきいる","v1|vt","dẫn dắt | thống lĩnh | chỉ huy","to lead | to command (troops)","1551210"),
    ("従える","したがえる","v1|vt","dẫn theo | đem theo | chinh phục","to be accompanied by | to take along | to subjugate","1335220"),
    ("奉仕","ほうし","n|vs|vi","phục vụ | cống hiến | bán giá ưu đãi","service | ministry | offering at a reduced price","1515950"),
    ("貢献","こうけん","n|vs|vi","cống hiến | đóng góp","contribution | services (to a cause)","1282410"),
    ("寄与","きよ","n|vs|vi","đóng góp | cống hiến | giúp ích","contribution | service","1219810"),
    ("補助","ほじょ","n|vs|vt","hỗ trợ | trợ giúp | trợ cấp | bổ trợ","assistance | support | subsidy | supplement","1514590"),
    ("助成","じょせい","n|vs|vt","tài trợ | hỗ trợ | bồi dưỡng","assisting | fostering | aiding","1344700"),
    ("給付","きゅうふ","n|vs|vt","chi trả | cấp phát | trợ cấp","provision | payment | benefit","1230320"),
    ("募金","ぼきん","n|vs|vi","quyên góp | gây quỹ | đóng góp","fundraising | collection of contributions | donation","1514810"),
    ("慈善","じぜん","n","từ thiện | thiện nguyện | nhân ái","charity | benevolence | philanthropy","1315360"),
    ("奉納","ほうのう","n|vs|vt","dâng cúng | tiến cúng | dâng lễ","dedication | offering | oblation","1516090"),
    ("配給","はいきゅう","n|vs|vt","phân phối | phân phát | khẩu phần","distribution | rationing | food ration","1473030"),
    ("分配","ぶんぱい","n|vs|vt","phân chia | chia sẻ | phân phối","division | sharing | distribution | allocation","1504090"),
    ("配分","はいぶん","n|vs|vt","phân bổ | phân chia","distribution | allotment","1473200"),
    ("割り当て","わりあて","n","phân bổ | chỉ tiêu | định mức","allotment | assignment | quota | allocation","1606820"),
    ("支度","したく","n|vs|vt","chuẩn bị | sắm sửa | sửa soạn","preparation | arrangements","1310260"),
    ("用意","ようい","n|vs|vt","chuẩn bị | sắp xếp | sẵn sàng","preparation | arrangements | getting ready","1546220"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
