# -*- coding: utf-8 -*-
"""Build N1 ready wave 079 — advanced katakana loanwords (set 79)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-079.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("アイロニー","アイロニー","n","sự mỉa mai | châm biếm | trớ trêu","irony","1014570"),
    ("アウトライン","アウトライン","n","phác thảo | đường nét chính | đại cương | dàn ý","an outline","1014890"),
    ("アカデミック","アカデミック","adj-na|n","mang tính học thuật | hàn lâm | kinh viện","academic","1015030"),
    ("アクセサリー","アクセサリー","n","phụ kiện | đồ trang sức | đồ trang trí | phụ tùng","an accessory | jewelry","1015220"),
    ("アクセント","アクセント","n","trọng âm | ngữ điệu | điểm nhấn | sự nhấn mạnh","an accent | stress | emphasis","1015310"),
    ("アジテーション","アジテーション","n","sự kích động | sự xúi giục | sự khích động quần chúng","agitation","1015870"),
    ("アプローチ","アプローチ","n|vs|vi","cách tiếp cận | phương pháp | sự tiếp cận | đường dẫn vào","an approach (to a problem)","1018260"),
    ("アマチュア","アマチュア","n|adj-no","nghiệp dư | tay ngang | không chuyên","an amateur","1018550"),
    ("アンビバレント","アンビバレント","adj-na","mâu thuẫn nội tâm | nước đôi | vừa yêu vừa ghét | lưỡng lự cảm xúc","ambivalent","2801200"),
    ("イデオロギー","イデオロギー","n","hệ tư tưởng | ý thức hệ | tư tưởng","ideology","1021500"),
    ("イノベーション","イノベーション","n","sự đổi mới | cách tân | sáng tạo đột phá","innovation","1021630"),
    ("インスピレーション","インスピレーション","n","nguồn cảm hứng | linh cảm | sự khơi gợi","inspiration","1022660"),
    ("インセンティブ","インセンティブ","n","động lực | sự khích lệ | tiền thưởng khuyến khích | ưu đãi","an incentive","1022720"),
    ("インテリジェンス","インテリジェンス","n","trí tuệ | trí thông minh | tình báo","intelligence","1023490"),
    ("エキセントリック","エキセントリック","adj-na","lập dị | kỳ quặc | khác người | quái dị","eccentric","1027850"),
    ("エゴ","エゴ","n","cái tôi | bản ngã | tính ích kỷ | sự vị kỷ","ego | egoism","1028420"),
    ("エッセンス","エッセンス","n","tinh chất | bản chất | tinh túy | cốt lõi | tinh dầu","essence | extract","1029140"),
    ("エピソード","エピソード","n","giai thoại | mẩu chuyện | tập (phim) | tình tiết","an episode | an anecdote","1029620"),
    ("エリート","エリート","n|adj-no","tinh hoa | ưu tú | tầng lớp ưu tú | giới tinh anh","an elite","1030090"),
    ("エレガント","エレガント","adj-na","thanh lịch | tao nhã | sang trọng | duyên dáng","elegant","1030350"),
    ("オーソドックス","オーソドックス","adj-na","chính thống | truyền thống | theo lối cổ điển | quy chuẩn","orthodox","1031730"),
    ("オートマチック","オートマチック","adj-no|adj-na|n","tự động | máy tự động | súng tự động | hộp số tự động","automatic","1032100"),
    ("オリジナリティー","オリジナリティー","n","tính độc đáo | sự nguyên bản | nét riêng | tính sáng tạo","originality","1035630"),
    ("カリスマ","カリスマ","n|adj-f","sức hút | uy tín lôi cuốn | thần thái cuốn hút | thần tượng","charisma | a charismatic person","1038790"),
    ("ガイドライン","ガイドライン","n","hướng dẫn | nguyên tắc chỉ đạo | quy tắc định hướng | khung hướng dẫn","a guideline","1039940"),
    ("キャリア","キャリア","n","sự nghiệp | kinh nghiệm nghề nghiệp | quá trình công tác | công chức cấp cao","a career | professional experience","1041980"),
    ("グローバル","グローバル","adj-na","toàn cầu | mang tính quốc tế | trên phạm vi thế giới","global","1047700"),
    ("コラボレーション","コラボレーション","n|vs|vi","sự hợp tác | cộng tác | hợp tác chung | kết hợp","collaboration","1051320"),
    ("コンスタント","コンスタント","adj-na|n","ổn định | đều đặn | nhất quán | không đổi | hằng số","constant | steady","1052190"),
    ("コンセプト","コンセプト","n","ý tưởng | concept | quan niệm | chủ đề | triết lý chủ đạo","a concept | a general idea","1052280"),
    ("コンセンサス","コンセンサス","n","sự đồng thuận | nhất trí chung | thỏa thuận tập thể","consensus","1052320"),
    ("コントラスト","コントラスト","n","sự tương phản | độ tương phản | sự đối lập","contrast","1052780"),
    ("コンプレックス","コンプレックス","n","mặc cảm | phức cảm tự ti | tổ hợp (công trình)","a complex | an inferiority complex","1053800"),
    ("コンプライアンス","コンプライアンス","n","sự tuân thủ | tuân thủ quy định | tuân thủ pháp luật","compliance","1053740"),
    ("サジェスチョン","サジェスチョン","n","gợi ý | đề xuất | lời khuyên | sự gợi mở","a suggestion","1056540"),
    ("ジレンマ","ジレンマ","n","thế tiến thoái lưỡng nan | tình thế khó xử | nan đề","a dilemma","1066560"),
    ("シニカル","シニカル","adj-na","hoài nghi yếm thế | cay độc | mỉa mai chua chát | bi quan giễu cợt","cynical","1060870"),
    ("シミュレーション","シミュレーション","n|vs|vt","sự mô phỏng | giả lập | diễn tập | mô hình hóa","simulation","1061210"),
    ("シリアス","シリアス","adj-na|n","nghiêm túc | nghiêm trọng | hệ trọng | căng thẳng","serious","1062930"),
    ("スキャンダル","スキャンダル","n","vụ bê bối | tai tiếng | xì căng đan","a scandal","1068010"),
    ("ステータス","ステータス","n","địa vị | vị thế | đẳng cấp | thân phận | trạng thái","status","1070330"),
    ("ストイック","ストイック","adj-na|n","khắc kỷ | kỷ luật cao | nghiêm khắc với bản thân | khổ hạnh","stoic | self-disciplined","1070980"),
    ("ストラテジー","ストラテジー","n","chiến lược | sách lược | đường lối","strategy","1071260"),
    ("スペック","スペック","n","thông số kỹ thuật | cấu hình | đặc tả | quy cách","specifications | specs","1073090"),
    ("セオリー","セオリー","n","lý thuyết | nguyên lý | quy trình chuẩn | chiến thuật thường lệ","theory | standard procedure","1074410"),
    ("セクション","セクション","n","bộ phận | mục | phần | khu vực | tiết đoạn","a section","1074490"),
    ("センセーション","センセーション","n","sự chấn động | cơn sốt dư luận | sự gây xôn xao","a sensation","1075020"),
    ("センチメンタル","センチメンタル","adj-na|n","đa cảm | ủy mị | sướt mướt | dễ xúc động","sentimental","1075080"),
    ("ソリューション","ソリューション","n","giải pháp | lời giải | phương án giải quyết | dung dịch","a solution","1929880"),
    ("ターニングポイント","ターニングポイント","n","bước ngoặt | điểm xoay chuyển | điểm chuyển biến","a turning point","2183800"),
    ("タブー","タブー","n","điều cấm kỵ | điều kiêng kỵ | điều cấm","a taboo","1076400"),
    ("ダイナミック","ダイナミック","adj-na","năng động | sôi động | đầy sức sống | mạnh mẽ linh hoạt","dynamic","1076820"),
    ("デリケート","デリケート","adj-na","nhạy cảm | tế nhị | mong manh | tinh tế | dễ tổn thương","sensitive | delicate","1084320"),
    ("デモンストレーション","デモンストレーション","n","sự trình diễn | màn biểu diễn | cuộc biểu tình | sự phô diễn","a demonstration","1084080"),
    ("トラウマ","トラウマ","n","sang chấn tâm lý | vết thương lòng | ám ảnh tâm lý","(psychological) trauma","1085640"),
    ("ドグマ","ドグマ","n","giáo điều | tín điều | nguyên lý cứng nhắc","dogma","1088190"),
    ("ナイーブ","ナイーブ","adj-na|n","ngây thơ | nhạy cảm | chất phác | thật thà | mộc mạc","innocent | sensitive | unpretentious","1089660"),
    ("ナンセンス","ナンセンス","n|adj-na","vô nghĩa | nhảm nhí | vô lý | lố bịch","nonsense","1090840"),
    ("ニーズ","ニーズ","n","nhu cầu | yêu cầu | đòi hỏi | nguyện vọng","needs | demands","1090960"),
    ("ニュアンス","ニュアンス","n","sắc thái | nghĩa hàm ẩn | tế nhị trong ý | ý vị tinh tế","nuance","1092110"),
    ("ネガティブ","ネガティブ","adj-na|n","tiêu cực | bi quan | âm tính | phim âm bản","negative","1092790"),
    ("ノスタルジー","ノスタルジー","n","nỗi hoài niệm | nỗi nhớ quá khứ | tâm trạng hoài cổ","nostalgia","1093870"),
    ("ノルマ","ノルマ","n","chỉ tiêu | định mức | hạn ngạch | nhiệm vụ được giao","one's quota | an assignment","2037400"),
    ("ハードル","ハードル","n","rào cản | chướng ngại | trở ngại | môn chạy vượt rào","a hurdle | an obstacle","1094650"),
    ("バイアス","バイアス","n","thiên kiến | sự thiên lệch | định kiến | khuynh hướng lệch","bias","1097460"),
    ("バリエーション","バリエーション","n","biến thể | sự đa dạng | các kiểu | biến tấu","variation","1099760"),
    ("パラドックス","パラドックス","n","nghịch lý | điều ngược đời | mâu thuẫn biểu kiến","paradox","1102560"),
    ("ヒエラルキー","ヒエラルキー","n","hệ thống thứ bậc | tôn ti trật tự | hệ cấp bậc","hierarchy","1103660"),
    ("ビジョン","ビジョン","n","tầm nhìn | viễn cảnh | hình dung tương lai | tầm nhìn chiến lược","a vision","1105070"),
    ("ファクター","ファクター","n","yếu tố | nhân tố | thừa số | nhân tố tác động","a factor","1107980"),
    ("フィードバック","フィードバック","n|vs|vt|vi","phản hồi | ý kiến đóng góp | sự hồi đáp | hồi tiếp","feedback","1108840"),
    ("フォーマル","フォーマル","adj-na","trang trọng | chính thức | nghi thức | lịch sự","formal","1110290"),
    ("プロセス","プロセス","n","quá trình | tiến trình | quy trình | các bước","a process","1117310"),
    ("ペシミスト","ペシミスト","adj-na|n","người bi quan | kẻ yếm thế | người hay nghĩ tiêu cực","a pessimist","1120870"),
    ("ポテンシャル","ポテンシャル","n","tiềm năng | tiềm lực | khả năng tiềm ẩn | thế năng","potential","1125440"),
    ("ポリシー","ポリシー","n","chính sách | phương châm | nguyên tắc | đường lối","policy","1125710"),
    ("マイノリティー","マイノリティー","n","thiểu số | nhóm thiểu số | cộng đồng thiểu số","minority","1127020"),
    ("マジョリティー","マジョリティー","n","đa số | phần đông | nhóm đa số","majority","1127770"),
    ("モチベーション","モチベーション","n","động lực | động cơ | sự thúc đẩy | tinh thần phấn đấu","motivation","1135080"),
    ("モラル","モラル","n","đạo đức | luân lý | luân thường | phẩm hạnh","morals | ethics","1135820"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
