# -*- coding: utf-8 -*-
"""Build N3 ready wave 042 — the remaining 165 curated N3 source words.
Readings/pos/source_id pulled from japanese_raw_jmdict; meaning_vi authored by hand.
4 homograph readings corrected: 変化→へんか, 地震→じしん, 伝言→でんごん, 温める→あたためる.
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-042.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, pos, vi, en, sid):
    return ",".join([q(word), q(reading), q(""), q("N3"), q(pos), q(vi), q(en), q(""), q("0"),
        q("jmdict"), q(sid), q(LIC), q("JMdict/EDRDG"), q(""), q(""), q(""), q(""), q("ai_draft"), q("jmdict_ai")])

# (word, reading, pos, meaning_vi, meaning_en, source_id)
DATA = [
    ("解決","かいけつ","n|vs|vt|vi","giải quyết | giải pháp | sự dàn xếp","settlement | solution | resolution","1198960"),
    ("結果","けっか","n|adv|vs|vi","kết quả | hậu quả | hệ quả","result | consequence | outcome | effect","1254690"),
    ("影響","えいきょう","n|vs|vi","ảnh hưởng | tác động","influence | effect | impact","1173660"),
    ("変化","へんか","n|vs|vi","thay đổi | biến hóa | biến đổi | sự chuyển biến","change | variation | alteration | transformation","1510890"),
    ("発展","はってん","n|vs|vi","phát triển | mở rộng | hưng thịnh","development | growth | expansion | advancement","1477720"),
    ("研究","けんきゅう","n|vs|vt","nghiên cứu | khảo cứu","research | study | investigation","1258520"),
    ("調査","ちょうさ","n|vs|vt","điều tra | khảo sát | thẩm tra","investigation | examination | inquiry | survey","1429120"),
    ("報告","ほうこく","n|vs|vt","báo cáo | thông báo","report | information","1515670"),
    ("議論","ぎろん","n|vs|vt","tranh luận | thảo luận | bàn cãi","argument | discussion | dispute | controversy","1226160"),
    ("目標","もくひょう","n","mục tiêu | đích | chỉ tiêu | dấu mốc","goal | target | aim | objective | mark","1535650"),
    ("状況","じょうきょう","n","tình hình | hoàn cảnh | tình trạng","state of affairs | situation | conditions | circumstances","1356700"),
    ("重要","じゅうよう","adj-na","quan trọng | trọng yếu | thiết yếu","important | essential | significant | key","1336820"),
    ("正確","せいかく","adj-na|n","chính xác | đúng đắn","accurate | correct | precise | exact","1376760"),
    ("明確","めいかく","adj-na","rõ ràng | minh bạch | rành mạch","clear | precise | definite | distinct","1532410"),
    ("具体的","ぐたいてき","adj-na","cụ thể | xác thực | rõ ràng","concrete | definite | specific | substantial","1245050"),
    ("特徴","とくちょう","n","đặc trưng | đặc điểm | nét riêng","feature | trait | characteristic | distinction","1455170"),
    ("比較","ひかく","n|vs|vt","so sánh | đối chiếu","comparison","1483560"),
    ("分析","ぶんせき","n|vs|vt","phân tích","analysis","1503870"),
    ("感動","かんどう","n|vs|vi","cảm động | xúc động | rung động","being deeply moved | excitement | deep emotion | strong impression","1212570"),
    ("怒り","いかり","n","sự tức giận | cơn giận | phẫn nộ","anger | rage | fury | wrath","1445670"),
    ("悲しみ","かなしみ","n","nỗi buồn | sự đau buồn | sầu thương","sadness | sorrow | grief","1590550"),
    ("期待","きたい","n|vs|vt|vi","kỳ vọng | mong đợi | trông chờ","expectation | anticipation | hope","1220570"),
    ("失望","しつぼう","n|vs|vi","thất vọng | tuyệt vọng","disappointment | despair","1320170"),
    ("記憶","きおく","n|vs|vt","ký ức | trí nhớ | sự ghi nhớ","memory | recollection | remembrance","1223150"),
    ("信頼","しんらい","n|vs|vt","tin tưởng | tín nhiệm | tin cậy","trust | confidence | faith | reliance","1359730"),
    ("批判","ひはん","n|vs|vt","phê phán | phê bình | chỉ trích","criticism | judgement | comment","1483420"),
    ("賛成","さんせい","n|vs|vi","tán thành | đồng ý | ủng hộ","approval | agreement | support | favour","1304200"),
    ("主張","しゅちょう","n|vs|vt","chủ trương | khẳng định | luận điểm","claim | insistence | assertion | contention","1325910"),
    ("証明","しょうめい","n|vs|vt","chứng minh | chứng nhận | xác minh","proof | demonstration | verification | certification","1351680"),
    ("観察","かんさつ","n|vs|vt","quan sát | theo dõi | khảo sát","observation | survey | watching","1214900"),
    ("実験","じっけん","n|vs|vt","thí nghiệm | thực nghiệm","experiment | experimentation","1320970"),
    ("契約","けいやく","n|vs|vt","hợp đồng | giao kèo | thỏa thuận","contract | compact | agreement","1250190"),
    ("収入","しゅうにゅう","n","thu nhập | doanh thu | khoản thu","income | earnings | revenue | proceeds","1330790"),
    ("利益","りえき","n|vs|vt","lợi nhuận | lợi ích | quyền lợi","profit | gains | benefit | advantage","1549470"),
    ("申請","しんせい","n|vs|vt","đơn xin | thỉnh cầu | đề nghị","application | request | petition","1363130"),
    ("許可","きょか","n|vs|vt","cho phép | giấy phép | phê chuẩn","permission | approval | authorization | license","1232880"),
    ("承認","しょうにん","n|vs|vt","phê duyệt | công nhận | chấp thuận","recognition | acknowledgement | approval | consent","1349520"),
    ("地域","ちいき","n","khu vực | vùng | địa phương","area | region | district | locality","1420800"),
    ("環境","かんきょう","n","môi trường | hoàn cảnh xung quanh","environment | surroundings | circumstances","1213280"),
    ("資源","しげん","n","tài nguyên | nguồn lực","resources","1312720"),
    ("消費","しょうひ","n|vs|vt","tiêu thụ | tiêu dùng | chi tiêu","consumption | expenditure | spending","1350290"),
    ("生産","せいさん","n|vs|vt","sản xuất | chế tạo","production | manufacture","1378990"),
    ("輸出","ゆしゅつ","n|vs|vt","xuất khẩu","export | exportation","1538820"),
    ("輸入","ゆにゅう","n|vs|vt","nhập khẩu","import | importation","1538870"),
    ("貿易","ぼうえき","n|vs|vi","mậu dịch | thương mại | giao thương","(foreign) trade | (international) commerce","1520120"),
    ("制度","せいど","n","chế độ | thể chế | hệ thống","system | institution | organization","1374880"),
    ("規制","きせい","n|vs|vt","quy chế | kiểm soát | hạn chế","regulation | control | restriction","1223010"),
    ("条件","じょうけん","n","điều kiện | điều khoản | yêu cầu","condition | term | requirement | prerequisite","1356510"),
    ("基準","きじゅん","n","tiêu chuẩn | chuẩn mực | mốc chuẩn","standard | criterion | norm | benchmark","1591210"),
    ("論文","ろんぶん","n","luận văn | bài luận | luận án","thesis | essay | treatise | paper","1561840"),
    ("資料","しりょう","n","tài liệu | dữ liệu | tư liệu","material | data | information | documents","1312820"),
    ("技能","ぎのう","n","kỹ năng | tay nghề | năng lực","technical skill | ability | capacity","1225230"),
    ("才能","さいのう","n","tài năng | năng khiếu","talent | ability","1294630"),
    ("期間","きかん","n","thời kỳ | thời hạn | khoảng thời gian","period | term | interval","1220550"),
    ("過程","かてい","n","quá trình | tiến trình","process | course | mechanism","1196270"),
    ("手順","てじゅん","n","trình tự | quy trình | thủ tục","process | procedure | sequence | protocol","1327810"),
    ("段階","だんかい","n","giai đoạn | bước | cấp độ","stage | step | phase | level","1419950"),
    ("手段","しゅだん","n","phương tiện | biện pháp | cách thức","means | way | measure","1328110"),
    ("方針","ほうしん","n","phương châm | đường lối | kế hoạch","policy | course | plan (of action) | principle","1517040"),
    ("課題","かだい","n","đề tài | nhiệm vụ | bài tập | vấn đề","subject | theme | issue | assignment | task","1195820"),
    ("根拠","こんきょ","n","căn cứ | cơ sở | nền tảng","basis | grounds | foundation | reason","1290120"),
    ("前提","ぜんてい","n","tiền đề | điều kiện tiên quyết | giả định","condition | assumption | prerequisite | premise","1393680"),
    ("傾向","けいこう","n","khuynh hướng | xu hướng","tendency | trend | inclination","1249470"),
    ("意図","いと","n|vs|vt","ý đồ | ý định | dụng ý","intention | aim | design","1156690"),
    ("欠点","けってん","n","khuyết điểm | nhược điểm | thiếu sót","fault | defect | flaw | weak point | drawback","1254050"),
    ("結構","けっこう","adj-na|adv|n","tốt | ổn | đủ rồi | khá | kết cấu","splendid | fine | sufficient | all right | quite | structure","1254760"),
    ("隙間","すきま","n","khe hở | kẽ hở | khoảng trống","gap | opening | crevice | crack | space","1253790"),
    ("仕草","しぐさ","n","cử chỉ | điệu bộ | hành động","gesture | movement | action | behavior","1305210"),
    ("即ち","すなわち","conj","tức là | nói cách khác | nghĩa là","that is (to say) | namely | i.e.","1404100"),
    ("足取り","あしどり","n","dáng đi | bước chân | dấu vết","gait | walk | stride | step | trace | trail","1404830"),
    ("足場","あしば","n","giàn giáo | chỗ đặt chân | bàn đạp","scaffold | scaffolding | foothold | footing","1404860"),
    ("一応","いちおう","n|adv","tạm thời | đại khái | cho chắc | một lần","more or less | for the time being | just in case | tentatively","1161170"),
    ("一気に","いっきに","adv","một mạch | một hơi | trong một lần","in one go | in one breath | without stopping | all at once","1161730"),
    ("加減","かげん","n|vs|vt","mức độ | sự điều chỉnh | tình trạng | cộng trừ","degree | adjustment | condition | addition and subtraction","1190080"),
    ("可愛がる","かわいがる","v5r|vt","yêu thương | cưng chiều | quý mến","to be affectionate to | to dote on | to cherish","1190730"),
    ("機嫌","きげん","n|adj-na","tâm trạng | tính khí | tâm trạng tốt","humour | temper | mood | spirits","1220930"),
    ("機関","きかん","n","cơ quan | tổ chức | động cơ | bộ máy","engine | agency | organization | institution","1220870"),
    ("仕掛ける","しかける","v1|vt","khơi mào | gây | cài đặt | bắt đầu","to start | to challenge | to set (traps) | to plant","1304820"),
    ("仕切る","しきる","v5r|vt|vi","ngăn chia | quản lý | điều hành | quyết toán","to partition | to divide | to manage | to settle accounts","1305180"),
    ("大使館","たいしかん","n","đại sứ quán","embassy","1413890"),
    ("暖房","だんぼう","n|vs|vt","sưởi ấm | máy sưởi","(indoor) heating","1419860"),
    ("地震","じしん","n","động đất","earthquake","1421210"),
    ("地図","ちず","n","bản đồ | sơ đồ","map | atlas | chart | plan","1421290"),
    ("両替","りょうがえ","n|vs|vt","đổi tiền | quy đổi tiền tệ","change | money exchange","1553820"),
    ("領収書","りょうしゅうしょ","n","biên lai | hóa đơn thu tiền","formal receipt (of payment)","1554760"),
    ("例外","れいがい","n|adj-no","ngoại lệ | trường hợp đặc biệt","exception","1556410"),
    ("冷える","ひえる","v1|vi","trở lạnh | nguội đi | mát đi","to grow cold | to get chilly | to cool down","1556630"),
    ("冷静","れいせい","n|adj-na","bình tĩnh | điềm tĩnh | trầm tĩnh","calmness | composure | coolness | serenity","1557050"),
    ("冷房","れいぼう","n|vs|vt","điều hòa | làm mát","air conditioning | air cooling","1557290"),
    ("励ます","はげます","v5s|vt","động viên | cổ vũ | khích lệ","to encourage | to cheer on | to cheer up","1557350"),
    ("礼儀","れいぎ","n","lễ nghĩa | phép lịch sự | nghi thức","manners | courtesy | etiquette","1557470"),
    ("恋しい","こいしい","adj-i","nhớ nhung | khao khát | mong nhớ","yearned for | longed for | missed","1558760"),
    ("連絡先","れんらくさき","n","thông tin liên lạc | địa chỉ liên hệ","contact information (address, phone number, etc.)","1559930"),
    ("路線","ろせん","n","tuyến đường | tuyến | đường lối","route (bus, train, etc.) | line | policy | course","1560040"),
    ("廊下","ろうか","n","hành lang | lối đi","corridor | hallway | passageway","1560670"),
    ("朗らか","ほがらか","adj-na","vui vẻ | tươi sáng | rạng rỡ","cheerful | merry | sunny | bright | clear","1560710"),
    ("浪費","ろうひ","n|vs|vt","lãng phí | phung phí","waste | extravagance","1560800"),
    ("論争","ろんそう","n|vs|vi","tranh luận | tranh cãi","dispute | controversy | debate | argument","1561760"),
    ("論点","ろんてん","n","luận điểm | vấn đề tranh luận","point in question (at issue)","1561800"),
    ("論理","ろんり","n","lý luận | logic","logic","1561850"),
    ("論理的","ろんりてき","adj-na","mang tính logic | hợp lý","logical","1561890"),
    ("和室","わしつ","n","phòng kiểu Nhật","Japanese-style room","1562110"),
    ("和食","わしょく","n","món ăn Nhật | ẩm thực Nhật","Japanese food | Japanese cuisine","1562130"),
    ("話し合う","はなしあう","v5u|vt","bàn bạc | thảo luận | nói chuyện cùng nhau","to discuss | to talk together","1562310"),
    ("途中","とちゅう","n|adv","trên đường | giữa chừng | nửa chừng","on the way | en route | in the middle of | halfway","1582200"),
    ("伝言","でんごん","n|vs|vt","lời nhắn | tin nhắn (lời)","(verbal) message | word (from someone)","1582180"),
    ("梅雨","つゆ","n","mùa mưa (đầu hè) | mưa mùa","(East Asian) rainy season | rain during the rainy season","1582960"),
    ("燃やす","もやす","v5s|vt","đốt | thiêu | nung nấu (cảm xúc)","to burn | to burn with (emotion)","1582900"),
    ("文書","ぶんしょ","n","văn bản | tài liệu | giấy tờ","document | writing | letter | papers | records","1583840"),
    ("夫婦","ふうふ","n","vợ chồng | cặp vợ chồng","married couple | husband and wife","1583640"),
    ("牧場","ぼくじょう","n","nông trại | trang trại chăn nuôi | đồng cỏ","farm (livestock) | ranch | pasture","1584250"),
    ("頬","ほお","n","má","cheek (of the face)","1584160"),
    ("浴衣","ゆかた","n","yukata | kimono cotton mỏng mặc mùa hè","yukata | light cotton kimono worn in summer","1584990"),
    ("落ち葉","おちば","n","lá rụng | lá khô rơi","fallen leaves | leaf litter | falling leaves","1585070"),
    ("温まる","あたたまる","v5r|vi","ấm lên | sưởi ấm","to warm oneself | to warm up | to get warm","1586430"),
    ("温める","あたためる","v1|vt","làm ấm | hâm nóng | ấp ủ (ý tưởng)","to warm (up) | to heat (up) | to sit on (an idea)","1586440"),
    ("暗記","あんき","n|vs|vt","học thuộc lòng | ghi nhớ","memorization | learning by heart","1586910"),
    ("言い訳","いいわけ","n|vs|vt","lời bào chữa | sự biện minh | thanh minh","excuse | explanation","1587030"),
    ("受付","うけつけ","n|vs|vt","lễ tân | quầy tiếp nhận | sự tiếp nhận","reception (desk) | information desk | acceptance","1588060"),
    ("打ち明ける","うちあける","v1|vt","thổ lộ | tâm sự | bộc bạch","to confide | to reveal | to disclose | to speak frankly","1588130"),
    ("打ち合わせ","うちあわせ","n|vs|vt","buổi họp bàn | sự trao đổi trước","(preparatory) meeting | briefing | advance arrangements","1588140"),
    ("思いつく","おもいつく","v5k|vt|vi","nghĩ ra | chợt nghĩ | nhớ ra","to think of | to hit upon | to recall","1589330"),
    ("仮説","かせつ","n","giả thuyết | giả định","hypothesis | supposition | assumption","1590320"),
    ("傷つく","きずつく","v5k|vi","bị thương | tổn thương | bị xước","to be wounded | to get hurt | to get damaged | to get scratched","1591240"),
    ("交差点","こうさてん","n","ngã tư | giao lộ","crossing | intersection","1592970"),
    ("交代","こうたい","n|vs|vt|vi","thay phiên | luân phiên | thay thế","change | alternation | rotation | shift","1592990"),
    ("木漏れ日","こもれび","n","nắng xuyên kẽ lá","sunlight filtering through trees","1593440"),
    ("砂漠","さばく","n","sa mạc | hoang mạc","desert","1593800"),
    ("幸せ","しあわせ","n|adj-na","hạnh phúc | may mắn | phúc lành","happiness | good fortune | luck | blessing","1594060"),
    ("仕方","しかた","n","cách làm | phương pháp | cách thức","way | method | means","1594110"),
    ("支払い","しはらい","n","sự chi trả | thanh toán","payment","1594480"),
    ("締め切り","しめきり","n","hạn chót | thời hạn cuối","deadline | closing | cut-off","1594590"),
    ("醤油","しょうゆ","n","nước tương | xì dầu","soy sauce | soya sauce","1595020"),
    ("清々しい","すがすがしい","adj-i","sảng khoái | trong lành | tươi mát","refreshing | brisk | bracing | fresh","1595560"),
    ("徐々に","じょじょに","adv","dần dần | từ từ | từng bước","gradually | steadily | little by little | step by step","1595480"),
    ("掃除機","そうじき","n","máy hút bụi","vacuum cleaner","1596390"),
    ("台風","たいふう","n","bão | cuồng phong","typhoon | hurricane","1596780"),
    ("ため息","ためいき","n","tiếng thở dài","sigh","1597190"),
    ("頼る","たよる","v5r|vi|vt","dựa vào | trông cậy | nương tựa","to rely on | to depend on | to count on","1597200"),
    ("近道","ちかみち","n|vs|vi","đường tắt | lối đi gần","shorter way | shortcut","1597380"),
    ("直径","ちょっけい","n","đường kính","diameter","1597720"),
    ("手がかり","てがかり","n","manh mối | đầu mối | điểm tựa tay","clue | lead | key | trail | handhold","1598300"),
    ("手続き","てつづき","n","thủ tục | trình tự | quy trình","procedure | process | proceedings | formalities","1598350"),
    ("問い合わせ","といあわせ","n","sự hỏi thông tin | truy vấn","inquiry | query | enquiry","1598590"),
    ("取り扱い","とりあつかい","n","sự xử lý | cách sử dụng | dịch vụ","treatment | service | handling | management","1598990"),
    ("取り組み","とりくみ","n","nỗ lực | sự bắt tay vào | trận đấu","effort | initiative | dealing with | bout (sumo)","1599040"),
    ("取引","とりひき","n|vs|vt","giao dịch | mua bán | làm ăn","transactions | dealings | business","1599120"),
    ("同盟","どうめい","n|vs|vi","liên minh | đồng minh","alliance | union | league","1599290"),
    ("情けない","なさけない","adj-i","đáng thương | thảm hại | đáng xấu hổ","miserable | pitiable | shameful | pathetic","1599480"),
    ("成り行き","なりゆき","n","diễn biến | tiến triển | kết cục","course (of events) | development | progress | outcome","1599700"),
    ("値上がり","ねあがり","n|vs|vi","sự tăng giá","price increase | rise in price","1600020"),
    ("値段","ねだん","n","giá cả | giá tiền","price | cost","1600160"),
    ("値引き","ねびき","n|vs|vt","giảm giá | chiết khấu","price reduction | discount","1600190"),
    ("年齢","ねんれい","n","tuổi | độ tuổi","age | years","1600240"),
    ("乗り換える","のりかえる","v1|vt","đổi xe | chuyển tàu | chuyển sang","to transfer (trains) | to change | to switch to","1600470"),
    ("乗り物","のりもの","n","phương tiện đi lại | xe cộ","vehicle | conveyance | means of transport","1600530"),
    ("飲み物","のみもの","n","đồ uống | thức uống","drink | beverage","1600430"),
    ("引き出し","ひきだし","n","ngăn kéo | sự rút tiền | vốn kinh nghiệm","drawer | withdrawal (of money) | variety of knowledge","1601650"),
    ("引っ越し","ひっこし","n|vs|vi","chuyển nhà | dọn nhà","moving (dwelling, office) | changing residence","1601880"),
    ("広がる","ひろがる","v5r|vi","lan rộng | trải rộng | mở rộng ra","to spread (out) | to extend | to stretch","1602360"),
    ("増える","ふえる","v1|vi","tăng lên | gia tăng","to increase | to multiply","1602440"),
    ("踏切","ふみきり","n","chỗ đường ray giao nhau | vạch xuất phát","railway crossing | level crossing | starting line","1602840"),
    ("増やす","ふやす","v5s|vt","làm tăng | gia tăng | bổ sung","to increase | to add to | to augment","1602880"),
    ("部署","ぶしょ","n","bộ phận | phòng ban | vị trí công tác","one's post | department | bureau | section","1603140"),
    ("包帯","ほうたい","n|vs|vt","băng (gạc) | sự băng bó","bandage | dressing","1603360"),
]

rows = [row(*d) for d in DATA]
content = HEADER + "\n" + "\n".join(rows) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(rows)} rows to {os.path.abspath(OUT)}")
