# -*- coding: utf-8 -*-
OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n3-vi-ready-009.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id):
    return ",".join([q(word), q(reading), q(""), q(lvl), q(pos), q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"), q(""), q(""), q(""), q(""), q("ai_draft"), q("jmdict_ai")])

ROWS = [
    row("旗","はた","N3","n",
        "lá cờ | biểu ngữ | cờ hiệu",
        "flag | pataka (banner) | banner","1220240"),
    row("激動","げきどう","N3","n|vs|vi",
        "biến động dữ dội | chấn động | xáo trộn lớn",
        "violent shock | agitation | turbulence | turmoil | upheaval","1253720"),
    row("激戦","げきせん","N3","n|vs|vi",
        "trận chiến quyết liệt | cuộc đấu khốc liệt",
        "fierce battle | hard-fought battle | hot contest | severe fighting","1253680"),
    row("激流","げきりゅう","N3","n",
        "dòng chảy xiết | thác ghềnh | dòng cuồn cuộn",
        "raging stream | rapids","1253750"),
    row("欠勤","けっきん","N3","n|vs|vi",
        "vắng mặt (tại nơi làm việc) | nghỉ làm không phép",
        "absence (from work)","1253960"),
    row("欠航","けっこう","N3","n|vs|vi",
        "hủy chuyến (bay hoặc tàu thủy)",
        "cancellation (of a flight or sea voyage)","1253980"),
    row("決議","けつぎ","N3","n|vs|vt",
        "nghị quyết | quyết định (chính thức)",
        "resolution | vote | decision","1254240"),
    row("決行","けっこう","N3","n|vs|vt",
        "quyết tâm thực hiện | tiến hành dứt khoát",
        "doing (with resolve) | carrying out (e.g. a plan) | going ahead with","1254250"),
    row("決済","けっさい","N3","n|vs|vt",
        "thanh toán (tài khoản) | quyết toán | trả nợ",
        "settlement (of an account) | liquidation of debts | payment","1254260"),
    row("決裂","けつれつ","N3","n|vs|vi",
        "tan vỡ (đàm phán) | đổ vỡ | sụp đổ",
        "breakdown (of talks, negotiations, etc.) | breaking off | rupture","1254430"),
    row("結成","けっせい","N3","n|vs|vt",
        "thành lập | hình thành (tổ chức, đoàn thể)",
        "formation | combination","1254900"),
    row("血縁","けつえん","N3","adj-no|n",
        "quan hệ huyết thống | họ hàng máu mủ",
        "blood relationship | consanguinity | blood relative","1255170"),
    row("血統","けっとう","N3","n",
        "dòng máu | huyết thống | gia phả | nòi giống",
        "lineage | pedigree | family line | birth","1255360"),
    row("幻滅","げんめつ","N3","n|vs|vi",
        "vỡ mộng | thất vọng | ảo tưởng tan vỡ",
        "disillusionment | disillusion | disenchantment","1263010"),
    row("現役","げんえき","N3","adj-no|n",
        "đang tại ngũ | đang hoạt động | đang ôn thi đại học",
        "active duty | active service | student taking university entrance exams","1263890"),
    row("現状","げんじょう","N3","n",
        "tình trạng hiện tại | hiện trạng | nguyên trạng",
        "present condition | existing state | status quo | current state","1263770"),
    row("権威","けんい","N3","adj-no|n",
        "thẩm quyền | uy tín | quyền uy | chuyên gia có uy tín",
        "authority | power | influence | prestige | (an) authority (on a subject)","1258090"),
    row("権限","けんげん","N3","n",
        "quyền hạn | thẩm quyền | phạm vi quyền lực",
        "power | authority | jurisdiction","1258130"),
    row("権力","けんりょく","N3","n",
        "quyền lực (chính trị) | thẩm quyền | ảnh hưởng",
        "(political) power | authority | influence","1258220"),
    row("謙遜","けんそん","N3","adj-na|n|vs|vi",
        "khiêm tốn | khiêm nhường | hạ mình",
        "modesty | humility | being humble","1260240"),
    row("残暑","ざんしょ","N3","n",
        "nắng nóng cuối hè | hơi nóng còn sót lại sau mùa hè",
        "late summer heat | lingering summer heat","1304620"),
    row("残像","ざんぞう","N3","n",
        "ảnh lưu | hình ảnh còn lại trên võng mạc",
        "afterimage | after image","1304640"),
    row("仕業","しわざ","N3","n",
        "hành động (thường tiêu cực) | việc làm | trò | tác phẩm",
        "deed (esp. negative) | act | action | one's doing | one's work","1304870"),
    row("仕送り","しおくり","N3","n|vs|vt",
        "trợ cấp (tiền) | tiền chu cấp | tiền gửi về nhà",
        "allowance | remittance | sending (someone) an allowance","1305220"),
    row("見習う","みならう","N3","v5u|vt",
        "noi gương | học theo | bắt chước (điều tốt)",
        "to follow (someone's) example | to imitate | to copy | to pattern after","1259700"),
    row("見捨てる","みすてる","N3","v1|vt",
        "từ bỏ | bỏ mặc | phụ bạc | bỏ rơi",
        "to abandon | to fail | to desert | to forsake","1259660"),
    row("見積もる","みつもる","N3","v5r|vt",
        "ước tính | dự toán | tính sơ bộ",
        "to estimate","1259790"),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
