# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-026.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-026.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("お邪魔します","おじゃまします","N4","exp",
        "xin phép vào | tôi vào nhà nhé",
        "please excuse the intrusion | I'm coming in",
        "1002050",
        "お邪魔します。","おじゃまします。","Tôi vào nhà nhé.","Please excuse the intrusion."),
    row("インフラ","インフラ","N4","n",
        "cơ sở hạ tầng",
        "infrastructure",
        "1024370",
        "インフラを整備します。","インフラをせいびします。","Tôi hoàn thiện cơ sở hạ tầng.","I develop the infrastructure."),
    row("改修","かいしゅう","N4","n|vs|vt",
        "sửa chữa | cải tạo | cải tiến",
        "repair | improvement",
        "1200880",
        "建物を改修します。","たてものをかいしゅうします。","Tôi cải tạo tòa nhà.","I repair the building."),
    row("建築","けんちく","N4","n|vs|vt",
        "xây dựng | kiến trúc",
        "construction | architecture (of buildings)",
        "1257500",
        "建築を学びます。","けんちくをまなびます。","Tôi học kiến trúc.","I study architecture."),
    row("高まる","たかまる","N4","v5r|vi",
        "dâng cao | tăng lên | được thăng tiến",
        "to rise | to swell | to be promoted",
        "1283220",
        "期待が高まります。","きたいがたかまります。","Kỳ vọng dâng cao.","Expectations rise."),
    row("高める","たかめる","N4","v1|vt",
        "nâng cao | tăng cường | thúc đẩy",
        "to raise | to lift | to boost | to enhance",
        "1283240",
        "スキルを高めます。","スキルをたかめます。","Tôi nâng cao kỹ năng.","I enhance my skills."),
    row("真面目","しんめんもく","N4","n|adj-na",
        "bản chất thật | con người thật | nghiêm túc | thành thật",
        "one's true character | one's true self | one's true worth | serious | earnest",
        "1364350",
        "真面目に取り組みます。","しんめんもくにとりくみます。","Tôi nghiêm túc giải quyết.","I tackle it earnestly."),
    row("神経質","しんけいしつ","N4","adj-na|n",
        "hay lo lắng | căng thẳng | nhạy cảm | khó tính",
        "nervous | highly strung | sensitive | fussy | worried about petty things",
        "1364600",
        "神経質な人です。","しんけいしつなひとです。","Đó là người hay lo lắng.","They are a nervous person."),
    row("生物学","せいぶつがく","N4","n",
        "sinh vật học | sinh học",
        "biology",
        "1379450",
        "生物学を専攻します。","せいぶつがくをせんこうします。","Tôi chuyên ngành sinh học.","I major in biology."),
    row("説明書","せつめいしょ","N4","n",
        "hướng dẫn (in) | sách hướng dẫn | tờ giải thích",
        "(printed) instructions | manual | explanatory leaflet (pamphlet, note) | description",
        "1386470",
        "説明書を読みます。","せつめいしょをよみます。","Tôi đọc hướng dẫn.","I read the instructions."),
    row("比率","ひりつ","N4","n",
        "tỉ lệ | tỷ số | phần trăm",
        "ratio | proportion | percentage",
        "1483680",
        "比率を計算します。","ひりつをけいさんします。","Tôi tính tỉ lệ.","I calculate the ratio."),
    row("揺らぐ","ゆらぐ","N4","v5g|vi",
        "dao động | lung lay | rung chuyển | không vững",
        "to swing | to sway | to shake | to tremble | to waver | to feel shaken | to become unstable",
        "1545630",
        "気持ちが揺らぎます。","きもちがゆらぎます。","Tâm trạng tôi dao động.","My feelings waver."),
    row("理論","りろん","N4","n",
        "lý thuyết",
        "theory",
        "1550160",
        "理論を学びます。","りろんをまなびます。","Tôi học lý thuyết.","I study the theory."),
    row("輪郭","りんかく","N4","n",
        "đường viền | hình bóng | phác thảo | nét đặc trưng",
        "contour | outline | silhouette | summary | outline | sketch | looks | features",
        "1555740",
        "輪郭を描きます。","りんかくをえがきます。","Tôi vẽ đường viền.","I draw the outline."),
    row("下半期","しもはんき","N4","n",
        "nửa sau của năm | nửa cuối năm tài chính",
        "second half of the year | second half of the fiscal year",
        "1576980",
        "下半期の計画を立てます。","しもはんきのけいかくをたてます。","Tôi lập kế hoạch nửa cuối năm.","I make plans for the second half of the year."),
    row("苛立ち","いらだち","N4","n",
        "sự bực bội | khó chịu | tức giận",
        "irritation | annoyance | frustration",
        "1975500",
        "苛立ちを感じます。","いらだちをかんじます。","Tôi cảm thấy bực bội.","I feel irritated."),
    row("何割","なんわり","N4","n",
        "bao nhiêu phần | bao nhiêu phần trăm",
        "what proportion | what percentage",
        "2838977",
        "何割が賛成しますか。","なんわりがさんせいしますか。","Bao nhiêu phần trăm đồng ý?","What percentage agrees?"),
    row("復習","ふくしゅう","N4","n|vs|vt",
        "ôn tập | ôn lại bài",
        "review (of learned material) | revision",
        "1500800",
        "授業の復習をします。","じゅぎょうのふくしゅうをします。","Tôi ôn tập bài học.","I review the lesson."),
    row("お世話になる","おせわになる","N4","exp|v5r",
        "được giúp đỡ | được chăm sóc | mang ơn | cảm ơn sự giúp đỡ",
        "to receive favor | to receive assistance | to receive help | to be looked after | to be taken care of | to become dependent (on) | to become much obliged (to someone) | to become indebted",
        "1002260",
        "お世話になっております。","おせわになっております。","Cảm ơn sự giúp đỡ của bạn.","I am grateful for your help."),
    row("印象","いんしょう","N4","n",
        "ấn tượng",
        "impression",
        "1168390",
        "良い印象を与えます。","よいいんしょうをあたえます。","Tôi tạo ấn tượng tốt.","I make a good impression."),
    row("仮定","かてい","N4","n|vs|vt",
        "giả định | giả thuyết | giả sử",
        "assumption | supposition | hypothesis | supposition",
        "1187870",
        "仮定の話をします。","かていのはなしをします。","Tôi nói chuyện giả định.","I talk hypothetically."),
    row("解体","かいたい","N4","n|vs|vt|vi",
        "phá dỡ | tháo rời | giải thể (tổ chức) | mổ xẻ",
        "demolition | taking down | dismantling | disassembly | taking apart | dissolution (of an organization, company, etc.) | breaking up | dissection (of a body) | dismemberment",
        "1199120",
        "建物を解体します。","たてものをかいたいします。","Tôi phá dỡ tòa nhà.","I demolish the building."),
    row("外観","がいかん","N4","n",
        "ngoại quan | diện mạo | bề ngoài",
        "outward appearance | exterior appearance | outward show | looks",
        "1203460",
        "外観が良いです。","がいかんがよいです。","Diện mạo bên ngoài đẹp.","The exterior looks good."),
    row("概念","がいねん","N4","n",
        "khái niệm | ý niệm | quan niệm",
        "general idea | concept | notion",
        "1204480",
        "概念を理解します。","がいねんをりかいします。","Tôi hiểu khái niệm.","I understand the concept."),
    row("乾燥","かんそう","N4","n|vs|vt|vi|adj-na",
        "khô ráo | khô hạn | sấy khô | khô khan (nhạt nhẽo)",
        "dryness | aridity | drying (e.g. clothes) | dehydration | desiccation | insipidity",
        "1209920",
        "洗濯物を乾燥させます。","せんたくものをかんそうさせます。","Tôi sấy quần áo.","I dry the laundry."),
    row("感激","かんげき","N4","n|vs|vi",
        "xúc động sâu sắc | cảm kích | cảm hứng",
        "deep emotion | impression | inspiration",
        "1212360",
        "感激して涙が出ます。","かんげきしてなみだがでます。","Tôi xúc động đến rơi nước mắt.","I am so moved that tears come out."),
    row("形状","けいじょう","N4","n",
        "hình dạng | hình thức",
        "shape | form",
        "1250340",
        "形状を確認します。","けいじょうをかくにんします。","Tôi kiểm tra hình dạng.","I check the shape."),
    row("いい加減","いいかげん","N4","adj-na|adv",
        "vô trách nhiệm | cẩu thả | qua loa | nửa vời | mơ hồ | đủ rồi | khá",
        "irresponsible | perfunctory | careless | lukewarm | half-baked | halfhearted | vague | (already) enough | considerably | quite | rather | pretty",
        "1277440",
        "いい加減にしてください。","いいかげんにしてください。","Xin dừng lại đi.","Please stop it already."),
    row("工事","こうじ","N4","n|vs|vt|vi",
        "công trình xây dựng | thi công",
        "construction work",
        "1278130",
        "道路工事があります。","どうろこうじがあります。","Có công trình đường bộ.","There is road construction."),
    row("構造","こうぞう","N4","n",
        "cấu trúc | cấu tạo | khung | tổ chức",
        "structure | construction | makeup | framework | organization | pattern",
        "1279790",
        "建物の構造を調べます。","たてもののこうぞうをしらべます。","Tôi nghiên cứu cấu trúc tòa nhà.","I examine the building structure."),
    row("豪雨","ごうう","N4","n",
        "mưa lớn | mưa xối xả | trận mưa",
        "torrential rain | heavy rain | cloudburst | downpour",
        "1285490",
        "豪雨で川が増水します。","ごううでかわがぞうすいします。","Mưa lớn làm sông dâng nước.","The river rises due to heavy rain."),
    row("刻む","きざむ","N4","v5m|vt",
        "băm nhỏ | thái nhỏ | khắc | chạm | đếm (thời gian) | gõ nhịp | khắc sâu (vào tâm trí)",
        "to mince | to cut fine | to chop up | to hash | to shred | to carve | to engrave | to chisel | to notch | to tick away (time) | to beat out (e.g. rhythm) | to record the passing moments | to etch (into one's mind) | to remember distinctly | to have tattooed | to torment",
        "1285890",
        "野菜を刻みます。","やさいをきざみます。","Tôi băm nhỏ rau.","I mince the vegetables."),
    row("根拠","こんきょ","N4","n",
        "cơ sở | căn cứ | nền tảng | căn cứ điểm",
        "basis | grounds | foundation | reason | authority | base (of operations) | base (of a group of stones)",
        "1290120",
        "根拠を示します。","こんきょをしめします。","Tôi đưa ra cơ sở.","I show the grounds."),
    row("署名","しょめい","N4","n|vs|vi",
        "chữ ký | ký tên",
        "signature | autograph",
        "1343640",
        "書類に署名します。","しょるいにしょめいします。","Tôi ký tên vào tài liệu.","I sign the document."),
    row("書き込む","かきこむ","N4","v5m|vt",
        "điền vào | viết vào | đăng bài | ghi dữ liệu",
        "to fill in (field, entry, etc.) | to fill out (form) | to post a message (e.g. on a bulletin-board) | to store | to write (data) | to flash",
        "1343730",
        "フォームに書き込みます。","フォームにかきこみます。","Tôi điền vào biểu mẫu.","I fill in the form."),
    row("小計","しょうけい","N4","n|vs|vt",
        "tiểu kế | tổng số con",
        "subtotal",
        "1348010",
        "小計は千円です。","しょうけいはせんえんです。","Tiểu kế là 1.000 yên.","The subtotal is 1,000 yen."),
    row("焦り","あせり","N4","n",
        "sự nóng vội | thiếu kiên nhẫn | hấp tấp",
        "impatience",
        "1350770",
        "焦りを感じます。","あせりをかんじます。","Tôi cảm thấy nóng vội.","I feel impatient."),
    row("証拠","しょうこ","N4","n",
        "bằng chứng | chứng cứ",
        "evidence | proof",
        "1351600",
        "証拠を集めます。","しょうこをあつめます。","Tôi thu thập bằng chứng.","I gather evidence."),
    row("吹雪","ふぶき","N4","n",
        "bão tuyết",
        "snow storm | blizzard",
        "1370780",
        "吹雪で外に出られません。","ふぶきでそとにでられません。","Bão tuyết không cho ra ngoài.","I can't go out due to the blizzard."),
    row("設計","せっけい","N4","n|vs|vt",
        "thiết kế | bản vẽ | kế hoạch",
        "plan | design | layout",
        "1386020",
        "家を設計します。","いえをせっけいします。","Tôi thiết kế ngôi nhà.","I design the house."),
    row("設備","せつび","N4","n|vs|vt",
        "thiết bị | cơ sở vật chất | lắp đặt",
        "equipment | facilities | installation | accommodations | conveniences | arrangements",
        "1386070",
        "設備を整えます。","せつびをととのえます。","Tôi trang bị đầy đủ.","I arrange the facilities."),
    row("染まる","そまる","N4","v5r|vi",
        "bị nhuộm | bị nhuốm màu | bị ảnh hưởng (xấu)",
        "to be dyed | to be tainted | to be infected | to be stained | to be steeped",
        "1391100",
        "布が赤く染まります。","ぬのがあかくそまります。","Vải bị nhuộm đỏ.","The cloth is dyed red."),
    row("染める","そめる","N4","v1|vt",
        "nhuộm | nhuộm màu",
        "to dye | to colour | to color",
        "1391160",
        "髪を染めます。","かみをそめます。","Tôi nhuộm tóc.","I dye my hair."),
    row("前向き","まえむき","N4","adj-na|adj-no|n",
        "nhìn về phía trước | tích cực | mang tính xây dựng",
        "front-facing | forward-looking | positive | constructive",
        "1392970",
        "前向きに考えます。","まえむきにかんがえます。","Tôi suy nghĩ tích cực.","I think positively."),
    row("前提","ぜんてい","N4","n",
        "tiền đề | điều kiện tiên quyết | giả định | mục tiêu",
        "condition | assumption | prerequisite | hypothesis | intention | intent | aim | goal | premise",
        "1393680",
        "前提を確認します。","ぜんていをかくにんします。","Tôi xác nhận tiền đề.","I confirm the premise."),
    row("日照り","ひでり","N4","n",
        "nắng hạn | hạn hán | khô hạn",
        "dry weather | drought",
        "1464160",
        "日照りで作物が枯れます。","ひでりでさくもつがかれます。","Hạn hán làm cây trồng chết.","The crops wither due to the drought."),
    row("濡らす","ぬらす","N4","v5s|vt",
        "làm ướt | thấm ướt | ngâm | nhúng",
        "to wet | to moisten | to dampen | to soak | to dip",
        "1467610",
        "手を濡らします。","てをぬらします。","Tôi làm ướt tay.","I wet my hands."),
    row("年度","ねんど","N4","n|n-suf",
        "năm tài chính | năm học | năm tài khóa",
        "fiscal year (usu. April 1 to March 31 in Japan) | financial year | academic year | school year | product year",
        "1469050",
        "今年度の目標を立てます。","こんねんどのもくひょうをたてます。","Tôi đặt mục tiêu năm tài chính này.","I set goals for this fiscal year."),
    row("無口","むくち","N4","adj-na|adj-no|n",
        "ít nói | im lặng | lầm lì | trầm tính",
        "taciturn | reticent | quiet | silent | untalkative",
        "1529940",
        "無口な人です。","むくちなひとです。","Đó là người ít nói.","They are a quiet person."),
    row("梅雨","つゆ","N4","n",
        "mùa mưa (Đông Á) | mùa mưa tháng 6-7 ở Nhật",
        "(East Asian) rainy season (in Japan, usu. from early June to mid-July) | rain during the rainy season",
        "1582960",
        "梅雨の時期は蒸し暑いです。","つゆのじきはむしあついです。","Mùa mưa thì oi bức.","The rainy season is hot and humid."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
