# -*- coding: utf-8 -*-
"""Build N2 ready wave 031 — plants, animal anatomy, biology, minerals/metals."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-031.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("樹皮","じゅひ","n","vỏ cây","bark (of a tree)","1330380"),
    ("樹液","じゅえき","n","nhựa cây | mủ cây","sap","1692520"),
    ("樹齢","じゅれい","n","tuổi cây | tuổi thọ của cây","age of a tree","1330420"),
    ("年輪","ねんりん","n","vòng tuổi cây | vân gỗ | từng trải","annual tree ring | experience in life","1469260"),
    ("梢","こずえ","n","ngọn cây | đầu cành","treetop | tip of a branch","1349980"),
    ("双葉","ふたば","n","lá mầm | mầm non | giai đoạn đầu | thuở ban đầu","seed leaves | bud | early stages","1602730"),
    ("常緑","じょうりょく","n|adj-no","thường xanh | xanh quanh năm","evergreen","1356180"),
    ("針葉樹","しんようじゅ","n","cây lá kim","conifer | needle-leaved tree","1768840"),
    ("広葉樹","こうようじゅ","n","cây lá rộng","broadleaf tree","1631270"),
    ("雑木","ぞうき","n","cây tạp | cây bụi linh tinh","various kinds of small trees | assorted trees","1299560"),
    ("苗木","なえぎ","n","cây giống | cây non | cây con","seedling | sapling | young tree","1490500"),
    ("花粉","かふん","n","phấn hoa","pollen","1194890"),
    ("球根","きゅうこん","n|adj-no","củ (cây) | thân hành","(plant) bulb","1229950"),
    ("塊茎","かいけい","n","củ | thân củ","tuber","1668390"),
    ("根菜","こんさい","n","rau củ | củ ăn được","root vegetable","1877590"),
    ("蔓","つる","n","dây leo | tua cuốn | gọng kính | quan hệ | chỗ dựa","vine | tendril | temple arm (glasses) | connections","2153670"),
    ("苔","こけ","n","rêu | rong rêu","moss","1411030"),
    ("菌","きん","n","nấm | vi khuẩn | mầm bệnh","fungus | germ | bacterium","1956120"),
    ("藻","も","n|adj-no","tảo | rong | rong rêu | bèo","algae | waterweed | seaweed","1402240"),
    ("海藻","かいそう","n","rong biển | tảo biển","seaweed","1201590"),
    ("野草","やそう","n","cỏ dại | cây dại | hoa dại","wild grasses | wildflowers","1537550"),
    ("薬草","やくそう","n","dược thảo | cây thuốc","medicinal herb","1538260"),
    ("香草","こうそう","n","rau thơm | thảo mộc thơm","herb | fragrant grass","1283080"),
    ("山菜","さんさい","n","rau rừng | rau dại ăn được","edible wild plants","1302860"),
    ("木の実","きのみ","n","quả cây | hạt | quả mọng","fruit of a tree | nut | berry","1534550"),
    ("果肉","かにく","n","thịt quả | cùi quả","flesh (of a fruit) | pulp","1193040"),
    ("種","たね","n","hạt giống | hạt | nguồn cơn | nguyên liệu (bài) | mánh khóe","seed | cause | material | trickery","1328820"),
    ("殻","から","n","vỏ | mai | vỏ trấu | vỏ bọc","shell | husk | hull | pod","1205740"),
    ("皮","かわ","n","da | lông thú | vỏ | vỏ bọc | lớp ngụy trang","skin | hide | peel | bark | mask","1483800"),
    ("鱗","うろこ","n","vảy (cá, rắn) | chân chữ (kiểu chữ)","scale (of fish, snake) | serif","1555890"),
    ("羽","はね","n","lông vũ | cánh | cánh quạt | cầu lông","feather | wing | blade | shuttlecock","1171680"),
    ("羽毛","うもう","n","lông vũ | lông tơ | lông chim","feather | plume | plumage | down","1171810"),
    ("甲羅","こうら","n","mai (cua, rùa) | mai cứng | lưng | thâm niên","shell (of a crab, tortoise) | carapace | years of experience","1280310"),
    ("触角","しょっかく","n","râu (côn trùng) | ăng-ten | xúc tu","feeler | antenna","1652940"),
    ("牙","きば","n","nanh | răng nanh | ngà","tusk | fang","1197030"),
    ("角","つの","n","sừng | gạc | ăng-ten | xúc tu | chóp nhọn","horn | antler | tentacle","1206120"),
    ("蹄","ひづめ","n","móng guốc","hoof","1436750"),
    ("尾","お","n","đuôi | phần đuôi | đuôi sao chổi | chân núi","tail | tail end | slope at foot of mountain","1485770"),
    ("翼","つばさ","n|suf|ctr","cánh | đôi cánh","wing","1547530"),
    ("鰭","ひれ","n","vây (cá)","fin (of a fish)","1490520"),
    ("鰓","えら","n","mang (cá) | góc hàm","gills | branchia","1574920"),
    ("肉食","にくしょく","n|vs|vi|adj-no|adj-f","ăn thịt | ăn mặn | loài ăn thịt","meat eating | carnivorous","1463630"),
    ("草食","そうしょく","adj-no|n|vs|vi","ăn cỏ | loài ăn cỏ | ăn thực vật","herbivorous | plant-eating","1610100"),
    ("雑食","ざっしょく","adj-no|n|vs|vt|vi","ăn tạp | loài ăn tạp","omnivorous","1813770"),
    ("猛獣","もうじゅう","n","thú dữ | mãnh thú | dã thú","fierce animal | beast of prey","1534040"),
    ("害獣","がいじゅう","n","thú gây hại | con vật phá hoại","harmful animal | pest | vermin","1977940"),
    ("家禽","かきん","n","gia cầm","(domestic) fowl | poultry","1191850"),
    ("幼虫","ようちゅう","n|adj-no","ấu trùng | sâu non | giòi","larva | grub | maggot","1545270"),
    ("成虫","せいちゅう","n","côn trùng trưởng thành | sâu trưởng thành","imago | adult (insect)","1645350"),
    ("脱皮","だっぴ","n|vs|vi","lột xác | thay da | thoát ra | đột phá","ecdysis | molting | breaking with convention","1416600"),
    ("変態","へんたい","n|vs|vi|adj-no","biến thái | dị thường | lệch lạc tình dục | biến hình","metamorphosis | abnormality | sexual perversion","1511350"),
    ("産卵","さんらん","n|vs|vt|vi","đẻ trứng | sinh sản trứng","egg-laying | spawning","1303890"),
    ("孵化","ふか","n|vs|vt|vi","ấp trứng | nở (trứng)","incubation | hatching","1566240"),
    ("鉱石","こうせき","n","quặng | khoáng vật | tinh thể","ore | mineral | crystal","1282620"),
    ("原石","げんせき","n","quặng thô | đá quý thô | nguyên thạch","(raw) ore | unpolished gemstone","1666160"),
    ("水晶","すいしょう","n","pha lê | thạch anh | tinh thể","(rock) crystal | quartz","1371630"),
    ("真珠","しんじゅ","n","ngọc trai","pearl","1363810"),
    ("琥珀","こはく","n|adj-no","hổ phách","amber","1569410"),
    ("原油","げんゆ","n","dầu thô","crude oil","1262430"),
    ("鉄鉱石","てっこうせき","n","quặng sắt","iron ore","1437870"),
    ("銅","どう","n","đồng (Cu) | huy chương đồng","copper (Cu) | bronze (medal)","1582390"),
    ("鉛","なまり","n","chì (Pb)","lead (Pb)","1178500"),
    ("亜鉛","あえん","n","kẽm (Zn)","zinc (Zn)","1149590"),
    ("錫","すず","n","thiếc (Sn)","tin (Sn)","1324280"),
    ("合金","ごうきん","n","hợp kim","alloy","1284730"),
    ("鋼","はがね","n","thép | thép rèn kiếm","steel | sword steel","1282680"),
    ("鋼鉄","こうてつ","n","thép","steel","1282740"),
    ("鋳鉄","ちゅうてつ","n","gang | sắt đúc","cast iron","1426870"),
    ("真鍮","しんちゅう","n","đồng thau","brass","1364430"),
    ("青銅","せいどう","n","đồng thiếc | đồng đỏ | đồng (bronze)","bronze","1381710"),
    ("水銀","すいぎん","n","thủy ngân (Hg)","mercury (Hg)","1371430"),
    ("硫黄","いおう","n","lưu huỳnh (S)","sulfur (S)","1552840"),
    ("石灰","せっかい","n|adj-no","vôi | vôi sống","lime | quicklime","1382530"),
    ("粘土","ねんど","n","đất sét","clay","1469760"),
    ("陶土","とうど","n","đất sét làm gốm | cao lanh","potter's clay | kaolin","1717190"),
    ("砂利","じゃり","n|adj-no","sỏi | đá dăm | sỏi đá","gravel | pebbles","1291660"),
    ("砕石","さいせき","n|vs|vt","đá nghiền | đá dăm | sự nghiền đá","crushed stone | crushing (rock)","1295210"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
