# -*- coding: utf-8 -*-
"""Build N2 ready wave 039 — compound verbs (〜立てる/〜直す/〜過ぎる/〜上げる/〜上がる/〜合う/〜違える)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-039.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("取り立てる","とりたてる","v1|vt","đòi (nợ) | thu (thuế) | đề bạt | nhấn mạnh | nêu bật","to collect (debts) | to promote | to emphasize","1326960"),
    ("取り立て","とりたて","n|adj-no","việc đòi nợ | sự đề bạt | tươi mới | mới hái","collection (of a debt) | exceptional promotion | freshly picked","1707460"),
    ("言い立てる","いいたてる","v1|vt","khẳng định | một mực nói | liệt kê | rêu rao","to assert | to enumerate | to spread rumours","1264340"),
    ("まくし立てる","まくしたてる","v1|vt","nói liến thoắng | nói thao thao | nói không ngừng","to talk on and on | to rattle on","1257790"),
    ("責め立てる","せめたてる","v1|vt","chỉ trích gay gắt | trách móc | hối thúc | dồn ép","to criticize harshly | to grill | to press","1383170"),
    ("追い立てる","おいたてる","v1|vt","xua đi | đuổi đi | thúc giục | đuổi khỏi (nhà)","to drive on | to shoo away | to evict","1432400"),
    ("掻き立てる","かきたてる","v1|vt","khơi dậy | khuấy lên | nhen nhóm | kích thích","to stir up | to arouse | to kindle | to stimulate","1399950"),
    ("飾り立てる","かざりたてる","v1|vt","trang trí lòe loẹt | tô vẽ rườm rà | trưng diện","to decorate gaudily | to deck out | to embellish","1357200"),
    ("見立てる","みたてる","v1|vt","chọn | chẩn đoán | đánh giá | ví như | coi như","to choose | to diagnose | to liken (to)","1260150"),
    ("役立てる","やくだてる","v1|vt","tận dụng | dùng vào việc có ích | phát huy","to put to use | to make use of","1657000"),
    ("打ち立てる","うちたてる","v1|vt","thiết lập | gây dựng | xác lập","to establish | to formulate","1849330"),
    ("押し立てる","おしたてる","v1|vt","dựng lên | giương cao | đề cử | đẩy mạnh","to set up | to nominate | to push","1180440"),
    ("盛り立てる","もりたてる","v1|vt","vực dậy (công ty) | nâng đỡ | cổ vũ (tinh thần)","to revive (a company) | to boost (morale)","2852287"),
    ("出直す","でなおす","v5s|vi","làm lại từ đầu | bắt đầu lại | đến lại lần nữa","to make a fresh start | to call again","1339750"),
    ("問い直す","といなおす","v5s","hỏi lại | hỏi lại cho rõ | xác nhận lại","to question again | to repeat a query","1985440"),
    ("聞き直す","ききなおす","v5s|vt","nghe lại | hỏi lại","to listen again | to ask again","1851140"),
    ("仕切り直す","しきりなおす","v5s|vt","chuẩn bị lại từ đầu | làm lại từ đầu | tái khởi động","to start from scratch | to get a fresh start","2868670"),
    ("練り直す","ねりなおす","v5s|vt","nhào lại | chỉnh sửa lại | trau chuốt lại","to rework | to revise | to polish","1849810"),
    ("組み直す","くみなおす","v5s","sắp xếp lại | tổ chức lại | lên lịch lại","to reschedule | to recompose | to reset","2011910"),
    ("見過ごす","みすごす","v5s|vt","bỏ qua | làm ngơ | để lọt | bỏ sót","to let go by | to overlook | to miss","1612560"),
    ("やり過ごす","やりすごす","v5s|vt","để (cái gì) đi qua | làm quá đà","to let (something) go past | to do too much","1612730"),
    ("行き過ぎる","いきすぎる","v1|vi","đi quá | đi quá đà | đi quá xa | làm quá lố","to go too far | to go past | to overdo it","1609150"),
    ("食べ過ぎる","たべすぎる","v1|vt","ăn quá nhiều | ăn quá độ","to overeat","1358300"),
    ("使い果たす","つかいはたす","v5s|vt","dùng cạn | tiêu hết | xài sạch | phung phí hết","to use up | to squander","1305750"),
    ("作り上げる","つくりあげる","v1|vt","làm xong | hoàn thành | tạo ra | dựng chuyện | bịa","to build up | to complete | to fabricate","1297320"),
    ("築き上げる","きずきあげる","v1|vt","gây dựng | xây dựng nên | tạo dựng (sự nghiệp)","to build up | to establish | to create","1422130"),
    ("鍛え上げる","きたえあげる","v1|vt","rèn giũa kỹ | tôi luyện | huấn luyện thành thục","to temper thoroughly | to train well","1419130"),
    ("磨き上げる","みがきあげる","v1|vt","đánh bóng | mài giũa | trau chuốt cho hoàn hảo","to polish up | to shine up","1523920"),
    ("読み上げる","よみあげる","v1|vt","đọc to | đọc thành tiếng | đọc xong","to read out | to read aloud | to finish reading","1456260"),
    ("数え上げる","かぞえあげる","v1|vt","đếm hết | liệt kê | kể ra từng cái","to count up | to enumerate","1372920"),
    ("召し上げる","めしあげる","v1|vt","tịch thu | sung công | triệu tập","to forfeit | to confiscate | to summon","1346380"),
    ("吸い上げる","すいあげる","v1|vt","hút lên | bơm lên | rút (lợi nhuận) | thu nhận (ý kiến)","to suck up | to pump up | to take up (opinions)","1228340"),
    ("巻き上げる","まきあげる","v1|vt","cuốn lên | trục lên | moi (tiền) | cuốn tung (bụi)","to roll up | to hoist | to rip off (money)","1211170"),
    ("締め上げる","しめあげる","v1|vt","siết chặt | bóp nghẹt | gây sức ép | truy ép","to firmly tighten | to crack down on | to put the screws on","1436640"),
    ("縛り上げる","しばりあげる","v1|vt","trói chặt | trói gô lại","to bind up | to tie up","1476030"),
    ("でっち上げる","でっちあげる","v1|vt","bịa đặt | dựng chuyện | ngụy tạo | vu khống","to fabricate | to invent | to trump up","1847240"),
    ("組み上げる","くみあげる","v1|vt","lắp ráp xong | ghép nên | dựng nên","to compose | to put together","1696990"),
    ("編み上げる","あみあげる","v1|vt","đan xong | thắt dây từ dưới lên | biên soạn xong","to finish knitting | to finish compiling","2222920"),
    ("打ち上げる","うちあげる","v1|vt","phóng | bắn lên | đánh bổng | sóng vỗ | khép lại (sự kiện)","to launch | to hit (a ball) high | to finish (an event)","1408700"),
    ("湧き上がる","わきあがる","v5r|vi","sôi lên | trào dâng | dấy lên | nổi lên (cuồng nhiệt)","to boil up | to arise | to get excited","1501680"),
    ("膨れ上がる","ふくれあがる","v5r|vi","phình to | phồng lên | tăng vọt (ngân sách, dân số)","to swell up | to balloon | to increase significantly","1905800"),
    ("震え上がる","ふるえあがる","v5r|vi","run bần bật | rùng mình | run lẩy bẩy","to tremble violently | to shudder","1366320"),
    ("晴れ上がる","はれあがる","v5r|vi","quang đãng | trời hửng lên","to clear up","1376490"),
    ("干上がる","ひあがる","v5r|vi","khô cạn | cạn kiệt | hết sạch","to dry up | to parch | to ebb away","1601410"),
    ("仕上がる","しあがる","v5r|vi","hoàn thành | xong | làm xong","to be finished | to be completed","1305130"),
    ("浮かび上がる","うかびあがる","v5r|vi","nổi lên | hiện lên | nổi bật | thoát khỏi (bóng tối)","to rise to the surface | to emerge | to stand out","1497350"),
    ("飛び上がる","とびあがる","v5r|vi","nhảy bật lên | bay vọt lên | nhảy vọt (bậc)","to jump up | to fly up | to jump ahead","1429690"),
    ("跳ね上がる","はねあがる","v5r|vi","nhảy lên | bật lên | tăng vọt (giá) | hành động liều","to jump up | to skyrocket | to act rashly","1601010"),
    ("駆け上がる","かけあがる","v5r|vi","chạy lên (dốc, cầu thang) | lao lên","to run up (stairs) | to dash up","1244790"),
    ("這い上がる","はいあがる","v5r|vi","bò lên | leo lên | vực dậy (sau thất bại)","to crawl up | to overcome (a bad situation)","2025500"),
    ("成り上がる","なりあがる","v5r|vi","phất lên | lên đời (đột ngột) | trèo cao","to rise (suddenly) in the world","1375590"),
    ("思い上がる","おもいあがる","v5r|vi","tự cao | ngạo mạn | tưởng bở","to be conceited","1309290"),
    ("のぼせ上がる","のぼせあがる","v5r|vi","mất bình tĩnh | mất trí | mê mẩn đến quên mình","to lose one's head | to go mad with something","2002520"),
    ("語り合う","かたりあう","v5u|vt","trò chuyện | tâm sự với nhau","to talk together","1270960"),
    ("慰め合う","なぐさめあう","v5u|vt","an ủi lẫn nhau | động viên nhau","to comfort one another","2840907"),
    ("信じ合う","しんじあう","v5u|vi","tin tưởng lẫn nhau | tin nhau","to believe in each other | to trust each other","2859466"),
    ("睨み合う","にらみあう","v5u|vi","lườm nhau | kình địch | đối đầu nhau","to glare at each other | to confront each other","1569850"),
    ("向かい合う","むかいあう","v5u|vi","đối diện nhau | quay mặt vào nhau","to face each other","1604760"),
    ("触れ合う","ふれあう","v5u|vi","tiếp xúc | chạm vào nhau | gần gũi giao lưu","to come into contact | to touch (each other)","1358010"),
    ("重なり合う","かさなりあう","v5u|vi","chồng lên nhau | xếp lớp | chất chồng","to lie on top of each other | to overlap","1335790"),
    ("絡み合う","からみあう","v5u|vi","quấn lấy nhau | rối vào nhau | đan xen (lợi ích)","to intertwine | to become entangled","1548500"),
    ("混じり合う","まじりあう","v5u|vi","hòa lẫn vào nhau | trộn lẫn | hòa quyện","to be mixed together | to intermingle","1909480"),
    ("溶け合う","とけあう","v5u|vi","hòa tan vào nhau | tan chảy quyện lại","to melt together","1546080"),
    ("補い合う","おぎないあう","v5u","bù trừ cho nhau | bổ sung lẫn nhau","to complement","2795680"),
    ("ぶつかり合う","ぶつかりあう","v5u|vt","va vào nhau | xung đột | đụng độ","to collide | to clash","2603200"),
    ("分け合う","わけあう","v5u|vt","chia sẻ với nhau | san sẻ","to share","1503020"),
    ("出し合う","だしあう","v5u|vt","cùng góp | góp chung","to contribute jointly","1338020"),
    ("持ち合う","もちあう","v5u|vi","cân bằng nhau | giữ nguyên | cùng gánh (chi phí)","to balance | to remain unchanged | to share","2217100"),
    ("請け合う","うけあう","v5u|vt","đảm nhận | đảm bảo | cam đoan | hứa chắc","to undertake | to guarantee | to vouch (for)","1381290"),
    ("掛け合う","かけあう","v5u|vi|vt","thương lượng | điều đình | té vào nhau | tạt vào nhau","to negotiate (with) | to splash on each other","1207620"),
    ("渡り合う","わたりあう","v5u|vi","giao đấu | đọ sức | tranh luận gay gắt","to fight (with) | to compete | to argue (with)","1444630"),
    ("行き違う","ゆきちがう","v5u|vi","đi lệch nhau | lỡ gặp nhau | hiểu lầm | trục trặc","to pass each other by | to have a misunderstanding","2010930"),
    ("取り違える","とりちがえる","v1|vt","nhầm lẫn | lấy nhầm | hiểu sai","to mistake one thing for another | to misunderstand","1326560"),
    ("履き違える","はきちがえる","v1|vt","đi nhầm giày | hiểu sai | nhận thức lệch lạc","to put on wrong shoes | to have a mistaken idea of","1549760"),
    ("聞き違える","ききちがえる","v1|vt","nghe nhầm","to mishear","1851220"),
    ("見違える","みちがえる","v1|vt","nhìn nhầm | không nhận ra (vì thay đổi)","to mistake (for someone else) | to be unable to recognize","1259300"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
