# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-048.csv -- 23 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-048.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("リス","リス","N4","n",
        "vết nứt gãy | đá thạch bản | chụp ảnh lithograph",
        "fracture | lithograph",
        "1141430",
        "リスの技法。","りすのぎほう。",
        "Kỹ thuật thạch bản.","Lithograph technique."),
    row("茜色","あかねいろ","N4","n",
        "màu đỏ thẫm | màu đỏ son | đỏ madder",
        "madder red | dark red | crimson",
        "1151220",
        "茜色の空。","あかねいろのそら。",
        "Bầu trời màu đỏ thẫm.","A crimson sky."),
    row("蚊","か","N4","n",
        "con muỗi | muỗi",
        "mosquito",
        "1196540",
        "蚊に刺される。","かにさされる。",
        "Bị muỗi đốt.","Get bitten by a mosquito."),
    row("菊","きく","N4","n",
        "hoa cúc | cúc vạn thọ",
        "chrysanthemum (Chrysanthemum morifolium)",
        "1226210",
        "菊の花が咲く。","きくのはながさく。",
        "Hoa cúc nở.","Chrysanthemums bloom."),
    row("銀色","ぎんいろ","N4","n",
        "màu bạc | màu trắng ánh bạc",
        "silver (color, colour)",
        "1243560",
        "銀色の月。","ぎんいろのつき。",
        "Mặt trăng màu bạc.","A silver moon."),
    row("空き地","あきち","N4","n",
        "đất trống | khu đất bỏ hoang | lô đất trống",
        "vacant land | unoccupied ground | empty lot",
        "1245340",
        "空き地で遊ぶ。","あきちであそぶ。",
        "Chơi ở khu đất trống.","Play on an empty lot."),
    row("栗","くり","N4","n",
        "hạt dẻ | cây dẻ Nhật Bản",
        "Japanese chestnut (Castanea crenata) | chestnut",
        "1246880",
        "栗ご飯を作る。","くりごはんをつくる。",
        "Nấu cơm hạt dẻ.","Make chestnut rice."),
    row("松茸","まつたけ","N4","n",
        "nấm matsutake | nấm thông Nhật | nấm quý hiếm",
        "matsutake mushroom (Tricholoma matsutake)",
        "1349910",
        "松茸は高価だ。","まつたけはこうかだ。",
        "Nấm matsutake rất đắt.","Matsutake mushrooms are expensive."),
    row("地層","ちそう","N4","n",
        "địa tầng | lớp đất đá | tầng địa chất",
        "stratum | geological formation | layer | bed (coal, gravel, etc.)",
        "1421320",
        "地層を調べる。","ちそうをしらべる。",
        "Khảo sát địa tầng.","Examine geological strata."),
    row("地平線","ちへいせん","N4","n",
        "đường chân trời (trên đất liền) | chân trời",
        "horizon (related to land)",
        "1421440",
        "地平線の彼方。","ちへいせんのかなた。",
        "Phía bên kia đường chân trời.","Beyond the horizon."),
    row("蝶","ちょう","N4","n",
        "con bướm | bướm",
        "butterfly",
        "1429010",
        "蝶が花に止まる。","ちょうがはなにとまる。",
        "Bướm đậu lên hoa.","A butterfly lands on a flower."),
    row("椎茸","しいたけ","N4","n",
        "nấm đông cô | nấm shiitake",
        "shiitake mushroom (Lentinula edodes)",
        "1432250",
        "椎茸を炒める。","しいたけをいためる。",
        "Xào nấm shiitake.","Stir-fry shiitake mushrooms."),
    row("藍色","あいいろ","N4","n",
        "màu chàm | màu xanh chàm | màu indigo",
        "indigo blue | indigo",
        "1549410",
        "藍色の着物。","あいいろのきもの。",
        "Kimono màu chàm.","An indigo-dyed kimono."),
    row("鈴虫","すずむし","N4","n",
        "dế chuông | dế kêu như chuông | dế mùa thu",
        "bell cricket (Meloimorpha japonica) | pine cricket",
        "1557590",
        "鈴虫が鳴く。","すずむしがなく。",
        "Dế chuông kêu.","Bell crickets chirp."),
    row("蓮","はす","N4","n",
        "hoa sen | sen | sen Ấn Độ",
        "sacred lotus (Nelumbo nucifera) | Indian lotus | lotus",
        "1559200",
        "蓮の花が咲く。","はすのはながさく。",
        "Hoa sen nở.","Lotus flowers bloom."),
    row("金色","きんいろ","N4","n",
        "màu vàng kim | màu vàng óng",
        "gold (colour, color)",
        "1578120",
        "金色に輝く。","きんいろにかがやく。",
        "Sáng lên màu vàng kim.","Shine in golden color."),
    row("杉","すぎ","N4","n",
        "cây tuyết tùng Nhật | cây sugi",
        "Japanese cedar (Cryptomeria japonica) | sugi",
        "1373520",
        "杉の木が高い。","すぎのきがたかい。",
        "Cây tuyết tùng Nhật cao vút.","Japanese cedar trees are tall."),
    row("柿","かき","N4","n",
        "quả hồng | hồng (quả) | quả hồng Nhật",
        "kaki | Japanese persimmon (Diospyros kaki)",
        "1204810",
        "柿を食べる。","かきをたべる。",
        "Ăn quả hồng.","Eat a persimmon."),
    row("蛍","ほたる","N4","n",
        "con đom đóm | đom đóm | đốm sáng",
        "firefly | lightning bug | glowworm",
        "1252000",
        "蛍が光る。","ほたるがひかる。",
        "Đom đóm phát sáng.","Fireflies glow."),
    row("蜂","はち","N4","n",
        "con ong | ong | ong bắp cày",
        "bee | wasp | hornet",
        "1517840",
        "蜂に刺される。","はちにさされる。",
        "Bị ong đốt.","Get stung by a bee."),
    row("地形","ちけい","N4","n",
        "địa hình | đặc điểm địa lý | địa mạo",
        "terrain | geographical features | topography",
        "1421030",
        "複雑な地形。","ふくざつなちけい。",
        "Địa hình phức tạp.","Complex terrain."),
    row("水平線","すいへいせん","N4","n",
        "đường chân trời (trên biển) | chân trời mặt nước",
        "horizon (related to bodies of water) | sea horizon",
        "1372060",
        "水平線に夕日が沈む。","すいへいせんにゆうひがしずむ。",
        "Mặt trời lặn xuống đường chân trời.","The sun sets below the sea horizon."),
    row("空き家","あきや","N4","n",
        "nhà trống | nhà bỏ hoang | nhà không người ở",
        "vacant house | unoccupied house",
        "1675850",
        "空き家が増えている。","あきやがふえている。",
        "Nhà trống ngày càng nhiều.","The number of vacant houses is increasing."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
