# -*- coding: utf-8 -*-
"""Build N2 ready wave 016 — politics, monarchy, diplomacy, military."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-016.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("政権","せいけん","n","chính quyền | quyền lực chính trị","(political) administration | political power","1375930"),
    ("官邸","かんてい","n","dinh thự (chính phủ) | phủ thủ tướng","official residence (e.g. of the prime minister)","1211750"),
    ("元首","げんしゅ","n","nguyên thủ | người đứng đầu nhà nước","sovereign | head of state","1260870"),
    ("閣僚","かくりょう","n","các bộ trưởng nội các","cabinet ministers","1206310"),
    ("議席","ぎせき","n","ghế nghị sĩ | ghế trong quốc hội","parliamentary seat","1226120"),
    ("開票","かいひょう","n|vs|vt|vi","kiểm phiếu | đếm phiếu","counting ballots | tally (of votes)","1202910"),
    ("得票","とくひょう","n|vs|vt|vi","số phiếu giành được | phiếu bầu","number of votes polled","1454610"),
    ("公約","こうやく","n|vs|vt|adj-no","cam kết công khai | lời hứa tranh cử","public commitment | campaign pledge","1274880"),
    ("党首","とうしゅ","n","lãnh đạo đảng | đảng trưởng","party leader","1446000"),
    ("派閥","はばつ","n|adj-no","phe phái | bè phái | phái hệ","clique | faction","1471180"),
    ("保守","ほしゅ","n|vs|vt","bảo thủ | bảo trì | bảo tồn","maintenance | conservatism","1513750"),
    ("急進","きゅうしん","n|vs|vi","cấp tiến | tiến nhanh | quá khích","rapid progress | radical progress","1228780"),
    ("穏健","おんけん","adj-na","ôn hòa | điều độ | chừng mực","moderate | temperate | sensible","1183600"),
    ("過激","かげき","adj-na|n","quá khích | cực đoan | dữ dội | nặng (lời)","extreme | radical | violent","1196060"),
    ("弾劾","だんがい","n|vs|vt","luận tội | đàn hặc | buộc tội","impeachment | denunciation | censure","1419430"),
    ("解散","かいさん","n|vs|vt|vi","giải tán | giải thể | (quốc hội) giải tán","breaking up | dissolution | disbandment","1199000"),
    ("総辞職","そうじしょく","n|vs|vi","từ chức tập thể | toàn bộ từ nhiệm","mass resignation","1401600"),
    ("施政","しせい","n","việc cai trị | điều hành chính sự","government | administration | statesmanship","1310400"),
    ("統治","とうち","n|vs|vt","cai trị | thống trị | quản trị","rule | reign | government","1449790"),
    ("君主","くんしゅ","n","quân chủ | vua | người trị vì","monarch | sovereign | ruler","1247290"),
    ("王朝","おうちょう","n","vương triều | triều đại","dynasty","1181630"),
    ("皇帝","こうてい","n","hoàng đế","emperor","1280490"),
    ("皇室","こうしつ","n","hoàng thất | hoàng gia","Imperial household","1280420"),
    ("即位","そくい","n|vs|vi","lên ngôi | đăng quang | tức vị","accession to the throne | enthronement","1404110"),
    ("退位","たいい","n|vs|vi","thoái vị | nhường ngôi","abdication","1411290"),
    ("譲位","じょうい","n|vs|vi","nhường ngôi | thoái vị truyền ngôi","abdication","1635430"),
    ("摂政","せっしょう","n","nhiếp chính | quan nhiếp chính","regency | regent","1385730"),
    ("朝廷","ちょうてい","n","triều đình","Imperial Court","1428490"),
    ("封建","ほうけん","n|vs|vt|adj-no","phong kiến","feudalism","1499620"),
    ("領主","りょうしゅ","n","lãnh chúa | địa chủ phong kiến","feudal lord","1757870"),
    ("貴族","きぞく","n|adj-no","quý tộc | tầng lớp quý tộc","nobility | aristocracy | peerage","1223550"),
    ("平民","へいみん","n","thường dân | dân thường","commoner | plebeian","1507930"),
    ("奴隷","どれい","n|adj-no","nô lệ | kẻ tôi đòi | chế độ nô lệ","slave | servant | slavery","1445650"),
    ("国交","こっこう","n","quan hệ ngoại giao | bang giao","diplomatic relations","1286380"),
    ("外相","がいしょう","n","bộ trưởng ngoại giao | ngoại trưởng","Foreign Minister","1203940"),
    ("領事","りょうじ","n","lãnh sự","consul","1554730"),
    ("公使","こうし","n","công sứ | nhà ngoại giao dưới hàm đại sứ","envoy | minister (of legation)","1273730"),
    ("領事館","りょうじかん","n","lãnh sự quán","consulate","1554740"),
    ("盟約","めいやく","n|vs|vt","minh ước | hiệp ước | thề ước | liên minh","oath | pledge | pact | alliance","1532670"),
    ("交戦","こうせん","n|vs|vi","giao chiến | chiến tranh | giao tranh","war | battle | hostilities","1272190"),
    ("宣戦","せんせん","n|vs|vi","tuyên chiến | tuyên bố chiến tranh","declaration of war","1389720"),
    ("休戦","きゅうせん","n|vs|vi","ngừng bắn | đình chiến","cease-fire | truce | armistice","1227890"),
    ("停戦","ていせん","n|vs|vi","ngừng bắn | đình chiến","armistice | ceasefire","1434980"),
    ("講和","こうわ","n|vs|vi","giảng hòa | nghị hòa | lập lại hòa bình","reconciliation | making of peace","1875990"),
    ("武装","ぶそう","n|vs|vi","vũ trang | trang bị vũ khí | cầm vũ khí","arms | armament | arming oneself","1498740"),
    ("軍縮","ぐんしゅく","n","giải trừ quân bị | cắt giảm vũ trang","reduction of armaments | disarmament","1248470"),
    ("兵器","へいき","n","vũ khí | binh khí | quân khí","arms | weapon | ordnance","1506320"),
    ("弾薬","だんやく","n","đạn dược","ammunition | ammo","1419520"),
    ("砲撃","ほうげき","n|vs|vt","pháo kích | nã pháo | bắn phá","bombarding | shelling | bombardment","1517600"),
    ("爆撃","ばくげき","n|vs|vt","ném bom | oanh tạc","bombing (raid)","1475810"),
    ("空襲","くうしゅう","n|vs|vt|adj-no","không kích | đột kích trên không","air-raid","1245650"),
    ("占領","せんりょう","n|vs|vt","chiếm đóng | chiếm cứ | chiếm giữ","occupying | military occupation | capture","1389610"),
    ("征服","せいふく","n|vs|vt","chinh phục | khuất phục | chế ngự","conquest | subjugation | mastery","1375230"),
    ("援軍","えんぐん","n","viện binh | quân tiếp viện","reinforcement","1176650"),
    ("派兵","はへい","n|vs|vi","điều quân | phái binh","dispatch of troops","1625500"),
    ("撤兵","てっぺい","n|vs|vi","rút quân | triệt thoái binh lính","withdrawal of troops","1437760"),
    ("駐留","ちゅうりゅう","n|vs|vi","đồn trú | đóng quân","stationing (e.g. of troops) | garrison","1426980"),
    ("徴兵","ちょうへい","n|vs|vt|vi","trưng binh | nghĩa vụ quân sự | cưỡng bách nhập ngũ","conscription | military draft","1428130"),
    ("動員","どういん","n|vs|vt","động viên | huy động | điều động","mobilization","1451260"),
    ("将校","しょうこう","n","sĩ quan | võ quan","commissioned officer | military officer","1347690"),
    ("司令","しれい","n|vs|vt","tư lệnh | chỉ huy | bộ chỉ huy","command | commander | commandant","1306710"),
    ("指令","しれい","n|vs|vt","mệnh lệnh | chỉ thị | huấn lệnh","order | directive | instructions","1310060"),
    ("部隊","ぶたい","n","đơn vị (quân đội) | binh đoàn | tiểu đội","force | unit | corps | troops","1499430"),
    ("艦隊","かんたい","n","hạm đội","(naval) fleet | armada","1214740"),
    ("戦艦","せんかん","n","thiết giáp hạm | chiến hạm","battleship","1390170"),
    ("軍艦","ぐんかん","n","tàu chiến | chiến hạm","warship | battleship","1247830"),
    ("潜水艦","せんすいかん","n","tàu ngầm","submarine","1391340"),
    ("戦車","せんしゃ","n","xe tăng | chiến xa","tank (military vehicle) | chariot","1390270"),
    ("戦闘","せんとう","n|vs|vi","chiến đấu | giao chiến | trận đánh","battle | fight | combat","1390420"),
    ("作戦","さくせん","n","chiến thuật | chiến dịch | tác chiến","tactics | strategy | military operation","1297800"),
    ("陣営","じんえい","n","phe phái | trại quân | doanh trại","camp (faction) | military camp","1370180"),
    ("要塞","ようさい","n","pháo đài | thành lũy | công sự","fort | stronghold | fortification","1546760"),
    ("基地","きち","n|n-suf","căn cứ | căn cứ (quân sự)","base (military) | enthusiast","1219110"),
    ("前線","ぜんせん","n","tiền tuyến | mặt trận | front (thời tiết)","(weather) front | front line | battlefront","1393510"),
    ("戦線","せんせん","n","chiến tuyến | mặt trận","(war) front","1390340"),
    ("最前線","さいぜんせん","n","tuyến đầu | tiền tuyến | hàng đầu","front line | forefront","1294150"),
    ("銃撃","じゅうげき","n|vs|vt","bắn súng | xả súng","shooting | gunning (down)","1635700"),
    ("狙撃","そげき","n|vs|vt","bắn tỉa | bắn lén","shooting | sniping","1396600"),
    ("迎撃","げいげき","n|vs|vt","đánh chặn | nghênh chiến | phản công","intercept | interception | counter-attack","1253230"),
    ("奇襲","きしゅう","n|vs|vt|adj-no","tập kích bất ngờ | đánh úp","surprise attack","1219360"),
    ("強襲","きょうしゅう","n|vs|vt","cường tập | tấn công mãnh liệt","assault | violent attack","1638680"),
    ("襲撃","しゅうげき","n|vs|vt","tấn công | tập kích | đột kích","(surprise) attack | assault | raid","1333340"),
    ("応戦","おうせん","n|vs|vi","đánh trả | bắn trả | phản công | nhận lời thách","fighting back | returning fire","1179970"),
    ("敗走","はいそう","n|vs|vi","tháo chạy | thua chạy | bại trận bỏ chạy","flight | rout | debacle","1472590"),
    ("全滅","ぜんめつ","n|vs|vt|vi","toàn diệt | xóa sổ | tiêu diệt hoàn toàn","total destruction | annihilation","1396240"),
    ("壊滅","かいめつ","n|vs|vi","tàn phá | hủy diệt | tiêu tan","(complete) destruction | annihilation | devastation","1199930"),
    ("殲滅","せんめつ","n|vs|vt","tiêu diệt | quét sạch | hủy diệt hoàn toàn","annihilation | extermination | wiping out","1568490"),
    ("鎮圧","ちんあつ","n|vs|vt","trấn áp | dẹp loạn | đàn áp (bạo loạn)","suppression | putting down | quelling","1432040"),
    ("制圧","せいあつ","n|vs|vt","khống chế | trấn áp | giành quyền kiểm soát","gaining total control | suppression | mastery","1374640"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
