# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-031.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-031.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("乾燥機","かんそうき","N4","n",
        "máy sấy | máy sấy quần áo",
        "drying machine | dryer | desiccator",
        "1209940",
        "乾燥機で乾かします。","かんそうきでかわかします。","Tôi sấy bằng máy sấy.","I dry with the dryer."),
    row("渓谷","けいこく","N4","n",
        "thung lũng | hẻm núi | khe núi | hẻm vực",
        "valley (with a river running through it) | gorge | ravine | canyon",
        "1250950",
        "渓谷を散歩します。","けいこくをさんぽします。","Tôi đi dạo trong thung lũng.","I walk in the valley."),
    row("見解","けんかい","N4","n",
        "quan điểm | ý kiến | cách nhìn nhận",
        "opinion | point of view",
        "1259390",
        "私の見解を述べます。","わたしのけんかいをのべます。","Tôi trình bày quan điểm.","I state my opinion."),
    row("賛成","さんせい","N4","n|vs|vi|adj-no",
        "tán thành | đồng ý | ủng hộ | chấp thuận",
        "approval | agreement | support | favour | favor",
        "1304200",
        "賛成します。","さんせいします。","Tôi tán thành.","I agree."),
    row("生まれ変わる","うまれかわる","N4","v5r|vi",
        "được tái sinh | bắt đầu lại cuộc sống mới",
        "to be born again | to make a fresh start in life",
        "1378710",
        "新しい自分に生まれ変わります。","あたらしいじぶんにうまれかわります。","Tôi tái sinh thành bản thân mới.","I am reborn as a new self."),
    row("走り出す","はしりだす","N4","v5s|vi",
        "bắt đầu chạy | chạy bộ | xuất phát | lao vút đi",
        "to begin to run | to start running | to break into a run | to start moving (e.g. a vehicle) | to take off | to get under way",
        "1402480",
        "急に走り出します。","きゅうにはしりだします。","Bỗng nhiên tôi bắt đầu chạy.","I suddenly start running."),
    row("体温計","たいおんけい","N4","n",
        "nhiệt kế | nhiệt kế y tế",
        "(clinical) thermometer",
        "1409270",
        "体温計で熱を測ります。","たいおんけいでねつをはかります。","Tôi đo nhiệt độ bằng nhiệt kế.","I measure my temperature with a thermometer."),
    row("怠け者","なまけもの","N4","n",
        "người lười biếng | kẻ lười nhác",
        "lazy person | lazy fellow | slothful person",
        "1410670",
        "怠け者にならないでください。","なまけものにならないでください。","Đừng trở thành người lười biếng.","Please don't become a lazy person."),
    row("聴診器","ちょうしんき","N4","n",
        "ống nghe (y tế) | ống nghe tim phổi",
        "stethoscope",
        "1428920",
        "聴診器で心音を聞きます。","ちょうしんきでしんおんをききます。","Tôi nghe tiếng tim bằng ống nghe.","I listen to heartbeats with the stethoscope."),
    row("癖","くせ","N4","n",
        "thói quen (thường xấu) | tính kỳ quặc | tật xấu | nếp nhăn",
        "habit (usu. a bad one) | tendency | peculiarity | idiosyncrasy | mannerism | quirk | crease | wrinkle | curl | kink",
        "1509350",
        "悪い癖を直します。","わるいくせをなおします。","Tôi sửa tật xấu.","I fix my bad habit."),
    row("変わり果てる","かわりはてる","N4","v1|vi",
        "biến đổi hoàn toàn (theo chiều xấu) | thay đổi không nhận ra",
        "to be completely changed (for the worse) | to be transformed",
        "1510750",
        "様子が変わり果てました。","ようすがかわりはてました。","Diện mạo đã biến đổi hoàn toàn.","The appearance has changed completely."),
    row("方言","ほうげん","N4","n",
        "phương ngữ | thổ ngữ | tiếng địa phương",
        "dialect | provincialism",
        "1516980",
        "方言が面白いです。","ほうげんがおもしろいです。","Phương ngữ thú vị.","Dialects are interesting."),
    row("冷凍庫","れいとうこ","N4","n",
        "ngăn đông | tủ đông | ngăn đá",
        "freezer",
        "1557210",
        "冷凍庫に入れます。","れいとうこにいれます。","Tôi bỏ vào ngăn đông.","I put it in the freezer."),
    row("幹","みき","N4","n",
        "thân cây | thân gỗ | nền tảng | trụ cột",
        "tree trunk | bole | backbone | base | foundation",
        "1577640",
        "木の幹が太いです。","きのみきがふといです。","Thân cây to.","The tree trunk is thick."),
    row("ため息","ためいき","N4","n",
        "tiếng thở dài | tiếng thở nặng",
        "sigh",
        "1597190",
        "ため息をつきます。","ためいきをつきます。","Tôi thở dài.","I let out a sigh."),
    row("成り行き","なりゆき","N4","n",
        "diễn biến (sự việc) | kết quả | tiến triển | lệnh thị trường",
        "course (of events) | development | progress | outcome | result | market order | order without limit",
        "1599700",
        "成り行きを見守ります。","なりゆきをみまもります。","Tôi theo dõi diễn biến.","I watch the course of events."),
    row("岬","みさき","N4","n",
        "mũi đất | mũi biển | bán đảo nhỏ",
        "cape (on coast)",
        "1611700",
        "岬の灯台が見えます。","みさきのとうだいがみえます。","Tôi thấy ngọn hải đăng ở mũi đất.","I can see the lighthouse on the cape."),
    row("桃の節句","もものせっく","N4","exp|n",
        "Lễ hội búp bê (3/3) | Lễ hội đào | Hinamatsuri",
        "Doll's Festival (March 3) | Peach Festival",
        "1448300",
        "桃の節句にひな人形を飾ります。","もものせっくにひなにんぎょうをかざります。","Dịp Hinamatsuri tôi trang trí búp bê.","I decorate dolls on the Doll's Festival."),
    row("仏間","ぶつま","N4","n",
        "phòng thờ Phật | phòng bàn thờ | gian thờ",
        "Buddhist family chapel | altar room",
        "1501890",
        "仏間でお参りします。","ぶつまでおまいりします。","Tôi lễ bái ở phòng thờ Phật.","I pray in the altar room."),
    row("容量","ようりょう","N4","n",
        "dung lượng | sức chứa | điện dung",
        "capacity | volume | capacitance",
        "1545450",
        "容量を確認します。","ようりょうをかくにんします。","Tôi kiểm tra dung lượng.","I check the capacity."),
    row("陸上競技","りくじょうきょうぎ","N4","n",
        "điền kinh | thi đấu điền kinh",
        "track and field | athletics",
        "1551060",
        "陸上競技に出場します。","りくじょうきょうぎにしゅつじょうします。","Tôi tham gia thi điền kinh.","I participate in track and field."),
    row("枝","し","N4","ctr",
        "đơn vị đếm vật dài và mảnh (như gươm, cây bút)",
        "counter for long, thin things (i.e. swords)",
        "2080710",
        "刀が一支あります。","かたながいっしあります。","Có một thanh kiếm.","There is one sword."),
    row("幹","から","N4","n",
        "thân | cuống | cán (mũi tên) | tay cầm",
        "trunk | stem | stalk | shaft (of an arrow) | handle",
        "2396230",
        "矢のからを持ちます。","やのからをもちます。","Tôi cầm cán mũi tên.","I hold the shaft of the arrow."),
    row("クールダウン","クールダウン","N4","n",
        "hạ nhiệt | thả lỏng sau tập luyện | cooldown",
        "cool down",
        "1043400",
        "クールダウンをします。","クールダウンをします。","Tôi thả lỏng sau tập.","I do a cool-down."),
    row("ストレッチ","ストレッチ","N4","n",
        "căng cơ | khởi động | vải co giãn | đoạn thẳng",
        "stretch (of a material) | stretch material | stretch (exercise) | stretching | stretch | straight (course) | straightaway",
        "1071500",
        "毎朝ストレッチをします。","まいあさストレッチをします。","Tôi tập căng cơ mỗi sáng.","I do stretching every morning."),
    row("漁村","ぎょそん","N4","n",
        "làng chài | làng ngư dân | làng đánh cá",
        "fishing village",
        "1233060",
        "漁村で育ちました。","ぎょそんでそだちました。","Tôi lớn lên ở làng chài.","I grew up in a fishing village."),
    row("口癖","くちぐせ","N4","n",
        "câu cửa miệng | câu nói quen thuộc | lời cửa miệng",
        "pet saying | favorite phrase | stock phrase | catchphrase | manner of talking",
        "1276890",
        "「大丈夫」が口癖です。","「だいじょうぶ」がくちぐせです。","Câu cửa miệng là 「大丈夫」.","My pet saying is 「大丈夫」."),
    row("賛否","さんぴ","N4","n",
        "ủng hộ và phản đối | tán thành hay không | ý kiến trái chiều",
        "yes and no | for and against",
        "1304220",
        "賛否両論あります。","さんぴりょうろんあります。","Có ý kiến trái chiều.","There are pros and cons."),
    row("湿布","しっぷ","N4","n|vs|vt|vi",
        "miếng dán giảm đau | gạc ướt | đắp thuốc | băng dán vào vết đau",
        "(wet) compress | poultice | fomentation",
        "1320510",
        "足に湿布を貼ります。","あしにしっぷをはります。","Tôi dán miếng dán vào chân.","I apply a compress to my leg."),
    row("主張","しゅちょう","N4","n|vs|vt",
        "chủ trương | lập luận | khẳng định | đề xuất | quan điểm",
        "claim | insistence | assertion | advocacy | emphasis | contention | opinion | tenet",
        "1325910",
        "自分の主張を述べます。","じぶんのしゅちょうをのべます。","Tôi trình bày chủ trương của mình.","I state my own claim."),
    row("生き残る","いきのこる","N4","v5r|vi",
        "sống sót | tồn tại",
        "to survive",
        "1378560",
        "困難を乗り越えて生き残ります。","こんなんをのりこえていきのこります。","Tôi vượt qua khó khăn và sống sót.","I overcome difficulties and survive."),
    row("送料","そうりょう","N4","n",
        "phí vận chuyển | phí bưu phẩm | tiền chuyển hàng",
        "postage | carriage | shipping charge",
        "1402870",
        "送料は無料です。","そうりょうはむりょうです。","Phí vận chuyển miễn phí.","The shipping charge is free."),
    row("滝","たき","N4","n",
        "thác nước | ghềnh thác",
        "waterfall | rapids",
        "1415520",
        "滝を見に行きます。","たきをみにいきます。","Tôi đi xem thác nước.","I go to see the waterfall."),
    row("追い越す","おいこす","N4","v5s|vt",
        "vượt qua | qua mặt | bỏ xa | vượt trội",
        "to pass (e.g. car) | to overtake | to surpass | to outstrip | to get ahead of | to outdistance",
        "1432280",
        "前の車を追い越します。","まえのくるまをおいこします。","Tôi vượt qua chiếc xe phía trước.","I overtake the car in front."),
    row("点滴","てんてき","N4","n|vs|vt",
        "giọt mưa | truyền dịch (y tế) | IV | giọt nhỏ",
        "raindrops | falling drop of water | intravenous drip | IV | drip-feed",
        "1441720",
        "点滴を打ちます。","てんてきをうちます。","Tôi truyền dịch.","I receive an IV drip."),
    row("田んぼ","たんぼ","N4","n",
        "ruộng lúa | cánh đồng lúa | ruộng nước",
        "rice field | rice paddy | paddy field",
        "1442840",
        "田んぼで働きます。","たんぼではたらきます。","Tôi làm việc trên ruộng lúa.","I work in the rice paddy."),
    row("農村","のうそん","N4","n|adj-no",
        "làng nông nghiệp | nông thôn | khu vực nông thôn",
        "agricultural community | farm village | rural",
        "1470730",
        "農村に移住します。","のうそんにいじゅうします。","Tôi chuyển về nông thôn.","I move to the farm village."),
    row("並行","へいこう","N4","n|vs|vi|adj-no",
        "song song | cùng lúc | tiến hành đồng thời",
        "going side-by-side | going abreast | running concurrently | occurring at the same time | keeping pace with",
        "1508480",
        "並行して作業します。","へいこうしてさぎょうします。","Tôi làm việc song song.","I work concurrently."),
    row("余計","よけい","N4","adj-na|adv",
        "thừa | quá mức | dư thừa | không cần thiết | còn nhiều hơn",
        "extra | more | too much | too many | excessive | superfluous | spare | surplus | unnecessary | needless | uncalled-for | unwanted | uninvited | all the more | even more",
        "1544090",
        "余計なことを言わないでください。","よけいなことをいわないでください。","Đừng nói những điều thừa.","Please don't say unnecessary things."),
    row("容積","ようせき","N4","n",
        "thể tích | dung tích | sức chứa",
        "capacity | volume",
        "1545420",
        "容積を測ります。","ようせきをはかります。","Tôi đo thể tích.","I measure the volume."),
    row("立ち向かう","たちむかう","N4","v5u|vi",
        "đứng lên đối mặt | chống lại | đối đầu",
        "to fight against | to oppose | to face",
        "1551330",
        "困難に立ち向かいます。","こんなんにたちむかいます。","Tôi đối mặt với khó khăn.","I face the difficulties."),
    row("立ち上がる","たちあがる","N4","v5r|vi",
        "đứng dậy | vươn lên | hành động | phục hồi | khởi động (máy tính)",
        "to stand up | to get up | to rise (to one's feet) | to recover | to regain one's energy | to rise | to (stand up and) take action | to rise up (against) | to start (doing) | to start up | to boot up | to be established | to be set up | to be formed | to be created | to rise (of steam, smoke, etc.)",
        "1551370",
        "立ち上がって行動します。","たちあがっておこうします。","Tôi đứng dậy và hành động.","I stand up and take action."),
    row("立ち直る","たちなおる","N4","v5r|vi",
        "phục hồi | đứng dậy | tìm lại thăng bằng | cải thiện (thị trường)",
        "to regain one's footing | to get back on one's feet | to recover | (of the market) to improve",
        "1551440",
        "失敗から立ち直ります。","しっぱいからたちなおります。","Tôi phục hồi từ thất bại.","I recover from failure."),
    row("連続","れんぞく","N4","n|vs|vt|vi|adj-na",
        "liên tục | nối tiếp | chuỗi | loạt",
        "continuation | succession | series | sequence | continuous",
        "1559610",
        "三日連続で雨が降ります。","みっかれんぞくであめがふります。","Mưa liên tục ba ngày.","It rains three days in a row."),
    row("絆創膏","ばんそうこう","N4","n",
        "băng cá nhân | miếng dán vết thương | band-aid",
        "adhesive bandage | sticking plaster | band-aid",
        "1570430",
        "絆創膏を貼ります。","ばんそうこうをはります。","Tôi dán băng cá nhân.","I put on an adhesive bandage."),
    row("牧場","ぼくじょう","N4","n",
        "trang trại chăn nuôi | đồng cỏ | đồng chăn thả",
        "farm (livestock) | stock farm | ranch | station | pasture | meadow | grazing land",
        "1584250",
        "牧場で牛を育てます。","ぼくじょうでうしをそだてます。","Tôi nuôi bò ở trang trại.","I raise cows at the ranch."),
    row("芽吹く","めぶく","N4","v5k|vi",
        "nảy mầm | đâm chồi | ra nụ",
        "to bud",
        "1641200",
        "春になると木が芽吹きます。","はるになるときがめぶきます。","Mùa xuân đến cây đâm chồi.","Trees bud when spring comes."),
    row("血圧計","けつあつけい","N4","n",
        "máy đo huyết áp | huyết áp kế",
        "sphygmomanometer (instrument used to measure blood pressure)",
        "1669820",
        "血圧計で血圧を測ります。","けつあつけいでけつあつをはかります。","Tôi đo huyết áp bằng máy đo huyết áp.","I measure blood pressure with a sphygmomanometer."),
    row("空気清浄機","くうきせいじょうき","N4","n",
        "máy lọc không khí",
        "air purifier",
        "1675600",
        "空気清浄機を使います。","くうきせいじょうきをつかいます。","Tôi dùng máy lọc không khí.","I use an air purifier."),
    row("山村","さんそん","N4","n",
        "làng miền núi | thôn núi | bản làng",
        "mountain village",
        "1755230",
        "山村に住んでいます。","さんそんにすんでいます。","Tôi sống ở làng miền núi.","I live in a mountain village."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
