# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-030.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-030.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("枯らす","からす","N4","v5s|vt",
        "làm khô | giết chết (thực vật) | hong khô (gỗ)",
        "to let dry | to kill (vegetation) | to season (lumber)",
        "1267210",
        "草花を枯らします。","くさばなをからします。","Tôi làm khô hoa cỏ.","I let the flowers dry."),
    row("散る","ちる","N4","v5r|vi",
        "rụng (hoa, lá) | tan tán | phân tán | biến mất | ngã xuống vì danh dự",
        "to fall (e.g. blossoms, leaves) | to scatter | to be dispersed | to disappear | to dissolve | to break up | to spread | to run | to blur | to die a noble death",
        "1303490",
        "花びらが散ります。","はなびらがちります。","Cánh hoa rụng.","The petals fall."),
    row("指定席","していせき","N4","n",
        "ghế đặt trước | ghế chỉ định",
        "reserved seat",
        "1309930",
        "指定席を予約します。","していせきをよやくします。","Tôi đặt ghế chỉ định.","I reserve a reserved seat."),
    row("実る","みのる","N4","v5r|vi",
        "ra quả | chín | cho kết quả | đơm hoa kết trái",
        "to bear fruit | to ripen | to produce (good) results | to show results | to bear fruit",
        "1320850",
        "努力が実ります。","どりょくがみのります。","Nỗ lực đơm hoa kết trái.","Effort bears fruit."),
    row("手本","てほん","N4","n",
        "mẫu | ví dụ tốt | khuôn mẫu | mẫu viết tay",
        "model | (good) example | exemplar | paragon | model handwriting | model drawing | copybook",
        "1328390",
        "手本を見て書きます。","てほんをみてかきます。","Tôi viết theo mẫu.","I write while looking at the model."),
    row("申し訳","もうしわけ","N4","n|vs",
        "lời xin lỗi | lý do | biện hộ",
        "apology | excuse",
        "1363050",
        "申し訳ありません。","もうしわけありません。","Tôi xin lỗi.","I am terribly sorry."),
    row("段階","だんかい","N4","n",
        "giai đoạn | bước | pha | cấp độ | thứ tự",
        "stage | step | phase | level | rank | grade | gradation | order | stairs",
        "1419950",
        "次の段階に進みます。","つぎのだんかいにすすみます。","Tôi tiến lên giai đoạn tiếp theo.","I advance to the next stage."),
    row("地下室","ちかしつ","N4","n",
        "tầng hầm | phòng hầm",
        "cellar | basement",
        "1420890",
        "地下室に荷物を置きます。","ちかしつににもつをおきます。","Tôi để hành lý ở tầng hầm.","I put the luggage in the basement."),
    row("逃げ出す","にげだす","N4","v5s|vi",
        "chạy trốn | bỏ chạy | tháo lui | bắt đầu chạy trốn",
        "to run away | to flee | to make off | to take to one's heels | to escape | to start to run away",
        "1450390",
        "危険から逃げ出します。","きけんからにげだします。","Tôi chạy trốn khỏi nguy hiểm.","I flee from the danger."),
    row("品揃え","しなぞろえ","N4","n",
        "danh mục sản phẩm | hàng hóa đa dạng | chủng loại",
        "assortment | product lineup",
        "1490650",
        "品揃えが豊富です。","しなぞろえがほうふです。","Hàng hóa đa dạng.","The assortment is rich."),
    row("洋室","ようしつ","N4","n",
        "phòng kiểu phương Tây",
        "Western-style room",
        "1545970",
        "洋室に住んでいます。","ようしつにすんでいます。","Tôi sống trong phòng kiểu phương Tây.","I live in a Western-style room."),
    row("立方","たちかた","N4","n",
        "tư thế đứng | vũ công (múa Nhật Bản)",
        "way of standing | dancer (in a Japanese dance performance)",
        "1551810",
        "正しい立方を練習します。","ただしいたちかたをれんしゅうします。","Tôi luyện tập tư thế đứng đúng.","I practice the correct stance."),
    row("和室","わしつ","N4","n",
        "phòng kiểu Nhật Bản",
        "Japanese-style room",
        "1562110",
        "和室でくつろぎます。","わしつでくつろぎます。","Tôi thư giãn trong phòng kiểu Nhật.","I relax in the Japanese-style room."),
    row("言い訳","いいわけ","N4","n|vs|vt|vi",
        "lý do | biện hộ | biện minh | bào chữa",
        "excuse | explanation",
        "1587030",
        "言い訳をしないでください。","いいわけをしないでください。","Đừng biện hộ.","Please don't make excuses."),
    row("売れ行き","うれゆき","N4","n",
        "tình hình bán hàng | nhu cầu thị trường",
        "sales | demand",
        "1588590",
        "売れ行きが好調です。","うれゆきがこうちょうです。","Tình hình bán hàng tốt.","Sales are going well."),
    row("泣き出す","なきだす","N4","v5s|vi",
        "bật khóc | oà khóc | bắt đầu khóc",
        "to burst into tears | to burst out crying | to begin to cry | to be moved to tears",
        "1633080",
        "突然泣き出します。","とつぜんなきだします。","Bỗng nhiên bật khóc.","I suddenly burst into tears."),
    row("話し相手","はなしあいて","N4","n",
        "người để nói chuyện | bạn trò chuyện | người cố vấn",
        "person with whom to speak | someone to talk to | companion | advisor | adviser",
        "1782940",
        "話し相手がいません。","はなしあいてがいません。","Không có ai để nói chuyện.","I have no one to talk to."),
    row("芽","め","N4","n",
        "mầm | chồi | nụ | phôi",
        "sprout | shoot | bud | germinal disk (in an egg)",
        "1197710",
        "芽が出ます。","めがでます。","Mầm nảy ra.","The sprout comes out."),
    row("屋根裏","やねうら","N4","n",
        "gác mái | tầng trên cùng | gác xép",
        "attic | loft",
        "1815850",
        "屋根裏に荷物を入れます。","やねうらににもつをいれます。","Tôi để hành lý ở gác mái.","I put luggage in the attic."),
    row("笑い出す","わらいだす","N4","v5s",
        "bật cười | oà cười | phá lên cười",
        "to burst into laughter",
        "1847730",
        "思わず笑い出します。","おもわずわらいだします。","Tôi bất ngờ phá lên cười.","I burst into laughter without thinking."),
    row("根","ね","N4","n",
        "rễ (cây) | chân (răng, tóc) | nguồn gốc | căn nguyên | bản chất thật",
        "root (of a plant) | root (of a tooth, hair, etc.) | center (of a pimple, etc.) | root (of all evil, etc.) | source | origin | cause | basis | one's true nature | (fishing) reef",
        "1290020",
        "木の根が深いです。","きのねがふかいです。","Rễ cây ăn sâu.","The tree roots are deep."),
    row("思いやり","おもいやり","N4","n",
        "sự đồng cảm | lòng trắc ẩn | sự quan tâm | tâm lý thấu hiểu",
        "consideration | thoughtfulness | sympathy | compassion | feeling | kindness | understanding | regard | kindheartedness",
        "1309180",
        "思いやりのある人です。","おもいやりのあるひとです。","Đó là người có lòng trắc ẩn.","They are a compassionate person."),
    row("枝","えだ","N4","n",
        "cành | nhánh cây | cành nhỏ",
        "branch | bough | limb | twig | sprig | spray",
        "1310530",
        "枝を切ります。","えだをきります。","Tôi cắt cành.","I cut the branch."),
    row("手配","てはい","N4","n|vs|vt",
        "sắp xếp | chuẩn bị | lùng bắt (của cảnh sát)",
        "arrangement | preparations | search (by police)",
        "1328260",
        "旅の手配をします。","たびのてはいをします。","Tôi sắp xếp chuyến đi.","I make travel arrangements."),
    row("組み立てる","くみたてる","N4","v1|vt",
        "lắp ráp | ghép lại | xây dựng | tổ hợp | soạn thảo",
        "to assemble | to put together | to set up | to construct | to build | to compose (a story, poem, etc.) | to form (words, sentences, etc.)",
        "1397580",
        "机を組み立てます。","つくえをくみたてます。","Tôi lắp ráp cái bàn.","I assemble the desk."),
    row("倉庫","そうこ","N4","n",
        "nhà kho | kho hàng | kho chứa",
        "storehouse | warehouse | godown",
        "1399120",
        "倉庫に荷物を入れます。","そうこににもつをいれます。","Tôi đưa hàng vào kho.","I put goods in the warehouse."),
    row("品質","ひんしつ","N4","n",
        "chất lượng | chất lượng sản phẩm",
        "quality (of a product or a service)",
        "1490580",
        "品質を管理します。","ひんしつをかんりします。","Tôi quản lý chất lượng.","I manage the quality."),
    row("平方","へいほう","N4","n",
        "bình phương | vuông (đơn vị đo)",
        "square (e.g. metre)",
        "1507850",
        "平方メートルを計算します。","へいほうメートルをけいさんします。","Tôi tính mét vuông.","I calculate square metres."),
    row("立方","りっぽう","N4","n|vs",
        "lập phương | hình khối lập phương",
        "cube",
        "1551820",
        "立方センチを求めます。","りっぽうセンチをもとめます。","Tôi tính xen-ti-mét khối.","I find the cubic centimetre."),
    row("前払い","まえばらい","N4","n|vs|vt",
        "thanh toán trước | trả trước | ứng tiền trước",
        "payment in advance | advance payment | prepayment",
        "1603800",
        "前払いでお願いします。","まえばらいでおねがいします。","Xin vui lòng thanh toán trước.","Please pay in advance."),
    row("根付く","ねづく","N4","v5k|vi",
        "bén rễ | ăn rễ | bám rễ",
        "to take root | to strike",
        "1900530",
        "木が根付きました。","きがねづきました。","Cây đã bén rễ.","The tree has taken root."),
    row("代引き","だいびき","N4","n",
        "thanh toán khi nhận hàng | COD",
        "cash on delivery | COD",
        "2232390",
        "代引きで注文します。","だいびきでちゅうもんします。","Tôi đặt hàng thanh toán khi nhận.","I order with cash on delivery."),
    row("データ収集","データしゅうしゅう","N4","n",
        "thu thập dữ liệu | thu thập thông tin",
        "data collection | data acquisition",
        "2310380",
        "データ収集を行います。","データしゅうしゅうをおこないます。","Tôi thực hiện thu thập dữ liệu.","I carry out data collection."),
    row("ご案内","ごあんない","N4","n|vs",
        "hướng dẫn | dẫn đường | thông báo | lời mời",
        "guidance | leading (the way) | showing around | information | notice | notification | announcement (of one's arrival) | invitation | acquaintance | knowledge",
        "2833392",
        "ご案内します。","ごあんないします。","Tôi xin hướng dẫn.","I will guide you."),
    row("その結果","そのけっか","N4","exp",
        "kết quả là | do đó | vì vậy",
        "as a result",
        "2851217",
        "その結果、成功しました。","そのけっか、せいこうしました。","Kết quả là tôi đã thành công.","As a result, I succeeded."),
    row("ご連絡","ごれんらく","N4","n|vs|vt",
        "liên hệ | thông báo | liên lạc",
        "contacting | getting in touch | communication | call | message",
        "1270820",
        "ご連絡ありがとうございます。","ごれんらくありがとうございます。","Cảm ơn bạn đã liên hệ.","Thank you for contacting us."),
    row("後払い","あとばらい","N4","n|vs|vt",
        "thanh toán sau | trả sau | trả chậm",
        "deferred payment",
        "1270070",
        "後払いが可能です。","あとばらいがかのうです。","Thanh toán sau là khả dụng.","Deferred payment is available."),
    row("ご協力","ごきょうりょく","N4","n|vs|vi",
        "hợp tác | cộng tác | sự giúp đỡ | ủng hộ",
        "cooperation | collaboration | help | support",
        "1270290",
        "ご協力をお願いします。","ごきょうりょくをおねがいします。","Xin vui lòng hợp tác.","Please cooperate with us."),
    row("ウォーミングアップ","ウォーミングアップ","N4","n|vs|vi",
        "khởi động | làm ấm cơ thể | warm-up",
        "warming up | warm-up",
        "1026550",
        "運動前にウォーミングアップします。","うんどうまえにウォーミングアップします。","Tôi khởi động trước khi tập.","I warm up before exercise."),
    row("引用","いんよう","N4","n|vs|vt|adj-no",
        "trích dẫn | trích đoạn | tham chiếu",
        "quotation | citation | reference",
        "1169660",
        "論文を引用します。","ろんぶんをいんようします。","Tôi trích dẫn bài luận.","I cite the paper."),
    row("応接間","おうせつま","N4","n",
        "phòng tiếp khách | phòng khách",
        "reception room | parlor | parlour",
        "1179950",
        "応接間でお待ちください。","おうせつまでおまちください。","Xin vui lòng chờ ở phòng tiếp khách.","Please wait in the reception room."),
    row("交互","こうご","N4","adj-no|n|vs",
        "xen kẽ | luân phiên | lần lượt thay thế",
        "alternate | alternating",
        "1271940",
        "交互に作業します。","こうごにさぎょうします。","Chúng tôi làm việc luân phiên.","We work alternately."),
    row("七五三","しちごさん","N4","n",
        "Shichi-go-san | lễ mừng trẻ em 7, 5 và 3 tuổi (15/11)",
        "shichi-go-san | 7-5-3 day | festival day for children aged 7, 5 and 3 held on or around November 15 | lucky numbers 7, 5 and 3",
        "1319310",
        "七五三のお祝いをします。","しちごさんのおいわいをします。","Tôi mừng lễ Shichi-go-san.","I celebrate shichi-go-san."),
    row("順序","じゅんじょ","N4","n",
        "thứ tự | trình tự | thủ tục",
        "order | sequence | procedure",
        "1342340",
        "順序を守ります。","じゅんじょをまもります。","Tôi giữ thứ tự.","I follow the order."),
    row("順番","じゅんばん","N4","n",
        "thứ tự | lượt | lần lượt",
        "order | turn",
        "1342390",
        "順番を待ちます。","じゅんばんをまちます。","Tôi chờ đến lượt.","I wait for my turn."),
    row("初詣","はつもうで","N4","n",
        "chuyến thăm đền đầu năm mới | viếng thăm đền thờ ngày tết",
        "first shrine visit of the New Year",
        "1342720",
        "初詣に行きます。","はつもうでにいきます。","Tôi đi viếng đền đầu năm.","I go to the first shrine visit of the New Year."),
    row("深呼吸","しんこきゅう","N4","n|vs|vi",
        "hít thở sâu",
        "deep breath",
        "1362720",
        "深呼吸してください。","しんこきゅうしてください。","Hãy hít thở sâu.","Please take a deep breath."),
    row("節分","せつぶん","N4","n",
        "Setsubun | ngày cuối mùa đông (khoảng 3-4/2) | lễ ném đậu",
        "setsubun | last day of winter in the traditional Japanese calendar (usu. February 3 or 4) on which a bean scattering ceremony is held | last day of any season (according to the traditional Japanese calendar)",
        "1386340",
        "節分に豆まきをします。","せつぶんにまめまきをします。","Tôi ném đậu dịp Setsubun.","I do the bean scattering at Setsubun."),
    row("段取り","だんどり","N4","n|vs",
        "kế hoạch | chuẩn bị | sắp xếp chương trình",
        "programme | program | plans | arrangements",
        "1419970",
        "段取りを決めます。","だんどりをきめます。","Tôi quyết định kế hoạch.","I decide on the arrangements."),
    row("余地","よち","N4","n",
        "chỗ trống | dư địa | phạm vi | không gian",
        "place | room | margin | scope",
        "1544380",
        "改善の余地があります。","かいぜんのよちがあります。","Có dư địa cải thiện.","There is room for improvement."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
