# -*- coding: utf-8 -*-
"""Build N2 ready wave 014 — weather, disaster, geography, agriculture, mining."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-014.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("降水","こうすい","n","lượng mưa | giáng thủy","rainfall | precipitation","1282890"),
    ("降雨","こうう","n","mưa | lượng mưa rơi","rainfall | rain","1282810"),
    ("降雪","こうせつ","n|vs|vi","tuyết rơi | lượng tuyết","snowfall | snow","1282910"),
    ("豪雪","ごうせつ","n","tuyết lớn | mưa tuyết dày","tremendous snowfall | heavy snow","1285610"),
    ("暴風","ぼうふう","n","bão | gió bão | gió mạnh","storm | windstorm | gale","1519540"),
    ("暴風雨","ぼうふうう","n","mưa bão | bão tố","rainstorm | storm","1519550"),
    ("強風","きょうふう","n","gió mạnh | gió lớn","strong wind | high wind","1236530"),
    ("突風","とっぷう","n","gió giật | cơn gió mạnh bất ngờ","gust (of wind) | blast","1457160"),
    ("旋風","せんぷう","n","gió lốc | cơn lốc | cơn chấn động (dư luận)","whirlwind | sensation | commotion","1391700"),
    ("高潮","たかしお","n","triều cường (do bão) | nước dâng","storm surge","2657650"),
    ("氾濫","はんらん","n|vs|vi","ngập lụt | tràn ngập | lụt lội | dư thừa","overflowing | flood | inundation | plethora","1481420"),
    ("浸水","しんすい","n|vs|vi","ngập nước | ngấm nước | chìm ngập","inundation | submersion | flood","1362610"),
    ("冠水","かんすい","n|vs|vi","bị ngập (do lũ) | chìm trong nước","being submerged | being inundated | flooding","1210310"),
    ("決壊","けっかい","n|vs|vt|vi","vỡ (đê, đập) | sạt lở | sụp đổ","burst (e.g. dam, levee) | breach | collapse","1254230"),
    ("土砂","どしゃ","n","đất cát | bùn đất","sediment | earth and sand","1624160"),
    ("土砂崩れ","どしゃくずれ","n","sạt lở đất | lở đất","landslide","1445350"),
    ("雪崩","なだれ","n","tuyết lở | lở tuyết","avalanche | snowslide","1386690"),
    ("噴煙","ふんえん","n","khói phun (núi lửa) | khói bốc","(eruption of) smoke","1689560"),
    ("溶岩","ようがん","n","dung nham","lava","1546120"),
    ("余震","よしん","n","dư chấn","aftershock","1544290"),
    ("震源","しんげん","n","tâm chấn | chấn tiêu | nguồn động đất","hypocentre (of an earthquake) | focus","1366350"),
    ("震度","しんど","n","cường độ địa chấn | độ rung động đất","seismic intensity","1366380"),
    ("隆起","りゅうき","n|vs|vi|adj-no","gồ lên | nhô lên | nâng lên (địa chất)","protuberance | bulge | uplift | upheaval","1552930"),
    ("陥没","かんぼつ","n|vs|vi","sụt lún | sụp xuống | lõm xuống","cave-in | collapse | sinking | subsidence","1216140"),
    ("飢饉","ききん","n","nạn đói | mất mùa | khan hiếm trầm trọng","famine | crop failure | chronic shortage","1591080"),
    ("凶作","きょうさく","n|adj-no","mất mùa | thất bát | vụ mùa kém","bad harvest | poor crop","1235440"),
    ("豊作","ほうさく","n","được mùa | trúng mùa | bội thu","abundant harvest | bumper crop","1518150"),
    ("収穫","しゅうかく","n|vs|vt","thu hoạch | mùa màng | thành quả","harvest | crop | gain | result","1330510"),
    ("作物","さくもつ","n","cây trồng | nông sản | hoa màu","crop | crops | farm products","1297950"),
    ("穀物","こくもつ","n|adj-no","ngũ cốc | lương thực","grain | cereal | corn","1287280"),
    ("穀類","こくるい","n|adj-no","các loại ngũ cốc","grains","1287310"),
    ("小麦","こむぎ","n","lúa mì","wheat","1348630"),
    ("稲作","いなさく","n","trồng lúa | vụ lúa","rice cultivation | rice crop","1167870"),
    ("田畑","たはた","n","ruộng vườn | đồng ruộng","fields (of rice and other crops)","1442830"),
    ("畑作","はたさく","n","canh tác trên ruộng cạn | hoa màu","dry field farming | dry field crop","1626340"),
    ("耕作","こうさく","n|vs|vt","canh tác | cày cấy | trồng trọt","cultivation | farming","1280970"),
    ("栽培","さいばい","n|vs|vt","gieo trồng | nuôi trồng | gây giống","cultivation","1294910"),
    ("施肥","せひ","n|vs|vt|vi","bón phân","manuring | fertilization","1310420"),
    ("肥料","ひりょう","n","phân bón","manure | fertilizer | compost","1484310"),
    ("農薬","のうやく","n","thuốc nông nghiệp | thuốc trừ sâu","agricultural chemical | agrochemical","1470780"),
    ("害虫","がいちゅう","n","sâu bọ hại | côn trùng có hại | sâu bệnh","harmful insect | pest | vermin","1204350"),
    ("益虫","えきちゅう","n","côn trùng có ích","useful insect","1175110"),
    ("品種","ひんしゅ","n","giống loài | chủng loại | giống (cây trồng)","breed | variety | cultivar","1490620"),
    ("畜産","ちくさん","n","chăn nuôi | ngành chăn nuôi","animal husbandry | livestock industry","1422180"),
    ("酪農","らくのう","n","chăn nuôi bò sữa | nghề nuôi bò sữa","dairy farming","1548890"),
    ("漁業","ぎょぎょう","n","ngư nghiệp | nghề cá","fishing industry | fishery","1232990"),
    ("養殖","ようしょく","n|vs|vt","nuôi trồng (thủy sản) | nuôi cấy","aquaculture | cultivation | raising","1547180"),
    ("漁獲","ぎょかく","n|vs|vt","đánh bắt cá | sản lượng cá | mẻ cá","fishery | fishing | catch","1232980"),
    ("林業","りんぎょう","n","lâm nghiệp","forestry","1555470"),
    ("伐採","ばっさい","n|vs|vt","đốn gỗ | chặt cây | khai thác gỗ","felling timber | logging | lumbering","1478020"),
    ("植林","しょくりん","n|vs|vt|vi","trồng rừng | gây rừng","afforestation","1357390"),
    ("湿原","しつげん","n","đầm lầy cỏ | vùng đất ngập nước","marshy grassland | wetlands","1320430"),
    ("干潟","ひがた","n","bãi triều | bãi bồi ven biển","tidal flat | tideland","1212030"),
    ("沼地","ぬまち","n","đầm lầy | vùng lầy lội","marshland | wetland | swampland","1350030"),
    ("盆地","ぼんち","n","lòng chảo | bồn địa (giữa núi)","basin (e.g. between mountains)","1523760"),
    ("丘陵","きゅうりょう","n","đồi | gò đồi | vùng đồi thoai thoải","hill | hillock | rolling hills","1227320"),
    ("峡谷","きょうこく","n","hẻm núi | thung lũng sâu | hẻm vực","gorge | ravine | canyon","1236040"),
    ("断崖","だんがい","n","vách đá | vực thẳm | bờ dốc đứng","precipice | cliff | bluff","1419580"),
    ("入り江","いりえ","n","vịnh nhỏ | lạch | vũng","inlet | cove | creek | bay","1587730"),
    ("潮流","ちょうりゅう","n","dòng thủy triều | trào lưu | xu thế","tide | tidal current | tendency | trend","1428720"),
    ("海流","かいりゅう","n","dòng hải lưu | dòng biển","ocean current","1201820"),
    ("干潮","かんちょう","n","triều xuống | nước ròng | thủy triều thấp","low tide | low water | ebb","2657680"),
    ("満潮","まんちょう","n","triều lên | nước lớn | thủy triều cao","high tide | high water | full tide","1526870"),
    ("水位","すいい","n","mực nước","water level","1651070"),
    ("水源","すいげん","n","nguồn nước | đầu nguồn sông","source of river | fountainhead","1371460"),
    ("源流","げんりゅう","n","thượng nguồn | cội nguồn | khởi nguồn","source (of a river) | headwaters | origin","1263390"),
    ("下流","かりゅう","n","hạ lưu | tầng lớp dưới","downstream | lower reaches | lower classes","1186560"),
    ("支流","しりゅう","n","nhánh sông | chi lưu | phụ lưu","tributary | branch","1310330"),
    ("本流","ほんりゅう","n|adj-no","dòng chính | dòng chủ lưu | trào lưu chính","main course (of a river) | mainstream","1523280"),
    ("湖沼","こしょう","n","ao hồ | hồ đầm | thủy vực nội địa","lake | marsh | inland waters","1267290"),
    ("温泉","おんせん","n","suối nước nóng | onsen | khu tắm suối nóng","hot spring | onsen | hot spring resort","1183450"),
    ("鉱泉","こうせん","n","suối khoáng","mineral spring","1282630"),
    ("地下水","ちかすい","n","nước ngầm","groundwater | underground water","1622630"),
    ("湧水","ゆうすい","n","mạch nước phun | nước suối tự nhiên","welling of water | spring water","1855270"),
    ("氷河","ひょうが","n","sông băng | băng hà","glacier","1488880"),
    ("氷山","ひょうざん","n","núi băng | tảng băng trôi","iceberg","1489030"),
    ("噴泉","ふんせん","n","suối phun | mạch nước phun","fountain | spring","1689540"),
    ("鍾乳洞","しょうにゅうどう","n","hang động đá vôi | hang nhũ đá","limestone cave | limestone cavern","1352020"),
    ("鉱床","こうしょう","n","mỏ khoáng | vỉa quặng","mineral deposit | ore deposit","1282610"),
    ("鉱脈","こうみゃく","n","mạch quặng | vỉa quặng | mạch khoáng","vein (of ore) | reef | lode","1282670"),
    ("埋蔵","まいぞう","n|vs|vt","chôn giấu | trữ lượng (dưới lòng đất)","burying in the ground | underground deposits","1524560"),
    ("掘削","くっさく","n|vs|vt","đào | khai quật | đào khoét","digging out | excavation","1614980"),
    ("精錬","せいれん","n|vs|vt","tinh luyện | luyện kim | rèn giũa","refining | smelting | training","1380250"),
    ("冶金","やきん","n","luyện kim | thuật luyện kim","metallurgy","1536310"),
    ("鋳造","ちゅうぞう","n|vs|vt","đúc | đúc khuôn | đúc tiền","casting | founding | minting","1426860"),
    ("鍛造","たんぞう","n|vs|vt","rèn | gia công rèn","forging","1654390"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
