# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-029.csv — 49 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-029.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("温厚","おんこう","N4","adj-na|n",
        "ôn hòa | dịu dàng | hiền lành",
        "gentle | mild-mannered",
        "1183380",
        "温厚な性格です。","おんこうなせいかくです。","Tính cách ôn hòa.","They have a gentle personality."),
    row("漢語","かんご","N4","n",
        "từ Hán-Nhật | từ gốc Trung Hoa | tiếng Hán",
        "Japanese word of Chinese origin | Sino-Japanese word | language of the Han people | Chinese",
        "1213150",
        "漢語は難しいです。","かんごはむずかしいです。","Từ Hán-Nhật khó.","Sino-Japanese words are difficult."),
    row("規制","きせい","N4","n|vs|vt",
        "quy định | kiểm soát | hạn chế | điều tiết giao thông",
        "regulation | (traffic) policing | control | restriction",
        "1223010",
        "規制を守ります。","きせいをまもります。","Tôi tuân thủ quy định.","I follow the regulations."),
    row("規約","きやく","N4","n",
        "quy định | điều lệ | quy ước | nghị định",
        "agreement | rules | code | protocol | convention | bylaw",
        "1223110",
        "規約に同意します。","きやくにどういします。","Tôi đồng ý với điều lệ.","I agree to the terms."),
    row("急行","きゅうこう","N4","n|vs|adj-no|vi",
        "vội vàng | tàu nhanh | tàu tốc hành",
        "hurrying (to somewhere) | rushing | hastening | express (train)",
        "1228690",
        "急行に乗ります。","きゅうこうにのります。","Tôi đi tàu tốc hành.","I ride the express train."),
    row("勤勉","きんべん","N4","adj-na|n",
        "chăm chỉ | cần cù | siêng năng",
        "diligent | hard-working | industrious",
        "1241060",
        "勤勉な学生です。","きんべんながくせいです。","Đó là học sinh chăm chỉ.","They are a diligent student."),
    row("謙譲語","けんじょうご","N4","n",
        "ngôn ngữ khiêm nhường | kính ngữ khiêm tốn",
        "humble language (e.g. itadaku)",
        "1260230",
        "謙譲語を使います。","けんじょうごをつかいます。","Tôi dùng kính ngữ khiêm nhường.","I use humble language."),
    row("謙虚","けんきょ","N4","adj-na|n",
        "khiêm tốn | khiêm nhường",
        "modest | humble",
        "1260190",
        "謙虚な態度を取ります。","けんきょなたいどをとります。","Tôi có thái độ khiêm tốn.","I have a modest attitude."),
    row("鍵盤","けんばん","N4","n",
        "bàn phím | bàn phím đàn piano",
        "keyboard (of a piano, typewriter, etc.)",
        "1260520",
        "鍵盤を弾きます。","けんばんをひきます。","Tôi gõ bàn phím đàn.","I play the keyboard."),
    row("原材料","げんざいりょう","N4","n",
        "nguyên liệu thô | nguyên liệu | thành phần",
        "raw materials | ingredients",
        "1261430",
        "原材料を確認します。","げんざいりょうをかくにんします。","Tôi kiểm tra nguyên liệu.","I check the raw materials."),
    row("試し","ためし","N4","n",
        "thử nghiệm | thử | kiểm tra",
        "trial | test | try",
        "1312250",
        "試しに使ってみます。","ためしにつかってみます。","Tôi thử dùng xem.","I try using it."),
    row("尊敬語","そんけいご","N4","n",
        "ngôn ngữ tôn kính | kính ngữ tôn trọng",
        "honorific language",
        "1406410",
        "尊敬語を正しく使います。","そんけいごをただしくつかいます。","Tôi dùng đúng kính ngữ tôn trọng.","I use honorific language correctly."),
    row("丁寧語","ていねいご","N4","n",
        "ngôn ngữ lịch sự | kính ngữ lịch sự",
        "polite language (e.g. masu, desu)",
        "1427370",
        "丁寧語で話します。","ていねいごではなします。","Tôi nói bằng ngôn ngữ lịch sự.","I speak in polite language."),
    row("分数","ぶんすう","N4","n|adj-no",
        "phân số",
        "fraction",
        "1503860",
        "分数を計算します。","ぶんすうをけいさんします。","Tôi tính phân số.","I calculate fractions."),
    row("仕組み","しくみ","N4","n",
        "cơ cấu | cơ chế | cấu trúc | cách thức hoạt động",
        "structure | construction | arrangement | contrivance | mechanism | workings | plan | plot | contrivance",
        "1594180",
        "システムの仕組みを学びます。","システムのしくみをまなびます。","Tôi học cơ chế của hệ thống.","I learn the mechanism of the system."),
    row("枠組み","わくぐみ","N4","n",
        "khung | khung cơ cấu | cấu trúc | phác thảo",
        "frame (physical structure) | framework | framework (of a plan, system, etc.) | structure | outline",
        "1606690",
        "枠組みを作ります。","わくぐみをつくります。","Tôi tạo khung cơ cấu.","I create a framework."),
    row("見通し","みとおし","N4","n",
        "tầm nhìn | triển vọng | dự báo | cái nhìn xa",
        "unobstructed view | perspective | visibility | vista | forecast | outlook | prospect | prediction | insight | foresight",
        "1604610",
        "将来の見通しを立てます。","しょうらいのみとおしをたてます。","Tôi lập triển vọng tương lai.","I make a forecast for the future."),
    row("自然保護","しぜんほご","N4","n",
        "bảo tồn thiên nhiên | bảo vệ tự nhiên",
        "nature conservation",
        "1726660",
        "自然保護に取り組みます。","しぜんほごにとりくみます。","Tôi tham gia bảo tồn thiên nhiên.","I engage in nature conservation."),
    row("密度","みつど","N4","n",
        "mật độ | tỉ trọng",
        "density",
        "1528320",
        "密度を計算します。","みつどをけいさんします。","Tôi tính mật độ.","I calculate the density."),
    row("和語","わご","N4","n",
        "từ thuần Nhật | từ Nhật gốc bản địa | từ Yamato",
        "Japanese language | wago | native Japanese words (as opposed to Chinese-derived words and other loanwords)",
        "1562080",
        "和語は日本固有の言葉です。","わごはにほんこゆうのことばです。","Từ Yamato là từ ngữ riêng của Nhật Bản.","Wago are Japan's native words."),
    row("切符売り場","きっぷうりば","N4","n",
        "quầy bán vé | phòng vé",
        "ticket window | box office | ticket",
        "1591310",
        "切符売り場で買います。","きっぷうりばでかいます。","Tôi mua ở quầy bán vé.","I buy at the ticket window."),
    row("直径","ちょっけい","N4","n",
        "đường kính",
        "diameter",
        "1597720",
        "直径を測ります。","ちょっけいをはかります。","Tôi đo đường kính.","I measure the diameter."),
    row("手がかり","てがかり","N4","n",
        "manh mối | chìa khóa | dấu vết | chỗ bám",
        "clue | lead | key | trail | scent | track | handhold | hold",
        "1598300",
        "手がかりを見つけます。","てがかりをみつけます。","Tôi tìm manh mối.","I find a clue."),
    row("見込み","みこみ","N4","n",
        "kỳ vọng | triển vọng | khả năng | dự tính",
        "hope | promise | possibility | chance | probability | likelihood | expectation | anticipation | forecast | estimate",
        "1604480",
        "見込みがあります。","みこみがあります。","Có triển vọng.","There is hope."),
    row("自治会","じちかい","N4","n",
        "hội cư dân | hội tự quản | hội tự trị",
        "neighborhood council | neighbourhood council | residents' association | student council",
        "1726190",
        "自治会の活動に参加します。","じちかいのかつどうにさんかします。","Tôi tham gia hoạt động hội cư dân.","I participate in residents' association activities."),
    row("言い直す","いいなおす","N4","v5s|vt",
        "nói lại | sửa lại lời nói | phát biểu lại",
        "to correct oneself | to restate",
        "1848310",
        "間違えたので言い直します。","まちがえたのでいいなおします。","Tôi nói lại vì đã nhầm.","I restate because I made a mistake."),
    row("解き放つ","ときはなつ","N4","v5t|vt",
        "giải phóng | thả ra | trả tự do",
        "to release",
        "2006230",
        "囚人を解き放ちます。","しゅうじんをときはなちます。","Tôi thả tù nhân.","I release the prisoner."),
    row("乗り継ぎ","のりつぎ","N4","adj-f",
        "nối tuyến | chuyến nối | trung chuyển",
        "transit (passenger) | connecting (flight) | transfer (ticket)",
        "2011410",
        "乗り継ぎがあります。","のりつぎがあります。","Có chuyến nối.","There is a connection."),
    row("グリーン車","グリーンしゃ","N4","n",
        "toa hạng nhất | toa xanh (Japan Railway)",
        "green car (Japan Railway's 1st class)",
        "1047120",
        "グリーン車に乗ります。","グリーンしゃにのります。","Tôi đi toa hạng nhất.","I ride the green car."),
    row("違反","いはん","N4","n|vs|vi",
        "vi phạm | phạm luật | xâm phạm",
        "violation | offense | offence | breach | transgression | infringement | contravention",
        "1158950",
        "交通違反をします。","こうつういはんをします。","Tôi vi phạm giao thông.","I commit a traffic violation."),
    row("円周","えんしゅう","N4","n|adj-no",
        "chu vi | chu vi đường tròn",
        "circumference",
        "1175860",
        "円周を計算します。","えんしゅうをけいさんします。","Tôi tính chu vi.","I calculate the circumference."),
    row("回数券","かいすうけん","N4","n",
        "vé nhiều lần | vé giảm giá | tập vé",
        "coupon tickets | discount tickets | book of tickets",
        "1199520",
        "回数券を買います。","かいすうけんをかいます。","Tôi mua vé nhiều lần.","I buy coupon tickets."),
    row("外来語","がいらいご","N4","n",
        "từ ngoại lai | từ vay mượn | từ có gốc nước ngoài",
        "loanword (in Japanese, esp. one of Western origin) | word of foreign origin",
        "1204260",
        "外来語はカタカナで書きます。","がいらいごはカタカナでかきます。","Từ ngoại lai được viết bằng katakana.","Loanwords are written in katakana."),
    row("気遣い","きづかい","N4","n",
        "quan tâm | lo lắng | chú ý | sự ân cần",
        "consideration | concern | fear | worry | solicitude",
        "1222140",
        "気遣いをありがとう。","きづかいをありがとう。","Cảm ơn sự quan tâm.","Thank you for your consideration."),
    row("敬語","けいご","N4","n",
        "kính ngữ | ngôn ngữ tôn trọng | từ lịch sự",
        "honorific | term of respect | polite expression | honorific language",
        "1250750",
        "敬語を使います。","けいごをつかいます。","Tôi dùng kính ngữ.","I use honorifics."),
    row("標準語","ひょうじゅんご","N4","n",
        "ngôn ngữ chuẩn | tiếng Nhật chuẩn | thổ ngữ chuẩn",
        "standard language (used in government, education, etc.) | standard Japanese",
        "1488730",
        "標準語を話します。","ひょうじゅんごをはなします。","Tôi nói tiếng chuẩn.","I speak standard language."),
    row("検証","けんしょう","N4","n|vs|vt",
        "kiểm chứng | xác minh | kiểm tra tại chỗ",
        "verification | confirmation | substantiation | on-site inspection (by a judge, investigator, etc.) to gather physical evidence | verification",
        "1257950",
        "データを検証します。","データをけんしょうします。","Tôi kiểm chứng dữ liệu.","I verify the data."),
    row("試み","こころみ","N4","n",
        "thử nghiệm | nỗ lực | cố gắng | sáng kiến",
        "attempt | trial | experiment | endeavour (endeavor) | effort | venture | initiative",
        "1312270",
        "新しい試みをします。","あたらしいこころみをします。","Tôi thử nghiệm mới.","I try a new initiative."),
    row("自由席","じゆうせき","N4","n",
        "chỗ ngồi tự do | ghế không đặt trước",
        "unreserved seat | non-reserved seat",
        "1318790",
        "自由席に座ります。","じゆうせきにすわります。","Tôi ngồi ghế tự do.","I sit in the unreserved seat."),
    row("小数","しょうすう","N4","n|adj-no",
        "số thập phân | phân số nhỏ",
        "fraction (part of) | decimal fraction",
        "1348370",
        "小数を計算します。","しょうすうをけいさんします。","Tôi tính số thập phân.","I calculate decimal fractions."),
    row("焦る","あせる","N4","v5r|vi",
        "nôn nóng | vội vã | lo lắng | hoảng hốt | mất bình tĩnh",
        "to be in a hurry | to be impatient | to be anxious (to do) | to fret | to get a fright | to panic | to get flustered | to be startled",
        "1350780",
        "焦らないでください。","あせらないでください。","Đừng vội vã.","Please don't panic."),
    row("寸法","すんぽう","N4","n",
        "kích thước | số đo | chiều kích | kế hoạch",
        "measurement | size | extent | dimension | plan | intention | arrangement | schedule",
        "1373810",
        "寸法を測ります。","すんぽうをはかります。","Tôi đo kích thước.","I measure the dimensions."),
    row("整数","せいすう","N4","n",
        "số nguyên",
        "integer",
        "1376190",
        "整数を計算します。","せいすうをけいさんします。","Tôi tính số nguyên.","I calculate integers."),
    row("誠実","せいじつ","N4","adj-na|n",
        "thành thật | trung thực | chân thành",
        "sincere | honest | faithful",
        "1381180",
        "誠実な人が好きです。","せいじつなひとがすきです。","Tôi thích người thành thật.","I like sincere people."),
    row("特急","とっきゅう","N4","n",
        "tàu tốc hành đặc biệt | tốc hành hạn chế dừng | rất vội",
        "limited express (train for which a limited-express ticket is required) | limited express (train making a limited no. of stops) | great hurry",
        "1454750",
        "特急で行きます。","とっきゅうでいきます。","Tôi đi bằng tàu tốc hành.","I go by limited express."),
    row("罰則","ばっそく","N4","n",
        "quy định phạt | hình phạt | chế tài",
        "punishment | penalty | penal regulations | penal provisions | penal code",
        "1478100",
        "罰則を受けます。","ばっそくをうけます。","Tôi bị hình phạt.","I receive a penalty."),
    row("半径","はんけい","N4","n",
        "bán kính",
        "radius",
        "1479230",
        "半径を求めます。","はんけいをもとめます。","Tôi tính bán kính.","I find the radius."),
    row("聞き逃す","ききのがす","N4","v5s|vt",
        "không nghe thấy | bỏ lỡ (lời nói) | giả vờ không nghe",
        "to fail to hear something | to miss | to act as if one didn't hear something | to let a remark slide",
        "2396580",
        "大切なことを聞き逃します。","たいせつなことをききのがします。","Tôi bỏ lỡ điều quan trọng.","I miss something important."),
    row("無口","むこう","N4","adj-no",
        "không miệng | không có lỗ miệng (sinh học)",
        "astomatous",
        "2826903",
        "無口の生物です。","むこうのせいぶつです。","Đây là sinh vật không có miệng.","This is an organism without a mouth."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
