# -*- coding: utf-8 -*-
"""Build N2 ready wave 029 — physics/state changes, fluids, adhesion, electricity, weather phenomena."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-029.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("震動","しんどう","n|vs|vi","chấn động | rung chuyển | rung động","shock | tremor | vibration","1366390"),
    ("揺動","ようどう","n|vs|vt|vi","lắc lư | đung đưa | dao động","shaking | swinging","1855110"),
    ("旋回","せんかい","n|vs|vi","quay | xoay | lượn vòng | vòng (máy bay)","revolution | rotation | circling | turning","1391650"),
    ("循環","じゅんかん","n|vs|vi","tuần hoàn | luân chuyển | chu trình | vòng lặp","circulation | rotation | cycle | loop","1341340"),
    ("還流","かんりゅう","n|vs|vi","dòng hồi lưu | dòng chảy ngược","return current | reflux | back flow","1215150"),
    ("逆流","ぎゃくりゅう","n|vs|vi","chảy ngược | trào ngược | dòng nghịch lưu","backward flow | countercurrent | regurgitation","1227270"),
    ("渦","うず","n","xoáy nước | vòng xoáy | cơn lốc","whirlpool | swirl | eddy | vortex","1172310"),
    ("気流","きりゅう","n","luồng khí | dòng khí | luồng không khí","atmospheric current | air current | airflow","1222680"),
    ("対流","たいりゅう","n|adj-no","đối lưu","convection","1713920"),
    ("噴射","ふんしゃ","n|vs|vt","phun | tia phun | phun đẩy | phản lực","jet | spray | jet propulsion","1504590"),
    ("放射","ほうしゃ","n|vs|vt","bức xạ | phát xạ | tỏa ra","radiation | emission","1516600"),
    ("回折","かいせつ","n|vs|vi","nhiễu xạ","diffraction","1199540"),
    ("散乱","さんらん","n|adj-f|vs|vi","tán xạ | rải rác | vương vãi | phân tán","dispersion | scattering | diffusion","1303640"),
    ("収束","しゅうそく","n|vs|vt|vi","kết thúc | lắng xuống | hội tụ | gom lại","conclusion | settling | convergence","1330750"),
    ("集束","しゅうそく","n|vs|vt|vi","hội tụ (ánh sáng) | tụ chùm | bó lại","focusing (of light) | convergence","1952350"),
    ("共振","きょうしん","n|vs|vi","cộng hưởng | rung đồng pha","resonance | sympathetic vibration","1234630"),
    ("増幅","ぞうふく","n|vs|vt|vi","khuếch đại | phóng đại | làm tăng","amplification | magnification","1403360"),
    ("減衰","げんすい","n|vs|vi","suy giảm | tắt dần | giảm chấn","attenuation | damping | decay","1263230"),
    ("振幅","しんぷく","n","biên độ (dao động) | mức biến động | độ dao động","amplitude (of vibration) | fluctuation | swing","1361440"),
    ("波動","はどう","n|adj-no","chuyển động sóng | làn sóng | sự dao động","wave motion | undulation | surge","1471080"),
    ("脈動","みゃくどう","n|vs|vi","sự đập (mạch) | chuyển động nhịp nhàng","pulsation | pulsatory motion","1528460"),
    ("拍動","はくどう","n|vs|vi|adj-no","nhịp đập | sự đập (tim)","pulsation | pulsebeat","1625910"),
    ("伸縮","しんしゅく","n|vs|vt|vi","co giãn | đàn hồi | linh hoạt","expansion and contraction | elasticity","1358960"),
    ("弛緩","しかん","n|vs|vi","thư giãn | giãn ra | nhão ra (cơ)","relaxation (of muscles) | becoming flaccid","1581650"),
    ("緊縮","きんしゅく","n|vs|vt|vi","thắt chặt | co lại | thắt lưng buộc bụng | khắc khổ","tightening | contraction | austerity","1241870"),
    ("希釈","きしゃく","n|vs|vt","pha loãng | làm loãng","dilution","1219870"),
    ("濃縮","のうしゅく","n|vs|vt|adj-no","cô đặc | làm đậm đặc | làm giàu (chất)","concentration | enrichment | condensation","1469930"),
    ("飽和","ほうわ","n|vs|vi","bão hòa | no | đầy ắp","saturation | satiation","1518350"),
    ("沈殿","ちんでん","n|vs|vi","lắng cặn | kết tủa | lắng đọng","precipitation | deposition | settlement","1431790"),
    ("沈降","ちんこう","n|vs|vi","lắng xuống | kết lắng | sụt lún | chìm xuống","sedimentation | precipitation | subsidence","1431700"),
    ("潜航","せんこう","n|vs|vi","lặn (tàu ngầm) | đi ngầm dưới nước","submarine voyage | underwater navigation","1391300"),
    ("浮遊","ふゆう","n|vs|vt|vi","trôi nổi | lơ lửng | lang thang | huyền phù","floating | drifting | suspension | wandering","1625100"),
    ("滞留","たいりゅう","n|vs|vi","ứ đọng | đình trệ | dồn ứ | lưu lại","stagnation | accumulation | sojourn","1661070"),
    ("透過","とうか","adj-na|n|vs|vi","thấm qua | xuyên qua | truyền qua","penetration | permeation | transmission","1450540"),
    ("通気","つうき","n","thông gió | thông khí | thoáng khí","ventilation | airflow","1433110"),
    ("通風","つうふう","n|vs|vi|adj-no","thông gió | lưu thông không khí","ventilation | draft | airing","1433510"),
    ("吸気","きゅうき","n","hít vào | khí hít vào | khí nạp","inhalation | intake (of air)","1228280"),
    ("吸引","きゅういん","n|vs|vt","hút | hấp thụ | thu hút | lực hút","absorption | suction | attraction","1228270"),
    ("吸収","きゅうしゅう","n|vs|vt","hấp thu | hấp thụ | thu hút","absorption | suction | attraction","1228330"),
    ("吸着","きゅうちゃく","n|vs|vi","hấp phụ | bám hút | dính chặt","adsorption | adhesion (by suction)","1228360"),
    ("付着","ふちゃく","n|vs|vi","dính vào | bám vào | kết dính","sticking to | adhesion | cohesion","1496400"),
    ("癒着","ゆちゃく","n|vs|vi","dính liền (vết thương) | cấu kết | quan hệ mờ ám","adhesion | collusion | cozy relationship","1538760"),
    ("粘着","ねんちゃく","n|vs|vi","kết dính | bám dính","cohesion | adhesion","1469730"),
    ("接着","せっちゃく","n|vs|vt|vi","dán | gắn kết | kết dính","adhesion | gluing | bonding","1385570"),
    ("凝着","ぎょうちゃく","n|vs|vi","bám dính | kết dính","adhesion","1239220"),
    ("剥離","はくり","n|vs|vt|vi","bong tróc | tách rời | bóc ra","detachment | peeling off | exfoliation","1474520"),
    ("剥落","はくらく","n|vs|vi","bong ra | rơi rụng (sơn, gạch) | tróc ra","peeling off | falling off | exfoliation","1474510"),
    ("脱落","だつらく","n|vs|vi","rơi rụng | bị loại | tụt lại | thiếu sót | bỏ cuộc","dropping out | falling behind | omission","1416640"),
    ("欠落","けつらく","n|vs|vi","thiếu | khuyết | thiếu sót | mất","lack | absence | omission","1254110"),
    ("崩落","ほうらく","n|vs|vi","sụp đổ | sạt lở | lao dốc (thị trường)","collapse | cave-in | market decline","1627430"),
    ("崩壊","ほうかい","n|vs|vi","sụp đổ | đổ vỡ | tan rã | phân rã (hạt nhân)","collapse | breaking down | (radioactive) decay","1516280"),
    ("倒壊","とうかい","n|vs|vi","đổ sập | sụp đổ | đổ nát","destruction | collapse | crumbling","1896720"),
    ("亀裂","きれつ","n","vết nứt | kẽ nứt | rạn nứt | rạn (quan hệ)","crack | crevice | fissure | rift","1224320"),
    ("破裂","はれつ","n|vs|vi","vỡ | nổ | bục | đổ vỡ (đàm phán)","bursting | rupture | explosion | breakdown","1471470"),
    ("炸裂","さくれつ","n|vs|vi","nổ tung | nổ dữ dội | bùng nổ","violent explosion | bursting","1568980"),
    ("爆発","ばくはつ","n|vs|vi","nổ | bùng nổ | phun trào | bộc phát (cảm xúc)","explosion | detonation | outburst (of emotion)","1475910"),
    ("発光","はっこう","n|vs|vi","phát sáng | phát quang | tỏa sáng","emission of light | luminescence","1477360"),
    ("明滅","めいめつ","n|vs|vi","nhấp nháy | chớp tắt | lập lòe","flickering | blinking","1618330"),
    ("放熱","ほうねつ","n|vs|vi","tỏa nhiệt | thoát nhiệt | tản nhiệt","radiant heat | heat dissipation","1516850"),
    ("吸熱","きゅうねつ","n|vs|adj-no","thu nhiệt | hấp thụ nhiệt","absorption of heat","2843620"),
    ("凍結","とうけつ","n|vs|vi|vt","đông cứng | đóng băng | phong tỏa (tài sản, giá)","freezing | freezing (assets) | suspension","1446300"),
    ("融解","ゆうかい","n|vs|vt|vi","nóng chảy | tan chảy | hợp nhất","melting | fusion | liquefaction","1542580"),
    ("昇華","しょうか","n|vs|vi|vt","thăng hoa | nâng lên tầm cao | hóa hơi (rắn)","sublimation | sublimation (of an impulse)","1706840"),
    ("液状","えきじょう","n|adj-no","thể lỏng | trạng thái lỏng","liquid state","1175010"),
    ("固形","こけい","n|adj-no","thể rắn | dạng rắn | dạng đặc","solid (body)","1266590"),
    ("結露","けつろ","n|vs|vi","ngưng tụ hơi nước | đọng sương","condensation | formation of dew","1628420"),
    ("霞","かすみ","n","sương mù (mùa xuân) | màn sương | mờ mắt","haze (esp. in spring) | mist | dimness (of sight)","1196510"),
    ("陽炎","かげろう","n","ảo ảnh do nắng | hơi nóng lung linh","heat shimmer | heat haze","1546970"),
    ("蜃気楼","しんきろう","n","ảo ảnh | ảo cảnh | hải thị","mirage","1571970"),
    ("雷鳴","らいめい","n","tiếng sấm | sấm rền","thunder | thunderclap","1548470"),
    ("落雷","らくらい","n|vs|vi","sét đánh | tia sét","lightning strike | lightning bolt","1548860"),
    ("帯電","たいでん","n|vs|vi","nhiễm điện | mang điện","electrification","1753690"),
    ("放電","ほうでん","n|vs|vi","phóng điện | xả điện","discharging (electrically) | electrical discharge","1516800"),
    ("感電","かんでん","n|vs|vi","bị điện giật | giật điện","receiving an electric shock","1212540"),
    ("漏電","ろうでん","n|vs|vi","rò điện | chập điện | hở điện","short circuit | leakage (of electricity)","1560900"),
    ("通電","つうでん","n|vs|vi","cấp điện | thông điện | có điện","flow of electric current | supply of power","1983870"),
    ("蓄電","ちくでん","n|vs|vt|vi","tích điện | trữ điện","storage of electricity","1698010"),
    ("送電","そうでん","n|vs|vt|vi","truyền tải điện | cấp điện","transmission of electricity | power supply","1402830"),
    ("変電","へんでん","n","biến đổi điện năng","transformation of electrical energy","2829295"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
