# -*- coding: utf-8 -*-
"""Build N2 ready wave 041 — disposition, attitude, 〜っぽい adjectives, true feelings, ulterior motives."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-041.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("気立て","きだて","n","tính tình | bản tính | tâm tính","disposition | nature","1222670"),
    ("気心","きごころ","n","tính khí | tâm tính | bụng dạ","temper | disposition","1222360"),
    ("気骨","きこつ","n","khí cốt | cốt cách | bản lĩnh | tinh thần","(moral) backbone | spirit | grit","1222220"),
    ("心情","しんじょう","n","tâm tình | tình cảm | nỗi lòng","sentiment | one's feelings | one's heart","1360720"),
    ("心境","しんきょう","n","tâm trạng | trạng thái tinh thần","state of mind | mental attitude","1360630"),
    ("心持ち","こころもち","n|adv","tâm trạng | cảm giác | tinh thần | hơi | một chút","feeling | mood | disposition | slightly","1360700"),
    ("心構え","こころがまえ","n|vs","sự chuẩn bị tâm lý | tâm thế | tinh thần sẵn sàng","preparedness | mental attitude","1360670"),
    ("気兼ね","きがね","n|vs|vi","sự nể nang | ngại ngần | e dè | sợ làm phiền","constraint | reserve | feeling hesitant","1222120"),
    ("気落ち","きおち","n|vs|vi","ngã lòng | nản chí | chán nản","discouraged | dispirited | despondent","1618040"),
    ("気休め","きやすめ","n","lời an ủi suông | sự yên tâm tạm thời","mere consolation | temporary peace of mind","1222060"),
    ("意気地","いくじ","n","lòng tự trọng | sự tự tin | bản lĩnh | ý chí","self-respect | guts | backbone | willpower","1156480"),
    ("意地っ張り","いじっぱり","adj-na|n","bướng bỉnh | cố chấp | người ngoan cố","obstinate | stubborn person","1156730"),
    ("弱腰","よわごし","adj-na|adj-no|n","thái độ nhu nhược | yếu thế | rụt rè","weak attitude","1324740"),
    ("強腰","つよごし","n","thái độ cứng rắn | lập trường kiên quyết","firm or tough stance","1799870"),
    ("本腰","ほんごし","n","sự nghiêm túc | dốc sức | quyết tâm thật sự","strenuous effort | seriousness","1522550"),
    ("及び腰","およびごし","n","tư thế khom lưng | thái độ do dự | rụt rè | thiếu quyết đoán","indecisive attitude | timidity","1228150"),
    ("逃げ腰","にげごし","n","tư thế chực bỏ chạy | thái độ né tránh | sẵn sàng chuồn","preparing to flee | being ready to run away","1636960"),
    ("喧嘩腰","けんかごし","n|adj-no","thái độ hiếu chiến | gây sự | sẵn sàng cãi vã","belligerent attitude | readiness to fight","1257050"),
    ("低姿勢","ていしせい","n","thái độ khiêm nhường | giữ thái độ thấp","(keeping a) low profile","1758880"),
    ("高姿勢","こうしせい","adj-na|n","thái độ kẻ cả | thái độ hung hăng | bề trên","high profile | aggressive attitude","1283540"),
    ("腰抜け","こしぬけ","n","kẻ hèn nhát | đồ nhát gan","coward","1288450"),
    ("小心","しょうしん","n|adj-na","nhút nhát | hèn nhát | thận trọng | tủn mủn","timidity | cowardice | prudence","1348320"),
    ("不用心","ぶようじん","adj-na|n","không an toàn | sơ hở | bất cẩn | thiếu đề phòng","unsafe | careless | incautious","1583610"),
    ("不注意","ふちゅうい","n|adj-na","bất cẩn | sơ ý | thiếu chú ý | cẩu thả","carelessness | inattention | negligence","1493830"),
    ("無造作","むぞうさ","adj-na|n","tùy tiện | qua loa | thoải mái | không cầu kỳ | cẩu thả","easy | casual | off-hand | careless","1530500"),
    ("無遠慮","ぶえんりょ","adj-na|n","thiếu ý tứ | sỗ sàng | tự tiện | trơ trẽn","rude | outspoken | presumptuous","1529670"),
    ("不躾","ぶしつけ","adj-na|n","thiếu lễ độ | bất lịch sự | suồng sã | đường đột","ill-bred | impolite | rude | blunt","1495530"),
    ("出しゃばり","でしゃばり","n|adj-na|adj-no","sự lắm chuyện | xen vào việc người | người hay xía","being intrusive | intrusive person","2582090"),
    ("世話好き","せわずき","adj-na|n","người thích chăm lo người khác | hay giúp đỡ","obliging person | person who likes looking after others","1753900"),
    ("お人好し","おひとよし","n|adj-na|adj-no","người tốt bụng | người cả tin | dễ bị lừa","good-natured person | credulous person | soft touch","1648010"),
    ("人懐っこい","ひとなつっこい","adj-i","dễ gần | thân thiện | dễ mến | quấn người","friendly | affable | sociable","1366670"),
    ("社交性","しゃこうせい","n","tính hòa đồng | khả năng giao tiếp","sociability","1702670"),
    ("協調性","きょうちょうせい","n","tính hợp tác | tinh thần phối hợp","cooperativeness | spirit of cooperation","1814940"),
    ("自主性","じしゅせい","n","tính tự chủ | tính độc lập | sự tự giác","autonomy | independence","1726040"),
    ("忍耐力","にんたいりょく","n","sức chịu đựng | tính kiên nhẫn | sự bền bỉ","fortitude | perseverance | patience","1729400"),
    ("根気強い","こんきづよい","adj-i","kiên trì | bền bỉ | nhẫn nại | không nản","persevering | persistent | patient","2870939"),
    ("我が強い","ががつよい","exp|adj-i","cái tôi lớn | ích kỷ | bảo thủ ý mình","egoistic | selfish | self-willed","1625130"),
    ("飽きっぽい","あきっぽい","adj-i","mau chán | cả thèm chóng chán | thất thường","easily bored | quick to lose interest | fickle","1621650"),
    ("怒りっぽい","おこりっぽい","adj-i","dễ nổi nóng | nóng tính | hay cáu","hot-tempered | irascible | touchy","2013850"),
    ("忘れっぽい","わすれっぽい","adj-i","hay quên | đãng trí","forgetful","1519200"),
    ("湿っぽい","しめっぽい","adj-i","ẩm ướt | ẩm thấp | buồn bã | ảm đạm","damp | humid | gloomy | melancholy","1609910"),
    ("理屈っぽい","りくつっぽい","adj-i","hay lý sự | thích cãi lý | lý luận","argumentative","1795760"),
    ("俗っぽい","ぞくっぽい","adj-i","tầm thường | thô tục | rẻ tiền | kém tinh tế","vulgar | in poor taste | cheap","1405110"),
    ("水っぽい","みずっぽい","adj-i","loãng | nhão nước | ướt át | gợi tình | khêu gợi","watery | soggy | racy | suggestive","1637530"),
    ("安っぽい","やすっぽい","adj-i","rẻ tiền | tầm thường | kém sang | không đáng kể","cheap-looking | tawdry | insignificant","1153680"),
    ("荒っぽい","あらっぽい","adj-i","thô bạo | hung hăng | cộc cằn | qua loa | cẩu thả","wild | violent | rough-mannered | crude","1281470"),
    ("熱っぽい","ねつっぽい","adj-i","sốt sốt | hâm hấp sốt | đầy nhiệt huyết","feverish | enthusiastic","2012730"),
    ("哀れっぽい","あわれっぽい","adj-i","thảm thương | đáng thương | ai oán","plaintive | piteous | doleful","1150120"),
    ("子供っぽい","こどもっぽい","adj-i","trẻ con | con nít | ngây ngô | non nớt","childish | childlike | immature","2103380"),
    ("大人びる","おとなびる","v1|vi","ra dáng người lớn | trưởng thành | chững chạc","to look grown-up | to be adult-like | to mature","2012150"),
    ("照れくさい","てれくさい","adj-i","ngượng ngùng | bẽn lẽn | khó xử","embarrassing | awkward","1350900"),
    ("面倒くさい","めんどくさい","adj-i","phiền phức | rắc rối | ngại làm | lười","bothersome | tiresome | a bother to do","1533560"),
    ("胡散臭い","うさんくさい","adj-i","đáng ngờ | khả nghi | ám muội | mờ ám","suspicious-looking | shady | dubious | fishy","1267540"),
    ("嘘くさい","うそくさい","adj-i","có vẻ giả dối | nghe như bịa | không thật","contrived | false-sounding","2750860"),
    ("インチキ","インチキ","n|adj-na","gian lận | lừa đảo | giả mạo | dỏm | bịp","cheating | fraud | fake | bogus | sham","1023340"),
    ("まやかし","まやかし","n|adj-no","sự lừa gạt | trò bịp | đồ giả | hàng dỏm","deception | fake | counterfeit | phony","1012220"),
    ("偽物","にせもの","n","đồ giả | hàng nhái | đồ giả mạo","forgery | counterfeit | imitation","1577800"),
    ("本物","ほんもの","n|adj-no","đồ thật | hàng thật | thứ thiệt","genuine article | real thing","1523180"),
    ("代物","しろもの","n","món hàng | thứ | của nợ | gã | giá tiền","article | goods | fellow | stuff","1412270"),
    ("得体","えたい","n","bản chất | tính cách | lai lịch","nature | character","1454570"),
    ("正体","しょうたい","n","bản chất thật | nguyên hình | chân tướng | ý thức","true character | true form | identity | consciousness","1377530"),
    ("化けの皮","ばけのかわ","exp|n","lớp mặt nạ | vỏ bọc che giấu bản chất | sự ngụy trang","mask (concealing one's true character) | disguise","1186680"),
    ("裏表","うらおもて","n","mặt trái mặt phải | trong ngoài | lộn ngược | hai mặt","back and front | inside out | double-dealing | two faces","1550560"),
    ("胸の内","むねのうち","exp|n","nỗi lòng | tâm tư | điều trong lòng","what's in one's heart | one's emotional state","2840953"),
    ("心の内","こころのうち","exp|n","trong lòng | tâm tư | suy nghĩ thầm kín","one's heart | one's feelings | one's inner thoughts","1876420"),
    ("内心","ないしん","n|adj-no|adv","nội tâm | trong lòng | ý định thật | thâm tâm","inner thoughts | real intention | at heart","1458550"),
    ("本心","ほんしん","n","lòng thành thật | ý định thật | bản tâm | lương tâm","true feelings | real intention | one's conscience","1522740"),
    ("真情","しんじょう","n","tình cảm thật | tâm tình chân thật","true feeling","1363950"),
    ("心底","しんそこ","n|adv","đáy lòng | tận đáy lòng | thật lòng | hết lòng","bottom of one's heart | wholeheartedly | truly","1360860"),
    ("胸中","きょうちゅう","n|adj-no","tâm tư | nỗi lòng | ý định trong lòng","one's heart | one's mind | one's intentions","1237950"),
    ("思惑","おもわく","n","dự tính | toan tính | ý đồ | động cơ | dư luận","expectation | calculations | intention | ulterior motive","1309630"),
    ("魂胆","こんたん","n","mưu đồ | toan tính | âm mưu | uẩn khúc","ulterior motive | plot | scheme","1290640"),
    ("下心","したごころ","n","ý đồ thầm kín | dụng tâm | dã tâm","secret intention | ulterior motive","1185450"),
    ("邪心","じゃしん","n","tà tâm | ác tâm | dã tâm xấu","wicked heart | evil design","1634860"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
