# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-036.csv -- 24 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-036.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("成り立つ","なりたつ","N4","v5t|vi",
        "gồm có | được tạo thành từ | có hiệu lực | khả thi | thành lập được",
        "to consist of | to be made up of | to hold true | to be viable | to carry on",
        "1375600",
        "契約が成り立つ。","けいやくがなりたつ。",
        "Hợp đồng được thành lập.","The contract is concluded."),
    row("畑","はたけ","N4","n|n-suf",
        "ruộng | đất trồng trọt | vườn rau | lĩnh vực chuyên môn",
        "field (for growing wheat, fruit, vegetables, etc.) | cultivated land | vegetable plot | field (of specialization)",
        "1476520",
        "畑で野菜を育てる。","はたけでやさいをそだてる。",
        "Trồng rau trên ruộng.","Grow vegetables in the field."),
    row("体","たい","N4","n|n-suf|ctr",
        "cơ thể | hình thức | thực thể | kiểu chữ | con (đơn vị đếm hình người)",
        "body | physique | shape | form | style | substance | counter for humanoid forms | typeface",
        "1409150",
        "固体と液体。","こたいとえきたい。",
        "Chất rắn và chất lỏng.","Solid and liquid."),
    row("腸","はらわた","N4","n",
        "ruột | nội tạng | tâm hồn | tinh thần",
        "intestines | bowels | entrails | guts | heart | spirit",
        "2863260",
        "はらわたが煮え繰り返る。","はらわたがにえくりかえる。",
        "Bên trong sục sôi giận dữ.","Be boiling with rage."),
    row("不透明","ふとうめい","N4","adj-na|n",
        "không trong suốt | mờ đục | không rõ ràng | không chắc chắn",
        "opaque | obscure | murky | unclear | unpredictable | uncertain",
        "1494200",
        "将来が不透明だ。","しょうらいがふとうめいだ。",
        "Tương lai không chắc chắn.","The future is uncertain."),
    row("反対","はんたい","N4","n|vs|vi|adj-no|adj-na",
        "phản đối | chống lại | ngược lại | trái ngược | đối lập",
        "opposition | resistance | objection | dissent | reverse | opposite | contrary",
        "1480670",
        "反対意見を述べる。","はんたいいけんをのべる。",
        "Trình bày ý kiến phản đối.","State an opposing opinion."),
    row("切り捨てる","きりすてる","N4","v1|vt",
        "cắt bỏ | từ bỏ | bỏ mặc | làm tròn xuống | chém hạ",
        "to cut off and throw away | to abandon | to discard | to round down | to cut (someone) down",
        "1591810",
        "端数を切り捨てる。","はすうをきりすてる。",
        "Làm tròn xuống số lẻ.","Round down the fraction."),
    row("打ち壊す","うちこわす","N4","v5s|vt",
        "phá hủy | đập tan | phá vỡ | xóa bỏ (phong tục) | lật đổ",
        "to destroy | to break (by striking) | to smash | to ruin (e.g. a plan) | to overthrow (a system)",
        "2859185",
        "既成概念を打ち壊す。","きせいがいねんをうちこわす。",
        "Phá vỡ quan niệm cũ.","Destroy old concepts."),
    row("湧く","わく","N4","v5k|vi",
        "trào ra | phun lên | nảy sinh | xuất hiện (cảm xúc) | nở ra (trứng)",
        "to well (up) | to gush out | to spring out | to feel emotions (e.g. joy, bravery) | to spring up (an idea) | to hatch",
        "1606685",
        "勇気が湧く。","ゆうきがわく。",
        "Dũng cảm trào dâng.","Courage wells up."),
    row("滲む","にじむ","N4","v5m|vi",
        "chảy loang | nhòa | rỉ ra | ứa ra (nước mắt) | hiện ra (cảm xúc)",
        "to run (of liquid) | to spread | to blur | to ooze | to well up (of tears) | to show through (of feelings)",
        "1568800",
        "インクが滲む。","いんくがにじむ。",
        "Mực bị nhòa.","Ink blurs."),
    row("潜る","くぐる","N4","v5r|vi",
        "chui qua | đi qua bên dưới | lách qua | sống sót qua",
        "to go under | to pass under | to go through | to pass through | to dive | to slip past | to survive",
        "1609710",
        "門をくぐる。","もんをくぐる。",
        "Đi qua cổng.","Pass through the gate."),
    row("潜る","もぐる","N4","v5r|vi",
        "lặn xuống | chui vào | ẩn náu | lẩn trốn | hoạt động bí mật",
        "to dive (into or under water) | to get into | to creep into | to hide oneself | to go underground",
        "1609715",
        "水中に潜る。","すいちゅうにもぐる。",
        "Lặn xuống nước.","Dive underwater."),
    row("色合い","いろあい","N4","n",
        "sắc thái màu | tông màu | màu sắc | sắc thái (ý nghĩa)",
        "colouring | shade (of colour) | hue | tone | tinge | nuance | feel",
        "1357710",
        "温かい色合い。","あたたかいいろあい。",
        "Sắc thái màu ấm áp.","A warm color tone."),
    row("艶","つや","N4","n",
        "độ bóng | sự lấp lánh | sức hấp dẫn | vẻ quyến rũ",
        "gloss | luster | lustre | shine | sheen | polish | charm | appeal",
        "1177680",
        "髪に艶がある。","かみにつやがある。",
        "Tóc bóng sáng.","Hair has luster."),
    row("割り込む","わりこむ","N4","v5m|vt",
        "chen vào | xen vào | cắt vào hàng | ngắt lời",
        "to cut into (a line, conversation, etc.) | to force oneself into | to intrude on | to interrupt",
        "1606870",
        "列に割り込む。","れつにわりこむ。",
        "Chen vào hàng.","Cut into the queue."),
    row("吹き込む","ふきこむ","N4","v5m|vi|vt",
        "thổi vào | truyền cảm hứng | giáo hóa (tư tưởng) | thu âm",
        "to blow in (of wind) | to blow (air) into | to breathe (new life) into | to inspire | to instill | to record (audio)",
        "1370590",
        "元気を吹き込む。","げんきをふきこむ。",
        "Thổi sức sống vào.","Breathe new life into."),
    row("帯","たい","N4","n-suf",
        "vùng | đới (khoa học vật lý)",
        "band (e.g. conduction, valence) | belt (e.g. Van-Allen, asteroid, etc.)",
        "1410420",
        "熱帯地方。","ねったいちほう。",
        "Vùng nhiệt đới.","Tropical region."),
    row("着付け","きつけ","N4","n",
        "mặc kimono | kỹ thuật mặc áo kimono | giúp người khác mặc áo",
        "dressing (esp. in kimono) | fitting | helping someone get dressed",
        "1653870",
        "着付けを習う。","きつけをならう。",
        "Học mặc kimono.","Learn to dress in kimono."),
    row("着替え","きがえ","N4","n|vs|vi",
        "thay quần áo | bộ quần áo thay",
        "changing clothes | change of clothes",
        "1423160",
        "着替えをします。","きがえをします。",
        "Tôi thay quần áo.","I change clothes."),
    row("蕾","つぼみ","N4","n",
        "nụ hoa | chồi hoa | người trẻ đầy triển vọng",
        "(flower) bud | promising young person | budding beauty",
        "1571800",
        "蕾が開く。","つぼみがひらく。",
        "Nụ hoa nở ra.","The bud opens."),
    row("袖","そで","N4","n",
        "tay áo | cánh (sân khấu hoặc bàn) | vạt (bìa sách)",
        "sleeve | wing (of a stage, desk, gate, etc.) | flap (of a dust jacket)",
        "1406000",
        "袖をまくる。","そでをまくる。",
        "Xắn tay áo lên.","Roll up one's sleeves."),
    row("裾","すそ","N4","n",
        "gấu (áo váy) | đuôi áo | mép dưới | chân (núi)",
        "hem | (trouser) cuff | shirttail | bottom (of a kimono) | train (of a dress) | foot (of a mountain)",
        "1373610",
        "裾を踏む。","すそをふむ。",
        "Dẫm lên gấu áo.","Step on the hem."),
    row("雄しべ","おしべ","N4","n",
        "nhị đực | nhị hoa (đực)",
        "stamen",
        "1584890",
        "雄しべが長い。","おしべがながい。",
        "Nhị đực dài.","The stamen is long."),
    row("雌しべ","めしべ","N4","n",
        "nhụy cái | nhụy hoa",
        "pistil",
        "1649830",
        "雌しべに受粉する。","めしべにじゅふんする。",
        "Thụ phấn vào nhụy cái.","Pollinate the pistil."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
