# -*- coding: utf-8 -*-
"""Build N1 ready wave 025 — literary/formal Sino-Japanese nouns (set 25)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-025.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("裕福","ゆうふく","adj-na|n","giàu có | sung túc | dư dả | khá giả","wealthy | rich | affluent | well-off","1541830"),
    ("悠揚","ゆうよう","adj-t|adv-to","ung dung | điềm tĩnh | thong dong | bình thản","self-possessed | calm","1540720"),
    ("故","ゆえ","n|conj","lý do | nguyên cớ | vì | do bởi | cho nên","reason | cause | because of","1267120"),
    ("夢心地","ゆめごこち","n|adj-no","tâm trạng như mơ | lâng lâng | ngây ngất | mơ màng","dreamy state of mind | ecstasy | trance","1529460"),
    ("容喙","ようかい","n|vs|vi","can thiệp | xen vào | chõ mũi | dây vào","interference | meddling","2740940"),
    ("妖怪","ようかい","n","yêu quái | ma quái | yêu ma | quái vật | yokai","ghost | apparition | monster | yokai","1545300"),
    ("要諦","ようてい","n","yếu lĩnh | điểm cốt yếu | bí quyết | tinh túy","most important point | key | secret | essence","1836250"),
    ("夭折","ようせつ","n|vs|vi","yểu mệnh | chết yểu | mất sớm | đoản mệnh","premature death","1565890"),
    ("庸人","ようじん","n","kẻ tầm thường | người bình thường | phàm phu","common man","1545470"),
    ("横恋慕","よこれんぼ","n|vs|vi","yêu trộm (người có đôi) | si mê vụng trộm | tình yêu trái phép","illicit love | coveting another's spouse","1181140"),
    ("余喘","よぜん","n","tàn hơi | sống lay lắt | thoi thóp | bên bờ diệt vong","lingering life | feeble existence | brink of ruin","1544670"),
    ("予断","よだん","n|vs|vt","đoán trước | phán đoán sớm | kết luận vội (予断を許さない)","prediction | prejudgment | foregone conclusion","1543210"),
    ("余沢","よたく","n","ân huệ còn lại | phúc lộc thừa hưởng | lợi ích để lại","blessings | lingering benefits","1544360"),
    ("夜伽","よとぎ","n|vs|vi","trực đêm chăm sóc | ngủ hầu | thức canh đêm (bên người bệnh/quan tài)","attending someone through the night | overnight vigil","1536450"),
    ("羅針盤","らしんばん","n","la bàn | địa bàn | kim chỉ nam","compass","1547570"),
    ("埒","らち","n","ranh giới | giới hạn | hàng rào (埒が明かない: không tiến triển)","bounds | limits | boundary fence","2014290"),
    ("落胤","らくいん","n","con rơi (của quý tộc) | con ngoài giá thú của người quyền quý","nobleman's illegitimate child","1775640"),
    ("爛漫","らんまん","adj-t|adv-to","rực rỡ | nở rộ | tươi thắm | lộng lẫy (天真爛漫)","in full bloom | glorious | luxuriant","1569200"),
    ("吏道","りどう","n","đạo đức quan lại | phẩm hạnh công chức","official ethics","1549740"),
    ("俚諺","りげん","n","tục ngữ | ngạn ngữ | châm ngôn dân gian","proverb | saying","1563390"),
    ("立脚地","りっきゃくち","n","lập trường | chỗ đứng | điểm tựa | cơ sở lập luận","standpoint | position | footing | basis","1838250"),
    ("吝嗇家","りんしょくか","n","kẻ keo kiệt | người bủn xỉn | kẻ hà tiện","miser","1758820"),
    ("流謫","りゅうたく","n","lưu đày | đày ải | biếm trích | trục xuất","exile | deportation | banishment","2590720"),
    ("領袖","りょうしゅう","n","lãnh tụ | thủ lĩnh | người đứng đầu | chủ soái","leader | chief | boss","1644980"),
    ("両雄","りょうゆう","n","lưỡng hùng | hai anh hùng | hai bậc kiệt xuất (両雄並び立たず)","two great men","1554050"),
    ("怜悧","れいり","adj-na|n","lanh lợi | sắc sảo | thông minh | khôn ngoan","clever | sharp | wise | intelligent","1608730"),
    ("霊妙","れいみょう","adj-na|n","kỳ diệu | huyền diệu | linh diệu | thần kỳ","miraculous | wonderful","1616000"),
    ("冷遇","れいぐう","n|vs|vt","đối xử lạnh nhạt | hắt hủi | bạc đãi | ghẻ lạnh","cold reception | inhospitality","1556900"),
    ("歴訪","れきほう","n|vs|vt","viếng thăm lần lượt | công du nhiều nơi | đi thăm hàng loạt","round of calls | tour of visitation","1558300"),
    ("轢死","れきし","n|vs|vi","chết do bị cán | tử vong vì xe cán","death by being run over","1573550"),
    ("連綿","れんめん","adj-t|adv-to","liên miên | không dứt | liền mạch | nối tiếp không ngừng","unbroken | uninterrupted | continuous","1638150"),
    ("廉恥","れんち","n","liêm sỉ | lòng tự trọng | biết hổ thẹn","sense of honour","2510500"),
    ("労苦","ろうく","n|vs|vi","lao khổ | vất vả | nhọc nhằn | cực nhọc","labour | toil | hardship","1560270"),
    ("老成","ろうせい","adj-na|n|vs|vi","lão luyện | chững chạc | già dặn | trưởng thành sớm","mature | experienced | precocious","1618700"),
    ("籠城","ろうじょう","n|vs|vi","cố thủ trong thành | cầm cự | đóng cửa ở lì | bám trụ","holding a castle (in a siege) | holing up","1570330"),
    ("狼藉","ろうぜき","n|adj-t","bừa bộn | lộn xộn | hành hung | càn quấy | bạo loạn","disorder | violence | outrage | riot","1560970"),
    ("老婆心","ろうばしん","n","lòng tốt thái quá | sự quan tâm lo lắng | lòng nhiệt thành (lo xa)","solicitude | (excessive) kindness","1561140"),
    ("朧","おぼろ","adj-na|n","mờ ảo | lờ mờ | mơ hồ | mông lung | (món) ruốc cá","hazy | dim | faint | minced seasoned fish","2587070"),
    ("論難","ろんなん","n|vs|vt","phê phán | chỉ trích | bài bác | công kích","criticism | censure","1738840"),
    ("矮小化","わいしょうか","n|vs","thu nhỏ | làm giảm tầm | tầm thường hóa | xem nhẹ vấn đề","reduction | trivializing (an issue) | playing down","2836585"),
    ("和気","わき","n","bầu không khí hòa thuận | sự hòa hợp | ấm áp (和気あいあい)","harmonious atmosphere","1917290"),
    ("童","わらべ","n","đứa trẻ | trẻ con | trẻ thơ","child","1453920"),
    ("藁","わら","n","rơm | rạ | cọng rơm (藁にもすがる: vớ được cọng rơm)","straw","1562710"),
    ("腕力","わんりょく","n","sức tay | sức mạnh cơ bắp | vũ lực | bạo lực","strength in one's arms | physical force | violence","1562950"),
    ("庵","いおり","n|n-suf","am | thảo am | tịnh thất | nơi ẩn cư","hermitage | retreat","1154280"),
    ("横溢","おういつ","n|vs|vi","tràn trề | dạt dào | ngập tràn | dâng đầy","overflowing | inundation","1180620"),
    ("嗚咽","おえつ","n|vs|vi","nức nở | thổn thức | nghẹn ngào | sụt sùi","sobbing | weeping","1565430"),
    ("往時","おうじ","n","thời xưa | ngày trước | quá khứ | thuở xa xưa","the past | old times | bygone times","1179690"),
    ("謳歌","おうか","n|vs|vt","ca ngợi | tận hưởng | hân hoan tán dương | reo mừng","rejoicing | glorification | enjoyment | singing praises","1572900"),
    ("横死","おうし","n|vs|vi","chết bất đắc kỳ tử | chết thảm | chết oan | bỏ mạng","violent (tragic) death","1180790"),
    ("殴殺","おうさつ","n|vs","đánh chết | đánh đến chết | đả thương tử vong","beating to death","1181400"),
    ("臆面","おくめん","n","vẻ rụt rè | nét e dè | (臆面もなく: không chút ngượng ngùng)","timid face","1182800"),
    ("汚辱","おじょく","n","ô nhục | nhục nhã | sỉ nhục | làm bẽ mặt","disgrace | humiliation | insult","1179020"),
    ("悍ましい","おぞましい","adj-i","ghê tởm | kinh tởm | rùng rợn | gớm ghiếc","appalling | horrifying | hideous | revolting","1001290"),
    ("煽て","おだて","n","sự xúi giục | lời tâng bốc | nịnh nọt | khích bác","instigation | flattery","1391590"),
    ("落ち度","おちど","n","sai sót | lỗi lầm | sơ suất | thiếu sót","mistake | error | fault | oversight","1548610"),
    ("乙","おつ","n|adj-na|exp","loại hai | hạng B | cái sau | lịch lãm | ngộ nghĩnh | lạ kỳ","the second | B (grade) | the latter | stylish | strange","1182940"),
    ("音沙汰","おとさた","n","tin tức | hồi âm | tăm hơi | tin nhắn (音沙汰がない: bặt vô âm tín)","news (from someone) | word | tidings","1183840"),
    ("鬼籍","きせき","n","sổ thiên tào | danh sách người chết | sổ bộ vong (鬼籍に入る: qua đời)","necrology | roster of the dead","1668370"),
    ("快哉","かいさい","n","niềm vui sướng | sự hả hê | reo mừng đắc thắng (快哉を叫ぶ)","joy | exultation","1200030"),
    ("皆既","かいき","n","toàn phần (nhật/nguyệt thực) | sự che khuất hoàn toàn","total eclipse | totality","1202180"),
    ("邂逅","かいこう","n|vs|vi","tao ngộ | cuộc gặp tình cờ | hội ngộ bất ngờ","chance meeting","1573670"),
    ("晦渋","かいじゅう","adj-na|n","tối nghĩa | khó hiểu | mơ hồ | hàm hồ","ambiguous | obscure | equivocal","1615550"),
    ("凱歌","がいか","n","khúc khải hoàn | bài ca chiến thắng | thắng lợi","victory song | victory","1203190"),
    ("乖離","かいり","n|vs|vi","tách rời | xa rời | phân ly | chênh lệch | rời rạc","divergence | alienation | deviation | estrangement","1563010"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
