# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-023.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-023.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("楽しみ","たのしみ","N4","n|adj-na",
        "niềm vui | thú vui | sự thích thú | sở thích | sự mong chờ | điều đáng mong đợi",
        "enjoyment | pleasure | amusement | delight | joy | fun | diversion | hobby | anticipation | looking forward to | something to look forward to",
        "1207250",
        "楽しみにしています。","たのしみにしています。","Tôi đang mong đợi điều đó.","I am looking forward to it."),
    row("頑固","がんこ","N4","adj-na|n",
        "cứng đầu | bướng bỉnh | ngoan cố",
        "stubborn | obstinate | pigheaded",
        "1217680",
        "頑固な人です。","がんこなひとです。","Đó là người cứng đầu.","They are a stubborn person."),
    row("議会","ぎかい","N4","n",
        "quốc hội | nghị viện | hội đồng lập pháp",
        "congress | parliament | diet | legislative assembly",
        "1226040",
        "議会で法案を通します。","ぎかいでほうあんをとおします。","Quốc hội thông qua dự luật.","The parliament passes the bill."),
    row("許可","きょか","N4","n|vs|vt",
        "sự cho phép | giấy phép | ủy quyền | cấp phép",
        "permission | approval | authorization | license",
        "1232880",
        "許可をもらいます。","きょかをもらいます。","Tôi xin phép.","I get permission."),
    row("厳格","げんかく","N4","adj-na|n",
        "nghiêm khắc | khắt khe | cứng nhắc | chặt chẽ",
        "strict | severe | stern | rigid | rigorous | tough",
        "1262570",
        "厳格なルールです。","げんかくなルールです。","Đây là quy tắc nghiêm khắc.","It is a strict rule."),
    row("煮物","にもの","N4","n",
        "món ninh | đồ ăn hầm hoặc om",
        "nimono | food cooked by boiling or stewing",
        "1322630",
        "煮物を作ります。","にものをつくります。","Tôi nấu món hầm.","I make a simmered dish."),
    row("手荷物","てにもつ","N4","n",
        "hành lý xách tay",
        "hand luggage | hand baggage",
        "1327360",
        "手荷物を預けます。","てにもつをあずけます。","Tôi gửi hành lý xách tay.","I check in my hand luggage."),
    row("消化","しょうか","N4","n|vs|vt|vi",
        "tiêu hóa (thức ăn) | tiêu hóa (thông tin) | thấm nhuần | tiêu thụ | hoàn thành (chỉ tiêu)",
        "digestion (of food) | digestion (of information) | assimilation | thorough understanding | consumption | absorption | using up | meeting (e.g. a quota) | completion | losing one's form and turning into something else",
        "1350140",
        "食べ物を消化します。","たべものをしょうかします。","Tôi tiêu hóa thức ăn.","I digest the food."),
    row("消極的","しょうきょくてき","N4","adj-na",
        "tiêu cực | thụ động | thiếu nhiệt tình",
        "negative | passive | half-hearted | unmotivated",
        "1350220",
        "消極的な態度です。","しょうきょくてきなたいどです。","Đó là thái độ thụ động.","It is a passive attitude."),
    row("食物","しょくもつ","N4","n",
        "thức ăn | thực phẩm",
        "food | foodstuff",
        "1358620",
        "食物を用意します。","しょくもつをようだします。","Tôi chuẩn bị thức ăn.","I prepare food."),
    row("深まる","ふかまる","N4","v5r|vi",
        "trở nên sâu sắc hơn | tăng cường | đậm đà hơn",
        "to deepen | to heighten | to intensify",
        "1362660",
        "理解が深まります。","りかいがふかまります。","Sự hiểu biết trở nên sâu sắc hơn.","Understanding deepens."),
    row("親族","しんぞく","N4","n",
        "họ hàng | thân nhân | người thân",
        "relative | relation | kin",
        "1365270",
        "親族が集まります。","しんぞくがあつまります。","Họ hàng tập hợp.","Relatives gather."),
    row("税関","ぜいかん","N4","n",
        "hải quan",
        "customs | customs house",
        "1382090",
        "税関を通ります。","ぜいかんをとおります。","Tôi qua hải quan.","I pass through customs."),
    row("節水","せっすい","N4","n|vs|vi",
        "tiết kiệm nước | bảo tồn nguồn nước",
        "saving water | water conservation | economizing on water",
        "1386260",
        "節水に努めます。","せっすいにつとめます。","Tôi cố gắng tiết kiệm nước.","I try to conserve water."),
    row("祖先","そせん","N4","n",
        "tổ tiên | ông cha",
        "ancestor",
        "1396820",
        "祖先を敬います。","そせんをうやまいます。","Tôi tôn kính tổ tiên.","I honor my ancestors."),
    row("組織","そしき","N4","n|vs|vt|vi",
        "tổ chức | cấu trúc | hệ thống | mô (sinh học) | kết cấu (đá)",
        "organization | organisation | formation | structure | construction | setup | constitution | system (e.g. railroad, transport, party, etc.) | tissue | texture (of a rock) | weave (of a fabric)",
        "1397630",
        "組織を作ります。","そしきをつくります。","Tôi thành lập tổ chức.","I form an organization."),
    row("大臣","だいじん","N4","n",
        "bộ trưởng | đại thần",
        "cabinet minister",
        "1414160",
        "大臣が演説します。","だいじんがえんぜつします。","Bộ trưởng đọc diễn văn.","The minister gives a speech."),
    row("入国","にゅうこく","N4","n|vs|vi",
        "nhập cảnh | vào nước",
        "entry into a country",
        "1466130",
        "入国審査を受けます。","にゅうこくしんさをうけます。","Tôi làm thủ tục nhập cảnh.","I go through immigration."),
    row("片道","かたみち","N4","n|adj-no",
        "một chiều | vé một chiều",
        "one-way (trip) | one-way ticket",
        "1511760",
        "片道切符を買います。","かたみちきっぷをかいます。","Tôi mua vé một chiều.","I buy a one-way ticket."),
    row("免疫","めんえき","N4","n",
        "miễn dịch | tiêm phòng | quen với (điều gì)",
        "immunity | immunization | immunisation | being hardened (to) | being unaffected (by) | being accustomed (to)",
        "1533090",
        "免疫力を高めます。","めんえきりょくをたかめます。","Tôi tăng cường khả năng miễn dịch.","I boost my immunity."),
    row("勇敢","ゆうかん","N4","adj-na|n",
        "dũng cảm | can đảm | anh hùng",
        "brave | courageous | gallant | valiant | heroic",
        "1539730",
        "勇敢に戦います。","ゆうかんにたたかいます。","Tôi chiến đấu dũng cảm.","I fight bravely."),
    row("用心深い","ようじんぶかい","N4","adj-i",
        "cẩn thận | thận trọng | dè dặt | cảnh giác",
        "careful | cautious | wary | watchful | vigilant | prudent",
        "1546330",
        "用心深く行動します。","ようじんぶかくこうどうします。","Tôi hành động cẩn thận.","I act cautiously."),
    row("頼もしい","たのもしい","N4","adj-i",
        "đáng tin cậy | đáng phụ thuộc | an tâm | đầy hứa hẹn",
        "reliable | dependable | trustworthy | reassuring | hopeful | promising",
        "1548380",
        "頼もしい人です。","たのもしいひとです。","Đó là người đáng tin cậy.","They are a dependable person."),
    row("炒め物","いためもの","N4","n",
        "món xào | đồ ăn xào",
        "stir-fry | stir-fried food",
        "1568930",
        "炒め物を作ります。","いためものをつくります。","Tôi nấu món xào.","I make a stir-fry."),
    row("民族","みんぞく","N4","n",
        "dân tộc | sắc tộc | nhân dân",
        "people | race | nation | ethnic group | ethnos",
        "1604740",
        "少数民族を尊重します。","しょうすうみんぞくをそんちょうします。","Tôi tôn trọng dân tộc thiểu số.","I respect ethnic minorities."),
    row("焼き物","やきもの","N4","n",
        "đồ gốm | đồ sứ | đồ nung | món nướng (cá)",
        "pottery | earthenware | ceramics | porcelain | china | yakimono | flame-broiled food (esp. fish) | grilled dish | tempered blade",
        "1605450",
        "焼き物を買います。","やきものをかいます。","Tôi mua đồ gốm.","I buy pottery."),
    row("刑事","でか","N4","n",
        "thám tử | cảnh sát điều tra (cách gọi thông thường)",
        "(police) detective",
        "1008360",
        "刑事が現場に来ます。","でかがげんばにきます。","Thám tử đến hiện trường.","The detective arrives at the scene."),
    row("アドバイス","アドバイス","N4","n|vs|vt",
        "lời khuyên | tư vấn",
        "advice",
        "1017070",
        "アドバイスをもらいます。","アドバイスをもらいます。","Tôi nhận lời khuyên.","I receive advice."),
    row("がん","がん","N4","adv-to|n",
        "thình thịch | đánh mạnh | ký hiệu gian lận (bài)",
        "with a thump | with a thud | with a bang | hard (hit, scold, etc.) | severely | marking (on a card or tile for the purpose of cheating) | card marking | tile marking | alteration",
        "2107080",
        "がんと叩きます。","がんとたたきます。","Tôi gõ thình thịch.","I hit with a thud."),
    row("往復","おうふく","N4","n|vs|vi",
        "khứ hồi | chuyến đi về | vé khứ hồi | trao đổi thư từ | giao du",
        "making a round trip | going and returning | coming and going | round-trip ticket | return ticket | correspondence | exchanging (of letters) | keeping company (with) | socializing | visiting each other",
        "1179760",
        "往復切符を買います。","おうふくきっぷをかいます。","Tôi mua vé khứ hồi.","I buy a round-trip ticket."),
    row("海底","かいてい","N4","n|adj-f",
        "đáy biển | đáy đại dương | dưới biển",
        "bottom of the ocean | seafloor | seabed | undersea | submarine",
        "1201650",
        "海底を探検します。","かいていをたんけんします。","Tôi khám phá đáy biển.","I explore the seafloor."),
    row("寛大","かんだい","N4","adj-na|n",
        "khoan dung | rộng lượng | độ lượng | bao dung",
        "tolerant | generous | lenient | broad-minded | magnanimous",
        "1211960",
        "寛大に許します。","かんだいにゆるします。","Tôi khoan dung tha thứ.","I forgive generously."),
    row("義務","ぎむ","N4","n",
        "nghĩa vụ | bổn phận | trách nhiệm",
        "duty | obligation | responsibility",
        "1225900",
        "義務を果たします。","ぎむをはたします。","Tôi hoàn thành nghĩa vụ.","I fulfill my duty."),
    row("議論","ぎろん","N4","n|vs|vt",
        "tranh luận | thảo luận | tranh cãi | bàn cãi",
        "argument | discussion | dispute | controversy",
        "1226160",
        "議論が白熱します。","ぎろんがはくねつします。","Cuộc tranh luận trở nên sôi nổi.","The discussion heats up."),
    row("強まる","つよまる","N4","v5r|vi",
        "trở nên mạnh hơn | tăng cường | mạnh lên",
        "to get strong | to gain strength",
        "1236130",
        "風が強まります。","かぜがつよまります。","Gió trở nên mạnh hơn.","The wind grows stronger."),
    row("禁止","きんし","N4","n|vs|vt",
        "cấm | lệnh cấm | cấm chỉ",
        "prohibition | inhibition | ban",
        "1241550",
        "喫煙を禁止します。","きつえんをきんしします。","Hút thuốc bị cấm.","Smoking is prohibited."),
    row("経由","けいゆ","N4","n|vs|vi",
        "đi qua | đi ngang qua | thông qua",
        "going through | going via | going by way of",
        "1251670",
        "東京経由で行きます。","とうきょうけいゆでいきます。","Tôi đi qua Tokyo.","I go via Tokyo."),
    row("試着","しちゃく","N4","n|vs|vt",
        "thử quần áo | mặc thử",
        "trying on clothes",
        "1312500",
        "服を試着します。","ふくをしちゃくします。","Tôi thử quần áo.","I try on clothes."),
    row("弱まる","よわまる","N4","v5r|vi",
        "suy yếu | trở nên yếu | lắng xuống",
        "to abate | to weaken | to be emaciated | to be dejected | to be perplexed",
        "1324580",
        "雨が弱まります。","あめがよわまります。","Mưa lắng xuống.","The rain weakens."),
    row("首相","しゅしょう","N4","n",
        "thủ tướng",
        "prime minister | chancellor (Germany, Austria, etc.) | premier",
        "1329300",
        "首相が発表します。","しゅしょうがはっぴょうします。","Thủ tướng công bố.","The prime minister announces."),
    row("出国","しゅっこく","N4","n|vs|vi",
        "xuất cảnh | rời khỏi đất nước",
        "departure from a country | leaving a country",
        "1580020",
        "出国手続きをします。","しゅっこくてつづきをします。","Tôi làm thủ tục xuất cảnh.","I do exit procedures."),
    row("将来","しょうらい","N4","n|adv|vs|vt",
        "tương lai | triển vọng | mang đến | gây ra",
        "future | (future) prospects | bringing (from abroad, another region, etc.) | bringing about | giving rise to | causing | incurring",
        "1347710",
        "将来の夢を語ります。","しょうらいのゆめをかたります。","Tôi kể về ước mơ tương lai.","I talk about my future dreams."),
    row("慎重","しんちょう","N4","adj-na|n",
        "thận trọng | cẩn thận | sáng suốt | chu đáo",
        "careful | cautious | prudent | discreet | deliberate",
        "1361110",
        "慎重に判断します。","しんちょうにはんだんします。","Tôi phán xét thận trọng.","I judge carefully."),
    row("振り向く","ふりむく","N4","v5k|vt|vi",
        "quay đầu lại | nhìn qua vai | quay người lại",
        "to turn one's face | to turn around | to look over one's shoulder",
        "1361190",
        "名前を呼ばれて振り向きます。","なまえをよばれてふりむきます。","Nghe gọi tên, tôi quay đầu lại.","I turn around when my name is called."),
    row("振り返る","ふりかえる","N4","v5r|vi|vt",
        "quay đầu nhìn lại | nhìn qua vai | nhìn lại quá khứ | suy ngẫm | hồi tưởng",
        "to turn one's head | to look over one's shoulder | to turn around | to look back | to think back (on) | to reminisce | to look back (on) | to reflect (on)",
        "1361290",
        "過去を振り返ります。","かこをふりかえります。","Tôi nhìn lại quá khứ.","I look back on the past."),
    row("政党","せいとう","N4","n",
        "đảng phái chính trị | đảng chính trị",
        "political party",
        "1376060",
        "政党を支持します。","せいとうをしじします。","Tôi ủng hộ đảng chính trị.","I support a political party."),
    row("切り取る","きりとる","N4","v5r|vt",
        "cắt ra | cắt đứt | cắt bỏ | tách ra | cắt cụt",
        "to cut off | to excise | to tear off | to cut out | to whittle down | to tear out | to cut down | to amputate",
        "1384260",
        "クーポンを切り取ります。","クーポンをきりとります。","Tôi cắt phiếu giảm giá.","I cut out the coupon."),
    row("節電","せつでん","N4","n|vs|vt|vi",
        "tiết kiệm điện",
        "saving electricity | power saving | reducing electricity usage | reducing power consumption",
        "1386310",
        "節電を心がけます。","せつでんをこころがけます。","Tôi cố gắng tiết kiệm điện.","I try to save electricity."),
    row("大使館","たいしかん","N4","n",
        "đại sứ quán",
        "embassy",
        "1413890",
        "大使館に連絡します。","たいしかんにれんらくします。","Tôi liên lạc với đại sứ quán.","I contact the embassy."),
    row("大胆","だいたん","N4","adj-na|n",
        "táo bạo | mạo hiểm | liều lĩnh",
        "bold | daring | audacious",
        "1414500",
        "大胆な決断をします。","だいたんなけつだんをします。","Tôi đưa ra quyết định táo bạo.","I make a bold decision."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
