# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-020.csv — 28 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-020.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("崩す","くずす","N4","v5s|vt",
        "phá hủy | hạ xuống | làm mất cân bằng | thư giãn tư thế | đổi tiền lẻ | viết theo thể chảy | bật cười",
        "to destroy | to demolish | to pull down | to tear down | to level | to disturb | to put into disorder | to throw off balance | to make shaky | to relax (one's pose) | to make oneself at ease | to break (a bill) | to change | to make change | to write in cursive style | to break into a smile | to lower (a price)",
        "1516260",
        "体調を崩します。","たいちょうをくずします。","Sức khỏe của tôi suy giảm.","My health deteriorates."),
    row("崩れる","くずれる","N4","v1|vi",
        "sụp đổ | vỡ vụn | mất hình dạng | bị xáo trộn | lao dốc (thị trường) | xấu đi (thời tiết)",
        "to collapse | to crumble | to get out of shape | to lose one's shape | to become disorganized | to become untidy | to break down | to be thrown into disarray | to crash (stock market) | to slump | to decline | to turn bad (e.g. weather) | to change for the worse | to deteriorate",
        "1516270",
        "計画が崩れます。","けいかくがくずれます。","Kế hoạch sụp đổ.","The plan falls apart."),
    row("揺らす","ゆらす","N4","v5s|vt",
        "lắc | rung | dao động",
        "to rock | to shake | to swing",
        "1545640",
        "体を揺らします。","からだをゆらします。","Tôi lắc cơ thể.","I rock my body."),
    row("溶かす","とかす","N4","v5s|vt",
        "làm tan chảy | làm hóa lỏng | pha tan | làm cạn kiệt (tiền)",
        "to melt | to liquefy | to thaw | to dissolve (in a liquid) | to bring into solution | to lose (money; through gambling, etc.) | to squander",
        "1546040",
        "砂糖を溶かします。","さとうをとかします。","Tôi pha tan đường.","I dissolve the sugar."),
    row("溶ける","とける","N4","v1|vi",
        "tan chảy | hóa lỏng | tan ra (trong chất lỏng) | cạn dần",
        "to melt | to liquefy | to soften (e.g. through heat) | to thaw | to dissolve (in a liquid) | to be soluble (in) | to be used up (of money or time) | to be wasted | to melt away",
        "1546070",
        "氷が溶けます。","こおりがとけます。","Đá tan chảy.","The ice melts."),
    row("論文","ろんぶん","N4","n",
        "luận văn | tiểu luận | bài viết | bài báo khoa học",
        "thesis | essay | treatise | paper | article",
        "1561840",
        "論文を書きます。","ろんぶんをかきます。","Tôi viết luận văn.","I write a thesis."),
    row("仮説","かせつ","N4","n",
        "giả thuyết | giả định | lý thuyết tạm thời",
        "hypothesis | supposition | assumption | tentative theory",
        "1590320",
        "仮説を立てます。","かせつをたてます。","Tôi đặt ra giả thuyết.","I set up a hypothesis."),
    row("踏切","ふみきり","N4","n",
        "đường giao cắt đường sắt | vạch xuất phát | quyết tâm bước ra",
        "railway crossing | railroad crossing | train crossing | level crossing | starting line | scratch | determination | stepping over the edge of the ring",
        "1602840",
        "踏切を渡ります。","ふみきりをわたります。","Tôi qua đường giao cắt đường sắt.","I cross the railway crossing."),
    row("処方箋","しょほうせん","N4","n",
        "đơn thuốc",
        "prescription",
        "1655680",
        "処方箋をもらいます。","しょほうせんをもらいます。","Tôi nhận đơn thuốc.","I receive a prescription."),
    row("社会問題","しゃかいもんだい","N4","n",
        "vấn đề xã hội",
        "social problem",
        "1658870",
        "社会問題を解決します。","しゃかいもんだいをかいけつします。","Chúng tôi giải quyết vấn đề xã hội.","We solve social problems."),
    row("卒業論文","そつぎょうろんぶん","N4","n",
        "luận văn tốt nghiệp",
        "graduation thesis",
        "1699960",
        "卒業論文を書きます。","そつぎょうろんぶんをかきます。","Tôi viết luận văn tốt nghiệp.","I write my graduation thesis."),
    row("コンテンツ","コンテンツ","N4","n",
        "nội dung",
        "contents | content",
        "1052650",
        "コンテンツを作ります。","コンテンツをつくります。","Tôi tạo nội dung.","I create content."),
    row("印刷","いんさつ","N4","n|vs|vt",
        "in ấn | in",
        "printing",
        "1168190",
        "書類を印刷します。","しょるいをいんさつします。","Tôi in tài liệu.","I print documents."),
    row("回復","かいふく","N4","n|vs|vt|vi",
        "phục hồi | hồi phục | khôi phục | bình phục (bệnh)",
        "restoration | recovery | rehabilitation | return | improvement | recovery (from an illness) | recuperation | convalescence",
        "1199720",
        "健康が回復します。","けんこうがかいふくします。","Sức khỏe phục hồi.","My health recovers."),
    row("記事","きじ","N4","n",
        "bài báo | tin tức | bài viết | báo cáo",
        "article | news story | report | account",
        "1223240",
        "記事を書きます。","きじをかきます。","Tôi viết bài báo.","I write an article."),
    row("記者","きしゃ","N4","n",
        "phóng viên | nhà báo",
        "reporter | journalist",
        "1223250",
        "記者が取材します。","きしゃがとざいします。","Phóng viên phỏng vấn.","The reporter conducts an interview."),
    row("健康診断","けんこうしんだん","N4","n",
        "kiểm tra sức khỏe định kỳ | khám sức khỏe tổng quát",
        "health checkup | (general) medical examination | physical examination",
        "1256210",
        "健康診断を受けます。","けんこうしんだんをうけます。","Tôi khám sức khỏe định kỳ.","I get a health checkup."),
    row("宣伝","せんでん","N4","n|vs|vt",
        "quảng cáo | tuyên truyền | quảng bá",
        "publicity | advertisement | advertising | propaganda",
        "1389730",
        "商品を宣伝します。","しょうひんをせんでんします。","Tôi quảng cáo sản phẩm.","I advertise the product."),
    row("地方","ちほう","N4","n",
        "địa phương | khu vực | vùng | miền quê | nông thôn",
        "district | region | area | locality | the country | countryside | the provinces | rural area | civilian society",
        "1421450",
        "地方に旅行します。","ちほうにりょこうします。","Tôi du lịch miền quê.","I travel to the countryside."),
    row("敷金","しききん","N4","n",
        "tiền đặt cọc | tiền bảo đảm thuê nhà",
        "(security) deposit | caution money",
        "1497040",
        "敷金を払います。","しききんをはらいます。","Tôi trả tiền đặt cọc.","I pay the security deposit."),
    row("報道","ほうどう","N4","n|vs|vt",
        "đưa tin | báo cáo tin tức | tin tức | thông tin | đưa tin truyền thông",
        "report (of news) | reporting | news | information | (media) coverage",
        "1515730",
        "事件を報道します。","じけんをほうどうします。","Tôi đưa tin về sự vụ.","I report on the incident."),
    row("放送","ほうそう","N4","n|vs|vt",
        "phát sóng | truyền hình | chương trình | thông báo",
        "broadcasting | broadcast | program | announcement",
        "1516750",
        "テレビで放送します。","テレビでほうそうします。","Tôi phát sóng trên TV.","I broadcast on TV."),
    row("礼金","れいきん","N4","n",
        "tiền cảm ơn | tiền thưởng | phí | tiền thuê đầu tiên (Nhật Bản)",
        "money (given as thanks) | reward money | fee | recompense | remuneration | honorarium | key money | fee paid for rental rights",
        "1557500",
        "礼金を払います。","れいきんをはらいます。","Tôi trả tiền cảm ơn.","I pay the key money."),
    row("感染症","かんせんしょう","N4","n",
        "bệnh truyền nhiễm | nhiễm trùng",
        "infectious disease | infection",
        "1614180",
        "感染症を予防します。","かんせんしょうをよぼうします。","Tôi phòng ngừa bệnh truyền nhiễm.","I prevent infectious disease."),
    row("一方","ひとかた","N4","n|adj-na",
        "một người | bình thường | phổ thông",
        "one person | ordinary | common",
        "2258660",
        "一方ならぬ努力をします。","ひとかたならぬどりょくをします。","Tôi nỗ lực phi thường.","I make extraordinary effort."),
    row("管理費","かんりひ","N4","n",
        "phí quản lý | chi phí quản lý | chi phí hành chính",
        "administration costs | administrative expenses | management costs",
        "2612860",
        "管理費を払います。","かんりひをはらいます。","Tôi trả phí quản lý.","I pay the management costs."),
    row("傾く","かぶく","N4","v4k",
        "nghiêng (bông lúa chín) | ngả | hành động kỳ lạ | ăn mặc lố bịch | biểu diễn kabuki",
        "to lean (esp. of a ripe ear of rice) | to incline | to slant | to tilt | to behave oddly | to attire oneself strangely | to perform kabuki",
        "2793680",
        "穂が傾きます。","ほがかぶきます。","Bông lúa cúi xuống.","The ear of rice leans down."),
    row("鈍い","のろい","N4","adj-i",
        "chậm chạp | đần độn | lề mề | lờ đờ | nuông chiều (người khác giới)",
        "thickheaded | obtuse | stupid | slow | sluggish | inert | lethargic | indulgent (esp. to the opposite sex) | doting",
        "2838553",
        "反応がのろいです。","はんのうがのろいです。","Phản ứng chậm chạp.","The reaction is sluggish."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
