# -*- coding: utf-8 -*-
"""Build N1 ready wave 019 — literary/formal Sino-Japanese nouns (set 19)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-019.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("専心","せんしん","n|vs|vi","chuyên tâm | toàn tâm toàn ý | dốc lòng | tập trung","undivided attention | concentration","1389800"),
    ("浅薄","せんぱく","adj-na|n","nông cạn | hời hợt | thiển cận | thiếu sâu sắc","shallow | superficial","1390860"),
    ("僭称","せんしょう","n|vs|vt","tiếm xưng | mạo nhận (danh hiệu) | tự xưng càn","pretension | assumption (of a title)","1564080"),
    ("先鞭","せんべん","n","đi tiên phong | mở đường | ra tay trước | đầu têu","initiative | pioneering","1388580"),
    ("善後","ぜんご","n","thu xếp ổn thỏa | xử lý hậu quả | lo liệu chu toàn","careful settlement | dealing with properly","1394370"),
    ("相克","そうこく","n|vs|vi","tương khắc | xung khắc | mâu thuẫn | đối chọi","rivalry | conflict | strife | mutual overcoming","1596360"),
    ("造詣","ぞうけい","n","sự uyên thâm | hiểu biết sâu rộng | tạo nghệ | tinh thông","deep knowledge | attainments | scholarship","1662790"),
    ("象嵌","ぞうがん","n|vs|vt","khảm | cẩn | chạm khảm | nạm","inlay | inlaying | damascening","1662730"),
    ("総帥","そうすい","n","tổng tư lệnh | thủ lĩnh | người đứng đầu (tập đoàn)","commander-in-chief | leader | head","1401650"),
    ("霜害","そうがい","n","thiệt hại do sương giá | hại sương muối","frost damage","1402950"),
    ("俗世","ぞくせ","n","cõi trần | thế tục | trần gian | đời thường","this world | earthly existence | mundane life","1405480"),
    ("速断","そくだん","n|vs|vt","vội kết luận | quyết định hấp tấp | phán đoán vội","rash decision | jumping to a conclusion","1405040"),
    ("忖度","そんたく","n|vs|vt|vi","suy bụng (đoán ý) | nể nang ý người | chiều theo ý ngầm","surmising someone's feelings | deference | consideration","1566740"),
    ("怠業","たいぎょう","n|vs|vi","lãn công | đình công ngầm | làm việc cầm chừng","sabotage | slow-down tactics","1410720"),
    ("泰斗","たいと","n","bậc thái đẩu | uy quyền lớn | bậc kỳ cựu | đại thụ","great authority | eminent person | luminary","1787250"),
    ("大成","たいせい","n|vs|vt|vi","đại thành | hoàn thành sự nghiệp | thành công lớn | tập đại thành","completion | accomplishment | attaining greatness","1785700"),
    ("大義","たいぎ","n","đại nghĩa | chính nghĩa | lẽ phải lớn lao","great cause | moral law | justice","1786870"),
    ("託宣","たくせん","n|vs","lời sấm truyền | lời thần phán | thiên khải","oracle | revelation | divine message","1415910"),
    ("打開策","だかいさく","n","giải pháp đột phá | cách phá thế bế tắc | kế tháo gỡ","breakthrough solution | plan to break a deadlock","2133720"),
    ("脱稿","だっこう","n|vs|vt|vi","viết xong | hoàn thành bản thảo | đặt bút kết thúc","finishing writing | completion of a manuscript","1616670"),
    ("他言","たごん","n|vs|vt","tiết lộ | nói cho người khác | để lộ (bí mật)","telling others | divulging (a secret)","1581390"),
    ("端役","はやく","n|adj-no","vai phụ | vai nhỏ | vai quần chúng","minor role | small part","1418970"),
    ("胆略","たんりゃく","n","gan dạ và mưu lược | dũng cảm tháo vát | trí dũng","courage and resourcefulness","1804750"),
    ("知遇","ちぐう","n|vs|vi","sự tri ngộ | được trọng dụng | tình tri kỷ | hậu đãi","favour | warm friendship | recognition","1420520"),
    ("寵愛","ちょうあい","n|vs|vt","sủng ái | yêu chiều | sủng hạnh | cưng chiều","favor | affection | dotage","1699940"),
    ("重畳","ちょうじょう","n|vs|vi|adj-t","chồng chất | tầng tầng lớp lớp | tuyệt vời | mãn nguyện","piling up | superimposition | excellent | splendid","1336340"),
    ("直情","ちょくじょう","n","tính bộc trực | thẳng thắn | nóng nảy bốc đồng","frankness | impulsiveness","1431050"),
    ("追従","ついしょう","n|vs|vi","nịnh hót | bợ đỡ | xu nịnh | tâng bốc","flattery | sycophancy | adulation","1661870"),
    ("痛切","つうせつ","adj-na|n","thấm thía | sâu sắc | day dứt | tha thiết","keen | acute | heartfelt","1432790"),
    ("定石","じょうせき","n","nước đi chuẩn (cờ vây) | bài bản | quy chuẩn | lối mòn","standard practice | established tactic | joseki","1435690"),
    ("泥酔","でいすい","n|vs|vi","say bí tỉ | say mèm | say khướt | say quắc cần câu","being dead drunk | drunken stupor","1436980"),
    ("徹宵","てっしょう","n|vs|vi","thức trắng đêm | suốt đêm không ngủ | thâu đêm","all night | without sleep","1437660"),
    ("天賦","てんぷ","adj-no","thiên phú | bẩm sinh | trời cho | tự nhiên có","natural (talent) | innate | inborn","1440220"),
    ("韜晦","とうかい","n|vs|vt|vi","giấu tài | che giấu ý đồ | ẩn danh | náu mình","concealing one's talents/intentions | self-effacement","1574240"),
    ("陶冶","とうや","n|vs","hun đúc | rèn luyện | bồi dưỡng | đào tạo (nhân cách)","training | education | cultivation","1655600"),
    ("洞察力","どうさつりょく","n","khả năng thấu hiểu | óc nhận thức sắc bén | tầm nhìn thấu đáo","insight | discernment | perspicacity | acumen","1687840"),
    ("怒気","どき","n","vẻ giận dữ | nộ khí | cơn thịnh nộ | sắc giận","anger | wrath","1445700"),
    ("篤志","とくし","n","lòng hảo tâm | tấm lòng từ thiện | nhiệt tâm thiện nguyện","charity | benevolence | charitable spirit","1717300"),
    ("咄嗟","とっさ","n|adj-no","khoảnh khắc | trong tích tắc | nhất thời | bất chợt","moment | instant","1565170"),
    ("徒手","としゅ","n","tay không | tay trắng | không có gì | không vũ khí","being empty-handed | bare hands | being penniless","1444460"),
    ("頓挫","とんざ","n|vs|vi","đình trệ | bế tắc | đổ bể giữa chừng | sụp đổ","setback | deadlock | standstill | miscarriage","1713330"),
    ("内憂","ないゆう","n","nội ưu | mối lo trong nước | lục đục nội bộ","internal troubles | domestic discord","1459370"),
    ("名状","めいじょう","n|vs|vt","diễn tả | mô tả | hình dung bằng lời","description | describing | depicting","1531660"),
    ("納涼","のうりょう","n|vs|vi","hóng mát | tránh nóng hưởng gió mát (bên sông)","escaping the heat to enjoy the cool breeze","1792210"),
    ("能弁","のうべん","adj-na|n","tài hùng biện | ăn nói lưu loát | khéo ăn nói","eloquence | oratory","1600250"),
    ("覇気","はき","n","khí phách | hoài bão | chí tiến thủ | tham vọng","spirit | drive | ambition | aspiration","1470940"),
    ("卑近","ひきん","adj-na|n","gần gũi | thông thường | giản dị dễ hiểu | bình dân","common | simple | familiar","1482720"),
    ("悲憤","ひふん","n|vs|vi","bi phẫn | căm phẫn đau buồn | uất hận","indignation | resentment","1626680"),
    ("皮相","ひそう","n|adj-na|adj-no","hời hợt | bề ngoài | phiến diện | nông cạn","surface | superficial | shallow","1483890"),
    ("標的","ひょうてき","n","mục tiêu | đích nhắm | bia ngắm | đối tượng nhắm tới","target","1488810"),
    ("不羈","ふき","n","tự do phóng khoáng | không bị ràng buộc | độc lập | bất kham","freedom | liberty | independence","1602470"),
    ("不偏","ふへん","adj-na|adj-no|n","không thiên vị | công bằng | trung lập | vô tư","impartiality | neutrality | fairness","1494820"),
    ("不憫","ふびん","adj-na|n","đáng thương | tội nghiệp | đáng ái ngại | thảm thương","poor | pitiful | pitiable","1602810"),
    ("払底","ふってい","n|vs|vi","khan hiếm | thiếu hụt | cạn kiệt | hết sạch","shortage | scarcity | dearth","1501650"),
    ("辟易","へきえき","vs|vi|n","ngán ngẩm | phát chán | bó tay | nao núng | chùn bước","being fed up | being bored | being stumped | shrinking back","1573590"),
    ("偏狭","へんきょう","adj-na|n","hẹp hòi | thiển cận | hẹp lượng | thiếu bao dung","narrow-mindedness | intolerance | narrowness","1510370"),
    ("変節","へんせつ","n|vs|vi","phản bội | trở mặt | thay lòng đổi dạ | bội ước","betrayal | defection | treachery | apostasy","1511250"),
    ("放縦","ほうじゅう","adj-na|n","buông thả | phóng túng | bừa bãi | vô độ","self-indulgence | looseness | dissolution","1516700"),
    ("泡沫","うたかた","n|adj-no","bọt nước | phù du | thoáng qua | hư ảo phù phiếm","bubble on water | ephemeral | transient","1584110"),
    ("朴訥","ぼくとつ","adj-na","mộc mạc | chất phác | thật thà vụng về | hồn nhiên giản dị","unsophisticated | ruggedly honest | artless | naive","1521760"),
    ("発起","ほっき","n|vs|vt|vi","khởi xướng | đề xướng | phát tâm | nảy ra ý định","originating | initiating | proposing | spiritual awakening","1679420"),
    ("没我","ぼつが","n","quên mình | vô ngã | xả thân | quên bản thân","selflessness","1622040"),
    ("翻意","ほんい","n|vs|vi","thay đổi ý định | đổi ý | nghĩ lại","changing one's mind","1523370"),
    ("末席","まっせき","n","chỗ cuối bàn | vị trí thấp nhất | hạng bét | cuối lớp","lowest seat | foot of the table | lowest rank","1584390"),
    ("満腔","まんこう","adj-no|n","hết lòng | toàn tâm | chân thành | tận đáy lòng","heartfelt | sincere | wholehearted","1812570"),
    ("無下","むげ","adj-na|n","phũ phàng | hoàn toàn (cự tuyệt) | thẳng thừng | lạnh lùng dứt khoát","flatly | curtly | without consideration","2863328"),
    ("無尽","むじん","n|adj-na","vô tận | không cùng | hội tương trợ (góp vốn)","inexhaustibility | mutual financing association","1642300"),
    ("妄動","もうどう","n|vs|vi","hành động hấp tấp | manh động | làm liều | bồng bột","rash act | reckless act","1584740"),
    ("盲目","もうもく","n|adj-no|adj-na","mù lòa | mù quáng | (tình yêu) mù quáng | thiếu suy xét","blindness | blind (love, faith) | reckless","1534340"),
    ("門戸","もんこ","n","cửa nẻo | cánh cửa | cửa ngõ (門戸開放: mở cửa)","door | gateway","1536180"),
    ("夜陰","やいん","n","đêm khuya | bóng tối ban đêm | màn đêm","shades of evening | dead of night","1536410"),
    ("悠久","ゆうきゅう","adj-no|adj-na|n","vĩnh cửu | trường tồn | lâu đời | thiên thu","eternal | everlasting | perpetual","1540690"),
    ("湧出","ゆうしゅつ","n|vs|vi","phun trào | tuôn ra | vọt lên | dâng trào","gushing out | welling up | springing up","1652520"),
    ("雄飛","ゆうひ","n|vs|vi","vẫy vùng | tung hoành | dấn thân lập nghiệp | bay cao","launching out (career) | embarking with ambition","1620110"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
