# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-010.csv — 50 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-010.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("火","ひ","N4","n",
        "lửa | ngọn lửa",
        "fire | flame | blaze",
        "1193610",
        "火が燃えます。","ひがもえます。","Lửa cháy.","The fire burns."),
    row("花びら","はなびら","N4","n",
        "cánh hoa",
        "petal",
        "1194520",
        "花びらが散ります。","はなびらがちります。","Cánh hoa rụng.","The petals fall."),
    row("課題","かだい","N4","n",
        "chủ đề | đề tài | vấn đề | bài tập về nhà | bài tập | vấn đề (cần giải quyết) | nhiệm vụ | thử thách | câu hỏi",
        "subject | theme | issue | matter | homework | assignment | problem (that needs solving) | task | challenge | question",
        "1195820",
        "課題を提出します。","かだいをていしゅつします。","Tôi nộp bài tập.","I submit the assignment."),
    row("回答","かいとう","N4","n|vs|vt|vi",
        "trả lời | câu trả lời",
        "reply | answer",
        "1199680",
        "質問に回答します。","しつもんにかいとうします。","Tôi trả lời câu hỏi.","I answer the question."),
    row("願う","ねがう","N4","v5u|vt|aux-v",
        "mong muốn | ước | hy vọng | xin cầu | yêu cầu | van xin | cầu nguyện | nhờ ai đó làm gì cho mình",
        "to desire | to wish | to hope | to beg | to request | to implore | to pray | to have something done for oneself",
        "1217950",
        "成功を願います。","せいこうをねがいます。","Tôi chúc mừng thành công.","I wish for success."),
    row("企画","きかく","N4","n|vs|vt",
        "lập kế hoạch | kế hoạch | dự án | sắp xếp",
        "planning | plan | project | arrangements",
        "1218150",
        "新しい企画を立てます。","あたらしいきかくをたてます。","Tôi lập kế hoạch mới.","I make a new plan."),
    row("基本的に","きほんてきに","N4","adv",
        "về cơ bản | về mặt căn bản",
        "basically | fundamentally",
        "1219270",
        "基本的に賛成です。","きほんてきにさんせいです。","Về cơ bản tôi đồng ý.","I basically agree."),
    row("期間","きかん","N4","n",
        "khoảng thời gian | thời hạn | giai đoạn",
        "period | term | interval",
        "1220550",
        "期間は3ヶ月です。","きかんはさんかげつです。","Thời hạn là 3 tháng.","The period is 3 months."),
    row("期限","きげん","N4","n",
        "thời hạn | giới hạn thời gian | hạn chót | ngày cắt",
        "term | period | time frame | time limit | deadline | cutoff (date)",
        "1220560",
        "期限に間に合います。","きげんにまにあいます。","Tôi kịp hạn chót.","I make it in time for the deadline."),
    row("気にする","きにする","N4","exp|vs-i",
        "để ý (với sắc thái tiêu cực) | quan tâm đến | lo lắng | chú ý quá mức đến",
        "to mind (negative nuance) | to care about | to worry | to pay undue attention to (something)",
        "1221680",
        "気にしないでください。","きにしないでください。","Đừng để ý.","Please don't mind it."),
    row("気温","きおん","N4","n",
        "nhiệt độ (không khí) | nhiệt độ",
        "(air) temperature",
        "1221950",
        "気温が下がります。","きおんがさがります。","Nhiệt độ giảm.","The temperature drops."),
    row("気候","きこう","N4","n",
        "khí hậu",
        "climate",
        "1222170",
        "気候が変わります。","きこうがかわります。","Khí hậu thay đổi.","The climate changes."),
    row("祈る","いのる","N4","v5r|vt",
        "cầu nguyện | đọc kinh | cầu bình an trước bữa ăn | ước | hy vọng",
        "to pray | to say a prayer | to say grace | to wish | to hope",
        "1222770",
        "神に祈ります。","かみにいのります。","Tôi cầu nguyện với thần.","I pray to god."),
    row("規則","きそく","N4","n",
        "quy tắc | quy định",
        "rule | regulation",
        "1223021",
        "規則を守ります。","きそくをまもります。","Tôi tuân thủ quy tắc.","I follow the rules."),
    row("検査","けんさ","N4","n|vs|vt",
        "kiểm tra (ví dụ hải quan, nhà máy) | khám | kiểm tra | kiểm soát | chụp quét (ví dụ MRI, PET) | kiểm toán",
        "inspection (e.g. customs, factory) | examination | test | check | scan (e.g. MRI, PET) | audit",
        "1257890",
        "血液検査をします。","けつえきけんさをします。","Tôi xét nghiệm máu.","I have a blood test."),
    row("賢い","かしこい","N4","adj-i",
        "thông minh | khôn ngoan | sáng dạ | ngoan ngoãn (đặc biệt trẻ em và thú cưng) | vâng lời",
        "wise | clever | smart | well-behaved (esp. children and pets) | obedient | good",
        "1260260",
        "賢い子供です。","かしこいこどもです。","Là đứa trẻ thông minh.","A clever child."),
    row("市民","しみん","N4","n",
        "công dân (của một quốc gia) | dân | cư dân (của một thành phố) | người ở | thị dân | tầng lớp trung lưu",
        "citizen (of a country) | citizenry | citizen (of a city) | resident | inhabitant | townspeople | bourgeoisie | middle class",
        "1308690",
        "市民の声を聞きます。","しみんのこえをきます。","Tôi lắng nghe tiếng nói của công dân.","I listen to the voice of the citizens."),
    row("糸","いと","N4","n|n-suf",
        "chỉ | sợi chỉ | dây",
        "thread | yarn | string",
        "1311450",
        "糸を使います。","いとをつかいます。","Tôi dùng chỉ.","I use thread."),
    row("試す","ためす","N4","v5s|vt",
        "thử | thử nghiệm | kiểm tra | đưa vào thử thách",
        "to try (out) | to have a try (at) | to test | to put to the test",
        "1312260",
        "新しい方法を試します。","あたらしいほうほうをためします。","Tôi thử phương pháp mới.","I try a new method."),
    row("主に","おもに","N4","adv",
        "chủ yếu | chính yếu | phần lớn | hầu hết",
        "mainly | primarily | mostly | largely | chiefly",
        "1324990",
        "主に野菜を食べます。","おもにやさいをたべます。","Tôi chủ yếu ăn rau.","I mainly eat vegetables."),
    row("蹴る","ける","N4","v5r|vt",
        "đá | từ chối | khước từ | dậm chân (xuống đất) | ấn chân vào",
        "to kick | to refuse | to reject | to stamp (on the ground) | to firmly press one's feet (against something)",
        "1333400",
        "ボールを蹴ります。","ボールをけります。","Tôi đá bóng.","I kick the ball."),
    row("醜い","みにくい","N4","adj-i",
        "xấu xí | không hấp dẫn | trông xấu | mất thẩm mỹ | bê bối | nhục nhã | mất danh dự",
        "ugly | unattractive | bad-looking | unsightly | unseemly | disgraceful | shameful | dishonorable",
        "1333810",
        "醜い行為です。","みにくいこういです。","Là hành vi bê bối.","It is a disgraceful act."),
    row("奨学金","しょうがくきん","N4","n",
        "học bổng | phụ cấp | trợ cấp học bổng | vay sinh viên",
        "scholarship | stipend | bursary | grant-in-aid | student loan",
        "1347530",
        "奨学金を受けます。","しょうがくきんをうけます。","Tôi nhận học bổng.","I receive a scholarship."),
    row("消毒","しょうどく","N4","n|vs|vt",
        "khử trùng | tiệt khuẩn | vô trùng hóa",
        "disinfection | sterilization | sterilisation",
        "1350270",
        "消毒をします。","しょうどくをします。","Tôi khử trùng.","I disinfect."),
    row("消費者","しょうひしゃ","N4","n",
        "người tiêu dùng (sản phẩm, dịch vụ) | khách hàng | người dùng cuối | người mua | người tiêu thụ (trong chuỗi thức ăn)",
        "consumer (of a product, service, etc.) | customer | (end) user | buyer | consumer (in a food chain)",
        "1350300",
        "消費者を守ります。","しょうひしゃをまもります。","Tôi bảo vệ người tiêu dùng.","I protect the consumer."),
    row("症状","しょうじょう","N4","n",
        "triệu chứng | tình trạng (của bệnh nhân)",
        "symptoms | condition (of a patient)",
        "1351030",
        "症状を伝えます。","しょうじょうをつたえます。","Tôi mô tả triệu chứng.","I describe the symptoms."),
    row("親友","しんゆう","N4","n",
        "bạn thân | bạn thân thiết | bạn cật ruột",
        "close friend | bosom friend | buddy | crony | chum",
        "1365410",
        "親友と話します。","しんゆうとはなします。","Tôi nói chuyện với bạn thân.","I talk with my close friend."),
    row("診る","みる","N4","v1|vt",
        "khám bệnh | kiểm tra y tế | kiểm tra (mạch của bệnh nhân)",
        "to examine (medically) | to have a look at | to check (a patient's pulse)",
        "1365450",
        "患者を診ます。","かんじゃをみます。","Tôi khám bệnh nhân.","I examine the patient."),
    row("進歩","しんぽ","N4","n|vs|vi",
        "tiến bộ | phát triển | cải tiến",
        "progress | advance | improvement | development",
        "1366190",
        "技術が進歩します。","ぎじゅつがしんぽします。","Công nghệ tiến bộ.","Technology advances."),
    row("針","はり","N4","n|ctr|n-suf",
        "kim | ghim | móc câu | ngòi | gai | kim đồng hồ | con trỏ | ghim bấm | đường may | ác ý | đếm mũi khâu",
        "needle | pin | hook | stinger | thorn | hand (e.g. clock, etc.) | pointer | staple (for a stapler) | needlework | sewing | malice | counter for stitches",
        "1366210",
        "針で縫います。","はりでぬいます。","Tôi may bằng kim.","I sew with a needle."),
    row("人工知能","じんこうちのう","N4","n",
        "trí tuệ nhân tạo | AI",
        "artificial intelligence | AI",
        "1367560",
        "人工知能を使います。","じんこうちのうをつかいます。","Tôi sử dụng trí tuệ nhân tạo.","I use artificial intelligence."),
    row("生産者","せいさんしゃ","N4","n",
        "nhà sản xuất | người trồng trọt | nhà chế tạo | nhà sản xuất (trong chuỗi thức ăn)",
        "producer | grower | maker | manufacturer | producer (in a food chain)",
        "1379020",
        "生産者を支援します。","せいさんしゃをしえんします。","Tôi hỗ trợ nhà sản xuất.","I support the producer."),
    row("生物","なまもの","N4","n",
        "thực phẩm tươi sống | đồ ăn tươi | hàng dễ hỏng",
        "raw food | perishables",
        "1379440",
        "生物は冷蔵します。","なまものはれいぞうします。","Thực phẩm tươi sống cần bảo quản lạnh.","Raw food is refrigerated."),
    row("惜しい","おしい","N4","adj-i",
        "đáng tiếc | đáng thất vọng | không may | quý giá | đáng trân trọng | suýt (nhưng không đủ)",
        "regrettable | disappointing | unfortunate | precious | dear | valuable | almost (but not quite) | close (but no cigar)",
        "1382280",
        "惜しいミスです。","おしいミスです。","Là lỗi đáng tiếc.","It is a regrettable mistake."),
    row("退院","たいいん","N4","n|vs|vi",
        "xuất viện | ra viện",
        "leaving hospital | discharge from hospital",
        "1411300",
        "明日退院します。","あしたたいいんします。","Ngày mai tôi xuất viện.","I will be discharged from the hospital tomorrow."),
    row("退学","たいがく","N4","n|vs|vi",
        "bỏ học | rút khỏi trường | bị đuổi học | rời trường (đại học, v.v.) sau khi hoàn thành khóa học",
        "dropping out of school | withdrawal from school | expulsion from school | dismissal | leaving school after completing a course",
        "1411340",
        "大学を退学しました。","だいがくをたいがくしました。","Tôi đã bỏ đại học.","I dropped out of university."),
    row("投げる","なげる","N4","v1|vt",
        "ném | liệng | tung | thả | từ bỏ | bỏ cuộc | ném đi | bắn (ánh nhìn, bóng tối, nghi ngờ)",
        "to throw | to hurl | to fling | to toss | to cast | to give up | to abandon | to throw away | to cast (a glance, shadow, doubt, etc.)",
        "1447000",
        "ボールを投げます。","ボールをなげます。","Tôi ném bóng.","I throw the ball."),
    row("年金","ねんきん","N4","n|adj-no",
        "niên kim | lương hưu | tiền hưu trí",
        "annuity | pension",
        "1468540",
        "年金を受け取ります。","ねんきんをうけとります。","Tôi nhận lương hưu.","I receive a pension."),
    row("俳優","はいゆう","N4","n",
        "diễn viên | người biểu diễn",
        "actor | actress | player | performer",
        "1471970",
        "有名な俳優です。","ゆうめいなはいゆうです。","Là diễn viên nổi tiếng.","A famous actor."),
    row("背","せい","N4","n",
        "chiều cao | tầm vóc",
        "height | stature",
        "1472650",
        "背が高いです。","せいがたかいです。","Chiều cao cao.","I am tall."),
    row("倍","ばい","N4","n|adj-no|ctr",
        "gấp đôi | hai lần (nhiều hơn) | lần (nhiều như vậy) | bội số",
        "double | twice (as much) | times (as much) | -fold",
        "1473230",
        "二倍になります。","にばいになります。","Trở thành gấp đôi.","It becomes double."),
    row("発達","はったつ","N4","n|vs|vi",
        "phát triển | tăng trưởng | tiến bộ | mở rộng (của bão, vùng áp thấp)",
        "development | growth | progress | advancement | expansion (of a typhoon, low-pressure area, etc.)",
        "1477680",
        "子供が発達します。","こどもがはったつします。","Đứa trẻ phát triển.","The child develops."),
    row("発展","はってん","N4","n|vs|vi",
        "phát triển | tăng trưởng | mở rộng | phát triển (của tình huống, câu chuyện) | tiến bộ | diễn biến",
        "development | growth | expansion | extension | flourishing | development (of a situation, story, etc.) | advancement | progression | unfolding",
        "1477720",
        "都市が発展します。","としがはってんします。","Thành phố phát triển.","The city develops."),
    row("発表","はっぴょう","N4","n|vs|vt",
        "thông báo | công bố | trình bày | tuyên bố | công khai hóa | đưa tin | bày tỏ (ý kiến) | phát hành | giới thiệu",
        "announcement | publication | presenting | statement | communique | making known | breaking (news story) | expressing (one's opinion) | releasing | unveiling",
        "1477840",
        "結果を発表します。","けっかをはっぴょうします。","Tôi công bố kết quả.","I announce the results."),
    row("塀","へい","N4","n",
        "tường | hàng rào | bờ tường",
        "wall | fence",
        "1506870",
        "高い塀があります。","たかいへいがあります。","Có bức tường cao.","There is a high wall."),
    row("法律","ほうりつ","N4","n",
        "luật pháp | luật | đạo luật",
        "law | legislation | act",
        "1517480",
        "法律を守ります。","ほうりつをまもります。","Tôi tuân thủ luật pháp.","I obey the law."),
    row("優勝","ゆうしょう","N4","n|vs|vi",
        "chiến thắng toàn diện | chức vô địch | giành danh hiệu",
        "overall victory | championship | winning the title",
        "1539280",
        "試合に優勝します。","しあいにゆうしょうします。","Tôi giành chức vô địch trong trận đấu.","I win the championship."),
    row("要するに","ようするに","N4","exp|adv",
        "tóm lại | nói gọn lại | để tóm tắt | nói đơn giản | rút ngắn câu chuyện",
        "in short | in a word | to sum up | to put it simply | to make a long story short | after all",
        "1546620",
        "要するに、無理です。","ようするに、むりです。","Tóm lại, là không thể.","In short, it's impossible."),
    row("囁く","ささやく","N4","v5k|vi",
        "thì thầm | thầm thì | lan truyền tin đồn",
        "to whisper | to murmur | to rumor | to rumour",
        "1565670",
        "耳に囁きます。","みみにささやきます。","Tôi thì thầm vào tai.","I whisper in the ear."),
    row("曖昧","あいまい","N4","adj-na|n",
        "mơ hồ | không rõ ràng | mập mờ | đáng ngờ | không có tiếng tốt | không rõ nét",
        "vague | ambiguous | unclear | shady | disreputable | fuzzy",
        "1567920",
        "曖昧な返事です。","あいまいなへんじです。","Là câu trả lời mơ hồ.","It is a vague reply."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
