# -*- coding: utf-8 -*-
"""Build N1 ready wave 084 — advanced katakana loanwords (set 84)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-084.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("アイソレーション","アイソレーション","n","sự cô lập | sự cách ly | sự tách biệt","isolation","1014150"),
    ("アウトプット","アウトプット","n|vs|vt","đầu ra | kết quả xuất ra | sản lượng | dữ liệu xuất","output","1014850"),
    ("アジャスト","アジャスト","n|vs","sự điều chỉnh | sự thích ứng | hiệu chỉnh","adjustment","1015910"),
    ("アスペクト","アスペクト","n","khía cạnh | phương diện | góc độ","aspect","1016160"),
    ("アトラクティブ","アトラクティブ","adj-na","hấp dẫn | lôi cuốn | thu hút | quyến rũ","attractive","1016900"),
    ("アブストラクト","アブストラクト","adj-na|n","trừu tượng | tranh trừu tượng | bản tóm tắt | phần lược trích","abstract","1018130"),
    ("アライメント","アライメント","n","sự căn chỉnh | sự thẳng hàng | sự đồng bộ định hướng","alignment","2430650"),
    ("アンビエント","アンビエント","n","môi trường xung quanh | nhạc nền không gian | ambient","ambient","2281850"),
    ("イニシャル","イニシャル","n|adj-no","chữ cái đầu | viết tắt tên | chữ đầu | ban đầu","initial","1021570"),
    ("インクルージョン","インクルージョン","n","sự hòa nhập | sự bao hàm | tính bao trùm","inclusion","2829829"),
    ("インスタント","インスタント","adj-na|n","ăn liền | tức thì | ngay lập tức | pha sẵn","instant","1022550"),
    ("インスティテューション","インスティテューション","n","thể chế | định chế | tổ chức | cơ quan","institution","1022570"),
    ("インディビジュアル","インディビジュアル","n","cá nhân | cá thể | riêng lẻ","individual","1023710"),
    ("インフルエンス","インフルエンス","n","sự ảnh hưởng | tầm ảnh hưởng | sức tác động","influence","1024420"),
    ("エクセレント","エクセレント","adj-na","xuất sắc | tuyệt vời | ưu tú","excellent","1028160"),
    ("エッジ","エッジ","n","cạnh | rìa | nét sắc sảo | lưỡi (dao)","edge","1029050"),
    ("エナジー","エナジー","n","năng lượng | sinh lực | nguồn năng lượng","energy","1029350"),
    ("エンカレッジ","エンカレッジ","n","sự khích lệ | sự động viên | tạo động lực","encouragement","2841161"),
    ("オーバーホール","オーバーホール","n|vs|vt","sự đại tu | kiểm tra toàn diện | tu sửa toàn bộ","overhaul","1032760"),
    ("オブジェクション","オブジェクション","n","sự phản đối | lời phản bác | ý kiến trái chiều","objection","1034910"),
    ("オペラント","オペラント","n","hành vi tạo tác | điều kiện hóa thao tác (tâm lý học)","operant","2211690"),
    ("カウンセラー","カウンセラー","n","chuyên viên tư vấn | nhà tham vấn | cố vấn tâm lý","counselor","1036900"),
    ("カジュアル","カジュアル","adj-na","giản dị | thường nhật | thoải mái | không trang trọng","casual","1037200"),
    ("カスタマー","カスタマー","n","khách hàng | người tiêu dùng","customer","2195900"),
    ("カルテル","カルテル","n","các-ten | liên minh độc quyền | thỏa thuận ấn định giá","cartel","1039030"),
    ("ガバメント","ガバメント","n","chính phủ | bộ máy nhà nước | chính quyền","government","2469200"),
    ("キャパシティビルディング","キャパシティビルディング","n","nâng cao năng lực | xây dựng năng lực | bồi dưỡng năng lực","capacity building","2647410"),
    ("グラビティ","グラビティ","n","trọng lực | lực hấp dẫn | sức hút trái đất","gravity","2805520"),
    ("グリーフ","グリーフ","n","nỗi đau buồn | sự tang thương | đau khổ mất mát","grief","2826161"),
    ("グローバリゼーション","グローバリゼーション","n","sự toàn cầu hóa | quá trình toàn cầu hóa","globalization","2010300"),
    ("コアコンピタンス","コアコンピタンス","n","năng lực cốt lõi | thế mạnh chủ chốt | năng lực lõi","core competence","2829681"),
    ("コーション","コーション","n","sự cảnh báo | lời cảnh giác | thận trọng","caution","1048810"),
    ("コミュニタリアニズム","コミュニタリアニズム","n","chủ nghĩa cộng đồng | tư tưởng coi trọng cộng đồng","communitarianism","2844426"),
    ("コラボ","コラボ","n|vs|vi","sự hợp tác | cộng tác | bắt tay làm chung","collaboration | collab","2058610"),
    ("コンサルタント","コンサルタント","n","chuyên gia tư vấn | cố vấn | nhà tư vấn","consultant","1052050"),
    ("コンソール","コンソール","n","bảng điều khiển | máy chơi game | giao diện điều khiển","console","1052380"),
    ("コンバージョン","コンバージョン","n","sự chuyển đổi | tỷ lệ chuyển đổi | sự cải đạo","conversion","1052920"),
    ("サブカル","サブカル","n","văn hóa ngách | tiểu văn hóa | văn hóa nhóm nhỏ","subculture","2811830"),
    ("シェアリング","シェアリング","n","sự chia sẻ | kinh tế chia sẻ | dùng chung","sharing","1059960"),
    ("ジェントル","ジェントル","adj-na","nhẹ nhàng | dịu dàng | lịch thiệp | hòa nhã","gentle","2702810"),
    ("ジャッジメント","ジャッジメント","n","sự phán xét | quyết định | đánh giá | phán quyết","judgement","1065470"),
    ("ジャンク","ジャンク","n","đồ bỏ đi | rác | thứ vô giá trị | đồ phế thải","junk","1065730"),
    ("シンプリシティー","シンプリシティー","n","sự đơn giản | tính giản dị | sự mộc mạc","simplicity","1063850"),
    ("スタンプ","スタンプ","n","con dấu | tem | nhãn dán (ứng dụng nhắn tin) | dấu đóng","stamp | sticker","1070030"),
    ("ステークホルダー","ステークホルダー","n","các bên liên quan | bên có quyền lợi | đối tượng hữu quan","stakeholder","2123270"),
    ("ストイシズム","ストイシズム","n","chủ nghĩa khắc kỷ | tinh thần khổ hạnh | thuyết Stoic","stoicism","2497810"),
    ("スピリチュアル","スピリチュアル","adj-na|n","thuộc tâm linh | mang tính tinh thần | thiêng liêng","spiritual","1072450"),
    ("スプレッド","スプレッド","n","sự lan rộng | biên độ chênh lệch | đồ phết bánh | sự trải rộng","spread","1072770"),
    ("スランプ","スランプ","n","sự sa sút phong độ | tình trạng giảm sút | giai đoạn xuống dốc","slump","1073830"),
    ("セクシュアリティ","セクシュアリティ","n","tính dục | xu hướng tính dục | bản dạng tính dục","sexuality","2502100"),
    ("セレクション","セレクション","n","sự lựa chọn | sự tuyển chọn | bộ sưu tập chọn lọc","selection","1074880"),
    ("ソーシャル","ソーシャル","adj-f","thuộc xã hội | mang tính xã hội | cộng đồng","social","2496750"),
    ("ターニング","ターニング","n|adj-no","sự xoay chuyển | bước ngoặt | sự chuyển hướng","turning","2183790"),
    ("ダイアログ","ダイアログ","n","đối thoại | hội thoại | cuộc trao đổi | hộp thoại","dialogue","1076720"),
    ("ダイナミクス","ダイナミクス","n","động lực học | sự vận động | tính năng động | động lực","dynamics","1076800"),
    ("ダウト","ダウト","n|int","sự nghi ngờ | trò bài Doubt | điều đáng ngờ | bịp","doubt | (the card game) Cheat","1076970"),
    ("タレント","タレント","n","nghệ sĩ truyền hình | người nổi tiếng | tài năng | người dẫn chương trình","a (TV) personality | talent","1076460"),
    ("ディスカウント","ディスカウント","n|vs|vt","sự giảm giá | chiết khấu | hạ giá","discount","1081680"),
    ("ディベロップメント","ディベロップメント","n","sự phát triển | việc khai phá | sự phát triển dự án","development","2448180"),
    ("デカダン","デカダン","adj-na","suy đồi | sa đọa | trụy lạc | đồi trụy","decadent","1082620"),
    ("デモクラシー","デモクラシー","n","nền dân chủ | chế độ dân chủ | tư tưởng dân chủ","democracy","1084020"),
    ("トランジション","トランジション","n","sự chuyển tiếp | giai đoạn quá độ | sự chuyển đổi","transition","2025690"),
    ("トリビュート","トリビュート","n","sự tri ân | lời tôn vinh | tác phẩm tưởng nhớ","tribute","2475050"),
    ("ナレッジ","ナレッジ","n","tri thức | kiến thức | hiểu biết chuyên môn","knowledge","1982470"),
    ("ニュートラリティー","ニュートラリティー","n","tính trung lập | sự trung dung | thái độ vô tư","neutrality","2471330"),
    ("ネゴ","ネゴ","n","sự đàm phán | thương lượng | mặc cả","negotiation","2851726"),
    ("ハードコア","ハードコア","adj-na|n","cực đoan | gắt | thành phần cốt cán cứng rắn | nhạc hardcore","hardcore","1094530"),
    ("バイタル","バイタル","adj-na|n","sống động | tràn đầy sức sống | thiết yếu | dấu hiệu sinh tồn","vital | lively | vital signs","2500650"),
    ("バウンダリー","バウンダリー","n","ranh giới | đường biên | giới hạn","boundary","2817580"),
    ("パッショネート","パッショネート","adj-na","đầy đam mê | nồng nhiệt | sôi nổi | nhiệt huyết","passionate","1101790"),
    ("ハラスメント","ハラスメント","n","sự quấy rối | sự sách nhiễu | sự bắt nạt (nơi làm việc)","harassment","2715300"),
    ("バリュー","バリュー","n","giá trị | giá trị sử dụng | tầm quan trọng","value","1099810"),
    ("ヒーリング","ヒーリング","n","sự chữa lành | sự an ủi tinh thần | xoa dịu tâm hồn","healing","2448150"),
    ("ビビッド","ビビッド","adj-na","sống động | rực rỡ | sinh động | sắc nét","vivid","1105670"),
    ("フィロソフィー","フィロソフィー","n","triết học | triết lý | quan niệm sống","philosophy","1109410"),
    ("フラジャイル","フラジャイル","adj-na","mong manh | dễ vỡ | dễ tổn thương | mỏng manh","fragile","2862945"),
    ("プレリュード","プレリュード","n","khúc dạo đầu | màn mở đầu | sự khởi đầu","prelude","1117010"),
    ("プロアクティブ","プロアクティブ","adj-na","chủ động | tích cực đón đầu | đi trước đón đầu","proactive","2327390"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
