# -*- coding: utf-8 -*-
"""Build N2 ready wave 011 — sino-verbs (suru): construction, transport, employment, processing."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-011.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("掌握","しょうあく","n|vs|vt","nắm giữ | thâu tóm | khống chế","grasping | commanding | having control over","1349660"),
    ("克服","こくふく","n|vs|vt","khắc phục | vượt qua | chế ngự","overcoming | surmounting","1285790"),
    ("打破","だは","n|vs|vt","đập tan | phá bỏ | đánh bại","breaking down | defeating | abolishing","1408950"),
    ("是正","ぜせい","n|vs|vt","chấn chỉnh | sửa chữa | điều chỉnh","correction | redressing | rectifying","1374510"),
    ("矯正","きょうせい","n|vs|vt","sửa chữa | uốn nắn | chỉnh (răng)","correction | rectification | straightening","1237800"),
    ("訂正","ていせい","n|vs|vt|adj-no","đính chính | sửa lại | hiệu đính","correction | revision | amendment","1436710"),
    ("改訂","かいてい","n|vs|vt|adj-no","sửa đổi (văn bản) | tu chỉnh","revision (of text) | alteration","1201060"),
    ("新築","しんちく","n|vs|vt|adj-no","xây mới | nhà xây mới","new building | new construction","1362160"),
    ("着工","ちゃっこう","n|vs|vi","khởi công | bắt đầu thi công","starting (construction) work","1423030"),
    ("竣工","しゅんこう","n|vs|vi","hoàn công | hoàn thành xây dựng","completion of construction","1341260"),
    ("落成","らくせい","n|vs|vi","khánh thành | hoàn thành (công trình)","completion (of a building)","1548780"),
    ("起工","きこう","n|vs|vt|vi","khởi công | bắt tay vào làm","setting to work","1223760"),
    ("撤去","てっきょ","n|vs|vt","dỡ bỏ | tháo dỡ | di dời","removal | dismantling","1437720"),
    ("撤収","てっしゅう","n|vs|vt|vi","thu dọn | rút (quân) | dỡ bỏ","removal | dismantling | withdrawal","1437730"),
    ("撤退","てったい","n|vs|vi","rút lui | rút quân | rút khỏi","evacuation | withdrawal | retreat","1437740"),
    ("後退","こうたい","n|vs|vi","lùi lại | thụt lùi | thoái lui | suy thoái","retreat | moving backwards | recession","1269880"),
    ("前進","ぜんしん","n|vs|vi","tiến lên | tiến tới | tiến bộ","advance | moving forward | progress","1393350"),
    ("邁進","まいしん","n|vs|vi","tiến tới (kiên định) | dốc sức hướng tới","pushing forward | striving (for)","1573680"),
    ("推進","すいしん","n|vs|vt","thúc đẩy | đẩy mạnh | xúc tiến","propulsion | promotion | advancement","1371140"),
    ("失速","しっそく","n|vs|vi","mất đà | chững lại | sa sút","stall | downturn | slump","1320050"),
    ("停滞","ていたい","n|vs|vi","trì trệ | đình trệ | ứ đọng","stagnation | standstill | delay","1435010"),
    ("休止","きゅうし","n|vs|vt|vi","tạm dừng | nghỉ | ngừng","pause | suspension | stoppage","1227800"),
    ("中止","ちゅうし","n|vs|vt","đình chỉ | hủy bỏ | ngừng giữa chừng","interruption | suspension | cancellation","1424410"),
    ("存続","そんぞく","n|vs|vt|vi","tiếp tục tồn tại | duy trì | kéo dài","continuance | survival | retention","1406190"),
    ("永続","えいぞく","n|vs|vi|adj-no","lâu dài | vĩnh viễn | liên tục","permanence | continuation","1174230"),
    ("断続","だんぞく","n|vs|vi","gián đoạn | ngắt quãng | lúc có lúc không","intermittence | occurring intermittently","1419710"),
    ("発進","はっしん","n|vs|vi","xuất phát | cất cánh | khởi hành","departure | takeoff | starting (to move)","1477610"),
    ("始動","しどう","n|vs|vt|vi","khởi động | bắt đầu (dự án) | đi vào hoạt động","starting (a machine) | initiation","1307600"),
    ("運搬","うんぱん","n|vs|vt","vận chuyển | chuyên chở","transport | conveyance | carriage","1173010"),
    ("搬入","はんにゅう","n|vs|vt","mang vào | đưa vào (đồ nặng)","carrying in | bringing in","1481320"),
    ("搬出","はんしゅつ","n|vs|vt","mang ra | đưa ra (đồ nặng)","carrying out | taking out","1481290"),
    ("輸送","ゆそう","n|vs|vt","vận tải | vận chuyển | chuyên chở","transport | transportation | transit","1538850"),
    ("配送","はいそう","n|vs|vt","giao hàng | phân phối giao tới","delivery","1473120"),
    ("発送","はっそう","n|vs|vt","gửi đi | chuyển đi | giao hàng","sending | forwarding | shipping","1477670"),
    ("郵送","ゆうそう","n|vs|vt","gửi qua bưu điện","mailing | posting","1542380"),
    ("送付","そうふ","n|vs|vt","gửi | chuyển | gửi kèm","sending | forwarding | remitting","1402840"),
    ("添付","てんぷ","n|vs|vt","đính kèm | kèm theo (tài liệu)","attaching (documents) | appending","1440880"),
    ("同封","どうふう","n|vs|vt|adj-no","gửi kèm (trong phong bì)","enclosing (e.g. with a letter)","1453340"),
    ("返却","へんきゃく","n|vs|vt","trả lại | hoàn trả","return of something | repayment","1512180"),
    ("返還","へんかん","n|vs|vt","hoàn trả | trao trả | phục hồi","return | restoration","1512170"),
    ("償還","しょうかん","n|vs|vt","hoàn trả | thanh toán | chuộc lại","repayment | redemption | amortization","1346030"),
    ("完済","かんさい","n|vs|vt","trả hết nợ | thanh toán toàn bộ","full payment | liquidation","1211460"),
    ("返納","へんのう","n|vs|vt","trả lại (cho cơ quan) | nộp trả","returning (to the authorities)","1617080"),
    ("納入","のうにゅう","n|vs|vt","nộp (thuế, phí) | giao (hàng)","payment | supply (of goods) | delivery","1470090"),
    ("収納","しゅうのう","n|vs|vt","cất giữ | thu (tiền) | thu hoạch","storage | receipt (of funds) | harvesting","1330830"),
    ("収容","しゅうよう","n|vs|vt","thu nhận | chứa | giam giữ | tiếp nhận","accommodation | housing | detention","1330880"),
    ("収拾","しゅうしゅう","n|vs|vt","thu xếp | kiểm soát | dàn xếp ổn thỏa","control | bringing under control | settling","1330660"),
    ("採取","さいしゅ","n|vs|vt","thu thập | lấy mẫu | hái lượm | khai thác","picking | collecting | extraction","1294800"),
    ("選定","せんてい","n|vs|vt","tuyển chọn | lựa chọn","selection","1392360"),
    ("選出","せんしゅつ","n|vs|vt","bầu chọn | tuyển ra","election | selection | choice","1392280"),
    ("選抜","せんばつ","n|vs|vt","tuyển chọn | chọn lọc | tuyển lựa","selection | picking out","1392380"),
    ("抽出","ちゅうしゅつ","n|vs|vt","trích xuất | chiết xuất | lấy mẫu","extraction | sampling","1426180"),
    ("除去","じょきょ","n|vs|vt","loại bỏ | khử | tẩy bỏ","removal | getting rid of","1345670"),
    ("破棄","はき","n|vs|vt","hủy bỏ | xé bỏ | hủy (hợp đồng) | bác bỏ","destruction | annulment | breaking (a treaty)","1471300"),
    ("遺棄","いき","n|adj-no|vs|vt","bỏ rơi | ruồng bỏ | vứt bỏ","abandonment | desertion","1587090"),
    ("投棄","とうき","n|vs|vt","vứt bỏ | thải bỏ | đổ (rác)","abandonment | throwing away | dumping","1619790"),
    ("処理","しょり","n|vs|vt","xử lý | giải quyết | xử trí","processing | dealing with | treatment","1342510"),
    ("処置","しょち","n|vs|vt","xử trí | biện pháp | điều trị (y tế)","measure | dealing with | medical treatment","1342470"),
    ("応対","おうたい","n|vs|vi","tiếp đón | tiếp khách | ứng phó","dealing with (people) | receiving (callers)","1179980"),
    ("応接","おうせつ","n|vs|vt|vi","tiếp đón | tiếp khách","reception (of visitors) | dealing with","1179930"),
    ("接客","せっきゃく","n|vs|vi","tiếp khách | phục vụ khách","serving customers | reception","1385360"),
    ("接待","せったい","n|vs|vt","chiêu đãi | tiếp đãi (đối tác)","entertainment (of guests) | wining and dining","1385530"),
    ("歓待","かんたい","n|vs|vt","tiếp đón nồng hậu | hiếu khách","warm welcome | hospitality","1213040"),
    ("歓迎","かんげい","n|vs|vt","chào đón | hoan nghênh | đón tiếp nồng nhiệt","welcome | warm reception","1212960"),
    ("送迎","そうげい","n|vs|vt","đưa đón","seeing off and meeting on return","1402770"),
    ("出迎え","でむかえ","n","sự ra đón | đón tiếp","meeting | reception","1338710"),
    ("見送り","みおくり","n","tiễn đưa | hoãn lại | tạm gác | bỏ qua","seeing off | deferment | wait-and-see","1259820"),
    ("派遣","はけん","n|vs|vt","cử đi | phái cử | nhân viên phái cử","dispatch | deployment | temporary employee","1471130"),
    ("赴任","ふにん","n|vs|vi","đi nhậm chức (xa) | chuyển đến nơi làm mới","moving to start a new job | new appointment","1498200"),
    ("着任","ちゃくにん","n|vs|vi","nhậm chức | đến nhận việc mới","taking up a new post","1423200"),
    ("就任","しゅうにん","n|vs|vi","nhậm chức | lên nắm chức | nhậm nhiệm","assumption of office | inauguration","1331780"),
    ("退任","たいにん","n|vs|vi","từ nhiệm | rời chức | mãn nhiệm","retirement | resignation | stepping down","1411440"),
    ("辞任","じにん","n|vs|vi","từ chức | từ nhiệm","resignation (from a position)","1319000"),
    ("解任","かいにん","n|vs|vt","cách chức | bãi nhiệm | miễn nhiệm","dismissal (from a post) | removal","1199210"),
    ("罷免","ひめん","n|vs|vt","cách chức | bãi miễn | sa thải","dismissal (from a position) | discharge","1484240"),
    ("更迭","こうてつ","n|vs|vt|vi","thay đổi nhân sự | cải tổ | bãi nhiệm thay người","change (of personnel) | reshuffle | dismissal","1279430"),
    ("任命","にんめい","n|vs|vt","bổ nhiệm | chỉ định | đề cử","appointment | nomination | designation","1467280"),
    ("任免","にんめん","n|vs|vt","bổ nhiệm và bãi nhiệm","appointments and dismissal","1467310"),
    ("昇格","しょうかく","n|vs|vi","thăng cấp | nâng cấp bậc","promotion | raising of status","1349740"),
    ("降格","こうかく","n|vs|vt|vi","giáng cấp | hạ bậc | xuống hạng","demotion | relegation | downgrading","1631480"),
    ("左遷","させん","n|vs|vt","giáng chức | thuyên chuyển xuống thấp","demotion | relegation | downward move","1290940"),
    ("栄転","えいてん","n|vs|vi","thăng chức (chuyển đi) | thăng tiến","promotion","1173960"),
    ("転任","てんにん","n|vs|vi","thuyên chuyển công tác | đổi chỗ làm","change of post","1441320"),
    ("離職","りしょく","n|vs|vi","nghỉ việc | thôi việc | mất việc","leaving one's job | losing one's job","1821700"),
    ("失職","しっしょく","n|vs|vi","mất việc | thất nghiệp","losing one's job","1320010"),
    ("就職","しゅうしょく","n|vs|vi","xin việc | tìm được việc | đi làm","finding employment | getting a job","1331670"),
    ("内定","ないてい","n|vs|vt|vi","quyết định sơ bộ | offer không chính thức (việc làm)","tentative decision | unofficial (job) offer","1458920"),
    ("減算","げんざん","n|vs|vt|vi","phép trừ | tính trừ","subtraction","1682990"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
