# -*- coding: utf-8 -*-
"""Build N3 ready wave 067 — 87 freshly-curated N3 compound verbs + time/life nouns + balance/quality adjectives."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n3-vi-ready-067.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N3"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("取り寄せる","とりよせる","v1|vt","đặt hàng | gọi đến | kéo lại gần","to order | to send away for | to pull closer","1326620"),
    ("取り掛かる","とりかかる","v5r|vi","bắt tay vào | bắt đầu | khởi sự","to begin (doing) | to set about | to get down to","1326600"),
    ("取り壊す","とりこわす","v5s|vt","phá dỡ | tháo dỡ | đập bỏ","to demolish | to tear down | to pull down","1658970"),
    ("切り上げる","きりあげる","v1|vt","kết thúc sớm | làm tròn lên | nâng giá","to cut short | to round up (number) | to revalue (currency)","1384300"),
    ("立ち上げる","たちあげる","v1|vt","khởi động | thành lập | khởi chạy","to start up | to launch (a business) | to boot (a computer)","1551380"),
    ("立て替える","たてかえる","v1|vt","trả thay (ứng trước) | ứng tiền giúp","to pay for someone else | to make a temporary payment","1551550"),
    ("引き上げる","ひきあげる","v1|vt|vi","kéo lên | nâng (giá, thuế) | rút lui | thăng chức","to pull up | to raise (taxes) | to withdraw | to promote","1601480"),
    ("引き下げる","ひきさげる","v1|vt","hạ (giá, thuế) | giảm | rút lại | rút lui","to lower (price, tax) | to reduce | to withdraw","1601600"),
    ("引き取る","ひきとる","v5r|vt","nhận về | tiếp nhận | nhận nuôi | rời đi","to take into one's possession | to take custody of | to leave","1168960"),
    ("引き渡す","ひきわたす","v5s|vt","bàn giao | giao nộp | dẫn độ | căng ngang","to deliver | to hand over | to extradite","1601790"),
    ("引き継ぐ","ひきつぐ","v5g|vt","kế nhiệm | tiếp quản | kế thừa | bàn giao","to take over (duties) | to inherit | to hand over","1168910"),
    ("盛り上げる","もりあげる","v1|vt","chất cao | khuấy động | làm sôi nổi | đẩy lên cao trào","to pile up | to stir up | to enliven | to bring to a climax","1379700"),
    ("盛り上がる","もりあがる","v5r|vi","dâng lên | phồng lên | sôi nổi | hứng khởi","to swell | to bulge | to get excited","1379690"),
    ("仕立てる","したてる","v1|vt","may (đồ) | đào tạo | dựng thành | chuẩn bị","to tailor | to train | to turn into (a play) | to prepare","1305560"),
    ("組み合わせる","くみあわせる","v1|vt","kết hợp | ghép lại | phối hợp | đối đầu","to put together | to combine | to match against","1397480"),
    ("置き換える","おきかえる","v1|vt","sắp xếp lại | thay thế | hoán đổi | thay vị trí","to rearrange | to replace | to swap | to substitute","1421820"),
    ("書き換える","かきかえる","v1|vt","viết lại | ghi đè | gia hạn | sang tên","to rewrite | to overwrite | to renew | to transfer","1589920"),
    ("すり替える","すりかえる","v1|vt","tráo | đánh tráo | thay lén | lảng tránh (vấn đề)","to switch (secretly) | to substitute | to sidestep (an issue)","1298850"),
    ("締め付ける","しめつける","v1|vt","siết chặt | thắt chặt | gây áp lực | bóp nghẹt","to tighten | to constrict | to put pressure on | to oppress","1436650"),
    ("締めくくる","しめくくる","v5r|vt","kết thúc | tổng kết | buộc chặt | quản lý","to bring to a finish | to bind firmly | to superintend","1436610"),
    ("取り計らう","とりはからう","v5u|vt","thu xếp | dàn xếp | xử lý | bố trí","to manage | to settle | to deal with | to arrange","1326660"),
    ("取り仕切る","とりしきる","v5r|vt","quán xuyến | điều hành | nắm toàn quyền","to manage (all by oneself) | to control | to take charge of","1327030"),
    ("食らう","くらう","v5u|vt","đớp | tọng | hứng (đòn) | gặp (rắc rối)","to eat | to wolf | to receive (a blow) | to undergo (trouble)","1592410"),
    ("張り付く","はりつく","v5k|vi","bám dính | bám chặt | đeo bám | túc trực","to stick (to) | to cling (to) | to stay (in a place)","1665010"),
    ("貼り付ける","はりつける","v1|vt","dán | dán lên | gắn | bố trí","to paste | to stick | to affix | to station","1601120"),
    ("包み込む","つつみこむ","v5m|vt","bao bọc | gói trọn | ôm trọn","to wrap up | to envelop","1515380"),
    ("覆う","おおう","v5u|vt","che phủ | che giấu | bao trùm | ngụy trang","to cover | to hide | to conceal | to disguise","1588840"),
    ("被せる","かぶせる","v1|vt","đậy | trùm lên | đổ (nước) | đổ lỗi (cho ai)","to cover (with) | to put on | to pour over | to put the blame on","1484320"),
    ("羽織る","はおる","v5r|vt","khoác (áo) | choàng lên","to put on (a coat, gown, etc.)","1171780"),
    ("身にまとう","みにまとう","exp|v5u","mặc | khoác lên người | vận","to wear | to be dressed in | to have on","2841283"),
    ("裸足","はだし","n|adj-no","chân trần | đi chân không | vượt trội (hơn cả chuyên gia)","barefoot | superior to (e.g. a professional)","1547660"),
    ("西暦","せいれき","n","Dương lịch | Công nguyên | lịch phương Tây","Common Era | AD | Western (Gregorian) calendar","1381140"),
    ("年号","ねんごう","n","niên hiệu | tên niên đại (Nhật)","name of an imperial era | Japanese era name","1468650"),
    ("時期","じき","n|adv","thời kỳ | thời điểm | mùa | giai đoạn","time | season | period | phase | stage","1316040"),
    ("時間帯","じかんたい","n","khung giờ | múi giờ | khoảng thời gian","period of time | time slot | time zone","1316010"),
    ("任期","にんき","n","nhiệm kỳ","term of office","1467190"),
    ("満期","まんき","n|adj-no","hết hạn | đáo hạn | mãn hạn","expiration (of a term) | maturity (investment)","1641040"),
    ("定年","ていねん","n|vs|vi","tuổi nghỉ hưu | nghỉ hưu (đến tuổi)","(compulsory) retirement age | mandatory retirement","1435740"),
    ("青春","せいしゅん","n","tuổi thanh xuân | thời thanh niên","youth | adolescence | springtime of life","1381550"),
    ("成人","せいじん","n|vs|vi","người trưởng thành | sự trưởng thành","adult | grown-up | coming of age","1375740"),
    ("一生","いっしょう","n|adj-no|adv","cả đời | một đời | suốt đời","whole life | a lifetime | all through life","1576200"),
    ("生涯","しょうがい","n|adv","cuộc đời | sự nghiệp | trọn đời","life | lifetime | career | for life","1378840"),
    ("誕生","たんじょう","n|vs|vi","sự ra đời | sự sinh ra | sự hình thành","birth | nativity | creation | formation","1419080"),
    ("晩年","ばんねん","n","những năm cuối đời | tuổi xế chiều","one's later years | final years (in life)","1482230"),
    ("幼少","ようしょう","n|adj-na","thời thơ ấu | tuổi nhỏ | ấu thơ","infancy | childhood | tender age","1545220"),
    ("還暦","かんれき","n","lễ thọ 60 tuổi | tuổi 60 (giáp tròn)","kanreki | one's 60th birthday","1215160"),
    ("命日","めいにち","n","ngày giỗ | ngày mất","anniversary of a person's death","1532120"),
    ("法要","ほうよう","n","lễ cầu siêu | lễ giỗ (Phật giáo)","Buddhist memorial service","1627580"),
    ("円満","えんまん","adj-na|n","viên mãn | hòa thuận | êm đẹp | suôn sẻ","harmonious | peaceful | amicable | smooth","1176200"),
    ("良好","りょうこう","adj-na|n","tốt | tốt đẹp | thuận lợi | khả quan","good | fine | excellent | favorable","1554550"),
    ("健全","けんぜん","adj-na|n","lành mạnh | khỏe mạnh | vững vàng","healthy | sound | wholesome","1256360"),
    ("順調","じゅんちょう","adj-na|n","thuận lợi | suôn sẻ | tiến triển tốt","favourable | doing well | all right","1342380"),
    ("上質","じょうしつ","adj-na|n","chất lượng cao | hảo hạng","fine quality","1353310"),
    ("高価","こうか","adj-na|n","đắt tiền | đắt đỏ | có giá trị","highly priced | expensive | valuable","1283300"),
    ("安価","あんか","adj-na|n","rẻ | giá rẻ | hời hợt (rẻ tiền)","low-priced | cheap | inexpensive | superficial","1153740"),
    ("割安","わりやす","adj-na|n","rẻ tương đối | hời | kinh tế","economical | comparatively cheap","1606990"),
    ("割高","わりだか","adj-na|n","đắt tương đối | hơi đắt","comparatively high | fairly expensive","1606890"),
    ("適正","てきせい","adj-na|n","hợp lý | thích đáng | phù hợp","reasonable | suitable","1437420"),
    ("正当","せいとう","adj-na|n","chính đáng | hợp lý | hợp pháp","just | justifiable | proper | legitimate | lawful","1377660"),
    ("不当","ふとう","adj-na|n","bất công | không chính đáng | phi lý","unfair | unjust | improper | unreasonable","1494120"),
    ("公正","こうせい","n|adj-na","công chính | công bằng | vô tư","justice | fairness | impartiality","1274120"),
    ("公平","こうへい","n|adj-na","công bằng | vô tư | khách quan","fairness | impartiality | objectivity","1274640"),
    ("均等","きんとう","adj-na|n","đồng đều | cân bằng | bình quân","equal (distribution) | even | uniform","1241310"),
    ("互角","ごかく","adj-no|adj-na|n","ngang tài | ngang sức | kẻ tám lạng người nửa cân","equal (in ability) | evenly matched | on par","1268820"),
    ("五分五分","ごぶごぶ","n|adj-no","năm ăn năm thua | ngang ngửa | hòa","fifty-fifty | even match | tie","1268610"),
    ("対称","たいしょう","n","đối xứng | ngôi thứ hai","symmetry | second person","1410100"),
    ("左右対称","さゆうたいしょう","n|adj-no","đối xứng trái phải | đối xứng hai bên","bilateral symmetry","2058100"),
    ("非対称","ひたいしょう","n|adj-no","bất đối xứng | không đối xứng","asymmetry | dissymmetry","1485110"),
    ("均衡","きんこう","n|vs|vi","cân bằng | thăng bằng | cân đối","balance | equilibrium","1241270"),
    ("不均衡","ふきんこう","adj-na|n","mất cân bằng | mất cân đối | chênh lệch","imbalance | disproportion | disparity","1491970"),
    ("偏り","かたより","n","sự thiên lệch | độ lệch | thành kiến","deviation | inclination | bias | prejudice","1510330"),
    ("偏重","へんちょう","n|vs|vt","coi trọng quá mức | thiên về | đặt nặng","attaching too much importance to | overemphasis","1510500"),
    ("折衷","せっちゅう","n|vs|vt","dung hòa | chiết trung | pha trộn","compromise | blending | eclecticism","1385960"),
    ("緩和","かんわ","n|vs|vt|vi","nới lỏng | xoa dịu | giảm nhẹ | làm dịu","relief | mitigation | relaxation | easing","1214530"),
    ("緩衝","かんしょう","n|vs|vt","giảm chấn | đệm | vùng đệm","shock absorption | buffer | cushioning","1214490"),
    ("調和","ちょうわ","n|vs|vi","hài hòa | hòa hợp | cân đối","harmony | accord | agreement","1429330"),
    ("不調和","ふちょうわ","n|adj-na","bất hòa | không hài hòa | lạc điệu","disharmony | discord | incongruity","1493850"),
    ("兼ね合い","かねあい","n|vs","sự cân bằng | sự dung hòa | thế cân","equilibrium | good balance | poise","1256530"),
    ("釣り合い","つりあい","n","sự cân bằng | sự cân xứng | thế thăng bằng","balance | equilibrium","1598110"),
    ("釣り合う","つりあう","v5u|vi","cân bằng | cân xứng | hợp | tương xứng","to balance | to be in harmony | to suit | to be a good match","1434050"),
    ("見合う","みあう","v5u|vt|vi","nhìn nhau | tương xứng | bù trừ | cân đối","to look at each other | to be proportionate (to) | to offset","1259560"),
    ("相応","そうおう","adj-na|n|vs","tương xứng | phù hợp | thích đáng","suitable | appropriate | befitting | adequate","1400840"),
    ("不相応","ふそうおう","adj-na|n","không tương xứng | không phù hợp | không xứng","unsuited | inappropriate | undeserved","1493640"),
    ("分相応","ぶんそうおう","adj-na|n","đúng với khả năng | trong khả năng (của mình)","within one's means","1689190"),
    ("身分相応","みぶんそうおう","n|adj-na","đúng với địa vị | hợp với thân phận","appropriate to one's position | within one's means","2053870"),
    ("似つかわしい","につかわしい","adj-i","phù hợp | thích hợp | hợp | xứng","suitable | appropriate | becoming | fitting","1599880"),
    ("そぐわない","そぐわない","adj-i","không hợp | không tương xứng | lạc lõng","unsuitable | not matching | out of character","2008690"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
