# -*- coding: utf-8 -*-
"""Build N2 ready wave 040 — taste, texture, cooking, dishes, sweets, heat/fire, food."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-040.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("辛味","からみ","n","vị cay | vị nồng | vị mặn","hot taste | pungent taste","1365940"),
    ("塩味","しおあじ","n|adj-no","vị mặn | độ mặn","salty taste | saltiness","1178880"),
    ("歯ごたえ","はごたえ","n","độ giòn | độ dai | cảm giác khi nhai | sự thử thách","chewiness | firmness | challenge","1313090"),
    ("舌触り","したざわり","n","cảm giác trên lưỡi | kết cấu (khi nếm)","feel on the tongue | texture","1788130"),
    ("口当たり","くちあたり","n","cảm giác đầu lưỡi | cách cư xử | thái độ","taste | feel on the tongue | manner | demeanour","1276680"),
    ("濃厚","のうこう","adj-na","đậm đà | đặc sánh | nồng | (khả năng) cao | nồng nàn","rich (flavor) | thick | (very) likely | passionate","1469910"),
    ("淡白","たんぱく","adj-na|n","thanh đạm | nhạt | giản dị | điềm đạm | thẳng thắn","light (flavor) | plain | frank | easygoing","1597290"),
    ("新鮮","しんせん","adj-na","tươi | tươi mới | mới mẻ","fresh","1362100"),
    ("熟れる","うれる","v1|vi","chín (quả, hạt) | chín muồi","to ripen (fruit) | to become ripe","1337820"),
    ("熟す","じゅくす","v5s|vs-c|vi","chín | chín muồi | đến lúc | trở nên thành thạo","to ripen | to mature | to be the right time","1337800"),
    ("醸造","じょうぞう","n|vs|vt","ủ men | nấu (rượu, tương) | lên men chế biến","brewing","1357090"),
    ("蒸留","じょうりゅう","n|vs|vt","chưng cất","distillation","1356970"),
    ("精米","せいまい","n|vs|vt|vi","xát gạo | gạo đã xát | gạo trắng","rice polishing | polished rice","1380180"),
    ("製粉","せいふん","n|vs|vt|vi","xay bột | nghiền thành bột","milling | grinding into flour","1380790"),
    ("製麺","せいめん","n|vs|vt|vi","làm mì | sản xuất mì sợi","noodle making","1953050"),
    ("製パン","せいパン","n","làm bánh mì","bread making","2831861"),
    ("製菓","せいか","n","làm bánh kẹo | sản xuất bánh kẹo","confectionery production","1380590"),
    ("味醂","みりん","n","mirin | rượu ngọt nấu ăn","mirin | sweet rice wine for cooking","1527080"),
    ("だし汁","だしじる","n","nước dùng | nước hầm | nước lèo","broth | stock | sauce","1338040"),
    ("香味料","こうみりょう","n","gia vị tạo hương | hương liệu","flavoring | spice","1283120"),
    ("具","ぐ","n|ctr","dụng cụ | cái | nguyên liệu (cho vào canh, cơm)","tool | ingredients (in soup, rice)","1244950"),
    ("餡","あん","n","nhân đậu đỏ | mứt đậu | nhân (bánh) | nước xốt sệt","red bean paste | filling (of a dumpling)","1610575"),
    ("餅","もち","n","bánh giầy | bánh nếp | mochi","mochi | rice cake","1535790"),
    ("団子","だんご","n","bánh dango | bánh trôi | viên tròn | cụm | đám","dango | dumpling | ball-shaped object | bunch","1419240"),
    ("煎餅","せんべい","n","bánh gạo (giòn) | senbei","(Japanese) rice cracker | senbei","1391560"),
    ("饅頭","まんじゅう","n","bánh bao ngọt | bánh manju (hấp có nhân)","manjū | steamed bun with filling","1574480"),
    ("羊羹","ようかん","n","yokan | bánh thạch đậu đỏ","yōkan | jellied red bean dessert","1546540"),
    ("和菓子","わがし","n","bánh kẹo truyền thống Nhật | bánh ngọt Nhật","wagashi | traditional Japanese confectionery","1562020"),
    ("洋菓子","ようがし","n","bánh ngọt kiểu Tây","Western confectionery","1545870"),
    ("駄菓子","だがし","n","bánh kẹo rẻ tiền | kẹo vặt","penny candy | cheap sweets","1409020"),
    ("珍味","ちんみ","n","món lạ | sơn hào hải vị | của ngon vật lạ","delicacy | dainties","1431970"),
    ("佳肴","かこう","n","mỹ vị | món ngon | cao lương mỹ vị","delicacy | rare treat","1189750"),
    ("副菜","ふくさい","n","món phụ | món ăn kèm (rau, đậu, dưa muối)","side dish","2553350"),
    ("主菜","しゅさい","n","món chính (thịt, cá)","main dish | principal dish","2411790"),
    ("特盛","とくもり","n","phần cực lớn | phần đặc biệt to","extra-large portion","2413990"),
    ("大盛り","おおもり","n","phần lớn | suất to","large serving | large portion","1414280"),
    ("小盛り","こもり","n","phần nhỏ | suất nhỏ","small portion | small serving","2836520"),
    ("盛り付け","もりつけ","n","cách bày món | trình bày món ăn | trang trí đĩa","arrangement of food (on a dish)","2140820"),
    ("取り皿","とりざら","n","đĩa cá nhân | đĩa nhỏ để gắp đồ ăn chung","individual plate","1707480"),
    ("箸置き","はしおき","n","gác đũa | đồ kê đũa","chopstick rest","1701360"),
    ("楊枝","ようじ","n","tăm | xiên (đồ ngọt) | bàn chải răng (xưa)","toothpick | skewer","1545780"),
    ("膳","ぜん","n|ctr","bàn ăn nhỏ (cá nhân) | khay ăn | bữa ăn | suất","small dining table | serving tray | meal","1396490"),
    ("土鍋","どなべ","n","nồi đất","earthenware pot","1445520"),
    ("蒸し器","むしき","n","xửng hấp | nồi hấp","steamer | steam cooker","1604840"),
    ("鉄板","てっぱん","n","tấm thép | bàn nướng sắt | điều chắc chắn","iron plate | sure thing","1437970"),
    ("網焼き","あみやき","n","nướng vỉ | nướng lưới","grilling | broiling","1671540"),
    ("炭火","すみび","n","lửa than | than hồng","charcoal fire","1837240"),
    ("直火","じかび","n","lửa trực tiếp | nướng trực lửa","open fire (in cooking) | direct heat","2111590"),
    ("弱火","よわび","n","lửa nhỏ | lửa liu riu","low flame (cooking) | low heat","1662360"),
    ("強火","つよび","n","lửa lớn | lửa to","high flame (cooking) | high heat","1799650"),
    ("中火","ちゅうび","n","lửa vừa","medium flame (cooking) | medium heat","1695550"),
    ("余熱","よねつ","n","nhiệt thừa | hơi nóng còn lại | nhiệt dư","waste heat | residual heat","1544440"),
    ("予熱","よねつ","n|vs|vt","làm nóng trước (lò) | khởi động làm ấm","preheating (an oven) | warming up","2211870"),
    ("湯沸かし","ゆわかし","n","ấm đun nước | bình đun nước","teakettle | kettle","1605800"),
    ("水切り","みずきり","n|vs|vt","để ráo nước | giá ráo | rổ ráo | cắt cành dưới nước","straining | draining | colander","1641810"),
    ("あく抜き","あくぬき","n|vs|vt|vi","khử vị chát | khử vị đắng (khi nấu)","removal of astringent taste","2024780"),
    ("下味","したあじ","n","ướp gia vị trước | tẩm ướp món ăn","seasoning of food","1718890"),
    ("隠し味","かくしあじ","n","gia vị bí mật | vị nêm kín đáo làm dậy hương","subtle seasoning | secret ingredient","1822370"),
    ("毒味","どくみ","n|vs|vt|vi","nếm thử (xem có độc) | nếm thử vị món ăn","tasting for poison | checking the taste","1599310"),
    ("火加減","ひかげん","n","độ lửa | mức lửa | cách điều chỉnh lửa","condition of fire | heat level","1193750"),
    ("水加減","みずかげん","n","lượng nước | cách canh nước","amount of water","1736820"),
    ("さじ加減","さじかげん","n","liều lượng (thuốc) | cách nêm nếm | sự khéo léo điều chỉnh","measured amount | manner of seasoning | knack","1734760"),
    ("腹八分","はらはちぶ","n","ăn tám phần no | ăn vừa phải | ăn no 80%","eating moderately | eating until 80% full","1748170"),
    ("腹持ち","はらもち","n","sự no lâu | khả năng giữ no của món ăn","feeling of fullness | ability of a food to fill you up","1748290"),
    ("食べ応え","たべごたえ","n","cảm giác no nê | độ chắc bụng (của món)","substantiality (of a meal) | fillingness","2803560"),
    ("食通","しょくつう","n","người sành ăn | tín đồ ẩm thực | dân ăn uống","gourmet | foodie","1358540"),
    ("美食","びしょく","n|vs","mỹ thực | món ngon | việc ăn ngon | lối ăn sang","gourmet food | dining on gourmet food","1724970"),
    ("粗食","そしょく","n|vs|vi","ăn đạm bạc | bữa ăn giản dị | ăn kham khổ","simple diet | plain food | frugal meal","1397000"),
    ("飽食","ほうしょく","n|vs|vt|vi","ăn no nê | ăn thỏa thuê | dư dật cái ăn","eating one's fill | gorging | satiation","1518340"),
    ("保存食","ほぞんしょく","n","thực phẩm bảo quản | đồ ăn để dành","preserved foods","1748040"),
    ("非常食","ひじょうしょく","n","lương thực dự phòng | đồ ăn khẩn cấp","emergency food | emergency rations","2161400"),
    ("離乳食","りにゅうしょく","n","đồ ăn dặm | thức ăn cai sữa","weaning food | solids (for babies)","1821580"),
    ("流動食","りゅうどうしょく","n","thức ăn lỏng | chế độ ăn lỏng","liquid food (diet)","1645050"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
