# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-042.csv -- 22 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-042.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("崖","がけ","N4","n",
        "vách đá | bờ vực | sườn dốc đứng",
        "cliff | precipice | brink of a dangerous situation",
        "1204380",
        "崖から落ちる。","がけからおちる。",
        "Rơi xuống từ vách đá.","Fall off a cliff."),
    row("街角","まちかど","N4","n",
        "góc phố | góc đường | ngã đường nhỏ",
        "street corner",
        "1204580",
        "街角で待つ。","まちかどでまつ。",
        "Chờ ở góc phố.","Wait at the street corner."),
    row("校庭","こうてい","N4","n",
        "sân trường | khuôn viên trường | sân chơi trường học",
        "schoolyard | school playground | school grounds | campus",
        "1279600",
        "校庭で遊ぶ。","こうていであそぶ。",
        "Chơi trong sân trường.","Play in the schoolyard."),
    row("湿地","しっち","N4","n",
        "đất ngập nước | vùng đầm lầy | đất ẩm ướt",
        "damp ground | wetland | bog | marsh",
        "1320470",
        "湿地帯を歩く。","しっちたいをあるく。",
        "Đi bộ qua vùng đầm lầy.","Walk through the wetlands."),
    row("真夜中","まよなか","N4","n",
        "nửa đêm | giữa đêm khuya",
        "dead of night | midnight",
        "1364380",
        "真夜中に目が覚めた。","まよなかにめがさめた。",
        "Thức dậy vào giữa đêm khuya.","Woke up in the dead of night."),
    row("泉","いずみ","N4","n",
        "suối nguồn | mạch nước ngầm | giếng nước",
        "spring | fountain",
        "1390780",
        "きれいな泉がある。","きれいないずみがある。",
        "Có một dòng suối trong.","There is a clear spring."),
    row("草履","ぞうり","N4","n",
        "dép zori (dép truyền thống Nhật) | dép xỏ ngón kiểu Nhật",
        "zori | traditional Japanese thonged sandals",
        "1402060",
        "草履を履く。","ぞうりをはく。",
        "Đi dép zori.","Put on zori sandals."),
    row("足袋","たび","N4","n",
        "tất tabi (tất Nhật hai ngón) | vớ ngón kiểu Nhật",
        "tabi | traditional split-toe socks",
        "1404920",
        "足袋を履く。","たびをはく。",
        "Đi tất tabi.","Put on tabi socks."),
    row("路地","ろじ","N4","n",
        "ngõ nhỏ | hẻm | lối vào vườn trà đạo",
        "alley | alleyway | lane | path through a gate or garden | teahouse garden",
        "1560050",
        "路地を歩く。","ろじをあるく。",
        "Đi bộ qua ngõ nhỏ.","Walk through an alley."),
    row("夜半","やはん","N4","n|adv",
        "nửa đêm | giữa đêm | đêm khuya",
        "middle of the night | dead of night",
        "1584840",
        "夜半に出発する。","やはんにしゅっぱつする。",
        "Khởi hành vào lúc nửa đêm.","Depart in the middle of the night."),
    row("浴衣","ゆかた","N4","n",
        "yukata (kimono mùa hè nhẹ bằng cotton) | áo mặc tắm kiểu Nhật",
        "yukata | light cotton kimono worn in the summer or used as a bathrobe after a bath",
        "1584990",
        "浴衣を着て花火大会へ。","ゆかたをきてはなびたいかいへ。",
        "Mặc yukata đi xem pháo hoa.","Wear a yukata to the fireworks festival."),
    row("丘","おか","N4","n",
        "đồi | gò đất | đất cao",
        "hill | height | knoll | rising ground",
        "1588920",
        "丘の上に立つ。","おかのうえにたつ。",
        "Đứng trên đỉnh đồi.","Stand on top of the hill."),
    row("休み時間","やすみじかん","N4","n",
        "giờ ra chơi | giờ nghỉ giải lao | thời gian nghỉ",
        "recess | break time | break between classes | free period",
        "2654070",
        "休み時間に遊ぶ。","やすみじかんにあそぶ。",
        "Chơi trong giờ ra chơi.","Play during recess."),
    row("和装","わそう","N4","n",
        "trang phục truyền thống Nhật | mặc kimono | đóng sách kiểu Nhật",
        "Japanese clothing | being dressed in a kimono | Japanese-style bookbinding",
        "1562150",
        "和装で結婚式に参加する。","わそうでけっこんしきにさんかする。",
        "Tham dự đám cưới mặc trang phục truyền thống Nhật.","Attend a wedding in Japanese attire."),
    row("商店街","しょうてんがい","N4","n",
        "phố mua sắm | khu thương mại sầm uất | dãy cửa hàng",
        "shopping district | shopping street | downtown",
        "1347190",
        "商店街で買い物をする。","しょうてんがいでかいものをする。",
        "Mua sắm ở phố thương mại.","Shop in the shopping street."),
    row("夜半","よわ","N4","n",
        "đêm khuya | lúc đêm tối | nửa đêm (cách đọc cổ)",
        "night | middle of the night",
        "2863189",
        "夜半の静寂。","よわのせいじゃく。",
        "Sự tĩnh lặng của đêm khuya.","The silence of the night."),
    row("放課後","ほうかご","N4","n|adv",
        "sau giờ tan học | buổi chiều sau giờ học",
        "after school (at the end of the day)",
        "1516570",
        "放課後に図書館へ行く。","ほうかごにとしょかんへいく。",
        "Đi thư viện sau giờ tan học.","Go to the library after school."),
    row("早朝","そうちょう","N4","n|adv",
        "sáng sớm | buổi sáng sớm | tinh mơ",
        "early morning",
        "1400330",
        "早朝から働く。","そうちょうからはたらく。",
        "Làm việc từ sáng sớm.","Work from early morning."),
    row("横断歩道","おうだんほどう","N4","n",
        "vạch sang đường | lối đi dành cho người đi bộ | vạch kẻ đường",
        "pedestrian crossing | crosswalk",
        "1180910",
        "横断歩道を渡る。","おうだんほどうをわたる。",
        "Băng qua vạch sang đường.","Cross at the pedestrian crossing."),
    row("袴","はかま","N4","n",
        "hakama (quần/váy xếp ly mặc ngoài kimono) | trang phục truyền thống Nhật",
        "hakama | pleated skirt or loose-legged trousers worn over a kimono",
        "1267440",
        "袴を着て卒業式に出る。","はかまをきてそつぎょうしきにでる。",
        "Mặc hakama dự lễ tốt nghiệp.","Wear hakama to the graduation ceremony."),
    row("袴","パジ","N4","n",
        "quần truyền thống Hàn Quốc (paji)",
        "traditional Korean pants",
        "2824330",
        "袴はパジとも呼ばれる。","はかまはぱじともよばれる。",
        "Hakama còn được gọi là paji.","Hakama is also called paji."),
    row("高原","こうげん","N4","n",
        "cao nguyên | vùng đất cao | đồng bằng cao",
        "tableland | plateau",
        "1283490",
        "高原の空気は清々しい。","こうげんのくうきはすがすがしい。",
        "Không khí cao nguyên trong lành.","The air on the plateau is refreshing."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
