# -*- coding: utf-8 -*-
"""Build N2 ready wave 008 — economy / law / crime / government terms."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-008.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("債券","さいけん","n","trái phiếu | giấy nợ","bond | debenture","1292070"),
    ("株主","かぶぬし","n","cổ đông","shareholder | stockholder","1209010"),
    ("利潤","りじゅん","n","lợi nhuận | lãi","profit | returns","1549580"),
    ("損益","そんえき","n","lãi lỗ | lời lỗ | được mất","profit and loss","1406700"),
    ("恐慌","きょうこう","n","khủng hoảng (kinh tế) | hoảng loạn","panic | financial panic","1236710"),
    ("抵当","ていとう","n|adj-no","thế chấp | cầm cố | vật bảo đảm","mortgage | security | pledge","1436290"),
    ("税収","ぜいしゅう","n","nguồn thu thuế | thuế thu được","tax yields | revenue","1382120"),
    ("関税","かんぜい","n","thuế quan | thuế nhập khẩu","customs duties | tariff","1215930"),
    ("免税","めんぜい","n|vs|vt|vi|adj-no","miễn thuế","tax exemption | duty exemption","1533230"),
    ("課税","かぜい","n|vs|vi","đánh thuế | áp thuế","taxation","1195790"),
    ("解約","かいやく","n|vs|vt","hủy hợp đồng | hủy giao kèo","cancellation of a contract","1199300"),
    ("違約","いやく","n|vs|vi","vi phạm hợp đồng | bội ước","breach of contract | default","1158970"),
    ("賠償","ばいしょう","n|vs|vt","bồi thường | đền bù thiệt hại","compensation | reparations | damages","1474110"),
    ("弁償","べんしょう","n|vs|vt","đền bù | bồi hoàn","compensation | indemnification | restitution","1512980"),
    ("慰謝料","いしゃりょう","n","tiền bồi thường tinh thần | tiền an ủi","consolation money | reparation | damages","1156930"),
    ("弁論","べんろん","n|vs|vt|adj-no","tranh luận | biện luận | hùng biện","discussion | debate | argument","1513170"),
    ("審理","しんり","n|vs|vt","xét xử | thẩm lý","trial","1360470"),
    ("有罪","ゆうざい","n|adj-no","có tội | phạm tội","guilt | culpability","1541350"),
    ("無罪","むざい","n|adj-no","vô tội | trắng án","innocence | being not guilty","1529980"),
    ("量刑","りょうけい","n|vs|vi","lượng hình | mức án | định hình phạt","judge's sentence | assessment of a case","1644830"),
    ("懲役","ちょうえき","n","tù khổ sai | án tù lao động","penal servitude | imprisonment with hard labor","1428220"),
    ("保釈","ほしゃく","n|vs|vt","bảo lãnh tại ngoại | tại ngoại","bail | releasing on bail","1513720"),
    ("仮釈放","かりしゃくほう","n|vs","tạm tha | thả có điều kiện | ân xá có điều kiện","releasing on parole | conditional release","1187510"),
    ("撤廃","てっぱい","n|vs|vt","bãi bỏ | hủy bỏ | dỡ bỏ","annulment | abolition | repeal","1437750"),
    ("廃止","はいし","n|vs|vt","bãi bỏ | đình chỉ | hủy bỏ","abolition | discontinuance | repeal","1472100"),
    ("制定","せいてい","n|vs|vt","ban hành | chế định | thiết lập","enactment | establishment","1374870"),
    ("公布","こうふ","n|vs|vt","công bố | ban bố (luật)","official proclamation | promulgation","1274570"),
    ("立法","りっぽう","n|vs|vt|vi|adj-f","lập pháp | làm luật","legislation | lawmaking","1551840"),
    ("司法","しほう","n","tư pháp | xét xử","administration of justice | judicature","1306680"),
    ("管轄","かんかつ","n|vs|vt|adj-no","quản hạt | thẩm quyền | phạm vi quản lý","jurisdiction | control","1214090"),
    ("裁量","さいりょう","n|vs|vt","tự quyết | toàn quyền xét đoán | tùy nghi","discretion | judgement","1296220"),
    ("批准","ひじゅん","n|vs|vt","phê chuẩn (hiệp ước)","ratification","1483390"),
    ("公示","こうじ","n|vs|vt","công bố chính thức | yết thị","public announcement | official notice","1273810"),
    ("告示","こくじ","n|vs|vt","cáo thị | thông báo | yết bảng","notice | bulletin","1286010"),
    ("通達","つうたつ","n|vs|vt|vi","thông tri | chỉ thị | thông thạo","notification | directive | being well versed","1433460"),
    ("省庁","しょうちょう","n","các bộ ngành | cơ quan chính phủ","ministries and government offices","1351100"),
    ("自治体","じちたい","n","chính quyền địa phương | đơn vị tự trị","municipality | local government","1317830"),
    ("首長","しゅちょう","n","người đứng đầu | thủ trưởng | tù trưởng","head (of organization) | chief","1329320"),
    ("動向","どうこう","n","động thái | xu hướng | diễn biến","trend | tendency | movement","1451330"),
    ("扶養","ふよう","n|vs|vt","cấp dưỡng | nuôi dưỡng | phụng dưỡng","support (of dependents) | maintenance","1496990"),
    ("過疎","かそ","n|adj-no","thưa dân | giảm dân số | dân cư thưa thớt","underpopulation | depopulation","1196220"),
    ("防犯","ぼうはん","n|adj-no|n-pref","phòng chống tội phạm | an ninh","prevention of crime | security","1520570"),
    ("摘発","てきはつ","n|vs|vt","phanh phui | vạch trần | phát giác","exposing | unmasking | laying bare","1437080"),
    ("検挙","けんきょ","n|vs|vt","bắt giữ | truy quét | tóm cổ","arrest | roundup","1257880"),
    ("尋問","じんもん","n|vs|vt","thẩm vấn | tra hỏi | hỏi cung","questioning | interrogation","1369980"),
    ("物証","ぶっしょう","n","vật chứng | bằng chứng vật chất","physical evidence | material evidence","1502580"),
    ("鑑定","かんてい","n|vs|vt|adj-no","giám định | thẩm định | định giá","judgement | expert opinion | appraisal","1215210"),
    ("偵察","ていさつ","n|vs|vt","trinh sát | do thám","scouting | reconnaissance","1435100"),
    ("潜入","せんにゅう","n|vs|vi","xâm nhập | trà trộn | hoạt động ngầm","infiltration | sneaking in | going undercover","1391360"),
    ("密輸","みつゆ","n|vs|vt","buôn lậu | nhập lậu","smuggling | contraband trade","1528370"),
    ("横領","おうりょう","n|vs|vt","biển thủ | tham ô | chiếm dụng","embezzlement | misappropriation","1181130"),
    ("贈賄","ぞうわい","n|vs|vi","đưa hối lộ | hối lộ","giving a bribe | bribery","1403610"),
    ("収賄","しゅうわい","n|vs|vt|vi","nhận hối lộ | ăn hối lộ","accepting a bribe","1330990"),
    ("汚職","おしょく","n|vs|vi","tham nhũng | hối lộ | tham ô","corruption | bribery | graft","1179010"),
    ("詐欺","さぎ","n","lừa đảo | lừa gạt | bịp bợm","fraud | swindle | scam","1291690"),
    ("恐喝","きょうかつ","n|vs|vt","tống tiền | hăm dọa moi tiền","blackmail | extortion","1236700"),
    ("脅迫","きょうはく","n|vs|vt","đe dọa | uy hiếp | cưỡng ép","threat | menace | coercion","1238110"),
    ("誘拐","ゆうかい","n|vs|vt","bắt cóc | dụ dỗ bắt đi","abduction | kidnapping","1541930"),
    ("暴行","ぼうこう","n|vs|vt|vi","hành hung | bạo hành | cưỡng hiếp","assault | act of violence | sexual assault","1519460"),
    ("傷害","しょうがい","n|vs|vt","gây thương tích | cố ý gây thương tích","injury | inflicting bodily injury","1345840"),
    ("殺人","さつじん","n|vs|vt|vi","giết người | sát nhân","murder | homicide | manslaughter","1299100"),
    ("窃盗","せっとう","n|vs|vt|adj-no","trộm cắp | ăn trộm","theft | stealing | larceny","1386110"),
    ("強盗","ごうとう","n","cướp | kẻ cướp | vụ cướp","robber | robbery | burglary","1236500"),
    ("放火","ほうか","n|vs|vi|adj-no","phóng hỏa | đốt nhà | cố ý gây cháy","arson | setting fire","1516560"),
    ("密告","みっこく","n|vs|vt","tố giác ngầm | mật báo | chỉ điểm","anonymous report | tip-off | informing","1528250"),
    ("内偵","ないてい","n|vs|vt","điều tra ngầm | điều tra bí mật | trinh sát","secret investigation | reconnaissance","1458910"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
