# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-011.csv — 18 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-011.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("痒い","かゆい","N4","adj-i",
        "ngứa | ngứa ngáy",
        "itchy",
        "1569570",
        "背中が痒いです。","せなかがかゆいです。","Lưng tôi ngứa.","My back is itchy."),
    row("眩しい","まぶしい","N4","adj-i",
        "chói mắt | lấp lánh | rực rỡ",
        "dazzling | radiant",
        "1569790",
        "光が眩しいです。","ひかりがまぶしいです。","Ánh sáng chói mắt.","The light is dazzling."),
    row("ホームページ","ホームページ","N4","n",
        "trang chủ (của một trang web hoặc trình duyệt) | trang web",
        "home page (of a website or browser) | homepage | web page | website",
        "1648000",
        "ホームページを作ります。","ホームページをつくります。","Tôi tạo trang web.","I create a website."),
    row("ボランティア活動","ボランティアかつどう","N4","n",
        "hoạt động tình nguyện | tinh thần tình nguyện",
        "volunteer activities | volunteerism",
        "1968470",
        "ボランティア活動に参加します。","ボランティアかつどうにさんかします。","Tôi tham gia hoạt động tình nguyện.","I participate in volunteer activities."),
    row("プレゼン","プレゼン","N4","n|vs",
        "bài thuyết trình | buổi trình bày",
        "presentation",
        "1981320",
        "プレゼンをします。","プレゼンをします。","Tôi trình bày.","I give a presentation."),
    row("ウェブサイト","ウェブサイト","N4","n",
        "trang web",
        "website | web site",
        "1986140",
        "ウェブサイトを見ます。","ウェブサイトをみます。","Tôi xem trang web.","I look at the website."),
    row("腕","かいな","N4","n",
        "cánh tay | bắp tay trên",
        "arm | upper arm",
        "2139850",
        "腕を伸ばします。","かいなをのばします。","Tôi duỗi cánh tay.","I extend my arm."),
    row("注ぐ","つぐ","N4","v5g|vt",
        "rót vào (bình chứa) | đổ đầy (cốc, bát...) | múc ra (thức ăn, đồ uống)",
        "to pour (into a vessel) | to fill (a cup, bowl, etc.) with | to dish out (food or drink)",
        "2145240",
        "お茶を注ぎます。","おちゃをつぎます。","Tôi rót trà.","I pour tea."),
    row("顔","かんばせ","N4","n",
        "vẻ mặt | dung mạo | nét mặt | khuôn mặt | danh dự | thể diện | phẩm giá",
        "countenance | visage | (facial) features | face | looks | honor (honour) | face | dignity",
        "2221310",
        "美しい顔です。","うつくしいかんばせです。","Là khuôn mặt đẹp.","A beautiful countenance."),
    row("木","もく","N4","n",
        "thứ Năm | gỗ (nguyên tố đầu tiên trong ngũ hành)",
        "Thursday | wood (first of the five elements)",
        "2248570",
        "木曜日に会います。","もくようびにあいます。","Chúng tôi gặp nhau vào thứ Năm.","We meet on Thursday."),
    row("土","ど","N4","n",
        "thứ Bảy | đất | đất đai | mặt đất | đất (hành đất trong ngũ hành)",
        "Saturday | earth | dirt | soil | land | ground | earth (third of the five elements)",
        "2248580",
        "土曜日は休みです。","どようびはやすみです。","Thứ Bảy là ngày nghỉ.","Saturday is a day off."),
    row("次に","つぎに","N4","conj",
        "tiếp theo | sau đó | sau đó thì",
        "next | then | after that",
        "2600340",
        "次に何をしますか。","つぎになにをしますか。","Tiếp theo bạn làm gì?","What do you do next?"),
    row("細い","こまい","N4","adj-i",
        "nhỏ | mịn | tinh vi | bủn xỉn | rẻ tiền",
        "small | fine | minute | stingy | cheap",
        "2719870",
        "細かいことを気にします。","こまかいことをきにします。","Tôi để ý những chi tiết nhỏ.","I pay attention to small details."),
    row("能力","のうりき","N4","n",
        "tu sĩ cấp thấp làm công việc chân tay tại chùa | nhân viên nam của chùa",
        "low-ranking priest who does manual labour at a temple | male temple employee",
        "2721460"),
    row("噛む","しがむ","N4","v5m|vt",
        "nhai (mạnh)",
        "to chew (strongly)",
        "2826405",
        "よく噛みます。","よくしがみます。","Tôi nhai kỹ.","I chew thoroughly."),
    row("先生","せんじょう","N4","n",
        "thầy giáo | người hướng dẫn | bậc thầy | tiền kiếp",
        "teacher | instructor | master | previous existence",
        "2841735",
        "先生に習います。","せんじょうにならいます。","Tôi học từ thầy giáo.","I learn from the teacher."),
    row("船","せん","N4","n-suf",
        "tàu | thuyền | tàu thuyền",
        "ship | boat | vessel",
        "2855971",
        "渡し船があります。","わたしせんがあります。","Có thuyền phà.","There is a ferry boat."),
    row("クラウド","クラウド","N4","n",
        "đám đông",
        "crowd",
        "2857863",
        "クラウドに囲まれます。","クラウドにかこまれます。","Tôi bị bao quanh bởi đám đông.","I am surrounded by a crowd."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
