# -*- coding: utf-8 -*-
"""Build N1 ready wave 083 — advanced katakana loanwords (set 83)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n1-vi-ready-083.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N1"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("アースカラー","アースカラー","n","tông màu đất | màu trung tính tự nhiên | màu nâu xám tự nhiên","earth color","1013510"),
    ("アグリーメント","アグリーメント","n","sự đồng thuận | thỏa thuận | hiệp định","agreement","1015540"),
    ("アコモデーション","アコモデーション","n","chỗ ở | nơi lưu trú | tiện nghi ăn ở","accommodation","2447320"),
    ("アスピレーション","アスピレーション","n","khát vọng | hoài bão | ước mơ | nguyện vọng","aspiration | ambition","2836352"),
    ("アディクション","アディクション","n","sự nghiện | chứng nghiện | sự lệ thuộc","addiction","2855936"),
    ("アドミニストレーション","アドミニストレーション","n","sự quản lý | bộ máy hành chính | việc điều hành","administration","2280220"),
    ("アファーマティブ","アファーマティブ","adj-f","khẳng định | tích cực ủng hộ | mang tính ưu đãi","affirmative","2754730"),
    ("アンコール","アンコール","n|vs|vt|vi","sự yêu cầu diễn lại | màn diễn lại theo yêu cầu | encore","encore","1019950"),
    ("インバウンド","インバウンド","adj-no|n","du lịch nội địa (khách nước ngoài đến) | hướng vào trong | inbound","inbound (tourism)","2283900"),
    ("インフォメーション","インフォメーション","n","thông tin | quầy thông tin | tin tức","information","1024190"),
    ("インプット","インプット","n|vs|vt","đầu vào | dữ liệu nhập | sự nạp vào","input","1024470"),
    ("ウィークポイント","ウィークポイント","n","điểm yếu | nhược điểm | chỗ sơ hở","weak point","1025310"),
    ("ウィスパー","ウィスパー","n","tiếng thì thầm | lời thì thào | giọng nói khẽ","whisper","2440750"),
    ("エクスペリエンス","エクスペリエンス","n","trải nghiệm | kinh nghiệm | sự từng trải","experience","2458370"),
    ("エンゲージメント","エンゲージメント","n","sự gắn kết | mức độ tương tác | sự cam kết tham gia | hôn ước","engagement","1030840"),
    ("エンジニアリング","エンジニアリング","n","kỹ thuật | công trình kỹ thuật | ngành kỹ sư","engineering","1030920"),
    ("エンドユーザー","エンドユーザー","n","người dùng cuối | khách hàng tiêu thụ cuối","end user","1031230"),
    ("オーセンティシティ","オーセンティシティ","n","tính xác thực | sự chân thực | tính nguyên bản","authenticity","2060260"),
    ("オーディエンス","オーディエンス","n","khán giả | thính giả | người xem | công chúng","audience","1031820"),
    ("オピニオン","オピニオン","n","ý kiến | quan điểm | nhận định","opinion","1034580"),
    ("オリジン","オリジン","n","nguồn gốc | xuất xứ | căn nguyên | gốc rễ","origin","1035680"),
    ("カウンターカルチャー","カウンターカルチャー","n","văn hóa phản kháng | văn hóa đối nghịch | trào lưu phản văn hóa","counterculture","2187340"),
    ("カタルシス","カタルシス","n","sự giải tỏa cảm xúc | thanh tẩy tâm hồn | sự xả cảm","catharsis","1037550"),
    ("クライテリア","クライテリア","n","tiêu chí | tiêu chuẩn đánh giá | chuẩn mực","criteria","1043910"),
    ("クラスター","クラスター","n|n-suf","cụm | nhóm | chùm | cụm lây nhiễm | bè phái","cluster","1044090"),
    ("グルーミング","グルーミング","n","sự chải chuốt | việc chăm sóc ngoại hình | vệ sinh cá nhân","grooming","2469290"),
    ("ゲーミフィケーション","ゲーミフィケーション","n","game hóa | ứng dụng yếu tố trò chơi | trò chơi hóa","gamification","2704350"),
    ("コンサルティング","コンサルティング","n","tư vấn | dịch vụ tư vấn | cố vấn chuyên môn","consulting","1052070"),
    ("コンテキスト","コンテキスト","n","ngữ cảnh | bối cảnh | mạch văn","context","1036030"),
    ("コンテンポラリー","コンテンポラリー","adj-na","đương đại | hiện đại | cùng thời","contemporary","1052660"),
    ("コンビネーション","コンビネーション","n","sự kết hợp | tổ hợp | sự phối hợp","combination","1053320"),
    ("コンフリクト","コンフリクト","n|vs","sự xung đột | mâu thuẫn | sự va chạm | tranh chấp","conflict","1053720"),
    ("サーベイ","サーベイ","n","cuộc khảo sát | điều tra | khảo cứu","survey","1055200"),
    ("サブスクリプション","サブスクリプション","n","gói đăng ký | hình thức thuê bao | đặt mua định kỳ","subscription","2497990"),
    ("シーケンス","シーケンス","n","trình tự | chuỗi liên tiếp | dãy | trình tự diễn biến","sequence","1059120"),
    ("ジェノサイド","ジェノサイド","n","tội diệt chủng | nạn diệt chủng | sự tàn sát hàng loạt","genocide","1064410"),
    ("ジオメトリー","ジオメトリー","n","hình học | môn hình học","geometry","1064560"),
    ("シナプス","シナプス","n|adj-no","khớp thần kinh | điểm nối nơ-ron | synap","synapse","1060810"),
    ("シンクタンク","シンクタンク","n","viện nghiên cứu chính sách | tổ chức cố vấn | nhóm chuyên gia tư vấn","think tank","1063450"),
    ("スキャンダラス","スキャンダラス","adj-na","tai tiếng | bê bối | gây xì căng đan","scandalous","1068000"),
    ("スクラップ","スクラップ","n|vs|vt","phế liệu | sắt vụn | mẩu báo cắt | sưu tập cắt dán","scrap | a clipping","1068420"),
    ("スタートアップ","スタートアップ","n","công ty khởi nghiệp | sự khởi động | startup | khởi chạy","startup","2303530"),
    ("スパルタ","スパルタ","n|adj-na","kiểu Sparta | rèn luyện hà khắc | giáo dục nghiêm khắc | khổ luyện","Spartan (strict, severe) education","2854605"),
    ("スペクタクル","スペクタクル","n|adj-na","cảnh tượng hoành tráng | màn trình diễn ngoạn mục | bom tấn","spectacle | spectacular","1073010"),
    ("セパレート","セパレート","adj-f","tách rời | riêng biệt | rời nhau","separate","1984070"),
    ("セルフコントロール","セルフコントロール","n","sự tự chủ | khả năng kiềm chế bản thân | tự kiểm soát","self-control","2422430"),
    ("セレンディピティ","セレンディピティ","n","sự tình cờ may mắn | duyên may bất ngờ | khả năng phát hiện may mắn","serendipity","2473420"),
    ("ソリッド","ソリッド","n","rắn chắc | vững chắc | đặc | thể rắn","solid","1075590"),
    ("ターミナル","ターミナル","n","nhà ga cuối | bến cuối | điểm đầu cuối | thiết bị đầu cuối","terminal","1075760"),
    ("タイムリー","タイムリー","adj-na|n","đúng lúc | kịp thời | hợp thời điểm | cú đánh ghi điểm","timely | well-timed","1076090"),
    ("ダイナミズム","ダイナミズム","n","tính năng động | sức sống mạnh mẽ | động lực sôi nổi","dynamism","1076810"),
    ("ダブルスタンダード","ダブルスタンダード","n","tiêu chuẩn kép | sự đối xử bất nhất | luật chơi hai mặt","double standard","2447750"),
    ("チームワーク","チームワーク","n","tinh thần đồng đội | sự phối hợp nhóm | làm việc nhóm","teamwork","1077370"),
    ("ディスコース","ディスコース","n","diễn ngôn | bài thuyết trình | ngôn bản | sự bàn luận","discourse","2845975"),
    ("ディメンション","ディメンション","n","chiều | kích thước | chiều không gian | phương diện","dimension","1082390"),
    ("デバッグ","デバッグ","n|vs|vt","sự gỡ lỗi | tìm và sửa lỗi (phần mềm) | khử lỗi","debugging","1083560"),
    ("デリゲーション","デリゲーション","n","đoàn đại biểu | sự ủy quyền | sự phân quyền","delegation","1084330"),
    ("トレードオフ","トレードオフ","n","sự đánh đổi | được cái này mất cái kia | cân bằng đánh đổi","trade-off","1087040"),
    ("ドラフト","ドラフト","n","bản nháp | bản phác thảo | sự tuyển chọn (thể thao) | bia tươi","draft","1088810"),
    ("ナラティブ","ナラティブ","n","sự tường thuật | câu chuyện | mạch truyện | lối kể","narrative","2829425"),
    ("ノミナル","ノミナル","adj-na","trên danh nghĩa | hình thức | danh nghĩa","nominal","1094070"),
    ("バイアグラ","バイアグラ","n","Viagra | thuốc cường dương","Viagra","2093050"),
    ("バリアフリー","バリアフリー","adj-no|n","không rào cản | thiết kế thuận tiện cho người khuyết tật/cao tuổi","barrier-free","1957980"),
    ("パブリシティー","パブリシティー","n","sự công khai | quảng bá | tuyên truyền công chúng | tiếng tăm","publicity","1102270"),
    ("ビジネスライク","ビジネスライク","adj-na","kiểu cách công việc | chuyên nghiệp | thực dụng rạch ròi","businesslike","1104940"),
    ("ピンポイント","ピンポイント","n","chính xác từng điểm | nhắm trúng đích | điểm cụ thể","pinpoint","1107300"),
    ("フィランソロピー","フィランソロピー","n","hoạt động từ thiện | lòng nhân ái | sự bác ái xã hội","philanthropy","2472000"),
    ("フェアプレー","フェアプレー","n","chơi đẹp | tinh thần thượng võ | sự công bằng fair-play","fair play","1109650"),
    ("フェノメノン","フェノメノン","n","hiện tượng | điều phi thường | hiện tượng lạ","phenomenon","1109890"),
    ("プラクティカル","プラクティカル","adj-na","thực tế | thực dụng | thiết thực | mang tính ứng dụng","practical","1115560"),
    ("プラグマティック","プラグマティック","adj-na","thực dụng | thực tế | thiết thực","pragmatic","2493430"),
    ("ブレークスルー","ブレークスルー","n","bước đột phá | sự khai thông | bước ngoặt lớn","breakthrough","2025840"),
    ("ベンチャー","ベンチャー","n","doanh nghiệp mạo hiểm | công ty khởi nghiệp | đầu tư mạo hiểm","venture","1120330"),
    ("ボトルネック","ボトルネック","n","nút thắt cổ chai | điểm nghẽn | chỗ ách tắc | giới hạn cản trở","bottleneck","1124190"),
    ("ポピュラリティー","ポピュラリティー","n","sự nổi tiếng | mức độ phổ biến | sự được ưa chuộng","popularity","1125510"),
    ("マイルド","マイルド","adj-na","nhẹ nhàng | dịu | êm dịu | nhẹ (vị)","mild","1127100"),
    ("マインドフルネス","マインドフルネス","n","sự chánh niệm | sự tỉnh thức | sự sống trong hiện tại","mindfulness","2841997"),
    ("マテリアル","マテリアル","n","vật liệu | nguyên liệu | chất liệu | tư liệu","material","1128580"),
    ("ミニマル","ミニマル","adj-na","tối giản | giản lược | tối thiểu","minimal","2792310"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
