# -*- coding: utf-8 -*-
"""Build N2 ready wave 048 — clothing/attire, kimono, accessories, makeup, hair grooming."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-048.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("装い","よそおい","n","trang phục | cách ăn mặc | trang điểm | dáng vẻ","dress | outfit | makeup | guise","1855190"),
    ("身なり","みなり","n","trang phục | cách ăn vận | bề ngoài","dress | attire | personal appearance","1365570"),
    ("着こなし","きこなし","n","cách phối đồ | cách mặc | gu ăn mặc","manner of wearing clothes | way of dressing","2012230"),
    ("正装","せいそう","n|vs|vi","trang phục trang trọng | lễ phục | đồng phục","full dress | formal dress","1377480"),
    ("礼装","れいそう","n|vs|vi","lễ phục | trang phục nghi lễ","formal dress","1843410"),
    ("盛装","せいそう","n|vs|vi","ăn diện | trang phục lộng lẫy | đồ đẹp nhất","dressing up in fine clothes | one's best clothes","1379810"),
    ("平服","へいふく","n|adj-no","thường phục | quần áo thường ngày | đồ dân sự","ordinary clothes | plain clothes","1507830"),
    ("よそ行き","よそゆき","n|adj-no","đi ra ngoài | đồ đẹp nhất | (cách nói) trang trọng","going out | one's best clothes | formal","1584940"),
    ("晴れ着","はれぎ","n","quần áo đẹp | đồ diện dịp lễ | y phục ngày trọng đại","one's best clothes | glad rags","1601150"),
    ("喪服","もふく","n","tang phục | quần áo tang | đồ chịu tang","mourning clothes | mourning dress","1399340"),
    ("洋装","ようそう","n|vs|vi","trang phục kiểu Tây | đóng bìa kiểu Tây","Western clothing | Western binding","1794510"),
    ("着物","きもの","n","kimono | y phục truyền thống Nhật | quần áo","kimono | Japanese traditional clothing","1423240"),
    ("羽織","はおり","n","haori | áo khoác ngoài kimono","haori (Japanese formal coat)","1171770"),
    ("雪駄","せった","n","dép geta đế da","leather-soled sandals (geta)","1596110"),
    ("襟元","えりもと","n","vùng cổ | gáy | phần cổ áo","(around the) neck | nape | collar area","1242010"),
    ("袖口","そでぐち","n","cổ tay áo | măng-séc | lỗ tay áo","cuff | armhole","1406010"),
    ("裾野","すその","n","chân núi | đồng bằng dưới chân núi | phạm vi | mức lan tỏa","foot of a mountain | range | extent","1718020"),
    ("裏地","うらじ","n","lớp lót | vải lót (áo)","lining","1550450"),
    ("着丈","きたけ","n","chiều dài áo","dress length","1423070"),
    ("身丈","みたけ","n","chiều dài thân áo","length (of clothing)","1365710"),
    ("袖丈","そでたけ","n","chiều dài tay áo","length of a sleeve","1695230"),
    ("試着室","しちゃくしつ","n","phòng thử đồ","dressing room | fitting room","1312510"),
    ("鏡台","きょうだい","n","bàn trang điểm | tủ gương trang điểm","dresser | dressing table | vanity table","1238570"),
    ("姿見","すがたみ","n","gương soi toàn thân","full-length mirror","1307730"),
    ("薄化粧","うすげしょう","n|vs|vi","trang điểm nhẹ | lớp tuyết mỏng phủ","light makeup | light covering of snow","1475550"),
    ("厚化粧","あつげしょう","n|vs|vi","trang điểm đậm | đánh phấn dày","thick makeup | heavy makeup","1275400"),
    ("素顔","すがお","n","mặt mộc | gương mặt thật | bộ mặt thật (của ai)","face with no make-up | true face","1397190"),
    ("身支度","みじたく","n|vs|vi","sửa soạn trang phục | chuẩn bị ăn mặc | sắm sửa","dress | outfit | to dress oneself","1705810"),
    ("身繕い","みづくろい","n|vs|vi","sửa soạn quần áo | chỉnh trang bản thân","dressing oneself | personal grooming","1365560"),
    ("身だしなみ","みだしなみ","n","tác phong ăn mặc | sự gọn gàng tươm tất | kỹ năng cần có","(personal) appearance | grooming | essential skill","2114830"),
    ("めかし込む","めかしこむ","v5m|vi","ăn diện | chưng diện | trang điểm bảnh bao","to dress oneself up | to deck oneself out","2009860"),
    ("着飾る","きかざる","v5r|vt","ăn diện | chưng diện | diện đồ đẹp","to dress up","1423080"),
    ("重ね着","かさねぎ","n|vs|vt|vi","mặc nhiều lớp | mặc chồng đồ","layering (clothing)","1335910"),
    ("薄着","うすぎ","n|vs|adj-no","mặc mỏng manh | mặc phong phanh","being lightly dressed","1475620"),
    ("厚着","あつぎ","n|vs|vi","mặc dày | mặc ấm | mặc nhiều đồ","wearing thick clothes | dressing warmly","1275560"),
    ("肌着","はだぎ","n","áo lót | đồ lót | áo trong","underwear | underclothes | lingerie","1476500"),
    ("寝巻き","ねまき","n","đồ ngủ | quần áo ngủ | áo ngủ","nightclothes | sleepwear | pajamas","1360040"),
    ("普段","ふだん","adj-no|n|adv","thường ngày | bình thường | hằng ngày | thường lệ","usual | everyday | habitual | normally","1497180"),
    ("作業着","さぎょうぎ","n","quần áo bảo hộ lao động | đồ làm việc","work clothes | fatigues","2112130"),
    ("礼帽","れいぼう","n","mũ nghi lễ","ceremonial hat","1843400"),
    ("頭巾","ずきん","n","khăn trùm đầu | mũ trùm | khăn bịt đầu","headgear | hood | kerchief | cap","1450830"),
    ("靴墨","くつずみ","n","xi đánh giày","shoe polish","1246810"),
    ("靴磨き","くつみがき","n","đánh giày | việc đánh bóng giày","shoeshine | shoe polishing","1246820"),
    ("雨具","あまぐ","n","đồ đi mưa | dụng cụ che mưa","rain gear","1171940"),
    ("日傘","ひがさ","n","ô che nắng | dù chống nắng","parasol | sunshade","1464080"),
    ("雨傘","あまがさ","n","ô che mưa | dù đi mưa","umbrella","1586610"),
    ("扇子","せんす","n","quạt xếp | quạt giấy","folding fan","1390730"),
    ("団扇","うちわ","n","quạt nan | quạt tròn cầm tay","uchiwa | traditional handheld fan","1419250"),
    ("老眼鏡","ろうがんきょう","n","kính lão | kính viễn (cho người lớn tuổi)","reading glasses | spectacles for the aged","1644540"),
    ("色眼鏡","いろめがね","n","kính màu | kính râm | cái nhìn định kiến","coloured glasses | sunglasses | biased view","1357650"),
    ("懐中時計","かいちゅうどけい","n","đồng hồ bỏ túi","pocket watch","2846023"),
    ("首飾り","くびかざり","n","vòng cổ | dây chuyền","necklace | choker","1329280"),
    ("腕輪","うでわ","n","vòng tay | lắc tay","bracelet | bangle","1562960"),
    ("耳飾り","みみかざり","n","khuyên tai | bông tai","earring","1317260"),
    ("髪飾り","かみかざり","n","đồ trang trí tóc | phụ kiện tóc","hair ornament","1477980"),
    ("簪","かんざし","n","trâm cài tóc | kẹp tóc trang trí","ornamental hairpin","1985350"),
    ("櫛","くし","n","cái lược","comb","1246490"),
    ("化粧水","けしょうすい","n","nước hoa hồng | toner | lotion dưỡng da","skin lotion | face lotion","1577050"),
    ("乳液","にゅうえき","n","sữa dưỡng | nhũ tương dưỡng da | mủ cây","milky lotion (cosmetic) | latex","1464990"),
    ("口紅","くちべに","n|adj-no","son môi","lipstick","1276110"),
    ("頬紅","ほおべに","n","má hồng | phấn má","cheek rouge | blusher","1520640"),
    ("白粉","おしろい","n","phấn trắng | phấn phủ mặt","white makeup powder | (face) powder","1609400"),
    ("整髪","せいはつ","n|vs|vt|vi","làm tóc | tạo kiểu tóc | chải chuốt tóc","hairdressing","1764810"),
    ("散髪","さんぱつ","n|vs|vi","cắt tóc | hớt tóc | tóc rối bù","(having a) haircut | unkempt hair","1303590"),
    ("理髪","りはつ","n|vs|vi|adj-no","cắt tóc | hớt tóc","haircut","1550070"),
    ("調髪","ちょうはつ","n|vs|vi","cắt tỉa tóc | chỉnh trang tóc","haircut | barbering","1717090"),
    ("丸刈り","まるがり","n|adj-no","cắt tóc cua | cạo trọc lủi | tóc ngắn sát","buzz cut | close crop","1216340"),
    ("角刈り","かくがり","n","tóc đầu đinh | kiểu tóc dựng vuông","crew cut","1836670"),
    ("坊主","ぼうず","n","nhà sư | đầu trọc | tóc cạo trọc | thằng nhóc | về tay không","Buddhist priest | close-cropped hair | boy | getting skunked","1519080"),
    ("癖毛","くせげ","n","tóc xoăn tự nhiên | tóc rối khó vào nếp","kinky hair | frizzy hair | unruly hair","1640600"),
    ("天然パーマ","てんねんパーマ","n","tóc xoăn tự nhiên","naturally curly hair","2620890"),
    ("若白髪","わかしらが","n","tóc bạc sớm | bạc tóc khi còn trẻ","prematurely gray hair","1762470"),
    ("抜け毛","ぬけげ","n","tóc rụng | rụng tóc","fallen hair | combings","1643350"),
    ("枝毛","えだげ","n","tóc chẻ ngọn","split end of hair","1624240"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
