# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-049.csv -- 17 rows."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-049.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("検索","けんさく","N4","n|vs|vt",
        "tìm kiếm | tra cứu | tra từ điển",
        "looking up (e.g. a word in a dictionary) | search (e.g. on the Internet) | retrieval",
        "1257900",
        "インターネットで検索する。","いんたーねっとでけんさくする。",
        "Tìm kiếm trên Internet.","Search on the Internet."),
    row("更新","こうしん","N4","n|vs|vt",
        "cập nhật | gia hạn | đổi mới | phá kỷ lục",
        "renewal | update | replacement | renovation | breaking (a record)",
        "1279370",
        "ソフトを更新する。","そふとをこうしんする。",
        "Cập nhật phần mềm.","Update the software."),
    row("国語","こくご","N4","n",
        "ngôn ngữ quốc gia | tiếng Nhật (môn học)",
        "national language | Japanese language (esp. as a school subject in Japan)",
        "1286370",
        "国語の授業。","こくごのじゅぎょう。",
        "Giờ học tiếng Nhật.","Japanese language class."),
    row("指揮","しき","N4","n|vs|vt",
        "chỉ huy | điều hành | chỉ đạo | bắt nhịp (dàn nhạc)",
        "command | direction | supervision | conducting (an orchestra, choir, etc.)",
        "1309700",
        "楽団を指揮する。","がくだんをしきする。",
        "Bắt nhịp ban nhạc.","Conduct an orchestra."),
    row("柔道","じゅうどう","N4","n",
        "judo | nhu đạo | võ judo",
        "judo",
        "1335440",
        "柔道の黒帯。","じゅうどうのくろおび。",
        "Đai đen judo.","A black belt in judo."),
    row("相撲","すもう","N4","n",
        "sumo | đấu vật sumo | lực sĩ sumo",
        "sumo (wrestling) | sumo wrestler",
        "1401360",
        "相撲を見に行く。","すもうをみにいく。",
        "Đi xem sumo.","Go to watch sumo wrestling."),
    row("道徳","どうとく","N4","n",
        "đạo đức | đức hạnh | luân lý",
        "morals | morality",
        "1454240",
        "道徳を学ぶ。","どうとくをまなぶ。",
        "Học về đạo đức.","Learn about morality."),
    row("体操","たいそう","N4","n|vs|vi",
        "thể dục | thể dục dụng cụ | tập thể dục",
        "gymnastics | physical exercises | artistic gymnastics | gymnastics competition",
        "1409580",
        "朝体操をする。","あさたいそうをする。",
        "Tập thể dục buổi sáng.","Do morning exercises."),
    row("保存","ほぞん","N4","n|vs|vt",
        "bảo tồn | lưu trữ | bảo quản | lưu file",
        "preservation | conservation | storage | maintenance | save (to storage)",
        "1513940",
        "ファイルを保存する。","ふぁいるをほぞんする。",
        "Lưu file.","Save the file."),
    row("充電","じゅうでん","N4","n|vs|vi|vt",
        "sạc pin | nạp điện | hồi phục năng lượng",
        "charging (electrically) | recharging one's batteries (e.g. by taking a vacation)",
        "1334390",
        "スマホを充電する。","すまほをじゅうでんする。",
        "Sạc điện thoại.","Charge the smartphone."),
    row("充電器","じゅうでんき","N4","n",
        "bộ sạc pin | bộ sạc | adapter",
        "(battery) charger | AC adapter",
        "1334400",
        "充電器を貸す。","じゅうでんきをかす。",
        "Cho mượn bộ sạc.","Lend a charger."),
    row("削除","さくじょ","N4","n|vs|vt",
        "xóa | xóa bỏ | loại bỏ | xóa dữ liệu",
        "deletion | elimination | erasure | striking out",
        "1298120",
        "データを削除する。","でーたをさくじょする。",
        "Xóa dữ liệu.","Delete data."),
    row("剣道","けんどう","N4","n",
        "kendo | kiếm đạo | võ kiếm Nhật",
        "kendo | Japanese martial art using bamboo swords",
        "1256910",
        "剣道の練習。","けんどうのれんしゅう。",
        "Luyện tập kendo.","Kendo practice."),
    row("合唱","がっしょう","N4","n|vs|vi",
        "hợp xướng | đồng ca | hát đồng thanh",
        "singing together | singing in unison | chorus | ensemble singing",
        "1284870",
        "合唱コンクール。","がっしょうこんくーる。",
        "Hội thi hợp xướng.","A choral competition."),
    row("接続","せつぞく","N4","n|vs|vt|vi",
        "kết nối | liên kết | nối mạng | chuyển tàu",
        "connection | attachment | union | join | joint | link | changing trains",
        "1385480",
        "インターネットに接続する。","いんたーねっとにせつぞくする。",
        "Kết nối với Internet.","Connect to the Internet."),
    row("登録","とうろく","N4","n|vs|vt",
        "đăng ký | ghi danh | đăng ký tài khoản",
        "registration | accession | register | entry | record | subscription",
        "1444810",
        "会員登録する。","かいいんとうろくする。",
        "Đăng ký thành viên.","Register as a member."),
    row("算数","さんすう","N4","n",
        "số học | tính toán | môn toán (tiểu học)",
        "arithmetic | calculation",
        "1303930",
        "算数が得意だ。","さんすうがとくいだ。",
        "Giỏi môn toán.","Be good at arithmetic."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
