# -*- coding: utf-8 -*-
"""Build N2 ready wave 015 — arts, crafts, literature, religion, history/prosperity."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "japanese", "jmdict-n2-vi-ready-015.csv")
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"
def q(v): return '"' + str(v).replace('"','""') + '"'
def row(w,r,p,vi,en,s):
    return ",".join([q(w),q(r),q(""),q("N2"),q(p),q(vi),q(en),q(""),q("0"),q("jmdict"),q(s),q(LIC),q("JMdict/EDRDG"),q(""),q(""),q(""),q(""),q("ai_draft"),q("jmdict_ai")])
DATA = [
    ("工芸","こうげい","n","thủ công mỹ nghệ | nghề thủ công","industrial arts | craft","1278090"),
    ("彫像","ちょうぞう","n","tượng điêu khắc | pho tượng","statue | sculpture","1428090"),
    ("塑像","そぞう","n","tượng nặn | tượng đất sét","plaster image | clay figure","1396510"),
    ("水墨画","すいぼくが","n","tranh thủy mặc | tranh mực tàu","India-ink painting | ink wash painting","1372080"),
    ("版画","はんが","n","tranh khắc gỗ | tranh in mộc bản","woodcut | woodblock print | art print","1481510"),
    ("壁画","へきが","n","tranh tường | bích họa","fresco | mural | wall painting","1509310"),
    ("書道","しょどう","n","thư pháp","calligraphy","1344130"),
    ("華道","かどう","n","nghệ thuật cắm hoa | hoa đạo | ikebana","flower arrangement | floral art | ikebana","1590510"),
    ("陶芸","とうげい","n","nghệ thuật gốm | đồ gốm","ceramic art | ceramics","1450620"),
    ("陶磁器","とうじき","n","đồ gốm sứ | gốm và sứ","ceramics | pottery and porcelain","1450660"),
    ("漆器","しっき","n","đồ sơn mài","lacquer ware | lacquerwork","1320530"),
    ("織物","おりもの","n","vải dệt | hàng dệt","textile | fabric","1357450"),
    ("染色","せんしょく","n|vs|vt|vi","nhuộm màu | sự nhuộm | màu nhuộm","dyeing | staining | dyed colour","1391210"),
    ("刺繍","ししゅう","n|vs|vt","thêu | thêu thùa","embroidery","1306540"),
    ("民芸","みんげい","n","nghề thủ công dân gian | mỹ nghệ dân gian","folk craft | folk art","1528680"),
    ("骨董","こっとう","n","đồ cổ | đồ cổ ngoạn","antique | curio","1288700"),
    ("名作","めいさく","n","kiệt tác | tác phẩm nổi tiếng","masterpiece | masterwork","1531500"),
    ("傑作","けっさく","n|adj-na","kiệt tác | tuyệt tác | (vô tình) buồn cười | lố bịch","masterpiece | (unintentionally) hilarious","1253840"),
    ("駄作","ださく","n","tác phẩm dở | đồ bỏ đi | rác rưởi","poor piece of work | rubbish | trash","1409040"),
    ("作風","さくふう","n","phong cách (tác phẩm) | nét đặc trưng","style (of a work) | characteristics","1297930"),
    ("画風","がふう","n","phong cách hội họa | lối vẽ","style of painting","1197560"),
    ("編曲","へんきょく","n|vs|vt|vi","phối khí | soạn lại bản nhạc","arrangement","1511970"),
    ("合奏","がっそう","n|vs|vt","hòa tấu | hợp tấu | dàn nhạc cùng chơi","ensemble | concert","1285070"),
    ("独奏","どくそう","n|vs|vt","độc tấu | solo nhạc cụ","instrumental solo | recital","1455960"),
    ("伴奏","ばんそう","n|vs|vi","đệm nhạc | hòa âm đệm","accompaniment","1478400"),
    ("旋律","せんりつ","n|adj-no","giai điệu | làn điệu","melody | tune","1391730"),
    ("和音","わおん","n","hợp âm | âm hài hòa","chord","1561990"),
    ("音色","ねいろ","n","âm sắc | màu âm | chất âm","tone color | timbre","1576910"),
    ("楽譜","がくふ","n","bản nhạc | nhạc phổ","score | sheet music","1207490"),
    ("譜面","ふめん","n","bản nhạc | tờ nhạc","sheet music | score","1497900"),
    ("舞踊","ぶよう","n","múa | vũ điệu | khiêu vũ","dancing | dance","1499220"),
    ("戯曲","ぎきょく","n","kịch bản | vở kịch | tuồng","drama | play","1225010"),
    ("劇団","げきだん","n","đoàn kịch | đoàn nghệ thuật","troupe | theatrical company","1253450"),
    ("女優","じょゆう","n","nữ diễn viên | diễn viên nữ","actress | female actor","1345430"),
    ("演出","えんしゅつ","n|vs|vt","đạo diễn | dàn dựng | tổ chức (sự kiện)","direction (of a play) | production | staging","1176950"),
    ("封切り","ふうきり","n|vs|vt","công chiếu | ra mắt (phim)","premiere | first showing | release (film)","1499680"),
    ("詩集","ししゅう","n","tập thơ | thi tập","poetry anthology | collected poems","1312190"),
    ("随筆","ずいひつ","n","tùy bút | tản văn | bút ký","essays | miscellaneous writings","1372790"),
    ("小説","しょうせつ","n","tiểu thuyết | truyện | tác phẩm hư cấu","novel | story | fiction","1348430"),
    ("物語","ものがたり","n","câu chuyện | truyện kể | giai thoại","story | tale | narrative | legend","1502480"),
    ("童話","どうわ","n","truyện thiếu nhi | truyện cổ tích","children's story | fairy tale","1454000"),
    ("寓話","ぐうわ","n|adj-no","truyện ngụ ngôn","fable | allegory","1246410"),
    ("叙事詩","じょじし","n","sử thi | trường ca anh hùng","epic (poem) | epic poetry","1344850"),
    ("俳句","はいく","n","thơ haiku | thơ 17 âm tiết","haiku","1471900"),
    ("短歌","たんか","n","thơ tanka | thơ 31 âm tiết","tanka","1418630"),
    ("和歌","わか","n","waka | thơ cổ Nhật Bản","waka | classic Japanese poem","1562000"),
    ("川柳","せんりゅう","n","thơ senryū | haiku trào phúng","senryū | comic haiku","1390110"),
    ("韻","いん","n","vần | vần điệu","rhyme | rime","1170930"),
    ("寺院","じいん","n","chùa | đền | nơi thờ tự | nhà thờ","Buddhist temple | religious building","1315250"),
    ("仏閣","ぶっかく","n","chùa chiền | đền chùa","Buddhist temple","1501860"),
    ("本堂","ほんどう","n","chính điện | gian thờ chính (chùa)","main hall (of a Buddhist temple)","1523070"),
    ("僧侶","そうりょ","n","tăng lữ | nhà sư | tu sĩ","priest | monk | bonze","1398240"),
    ("住職","じゅうしょく","n","trụ trì | sư trụ trì","chief priest (of a temple) | abbot","1334100"),
    ("礼拝","れいはい","n|vs|vt","lễ bái | thờ phụng | lễ (nhà thờ)","worship | church service","1557560"),
    ("祈祷","きとう","n|vs|vt|vi","cầu nguyện | cầu khấn | trừ tà","prayer | exorcism","1591350"),
    ("巡礼","じゅんれい","n|vs|vi","hành hương | người hành hương","pilgrimage | pilgrim","1342150"),
    ("輪廻","りんね","n|vs|vi","luân hồi | tái sinh | đầu thai","samsara | reincarnation","1555730"),
    ("霊魂","れいこん","n","linh hồn | hồn | vong linh","soul | spirit","1557790"),
    ("祝福","しゅくふく","n|vs|vt","chúc phúc | ban phước | chúc mừng","celebration | blessing","1337520"),
    ("祭礼","さいれい","n","lễ hội (tôn giáo) | tế lễ","(religious) festival","1295320"),
    ("典礼","てんれい","n|adj-no","nghi lễ | điển lễ | phụng vụ","ceremony | liturgy","1438180"),
    ("習俗","しゅうぞく","n","phong tục tập quán | tập tục","manners and customs | folkways","1660590"),
    ("踏襲","とうしゅう","n|vs|vt","kế thừa | noi theo | tiếp nối (tiền lệ)","following (a precedent) | continuing with","1619900"),
    ("維新","いしん","n","duy tân | cải cách | Minh Trị Duy Tân","reformation | renewal | Meiji Restoration","1158470"),
    ("復興","ふっこう","n|vs|vt|vi","phục hưng | tái thiết | khôi phục","revival | reconstruction | restoration","1500750"),
    ("再興","さいこう","n|vs|vt|vi","chấn hưng lại | phục hồi | khôi phục","revival | restoration | resuscitation","1292540"),
    ("衰退","すいたい","n|vs|vi","suy thoái | suy tàn | sa sút","decline | decay | waning","1372550"),
    ("没落","ぼつらく","n|vs|vi","sa sút | suy tàn | phá sản | sụp đổ","ruin | fall | downfall | bankruptcy","1522040"),
    ("繁栄","はんえい","n|vs|vi","phồn vinh | thịnh vượng | hưng thịnh","prosperity | thriving | flourishing","1481670"),
    ("盛衰","せいすい","n","thịnh suy | hưng thịnh và suy vong","rise and fall | ups and downs","1379800"),
    ("興亡","こうぼう","n","hưng vong | thịnh suy | nổi lên và sụp đổ","rise and fall | ups and downs","1238400"),
    ("栄華","えいが","n","vinh hoa | phú quý | huy hoàng | xa hoa","prosperity | glory | splendour | luxury","1173880"),
    ("全盛","ぜんせい","n|adj-no","thời hoàng kim | thời cực thịnh","height of prosperity","1395560"),
]
rows=[row(*d) for d in DATA]
open(OUT,"w",encoding="utf-8",newline="\n").write(HEADER+"\n"+"\n".join(rows)+"\n")
print(f"Written {len(rows)} rows")
