# -*- coding: utf-8 -*-
"""Writes jmdict-n4-vi-ready-001.csv in UTF-8."""

OUT = r"C:\Users\QuanLV17\Downloads\chococfko-web\web\data\japanese\jmdict-n4-vi-ready-001.csv"
HEADER = "word,reading,romaji,jlpt_level,pos,meaning_vi,meaning_en,tags,frequency,source,source_id,license,attribution,example_jp,example_reading,example_vi,example_en,review_status,meaning_source"
LIC = "CC BY-SA 3.0 — verify at edrdg.org before production use"

def q(v):
    return '"' + str(v).replace('"', '""') + '"'

def row(word, reading, lvl, pos, vi, en, src_id,
        ex_jp="", ex_rd="", ex_vi="", ex_en=""):
    return ",".join([
        q(word), q(reading), q(""), q(lvl), q(pos),
        q(vi), q(en), q(""), q("0"), q("jmdict"), q(src_id),
        q(LIC), q("JMdict/EDRDG"),
        q(ex_jp), q(ex_rd), q(ex_vi), q(ex_en),
        q("ai_draft"), q("jmdict_ai"),
    ])

ROWS = [
    row("お菓子","おかし","N4","n",
        "bánh kẹo | đồ ngọt | kẹo | bánh",
        "confections | sweets | candy | cake",
        "1001710",
        "お菓子を食べます。","おかしをたべます。","Tôi ăn bánh kẹo.","I eat sweets."),
    row("お客さん","おきゃくさん","N4","n",
        "khách | du khách | khách hàng | thân chủ | người mua sắm | khán giả | khán thính giả | khách du lịch | hành khách",
        "guest | visitor | customer | client | shopper | spectator | audience | tourist | sightseer | passenger",
        "1001760",
        "お客さんが来ます。","おきゃくさんがきます。","Khách đến.","A guest is coming."),
    row("以外","いがい","N4","n-suf",
        "ngoại trừ | ngoài ra | không tính | khác với | bên cạnh | ngoài phạm vi",
        "excluding | except (for) | apart from | other than | besides | in addition to | outside (a boundary, scope, etc.)",
        "1155090",
        "これ以外はありません。","これいがいはありません。","Không có gì ngoài cái này.","There is nothing other than this."),
    row("以内","いない","N4","n|n-suf|adv",
        "trong vòng | bên trong | ít hơn",
        "within | inside of | less than",
        "1155180",
        "三日以内に返します。","みっかいないにかえします。","Tôi sẽ trả lại trong vòng 3 ngày.","I will return it within three days."),
    row("影響","えいきょう","N4","n|vs|vi",
        "ảnh hưởng | tác động | tác dụng",
        "influence | effect | impact",
        "1173660",
        "悪影響があります。","わるえいきょうがあります。","Có ảnh hưởng xấu.","There is a bad influence."),
    row("砂","すな","N4","n",
        "cát | sỏi | cát mịn",
        "sand | grit | fine gravel",
        "1291500",
        "砂浜を歩きます。","すなはまをあるきます。","Tôi đi dạo trên bãi cát.","I walk on the sandy beach."),
    row("責任","せきにん","N4","n",
        "trách nhiệm | nghĩa vụ | trách nhiệm pháp lý | gánh nặng",
        "duty | responsibility (incl. supervision of staff) | liability | onus",
        "1383180",
        "責任を持ちます。","せきにんをもちます。","Tôi có trách nhiệm.","I take responsibility."),
    row("お弁当","おべんとう","N4","n",
        "cơm hộp | cơm hộp kiểu Nhật",
        "bento | Japanese box lunch",
        "1513065",
        "お弁当を作ります。","おべんとうをつくります。","Tôi làm cơm hộp.","I make a bento lunch."),
    row("隣人","りんじん","N4","n",
        "người hàng xóm | láng giềng | dân cư vùng lân cận",
        "neighbour | neighbor | (people in the) neighbourhood | neighborhood",
        "1555850",
        "隣人に挨拶します。","りんじんにあいさつします。","Tôi chào hàng xóm.","I greet my neighbor."),
    row("冷める","さめる","N4","v1|vi",
        "nguội | nguội lạnh | hạ nhiệt (hứng khởi, tức giận) | lắng xuống | giảm bớt | phai dần | tắt | lạnh (mắt, vẻ mặt) | bình tĩnh",
        "to cool down | to get cold | to cool off (excitement, temper, etc.) | to subside | to dampen | to fade | to wane | to be cold (eyes, expression, etc.) | to be composed",
        "1556750",
        "料理が冷めました。","りょうりがさめました。","Món ăn nguội rồi.","The food has cooled down."),
    row("増やす","ふやす","N4","v5s|vt",
        "tăng | thêm vào | tăng thêm",
        "to increase | to add to | to augment",
        "1602880",
        "収入を増やします。","しゅうにゅうをふやします。","Tôi tăng thu nhập.","I increase my income."),
    row("インターネット","インターネット","N4","n",
        "Internet | mạng internet",
        "Internet",
        "1022880",
        "インターネットを使います。","インターネットをつかいます。","Tôi dùng Internet.","I use the Internet."),
    row("アルバム","アルバム","N4","n",
        "album | tập ảnh",
        "album",
        "1019450",
        "アルバムを見ます。","アルバムをみます。","Tôi xem album ảnh.","I look at an album."),
    row("エネルギー","エネルギー","N4","n",
        "năng lượng | sức mạnh | sức lực | nghị lực | nguồn năng lượng | năng lượng thực phẩm | calo",
        "energy | energy | strength | power | stamina | get-up-and-go | energy source | energy resource | food energy | calories",
        "1029430",
        "エネルギーが必要です。","エネルギーがひつようです。","Cần có năng lượng.","Energy is necessary."),
    row("コミュニケーション","コミュニケーション","N4","n",
        "giao tiếp | truyền thông",
        "communication",
        "1050980",
        "コミュニケーションが大切です。","コミュニケーションがたいせつです。","Giao tiếp rất quan trọng.","Communication is important."),
    row("スケジュール","スケジュール","N4","n",
        "lịch trình | chương trình | lịch",
        "schedule | program | calendar",
        "1068870",
        "スケジュールを確認します。","スケジュールをかくにんします。","Tôi kiểm tra lịch trình.","I check the schedule."),
    row("スタート","スタート","N4","n|vs|vt|vi",
        "bắt đầu | khởi đầu | xuất phát | khởi hành | điểm xuất phát | vạch xuất phát",
        "start | beginning | starting (e.g. a race) | departing | starting point | starting line",
        "1069370",
        "スタートします！","スタートします！","Bắt đầu!","Let's start!"),
    row("テーマ","テーマ","N4","n",
        "chủ đề | đề tài | nội dung chính | mô-típ | dự án | khẩu hiệu",
        "theme | topic | subject matter | motif | project | slogan",
        "1078830",
        "テーマを決めます。","テーマをきめます。","Tôi quyết định chủ đề.","I decide on the theme."),
    row("パソコン","パソコン","N4","n",
        "máy tính cá nhân | PC",
        "personal computer | PC",
        "1101570",
        "パソコンで作業します。","パソコンでさぎょうします。","Tôi làm việc bằng máy tính.","I work on a PC."),
    row("ファッション","ファッション","N4","n",
        "thời trang | mốt",
        "fashion",
        "1108210",
        "ファッションに興味があります。","ファッションにきょうみがあります。","Tôi quan tâm đến thời trang.","I am interested in fashion."),
    row("ボランティア","ボランティア","N4","n",
        "tình nguyện viên | tình nguyện",
        "volunteer",
        "1124300",
        "ボランティアをします。","ボランティアをします。","Tôi làm tình nguyện.","I do volunteer work."),
    row("レポート","レポート","N4","n|vs|vt",
        "báo cáo | bài báo | phóng sự",
        "report | paper | reportage",
        "1145990",
        "レポートを書きます。","レポートをかきます。","Tôi viết báo cáo.","I write a report."),
    row("一生懸命","いっしょうけんめい","N4","adv|adj-na|n",
        "hết lòng | hết sức | toàn lực | cố hết sức | dốc toàn bộ tâm sức | nỗ lực tột bậc | khẩn cấp",
        "very hard | with utmost effort | as hard as one can | with all one's might | for dear life | eagerly | desperately",
        "1164010",
        "一生懸命勉強します。","いっしょうけんめいべんきょうします。","Tôi học hết sức mình.","I study with all my might."),
    row("関係","かんけい","N4","n|vs|vi|n-suf",
        "mối quan hệ | liên quan | kết nối | sự tham gia | liên đới | mối bận tâm | ảnh hưởng | tác động | quan hệ tình dục | có liên quan | kết nối với",
        "relation | relationship | connection | participation | involvement | concern | influence | effect | sexual relations | sexual relationship | related to | connected to",
        "1215810",
        "関係がありますか。","かんけいがありますか。","Có liên quan không?","Is there a connection?"),
    row("渇く","かわく","N4","v5k|vi",
        "khát | cảm thấy khát | thèm khát | thèm muốn",
        "to be thirsty | to feel thirsty | to thirst for | to crave",
        "1208520",
        "のどが渇きました。","のどがかわきました。","Tôi khát nước.","I am thirsty."),
    row("乾く","かわく","N4","v5k|vi",
        "khô | khô đi",
        "to get dry",
        "1209650",
        "洗濯物が乾きました。","せんたくものがかわきました。","Quần áo đã khô.","The laundry has dried."),
    row("感動","かんどう","N4","n|vs|vi",
        "xúc động sâu sắc | hứng khởi | đam mê | cảm hứng | cảm xúc sâu sắc | ấn tượng mạnh",
        "being deeply moved emotionally | excitement | passion | inspiration | deep emotion | strong impression",
        "1212570",
        "感動しました！","かんどうしました！","Tôi thật sự xúc động!","I was deeply moved!"),
    row("給料","きゅうりょう","N4","n",
        "lương | tiền lương | thù lao",
        "salary | wages | pay",
        "1230360",
        "給料が上がりました。","きゅうりょうがあがりました。","Lương tôi tăng rồi.","My salary went up."),
    row("玄関","げんかん","N4","n",
        "lối vào | cửa chính | hành lang vào | sảnh vào | cửa ra vào",
        "entrance | front door | entryway | entranceway | entry hall | vestibule | porch | foyer | mud room",
        "1263400",
        "玄関で靴を脱ぎます。","げんかんでくつをぬぎます。","Tôi cởi giày ở lối vào.","I take off my shoes at the entrance."),
    row("結果","けっか","N4","n|adv|vs|vi",
        "kết quả | hậu quả | tác động | là kết quả của ... | sau ... | đơm hoa kết trái",
        "result | consequence | outcome | effect | as a result of ... | as a consequence of ... | after ... | following ... | bearing fruit | fruiting",
        "1254690",
        "結果が出ました。","けっかがでました。","Kết quả đã có.","The result is out."),
    row("研究","けんきゅう","N4","n|vs|vt",
        "nghiên cứu | học tập | điều tra",
        "research | study | investigation",
        "1258520",
        "研究を続けます。","けんきゅうをつづけます。","Tôi tiếp tục nghiên cứu.","I continue my research."),
    row("厳しい","きびしい","N4","adj-i",
        "nghiêm khắc | nghiêm ngặt | cứng nhắc | không khoan nhượng | không ngừng nghỉ | khó (thực hiện) | khó khăn | rắc rối | dữ dội (ví dụ lạnh) | khắc nghiệt (thời tiết)",
        "severe | strict | rigid | unsparing | relentless | hard (to do) | difficult | tricky | intense (e.g. cold) | harsh (weather) | inclement",
        "1262530",
        "先生が厳しいです。","せんせいがきびしいです。","Thầy giáo rất nghiêm khắc.","The teacher is strict."),
    row("減らす","へらす","N4","v5s|vt",
        "giảm | giảm bớt | giảm thiểu | rút ngắn",
        "to abate | to decrease | to diminish | to shorten",
        "1263110",
        "体重を減らします。","たいじゅうをへらします。","Tôi giảm cân.","I reduce my weight."),
    row("減る","へる","N4","v5r|vi",
        "giảm (kích thước hoặc số lượng) | giảm dần | bớt đi",
        "to decrease (in size or number) | to diminish | to abate",
        "1263120",
        "お金が減りました。","おかねがへりました。","Tiền bị hao hụt.","The money has decreased."),
    row("後悔","こうかい","N4","n|vs|vt|vi|adj-no",
        "hối hận | sự ăn năn | hối tiếc",
        "regret | repentance | remorse",
        "1269510",
        "後悔しています。","こうかいしています。","Tôi đang hối hận.","I am regretting it."),
    row("後輩","こうはい","N4","n",
        "đàn em | người em | học sinh trẻ tuổi hơn | người trẻ tuổi hơn",
        "junior (at work, school, etc.) | younger people | younger student",
        "1270010",
        "後輩を指導します。","こうはいをしどうします。","Tôi hướng dẫn đàn em.","I guide my juniors."),
    row("光る","ひかる","N4","v5r|vi",
        "tỏa sáng | lấp lánh | sáng rực",
        "to shine | to glitter | to be bright",
        "1272820",
        "星が光っています。","ほしがひかっています。","Những ngôi sao đang tỏa sáng.","The stars are shining."),
    row("向く","むく","N4","v5k|vt|vi",
        "quay về | nhìn (lên, xuống) | hướng về phía (ví dụ đông) | nhìn ra | trỏ (của mũi tên, kim la bàn) | phù hợp với | thích hợp với | hướng tới | nghiêng về",
        "to turn toward | to look (up, down, etc.) | to face (e.g. east) (of a building, window, etc.) | to look out on | to front (on) | to point (of an arrow, compass needle, etc.) | to be suited to | to be fit for | to go towards | to turn to (of one's interests, feelings, etc.) | to be inclined (to do)",
        "1277080",
        "こちらを向いてください。","こちらをむいてください。","Hãy quay về phía này.","Please face this way."),
    row("合格","ごうかく","N4","n|vs|vi",
        "đậu (kỳ thi) | vượt qua | thành công | đạt điểm đủ tiêu chuẩn | đạt tiêu chuẩn | đủ điều kiện",
        "passing (an exam) | pass | success | passing grade | meeting (specifications, standards, etc.) | passing (inspection) | qualification | being found eligible",
        "1284600",
        "試験に合格しました！","しけんにごうかくしました！","Tôi đã đậu kỳ thi!","I passed the exam!"),
    row("混ぜる","まぜる","N4","v1|vt",
        "trộn | khuấy | pha trộn",
        "to mix | to stir | to blend",
        "1290310",
        "材料を混ぜます。","ざいりょうをまぜます。","Tôi trộn nguyên liệu.","I mix the ingredients."),
    row("差","さ","N4","n|n-suf",
        "sự khác biệt | chênh lệch",
        "difference | variation | difference",
        "1291070",
        "差があります。","さがあります。","Có sự khác biệt.","There is a difference."),
    row("済む","すむ","N4","v5m|vi",
        "kết thúc | hoàn thành | được giải quyết | nhẹ hơn dự kiến | cảm thấy thoải mái | xin lỗi (vì làm phiền ai đó)",
        "to finish | to end | to be completed | to be resolved | to have a result less severe than expected | to feel at ease | to feel unease or guilt for troubling someone | to be sorry",
        "1295070",
        "仕事が済みました。","しごとがすみました。","Công việc xong rồi.","The work is done."),
    row("病気","やまいけ","N4","n",
        "cảm thấy không khỏe | cảm giác ốm | dấu hiệu ốm",
        "feeling ill | sensation of illness | signs of illness",
        "2839802"),
    row("出口","でぐち","N4","n",
        "lối ra | đường ra | ống thoát | cửa thoát",
        "exit | way out | outlet | vent",
        "1338850",
        "出口はどこですか。","でぐちはどこですか。","Lối ra ở đâu?","Where is the exit?"),
    row("そろそろ","そろそろ","N4","adv|adv-to",
        "sắp | sắp tới | bất cứ lúc nào | từ từ | nhẹ nhàng | dần dần | cẩn thận | đã gần đến lúc",
        "soon | before long | any time now | momentarily | slowly | quietly | steadily | gradually | gingerly | already | about time",
        "1345605",
        "そろそろ出発します。","そろそろしゅっぱつします。","Sắp xuất phát rồi.","It's about time to depart."),
    row("勝つ","かつ","N4","v5t|vi",
        "thắng | giành chiến thắng",
        "to win | to gain victory",
        "1346150",
        "試合に勝ちました！","しあいにかちました！","Tôi thắng trận đấu!","I won the match!"),
    row("焼ける","やける","N4","v1|vi",
        "cháy | cháy rụi | bị rang | chín kỹ | bị rám nắng | phai màu (dưới nắng) | ửng đỏ (bầu trời lúc hoàng hôn) | nóng (do mặt trời) | ghen tuông",
        "to burn | to burn down | to go down in flames | to be roasted | to be thoroughly cooked | to be sunburnt | to fade (in the sun) | to glow red (i.e. of the sky at sunset) | to become hot (from the sun) | to be jealous | to be envious",
        "1350610",
        "パンが焼けました。","パンがやけました。","Bánh mì đã nướng xong.","The bread is baked."),
    row("蒸す","むす","N4","v5s|vt|vi",
        "hấp (thức ăn, khăn) | nóng ẩm | oi bức",
        "to steam (food, towel, etc.) | to be hot and humid | to be sultry",
        "1356900",
        "野菜を蒸します。","やさいをむします。","Tôi hấp rau.","I steam vegetables."),
    row("真剣","しんけん","N4","adj-na|n",
        "nghiêm túc | thật lòng | kiếm thật (khác với kiếm gỗ tập luyện)",
        "serious | earnest | real sword (as opposed to a wooden practice weapon)",
        "1363650",
        "真剣に考えます。","しんけんにかんがえます。","Tôi suy nghĩ nghiêm túc.","I think seriously."),
    row("親しい","したしい","N4","adj-i",
        "thân thiết | quen thuộc | thân thiện | thân mật | quen (câu chuyện) | gần gũi (họ hàng) | có họ hàng gần",
        "close (e.g. friend) | familiar | friendly | intimate | familiar (e.g. story) | well-known (to one) | close (relatives) | closely related",
        "1365050",
        "親しい友達です。","したしいともだちです。","Bạn thân của tôi.","A close friend."),
    row("人気","にんき","N4","n|adj-no",
        "sự nổi tiếng | được ưa thích | tình trạng (ví dụ thị trường) | tính cách | bản chất",
        "popularity | public favor | condition (e.g. market) | tone | character | nature",
        "1367010",
        "人気があります。","にんきがあります。","Rất nổi tiếng.","It's popular."),
    row("先輩","せんぱい","N4","n|suf",
        "đàn anh | đàn chị | cấp trên | người lớn tuổi hơn | người đi trước",
        "senior (at school, work, etc.) | superior | elder | older person | predecessor",
        "1388410",
        "先輩に相談します。","せんぱいにそうだんします。","Tôi tham khảo ý kiến đàn anh.","I consult my senior."),
    row("羨ましい","うらやましい","N4","adj-i",
        "ghen tị | ganh tị | đáng ghen tị (vị trí, hoàn cảnh)",
        "envious | jealous | enviable (position, etc.)",
        "1391940",
        "羨ましいなあ。","うらやましいなあ。","Ghen quá đi.","I'm so jealous."),
    row("選択","せんたく","N4","n|vs|vt",
        "lựa chọn | tuyển chọn | chọn lựa",
        "choice | selection | option",
        "1392290",
        "選択肢が多いです。","せんたくしがおおいです。","Có nhiều lựa chọn.","There are many options."),
    row("通う","かよう","N4","v5u|vi",
        "đi lại | qua lại giữa | chạy giữa (ví dụ xe buýt, tàu) | đi học | đi làm | tham dự | đi về hàng ngày | lui tới | lưu thông (ví dụ máu, điện) | được truyền đạt (ý nghĩ) | giống nhau",
        "to go to and from (a place) | to go back and forth between | to run between (e.g. bus, train, etc.) | to ply between | to go to (school, work, etc.) | to attend | to commute | to frequent | to circulate (e.g. blood, electricity) | to be communicated (e.g. thought) | to resemble",
        "1432850",
        "毎日学校に通います。","まいにちがっこうにかよいます。","Tôi đi học hàng ngày.","I commute to school every day."),
    row("天気予報","てんきよほう","N4","n",
        "dự báo thời tiết | bản tin thời tiết",
        "weather forecast | weather report",
        "1438770",
        "天気予報を見ます。","てんきよほうをみます。","Tôi xem dự báo thời tiết.","I watch the weather forecast."),
    row("道路","どうろ","N4","n",
        "đường | đường quốc lộ",
        "road | highway",
        "1454290",
        "道路が混んでいます。","どうろがこんでいます。","Đường đang tắc.","The road is congested."),
    row("特徴","とくちょう","N4","n",
        "đặc điểm | nét đặc trưng | đặc tính | điểm nổi bật | điểm phân biệt",
        "feature | trait | characteristic | peculiarity | distinction",
        "1455170",
        "この製品の特徴は何ですか。","このせいひんのとくちょうはなんですか。","Đặc điểm của sản phẩm này là gì?","What are the features of this product?"),
    row("虹","にじ","N4","n",
        "cầu vồng",
        "rainbow",
        "1463740",
        "虹が出ました。","にじがでました。","Cầu vồng xuất hiện rồi.","A rainbow appeared."),
    row("麦","むぎ","N4","n",
        "lúa mì | lúa mạch | yến mạch",
        "wheat | barley | oat (oats)",
        "1476080",
        "麦茶を飲みます。","むぎちゃをのみます。","Tôi uống trà mạch.","I drink barley tea."),
    row("枕","まくら","N4","n|n-suf",
        "gối | gối dài | mở đầu (câu chuyện rakugo)",
        "pillow | bolster | introduction (e.g. to a rakugo story) | lead-in",
        "1524860",
        "枕が柔らかいです。","まくらがやわらかいです。","Cái gối mềm quá.","The pillow is soft."),
    row("掃除機","そうじき","N4","n",
        "máy hút bụi | đồ hút bụi",
        "vacuum cleaner | vacuum | hoover | cleaning device",
        "1596390",
        "掃除機をかけます。","そうじきをかけます。","Tôi dùng máy hút bụi.","I vacuum the floor."),
    row("自然","じねん","N4","n|adv",
        "xảy ra tự nhiên (không có tác động của con người)",
        "occurring naturally (without human influence)",
        "2837784"),
    row("炊く","たく","N4","v5k|vt|vi",
        "nấu (ngũ cốc, ví dụ cơm) | đun sôi | hầm nhỏ lửa | hầm | sục sôi | nổi giận | nổi cáu",
        "to cook (grains, e.g. rice) | to boil | to simmer | to stew | to seethe | to get angry | to snap",
        "1596830",
        "ご飯を炊きます。","ごはんをたきます。","Tôi nấu cơm.","I cook rice."),
    row("残す","のこす","N4","v5s|vt",
        "để lại | để lại (chưa xong) | không hoàn thành | lưu giữ | để dành | dự trữ | để lại (cho ai đó sau khi chết) | di chúc | ở lại (trong đài) | bám trụ",
        "to leave (behind) | to leave (undone) | to not finish | to save | to set aside | to reserve | to leave (to someone, esp. after one's death) | to bequeath | to stay (in the ring) | to hold on",
        "1600260",
        "少し残します。","すこしのこします。","Tôi để lại một chút.","I leave a little behind."),
    row("乗り換える","のりかえる","N4","v1|vt",
        "chuyển tàu | chuyển xe | chuyển sang (ý thức hệ, đảng, công ty) | chuyển đổi (hệ thống, phương pháp) | chuyển sang (ví dụ mối tình mới)",
        "to transfer (trains) | to change (bus, train) | to change (to another ideology, party, company, etc.) | to switch (to a different system, method, etc.) | to move on to (e.g. a new love interest)",
        "1600470",
        "次の駅で乗り換えます。","つぎのえきでのりかえます。","Tôi chuyển tàu ở ga tiếp theo.","I transfer at the next station."),
    row("引き出し","ひきだし","N4","n",
        "ngăn kéo | rút tiền (từ tài khoản) | vốn kiến thức và kinh nghiệm để xử lý tình huống",
        "drawer | withdrawal (of money from an account) | variety of knowledge and experience useful for handling things impromptu",
        "1601650",
        "引き出しを開けます。","ひきだしをあけます。","Tôi mở ngăn kéo.","I open the drawer."),
    row("沸く","わく","N4","v5k|vi",
        "nóng lên (ví dụ nước) | sôi | hứng khởi | bùng lên (tiếng vỗ tay, reo hò) | lên men | diễn ra sôi nổi | lên men | nóng chảy (kim loại)",
        "to grow hot (e.g. water) | to boil | to get excited (at) | to erupt (in applause, cheering, etc.) | to be in a ferment | to take place energetically | to ferment | to melt (of metal)",
        "1606680",
        "お湯が沸きました。","おゆがわきました。","Nước sôi rồi.","The water has boiled."),
    row("過ぎる","よぎる","N4","v5r|vi",
        "đi qua | băng qua | lướt qua | chớp qua",
        "to go by | to cross | to pass by | to flash across",
        "2106790",
        "頭によぎりました。","あたまによぎりました。","Nó thoáng qua trong đầu tôi.","It flashed through my mind."),
    row("伝言","つてこと","N4","n",
        "lời nhắn | tin nhắn lời nói | lời đồn",
        "(verbal) message | word (from someone) | rumour | rumor",
        "2545840",
        "伝言をお願いします。","つてことをおねがいします。","Nhờ nhắn giúp.","Please pass on a message."),
    row("お年寄り","おとしより","N4","n|adj-no",
        "người già | người cao tuổi | người lớn tuổi",
        "old person | elderly person | senior citizen",
        "2859199",
        "お年寄りに席を譲ります。","おとしよりにせきをゆずります。","Tôi nhường ghế cho người già.","I give up my seat for elderly people."),
]

content = HEADER + "\n" + "\n".join(ROWS) + "\n"
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print(f"Written {len(ROWS)} rows to {OUT}")
